module.exports = [
  "You're crashing into me like waves on the coast",
  "Every time we talk, you move in close",
  "I don't want you stop, I don't want you to stop tonight",
  "We've got the last two glasses on a straw hook bar",
  "Trying to remember what number we are",
  "String of white lights making your eyes shine tonight",
  "",
  "We're buzzing like that no vacancy sign out front",
  "Your skin is begging to be kissed by a little more than the sun",
  "You take my hand in yours, you lean in",
  "And your lips taste like sangria, your lips taste like sangria",
  "",
  "Wrecking ball dancing down the hallway",
  "You're holding your shoes, wearing my shades",
  "We fall against the door, we fall into a wild warm kiss",
  "",
  "We're buzzing like that no vacancy sign out front",
  "Your skin is begging to be kissed by a little more than the sun",
  "You take my hand in yours, you lean in",
  "And your lips taste like sangria, your lips taste like sangria",
  "",
  "Only thing I want to do tonight is drink you like a Spanish wine",
  "Let you let this head of mine keep spinning, spinning around",
  "",
  "We're buzzing like that no vacancy sign out front",
  "Your skin is begging to be kissed by a little more than the sun",
  "You take my hand in yours, you lean in",
  "And your lips taste like sangria, your lips taste like sangria",
  "Your lips taste like sangria, your lips taste like sangria",
  "",
  "Only thing I want to do tonight is drink you like a Spanish wine",
  "Let you let this head of mine keep spinning, spinning around",
  ""
]