module.exports = [
  "I, I been gone I been gone too long singing my songs on the road.",
  "Another town one more show and I'm coming home.",
  "Don't give a damn what these keys I hold I'm gonna knock down that front door, and",
  "",
  "I'ma find out what that house is made of.",
  "It's been too many nights since its felt us make love.",
  "I wanna rock some Sheetrock, knock some pictures off the wall.",
  "Love you baby, like a wrecking ball.",
  "",
  "You... look at you send me one more shot sitting on a bathroom sink.",
  "Damn you really turn me on painting your toenails pink.",
  "Easy baby before you say but if I can make it just one more day, and",
  "",
  "That old house is gonna be shaking.",
  "I hope those bricks and boards can take it.",
  "But I won't be surprised if the whole damn place just falls.",
  "I'm gonna rock you baby, like a wrecking ball.",
  "",
  "And that old house is gonna be shaking.",
  "Rafter and rocking foundation quaking.",
  "Crash right through the front door, back you up against the wall.",
  "Love you baby take it right there baby rock you baby, like a wrecking ball.",
  ""
]