module.exports = [
  "Some legends are told, some turn to dust or to gold",
  "But you will remember me, remember me for centuries",
  "And just one mistake is all it will take",
  "We'll go down in history, remember me for centuries",
  "",
  "Hey, hey, hey",
  "Remember me for centuries!",
  "",
  "Mummified my teenage dreams",
  "No, it's nothing wrong with me",
  "The kids are all wrong, the story's all off",
  "Heavy metal broke my <i>heart</i>",
  "Come on, come on and let me in",
  "The bruises on your thighs like my fingerprints",
  "And this is supposed to match the darkness that you felt",
  "I never meant for you to fix yourself",
  "",
  "Some legends are told, some turn to dust or to gold",
  "But you will remember me, remember me for centuries",
  "And just one mistake is all it will take",
  "We'll go down in history, remember me for centuries",
  "",
  "Hey, hey, hey",
  "Remember me for centuries!",
  "",
  "And I can't stop 'til the whole word knows my name",
  "'Cause I was only born inside my dreams",
  "Until you die for me, as long as there's a light, my shadow's over you",
  "Cause I, I am the opposite of amnesia",
  "And you're a cherry blossom, you're about to bloom",
  "You look so pretty, but you're gone so soon",
  "",
  "Some legends are told, some turn to dust or to gold",
  "But you will remember me, remember me for centuries",
  "And just one mistake is all it will take",
  "We'll go down in history, remember me for centuries",
  "",
  "Hey, hey, hey",
  "Remember me for centuries!",
  "",
  "We've been here forever",
  "And here is the frozen proof",
  "I could scream forever",
  "We are the poisoned youth",
  "",
  "Some legends are told, some turn to dust or to gold",
  "But you will remember me, remember me for centuries",
  "And just one mistake is all it will take",
  "We'll go down in history, remember me for centuries",
  "",
  "Hey, hey, hey ",
  "We'll go down in history",
  "Remember me for centuries",
  ""
]