module.exports = [
  "Taking down your neighbor won't take you any higher",
  "I burned my own damn finger pokin' someone else's fire",
  "I've never gotten taller makin' someone else feel small",
  "If you ain't got nothin' nice to say don't say nothin' at all",
  "",
  "Just hoe your own row and raise your own babies",
  "Smoke your own smoke and grow your own daisies",
  "Mend your own fences and own your own crazy",
  "Mind your own biscuits and life will be gravy",
  "Mind your own biscuits and life will be gravy",
  "",
  "Nobody's perfect, we've all lost and we've all lied",
  "Most of us have cheated, the rest of us have tried",
  "The holiest of holies even slip from time to time",
  "We've all got dirty laundry hangin' on the line",
  "",
  "So hoe your own row and raise your own babies",
  "Smoke your own smoke and grow your own daisies",
  "Mend your own fences and own your own crazy",
  "Mind your own biscuits and life will be gravy",
  "Mind your own biscuits and life will be gravy",
  "",
  "Pourin' salt in my sugar won't make yours any sweeter",
  "Pissin' in my yard ain't gonna make yours any greener",
  "And I wouldn't know about the rocks in your shoes",
  "So I'll just do me and honey you can just do you",
  "",
  "So hoe your own row and raise your own babies",
  "Smoke your own smoke and grow your own daisies",
  "Mend your own fences and own your own crazy",
  "Mind your own biscuits and life will be gravy",
  "Mind your own biscuits and life will be gravy",
  ""
]