module.exports = [
  "Oh hey",
  "Boy with your hat back",
  "Mmm I kinda like that",
  "If you wanna walk my way",
  "I'mma shoot you straight up",
  "Show me what you are made of",
  "",
  "I don't have time to waste on the boys",
  "That are playing the games",
  "And leaving the girls crying out in the rain",
  "So tell me, baby",
  "Do you got what it takes?",
  "",
  "If you're gonna hold me hold me like I'm leaving",
  "If you're gonna kiss me kiss me like you need it",
  "Baby, if you're not you best get to leaving",
  "If you're gonna love me love me like you mean it",
  "",
  "If you're gonna talk the talk you better walk it",
  "If you wanna keep me keep me like you lost it",
  "If you're gonna say it and make me believe it",
  "If you're gonna love me boy love me like you mean it",
  "",
  "I've had my share of losers, liars and users",
  "Looking for a heart to break",
  "So if you're like that",
  "Well take a step back",
  "",
  "'Cause I don't have time to waste on the boys",
  "That are playing the game",
  "And leaving the girls crying out in the rain",
  "So tell me, baby",
  "Are you just crazy or crazy over me",
  "",
  "If you're gonna hold me hold me like I'm leaving",
  "If you're gonna kiss me kiss me like you need it",
  "Baby, if you're not you best get to leaving",
  "If you're gonna love me love me like you mean it",
  "",
  "If you're gonna talk the talk you better walk it",
  "If you're gonna keep me keep me like you lost it",
  "If you're gonna say it and make me believe it",
  "If you're gonna love me love me like you mean it",
  "",
  "If you're gonna hold me hold me like I'm leaving",
  "If you're gonna kiss me kiss me like you need it",
  "Baby, if you're not you best get to leaving",
  "If you're gonna love me love me love me",
  "",
  "If you're gonna talk the talk you better walk it",
  "If you're gonna keep me keep me like you lost it",
  "If you're say it and make me believe it",
  "If you're gonna love me love me like you mean it",
  "",
  "Love me like you mean it",
  "Love me like you mean it",
  ""
]