module.exports = [
  "I stay out too late",
  "Got nothin' in my brain",
  "That's what people say, mmh-hmm",
  "That's what people say, mmh-hmm",
  "",
  "I go on too many dates <i>(heh-heh)</i>",
  "But I can't make 'em stay",
  "At least that's what people say, mmh-hmm",
  "That's what people say, mmh-hmm",
  "",
  "But I keep cruisin'",
  "Can't stop, won't stop movin'",
  "It's like I got this music",
  "In my mind sayin', \"it's gonna be all right\"",
  "",
  "'Cause the players gonna play, play, play, play, play",
  "And the haters gonna hate, hate, hate, hate, hate",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "Heartbreakers gonna break, break, break, break, break",
  "And the fakers gonna fake, fake, fake, fake, fake",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "I never miss a beat, ah",
  "I'm lightnin' on my feet",
  "And that's what they don't see, mmh-hmm",
  "That's what they don't see, mmh-hmm",
  "",
  "I'm dancin' on my own <i>(dancin' on my own)</i>",
  "I'll make the moves up as I go <i>(moves up as I go)</i>",
  "And that's what they don't know, mmh-hmm",
  "That's what they don't know, mmh-hmm",
  "",
  "But I keep cruisin'",
  "Can't stop, won't stop groovin'",
  "It's like I got this music",
  "In my mind sayin', \"it's gonna be all right\"",
  "",
  "'Cause the players gonna play, play, play, play, play",
  "And the haters gonna hate, hate, hate, hate, hate",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "Heartbreakers gonna break, break, break, break, break",
  "And the fakers gonna fake, fake, fake, fake, fake",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "Hey, hey, hey",
  "Just think while you've been getting down and out about the liars and the dirty, dirty cheats of the world",
  "You could've been getting down to this sick beat",
  "",
  "My ex-man brought his new girlfriend",
  "She's like, \"Oh my God\"",
  "But I'm just gonna shake",
  "And to the fella over there",
  "With the hella good hair",
  "Won't you come on over, baby",
  "We can shake, shake, shake",
  "Yeah, oh",
  "",
  "'Cause the players gonna play, play, play, play, play",
  "And the haters gonna hate, hate, hate, hate, hate <i>(haters gonna hate)</i>",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "Heartbreakers gonna break, break, break, break, break <i>(mmm)</i>",
  "And the fakers gonna fake, fake, fake, fake, fake <i>(they fake, they fake, they fake)</i>",
  "Baby, I'm just gonna shake, shake, shake, shake, shake",
  "I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off <i>(whoo)</i>",
  "",
  "I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off <i>(you got to)</i>",
  "I, I, I shake it off, I shake it off",
  "I, I, I shake it off, I shake it off <i>(whoo)</i>",
  ""
]