module.exports = [
  "We say \"goodbye, see you around\"",
  "We turn our backs then turn back around",
  "We break up, we make up, and we make love",
  "We can't seem to let go, girl",
  "",
  "So I'm comin' over, runnin' every red light",
  "To hell with the closure - save it for another time",
  "Try not to think about you, but it ain't workin'",
  "Why put out a fire when it's still burnin'",
  "Just when I think movin' on is getting closer",
  "I'm comin' over",
  "",
  "I'm all alone, but you're on my phone",
  "Tellin' me you miss me and that you're at home",
  "Who knows what we are in the morning",
  "All I know is I want you",
  "",
  "So I'm comin' over, runnin' every red light",
  "To hell with the closure - save it for another time",
  "Try not to think about you, but it ain't workin'",
  "Why put out a fire when it's still burnin'",
  "Just when I think movin' on is getting closer",
  "I'm comin' over",
  "",
  "Ooooh, I'm comin' over",
  "",
  "Yeah, we said that we're done and I know that it's late",
  "But you already know I'm on my way",
  "",
  "I'm comin' over, runnin' every red light",
  "To hell with the closure - save it for another time",
  "Try not to think about you, but it ain't workin'",
  "Why put out a fire that's burnin'",
  "",
  "I'm comin' over, runnin' every red light",
  "To hell with the closure - save it for another time",
  "Try not to think about you, but it ain't workin'",
  "Why put out a fire when it's still burnin'",
  "Just when I think movin' on is getting closer",
  "I'm comin' over",
  "",
  "Ooooh, I'm comin' over",
  ""
]