module.exports = [
  "<b>Louis:</b>",
  "I might never be your knight in shining armour",
  "I might never be the one you take home to mother",
  "And I might never be the one who brings you flowers",
  "But I can be the one, be the one tonight",
  "",
  "<b>Liam:</b>",
  "When I first saw you from across the room",
  "I could tell that you were curious, oh yeah",
  "Girl, I hope you're sure what you're looking for",
  "'Cause I'm not good at making promises",
  "",
  "<b>Harry:</b>",
  "But if you like causing trouble up in hotel rooms",
  "And if you like having secret little rendezvous ",
  "If you like to do the things you know that we shouldn't do",
  "Then baby I'm perfect, baby I'm perfect for you",
  "",
  "<b>Harry (with others backing):</b>",
  "And if you like midnight driving with the windows down",
  "And if you like going places we can't even pronounce ",
  "If you like to do whatever you've been dreaming about",
  "Baby you're perfect, baby you're perfect",
  "<b>Harry:</b>",
  "So let's start right now",
  "",
  "<b>Niall:</b>",
  "I might never be the hand you put your heart in",
  "Or the arms that hold you anytime you want them",
  "But that don't mean that we can't live here in the moment",
  "'Cause I can be the one you love from time to time",
  "",
  "<b>Liam:</b>",
  "When I first saw you from across the room",
  "I could tell that you were curious, oh yeah",
  "Girl, I hope you're sure what you're looking for",
  "'Cause I'm not good at making promises",
  "",
  "<b>Harry:</b>",
  "But if you like causing trouble up in hotel rooms",
  "And if you like having secret little rendezvous ",
  "If you like to do the things you know that we shouldn't do",
  "Then baby I'm perfect, baby I'm perfect for you",
  "",
  "<b>Harry (With others backing):</b>",
  "And if you like midnight driving with the windows down",
  "And if you like going places we can't even pronounce ",
  "If you like to do whatever you've been dreaming about",
  "Baby you're perfect, baby you're perfect",
  "<b>Harry:</b>",
  "So let's start right now",
  "",
  "<b>Harry:</b>",
  "And if you like camera's flashing every time we go out, oh yeah",
  "And if you're looking for someone to write your break up songs about",
  "Baby I'm perfect, baby we're perfect",
  "",
  "But if you like causing trouble up in hotel rooms",
  "And if you like having secret little rendezvous ",
  "If you like the do the things you know that we shouldn't do",
  "Then baby I'm perfect, baby I'm perfect for you",
  "",
  "<b>Harry (with others backing)</b>",
  "And if you like midnight driving with the windows down",
  "And if you like going places we can't even pronounce ",
  "If you like to do whatever you've been dreaming about",
  "Baby you're perfect, baby you're perfect",
  "<b>Harry:</b>",
  "So let's start right now",
  ""
]