module.exports = [
  "Where your ass was at dog, when niggas wasn’t feed me?",
  "Where your ass was at dog, when bitches didn’t need me?",
  "Where your ass was at dog, when niggas tried to run off?",
  "Where your ass was at dog? You made me pull this gun out",
  "Where your ass was at, dog, you went and switched sides?",
  "Where your ass was at, dog, when niggas spread lies on you?",
  "Where your ass was at, dog, when the bodies come slide?",
  "Where your ass was at, dog, when I was serving piles?",
  "Where your ass was at, dog, when niggas wasn’t feeding?",
  "Where your ass was at, dog, when bitches didn’t eat?",
  "Where your ass was at, dog, when niggas tried to run off?",
  "Where your ass was at, dog? You made me pull this gun out",
  "Where your ass was at, dog, when I was in the Pyrex?",
  "Where your ass was at, dog, when I was drinking Hi-Tech?",
  "Where your ass was at, dog, came through the projects?",
  "Where your ass at we keep that fully loaded contracts",
  "Had to rent that on the dick ass jocking",
  "Running through the pussy like a nigga going jogging",
  "Fuck a little Louis, put it in a bitch pocket",
  "Put a pic with me on the gram now you popping",
  "Where your ass was at when I was trapping in the stove?",
  "Had to struggle to get where I'm at and sell dope",
  "Jackie Chan moves got game in the choke",
  "Gas rolling up in the blunt, Amoco",
  "12 jumpers came in the spot to open up the dope",
  "Carlo, Bob, Joe gotta young nigga coughing",
  "Janet out the stove and we still raised honest",
  "Blowing on the O ho we call it full onion",
  "",
  "Man, where your ass was at when we took the city over?",
  "Where your ass was at when all they ask us, \"Whats the hold up?\"",
  "Where your ass was at when niggas first got the news?",
  "Now your ass around because we’re paying back dues",
  "Where were you? When all the dogs needed help",
  "Lawyers and the commissary ain’t gon’ pay itself",
  "Where your ass was at when we recorded in the bathroom?",
  "Where your ass was at I take attendance like a classroom",
  "Man I ain’t got no choice ‘cause nowadays I swear this shit done changed up for the boy",
  "I’m selfmade, selfish with my women, self employed",
  "I’ll buy the neighbors house if they complain about the noise",
  "Man, where your ass was at, dog, when niggas wouldn’t feed me?",
  "Where your ass was at, dog, when bitches didn’t need me?",
  "Where your ass was at, last winter was the coldest?",
  "Fuck was you at? I had the 6 on my shoulders",
  "",
  "Where your ass was at dog, when niggas wasn’t feed me?",
  "Where your ass was at dog, when bitches didn’t need me?",
  "Where your ass was at dog, when niggas tried to run off?",
  "Where your ass was at dog? You made me pull this gun out",
  "60 for a walk thru bitch don’t panic",
  "Had them bitches fall through fucking like a savage",
  "Heard you tryna swim in the ocean no jacket",
  "Heard that nigga came through squeezing on a ratchet",
  "Heard that nigga came through squeezing on a ratchet",
  "Heard a lot of dogs who will call you a mutt",
  "Where your ass was at dog, when I was in my cup?",
  "The reason I’m here today is cause I never gave up",
  "Where your ass was at, dog, when niggas wasn’t feed me?",
  "Where your ass was at, dog, when bitches didn’t need me?",
  "Where your ass was at, dog, when niggas tried to run off?",
  "Where your ass was at, dog? You made me pull this gun out",
  "Where you ass was at, when I was trapping at the stove?",
  "Had to scrub to get where I was at and sell dope",
  "Janet out the stove and we still raised honest",
  "Blowing on the O ho we call it full onion",
  ""
]