module.exports = [
  "This hit that ice cold",
  "Michelle Pfeiffer, that white gold",
  "This one for them hood girls",
  "Them good girls, straight masterpieces",
  "",
  "Stylin', wilin' ",
  "Livin' it up in the city",
  "Got Chucks on with Saint Laurent",
  "Gotta kiss myself I'm so pretty",
  "",
  "I'm too hot <i>(hot damn)</i>",
  "Call the police and the fireman",
  "I'm too hot <i>(hot damn)</i>",
  "Make a dragon wanna retire, man",
  "I'm too hot <i>(hot damn)</i>",
  "Say my name you know who I am",
  "I'm too hot <i>(hot damn)</i>",
  "And my band 'bout that  money",
  "Break it down",
  "",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "'Cause uptown funk gon' give it to you",
  "'Cause uptown funk gon' give it to you",
  "'Cause uptown funk gon' give it to you",
  "Saturday night and we in the spot",
  "Don't believe me just watch, come on",
  "",
  "<i>(Ha)</i> Don't believe me just watch",
  "<i>(Ha)</i> Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Hey, hey, hey, oh",
  "",
  "Stop, wait a minute",
  "Fill my cup put some liquor in it",
  "Take a sip, sign the check",
  "Julio, get the stretch",
  "",
  "Ride to Harlem, Hollywood",
  "Jackson, Mississippi",
  "If we show up, we gon' show out",
  "Smoother than a fresh jar of Skippy",
  "",
  "I'm too hot <i>(hot damn)</i>",
  "Call the police and the fireman",
  "I'm too hot <i>(hot damn)</i>",
  "Make a dragon wanna retire, man",
  "I'm too hot <i>(hot damn)</i>",
  "Bitch, say my name you know who I am",
  "I'm too hot <i>(hot damn)</i>",
  "And my band 'bout that money",
  "Break it down",
  "",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "Girls hit your hallelujah <i>(ooh)</i>",
  "'Cause uptown funk gon' give it to you",
  "'Cause uptown funk gon' give it to you",
  "'Cause uptown funk gon' give it to you",
  "Saturday night and we in the spot",
  "Don't believe me just watch, come on",
  "",
  "<i>(Ha)</i> Don't believe me just watch",
  "<i>(Ha)</i> Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Hey, hey, hey, oh",
  "",
  "Before we leave",
  "Let me tell y'all a little something",
  "",
  "Uptown funk you up",
  "Uptown funk you up",
  "Uptown funk you up",
  "Uptown funk you up",
  "I said, uptown funk you up",
  "Uptown funk you up",
  "Uptown funk you up",
  "Uptown funk you up",
  "",
  "Come on, dance, jump on it",
  "If you sexy then flaunt it",
  "If you freaky then own it",
  "Don't brag about it, come show me",
  "",
  "Come on, dance, jump on it",
  "If you sexy then flaunt it",
  "Well, it's Saturday night and we in the spot",
  "Don't believe me, just watch, come on",
  "",
  "<i>(Ha)</i> Don't believe me just watch",
  "<i>(Ha)</i> Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Don't believe me just watch",
  "Hey, hey, hey, oh",
  "",
  "Uptown funk you up, <i>(wooh c'mon)</i>",
  "Uptown funk you up, <i>(say what?)</i>",
  "Uptown funk you up",
  "Uptown funk you up, <i>(c'mon wooh)</i>",
  "Uptown funk you up, <i>(c'mon)</i>",
  "Uptown funk you up, <i>(say what?)</i>",
  "Uptown funk you up, <i>(hey)</i>",
  "Uptown funk you up, <i>(c'mon)</i>",
  "Uptown funk you up, <i>(wooh, c'mon)</i>",
  "Uptown funk you up, <i>(say what?)</i>",
  "Uptown funk you up",
  "Uptown funk you up",
  "Uptown funk you up, <i>(oh, oh)</i>",
  "Uptown funk you up, <i>(say what?)</i>",
  "Uptown funk you up",
  ""
]