module.exports = [
  "Hey girl, what's up?",
  "I know it's late, but I knew you'd pick it up",
  "Naw, I ain't drunk",
  "Okay, maybe I do have a little buzz but",
  "That song came on and I just thought what harm could come from one little call?",
  "I know you say you're taken, but I say girl you're taking too long",
  "",
  "To tell him that it's over",
  "Then bring it on over",
  "Stringing him along any longer girl, it's just wasting precious time",
  "Girl, you know it can't wait",
  "Rip it off just like a band-aid",
  "The way you look at me, girl, you can't pretend",
  "I know you ain't in love with him, break up with him",
  "",
  "I know, you don't wanna break his heart, but that ain't no good reason to be keeping us apart look,",
  "just tell him, it's you, it ain't him,",
  "and maybe you can lie to him and say you'll still be friends",
  "Whatever you got to say to get through to him that you ain't in love",
  "C'mon you can't deny that you and I kinda fit like a glove",
  "",
  "So tell him that it's over",
  "Then bring it on over",
  "Stringing him along any longer girl, it's just wasting precious time",
  "Girl, you know it can't wait",
  "Rip it off just like a band-aid",
  "It ain't my business to be all up in, but I know you ain't in love with him, break up with him",
  "I know that you're so done with him, break up with him, break up with him",
  "",
  "You would've hung up by now if you weren't thinking it too",
  "No pressure, whatever, just do what you gotta do, but if I was you",
  "I'd tell him that it's over",
  "Then bring it on over",
  "Stringing him along any longer girl, it's just wasting precious time",
  "Girl, you know it can't wait",
  "Just rip it off like a band-aid",
  "Yeah, I know I said it, but I'll say it again, I know you ain't in love with him, break up with him",
  "The way you look at me, girl, you can't pretend,",
  "I know you ain't in love with him, break up with him, yeah",
  "Just break up with him",
  ""
]