module.exports = [
  "I ain’t rich, but I damn sure wanna be",
  "Working like a dog all day, ain’t working for me",
  "I wish I had a rich uncle that’d kick the bucket",
  "And that I was sitting on a pile like Warren Buffett",
  "I know everybody says",
  "Money can’t buy happiness",
  "",
  "But it could buy me a boat, it could buy me a truck to pull it",
  "It could buy me a Yeti 110 iced down with some silver bullets",
  "Yeah, and I know what they say,",
  "Money can’t buy everything",
  "Well, maybe so,",
  "But it could buy me a boat",
  "",
  "They call me redneck, white trash and blue collar",
  "But I could change all that if I had a couple million dollars",
  "I keep hearing that money is the root of all evil",
  "And you can’t fit a camel through the eye of a needle",
  "I’m sure that’s probably true,",
  "But it still sounds pretty cool",
  "",
  "‘Cause it could buy me a boat, it could buy me a truck to pull it",
  "It could buy me a Yeti 110 iced down with some silver bullets",
  "Yeah, and I know what they say,",
  "Money can’t buy everything",
  "Well, maybe so,",
  "But it could buy me a boat",
  "",
  "To float down on the water with a beer…",
  "I hear the Powerball Lotto is a-sitting’ on a hundred mill…",
  "Well, that would buy me a brand new rod and reel…",
  "",
  "And it could buy me a boat, it could buy me a truck to pull it",
  "It could buy me a Yeti 110 iced down with some Silver Bullets",
  "Yeah, and I know what they say,",
  "Money can’t buy everything",
  "Well, maybe so,",
  "But it could buy me a boat",
  "",
  "Yeah, and I know what they say,",
  "Money can’t buy everything",
  "Well, maybe so,",
  "But it could buy me a boat",
  "It could buy me a boat.",
  ""
]