module.exports = [
  "Alabama on the boombox, baby",
  "'Bout to get a little boondock crazy",
  "",
  "Big stars breaking out through the indigo ",
  "Chevy wind comin' in and stereo",
  "Tail lights disappear in bout a mile or so ",
  "Down a county road",
  "Phone blowing up where you is",
  "Baby sayin' baby, let's do this",
  "Rocket in a bottle with a fuse lit",
  "'Bout to lift it off, I'm 'bout to twist it off ",
  "",
  "Lime on the rim of that dixie silver",
  "Smokin' up a faded out 4x4",
  "Girls headin' off to the river, yeah",
  "Victoria's Secret ain't a secret no more ",
  "I brought the songs and you brought the party",
  "Only one way to do it up right",
  "Everybody goes where everybody knows ",
  "That anything goes on a Friday night",
  "Get your party right, it's a Friday night ",
  "Get your party right, it's a Friday night",
  "",
  "Well baby you ain't nothin' but a masterpiece ",
  "Swayin' and sippin' that Dos Equis ",
  "Losin' yourself in the big loud beat, nothin' but heat",
  "Somebody's rockin' that bang box ",
  "Everybody hittin' that sweet spot",
  "Nobody mindin' that tick tock ",
  "Gettin' all locked in with all my friends ",
  "",
  "Lime on the rim of that dixie silver",
  "Smokin' up a faded out 4x4",
  "Girls headin' off to the river, yeah",
  "Victoria's Secret ain't a secret no more ",
  "I brought the songs and you brought the party",
  "Only one way to do it up right",
  "Everybody goes where everybody knows ",
  "That anything goes on a Friday night",
  "Get your party right, it's a Friday night ",
  "Get your party right, it's a Friday night",
  "",
  "Alabama on the boombox baby ",
  "Bout to get a little boondock crazy ",
  "Hop on, it's a helluva ride ",
  "'Cause anything goes on a Friday night",
  "",
  "Lime on the rim of that dixie silver",
  "Smokin' up a faded out 4x4",
  "Girls headin' off to the river, yeah",
  "Victoria's Secret ain't a secret no more ",
  "I brought the songs and you brought the party",
  "Only one way to do it up right",
  "Everybody goes where everybody knows ",
  "That anything goes on a Friday Night",
  "Get your party right It's a Friday night ",
  "Get your party right It's a Friday night",
  ""
]