module.exports = ["I remember when we broke up the first time",
"We hadn't seen each other in a month",
"When you said you needed space. (What?)",
"Then you come around again and say",
"Remember how that lasted for a day?",
"Ooh, we called it off again last night",
"But ooh, this time I'm telling you, I'm telling you",
"We are never ever ever getting back together,",
"You go talk to your friends, talk to my friends, talk to me",
"But we are never ever ever ever getting back together",
"Like, ever...",
"I'm really gonna miss you picking fights",
"And me falling for it screaming that I'm right",
"And you would hide away and find your peace of mind",
"With some indie record that's much cooler than mine",
"Ooh, you called me up again tonight",
"We are never, ever, ever getting back together",
"You go talk to your friends, talk to my friends, talk to me (talk to me)",
"Ooh, yeah, ooh yeah, ooh yeah",
"Oh oh oh",
"I used to think that we were forever ever",
"No!",
"We are never ever ever getting back together",
"We, ooh, getting back together, ohhh,",
"We, ooh, getting back together",
"It feels like a perfect night to dress up like hipsters",
"And make fun of our exes, uh uh, uh uh.",
"It feels like a perfect night for breakfast at midnight",
"To fall in love with strangers, uh uh, uh uh.",
"Yeah,",
"We're happy, free, confused, and lonely at the same time",
"It's miserable and magical.",
"Oh, yeah",
"Tonight's the night when we forget about the deadlines",
"It's time",
"Uh oh!",
"I don't know about you",
"But I'm feeling 22",
"Everything will be alright",
"If you keep me next to you",
"You don't know about me",
"But I'll bet you want to",
"If we just keep dancing like we're",
"22, ooh-ooh",
"It seems like one of those nights,",
"This place is too crowded.",
"Too many cool kids, uh uh, uh uh (who's Taylor Swift anyway, ew?)",
"We ditch the whole scene and end up dreaming",
"Instead of sleeping.",
"We're happy, free, confused, and lonely in the best way",
"Tonight's the night when we forget about the heartbreaks",
"Uh oh! (hey!)",
"Everything will be alright (alright)",
"22, ooh-ooh (oh, oh, oh)",
"It feels like one of those nights,",
"We ditch the whole scene.",
"We won't be sleeping.",
"You look like bad news.",
"I gotta have you,",
"I gotta have you.",
"Ooh-ooh",
"Ooh-ooh, ye-e-e-e-eah, hey",
"I don't know about you (I don't know about you)",
"You don't know about me (you don't know about me)",
"22, ooh-ooh, yeah, yeah",
"22, ooh-ooh, yeah, yeah, yeah",
"We ditch the whole scene",
"We won't be sleeping",
"You look like bad news,",
"Loving him is like driving a new Maserati down a dead-end street",
"Faster than the wind, passionate as sin, ending so suddenly",
"Loving him is like trying to change your mind once you're already flying through the free fall",
"Like the colors in autumn, so bright just before they lose it all",
"Losing him was blue like I'd never known",
"Missing him was dark grey all alone",
"Forgetting him was like trying to know somebody you never met",
"But loving him was red",
"Loving him was red",
"Touching him was like realizing all you ever wanted was right there in front of you",
"Memorizing him was as easy as knowing all the words to your old favorite song",
"Fighting with him was like trying to solve a crossword and realizing there's no right answer",
"Regretting him was like wishing you never found out that love could be that strong",
"Oh, red",
"Burning red",
"Remembering him comes in flashbacks and echoes",
"Tell myself it's time now, gotta let go",
"But moving on from him is impossible",
"When I still see it all in my head",
"In burning red",
"Burning, it was red",
"Oh, losing him was blue like I'd never known",
"'Cause loving him was red",
"Yeah, yeah, red",
"We're burning red",
"And that's why he's spinnin' 'round in my head",
"Comes back to me, burning red",
"Yeah, yeah",
"His love was like driving a new Maserati down a dead-end street",
"I think--I think when it's all over,",
"It just comes back in flashes, you know?",
"It's like a kaleidoscope of memories.",
"It just all comes back. But he never does.",
"I think part of me knew the second I saw him that this would happen.",
"It's not really anything he said or anything he did,",
"It was the feeling that came along with it.",
"And the crazy thing is I don't know if I'm ever gonna feel that way again.",
"But I don't know if I should.",
"I knew his world moved too fast and burned too bright.",
"But I just thought, how can the devil be pulling you toward someone who looks so much like an angel when he smiles at you?",
"Maybe he knew that when he saw me.",
"I guess I just lost my balance.",
"I think that the worst part of it all wasn't losing him.",
"It was losing me.",
"Once upon a time a few mistakes ago",
"I was in your sights, you got me alone",
"You found me, you found me, you found me",
"I guess you didn't care, and I guess I liked that",
"And when I fell hard you took a step back",
"Without me, without me, without me",
"And he's long gone when he's next to me",
"And I realize the blame is on me",
"'Cause I knew you were trouble when you walked in",
"So shame on me now",
"Flew me to places I'd never been",
"'Til you put me down, oh",
"I knew you were trouble when you walked in",
"Now I'm lying on the cold hard ground",
"Oh, oh, trouble, trouble, trouble",
"No apologies. He'll never see you cry,",
"Pretends he doesn't know that he's the reason why.",
"You're drowning, you're drowning, you're drowning.",
"Now I heard you moved on from whispers on the street",
"A new notch in your belt is all I'll ever be",
"And now I see, now I see, now I see",
"He was long gone when he met me",
"And I realize the joke is on me, yeah!",
"And the saddest fear comes creeping in",
"That you never loved me or her, or anyone, or anything, yeah",
"I knew you were trouble when you walked in (you were right there, you were right there)",
"Trouble, trouble, trouble",
"I stay out too late",
"Got nothing in my brain",
"That's what people say, mmm-mmm",
"But I can't make them stay",
"At least that's what people say, mmm-mmm",
"But I keep cruising",
"Can't stop, won't stop moving",
"It's like I got this music",
"In my mind",
"'Cause the players gonna play, play, play, play, play",
"And the haters gonna hate, hate, hate, hate, hate",
"Baby, I'm just gonna shake, shake, shake, shake, shake",
"I shake it off, I shake it off",
"Heart-breakers gonna break, break, break, break, break",
"And the fakers gonna fake, fake, fake, fake, fake",
"I never miss a beat",
"I'm lightning on my feet",
"And that's what they don't see, mmm-mmm",
"That's what they don't see, mmm-mmm",
"I'm dancing on my own (dancing on my own)",
"I make the moves up as I go (moves up as I go)",
"And that's what they don't know, mmm-mmm",
"That's what they don't know, mmm-mmm",
"Can't stop, won't stop grooving",
"Shake it off, I shake it off,",
"I, I, I shake it off, I shake it off,",
"I, I, I shake it off, I shake it off",
"Hey, hey, hey",
"Just think while you've been getting down and out about the liars and the dirty, dirty cheats of the world,",
"You could've been getting down to this sick beat.",
"My ex-man brought his new girlfriend",
"And to the fella over there with the hella good hair",
"Won't you come on over, baby? We can shake, shake, shake",
"Yeah ohhh",
"And the haters gonna hate, hate, hate, hate, hate (haters gonna hate)",
"I'm just gonna shake, shake, shake, shake, shake",
"Heart-breakers gonna break, break, break, break, break (mmmm)",
"And the fakers gonna fake, fake, fake, fake, fake (and fake, and fake, and fake)",
"I, I, I shake it off, I shake it off (you've got to),",
"'Cause, baby, now we got bad blood",
"You know it used to be mad love",
"So take a look what you've done",
"Hey",
"Now we got problems",
"And I don't think we can solve them",
"You made a really deep cut",
"And, baby, now we got bad blood",
"Did you have to do this? I was thinking that you could be trusted",
"Did you have to ruin what was shiny? Now it's all rusted",
"Did you have to hit me, where I'm weak? Baby, I couldn't breathe",
"And rub it in so deep, salt in the wound like you're laughing right at me",
"Oh, it's so sad to think about the good times, you and I",
"Did you think we'd be fine? Still got scars on my back from your knife",
"So don't think it's in the past, these kinda wounds they last and they last.",
"Now did you think it all through? All these things will catch up to you",
"And time can heal but this won't, so if you're coming my way, just don't",
"Band-aids don't fix bullet holes",
"You say sorry just for show",
"If you live like that, you live with ghosts (ghosts)",
"Band-aids don't fix bullet holes (hey)",
"You say sorry just for show (hey)",
"If you live like that, you live with ghosts (hey)",
"If you love like that blood runs cold",
"You know it used to be mad love (mad love)",
"And I don't think we can solve them (think we can solve them)",
"(Hey)",
"So take a look what you've done (look what you've done)",
"Midnight,",
"You come and pick me up, no headlights",
"A long drive,",
"Could end in burning flames or paradise",
"Fade into view, oh, it's been a while since I have even heard from you (heard from you)",
"I should just tell you to leave 'cause I",
"Know exactly where it leads but I",
"Watch us go 'round and 'round each time",
"You got that James Dean daydream look in your eye",
"And I got that red lip classic thing that you like",
"And when we go crashing down, we come back every time",
"'Cause we never go out of style",
"We never go out of style",
"You got that long hair, slicked back, white t-shirt",
"And I got that good girl faith and a tight little skirt",
"We never go out of style.",
"So it goes",
"He can't keep his wild eyes on the road",
"Takes me home",
"Lights are off, he's taking off his coat, hmm, yeah.",
"'Cause you got that James Dean daydream look in your eye",
"And I got that good girl faith and a tight little skirt (tight little skirt)",
"Take me home",
"Just take me home, yeah.",
"Just take me home",
"(out of style)",
"I was reminiscing just the other day,",
"While having coffee all alone and Lord, it took me away.",
"Back to a first-glance feeling on New York Time.",
"Back when you fit in my poems like a perfect rhyme.",
"Yeah, you skipped the conversation when you already know.",
"I left a note on the door with a joke we’d made,",
"And that was the first day.",
"And darling, it was good never looking down.",
"And right there where we stood was holy ground.",
"Spinning like a girl in a brand new dress,",
"We had this big wide city all to ourselves.",
"We blocked the noise with the sound of ‘I need you’,",
"And for the first time I had something to lose,",
"And I guess we fell apart in the usual way.",
"And the story’s got dust on every page,",
"But sometimes I wonder how you think about it now.",
"And I see your face in every crowd.",
"Cause darling, it was good never looking down.",
"Tonight I’m gonna dance for all that we’ve been through.",
"But I don’t wanna dance if I’m not dancing with you.",
"Tonight I’m gonna dance like you were in this room.",
"But I don’t wanna dance if I’m not dancing with you,",
"It was good never looking down.",
"I still remember the look on your face",
"Lit through the darkness at 1:58",
"The words that you whispered",
"For just us to know",
"You told me you loved me",
"So why did you go away?",
"Away",
"I do recall now the smell of the rain",
"Fresh on the pavement",
"I ran off the plane",
"That July 9th",
"The beat of your heart",
"It jumps through your shirt",
"I can still feel your arms",
"But now I'll go sit on the floor",
"Wearing your clothes",
"All that I know is",
"I don't know how to be something you miss",
"I never thought we'd have a last kiss",
"Never imagined we'd end like this",
"Your name, forever the name on my lips",
"I do remember the swing of your step",
"The life of the party, you're showing off again",
"And I roll my eyes and then",
"You pull me in",
"I'm not much for dancing",
"But for you I did",
"Because I love your handshake, meeting my father",
"I love how you walk with your hands in your pockets",
"How you kissed me when I was in the middle of saying something",
"There's not a day I don't miss those rude interruptions",
"And I'll go sit on the floor",
"Never thought we'd have a last kiss",
"So I'll watch your life in pictures like I used to watch you sleep",
"And I feel you forget me like I used to feel you breathe",
"And I keep up with our old friends just to ask them how you are",
"Hope it's nice where you are",
"And I hope the sun shines",
"And it's a beautiful day",
"And something reminds you",
"You wish you had stayed",
"You can plan for a change in weather and time",
"But I never planned on you changing your mind",
"So I'll go sit on the floor",
"Just like our last kiss",
"Forever the name on my lips",
"Just like our last...",
"You're on the phone with your girlfriend",
"She's upset, she's going off about something that you said",
"'Cause she doesn't get your humor like I do.",
"I'm in the room, it's a typical Tuesday night.",
"I'm listening to the kind of music she doesn't like.",
"And she'll never know your story like I do.",
"But she wears short skirts",
"I wear t-shirts",
"She's cheer captain",
"And I'm on the bleachers",
"Dreaming about the day when you wake up and find",
"That what you're looking for has been here the whole time.",
"If you could see",
"That I'm the one",
"Who understands you.",
"Been here all along.",
"So, why can't you see",
"You belong with me,",
"You belong with me.",
"Walk in the streets with you in your worn out jeans",
"I can't help thinking this is how it ought to be.",
"Laughing on a park bench thinking to myself,",
"And you've got a smile",
"That could light up this whole town.",
"I haven't seen it in a while",
"Since she brought you down.",
"You say you're fine I know you better than that.",
"Hey, what you doing with a girl like that?",
"She wears high heels,",
"I wear sneakers.",
"She's cheer captain,",
"And I'm on the bleachers.",
"Who understands you,",
"Standing by and waiting at your backdoor.",
"All this time how could you not know, baby?",
"[Instrumental]",
"Oh, I remember you driving to my house",
"In the middle of the night.",
"I'm the one who makes you laugh",
"When you know you're 'bout to cry.",
"I know your favorite songs,",
"And you tell me about your dreams.",
"Think I know where you belong,",
"Think I know it's with me.",
"Can't you see",
"Who understands you?",
"Have you ever thought just maybe",
"You belong with me?",
"Nice to meet you, where you been?",
"I could show you incredible things",
"Magic, madness, heaven, sin",
"Saw you there and I thought",
"Oh my God, look at that face",
"You look like my next mistake",
"Love's a game, wanna play?",
"New money, suit and tie",
"I can read you like a magazine",
"Ain't it funny, rumors fly",
"And I know you heard about me",
"So hey, let's be friends",
"I'm dying to see how this one ends",
"Grab your passport and my hand",
"I can make the bad guys good for a weekend",
"So it's gonna be forever",
"Or it's gonna go down in flames",
"You can tell me when it's over",
"If the high was worth the pain",
"Got a long list of ex-lovers",
"They'll tell you I'm insane",
"'Cause you know I love the players",
"And you love the game",
"'Cause we're young and we're reckless",
"We'll take this way too far",
"It'll leave you breathless",
"Or with a nasty scar",
"But I've got a blank space, baby",
"And I'll write your name",
"Cherry lips, crystal skies",
"Stolen kisses, pretty lies",
"You're the King, baby, I'm your Queen",
"Find out what you want",
"Be that girl for a month",
"Wait, the worst is yet to come, oh no",
"Screaming, crying, perfect storms",
"I can make all the tables turn",
"Rose garden filled with thorns",
"Keep you second guessing like",
"I get drunk on jealousy",
"But you'll come back each time you leave",
"'Cause, darling, I'm a nightmare dressed like a daydream",
"Boys only want love if it's torture",
"Don't say I didn't say, I didn't warn ya",
"You stand with your hand on my waist line",
"It's a scene and we're out here in plain sight",
"I can hear them whisper as we pass by",
"It's a bad sign, bad sign",
"Something happens when everybody finds out",
"See the vultures circling dark clouds",
"Love's a fragile little flame, it could burn out",
"It could burn out",
"Cause they got the cages, they got the boxes",
"And guns",
"They are the hunters, we are the foxes",
"And we run",
"Baby, I know places we won't be found",
"And they'll be chasing their tails tryin' to track us down",
"Cause I, I know places we can hide",
"I know places, I know places",
"Lights flash and we'll run for the fences",
"Let them say what they want, we won't hear it",
"Loose lips sink ships all the damn time",
"Not this time",
"Just grab my hand and don't ever drop it",
"My love",
"I know places",
"They take their shots, but we're bulletproof",
"And you know for me, it's always you",
"In the dead of night, your eyes so green",
"And I know for you, it's always me"]