module.exports = [
  "AGAIN rejoicing Nature sees",
  "  Her robe assume its vernal hues:",
  "Her leafy locks wave in the breeze,",
  "  All freshly steep’d in morning dews.",
  "",
  "",
  "  Chorus.—And maun I still on Menie doat,",
  "    And bear the scorn that’s in her e’e?",
  "  For it’s jet, jet black, an’ it’s like a hawk,",
  "    An’ it winna let a body be.",
  "",
  "",
  "In vain to me the cowslips blaw,",
  "  In vain to me the vi’lets spring;",
  "In vain to me in glen or shaw,",
  "  The mavis and the lintwhite sing.",
  "                And maun I still, &c.",
  "",
  "",
  "The merry ploughboy cheers his team,",
  "Wi’ joy the tentie seedsman stalks;",
  "But life to me’s a weary dream,",
  "A dream of ane that never wauks.",
  "                And maun I still, &c.",
  "",
  "",
  "The wanton coot the water skims,",
  "Amang the reeds the ducklings cry,",
  "The stately swan majestic swims,",
  "And ev’ry thing is blest but I.",
  "                And maun I still, &c.",
  "",
  "",
  "The sheep-herd steeks his faulding slap,",
  "And o’er the moorlands whistles shill:",
  "Wi’ wild, unequal, wand’ring step,",
  "I meet him on the dewy hill.",
  "                And maun I still, &c.",
  "",
  "",
  "And when the lark, ’tween light and dark,",
  "Blythe waukens by the daisy’s side,",
  "And mounts and sings on flittering wings,",
  "A woe-worn ghaist I hameward glide.",
  "                And maun I still, &c.",
  "",
  "",
  "Come winter, with thine angry howl,",
  "And raging, bend the naked tree;",
  "Thy gloom will soothe my cheerless soul,",
  "When nature all is sad like me!",
  "                And maun I still, &c.",
  ""
]