module.exports = [
  "ADIEU! a heart-warm fond adieu;",
  "  Dear brothers of the mystic tie!",
  "Ye favourèd, enlighten’d few,",
  "  Companions of my social joy;",
  "Tho’ I to foreign lands must hie,",
  "  Pursuing Fortune’s slidd’ry ba’;",
  "With melting heart, and brimful eye,",
  "  I’ll mind you still, tho’ far awa.",
  "",
  "",
  "Oft have I met your social band,",
  "  And spent the cheerful, festive night;",
  "Oft, honour’d with supreme command,",
  "  Presided o’er the sons of light:",
  "And by that hieroglyphic bright,",
  "  Which none but Craftsmen ever saw",
  "Strong Mem’ry on my heart shall write",
  "  Those happy scenes, when far awa.",
  "",
  "",
  "May Freedom, Harmony, and Love,",
  "  Unite you in the grand Design,",
  "Beneath th’ Omniscient Eye above,",
  "  The glorious Architect Divine,",
  "That you may keep th’ unerring line,",
  "  Still rising by the plummet’s law,",
  "Till Order bright completely shine,",
  "  Shall be my pray’r when far awa.",
  "",
  "",
  "And you, farewell! whose merits claim",
  "  Justly that highest badge to wear:",
  "Heav’n bless your honour’d noble name,",
  "  To Masonry and Scotia dear!",
  "A last request permit me here,—",
  "  When yearly ye assemble a’,",
  "One round, I ask it with a tear,",
  "  To him, the Bard that’s far awa.",
  ""
]