module.exports = [
  "FROM thee, Eliza, I must go,",
  "  And from my native shore;",
  "The cruel fates between us throw",
  "  A boundless ocean’s roar:",
  "But boundless oceans, roaring wide,",
  "  Between my love and me,",
  "They never, never can divide",
  "  My heart and soul from thee.",
  "",
  "",
  "Farewell, farewell, Eliza dear,",
  "  The maid that I adore!",
  "A boding voice is in mine ear,",
  "  We part to meet no more!",
  "But the latest throb that leaves my heart,",
  "  While Death stands victor by,—",
  "That throb, Eliza, is thy part,",
  "  And thine that latest sigh!",
  ""
]