module.exports = [
  "LET other heroes boast their scars,",
  "  The marks of sturt and strife:",
  "And other poets sing of wars,",
  "  The plagues of human life:",
  "Shame fa’ the fun, wi’ sword and gun",
  "  To slap mankind like lumber!",
  "I sing his name, and nobler fame,",
  "  Wha multiplies our number.",
  "",
  "",
  "Great Nature spoke, with air benign,",
  "  “Go on, ye human race;",
  "This lower world I you resign;",
  "  Be fruitful and increase.",
  "The liquid fire of strong desire",
  "  I’ve pour’d it in each bosom;",
  "Here, on this had, does Mankind stand,",
  "  And there is Beauty’s blossom.”",
  "",
  "",
  "The Hero of these artless strains,",
  "  A lowly bard was he,",
  "Who sung his rhymes in Coila’s plains,",
  "  With meikle mirth an’glee;",
  "Kind Nature’s care had given his share",
  "  Large, of the flaming current;",
  "And, all devout, he never sought",
  "  To stem the sacred torrent.",
  "",
  "",
  "He felt the powerful, high behest",
  "  Thrill, vital, thro’ and thro’;",
  "And sought a correspondent breast,",
  "  To give obedience due:",
  "Propitious Powers screen’d the young flow’rs,",
  "  From mildews of abortion;",
  "And low! the bard—a great reward—",
  "  Has got a double portion!",
  "",
  "",
  "Auld cantie Coil may count the day,",
  "  As annual it returns,",
  "The third of Libra’s equal sway,",
  "  That gave another Burns,",
  "With future rhymes, an’ other times,",
  "  To emulate his sire:",
  "To sing auld Coil in nobler style",
  "  With more poetic fire.",
  "",
  "",
  "Ye Powers of peace, and peaceful song,",
  "  Look down with gracious eyes;",
  "And bless auld Coila, large and long,",
  "  With multiplying joys;",
  "Lang may she stand to prop the land,",
  "  The flow’r of ancient nations;",
  "And Burnses spring, her fame to sing,",
  "  To endless generations!",
  ""
]