module.exports = [
  "A ROSE-BUD by my early walk,",
  "Adown a corn-enclosed bawk,",
  "Sae gently bent its thorny stalk,",
  "    All on a dewy morning.",
  "Ere twice the shades o’ dawn are fled,",
  "In a’ its crimson glory spread,",
  "And drooping rich the dewy head,",
  "    It scents the early morning.",
  "",
  "",
  "Within the bush her covert nest",
  "A little linnet fondly prest;",
  "The dew sat chilly on her breast,",
  "    Sae early in the morning.",
  "She soon shall see her tender brood,",
  "The pride, the pleasure o’ the wood,",
  "Amang the fresh green leaves bedew’d,",
  "    Awake the early morning.",
  "",
  "",
  "So thou, dear bird, young Jeany fair,",
  "On trembling string or vocal air,",
  "Shall sweetly pay the tender care",
  "    That tents thy early morning.",
  "So thou, sweet Rose-bud, young and gay,",
  "Shalt beauteous blaze upon the day,",
  "And bless the parent’s evening ray",
  "    That watch’d thy early morning.",
  ""
]