module.exports = [
  "AFAR 1 the illustrious Exile roams,",
  "    Whom kingdoms on this day should hail;",
  "  An inmate in the casual shed,",
  "  On transient pity’s bounty fed,",
  "    Haunted by busy memory’s bitter tale!",
  "  Beasts of the forest have their savage homes,",
  "    But He, who should imperial purple wear,",
  "Owns not the lap of earth where rests his royal head!",
  "    His wretched refuge, dark despair,",
  "  While ravening wrongs and woes pursue,",
  "  And distant far the faithful few",
  "    Who would his sorrows share.",
  "",
  "",
  "  False flatterer, Hope, away!",
  "    Nor think to lure us as in days of yore:",
  "  We solemnize this sorrowing natal day,",
  "    To prove our loyal truth-we can no more,",
  "  And owning Heaven’s mysterious sway,",
  "    Submissive, low adore.",
  "",
  "",
  "  Ye honored, mighty Dead,",
  "    Who nobly perished in the glorious cause,",
  "    Your King, your Country, and her laws,",
  "  From great DUNDEE, who smiling Victory led,",
  "  And fell a Martyr in her arms,",
  "  (What breast of northern ice but warms!)",
  "  To bold BALMERINO’S undying name,",
  "  Whose soul of fire, lighted at Heaven’s high flame,",
  "Deserves the proudest wreath departed heroes claim:",
  "  Nor unrevenged your fate shall lie,",
  "    It only lags, the fatal hour,",
  "  Your blood shall, with incessant cry,",
  "    Awake at last, th’ unsparing Power;",
  "  As from the cliff, with thundering course,",
  "    The snowy ruin smokes along",
  "  With doubling speed and gathering force,",
  "Till deep it, crushing, whelms the cottage in the vale;",
  "    So Vengeance’ arm, ensanguin’d, strong,",
  "  Shall with resistless might assail,",
  "  Usurping Brunswick’s pride shall lay,",
  "And STEWART’S wrongs and yours, with tenfold weight repay.",
  "",
  "",
  "  PERDITION, baleful child of night!",
  "  Rise and revenge the injured right",
  "    Of STEWART’S royal race:",
  "  Lead on the unmuzzled hounds of hell,",
  "  Till all the frighted echoes tell",
  "    The blood-notes of the chase!",
  "  Full on the quarry point their view,",
  "  Full on the base usurping crew,",
  "The tools of faction, and the nation’s curse!",
  "  Hark how the cry grows on the wind;",
  "  They leave the lagging gale behind,",
  "  Their savage fury, pitiless, they pour;",
  "  With murdering eyes already they devour;",
  "    See Brunswick spent, a wretched prey,",
  "  His life one poor despairing day,",
  "Where each avenging hour still ushers in a worse!",
  "    Such havock, howling all abroad,",
  "      Their utter ruin bring,",
  "    The base apostates to their God,",
  "      Or rebels to their King.",
  "",
  "",
  " Note 1. The last birthday of Prince Charles Edward. [back]",
  ""
]