module.exports = [
  "WHEN dear Clarinda, 1 matchless fair,",
  "  First struck Sylvander’s raptur’d view,",
  "He gaz’d, he listened to despair,",
  "  Alas! ’twas all he dared to do.",
  "",
  "",
  "Love, from Clarinda’s heavenly eyes,",
  "  Transfixed his bosom thro’ and thro’;",
  "But still in Friendships’ guarded guise,",
  "  For more the demon fear’d to do.",
  "",
  "",
  "That heart, already more than lost,",
  "  The imp beleaguer’d all perdue;",
  "For frowning Honour kept his post—",
  "  To meet that frown, he shrunk to do.",
  "",
  "",
  "His pangs the Bard refused to own,",
  "  Tho’ half he wish’d Clarinda knew;",
  "But Anguish wrung the unweeting groan—",
  "  Who blames what frantic Pain must do?",
  "",
  "",
  "That heart, where motley follies blend,",
  "  Was sternly still to Honour true:",
  "To prove Clarinda’s fondest friend,",
  "  Was what a lover sure might do.",
  "",
  "",
  "The Muse his ready quill employed,",
  "  No nearer bliss he could pursue;",
  "That bliss Clarinda cold deny’d—",
  "  “Send word by Charles how you do!”",
  "",
  "",
  "The chill behest disarm’d his muse,",
  "  Till passion all impatient grew:",
  "He wrote, and hinted for excuse,",
  "  ’Twas, ’cause “he’d nothing else to do.”",
  "",
  "",
  "But by those hopes I have above!",
  "  And by those faults I dearly rue!",
  "The deed, the boldest mark of love,",
  "  For thee that deed I dare uo do!",
  "",
  "",
  "O could the Fates but name the price",
  "  Would bless me with your charms and you!",
  "With frantic joy I’d pay it thrice,",
  "  If human art and power could do!",
  "",
  "",
  "Then take, Clarinda, friendship’s hand,",
  "  (Friendship, at least, I may avow;)",
  "And lay no more your chill command,—",
  "  I’ll write whatever I’ve to do.SYLVANDER.",
  "",
  "",
  " Note 1. A grass-widow, Mrs. M’Lehose. [back]",
  ""
]