module.exports = [
  "THERE was once a day, but old Time wasythen young,",
  "  That brave Caledonia, the chief of her line,",
  "From some of your northern deities sprung,",
  "  (Who knows not that brave Caledonia’s divine?)",
  "From Tweed to the Orcades was her domain,",
  "  To hunt, or to pasture, or do what she would:",
  "Her heav’nly relations there fixed her reign,",
  "  And pledg’d her their godheads to warrant it good.",
  "",
  "",
  "A lambkin in peace, but a lion in war,",
  "  The pride of her kindred, the heroine grew:",
  "Her grandsire, old Odin, triumphantly swore,—",
  "  “Whoe’er shall provoke thee, th’ encounter shall rue!”",
  "With tillage or pasture at times she would sport,",
  "  To feed her fair flocks by her green rustling corn;",
  "But chiefly the woods were her fav’rite resort,",
  "  Her darling amusement, the hounds and the horn.",
  "",
  "",
  "Long quiet she reigned; till thitherward steers",
  "  A flight of bold eagles from Adria’s strand:",
  "Repeated, successive, for many long years,",
  "  They darken’d the air, and they plunder’d the land:",
  "Their pounces were murder, and terror their cry,",
  "  They’d conquer’d and ruin’d a world beside;",
  "She took to her hills, and her arrows let fly,",
  "  The daring invaders they fled or they died.",
  "",
  "",
  "The Cameleon-Savage disturb’d her repose,",
  "  With tumult, disquiet, rebellion, and strife;",
  "Provok’d beyond bearing, at last she arose,",
  "  And robb’d him at once of his hopes and his life:",
  "The Anglian lion, the terror of France,",
  "  Oft prowling, ensanguin’d the Tweed’s silver flood;",
  "But, taught by the bright Caledonian lance,",
  "  He learnèd to fear in his own native wood.",
  "",
  "",
  "The fell Harpy-raven took wing from the north,",
  "  The scourge of the seas, and the dread of the shore;",
  "The wild Scandinavian boar issued forth",
  "  To wanton in carnage and wallow in gore:",
  "O’er countries and kingdoms their fury prevail’d,",
  "  No arts could appease them, no arms could repel;",
  "But brave Caledonia in vain they assail’d,",
  "  As Largs well can witness, and Loncartie tell.",
  "",
  "",
  "Thus bold, independent, unconquer’d, and free,",
  "  Her bright course of glory for ever shall run:",
  "For brave Caledonia immortal must be;",
  "  I’ll prove it from Euclid as clear as the sun:",
  "Rectangle-triangle, the figure we’ll chuse:",
  "  The upright is Chance, and old Time is the base;",
  "But brave Caledonia’s the hypothenuse;",
  "  Then, ergo, she’ll match them, and match them always.",
  ""
]