module.exports = [
  "HEAR, Land o’ Cakes, and brither Scots,",
  "Frae Maidenkirk to Johnie Groat’s;—",
  "If there’s a hole in a’ your coats,",
  "                  I rede you tent it:",
  "A chield’s amang you takin notes,",
  "                  And, faith, he’ll prent it:",
  "",
  "",
  "If in your bounds ye chance to light",
  "Upon a fine, fat fodgel wight,",
  "O’ stature short, but genius bright,",
  "                  That’s he, mark weel;",
  "And wow! he has an unco sleight",
  "                  O’ cauk and keel.",
  "",
  "",
  "By some auld, houlet-haunted biggin,",
  "Or kirk deserted by its riggin,",
  "It’s ten to ane ye’ll find him snug in",
  "                  Some eldritch part,",
  "Wi’ deils, they say, L—d save’s! colleaguin",
  "                  At some black art.",
  "",
  "",
  "Ilk ghaist that haunts auld ha’ or chaumer,",
  "Ye gipsy-gang that deal in glamour,",
  "And you, deep-read in hell’s black grammar,",
  "                  Warlocks and witches,",
  "Ye’ll quake at his conjuring hammer,",
  "                  Ye midnight bitches.",
  "",
  "",
  "It’s tauld he was a sodger bred,",
  "And ane wad rather fa’n than fled;",
  "But now he’s quat the spurtle-blade,",
  "                  And dog-skin wallet,",
  "And taen the—Antiquarian trade,",
  "                  I think they call it.",
  "",
  "",
  "He has a fouth o’ auld nick-nackets:",
  "Rusty airn caps and jinglin jackets,",
  "Wad haud the Lothians three in tackets,",
  "                  A towmont gude;",
  "And parritch-pats and auld saut-backets,",
  "                  Before the flood.",
  "",
  "",
  "Of Eve’s first fire he has a cinder;",
  "Auld Tubalcain’s fire-shool and fender;",
  "That which distinguished the gender",
  "                  O’ Balaam’s ass:",
  "A broomstick o’ the witch of Endor,",
  "                  Weel shod wi’ brass.",
  "",
  "",
  "Forbye, he’ll shape you aff fu’ gleg",
  "The cut of Adam’s philibeg;",
  "The knife that nickit Abel’s craig",
  "                  He’ll prove you fully,",
  "It was a faulding jocteleg,",
  "                  Or lang-kail gullie.",
  "",
  "",
  "But wad ye see him in his glee,",
  "For meikle glee and fun has he,",
  "Then set him down, and twa or three",
  "                  Gude fellows wi’ him:",
  "And port, O port! shine thou a wee,",
  "                  And THEN ye’ll see him!",
  "",
  "",
  "Now, by the Pow’rs o’ verse and prose!",
  "Thou art a dainty chield, O Grose!—",
  "Whae’er o’ thee shall ill suppose,",
  "                  They sair misca’ thee;",
  "I’d take the rascal by the nose,",
  "                  Wad say, “Shame fa’ thee!”",
  ""
]