module.exports = [
  "ORTHODOX! orthodox, who believe in John Knox,",
  "  Let me sound an alarm to your conscience:",
  "A heretic blast has been blown in the West,",
  "  That what is no sense must be nonsense,",
  "Orthodox! That what is no sense must be nonsense.",
  "",
  "",
  "Doctor Mac! Doctor Mac, you should streek on a rack,",
  "  To strike evil-doers wi’ terror:",
  "To join Faith and Sense, upon any pretence,",
  "  Was heretic, damnable error,",
  "Doctor Mac! 1 ’Twas heretic, damnable error.",
  "",
  "",
  "Town of Ayr! town of Ayr, it was mad, I declare,",
  "  To meddle wi’ mischief a-brewing, 2",
  "Provost John 3 is still deaf to the Church’s relief,",
  "  And Orator Bob 4 is its ruin,",
  "Town of Ayr! Yes, Orator Bob is its ruin.",
  "",
  "",
  "D’rymple mild! D’rymple mild, tho’ your heart’s like a child,",
  "  And your life like the new-driven snaw,",
  "Yet that winna save you, auld Satan must have you,",
  "  For preaching that three’s ane an’ twa,",
  "D’rymple mild! 5 For preaching that three’s ane an’ twa.",
  "",
  "",
  "Rumble John! rumble John, mount the steps with a groan,",
  "  Cry the book is with heresy cramm’d;",
  "Then out wi’ your ladle, deal brimstone like aidle,",
  "  And roar ev’ry note of the D—’d.",
  "Rumble John! 6 And roar ev’ry note of the D—’d.",
  "",
  "",
  "Simper James! simper James, leave your fair Killie dames,",
  "  There’s a holier chase in your view:",
  "I’ll lay on your head, that the pack you’ll soon lead,",
  "  For puppies like you there’s but few,",
  "Simper James! 7 For puppies like you there’s but few.",
  "",
  "",
  "Singet Sawnie! singet Sawnie, are ye huirdin the penny,",
  "  Unconscious what evils await?",
  "With a jump, yell, and howl, alarm ev’ry soul,",
  "  For the foul thief is just at your gate.",
  "Singet Sawnie! 8 For the foul thief is just at your gate.",
  "",
  "",
  "Poet Willie! poet Willie, gie the Doctor a volley,",
  "  Wi’ your “Liberty’s Chain” and your wit;",
  "O’er Pegasus’ side ye ne’er laid a stride,",
  "  Ye but smelt, man, the place where he sh-t.",
  "Poet Willie! 9 Ye but smelt man, the place where he sh-t.",
  "",
  "",
  "Barr Steenie! Barr Steenie, what mean ye, what mean ye?",
  "  If ye meddle nae mair wi’ the matter,",
  "Ye may hae some pretence to havins and sense,",
  "  Wi’ people that ken ye nae better,",
  "Barr Steenie! 10 Wi’people that ken ye nae better.",
  "",
  "",
  "Jamie Goose! Jamie Goose, ye made but toom roose,",
  "  In hunting the wicked Lieutenant;",
  "But the Doctor’s your mark, for the Lord’s holy ark,",
  "  He has cooper’d an’ ca’d a wrang pin in’t,",
  "Jamie Goose! 11 He has cooper’d an’ ca’d a wrang pin in’t.",
  "",
  "",
  "Davie Bluster! Davie Bluster, for a saint ye do muster,",
  "  The core is no nice o’ recruits;",
  "Yet to worth let’s be just, royal blood ye might boast,",
  "  If the Ass were the king o’ the brutes,",
  "Davie Bluster! 12 If the Ass were the king o’ the brutes.",
  "",
  "",
  "Cessnock-side! Cessnock-side, wi’ your turkey-cock pride",
  "  Of manhood but sma’ is your share:",
  "Ye’ve the figure, ’tis true, ev’n your foes will allow,",
  "  And your friends they dare grant you nae mair,",
  "Cessnock-side! 13 And your friends they dare grant you nae mair.",
  "",
  "",
  "Muirland Jock! muirland Jock, when the L—d makes a rock,",
  "  To crush common-sense for her sins;",
  "If ill-manners were wit, there’s no mortal so fit",
  "  To confound the poor Doctor at ance,",
  "Muirland Jock! 14 To confound the poor Doctor at ance.",
  "",
  "",
  "Andro Gowk! Andro Gowk, ye may slander the Book,",
  "  An’ the Book nought the waur, let me tell ye;",
  "Tho’ ye’re rich, an’ look big, yet, lay by hat an’ wig,",
  "  An’ ye’ll hae a calf’s-had o’ sma’ value,",
  "Andro Gowk! 15 Ye’ll hae a calf’s head o’ sma value.",
  "",
  "",
  "Daddy Auld! daddy Auld, there’a a tod in the fauld,",
  "  A tod meikle waur than the clerk;",
  "Tho’ ye do little skaith, ye’ll be in at the death,",
  "  For gif ye canna bite, ye may bark,",
  "Daddy Auld! 16 Gif ye canna bite, ye may bark.",
  "",
  "",
  "Holy Will! holy Will, there was wit in your skull,",
  "  When ye pilfer’d the alms o’ the poor;",
  "The timmer is scant when ye’re taen for a saunt,",
  "  Wha should swing in a rape for an hour,",
  "Holy Will! 17 Ye should swing in a rape for an hour.",
  "",
  "",
  "Calvin’s sons! Calvin’s sons, seize your spiritual guns,",
  "  Ammunition you never can need;",
  "Your hearts are the stuff will be powder enough,",
  "  And your skulls are a storehouse o’ lead,",
  "Calvin’s sons! Your skulls are a storehouse o’ lead.",
  "",
  "",
  "Poet Burns! poet Burns, wi” your priest-skelpin turns,",
  "  Why desert ye your auld native shire?",
  "Your muse is a gipsy, yet were she e’en tipsy,",
  "  She could ca’us nae waur than we are,",
  "Poet Burns! She could ca’us nae waur than we are.",
  "",
  "",
  "PRESENTATION STANZAS TO CORRESPONDENTSFactor John! Factor John, whom the Lord made alone,",
  "  And ne’er made anither, thy peer,",
  "Thy poor servant, the Bard, in respectful regard,",
  "  He presents thee this token sincere,",
  "Factor John! He presents thee this token sincere.",
  "",
  "",
  "Afton’s Laird! Afton’s Laird, when your pen can be spared,",
  "  A copy of this I bequeath,",
  "On the same sicker score as I mention’d before,",
  "  To that trusty auld worthy, Clackleith,",
  "Afton’s Laird! To that trusty auld worthy, Clackleith.",
  "",
  "",
  " Note 1. Dr. M’Gill, Ayr.—R. B. [back]",
  "Note 2. See the advertisement.—R. B. [back]",
  "Note 3. John Ballantine,—R. B. [back]",
  "Note 4. Robert Aiken.—R. B. [back]",
  "Note 5. Dr. Dalrymple, Ayr.—R. B. [back]",
  "Note 6. John Russell, Kilmarnock.—R. B. [back]",
  "Note 7. James Mackinlay, Kilmarnock.—R. B. [back]",
  "Note 8. Alexander Moodie of Riccarton.—R. B. [back]",
  "Note 9. William Peebles, in Newton-upon-Ayr, a poetaster, who, among many other things, published an ode on the “Centenary of the Revolution,” in which was the line:        “And bound in Liberty’s endering chain.”—R. B.",
  " [back]",
  "Note 10. Stephen Young of Barr.—R. B. [back]",
  "Note 11. James Young, in New Cumnock, who had lately been foiled in an ecclesiastical prosecution against a Lieutenant Mitchel—R. B. [back]",
  "Note 12. David Grant, Ochiltree.—R. B. [back]",
  "Note 13. George Smith, Galston.—R. B. [back]",
  "Note 14. John Shepherd Muirkirk.—R. B. [back]",
  "Note 15. Dr. Andrew Mitchel, Monkton.—R. B. [back]",
  "Note 16. William Auld, Mauchline; for the clerk, see “Holy Willie”s Prayer.”—R. B. [back]",
  "Note 17. Vide the “Prayer” of this saint.—R. B. [back]",
  ""
]