module.exports = [
  "I SING of a Whistle, a Whistle of worth,",
  "I sing of a Whistle, the pride of the North.",
  "Was brought to the court of our good Scottish King,",
  "And long with this Whistle all Scotland shall ring.",
  "",
  "",
  "Old Loda, still rueing the arm of Fingal,",
  "The god of the bottle sends down from his hall—",
  "“The Whistle’s your challenge, to Scotland get o’er,",
  "And drink them to hell, Sir! or ne’er see me more!”",
  "",
  "",
  "Old poets have sung, and old chronicles tell,",
  "What champions ventur’d, what champions fell:",
  "The son of great Loda was conqueror still,",
  "And blew on the Whistle their requiem shrill.",
  "",
  "",
  "Till Robert, the lord of the Cairn and the Scaur,",
  "Unmatch’d at the bottle, unconquer’d in war,",
  "He drank his poor god-ship as deep as the sea;",
  "No tide of the Baltic e’er drunker than he.",
  "",
  "",
  "Thus Robert, victorious, the trophy has gain’d;",
  "Which now in his house has for ages remain’d;",
  "Till three noble chieftains, and all of his blood,",
  "The jovial contest again have renew’d.",
  "",
  "",
  "Three joyous good fellows, with hearts clear of flaw",
  "Craigdarroch, so famous for with, worth, and law;",
  "And trusty Glenriddel, so skill’d in old coins;",
  "And gallant Sir Robert, deep-read in old wines.",
  "",
  "",
  "Craigdarroch began, with a tongue smooth as oil,",
  "Desiring Downrightly to yield up the spoil;",
  "Or else he would muster the heads of the clan,",
  "And once more, in claret, try which was the man.",
  "",
  "",
  "“By the gods of the ancients!” Downrightly replies,",
  "“Before I surrender so glorious a prize,",
  "I’ll conjure the ghost of the great Rorie More,",
  "And bumper his horn with him twenty times o’er.”",
  "",
  "",
  "Sir Robert, a soldier, no speech would pretend,",
  "But he ne’er turn’d his back on his foe, or his friend;",
  "Said, “Toss down the Whistle, the prize of the field,”",
  "And, knee-deep in claret, he’d die ere he’d yield.",
  "",
  "",
  "To the board of Glenriddel our heroes repair,",
  "So noted for drowning of sorrow and care;",
  "But, for wine and for welcome, not more known to fame,",
  "Than the sense, wit, and taste, of a sweet lovely dame.",
  "",
  "",
  "A bard was selected to witness the fray,",
  "And tell future ages the feats of the day;",
  "A Bard who detested all sadness and spleen,",
  "And wish’d that Parnassus a vineyard had been.",
  "",
  "",
  "The dinner being over, the claret they ply,",
  "And ev’ry new cork is a new spring of joy;",
  "In the bands of old friendship and kindred so set,",
  "And the bands grew the tighter the more they were wet.",
  "",
  "",
  "Gay Pleasure ran riot as bumpers ran o’er:",
  "Bright Phoebus ne’er witness’d so joyous a core,",
  "And vow’d that to leave them he was quite forlorn,",
  "Till Cynthia hinted he’d see them next morn.",
  "",
  "",
  "Six bottles a-piece had well wore out the night,",
  "When gallant Sir Robert, to finish the fight,",
  "Turn’d o’er in one bumper a bottle of red,",
  "And swore ’twas the way that their ancestor did.",
  "",
  "",
  "Then worthy Glenriddel, so cautious and sage,",
  "No longer the warfare ungodly would wage;",
  "A high Ruling Elder to wallow in wine;",
  "He left the foul business to folks less divine.",
  "",
  "",
  "The gallant Sir Robert fought hard to the end;",
  "But who can with Fate and quart bumpers contend!",
  "Though Fate said, a hero should perish in light;",
  "So uprose bright Phoebus-and down fell the knight.",
  "",
  "",
  "Next uprose our Bard, like a prophet in drink:—",
  "“Craigdarroch, thou’lt soar when creation shall sink!",
  "But if thou would flourish immortal in rhyme,",
  "Come—one bottle more—and have at the sublime!",
  "",
  "",
  "“Thy line, that have struggled for freedom with Bruce,",
  "Shall heroes and patriots ever produce:",
  "So thine be the laurel, and mine be the bay;",
  "The field thou hast won, by yon bright god of day!”",
  ""
]