module.exports = [
  "THOU ling’ring star, with lessening ray,",
  "  That lov’st to greet the early morn,",
  "Again thou usher’st in the day",
  "  My Mary from my soul was torn.",
  "O Mary! dear departed shade!",
  "  Where is thy place of blissful rest?",
  "See’st thou thy lover lowly laid?",
  "  Hear’st thou the groans that rend his breast?",
  "",
  "",
  "That sacred hour can I forget,",
  "  Can I forget the hallow’d grove,",
  "Where, by the winding Ayr, we met,",
  "  To live one day of parting love!",
  "Eternity will not efface",
  "  Those records dear of transports past,",
  "Thy image at our last embrace,",
  "  Ah! little thought we ’twas our last!",
  "",
  "",
  "Ayr, gurgling, kiss’d his pebbled shore,",
  "  O’erhung with wild-woods, thickening green;",
  "The fragrant birch and hawthorn hoar,",
  "  ’Twin’d amorous round the raptur’d scene:",
  "The flowers sprang wanton to be prest,",
  "  The birds sang love on every spray;",
  "Till too, too soon, the glowing west,",
  "  Proclaim’d the speed of winged day.",
  "",
  "",
  "Still o’er these scenes my mem’ry wakes,",
  "  And fondly broods with miser-care;",
  "Time but th’ impression stronger makes,",
  "  As streams their channels deeper wear,",
  "My Mary! dear departed shade!",
  "  Where is thy blissful place of rest?",
  "See’st thou thy lover lowly laid?",
  "  Hear’st thou the groans that rend his breast?",
  ""
]