module.exports = [
  "THERE was five Carlins in the South,",
  "  They fell upon a scheme,",
  "To send a lad to London town,",
  "  To bring them tidings hame.",
  "",
  "",
  "Nor only bring them tidings hame,",
  "  But do their errands there,",
  "And aiblins gowd and honor baith",
  "  Might be that laddie’s share.",
  "",
  "",
  "There was Maggy by the banks o’ Nith,",
  "  A dame wi’ pride eneugh;",
  "And Marjory o’ the mony Lochs,",
  "  A Carlin auld and teugh.",
  "",
  "",
  "And blinkin Bess of Annandale,",
  "  That dwelt near Solway-side;",
  "And whisky Jean, that took her gill,",
  "  In Galloway sae wide.",
  "",
  "",
  "And auld black Joan frae Crichton Peel, 1",
  "  O’ gipsy kith an’ kin;",
  "Five wighter Carlins were na found",
  "  The South countrie within.",
  "",
  "",
  "To send a lad to London town,",
  "  They met upon a day;",
  "And mony a knight, and mony a laird,",
  "  This errand fain wad gae.",
  "",
  "",
  "O mony a knight, and mony a laird,",
  "  This errand fain wad gae;",
  "But nae ane could their fancy please,",
  "  O ne’er a ane but twae.",
  "",
  "",
  "The first ane was a belted Knight,",
  "  Bred of a Border band; 2",
  "And he wad gae to London town,",
  "  Might nae man him withstand.",
  "",
  "",
  "And he wad do their errands weel,",
  "  And meikle he wad say;",
  "And ilka ane about the court",
  "  Wad bid to him gude-day.",
  "",
  "",
  "The neist cam in a Soger youth, 3",
  "  Who spak wi’ modest grace,",
  "And he wad gae to London town,",
  "  If sae their pleasure was.",
  "",
  "",
  "He wad na hecht them courtly gifts,",
  "  Nor meikle speech pretend;",
  "But he wad hecht an honest heart,",
  "  Wad ne’er desert his friend.",
  "",
  "",
  "Now, wham to chuse, and wham refuse,",
  "  At strife thir Carlins fell;",
  "For some had Gentlefolks to please,",
  "  And some wad please themsel’.",
  "",
  "",
  "Then out spak mim-mou’d Meg o’ Nith,",
  "  And she spak up wi’ pride,",
  "And she wad send the Soger youth,",
  "  Whatever might betide.",
  "",
  "",
  "For the auld Gudeman o’ London court 4",
  "  She didna care a pin;",
  "But she wad send the Soger youth,",
  "  To greet his eldest son. 5",
  "",
  "",
  "Then up sprang Bess o’ Annandale,",
  "  And a deadly aith she’s ta’en,",
  "That she wad vote the Border Knight,",
  "  Though she should vote her lane.",
  "",
  "",
  "“For far-off fowls hae feathers fair,",
  "  And fools o’ change are fain;",
  "But I hae tried the Border Knight,",
  "  And I’ll try him yet again.”",
  "",
  "",
  "Says black Joan frae Crichton Peel,",
  "  A Carlin stoor and grim.",
  "“The auld Gudeman or young Gudeman,",
  "  For me may sink or swim;",
  "",
  "",
  "For fools will prate o’ right or wrang,",
  "  While knaves laugh them to scorn;",
  "But the Soger’s friends hae blawn the best,",
  "  So he shall bear the horn.”",
  "",
  "",
  "Then whisky Jean spak owre her drink,",
  "  “Ye weel ken, kimmers a’,",
  "The auld gudeman o’ London court,",
  "  His back’s been at the wa’;",
  "",
  "",
  "“And mony a friend that kiss’d his caup",
  "  Is now a fremit wight;",
  "But it’s ne’er be said o’ whisky Jean—",
  "  We’ll send the Border Knight.”",
  "",
  "",
  "Then slow raise Marjory o’ the Lochs,",
  "  And wrinkled was her brow,",
  "Her ancient weed was russet gray,",
  "  Her auld Scots bluid was true;",
  "",
  "",
  "“There’s some great folk set light by me,",
  "  I set as light by them;",
  "But I will send to London town",
  "  Wham I like best at hame.”",
  "",
  "",
  "Sae how this mighty plea may end,",
  "  Nae mortal wight can tell;",
  "God grant the King and ilka man",
  "  May look weel to himsel.",
  "",
  "",
  " Note 1. Sanquhar. [back]",
  "Note 2. Sir James Johnston of Westerhall. [back]",
  "Note 3. Captain Patrick Millar of Dalswinton. [back]",
  "Note 4. The King. [back]",
  "Note 5. The Prince of Wales. [back]",
  ""
]