module.exports = [
  "THE LADDIES by the banks o’ Nith",
  "  Wad trust his Grace 1 wi a’, Jamie;",
  "But he’ll sair them, as he sair’d the King—",
  "  Turn tail and rin awa’, Jamie.",
  "",
  "",
  "Chorus.—Up and waur them a’, Jamie,",
  "  Up and waur them a’;",
  "The Johnstones hae the guidin o’t,",
  "  Ye turncoat Whigs, awa’!",
  "",
  "",
  "The day he stude his country’s friend,",
  "  Or gied her faes a claw, Jamie,",
  "Or frae puir man a blessin wan,",
  "  That day the Duke ne’er saw, Jamie.",
  "    Up and waur them, &c.",
  "",
  "",
  "But wha is he, his country’s boast?",
  "  Like him there is na twa, Jamie;",
  "There’s no a callent tents the kye,",
  "  But kens o’ Westerha’, Jamie.",
  "    Up and waur them, &c.",
  "",
  "",
  "To end the wark, here’s Whistlebirk,",
  "  Lang may his whistle blaw, Jamie;",
  "And Maxwell true, o’ sterling blue;",
  "  And we’ll be Johnstones a’, Jamie.",
  "    Up and waur them, &c.",
  ""
]