module.exports = [
  "GANE is the day, and mirk’s the night,",
  "But we’ll ne’er stray for faut o’ light;",
  "Gude ale and bratdy’s stars and moon,",
  "And blue-red wine’s the risin’ sun.",
  "",
  "",
  "Chorus.—Then gudewife, count the lawin,",
  "The lawin, the lawin,",
  "Then gudewife, count the lawin,",
  "    And bring a coggie mair.",
  "",
  "",
  "There’s wealth and ease for gentlemen,",
  "And simple folk maun fecht and fen’;",
  "But here we’re a’ in ae accord,",
  "For ilka man that’s drunk’s a lord.",
  "            Then gudewife, &c.",
  "",
  "",
  "My coggie is a haly pool",
  "That heals the wounds o’ care and dool;",
  "And Pleasure is a wanton trout,",
  "An ye drink it a’, ye’ll find him out.",
  "            Then gudewife, &c.",
  ""
]