module.exports = [
  "FINTRY, my stay in wordly strife,",
  "Friend o’ my muse, friend o’ my life,",
  "            Are ye as idle’s I am?",
  "Come then, wi’ uncouth kintra fleg,",
  "O’er Pegasus I’ll fling my leg,",
  "            And ye shall see me try him.",
  "",
  "",
  "But where shall I go rin a ride,",
  "That I may splatter nane beside?",
  "            I wad na be uncivil:",
  "In manhood’s various paths and ways",
  "There’s aye some doytin’ body strays,",
  "            And I ride like the devil.",
  "",
  "",
  "Thus I break aff wi’ a’ my birr,",
  "And down yon dark, deep alley spur,",
  "            Where Theologics daunder:",
  "Alas! curst wi’ eternal fogs,",
  "And damn’d in everlasting bogs,",
  "            As sure’s the creed I’ll blunder!",
  "",
  "",
  "I’ll stain a band, or jaup a gown,",
  "Or rin my reckless, guilty crown",
  "            Against the haly door:",
  "Sair do I rue my luckless fate,",
  "When, as the Muse an’ Deil wad hae’t,",
  "            I rade that road before.",
  "",
  "",
  "Suppose I take a spurt, and mix",
  "Amang the wilds o’ Politics—",
  "            Electors and elected,",
  "Where dogs at Court (sad sons of bitches!)",
  "Septennially a madness touches,",
  "            Till all the land’s infected.",
  "",
  "",
  "All hail! Drumlanrig’s haughty Grace,",
  "Discarded remnant of a race",
  "            Once godlike-great in story;",
  "Thy forbears’ virtues all contrasted,",
  "The very name of Douglas blasted,",
  "            Thine that inverted glory!",
  "",
  "",
  "Hate, envy, oft the Douglas bore,",
  "But thou hast superadded more,",
  "            And sunk them in contempt;",
  "Follies and crimes have stain’d the name,",
  "But, Queensberry, thine the virgin claim,",
  "            From aught that’s good exempt!",
  "",
  "",
  "I’ll sing the zeal Drumlanrig bears,",
  "Who left the all-important cares",
  "            Of princes, and their darlings:",
  "And, bent on winning borough touns,",
  "Came shaking hands wi’ wabster-loons,",
  "            And kissing barefit carlins.",
  "",
  "",
  "Combustion thro’ our boroughs rode,",
  "Whistling his roaring pack abroad",
  "            Of mad unmuzzled lions;",
  "As Queensberry blue and buff unfurl’d,",
  "And Westerha’ and Hopetoun hurled",
  "            To every Whig defiance.",
  "",
  "",
  "But cautious Queensberry left the war,",
  "Th’ unmanner’d dust might soil his star,",
  "            Besides, he hated bleeding:",
  "But left behind him heroes bright,",
  "Heroes in C&æsarean fight,",
  "            Or Ciceronian pleading.",
  "",
  "",
  "O for a throat like huge Mons-Meg,",
  "To muster o’er each ardent Whig",
  "            Beneath Drumlanrig’s banners;",
  "Heroes and heroines commix,",
  "All in the field of politics,",
  "            To win immortal honours.",
  "",
  "",
  "M’Murdo and his lovely spouse,",
  "(Th’ enamour’d laurels kiss her brows!)",
  "            Led on the Loves and Graces:",
  "She won each gaping burgess’ heart,",
  "While he, sub rosa, played his part",
  "            Amang their wives and lasses.",
  "",
  "",
  "Craigdarroch led a light-arm’d core,",
  "Tropes, metaphors, and figures pour,",
  "            Like Hecla streaming thunder:",
  "Glenriddel, skill’d in rusty coins,",
  "Blew up each Tory’s dark designs,",
  "            And bared the treason under.",
  "",
  "",
  "In either wing two champions fought;",
  "Redoubted Staig, who set at nought",
  "            The wildest savage Tory;",
  "And Welsh who ne’er yet flinch’d his ground,",
  "High-wav’d his magnum-bonum round",
  "            With Cyclopeian fury.",
  "",
  "",
  "Miller brought up th’ artillery ranks,",
  "The many-pounders of the Banks,",
  "            Resistless desolation!",
  "While Maxwelton, that baron bold,",
  "’Mid Lawson’s port entrench’d his hold,",
  "            And threaten’d worse damnation.",
  "",
  "",
  "To these what Tory hosts oppos’d",
  "With these what Tory warriors clos’d",
  "            Surpasses my descriving;",
  "Squadrons, extended long and large,",
  "With furious speed rush to the charge,",
  "            Like furious devils driving.",
  "",
  "",
  "What verse can sing, what prose narrate,",
  "The butcher deeds of bloody Fate,",
  "            Amid this mighty tulyie!",
  "Grim Horror girn’d, pale Terror roar’d,",
  "As Murder at his thrapple shor’d,",
  "            And Hell mix’d in the brulyie.",
  "",
  "",
  "As Highland craigs by thunder cleft,",
  "When lightnings fire the stormy lift,",
  "            Hurl down with crashing rattle;",
  "As flames among a hundred woods,",
  "As headlong foam from a hundred floods,",
  "            Such is the rage of Battle.",
  "",
  "",
  "The stubborn Tories dare to die;",
  "As soon the rooted oaks would fly",
  "            Before th’ approaching fellers:",
  "The Whigs come on like Ocean’s roar,",
  "When all his wintry billows pour",
  "            Against the Buchan Bullers.",
  "",
  "",
  "Lo, from the shades of Death’s deep night,",
  "Departed Whigs enjoy the fight,",
  "            And think on former daring:",
  "The muffled murtherer of Charles",
  "The Magna Charter flag unfurls,",
  "            All deadly gules its bearing.",
  "",
  "",
  "Nor wanting ghosts of Tory fame;",
  "Bold Scrimgeour follows gallant Graham;",
  "            Auld Covenanters shiver—",
  "Forgive! forgive! much-wrong’d Montrose!",
  "Now Death and Hell engulph thy foes,",
  "            Thou liv’st on high for ever.",
  "",
  "",
  "Still o’er the field the combat burns,",
  "The Tories, Whigs, give way by turns;",
  "            But Fate the word has spoken:",
  "For woman’s wit and strength o’man,",
  "Alas! can do but what they can;",
  "            The Tory ranks are broken.",
  "",
  "",
  "O that my een were flowing burns!",
  "My voice, a lioness that mourns",
  "            Her darling cubs’ undoing!",
  "That I might greet, that I might cry,",
  "While Tories fall, while Tories fly,",
  "            And furious Whigs pursuing!",
  "",
  "",
  "What Whig but melts for good Sir James,",
  "Dear to his country, by the names,",
  "            Friend, Patron, Benefactor!",
  "Not Pulteney’s wealth can Pulteney save;",
  "And Hopetoun falls, the generous, brave;",
  "            And Stewart, bold as Hector.",
  "",
  "",
  "Thou, Pitt, shalt rue this overthrow,",
  "And Thurlow growl a curse of woe,",
  "            And Melville melt in wailing:",
  "Now Fox and Sheridan rejoice,",
  "And Burke shall sing, “O Prince, arise!",
  "            Thy power is all-prevailing!”",
  "",
  "",
  "For your poor friend, the Bard, afar",
  "He only hears and sees the war,",
  "            A cool spectator purely!",
  "So, when the storm the forest rends,",
  "The robin in the hedge descends,",
  "            And sober chirps securely.",
  "",
  "",
  "Now, for my friends’ and brethren’s sakes,",
  "And for my dear-lov’d Land o’ Cakes,",
  "            I pray with holy fire:",
  "Lord, send a rough-shod troop o’ Hell",
  "O’er a’ wad Scotland buy or sell,",
  "            To grind them in the mire!",
  ""
]