module.exports = [
  "BY yon Castle wa’, at the close of the day,",
  "I heard a man sing, tho’ his head it was grey:",
  "And as he was singing, the tears doon came,—",
  "There’ll never be peace till Jamie comes hame.",
  "",
  "",
  "The Church is in ruins, the State is in jars,",
  "Delusions, oppressions, and murderous wars,",
  "We dare na weel say’t, but we ken wha’s to blame,—",
  "There’ll never be peace till Jamie comes hame.",
  "",
  "",
  "My seven braw sons for Jamie drew sword,",
  "But now I greet round their green beds in the yerd;",
  "It brak the sweet heart o’ my faithful and dame,—",
  "There’ll never be peace till Jamie comes hame.",
  "",
  "",
  "Now life is a burden that bows me down,",
  "Sin’ I tint my bairns, and he tint his crown;",
  "But till my last moments my words are the same,—",
  "There’ll never be peace till Jamie comes hame.",
  ""
]