module.exports = [
  "YE Jacobites by name, give an ear, give an ear,",
  "Ye Jacobites by name, give an ear,",
  "  Ye Jacobites by name,",
  "  Your fautes I will proclaim,",
  "Your doctrines I maun blame, you shall hear.",
  "",
  "",
  "What is Right, and What is Wrang, by the law, by the law?",
  "What is Right and what is Wrang by the law?",
  "  What is Right, and what is Wrang?",
  "  A short sword, and a lang,",
  "A weak arm and a strang, for to draw.",
  "",
  "",
  "What makes heroic strife, famed afar, famed afar?",
  "What makes heroic strife famed afar?",
  "  What makes heroic strife?",
  "  To whet th’ assassin’s knife,",
  "Or hunt a Parent’s life, wi’ bluidy war?",
  "",
  "",
  "Then let your schemes alone, in the state, in the state,",
  "Then let your schemes alone in the state.",
  "  Then let your schemes alone,",
  "  Adore the rising sun,",
  "And leave a man undone, to his fate.",
  ""
]