module.exports = [
  "FAREWELL, thou fair day, thou green earth, and ye skies,",
  "  Now gay with the broad setting sun;",
  "Farewell, loves and friendships, ye dear tender ties,",
  "  Our race of existence is run!",
  "Thou grim King of Terrors; thou Life’s gloomy foe!",
  "  Go, frighten the coward and slave;",
  "Go, teach them to tremble, fell tyrant! but know",
  "  No terrors hast thou to the brave!",
  "",
  "",
  "Thou strik’st the dull peasant—he sinks in the dark,",
  "  Nor saves e’en the wreck of a name;",
  "Thou strik’st the young hero—a glorious mark;",
  "  He falls in the blaze of his fame!",
  "In the field of proud honour—our swords in our hands,",
  "  Our King and our country to save;",
  "While victory shines on Life’s last ebbing sands,—",
  "  O! who would not die with the brave!",
  ""
]