module.exports = [
  "WILLIE WASTLE dwalt on Tweed,",
  "  The spot they ca’d it Linkumdoddie;",
  "Willie was a wabster gude,",
  "  Could stown a clue wi’ ony body:",
  "He had a wife was dour and din,",
  "  O Tinkler Maidgie was her mither;",
  "Sic a wife as Willie had,",
  "  I wad na gie a button for her!",
  "",
  "",
  "She has an e’e, she has but ane,",
  "  The cat has twa the very colour;",
  "Five rusty teeth, forbye a stump,",
  "  A clapper tongue wad deave a miller:",
  "A whiskin beard about her mou’,",
  "  Her nose and chin they threaten ither;",
  "Sic a wife as Willie had,",
  "  I wadna gie a button for her!",
  "",
  "",
  "She’s bow-hough’d, she’s hein-shin’d,",
  "  Ae limpin leg a hand-breed shorter;",
  "She’s twisted right, she’s twisted left,",
  "  To balance fair in ilka quarter:",
  "She has a lump upon her breast,",
  "  The twin o’ that upon her shouther;",
  "Sic a wife as Willie had,",
  "  I wadna gie a button for her!",
  "",
  "",
  "Auld baudrons by the ingle sits,",
  "  An’ wi’ her loof her face a-washin;",
  "But Willie’s wife is nae sae trig,",
  "  She dights her grunzie wi’ a hushion;",
  "Her walie nieves like midden-creels,",
  "  Her face wad fyle the Logan Water;",
  "Sic a wife as Willie had,",
  "  I wadna gie a button for her!",
  ""
]