module.exports = [
  "THE BAIRNS gat out wi’ an unco shout,",
  "  The deuks dang o’er my daddie, O!",
  "The fien-ma-care, quo’ the feirrie auld wife,",
  "  He was but a paidlin’ body, O!",
  "He paidles out, and he paidles in,",
  "  An’ he paidles late and early, O!",
  "This seven lang years I hae lien by his side,",
  "  An’ he is but a fusionless carlie, O.",
  "",
  "",
  "O haud your tongue, my feirrie auld wife,",
  "  O haud your tongue, now Nansie, O:",
  "I’ve seen the day, and sae hae ye,",
  "  Ye wad na ben sae donsie, O.",
  "I’ve seen the day ye butter’d my brose,",
  "  And cuddl’d me late and early, O;",
  "But downa-do’s come o’er me now,",
  "  And oh, I find it sairly, O!",
  ""
]