module.exports = [
  "WHEN Princes and Prelates,",
  "  And hot-headed zealots,",
  "A’ Europe had set in a low, a low,",
  "  The poor man lies down,",
  "  Nor envies a crown,",
  "And comforts himself as he dow, as he dow,",
  "And comforts himself as he dow.",
  "",
  "",
  "  The black-headed eagle,",
  "  As keen as a beagle,",
  "He hunted o’er height and o’er howe,",
  "  In the braes o’ Gemappe,",
  "  He fell in a trap,",
  "E’en let him come out as he dow, dow, dow,",
  "E’en let him come out as he dow.",
  "·      ·      ·      ·      ·      ·      ·  But truce with commotions,",
  "  And new-fangled notions,",
  "A bumper, I trust you’ll allow;",
  "  Here’s George our good king,",
  "  And Charlotte his queen,",
  "And lang may they ring as they dow, dow, dow,",
  "And lang may they ring as they dow.",
  ""
]