module.exports = [
  "BRAW, braw lads on Yarrow-braes,",
  "  They rove amang the blooming heather;",
  "But Yarrow braes, nor Ettrick shaws",
  "  Can match the lads o’ Galla Water.",
  "",
  "",
  "But there is ane, a secret ane,",
  "  Aboon them a’ I loe him better;",
  "And I’ll be his, and he’ll be mine,",
  "  The bonie lad o’ Galla Water.",
  "",
  "",
  "Altho’ his daddie was nae laird,",
  "  And tho’ I hae nae meikle tocher,",
  "Yet rich in kindest, truest love,",
  "  We’ll tent our flocks by Galla Water.",
  "",
  "",
  "It ne’er was wealth, it ne’er was wealth,",
  "  That coft contentment, peace, or pleasure;",
  "The bands and bliss o’ mutual love,",
  "  O that’s the chiefest warld’s treasure.",
  ""
]