module.exports = [
  "HERE is the glen, and here the bower",
  "  All underneath the birchen shade;",
  "The village-bell has told the hour,",
  "  O what can stay my lovely maid?",
  "",
  "",
  "’Tis not Maria’s whispering call;",
  "  ’Tis but the balmy breathing gale,",
  "Mixt with some warbler’s dying fall,",
  "  The dewy star of eve to hail.",
  "",
  "",
  "It is Maria’s voice I hear;",
  "  So calls the woodlark in the grove,",
  "His little, faithful mate to cheer;",
  "  At once ’tis music and ’tis love.",
  "",
  "",
  "And art thou come! and art thou true!",
  "  O welcome dear to love and me!",
  "And let us all our vows renew,",
  "  Along the flowery banks of Cree.",
  ""
]