module.exports = [
  "NO Spartan tube, no Attic shell,",
  "  No lyre Æolian I awake;",
  "’Tis liberty’s bold note I swell,",
  "  Thy harp, Columbia, let me take!",
  "See gathering thousands, while I sing,",
  "A broken chain exulting bring,",
  "  And dash it in a tyrant’s face,",
  "And dare him to his very beard,",
  "And tell him he no more is feared—",
  "  No more the despot of Columbia’s race!",
  "A tyrant’s proudest insults brav’d,",
  "They shout—a People freed! They hail an Empire saved.",
  "",
  "",
  "Where is man’s god-like form?",
  "  Where is that brow erect and bold—",
  "  That eye that can unmov’d behold",
  "The wildest rage, the loudest storm",
  "That e’er created fury dared to raise?",
  "Avaunt! thou caitiff, servile, base,",
  "That tremblest at a despot’s nod,",
  "Yet, crouching under the iron rod,",
  "  Canst laud the hand that struck th’ insulting blow!",
  "Art thou of man’s Imperial line?",
  "Dost boast that countenance divine?",
  "  Each skulking feature answers, No!",
  "But come, ye sons of Liberty,",
  "Columbia’s offspring, brave as free,",
  "In danger’s hour still flaming in the van,",
  "Ye know, and dare maintain, the Royalty of Man!",
  "",
  "",
  "Alfred! on thy starry throne,",
  "  Surrounded by the tuneful choir,",
  "  The bards that erst have struck the patriot lyre,",
  "  And rous’d the freeborn Briton’s soul of fire,",
  "No more thy England own!",
  "Dare injured nations form the great design,",
  "  To make detested tyrants bleed?",
  "  Thy England execrates the glorious deed!",
  "  Beneath her hostile banners waving,",
  "  Every pang of honour braving,",
  "England in thunder calls, “The tyrant’s cause is mine!”",
  "That hour accurst how did the fiends rejoice",
  "And hell, thro’ all her confines, raise the exulting voice,",
  "That hour which saw the generous English name",
  "Linkt with such damned deeds of everlasting shame!",
  "",
  "",
  "Thee, Caledonia! thy wild heaths among,",
  "Fam’d for the martial deed, the heaven-taught song,",
  "  To thee I turn with swimming eyes;",
  "Where is that soul of Freedom fled?",
  "Immingled with the mighty dead,",
  "  Beneath that hallow’d turf where Wallace lies",
  "Hear it not, WALLACE! in thy bed of death.",
  "  Ye babbling winds! in silence sweep,",
  "  Disturb not ye the hero’s sleep,",
  "Nor give the coward secret breath!",
  "Is this the ancient Caledonian form,",
  "Firm as the rock, resistless as the storm?",
  "Show me that eye which shot immortal hate,",
  "  Blasting the despot’s proudest bearing;",
  "Show me that arm which, nerv’d with thundering fate,",
  "  Crush’d Usurpation’s boldest daring!—",
  "Dark-quench’d as yonder sinking star,",
  "No more that glance lightens afar;",
  "That palsied arm no more whirls on the waste of war.",
  ""
]