module.exports = [
  "BUT lately seen in gladsome green,",
  "  The woods rejoic’d the day,",
  "Thro’ gentle showers, the laughing flowers",
  "  In double pride were gay:",
  "But now our joys are fled",
  "  On winter blasts awa;",
  "Yet maiden May, in rich array,",
  "  Again shall bring them a’.",
  "",
  "",
  "But my white pow, nae kindly thowe",
  "  Shall melt the snaws of Age;",
  "My trunk of eild, but buss or beild,",
  "  Sinks in Time’s wintry rage.",
  "Oh, Age has weary days,",
  "  And nights o’ sleepless pain:",
  "Thou golden time, o’ Youthfu’ prime,",
  "  Why comes thou not again!",
  ""
]