module.exports = [
  "WHOM will you send to London town,",
  "  To Parliament and a’ that?",
  "Or wha in a’ the country round",
  "  The best deserves to fa’ that?",
  "    For a’ that, and a’ that,",
  "    Thro’ Galloway and a’ that,",
  "  Where is the Laird or belted Knight",
  "    The best deserves to fa’ that?",
  "",
  "",
  "Wha sees Kerroughtree’s open yett,",
  "  (And wha is’t never saw that?)",
  "Wha ever wi’ Kerroughtree met,",
  "  And has a doubt of a’ that?",
  "    For a’ that, and a’ that,",
  "    Here’s Heron yet for a’ that!",
  "  The independent patriot,",
  "    The honest man, and a’ that.",
  "",
  "",
  "Tho’ wit and worth, in either sex,",
  "  Saint Mary’s Isle can shaw that,",
  "Wi’ Dukes and Lords let Selkirk mix,",
  "  And weel does Selkirk fa’ that.",
  "    For a’ that, and a’ that,",
  "    Here’s Heron yet for a’ that!",
  "  The independent commoner",
  "    Shall be the man for a’ that.",
  "",
  "",
  "But why should we to Nobles jouk,",
  "  And is’t against the law, that?",
  "For why, a Lord may be a gowk,",
  "  Wi’ ribband, star and a’ that,",
  "    For a’ that, and a’ that,",
  "    Here’s Heron yet for a’ that!",
  "  A Lord may be a lousy loun,",
  "    Wi’ ribband, star and a’ that.",
  "",
  "",
  "A beardless boy comes o’er the hills,",
  "  Wi’ uncle’s purse and a’ that;",
  "But we’ll hae ane frae mang oursels,",
  "  A man we ken, and a’ that.",
  "    For a’ that, and a’ that,",
  "    Here’s Heron yet for a’ that!",
  "  For we’re not to be bought and sold,",
  "    Like naigs, and nowt, and a’ that.",
  "",
  "",
  "Then let us drink—The Stewartry,",
  "  Kerroughtree’s laird, and a’ that,",
  "Our representative to be,",
  "  For weel he’s worthy a’ that.",
  "    For a’ that, and a’ that,",
  "    Here’s Heron yet for a’ that!",
  "A House of Commons such as he,",
  "  They wad be blest that saw that.",
  ""
]