module.exports = [
  "’TWAS in the seventeen hunder year",
  "  O’ grace, and ninety-five,",
  "That year I was the wae’est man",
  "  Of ony man alive.",
  "",
  "",
  "In March the three-an’-twentieth morn,",
  "  The sun raise clear an’ bright;",
  "But oh! I was a waefu’ man,",
  "  Ere to-fa’ o’ the night.",
  "",
  "",
  "Yerl Galloway lang did rule this land,",
  "  Wi’ equal right and fame,",
  "And thereto was his kinsmen join’d,",
  "  The Murray’s noble name.",
  "",
  "",
  "Yerl Galloway’s man o’ men was I,",
  "  And chief o’ Broughton’s host;",
  "So twa blind beggars, on a string,",
  "  The faithfu’ tyke will trust.",
  "",
  "",
  "But now Yerl Galloway’s sceptre’s broke,",
  "  And Broughton’s wi’ the slain,",
  "And I my ancient craft may try,",
  "  Sin’ honesty is gane.",
  "",
  "",
  "’Twas by the banks o’ bonie Dee,",
  "  Beside Kirkcudbright’s towers,",
  "The Stewart and the Murray there,",
  "  Did muster a’ their powers.",
  "",
  "",
  "Then Murray on the auld grey yaud,",
  "  Wi’ winged spurs did ride,",
  "That auld grey yaud a’ Nidsdale rade,",
  "  He staw upon Nidside.",
  "",
  "",
  "And there had na been the Yerl himsel,",
  "  O there had been nae play;",
  "But Garlies was to London gane,",
  "  And sae the kye might stray.",
  "",
  "",
  "And there was Balmaghie, I ween,",
  "  In front rank he wad shine;",
  "But Balmaghie had better been",
  "  Drinkin’ Madeira wine.",
  "",
  "",
  "And frae Glenkens cam to our aid",
  "  A chief o’ doughty deed;",
  "In case that worth should wanted be,",
  "  O’ Kenmure we had need.",
  "",
  "",
  "And by our banners march’d Muirhead,",
  "  And Buittle was na slack;",
  "Whase haly priesthood nane could stain,",
  "  For wha could dye the black?",
  "",
  "",
  "And there was grave squire Cardoness,",
  "  Look’d on till a’ was done;",
  "Sae in the tower o’ Cardoness",
  "  A howlet sits at noon.",
  "",
  "",
  "And there led I the Bushby clan,",
  "  My gamesome billie, Will,",
  "And my son Maitland, wise as brave,",
  "  My footsteps follow’d still.",
  "",
  "",
  "The Douglas and the Heron’s name,",
  "  We set nought to their score;",
  "The Douglas and the Heron’s name,",
  "  Had felt our weight before.",
  "",
  "",
  "But Douglasses o’ weight had we,",
  "  The pair o’ lusty lairds,",
  "For building cot-houses sae fam’d,",
  "  And christenin’ kail-yards.",
  "",
  "",
  "And there Redcastle drew his sword,",
  "  That ne’er was stain’d wi’ gore,",
  "Save on a wand’rer lame and blind,",
  "  To drive him frae his door.",
  "",
  "",
  "And last cam creepin’ Collieston,",
  "  Was mair in fear than wrath;",
  "Ae knave was constant in his mind—",
  "  To keep that knave frae scaith.",
  ""
]