module.exports = [
  "O THOU, who in the heavens does dwell,",
  "Who, as it pleases best Thysel’,",
  "Sends ane to heaven an’ ten to hell,",
  "                A’ for Thy glory,",
  "And no for ony gude or ill",
  "                They’ve done afore Thee!",
  "",
  "",
  "I bless and praise Thy matchless might,",
  "When thousands Thou hast left in night,",
  "That I am here afore Thy sight,",
  "                For gifts an’ grace",
  "A burning and a shining light",
  "                To a’ this place.",
  "",
  "",
  "What was I, or my generation,",
  "That I should get sic exaltation,",
  "I wha deserve most just damnation",
  "                For broken laws,",
  "Five thousand years ere my creation,",
  "                Thro’ Adam’s cause?",
  "",
  "",
  "When frae my mither’s womb I fell,",
  "Thou might hae plunged me in hell,",
  "To gnash my gums, to weep and wail,",
  "                In burnin lakes,",
  "Where damned devils roar and yell,",
  "                Chain’d to their stakes.",
  "",
  "",
  "Yet I am here a chosen sample,",
  "To show thy grace is great and ample;",
  "I’m here a pillar o’ Thy temple,",
  "                Strong as a rock,",
  "A guide, a buckler, and example,",
  "                To a’ Thy flock.",
  "",
  "",
  "O L—d, Thou kens what zeal I bear,",
  "When drinkers drink, an’ swearers swear,",
  "An’ singin there, an’ dancin here,",
  "                Wi’ great and sma’;",
  "For I am keepit by Thy fear",
  "                Free frae them a’.",
  "",
  "",
  "But yet, O L—d! confess I must,",
  "At times I’m fash’d wi’ fleshly lust:",
  "An’ sometimes, too, in wardly trust,",
  "                Vile self gets in:",
  "But Thou remembers we are dust,",
  "                Defil’d wi’ sin.",
  "",
  "",
  "O L—d! yestreen, Thou kens, wi’ Meg—",
  "Thy pardon I sincerely beg,",
  "O! may’t ne’er be a livin plague",
  "                To my dishonour,",
  "An’ I’ll ne’er lift a lawless leg",
  "                Again upon her.",
  "",
  "",
  "Besides, I farther maun allow,",
  "Wi’ Leezie’s lass, three times I trow—",
  "But L—d, that Friday I was fou,",
  "                When I cam near her;",
  "Or else, Thou kens, Thy servant true",
  "                Wad never steer her.",
  "",
  "",
  "Maybe Thou lets this fleshly thorn",
  "Buffet Thy servant e’en and morn,",
  "Lest he owre proud and high shou’d turn,",
  "                That he’s sae gifted:",
  "If sae, Thy han’ maun e’en be borne,",
  "                Until Thou lift it.",
  "",
  "",
  "L—d, bless Thy chosen in this place,",
  "For here Thou hast a chosen race:",
  "But G—d confound their stubborn face,",
  "                An’ blast their name,",
  "Wha bring Thy elders to disgrace",
  "                An’ public shame.",
  "",
  "",
  "L—d, mind Gaw’n Hamilton’s deserts;",
  "He drinks, an’ swears, an’ plays at cartes,",
  "Yet has sae mony takin arts,",
  "                Wi’ great and sma’,",
  "Frae G—d’s ain priest the people’s hearts",
  "                He steals awa.",
  "",
  "",
  "An’ when we chasten’d him therefor,",
  "Thou kens how he bred sic a splore,",
  "An’ set the warld in a roar",
  "                O’ laughing at us;—",
  "Curse Thou his basket and his store,",
  "                Kail an’ potatoes.",
  "",
  "",
  "L—d, hear my earnest cry and pray’r,",
  "Against that Presbyt’ry o’ Ayr;",
  "Thy strong right hand, L—d, make it bare",
  "                Upo’ their heads;",
  "L—d visit them, an’ dinna spare,",
  "                For their misdeeds.",
  "",
  "",
  "O L—d, my G—d! that glib-tongu’d Aiken,",
  "My vera heart and flesh are quakin,",
  "To think how we stood sweatin’, shakin,",
  "                An’ p—’d wi’ dread,",
  "While he, wi’ hingin lip an’ snakin,",
  "                Held up his head.",
  "",
  "",
  "L—d, in Thy day o’ vengeance try him,",
  "L—d, visit them wha did employ him,",
  "And pass not in Thy mercy by ’em,",
  "                Nor hear their pray’r,",
  "But for Thy people’s sake, destroy ’em,",
  "                An’ dinna spare.",
  "",
  "",
  "But, L—d, remember me an’ mine",
  "Wi’ mercies temp’ral an’ divine,",
  "That I for grace an’ gear may shine,",
  "                Excell’d by nane,",
  "And a’ the glory shall be thine,",
  "                Amen, Amen!",
  ""
]