module.exports = [
  "SOME books are lies frae end to end,",
  "And some great lies were never penn’d:",
  "Ev’n ministers they hae been kenn’d,",
  "                In holy rapture,",
  "A rousing whid at times to vend,",
  "                And nail’t wi’ Scripture.",
  "",
  "",
  "But this that I am gaun to tell,",
  "Which lately on a night befell,",
  "Is just as true’s the Deil’s in hell",
  "                Or Dublin city:",
  "That e’er he nearer comes oursel’",
  "                ’S a muckle pity.",
  "",
  "",
  "The clachan yill had made me canty,",
  "I was na fou, but just had plenty;",
  "I stacher’d whiles, but yet too tent aye",
  "                To free the ditches;",
  "An’ hillocks, stanes, an’ bushes, kenn’d eye",
  "                Frae ghaists an’ witches.",
  "",
  "",
  "The rising moon began to glowre",
  "The distant Cumnock hills out-owre:",
  "To count her horns, wi’ a my pow’r,",
  "                I set mysel’;",
  "But whether she had three or four,",
  "                I cou’d na tell.",
  "",
  "",
  "I was come round about the hill,",
  "An’ todlin down on Willie’s mill,",
  "Setting my staff wi’ a’ my skill,",
  "                To keep me sicker;",
  "Tho’ leeward whiles, against my will,",
  "                I took a bicker.",
  "",
  "",
  "I there wi’ Something did forgather,",
  "That pat me in an eerie swither;",
  "An’ awfu’ scythe, out-owre ae shouther,",
  "                Clear-dangling, hang;",
  "A three-tae’d leister on the ither",
  "                Lay, large an’ lang.",
  "",
  "",
  "Its stature seem’d lang Scotch ells twa,",
  "The queerest shape that e’er I saw,",
  "For fient a wame it had ava;",
  "                And then its shanks,",
  "They were as thin, as sharp an’ sma’",
  "                As cheeks o’ branks.",
  "",
  "",
  "“Guid-een,” quo’ I; “Friend! hae ye been mawin,",
  "When ither folk are busy sawin!” 1",
  "I seem’d to make a kind o’ stan’",
  "                But naething spak;",
  "At length, says I, “Friend! whare ye gaun?",
  "                Will ye go back?”",
  "",
  "",
  "It spak right howe,—“My name is Death,",
  "But be na fley’d.”—Quoth I, “Guid faith,",
  "Ye’re maybe come to stap my breath;",
  "                But tent me, billie;",
  "I red ye weel, tak care o’ skaith",
  "                See, there’s a gully!”",
  "",
  "",
  "“Gudeman,” quo’ he, “put up your whittle,",
  "I’m no designed to try its mettle;",
  "But if I did, I wad be kittle",
  "                To be mislear’d;",
  "I wad na mind it, no that spittle",
  "                Out-owre my beard.”",
  "",
  "",
  "“Weel, weel!” says I, “a bargain be’t;",
  "Come, gie’s your hand, an’ sae we’re gree’t;",
  "We’ll ease our shanks an tak a seat—",
  "                Come, gie’s your news;",
  "This while ye hae been mony a gate,",
  "                At mony a house.” 2",
  "",
  "",
  "“Ay, ay!” quo’ he, an’ shook his head,",
  "“It’s e’en a lang, lang time indeed",
  "Sin’ I began to nick the thread,",
  "                An’ choke the breath:",
  "Folk maun do something for their bread,",
  "                An’ sae maun Death.",
  "",
  "",
  "“Sax thousand years are near-hand fled",
  "Sin’ I was to the butching bred,",
  "An’ mony a scheme in vain’s been laid,",
  "                To stap or scar me;",
  "Till ane Hornbook’s 3 ta’en up the trade,",
  "                And faith! he’ll waur me.",
  "",
  "",
  "“Ye ken Hornbook i’ the clachan,",
  "Deil mak his king’s-hood in spleuchan!",
  "He’s grown sae weel acquaint wi’ Buchan 4",
  "                And ither chaps,",
  "The weans haud out their fingers laughin,",
  "                An’ pouk my hips.",
  "",
  "",
  "“See, here’s a scythe, an’ there’s dart,",
  "They hae pierc’d mony a gallant heart;",
  "But Doctor Hornbook, wi’ his art",
  "                An’ cursed skill,",
  "Has made them baith no worth a f—t,",
  "                D—n’d haet they’ll kill!",
  "",
  "",
  "“’Twas but yestreen, nae farther gane,",
  "I threw a noble throw at ane;",
  "Wi’ less, I’m sure, I’ve hundreds slain;",
  "But deil-ma-care,",
  "It just play’d dirl on the bane,",
  "But did nae mair.",
  "",
  "",
  "“Hornbook was by, wi’ ready art,",
  "An’ had sae fortify’d the part,",
  "That when I looked to my dart,",
  "                It was sae blunt,",
  "Fient haet o’t wad hae pierc’d the heart",
  "                Of a kail-runt.",
  "",
  "",
  "“I drew my scythe in sic a fury,",
  "I near-hand cowpit wi’ my hurry,",
  "But yet the bauld Apothecary",
  "                Withstood the shock;",
  "I might as weel hae tried a quarry",
  "                O’ hard whin rock.",
  "",
  "",
  "“Ev’n them he canna get attended,",
  "Altho’ their face he ne’er had kend it,",
  "Just —— in a kail-blade, an’ sent it,",
  "                As soon’s he smells ’t,",
  "Baith their disease, and what will mend it,",
  "                At once he tells ’t.",
  "",
  "",
  "“And then, a’ doctor’s saws an’ whittles,",
  "Of a’ dimensions, shapes, an’ mettles,",
  "A’ kind o’ boxes, mugs, an’ bottles,",
  "                He’s sure to hae;",
  "Their Latin names as fast he rattles",
  "                As A B C.",
  "",
  "",
  "“Calces o’ fossils, earths, and trees;",
  "True sal-marinum o’ the seas;",
  "The farina of beans an’ pease,",
  "                He has’t in plenty;",
  "Aqua-fontis, what you please,",
  "                He can content ye.",
  "",
  "",
  "“Forbye some new, uncommon weapons,",
  "Urinus spiritus of capons;",
  "Or mite-horn shavings, filings, scrapings,",
  "                Distill’d per se;",
  "Sal-alkali o’ midge-tail clippings,",
  "                And mony mae.”",
  "",
  "",
  "“Waes me for Johnie Ged’s-Hole 5 now,”",
  "Quoth I, “if that thae news be true!",
  "His braw calf-ward whare gowans grew,",
  "                Sae white and bonie,",
  "Nae doubt they’ll rive it wi’ the plew;",
  "                They’ll ruin Johnie!”",
  "",
  "",
  "The creature grain’d an eldritch laugh,",
  "And says “Ye needna yoke the pleugh,",
  "Kirkyards will soon be till’d eneugh,",
  "                Tak ye nae fear:",
  "They’ll be trench’d wi’ mony a sheugh,",
  "                In twa-three year.",
  "",
  "",
  "“Whare I kill’d ane, a fair strae-death,",
  "By loss o’ blood or want of breath",
  "This night I’m free to tak my aith,",
  "                That Hornbook’s skill",
  "Has clad a score i’ their last claith,",
  "                By drap an’ pill.",
  "",
  "",
  "“An honest wabster to his trade,",
  "Whase wife’s twa nieves were scarce weel-bred",
  "Gat tippence-worth to mend her head,",
  "                When it was sair;",
  "The wife slade cannie to her bed,",
  "                But ne’er spak mair.",
  "",
  "",
  "“A country laird had ta’en the batts,",
  "Or some curmurring in his guts,",
  "His only son for Hornbook sets,",
  "                An’ pays him well:",
  "The lad, for twa guid gimmer-pets,",
  "                Was laird himsel’.",
  "",
  "",
  "“A bonie lass—ye kend her name—",
  "Some ill-brewn drink had hov’d her wame;",
  "She trusts hersel’, to hide the shame,",
  "                In Hornbook’s care;",
  "Horn sent her aff to her lang hame,",
  "                To hide it there.",
  "",
  "",
  "“That’s just a swatch o’ Hornbook’s way;",
  "Thus goes he on from day to day,",
  "Thus does he poison, kill, an’ slay,",
  "                An’s weel paid for’t;",
  "Yet stops me o’ my lawfu’ prey,",
  "                Wi’ his d—n’d dirt:",
  "",
  "",
  "“But, hark! I’ll tell you of a plot,",
  "Tho’ dinna ye be speakin o’t;",
  "I’ll nail the self-conceited sot,",
  "                As dead’s a herrin;",
  "Neist time we meet, I’ll wad a groat,",
  "                He gets his fairin!”",
  "",
  "",
  "But just as he began to tell,",
  "The auld kirk-hammer strak the bell",
  "Some wee short hour ayont the twal’,",
  "                Which rais’d us baith:",
  "I took the way that pleas’d mysel’,",
  "                And sae did Death.",
  "",
  "",
  " Note 1. This recontre happened in seed-time, 1785.—R. B. [back]",
  "Note 2. An epidemical fever was then raging in that country.—R. B. [back]",
  "Note 3. This gentleman, Dr. Hornbook, is professionally a brother of the sovereign Order of the Ferula; but, by intuition and inspiration, is at once an apothecary, surgeon, and physician.—R. B. [back]",
  "Note 4. Burchan’s Domestic Medicine.—R. B. [back]",
  "Note 5. The grave-digger.—R. B. [back]",
  ""
]