module.exports = [
  "Soule of my soule! my Joy, my crown, my friend!",
  "A name which all the rest doth comprehend;",
  "How happy are we now, whose sols are grown,",
  "By an incomparable mixture, One:",
  "Whose well acquainted minds are not as neare",
  "As Love, or vows, or secrets can endeare.",
  "I have no thought but what's to thee reveal'd,",
  "Nor thou desire that is from me conceal'd.",
  "Thy heart locks up my secrets richly set,",
  "And my breast is thy private cabinet.",
  "Thou shedst no teare but what but what my moisture lent,",
  "And if I sigh, it is thy breath is spent.",
  "United thus, what horrour can appeare",
  "Worthy our sorrow, anger, or our feare?",
  "Let the dull world alone to talk and fight",
  "And with their vast ambitions nature fright;",
  "Let them despise so innocent a flame,",
  "While Envy, pride, and faction play their game:",
  "But we by Love sublim'd so high shall rise,",
  "To pitty Kings, and Conquerours despise,",
  "Since we that sacred union have engrost,",
  "Which they and all the sullen world have lost.",
  ""
]