module.exports = [
  "UPON that night, when fairies light",
  "  On Cassilis Downans 2 dance,",
  "Or owre the lays, in splendid blaze,",
  "  On sprightly coursers prance;",
  "Or for Colean the rout is ta’en,",
  "  Beneath the moon’s pale beams;",
  "There, up the Cove, 3 to stray an’ rove,",
  "  Amang the rocks and streams",
  "            To sport that night;",
  "",
  "",
  "Amang the bonie winding banks,",
  "  Where Doon rins, wimplin, clear;",
  "Where Bruce 4 ance rul’d the martial ranks,",
  "  An’ shook his Carrick spear;",
  "Some merry, friendly, countra-folks",
  "  Together did convene,",
  "To burn their nits, an’ pou their stocks,",
  "  An’ haud their Halloween",
  "            Fu’ blythe that night.",
  "",
  "",
  "The lasses feat, an’ cleanly neat,",
  "  Mair braw than when they’re fine;",
  "Their faces blythe, fu’ sweetly kythe,",
  "  Hearts leal, an’ warm, an’ kin’:",
  "The lads sae trig, wi’ wooer-babs",
  "  Weel-knotted on their garten;",
  "Some unco blate, an’ some wi’ gabs",
  "  Gar lasses’ hearts gang startin",
  "            Whiles fast at night.",
  "",
  "",
  "Then, first an’ foremost, thro’ the kail,",
  "  Their stocks 5 maun a’ be sought ance;",
  "They steek their een, and grape an’ wale",
  "  For muckle anes, an’ straught anes.",
  "Poor hav’rel Will fell aff the drift,",
  "  An’ wandered thro’ the bow-kail,",
  "An’ pou’t for want o’ better shift",
  "  A runt was like a sow-tail",
  "            Sae bow’t that night.",
  "",
  "",
  "Then, straught or crooked, yird or nane,",
  "  They roar an’ cry a’ throu’ther;",
  "The vera wee-things, toddlin, rin,",
  "  Wi’ stocks out owre their shouther:",
  "An’ gif the custock’s sweet or sour,",
  "  Wi’ joctelegs they taste them;",
  "Syne coziely, aboon the door,",
  "  Wi’ cannie care, they’ve plac’d them",
  "            To lie that night.",
  "",
  "",
  "The lassies staw frae ’mang them a’,",
  "  To pou their stalks o’ corn; 6",
  "But Rab slips out, an’ jinks about,",
  "  Behint the muckle thorn:",
  "He grippit Nelly hard and fast:",
  "  Loud skirl’d a’ the lasses;",
  "But her tap-pickle maist was lost,",
  "  Whan kiutlin in the fause-house 7",
  "            Wi’ him that night.",
  "",
  "",
  "The auld guid-wife’s weel-hoordit nits 8",
  "  Are round an’ round dividend,",
  "An’ mony lads an’ lasses’ fates",
  "  Are there that night decided:",
  "Some kindle couthie side by side,",
  "  And burn thegither trimly;",
  "Some start awa wi’ saucy pride,",
  "  An’ jump out owre the chimlie",
  "            Fu’ high that night.",
  "",
  "",
  "Jean slips in twa, wi’ tentie e’e;",
  "  Wha ’twas, she wadna tell;",
  "But this is Jock, an’ this is me,",
  "  She says in to hersel’:",
  "He bleez’d owre her, an’ she owre him,",
  "  As they wad never mair part:",
  "Till fuff! he started up the lum,",
  "  An’ Jean had e’en a sair heart",
  "            To see’t that night.",
  "",
  "",
  "Poor Willie, wi’ his bow-kail runt,",
  "  Was brunt wi’ primsie Mallie;",
  "An’ Mary, nae doubt, took the drunt,",
  "  To be compar’d to Willie:",
  "Mall’s nit lap out, wi’ pridefu’ fling,",
  "  An’ her ain fit, it brunt it;",
  "While Willie lap, and swore by jing,",
  "  ’Twas just the way he wanted",
  "            To be that night.",
  "",
  "",
  "Nell had the fause-house in her min’,",
  "  She pits hersel an’ Rob in;",
  "In loving bleeze they sweetly join,",
  "  Till white in ase they’re sobbin:",
  "Nell’s heart was dancin at the view;",
  "  She whisper’d Rob to leuk for’t:",
  "Rob, stownlins, prie’d her bonie mou’,",
  "  Fu’ cozie in the neuk for’t,",
  "            Unseen that night.",
  "",
  "",
  "But Merran sat behint their backs,",
  "  Her thoughts on Andrew Bell:",
  "She lea’es them gashin at their cracks,",
  "  An’ slips out-by hersel’;",
  "She thro’ the yard the nearest taks,",
  "  An’ for the kiln she goes then,",
  "An’ darklins grapit for the bauks,",
  "  And in the blue-clue 9 throws then,",
  "            Right fear’t that night.",
  "",
  "",
  "An’ ay she win’t, an’ ay she swat—",
  "  I wat she made nae jaukin;",
  "Till something held within the pat,",
  "  Good L—d! but she was quaukin!",
  "But whether ’twas the deil himsel,",
  "  Or whether ’twas a bauk-en’,",
  "Or whether it was Andrew Bell,",
  "  She did na wait on talkin",
  "            To spier that night.",
  "",
  "",
  "Wee Jenny to her graunie says,",
  "  “Will ye go wi’ me, graunie?",
  "I’ll eat the apple at the glass, 10",
  "  I gat frae uncle Johnie:”",
  "She fuff’t her pipe wi’ sic a lunt,",
  "  In wrath she was sae vap’rin,",
  "She notic’t na an aizle brunt",
  "  Her braw, new, worset apron",
  "            Out thro’ that night.",
  "",
  "",
  "“Ye little skelpie-limmer’s face!",
  "  I daur you try sic sportin,",
  "As seek the foul thief ony place,",
  "  For him to spae your fortune:",
  "Nae doubt but ye may get a sight!",
  "  Great cause ye hae to fear it;",
  "For mony a ane has gotten a fright,",
  "  An’ liv’d an’ died deleerit,",
  "            On sic a night.",
  "",
  "",
  "“Ae hairst afore the Sherra-moor,",
  "  I mind’t as weel’s yestreen—",
  "I was a gilpey then, I’m sure",
  "  I was na past fyfteen:",
  "The simmer had been cauld an’ wat,",
  "  An’ stuff was unco green;",
  "An’ eye a rantin kirn we gat,",
  "  An’ just on Halloween",
  "            It fell that night.",
  "",
  "",
  "“Our stibble-rig was Rab M’Graen,",
  "  A clever, sturdy fallow;",
  "His sin gat Eppie Sim wi’ wean,",
  "  That lived in Achmacalla:",
  "He gat hemp-seed, 11 I mind it weel,",
  "  An’he made unco light o’t;",
  "But mony a day was by himsel’,",
  "  He was sae sairly frighted",
  "            That vera night.”",
  "",
  "",
  "Then up gat fechtin Jamie Fleck,",
  "  An’ he swoor by his conscience,",
  "That he could saw hemp-seed a peck;",
  "  For it was a’ but nonsense:",
  "The auld guidman raught down the pock,",
  "  An’ out a handfu’ gied him;",
  "Syne bad him slip frae’ mang the folk,",
  "  Sometime when nae ane see’d him,",
  "            An’ try’t that night.",
  "",
  "",
  "He marches thro’ amang the stacks,",
  "  Tho’ he was something sturtin;",
  "The graip he for a harrow taks,",
  "  An’ haurls at his curpin:",
  "And ev’ry now an’ then, he says,",
  "  “Hemp-seed I saw thee,",
  "An’ her that is to be my lass",
  "  Come after me, an’ draw thee",
  "            As fast this night.”",
  "",
  "",
  "He wistl’d up Lord Lennox’ March",
  "  To keep his courage cherry;",
  "Altho’ his hair began to arch,",
  "  He was sae fley’d an’ eerie:",
  "Till presently he hears a squeak,",
  "  An’ then a grane an’ gruntle;",
  "He by his shouther gae a keek,",
  "  An’ tumbled wi’ a wintle",
  "            Out-owre that night.",
  "",
  "",
  "He roar’d a horrid murder-shout,",
  "  In dreadfu’ desperation!",
  "An’ young an’ auld come rinnin out,",
  "  An’ hear the sad narration:",
  "He swoor ’twas hilchin Jean M’Craw,",
  "  Or crouchie Merran Humphie—",
  "Till stop! she trotted thro’ them a’;",
  "  And wha was it but grumphie",
  "            Asteer that night!",
  "",
  "",
  "Meg fain wad to the barn gaen,",
  "  To winn three wechts o’ naething; 12",
  "But for to meet the deil her lane,",
  "  She pat but little faith in:",
  "She gies the herd a pickle nits,",
  "  An’ twa red cheekit apples,",
  "To watch, while for the barn she sets,",
  "  In hopes to see Tam Kipples",
  "            That vera night.",
  "",
  "",
  "She turns the key wi’ cannie thraw,",
  "  An’owre the threshold ventures;",
  "But first on Sawnie gies a ca’,",
  "  Syne baudly in she enters:",
  "A ratton rattl’d up the wa’,",
  "  An’ she cry’d Lord preserve her!",
  "An’ ran thro’ midden-hole an’ a’,",
  "  An’ pray’d wi’ zeal and fervour,",
  "            Fu’ fast that night.",
  "",
  "",
  "They hoy’t out Will, wi’ sair advice;",
  "  They hecht him some fine braw ane;",
  "It chanc’d the stack he faddom’t thrice 13",
  "  Was timmer-propt for thrawin:",
  "He taks a swirlie auld moss-oak",
  "  For some black, grousome carlin;",
  "An’ loot a winze, an’ drew a stroke,",
  "  Till skin in blypes cam haurlin",
  "            Aff’s nieves that night.",
  "",
  "",
  "A wanton widow Leezie was,",
  "  As cantie as a kittlen;",
  "But och! that night, amang the shaws,",
  "  She gat a fearfu’ settlin!",
  "She thro’ the whins, an’ by the cairn,",
  "  An’ owre the hill gaed scrievin;",
  "Whare three lairds’ lan’s met at a burn, 14",
  "  To dip her left sark-sleeve in,",
  "            Was bent that night.",
  "",
  "",
  "Whiles owre a linn the burnie plays,",
  "  As thro’ the glen it wimpl’t;",
  "Whiles round a rocky scar it strays,",
  "  Whiles in a wiel it dimpl’t;",
  "Whiles glitter’d to the nightly rays,",
  "  Wi’ bickerin’, dancin’ dazzle;",
  "Whiles cookit undeneath the braes,",
  "  Below the spreading hazel",
  "            Unseen that night.",
  "",
  "",
  "Amang the brachens, on the brae,",
  "  Between her an’ the moon,",
  "The deil, or else an outler quey,",
  "  Gat up an’ ga’e a croon:",
  "Poor Leezie’s heart maist lap the hool;",
  "  Near lav’rock-height she jumpit,",
  "But mist a fit, an’ in the pool",
  "  Out-owre the lugs she plumpit,",
  "            Wi’ a plunge that night.",
  "",
  "",
  "In order, on the clean hearth-stane,",
  "  The luggies 15 three are ranged;",
  "An’ ev’ry time great care is ta’en",
  "  To see them duly changed:",
  "Auld uncle John, wha wedlock’s joys",
  "  Sin’ Mar’s-year did desire,",
  "Because he gat the toom dish thrice,",
  "  He heav’d them on the fire",
  "            In wrath that night.",
  "",
  "",
  "Wi’ merry sangs, an’ friendly cracks,",
  "  I wat they did na weary;",
  "And unco tales, an’ funnie jokes—",
  "  Their sports were cheap an’ cheery:",
  "Till butter’d sowens, 16 wi’ fragrant lunt,",
  "  Set a’ their gabs a-steerin;",
  "Syne, wi’ a social glass o’ strunt,",
  "  They parted aff careerin",
  "            Fu’ blythe that night.",
  "",
  "",
  " Note 1. Is thought to be a night when witches, devils, and other mischief-making beings are abroad on their baneful midnight errands; particularly those aerial people, the fairies, are said on that night to hold a grand anniversary.—R. B. [back]",
  "Note 2. Certain little, romantic, rocky, green hills, in the neighbourhood of the ancient seat of the Earls of Cassilis.—R.B. [back]",
  "Note 3. A noted cavern near Colean house, called the Cove of Colean; which, as well as Cassilis Downans, is famed, in country story, for being a favorite haunt of fairies.—R. B. [back]",
  "Note 4. The famous family of that name, the ancestors of Robert, the great deliverer of his country, were Earls of Carrick.—R. B. [back]",
  "Note 5. The first ceremony of Halloween is pulling each a “stock,” or plant of kail. They must go out, hand in hand, with eyes shut, and pull the first they meet with: its being big or little, straight or crooked, is prophetic of the size and shape of the grand object of all their spells-the husband or wife. If any “yird,” or earth, stick to the root, that is “tocher,” or fortune; and the taste of the “custock,” that is, the heart of the stem, is indicative of the natural temper and disposition. Lastly, the stems, or, to give them their ordinary appellation, the “runts,” are placed somewhere above the head of the door; and the Christian names of the people whom chance brings into the house are, according to the priority of placing the “runts,” the names in question.—R. B. [back]",
  "Note 6. They go to the barnyard, and pull each, at three different times, a stalk of oats. If the third stalk wants the “top-pickle,” that is, the grain at the top of the stalk, the party in question will come to the marriage-bed anything but a maid.—R. B. [back]",
  "Note 7. When the corn is in a doubtful state, by being too green or wet, the stack-builder, by means of old timber, etc., makes a large apartment in his stack, with an opening in the side which is fairest exposed to the wind: this he calls a “fause-house.”—R. B. [back]",
  "Note 8. Burning the nuts is a favorite charm. They name the lad and lass to each particular nut, as they lay them in the fire; and according as they burn quietly together, or start from beside one another, the course and issue of the courtship will be.—R. B. [back]",
  "Note 9. Whoever would, with success, try this spell, must strictly observe these directions: Steal out, all alone, to the kiln, and darkling, throw into the “pot” a clue of blue yarn; wind it in a new clue off the old one; and, toward the latter end, something will hold the thread: demand, “Wha hauds?” i. e., who holds? and answer will be returned from the kiln-pot, by naming the Christian and surname of your future spouse.—R. B. [back]",
  "Note 10. Take a candle and go alone to a looking-glass; eat an apple before it, and some traditions say you should comb your hair all the time; the face of your conjungal companion, to be, will be seen in the glass, as if peeping over your shoulder.—R. B. [back]",
  "Note 11. Steal out, unperceived, and sow a handful of hemp-seed, harrowing it with anything you can conveniently draw after you. Repeat now and then: “Hemp-seed, I saw thee, hemp-seed, I saw thee; and him (or her) that is to be my true love, come after me and pou thee.” Look over your left shoulder, and you will see the appearance of the person invoked, in the attitude of pulling hemp. Some traditions say, “Come after me and shaw thee,” that is, show thyself; in which case, it simply appears. Others omit the harrowing, and say: “Come after me and harrow thee.”—R. B. [back]",
  "Note 12. This charm must likewise be performed unperceived and alone. You go to the barn, and open both doors, taking them off the hinges, if possible; for there is danger that the being about to appear may shut the doors, and do you some mischief. Then take that instrument used in winnowing the corn, which in our country dialect we call a “wecht,” and go through all the attitudes of letting down corn against the wind. Repeat it three times, and the third time an apparition will pass through the barn, in at the windy door and out at the other, having both the figure in question, and the appearance or retinue, marking the employment or station in life.—R. B. [back]",
  "Note 13. Take an opportunity of going unnoticed to a “bear-stack,” and fathom it three times round. The last fathom of the last time you will catch in your arms the appearance of your future conjugal yoke-fellow.—R. B. [back]",
  "Note 14. Take an opportunity of going unnoticed to a “bear-stack,” and fathom it three times round. The last fathom of the last time you will catch in your arms the appearance of your future conjugal yoke-fellow.—R. B. [back]",
  "Note 15. Take three dishes, put clean water in one, foul water in another, and leave the third empty; blindfold a person and lead him to the hearth where the dishes are ranged; he (or she) dips the left hand; if by chance in the clean water, the future (husband or) wife will come to the bar of matrimony a maid; if in the foul, a widow; if in the empty dish, it foretells, with equal certainty, no marriage at all. It is repeated three times, and every time the arrangement of the dishes is altered.—R. B. [back]",
  "Note 16. Sowens, with butter instead of milk to them, is always the Halloween Supper.—R. B. [back]",
  ""
]