module.exports = [
  "GUDE pity me, because I’m little!",
  "For though I am an elf o’ mettle,",
  "An’ can, like ony wabster’s shuttle,",
  "                Jink there or here,",
  "Yet, scarce as lang’s a gude kail-whittle,",
  "                I’m unco queer.",
  "",
  "",
  "An’ now Thou kens our waefu’ case;",
  "For Geordie’s jurr we’re in disgrace,",
  "Because we stang’d her through the place,",
  "                An’ hurt her spleuchan;",
  "For whilk we daurna show our face",
  "                Within the clachan.",
  "",
  "",
  "An’ now we’re dern’d in dens and hollows,",
  "And hunted, as was William Wallace,",
  "Wi’ constables-thae blackguard fallows,",
  "                An’ sodgers baith;",
  "But Gude preserve us frae the gallows,",
  "                That shamefu’ death!",
  "",
  "",
  "Auld grim black-bearded Geordie’s sel’—",
  "O shake him owre the mouth o’ hell!",
  "There let him hing, an’ roar, an’ yell",
  "                Wi’ hideous din,",
  "And if he offers to rebel,",
  "                Then heave him in.",
  "",
  "",
  "When Death comes in wi’ glimmerin blink,",
  "An’ tips auld drucken Nanse the wink,",
  "May Sautan gie her doup a clink",
  "                Within his yett,",
  "An’ fill her up wi’ brimstone drink,",
  "                Red-reekin het.",
  "",
  "",
  "Though Jock an’ hav’rel Jean are merry—",
  "Some devil seize them in a hurry,",
  "An’ waft them in th’ infernal wherry",
  "                Straught through the lake,",
  "An’ gie their hides a noble curry",
  "                Wi’ oil of aik!",
  "",
  "",
  "As for the jurr-puir worthless body!",
  "She’s got mischief enough already;",
  "Wi’ stanged hips, and buttocks bluidy",
  "                She’s suffer’d sair;",
  "But, may she wintle in a woody,",
  "                If she wh-e mair!",
  ""
]