module.exports = [
  "’TWAS 1 in that place o’ Scotland’s isle,",
  "That bears the name o’ auld King Coil,",
  "Upon a bonie day in June,",
  "When wearin’ thro’ the afternoon,",
  "Twa dogs, that were na thrang at hame,",
  "Forgather’d ance upon a time.",
  "  The first I’ll name, they ca’d him Caesar,",
  "Was keepit for His Honor’s pleasure:",
  "His hair, his size, his mouth, his lugs,",
  "Shew’d he was nane o’ Scotland’s dogs;",
  "But whalpit some place far abroad,",
  "Whare sailors gang to fish for cod.",
  "  His locked, letter’d, braw brass collar",
  "Shew’d him the gentleman an’ scholar;",
  "But though he was o’ high degree,",
  "The fient a pride, nae pride had he;",
  "But wad hae spent an hour caressin,",
  "Ev’n wi’ al tinkler-gipsy’s messin:",
  "At kirk or market, mill or smiddie,",
  "Nae tawted tyke, tho’ e’er sae duddie,",
  "But he wad stan’t, as glad to see him,",
  "An’ stroan’t on stanes an’ hillocks wi’ him.",
  "  The tither was a ploughman’s collie—",
  "A rhyming, ranting, raving billie,",
  "Wha for his friend an’ comrade had him,",
  "And in freak had Luath ca’d him,",
  "After some dog in Highland Sang, 2",
  "Was made lang syne,—Lord knows how lang.",
  "  He was a gash an’ faithfu’ tyke,",
  "As ever lap a sheugh or dyke.",
  "His honest, sonsie, baws’nt face",
  "Aye gat him friends in ilka place;",
  "His breast was white, his touzie back",
  "Weel clad wi’ coat o’ glossy black;",
  "His gawsie tail, wi’ upward curl,",
  "Hung owre his hurdie’s wi’ a swirl.",
  "  Nae doubt but they were fain o’ ither,",
  "And unco pack an’ thick thegither;",
  "Wi’ social nose whiles snuff’d an’ snowkit;",
  "Whiles mice an’ moudieworts they howkit;",
  "Whiles scour’d awa’ in lang excursion,",
  "An’ worry’d ither in diversion;",
  "Until wi’ daffin’ weary grown",
  "Upon a knowe they set them down.",
  "An’ there began a lang digression.",
  "About the “lords o’ the creation.”",
  "",
  "",
  "CÆSAR  I’ve aften wonder’d, honest Luath,",
  "What sort o’ life poor dogs like you have;",
  "An’ when the gentry’s life I saw,",
  "What way poor bodies liv’d ava.",
  "  Our laird gets in his racked rents,",
  "His coals, his kane, an’ a’ his stents:",
  "He rises when he likes himsel’;",
  "His flunkies answer at the bell;",
  "He ca’s his coach; he ca’s his horse;",
  "He draws a bonie silken purse,",
  "As lang’s my tail, where, thro’ the steeks,",
  "The yellow letter’d Geordie keeks.",
  "  Frae morn to e’en, it’s nought but toiling",
  "At baking, roasting, frying, boiling;",
  "An’ tho’ the gentry first are stechin,",
  "Yet ev’n the ha’ folk fill their pechan",
  "Wi’ sauce, ragouts, an’ sic like trashtrie,",
  "That’s little short o’ downright wastrie.",
  "Our whipper-in, wee, blasted wonner,",
  "Poor, worthless elf, it eats a dinner,",
  "Better than ony tenant-man",
  "His Honour has in a’ the lan’:",
  "An’ what poor cot-folk pit their painch in,",
  "I own it’s past my comprehension.",
  "",
  "",
  "LUATH  Trowth, C&æsar, whiles they’re fash’t eneugh:",
  "A cottar howkin in a sheugh,",
  "Wi’ dirty stanes biggin a dyke,",
  "Baring a quarry, an’ sic like;",
  "Himsel’, a wife, he thus sustains,",
  "A smytrie o’ wee duddie weans,",
  "An’ nought but his han’-daurk, to keep",
  "Them right an’ tight in thack an’ rape.",
  "  An’ when they meet wi’ sair disasters,",
  "Like loss o’ health or want o’ masters,",
  "Ye maist wad think, a wee touch langer,",
  "An’ they maun starve o’ cauld an’ hunger:",
  "But how it comes, I never kent yet,",
  "They’re maistly wonderfu’ contented;",
  "An’ buirdly chiels, an’ clever hizzies,",
  "Are bred in sic a way as this is.",
  "",
  "",
  "CÆSAR  But then to see how ye’re negleckit,",
  "How huff’d, an’ cuff’d, an’ disrespeckit!",
  "Lord man, our gentry care as little",
  "For delvers, ditchers, an’ sic cattle;",
  "They gang as saucy by poor folk,",
  "As I wad by a stinkin brock.",
  "  I’ve notic’d, on our laird’s court-day,—",
  "An’ mony a time my heart’s been wae,—",
  "Poor tenant bodies, scant o’cash,",
  "How they maun thole a factor’s snash;",
  "He’ll stamp an’ threaten, curse an’ swear",
  "He’ll apprehend them, poind their gear;",
  "While they maun stan’, wi’ aspect humble,",
  "An’ hear it a’, an’ fear an’ tremble!",
  "  I see how folk live that hae riches;",
  "But surely poor-folk maun be wretches!",
  "",
  "",
  "LUATH  They’re no sae wretched’s ane wad think.",
  "Tho’ constantly on poortith’s brink,",
  "They’re sae accustom’d wi’ the sight,",
  "The view o’t gives them little fright.",
  "  Then chance and fortune are sae guided,",
  "They’re aye in less or mair provided:",
  "An’ tho’ fatigued wi’ close employment,",
  "A blink o’ rest’s a sweet enjoyment.",
  "  The dearest comfort o’ their lives,",
  "Their grushie weans an’ faithfu’ wives;",
  "The prattling things are just their pride,",
  "That sweetens a’ their fire-side.",
  "  An’ whiles twalpennie worth o’ nappy",
  "Can mak the bodies unco happy:",
  "They lay aside their private cares,",
  "To mind the Kirk and State affairs;",
  "They’ll talk o’ patronage an’ priests,",
  "Wi’ kindling fury i’ their breasts,",
  "Or tell what new taxation’s comin,",
  "An’ ferlie at the folk in Lon’on.",
  "  As bleak-fac’d Hallowmass returns,",
  "They get the jovial, rantin kirns,",
  "When rural life, of ev’ry station,",
  "Unite in common recreation;",
  "Love blinks, Wit slaps, an’ social Mirth",
  "Forgets there’s Care upo’ the earth.",
  "  That merry day the year begins,",
  "They bar the door on frosty win’s;",
  "The nappy reeks wi’ mantling ream,",
  "An’ sheds a heart-inspiring steam;",
  "The luntin pipe, an’ sneeshin mill,",
  "Are handed round wi’ right guid will;",
  "The cantie auld folks crackin crouse,",
  "The young anes rantin thro’ the house—",
  "My heart has been sae fain to see them,",
  "That I for joy hae barkit wi’ them.",
  "  Still it’s owre true that ye hae said,",
  "Sic game is now owre aften play’d;",
  "There’s mony a creditable stock",
  "O’ decent, honest, fawsont folk,",
  "Are riven out baith root an’ branch,",
  "Some rascal’s pridefu’ greed to quench,",
  "Wha thinks to knit himsel the faster",
  "In favour wi’ some gentle master,",
  "Wha, aiblins, thrang a parliamentin,",
  "For Britain’s guid his saul indentin—",
  "",
  "",
  "CÆSAR  Haith, lad, ye little ken about it:",
  "For Britain’s guid! guid faith! I doubt it.",
  "Say rather, gaun as Premiers lead him:",
  "An’ saying ay or no’s they bid him:",
  "At operas an’ plays parading,",
  "Mortgaging, gambling, masquerading:",
  "Or maybe, in a frolic daft,",
  "To Hague or Calais takes a waft,",
  "To mak a tour an’ tak a whirl,",
  "To learn bon ton, an’ see the worl’.",
  "  There, at Vienna, or Versailles,",
  "He rives his father’s auld entails;",
  "Or by Madrid he takes the rout,",
  "To thrum guitars an’ fecht wi’ nowt;",
  "Or down Italian vista startles,",
  "  Wh-re-hunting amang groves o’ myrtles:",
  "Then bowses drumlie German-water,",
  "To mak himsel look fair an’ fatter,",
  "An’ clear the consequential sorrows,",
  "Love-gifts of Carnival signoras.",
  "  For Britain’s guid! for her destruction!",
  "Wi’ dissipation, feud, an’ faction.",
  "",
  "",
  "LUATH  Hech, man! dear sirs! is that the gate",
  "They waste sae mony a braw estate!",
  "Are we sae foughten an’ harass’d",
  "For gear to gang that gate at last?",
  "  O would they stay aback frae courts,",
  "An’ please themsels wi’ country sports,",
  "It wad for ev’ry ane be better,",
  "The laird, the tenant, an’ the cotter!",
  "For thae frank, rantin, ramblin billies,",
  "Feint haet o’ them’s ill-hearted fellows;",
  "Except for breakin o’ their timmer,",
  "Or speakin lightly o’ their limmer,",
  "Or shootin of a hare or moor-cock,",
  "The ne’er-a-bit they’re ill to poor folk,",
  "  But will ye tell me, Master C&æsar,",
  "Sure great folk’s life’s a life o’ pleasure?",
  "Nae cauld nor hunger e’er can steer them,",
  "The very thought o’t need na fear them.",
  "",
  "",
  "CÆSAR  L—d, man, were ye but whiles whare I am,",
  "The gentles, ye wad ne’er envy them!",
  "  It’s true, they need na starve or sweat,",
  "Thro’ winter’s cauld, or simmer’s heat:",
  "They’ve nae sair wark to craze their banes,",
  "An’ fill auld age wi’ grips an’ granes:",
  "But human bodies are sic fools,",
  "For a’ their colleges an’ schools,",
  "That when nae real ills perplex them,",
  "They mak enow themsel’s to vex them;",
  "An’ aye the less they hae to sturt them,",
  "In like proportion, less will hurt them.",
  "  A country fellow at the pleugh,",
  "His acre’s till’d, he’s right eneugh;",
  "A country girl at her wheel,",
  "Her dizzen’s dune, she’s unco weel;",
  "But gentlemen, an’ ladies warst,",
  "Wi’ ev’n-down want o’ wark are curst.",
  "They loiter, lounging, lank an’ lazy;",
  "Tho’ deil-haet ails them, yet uneasy;",
  "Their days insipid, dull, an’ tasteless;",
  "Their nights unquiet, lang, an’ restless.",
  "  An’ev’n their sports, their balls an’ races,",
  "Their galloping through public places,",
  "There’s sic parade, sic pomp, an’ art,",
  "The joy can scarcely reach the heart.",
  "  The men cast out in party-matches,",
  "Then sowther a’ in deep debauches.",
  "Ae night they’re mad wi’ drink an’ whoring,",
  "Niest day their life is past enduring.",
  "  The ladies arm-in-arm in clusters,",
  "As great an’ gracious a’ as sisters;",
  "But hear their absent thoughts o’ ither,",
  "They’re a’ run-deils an’ jads thegither.",
  "Whiles, owre the wee bit cup an’ platie,",
  "They sip the scandal-potion pretty;",
  "Or lee-lang nights, wi’ crabbit leuks",
  "Pore owre the devil’s pictur’d beuks;",
  "Stake on a chance a farmer’s stackyard,",
  "An’ cheat like ony unhanged blackguard.",
  "  There’s some exceptions, man an’ woman;",
  "But this is gentry’s life in common.",
  "  By this, the sun was out of sight,",
  "An’ darker gloamin brought the night;",
  "The bum-clock humm’d wi’ lazy drone;",
  "The kye stood rowtin i’ the loan;",
  "When up they gat an’ shook their lugs,",
  "Rejoic’d they werena men but dogs;",
  "An’ each took aff his several way,",
  "Resolv’d to meet some ither day.",
  "",
  "",
  " Note 1. Luath was Burns’ own dog. [back]",
  "Note 2. Cuchullin’s dog in Ossian’s “Fingal.”—R. B. [back]",
  ""
]