module.exports = [
  "THE SUN had clos’d the winter day,",
  "The curless quat their roarin play,",
  "And hunger’d maukin taen her way,",
  "                To kail-yards green,",
  "While faithless snaws ilk step betray",
  "                Whare she has been.",
  "",
  "",
  "The thresher’s weary flingin-tree,",
  "The lee-lang day had tired me;",
  "And when the day had clos’d his e’e,",
  "                Far i’ the west,",
  "Ben i’ the spence, right pensivelie,",
  "                I gaed to rest.",
  "",
  "",
  "There, lanely by the ingle-cheek,",
  "I sat and ey’d the spewing reek,",
  "That fill’d, wi’ hoast-provoking smeek,",
  "                The auld clay biggin;",
  "An’ heard the restless rattons squeak",
  "                About the riggin.",
  "",
  "",
  "All in this mottie, misty clime,",
  "I backward mus’d on wasted time,",
  "How I had spent my youthfu’ prime,",
  "                An’ done nae thing,",
  "But stringing blethers up in rhyme,",
  "                For fools to sing.",
  "",
  "",
  "Had I to guid advice but harkit,",
  "I might, by this, hae led a market,",
  "Or strutted in a bank and clarkit",
  "                My cash-account;",
  "While here, half-mad, half-fed, half-sarkit.",
  "                Is a’ th’ amount.",
  "",
  "",
  "I started, mutt’ring, “blockhead! coof!”",
  "And heav’d on high my waukit loof,",
  "To swear by a’ yon starry roof,",
  "                Or some rash aith,",
  "That I henceforth wad be rhyme-proof",
  "                Till my last breath—",
  "",
  "",
  "When click! the string the snick did draw;",
  "An’ jee! the door gaed to the wa’;",
  "An’ by my ingle-lowe I saw,",
  "                Now bleezin bright,",
  "A tight, outlandish hizzie, braw,",
  "                Come full in sight.",
  "",
  "",
  "Ye need na doubt, I held my whisht;",
  "The infant aith, half-form’d, was crusht",
  "I glowr’d as eerie’s I’d been dusht",
  "                In some wild glen;",
  "When sweet, like honest Worth, she blusht,",
  "                An’ steppèd ben.",
  "",
  "",
  "Green, slender, leaf-clad holly-boughs",
  "Were twisted, gracefu’, round her brows;",
  "I took her for some Scottish Muse,",
  "                By that same token;",
  "And come to stop those reckless vows,",
  "                Would soon been broken.",
  "",
  "",
  "A “hair-brain’d, sentimental trace”",
  "Was strongly markèd in her face;",
  "A wildly-witty, rustic grace",
  "                Shone full upon her;",
  "Her eye, ev’n turn’d on empty space,",
  "                Beam’d keen with honour.",
  "",
  "",
  "Down flow’d her robe, a tartan sheen,",
  "Till half a leg was scrimply seen;",
  "An’ such a leg! my bonie Jean",
  "                Could only peer it;",
  "Sae straught, sae taper, tight an’ clean—",
  "                Nane else came near it.",
  "",
  "",
  "Her mantle large, of greenish hue,",
  "My gazing wonder chiefly drew:",
  "Deep lights and shades, bold-mingling, threw",
  "                A lustre grand;",
  "And seem’d, to my astonish’d view,",
  "                A well-known land.",
  "",
  "",
  "Here, rivers in the sea were lost;",
  "There, mountains to the skies were toss’t:",
  "Here, tumbling billows mark’d the coast,",
  "                With surging foam;",
  "There, distant shone Art’s lofty boast,",
  "                The lordly dome.",
  "",
  "",
  "Here, Doon pour’d down his far-fetch’d floods;",
  "There, well-fed Irwine stately thuds:",
  "Auld hermit Ayr staw thro’ his woods,",
  "                On to the shore;",
  "And many a lesser torrent scuds,",
  "                With seeming roar.",
  "",
  "",
  "Low, in a sandy valley spread,",
  "An ancient borough rear’d her head;",
  "Still, as in Scottish story read,",
  "                She boasts a race",
  "To ev’ry nobler virtue bred,",
  "                And polish’d grace. 2",
  "",
  "",
  "By stately tow’r, or palace fair,",
  "Or ruins pendent in the air,",
  "Bold stems of heroes, here and there,",
  "                I could discern;",
  "Some seem’d to muse, some seem’d to dare,",
  "                With feature stern.",
  "",
  "",
  "My heart did glowing transport feel,",
  "To see a race heroic 3 wheel,",
  "And brandish round the deep-dyed steel,",
  "                In sturdy blows;",
  "While, back-recoiling, seem’d to reel",
  "                Their Suthron foes.",
  "",
  "",
  "His Country’s Saviour, 4 mark him well!",
  "Bold Richardton’s heroic swell,; 5",
  "The chief, on Sark who glorious fell, 6",
  "                In high command;",
  "And he whom ruthless fates expel",
  "His native land.",
  "",
  "",
  "There, where a sceptr’d Pictish shade",
  "Stalk’d round his ashes lowly laid, 7",
  "I mark’d a martial race, pourtray’d",
  "In colours strong:",
  "Bold, soldier-featur’d, undismay’d,",
  "They strode along.",
  "",
  "",
  "Thro’ many a wild, romantic grove, 8",
  "Near many a hermit-fancied cove",
  "(Fit haunts for friendship or for love,",
  "In musing mood),",
  "An aged Judge, I saw him rove,",
  "Dispensing good.",
  "",
  "",
  "With deep-struck, reverential awe,",
  "The learned Sire and Son I saw: 9",
  "To Nature’s God, and Nature’s law,",
  "They gave their lore;",
  "This, all its source and end to draw,",
  "That, to adore.",
  "",
  "",
  "Brydon’s brave ward 10 I well could spy,",
  "Beneath old Scotia’s smiling eye:",
  "Who call’d on Fame, low standing by,",
  "                To hand him on,",
  "Where many a patriot-name on high,",
  "                And hero shone.",
  "",
  "",
  "DUAN SECONDWith musing-deep, astonish’d stare,",
  "I view’d the heavenly-seeming Fair;",
  "A whispering throb did witness bear",
  "                Of kindred sweet,",
  "When with an elder sister’s air",
  "                She did me greet.",
  "",
  "",
  "“All hail! my own inspired bard!",
  "In me thy native Muse regard;",
  "Nor longer mourn thy fate is hard,",
  "                Thus poorly low;",
  "I come to give thee such reward,",
  "                As we bestow!",
  "",
  "",
  "“Know, the great genius of this land",
  "Has many a light aerial band,",
  "Who, all beneath his high command,",
  "                Harmoniously,",
  "As arts or arms they understand,",
  "                Their labours ply.",
  "",
  "",
  "“They Scotia’s race among them share:",
  "Some fire the soldier on to dare;",
  "Some rouse the patriot up to bare",
  "                Corruption’s heart:",
  "Some teach the bard—a darling care—",
  "                The tuneful art.",
  "",
  "",
  "“’Mong swelling floods of reeking gore,",
  "They, ardent, kindling spirits pour;",
  "Or, ’mid the venal senate’s roar,",
  "                They, sightless, stand,",
  "To mend the honest patriot-lore,",
  "                And grace the hand.",
  "",
  "",
  "“And when the bard, or hoary sage,",
  "Charm or instruct the future age,",
  "They bind the wild poetric rage",
  "                In energy,",
  "Or point the inconclusive page",
  "                Full on the eye.",
  "",
  "",
  "“Hence, Fullarton, the brave and young;",
  "Hence, Dempster’s zeal-inspired tongue;",
  "Hence, sweet, harmonious Beattie sung",
  "                His ’Minstrel lays’;",
  "Or tore, with noble ardour stung,",
  "                The sceptic’s bays.",
  "",
  "",
  "“To lower orders are assign’d",
  "The humbler ranks of human-kind,",
  "The rustic bard, the lab’ring hind,",
  "                The artisan;",
  "All choose, as various they’re inclin’d,",
  "                The various man.",
  "",
  "",
  "“When yellow waves the heavy grain,",
  "The threat’ning storm some strongly rein;",
  "Some teach to meliorate the plain",
  "                With tillage-skill;",
  "And some instruct the shepherd-train,",
  "                Blythe o’er the hill.",
  "",
  "",
  "“Some hint the lover’s harmless wile;",
  "Some grace the maiden’s artless smile;",
  "Some soothe the lab’rer’s weary toil",
  "                For humble gains,",
  "And make his cottage-scenes beguile",
  "                His cares and pains.",
  "",
  "",
  "“Some, bounded to a district-space",
  "Explore at large man’s infant race,",
  "To mark the embryotic trace",
  "                Of rustic bard;",
  "And careful note each opening grace,",
  "                A guide and guard.",
  "",
  "",
  "“Of these am I—Coila my name:",
  "And this district as mine I claim,",
  "Where once the Campbells, chiefs of fame,",
  "                Held ruling power:",
  "I mark’d thy embryo-tuneful flame,",
  "                Thy natal hour.",
  "",
  "",
  "“With future hope I oft would gaze",
  "Fond, on thy little early ways,",
  "Thy rudely, caroll’d, chiming phrase,",
  "                In uncouth rhymes;",
  "Fir’d at the simple, artless lays",
  "                Of other times.",
  "",
  "",
  "“I saw thee seek the sounding shore,",
  "Delighted with the dashing roar;",
  "                Or when the North his fleecy store",
  "Drove thro’ the sky,",
  "I saw grim Nature’s visage hoar",
  "                Struck thy young eye.",
  "",
  "",
  "“Or when the deep green-mantled earth",
  "Warm cherish’d ev’ry floweret’s birth,",
  "And joy and music pouring forth",
  "                In ev’ry grove;",
  "I saw thee eye the general mirth",
  "                With boundless love.",
  "",
  "",
  "“When ripen’d fields and azure skies",
  "Call’d forth the reapers’ rustling noise,",
  "I saw thee leave their ev’ning joys,",
  "                And lonely stalk,",
  "To vent thy bosom’s swelling rise,",
  "                In pensive walk.",
  "",
  "",
  "“When youthful love, warm-blushing, strong,",
  "Keen-shivering, shot thy nerves along,",
  "Those accents grateful to thy tongue,",
  "                Th’ adorèd Name,",
  "I taught thee how to pour in song,",
  "                To soothe thy flame.",
  "",
  "",
  "“I saw thy pulse’s maddening play,",
  "Wild send thee Pleasure’s devious way,",
  "Misled by Fancy’s meteor-ray,",
  "                By passion driven;",
  "But yet the light that led astray",
  "                Was light from Heaven.",
  "",
  "",
  "“I taught thy manners-painting strains,",
  "The loves, the ways of simple swains,",
  "Till now, o’er all my wide domains",
  "                Thy fame extends;",
  "And some, the pride of Coila’s plains,",
  "                Become thy friends.",
  "",
  "",
  "“Thou canst not learn, nor I can show,",
  "To paint with Thomson’s landscape glow;",
  "Or wake the bosom-melting throe,",
  "                With Shenstone’s art;",
  "Or pour, with Gray, the moving flow",
  "                Warm on the heart.",
  "",
  "",
  "“Yet, all beneath th’ unrivall’d rose,",
  "T e lowly daisy sweetly blows;",
  "Tho’ large the forest’s monarch throws",
  "                His army shade,",
  "Yet green the juicy hawthorn grows,",
  "                Adown the glade.",
  "",
  "",
  "“Then never murmur nor repine;",
  "Strive in thy humble sphere to shine;",
  "And trust me, not Potosi’s mine,",
  "                Nor king’s regard,",
  "Can give a bliss o’ermatching thine,",
  "                A rustic bard.",
  "",
  "",
  "“To give my counsels all in one,",
  "Thy tuneful flame still careful fan:",
  "Preserve the dignity of Man,",
  "                With soul erect;",
  "And trust the Universal Plan",
  "                Will all protect.",
  "",
  "",
  "“And wear thou this”—she solemn said,",
  "And bound the holly round my head:",
  "The polish’d leaves and berries red",
  "                Did rustling play;",
  "And, like a passing thought, she fled",
  "                In light away.  [To Mrs. Stewart of Stair Burns presented a manuscript copy of the Vision. That copy embraces about twenty stanzas at the end of Duan First, which he cancelled when he came to print the price in his Kilmarnock volume. Seven of these he restored in printing his second edition, as noted on p. 174. The following are the verses which he left unpublished.]",
  "",
  "",
  " Note 1. Duan, a term of Ossian’s for the different divisions of a digressive poem. See his Cath-Loda, vol. 2 of M’Pherson’s translation.—R. B. [back]",
  "Note 2. The seven stanzas following this were first printed in the Edinburgh edition, 1787. Other stanzas, never published by Burns himself, are given on p. 180. [back]",
  "Note 3. The Wallaces.—R. B. [back]",
  "Note 4. William Wallace.—R. B. [back]",
  "Note 5. Adam Wallace of Richardton, cousin to the immortal preserver of Scottish independence.—R. B. [back]",
  "Note 6. Wallace, laird of Craigie, who was second in command under Douglas, Earl of Ormond, at the famous battle on the banks of Sark, fought anno 1448. That glorious victory was principally owing to the judicious conduct and intrepid valour of the gallant laird of Craigie, who died of his wounds after the action.—R. B. [back]",
  "Note 7. Coilus, King of the Picts, from whom the district of Kyle is said to take its name, lies buried, as tradition says, near the family seat of the Montgomeries of Coilsfield, where his burial-place is still shown.—R. B. [back]",
  "Note 8. Barskimming, the seat of the Lord Justice-Clerk.—R. B. [back]",
  "Note 9. Catrine, the seat of the late Doctor and present Professor Stewart.—R. B. [back]",
  ""
]