module.exports = [
  "\"Faithful to the end\" Amended",
  "From the Heavenly Clause --",
  "Constancy with a Proviso",
  "Constancy abhors --",
  "",
  "\"Crowns of Life\" are servile Prizes",
  "To the stately Heart,",
  "Given for the Giving, solely,",
  "No Emolument.",
  "",
  "--",
  "",
  "\"Faithful to the end\" Amended",
  "From the Heavenly clause --",
  "Lucrative indeed the offer",
  "But the Heart withdraws --",
  "",
  "\"I will give\" the base Proviso --",
  "Spare Your \"Crown of Life\" --",
  "Those it fits, too fair to wear it --",
  "Try it on Yourself --",
  ""
]