module.exports = [
  "I tell thee, Dick, where I have been,",
  "Where I the rarest things have seen,",
  "O, things without compare!",
  "Such sights again cannot be found",
  "In any place on English ground,",
  "Be it at wake or fair.",
  "",
  "At Charing Cross, hard by the way",
  "Where we, thou know'st, do sell our hay,",
  "There is a house with stairs;",
  "And there did I see coming down",
  "Such folks as are not in our town,",
  "Forty at least, in pairs.",
  "",
  "Amongst the rest, one pest'lent fine",
  "(His beard no bigger, though, than thine)",
  "Walked on before the rest:",
  "Our landlord looks like nothing to him;",
  "The King (God bless him!) 'twould undo him,",
  "Should he go still so dressed.",
  "",
  "At course-a-park, without all doubt,",
  "He should have first been taken out",
  "By all the maids i' th' town:",
  "Though lusty Roger there had been,",
  "Or little George upon the Green,",
  "Or Vincent of the Crown.",
  "",
  "But wot you what? the youth was going",
  "To make an end of all his wooing;",
  "The Parson for him stayed.",
  "Yet, by his leave, for all his haste,",
  "He did not so much wish all past,",
  "Perchance, as did the maid.",
  "",
  "The maid (and thereby hangs a tale),",
  "For such a maid no Whitsun-ale",
  "Could ever yet produce;",
  "No grape that's kindly ripe could be",
  "So round, so plump, so soft, as she,",
  "Nor half so full of juice!",
  "",
  "Her finger was so small the ring",
  "Would not stay on, which they did bring;",
  "It was too wide a peck:",
  "And to say truth (for out it must),",
  "It looked like a great collar (just)",
  "About our young colt's neck.",
  "",
  "Her feet beneath her petticoat,",
  "Like little mice, stole in and out,",
  "As if they feared the light:",
  "But oh! she dances such a way,",
  "No sun upon an Easter Day",
  "Is half so fine a sight!",
  "",
  "He would have kissed her once or twice,",
  "But she would not, she was so nice,",
  "She would not do 't in sight:",
  "And then she looked as who should say",
  "\"I will do what I list today,",
  "And you shall do 't at night.\"",
  "",
  "Her cheeks so rare a white was on,",
  "No daisy makes comparison,",
  "(Who sees them is undone),",
  "For streaks of red were mingled there,",
  "Such as are on a Catherine pear,",
  "(The side that's next the sun).",
  "",
  "Her lips were red, and one was thin",
  "Compared to that was next her chin, -",
  "(Some bee had stung it newly);",
  "But, Dick, her eyes so guard her face,",
  "I durst no more upon them gaze",
  "Than on the sun in July.",
  "",
  "Her mouth so small, when she does speak",
  "Thou'dst swear her teeth her words did break,",
  "That they might passage get;",
  "But she so handled still the matter,",
  "They came as good as ours, or better,",
  "And are not spent a whit.",
  "",
  "If wishing should be any sin,",
  "The Parson himself had guilty been,",
  "(She looked that day so purely);",
  "And, did the youth so oft the feat",
  "At night, as some did in conceit,",
  "It would have spoiled him surely.",
  "",
  "Just in the nick, the cook knocked thrice,",
  "And all the waiters in a trice",
  "His summons did obey.",
  "Each servingman, with dish in hand,",
  "Marched boldly up, like our trained band,",
  "Presented, and away.",
  "",
  "When all the meat was on the table,",
  "What man of knife or teeth was able",
  "To stay to be entreated?",
  "And this the very reason was,",
  "Before the parson could say grace,",
  "The company was seated.",
  "",
  "The business of the kitchen's great,",
  "For it is fit that man should eat;",
  "Nor was it there denied.",
  "Passion o' me, how I run on!",
  "There's that that would be thought upon,",
  "I trow, besides the bride.",
  "",
  "Now hats fly off, and youths carouse,",
  "Healths first go round, and then the house:",
  "The bride's came thick and thick;",
  "And when 'twas named another's health,",
  "Perhaps he made it hers by stealth.",
  "And who could help it, Dick?",
  "",
  "O' th' sudden, up they rise and dance;",
  "Then sit again and sigh and glance;",
  "Then dance again and kiss.",
  "Thus several ways the time did pass,",
  "Whilst every woman wished her place,",
  "And every man wished his!",
  "",
  "By this time all were stolen aside",
  "To counsel and undress the bride;",
  "But that he must not know;",
  "And yet 'twas thought he guessed her mind,",
  "And did not mean to stay behind",
  "Above an hour or so.",
  "",
  "When in he came, Dick, there she lay",
  "Like new-fallen snow melting away",
  "('Twas time, I trow, to part).",
  "Kisses were now the only stay,",
  "Which soon she gave, as one would say,",
  "\"God-be-with-ye, with all my heart.\"",
  "",
  "But, just as Heavens would have, to cross it,",
  "In came the bridesmaids with the posset:",
  "The bridegroom ate in spite;",
  "For, had he left the women to 't,",
  "It would have cost two hours to do 't,",
  "Which were too much that night.",
  "",
  "At length the candle's out, and now",
  "All that they had not done they do;",
  "What that is, who can tell?",
  "But I believe it was no more",
  "Than thou and I have done before",
  "With Bridget and with Nell.",
  ""
]