module.exports = [
  "\"HE has robbed two clubs. The judge at Salisbury",
  "Can't give him more than he undoubtedly",
  "Deserves. The scoundrel! Look at his photograph!",
  "A lady-killer! Hanging's too good by half",
  "For such as he.\" So said the stranger, one",
  "With crimes yet undiscovered or undone.",
  "But at the inn the Gipsy dame began:",
  "\"Now he was what I call a gentleman.",
  "He went along with Carrie, and when she",
  "Had a baby he paid up so readily",
  "His half a crown. Just like him. A crown'd have",
  "   been",
  "More like him. For I never knew him mean.",
  "Oh! but he was such a nice gentleman. Oh!",
  "Last time we met he said if me and Joe",
  "Was anywhere near we must be sure and call.",
  "He put his arms around our Amos all",
  "As if he were his own son. I pray God",
  "Save him from justice! Nicer man never trod.\"",
  ""
]