module.exports = [
  "LOVE, thou are absolute, sole Lord",
  "Of life and death. To prove the word,",
  "We'll now appeal to none of all",
  "Those thy old soldiers, great and tall,",
  "Ripe men of martyrdom, that could reach down",
  "With strong arms their triumphant crown:",
  "Such as could with lusty breath",
  "Speak loud, unto the face of death,",
  "Their great Lord's glorious name; to none",
  "Of those whose spacious bosoms spread a throne",
  "For love at large to fill. Spare blood and sweat:",
  "We'll see Him take a private seat,",
  "And make His mansion in the mild",
  "And milky soul of a soft child.",
  "Scarce has she learnt to lisp a name",
  "Of martyr, yet she thinks it shame",
  "Life should so long play with that breath",
  "Which spent can buy so brave a death.",
  "She never undertook to know",
  "What death with love should have to do.",
  "Nor has she e'er yet understood",
  "Why, to show love, she should shed blood;",
  "Yet, though she cannot tell you why,",
  "She can love, and she can die.",
  "Scarce has she blood enough to make",
  "A guilty sword blush for her sake;",
  "Yet has a heart dares hope to prove",
  "How much less strong is death than love....",
  "",
  "Since 'tis not to be had at home,",
  "She'll travel for a martyrdom.",
  "No home for her, confesses she,",
  "But where she may a martyr be.",
  "She'll to the Moors, and trade with them",
  "For this unvalued diadem;",
  "She offers them her dearest breath,",
  "With Christ's name in 't, in charge for death:",
  "She'll bargain with them, and will give",
  "Them God, and teach them how to live",
  "In Him; or, if they this deny,",
  "For Him she'll teach them how to die.",
  "So shall she leave amongst them sown",
  "Her Lord's blood, or at least her own.",
  "",
  "Farewell then, all the world, adieu!",
  "Teresa is no more for you.",
  "Farewell all pleasures, sports, and joys,",
  "Never till now esteemed toys!",
  "",
  "Farewell whatever dear may be--",
  "Mother's arms, or father's knee!",
  "Farewell house, and farewell home!",
  "She 's for the Moors and Martyrdom.",
  "",
  "Sweet, not so fast; lo! thy fair spouse,",
  "Whom thou seek'st with so swift vows,",
  "Calls thee back, and bids thee come",
  "T' embrace a milder martyrdom....",
  "",
  "O how oft shalt thou complain",
  "Of a sweet and subtle pain!",
  "Of intolerable joys!",
  "Of a death, in which who dies",
  "Loves his death, and dies again,",
  "And would for ever so be slain;",
  "And lives and dies, and knows not why",
  "To live, but that he still may die!",
  "How kindly will thy gentle heart",
  "Kiss the sweetly-killing dart!",
  "And close in his embraces keep",
  "Those delicious wounds, that weep",
  "Balsam, to heal themselves with thus,",
  "When these thy deaths, so numerous,",
  "Shall all at once die into one,",
  "And melt thy soul's sweet mansion;",
  "Like a soft lump of incense, hasted",
  "By too hot a fire, and wasted",
  "Into perfuming clouds, so fast",
  "Shalt thou exhale to heaven at last",
  "In a resolving sigh, and then,--",
  "O what? Ask not the tongues of men.",
  "",
  "Angels cannot tell; suffice,",
  "Thyself shalt feel thine own full joys,",
  "And hold them fast for ever there.",
  "So soon as thou shalt first appear,",
  "The moon of maiden stars, thy white",
  "Mistress, attended by such bright",
  "Souls as thy shining self, shall come,",
  "And in her first ranks make thee room;",
  "Where, 'mongst her snowy family,",
  "Immortal welcomes wait for thee.",
  "O what delight, when she shall stand",
  "And teach thy lips heaven, with her hand,",
  "On which thou now may'st to thy wishes",
  "Heap up thy consecrated kisses!",
  "What joy shall seize thy soul, when she,",
  "Bending her blessed eyes on thee,",
  "Those second smiles of heaven, shall dart",
  "Her mild rays through thy melting heart!",
  "",
  "Angels, thy old friends, there shall greet thee,",
  "Glad at their own home now to meet thee.",
  "All thy good works which went before,",
  "And waited for thee at the door,",
  "Shall own thee there; and all in one",
  "Weave a constellation",
  "Of crowns, with which the King, thy spouse,",
  "Shall build up thy triumphant brows.",
  "All thy old woes shall now smile on thee,",
  "And thy pains sit bright upon thee:",
  "All thy sorrows here shall shine,",
  "And thy sufferings be divine.",
  "Tears shall take comfort, and turn gems,",
  "And wrongs repent to diadems.",
  "Even thy deaths shall live, and new",
  "Dress the soul which late they slew.",
  "Thy wounds shall blush to such bright scars",
  "As keep account of the Lamb's wars.",
  "",
  "Those rare works, where thou shalt leave writ",
  "Love's noble history, with wit",
  "Taught thee by none but Him, while here",
  "They feed our souls, shall clothe thine there.",
  "Each heavenly word by whose hid flame",
  "Our hard hearts shall strike fire, the same",
  "Shall flourish on thy brows, and be",
  "Both fire to us and flame to thee;",
  "Whose light shall live bright in thy face",
  "By glory, in our hearts by grace.",
  "Thou shalt look round about, and see",
  "Thousands of crown'd souls throng to be",
  "Themselves thy crown, sons of thy vows,",
  "The virgin-births with which thy spouse",
  "Made fruitful thy fair soul; go now,",
  "And with them all about thee bow",
  "To Him; put on, He'll say, put on,",
  "My rosy Love, that thy rich zone,",
  "Sparkling with the sacred flames",
  "Of thousand souls, whose happy names",
  "Heaven keeps upon thy score: thy bright",
  "Life brought them first to kiss the light",
  "That kindled them to stars; and so",
  "Thou with the Lamb, thy Lord, shalt go.",
  "And, wheresoe'er He sets His white",
  "Steps, walk with Him those ways of light,",
  "Which who in death would live to see,",
  "Must learn in life to die like thee.",
  ""
]