module.exports = [
  "I have not brought my Odyssey",
  "With me here across the sea;",
  "But you'll remember, when I say",
  "How, when they went down Sparta way,",
  "To sandy Sparta, long ere dawn",
  "Horses were harnessed, rations drawn,",
  "Equipment polished sparkling bright,",
  "And breakfasts swallowed (as the white",
  "Of eastern heavens turned to gold) -",
  "The dogs barked, swift farewells were told.",
  "The sun springs up, the horses neigh,",
  "Crackles the whip thrice-then away!",
  "From sun-go-up to sun-go-down",
  "All day across the sandy down",
  "The gallant horses galloped, till",
  "The wind across the downs more chill",
  "Blew, the sun sank and all the road",
  "Was darkened, that it only showed",
  "Right at the end the town's red light",
  "And twilight glimmering into night.",
  "",
  "The horses never slackened till",
  "They reached the doorway and stood still.",
  "Then came the knock, the unlading; then",
  "The honey-sweet converse of men,",
  "The splendid bath, the change of dress,",
  "Then - oh the grandeur of their Mess,",
  "The henchmen, the prim stewardess!",
  "And oh the breaking of old ground,",
  "The tales, after the port went round!",
  "(The wondrous wiles of old Odysseus,",
  "Old Agamemnon and his misuse",
  "Of his command, and that young chit",
  "Paris - who didn't care a bit",
  "For Helen - only to annoy her",
  "He did it really, K.T.A.)",
  "But soon they led amidst the din",
  "The honey-sweet -- in,",
  "Whose eyes were blind, whose soul had sight,",
  "Who knew the fame of men in fight -",
  "Bard of white hair and trembling foot,",
  "Who sang whatever God might put",
  "Into his heart.",
  "And there he sung,",
  "Those war-worn veterans among,",
  "Tales of great war and strong hearts wrung,",
  "Of clash of arms, of council's brawl,",
  "Of beauty that must early fall,",
  "Of battle hate and battle joy",
  "By the old windy walls of Troy.",
  "They felt that they were unreal then,",
  "Visions and shadow-forms, not men.",
  "But those the Bard did sing and say",
  "(Some were their comrades, some were they)",
  "Took shape and loomed and strengthened more",
  "Greatly than they had guessed of yore.",
  "And now the fight begins again,",
  "The old war-joy, the old war-pain.",
  "Sons of one school across the sea",
  "We have no fear to fight -",
  "",
  "And soon, oh soon, I do not doubt it,",
  "With the body or without it,",
  "We shall all come tumbling down",
  "To our old wrinkled red-capped town.",
  "Perhaps the road up llsley way,",
  "The old ridge-track, will be my way.",
  "High up among the sheep and sky,",
  "Look down on Wantage, passing by,",
  "And see the smoke from Swindon town;",
  "And then full left at Liddington,",
  "Where the four winds of heaven meet",
  "The earth-blest traveller to greet.",
  "And then my face is toward the south,",
  "There is a singing on my mouth",
  "Away to rightward I descry",
  "My Barbury ensconced in sky,",
  "Far underneath the Ogbourne twins,",
  "And at my feet the thyme and whins,",
  "The grasses with their little crowns",
  "Of gold, the lovely Aldbourne downs,",
  "And that old signpost (well I knew",
  "That crazy signpost, arms askew,",
  "Old mother of the four grass ways).",
  "And then my mouth is dumb with praise,",
  "For, past the wood and chalkpit tiny,",
  "A glimpse of Marlborough --!",
  "So I descend beneath the rail",
  "To warmth and welcome and wassail.",
  "",
  "This from the battered trenches - rough,",
  "Jingling and tedious enough.",
  "And so I sign myself to you:",
  "One, who some crooked pathways knew",
  "Round Bedwyn: who could scarcely leave",
  "The Downs on a December eve:",
  "Was at his happiest in shorts,",
  "And got - not many good reports!",
  "Small skill of rhyming in his hand -",
  "But you'll forgive - you'll understand.",
  ""
]