module.exports = [
  "Green is the plane-tree in the square,",
  "The other trees are brown;",
  "They droop and pine for country air;",
  "The plane-tree loves the town.",
  "",
  "Here from my garret-pane, I mark",
  "The plane-tree bud and blow,",
  "Shed her recuperative bark,",
  "And spread her shade below.",
  "",
  "Among her branches, in and out,",
  "The city breezes play;",
  "The dun fog wraps her round about;",
  "Above, the smoke curls grey.",
  "",
  "Others the country take for choice,",
  "And hold the town in scorn;",
  "But she has listened to the voice",
  "On city breezes borne.",
  ""
]