module.exports = [
  "'Twas in the United States of America some years ago",
  "An aged father sat at his fireside with his heart full of woe,",
  "And talking to his neighbour, Mr Allan, about his boy Bennie",
  "That was to be shot because found asleep doing sentinel duty.",
  "",
  "\"Inside of twenty-four hours, the telegram said,",
  "And, oh! Mr Allan, he's dead, I am afraid.",
  "Where is my brave Bennie now to me is a mystery.\"",
  "\"We will hope with his heavenly Father,\" said Mr Allen, soothingly.",
  "",
  "\"Yes, let us hope God is very merciful,\" said Mr Allan.",
  "\"Yes, yes,\" said Bennie's father, \"my Bennie was a good man.",
  "He said, 'Father, I'll go and fight for my country.",
  "Go, then, Bennie,' I said, 'and God be with ye.' \"",
  "",
  "Little Blossom, Bennie's sister, sat listening with a blanched cheek,",
  "Poor soul, but she didn't speak,",
  "Until a gentle tap was heard at the kitchen door,",
  "Then she arose quickly and tripped across the floor.",
  "",
  "And opening the door, she received a letter from a neighbour's hand,",
  "And as she looked upon it in amazement she did stand.",
  "Then she cried aloud, \"It is from my brother Bennie.",
  "Yes, it is, dear father, as you can see.\"",
  "",
  "And as his father gazed upon it he thought Bennie was dead,",
  "Then he handed the letter to Mr Allan and by him it was read,",
  "And the minister read as follows: \"Dear father, when this you see",
  "I shall be dead and in eternity.",
  "",
  "\"And, dear father, at first it seemed awful to me",
  "The thought of being launched into eternity.",
  "But, dear father, I'm resolved to die like a man,",
  "And keep up my courage and do the best I can.",
  "",
  "\"You know I promised Jemmie Carr's mother to look after her boy,",
  "Who was his mother's pet and only joy.",
  "But one night while on march Jemmie turned sick,",
  "And if I hadn't lent him my arm he'd have dropped very quick.",
  "",
  "\"And that night it was Jemmie's turn to be sentry,",
  "And take poor Jemmie's place I did agree,",
  "But I couldn't keep awake, father, I'm sorry to relate,",
  "And I didn't know it, well, until it was too late.",
  "",
  "\"Good-bye, dear father, God seems near me,",
  "But I'm not afraid now to be launched into eternity.",
  "No, dear father, I'm going to a world free from strife,",
  "And see my Saviour there in a better, better life.\"",
  "",
  "That night, softly, little Blossom, Bennie's sister, stole out",
  "And glided down the footpath without any doubt.",
  "She was on her way to Washington, with her heart full of woe,",
  "To try and save her brother's life, blow high, blow low.",
  "",
  "And when Blossom appeared before President Lincoln,",
  "Poor child, she was looking very woebegone.",
  "Then the President said, \"My child, what do you want with me?\"",
  "\"Please, Bennie's life, sir,\" she answered timidly.",
  "",
  "\"Jemmie was sick, sir, and my brother took his place.\"",
  "\"What is this you say, child? Come here and let me see your face.\"",
  "Then she handed him Bennie's letter, and he read if carefully,",
  "And taking up his pen he wrote a few lines hastily.",
  "",
  "Then he said to Blossom, \"To-morrow, Bennie will go with you.\"",
  "And two days after this interview",
  "Bennie and Blossom took their way to their green mountain home,",
  "And poor little Blossom was footsore, but she didn't moan.",
  "",
  "",
  "And a crowd gathered at the mill depot to welcome them back,",
  "And to grasp the hand of his boy, Farmer Owen wasn't slack,",
  "And tears flowed down his cheeks as he said fervently,",
  "\"The Lord be praised for setting my dear boy free.\"",
  ""
]