module.exports = [
  "The Bombola faints in the hot Bowral tree,",
  "Where fierce Mullengudgery's smothering fires",
  "Far from the breezes of Coolgardie",
  "Burn ghastly and blue as the day expires;",
  "",
  "And Murriwillumba complaineth in song",
  "For the garlanded bowers of Woolloomooloo,",
  "And the Ballarat Fly and the lone Wollongong",
  "They dream of the gardens of Jamberoo;",
  "",
  "The wallabi sighs for the Murrubidgee,",
  "For the velvety sod of the Munno Parah,",
  "Where the waters of healing from Muloowurtie",
  "Flow dim in the gloaming by Yaranyackah;",
  "",
  "The Koppio sorrows for lost Wolloway,",
  "And sigheth in secret for Murrurundi,",
  "The Whangeroo wombat lamenteth the day",
  "That made him an exile from Jerrilderie;",
  "",
  "The Teawamute Tumut from Wirrega's glade,",
  "The Nangkita swallow, the Wallaroo swan,",
  "They long for the peace of the Timaru shade",
  "And thy balmy soft airs, O sweet Mittagong!",
  "",
  "The Kooringa buffalo pants in the sun,",
  "The Kondoparinga lies gaping for breath,",
  "The Kongorong Camaum to the shadow has won,",
  "But the Goomeroo sinks in the slumber of death;",
  "",
  "In the weltering hell of the Moorooroo plain",
  "The Yatala Wangary withers and dies,",
  "And the Worrow Wanilla, demented with pain,",
  "To the Woolgoolga woodlands despairingly flies;",
  "",
  "Sweet Nangwarry's desolate, Coonamble wails,",
  "And Tungkillo Kuito in sables is drest,",
  "For the Whangerei winds fall asleep in the sails",
  "And the Booleroo life-breeze is dead in the west.",
  "",
  "Mypongo, Kapunda, O slumber no more",
  "Yankalilla, Parawirra, be warned",
  "There's death in the air!",
  "Killanoola, wherefore",
  "Shall the prayer of Penola be scorned?",
  "",
  "Cootamundra, and Takee, and Wakatipu,",
  "Toowoomba, Kaikoura are lost",
  "From Onkaparinga to far Oamaru",
  "All burn in this hell's holocaust!",
  "",
  "Paramatta and Binnum are gone to their rest",
  "In the vale of Tapanni Taroom,",
  "Kawakawa, Deniliquin - all that was best",
  "In the earth are but graves and a tomb!",
  "",
  "Narrandera mourns, Cameron answers not",
  "When the roll of the scathless we cry",
  "Tongariro, Goondiwindi, Woolundunga, the spot",
  "Is mute and forlorn where ye lie.",
  ""
]