module.exports = [
  "What a pretty tale you told me",
  "  Once upon a time",
  "--Said you found it somewhere (scold me!)",
  "  Was it prose or was it rhyme,",
  "Greek or Latin? Greek, you said,",
  "While your shoulder propped my head.",
  "",
  "Anyhow there's no forgetting",
  "  This much if no more,",
  "That a poet (pray, no petting!)",
  "  Yes, a bard, sir, famed of yore,",
  "Went where suchlike used to go,",
  "Singing for a prize, you know.",
  "",
  "Well, he had to sing, nor merely",
  "  Sing but play the lyre;",
  "Playing was important clearly",
  "  Quite as singing: I desire,",
  "Sir, you keep the fact in mind",
  "For a purpose that's behind.",
  "",
  "There stood he, while deep attention",
  "  Held the judges round,",
  "--Judges able, I should mention,",
  "  To detect the slightest sound",
  "Sung or played amiss: such ears",
  "Had old judges, it appears!",
  "",
  "None the less he sang out boldly,",
  "  Played in time and tune,",
  "Till the judges, weighing coldly",
  "  Each note's worth, seemed, late or soon,",
  "Sure to smile \"In vain one tries",
  "Picking faults out: take the prize!\"",
  "",
  "When, a mischief! Were they seven",
  "  Strings the lyre possessed?",
  "Oh, and afterwards eleven,",
  "  Thank you! Well, sir,--who had guessed",
  "Such ill luck in store?--it happed",
  "One of those same seven strings snapped.",
  "",
  "All was lost, then! No! a cricket",
  "  (What \"cicada\"? Pooh!)",
  "--Some mad thing that left its thicket",
  "  For mere love of music--flew",
  "With its little heart on fire,",
  "Lighted on the crippled lyre.",
  "",
  "So that when (Ah joy!) our singer",
  "  For his truant string",
  "Feels with disconcerted finger,",
  "  What does cricket else but fling",
  "Fiery heart forth, sound the note",
  "Wanted by the throbbing throat?",
  "",
  "Ay and, ever to the ending,",
  "  Cricket chirps at need,",
  "Executes the hand's intending,",
  "  Promptly, perfectly,--indeed",
  "Saves the singer from defeat",
  "With her chirrup low and sweet.",
  "",
  "Till, at ending, all the judges",
  "  Cry with one assent",
  "\"Take the prize--a prize who grudges",
  "  Such a voice and instrument?",
  "Why, we took your lyre for harp,",
  "So it shrilled us forth F sharp!\"",
  "",
  "Did the conqueror spurn the creature",
  "  Once its service done?",
  "That's no such uncommon feature",
  "  In the case when Music's son",
  "Finds his Lotte's power too spent",
  "For aiding soul development.",
  "",
  "No! This other, on returning",
  "  Homeward, prize in hand,",
  "Satisfied his bosom's yearning:",
  "   (Sir, I hope you understand!)",
  "--Said \"Some record there must be",
  "Of this cricket's help to me!\"",
  "",
  "So, he made himself a statue:",
  "   Marble stood, life size;",
  "On the lyre, he pointed at you,",
  "   Perched his partner in the prize;",
  "Never more apart you found",
  "Her, he throned, from him, she crowned.",
  "",
  "That's the tale: its application?",
  "   Somebody I know",
  "Hopes one day for reputation",
  "  Thro' his poetry that's--Oh,",
  "All so learned and so wise",
  "And deserving of a prize!",
  "",
  "If he gains one, will some ticket",
  "   When his statue's built,",
  "Tell the gazer \"'Twas a cricket",
  "   Helped my crippled lyre, whose lilt",
  "Sweet and low, when strength usurped",
  "Softness' place i' the scale, she chirped?",
  "",
  "\"For as victory was nighest,",
  "  While I sang and played,--",
  "With my lyre at lowest, highest,",
  "   Right alike,--one string that made",
  "'Love' sound soft was snapt in twain",
  "Never to be heard again,--",
  "",
  "\"Had not a kind cricket fluttered,",
  "   Perched upon the place",
  "Vacant left, and duly uttered",
  "   'Love, Love, Love,' whene'er the bass",
  "Asked the treble to atone",
  "For its somewhat sombre drone.\"",
  "",
  "But you don't know music! Wherefore",
  "   Keep on casting pearls",
  "To a--poet? All I care for",
  "   Is--to tell him that a girl's",
  "\"Love\" comes aptly in when gruff",
  "Grows his singing, (There, enough!)",
  ""
]