module.exports = [
  "Sent to a friend who had complained that I was glad enough to see",
  "him when he came, but didn't seem to miss him if he stayed away.",
  "",
  "And cannot pleasures, while they last,",
  "Be actual unless, when past,",
  "They leave us shuddering and aghast,",
  "With anguish smarting?",
  "And cannot friends be firm and fast,",
  "And yet bear parting?",
  "",
  "And must I then, at Friendship's call,",
  "Calmly resign the little all",
  "(Trifling, I grant, it is and small)",
  "I have of gladness,",
  "And lend my being to the thrall",
  "Of gloom and sadness?",
  "",
  "And think you that I should be dumb,",
  "And full DOLORUM OMNIUM,",
  "Excepting when YOU choose to come",
  "And share my dinner?",
  "At other times be sour and glum",
  "And daily thinner?",
  "",
  "Must he then only live to weep,",
  "Who'd prove his friendship true and deep",
  "By day a lonely shadow creep,",
  "At night-time languish,",
  "Oft raising in his broken sleep",
  "The moan of anguish?",
  "",
  "The lover, if for certain days",
  "His fair one be denied his gaze,",
  "Sinks not in grief and wild amaze,",
  "But, wiser wooer,",
  "He spends the time in writing lays,",
  "And posts them to her.",
  "",
  "And if the verse flow free and fast,",
  "Till even the poet is aghast,",
  "A touching Valentine at last",
  "The post shall carry,",
  "When thirteen days are gone and past",
  "Of February.",
  "",
  "Farewell, dear friend, and when we meet,",
  "In desert waste or crowded street,",
  "Perhaps before this week shall fleet,",
  "Perhaps to-morrow.",
  "I trust to find YOUR heart the seat",
  "Of wasting sorrow.",
  ""
]