module.exports = [
  "I lounge in the doorway and languish in vain",
  "While Tom, Dick and Harry are dancing with Jane",
  "",
  "",
  "My spirit rises to the music's beat;",
  "There is a leaden fiend lurks in my feet!",
  "To move unto your motion, Love, were sweet.",
  "",
  "Somewhere, I think, some other where, not here,",
  "In other ages, on another sphere,",
  "I danced with you, and you with me, my dear.",
  "",
  "In perfect motion did our bodies sway,",
  "To perfect music that was heard alway;",
  "Woe's me, that am so dull of foot to-day!",
  "",
  "To move unto your motion, Love, were sweet;",
  "My spirit rises to the music's beat--",
  "But, ah, the leaden demon in my feet!",
  ""
]