module.exports = [
  "Who hath not glowed above the page where Fame",
  "Hath fixed high Caledon's unconquered name;",
  "The mountain-land which spurned the Roman chain,",
  "And baffled back the fiery-crested Dane,",
  "Whose bright claymore and hardihood of hand",
  "No foe could tame--no tyrant could command?",
  "That race is gone--but still their children breathe,",
  "And Glory crowns them with redoubled wreath:",
  "O'er Gael and Saxon mingling banners shine,",
  "And, England! add their stubborn strength to thine.",
  "The blood which flowed with Wallace flows as free,",
  "But now 'tis only shed for Fame and thee!",
  "Oh! pass not by the northern veteran's claim,",
  "But give support--the world hath given him fame!",
  "",
  "The humbler ranks, the lowly brave, who bled",
  "While cheerly following where the Mighty led--",
  "Who sleep beneath the undistinguished sod",
  "Where happier comrades in their triumph trod,",
  "To us bequeath--'tis all their fate allows--",
  "The sireless offspring and the lonely spouse:",
  "She on high Albyn's dusky hills may raise",
  "The tearful eye in melancholy gaze,",
  "Or view, while shadowy auguries disclose",
  "The Highland Seer's anticipated woes,",
  "The bleeding phantom of each martial form",
  "Dim in the cloud, or darkling in the storm;",
  "While sad, she chaunts the solitary song,",
  "The soft lament for him who tarries long--",
  "For him, whose distant relics vainly crave",
  "The Coronach's wild requiem to the brave!",
  "",
  "'Tis Heaven--not man--must charm away the woe,",
  "Which bursts when Nature's feelings newly flow;",
  "Yet Tenderness and Time may rob the tear",
  "Of half its bitterness for one so dear;",
  "A Nation's gratitude perchance may spread",
  "A thornless pillow for the widowed head;",
  "May lighten well her heart's maternal care,",
  "And wean from Penury the soldier's heir;",
  "Or deem to living war-worn Valour just",
  "Each wounded remnant--Albion's cherished trust--",
  "Warm his decline with those endearing rays,",
  "Whose bounteous sunshine yet may gild his days--",
  "So shall that Country--while he sinks to rest--",
  "His hand hath fought for--by his heart be blest!",
  ""
]