module.exports = [
  "In one dread night our city saw, and sighed,",
  "Bowed to the dust, the Drama's tower of pride;",
  "In one short hour beheld the blazing fane,",
  "Apollo sink, and Shakespeare cease to reign.",
  "",
  "  Ye who beheld, (oh! sight admired and mourned,",
  "Whose radiance mocked the ruin it adorned!)",
  "Through clouds of fire the massy fragments riven,",
  "Like Israel's pillar, chase the night from heaven;",
  "Saw the long column of revolving flames",
  "Shake its red shadow o'er the startled Thames,",
  "While thousands, thronged around the burning dome,",
  "Shrank back appalled, and trembled for their home,",
  "As glared the volumed blaze, and ghastly shone",
  "The skies, with lightnings awful as their own,",
  "Till blackening ashes and the lonely wall",
  "Usurped the Muse's realm, and marked her fall;",
  "Say--shall this new, nor less aspiring pile,",
  "Reared where once rose the mightiest in our isle,",
  "Know the same favour which the former knew,",
  "A shrine for Shakespeare--worthy him and _you_?",
  "",
  "  Yes--it shall be--the magic of that name",
  "Defies the scythe of time, the torch of flame;",
  "On the same spot still consecrates the scene,",
  "And bids the Drama _be_ where she hath _been_:",
  "This fabric's birth attests the potent spell----",
  "Indulge our honest pride, and say, _How well_!",
  "",
  "  As soars this fane to emulate the last,",
  "Oh! might we draw our omens from the past,",
  "Some hour propitious to our prayers may boast",
  "Names such as hallow still the dome we lost.",
  "On Drury first your Siddons' thrilling art",
  "O'erwhelmed the gentlest, stormed the sternest heart.",
  "On Drury, Garrick's latest laurels grew;",
  "Here your last tears retiring Roscius drew,",
  "Sighed his last thanks, and wept his last adieu:",
  "But still for living wit the wreaths may bloom,",
  "That only waste their odours o'er the tomb.",
  "Such Drury claimed and claims--nor you refuse",
  "One tribute to revive his slumbering muse;",
  "With garlands deck your own Menander's head,",
  "Nor hoard your honours idly for the dead!",
  "Dear are the days which made our annals bright,",
  "Ere Garrick fled, or Brinsley ceased to write",
  "Heirs to their labours, like all high-born heirs,",
  "Vain of _our_ ancestry as they of _theirs_;",
  "While thus Remembrance borrows Banquo's glass",
  "To claim the sceptred shadows as they pass,",
  "And we the mirror hold, where imaged shine",
  "Immortal names, emblazoned on our line,",
  "Pause--ere their feebler offspring you condemn,",
  "Reflect how hard the task to rival them!",
  "",
  "  Friends of the stage! to whom both Players and Plays",
  "Must sue alike for pardon or for praise,",
  "Whose judging voice and eye alone direct",
  "The boundless power to cherish or reject;",
  "If e'er frivolity has led to fame,",
  "And made us blush that you forbore to blame--",
  "If e'er the sinking stage could condescend",
  "To soothe the sickly taste it dare not mend--",
  "All past reproach may present scenes refute,",
  "And censure, wisely loud, be justly mute!",
  "Oh! since your fiat stamps the Drama's laws,",
  "Forbear to mock us with misplaced applause;",
  "So Pride shall doubly nerve the actor's powers,",
  "And Reason's voice be echoed back by ours!",
  "",
  "  This greeting o'er--the ancient rule obeyed,",
  "The Drama's homage by her herald paid--",
  "Receive _our welcome_ too--whose every tone",
  "Springs from our hearts, and fain would win your own.",
  "The curtain rises--may our stage unfold",
  "Scenes not unworthy Drury's days of old!",
  "Britons our judges, Nature for our guide,",
  "Still may _we_ please--long, long may _you_ preside.",
  ""
]