module.exports = [
  "THE rain of a night and a day and a night",
  "Stops at the light",
  "Of this pale choked day. The peering sun",
  "Sees what has been done.",
  "The road under the trees has a border new",
  "Of purple hue",
  "Inside the border of bright thin grass:",
  "For all that has",
  "Been left by November of leaves is torn",
  "From hazel and thorn",
  "And the greater trees. Throughout the copse",
  "No dead leaf drops",
  "On grey grass, green moss, burnt-orange fern,",
  "At the wind's return:",
  "The leaflets out of the ash-tree shed",
  "Are thinly spread",
  "In the road, like little black fish, inlaid,",
  "As if they played.",
  "What hangs from the myriad branches down there",
  "So hard and bare",
  "Is twelve yellow apples lovely to see",
  "On one crab-tree.",
  "And on each twig of every tree in the dell",
  "Uncountable",
  "Crystals both dark and bright of the rain",
  "That begins again.",
  ""
]