module.exports = [
  "UNLESS it was that day I never knew",
  "Ambition. After a night of frost, before",
  "The March sun brightened and the South-west blew,",
  "Jackdaws began to shout and float and soar",
  "Already, and one was racing straight and high",
  "Alone, shouting like a black warrior",
  "Challenges and menaces to the wide sky.",
  "With loud long laughter then a woodpecker",
  "Ridiculed the sadness of the owl's last cry.",
  "And through the valley where all the folk astir",
  "Made only plumes of pearly smoke to tower",
  "Over dark trees and white meadows happier",
  "Than was Elysium in that happy hour,",
  "A train that roared along raised after it",
  "And carried with it a motionless white bower",
  "Of purest cloud, from end to end close-knit,",
  "So fair it touched the roar with silence. Time",
  "Was powerless while that lasted. I could sit",
  "And think I had made the loveliness of prime,",
  "Breathed its life into it and were its lord,",
  "And no mind lived save this 'twixt clouds and rime.",
  "Omnipotent I was, nor even deplored",
  "That I did nothing. But the end fell like a bell:",
  "The bower was scattered; far off the train roared.",
  "But if this was ambition I cannot tell.",
  "What 'twas ambition for I know not well.",
  ""
]