module.exports = [
  "Beautiful new railway bridge of the Silvery Tay,",
  "With your strong brick piers and buttresses in so grand array,",
  "And your thirteen central girders, which seem to my eye",
  "Strong enough all windy storms to defy.",
  "And as I gaze upon thee my heart feels gay,",
  "Because thou are the greatest railway bridge of the present day,",
  "And can be seen for miles away",
  "From North, South, East or West of the Tay",
  "On a beautiful and clear sunshiny day,",
  "And ought to make the hearts of the \"Mars\" boys feel gay,",
  "Because thine equal nowhere can be seen,",
  "Only near by Dundee and the bonnie Magdalen Green.",
  "Beautiful new railway bridge of the Silvery Tay,",
  "With thy beautiful side-screens along your railway,",
  "Which will be a great protection on a windy day,",
  "So as the railway carriages won`t be blown away,",
  "And ought to cheer the hearts of the passengers night and day",
  "As they are conveyed along thy beautiful railway,",
  "And towering above the Silvery Tay,",
  "Spanning the beautiful river shore to shore",
  "Upwards of two miles and more,",
  "Which is most beautiful to be seen",
  "Near by Dundee and the bonnie Magdalen Green,",
  "",
  "Thy structure to my eye seems strong and grand,",
  "And the workmanship most skilfully planned;",
  "And I hope the designers, Messrs Barlow and Arrol, will prosper for many a day",
  "For erecting thee across the beautiful Tay.",
  "And I think nobody need have the least dismay",
  "To cross o`er thee by night or by day,",
  "Because thy strength is visible to be seen",
  "Near by Dundee and the bonnie Magdalen Green.",
  "",
  "Beautiful new railway bridge of the Silvery Tay,",
  "I wish you success for many a year and a day,",
  "And I hope thousands of people will come from faraway,",
  "Both high and low without delay,",
  "From the North, South, East and West,",
  "Because as a railway bridge thou art the best;",
  "Thou standest unequalled to be seen",
  "Near by Dundee and bonnie Magdalen Green.",
  "",
  "And for beauty thou art most lovely to be seen",
  "As the train crosses o'er thee with her cloud of steam;",
  "And you look well, painted the colour of marone,",
  "And to find thy equal there is none,",
  "Which, without fear of contradiction, I venture to say,",
  "Because you are the longest railway bridge of the present day",
  "That now crosses o'er a tidal river stream,",
  "And the most handsome to be seen",
  "Near by Dundee and the bonnie Magdalen Green.",
  "",
  "",
  "The New Yorkers boast about their Brooklyn Bridge,",
  "But in comparison to thee it seems like a midge,",
  "Because thou spannest the Silvery Tay",
  "A mile and more longer I venture to say;",
  "Besides the railway carriages are pulled across by a rope,",
  "Therefore Brooklyn Bridge cannot with thee cope;",
  "And as you have been opened on the 20th day of June,",
  "I hope Her Majesty Queen Victoria will visit thee very soon,",
  "Because thou art worthy of a visit from Duke, Lord or Queen,",
  "And strong and securely built, which is most worthy to be seen",
  "Near by Dundee and the bonnie Magdalen Green.",
  ""
]