module.exports = [
  "PART FIRST.",
  "",
  "'Tis hard to say, if greater want of skill",
  "Appear in writing or in judging ill;",
  "But, of the two, less dangerous is the offence",
  "To tire our patience, than mislead our sense.",
  "Some few in that, but numbers err in this;",
  "Ten censure wrong for one who writes amiss;",
  "A fool might once himself alone expose,",
  "Now one in verse makes many more in prose.",
  "",
  "'Tis with our judgments as our watches, none",
  "Go just alike, yet each believes his own.",
  "In poets as true genius is but rare,",
  "True taste as seldom, is the critic's share;",
  "Both must alike from Heaven derive their light,",
  "These born to judge, as well as those to write.",
  "Let such teach others who themselves excel.",
  "And censure freely who have written well.",
  "Authors are partial to their wit, 'tis true,",
  "But are not critics to their judgment too?",
  "",
  "Yet if we look more closely, we shall find",
  "Most have the seeds of judgment in their mind:",
  "Nature affords at least a glimmering light;",
  "The lines, though touch'd but faintly, are drawn right.",
  "But as the slightest sketch, if justly traced,",
  "Is by ill colouring but the more disgraced,",
  "So by false learning is good sense defaced:",
  "Some are bewilder'd in the maze of schools,",
  "And some made coxcombs Nature meant but fools.",
  "In search of wit these lose their common sense,",
  "And then turn critics in their own defence:",
  "Each burns alike, who can, or cannot write,",
  "Or with a rival's, or an eunuch's spite.",
  "All fools have still an itching to deride,",
  "And fain would be upon the laughing side;",
  "If Maevius scribble in Apollo's spite,",
  "There are who judge still worse than he can write.",
  "",
  "Some have at first for wits, then poets pass'd,",
  "Turn'd critics next, and proved plain fools at last.",
  "Some neither can for wits nor critics pass,",
  "As heavy mules are neither horse nor ass.",
  "Those half-learn'd witlings, numerous in our isle,",
  "As half-form'd insects on the banks of Nile;",
  "Unfinished things, one knows not what to call,",
  "Their generation's so equivocal:",
  "To tell 'em would a hundred tongues require,",
  "Or one vain wit's, that might a hundred tire.",
  "",
  "But you who seek to give and merit fame,",
  "And justly bear a critic's noble name,",
  "Be sure yourself and your own reach to know,",
  "How far your genius, taste, and learning go;",
  "Launch not beyond your depth, but be discreet,",
  "And mark that point where sense and dulness meet.",
  "",
  "Nature to all things fix'd the limits fit,",
  "And wisely curb'd proud man's pretending wit.",
  "As on the land while here the ocean gains,",
  "In other parts it leaves wide sandy plains;",
  "Thus in the soul while memory prevails,",
  "The solid power of understanding fails;",
  "Where beams of warm imagination play,",
  "The memory's soft figures melt away.",
  "One science only will one genius fit,",
  "So vast is art, so narrow human wit:",
  "Not only bounded to peculiar arts,",
  "But oft in those confined to single parts.",
  "Like kings, we lose the conquests gain'd before,",
  "By vain ambition still to make them more;",
  "Each might his several province well command,",
  "Would all but stoop to what they understand.",
  "",
  "First follow Nature, and your judgment frame",
  "By her just standard, which is still the same:",
  "Unerring Nature, still divinely bright,",
  "One clear, unchanged, and universal light,",
  "Life, force, and beauty, must to all impart,",
  "At once the source, and end, and test of Art.",
  "Art from that fund each just supply provides,",
  "Works without show, and without pomp presides;",
  "In some fair body thus the informing soul",
  "With spirits feeds, with vigour fills the whole,",
  "Each motion guides, and every nerve sustains,",
  "Itself unseen, but in the effects, remains.",
  "Some, to whom Heaven in wit has been profuse,",
  "Want as much more to turn it to its use;",
  "For wit and judgment often are at strife,",
  "Though meant each other's aid, like man and wife,",
  "'Tis more to guide than spur the Muse's steed,",
  "Restrain his fury, than provoke his speed;",
  "The wingèd courser, like a generous horse,",
  "Shows most true mettle when you check his course.",
  "",
  "Those rules, of old discover'd, not devised,",
  "Are Nature still, but Nature methodised;",
  "Nature, like liberty, is but restrain'd",
  "By the same laws which first herself ordain'd.",
  "Hear how learn'd Greece her useful rules indites,",
  "When to repress, and when indulge our flights:",
  "High on Parnassus' top her sons she show'd,",
  "And pointed out those arduous paths they trod;",
  "Held from afar, aloft, the immortal prize,",
  "And urged the rest by equal steps to rise.",
  "Just precepts thus from great examples given,",
  "She drew from them what they derived from Heaven.",
  "The generous critic fann'd the poet's fire,",
  "And taught the world with reason to admire.",
  "Then Criticism the Muse's handmaid proved,",
  "To dress her charms, and make her more beloved:",
  "But following wits from that intention stray'd,",
  "Who could not win the mistress, woo'd the maid;",
  "Against the poets their own arms they turn'd,",
  "Sure to hate most the men from whom they learn'd.",
  "So modern 'pothecaries, taught the art,",
  "By doctor's bills to play the doctor's part,",
  "Bold in the practice of mistaken rules,",
  "Prescribe, apply, and call their masters fools.",
  "Some on the leaves of ancient authors prey,",
  "Nor time nor moths e'er spoil'd so much as they.",
  "Some drily plain, without invention's aid,",
  "Write dull receipts how poems may be made.",
  "These leave the sense, their learning to display,",
  "And those explain the meaning quite away.",
  "",
  "You then, whose judgment the right course would steer,",
  "Know well each ancient's proper character;",
  "His fable, subject, scope in every page;",
  "Religion, country, genius of his age;",
  "Without all these at once before your eyes,",
  "Cavil you may, but never criticise.",
  "Be Homer's works your study and delight,",
  "Read them by day, and meditate by night;",
  "Thence form your judgment, thence your maxims bring,",
  "And trace the Muses upward to their spring.",
  "Still with itself compared, his text peruse;",
  "And let your comment be the Mantuan Muse.",
  "When first young Maro in his boundless mind,",
  "A work t' outlast immortal Rome design'd,",
  "Perhaps he seem'd above the critic's law,",
  "And but from Nature's fountains scorn'd to draw:",
  "But when t' examine every part he came,",
  "Nature and Homer were, he found, the same.",
  "Convinced, amazed, he checks the bold design,",
  "And rules as strict his labour'd work confine,",
  "As if the Stagyrite o'erlook'd each line.",
  "Learn hence for ancient rules a just esteem;",
  "To copy nature is to copy them.",
  "Some beauties yet no precepts can declare,",
  "For there's a happiness as well as care.",
  "Music resembles poetry, in each",
  "Are nameless graces which no methods teach,",
  "And which a master-hand alone can reach.",
  "If, where the rules not far enough extend,",
  "(Since rules were made but to promote their end)",
  "Some lucky license answer to the full",
  "The intent proposed, that license is a rule;",
  "Thus Pegasus, a nearer way to take,",
  "May boldly deviate from the common track;",
  "Great wits sometimes may gloriously offend,",
  "And rise to faults true critics dare not mend,",
  "From vulgar bounds with brave disorder part,",
  "And snatch a grace beyond the reach of art,",
  "Which, without passing through the judgment, gains",
  "The heart, and all its end at once attains.",
  "In prospects thus, some objects please our eyes,",
  "Which out of nature's common order rise,",
  "The shapeless rock, or hanging precipice.",
  "But though the ancients thus their rules invade,",
  "(As kings dispense with laws themselves have made)",
  "Moderns, beware! or if you must offend",
  "Against the precept, ne'er transgress its end;",
  "Let it be seldom, and compell'd by need,",
  "And have at least their precedent to plead.",
  "The critic else proceeds without remorse,",
  "Seizes your fame, and puts his laws in force.",
  "",
  "I know there are, to whose presumptuous thoughts,",
  "Those freer beauties, even in them, seem faults.",
  "Some figures monstrous and misshaped appear,",
  "Consider'd singly, or beheld too near,",
  "Which, but proportion'd to their light, or place,",
  "Due distance reconciles to form and grace.",
  "A prudent chief not always must display",
  "His powers in equal ranks, and fair array,",
  "But with the occasion and the place comply,",
  "Conceal his force, nay, seem sometimes to fly.",
  "Those oft are stratagems which errors seem,",
  "Nor is it Homer nods, but we that dream.",
  "",
  "Still green with bays each ancient altar stands,",
  "Above the reach of sacrilegious hands;",
  "Secure from flames, from envy's fiercer rage,",
  "Destructive war, and all-involving age.",
  "See from each clime the learn'd their incense bring!",
  "Hear in all tongues consenting paeans ring!",
  "In praise so just let every voice be join'd,",
  "And fill the general chorus of mankind.",
  "Hail, Bards triumphant! born in happier days;",
  "Immortal heirs of universal praise!",
  "Whose honours with increase of ages grow,",
  "As streams roll down, enlarging as they flow;",
  "Nations unborn your mighty names shall sound,",
  "And worlds applaud that must not yet be found!",
  "Oh may some spark of your celestial fire,",
  "The last, the meanest of your sons inspire,",
  "(That on weak wings, from far, pursues your flights,",
  "Glows while he reads, but trembles as he writes)",
  "To teach vain wits a science little known,",
  "T' admire superior sense, and doubt their own!",
  "",
  "PART SECOND.",
  "",
  "Of all the causes which conspire to blind",
  "Man's erring judgment, and misguide the mind,",
  "What the weak head with strongest bias rules,",
  "Is PRIDE, the never-failing vice of fools.",
  "Whatever Nature has in worth denied,",
  "She gives in large recruits of needless pride;",
  "For as in bodies, thus in souls, we find",
  "What wants in blood and spirits, swell'd with wind:",
  "Pride, where wit fails, steps in to our defence,",
  "And fills up all the mighty void of sense:",
  "If once right reason drives that cloud away,",
  "Truth breaks upon us with resistless day.",
  "Trust not yourself; but your defects to know,",
  "Make use of every friend--and every foe.",
  "",
  "A little learning is a dangerous thing;",
  "Drink deep, or taste not the Pierian spring:",
  "There shallow draughts intoxicate the brain,",
  "And drinking largely sobers us again.",
  "Fired at first sight with what the Muse imparts,",
  "In fearless youth we tempt the heights of arts,",
  "While from the bounded level of our mind,",
  "Short views we take, nor see the lengths behind;",
  "But, more advanced, behold with strange surprise,",
  "New distant scenes of endless science rise!",
  "So, pleased at first the towering Alps we try,",
  "Mount o'er the vales, and seem to tread the sky,",
  "The eternal snows appear already past,",
  "And the first clouds and mountains seem the last:",
  "But, those attain'd, we tremble to survey",
  "The growing labours of the lengthen'd way,",
  "The increasing prospect tires our wandering eyes,",
  "Hills peep o'er hills, and Alps on Alps arise!",
  "",
  "A perfect judge will read each work of wit",
  "With the same spirit that its author writ:",
  "Survey the WHOLE, nor seek slight faults to find",
  "Where nature moves, and rapture warms the mind;",
  "Nor lose, for that malignant dull delight,",
  "The generous pleasure to be charm'd with wit.",
  "But in such lays as neither ebb nor flow,",
  "Correctly cold, and regularly low,",
  "That, shunning faults, one quiet tenor keep,",
  "We cannot blame indeed--but we may sleep.",
  "In wit, as nature, what affects our hearts",
  "Is not the exactness of peculiar parts;",
  "'Tis not a lip, or eye, we beauty call,",
  "But the joint force and full result of all.",
  "Thus when we view some well-proportion'd dome,",
  "(The world's just wonder, and even thine, O Rome!)",
  "No single parts unequally surprise,",
  "All comes united to th' admiring eyes;",
  "No monstrous height, or breadth, or length appear;",
  "The whole at once is bold, and regular.",
  "",
  "Whoever thinks a faultless piece to see,",
  "Thinks what ne'er was, nor is, nor e'er shall be.",
  "In every work regard the writer's end,",
  "Since none can compass more than they intend;",
  "And if the means be just, the conduct true,",
  "Applause, in spite of trivial faults, is due.",
  "As men of breeding, sometimes men of wit,",
  "To avoid great errors, must the less commit:",
  "Neglect the rules each verbal critic lays,",
  "For not to know some trifles is a praise.",
  "Most critics, fond of some subservient art,",
  "Still make the whole depend upon a part:",
  "They talk of principles, but notions prize,",
  "And all to one loved folly sacrifice.",
  "",
  "Once on a time, La Mancha's knight, they say,",
  "A certain bard encountering on the way,",
  "Discoursed in terms as just, with looks as sage,",
  "As e'er could Dennis, of the Grecian stage;",
  "Concluding all were desperate sots and fools,",
  "Who durst depart from Aristotle's rules.",
  "Our author, happy in a judge so nice,",
  "Produced his play, and begg'd the knight's advice;",
  "Made him observe the subject, and the plot,",
  "The Manners, Passions, Unities; what not?",
  "All which, exact to rule, were brought about,",
  "Were but a combat in the lists left out.",
  "'What! leave the combat out?' exclaims the knight.",
  "'Yes, or we must renounce the Stagyrite.'",
  "'Not so, by Heaven!' (he answers in a rage);",
  "'Knights, squires, and steeds must enter on the stage.'",
  "'So vast a throng the stage can ne'er contain.'",
  "'Then build a new, or act it in a plain.'",
  "",
  "Thus critics, of less judgment than caprice,",
  "Curious, not knowing, not exact but nice,",
  "Form short ideas, and offend in arts",
  "(As most in manners) by a love to parts.",
  "",
  "Some to conceit alone their taste confine,",
  "And glittering thoughts struck out at every line;",
  "Pleased with a work where nothing's just or fit;",
  "One glaring chaos and wild heap of wit.",
  "Poets, like painters, thus, unskill'd to trace",
  "The naked nature and the living grace,",
  "With gold and jewels cover every part,",
  "And hide with ornaments their want of art.",
  "True wit is nature to advantage dress'd;",
  "What oft was thought, but ne'er so well express'd;",
  "Something, whose truth convinced at sight we find,",
  "That gives us back the image of our mind.",
  "As shades more sweetly recommend the light,",
  "So modest plainness sets off sprightly wit.",
  "For works may have more wit than does 'em good,",
  "As bodies perish through excess of blood.",
  "",
  "Others for language all their care express,",
  "And value books, as women men, for dress:",
  "Their praise is still--'The style is excellent;'",
  "The sense, they humbly take upon content.",
  "Words are like leaves, and where they most abound,",
  "Much fruit of sense beneath is rarely found.",
  "False eloquence, like the prismatic glass,",
  "Its gaudy colours spreads on every place;",
  "The face of Nature we no more survey,",
  "All glares alike, without distinction gay;",
  "But true expression, like the unchanging sun,",
  "Clears, and improves whate'er it shines upon;",
  "It gilds all objects, but it alters none.",
  "Expression is the dress of thought, and still",
  "Appears more decent, as more suitable;",
  "A vile conceit in pompous words express'd,",
  "Is like a clown in regal purple dress'd:",
  "For different styles with different subjects sort,",
  "As several garbs with country, town, and court.",
  "Some by old words to fame have made pretence,",
  "Ancients in phrase, mere moderns in their sense;",
  "Such labour'd nothings, in so strange a style,",
  "Amaze the unlearn'd, and make the learnèd smile.",
  "Unlucky, as Fungoso in the play,",
  "These sparks with awkward vanity display",
  "What the fine gentleman wore yesterday;",
  "And but so mimic ancient wits at best,",
  "As apes our grandsires, in their doublets dress'd.",
  "In words, as fashions, the same rule will hold;",
  "Alike fantastic, if too new, or old:",
  "Be not the first by whom the new are tried,",
  "Nor yet the last to lay the old aside.",
  "",
  "But most by numbers judge a poet's song;",
  "And smooth or rough, with them, is right or wrong:",
  "In the bright Muse, though thousand charms conspire,",
  "Her voice is all these tuneful fools admire;",
  "Who haunt Parnassus but to please their ear,",
  "Not mend their minds; as some to church repair,",
  "Not for the doctrine, but the music there.",
  "These equal syllables alone require,",
  "Though oft the ear the open vowels tire;",
  "While expletives their feeble aid do join,",
  "And ten low words oft creep in one dull line:",
  "While they ring round the same unvaried chimes,",
  "With sure returns of still expected rhymes;",
  "Where'er you find 'the cooling western breeze,'",
  "In the next line, it 'whispers through the trees:'",
  "If crystal streams 'with pleasing murmurs creep,'",
  "The reader's threaten'd (not in vain) with 'sleep:'",
  "Then, at the last and only couplet fraught",
  "With some unmeaning thing they call a thought,",
  "A needless Alexandrine ends the song",
  "That, like a wounded snake, drags its slow length along.",
  "Leave such to tune their own dull rhymes, and know",
  "What's roundly smooth, or languishingly slow;",
  "And praise the easy vigour of a line,",
  "Where Denham's strength, and Waller's sweetness join.",
  "True ease in writing comes from art, not chance,",
  "As those move easiest who have learn'd to dance.",
  "'Tis not enough no harshness gives offence,",
  "The sound must seem an echo to the sense;",
  "Soft is the strain when Zephyr gently blows,",
  "And the smooth stream in smoother numbers flows:",
  "But when loud surges lash the sounding shore,",
  "The hoarse, rough verse should like the torrent roar.",
  "When Ajax strives some rock's vast weight to throw,",
  "The line too labours, and the words move slow;",
  "Not so, when swift Camilla scours the plain,",
  "Flies o'er the unbending corn, and skims along the main.",
  "Hear how Timotheus' varied lays surprise,",
  "And bid alternate passions fall and rise!",
  "While, at each change, the son of Libyan Jove",
  "Now burns with glory, and then melts with love;",
  "Now his fierce eyes with sparkling fury glow,",
  "Now sighs steal out, and tears begin to flow:",
  "Persians and Greeks like turns of nature found,",
  "And the world's victor stood subdued by sound!",
  "The power of music all our hearts allow,",
  "And what Timotheus was, is Dryden now.",
  "",
  "Avoid extremes; and shun the fault of such",
  "Who still are pleased, too little or too much.",
  "At every trifle scorn to take offence:",
  "That always shows great pride or little sense;",
  "Those heads, as stomachs, are not sure the best",
  "Which nauseate all, and nothing can digest.",
  "Yet let not each gay turn thy rapture move,",
  "For fools admire, but men of sense approve:",
  "As things seem large which we through mists descry,",
  "Dulness is ever apt to magnify.",
  "",
  "Some, foreign writers, some, our own despise;",
  "The ancients only, or the moderns prize.",
  "Thus wit, like faith, by each man is applied",
  "To one small sect, and all are damn'd beside.",
  "Meanly they seek the blessing to confine,",
  "And force that sun but on a part to shine,",
  "Which not alone the southern wit sublimes,",
  "But ripens spirits in cold northern climes;",
  "Which from the first has shone on ages past,",
  "Enlights the present, and shall warm the last;",
  "Though each may feel increases and decays,",
  "And see now clearer and now darker days.",
  "Regard not then if wit be old or new,",
  "But blame the false, and value still the true.",
  "",
  "Some ne'er advance a judgment of their own,",
  "But catch the spreading notion of the town;",
  "They reason and conclude by precedent,",
  "And own stale nonsense which they ne'er invent.",
  "Some judge of authors' names, not works, and then",
  "Nor praise nor blame the writings, but the men.",
  "Of all this servile herd, the worst is he",
  "That in proud dulness joins with quality;",
  "A constant critic at the great man's board,",
  "To fetch and carry nonsense for my lord.",
  "What woful stuff this madrigal would be,",
  "In some starved hackney sonnetteer, or me?",
  "But let a lord once own the happy lines",
  "How the wit brightens! how the style refines!",
  "Before his sacred name flies every fault,",
  "And each exalted stanza teems with thought!",
  "",
  "The vulgar thus through imitation err;",
  "As oft the learn'd by being singular:",
  "So much they scorn the crowd, that if the throng",
  "By chance go right, they purposely go wrong:",
  "So schismatics the plain believers quit,",
  "And are but damn'd for having too much wit.",
  "Some praise at morning what they blame at night,",
  "But always think the last opinion right.",
  "A Muse by these is like a mistress used,",
  "This hour she's idolised, the next abused;",
  "While their weak heads, like towns unfortified,",
  "'Twixt sense and nonsense daily change their side.",
  "Ask them the cause; they're wiser still, they say;",
  "And still to-morrow's wiser than to-day.",
  "We think our fathers fools, so wise we grow;",
  "Our wiser sons, no doubt, will think us so.",
  "Once school-divines this zealous isle o'erspread;",
  "Who knew most sentences, was deepest read;",
  "Faith, Gospel, all, seem'd made to be disputed,",
  "And none had sense enough to be confuted:",
  "Scotists and Thomists now in peace remain,",
  "Amidst their kindred cobwebs in Duck-lane.",
  "If Faith itself has different dresses worn,",
  "What wonder modes in wit should take their turn?",
  "Oft, leaving what is natural and fit,",
  "The current folly proves the ready wit,",
  "And authors think their reputation safe",
  "Which lives as long as fools are pleased to laugh.",
  "",
  "Some valuing those of their own side or mind,",
  "Still make themselves the measure of mankind:",
  "Fondly we think we honour merit then,",
  "When we but praise ourselves in other men.",
  "Parties in wit attend on those of state,",
  "And public faction doubles private hate.",
  "Pride, malice, folly, against Dryden rose,",
  "In various shapes of parsons, critics, beaux;",
  "But sense survived, when merry jests were past;",
  "For rising merit will buoy up at last.",
  "Might he return, and bless once more our eyes,",
  "New Blackmores and new Milbourns must arise:",
  "Nay, should great Homer lift his awful head,",
  "Zoilus again would start up from the dead.",
  "Envy will Merit, as its shade, pursue,",
  "But like a shadow, proves the substance true;",
  "For envied wit, like Sol eclipsed, makes known",
  "The opposing body's grossness, not its own.",
  "When first that sun too powerful beams displays,",
  "It draws up vapours which obscure its rays;",
  "But even those clouds at last adorn its way,",
  "Reflect new glories, and augment the day.",
  "",
  "Be thou the first true merit to befriend;",
  "His praise is lost, who stays till all commend.",
  "Short is the date, alas! of modern rhymes,",
  "And 'tis but just to let them live betimes.",
  "No longer now that golden age appears,",
  "When patriarch-wits survived a thousand years:",
  "Now length of fame (our second life) is lost,",
  "And bare threescore is all even that can boast;",
  "Our sons their fathers' failing language see,",
  "And such as Chaucer is, shall Dryden be.",
  "So when the faithful pencil has design'd",
  "Some bright idea of the master's mind,",
  "Where a new world leaps out at his command,",
  "And ready Nature waits upon his hand;",
  "When the ripe colours soften and unite,",
  "And sweetly melt into just shade and light;",
  "When mellowing years their full perfection give,",
  "And each bold figure just begins to live,",
  "The treacherous colours the fair art betray,",
  "And all the bright creation fades away!",
  "",
  "Unhappy wit, like most mistaken things,",
  "Atones not for that envy which it brings.",
  "In youth alone its empty praise we boast,",
  "But soon the short-lived vanity is lost:",
  "Like some fair flower the early spring supplies,",
  "That gaily blooms, but even in blooming dies.",
  "What is this wit, which must our cares employ?",
  "The owner's wife, that other men enjoy;",
  "Then most our trouble still when most admired,",
  "And still the more we give, the more required;",
  "Whose fame with pains we guard, but lose with ease,",
  "Sure some to vex, but never all to please;",
  "'Tis what the vicious fear, the virtuous shun,",
  "By fools 'tis hated, and by knaves undone!",
  "",
  "If wit so much from ignorance undergo,",
  "Ah, let not learning too commence its foe!",
  "Of old, those met rewards who could excel,",
  "And such were praised who but endeavour'd well:",
  "Though triumphs were to generals only due,",
  "Crowns were reserved to grace the soldiers too.",
  "Now, they who reach Parnassus' lofty crown,",
  "Employ their pains to spurn some others down;",
  "And while self-love each jealous writer rules,",
  "Contending wits become the sport of fools:",
  "But still the worst with most regret commend,",
  "For each ill author is as bad a friend.",
  "To what base ends, and by what abject ways,",
  "Are mortals urged through sacred lust of praise!",
  "Ah, ne'er so dire a thirst of glory boast,",
  "Nor in the critic let the man be lost.",
  "Good-nature and good-sense must ever join;",
  "To err is human--to forgive, divine.",
  "",
  "But if in noble minds some dregs remain,",
  "Not yet purged off, of spleen and sour disdain;",
  "Discharge that rage on more provoking crimes,",
  "Nor fear a dearth in these flagitious times.",
  "No pardon vile obscenity should find,",
  "Though wit and art conspire to move your mind;",
  "But dulness with obscenity must prove",
  "As shameful sure as impotence in love.",
  "In the fat age of pleasure, wealth, and ease,",
  "Sprung the rank weed, and thrived with large increase:",
  "When love was all an easy monarch's care;",
  "Seldom at council, never in a war:",
  "Jilts ruled the state, and statesmen farces writ;",
  "Nay, wits had pensions, and young lords had wit;",
  "The fair sat panting at a courtier's play,",
  "And not a mask went unimproved away:",
  "The modest fan was lifted up no more,",
  "And virgins smiled at what they blush'd before.",
  "The following license of a foreign reign",
  "Did all the dregs of bold Socinus drain;",
  "Then unbelieving priests reform'd the nation,",
  "And taught more pleasant methods of salvation;",
  "Where Heaven's free subjects might their rights dispute,",
  "Lest God himself should seem too absolute:",
  "Pulpits their sacred satire learn'd to spare,",
  "And vice admired to find a flatterer there!",
  "Encouraged thus, wit's Titans braved the skies,",
  "And the press groan'd with licensed blasphemies.",
  "These monsters, critics! with your darts engage,",
  "Here point your thunder, and exhaust your rage!",
  "Yet shun their fault, who, scandalously nice,",
  "Will needs mistake an author into vice;",
  "All seems infected that the infected spy,",
  "As all looks yellow to the jaundiced eye.",
  "",
  "PART THIRD.",
  "",
  "Learn, then, what MORALS critics ought to show,",
  "For 'tis but half a judge's task to know.",
  "'Tis not enough, taste, judgment, learning join;",
  "In all you speak, let truth and candour shine:",
  "That not alone what to your sense is due",
  "All may allow; but seek your friendship too.",
  "",
  "Be silent always when you doubt your sense;",
  "And speak, though sure, with seeming diffidence:",
  "Some positive, persisting fops we know,",
  "Who, if once wrong, will needs be always so;",
  "But you, with pleasure own your errors past,",
  "And make each day a critique on the last.",
  "",
  "'Tis not enough your counsel still be true;",
  "Blunt truths more mischief than nice falsehoods do;",
  "Men must be taught as if you taught them not,",
  "And things unknown proposed as things forgot.",
  "Without good-breeding, truth is disapproved;",
  "That only makes superior sense beloved.",
  "",
  "Be niggards of advice on no pretence;",
  "For the worst avarice is that of sense.",
  "With mean complaisance ne'er betray your trust,",
  "Nor be so civil as to prove unjust.",
  "Fear not the anger of the wise to raise;",
  "Those best can bear reproof, who merit praise.",
  "",
  "'Twere well might critics still this freedom take,",
  "But Appius reddens at each word you speak,",
  "And stares tremendous, with a threatening eye,",
  "Like some fierce tyrant in old tapestry.",
  "Fear most to tax an Honourable fool,",
  "Whose right it is, uncensured, to be dull;",
  "Such, without wit, are poets when they please,",
  "As without learning they can take degrees.",
  "Leave dangerous truths to unsuccessful satires,",
  "And flattery to fulsome dedicators,",
  "Whom, when they praise, the world believes no more,",
  "Than when they promise to give scribbling o'er.",
  "'Tis best sometimes your censure to restrain,",
  "And charitably let the dull be vain:",
  "Your silence there is better than your spite,",
  "For who can rail so long as they can write?",
  "Still humming on, their drowsy course they keep,",
  "And lash'd so long, like tops, are lash'd asleep.",
  "False steps but help them to renew the race,",
  "As, after stumbling, jades will mend their pace.",
  "What crowds of these, impenitently bold,",
  "In sounds and jingling syllables grown old,",
  "Still run on poets, in a raging vein,",
  "Even to the dregs and squeezings of the brain,",
  "Strain out the last dull droppings of their sense,",
  "And rhyme with all the rage of impotence!",
  "",
  "Such shameless bards we have; and yet 'tis true,",
  "There are as mad, abandon'd critics too.",
  "The bookful blockhead, ignorantly read,",
  "With loads of learnèd lumber in his head,",
  "With his own tongue still edifies his ears,",
  "And always listening to himself appears.",
  "All books he reads, and all he reads assails,",
  "From Dryden's Fables down to D'Urfey's Tales.",
  "With him, most authors steal their works, or buy;",
  "Garth did not write his own Dispensary.",
  "Name a new play, and he's the poet's friend,",
  "Nay, show'd his faults--but when would poets mend?",
  "No place so sacred from such fops is barr'd,",
  "Nor is Paul's church more safe than Paul's churchyard:",
  "Nay, fly to altars; there they'll talk you dead:",
  "For fools rush in where angels fear to tread.",
  "Distrustful sense with modest caution speaks,",
  "It still looks home, and short excursions makes;",
  "But rattling nonsense in full volleys breaks,",
  "And, never shock'd, and never turn'd aside,",
  "Bursts out, resistless, with a thundering tide.",
  "",
  "But where's the man, who counsel can bestow,",
  "Still pleased to teach, and yet not proud to know?",
  "Unbiass'd, or by favour, or by spite;",
  "Not dully prepossess'd, nor blindly right;",
  "Though learn'd, well-bred; and though well-bred, sincere;",
  "Modestly bold, and humanly severe:",
  "Who to a friend his faults can freely show,",
  "And gladly praise the merit of a foe?",
  "Bless'd with a taste exact, yet unconfined;",
  "A knowledge both of books and human kind;",
  "Generous converse; a soul exempt from pride;",
  "And love to praise, with reason on his side?",
  "",
  "Such once were critics; such the happy few,",
  "Athens and Rome in better ages knew.",
  "The mighty Stagyrite first left the shore,",
  "Spread all his sails, and durst the deeps explore;",
  "He steer'd securely, and discover'd far,",
  "Led by the light of the Maeonian star.",
  "Poets, a race long unconfined, and free,",
  "Still fond and proud of savage liberty,",
  "Received his laws; and stood convinced 'twas fit,",
  "Who conquer'd Nature, should preside o'er Wit.",
  "",
  "Horace still charms with graceful negligence,",
  "And without method talks us into sense,",
  "Will, like a friend, familiarly convey",
  "The truest notions in the easiest way.",
  "He who, supreme in judgment, as in wit,",
  "Might boldly censure, as he boldly writ,",
  "Yet judged with coolness, though he sung with fire;",
  "His precepts teach but what his works inspire.",
  "Our critics take a contrary extreme,",
  "They judge with fury, but they write with phlegm:",
  "Nor suffers Horace more in wrong translations",
  "By wits, than critics in as wrong quotations.",
  "",
  "See Dionysius Homer's thoughts refine,",
  "And call new beauties forth from every line!",
  "",
  "Fancy and art in gay Petronius please,",
  "The scholar's learning, with the courtier's ease.",
  "",
  "In grave Quintilian's copious work we find",
  "The justest rules and clearest method join'd:",
  "Thus useful arms in magazines we place,",
  "All ranged in order, and disposed with grace,",
  "But less to please the eye, than arm the hand,",
  "Still fit for use, and ready at command.",
  "",
  "Thee, bold Longinus! all the Nine inspire,",
  "And bless their critic with a poet's fire.",
  "An ardent judge, who, zealous in his trust,",
  "With warmth gives sentence, yet is always just;",
  "Whose own example strengthens all his laws;",
  "And is himself that Great Sublime he draws.",
  "",
  "Thus long succeeding critics justly reign'd,",
  "Licence repress'd, and useful laws ordain'd.",
  "Learning and Rome alike in empire grew;",
  "And arts still follow'd where her eagles flew;",
  "From the same foes, at last, both felt their doom,",
  "And the same age saw Learning fall, and Rome.",
  "With Tyranny then Superstition join'd,",
  "As that the body, this enslaved the mind;",
  "Much was believed, but little understood,",
  "And to be dull was construed to be good;",
  "A second deluge Learning thus o'errun,",
  "And the Monks finish'd what the Goths begun.",
  "",
  "At length Erasmus, that great injured name,",
  "(The glory of the priesthood, and the shame!)",
  "Stemm'd the wild torrent of a barbarous age,",
  "And drove those holy Vandals off the stage.",
  "",
  "But see! each Muse, in Leo's golden days,",
  "Starts from her trance, and trims her wither'd bays,",
  "Rome's ancient Genius, o'er its ruins spread,",
  "Shakes off the dust, and rears his reverend head.",
  "Then Sculpture and her sister-arts revive;",
  "Stones leap'd to form, and rocks began to live;",
  "With sweeter notes each rising temple rung:",
  "A Raphael painted, and a Vida sung:",
  "Immortal Vida! on whose honour'd brow",
  "The poet's bays and critic's ivy grow;",
  "Cremona now shall ever boast thy name,",
  "As next in place to Mantua, next in fame!",
  "",
  "But soon by impious arms from Latium chased,",
  "Their ancient bounds the banish'd Muses pass'd;",
  "Thence Arts o'er all the northern world advance,",
  "But critic-learning flourish'd most in France:",
  "The rules a nation, born to serve, obeys;",
  "And Boileau still in right of Horace sways.",
  "But we, brave Britons, foreign laws despised,",
  "And kept unconquer'd and uncivilised;",
  "Fierce for the liberties of wit, and bold,",
  "We still defied the Romans, as of old.",
  "Yet some there were, among the sounder few",
  "Of those who less presumed, and better knew,",
  "Who durst assert the juster ancient cause,",
  "And here restored Wit's fundamental laws.",
  "Such was the Muse, whose rules and practice tell,",
  "'Nature's chief masterpiece is writing well.'",
  "Such was Roscommon, not more learn'd than good,",
  "With manners generous as his noble blood;",
  "To him the wit of Greece and Rome was known,",
  "And every author's merit, but his own.",
  "Such late was Walsh--the Muse's judge and friend,",
  "Who justly knew to blame or to commend;",
  "To failings mild, but zealous for desert;",
  "The clearest head, and the sincerest heart.",
  "This humble praise, lamented Shade! receive,",
  "This praise at least a grateful Muse may give:",
  "The Muse, whose early voice you taught to sing,",
  "Prescribed her heights, and pruned her tender wing,",
  "(Her guide now lost) no more attempts to rise,",
  "But in low numbers short excursions tries:",
  "Content, if hence the unlearn'd their wants may view,",
  "The learn'd reflect on what before they knew:",
  "Careless of censure, nor too fond of fame;",
  "Still pleased to praise, yet not afraid to blame;",
  "Averse alike to flatter, or offend;",
  "Not free from faults, nor yet too vain to mend.",
  ""
]