module.exports = [
  "Since the refinement of this polish'd age",
  "Has swept immoral raillery from the stage;",
  "Since taste has now expung'd licentious wit,",
  "Which stamp'd disgrace on all an author writ;",
  "Since, now, to please with purer scenes we seek,",
  "Nor dare to call the blush from Beauty's cheek;",
  "Oh! let the modest Muse some pity claim,",
  "And meet indulgence--though she find not fame.",
  "Still, not for _her_ alone, we wish respect,",
  "_Others_ appear more conscious of defect:",
  "To-night no _vet'ran Roscii_ you behold,",
  "In all the arts of scenic action old;",
  "No COOKE, no KEMBLE, can salute you here,",
  "No SIDDONS draw the sympathetic tear;",
  "To-night you throng to witness the _début_",
  "Of embryo Actors, to the Drama new:",
  "Here, then, our almost unfledg'd wings we try;",
  "Clip not our _pinions_, ere the _birds can fly_:",
  "Failing in this our first attempt to soar,",
  "Drooping, alas! we fall to rise no more.",
  "Not one poor trembler, only, fear betrays,",
  "Who hopes, yet almost dreads to meet your praise;",
  "But all our Dramatis Personæ wait,",
  "In fond suspense this crisis of their fate.",
  "No venal views our progress can retard,",
  "Your generous plaudits are our sole reward;",
  "For these, each _Hero_ all his power displays,",
  "Each timid _Heroine_ shrinks before your gaze:",
  "Surely the last will some protection find?",
  "None, to the softer sex, can prove unkind:",
  "While Youth and Beauty form the female shield,",
  "The sternest Censor to the fair must yield.",
  "Yet, should our feeble efforts nought avail,",
  "Should, _after all_, our best endeavours fail;",
  "Still, let some mercy in your bosoms live,",
  "And, if you can't applaud, at least _forgive_.",
  ""
]