module.exports = [
  "I WAS not apprenticed nor ever dwelt in famous",
  "     Lincolnshire;",
  "I've served one master ill and well much more than",
  "     seven year;",
  "And never took up to poaching as you shall quickly",
  "     find;",
  "  But 'tis my delight of a shiny night in the season",
  "     of the year.",
  "",
  "I roamed where nobody had a right but keepers and",
  "     squires, and there",
  "I sought for nests, wild flowers, oak sticks, and",
  "     moles, both far and near.",
  "And had to run from farmers, and learnt the",
  "     Lincolnshire song:",
  "    \"Oh, 'tis my delight of a shiny night in the",
  "     season of the year.\"",
  "",
  "I took those walks years after, talking with friend",
  "     or dear,",
  "Or solitary musing; but when the moon shone clear",
  "I had no joy or sorrow that could not be expressed",
  "By \"'Tis my delight of a shiny night in the",
  "     season of the year.\"",
  "",
  "Since then I've thrown away a chance to fight a",
  "     gamekeeper;",
  "And I less often trespass, and what I see or hear",
  "Is mostly from the road or path by day: yet still",
  "     I sing:",
  "    \"Oh, 'tis my delight of a shiny night in the",
  "     season of the year.\"",
  "",
  "For if I am contented, at home or anywhere,",
  "Or if I sigh for I know not what, or my heart",
  "     beats with some fear,",
  "It is a strange kind of delight to sing or whistle just:",
  "    \"Oh, 'tis my delight of a shiny night in the",
  "     season of the year.\"",
  "",
  "And with this melody on my lips and no one by to",
  "     care,",
  "Indoors, or out on shiny nights or dark in open air,",
  "I am for a moment made a man that sings out of",
  "     his heart:",
  "    \"Oh, 'tis my delight of a shiny night in the",
  "     season of the year.\"",
  ""
]