module.exports = [
  "And wilt thou weep when I am low?",
  "  Sweet lady! speak those words again:",
  "Yet if they grieve thee, say not so--",
  "  I would not give that bosom pain.",
  "",
  "My heart is sad, my hopes are gone,",
  "  My blood runs coldly through my breast;",
  "And when I perish, thou alone",
  "  Wilt sigh above my place of rest.",
  "",
  "And yet, methinks, a gleam of peace",
  "  Doth through my cloud of anguish shine:",
  "And for a while my sorrows cease,",
  "  To know thy heart hath felt for mine.",
  "",
  "Oh lady! blessèd be that tear--",
  "  It falls for one who cannot weep;",
  "Such precious drops are doubly dear",
  "  To those whose eyes no tear may steep.",
  "",
  "Sweet lady! once my heart was warm",
  "  With every feeling soft as thine;",
  "But Beauty's self hath ceased to charm",
  "  A wretch created to repine.",
  "",
  "Yet wilt thou weep when I am low?",
  "Sweet lady! speak those words again:",
  "Yet if they grieve thee, say not so--",
  "I would not give that bosom pain.",
  ""
]