module.exports = [
  "Through thick Arcadian woods a hunter went,",
  "Following the beasts upon a fresh spring day;",
  "But since his horn-tipped bow but seldom bent,",
  "Now at the noontide nought had happed to slay,",
  "Within a vale he called his hounds away,",
  "Hearkening the echoes of his lone voice cling",
  "About the cliffs and through the beech-trees ring.",
  "",
  "But when they ended, still awhile he stood,",
  "And but the sweet familiar thrush could hear,",
  "And all the day-long noises of the wood,",
  "And o'er the dry leaves of the vanished year",
  "His hounds' feet pattering as they drew anear,",
  "And heavy breathing from their heads low hung,",
  "To see the mighty corner bow unstrung.",
  "",
  "Then smiling did he turn to leave the place,",
  "But with his first step some new fleeting thought",
  "A shadow cast across his sun-burnt face;",
  "I think the golden net that April brought",
  "From some warm world his wavering soul had caught;",
  "For, sunk in vague sweet longing, did he go",
  "Betwixt the trees with doubtful steps and slow.",
  "",
  "Yet howsoever slow he went, at last",
  "The trees grew sparser, and the wood was done;",
  "Whereon one farewell backward look he cast,",
  "Then, turning round to see what place was won,",
  "With shaded eyes looked underneath the sun,",
  "And o'er green meads and new-turned furrows brown",
  "Beheld the gleaming of King Schœneus' town.",
  "",
  "So thitherward he turned, and on each side",
  "The folk were busy on the teeming land,",
  "And man and maid from the brown furrows cried,",
  "Or midst the newly blossomed vines did stand,",
  "And as the rustic weapon pressed the hand",
  "Thought of the nodding of the well-filled ear,",
  "Or how the knife the heavy bunch should shear.",
  "",
  "Merry it was: about him sung the birds,",
  "The spring flowers bloomed along the firm dry road,",
  "The sleek-skinned mothers of the sharp-horned herds",
  "Now for the barefoot milking-maidens lowed;",
  "While from the freshness of his blue abode,",
  "Glad his death-bearing arrows to forget,",
  "The broad sun blazed, nor scattered plagues as yet.",
  "",
  "Through such fair things unto the gates he came,",
  "And found them open, as though peace were there;",
  "Wherethrough, unquestioned of his race or name,",
  "He entered, and along the streets 'gan fare,",
  "Which at the first of folk were well-nigh bare;",
  "But pressing on, and going more hastily,",
  "",
  "Men hurrying too he 'gan at last to see.",
  "Following the last of these he still pressed on,",
  "Until an open space he came unto,",
  "Where wreaths of fame had oft been lost and won,",
  "For feats of strength folks there were wont to do.",
  "And now our hunter looked for something new,",
  "Because the whole wide space was bare, and stilled",
  "The high seats were, with eager people filled.",
  "",
  "There with the others to a seat he gat,",
  "Whence he beheld a broidered canopy,",
  "'Neath which in fair array King Schœneus sat",
  "Upon his throne with councillors thereby;",
  "And underneath his well-wrought seat and high,",
  "He saw a golden image of the sun,",
  "A silver image of the Fleet-foot One.",
  "",
  "A brazen altar stood beneath their feet",
  "Whereon a thin flame flicker'd in the wind;",
  "Nigh this a herald clad in raiment meet",
  "Made ready even now his horn to wind,",
  "By whom a huge man held a sword, entwin'd",
  "With yellow flowers; these stood a little space",
  "From off the altar, nigh the starting place.",
  "",
  "And there two runners did the sign abide,",
  "Foot set to foot,--a young man slim and fair,",
  "Crisp-hair'd, well knit, with firm limbs often tried",
  "In places where no man his strength may spare:",
  "Dainty his thin coat was, and on his hair.",
  "A golden circlet of renown he wore,",
  "And in his hand an olive garland bore.",
  "",
  "But on this day with whom shall he contend?",
  "A maid stood by him like Diana clad",
  "When in the woods she lists her bow to bend,",
  "Too fair for one to look on and be glad,",
  "Who scarcely yet has thirty summers had,",
  "If he must still behold her from afar;",
  "Too fair to let the world live free from war.",
  "",
  "She seem'd all earthly matters to forget;",
  "Of all tormenting lines her face was clear;",
  "Her wide gray eyes upon the goal were set",
  "Calm and unmov'd as though no soul were near.",
  "But her foe trembled as a man in fear,",
  "Nor from her loveliness one moment turn'd",
  "His anxious face with fierce desire that burn'd.",
  "",
  "Now through the hush there broke the trumpet's clang",
  "Just as the setting sun made eventide.",
  "Then from light feet a spurt of dust there sprang,",
  "And swiftly were they running side by side;",
  "But silent did the thronging folk abide",
  "Until the turning-post was reach'd at last,",
  "And round about it still abreast they passed.",
  "",
  "But when the people saw how close they ran,",
  "When half-way to the starting-point they were,",
  "A cry of joy broke forth, whereat the man",
  "Headed the white-foot runner, and drew near",
  "Unto the very end of all his fear;",
  "And scarce his straining feet the ground could feel,",
  "And bliss unhop'd for o'er his heart 'gan steal.",
  "",
  "But 'midst the loud victorious shouts he heard",
  "Her footsteps drawing nearer, and the sound",
  "Of fluttering raiment, and thereat afeard",
  "His flush'd and eager face he turn'd around,",
  "And even then he felt her past him bound",
  "Fleet as the wind, but scarcely saw her there",
  "Till on the goal she laid her fingers fair.",
  "",
  "There stood she breathing like a little child",
  "Amid some warlike clamour laid asleep,",
  "For no victorious joy her red lips smil'd,",
  "Her cheek its wonted freshness did but keep;",
  "No glance lit up her clear gray eyes and deep,",
  "Though some divine thought soften'd all her face",
  "As once more rang the trumpet through the place.",
  "",
  "But her late foe stopp'd short amidst his course,",
  "One moment gaz'd upon her piteously.",
  "Then with a groan his lingering feet did force",
  "To leave the spot whence he her eyes could see;",
  "And, changed like one who knows his time must be",
  "But short and bitter, without any word",
  "He knelt before the bearer of the sword;",
  "",
  "Then high rose up the gleaming deadly blade,",
  "Bar'd of its flowers, and through the crowded place",
  "Was silence now, and midst of it the maid",
  "Went by the poor wretch at a gentle pace,",
  "And he to hers upturn'd his sad white face;",
  "Nor did his eyes behold another sight",
  "Ere on his soul there fell eternal light.",
  "",
  "So was the pageant ended, and all folk",
  "Talking of this and that familiar thing",
  "In little groups from that sad concourse broke,",
  "For now the shrill bats were upon the wing,",
  "And soon dark night would slay the evening,",
  "And in dark gardens sang the nightingale",
  "Her little-heeded, oft-repeated tale.",
  "",
  "And with the last of all the hunter went,",
  "Who, wondering at the strange sight he had seen,",
  "Prayed an old man to tell him what it meant,",
  "Both why the vanquished man so slain had been,",
  "And if the maiden were an earthly queen,",
  "Or rather what much more she seemed to be,",
  "No sharer in this world's mortality.",
  "",
  "\"Stranger,\" said he, \"I pray she soon may die",
  "Whose lovely youth has slain so many an one!",
  "King Schœneus' daughter is she verily,",
  "Who when her eyes first looked upon the sun",
  "Was fain to end her life but new begun,",
  "For he had vowed to leave but men alone",
  "Sprung from his loins when he from earth was gone.",
  "",
  "\"Therefore he bade one leave her in the wood,",
  "And let wild things deal with her as they might,",
  "But this being done, some cruel god thought good",
  "To save her beauty in the world's despite;",
  "Folk say that her, so delicate and white",
  "As now she is, a rough root-grubbing bear",
  "Amidst her shapeless cubs at first did rear.",
  "",
  "\"In course of time the woodfolk slew her nurse,",
  "And to their rude abode the youngling brought,",
  "And reared her up to be a kingdom's curse;",
  "Who grown a woman, of no kingdom thought,",
  "But armed and swift, 'mid beasts destruction wrought,",
  "Nor spared two shaggy centaur kings to slay",
  "To whom her body seemed an easy prey.",
  "",
  "\"So to this city, led by fate, she came",
  "Whom known by signs, whereof I cannot tell,",
  "King Schœneus for his child at last did claim.",
  "Nor otherwhere since that day doth she dwell",
  "Sending too many a noble soul to hell--",
  "What! shine eyes glisten! what then, thinkest thou",
  "Her shining head unto the yoke to bow?",
  "",
  "\"Listen, my son, and love some other maid",
  "For she the saffron gown will never wear,",
  "And on no flower-strewn couch shall she be laid,",
  "Nor shall her voice make glad a lover's ear:",
  "Yet if of Death thou hast not any fear,",
  "Yea, rather, if thou lov'st her utterly,",
  "Thou still may'st woo her ere thou com'st to die,",
  "",
  "\"Like him that on this day thou sawest lie dead;",
  "For fearing as I deem the sea-born one;",
  "The maid has vowed e'en such a man to wed",
  "As in the course her swift feet can outrun,",
  "But whoso fails herein, his days are done:",
  "He came the nighest that was slain to-day,",
  "Although with him I deem she did but play.",
  "",
  "\"Behold, such mercy Atalanta gives",
  "To those that long to win her loveliness;",
  "Be wise! be sure that many a maid there lives",
  "Gentler than she, of beauty little less,",
  "Whose swimming eyes thy loving words shall bless,",
  "When in some garden, knee set close to knee,",
  "Thou sing'st the song that love may teach to thee.\"",
  "",
  "So to the hunter spake that ancient man,",
  "And left him for his own home presently:",
  "But he turned round, and through the moonlight wan",
  "Reached the thick wood, and there 'twixt tree and tree",
  "Distraught he passed the long night feverishly,",
  "'Twixt sleep and waking, and at dawn arose",
  "To wage hot war against his speechless foes.",
  "",
  "There to the hart's flank seemed his shaft to grow,",
  "As panting down the broad green glades he flew,",
  "There by his horn the Dryads well might know",
  "His thrust against the bear's heart had been true,",
  "And there Adonis' bane his javelin slew,",
  "But still in vain through rough and smooth he went,",
  "For none the more his restlessness was spent.",
  "",
  "So wandering, he to Argive cities came,",
  "And in the lists with valiant men he stood,",
  "And by great deeds he won him praise and fame,",
  "And heaps of wealth for little-valued blood;",
  "But none of all these things, or life, seemed good",
  "Unto his heart, where still unsatisfied",
  "A ravenous longing warred with fear and pride.",
  "",
  "Therefore it happed when but a month had gone",
  "Since he had left King Schœneus' city old,",
  "In hunting-gear again, again alone",
  "The forest-bordered meads did he behold,",
  "Where still mid thoughts of August's quivering gold",
  "Folk hoed the wheat, and clipped the vine in trust",
  "Of faint October's purple-foaming must.",
  "",
  "And once again he passed the peaceful gate,",
  "While to his beating heart his lips did lie,",
  "That owning not victorious love and fate,",
  "Said, half aloud, \"And here too must I try,",
  "To win of alien men the mastery,",
  "And gather for my head fresh meed of fame",
  "And cast new glory on my father's name.\"",
  "",
  "In spite of that, how beat his heart, when first",
  "Folk said to him, \"And art thou come to see",
  "That which still makes our city's name accurst",
  "Among all mothers for its cruelty?",
  "Then know indeed that fate is good to thee",
  "Because to-morrow a new luckless one",
  "Against the white-foot maid is pledged to run.\"",
  "",
  "So on the morrow with no curious eyes",
  "As once he did, that piteous sight he saw,",
  "Nor did that wonder in his heart arise",
  "As toward the goal the conquering maid 'gan draw,",
  "Nor did he gaze upon her eyes with awe,",
  "Too full the pain of longing filled his heart",
  "For fear or wonder there to have a part.",
  "",
  "But O, how long the night was ere it went!",
  "How long it was before the dawn begun",
  "Showed to the wakening birds the sun's intent",
  "That not in darkness should the world be done!",
  "And then, and then, how long before the sun",
  "Bade silently the toilers of the earth",
  "Get forth to fruitless cares or empty mirth!",
  "",
  "And long it seemed that in the market-place",
  "He stood and saw the chaffering folk go by,",
  "Ere from the ivory throne King Schœneus' face",
  "Looked down upon the murmur royally,",
  "But then came trembling that the time was nigh",
  "When he midst pitying looks his love must claim,",
  "And jeering voices must salute his name.",
  "",
  "But as the throng he pierced to gain the throne,",
  "His alien face distraught and anxious told",
  "What hopeless errand he was bound upon,",
  "And, each to each, folk whispered to behold",
  "His godlike limbs; nay, and one woman old",
  "As he went by must pluck him by the sleeve",
  "And pray him yet that wretched love to leave.",
  "",
  "For sidling up she said, \"Canst thou live twice,",
  "Fair son? canst thou have joyful youth again,",
  "That thus thou goest to the sacrifice",
  "Thyself the victim? nay then, all in vain",
  "Thy mother bore her longing and her pain,",
  "And one more maiden on the earth must dwell",
  "Hopeless of joy, nor fearing death and hell.",
  "",
  "\"O, fool, thou knowest not the compact then",
  "That with the three-formed goddess she has made",
  "To keep her from the loving lips of men,",
  "And in no saffron gown to be arrayed,",
  "And therewithal with glory to be paid,",
  "And love of her the moonlit river sees",
  "White 'gainst the shadow of the formless trees.",
  "",
  "\"Come back, and I myself will pray for thee",
  "Unto the sea-born framer of delights,",
  "To give thee her who on the earth may be",
  "The fairest stirrer up to death and fights,",
  "To quench with hopeful days and joyous nights",
  "The flame that doth thy youthful heart consume:",
  "Come back, nor give thy beauty to the tomb.\"",
  "",
  "How should he listen to her earnest speech?",
  "Words, such as he not once or twice had said",
  "Unto himself, whose meaning scarce could reach",
  "The firm abode of that sad hardihead--",
  "He turned about, and through the marketstead",
  "Swiftly he passed, until before the throne",
  "In the cleared space he stood at last alone.",
  "",
  "Then said the King, \"Stranger, what dost thou here?",
  "Have any of my folk done ill to thee?",
  "Or art thou of the forest men in fear?",
  "Or art thou of the sad fraternity",
  "Who still will strive my daughter's mates to be,",
  "Staking their lives to win an earthly bliss,",
  "The lonely maid, the friend of Artemis?\"",
  "",
  "\"O King,\" he said, \"thou sayest the word indeed;",
  "Nor will I quit the strife till I have won",
  "My sweet delight, or death to end my need.",
  "And know that I am called Milanion,",
  "Of King Amphidamas the well-loved son:",
  "So fear not that to thy old name, O King,",
  "Much loss or shame my victory will bring.\"",
  "",
  "\"Nay, Prince,\" said Schœneus, \"welcome to this land",
  "Thou wert indeed, if thou wert here to try",
  "Thy strength 'gainst some one mighty of his hand;",
  "Nor would we grudge thee well-won mastery.",
  "But now, why wilt thou come to me to die,",
  "And at my door lay down thy luckless head,",
  "Swelling the band of the unhappy dead,",
  "",
  "\"Whose curses even now my heart doth fear?",
  "Lo, I am old, and know what life can be,",
  "And what a bitter thing is death anear.",
  "O, Son! be wise, and harken unto me,",
  "And if no other can be dear to thee,",
  "At least as now, yet is the world full wide,",
  "And bliss in seeming hopeless hearts may hide:",
  "",
  "\"But if thou losest life, then all is lost.\"",
  "\"Nay, King,\" Milanion said, \"thy words are vain.",
  "Doubt not that I have counted well the cost.",
  "But say, on what day wilt thou that I gain",
  "Fulfilled delight, or death to end my pain.",
  "Right glad were I if it could be to-day,",
  "And all my doubts at rest for ever lay.\"",
  "",
  "\"Nay,\" said King Schœneus, \"thus it shall not be,",
  "But rather shalt thou let a month go by,",
  "And weary with thy prayers for victory",
  "What god thou know'st the kindest and most nigh.",
  "So doing, still perchance thou shalt not die:",
  "And with my goodwill wouldst thou have the maid,",
  "For of the equal gods I grow afraid.",
  "",
  "\"And until then, O Prince, be thou my guest, .",
  "And all these troublous things awhile forget.\"",
  "\"Nay,\" said he, \"couldst thou give my soul good rest,",
  "And on mine head a sleepy garland set,",
  "Then had I 'scaped the meshes of the net,",
  "Nor should thou hear from me another word;",
  "But now, make sharp thy fearful heading-sword.",
  "",
  "\"Yet will I do what son of man may do,",
  "And promise all the gods may most desire,",
  "That to myself I may at least be true;",
  "And on that day my heart and limbs so tire,",
  "With utmost strain and measureless desire,",
  "That, at the worst, I may but fall asleep",
  "When in the sunlight round that sword shall sweep. \"",
  "",
  "He went therewith, nor anywhere would bide,",
  "But unto Argos restlessly did wend;",
  "And there, as one who lays all hope aside,",
  "Because the leech has said his life must end,",
  "Silent farewell he bade to foe and friend,",
  "And took his way unto the restless sea,",
  "For there he deemed his rest and help might be.",
  "",
  "Upon the shore of Argolis there stands",
  "A temple to the goddess that he sought,",
  "That, turned unto the lion-bearing lands,",
  "Fenced from the east, of cold winds hath no thought,",
  "Though to no homestead there the sheaves are brought,",
  "No groaning press torments the close-clipped murk,",
  "Lonely the fane stands, far from all men's work.",
  "",
  "Pass through a close, set thick with myrtle-trees,",
  "Through the brass doors that guard the holy place,",
  "And entering, hear the washing of the seas",
  "That twice a-day rise high above the base,",
  "And with the south-west urging them, embrace",
  "The marble feet of her that standeth there",
  "That shrink not, naked though they be and fair.",
  "",
  "Small is the fane through which the sea-wind sings",
  "About Queen Venus' well-wrought image white,",
  "But hung around are many precious things,",
  "The gifts of those who, longing for delight,",
  "Have hung them there within the goddess' sight,",
  "And in return have taken at her hands",
  "The living treasures of the Grecian lands.",
  "",
  "And thither now has come Milanion,",
  "And showed unto the priests' wide open eyes",
  "Gifts fairer than all those that there have shone,",
  "Silk cloths, inwrought with Indian fantasies,",
  "And bowls inscribed with sayings of the wise",
  "Above the deeds of foolish living things;",
  "And mirrors fit to be the gifts of kings.",
  "",
  "And now before the Sea-born One he stands,",
  "By the sweet veiling smoke made dim and soft,",
  "And while the incense trickles from his hands,",
  "And while the odorous smoke-wreaths hang aloft,",
  "Thus doth he pray to her: \"O Thou, who oft",
  "Hast holpen man and maid in their distress",
  "Despise me not for this my wretchedness!",
  "",
  "\"O goddess, among us who dwelt below,",
  "Kings and great men, great for a little while,",
  "Have pity on the lowly heads that bow,",
  "Nor hate the hearts that love them without guile;",
  "Wilt thou be worse than these, and is thy smile",
  "A vain device of him who set thee here,",
  "An empty dream of some artificer?",
  "",
  "\"O great one, some men love, and are ashamed;",
  "Some men are weary of the bonds of love;",
  "Yea, and by some men lightly art thou blamed,",
  "That from thy toils their lives they cannot move,",
  "And 'mid the ranks of men their manhood prove.",
  "Alas! O goddess, if thou slayest me,",
  "What new immortal can I serve but thee?",
  "",
  "\"Think then, will it bring honour to thy head",
  "If folk say, 'Everything aside he cast",
  "And to all fame and honour was he dead,",
  "And to his one hope now is dead at last,",
  "Since all unholpen he is gone and past;",
  "Ah, the gods love not man, for certainly,",
  "He to his helper did not cease to cry.'",
  "",
  "\"Nay, but thou wilt help; they who died before",
  "Not single-hearted as I deem came here,",
  "Therefore unthanked they laid their gifts before",
  "Thy stainless feet, still shivering with their fear,",
  "Lest in their eyes their true thought might appear,",
  "Who sought to be the lords of that fair town,",
  "Dreaded of men and winners of renown.",
  "",
  "\"O Queen, thou knowest I pray not for this:",
  "O set us down together in some place",
  "Where not a voice can break our heaven of bliss,",
  "Where nought but rocks and I can see her face,",
  "Softening beneath the marvel of thy grace,",
  "Where not a foot our vanished steps can track--",
  "The golden age, the golden age come back!",
  "",
  "\"O fairest, hear me now who do thy will,",
  "Plead for thy rebel that she be not slain,",
  "But live and love and be thy servant still;",
  "Ah, give her joy and take away my pain,",
  "And thus two long-enduring servants gain.",
  "An easy thing this is to do for me,",
  "What need of my vain words to weary thee.",
  "",
  "\"But none the less, this place will I not leave",
  "Until I needs must go my death to meet,",
  "Or at thy hands some happy sign receive",
  "That in great joy we twain may one day greet",
  "Thy presence here and kiss thy silver feet,",
  "Such as we deem thee, fair beyond all words,",
  "Victorious o'er our servants and our lords.\"",
  "",
  "Then from the altar back a space he drew,",
  "But from the Queen turned not his face away,",
  "But 'gainst a pillar leaned, until the blue",
  "That arched the sky, at ending of the day,",
  "Was turned to ruddy gold and changing gray,",
  "And clear, but low, the nigh-ebbed windless sea",
  "In the still evening murmured ceaselessly.",
  "",
  "And there he stood when all the sun was down,",
  "Nor had he moved, when the dim golden light,",
  "Like the fair lustre of a godlike town,",
  "Had left the world to seeming hopeless night,",
  "Nor would he move the more when wan moonlight",
  "Streamed through the pillows for a little while,",
  "And lighted up the white Queen's changeless smile.",
  "",
  "Nought noted he the shallow-flowing sea",
  "As step by step it set the wrack a-swim;",
  "The yellow torchlight nothing noted he",
  "Wherein with fluttering gown and half-bared limb",
  "The temple damsels sung their midnight hymn;",
  "And nought the doubled stillness of the fane",
  "When they were gone and all was hushed again.",
  "",
  "But when the waves had touched the marble base,",
  "And steps the fish swim over twice a-day,",
  "The dawn beheld him sunken in his place",
  "Upon the floor; and sleeping there he lay,",
  "Not heeding aught the little jets of spray",
  "The roughened sea brought nigh, across him cast,",
  "For as one dead all thought from him had passed.",
  "",
  "Yet long before the sun had showed his head,",
  "Long ere the varied hangings on the wall",
  "Had gained once more their blue and green and red,",
  "He rose as one some well-known sign doth call",
  "When war upon the city's gates doth fall,",
  "And scarce like one fresh risen out of sleep,",
  "He 'gan again his broken watch to keep.",
  "",
  "Then he turned round; not for the sea-gull's cry",
  "That wheeled above the temple in his flight,",
  "Not for the fresh south wind that lovingly",
  "Breathed on the new-born day and dying night,",
  "But some strange hope 'twixt fear and great delight",
  "Drew round his face, now flushed, now pale and wan,",
  "And still constrained his eyes the sea to scan.",
  "",
  "Now a faint light lit up the southern sky,",
  "Not sun or moon, for all the world was gray,",
  "But this a bright cloud seemed, that drew anigh,",
  "Lighting the dull waves that beneath it lay",
  "As toward the temple still it took its way,",
  "And still grew greater, till Milanion",
  "Saw nought for dazzling light that round him shone.",
  "",
  "But as he staggered with his arms outspread,",
  "Delicious unnamed odours breathed around,",
  "For languid happiness he bowed his head,",
  "And with wet eyes sank down upon the ground,",
  "Nor wished for aught, nor any dream he found",
  "To give him reason for that happiness,",
  "Or make him ask more knowledge of his bliss.",
  "",
  "At last his eyes were cleared, and he could see",
  "Through happy tears the goddess face to face",
  "With that faint image of Divinity,",
  "Whose well-wrought smile and dainty changeless grace",
  "Until that morn so gladdened all the place;",
  "Then, he unwitting cried aloud her name",
  "And covered up his eyes for fear and shame.",
  "",
  "But through the stillness he her voice could hear",
  "Piercing his heart with joy scarce bearable,",
  "That said, \"Milanion, wherefore dost thou fear,",
  "I am not hard to those who love me well;",
  "List to what I a second time will tell,",
  "And thou mayest hear perchance, and live to save",
  "The cruel maiden from a loveless grave.",
  "",
  "\"See, by my feet three golden apples lie--",
  "Such fruit among the heavy roses falls,",
  "Such fruit my watchful damsels carefully",
  "Store up within the best loved of my walls,",
  "Ancient Damascus, where the lover calls",
  "Above my unseen head, and faint and light",
  "The rose-leaves flutter round me in the night.",
  "",
  "\"And note, that these are not alone most fair",
  "With heavenly gold, but longing strange they bring",
  "Unto the hearts of men, who will not care",
  "Beholding these, for any once-loved thing",
  "Till round the shining sides their fingers cling.",
  "And thou shalt see thy well-girt swift-foot maid",
  "By sight of these amidst her glory stayed.",
  "",
  "\"For bearing these within a scrip with thee,",
  "When first she heads thee from the starting-place",
  "Cast down the first one for her eyes to see,",
  "And when she turns aside make on apace,",
  "And if again she heads thee in the race",
  "Spare not the other two to cast aside",
  "If she not long enough behind will bide.",
  "",
  "\"Farewell, and when has come the happy time",
  "That she Diana's raiment must unbind",
  "And all the world seems blessed with Saturn's clime,",
  "And thou with eager arms about her twined",
  "Beholdest first her gray eyes growing kind,",
  "Surely, O trembler, thou shalt scarcely then",
  "Forget the Helper of unhappy men.\"",
  "",
  "Milanion raised his head at this last word",
  "For now so soft and kind she seemed to be",
  "No longer of her Godhead was he feared;",
  "Too late he looked; for nothing could he see",
  "But the white image glimmering doubtfully",
  "In the departing twilight cold and gray,",
  "And those three apples on the step that lay.",
  "",
  "These then he caught up quivering with delight,",
  "Yet fearful lest it all might be a dream;",
  "And though aweary with the watchful night,",
  "And sleepless nights of longing, still did deem",
  "He could not sleep; but yet the first sunbeam",
  "That smote the fane across the heaving deep",
  "Shone on him laid in calm, untroubled sleep.",
  "",
  "But little ere the noontide did he rise,",
  "And why he felt so happy scarce could tell",
  "Until the gleaming apples met his eyes.",
  "Then leaving the fair place where this befell",
  "Oft he looked back as one who loved it well,",
  "Then homeward to the haunts of men, 'gan wend",
  "To bring all things unto a happy end.",
  "",
  "Now has the lingering month at last gone by,",
  "Again are all folk round the running place,",
  "Nor other seems the dismal pageantry",
  "Than heretofore, but that another face",
  "Looks o'er the smooth course ready for the race,",
  "For now, beheld of all, Milanion",
  "Stands on the spot he twice has looked upon.",
  "",
  "But yet--what change is this that holds the maid?",
  "Does she indeed see in his glittering eye",
  "More than disdain of the sharp shearing blade,",
  "Some happy hope of help and victory?",
  "The others seem'd to say, \"We come to die;",
  "Look down upon us for a little while,",
  "That, dead, we may bethink us of thy smile.\"",
  "",
  "But he--what look of mastery was this",
  "He cast on her? why were his lips so red;",
  "Why was his face so flush'd with happiness?",
  "So looks not one who deems himself but dead,",
  "E'en if to death he bows a willing head;",
  "So rather looks a god well pleas'd to find",
  "Some earthly damsel fashion'd to his mind,",
  "",
  "Why must she drop her lids before his gaze,",
  "And even as she casts adown her eyes",
  "Redden to note his eager glance of praise,",
  "And wish that she were clad in other guise?",
  "Why must the memory to her heart arise",
  "Of things unnoticed when they first were heard,",
  "Some lover's song, some answering maiden's word?",
  "",
  "What makes these longings, vague--without a name,",
  "And this vain pity never felt before,",
  "This sudden languor, this contempt of fame,",
  "This tender sorrow for the time past o'er,",
  "These doubts that grow each minute more and more?",
  "Why does she tremble as the time grows near,",
  "And weak defeat and woeful victory fear?",
  "",
  "But while she seem'd to hear her beating heart,",
  "Above their heads the trumpet blast rang out",
  "And forth they sprang, and she must play her part;",
  "Then flew her white feet, knowing not a doubt,",
  "Though, slackening once, she turn'd her head about,",
  "But then she cried aloud and faster fled",
  "Than e'er before, and all men deemed him dead.",
  "",
  "But with no sound he raised aloft his hand,",
  "And thence what seemed a ray of light there flew",
  "And past the maid rolled on along the sand;",
  "Then trembling she her feet together drew",
  "And in her heart a strong desire there grew",
  "To have the toy, some god she thought had given",
  "That gift to her, to make of earth a heaven.",
  "",
  "Then from the course with eager steps she ran,",
  "And in her odorous bosom laid the gold.",
  "But when she turned again, the great-limbed man,",
  "Now well ahead she failed not to behold,",
  "And mindful of her glory waxing cold,",
  "Sprang up and followed him in hot pursuit,",
  "Though with one hand she touched the golden fruit.",
  "",
  "Note, too, the bow that she was wont to bear",
  "She laid aside to grasp the glittering prize,",
  "And o'er her shoulder from the quiver fair",
  "Three arrows fell and lay before her eyes",
  "Unnoticed, as amidst the people's cries",
  "She sprang to head the strong Milanion,",
  "Who now the turning-post had well-nigh won.",
  "",
  "But as he set his mighty hand on it",
  "White fingers underneath his own were laid,",
  "And white limbs from his dazzled eyes did flit,",
  "Then he the second fruit cast by the maid:",
  "She ran awhile, and then as one afraid",
  "Wavered and stopped, and turned and made no stay,",
  "Until the globe with its bright fellow lay.",
  "",
  "Then, as a troubled glance she cast around,",
  "Now far ahead the Argive could she see,",
  "And in her garment's hem one hand she wound",
  "To keep the double prize, and strenuously",
  "Sped o'er the course, and little doubt had she",
  "To win the day, though now but scanty space",
  "Was left betwixt him and the winning place.",
  "",
  "Short was the way unto such wingèd feet,",
  "Quickly she gained upon him till at last",
  "He turned about her eager eyes to meet",
  "And from his hand the third fair apple cast.",
  "She wavered not, but turned and ran so fast",
  "After the prize that should her bliss fulfil,",
  "That in her hand it lay ere it was still.",
  "",
  "Nor did she rest, but turned about to win",
  "Once more, an unblest woeful victory--",
  "And yet--and yet--why does her breath begin",
  "To fail her, and her feet drag heavily?",
  "Why fails she now to see if far or nigh",
  "The goal is? why do her gray eyes grow dim?",
  "Why do these tremors run through every limb?",
  "",
  "She spreads her arms abroad some stay to find",
  "Else must she fall, indeed, and findeth this,",
  "A strong man's arms about her body twined.",
  "Nor may she shudder now to feel his kiss,",
  "So wrapped she is in new unbroken bliss:",
  "Made happy that the foe the prize hath won,",
  "She weeps glad tears for all her glory done.",
  "",
  "Shatter the trumpet, hew adown the posts!",
  "Upon the brazen altar break the sword,",
  "And scatter incense to appease the ghosts",
  "Of those who died here by their own award.",
  "Bring forth the image of the mighty Lord,",
  "And her who unseen o'er the runners hung,",
  "And did a deed for ever to be sung.",
  "",
  "Here are the gathered folk; make no delay,",
  "Open King Schœneus' well-filled treasury,",
  "Bring out the gifts long hid from light of day,",
  "The golden bowls o'erwrought with imagery,",
  "Gold chains, and unguents brought from over sea,",
  "The saffron gown the old Phœnician brought,",
  "Within the temple of the Goddess wrought.",
  "",
  "O ye, O damsels, who shall never see",
  "Her, that Love's servant bringeth now to you,",
  "Returning from another victory,",
  "In some cool bower do all that now is due!",
  "Since she in token of her service new",
  "Shall give to Venus offerings rich enow,",
  "Her maiden zone, her arrows and her bow.",
  ""
]