module.exports = [
  "Away, away, ye notes of Woe!",
  "  Be silent, thou once soothing Strain,",
  "Or I must flee from hence--for, oh!",
  "  I dare not trust those sounds again.",
  "To me they speak of brighter days--",
  "  But lull the chords, for now, alas!",
  "I must not think, I may not gaze,",
  "  On what I _am_--on what I _was_.",
  "",
  "The voice that made those sounds more sweet",
  "  Is hushed, and all their charms are fled;",
  "And now their softest notes repeat",
  "  A dirge, an anthem o'er the dead!",
  "Yes, Thyrza! yes, they breathe of thee,",
  "  Belovéd dust! since dust thou art;",
  "And all that once was Harmony",
  "  Is worse than discord to my heart!",
  "",
  "'Tis silent all!--but on my ear",
  "  The well remembered Echoes thrill;",
  "I hear a voice I would not hear,",
  "  A voice that now might well be still:",
  "Yet oft my doubting Soul 'twill shake;",
  "  Ev'n Slumber owns its gentle tone,",
  "Till Consciousness will vainly wake",
  "  To listen, though the dream be flown.",
  "",
  "Sweet Thyrza! waking as in sleep,",
  "  Thou art but now a lovely dream;",
  "A Star that trembled o'er the deep,",
  "  Then turned from earth its tender beam.",
  "But he who through Life's dreary way",
  "  Must pass, when Heaven is veiled in wrath,",
  "Will long lament the vanished ray",
  "  That scattered gladness o'er his path.",
  ""
]