module.exports = [
  "Beautiful Balmoral Castle,",
  "Most handsome to be seen,",
  "Highland home of the Empress of India,",
  "Great Britain's Queen.",
  "",
  "Your woods and waters and",
  "Mountains high are most",
  "Beautiful to see,",
  "Near by Balmoral Castle",
  "And the dark river Dee.",
  "",
  "Then there's the hill of Cairngorm",
  "To be seen from afar,",
  "And the beautiful heathery hills",
  "Of dark Lochnagar,",
  "And the handsome little village-",
  "The Castleton o' Braemar-",
  "Which is most beautiful to see,",
  "Near by Balmoral Castle",
  "And the dark river Dee.",
  "",
  "Then there's the handsome little church",
  "Of Crathie- most beautiful to be seen ;",
  "And the Queen goes there on Sunday",
  "To hear the Word of God Most solemn and serene,",
  "Which is most beautiful to see,",
  "Nor far from Balmoral Castle",
  "And the dark river Dee.",
  "",
  "Then, when she finds herself",
  "At leisure, she goes for to see",
  "Her old female acquaintances",
  "That lives on the river Dee,",
  "And reads the Bible unto them,",
  "Which is most beautiful to see,",
  "Near by Balmoral Castle",
  "And the dark river Dee.",
  ""
]