module.exports = [
  "Before the winter morn,",
  "Before the earliest cock crow,",
  "Jesus Christ was born:",
  "Born in a stable,",
  "Cradled in a manger,",
  "In the world his hands had made",
  "Born a stranger.",
  "",
  "Priest and king lay fast asleep",
  "In Jerusalem;",
  "Young and old lay fast asleep",
  "In crowded Bethlehem;",
  "Saint and angel, ox and ass,",
  "Kept a watch together",
  "Before the Christmas daybreak",
  "In the winter weather.",
  "",
  "Jesus on his mother's breast",
  "In the stable cold,",
  "Spotless lamb of God was he,",
  "Shepherd of the fold:",
  "Let us kneel with Mary maid,",
  "With Joseph bent and hoary,",
  "With saint and angel, ox and ass,",
  "To hail the King of Glory.",
  ""
]