module.exports = [
  "'Twas in the year of 1887, which many people will long remember,",
  "The burning of the Theatre at Exeter on the 5th of September,",
  "Alas! that ever-to-be-remembered and unlucky night,",
  "When one hundred and fifty lost their lives, a most agonising sight.",
  "",
  "The play on this night was called \"Romany Rye,\"",
  "And at act four, scene third, Fire! Fire! was the cry;",
  "And all in a moment flames were seen issuing from the stage,",
  "Then the women screamed frantically, like wild beasts in a cage.",
  "",
  "Then a panic ensued, and each one felt dismayed,",
  "And from the burning building a rush was made;",
  "And soon the theatre was filled with a blinding smoke,",
  "So that the people their way out had to grope.",
  "",
  "The shrieks of those trying to escape were fearful to hear,",
  "Especially the cries of those who had lost their friends most dear;",
  "Oh, the scene was most painful in the London Inn Square,",
  "To see them wringing their hands and tearing their hair!",
  "",
  "And as the flames spread, great havoc they did make,",
  "And the poor souls fought heroically in trying to make their escape;",
  "Oh, it was horrible to see men and women trying to reach the door!",
  "But in many cases death claimed the victory, and their struggles were o'er.",
  "",
  "Alas! 'twas pitiful the shrieks of the audience to hear,",
  "Especially as the flames to them drew near;",
  "Because on every face were depicted despair and woe,",
  "And many of them jumped from the windows into the street below.",
  "",
  "The crushed and charred bodies were carried into London Hotel yard,",
  "And to alleviate their sufferings the doctors tried hard;",
  "But, alas! their attendance on many was thrown away,",
  "But those that survived were conveyed to Exeter Hospital without delay.",
  "",
  "And all those that had their wounds dressed proceeded home,",
  "Accompanied by their friends, and making a loud moan;",
  "While the faces and necks of others were sickening to behold,",
  "Enough to chill one's blood, and make the heart turn cold.",
  "",
  "Alas! words fail to describe the desolation,",
  "And in many homes it will cause great lamentation;",
  "Because human remains are beyond all identification,",
  "Which will cause the relatives of the sufferers to be in great tribulation.",
  "",
  "Oh, Heaven! it must have been an awful sight,",
  "To see the poor souls struggling hard with all their might,",
  "Fighting hard their lives to save,",
  "While many in the smoke and burning flame did madly rave!",
  "",
  "It was the most sickening sight that ever anybody saw,",
  "Human remains, beyond recognition, covered with a heap of straw;",
  "And here and there a body might be seen, and a maimed hand,",
  "Oh, such a sight, that the most hard-hearted person could hardly withstand!",
  "",
  "The number of people in the theatre was between seven and eight thousand,",
  "But alas! one hundred and fifty by the fire have been found dead;",
  "And the most lives were lost on the stairs leading from the gallery,",
  "And these were roasted to death, which was sickening to see.",
  "",
  "The funerals were conducted at the expense of the local authority,",
  "And two hours and more elapsed at the mournful ceremony;",
  "And at one grave there were two thousand people, a very great crowd,",
  "And most of the men were bareheaded ad weeping aloud.",
  "",
  "Alas! many poor children have been bereft of their fathers and mothers,",
  "Who will be sorely missed by little sisters and brothers;",
  "But, alas! unto them they can ne'er return again,",
  "Therefore the poor little innocents must weep for them in vain.",
  "",
  "I hope all kind Christian souls will help the friends of the dead,",
  "Especially those that have lost the winners of their bread;",
  "And if they do, God surely will them bless,",
  "Because pure Christianity is to help the widows and orphans in distress.",
  "",
  "I am very glad to see Henry Irving has sent a hundred pounds,",
  "And I hope his brother actors will subscribe their mite all round;",
  "And if they do it will add honour to their name,",
  "Because whatever is given towards a good cause they will it regain.",
  ""
]