module.exports = [
  "We sate down and wept by the waters",
  "  Of Babel, and thought of the day",
  "When our foe, in the hue of his slaughters,",
  "  Made Salem's high places his prey;",
  "And Ye, oh her desolate daughters!",
  "  Were scattered all weeping away.",
  "",
  "While sadly we gazed on the river",
  "  Which rolled on in freedom below,",
  "They demanded the song; but, oh never",
  "  That triumph the Stranger shall know!",
  "May this right hand be withered for ever,",
  "  Ere it string our high harp for the foe!",
  "",
  "On the willow that harp is suspended,",
  "  Oh Salem! its sound should be free;",
  "And the hour when thy glories were ended",
  "  But left me that token of thee:",
  "And ne'er shall its soft tones be blended",
  "  With the voice of the Spoiler by me!",
  ""
]