module.exports = [
  "THINKING of her had saddened me at first,",
  "Until I saw the sun on the celandines lie",
  "Redoubled, and she stood up like a flame,",
  "A living thing, not what before I nursed,",
  "The shadow I was growing to love almost,",
  "The phantom, not the creature with bright eye",
  "That I had thought never to see, once lost.",
  "",
  "She found the celandines of February",
  "Always before us all. Her nature and name",
  "Were like those flowers, and now immediately",
  "For a short swift eternity back she came,",
  "Beautiful, happy, simply as when she wore",
  "Her brightest bloom among the winter hues",
  "Of all the world; and I was happy too,",
  "Seeing the blossoms and the maiden who",
  "Had seen them with me Februarys before,",
  "Bending to them as in and out she trod",
  "And laughed, with locks sweeping the mossy sod.",
  "",
  "But this was a dream: the flowers were not true,",
  "Until I stooped to pluck from the grass there",
  "One of five petals and I smelt the juice",
  "Which made me sigh, remembering she was no more,",
  "Gone like a never perfectly recalled air.",
  ""
]