module.exports = [
  "IMITATIONS OF ENGLISH POETS",
  "",
  "Women ben full of ragerie,",
  "Yet swinken nat sans secresie.",
  "Thilke moral shall ye understond,",
  "From schoole-boy's tale of fayre Irelond:",
  "Which to the fennes hath him betake,",
  "To filche the gray ducke fro the lake.",
  "Right then, there passen by the way",
  "His aunt, and eke her daughters tway.",
  "Ducke in his trowses hath he hent,",
  "Not to be spied of ladies gent.",
  "'But ho! our nephew!' crieth one;",
  "'Ho!' quoth another, 'Cozen John;'",
  "And stoppen, and lough, and callen out,--",
  "This sely clerke full low doth lout:",
  "They asken that, and talken this,",
  "'Lo here is Coz, and here is Miss.'",
  "But, as he glozeth with speeches soote,",
  "The ducke sore tickleth his erse roote:",
  "Fore-piece and buttons all to-brest,",
  "Forth thrust a white neck, and red crest.",
  "'Te-he,' cried ladies; clerke nought spake:",
  "Miss stared; and gray ducke crieth 'Quaake.'",
  "'O moder, moder!' quoth the daughter,",
  "'Be thilke same thing maids longen a'ter?",
  "Bette is to pyne on coals and chalke,",
  "Then trust on mon, whose yerde can talke.'",
  ""
]