module.exports = [
  "WHEN the vain triumph of the imperial lord,",
  "Whom servile Rome obeyed, and yet abhorred,",
  "Gave to the vulgar gaze each glorious bust,",
  "That left a likeness of the brave, or just;",
  "What most admired each scrutinising eye",
  "Of all that decked that passing pageantry?",
  "What spread from face to face that wondering air?",
  "The thought of Brutus--for his was not there!",
  "That absence proved his worth,--that absence fixed",
  "His memory on the longing mind, unmixed;",
  "And more decreed his glory to endure,",
  "Than all a gold Colossus could secure.",
  "",
  "If thus, fair Jersey, our desiring gaze",
  "Search for thy form, in vain and mute amaze,",
  "Amidst those pictured charms, whose loveliness,",
  "Bright though they be, thine own had rendered less:",
  "If he, that VAIN OLD MAN, whom truth admits",
  "Heir of his father's crown, and of his wits,",
  "If his corrupted eye, and withered heart,",
  "Could with thy gentle image bear to part;",
  "That tasteless shame be _his_, and ours the grief,",
  "To gaze on Beauty's band without its chief:",
  "Yet Comfort still one selfish thought imparts,",
  "We lose the portrait, but preserve our hearts.",
  "",
  "What can his vaulted gallery now disclose?",
  "A _garden_ with all flowers--except the rose;--",
  "A _fount_ that only wants its living stream;",
  "A _night_, with every star, save Dian's beam.",
  "Lost to our eyes the present forms shall be,",
  "That turn from tracing them to dream of thee;",
  "And more on that recalled resemblance pause,",
  "Than all he _shall_ not force on our applause.",
  "",
  "Long may thy yet meridian lustre shine,",
  "With all that Virtue asks of Homage thine:",
  "The symmetry of youth--the grace of mien--",
  "The eye that gladdens--and the brow serene;",
  "The glossy darkness of that clustering hair,",
  "Which shades, yet shows that forehead more than fair!",
  "Each glance that wins us, and the life that throws",
  "A spell which will not let our looks repose,",
  "But turn to gaze again, and find anew",
  "Some charm that well rewards another view.",
  "These are not lessened, these are still as bright,",
  "Albeit too dazzling _for a dotard's sight_;",
  "And those must wait till ev'ry charm is gone,",
  "To please the paltry heart that pleases none;--",
  "That dull cold sensualist, whose sickly eye",
  "In envious dimness passed thy portrait by;",
  "Who racked his little spirit to combine",
  "Its hate of _Freedom's_ loveliness, and _thine_.",
  ""
]