module.exports = [
  "Content, the false World's best disguise,",
  "The search and faction of the Wise,",
  "Is so abstruse and hid in night,",
  "That, like that Fairy Red-cross Knight,",
  "Who trech'rous Falshood for clear Truth had got,",
  "Men think they have it when they have it not.",
  "",
  "For Courts Content would gladly own,",
  "But she ne're dwelt about a Throne:",
  "And to be flatter'd, rich, and great,",
  "Are things which do Mens senses cheat.",
  "But grave Experience long since this did see,",
  "Ambition and Content would ne're agree.",
  "",
  "Some vainer would Content expect",
  "From what their bright Out-sides reflect:",
  "But sure Content is more Divine",
  "Then to be digg'd from Rock or Mine:",
  "And they that know her beauties will confess,",
  "She needs no lustre from a glittering dress.",
  "",
  "In Mirth some place her, but she scorns",
  "Th'assistance of such crackling thorns,",
  "Nor owes her self to such thin sport,",
  "That is so sharp and yet so short:",
  "And Painters tell us, they the same strokes place",
  "To make a laughing and a weeping face.",
  "",
  "Others there are that place Content",
  "In Liberty from Government:",
  "But who his Passions do deprave,",
  "Though free from shackles is a slave.",
  "Content and Bondage differ onely then,",
  "When we are chain'd by Vices, not by Men.",
  "",
  "Some think the Camp Content does know,",
  "And that she fits o'th' Victor's brow:",
  "But in his Laurel there is seen",
  "Often a Cypress-bow between.",
  "Nor will Content herself in that place give,",
  "Where Noise and Tumult and Destruction live.",
  "",
  "But yet the most Discreet believe,",
  "The Schools this Jewel do receive,",
  "And thus far's true without dispute,",
  "Knowledge is still the sweetest fruit.",
  "But whil'st men seek for Truth they lose their Peace;",
  "And who heaps Knowledge, Sorrow doth increase.",
  "",
  "But now some sullen Hermite smiles,",
  "And thinks he all the World beguiles,",
  "And that his Cell and Dish contain",
  "What all mankind wish for in vain.",
  "But yet his Pleasure's follow'd with a Groan,",
  "For man was never born to be alone.",
  "",
  "Content her self best comprehends",
  "Betwixt two souls, and they two friends,",
  "Whose either joyes in both are fixed,",
  "And multiply'd by being mixed:",
  "Whose minds and interests are still the same;",
  "Their Griefs, when once imparted, lose their name.",
  "",
  "These far remov'd from all bold noise,",
  "And (what is worse) all hollow joyes,",
  "Who never had a mean design,",
  "Whose flame is serious and divine,",
  "And calm, and even, must contented be,",
  "For they've both Union and Society.",
  "",
  "Then, my Lucasia, we have",
  "Whatever Love can give or crave;",
  "With scorn or pity can survey",
  "The Trifles which the most betray;",
  "With innocence and perfect friendship fired,",
  "By Vertue joyn'd, and by our Choice retired.",
  "",
  "Whose Mirrours are the crystal Brooks,",
  "Or else each others Hearts and Looks;",
  "Who cannot wish for other things",
  "Then Privacy and Friendship brings:",
  "Whose thoughts and persons chang'd and mixt are one,",
  "Enjoy Content, or else the World hath none.",
  ""
]