module.exports = [
  "DEATH, to the dead for evermore",
  "A King, a God, the last, the best of friends -",
  "Whene'er this mortal journey ends",
  "Death, like a host, comes smiling to the door;",
  "Smiling, he greets us, on that tranquil shore",
  "Where neither piping bird nor peeping dawn",
  "Disturbs the eternal sleep,",
  "But in the stillness far withdrawn",
  "Our dreamless rest for evermore we keep.",
  "",
  "For as from open windows forth we peep",
  "Upon the night-time star beset",
  "And with dews for ever wet;",
  "So from this garish life the spirit peers;",
  "And lo! as a sleeping city death outspread,",
  "Where breathe the sleepers evenly; and lo!",
  "After the loud wars, triumphs, trumpets, tears",
  "And clamour of man's passion, Death appears,",
  "And we must rise and go.",
  "",
  "Soon are eyes tired with sunshine; soon the ears",
  "Weary of utterance, seeing all is said;",
  "Soon, racked by hopes and fears,",
  "The all-pondering, all-contriving head,",
  "Weary with all things, wearies of the years;",
  "And our sad spirits turn toward the dead;",
  "And the tired child, the body, longs for bed.",
  ""
]