module.exports = [
  "GRANDMOTHER's mother: her age, I guess,",
  "Thirteen summers, or something less;",
  "Girlish bust, but womanly air;",
  "Smooth, square forehead with uprolled hair;",
  "Lips that lover has never kissed;",
  "Taper fingers and slender wrist;",
  "Hanging sleeves of stiff brocade;",
  "So they painted the little maid.",
  "",
  "On her hand a parrot green",
  "Sits unmoving and broods serene.",
  "Hold up the canvas full in view,--",
  "Look! there's a rent the light shines through,",
  "Dark with a century's fringe of dust,--",
  "That was a Red-Coat's rapier-thrust!",
  "Such is the tale the lady old,",
  "Dorothy's daughter's daughter, told.",
  "",
  "Who the painter was none may tell,--",
  "One whose best was not over well;",
  "Hard and dry, it must be confessed,",
  "Fist as a rose that has long been pressed;",
  "Yet in her cheek the hues are bright,",
  "Dainty colors of red and white,",
  "And in her slender shape are seen",
  "Hint and promise of stately mien.",
  "",
  "Look not on her with eyes of scorn,--",
  "Dorothy Q. was a lady born!",
  "Ay! since the galloping Normans came,",
  "England's annals have known her name;",
  "And still to the three-hilled rebel town",
  "Dear is that ancient name's renown,",
  "For many a civic wreath they won,",
  "The youthful sire and the gray-haired son.",
  "",
  "O Damsel Dorothy! Dorothy Q.!",
  "Strange is the gift that I owe to you;",
  "Such a gift as never a king",
  "Save to daughter or son might bring,--",
  "All my tenure of heart and hand,",
  "All my title to house and land;",
  "Mother and sister and child and wife",
  "And joy and sorrow and death and life!",
  "What if a hundred years ago",
  "Those close-shut lips had answered NO,",
  "When forth the tremulous question came",
  "That cost the maiden her Norman name,",
  "And under the folds that look so still",
  "The bodice swelled with the bosom's thrill?",
  "Should I be I, or would it be",
  "One tenth another, to nine tenths me?",
  "",
  "Soft is the breath of a maiden's YES:",
  "Not the light gossamer stirs with less;",
  "But never a cable that holds so fast",
  "Through all the battles of wave and blast,",
  "And never an echo of speech or song",
  "That lives in the babbling air so long!",
  "There were tones in the voice that whispered then",
  "You may hear to-day in a hundred men.",
  "",
  "O lady and lover, how faint and far",
  "Your images hover,-- and here we are,",
  "Solid and stirring in flesh and bone,--",
  "Edward's and Dorothy's-- all their own,--",
  "A goodly record for Time to show",
  "Of a syllable spoken so long ago!--",
  "Shall I bless you, Dorothy, or forgive",
  "For the tender whisper that bade me live?",
  "",
  "It shall be a blessing, my little maid!",
  "I will heal the stab of the Red-Coat's blade,",
  "And freshen the gold of the tarnished frame,",
  "And gild with a rhyme your household name;",
  "So you shall smile on us brave and bright",
  "As first you greeted the morning's light,",
  "And live untroubled by woes and fears",
  "Through a second youth of a hundred years.",
  ""
]