module.exports = [
  "OF rhymes I printed seven volumes--",
  "The list concludes John Murray's columns:",
  "Of these there have been few translations",
  "For Gallic or Italian nations;",
  "And one or two perhaps in German--",
  "But in this last I can't determine.",
  "But then I only sung of passions",
  "That do not suit with modern fashions;",
  "Of Incest and such like diversions",
  "Permitted only to the Persians,",
  "Or Greeks to bring upon their stages--",
  "But that was in the earlier ages",
  "Besides my style is the romantic,",
  "Which some call fine, and some call frantic;",
  "While others are or would seem _as_ sick",
  "Of repetitions nicknamed Classic.",
  "For my part all men must allow",
  "Whatever I was, I'm classic now.",
  "I saw and left my fault in time,",
  "And chose a topic all sublime--",
  "Wondrous as antient war or hero--",
  "Then played and sung away like Nero,",
  "Who sang of Rome, and I of Rizzo:",
  "The subject has improved my wit so,",
  "The first four lines the poet sees",
  "Start forth in fourteen languages!",
  "Though of seven volumes none before",
  "Could ever reach the fame of four,",
  "Henceforth I sacrifice all Glory",
  "To the Rinaldo of my Story:",
  "I've sung his health and appetite",
  "(The last word's not translated right--",
  "He's turned it, God knows how, to vigour)",
  "I'll sing them in a book that's bigger.",
  "Oh! Muse prepare for thy Ascension!",
  "And generous Rizzo! thou my pension.",
  ""
]