module.exports = [
  "EARLY one morning in May I set out,",
  "And nobody I knew was about.",
  "     I'm bound away for ever,",
  "     Away somewhere, away for ever.",
  "",
  "There was no wind to trouble the weathercocks.",
  "I had burnt my letters and darned my socks.",
  "",
  "No one knew I was going away,",
  "I thought myself I should come back some day.",
  "",
  "I heard the brook through the town gardens run.",
  "O sweet was the mud turned to dust by the sun.",
  "",
  "A gate banged in a fence and banged in my head.",
  "\"A fine morning, sir.\" a shepherd said.",
  "",
  "I could not return from my liberty,",
  "To my youth and my love and my misery.",
  "",
  "The past is the only dead thing that smells sweet,",
  "The only sweet thing that is not also fleet.",
  "     I'm bound away for ever,",
  "     Away somewhere, away for ever.",
  ""
]