module.exports = [
  "If Fate should seal my Death to-morrow,",
  "  (Though much _I_ hope she will _postpone_ it,)",
  "I've held a share _Joy_ and _Sorrow_,",
  "  Enough for _Ten_; and _here_ I _own_ it.",
  "",
  "I've lived, as many others live,",
  "And yet, I think, with more enjoyment;",
  "For could I through my days again live,",
  "I'd pass them in the 'same' employment.",
  "",
  "That 'is' to say, with 'some exception',",
  "For though I will not make confession,",
  "I've seen too much of man's deception",
  "Ever again to trust profession.",
  "",
  "Some sage 'Mammas' with gesture haughty,",
  "Pronounce me quite a youthful Sinner--",
  "But 'Daughters' say, \"although he's naughty,",
  "You must not check a 'Young Beginner'!\"",
  "",
  "I've loved, and many damsels know it--",
  "But whom I don't intend to mention,",
  "As 'certain stanzas' also show it,",
  "'Some' say 'deserving Reprehension'.",
  "",
  "Some ancient Dames, of virtue fiery,",
  "(Unless Report does much belie them,)",
  "Have lately made a sharp Enquiry,",
  "And much it 'grieves' me to 'deny' them.",
  "",
  "Two whom I lov'd had 'eyes' of 'Blue',",
  "To which I hope you've no objection;",
  "The 'Rest' had eyes of 'darker Hue'--",
  "Each Nymph, of course, was 'all perfection'.",
  "",
  "But here I'll close my 'chaste' Description,",
  "Nor say the deeds of animosity;",
  "For 'silence' is the best prescription,",
  "To 'physic' idle curiosity.",
  "",
  "Of 'Friends' I've known a 'goodly Hundred'--",
  "For finding 'one' in each acquaintance,",
  "By 'some deceived', by others plunder'd,",
  "'Friendship', to me, was not 'Repentance'.",
  "",
  "At 'School' I thought like other 'Children';",
  "Instead of 'Brains', a fine Ingredient,",
  "'Romance', my 'youthful Head bewildering',",
  "To 'Sense' had made me disobedient.",
  "",
  "A victim, 'nearly' from affection,",
  "To certain 'very precious scheming',",
  "The still remaining recollection",
  "Has 'cured' my 'boyish soul' of 'Dreaming'.",
  "",
  "By Heaven! I rather would forswear",
  "The Earth, and all the joys reserved me,",
  "Than dare again the 'specious Snare',",
  "From which 'my Fate' and 'Heaven preserved' me.",
  "",
  "Still I possess some Friends who love me--",
  "In each a much esteemed and true one;",
  "The Wealth of Worlds shall never move me",
  "To quit their Friendship, for a new one.",
  "",
  "But Becher! you're a 'reverend pastor',",
  "Now take it in consideration,",
  "Whether for penance I should fast, or",
  "Pray for my 'sins' in expiation.",
  "",
  "I own myself the child of 'Folly',",
  "But not so wicked as they make me--",
  "I soon must die of melancholy,",
  "If 'Female' smiles should e'er forsake me.",
  "",
  "'Philosophers' have 'never doubted',",
  "That 'Ladies' Lips' were made for 'kisses!'",
  "For 'Love!' I could not live without it,",
  "For such a 'cursed' place as 'This is'.",
  "",
  "Say, Becher, I shall be forgiven!",
  "If you don't warrant my salvation,",
  "I must resign all 'Hopes' of 'Heaven'!",
  "For, 'Faith', I can't withstand Temptation.",
  ""
]