module.exports = [
  "There is a tear for all that die,",
  "  A mourner o'er the humblest grave;",
  "But nations swell the funeral cry,",
  "  And Triumph weeps above the brave.",
  "",
  "For them is Sorrow's purest sigh",
  "  O'er Ocean's heaving bosom sent:",
  "In vain their bones unburied lie,",
  "  All earth becomes their monument!",
  "",
  "A tomb is theirs on every page,",
  "  An epitaph on every tongue:",
  "The present hours, the future age,",
  "  For them bewail, to them belong.",
  "",
  "For them the voice of festal mirth",
  "  Grows hushed, _their name_ the only sound;",
  "While deep Remembrance pours to Worth",
  "  The goblet's tributary round.",
  "",
  "A theme to crowds that knew them not,",
  "  Lamented by admiring foes,",
  "Who would not share their glorious lot?",
  "  Who would not die the death they chose?",
  "",
  "And, gallant Parker! thus enshrined",
  "  Thy life, thy fall, thy fame shall be;",
  "And early valour, glowing, find",
  "  A model in thy memory.",
  "",
  "But there are breasts that bleed with thee",
  "  In woe, that glory cannot quell;",
  "And shuddering hear of victory,",
  "  Where one so dear, so dauntless, fell.",
  "",
  "Where shall they turn to mourn thee less?",
  "  When cease to hear thy cherished name?",
  "Time cannot teach forgetfulness,",
  "  While Grief's full heart is fed by Fame.",
  "",
  "Alas! for them, though not for thee,",
  "  They cannot choose but weep the more;",
  "Deep for the dead the grief must be,",
  "  Who ne'er gave cause to mourn before.",
  ""
]