module.exports = [
  "  \"It is the voice of years, that are gone! they roll before me, with",
  "  all their deeds.\"",
  "",
  "  Ossian.",
  "",
  "NEWSTEAD! fast-falling, once-resplendent dome!",
  "Religion's shrine! repentant HENRY'S pride!",
  "Of Warriors, Monks, and Dames the cloister'd tomb,",
  " Whose pensive shades around thy ruins glide,",
  "",
  "Hail to thy pile! more honour'd in thy fall,",
  "  Than modern mansions, in their pillar'd state;",
  "Proudly majestic frowns thy vaulted hall,",
  "  Scowling defiance on the blasts of fate.",
  "",
  "No mail-clad Serfs, obedient to their Lord,",
  "  In grim array, the crimson cross demand;",
  "Or gay assemble round the festive board,",
  "  Their chief's retainers, an immortal band.",
  "",
  "Else might inspiring Fancy's magic eye",
  "  Retrace their progress, through the lapse of time;",
  "Marking each ardent youth, ordain'd to die,",
  "  A votive pilgrim, in Judea's clime.",
  "",
  "But not from thee, dark pile! departs the Chief;",
  "  His feudal realm in other regions lay:",
  "In thee the wounded conscience courts relief,",
  "  Retiring from the garish blaze of day.",
  "",
  "Yes! in thy gloomy cells and shades profound,",
  "  The monk abjur'd a world, he ne'er could view;",
  "Or blood-stain'd Guilt repenting, solace found,",
  "  Or Innocence, from stern Oppression, flew.",
  "",
  "A Monarch bade thee from that wild arise,",
  "  Where Sherwood's outlaws, once, were wont to prowl;",
  "And Superstition's crimes, of various dyes,",
  "  Sought shelter in the Priest's protecting cowl.",
  "",
  "Where, now, the grass exhales a murky dew,",
  "  The humid pall of life-extinguish'd clay,",
  "In sainted fame, the sacred Fathers grew,",
  "  Nor raised their pious voices, but to pray.",
  "",
  "Where, now, the bats their wavering wings extend,",
  "  Soon as the gloaming spreads her waning shade",
  "The choir did, oft, their mingling vespers blend,",
  "  Or matin orisons to Mary paid.",
  "",
  "Years roll on years; to ages, ages yield;",
  "  Abbots to Abbots, in a line, succeed:",
  "Religion's charter, their protecting shield,",
  "  Till royal sacrilege their doom decreed.",
  "",
  "One holy HENRY rear'd the Gothic walls,",
  "  And bade the pious inmates rest in peace;",
  "Another HENRY the kind gift recalls,",
  "  And bids devotion's hallow'd echoes cease.",
  "",
  "Vain is each threat, or supplicating prayer;",
  "  He drives them exiles from their blest abode,",
  "To roam a dreary world, in deep despair--",
  "  No friend, no home, no refuge, but their God.",
  "",
  "Hark! how the hall, resounding to the strain,",
  "  Shakes with the martial music's novel din!",
  "The heralds of a warrior's haughty reign,",
  "  High crested banners wave thy walls within.",
  "",
  "Of changing sentinels the distant hum,",
  "  The mirth of feasts, the clang of burnish'd arms,",
  "The braying trumpet, and the hoarser drum,",
  "  Unite in concert with increas'd alarms.",
  "",
  "An abbey once, a regal fortress now,",
  "  Encircled by insulting rebel powers;",
  "War's dread machines o'erhang thy threat'ning brow,",
  "  And dart destruction, in sulphureous showers.",
  "",
  "Ah! vain defence! the hostile traitor's siege,",
  "  Though oft repuls'd, by guile o'ercomes the brave;",
  "His thronging foes oppress the faithful Liege,",
  "  Rebellion's reeking standards o'er him wave.",
  "",
  "Not unaveng'd the raging Baron yields;",
  "  The blood of traitors smears the purple plain;",
  "Unconquer'd still, his falchion there he wields,",
  "  And days of glory, yet, for him remain.",
  "",
  "Still, in that hour, the warrior wish'd to strew",
  "  Self-gather'd laurels on a self-sought grave;",
  "But Charles' protecting genius hither flew,",
  "  The monarch's friend, the monarch's hope, to save.",
  "",
  "Trembling, she snatch'd him from th' unequal strife,",
  "  In other fields the torrent to repel;",
  "For nobler combats, here, reserv'd his life,",
  "  To lead the band, where godlike FALKLAND fell.",
  "",
  "From thee, poor pile! to lawless plunder given,",
  "  While dying groans their painful requiem sound,",
  "Far different incense, now, ascends to Heaven,",
  "  Such victims wallow on the gory ground.",
  "",
  "There many a pale and ruthless Robber's corse,",
  "  Noisome and ghast, defiles thy sacred sod;",
  "O'er mingling man, and horse commix'd with horse,",
  "  Corruption's heap, the savage spoilers trod.",
  "",
  "Graves, long with rank and sighing weeds o'erspread,",
  "  Ransack'd resign, perforce, their mortal mould:",
  "From ruffian fangs, escape not e'en the dead,",
  "  Racked from repose, in search for buried gold.",
  "",
  "Hush'd is the harp, unstrung the warlike lyre,",
  "  The minstrel's palsied hand reclines in death;",
  "No more he strikes the quivering chords with fire,",
  "  Or sings the glories of the martial wreath.",
  "",
  "At length the sated murderers, gorged with prey,",
  "  Retire: the clamour of the fight is o'er;",
  "Silence again resumes her awful sway,",
  "  And sable Horror guards the massy door.",
  "",
  "Here, Desolation holds her dreary court:",
  "  What satellites declare her dismal reign!",
  "Shrieking their dirge, ill-omen'd birds resort,",
  "  To flit their vigils, in the hoary fane.",
  "",
  "Soon a new Morn's restoring beams dispel",
  "  The clouds of Anarchy from Britain's skies;",
  "The fierce Usurper seeks his native hell,",
  "  And Nature triumphs, as the Tyrant dies.",
  "",
  "With storms she welcomes his expiring groans;",
  "  Whirlwinds, responsive, greet his labouring breath;",
  "Earth shudders, as her caves receive his bones,",
  "  Loathing the offering of so dark a death.",
  "",
  "The legal Ruler now resumes the helm,",
  "  He guides through gentle seas, the prow of state;",
  "Hope cheers, with wonted smiles, the peaceful realm,",
  "  And heals the bleeding wounds of wearied Hate.",
  "",
  "The gloomy tenants, Newstead! of thy cells,",
  "  Howling, resign their violated nest;",
  "Again, the Master on his tenure dwells,",
  "  Enjoy'd, from absence, with enraptured zest.",
  "",
  "Vassals, within thy hospitable pale,",
  "  Loudly carousing, bless their Lord's return;",
  "Culture, again, adorns the gladdening vale,",
  "  And matrons, once lamenting, cease to mourn.",
  "",
  "A thousand songs, on tuneful echo, float,",
  "  Unwonted foliage mantles o'er the trees;",
  "And, hark! the horns proclaim a mellow note,",
  "  The hunters' cry hangs lengthening on the breeze.",
  "",
  "Beneath their coursers' hoofs the valleys shake;",
  "  What fears! what anxious hopes! attend the chase!",
  "The dying stag seeks refuge in the lake;",
  "  Exulting shouts announce the finish'd race.",
  "",
  "Ah happy days! too happy to endure!",
  "  Such simple sports our plain forefathers knew:",
  "No splendid vices glitter'd to allure;",
  "  Their joys were many, as their cares were few.",
  "",
  "From these descending, Sons to Sires succeed;",
  "  Time steals along, and Death uprears his dart;",
  "Another Chief impels the foaming steed,",
  "  Another Crowd pursue the panting hart.",
  "",
  "Newstead! what saddening change of scene is thine!",
  "  Thy yawning arch betokens slow decay;",
  "The last and youngest of a noble line,",
  "  Now holds thy mouldering turrets in his sway.",
  "",
  "Deserted now, he scans thy gray worn towers;",
  "  Thy vaults, where dead of feudal ages sleep;",
  "Thy cloisters, pervious to the wintry showers;",
  "  These, these he views, and views them but to weep.",
  "",
  "Yet are his tears no emblem of regret:",
  "  Cherish'd Affection only bids them flow;",
  "Pride, Hope, and Love, forbid him to forget,",
  "  But warm his bosom, with impassion'd glow.",
  "",
  "Yet he prefers thee, to the gilded domes,",
  "  Or gewgaw grottos, of the vainly great;",
  "Yet lingers 'mid thy damp and mossy tombs,",
  "  Nor breathes a murmur 'gainst the will of Fate.",
  "",
  "Haply thy sun, emerging, yet, may shine,",
  "  Thee to irradiate with meridian ray;",
  "Hours, splendid as the past, may still be thine,",
  "  And bless thy future, as thy former day.",
  ""
]