module.exports = [
  "\"Oh! banish care\"--such ever be",
  "The motto of _thy_ revelry!",
  "Perchance of _mine,_ when wassail nights",
  "Renew those riotous delights,",
  "Wherewith the children of Despair",
  "Lull the lone heart, and \"banish care.\"",
  "But not in Morn's reflecting hour,",
  "When present, past, and future lower,",
  "When all I loved is changed or gone,",
  "Mock with such taunts the woes of one,",
  "Whose every thought--but let them pass--",
  "Thou know'st I am not what I was.",
  "But, above all, if thou wouldst hold",
  "Place in a heart that ne'er was cold,",
  "By all the powers that men revere,",
  "By all unto thy bosom dear,",
  "Thy joys below, thy hopes above,",
  "Speak--speak of anything but Love.",
  "",
  "  'Twere long to tell, and vain to hear,",
  "The tale of one who scorns a tear;",
  "And there is little in that tale",
  "Which better bosoms would bewail.",
  "But mine has suffered more than well",
  "'Twould suit philosophy to tell.",
  "I've seen my bride another's bride,--",
  "Have seen her seated by his side,--",
  "Have seen the infant, which she bore,",
  "Wear the sweet smile the mother wore,",
  "When she and I in youth have smiled,",
  "As fond and faultless as her child;--",
  "Have seen her eyes, in cold disdain,",
  "Ask if I felt no secret pain;",
  "And _I_ have acted well my part,",
  "And made my cheek belie my heart,",
  "Returned the freezing glance she gave,",
  "Yet felt the while that _woman's_ slave;--",
  "Have kissed, as if without design,",
  "The babe which ought to have been mine,",
  "And showed, alas! in each caress",
  "Time had not made me love the less.",
  "",
  "  But let this pass--I'll whine no more,",
  "Nor seek again an eastern shore;",
  "The world befits a busy brain,--",
  "I'll hie me to its haunts again.",
  "But if, in some succeeding year,",
  "When Britain's \"May is in the sere,\"",
  "Thou hear'st of one, whose deepening crimes",
  "Suit with the sablest of the times,",
  "Of one, whom love nor pity sways,",
  "Nor hope of fame, nor good men's praise;",
  "One, who in stern Ambition's pride,",
  "Perchance not blood shall turn aside;",
  "One ranked in some recording page",
  "With the worst anarchs of the age,",
  "Him wilt thou _know_--and _knowing_ pause,",
  "Nor with the _effect_ forget the cause.",
  ""
]