module.exports = [
  "Oh, Friend! for ever lov'd, for ever dear!",
  "What fruitless tears have bathed thy honour'd bier!",
  "What sighs re-echo'd to thy parting breath,",
  "Whilst thou wast struggling in the pangs of death!",
  "Could tears retard the tyrant in his course;",
  "Could sighs avert his dart's relentless force;",
  "Could youth and virtue claim a short delay,",
  "Or beauty charm the spectre from his prey;",
  "Thou still hadst liv'd to bless my aching sight,",
  "Thy comrade's honour and thy friend's delight.",
  "If yet thy gentle spirit hover nigh",
  "The spot where now thy mouldering ashes lie,",
  "Here wilt thou read, recorded on my heart,",
  "A grief too deep to trust the sculptor's art.",
  "No marble marks thy couch of lowly sleep,",
  "But living statues there are seen to weep;",
  "Affliction's semblance bends not o'er thy tomb,",
  "Affliction's self deplores thy youthful doom.",
  "What though thy sire lament his failing line,",
  "A father's sorrows cannot equal mine!",
  "Though none, like thee, his dying hour will cheer,",
  "Yet other offspring soothe his anguish here:",
  "But, who with me shall hold thy former place?",
  "Thine image, what new friendship can efface?",
  "Ah, none!--a father's tears will cease to flow,",
  "Time will assuage an infant brother's woe;",
  "To all, save one, is consolation known,",
  "While solitary Friendship sighs alone.",
  "",
  "Could youth and virtue claim a short delay,",
  "Or beauty charm the spectre from his prey,",
  "Thou still had'st liv'd to bless my aching sight,",
  "Thy comrade's honour, and thy friend's delight:",
  "Though low thy lot since in a cottage born,",
  "No titles did thy humble name adorn,",
  "To me, far dearer, was thy artless love,",
  "Than all the joys, wealth, fame, and friends could prove.",
  "For thee alone I liv'd, or wish'd to live,",
  "(Oh God! if impious, this rash word forgive,)",
  "Heart-broken now, I wait an equal doom,",
  "Content to join thee in thy turf-clad tomb;",
  "Where this frail form compos'd in endless rest,",
  "I'll make my last, cold, pillow on thy breast;",
  "That breast where oft in life, I've laid my head,",
  "Will yet receive me mouldering with the dead;",
  "This life resign'd, without one parting sigh,",
  "Together in one bed of earth we'll lie!",
  "Together share the fate to mortals given,",
  "Together mix our dust, and hope for Heaven._",
  ""
]