module.exports = [
  "[LATIN VERSION OF THE EPITAPH IN GRAY'S ELEGY.]",
  "",
  "Hic sinu fessum caput hospitali",
  "Cespitis dormit juvenis, nec illi",
  "Fata ridebant, popularis ille",
  "Nescius aurae.",
  "",
  "Musa non vultu genus arroganti",
  "Rustica natum grege despicata,",
  "Et suum tristis puerum notavit",
  "Sollicitudo.",
  "",
  "Indoles illi bene larga, pectus",
  "Veritas sedem sibi vindicavit,",
  "Et pari tantis meritis beavit",
  "Munere coelum.",
  "",
  "Omne quad moestis habuit miserto",
  "Corde largivit lacrimam, recepit",
  "Omne quod coelo voluit, fidelis",
  "Pectus amici.",
  "",
  "Longius sed tu fuge curiosus",
  "Caeteras laudes fuge suspicari,",
  "Caeteras culpas fuge velle tractas",
  "Sede tremenda.",
  "",
  "Spe tremescentes recubant in illa",
  "Sede virtutes pariterque culpae,",
  "In sui Patris gremio, tremenda",
  "Sede Deique.",
  ""
]