module.exports = [
  "These are two friends whose lives were undivided;",
  "So let their memory be, now they have glided",
  "Under the grave; let not their bones be parted,",
  "For their two hearts in life were single-hearted.",
  "",
  "    This morn thy gallant bark",
  "    Sailed on a sunny sea:",
  "    'Tis noon, and tempests dark",
  "    Have wrecked it on the lee.",
  "    Ah woe! ah woe!",
  "    By Spirits of the deep",
  "    Thou'rt cradled on the billow",
  "    To thy eternal sleep.",
  "",
  "    Thou sleep'st upon the shore",
  "    Beside the knelling surge,",
  "    And Sea-nymphs evermore",
  "    Shall sadly chant thy dirge.",
  "    They come, they come,",
  "    The Spirits of the deep,--",
  "    While near thy seaweed pillow",
  "    My lonely watch I keep.",
  "",
  "    From far across the sea",
  "    I hear a loud lament,",
  "    By Echo's voice for thee",
  "    From Ocean's caverns sent.",
  "    O list! O list!",
  "    The Spirits of the deep!",
  "    They raise a wail of sorrow,",
  "    While I forever weep.",
  ""
]