module.exports = [
  "ANOTHER VERSION OF THE PRECEDING.",
  "",
  "Night, with all thine eyes look down!",
  "Darkness shed its holiest dew!",
  "When ever smiled the inconstant moon",
  "On a pair so true?",
  "Hence, coy hour! and quench thy light,",
  "Lest eyes see their own delight!",
  "Hence, swift hour! and thy loved flight",
  "Oft renew.",
  "",
  "BOYS:",
  "O joy! O fear! what may be done",
  "In the absence of the sun?",
  "Come along!",
  "The golden gates of sleep unbar!",
  "When strength and beauty meet together,",
  "Kindles their image like a star",
  "In a sea of glassy weather.",
  "Hence, coy hour! and quench thy light,",
  "Lest eyes see their own delight!",
  "Hence, swift hour! and thy loved flight",
  "Oft renew.",
  "",
  "GIRLS:",
  "O joy! O fear! what may be done",
  "In the absence of the sun?",
  "Come along!",
  "Fairies! sprites! and angels, keep her!",
  "Holiest powers, permit no wrong!",
  "And return, to wake the sleeper,",
  "Dawn, ere it be long.",
  "Hence, swift hour! and quench thy light,",
  "Lest eyes see their own delight!",
  "Hence, coy hour! and thy loved flight",
  "Oft renew.",
  "",
  "BOYS AND GIRLS:",
  "O joy! O fear! what will be done",
  "In the absence of the sun?",
  "Come along!",
  "",
  "ANOTHER VERSION OF THE SAME.",
  "",
  "BOYS SING:",
  "Night! with all thine eyes look down!",
  "Darkness! weep thy holiest dew!",
  "Never smiled the inconstant moon",
  "On a pair so true.",
  "Haste, coy hour! and quench all light,",
  "Lest eyes see their own delight!",
  "Haste, swift hour! and thy loved flight",
  "Oft renew!",
  "",
  "GIRLS SING:",
  "Fairies, sprites, and angels, keep her!",
  "Holy stars! permit no wrong!",
  "And return, to wake the sleeper,",
  "Dawn, ere it be long!",
  "O joy! O fear! there is not one",
  "Of us can guess what may be done",
  "In the absence of the sun:--",
  "Come along!",
  "",
  "BOYS:",
  "Oh! linger long, thou envious eastern lamp",
  "In the damp",
  "Caves of the deep!",
  "",
  "GIRLS:",
  "Nay, return, Vesper! urge thy lazy car!",
  "Swift unbar",
  "The gates of Sleep!",
  "",
  "CHORUS:",
  "The golden gate of Sleep unbar,",
  "When Strength and Beauty, met together,",
  "Kindle their image, like a star",
  "In a sea of glassy weather.",
  "May the purple mist of love",
  "Round them rise, and with them move,",
  "Nourishing each tender gem",
  "Which, like flowers, will burst from them.",
  "As the fruit is to the tree",
  "May their children ever be!",
  ""
]