module.exports = [
  "A DIALOGUE.",
  "",
  "Whilst monarchs laughed upon their thrones",
  "To hear a famished nation's groans,",
  "And hugged the wealth wrung from the woe",
  "That makes its eyes and veins o'erflow,--",
  "Those thrones, high built upon the heaps",
  "Of bones where frenzied Famine sleeps,",
  "Where Slavery wields her scourge of iron,",
  "Red with mankind's unheeded gore,",
  "And War's mad fiends the scene environ,",
  "Mingling with shrieks a drunken roar,",
  "There Vice and Falsehood took their stand,",
  "High raised above the unhappy land.",
  "",
  "FALSEHOOD:",
  "Brother! arise from the dainty fare,",
  "Which thousands have toiled and bled to bestow;",
  "A finer feast for thy hungry ear",
  "Is the news that I bring of human woe.",
  "",
  "VICE:",
  "And, secret one, what hast thou done,",
  "To compare, in thy tumid pride, with me?",
  "I, whose career, through the blasted year,",
  "Has been tracked by despair and agony.",
  "",
  "FALSEHOOD:",
  "What have I done!--I have torn the robe",
  "From baby Truth's unsheltered form,",
  "And round the desolated globe",
  "Borne safely the bewildering charm:",
  "My tyrant-slaves to a dungeon-floor",
  "Have bound the fearless innocent,",
  "And streams of fertilizing gore",
  "Flow from her bosom's hideous rent,",
  "Which this unfailing dagger gave...",
  "I dread that blood!--no more--this day",
  "Is ours, though her eternal ray",
  "Must shine upon our grave.",
  "Yet know, proud Vice, had I not given",
  "To thee the robe I stole from Heaven,",
  "Thy shape of ugliness and fear",
  "Had never gained admission here.",
  "",
  "VICE:",
  "And know, that had I disdained to toil,",
  "But sate in my loathsome cave the while,",
  "And ne'er to these hateful sons of Heaven,",
  "GOLD, MONARCHY, and MURDER, given;",
  "Hadst thou with all thine art essayed",
  "One of thy games then to have played,",
  "With all thine overweening boast,",
  "Falsehood! I tell thee thou hadst lost!--",
  "Yet wherefore this dispute?--we tend,",
  "Fraternal, to one common end;",
  "In this cold grave beneath my feet,",
  "Will our hopes, our fears, and our labours, meet.",
  "",
  "FALSEHOOD:",
  "I brought my daughter, RELIGION, on earth:",
  "She smothered Reason's babes in their birth;",
  "But dreaded their mother's eye severe,--",
  "So the crocodile slunk off slily in fear,",
  "And loosed her bloodhounds from the den....",
  "They started from dreams of slaughtered men,",
  "And, by the light of her poison eye,",
  "Did her work o'er the wide earth frightfully:",
  "The dreadful stench of her torches' flare,",
  "Fed with human fat, polluted the air:",
  "The curses, the shrieks, the ceaseless cries",
  "Of the many-mingling miseries,",
  "As on she trod, ascended high",
  "And trumpeted my victory!--",
  "Brother, tell what thou hast done.",
  "",
  "VICE:",
  "I have extinguished the noonday sun,",
  "In the carnage-smoke of battles won:",
  "Famine, Murder, Hell and Power",
  "Were glutted in that glorious hour",
  "Which searchless fate had stamped for me",
  "With the seal of her security...",
  "For the bloated wretch on yonder throne",
  "Commanded the bloody fray to rise.",
  "Like me he joyed at the stifled moan",
  "Wrung from a nation's miseries;",
  "While the snakes, whose slime even him DEFILED,",
  "In ecstasies of malice smiled:",
  "They thought 'twas theirs,--but mine the deed!",
  "Theirs is the toil, but mine the meed--",
  "Ten thousand victims madly bleed.",
  "They dream that tyrants goad them there",
  "With poisonous war to taint the air:",
  "These tyrants, on their beds of thorn,",
  "Swell with the thoughts of murderous fame,",
  "And with their gains to lift my name",
  "Restless they plan from night to morn:",
  "I--I do all; without my aid",
  "Thy daughter, that relentless maid,",
  "Could never o'er a death-bed urge",
  "The fury of her venomed scourge.",
  "",
  "FALSEHOOD:",
  "Brother, well:--the world is ours;",
  "And whether thou or I have won,",
  "The pestilence expectant lowers",
  "On all beneath yon blasted sun.",
  "Our joys, our toils, our honours meet",
  "In the milk-white and wormy winding-sheet:",
  "A short-lived hope, unceasing care,",
  "Some heartless scraps of godly prayer,",
  "A moody curse, and a frenzied sleep",
  "Ere gapes the grave's unclosing deep,",
  "A tyrant's dream, a coward's start,",
  "The ice that clings to a priestly heart,",
  "A judge's frown, a courtier's smile,",
  "Make the great whole for which we toil;",
  "And, brother, whether thou or I",
  "Have done the work of misery,",
  "It little boots: thy toil and pain,",
  "Without my aid, were more than vain;",
  "And but for thee I ne'er had sate",
  "The guardian of Heaven's palace gate.",
  ""
]