module.exports = [
  "Farewell! if ever fondest prayer",
  "  For other's weal availed on high,",
  "Mine will not all be lost in air,",
  "  But waft thy name beyond the sky.",
  "'Twere vain to speak--to weep--to sigh:",
  "  Oh! more than tears of blood can tell,",
  "When wrung from Guilt's expiring eye,",
  "  Are in that word--Farewell!--Farewell!",
  "",
  "These lips are mute, these eyes are dry;",
  "  But in my breast and in my brain,",
  "Awake the pangs that pass not by,",
  "  The thought that ne'er shall sleep again.",
  "My soul nor deigns nor dares complain,",
  "  Though Grief and Passion there rebel:",
  "I only know we loved in vain--",
  "  I only feel--Farewell!--Farewell!",
  ""
]