module.exports = [
  "Those whom nor power, nor lying faith, nor toil,",
  "Nor custom, queen of many slaves, makes blind,",
  "Have ever grieved that man should be the spoil",
  "Of his own weakness, and with earnest mind",
  "Fed hopes of its redemption; these recur",
  "Chastened by deathful victory now, and find",
  "Foundations in this foulest age, and stir",
  "Me whom they cheer to be their minister.",
  "",
  "Dark is the realm of grief: but human things",
  "Those may not know who cannot weep for them.",
  "",
  "...",
  "",
  "Once more descend",
  "The shadows of my soul upon mankind,",
  "For to those hearts with which they never blend,",
  "Thoughts are but shadows which the flashing mind",
  "From the swift clouds which track its flight of fire,",
  "Casts on the gloomy world it leaves behind.",
  "",
  "...",
  "",
  "'O THAT A CHARIOT OF CLOUD WERE MINE'.",
  "",
  "O that a chariot of cloud were mine!",
  "Of cloud which the wild tempest weaves in air,",
  "When the moon over the ocean's line",
  "Is spreading the locks of her bright gray hair.",
  "O that a chariot of cloud were mine!",
  "I would sail on the waves of the billowy wind",
  "To the mountain peak and the rocky lake,",
  "And the...",
  ""
]