module.exports = [
  "In that fair capital where Pleasure, crowned",
  "Amidst her myriad courtiers, riots and rules,",
  "I too have been a suitor. Radiant eyes",
  "Were my life's warmth and sunshine, outspread arms",
  "My gilded deep horizons. I rejoiced",
  "In yielding to all amorous influence",
  "And multiple impulsion of the flesh,",
  "To feel within my being surge and sway",
  "The force that all the stars acknowledge too.",
  "Amid the nebulous humanity",
  "Where I an atom crawled and cleaved and sundered,",
  "I saw a million motions, but one law;",
  "And from the city's splendor to my eyes",
  "The vapors passed and there was nought but Love,",
  "A ferment turbulent, intensely fair,",
  "Where Beauty beckoned and where Strength pursued.",
  "",
  "II",
  "",
  "",
  "There was a time when I thought much of Fame,",
  "And laid the golden edifice to be",
  "That in the clear light of eternity",
  "Should fitly house the glory of my name.",
  "",
  "",
  "But swifter than my fingers pushed their plan,",
  "Over the fair foundation scarce begun,",
  "While I with lovers dallied in the sun,",
  "The ivy clambered and the rose-vine ran.",
  "",
  "",
  "And now, too late to see my vision, rise,",
  "In place of golden pinnacles and towers,",
  "Only some sunny mounds of leaves and flowers,",
  "Only beloved of birds and butterflies.",
  "",
  "",
  "My friends were duped, my favorers deceived;",
  "But sometimes, musing sorrowfully there,",
  "That flowered wreck has seemed to me so fair",
  "I scarce regret the temple unachieved.",
  "",
  "III",
  "",
  "",
  "For there were nights . . . my love to him whose brow",
  "Has glistened with the spoils of nights like those,",
  "Home turning as a conqueror turns home,",
  "What time green dawn down every street uprears",
  "Arches of triumph! He has drained as well",
  "Joy's perfumed bowl and cried as I have cried:",
  "Be Fame their mistress whom Love passes by.",
  "This only matters: from some flowery bed,",
  "Laden with sweetness like a homing bee,",
  "If one have known what bliss it is to come,",
  "Bearing on hands and breast and laughing lips",
  "The fragrance of his youth's dear rose. To him",
  "The hills have bared their treasure, the far clouds",
  "Unveiled the vision that o'er summer seas",
  "Drew on his thirsting arms. This last thing known,",
  "He can court danger, laugh at perilous odds,",
  "And, pillowed on a memory so sweet,",
  "Unto oblivious eternity",
  "Without regret yield his victorious soul,",
  "The blessed pilgrim of a vow fulfilled.",
  "",
  "IV",
  "",
  "",
  "What is Success? Out of the endless ore",
  "Of deep desire to coin the utmost gold",
  "Of passionate memory; to have lived so well",
  "That the fifth moon, when it swims up once more",
  "Through orchard boughs where mating orioles build",
  "And apple flowers unfold,",
  "Find not of that dear need that all things tell",
  "The heart unburdened nor the arms unfilled.",
  "",
  "",
  "O Love, whereof my boyhood was the dream,",
  "My youth the beautiful novitiate,",
  "Life was so slight a thing and thou so great,",
  "How could I make thee less than all-supreme!",
  "In thy sweet transports not alone I thought",
  "Mingled the twain that panted breast to breast.",
  "The sun and stars throbbed with them; they were caught",
  "Into the pulse of Nature and possessed",
  "By the same light that consecrates it so.",
  "Love! -- 'tis the payment of the debt we owe",
  "The beauty of the world, and whensoe'er",
  "In silks and perfume and unloosened hair",
  "The loveliness of lovers, face to face,",
  "Lies folded in the adorable embrace,",
  "Doubt not as of a perfect sacrifice",
  "That soul partakes whose inspiration fills",
  "The springtime and the depth of summer skies,",
  "The rainbow and the clouds behind the hills,",
  "That excellence in earth and air and sea",
  "That makes things as they are the real divinity.",
  ""
]