module.exports = [
  "\"WHAT say _I_?\"--not a syllable further in prose;",
  "I'm your man \"of all measures,\" dear Tom,--so here goes!",
  "Here goes, for a swim on the stream of old Time,",
  "On those buoyant supporters, the bladders of rhyme.",
  "If our weight breaks them down, and we sink in the flood,",
  "We are smothered, at least, in respectable mud,",
  "Where the divers of Bathos lie drowned in a heap,",
  "And Southey's last Pæan has pillowed his sleep;",
  "That _Felo de se_ who, half drunk with his Malmsey,",
  "Walked out of his depth and was lost in a calm sea,",
  "Singing \"Glory to God\" in a spick and span stanza,",
  "The like (since Tom Sternhold was choked) never man saw.",
  "",
  "The papers have told you, no doubt, of the fusses,",
  "The fêtes, and the gapings to get at these Russes,--",
  "Of his Majesty's suite, up from coachman to Hetman,--",
  "And what dignity decks the flat face of the great man.",
  "I saw him, last week, at two balls and a party,--",
  "For a Prince, his demeanour was rather too hearty.",
  "You know, _we_ are used to quite different graces,",
  "",
  "The Czar's look, I own, was much brighter and brisker,",
  "But then he is sadly deficient in whisker;",
  "And wore but a starless blue coat, and in kersey-",
  "mere breeches whisked round, in a waltz with the Jersey,",
  "Who, lovely as ever, seemed just as delighted",
  "With Majesty's presence as those she invited.",
  ""
]