module.exports = [
  "SCENE.--BEFORE THE CAVERN OF THE INDIAN ENCHANTRESS.",
  "",
  "THE ENCHANTRESS COMES FORTH.",
  "",
  "ENCHANTRESS:",
  "He came like a dream in the dawn of life,",
  "He fled like a shadow before its noon;",
  "He is gone, and my peace is turned to strife,",
  "And I wander and wane like the weary moon.",
  "O, sweet Echo, wake,",
  "And for my sake",
  "Make answer the while my heart shall break!",
  "",
  "But my heart has a music which Echo's lips,",
  "Though tender and true, yet can answer not,",
  "And the shadow that moves in the soul's eclipse",
  "Can return not the kiss by his now forgot;",
  "Sweet lips! he who hath",
  "On my desolate path",
  "Cast the darkness of absence, worse than death!",
  "",
  "[THE ENCHANTRESS MAKES HER SPELL: SHE IS ANSWERED BY A SPIRIT.]",
  "",
  "SPIRIT:",
  "Within the silent centre of the earth",
  "My mansion is; where I have lived insphered",
  "From the beginning, and around my sleep",
  "Have woven all the wondrous imagery",
  "Of this dim spot, which mortals call the world;",
  "Infinite depths of unknown elements",
  "Massed into one impenetrable mask;",
  "Sheets of immeasurable fire, and veins",
  "Of gold and stone, and adamantine iron.",
  "And as a veil in which I walk through Heaven",
  "I have wrought mountains, seas, and waves, and clouds,",
  "And lastly light, whose interfusion dawns",
  "In the dark space of interstellar air.",
  "",
  "ANOTHER SCENE.",
  "",
  "INDIAN YOUTH AND LADY.",
  "",
  "INDIAN:",
  "And, if my grief should still be dearer to me",
  "Than all the pleasures in the world beside,",
  "Why would you lighten it?--",
  "",
  "LADY:",
  "I offer only",
  "That which I seek, some human sympathy",
  "In this mysterious island.",
  "",
  "INDIAN:",
  "Oh! my friend,",
  "My sister, my beloved!--What do I say?",
  "My brain is dizzy, and I scarce know whether",
  "I speak to thee or her.",
  "",
  "LADY:",
  "Peace, perturbed heart!",
  "I am to thee only as thou to mine,",
  "The passing wind which heals the brow at noon,",
  "And may strike cold into the breast at night,",
  "Yet cannot linger where it soothes the most,",
  "Or long soothe could it linger.",
  "",
  "INDIAN:",
  "But you said",
  "You also loved?",
  "",
  "LADY:",
  "Loved! Oh, I love. Methinks",
  "This word of love is fit for all the world,",
  "And that for gentle hearts another name",
  "Would speak of gentler thoughts than the world owns.",
  "I have loved.",
  "",
  "INDIAN:",
  "And thou lovest not? if so,",
  "Young as thou art thou canst afford to weep.",
  "",
  "LADY:",
  "Oh! would that I could claim exemption",
  "From all the bitterness of that sweet name.",
  "I loved, I love, and when I love no more",
  "Let joys and grief perish, and leave despair",
  "To ring the knell of youth. He stood beside me,",
  "The embodied vision of the brightest dream,",
  "Which like a dawn heralds the day of life;",
  "The shadow of his presence made my world",
  "A Paradise. All familiar things he touched,",
  "All common words he spoke, became to me",
  "Like forms and sounds of a diviner world.",
  "He was as is the sun in his fierce youth,",
  "As terrible and lovely as a tempest;",
  "He came, and went, and left me what I am.",
  "Alas! Why must I think how oft we two",
  "Have sate together near the river springs,",
  "Under the green pavilion which the willow",
  "Spreads on the floor of the unbroken fountain,",
  "Strewn, by the nurslings that linger there,",
  "Over that islet paved with flowers and moss,",
  "While the musk-rose leaves, like flakes of crimson snow,",
  "Showered on us, and the dove mourned in the pine,",
  "Sad prophetess of sorrows not her own?",
  "The crane returned to her unfrozen haunt,",
  "And the false cuckoo bade the spray good morn;",
  "And on a wintry bough the widowed bird,",
  "Hid in the deepest night of ivy-leaves,",
  "Renewed the vigils of a sleepless sorrow.",
  "I, left like her, and leaving one like her,",
  "Alike abandoned and abandoning",
  "(Oh! unlike her in this!) the gentlest youth,",
  "Whose love had made my sorrows dear to him,",
  "Even as my sorrow made his love to me!",
  "",
  "INDIAN:",
  "One curse of Nature stamps in the same mould",
  "The features of the wretched; and they are",
  "As like as violet to violet,",
  "When memory, the ghost, their odours keeps",
  "Mid the cold relics of abandoned joy.--",
  "Proceed.",
  "",
  "LADY:",
  "He was a simple innocent boy.",
  "I loved him well, but not as he desired;",
  "Yet even thus he was content to be:--",
  "A short content, for I was--",
  "",
  "INDIAN [ASIDE]:",
  "God of Heaven!",
  "From such an islet, such a river-spring--!",
  "I dare not ask her if there stood upon it",
  "A pleasure-dome surmounted by a crescent,",
  "With steps to the blue water.",
  "[ALOUD.]",
  "It may be",
  "That Nature masks in life several copies",
  "Of the same lot, so that the sufferers",
  "May feel another's sorrow as their own,",
  "And find in friendship what they lost in love.",
  "That cannot be: yet it is strange that we,",
  "From the same scene, by the same path to this",
  "Realm of abandonment-- But speak! your breath--",
  "Your breath is like soft music, your words are",
  "The echoes of a voice which on my heart",
  "Sleeps like a melody of early days.",
  "But as you said--",
  "",
  "LADY:",
  "He was so awful, yet",
  "So beautiful in mystery and terror,",
  "Calming me as the loveliness of heaven",
  "Soothes the unquiet sea:--and yet not so,",
  "For he seemed stormy, and would often seem",
  "A quenchless sun masked in portentous clouds;",
  "For such his thoughts, and even his actions were;",
  "But he was not of them, nor they of him,",
  "But as they hid his splendour from the earth.",
  "Some said he was a man of blood and peril,",
  "And steeped in bitter infamy to the lips.",
  "More need was there I should be innocent,",
  "More need that I should be most true and kind,",
  "And much more need that there should be found one",
  "To share remorse and scorn and solitude,",
  "And all the ills that wait on those who do",
  "The tasks of ruin in the world of life.",
  "He fled, and I have followed him.",
  "",
  "INDIAN:",
  "Such a one",
  "Is he who was the winter of my peace.",
  "But, fairest stranger, when didst thou depart",
  "From the far hills where rise the springs of India?",
  "How didst thou pass the intervening sea?",
  "",
  "LADY:",
  "If I be sure I am not dreaming now,",
  "I should not doubt to say it was a dream.",
  "Methought a star came down from heaven,",
  "And rested mid the plants of India,",
  "Which I had given a shelter from the frost",
  "Within my chamber. There the meteor lay,",
  "Panting forth light among the leaves and flowers,",
  "As if it lived, and was outworn with speed;",
  "Or that it loved, and passion made the pulse",
  "Of its bright life throb like an anxious heart,",
  "Till it diffused itself; and all the chamber",
  "And walls seemed melted into emerald fire",
  "That burned not; in the midst of which appeared",
  "A spirit like a child, and laughed aloud",
  "A thrilling peal of such sweet merriment",
  "As made the blood tingle in my warm feet:",
  "Then bent over a vase, and murmuring",
  "Low, unintelligible melodies,",
  "Placed something in the mould like melon-seeds,",
  "And slowly faded, and in place of it",
  "A soft hand issued from the veil of fire,",
  "Holding a cup like a magnolia flower,",
  "And poured upon the earth within the vase",
  "The element with which it overflowed,",
  "Brighter than morning light, and purer than",
  "The water of the springs of Himalah.",
  "",
  "INDIAN:",
  "You waked not?",
  "",
  "LADY:",
  "Not until my dream became",
  "Like a child's legend on the tideless sand.",
  "Which the first foam erases half, and half",
  "Leaves legible. At length I rose, and went,",
  "Visiting my flowers from pot to pot, and thought",
  "To set new cuttings in the empty urns,",
  "And when I came to that beside the lattice,",
  "I saw two little dark-green leaves",
  "Lifting the light mould at their birth, and then",
  "I half-remembered my forgotten dream.",
  "And day by day, green as a gourd in June,",
  "The plant grew fresh and thick, yet no one knew",
  "What plant it was; its stem and tendrils seemed",
  "Like emerald snakes, mottled and diamonded",
  "With azure mail and streaks of woven silver;",
  "And all the sheaths that folded the dark buds",
  "Rose like the crest of cobra-di-capel,",
  "Until the golden eye of the bright flower,",
  "Through the dark lashes of those veined lids,",
  "...disencumbered of their silent sleep,",
  "Gazed like a star into the morning light.",
  "Its leaves were delicate, you almost saw",
  "The pulses",
  "With which the purple velvet flower was fed",
  "To overflow, and like a poet's heart",
  "Changing bright fancy to sweet sentiment,",
  "Changed half the light to fragrance. It soon fell,",
  "And to a green and dewy embryo-fruit",
  "Left all its treasured beauty. Day by day",
  "I nursed the plant, and on the double flute",
  "Played to it on the sunny winter days",
  "Soft melodies, as sweet as April rain",
  "On silent leaves, and sang those words in which",
  "Passion makes Echo taunt the sleeping strings;",
  "And I would send tales of forgotten love",
  "Late into the lone night, and sing wild songs",
  "Of maids deserted in the olden time,",
  "And weep like a soft cloud in April's bosom",
  "Upon the sleeping eyelids of the plant,",
  "So that perhaps it dreamed that Spring was come,",
  "And crept abroad into the moonlight air,",
  "And loosened all its limbs, as, noon by noon,",
  "The sun averted less his oblique beam.",
  "",
  "INDIAN:",
  "And the plant died not in the frost?",
  "",
  "LADY:",
  "It grew;",
  "And went out of the lattice which I left",
  "Half open for it, trailing its quaint spires",
  "Along the garden and across the lawn,",
  "And down the slope of moss and through the tufts",
  "Of wild-flower roots, and stumps of trees o'ergrown",
  "With simple lichens, and old hoary stones,",
  "On to the margin of the glassy pool,",
  "Even to a nook of unblown violets",
  "And lilies-of-the-valley yet unborn,",
  "Under a pine with ivy overgrown.",
  "And theme its fruit lay like a sleeping lizard",
  "Under the shadows; but when Spring indeed",
  "Came to unswathe her infants, and the lilies",
  "Peeped from their bright green masks to wonder at",
  "This shape of autumn couched in their recess,",
  "Then it dilated, and it grew until",
  "One half lay floating on the fountain wave,",
  "Whose pulse, elapsed in unlike sympathies,",
  "Kept time",
  "Among the snowy water-lily buds.",
  "Its shape was such as summer melody",
  "Of the south wind in spicy vales might give",
  "To some light cloud bound from the golden dawn",
  "To fairy isles of evening, and it seemed",
  "In hue and form that it had been a mirror",
  "Of all the hues and forms around it and",
  "Upon it pictured by the sunny beams",
  "Which, from the bright vibrations of the pool,",
  "Were thrown upon the rafters and the roof",
  "Of boughs and leaves, and on the pillared stems",
  "Of the dark sylvan temple, and reflections",
  "Of every infant flower and star of moss",
  "And veined leaf in the azure odorous air.",
  "And thus it lay in the Elysian calm",
  "Of its own beauty, floating on the line",
  "Which, like a film in purest space, divided",
  "The heaven beneath the water from the heaven",
  "Above the clouds; and every day I went",
  "Watching its growth and wondering;",
  "And as the day grew hot, methought I saw",
  "A glassy vapour dancing on the pool,",
  "And on it little quaint and filmy shapes.",
  "With dizzy motion, wheel and rise and fall,",
  "Like clouds of gnats with perfect lineaments.",
  "",
  "...",
  "",
  "O friend, sleep was a veil uplift from Heaven--",
  "As if Heaven dawned upon the world of dream--",
  "When darkness rose on the extinguished day",
  "Out of the eastern wilderness.",
  "",
  "INDIAN:",
  "I too",
  "Have found a moment's paradise in sleep",
  "Half compensate a hell of waking sorrow.",
  ""
]