module.exports = [
  "Come, my Lucasia, since we see",
  "That miracles Men's Faith do move,",
  "By wonder and by prodigy",
  "To the dull angry World let's prove",
  "There's a Religion in our Love.",
  "",
  "For Though we were design'd t'agree,",
  "That Fate no liberty destroys,",
  "But our Election is as free",
  "As Angels, who with greedy choice",
  "Are yet determin'd to their joys.",
  "",
  "Our hearts are doubled by the loss,",
  "Here Mixture is Addition grown;",
  "We both diffuse, and both ingross:",
  "And we whose minds are so much one,",
  "Never, yet ever are alone.",
  "",
  "We court our own Captivity",
  "Than Thrones more great and innocent:",
  "`Twere banishment to be set free,",
  "Since we wear fetters whose intent",
  "Not Bondage is but Ornament",
  "",
  "Divided joys are tedious found,",
  "And griefs united easier grow:",
  "We are our selves but by rebound,",
  "And all our Titles shuffled so,",
  "Both Princes, and both Subjects too.",
  "",
  "Our Hearts are mutual Victims laid,",
  "While they (such power in Friendship lies)",
  "Are Altars, Priests, and Off'rings made:",
  "And each Heart which thus kindly dies,",
  "Grows deathless by the Sacrifice.",
  ""
]