module.exports = [
  "VI",
  "We lack, yet cannot fix upon the lack:",
  "Not this, nor that; yet somewhat, certainly.",
  "We see the things we do not yearn to see",
  "Around us: and what see we glancing back?",
  "Lost hopes that leave our hearts upon the rack,",
  "Hopes that were never ours yet seem’d to be,",
  "For which we steer’d on life’s salt stormy sea",
  "Braving the sunstroke and the frozen pack.",
  "If thus to look behind is all in vain,",
  "And all in vain to look to left or right,",
  "Why face we not our future once again,",
  "Launching with hardier hearts across the main,",
  "Straining dim eyes to catch the invisible sight,",
  "And strong to bear ourselves in patient pain?",
  "",
  "IX",
  "Star Sirius and the Pole Star dwell afar",
  "Beyond the drawings each of other’s strength:",
  "One blazes through the brief bright summer’s length",
  "Lavishing life-heat from a flaming car;",
  "While one unchangeable upon a throne",
  "Broods o’er the frozen heart of earth alone,",
  "Content to reign the bright particular star",
  "Of some who wander or of some who groan.",
  "They own no drawings each of other’s strength,",
  "Nor vibrate in a visible sympathy,",
  "Nor veer along their courses each toward",
  "Yet are their orbits pitch’d in harmony",
  "Of one dear heaven, across whose depth and length",
  "Mayhap they talk together without speech.",
  ""
]