module.exports = [
  "Your soul was lifted by the wings today",
  "Hearing the master of the violin:",
  "You praised him, praised the great Sabastian too",
  "Who made that fine Chaconne; but did you think",
  "Of old Antonio Stradivari? -him",
  "Who a good century and a half ago",
  "Put his true work in that brown instrument",
  "And by the nice adjustment of its frame",
  "Gave it responsive life, continuous",
  "With the master's finger-tips and perfected",
  "Like them by delicate rectitude of use.",
  "That plain white-aproned man, who stood at work",
  "Patient and accurate full fourscore years,",
  "Cherished his sight and touch by temperance,",
  "And since keen sense is love of perfectness",
  "Made perfect violins, the needed paths",
  "For inspiration and high mastery.",
  "",
  "No simpler man than he; he never cried,",
  "\"why was I born to this monotonous task",
  "Of making violins?\" or flung them down",
  "To suit with hurling act well-hurled curse",
  "At labor on such perishable stuff.",
  "Hence neighbors in Cremona held him dull,",
  "Called him a slave, a mill-horse, a machine.",
  "",
  "Naldo, a painter of eclectic school,",
  "Knowing all tricks of style at thirty-one,",
  "And weary of them, while Antonio",
  "At sixty-nine wrought placidly his best,",
  "Making the violin you heard today -",
  "Naldo would tease him oft to tell his aims.",
  "\"Perhaps thou hast some pleasant vice to feed -",
  "the love of louis d'ors in heaps of four,",
  "Each violin a heap - I've naught to blame;",
  "My vices waste such heaps. But then, why work",
  "With painful nicety?\"",
  "",
  "Antonio then:",
  "\"I like the gold - well, yes - but not for meals.",
  "And as my stomach, so my eye and hand,",
  "And inward sense that works along with both,",
  "Have hunger that can never feed on coin.",
  "Who draws a line and satisfies his soul,",
  "Making it crooked where it should be straight?",
  "Antonio Stradivari has an eye",
  "That winces at false work and loves the true.\"",
  "Then Naldo: \"'Tis a petty kind of fame",
  "At best, that comes of making violins;",
  "And saves no masses, either. Thou wilt go",
  "To purgatory none the less.\"",
  "",
  "But he:",
  "\"'Twere purgatory here to make them ill;",
  "And for my fame - when any master holds",
  "'Twixt chin and hand a violin of mine,",
  "He will be glad that Stradivari lived,",
  "Made violins, and made them of the best.",
  "The masters only know whose work is good:",
  "They will choose mine, and while God gives them skill",
  "I give them instruments to play upon,",
  "God choosing me to help him.",
  "",
  "\"What! Were God",
  "at fault for violins, thou absent?\"",
  "",
  "\"Yes;",
  "He were at fault for Stradivari's work.\"",
  "",
  "\"Why, many hold Giuseppe's violins",
  "As good as thine.\"",
  "",
  "\"May be: they are different.",
  "His quality declines: he spoils his hand",
  "With over-drinking. But were his the best,",
  "He could not work for two. My work is mine,",
  "And, heresy or not, if my hand slacked",
  "I should rob God - since his is fullest good -",
  "Leaving a blank instead of violins.",
  "I say, not God himself can make man's best",
  "Without best men to help him.",
  "",
  "'Tis God gives skill,",
  "But not without men's hands: he could not make",
  "Antonio Stradivari's violins",
  "Without Antonio. Get thee to thy easel.\"",
  ""
]