module.exports = [
  "(Reply of the Pythian Oracle to Philip of Macedon.)",
  "",
  "Oh! could LE SAGE'S demon's gift",
  "  Be realis'd at my desire,",
  "This night my trembling form he'd lift",
  "  To place it on St. Mary's spire.",
  "",
  "Then would, unroof'd, old Granta's halls,",
  "  Pedantic inmates full display;",
  "_Fellows_ who dream on _lawn_ or _stalls_,",
  "  The price of venal votes to pay.",
  "",
  "Then would I view each rival wight,",
  "  PETTY and PALMERSTON survey;",
  "Who canvass there, with all their might,",
  "  Against the next elective day.",
  "",
  "Lo! candidates and voters lie",
  "  All lull'd in sleep, a goodly number!",
  "A race renown'd for piety,",
  "  Whose conscience won't disturb their slumber.",
  "",
  "Lord H---indeed, may not demur;",
  "  Fellows are sage, reflecting men:",
  "They know preferment can occur,",
  "  But very seldom,--_now_ and _then_.",
  "",
  "They know the Chancellor has got",
  "  Some pretty livings in disposal:",
  "Each hopes that _one_ may be his _lot_,",
  "  And, therefore, smiles on his proposal.",
  "",
  "Now from the soporific scene",
  "  I'll turn mine eye, as night grows later,",
  "To view, unheeded and unseen,",
  "  The studious sons of Alma Mater.",
  "",
  "There, in apartments small and damp,",
  "  The candidate for college prizes,",
  "Sits poring by the midnight lamp;",
  "  Goes late to bed, yet early rises.",
  "",
  "He surely well deserves to gain them,",
  "  With all the honours of his college,",
  "Who, striving hardly to obtain them,",
  "  Thus seeks unprofitable knowledge:",
  "",
  "Who sacrifices hours of rest,",
  "  To scan precisely metres Attic;",
  "Or agitates his anxious breast,",
  "  In solving problems mathematic:",
  "",
  "Who reads false quantities in Seale,",
  "  Or puzzles o'er the deep triangle;",
  "Depriv'd of many a wholesome meal;",
  "  In _barbarous Latin_ doom'd to wrangle:",
  "",
  "Renouncing every pleasing page,",
  "  From authors of historic use;",
  "Preferring to the letter'd sage,",
  "  The square of the hypothenuse.",
  "",
  "Still, harmless are these occupations,",
  "That hurt none but the hapless student,",
  "Compar'd with other recreations,",
  "Which bring together the imprudent;",
  "",
  "Whose daring revels shock the sight,",
  "When vice and infamy combine,",
  "When Drunkenness and dice invite,",
  "As every sense is steep'd in wine.",
  "",
  "Not so the methodistic crew,",
  "Who plans of reformation lay:",
  "In humble attitude they sue,",
  "And for the sins of others pray:",
  "",
  "Forgetting that their pride of spirit,",
  "Their exultation in their trial,",
  "Detracts most largely from the merit",
  "Of all their boasted self-denial.",
  "",
  "'Tis morn:--from these I turn my sight:",
  "What scene is this which meets the eye?",
  "A numerous crowd array'd in white,",
  "Across the green in numbers fly.",
  "",
  "Loud rings in air the chapel bell;",
  "'Tis hush'd:--what sounds are these I hear?",
  "The organ's soft celestial swell",
  "Rolls deeply on the listening ear.",
  "",
  "To this is join'd the sacred song,",
  "The royal minstrel's hallow'd strain;",
  "Though _he_ who hears the _music_ long,",
  "Will _never_ wish to _hear again_.",
  "",
  "Our choir would scarcely be excus'd,",
  "E'en as a band of raw beginners;",
  "All mercy, now, must be refus'd",
  "To such a set of croaking sinners.",
  "",
  "If David, when his toils were ended,",
  "Had heard these blockheads sing before him,",
  "To us his psalms had ne'er descended,--",
  "In furious mood he would have tore 'em.",
  "",
  "The luckless Israelites, when taken",
  "By some inhuman tyrant's order,",
  "Were ask'd to sing, by joy forsaken,",
  "On Babylonian river's border.",
  "",
  "Oh! had they sung in notes like these",
  "Inspir'd by stratagem or fear,",
  "They might have set their hearts at ease,",
  "The devil a soul had stay'd to hear.",
  "",
  "But if I scribble longer now,",
  "The deuce a soul will _stay to read_;",
  "My pen is blunt, my ink is low;",
  "'Tis almost time to _stop_, _indeed_.",
  "",
  "Therefore, farewell, old _Granta's_ spires!",
  "No more, like _Cleofas_, I fly;",
  "No more thy theme my Muse inspires:",
  "The reader's tir'd, and so am I.",
  ""
]