module.exports = [
  "He told a homely tale",
  "And spotted it with tears --",
  "Upon his infant face was set",
  "The Cicatrice of years --",
  "",
  "All crumpled was the cheek",
  "No other kiss had known",
  "Than flake of snow, divided with",
  "The Redbreast of the Barn --",
  "",
  "If Mother -- in the Grave --",
  "Or Father -- on the Sea --",
  "Or Father in the Firmament --",
  "Or Brethren, had he --",
  "",
  "If Commonwealth below,",
  "Or Commonwealth above",
  "Have missed a Barefoot Citizen --",
  "I've ransomed it -- alive --",
  ""
]