module.exports = [
  "FOUR miles at a leap, over the dark hollow land,",
  "To the frosted steep of the down and its junipers",
  "    black,",
  "Travels my eye with equal ease and delight:",
  "And scarce could my body leap four yards.",
  "",
  "This is the best and the worst of it--",
  "Never to know,",
  "Yet to imagine gloriously, pure health.",
  "",
  "To-day, had I suddenly health,",
  "I could not satisfy the desire of my heart",
  "Unless health abated it,",
  "So beautiful is the air in its softness and clearness,",
  "    while Spring",
  "Promises all and fails in nothing as yet;",
  "And what blue and what white is I never knew",
  "Before I saw this sky blessing the land.",
  "",
  "For had I health I could not ride or run or fly",
  "So far or so rapidly over the land",
  "As I desire: I should reach Wiltshire tired;",
  "I should have changed my mind before I could be",
  "    in Wales.",
  "I could not love; I could not command love.",
  "Beauty would still be far off",
  "However many hills I climbed over;",
  "Peace would still be farther.",
  "",
  "Maybe I should not count it anything",
  "To leap these four miles with the eye;",
  "And either I should not be filled almost to bursting",
  "    with desire,",
  "Or with my power desire would still keep pace.",
  "",
  "Yet I am not satisfied",
  "Even with knowing I never could be satisfied.",
  "With health and all the power that lies",
  "In maiden beauty, poet and warrior,",
  "In Caesar, Shakespeare, Alcibiades,",
  "Mazeppa, Leonardo, Michelangelo,",
  "In any maiden whose smile is lovelier",
  "Than sunlight upon dew,",
  "I could not be as the wagtail running up and down",
  "The warm tiles of the roof slope, twittering",
  "Happily and sweetly as if the sun itself",
  "Extracted the song",
  "As the hand makes sparks from the fur of a cat:",
  "",
  "I could not be as the sun.",
  "Nor should I be content to be",
  "As little as the bird or as mighty as the sun.",
  "For the bird knows not of the sun,",
  "And the sun regards not the bird.",
  "But I am almost proud to love both bird and sun,",
  "Though scarce this Spring could my body leap",
  "    four yards.",
  ""
]