module.exports = [
  "PART I.",
  "",
  "SCENE I.--_A woody and mountainous district near Mount",
  "                    Ararat.--Time, midnight_.",
  "",
  "               _Enter_ ANAH _and_ AHOLIBAMAH.",
  "",
  "_Anah_. OUR father sleeps: it is the hour when they",
  "Who love us are accustomed to descend",
  "Through the deep clouds o'er rocky Ararat:--",
  "How my heart beats!",
  "",
  "_Aho._               Let us proceed upon",
  "Our invocation.",
  "",
  "_Anah_.         But the stars are hidden.",
  "I tremble.",
  "",
  "_Aho._     So do I, but not with fear",
  "Of aught save their delay.",
  "",
  "_Anah_.                    My sister, though",
  "I love Azaziel more than----oh, too much!",
  "What was I going to say? my heart grows impious.",
  "",
  "_Aho._ And where is the impiety of loving",
  "Celestial natures?",
  "",
  "_Anah_.            But, Aholibamah,",
  "I love our God less since his angel loved me:",
  "This cannot be of good; and though I know not",
  "That I do wrong, I feel a thousand fears",
  "Which are not ominous of right.",
  "",
  "_Aho._                          Then wed thee",
  "Unto some son of clay, and toil and spin!",
  "There's Japhet loves thee well, hath loved thee long:",
  "Marry, and bring forth dust!",
  "",
  "_Anah_.                      I should have loved",
  "Azaziel not less were he mortal; yet",
  "I am glad he is not. I cannot outlive him.",
  "And when I think that his immortal wings",
  "Will one day hover o'er the sepulchre",
  "Of the poor child of clay which so adored him,",
  "As he adores the Highest, death becomes",
  "Less terrible; but yet I pity him:",
  "His grief will be of ages, or at least",
  "Mine would be such for him, were I the Seraph,",
  "And he the perishable.",
  "",
  "_Aho._                 Rather say,",
  "That he will single forth some other daughter",
  "Of earth, and love her as he once loved Anah.",
  "",
  "_Anah_. And if it should be so, and she loved him,",
  "Better thus than that he should weep for me.",
  "",
  "_Aho._ If I thought thus of Samiasa's love,",
  "All Seraph as he is, I'd spurn him from me.",
  "But to our invocation!--'Tis the hour.",
  "",
  "_Anah_.",
  "                Seraph!",
  "             From thy sphere!",
  "  Whatever star contain thy glory;",
  "    In the eternal depths of heaven",
  "    Albeit thou watchest with \"the seven,\"",
  "  Though through space infinite and hoary",
  "    Before thy bright wings worlds be driven,",
  "                   Yet hear!",
  "  Oh! think of her who holds thee dear!",
  "    And though she nothing is to thee,",
  "  Yet think that thou art all to her.",
  "    Thou canst not tell,--and never be",
  "    Such pangs decreed to aught save me,--",
  "      The bitterness of tears.",
  "      Eternity is in thine years,",
  "  Unborn, undying beauty in thine eyes;",
  "  With me thou canst not sympathise,",
  "    Except in love, and there thou must",
  "    Acknowledge that more loving dust",
  "  Ne'er wept beneath the skies.",
  "  Thou walk'st thy many worlds, thou see'st",
  "    The face of him who made thee great,",
  "  As he hath made me of the least",
  "    Of those cast out from Eden's gate:",
  "              Yet, Seraph dear!",
  "                  Oh hear!",
  "  For thou hast loved me, and I would not die",
  "    Until I know what I must die in knowing,",
  "  That thou forget'st in thine eternity",
  "    Her whose heart Death could not keep from o'er-flowing",
  "  For thee, immortal essence as thou art!",
  "    Great is their love who love in sin and fear;",
  "  And such, I feel, are waging in my heart",
  "  A war unworthy: to an Adamite",
  "    Forgive, my Seraph! that such thoughts appear,",
  "      For sorrow is our element;",
  "                 Delight",
  "  An Eden kept afar from sight,",
  "      Though sometimes with our visions blent.",
  "              The hour is near",
  "  Which tells me we are not abandoned quite.--",
  "               Appear! Appear!",
  "                  Seraph!",
  "      My own Azaziel! be but here,",
  "  And leave the stars to their own light!",
  "",
  "_Aho._",
  "               Samiasa!",
  "               Wheresoe'er",
  "      Thou rulest in the upper air--",
  "      Or warring with the spirits who may dare",
  "              Dispute with him",
  "    Who made all empires, empire; or recalling",
  "  Some wandering star, which shoots through the abyss,",
  "    Whose tenants dying, while their world is falling,",
  "  Share the dim destiny of clay in this;",
  "    Or joining with the inferior cherubim,",
  "    Thou deignest to partake their hymn--",
  "               Samiasa!",
  "  I call thee, I await thee, and I love thee.",
  "    Many may worship thee, that will I not:",
  "  If that thy spirit down to mine may move thee,",
  "    Descend and share my lot!",
  "    Though I be formed of clay,",
  "      And thou of beams",
  "    More bright than those of day",
  "      On Eden's streams,",
  "    Thine immortality can not repay",
  "      With love more warm than mine",
  "    My love. There is a ray",
  "      In me, which, though forbidden yet to shine,",
  "      I feel was lighted at thy God's and thine.",
  "    It may be hidden long: death and decay",
  "      Our mother Eve bequeathed us--but my heart",
  "    Defies it: though this life must pass away,",
  "      Is _that_ a cause for thee and me to part?",
  "    Thou art immortal--so am I: I feel--",
  "      I feel my immortality o'ersweep",
  "    All pains, all tears, all fears, and peal,",
  "      Like the eternal thunders of the deep,",
  "    Into my ears this truth--\"Thou liv'st for ever!\"",
  "        But if it be in joy",
  "    I know not, nor would know;",
  "  That secret rests with the Almighty giver,",
  "    Who folds in clouds the fonts of bliss and woe.",
  "        But thee and me he never can destroy;",
  "    Change us he may, but not o'erwhelm; we are",
  "    Of as eternal essence, and must war",
  "    With him if he will war with us; with _thee_",
  "      I can share all things, even immortal sorrow;",
  "    For thou hast ventured to share life with _me_,",
  "    And shall _I_ shrink from thine eternity?",
  "      No! though the serpent's sting should pierce me thorough,",
  "    And thou thyself wert like the serpent, coil",
  "      Around me still! and I will smile,",
  "            And curse thee not; but hold",
  "          Thee in as warm a fold",
  "          As----but descend, and prove",
  "          A mortal's love",
  "  For an immortal. If the skies contain",
  "  More joy than thou canst give and take, remain!",
  "",
  "_Anah_. Sister! sister! I view them winging",
  "Their bright way through the parted night.",
  "",
  "_Aho._ The clouds from off their pinions flinging,",
  "As though they bore to-morrow's light.",
  "",
  "_Anah_. But if our father see the sight!",
  "",
  "_Aho._ He would but deem it was the moon",
  "Rising unto some sorcerer's tune",
  "An hour too soon.",
  "",
  "_Anah_. They come! _he_ comes!--Azaziel!",
  "",
  "_Aho._                                   Haste",
  "To meet them! Oh! for wings to bear",
  "My spirit, while they hover there,",
  "        To Samiasa's breast!",
  "",
  "_Anah_. Lo! they have kindled all the west,",
  "Like a returning sunset;--lo!",
  "        On Ararat's late secret crest",
  "A mild and many-coloured bow,",
  "The remnant of their flashing path,",
  "Now shines! and now, behold! it hath",
  "Returned to night, as rippling foam,",
  "  Which the Leviathan hath lashed",
  "From his unfathomable home,",
  "When sporting on the face of the calm deep,",
  "  Subsides soon after he again hath dashed",
  "Down, down, to where the Ocean's fountains sleep.",
  "",
  "_Aho._ They have touched earth! Samiasa!",
  "",
  "_Anah_.                                 My Azaziel!",
  "                                                            [_Exeunt_.",
  "",
  "SCENE II.--_Enter_ IRAD _and_ JAPHET.",
  "",
  "_Irad_. Despond not: wherefore wilt thou wander thus",
  "To add thy silence to the silent night,",
  "And lift thy tearful eye unto the stars?",
  "They cannot aid thee.",
  "",
  "_Japh._               But they soothe me--now",
  "Perhaps she looks upon them as I look.",
  "Methinks a being that is beautiful",
  "Becometh more so as it looks on beauty,",
  "The eternal beauty of undying things.",
  "Oh, Anah!",
  "",
  "_Irad_.    But she loves thee not.",
  "",
  "_Japh._                           Alas!",
  "",
  "_Irad_. And proud Aholibamah spurns me also.",
  "",
  "_Japh._ I feel for thee too.",
  "",
  "_Irad_.                      Let her keep her pride,",
  "Mine hath enabled me to bear her scorn:",
  "It may be, time too will avenge it.",
  "",
  "_Japh._                            Canst thou",
  "Find joy in such a thought?",
  "",
  "_Irad_.                     Nor joy nor sorrow.",
  "I loved her well; I would have loved her better,",
  "Had love been met with love: as 'tis, I leave her",
  "To brighter destinies, if so she deems them.",
  "",
  "_Japh._ What destinies?",
  "",
  "_Irad_.                 I have some cause to think",
  "She loves another.",
  "",
  "_Japh._             Anah!",
  "",
  "_Irad_.                  No; her sister.",
  "",
  "_Japh._ What other?",
  "",
  "_Irad_.             That I know not; but her air,",
  "If not her words, tells me she loves another.",
  "",
  "_Japh._ Aye, but not Anah: she but loves her God.",
  "",
  "_Irad_. Whate'er she loveth, so she loves thee not,",
  "What can it profit thee?",
  "",
  "_Japh._                  True, nothing; but",
  "I love.",
  "",
  "_Irad_. And so did I.",
  "",
  "_Japh._               And now thou lov'st not,",
  "Or think'st thou lov'st not, art thou happier?",
  "",
  "_Irad_.                                       Yes.",
  "",
  "_Japh._ I pity thee.",
  "",
  "_Irad_.              Me! why?",
  "",
  "_Japh._                      For being happy,",
  "Deprived of that which makes my misery.",
  "",
  "_Irad_. I take thy taunt as part of thy distemper,",
  "And would not feel as thou dost for more shekels",
  "Than all our father's herds would bring, if weighed",
  "Against the metal of the sons of Cain--",
  "The yellow dust they try to barter with us,",
  "As if such useless and discoloured trash,",
  "The refuse of the earth, could be received",
  "For milk, and wool, and flesh, and fruits, and all",
  "Our flocks and wilderness afford.--Go, Japhet,",
  "Sigh to the stars, as wolves howl to the moon--",
  "I must back to my rest.",
  "",
  "_Japh._                  And so would I",
  "If I could rest.",
  "",
  "_Irad_.          Thou wilt not to our tents then?",
  "",
  "_Japh._ No, Irad; I will to the cavern, whose",
  "Mouth they say opens from the internal world,",
  "To let the inner spirits of the earth",
  "Forth when they walk its surface.",
  "",
  "_Irad_.                            Wherefore so?",
  "What wouldst thou there?",
  "",
  "_Japh._                   Soothe further my sad spirit",
  "With gloom as sad: it is a hopeless spot,",
  "And I am hopeless.",
  "",
  "_Irad_.            But 'tis dangerous;",
  "Strange sounds and sights have peopled it with terrors.",
  "I must go with thee.",
  "",
  "_Japh._               Irad, no; believe me",
  "I feel no evil thought, and fear no evil.",
  "",
  "_Irad_. But evil things will be thy foe the more",
  "As not being of them: turn thy steps aside,",
  "Or let mine be with thine.",
  "",
  "_Japh._                    No, neither, Irad;",
  "I must proceed alone.",
  "",
  "_Irad_.                Then peace be with thee!",
  "                                                         [_Exit_ IRAD.",
  "",
  "_Japh._ (_solus_).",
  "Peace! I have sought it where it should be found,",
  "In love--with love, too, which perhaps deserved it;",
  "And, in its stead, a heaviness of heart,",
  "A weakness of the spirit, listless days,",
  "And nights inexorable to sweet sleep",
  "Have come upon me. Peace! what peace? the calm",
  "Of desolation, and the stillness of",
  "The untrodden forest, only broken by",
  "The sweeping tempest through its groaning boughs;",
  "Such is the sullen or the fitful state",
  "Of my mind overworn. The Earth's grown wicked,",
  "And many signs and portents have proclaimed",
  "A change at hand, and an o'erwhelming doom",
  "To perishable beings. Oh, my Anah!",
  "When the dread hour denounced shall open wide",
  "The fountains of the deep, how mightest thou",
  "Have lain within this bosom, folded from",
  "The elements; this bosom, which in vain",
  "Hath beat for thee, and then will beat more vainly,",
  "While thine--Oh, God! at least remit to her",
  "Thy wrath! for she is pure amidst the failing",
  "As a star in the clouds, which cannot quench,",
  "Although they obscure it for an hour. My Anah!",
  "How would I have adored thee, but thou wouldst not;",
  "And still would I redeem thee--see thee live",
  "When Ocean is earth's grave, and, unopposed",
  "By rock or shallow, the Leviathan,",
  "Lord of the shoreless sea and watery world,",
  "Shall wonder at his boundlessness of realm.            [_Exit_ JAPHET.",
  "",
  "                      _Enter_ NOAH _and_ SHEM.",
  "",
  "_Noah_. Where is thy brother Japhet?",
  "",
  "_Shem_.                              He went forth,",
  "According to his wont, to meet with Irad,",
  "He said; but, as I fear, to bend his steps",
  "Towards Anah's tents, round which he hovers nightly,",
  "Like a dove round and round its pillaged nest;",
  "Or else he walks the wild up to the cavern",
  "Which opens to the heart of Ararat.",
  "",
  "_Noah_. What doth he there? It is an evil spot",
  "Upon an earth all evil; for things worse",
  "Than even wicked men resort there: he",
  "Still loves this daughter of a fated race,",
  "Although he could not wed her if she loved him,",
  "And that she doth not. Oh, the unhappy hearts",
  "Of men! that one of my blood, knowing well",
  "The destiny and evil of these days,",
  "And that the hour approacheth, should indulge",
  "In such forbidden yearnings! Lead the way;",
  "He must be sought for!",
  "",
  "_Shem_.                 Go not forward, father:",
  "I will seek Japhet.",
  "",
  "_Noah_.              Do not fear for me:",
  "All evil things are powerless on the man",
  "Selected by Jehovah.--Let us on.",
  "",
  "_Shem_. To the tents of the father of the sisters?",
  "",
  "_Noah_. No; to the cavern of the Caucasus.",
  "                                           [_Exeunt_ NOAH _and_ SHEM.",
  "",
  "SCENE III.--_The mountains.--A cavern, and the rocks",
  "                 of Caucasus_.",
  "",
  "_Japh._ (_solus_). Ye wilds, that look eternal; and thou cave,",
  "Which seem'st unfathomable; and ye mountains,",
  "So varied and so terrible in beauty;",
  "Here, in your rugged majesty of rocks",
  "And toppling trees that twine their roots with stone",
  "In perpendicular places, where the foot",
  "Of man would tremble, could he reach them--yes,",
  "Ye look eternal! Yet, in a few days,",
  "Perhaps even hours, ye will be changed, rent, hurled",
  "Before the mass of waters; and yon cave,",
  "Which seems to lead into a lower world,",
  "Shall have its depths searched by the sweeping wave,",
  "And dolphins gambol in the lion's den!",
  "And man----Oh, men! my fellow-beings! Who",
  "Shall weep above your universal grave,",
  "Save I? Who shall be left to weep? My kinsmen,",
  "Alas! what am I better than ye are,",
  "That I must live beyond ye? Where shall be",
  "The pleasant places where I thought of Anah",
  "While I had hope? or the more savage haunts,",
  "Scarce less beloved, where I despaired for her?",
  "And can it be!--Shall yon exulting peak,",
  "Whose glittering top is like a distant star,",
  "Lie low beneath the boiling of the deep?",
  "No more to have the morning sun break forth,",
  "And scatter back the mists in floating folds",
  "From its tremendous brow? no more to have",
  "Day's broad orb drop behind its head at even,",
  "Leaving it with a crown of many hues?",
  "No more to be the beacon of the world,",
  "For angels to alight on, as the spot",
  "Nearest the stars? And can those words \"_no more_\"",
  "Be meant for thee, for all things, save for us,",
  "And the predestined creeping things reserved",
  "By my sire to Jehovah's bidding? May",
  "_He_ preserve _them_, and I _not_ have the power",
  "To snatch the loveliest of earth's daughters from",
  "A doom which even some serpent, with his mate,",
  "Shall 'scape to save his kind to be prolonged,",
  "To hiss and sting through some emerging world,",
  "Reeking and dank from out the slime, whose ooze",
  "Shall slumber o'er the wreck of this, until",
  "The salt morass subside into a sphere",
  "Beneath the sun, and be the monument,",
  "The sole and undistinguished sepulchre,",
  "Of yet quick myriads of all life? How much",
  "Breath will be stilled at once! All beauteous world!",
  "So young, so marked out for destruction, I",
  "With a cleft heart look on thee day by day,",
  "And night by night, thy numbered days and nights.",
  "I cannot save thee, cannot save even her",
  "Whose love had made me love thee more; but as",
  "A portion of thy dust, I cannot think",
  "Upon thy coming doom without a feeling",
  "Such as--Oh God! and canst thou--                        [_He pauses_.",
  "",
  "               [_A rushing sound from the cavern is heard, and shouts",
  "                      of laughter--afterwards a Spirit passes_.",
  "",
  "_Japh._                             In the name",
  "Of the Most High, what art thou?",
  "",
  "_Spirit_ (_laughs_).             Ha! ha! ha!",
  "",
  "_Japh._ By all that earth holds holiest, speak!",
  "",
  "_Spirit_ (_laughs_).                           Ha! ha!",
  "",
  "_Japh._ By the approaching deluge! by the earth",
  "Which will be strangled by the ocean! by",
  "The deep which will lay open all her fountains!",
  "The heaven which will convert her clouds to seas,",
  "And the Omnipotent who makes and crushes!",
  "Thou unknown, terrible, and indistinct,",
  "Yet awful Thing of Shadows, speak to me!",
  "Why dost thou laugh that horrid laugh?",
  "",
  "_Spirit_.                             Why weep'st thou?",
  "",
  "_Japh._ For earth and all her children.",
  "",
  "_Spirit_.                              Ha! ha! ha!",
  "                                                   [_Spirit vanishes_.",
  "",
  "_Japh._ How the fiend mocks the tortures of a world,",
  "The coming desolation of an orb,",
  "On which the sun shall rise and warm no life!",
  "How the earth sleeps! and all that in it is",
  "Sleep too upon the very eve of death!",
  "Why should they wake to meet it? What are here,",
  "Which look like death in life, and speak like things",
  "Born ere this dying world? They come like clouds!",
  "                              [_Various Spirits pass from the cavern_.",
  "",
  "_Spirit_.",
  "            Rejoice!",
  "        The abhorréd race",
  "  Which could not keep in Eden their high place,",
  "        But listened to the voice",
  "  Of knowledge without power,",
  "        Are nigh the hour,",
  "            Of Death!",
  "  Not slow, not single, not by sword, nor sorrow,",
  "    Nor years, nor heart-break, nor Time's sapping motion,",
  "  Shall they drop off. Behold their last to-morrow!",
  "        Earth shall be Ocean!",
  "            And no breath,",
  "  Save of the winds, be on the unbounded wave!",
  "        Angels shall tire their wings, but find no spot:",
  "  Not even a rock from out the liquid grave",
  "        Shall lift its point to save,",
  "  Or show the place where strong Despair hath died,",
  "  After long looking o'er the ocean wide",
  "        For the expected ebb which cometh not:",
  "            All shall be void,",
  "                Destroyed!",
  "  Another element shall be the lord",
  "    Of life, and the abhorred",
  "  Children of dust be quenched; and of each hue",
  "  Of earth nought left but the unbroken blue;",
  "  And of the variegated mountain",
  "        Shall nought remain",
  "        Unchanged, or of the level plain;",
  "        Cedar and pine shall lift their tops in vain:",
  "  All merged within the universal fountain,",
  "        Man, earth, and fire, shall die,",
  "            And sea and sky",
  "  Look vast and lifeless in the eternal eye.",
  "            Upon the foam",
  "                Who shall erect a home?",
  "",
  "_Japh._ (_coming forward_).",
  "                My sire!",
  "            Earth's seed shall not expire;",
  "            Only the evil shall be put away",
  "                From day.",
  "        Avaunt! ye exulting demons of the waste!",
  "  Who howl your hideous joy",
  "  When God destroys whom you dare not destroy:",
  "            Hence! haste!",
  "      Back to your inner caves!",
  "      Until the waves",
  "  Shall search you in your secret place,",
  "        And drive your sullen race",
  "  Forth, to be rolled upon the tossing winds,",
  "      In restless wretchedness along all space!",
  "",
  "_Spirit_.",
  "            Son of the saved!",
  "      When thou and thine have braved",
  "        The wide and warring element;",
  "    When the great barrier of the deep is rent,",
  "  Shall thou and thine be good or happy?--No!",
  "  Thy new world and new race shall be of woe--",
  "    Less goodly in their aspect, in their years",
  "          Less than the glorious giants, who",
  "        Yet walk the world in pride,",
  "  The Sons of Heaven by many a mortal bride.",
  "    Thine shall be nothing of the past, save tears!",
  "          And art thou not ashamed",
  "              Thus to survive,",
  "          And eat, and drink, and wive?",
  "  With a base heart so far subdued and tamed,",
  "  As even to hear this wide destruction named,",
  "  Without such grief and courage, as should rather",
  "    Bid thee await the world-dissolving wave,",
  "  Than seek a shelter with thy favoured father,",
  "    And build thy city o'er the drowned earth's grave?",
  "          Who would outlive their kind,",
  "          Except the base and blind?",
  "                     Mine",
  "                 Hateth thine",
  "    As of a different order in the sphere,",
  "                But not our own.",
  "  There is not one who hath not left a throne",
  "    Vacant in heaven to dwell in darkness here,",
  "  Rather than see his mates endure alone.",
  "                Go, wretch! and give",
  "  A life like thine to other wretches--live!",
  "    And when the annihilating waters roar",
  "                Above what they have done,",
  "    Envy the giant patriarchs then no more,",
  "  And scorn thy sire as the surviving one!",
  "                Thyself for being his son!",
  "",
  "           _Chorus of Spirits issuing from the cavern_.",
  "",
  "                Rejoice!",
  "        No more the human voice",
  "        Shall vex our joys in middle air",
  "              With prayer;",
  "            No more",
  "            Shall they adore;",
  "  And we, who ne'er for ages have adored",
  "          The prayer-exacting Lord,",
  "  To whom the omission of a sacrifice",
  "               Is vice;",
  "  We, we shall view the deep's salt sources poured",
  "  Until one element shall do the work",
  "        Of all in chaos; until they,",
  "        The creatures proud of their poor clay,",
  "  Shall perish, and their bleached bones shall lurk",
  "        In caves, in dens, in clefts of mountains, where",
  "  The deep shall follow to their latest lair;",
  "        Where even the brutes, in their despair,",
  "  Shall cease to prey on man and on each other,",
  "    And the striped tiger shall lie down to die",
  "  Beside the lamb, as though he were his brother;",
  "             Till all things shall be as they were,",
  "         Silent and uncreated, save the sky:",
  "                While a brief truce",
  "         Is made with Death, who shall forbear",
  "       The little remnant of the past creation,",
  "     To generate new nations for his use;",
  "       This remnant, floating o'er the undulation",
  "         Of the subsiding deluge, from its slime,",
  "     When the hot sun hath baked the reeking soil",
  "         Into a world, shall give again to Time",
  "         New beings--years, diseases, sorrow, crime--",
  "     With all companionship of hate and toil,",
  "                   Until----",
  "",
  "_Japh._ (_Interrupting them_).",
  "                    The eternal Will",
  "            Shall deign to expound this dream",
  "            Of good and evil; and redeem",
  "                Unto himself all times, all things;",
  "                And, gathered under his almighty wings,",
  "                    Abolish Hell!",
  "            And to the expiated Earth",
  "            Restore the beauty of her birth,",
  "              Her Eden in an endless paradise,",
  "            Where man no more can fall as once he fell,",
  "            And even the very demons shall do well!",
  "",
  "_Spirits_. And when shall take effect this wondrous spell?",
  "",
  "_Japh._ When the Redeemer cometh; first in pain,",
  "                    And then in glory.",
  "",
  "_Spirit_. Meantime still struggle in the mortal chain,",
  "           Till Earth wax hoary;",
  "  War with yourselves, and Hell, and Heaven, in vain,",
  "           Until the clouds look gory",
  "  With the blood reeking from each battle-plain;",
  "  New times, new climes, new arts, new men; but still,",
  "  The same old tears, old crimes, and oldest ill,",
  "  Shall be amongst your race in different forms;",
  "           But the same moral storms",
  "    Shall oversweep the future, as the waves",
  "    In a few hours the glorious giants' graves.",
  "",
  "                       _Chorus of Spirits_.",
  "",
  "               Brethren, rejoice!",
  "               Mortal, farewell!",
  "Hark! hark! already we can hear the voice",
  "      Of growing Ocean's gloomy swell;",
  "    The winds, too, plume their piercing wings;",
  "    The clouds have nearly filled their springs;",
  "The fountains of the great deep shall be broken,",
  "  And heaven set wide her windows; while mankind",
  "View, unacknowledged, each tremendous token--",
  "  Still, as they were from the beginning, blind.",
  "    We hear the sound they cannot hear,",
  "    The mustering thunders of the threatening sphere;",
  "      Yet a few hours their coming is delayed;",
  "    Their flashing banners, folded still on high,",
  "              Yet undisplayed,",
  "    Save to the Spirit's all-pervading eye.",
  "              Howl! howl! oh Earth!",
  "Thy death is nearer than thy recent birth;",
  "Tremble, ye mountains, soon to shrink below",
  "          The Ocean's overflow!",
  "The wave shall break upon your cliffs; and shells,",
  "  The little shells, of ocean's least things be",
  "Deposed where now the eagle's offspring dwells--",
  "  How shall he shriek o'er the remorseless sea!",
  "And call his nestlings up with fruitless yell,",
  "Unanswered, save by the encroaching swell;--",
  "While man shall long in vain for his broad wings,",
  "  The wings which could not save:--",
  "Where could he rest them, while the whole space brings",
  "  Nought to his eye beyond the deep, his grave?",
  "           Brethren, rejoice!",
  "  And loudly lift each superhuman voice--",
  "                 All die,",
  "  Save the slight remnant of Seth's seed--",
  "           The seed of Seth,",
  "  Exempt for future sorrow's sake from death.",
  "        But of the sons of Cain",
  "           None shall remain;",
  "      And all his goodly daughters",
  "  Must lie beneath the desolating waters;",
  "  Or, floating upward, with their long hair laid",
  "  Along the wave, the cruel heaven upbraid,",
  "           Which would not spare",
  "         Beings even in death so fair.",
  "             It is decreed,",
  "                All die!",
  "    And to the universal human cry",
  "  The universal silence shall succeed!",
  "           Fly, brethren, fly!",
  "           But still rejoice!",
  "                We fell!",
  "               They fall!",
  "                 So perish all",
  "These petty foes of Heaven who shrink from Hell!",
  "                            [_The Spirits disappear, soaring upwards_.",
  "",
  "_Japh._ (_solus_).",
  "God hath proclaimed the destiny of earth;",
  "My father's ark of safety hath announced it;",
  "The very demons shriek it from their caves;",
  "The scroll of Enoch prophesied it long",
  "In silent books, which, in their silence, say",
  "More to the mind than thunder to the ear:",
  "And yet men listened not, nor listen; but",
  "Walk darkling to their doom: which, though so nigh,",
  "Shakes them no more in their dim disbelief,",
  "Than their last cries shall shake the Almighty purpose,",
  "Or deaf obedient Ocean, which fulfils it.",
  "No sign yet hangs its banner in the air;",
  "The clouds are few, and of their wonted texture;",
  "The Sun will rise upon the Earth's last day",
  "As on the fourth day of creation, when",
  "God said unto him, \"Shine!\" and he broke forth",
  "Into the dawn, which lighted not the yet",
  "Unformed forefather of mankind--but roused",
  "Before the human orison the earlier",
  "Made and far sweeter voices of the birds,",
  "Which in the open firmament of heaven",
  "Have wings like angels, and like them salute",
  "Heaven first each day before the Adamites:",
  "Their matins now draw nigh--the east is kindling--",
  "And they will sing! and day will break! Both near,",
  "So near the awful close! For these must drop",
  "Their outworn pinions on the deep; and day,",
  "After the bright course of a few brief morrows,--",
  "Aye, day will rise; but upon what?--a chaos,",
  "Which was ere day; and which, renewed, makes Time",
  "Nothing! for, without life, what are the hours?",
  "No more to dust than is Eternity",
  "Unto Jehovah, who created both.",
  "Without him, even Eternity would be",
  "A void: without man, Time, as made for man,",
  "Dies with man, and is swallowed in that deep",
  "Which has no fountain; as his race will be",
  "Devoured by that which drowns his infant world.--",
  "What have we here? Shapes of both earth and air?",
  "No--_all_ of heaven, they are so beautiful.",
  "I cannot trace their features; but their forms,",
  "How lovelily they move along the side",
  "Of the grey mountain, scattering its mist!",
  "And after the swart savage spirits, whose",
  "Infernal immortality poured forth",
  "Their impious hymn of triumph, they shall be",
  "Welcome as Eden. It may be they come",
  "To tell me the reprieve of our young world,",
  "For which I have so often prayed.--They come!",
  "Anah! oh, God! and with her----",
  "",
  "        _Enter_ SAMIASA, AZAZIEL, ANAH, _and_ AHOLIBAMAH.",
  "",
  "_Anah_.                         Japhet!",
  "",
  "_Sam._                                 Lo!",
  "A son of Adam!",
  "",
  "_Aza._        What doth the earth-born here,",
  "While all his race are slumbering?",
  "",
  "_Japh._                           Angel! what",
  "Dost thou on earth when thou should'st be on high?",
  "",
  "_Aza._ Know'st thou not, or forget'st thou, that a part",
  "Of our great function is to guard thine earth?",
  "",
  "_Japh._ But all good angels have forsaken earth,",
  "Which is condemned; nay, even the evil fly",
  "The approaching chaos. Anah! Anah! my",
  "In vain, and long, and still to be, beloved!",
  "Why walk'st thou with this Spirit, in those hours",
  "When no good Spirit longer lights below?",
  "",
  "_Anah_. Japhet, I cannot answer thee; yet, yet",
  "Forgive me----",
  "",
  "_Japh._       May the Heaven, which soon no more",
  "Will pardon, do so! for thou art greatly tempted.",
  "",
  "_Aho._ Back to thy tents, insulting son of Noah!",
  "We know thee not.",
  "",
  "_Japh._          The hour may come when thou",
  "May'st know me better; and thy sister know",
  "Me still the same which I have ever been.",
  "",
  "_Sam._ Son of the patriarch, who hath ever been",
  "Upright before his God, whate'er thy gifts,",
  "And thy words seem of sorrow, mixed with wrath,",
  "How have Azaziel, or myself, brought on thee",
  "Wrong?",
  "",
  "_Japh._ Wrong! the greatest of all wrongs! but, thou",
  "Say'st well, though she be dust--I did not, could not,",
  "Deserve her. Farewell, Anah! I have said",
  "That word so often! but now say it, ne'er",
  "To be repeated. Angel! or whate'er",
  "Thou art, or must be soon, hast thou the power",
  "To save this beautiful--_these_ beautiful",
  "Children of Cain?",
  "",
  "_Aza._           From what?",
  "",
  "_Japh._                    And is it so,",
  "That ye too know not? Angels! angels! ye",
  "Have shared man's sin, and, it may be, now must",
  "Partake his punishment; or, at the least,",
  "My sorrow.",
  "",
  "_Sam._ Sorrow! I ne'er thought till now",
  "To hear an Adamite speak riddles to me.",
  "",
  "_Japh._ And hath not the Most High expounded them?",
  "Then ye are lost as they are lost.",
  "",
  "_Aho._                            So be it!",
  "If they love as they are loved, they will not shrink",
  "More to be mortal, than I would to dare",
  "An immortality of agonies",
  "With Samiasa!",
  "",
  "_Anah_.      Sister! sister! speak not",
  "Thus.",
  "",
  "_Aza._ Fearest thou, my Anah?",
  "",
  "_Anah_.                       Yes, for thee:",
  "I would resign the greater remnant of",
  "This little life of mine, before one hour",
  "Of thine eternity should know a pang.",
  "",
  "_Japh._ It is for _him_, then! for the Seraph thou",
  "Hast left me! That is nothing, if thou hast not",
  "Left thy God too! for unions like to these,",
  "Between a mortal and an immortal, cannot",
  "Be happy or be hallowed. We are sent",
  "Upon the earth to toil and die; and they",
  "Are made to minister on high unto",
  "The Highest: but if he can _save_ thee, soon",
  "The hour will come in which celestial aid",
  "Alone can do so.",
  "",
  "_Anah_.         Ah! he speaks of Death.",
  "",
  "_Sam._ Of death to _us_! and those who are with us!",
  "But that the man seems full of sorrow, I",
  "Could smile.",
  "",
  "_Japh._      I grieve not for myself, nor fear.",
  "I am safe, not for my own deserts, but those",
  "Of a well-doing sire, who hath been found",
  "Righteous enough to save his children. Would",
  "His power was greater of redemption! or",
  "That by exchanging my own life for hers,",
  "Who could alone have made mine happy, she,",
  "The last and loveliest of Cain's race, could share",
  "The ark which shall receive a remnant of",
  "The seed of Seth!",
  "",
  "_Aho._            And dost thou think that we,",
  "With Cain's, the eldest born of Adam's, blood",
  "Warm in our veins,--strong Cain! who was begotten",
  "In Paradise,--would mingle with Seth's children?",
  "Seth, the last offspring of old Adam's dotage?",
  "No, not to save all Earth, were Earth in peril!",
  "Our race hath always dwelt apart from thine",
  "From the beginning, and shall do so ever.",
  "",
  "_Japh._ I did not speak to thee, Aholibamah!",
  "Too much of the forefather whom thou vauntest",
  "Has come down in that haughty blood which springs",
  "From him who shed the first, and that a brother's!",
  "But thou, my Anah! let me call thee mine,",
  "Albeit thou art not; 'tis a word I cannot",
  "Part with, although I must from thee. My Anah!",
  "Thou who dost rather make me dream that Abel",
  "Had left a daughter, whose pure pious race",
  "Survived in thee, so much unlike thou art",
  "The rest of the stem Cainites, save in beauty,",
  "For all of them are fairest in their favour----",
  "",
  "_Aho._ (_interrupting him_).",
  "And would'st thou have her like our father's foe",
  "In mind, in soul? If _I_ partook thy thought,",
  "And dreamed that aught of _Abel_ was in _her_!--",
  "Get thee hence, son of Noah; thou makest strife.",
  "",
  "_Japh._ Offspring of Cain, thy father did so!",
  "",
  "_Aho._                                        But",
  "He slew not Seth: and what hast thou to do",
  "With other deeds between his God and him?",
  "",
  "_Japh._ Thou speakest well: his God hath judged him, and",
  "I had not named his deed, but that thyself",
  "Didst seem to glory in him, nor to shrink",
  "From what he had done.",
  "",
  "_Aho._                 He was our father's father;",
  "The eldest born of man, the strongest, bravest,",
  "And most enduring:--Shall I blush for him",
  "From whom we had our being? Look upon",
  "Our race; behold their stature and their beauty,",
  "Their courage, strength, and length of days----",
  "",
  "_Japh._                                        They are numbered.",
  "",
  "_Aho._ Be it so! but while yet their hours endure,",
  "I glory in my brethren and our fathers.",
  "",
  "_Japh._ My sire and race but glory in their God,",
  "Anah! and thou?----",
  "",
  "_Anah_.             Whate'er our God decrees,",
  "The God of Seth as Cain, I must obey,",
  "And will endeavour patiently to obey.",
  "But could I dare to pray in his dread hour",
  "Of universal vengeance (if such should be),",
  "It would not be to live, alone exempt",
  "Of all my house. My sister! oh, my sister!",
  "What were the world, or other worlds, or all",
  "The brightest future, without the sweet past--",
  "Thy love, my father's, all the life, and all",
  "The things which sprang up with me, like the stars,",
  "Making my dim existence radiant with",
  "Soft lights which were not mine? Aholibamah!",
  "Oh! if there should be mercy--seek it, find it:",
  "I abhor Death, because that thou must die.",
  "",
  "_Aho._ What, hath this dreamer, with his father's ark,",
  "The bugbear he hath built to scare the world,",
  "Shaken _my_ sister? Are _we_ not the loved",
  "Of Seraphs? and if we were not, must we",
  "Cling to a son of Noah for our lives?",
  "Rather than thus----But the enthusiast dreams",
  "The worst of dreams, the fantasies engendered",
  "By hopeless love and heated vigils. Who",
  "Shall shake these solid mountains, this firm earth,",
  "And bid those clouds and waters take a shape",
  "Distinct from that which we and all our sires",
  "Have seen them wear on their eternal way?",
  "Who shall do this?",
  "",
  "_Japh._           He whose one word produced them.",
  "",
  "_Aho._ Who _heard_ that word?",
  "",
  "_Japh._                      The universe, which leaped",
  "To life before it. Ah! smilest thou still in scorn?",
  "Turn to thy Seraphs: if they attest it not,",
  "They are none.",
  "",
  "_Sam._        Aholibamah, own thy God!",
  "",
  "_Aho._ I have ever hailed our Maker, Samiasa,",
  "As thine, and mine: a God of Love, not Sorrow.",
  "",
  "_Japh._ Alas! what else is Love but Sorrow? Even",
  "He who made earth in love had soon to grieve",
  "Above its first and best inhabitants.",
  "",
  "_Aho._ 'Tis said so.",
  "",
  "_Japh._              It is even so.",
  "",
  "                     _Enter_ NOAH _and_ SHEM.",
  "",
  "_Noah_.                             Japhet! What",
  "Dost thou here with these children of the wicked?",
  "Dread'st thou not to partake their coming doom?",
  "",
  "_Japh._ Father, it cannot be a sin to seek",
  "To save an earth-born being; and behold,",
  "These are not of the sinful, since they have",
  "The fellowship of angels.",
  "",
  "_Noah_.                   These are they, then,",
  "Who leave the throne of God, to take them wives",
  "From out the race of Cain; the sons of Heaven,",
  "Who seek Earth's daughters for their beauty?",
  "",
  "_Aza._                                      Patriarch!",
  "Thou hast said it.",
  "",
  "_Noah_.            Woe, woe, woe to such communion!",
  "Has not God made a barrier between Earth",
  "And Heaven, and limited each, kind to kind?",
  "",
  "_Sam._ Was not man made in high Jehovah's image?",
  "Did God not love what he had made? And what",
  "Do we but imitate and emulate",
  "His love unto created love?",
  "",
  "_Noah_.                    I am",
  "But man, and was not made to judge mankind,",
  "Far less the sons of God; but as our God",
  "Has deigned to commune with me, and reveal",
  "_His_ judgments, I reply, that the descent",
  "Of Seraphs from their everlasting seat",
  "Unto a perishable and perishing,",
  "Even on the very _eve_ of _perishing_?--world,",
  "Cannot be good.",
  "",
  "_Aza._          What! though it were to save?",
  "",
  "_Noah_. Not ye in all your glory can redeem",
  "What he who made you glorious hath condemned.",
  "Were your immortal mission safety, 'twould",
  "Be general, not for two, though beautiful;",
  "And beautiful they are, but not the less",
  "Condemned.",
  "",
  "_Japh._    Oh, father! say it not.",
  "",
  "_Noah_.                            Son! son!",
  "If that thou wouldst avoid their doom, forget",
  "That they exist: they soon shall cease to be,",
  "While thou shalt be the sire of a new world,",
  "And better.",
  "",
  "_Japh._     Let me die with _this_, and _them_!",
  "",
  "_Noah_. Thou _shouldst_ for such a thought, but shalt not: he",
  "Who _can_, redeems thee.",
  "",
  "_Sam._                    And why him and thee,",
  "More than what he, thy son, prefers to both?",
  "",
  "_Noah_. Ask him who made thee greater than myself",
  "And mine, but not less subject to his own",
  "Almightiness. And lo! his mildest and",
  "Least to be tempted messenger appears!",
  "",
  "              _Enter_ RAPHAEL _the Archangel_.",
  "",
  "_Raph._",
  "                Spirits!",
  "        Whose seat is near the throne,",
  "            What do ye here?",
  "    Is thus a Seraph's duty to be shown,",
  "           Now that the hour is near",
  "       When Earth must be alone?",
  "                Return!",
  "            Adore and burn,",
  "  In glorious homage with the elected \"Seven.\"",
  "            Your place is Heaven.",
  "",
  "_Sam._",
  "                 Raphael!",
  "  The first and fairest of the sons of God,",
  "            How long hath this been law,",
  "  That Earth by angels must be left untrod?",
  "            Earth! which oft saw",
  "  Jehovah's footsteps not disdain her sod!",
  "      The world he loved, and made",
  "      For love; and oft have we obeyed",
  "  His frequent mission with delighted pinions:",
  "      Adoring him in his least works displayed;",
  "  Watching this youngest star of his dominions;",
  "      And, as the latest birth of his great word,",
  "      Eager to keep it worthy of our Lord.",
  "            Why is thy brow severe?",
  "  And wherefore speak'st thou of destruction near?",
  "",
  "_Raph._",
  "        Had Samiasa and Azaziel been",
  "    In their true place, with the angelic choir,",
  "                Written in fire",
  "              They would have seen",
  "              Jehovah's late decree,",
  "  And not enquired their Maker's breath of me:",
  "              But ignorance must ever be",
  "                A part of sin;",
  "  And even the Spirits' knowledge shall grow less",
  "              As they wax proud within;",
  "  For Blindness is the first-born of Excess.",
  "    When all good angels left the world, ye stayed,",
  "  Stung with strange passions, and debased",
  "    By mortal feelings for a mortal maid:",
  "  But ye are pardoned thus far, and replaced",
  "  With your pure equals. Hence! away! away!",
  "                 Or stay,",
  "  And lose Eternity by that delay!",
  "",
  "_Aza._",
  "        And thou! if Earth be thus forbidden",
  "                In the decree",
  "          To us until this moment hidden,",
  "                Dost thou not err as we",
  "                  In being here?",
  "",
  "_Raph._",
  "  I came to call ye back to your fit sphere,",
  "    In the great name and at the word of God,",
  "  Dear, dearest in themselves, and scarce less dear--",
  "    That which I came to do: till now we trod",
  "  Together the eternal space; together",
  "    Let us still walk the stars. True, Earth must die!",
  "  Her race, returned into her womb, must wither,",
  "    And much which she inherits: but oh! why",
  "    Cannot this Earth be made, or be destroyed,",
  "    Without involving ever some vast void",
  "  In the immortal ranks? immortal still",
  "    In their immeasurable forfeiture.",
  "  Our brother Satan fell; his burning will",
  "    Rather than longer worship dared endure!",
  "    But ye who still are pure!",
  "  Seraphs! less mighty than that mightiest one,--",
  "    Think how he was undone!",
  "  And think if tempting man can compensate",
  "    For Heaven desired too late?",
  "          Long have I warred,",
  "          Long must I war",
  "      With him who deemed it hard",
  "  To be created, and to acknowledge him",
  "  Who midst the cherubim",
  "    Made him as suns to a dependent star,",
  "  Leaving the archangels at his right hand dim.",
  "      I loved him--beautiful he was: oh, Heaven!",
  "  Save _his_ who made, what beauty and what power",
  "  Was ever like to Satan's! Would the hour",
  "      In which he fell could ever be forgiven!",
  "  The wish is impious: but, oh ye!",
  "  Yet undestroyed, be warned! Eternity",
  "    With him, or with his God, is in your choice:",
  "  He hath not tempted you; he cannot tempt",
  "  The angels, from his further snares exempt:",
  "    But man hath listened to his voice,",
  "  And ye to woman's--beautiful she is,",
  "  The serpent's voice less subtle than her kiss.",
  "  The snake but vanquished dust; but she will draw",
  "  A second host from heaven, to break Heaven's law.",
  "                Yet, yet, oh fly!",
  "                Ye cannot die;",
  "                But they",
  "                Shall pass away,",
  "  While ye shall fill with shrieks the upper sky",
  "      For perishable clay,",
  "  Whose memory in your immortality",
  "      Shall long outlast the Sun which gave them day.",
  "  Think how your essence differeth from theirs",
  "  In all but suffering! why partake",
  "  The agony to which they must be heirs--",
  "  Born to be ploughed with years, and sown with cares,",
  "    And reaped by Death, lord of the human soil?",
  "  Even had their days been left to toil their path",
  "  Through time to dust, unshortened by God's wrath,",
  "    Still they are Evil's prey, and Sorrow's spoil.",
  "",
  "_Aho._",
  "                Let them fly!",
  "  I hear the voice which says that all must die,",
  "  Sooner than our white-bearded patriarchs died;",
  "                And that on high",
  "              An ocean is prepared,",
  "                While from below",
  "  The deep shall rise to meet Heaven's overflow--",
  "              Few shall be spared,",
  "  It seems; and, of that few, the race of Cain",
  "  Must lift their eyes to Adam's God in vain.",
  "              Sister! since it is so,",
  "            And the eternal Lord",
  "          In vain would be implored",
  "      For the remission of one hour of woe,",
  "  Let us resign even what we have adored,",
  "  And meet the wave, as we would meet the sword,",
  "      If not unmoved, yet undismayed,",
  "  And wailing less for us than those who shall",
  "  Survive in mortal or immortal thrall,",
  "      And, when the fatal waters are allayed,",
  "  Weep for the myriads who can weep no more.",
  "  Fly, Seraphs! to your own eternal shore,",
  "  Where winds nor howl, nor waters roar.",
  "        Our portion is to die,",
  "      And yours to live for ever:",
  "    But which is best, a dead Eternity,",
  "  Or living, is but known to the great Giver.",
  "        Obey him, as we shall obey;",
  "    I would not keep this life of mine in clay",
  "        An hour beyond his will;",
  "  Nor see ye lose a portion of his grace,",
  "  For all the mercy which Seth's race",
  "              Find still.",
  "                  Fly!",
  "    And as your pinions bear ye back to Heaven,",
  "  Think that my love still mounts with thee on high,",
  "                Samiasa!",
  "  And if I look up with a tearless eye,",
  "    'Tis that an angel's bride disdains to weep,--",
  "    Farewell! Now rise, inexorable deep!",
  "",
  "_Anah_.",
  "                And must we die?",
  "              And must I lose thee too,",
  "                  Azaziel?",
  "            Oh, my heart! my heart!",
  "              Thy prophecies were true!",
  "            And yet thou wert so happy too!",
  "    The blow, though not unlocked for, falls as new:",
  "                But yet depart!",
  "                    Ah! why?",
  "        Yet let me not retain thee--fly!",
  "     My pangs can be but brief; but thine would be",
  "     Eternal, if repulsed from Heaven for me.",
  "         Too much already hast thou deigned",
  "             To one of Adam's race!",
  "  Our doom is sorrow: not to us alone,",
  "    But to the Spirits who have not disdained",
  "  To love us, cometh anguish with disgrace.",
  "  The first who taught us knowledge hath been hurled",
  "    From his once archangelic throne",
  "    Into some unknown world:",
  "         And thou, Azaziel! No--",
  "         Thou shall not suffer woe",
  "  For me. Away! nor weep!",
  "    Thou canst not weep; but yet",
  "    May'st suffer more, not weeping: then forget",
  "  Her, whom the surges of the all-strangling deep",
  "  Can bring no pang like this. Fly! fly!",
  "  Being gone, 'twill be less difficult to die.",
  "",
  "_Japh._",
  "            Oh say not so!",
  "          Father! and thou, archangel, thou!",
  "    Surely celestial mercy lurks below",
  "  That pure severe serenity of brow:",
  "    Let them not meet this sea without a shore,",
  "    Save in our ark, or let me be no more!",
  "",
  "_Noah_.",
  "      Peace, child of passion, peace!",
  "  If not within thy heart, yet with thy tongue",
  "      Do God no wrong!",
  "  Live as he wills it--die, when he ordains,",
  "  A righteous death, unlike the seed of Cain's.",
  "    Cease, or be sorrowful in silence; cease",
  "  To weary Heaven's ear with thy selfish plaint.",
  "    Wouldst thou have God commit a sin for thee?",
  "            Such would it be",
  "         To alter his intent",
  "  For a mere mortal sorrow. Be a man!",
  "  And bear what Adam's race must bear, and can.",
  "",
  "_Japh._",
  "      Aye, father! but when they are gone,",
  "        And we are all alone,",
  "  Floating upon the azure desert, and",
  "  The depth beneath us hides our own dear land,",
  "    And dearer, silent friends and brethren, all",
  "    Buried in its immeasurable breast,",
  "  Who, who, our tears, our shrieks, shall then command?",
  "    Can we in Desolation's peace have rest?",
  "      Oh God! be thou a God, and spare",
  "        Yet while 'tis time!",
  "      Renew not Adam's fall:",
  "    Mankind were then but twain,",
  "  But they are numerous now as are the waves",
  "        And the tremendous rain,",
  "  Whose drops shall be less thick than would their graves,",
  "    Were graves permitted to the seed of Cain.",
  "",
  "_Noah_. Silence, vain boy! each word of thine's a crime.",
  "Angel! forgive this stripling's fond despair.",
  "",
  "_Raph._ Seraphs! these mortals speak in passion: Ye!",
  "Who are, or should be, passionless and pure,",
  "May now return with me.",
  "",
  "_Sam._                  It may not be:",
  "We have chosen, and will endure.",
  "",
  "_Raph._ Say'st thou?",
  "",
  "_Aza._               He hath said it, and I say, Amen!",
  "",
  "_Raph._",
  "            Again!",
  "      Then from this hour,",
  "      Shorn as ye are of all celestial power,",
  "  And aliens from your God,",
  "            Farewell!",
  "",
  "_Japh._             Alas! where shall they dwell?",
  "Hark, hark! Deep sounds, and deeper still,",
  "  Are howling from the mountain's bosom:",
  "There's not a breath of wind upon the hill,",
  "  Yet quivers every leaf, and drops each blossom:",
  "Earth groans as if beneath a heavy load.",
  "",
  "_Noah_. Hark, hark! the sea-birds cry!",
  "  In clouds they overspread the lurid sky,",
  "And hover round the mountain, where before",
  "  Never a white wing, wetted by the wave,",
  "      Yet dared to soar,",
  "  Even when the waters waxed too fierce to brave.",
  "      Soon it shall be their only shore,",
  "      And then, no more!",
  "",
  "_Japh._ The sun! the sun!",
  "He riseth, but his better light is gone;",
  "        And a black circle, bound",
  "        His glaring disk around,",
  "Proclaims Earth's last of summer days hath shone!",
  "      The clouds return into the hues of night,",
  "Save where their brazen-coloured edges streak",
  "The verge where brighter morns were wont to break.",
  "",
  "_Noah_. And lo! yon flash of light,",
  "The distant thunder's harbinger, appears!",
  "      It cometh! hence, away!",
  "Leave to the elements their evil prey!",
  "Hence to where our all-hallowed ark uprears",
  "          Its safe and wreckless sides!",
  "",
  "_Japh._ Oh, father, stay!",
  "Leave not my Anah to the swallowing tides!",
  "",
  "_Noah_. Must we not leave all life to such? Begone!",
  "",
  "_Japh._                 Not I.",
  "",
  "_Noah_.                 Then die",
  "                       With them!",
  "How darest thou look on that prophetic sky,",
  "And seek to save what all things now condemn,",
  "        In overwhelming unison",
  "              With just Jehovah's wrath!",
  "",
  "_Japh._ Can rage and justice join in the same path?",
  "",
  "_Noah_. Blasphemer! darest thou murmur even now!",
  "",
  "_Raph._ Patriarch, be still a father! smooth thy brow:",
  "Thy son, despite his folly, shall not sink:",
  "He knows not what he says, yet shall not drink",
  "  With sobs the salt foam of the swelling waters;",
  "But be, when passion passeth, good as thou,",
  "  Nor perish like Heaven's children with man's daughters.",
  "",
  "_Aho._ The tempest cometh; heaven and earth unite",
  "    For the annihilation of all life.",
  "    Unequal is the strife",
  "Between our strength and the Eternal Might!",
  "",
  "_Sam._ But ours is with thee; we will bear ye far",
  "  To some untroubled star,",
  "Where thou, and Anah, shalt partake our lot:",
  "  And if thou dost not weep for thy lost earth,",
  "Our forfeit Heaven shall also be forgot.",
  "",
  "_Anah_. Oh! my dear father's tents, my place of birth,",
  "And mountains, land, and woods! when ye are not,",
  "Who shall dry up my tears?",
  "",
  "_Aza._                    Thy spirit-lord.",
  "Fear not; though we are shut from Heaven,",
  "Yet much is ours, whence we can not be driven.",
  "",
  "_Raph._ Rebel! thy words are wicked, as thy deeds",
  "Shall henceforth be but weak: the flaming sword,",
  "Which chased the first-born out of Paradise,",
  "Still flashes in the angelic hands.",
  "",
  "_Aza._ It cannot slay us: threaten dust with death,",
  "And talk of weapons unto that which bleeds.",
  "What are thy swords in our immortal eyes?",
  "",
  "_Raph._ The moment cometh to approve thy strength;",
  "          And learn at length",
  "How vain to war with what thy God commands:",
  "Thy former force was in thy faith.",
  "",
  "               _Enter Mortals, flying for refuge_.",
  "",
  "                       _Chorus of Mortals_.",
  "",
  "The heavens and earth are mingling--God! oh God!",
  "What have we done? Yet spare!",
  "Hark! even the forest beasts howl forth their prayer!",
  "  The dragon crawls from out his den,",
  "  To herd, in terror, innocent with men;",
  "And the birds scream their agony through air.",
  "Yet, yet, Jehovah! yet withdraw thy rod",
  "Of wrath, and pity thine own world's despair!",
  "Hear not man only but all nature plead!",
  "",
  "_Raph._ Farewell, thou earth! ye wretched sons of clay,",
  "I cannot, must not, aid you. 'Tis decreed!",
  "                                                      [_Exit_ RAPHAEL.",
  "",
  "_Japh._ Some clouds sweep on as vultures for their prey,",
  "While others, fixed as rocks, await the word",
  "At which their wrathful vials shall be poured.",
  "No azure more shall robe the firmament,",
  "  Nor spangled stars be glorious: Death hath risen:",
  "In the Sun's place a pale and ghastly glare",
  "Hath wound itself around the dying air.",
  "",
  "_Aza._ Come, Anah! quit this chaos-founded prison,",
  "To which the elements again repair,",
  "To turn it into what it was: beneath",
  "The shelter of these wings thou shall be safe,",
  "As was the eagle's nestling once within",
  "Its mother's.--Let the coming chaos chafe",
  "With all its elements! Heed not their din!",
  "A brighter world than this, where thou shalt breathe",
  "Ethereal life, will we explore:",
  "These darkened clouds are not the only skies.",
  "",
  "                        [AZAZIEL _and_ SAMIASA _fly off, and disappear",
  "                             with_ ANAH _and_ AHOLIBAMAH.",
  "",
  "_Japh._ They are gone! They have disappeared amidst the roar",
  "Of the forsaken world; and never more,",
  "Whether they live, or die with all Earth's life,",
  "Now near its last, can aught restore",
  "Anah unto these eyes.",
  "",
  "                       _Chorus of Mortals_.",
  "",
  "Oh son of Noah! mercy on thy kind!",
  "What! wilt thou leave us all--all--_all_ behind?",
  "While safe amidst the elemental strife,",
  "Thou sitt'st within thy guarded ark?",
  "",
  "_A Mother_ (_offering her infant to_ JAPHET).",
  "      Oh, let this child embark!",
  "      I brought him forth in woe,",
  "           But thought it joy",
  "   To see him to my bosom clinging so.",
  "           Why was he born?",
  "           What hath he done--",
  "           My unweaned son--",
  "    To move Jehovah's wrath or scorn?",
  "    What is there in this milk of mine, that Death",
  "      Should stir all Heaven and Earth up to destroy",
  "               My boy,",
  "    And roll the waters o'er his placid breath?",
  "    Save him, thou seed of Seth!",
  "    Or curséd be--with him who made",
  "    Thee and thy race, for which we are betrayed!",
  "",
  "_Japh._ Peace! 'tis no hour for curses, but for prayer!",
  "",
  "                       _Chorus of Mortals_.",
  "",
  "                For prayer!!!",
  "                And where",
  "            Shall prayer ascend,",
  "When the swoln clouds unto the mountains bend",
  "                And burst,",
  "And gushing oceans every barrier rend,",
  "  Until the very deserts know no thirst?",
  "                Accursed",
  "Be he who made thee and thy sire!",
  "We deem our curses vain; we must expire;",
  "        But as we know the worst,",
  "Why should our hymns be raised, our knees be bent",
  "Before the implacable Omnipotent,",
  "Since we must fall the same?",
  "If he hath made Earth, let it be his shame,",
  "  To make a world for torture.--Lo! they come,",
  "The loathsome waters, in their rage!",
  "  And with their roar make wholesome nature dumb!",
  "  The forest's trees (coeval with the hour",
  "When Paradise upsprung,",
  "  Ere Eve gave Adam knowledge for her dower,",
  "Or Adam his first hymn of slavery sung),",
  "  So massy, vast, yet green in their old age,",
  "          Are overtopped,",
  "Their summer blossoms by the surges lopped,",
  "Which rise, and rise, and rise.",
  "Vainly we look up to the lowering skies--",
  "  They meet the seas,",
  "And shut out God from our beseeching eyes.",
  "  Fly, son of Noah, fly! and take thine ease,",
  "In thine allotted ocean-tent;",
  "And view, all floating o'er the element,",
  "The corpses of the world of thy young days:",
  "        Then to Jehovah raise",
  "        Thy song of praise!",
  "",
  "_A Mortal_.",
  "            Blesséd are the dead",
  "            Who die in the Lord!",
  "And though the waters be o'er earth outspread,",
  "            Yet, as _his_ word,",
  "            Be the decree adored!",
  "He gave me life--he taketh but",
  "  The breath which is his own:",
  "And though these eyes should be for ever shut,",
  "  Nor longer this weak voice before his throne",
  "  Be heard in supplicating tone,",
  "          Still blessed be the Lord,",
  "            For what is past,",
  "            For that which is:",
  "            For all are his,",
  "            From first to last--",
  "Time--Space--Eternity--Life--Death--",
  "  The vast known and immeasurable unknown.",
  "He made, and can unmake;",
  "  And shall I, for a little gasp of breath,",
  "Blaspheme and groan?",
  "  No; let me die, as I have lived, in faith,",
  "Nor quiver, though the Universe may quake!",
  "",
  "                       _Chorus of Mortals_.",
  "",
  "            Where shall we fly?",
  "            Not to the mountains high;",
  "For now their torrents rush, with double roar,",
  "  To meet the Ocean, which, advancing still,",
  "  Already grasps each drowning hill,",
  "Nor leaves an unsearched cave.",
  "",
  "                         _Enter a Woman_.",
  "",
  "_Woman_.",
  "      Oh, save me, save!",
  "Our valley is no more:",
  "  My father and my father's tent,",
  "My brethren and my brethren's herds,",
  "  The pleasant trees that o'er our noonday bent,",
  "And sent forth evening songs from sweetest birds,",
  "The little rivulet which freshened all",
  "      Our pastures green,",
  "      No more are to be seen.",
  "When to the mountain cliff I climbed this morn,",
  "  I turned to bless the spot,",
  "  And not a leaf appeared about to fall;--",
  "  And now they are not!--",
  "Why was I born?",
  "",
  "_Japh._",
  "              To die! in youth to die!",
  "    And happier in that doom,",
  "    Than to behold the universal tomb,",
  "              Which I",
  "    Am thus condemned to weep above in vain.",
  "    Why, when all perish, why must I remain?",
  "",
  "                [_The waters rise; Men fly in every direction; many",
  "                    are overtaken by the waves: the Chorus of",
  "                    Mortals disperses in search of safety up the",
  "                    mountains:_ JAPHET _remains upon a rock, while",
  "                    the Ark floats towards him in the distance_.",
  ""
]