module.exports = [
  "Consecrated to the Glorious Memory of His",
  "Most Serene and Renowned Highness, Oliver,",
  "Late Lord Protector of This Commonwealth, etc.",
  "(Oliver Cromwell)",
  "",
  "Written After the Celebration of his Funeral",
  "",
  "",
  "1",
  "",
  "And now 'tis time; for their officious haste,",
  "Who would before have borne him to the sky,",
  "Like eager Romans ere all rites were past",
  "Did let too soon the sacred eagle fly.",
  "",
  "2",
  "",
  "Though our best notes are treason to his fame",
  "Join'd with the loud applause of public voice;",
  "Since Heav'n, what praise we offer to his name,",
  "Hath render'd too authentic by its choice;",
  "",
  "3",
  "",
  "Though in his praise no arts can liberal be,",
  "Since they whose Muses have the highest flown",
  "Add not to his immortal memory,",
  "But do an act of friendship to their own;",
  "",
  "4",
  "",
  "Yet 'tis our duty and our interest too",
  "Such monuments as we can build to raise,",
  "Lest all the world prevent what we should do",
  "And claim a title in him by their praise.",
  "",
  "5",
  "",
  "How shall I then begin, or where conclude",
  "To draw a fame so truly circular?",
  "For in a round what order can be shew'd,",
  "Where all the parts so equal perfect are?",
  "",
  "6",
  "",
  "His grandeur he deriv'd from Heav'n alone,",
  "For he was great ere fortune made him so,",
  "And wars like mists that rise against the sun",
  "Made him but greater seem, not greater grown.",
  "",
  "7",
  "",
  "No borrow'd bays his temples did adorn,",
  "But to our crown he did fresh jewels bring.",
  "Nor was his virtue poison'd soon as born",
  "With the too early thoughts of being king.",
  "",
  "8",
  "",
  "Fortune (that easy mistress of the young",
  "But to her ancient servant coy and hard)",
  "Him at that age her favorites rank'd among",
  "When she her best-lov'd Pompey did discard.",
  "",
  "9",
  "",
  "He, private, mark'd the faults of others' sway,",
  "And set as sea-marks for himself to shun,",
  "Not like rash monarchs who their youth betray",
  "By acts their age too late would wish undone.",
  "",
  "10",
  "",
  "And yet dominion was not his design;",
  "We owe that blessing not to him but Heaven,",
  "Which to fair acts unsought rewards did join,",
  "Rewards that less to him than us were given.",
  "",
  "11",
  "",
  "Our former chiefs like sticklers of the war",
  "First sought t'inflame the parties, then to poise,",
  "The quarrel lov'd, but did the cause abhor,",
  "And did not strike to hurt but make a noise.",
  "",
  "12",
  "",
  "War, our consumption, was their gainfull trade;",
  "We inward bled whilst they prolong'd our pain;",
  "He fought to end our fighting and assay'd",
  "To stanch the blood by breathing of the vein.",
  "",
  "13",
  "",
  "Swift and resistless through the land he pass'd",
  "Like that bold Greek who did the east subdue,",
  "And made to battles such heroic haste",
  "As if on wings of victory he flew.",
  "",
  "14",
  "",
  "He fought secure of fortune as of fame,",
  "Till by new maps the island might be shown,",
  "Of conquests which he strew'd where'er he came",
  "Thick as a galaxy with stars is sown.",
  "",
  "15",
  "",
  "His palms, though under weights they did not stand,",
  "Still thriv'd; no winter could his laurels fade;",
  "Heav'n in his portrait shew'd a workman's hand",
  "And drew it perfect yet without a shade.",
  "",
  "16",
  "",
  "Peace was the prize of all his toils and care,",
  "Which war had banish'd and did now restore;",
  "Bologna's walls thus mounted in the air",
  "To seat themselves more surely than before.",
  "",
  "17",
  "",
  "Her safety rescu'd Ireland to him owes,",
  "And treacherous Scotland, to no int'rest true,",
  "Yet bless'd that fate which did his arms dispose",
  "Her land to civilize as to subdue.",
  "",
  "18",
  "",
  "Nor was he like those stars which only shine",
  "When to pale mariners they storms portend;",
  "He had his calmer influence, and his mien",
  "Did love and majesty together blend.",
  "",
  "19",
  "",
  "'Tis true, his count'nance did imprint an awe,",
  "And naturally all souls to his did bow,",
  "As wands of divination downward draw",
  "And points to beds where sov'reign gold doth grow.",
  "",
  "20",
  "",
  "When past all offerings to Feretrian Jove,",
  "He Mars depos'd and arms to gowns made yield;",
  "Successful councils did him soon approve",
  "As fit for close intrigues as open field.",
  "",
  "21",
  "",
  "To suppliant Holland he vouchsaf'd a peace,",
  "Our once bold rival in the British main,",
  "Now tamely glad her unjust claim to cease",
  "And buy our friendship with her idol, gain.",
  "",
  "22",
  "",
  "Fame of th' asserted sea through Europe blown",
  "Made France and Spain ambitious of his love;",
  "Each knew that side must conquer he would own,",
  "And for him fiercely as for empire strove.",
  "",
  "23",
  "",
  "No sooner was the Frenchman's cause embrac'd",
  "Than the light monsieur the grave don outweigh'd;",
  "His fortune turn'd the scale where it was cast,",
  "Though Indian mines were in the other laid.",
  "",
  "24",
  "",
  "When absent, yet we conquer'd in his right,",
  "For though some meaner artist's skill were shown",
  "In mingling colours, or in placing light,",
  "Yet still the fair designment was his own.",
  "",
  "25",
  "",
  "For from all tempers he could service draw;",
  "The worth of each with its alloy he knew,",
  "And as the confidant of Nature saw",
  "How she complexions did divide and brew.",
  "",
  "26",
  "",
  "Or he their single virtues did survey",
  "By intuition in his own large breast,",
  "Where all the rich ideas of them lay,",
  "That were the rule and measure to the rest.",
  "",
  "27",
  "",
  "When such heroic virtue Heav'n sets out,",
  "The stars like Commons sullenly obey,",
  "Because it drains them when it comes about,",
  "And therefore is a tax they seldom pay.",
  "",
  "28",
  "",
  "From this high spring our foreign conquests flow,",
  "Which yet more glorious triumphs do portend,",
  "Since their commencement to his arms they owe,",
  "If springs as high as fountains may ascend.",
  "",
  "29",
  "",
  "He made us freemen of the continent",
  "Whom Nature did like captives treat before,",
  "To nobler preys the English lion sent,",
  "And taught him first in Belgian walks to roar.",
  "",
  "30",
  "",
  "That old unquestion'd pirate of the land,",
  "Proud Rome, with dread the fate of Dunkirk heard,",
  "And trembling wish'd behind more Alps to stand,",
  "Although an Alexander were here guard.",
  "",
  "31",
  "",
  "By his command we boldly cross'd the line",
  "And bravely fought where southern stars arise,",
  "We trac'd the far-fetch'd gold unto the mine",
  "And that which brib'd our fathers made our prize.",
  "",
  "32",
  "",
  "Such was our prince; yet own'd a soul above",
  "The highest acts it could produce to show:",
  "Thus poor mechanic arts in public move",
  "Whilst the deep secrets beyond practice go.",
  "",
  "33",
  "",
  "Nor di'd he when his ebbing fame went less,",
  "But when fresh laurels courted him to live;",
  "He seem'd but to prevent some new success,",
  "As if above what triumphs earth could give.",
  "",
  "34",
  "",
  "His latest victories still thickest came,",
  "As near the center motion does increase,",
  "Till he, press'd down by his own weighty name,",
  "Did, like the vestal, under spoils decrease.",
  "",
  "35",
  "",
  "But first the ocean as a tribute sent",
  "That giant prince of all her watery herd,",
  "And th' isle when her protecting genius went",
  "Upon his obsequies loud sighs conferr'd.",
  "",
  "36",
  "",
  "No civil broils have since his death arose,",
  "But faction now by habit does obey,",
  "And wars have that respect for his repose,",
  "As winds for halycons when they breed at sea.",
  "",
  "37",
  "",
  "His ashes in a peaceful urn shall rest;",
  "His name a great example stands to show",
  "How strangely high endeavours may be blest,",
  "Where piety and valour jointly go.",
  ""
]