module.exports = [
  "Fee, faw, fum! bubble and squeak!",
  "Blessedest Thursday's the fat of the week.",
  "Rumble and tumble, sleek and rough,",
  "Stinking and savoury, smug and gruff,",
  "Take the church-road, for the bell's due chime",
  "Gives us the summons--'tis sermon-time!",
  "",
  "Boh, here's Barnabas! Job, that's you?",
  "Up stumps Solomon--bustling too?",
  "Shame, man! greedy beyond your years",
  "To handsel the bishop's shaving-shears?",
  "Fair play's a jewel! Leave friends in the lurch?",
  "Stand on a line ere you start for the church!",
  "",
  "Higgledy piggledy, packed we lie,",
  "Rats in a hamper, swine in a stye,",
  "Wasps in a bottle, frogs in a sieve,",
  "Worms in a carcase, fleas in a sleeve.",
  "Hist! square shoulders, settle your thumbs",
  "And buzz for the bishop--here he comes.",
  "",
  "Bow, wow, wow--a bone for the dog!",
  "I liken his Grace to an acorned hog.",
  "What, a boy at his side, with the bloom of a lass,",
  "To help and handle my lord's hour-glass!",
  "Didst ever behold so lithe a chine?",
  "His cheek hath laps like a fresh-singed swine.",
  "",
  "Aaron's asleep--shove hip to haunch,",
  "Or somebody deal him a dig in the paunch!",
  "Look at the purse with the tassel and knob",
  "And the gown with the angel and thingumbob!",
  "What's he at, quotha? reading his text!",
  "Now you've his curtsey--and what comes next?",
  "",
  "See to our converts--you doomed black dozen--",
  "No stealing away--nor cog nor cozen!",
  "You five, that were thieves, deserve it fairly;",
  "You seven, that were beggars, will live less sparely;",
  "You took your turn and dipped in the hat,",
  "Got fortune--and fortune gets you; mind that!",
  "",
  "Give your first groan--compunction's at work",
  "And soft! from a Jew you mount to a Turk.",
  "Lo, Micah,--the selfsame beard on chin",
  "He was four times already converted in!",
  "Here's a knife, clip quick--it's a sign of grace--",
  "Or he ruins us all with his hanging-face.",
  "",
  "Whom now is the bishop a-leering at?",
  "I know a point where his text falls pat.",
  "I'll tell him to-morrow, a word just now",
  "Went to my heart and made me vow",
  "I meddle no more with the worst of trades--",
  "Let somebody else pay his serenades.",
  "",
  "Groan all together now, whee-hee-hee!",
  "It's a-work, it's a-work, ah, woe is me!",
  "It began, when a herd of us, picked and placed,",
  "Were spurred through the Corso, stripped to the waist;",
  "Jew brutes, with sweat and blood well spent",
  "To usher in worthily Christian Lent.",
  "",
  "It grew, when the hangman entered our bounds,",
  "Yelled, pricked us out to his church like hounds:",
  "It got to a pitch, when the hand indeed",
  "Which gutted my purse would throttle my creed:",
  "And it overflows when, to even the odd,",
  "Men I helped to their sins help me to their God.",
  "",
  "But now, while the scapegoats leave our flock,",
  "And the rest sit silent and count the clock,",
  "Since forced to muse the appointed time",
  "On these precious facts and truths sublime,",
  "Let us fitly employ it, under our breath,",
  "In saying Ben Ezra's Song of Death.",
  "",
  "For Rabbi Ben Ezra, the night he died,",
  "Called sons and sons' sons to his side,",
  "And spoke, \"This world has been harsh and strange;",
  "Something is wrong: there needeth change.",
  "But what, or where? at the last or first?",
  "In one point only we sinned, at worst.",
  "",
  "\"The Lord will have mercy on Jacob yet,",
  "And again in his border see Israel set.",
  "When Judah beholds Jerusalem,",
  "The stranger-seed shall be joined to them:",
  "To Jacob's House shall the Gentiles cleave.",
  "So the Prophet saith and his sons believe.",
  "",
  "\"Ay, the children of the chosen race",
  "Shall carry and bring them to their place:",
  "In the land of the Lord shall lead the same",
  "Bondsmen and handmaids. Who shall blame,",
  "When the slaves enslave, the oppressed ones o'er",
  "The oppressor triumph for evermore?",
  "",
  "\"God spoke, and gave us the word to keep,",
  "Bade never fold the hands nor sleep",
  "'Mid a faithless world, at watch and ward,",
  "Till Christ at the end relieve our guard.",
  "By His servant Moses the watch was set:",
  "Though near upon cock-crow, we keep it yet.",
  "",
  "\"Thou! if thou wast He, who at mid-watch came,",
  "By the starlight, naming a dubious name!",
  "And if, too heavy with sleep--too rash",
  "With fear--O Thou, if that martyr-gash",
  "Fell on Thee coming to take thine own,",
  "And we gave the Cross, when we owed the Throne--",
  "",
  "\"Thou art the Judge. We are bruised thus.",
  "But, the Judgment over,  join sides with us!",
  "Thine too is the cause! and not more thine",
  "Than ours, is the work of these dogs and swine,",
  "Whose life laughs through and spits at their creed!",
  "Who maintain Thee in word, and defy Thee in deed!",
  "",
  "\"We withstood Christ then? Be mindful how",
  "At least we withstand Barabbas now!",
  "Was our outrage sore? But the worst we spared,",
  "To have called these--Christians, had we dared!",
  "Let defiance to them pay mistrust of Thee,",
  "And Rome make amends for Calvary!",
  "",
  "\"By the torture, prolonged from age to age,",
  "By the infamy, Israel's heritage,",
  "By the Ghetto's plague, by the garb's disgrace,",
  "By the badge of shame, by the felon's place,",
  "By the branding-tool, the bloody whip,",
  "And the summons to Christian fellowship,--",
  "",
  "\"We boast our proof that at least the Jew",
  "Would wrest Christ's name from the Devil's crew.",
  "Thy face took never so deep a shade",
  "But we fought them in it, God our aid!",
  "A trophy to bear, as we march, thy band,",
  "South, East, and on to the Pleasant Land!\"",
  ""
]