module.exports = [
  "Is this a holy thing to see",
  "  In a rich and fruitful land,--",
  "Babes reduced to misery,",
  "  Fed with cold and usurous hand?",
  "",
  "Is that trembling cry a song?",
  "  Can it be a song of joy?",
  "And so many children poor?",
  "  It is a land of poverty!",
  "",
  "And their son does never shine,",
  "  And their fields are bleak and bare,",
  "And their ways are filled with thorns:",
  "  It is eternal winter there.",
  "",
  "For where'er the sun does shine,",
  "  And where'er the rain does fall,",
  "Babes should never hunger there,",
  "  Nor poverty the mind appall.",
  "ighty wild they raise to heaven the voice of song,",
  "Or like harmonious thunderings the seats of heaven among:",
  "Beneath them sit the aged man, wise guardians of the poor.",
  "Then cherish pity, lest you drive an angel from your door.",
  ""
]