module.exports = [
  "Believers buried with Christ in baptism.",
  "",
  "Rom. 6:3,4,etc.",
  "",
  "Do we not know that solemn word,",
  "That we are buried with the Lord,",
  "Baptized into his death, and then",
  "Put off the body of our sin?",
  "",
  "Our souls receive diviner breath,",
  "Raised from corruption, guilt, and death;",
  "So from the grave did Christ arise,",
  "And lives to God above the skies.",
  "",
  "No more let sin or Satan reign",
  "Over our mortal flesh again;",
  "The various lusts we served before",
  "Shall have dominion now no more.",
  ""
]