module.exports = [
  "Prophecy and inspiration.",
  "",
  "'Twas by an order from the Lord",
  "The ancient prophets spoke his word;",
  "His Spirit did their tongues inspire,",
  "And warmed their hearts with heav'nly fire.",
  "",
  "The works and wonders which they wrought",
  "Confirmed the messages they brought;",
  "The prophet's pen succeeds his breath,",
  "To save the holy words from death.",
  "",
  "Great God, mine eyes with pleasure look",
  "On the dear volume of thy book;",
  "There my Redeemer's face I see,",
  "And read his name who died for me.",
  "",
  "Let the false raptures of the mind",
  "Be lost, and vanish in the wind;",
  "Here I can fix my hope secure;",
  "This is thy word, and must endure.",
  ""
]