module.exports = [
  "Baptism.",
  "",
  "Matt. 28:19; Acts 2:38.",
  "",
  "'Twas the commission of our Lord,",
  "\"Go teach the nations, and baptize:\"",
  "The nations have received the word",
  "Since he ascended to the skies.",
  "",
  "He sits upon th' eternal hills,",
  "With grace and pardon in his hands;",
  "And sends his cov'nant with the seals,",
  "To bless the distant British lands.",
  "",
  "\"Repent, and be baptized,\" he saith,",
  "For the remission of your sins:\"",
  "And thus our sense assists our faith,",
  "And shows us what his gospel means.",
  "",
  "Our souls he washes in his blood,",
  "As water makes the body clean;",
  "And the good Spirit from our God",
  "Descends like purifying rain.",
  "",
  "Thus we engage ourselves to thee,",
  "And seal our cov'nant with the Lord;",
  "O may the great eternal Three",
  "In heav'n our solemn vows record!",
  ""
]