module.exports = [
  "I saw thee weep--the big bright tear",
  "  Came o'er that eye of blue;",
  "And then methought it did appear",
  "  A violet dropping dew:",
  "I saw thee smile--the sapphire's blaze",
  "  Beside thee ceased to shine;",
  "It could not match the living rays",
  "  That filled that glance of thine.",
  "",
  "As clouds from yonder sun receive",
  "  A deep and mellow dye,",
  "Which scarce the shade of coming eve",
  "  Can banish from the sky,",
  "Those smiles unto the moodiest mind",
  "  Their own pure joy impart;",
  "Their sunshine leaves a glow behind",
  "  That lightens o'er the heart.",
  ""
]