module.exports = [
  "'I've a pain in my head'",
  "Said the suffering Beckford;",
  "To her Doctor so dread.",
  "'Oh! what shall I take for't?'",
  "",
  "Said this Doctor so dread",
  "Whose name it was Newnham.",
  "'For this pain in your head",
  "Ah! What can you do Ma'am?'",
  "",
  "Said Miss Beckford, 'Suppose",
  "If you think there's no risk,",
  "I take a good Dose",
  "Of calomel brisk.'--",
  "",
  "'What a praise worthy Notion.'",
  "Replied Mr. Newnham.",
  "'You shall have such a potion",
  "And so will I too Ma'am.'",
  ""
]