module.exports = [
  "If sometimes in the haunts of men",
  "  Thine image from my breast may fade,",
  "The lonely hour presents again",
  "  The semblance of thy gentle shade:",
  "And now that sad and silent hour",
  "  Thus much of thee can still restore,",
  "And sorrow unobserved may pour",
  "  The plaint she dare not speak before.",
  "",
  "Oh, pardon that in crowds awhile",
  "  I waste one thought I owe to thee,",
  "And self-condemned, appear to smile,",
  "  Unfaithful to thy memory:",
  "Nor deem that memory less dear,",
  "  That then I seem not to repine;",
  "I would not fools should overhear",
  "  One sigh that should be wholly _thine_.",
  "",
  "If not the Goblet pass unquaffed,",
  "  It is not drained to banish care;",
  "The cup must hold a deadlier draught",
  "  That brings a Lethe for despair.",
  "And could Oblivion set my soul",
  "  From all her troubled visions free,",
  "I'd dash to earth the sweetest bowl",
  "  That drowned a single thought of thee.",
  "",
  "For wert thou vanished from my mind,",
  "  Where could my vacant bosom turn?",
  "And who would then remain behind",
  "  To honour thine abandoned Urn?",
  "No, no--it is my sorrow's pride",
  "  That last dear duty to fulfil;",
  "Though all the world forget beside,",
  "  'Tis meet that I remember still.",
  "",
  "For well I know, that such had been",
  "  Thy gentle care for him, who now",
  "Unmourned shall quit this mortal scene,",
  "  Where none regarded him, but thou:",
  "And, oh! I feel in _that_ was given",
  "  A blessing never meant for me;",
  "Thou wert too like a dream of Heaven,",
  "  For earthly Love to merit thee.",
  ""
]