module.exports = [
  "Proem.",
  "",
  "1.1 Although great Queen, thou now in silence lie,",
  "1.2 Yet thy loud Herald Fame, doth to the sky",
  "1.3 Thy wondrous worth proclaim, in every clime,",
  "1.4 And so has vow'd, whilst there is world or time.",
  "1.5 So great's thy glory, and thine excellence,",
  "1.6 The sound thereof raps every human sense",
  "1.7 That men account it no impiety",
  "1.8 To say thou wert a fleshly Deity.",
  "1.9 Thousands bring off'rings (though out of date)",
  "1.10 Thy world of honours to accumulate.",
  "1.11 'Mongst hundred Hecatombs of roaring Verse,",
  "1.12 'Mine bleating stands before thy royal Hearse.",
  "1.13 Thou never didst, nor canst thou now disdain,",
  "1.14 T' accept the tribute of a loyal Brain.",
  "1.15 Thy clemency did yerst esteem as much",
  "1.16 The acclamations of the poor, as rich,",
  "1.17 Which makes me deem, my rudeness is no wrong,",
  "1.18 Though I resound thy greatness 'mongst the throng.",
  "",
  "The Poem.",
  "",
  "2.1 No Ph{oe}nix Pen, nor Spenser's Poetry,",
  "2.2 No Speed's, nor Camden's learned History;",
  "2.3 Eliza's works, wars, praise, can e're compact,",
  "2.4 The World's the Theater where she did act.",
  "2.5 No memories, nor volumes can contain,",
  "2.6 The nine Olymp'ades of her happy reign,",
  "2.7 Who was so good, so just, so learn'd, so wise,",
  "2.8 From all the Kings on earth she won the prize.",
  "2.9 Nor say I more than truly is her due.",
  "2.10 Millions will testify that this is true.",
  "2.11 She hath wip'd off th' aspersion of her Sex,",
  "2.12 That women wisdom lack to play the Rex.",
  "2.13 Spain's Monarch sa's not so, not yet his Host:",
  "2.14 She taught them better manners to their cost.",
  "2.15 The Salic Law had not in force now been,",
  "2.16 If France had ever hop'd for such a Queen.",
  "2.17 But can you Doctors now this point dispute,",
  "2.18 She's argument enough to make you mute,",
  "2.19 Since first the Sun did run, his ne'er runn'd race,",
  "2.20 And earth had twice a year, a new old face;",
  "2.21 Since time was time, and man unmanly man,",
  "2.22 Come shew me such a Ph{oe}nix if you can.",
  "2.23 Was ever people better rul'd than hers?",
  "2.24 Was ever Land more happy, freed from stirs?",
  "2.25 Did ever wealth in England so abound?",
  "2.26 Her Victories in foreign Coasts resound?",
  "2.27 Ships more invincible than Spain's, her foe",
  "2.28 She rack't, she sack'd, she sunk his Armadoe.",
  "2.29 Her stately Troops advanc'd to Lisbon's wall,",
  "2.30 Don Anthony in's right for to install.",
  "2.31 She frankly help'd Franks' (brave) distressed King,",
  "2.32 The States united now her fame do sing.",
  "2.33 She their Protectrix was, they well do know,",
  "2.34 Unto our dread Virago, what they owe.",
  "2.35 Her Nobles sacrific'd their noble blood,",
  "2.36 Nor men, nor coin she shap'd, to do them good.",
  "2.37 The rude untamed Irish she did quell,",
  "2.38 And Tiron bound, before her picture fell.",
  "2.39 Had ever Prince such Counsellors as she?",
  "2.40 Her self Minerva caus'd them so to be.",
  "2.41 Such Soldiers, and such Captains never seen,",
  "2.42 As were the subjects of our (Pallas) Queen:",
  "2.43 Her Sea-men through all straits the world did round,",
  "2.44 Terra incognitæ might know her sound.",
  "2.45 Her Drake came laded home with Spanish gold,",
  "2.46 Her Essex took Cadiz, their Herculean hold.",
  "2.47 But time would fail me, so my wit would too,",
  "2.48 To tell of half she did, or she could do.",
  "2.49 Semiramis to her is but obscure;",
  "2.50 More infamy than fame she did procure.",
  "2.51 She plac'd her glory but on Babel's walls,",
  "2.52 World's wonder for a time, but yet it falls.",
  "2.53 Fierce Tomris (Cirus' Heads-man, Sythians' Queen)",
  "2.54 Had put her Harness off, had she but seen",
  "2.55 Our Amazon i' th' Camp at Tilbury,",
  "2.56 (Judging all valour, and all Majesty)",
  "2.57 Within that Princess to have residence,",
  "2.58 And prostrate yielded to her Excellence.",
  "2.59 Dido first Foundress of proud Carthage walls",
  "2.60 (Who living consummates her Funerals),",
  "2.61 A great Eliza, but compar'd with ours,",
  "2.62 How vanisheth her glory, wealth, and powers.",
  "2.63 Proud profuse Cleopatra, whose wrong name,",
  "2.64 Instead of glory, prov'd her Country's shame:",
  "2.65 Of her what worth in Story's to be seen,",
  "2.66 But that she was a rich Ægyptian Queen.",
  "2.67 Zenobia, potent Empress of the East,",
  "2.68 And of all these without compare the best",
  "2.69 (Whom none but great Aurelius could quell)",
  "2.70 Yet for our Queen is no fit parallel:",
  "2.71 She was a Ph{oe}nix Queen, so shall she be,",
  "2.72 Her ashes not reviv'd more Ph{oe}nix she.",
  "2.73 Her personal perfections, who would tell,",
  "2.74 Must dip his Pen i' th' Heliconian Well,",
  "2.75 Which I may not, my pride doth but aspire",
  "2.76 To read what others write and then admire.",
  "2.77 Now say, have women worth, or have they none?",
  "2.78 Or had they some, but with our Queen is't gone?",
  "2.79 Nay Masculines, you have thus tax'd us long,",
  "2.80 But she, though dead, will vindicate our wrong.",
  "2.81 Let such as say our sex is void of reason",
  "2.82 Know 'tis a slander now, but once was treason.",
  "2.83 But happy England, which had such a Queen,",
  "2.84 O happy, happy, had those days still been,",
  "2.85 But happiness lies in a higher sphere.",
  "2.86 Then wonder not, Eliza moves not here.",
  "2.87 Full fraught with honour, riches, and with days,",
  "2.88 She set, she set, like Titan in his rays.",
  "2.89 No more shall rise or set such glorious Sun,",
  "2.90 Until the heaven's great revolution:",
  "2.91 If then new things, their old form must retain,",
  "2.92 Eliza shall rule Albian once again.",
  "",
  "Her Epitaph.",
  "",
  "3.1 Here sleeps T H E Queen, this is the royal bed",
  "3.2 O' th' Damask Rose, sprung from the white and red,",
  "3.3 Whose sweet perfume fills the all-filling air,",
  "3.4 This Rose is withered, once so lovely fair:",
  "3.5 On neither tree did grow such Rose before,",
  "3.6 The greater was our gain, our loss the more.",
  "",
  "Another.",
  "",
  "4.1 Here lies the pride of Queens, pattern of Kings:",
  "4.2 So blaze it fame, here's feathers for thy wings.",
  "4.3 Here lies the envy'd, yet unparallel'd Prince,",
  "4.4 Whose living virtues speak (though dead long since).",
  "4.5 If many worlds, as that fantastic framed,",
  "4.6 In every one, be her great glory famed",
  ""
]