module.exports = [
  "I lay beneath the pine trees,",
  "And looked aloft, where, through",
  "The dusky, clustered tree-tops,",
  "Gleamed rent, gay rifts of blue.",
  "",
  "I shut my eyes, and a fancy",
  "Fluttered my sense around:",
  "\"I lie here dead and buried,",
  "And this is churchyard ground.",
  "",
  "\"I am at rest for ever;",
  "Ended the stress and strife.\"",
  "Straight I fell to and sorrowed",
  "For the pitiful past life.",
  "",
  "Right wronged, and knowledge wasted;",
  "Wise labour spurned for ease;",
  "The sloth and the sin and the failure;",
  "Did I grow sad for these?",
  "",
  "They had made me sad so often;",
  "Not now they made me sad;",
  "My heart was full of sorrow",
  "For joy it never had.",
  ""
]