module.exports = [
  "Whate'er we leave to God, God does,",
  "And blesses us;",
  "The work we choose should be our own,",
  "God leaves alone.",
  "If with light head erect I sing,",
  "Though all the Muses lend their force,",
  "From my poor love of anything,",
  "The verse is weak and shallow as its source.",
  "",
  "But if with bended neck I grope",
  "Listening behind me for my wit,",
  "With faith superior to hope,",
  "More anxious to keep back than forward it;",
  "",
  "Making my soul accomplice there",
  "Unto the flame my heart hath lit,",
  "Then will the verse forever wear--",
  "Time cannot bend the line which God hath writ.",
  "",
  "Always the general show of things",
  "Floats in review before my mind,",
  "And such true love and reverence brings,",
  "That sometimes I forget that I am blind.",
  "",
  "But now there comes unsought, unseen,",
  "Some clear divine electuary,",
  "And I, who had but sensual been,",
  "Grow sensible, and as God is, am wary.",
  "",
  "I hearing get, who had but ears,",
  "And sight, who had but eyes before,",
  "I moments live, who lived but years,",
  "And truth discern, who knew but learning's lore.",
  "",
  "I hear beyond the range of sound,",
  "I see beyond the range of sight,",
  "New earths and skies and seas around,",
  "And in my day the sun doth pale his light.",
  "",
  "A clear and ancient harmony",
  "Pierces my soul through all its din,",
  "As through its utmost melody--",
  "Farther behind than they, farther within.",
  "",
  "More swift its bolt than lightning is,",
  "Its voice than thunder is more loud,",
  "It doth expand my privacies",
  "To all, and leave me single in the crowd.",
  "",
  "It speaks with such authority,",
  "With so serene and lofty tone,",
  "That idle Time runs gadding by,",
  "And leaves me with Eternity alone.",
  "",
  "Now chiefly is my natal hour,",
  "And only now my prime of life;",
  "Of manhood's strength it is the flower,",
  "'Tis peace's end and war's beginning strife.",
  "",
  "It comes in summer's broadest noon,",
  "By a grey wall or some chance place,",
  "Unseasoning Time, insulting June,",
  "And vexing day with its presuming face.",
  "",
  "Such fragrance round my couch it makes,",
  "More rich than are Arabian drugs,",
  "That my soul scents its life and wakes",
  "The body up beneath its perfumed rugs.",
  "",
  "Such is the Muse, the heavenly maid,",
  "The star that guides our mortal course,",
  "Which shows where life's true kernel's laid,",
  "Its wheat's fine flour, and its undying force.",
  "",
  "She with one breath attunes the spheres,",
  "And also my poor human heart,",
  "With one impulse propels the years",
  "Around, and gives my throbbing pulse its start.",
  "",
  "I will not doubt for evermore,",
  "Nor falter from a steadfast faith,",
  "For thought the system be turned o'er,",
  "God takes not back the word which once He saith.",
  "",
  "I will not doubt the love untold",
  "Which not my worth nor want has bought,",
  "Which wooed me young, and woos me old,",
  "And to this evening hath me brought.",
  "",
  "My memory I'll educate",
  "To know the one historic truth,",
  "Remembering to the latest date",
  "The only true and sole immortal youth.",
  "",
  "Be but thy inspiration given,",
  "No matter through what danger sought,",
  "I'll fathom hell or climb to heaven,",
  "And yet esteem that cheap which love has bought.",
  "___________________",
  "",
  "Fame cannot tempt the bard",
  "Who's famous with his God,",
  "Nor laurel him reward",
  "Who has his Maker's nod.",
  ""
]