module.exports = [
  "IT rains, and nothing stirs within the fence",
  "Anywhere through the orchard's untrodden, dense",
  "Forest of parsley. The great diamonds",
  "Of rain on the grassblades there is none to break,",
  "Or the fallen petals further down to shake.",
  "",
  "And I am nearly as happy as possible",
  "To search the wilderness in vain though well,",
  "To think of two walking, kissing there,",
  "Drenched, yet forgetting the kisses of the rain:",
  "Sad, too, to think that never, never again,",
  "",
  "Unless alone, so happy shall I walk",
  "In the rain. When I turn away, on its fine stalk",
  "Twilight has fined to naught, the parsley flower",
  "Figures, suspended still and ghostly white,",
  "The past hovering as it revisits the light.",
  ""
]