module.exports = [
  "It would have starved a Gnat --",
  "To live so small as I --",
  "And yet I was a living Child --",
  "With Food's necessity",
  "",
  "Upon me -- like a Claw --",
  "I could no more remove",
  "Than I could coax a Leech away --",
  "Or make a Dragon -- move --",
  "",
  "Not like the Gnat -- had I --",
  "The privilege to fly",
  "And seek a Dinner for myself --",
  "How mightier He -- than I --",
  "",
  "Nor like Himself -- the Art",
  "Upon the Window Pane",
  "To gad my little Being out --",
  "And not begin -- again --",
  ""
]