module.exports = [
  "The Saviour, what a noble flame",
  "Was kindled in his breast,",
  "When hasting to Jerusalem,",
  "He march'd before the rest.",
  "",
  "Good will to men, and zeal for God,",
  "His every thought engross;",
  "He longs to be baptized with blood,",
  "He pants to reach the cross!",
  "",
  "With all His suffering full in view,",
  "And woes to us unknown,",
  "Forth to the task His spirit flew,",
  "'Twas love that urged Him on.",
  "",
  "Lord, we return Thee what we can:",
  "Our hearts shall sound abroad,",
  "Salvation to the dying Man,",
  "And to the rising God!",
  "",
  "And while Thy bleeding glories here",
  "Engage our wondering eyes,",
  "We learn our lighter cross to bear,",
  "And hasten to the skies.",
  ""
]