module.exports = [
  "Oh, mighty city of New York, you are wonderful to behold--",
  "Your buildings are magnificent-- the truth be it told--",
  "They were the only thing that seemed to arrest my eye,",
  "Because many of them are thirteen storeys high;",
  "",
  "And as for Central Park, it is lovely to be seen--",
  "Especially in the summer season when its shrubberies are green",
  "And the Burns Statue is there to be seen,",
  "Surrounded by trees on the beautiful sward so green;",
  "Also Shakespeare and the immortal Sir Walter Scott,",
  "Which by Scotchmen and Englishmen will never be forgot.",
  "",
  "There are people on the Sabbath day in thousands resort--",
  "All lov'd, in conversation, and eager for sport;",
  "And some of them viewing the wild beasts there,",
  "While the joyous shouts of children does rend the air--",
  "And also beautiful black swans, I do declare.",
  "",
  "And there's beautiful boats to be seen there,",
  "And joyous shouts of children does rend the air,",
  "While the boats sail along with them o'er Lohengrin Lake,",
  "And fare is 5 cents for children, and adults ten is all they take.",
  "",
  "And there's also summer-house shades, and merry-go-rounds",
  "And with the merry laughter of the children the Park resounds,",
  "During the live-long Sabbath day",
  "Enjoying themselves at the merry-go-round play.",
  "",
  "Then there's the elevated railroads abont five storeys high,",
  "Which the inhabitants can hear night and day passing by;",
  "Of, such a mass of people there daily do throng--",
  "No less than five 100,000 daily pass along;",
  "And all along the city you can get for five cents--",
  "And, believe me, among the passengers there's few discontent.",
  "",
  "And the top of the houses are mostly all flat,",
  "And in the warm weather the people gather to chat;",
  "Besides, on the housetops they dry their clothes;",
  "And, also, many people all night on the housetops repose.",
  "",
  "And numerous ships end steamboats are there to be seen,",
  "Sailing along the East River water, which is very green--",
  "Which is certainly a most beautiful sight",
  "To see them sailing o'er the smooth water day and night.",
  "",
  "And as for Brooklyn Bridge, it's a very great height,",
  "And fills the stranger's heart with wonder at first sight;",
  "And with all its loftiness I venture to say",
  "It cannot surpass the new railway bridge of the Silvery Tay.",
  "",
  "And there's also ten thousand rumsellers there--",
  "Oh, wonderful to think of, I do declare!",
  "To accommodate the people of New York therein,",
  "And to encourage them to commit all sorts of sin.",
  "",
  "And on the Sabbath day ye will see many a man",
  "Going for beer with a big tin can,",
  "And seems proud to be seen carrying home the beer",
  "To treat his neighbours and his family dear.",
  "",
  "Then at night numbers of the people dance and sing,",
  "Making the walls of their houses to ring",
  "With their songs and dancing on Sabbath night,",
  "Which I witnessed with disgust, and fled from the sight.",
  "",
  "And with regard to New York and the sights I did see--",
  "Believe me, I never saw such sights in Dundee;",
  "And the morning I sailed from the city of New York",
  "My heart it felt as light as a cork.",
  ""
]