module.exports = [
  "For God has given us a language of monosyllables to prevent our clipping.",
  "",
  "For a toad enjoys a finer prospect than another creature to compensate his lack.",
  "",
  "Tho' toad I am the object of man's hate.",
  "Yet better am I than a reprobate. who has the worst of prospects.",
  "For there are stones, whose constituent particles are little toads.",
  "",
  "For the spiritual musick is as follows.",
  "",
  "For there is the thunder-stop, which is the voice of God direct.",
  "",
  "For the rest of the stops are by their rhimes.",
  "",
  "For the trumpet rhimes are sound bound, soar more and the like.",
  "",
  "For the Shawm rhimes are lawn fawn moon boon and the like.",
  "",
  "For the harp rhimes are sing ring string and the like.",
  "",
  "For the cymbal rhimes are bell well toll soul and the like.",
  "",
  "For the flute rhimes are tooth youth suit mute and the like.",
  "",
  "For the dulcimer rhimes are grace place beat heat and the like.",
  "",
  "For the Clarinet rhimes are clean seen and the like.",
  "",
  "For the Bassoon rhimes are pass, class and the like. God be gracious to Baumgarden.",
  "",
  "For the dulcimer are rather van fan and the like and grace place &c are of the bassoon.",
  "",
  "For beat heat, weep peep &c are of the pipe.",
  "",
  "For every word has its marrow in the English tongue for order and for delight.",
  "",
  "For the dissyllables such as able table &c are the fiddle rhimes.",
  "",
  "For all dissyllables and some trissyllables are fiddle rhimes.",
  "",
  "For the relations of words are in pairs first.",
  "",
  "For the relations of words are sometimes in oppositions.",
  "",
  "For the relations of words are according to their distances from the pair.",
  "",
  "For there be twelve cardinal virtues the gifts of the twelve sons of Jacob.",
  "",
  "For Reuben is Great. God be gracious to Lord Falmouth.",
  "",
  "For Simeon is Valiant. God be gracious to the Duke of Somerset.",
  "",
  "For Levi is Pious. God be gracious to the Bishop of London.",
  "",
  "For Judah is Good. God be gracious to Lord Granville.",
  "",
  "For Dan is Clean -- neat, dextrous, apt, active, compact. God be gracious to Draper.",
  "",
  "For Naphtali is sublime -- God be gracious to Chesterfield.",
  "",
  "For Gad is Contemplative -- God be gracious to Lord Northampton.",
  "",
  "For Ashur is Happy -- God be gracious to George Bowes.",
  "",
  "For Issachar is strong -- God be gracious to the Duke of Dorsett.",
  "",
  "For Zabulon is Constant -- God be gracious to Lord Bath.",
  "",
  "For Joseph is Pleasant -- God be gracious to Lord Bolingbroke.",
  "",
  "For Benjamin is Wise -- God be gracious to Honeywood.",
  "",
  "For all Foundation is from God depending.",
  "",
  "For the two Universities are the Eyes of England.",
  "",
  "For Cambridge is the right and the brightest.",
  "",
  "For Pembroke Hall was founded more in the Lord than any College in Cambridge.",
  "",
  "For mustard is the proper food of birds and men are bound to cultivate it for their use.",
  "",
  "For they that study the works of God are peculiarly assisted by his Spirit.",
  "",
  "For all the creatures mentiond by Pliny are somewhere or other extant to the glory of God.",
  "",
  "For Rye is food rather for fowls than men.",
  "",
  "For Rye-bread is not taken with thankfulness.",
  "",
  "For the lack of Rye may be supplied by Spelt.",
  "",
  "For languages work into one another by their bearings.",
  "",
  "For the power of some animal is predominant in every language.",
  "",
  "For the power and spirit of a CAT is in the Greek.",
  "",
  "For the sound of a cat is in the most useful preposition êáô' åõ÷çí .",
  "",
  "For the pleasantry of a cat at pranks is in the language ten thousand times over.",
  "",
  "For JACK UPON PRANCK is in the performance of gåñé together or seperate.",
  "",
  "For Clapperclaw is in the grappling of the words upon one another in all the modes of versification.",
  "",
  "For the sleekness of a Cat is in his áãëáéçöé .",
  "",
  "For the Greek is thrown from heaven and falls upon its feet.",
  "",
  "For the Greek when distracted from the line is sooner restored to rank and rallied into some form than any other.",
  "",
  "For the purring of a Cat is his ôñõæåé .",
  "",
  "For his cry is in ïõáé , which I am sorry for.",
  "",
  "For the Mouse (Mus) prevails in the Latin.",
  "",
  "For Edi-mus, bibi-mus, vivi-mus -- ore-mus.",
  "",
  "For the Mouse is a creature of great personal valour.",
  "",
  "For -- this is a true case -- Cat takes female mouse from the company of male -- male mouse will not depart, but stands threatning and daring.",
  "",
  "For this is as much as to challenge, if you will let her go, I will engage you, as prodigious a creature as you are.",
  "",
  "For the Mouse is of an hospitable disposition.",
  "",
  "For bravery and hospitality were said and done by the Romans rather than others.",
  "",
  "For two creatures the Bull and the Dog prevail in the English.",
  "",
  "For all the words ending in ble are in the creature. Invisi-ble, Incomprehensi-ble, ineffa-ble, A-ble.",
  "",
  "For the Greek and Latin are not dead languages, but taken up and accepted for the sake of him that spake them.",
  "",
  "For can is (canis) is cause and effect a dog.",
  "",
  "For the English is concise and strong. Dog and Bull again.",
  "",
  "For Newton's notion of colours is áëïãïò unphilosophical.",
  "",
  "For the colours are spiritual.",
  "",
  "For WHITE is the first and the best.",
  "",
  "For there are many intermediate colours, before you come to SILVER.",
  "",
  "For the next colour is a lively GREY.",
  "",
  "For the next colour is BLUE.",
  "",
  "For the next is GREEN of which there are ten thousand distinct sorts.",
  "",
  "For the next is YELLOW which is more excellent than red, tho Newton makes red the prime. God be gracious to John Delap.",
  "",
  "For RED is the next working round the Orange.",
  "",
  "For Red is of sundry sorts till it deepens to BLACK.",
  "",
  "For black blooms and it is PURPLE.",
  "",
  "For purple works off to BROWN which is of ten thousand acceptable shades.",
  "",
  "For the next is PALE. God be gracious to William Whitehead.",
  "",
  "For pale works about to White again.",
  "",
  "NOW that colour is spiritual appears inasmuch as the blessing of God upon all things descends in colour.",
  "",
  "For the blessing of health upon the human face is in colour.",
  "",
  "For the blessing of God upon purity is in the Virgin's blushes.",
  "",
  "For the blessing of God in colour is on him that keeps his virgin.",
  "",
  "For I saw a blush in Staindrop Church, which was of God's own colouring.",
  "",
  "For it was the benevolence of a virgin shewn to me before the whole congregation.",
  "",
  "For the blessing of God upon the grass is in shades of Green visible to a nice observer as they light upon the surface of the earth.",
  "",
  "For the blessing of God unto perfection in all bloom and fruit is by colouring.",
  "",
  "For from hence something in the spirit may be taken off by painters.",
  "",
  "For Painting is a species of idolatry, tho' not so gross as statuary.",
  "",
  "For it is not good to look with earning upon any dead work.",
  "",
  "For by so doing something is lost in the spirit and given from life to death.",
  "",
  "For BULL in the first place is the word of Almighty God.",
  "",
  "For he is a creature of infinite magnitude in the height.",
  "",
  "For there is the model of every beast of the field in the height.",
  "",
  "For they are blessed intelligences and all angels of the living God.",
  "",
  "For there are many words under Bull.",
  "",
  "For Bul the Month is under it.",
  "",
  "For Sea is under Bull.",
  "",
  "For Brook is under Bull. God be gracious to Lord Bolingbroke.",
  "",
  "For Rock is under Bull.",
  "",
  "For Bullfinch is under Bull. God be gracious to the Duke of Cleveland.",
  "",
  "For God, which always keeps his work in view has paited a Bullfinch in the heart of a stone. God be gracious to Gosling and Canterbury.",
  "",
  "For the Bluecap is under Bull.",
  "",
  "For the Humming Bird is under Bull.",
  "",
  "For Beetle is under Bull.",
  "",
  "For Toad is under bull.",
  "",
  "For Frog is under Bull, which he has a delight to look at.",
  "",
  "For the Pheasant-eyed Pink is under Bull. Blessed Jesus R4NK EL.",
  "",
  "For Bugloss is under Bull.",
  "",
  "For Bugle is under Bull.",
  "",
  "For Oxeye is under Bull.",
  "",
  "For Fire is under Bull.",
  "",
  "For I will consider my Cat Jeoffry.",
  "",
  "For he is the servant of the Living God duly and daily serving him.",
  "",
  "For at the first glance of the glory of God in the East he worships in his way.",
  "",
  "For is this done by wreathing his body seven times round with elegant quickness.",
  "",
  "For then he leaps up to catch the musk, which is the blessing of God upon his prayer.",
  "",
  "For he rolls upon prank to work it in.",
  "",
  "For having done duty and received blessing he begins to consider himself.",
  "",
  "For this he performs in ten degrees.",
  "",
  "For first he looks upon his fore-paws to see if they are clean.",
  "",
  "For secondly he kicks up behind to clear away there.",
  "",
  "For thirdly he works it upon stretch with the fore paws extended.",
  "",
  "For fourthly he sharpens his paws by wood.",
  "",
  "For fifthly he washes himself.",
  "",
  "For Sixthly he rolls upon wash.",
  "",
  "For Seventhly he fleas himself, that he may not be interrupted upon the beat.",
  "",
  "For Eighthly he rubs himself against a post.",
  "",
  "For Ninthly he looks up for his instructions.",
  "",
  "For Tenthly he goes in quest of food.",
  "",
  "For having consider'd God and himself he will consider his neighbour.",
  "",
  "For if he meets another cat he will kiss her in kindness.",
  "",
  "For when he takes his prey he plays with it to give it chance.",
  "",
  "For one mouse in seven escapes by his dallying.",
  "",
  "For when his day's work is done his business more properly begins.",
  "",
  "For he keeps the Lord's watch in the night against the adversary.",
  "",
  "For he counteracts the powers of darkness by his electrical skin and glaring eyes.",
  "",
  "For he counteracts the Devil, who is death, by brisking about the life",
  "",
  "For in his morning orisons he loves the sun and the sun loves him.",
  "",
  "For he is of the tribe of Tiger.",
  "",
  "For the Cherub Cat is a term of the Angel Tiger.",
  "",
  "For he has the subtlety and hissing of a serpent, which in goodness he suppresses.",
  "",
  "For he will not do destruction, if he is well-fed, neither will he spit without provocation.",
  "",
  "For he purrs in thankfulness, when God tells him he's a good Cat.",
  "",
  "For he is an instrument for the children to learn benevolence upon.",
  "",
  "For every house is incompleat without him and a blessing is lacking in the spirit.",
  "",
  "For the Lord commanded Moses concerning the cats at the departure of the Children of Israel from Egypt.",
  "",
  "For every family had one cat at least in the bag.",
  "",
  "For the English Cats are the best in Europe.",
  "",
  "For he is the cleanest in the use of his fore-paws of any quadrupede.",
  "",
  "For the dexterity of his defence is an instance of the love of God to him exceedingly.",
  "",
  "For he is the quickest to his mark of any creature.",
  "",
  "For he is tenacious of his point.",
  "",
  "For he is a mixture of gravity and waggery.",
  "",
  "For he knows that God is his Saviour.",
  "",
  "For there is nothing sweeter than his peace when at rest.",
  "",
  "For there is nothing brisker than his life when in motion.",
  "",
  "For he is of the Lord's poor and so indeed is he called by benevolence perpetually -- Poor Jeoffry! poor Jeoffry! the rat has bit thy throat.",
  "",
  "For I bless the name of the Lord Jesus that Jeoffry is better.",
  "",
  "For the divine spirit comes about his body to sustain it in compleat cat.",
  "",
  "For his tongue is exceeding pure so that it has in purity what it wants in musick.",
  "",
  "For he is docile and can learn certain things.",
  "",
  "For he can set up with gravity which is patience upon approbation.",
  "",
  "For he can fetch and carry, which is patience in employment.",
  "",
  "For he can jump over a stick which is patience upon proof positive.",
  "",
  "For he can spraggle upon waggle at the word of command.",
  "",
  "For he can jump from an eminence into his master's bosom.",
  "",
  "For he can catch the cork and toss it again.",
  "",
  "For he is hated by the hypocrite and miser.",
  "",
  "For the former is affraid of detection.",
  "",
  "For the latter refuses the charge.",
  "",
  "For he camels his back to bear the first notion of business.",
  "",
  "For he is good to think on, if a man would express himself neatly.",
  "",
  "For he made a great figure in Egypt for his signal services.",
  "",
  "For he killed the Icneumon-rat very pernicious by land.",
  "",
  "For his ears are so acute that they sting again.",
  "",
  "For from this proceeds the passing quickness of his attention.",
  "",
  "For by stroaking of him I have found out electricity.",
  "",
  "For I perceived God's light about him both wax and fire.",
  "",
  "For the Electrical fire is the spiritual substance, which God sends from heaven to sustain the bodies both of man and beast.",
  "",
  "For God has blessed him in the variety of his movements.",
  "",
  "For, tho he cannot fly, he is an excellent clamberer.",
  "",
  "For his motions upon the face of the earth are more than any other quadrupede.",
  "",
  "For he can tread to all the measures upon the musick.",
  "",
  "For he can swim for life.",
  "",
  "For he can creep.",
  ""
]