module.exports = [
  "Let Dew, house of Dew rejoice with Xanthenes a precious stone of an amber colour.",
  "",
  "Let Round, house of Round rejoice with Myrmecites a gern having an Emmet in it.",
  "",
  "Let New, house of New rejoice with Nasamonites a gem of a sanguine colour with black veins.",
  "",
  "Let Hook, house of Hook rejoice with Sarda a Cornelian -- blessed be the name of the Lord Jesus by hook.",
  "",
  "Let Crook, house of Crook rejoice with Ophites black spotted marble -- Blessed be the name of the Lord Jesus by crook. The Lord enable me to shift.",
  "",
  "Let Lime, house of Lime rejoice with Sandareses a kind of gem in Pliny's list.",
  "",
  "Let Linnet, house of Linnet rejoice with Tanos, which is a mean sort of Emerald.",
  "",
  "Let Hind, house of Hind rejoice with Paederos Opal -- God be gracious to Mrs Hind, that lived at Canbury.",
  "",
  "Let Tyrrel, house of Tyrrel rejoice with Sardius Lapis an Onyx of a black colour. God speed Hawke's Fleet.",
  "",
  "Let Moss, house of Moss rejoice with the Pearl-Oyster behold how God has consider'd for him that lacketh.",
  "",
  "Let Ross, house of Ross rejoice with the Great Flabber Dabber Flat Clapping Fish with hands. Vide Anson's Voyage and Psalm 98th ix.",
  "",
  "Let Fisher, house of Fisher rejoice with Sandastros kind of burning stone with gold drops in the body of it. God be gracious to Fisher of Cambridge and to all of his name and kindred.",
  "",
  "Let Fuller, house of Fuller rejoice with Perileucos a precious stone with a white thread descending from its face to the bottom.",
  "",
  "Let Thorpe, house of Thorpe rejoice with Xystios an ordinary stone of the Jasper-kind.",
  "",
  "Let Alban, house of Alban rejoice with Scorpites a precious stone in some degree of the creatures.",
  "",
  "Let Wand, house of Wand rejoice with Synochitis a gem supposed by Pliny to have certain magical effects.",
  "",
  "Let Freeman, house of Freeman rejoice with Carcinias a precious stone the colour of a sea-crab. The Lord raise the landed interest.",
  "",
  "Let Quince, house of Quince rejoice with Onychipuncta a gem of the jasper kind.",
  "",
  "Let Manly, house of Manly rejoice with the Booby a tropical bird.",
  "",
  "Let Fage, house of Fage rejoice with the Fiddlefish -- Blessed be the name of the Lord Jesus in the fish's mouth.",
  "",
  "Let Benning, house of Benning rejoice with the Sea-Egg. Lord have mercy on the soul of Benning's wife.",
  "",
  "Let Singleton, house of Singleton rejoice with the Hog-Plumb. Lord have mercy on the soul of Lord Vane.",
  "",
  "Let Thickness, house of Thickness rejoice with The Papah a fruit found at Chequetan.",
  "",
  "Let Heartly, house of Heartly rejoice with the Drummer-Fish. God be gracious to Heartly of Christ, to Marsh, Hingeston and Bill.",
  "",
  "Let Sizer, house of Sizer rejoice with Trichros a precious stone black at bottom, white atop and blood-red in the middle.",
  "",
  "Let Chetwind, house of Chetwind rejoice with Hammocrysos, a gem with gold sands on it.",
  "",
  "Let Branch, house of Branch rejoice with Hæmatites -- Blessed be the name of the Lord Jesus THE BRANCH.",
  "",
  "Let Dongworth, house of Dongworth rejoice with Rhymay the Bread-fruit. God be gracious to the immortal soul of Richard Dongworth.",
  "",
  "Let Randall, house of Randall rejoice with Guavoes. God give Randall success.",
  "",
  "Let Osborne, house of Osborne rejoice with Lithizontes a sort of carbuncle. God be gracious to the Duke of Leeds and his family.",
  "",
  "Let Oldcastle, house of Oldcastle rejoice with Leucopthalmos. God put it in heart of king to repair and beautify Dover Castle.",
  "",
  "Let Beeson, house of Beeson rejoice with Pyropus, carbuncle opal. God be gracious to Masters of Yoke's Place.",
  "",
  "Let Salmon, house of Salmon rejoice with Sapinos a kind of Amethyst.",
  "",
  "Let Crutenden, house of Crutenden rejoice with Veneris Gemma a kind of amethyst.",
  "",
  "Let Bridges, house of Bridges rejoice with Jasponyx, which is the Jasper-Onyx.",
  "",
  "Let Lane, house of Lane rejoice with Myrmecias a precious stone with little knots in it.",
  "",
  "Let Cope, house of Cope rejoice with Centipedes. God give me strength to cope with all my adversaries.",
  "",
  "Let Sutton, house of Sutton rejoice with Cholos a gem of the Emerald kind.",
  "",
  "Let Pelham, house of Pelham rejoice with Callimus in Taphiusio one stone in the body of another. God bless the Duke of Newcastle.",
  "",
  "Let Holies, house of Holies rejoice with Pyriasis a black stone that burns by friction. The Lord kindle amongst Englishmen a sense of their name.",
  "",
  "Let Lister, house of Lister rejoice with Craterites a very hard stone. The Lord hear my prayer even as I attend unto his commandments.",
  "",
  "Let Ash, house of Ash rejoice with Callaica a green gem. God be gracious to Miss Leroche my fellow traveler from Calais.",
  "",
  "Let Baily, house of Baily rejoice with Catopyrites of Cappadocia. God be gracious to the immortal soul of Lewes Baily author of the Practice of Piety.",
  "",
  "Let Glover, house of Glover rejoice with Capnites a kind of Jasper -- blessed be the memory of Glover the martyr.",
  "",
  "Let Egerton, house of Egerton rejoice with Sphragis green but not pellucid.",
  "",
  "Let Reading, house of Reading rejoice with Synodontites found in the fish Synodontes. 27th July N.S. 1762 Lord Jesus have mercy on my soul.",
  "",
  "Let Bolton, house of Bolton rejoice with Polygrammos, a kind of Jasper with white streaks.",
  "",
  "Let Paulet, house of Paulet rejoice with Chalcites, a precious stone of the colour of Brass.",
  "",
  "Let Stapleton, house of Stapleton rejoice with Scythis a precious stone -- the Lord rebuild the old houses of England.",
  "",
  "Let Newdigate, house of Newdigate rejoice with Sandaserion a stone in India like Green Oil.",
  "",
  "Let Knightly, house of Knightly rejoice with Zoronysios a gem supposed by the ancients to have magical effects. Star -- word -- herb -- gem.",
  "",
  "Let Fellows, house of Fellows rejoice with Syrites a gem found in a Wolf's bladder.",
  "",
  "Let Ascham, house of Ascham rejoice with Thyitis a precious stone remarkably hard. God be gracious to Bennet.",
  "",
  "Let Mowbray, house of Mowbray rejoice with The Black and Blue Creeper a beautiful small bird of Brazil.",
  "",
  "Let Aldrich, house of Aldrich rejoice with the Trincalo or Tricolor, a leaf without a flower or the flower of a leaf.",
  "",
  "Let Culmer, house of Culmer rejoice with Phloginos a gem of a fire-colour.",
  "",
  "Let Catesby, house of Catesby rejoice with Cerites a precious stone like wax.",
  "",
  "Let Atterbury, house of Atterbury rejoice with Eurotias a black stone with the appearance of mould on it.",
  "",
  "Let Hoare, house of Hoare rejoice with Crysopis a precious stone of a gold-colour. God be gracious to John Rust.",
  "",
  "Let Fane, house of Fane rejoice with Chalcedonius Lapis a sort of onyx called a Chalcedony.",
  "",
  "Let Lorman, house of Lorman rejoice with Cheramites, a sort of precious stone.",
  "",
  "Let Flexney, house of Flexney rejoice with Triopthalmos -- God be gracious to Churchill, Loyd and especially to Sheels.",
  "",
  "Let Gavel, house of Gavel rejoice with Phlogites a precious stone of a various flame-colour.",
  "",
  "Let Hederick, house of Hederick rejoice with Pyritis a precious stone which held in the hand will burn it; this is fixed fire.",
  "",
  "Let Pleasant, house of Pleasant rejoice with The Carrier Fish -- God be gracious to Dame Fysh.",
  "",
  "Let Tayler, house of Tayler rejoice with the Flying Mole -- God keep him from the poor man's garden. God be gracious to William Tayler Sen and Junr.",
  "",
  "Let Grieve, house of Grieve rejoice with Orites a precious stone perfectly round. Blessed be the name of the Man of Melancholy, for Jacob Grieve.",
  "",
  "Let Bowes, house of Bowes rejoice with the Dog Fly. Lord have mercy upon me and support me in all my plagues and temptations.",
  "",
  "Let Alberton, house of Alberton rejoice with Paneros a precious stone good against barrenness.",
  "",
  "Let Morgan, house of Morgan rejoice with Prasius Lapis of a Leek-green colour.",
  "",
  "Let Powell, house of Powell rejoice with Synochitis a precious stone abused by the ancient sorcerers.",
  "",
  "Let Howell, house of Howell rejoice with Ostracias a gem like an oyster.",
  "",
  "Let Close, house of Close rejoice with Chalcophonos a gem sounding like brass. O all ye gems of the mine bless ye the Lord, praise him and magnify him for ever.",
  "",
  "Let Johnson, house of Johnson rejoice with Omphalocarpa a kind of bur. God be gracious to Samuel Johnson.",
  "",
  "Let Hopgood, house of Hopgood rejoice with Nepenthes an herb which infused in wine drives away sadness -- very likely.",
  "",
  "Let Hopwood, house of Hopwood rejoice with Aspalathus the Rose of Jerusalem.",
  "",
  "Let Benson, house of Benson rejoice with Sea-Ragwort or Powder'd Bean. Lord have mercy on the soul of Dr Benson Bsp. of Gloucester.",
  "",
  "Let Marvel, house of Marvel rejoice with Brya a little shrub like birch.",
  "",
  "Let Hull, house of Hull rejoice with Subis a bird called the Spight which breaks the Eagle's eggs.",
  "",
  "Let Mason, house of Mason rejoice with Suberies the Capitol Cork Tree. Lord be merciful to William Mason.",
  "",
  "Let Fountain, house of Fountain rejoice with Syriacus Rephanus a sweet kind of Radish.",
  "",
  "Let Scroop, house of Scroop rejoice with Fig-Wine -- Palmi primarium vinum. Not so -- Palmi-primum is the word.",
  "",
  "Let Hollingstead, house of Hollingstead rejoice with Sissitietaeris herb of good fellowship. Praise the name of the Lord September 1762.",
  "",
  "Let Moyle, house of Moyle rejoice with Phlox a flame-colour'd flower without smell, tentanda via est. Via, veritas, vita sunt Christus.",
  "",
  "Let Mount, house of Mount rejoice with Anthera a flowering herb. The Lord lift me up.",
  "",
  "Let Dowers, house of Dowers rejoice with The American Nonpareil a beautiful small-bird.",
  "",
  "Let Cudworth, house of Cudworth rejoice with the Indian Jaca Tree, which bears large clusters of fruit like apples.",
  "",
  "Let Cuthbert, house of Cuthbert rejoice with Phyllandrian a good herb growing in marshes -- Lord have mercy on the soul of Cornelius Harrison.",
  "",
  "Let Chillingworth, house of Chillingworth rejoice with Polygonoides an herb with leaves like laurel long and thick good against serpents.",
  "",
  "Let Conworth, house of Conworth rejoice with Nenuphar a kind of Water Lily.",
  "",
  "Let Ransom, house of Ransom rejoice with Isidos Plocamos a sea shrub of the Coral kind, or rather like Coral.",
  "",
  "Let Ponder, house of Ponder rejoice with Polion an herb, whose leaves are white in the morning, purple at noon, and blue in the evening.",
  "",
  "Let Woodward, house of Woodward rejoice with Nerium the Rose-Laurel -- God make the professorship of fossils in Cambridge a useful thing.",
  "",
  "Let Spincks, house of Spinks rejoice with Struthiomela a little sort of Quinces -- The Lord Jesus pray for me.",
  "",
  "Let Peacock, house of Peacock rejoice with Engalacton an herb good to breed milk.",
  "",
  "Let Nason, house of Nason rejoice with Errhinum a medicine to clear the nose.",
  "",
  "Let Bold, house of Bold rejoice with the Hop-Hornbeam. God send me a neighbour this September.",
  "",
  "Let Spriggings, house of Spriggings rejoice with Eon the Tree of which Argo was built.",
  "",
  "Let Bear, house of Bear rejoice with Gelotophyllis an herb which drank in wine and myrrh causes excess of laughter.",
  "",
  "Let Sloper, house of Sloper rejoice with Gelotophye another laughing plant.",
  "",
  "Let Tollfree, house of Tollfree rejoice with Fern of Trees -- Lord stave off evil this day.",
  "",
  "Let Clare, house of Clare rejoice with Galeotes a kind of Lizard at enmity with serpents. Lord receive the soul of Dr Wilcox Master of Clare Hall.",
  "",
  "Let Wilmot, house of Wilmot rejoice with Epipetros an herb coming up spontaneous (of the seed of the earth) but never flowers.",
  "",
  "Let Anstey, house of Anstey rejoice with Eumeces a kind of balm. Lord have mercy on Christopher Anstey and his kinswoman.",
  "",
  "Let Ruston, house of Ruston rejoice with Fulviana Herba, ab inventore good to provoke urine. Lord have mercy upon Roger Pratt and his family.",
  "",
  "Let Atwood, house of Atwood rejoice with Rhodora with leaves like a nettle and flower like a rose. God bless all benefactors of Pembroke Hall.",
  "",
  "Let Shield, house of Shield rejoice with Reseda herb dissolving swelling, and imposthumes.",
  "",
  "Let Atkins, house of Atkins rejoice with Salicastrum Wild Wine upon willows and osiers.",
  "",
  "Let Pearson, house of Pearson rejoice with the American Aloe. I pray for the soul of Frances Burton.",
  "",
  "Let Hough, house of Hough rejoice with Pegasus The Flying Horse there be millions of them in the air. God bless the memories of Bsp. Hough and of Peter.",
  "",
  "Let Evelyn, house of Evelyn rejoice with Phu a Plinian shrub sweet-scented. I pray God for trees enough in the posterities.",
  "",
  "Let Wing, house of Wing rejoice with Phlomos a sort of Rush. I give the glory to God, thro Christ, for taking the Havannah. Septr 30th 1762.",
  "",
  "Let Chace, house of Chace rejoice with Papyrus. God be gracious to Sr Richard and family.",
  "",
  "Let Pulteney, house of Pulteney rejoice with Tragion a shrub like Juniper.",
  "",
  "Let Abdy, house of Abdy rejoice with Ecbolia a medicine to fetch a dead child out of the womb. God give me to bless for Gulstone and Halford.",
  "",
  "Let Hoadley, house of Hoadley rejoice with Dryos Hyphear which is the Oak-Missletoe.",
  "",
  "Let Free, house of Free rejoice with Thya a kind of Wild Cypress.",
  "",
  "Let Pink, house of Pink rejoice with Trigonum herb used in garlands -- the Lord succeed my pink borders.",
  "",
  "Let Somner, house of Somner rejoice with the Blue Daisie -- God be gracious to my neighbour and his family this day, 7th Octr 1762.",
  "",
  "Let Race, house of Race rejoice with Osiritis Dogshead. God be praised for the eighth of October 1762.",
  "",
  "Let Trowell, house of Trowell rejoice with Teuchites kind of sweet rush.",
  "",
  "Let Tilson, house of Tilson rejoice with Teramnos a kind of weed. Lord have mercy on the soul of Tilson, Fellow of Pembroke Hall.",
  "",
  "Let Loom, house of Loom rejoice with Colocasia, an Egyptian Bean of whose leaves they made cups and pots.",
  "",
  "Let Knock, house of Knock rejoice with Condurdon which bears red flowers in July and worn about the neck is good for scrophulous cases.",
  "",
  "Let Case, house of Case rejoice with Coctanum a Syrian Fig. The Lord cure my cough.",
  "",
  "Let Tomlyn, house of Tomlyn rejoice with Tetralyx a kind of herb.",
  "",
  "Let Bason, house of Bason rejoice with Thelypteris which is Sea-Fern.",
  "",
  "Let Joslyn, house of Joslyn rejoice with Cotonea a Venetian herb.",
  "",
  "Let Mace, house of Mace rejoice with Adipsos a kind of Green Palm with the smell of a quince.",
  "",
  "Let Potts, house of Potts rejoice with Ulex an herb like rosemary with a quality of attracting gold.",
  "",
  "Let Bedingfield, house of Bedingfield rejoice with Zygia, which is a kind of maple.",
  "",
  "Let Tough, house of Tough rejoice with Accipitrina. N.B. The hawk beat the raven St Luke's day 1762.",
  "",
  "Let Balsam, house of Balsam rejoice with Chenomycon an herb the sight of which terrifies a goose. Lord have mercy on William Hunter his family.",
  "",
  "Let Graves, house of Graves rejoice with Cinnaris the Stag's antidote -- the persecuted Christian is as the hunted stag.",
  "",
  "Let Tombs, house of Tombs rejoice with Acesis Water Sage -- God be gracious to Christopher Charles Tombs.",
  "",
  "Let Addy, house of Addy rejoice with Crysippea a kind of herb so called from the discoverer.",
  "",
  "Let Jump, house of Jump rejoice with Zoster a Sea-Shrub. Blessed be the name of Christ for the Anniversary of the Battle of Agincourt 1762.",
  "",
  "Let Bracegirdle, house of Bracegirdle rejoice with Xiris a kind of herb with sharp leaves.",
  "",
  "Let Girdlestone, house of Girdlestone rejoice with Crysocarpum a kind of Ivy.",
  "",
  "Let Homer, house of Homer rejoice with Cinnabar which makes a red colour.",
  "",
  "Let Lenox, house of Lenox rejoice with Achnas the Wild Pear Tree. God be gracious to the Duke of Richmond.",
  "",
  "Let Altham, house of Altham rejoice with the Everlasting Apple-Tree.",
  "",
  "Let Travell, house of Travell rejoice with Ciborium The Egyptian Bean.",
  "",
  "Let Tyers, house of Tyers rejoice with Ægilops a kind of bulbous root. God give good will to Jonathan Tyers and his family this day. All Saints. N.S. 1762.",
  "",
  "Let Clever, house of Clever rejoice with Calathiana a sort of Autumnal flower.",
  "",
  "Let Bones, house of Bones rejoice with The Red-Crested Black and Blue Bird of Surinam.",
  "",
  "Let Pownall, house of Pownall rejoice with the Murrion a creature of the Beaver kind.",
  "",
  "Let Fig, house of Fig rejoice with Fleawort. The Lord magnify the idea of Smart singing hymns on this day in the eyes of the whole University of Cambridge. Novr 5th 1762. N.S.",
  "",
  "Let Codrington, house of Codrington rejoice with Thelyphonon an herb whose root kills scorpions.",
  "",
  "Let Butler, house of Butler rejoice with Theombrotios a Persian herb. God be gracious to the immortal Soul of the Duke of Ormond.",
  "",
  "Let Bodley, house of Bodley rejoice with Tetragnathius a creature of the Spider kind.",
  "",
  "Let Acton, house of Acton rejoice with Theangelis an herb used by the Ancients for magical purposes.",
  "",
  "Let Peckwater, house of Peckwater rejoice with Tettigonia a small kind of Grashopper.",
  "",
  "Let Sheldon, house of Sheldon rejoice with Teucrion an herb like Germander.",
  "",
  "Let Breckock, house of Brecknock rejoice with Thalassegle an herb. God be merciful to Timothy Brecknock.",
  "",
  "Let Plank, house of Plank rejoice with the Sea Purslain -- God be gracious to Thomas Rosoman and family.",
  "",
  "Let Goosetree, house of Goosetree rejoice with Hippophaes a kind of teazle used in the dressing of cloth. God exalt the Soul of Captain Goosetree.",
  "",
  "Let Baimbridge, house of Baimbridge rejoice with Hippophæstum of the same kind. Horses shou'd be dock'd in winter. -- Bambridge praise the name of the Lord.",
  "",
  "Let Metcalf, house of Metcalf rejoice with Holcus Wall-Barley -- God give grace to my adversaries to ask council of Abel.",
  "",
  "Let Graner, house of Graner rejoice with Hircules Bastard Nard. The Lord English Granier and his family.",
  "",
  "Let Cape, house of Cape rejoice with Orgament an herb.",
  "",
  "Let Oram, house of Oram rejoice with Halus an herb like unto Orgament.",
  "",
  "Let Sykes, house of Skyes rejoice with Hadrobolum a kind of sweet gum.",
  "",
  "Let Plumer, house of Plumer rejoice with Hastula Regia an herb resembling a spear.",
  "",
  "Let Digby, house of Digby rejoice with Glycryhiza Sweetroot. God be gracious to Sr Digby Legard his Son and family.",
  "",
  "Let Otway, house of Otway rejoice with Hippice an herb which being held in an horse's mouth keeps him from hunger.",
  "",
  "Let Cecil, house of Cecil rejoice with Gnaphalium an herb bleached by nature white and soft for the purpose of flax. God bless Lord Salisbury.",
  "",
  "Let Rogers, house of Rogers rejoice with Hypelates a kind of Laurel -- God be gracious to Rogers and Spilsbury with their families.",
  "",
  "Let Cambden, house of Cambden rejoice with Glischromargos a kind of white marl.",
  "",
  "Let Conduit, house of Conduit rejoice with Greecula a kind of Rose. God be gracious to the immortal soul of Sr Isaac Newton.",
  "",
  "Let Hands, house of Hands rejoice with Hadrosphserum kind of Spikenard with broad leaves.",
  "",
  "Let Snipe, house of Snipe rejoice with Hæmotimon a kind of red glass. Blessed be the name of Jesus for the 29th of Novr.",
  "",
  "Let Aylesworth, house of Aylesworth rejoice with Glinon which is a kind of Maple.",
  "",
  "Let Aisley, house of Aisley rejoice with Halicastrum which is a kind of bread corn.",
  "",
  "Let Ready, house of Ready rejoice with Junco The Reed Sparrow. Blessed be the name of Christ Jesus Voice and Instrument.",
  "",
  "Let Bland, house of Bland rejoice with Lacta a kind of Cassia. God be gracious to Bland of Durham and the Widow George.",
  "",
  "Let Abington, house of Abington rejoice with Lea a kind of Colewort praise him upon the sound of the trumpet.",
  "",
  "Let Adcock, house of Adcock rejoice with Lada a shrub, which has gummy leaves.",
  "",
  "Let Snow, house of Snow rejoice with Hysginum a plant dying Scarlet.",
  "",
  "Let Wardell, house of Wardell rejoice with Leiostreum a smooth oyster. God give grace to the black trumpeter and have mercy on the soul of Scipio.",
  "",
  "Let Herring, house of Herring rejoice with Iberica a kind of herb. Blessed be the name of the Lord Jesus for Miss Herring.",
  "",
  "Let Dolben, house of Dolben rejoice with Irio Winter Cresses, Rock Gentle or Rock Gallant.",
  "",
  "Let Oakley, house of Oakley rejoice with the Skink a little amphibious creature found upon Nile.",
  "",
  "Let Owen, house of Owen rejoice with the Shag-green a beast from which the skin so called is taken.",
  "",
  "Let Twist, house of Twist rejoice with Neottophora a little creature that carries its young upon its back.",
  "",
  "Let Constant, house of Constant rejoice with the Musk-Goat -- I bless God for two visions of Anne Hope's being in charity with me.",
  "",
  "Let Amos, house of Amos rejoice with The Avosetta a bird found at Rome.",
  "",
  "Let Humphreys, house of Humphreys rejoice with The Beardmanica a curious bird.",
  "",
  "Let Busby, house of Busby rejoice with The Ganser a bird. God prosper Westminster-School.",
  "",
  "Let Alured, house of Alured rejoice with the Book-Spider -- I refer the people of both Universitys to the Bible for their morality.",
  "",
  "Let Lidgate, house of Lidgate rejoice with The Flammant a curious large bird on the coast of Cuba. God make us amends for the restoration of the Havannah.",
  "",
  "Let Cunningham, house of Cunningham rejoice with The Bohemian Jay. I pray for Peace between the K. of Prussia and Empress Queen.",
  "",
  "Let Thornhill, house of Thornhill rejoice with The Albicore a Sea Bird. God be gracious to Hogarth his wife. Blessed be the name of the Lord Jesus at Adgecomb.",
  "",
  "Let Dawn, house of Dawn rejoice with The Frigate Bird which is found upon the coasts of India.",
  "",
  "Let Horton, house of Horton rejoice with Birdlime -- Blessed be the name of the Lord Jesus against the destruction of Small Birds.",
  "",
  "Let Arne, house of Arne rejoice with The Jay of Bengal. God be gracious to Arne his wife to Michael and Charles Burney.",
  "",
  "Let Westbrooke, house of Westbrooke rejoice with the Quail of Bengal. God be gracious to the people of Maidstone.",
  "",
  "Let Allcock, house of Allcock rejoice with The King of the Wavows a strange fowl. I pray for the whose University of Cambridge especially Jesus College this blessed day.",
  "",
  "Let Audley, house of Audley rejoice with The Green Crown Bird. The Lord help on with the hymns.",
  "",
  "Let Bloom, house of Bloom rejoice with Hecatompus a fish with an hundred feet.",
  "",
  "Let Beacon, house of Beacon rejoice with Amadavad a fine bird in the East Indies.",
  "",
  "Let Blomer, house of Blomer rejoice with Halimus a Shrub to hedge with. Lord have mercy upon poor labourers this bitter frost Deer 29 N.S. 1762.",
  "",
  "Let Merrick, house of Merrick rejoice with Lageus a kind of Grape. God all-sufficient bless and forward the Psalmist in the Lord Jesus.",
  "",
  "Let Appleby, house of Appleby rejoice with Laburnum a shrub whose blossom is disliked by bees.",
  "",
  "Let Waite, house of Waite rejoice with the Shittah-Tree -- blessed be the name of the Lord Jesus for the musicians and dancers this holiday-time.",
  "",
  "Let Stedman, house of Stedman rejoice with Jacobasa St James's Wort. God be merciful to the house of Stuart.",
  "",
  "Let Poet, house of Poet rejoice with Hedrychum a kind of ointment of a sweet smelling savour. God speed the New Year thro' Christ 1763.",
  "",
  "Let Jesse, house of Jesse rejoice with the Lawrey a kind of bird. God forward my version of the psalms thro' Jesus Christ our Lord.",
  "",
  "Let Clemison, house of Clemison rejoice with Helix a kind of Ivy. God be praised for the vision of the Redcap and packet.",
  "",
  "Let Crockatt, house of Crockatt rejoice with Emboline an Asiatic Shrub with small leaves an antidote. I pray for the soul of Crockatt the bookseller the first to put me upon a version of the Psalms.",
  "",
  "Let Oakley, house of Oakley rejoice with Haliphasus a tree with such bitter fruit that nothing but swine will touch it.",
  "",
  "Let Preacher, house of Preacher rejoice with Helvella a small sort of cabbage. God be merciful to the immortal soul of Stephen Preacher.",
  "",
  "Let Heron, house of Heron rejoice with the Tunal-Tree on which the Cochineal feeds.",
  "",
  "Let Kitcat, house of Kitcat rejoice with Copec the Pitch-Stone. Janry 8th 1763 Hallelujah.",
  "",
  "Let Gisbourne, house of Gisbourne rejoice with Isocinnamon an herb of a sweet smelling savour.",
  "",
  "Let Poor, house of Poor rejoice with Jasione a kind of Withwind -- Lord have mercy on the poor this hard weather. Jan: 10th 1763.",
  "",
  "Let Eccles, house of Eccles rejoice with Heptapleuros a kind of Plantain. I pray for a musician or musicians to set the new psalms.",
  "",
  "Let Moseley, house of Moseley rejoice with Spruce -- I bless God for Old Foundation Day at Pemb. Hall.",
  "",
  "Let Pass, house of Pass rejoice with Salt -- The Lord pass the last year's accounts in my conscience thro' the merits of Jesus Christ. New Year by Old Stile 1763.",
  "",
  "Let Forward, house of Forward rejoice with Immussulus a kind of bird -- the Lord forward my translation of the psalms this year.",
  "",
  "Let Quarme, house of Quarme rejoice with Thyosiris yellow Succory -- I pray God bless all my Subscribers.",
  "",
  "Let Larkin, house of Larkin rejoice with Long-wort or Torch-herb -- God give me good riddance of my present grievances.",
  "",
  "Let Halford, house of Halford rejoice with Siren a musical bird. God considered thou me for the baseness of those I have served very highly.",
  "",
  "Let Ayerst, house of Ayerst rejoice with the Wild Beet -- God be gracious to Smith, Cousins, Austin, Cam and Kingsley and Kinleside.",
  "",
  "Let Decker, house of Decker rejoice with Sirpe a Cyrenian plant yielding an odoriferous juice.",
  "",
  "Let Cust, house of Cust rejoice with Margaris a date like unto a pearl.",
  "",
  "Let Usher, house of Usher rejoice with Condurdon an herb with a red flower worn about the neck for the scurvy.",
  "",
  "Let Slingsby, house of Slingsby rejoice with Midas a little worm breeding in beans.",
  "",
  "Let Farmer, house of Farmer rejoice with Merois an herb growing at Meroe leaf like lettuce and good for dropsy.",
  "",
  "Let Affleck, house of Affleck rejoice with The Box-thorn. Blessed be the name of the Lord Jesus Emanuel.",
  "",
  "Let Arnold, house of Arnold rejoice with Leucographis a simple good against spitting of blood.",
  "",
  "Let Morris, house of Morris rejoice with Lepidium a Simple of the Cress kind.",
  "",
  "Let Crane, house of Crane rejoice with Libanotis an herb that smells like Frankinsense.",
  "",
  "Let Arden, house of Arden rejoice with Mew an herb with the stalk and leaves like Anise.",
  "",
  "Let Joram, house of Joram rejoice with Meliphylla Balm Gentle God be gracious to John Sherrat.",
  "",
  "Let Odwell, house of Odwell rejoice with Lappago Maiden Lips. Blessed be the name of Jesus in singularities and singular mercies.",
  "",
  "Let Odney, house of Odney rejoice with Canaria a simple called Hound's-grass.",
  ""
]