module.exports = [
  "For a Man is to be looked upon in that which he excells as on a prospect.",
  "",
  "For there be twelve cardinal virtues -- three to the East -- Greatness, Valour, Piety.",
  "",
  "For there be three to the West -- Goodness, Purity and Sublimity.",
  "",
  "For there be three to the North -- Meditation, Happiness, Strength.",
  "",
  "For there be three to the South -- Constancy, Pleasantry and Wisdom.",
  "",
  "For the Argument A PRIORI is GOD in every man's CONSCIENCE.",
  "",
  "For the Argument A POSTERIORI is God before every man's eyes.",
  "",
  "For the Four and Twenty Elders of the Revelation are Four and Twenty Eternities.",
  "",
  "For their Four and Twenty Crowns are their respective Consummations.",
  "",
  "For a CHARACTER is the votes of the Worldlings, but the seal is of Almighty GOD alone.",
  "",
  "For there is no musick in flats and sharps which are not in God's natural key.",
  "",
  "For where Accusation takes the place of encouragement a man of Genius is driven to act the vices of a fool.",
  "",
  "For the Devil can set a house on fire, when the inhabitants find combustibles.",
  "",
  "For the old account of time is the true -- Decr 28th 1759-60 -- -- --",
  "",
  "For Faith as a grain of mustard seed is to believe, as I do, that an Eternity is such in respect to the power and magnitude of Almighty God.",
  "",
  "For a DREAM is a good thing from GOD.",
  "",
  "For there is a dream from the adversary which is terror.",
  "",
  "For the phenomenon of dreaming is not of one solution, but many.",
  "",
  "For Eternity is like a grain of mustard as a growing body and improving spirit.",
  "",
  "For the malignancy of fire is oweing to the Devil's hiding of light, till it became visible darkness.",
  "",
  "For the Circle may be SQUARED by swelling and flattening.",
  "",
  "For the Life of God is in the body of man and his spirit in the Soul.",
  "",
  "For there was no rain in Paradise because of the delicate construction of the spiritual herbs and flowers.",
  "",
  "For the Planet Mercury is the WORD DISCERNMENT.",
  "",
  "For the Scotchman seeks for truth at the bottom of a well, the Englishman in the Heavn of Heavens.",
  "",
  "For the Planet Venus is the WORD PRUDENCE or providence.",
  "",
  "For GOD nevertheless is an extravagant BEING and generous unto loss.",
  "",
  "For there is no profit in the generation of man and the loss of millions is not worth God's tear.",
  "",
  "For this is the twelfth day of the MILLENNIUM of the MILLENNIUM foretold by the prophets -- give the glory to God ONE THOUSAND SEVEN HUNDRED AND SIXTY --",
  "",
  "For the Planet Mars is the word FORTITUDE.",
  "",
  "For to worship naked in the Rain is the bravest thing for the refreshing and purifying the body.",
  "",
  "For the Planet Jupiter is the WORD DISPENSATION.",
  "",
  "For Tully says to be generous you must be first just, but the voice of Christ is distribute at all events.",
  "",
  "For Kittim is the father of the Pygmies, God be gracious to Pigg his family.",
  "",
  "For the Soul is divisible and a portion of the Spirit may be cut off from one and applied to another.",
  "",
  "For NEW BREAD is the most wholesome especially if it be leaven'd with honey.",
  "",
  "For a NEW SONG also is best, if it be to the glory of God; and taken with the food like the psalms.",
  "",
  "For the Planet Saturn is the word TEMPERANCE or PATIENCE.",
  "",
  "For Jacob's Ladder are the steps of the Earth graduated hence to Paradice and thence to the throne of God.",
  "",
  "For a good wish is well but a faithful prayer is an eternal benefit.",
  "",
  "For SPICA VIRGINIS is the star that appeared to the wise men in the East and directed their way before it was yet insphered.",
  "",
  "For an IDEA is the mental vision of an object.",
  "",
  "For Lock supposes that an human creature, at a given time may be an atheist i.e. without God, by the folly of his doctrine concerning innate ideas.",
  "",
  "For it is not lawful to sell poyson in England any more than it is in Venice, the Lord restrain both the finder and receiver.",
  "",
  "For the ACCENTS are the invention of the Moabites, who learning the GREEK tongue marked the words after their own vicious pronuntiation.",
  "",
  "For the GAULS (the now-French and original Moabites) after they were subdued by Cæsar became such Grecians at Rome.",
  "",
  "For the Gaullic manuscripts fell into the hands of the inventors of printing.",
  "",
  "For all the inventions of man, which are good, are the communications of Almighty God.",
  "",
  "For all the stars have satellites, which are terms under their respective words.",
  "",
  "For tiger is a word and his satellites are Griffin, Storgis, Cat and others.",
  "",
  "For my talent is to give an Impression upon words by punching, that when the reader casts his eye upon 'em, he takes up the image from the mould which I have made.",
  "",
  "For JOB was the son of Issachar and patience is the child of strength.",
  "",
  "For the Names of the DAYS, as they now stand, are foolish and abominable.",
  "",
  "For the Days are the First, Second, Third, Fourth, Fifth, Sixth and Seventh.",
  "",
  "For the names of the months are false -- the Hebrew appellatives are of God.",
  "",
  "For the Time of the Lord's temptation was in early youth and imminent danger.",
  "",
  "For an equivocal generation is a generation and no generation.",
  "",
  "For putrifying matter nevertheless will yield up its life in diverse creatures and combinations of creatures.",
  "",
  "For a TOAD can dwell in the centre of a stone, because -- there are stones whose constituent life is of those creatures.",
  "",
  "For a Toad hath by means of his eye the most beautiful prospects of any other animal to make him amends for his distance from his Creator in Glory.",
  "",
  "For FAT is the fruit of benevolence, therefore it was the Lord's in the Mosaic sacrifices.",
  "",
  "For the very particular laws of Moses are the determinations of CASES that fell under his cognizance.",
  "",
  "For the Devil can make the shadow thicker by candlelight by reason of his pow'r over malignant fire.",
  "",
  "For the Romans clipped their words in the Augustan thro idleness and effeminacy and paid foreign actors for speaking them out.",
  "",
  "For when the weight and the pow'r are equivalent the prop is of none effect.",
  "",
  "For shaving of the beard was an invention of the people of Sodom to make men look like women.",
  "",
  "For the ends of the world are the accomplishment of great events, and the consummation of periods.",
  "",
  "For ignorance is a sin because illumination is to be obtained by prayer.",
  "",
  "For Preferment is not from the East, West or South, but from the North, where Satan has most power.",
  "",
  "For the ministers of the Devil set the hewer of wood over the head of God's free Man.",
  "",
  "For this inverting God's good order, edifice and edification, and appointing place, where the Lord has not appointed.",
  "",
  "For the Ethiopian question is already solved in that the Blacks are the children of Cain.",
  "",
  "For the phenomenon of the horizontal moon is the truth -- she appears bigger in the horizon because she actually is so.",
  "",
  "For it was said of old 'can the Ethiopian change his skin?' the Lord has answered the question by his merit and death he shall. --",
  "",
  "For the moon is magnified in the horizon by Almighty God, and so is the Sun.",
  "",
  "For she has done her day's-work and the blessing of God upon her, and she communicates with the earth.",
  "",
  "For when she rises she has been strength'ned by the Sun, who cherishes her by night.",
  "",
  "For man is born to trouble in the body, as the sparks fly upwards in the spirit.",
  "",
  "For man is between the pinchers while his soul is shaping and purifying.",
  "",
  "For the ENGLISH are the seed of Abraham and work up to him by Joab, David, and Naphtali. God be gracious to us this day. General Fast March 14th 1760.",
  "",
  "For the Romans and the English are one people the children of the brave man who died at the altar praying for his posterity, whose death was the type of our Saviour's.",
  "",
  "For the WELCH are the children of Mephibosheth and Ziba with a mixture of David in the Jones's.",
  "",
  "For the Scotch are the children of Doeg with a mixture of Cush the Benjamite, whence their innate antipathy to the English.",
  "",
  "For the IRISH are the children of Shimei and Cush with a mixture of something lower -- the Lord raise them!",
  "",
  "For the FRENCH are Moabites even the children of Lot.",
  "",
  "For the DUTCH are the children of Gog.",
  "",
  "For the Poles are the children of Magog.",
  "",
  "For the Italians are the children of Samuel and are the same as the Grecians.",
  "",
  "For the Spaniards are the children of Abishai Joab's brother, hence is the goodwill between the two nations.",
  "",
  "For the Portuguese are the children of Amman -- God be gracious to Lisbon and send good angels amongst them!",
  "",
  "For the Hottentots are the children of Gog with a Black mixture.",
  "",
  "For the Russians are the Children of Ishmael.",
  "",
  "For the Turks are the children of Esaw, which is Edom.",
  "",
  "For the Wallachians are the children of Huz. God be gracious to Elizabeth Hughes, as she was.",
  "",
  "For the Germans are the children of the Philistins even the seed of Anak.",
  "",
  "For the Prussians are the children of Goliah -- but the present, whom God bless this hour, is a Campbell of the seed of Phinees.",
  "",
  "For the Hanoverians are Hittites of the seed of Uriah. God save the king.",
  "",
  "For the Hessians are Philistines with a mixture of Judah.",
  "",
  "For the Saxons are Benjamites, men of great subtlety and Marshal Saxe was direct from Benjamin.",
  "",
  "For the Danes are of the children of Zabulon.",
  "",
  "For the Venetians are the children of Mark and Romans.",
  "",
  "For the Swiss are Philistins of a particular family. God be gracious to Jonathan Tyers his family and to all the people at Vaux Hall.",
  "",
  "For the Sardinians are of the seed of David -- The Lord forward the Reformation amongst the good seed first. --",
  "",
  "For the Mogul's people are the children of Phut.",
  "",
  "For the Old Greeks and the Italians are one people, which are blessed in the gift of Mustek by reason of the song of Hannah and the care of Samuel with regard to divine melody.",
  "",
  "For the Germans and the Dutch are the children of the Goths and Vandals who did a good in destruction books written by heathen Free-Thinkers against God.",
  "",
  "For there are Americans of the children of Toi. --",
  "",
  "For the Laplanders are the children of Gomer.",
  "",
  "For the Phenomena of the Diving Bell are solved right in the schools.",
  "",
  "For NEW BREAD is the most wholesome -- God be gracious to Baker.",
  "",
  "For the English are the children of Joab, Captain of the host of Israel, who was the greatest man in the world to GIVE and to ATCHIEVE.",
  "",
  "For TEA is a blessed plant and of excellent virtue. God give the Physicians more skill and honesty!",
  "",
  "For nutmeg is exceeding wholesome and cherishing, neither does it hurt the liver.",
  "",
  "For The Lightning before death is God's illumination in the spirit for preparation and for warning.",
  "",
  "For Lavender Cotton is exceeding good for the teeth. God be gracious to Windsmore.",
  "",
  "For the Fern is exceeding good and pleasant to rub the teeth.",
  "",
  "For a strong preparation of Mandragora is good for the gout.",
  "",
  "For the Bark was a communication from God and is sovereign.",
  "",
  "For the method of curing an ague by terror is exaction.",
  "",
  "For Exaction is the most accursed of all things, because it brought the Lord to the cross, his betrayers and murderers being such from their exaction.",
  "",
  "For an Ague is the terror of the body, when the blessing of God is withheld for a season.",
  "",
  "For benevolence is the best remedy in the first place and the bark in the second.",
  "",
  "For, when the nation is at war, it is better to abstain from the punishment of criminals especially, every act of human vengeance being a check to the grace of God.",
  "",
  "For the letter ל [Hebrew character lamed] which signifies GOD by himself is on the fibre of some leaf in every Tree.",
  "",
  "For ל is the grain of the human heart and on the network of the skin.",
  "",
  "For ל is in the veins of all stones both precious and common.",
  "",
  "For ל is upon every hair both of man and beast.",
  "",
  "For ל is in the grain of wood.",
  "",
  "For ל is in the ore of all metals.",
  "",
  "For ל is on the scales of all fish.",
  "",
  "For ל is on the petals of all flowers.",
  "",
  "For ל is upon on all shells.",
  "",
  "For ל is in the constituent particles of air.",
  "",
  "For ל is on the mite of the earth.",
  "",
  "For ל is in the water yea in every drop.",
  "",
  "For ל is in the incomprehensible ingredients of fire.",
  "",
  "For ל is in the stars the sun and in the Moon.",
  "",
  "For ל is upon the Sapphire Vault.",
  "",
  "For the doubling of flowers is the improvement of the gardners talent.",
  "",
  "For the flowers are great blessings.",
  "",
  "For the Lord made a Nosegay in the meadow with his disciples and preached upon the lily.",
  "",
  "For the angels of God took it out of his hand and carried it to the Height.",
  "",
  "For a man cannot have publick spirit, who is void of private benevolence.",
  "",
  "For there is no Height in which there are not flowers.",
  "",
  "For flowers have great virtues for all the senses.",
  "",
  "For the flower glorifies God and the root parries the adversary.",
  "",
  "For the flowers have their angels even the words of God's Creation.",
  "",
  "For the warp and woof of flowers are worked by perpetual moving spirits.",
  "",
  "For flowers are good both for the living and the dead.",
  "",
  "For there is a language of flowers.",
  "",
  "For there is a sound reasoning upon all flowers.",
  "",
  "For elegant phrases are nothing but flowers.",
  "",
  "For flowers are peculiarly the poetry of Christ.",
  "",
  "For flowers are medicinal.",
  "",
  "For flowers are musical in ocular harmony.",
  "",
  "For the right names of flowers are yet in heaven. God make gard'ners better nomenclators.",
  "",
  "For the Poorman's nosegay is an introduction to a Prince.",
  "",
  "For it were better for the SERVICE, if only select psalms were read.",
  "",
  "For the Lamentations of Jeremiah, Songs from other scriptures, and parts of Esdras might be taken to supply the quantity.",
  "",
  "For A is the beginning of learning and the door of heaven.",
  "",
  "For B is a creature busy and bustling.",
  "",
  "For C is a sense quick and penetrating.",
  "",
  "For D is depth.",
  "",
  "For E is eternity -- such is the power of the English letters taken singly.",
  "",
  "For F is faith.",
  "",
  "For G is God -- whom I pray to be gracious to Liveware my fellow prisoner.",
  "",
  "For H is not a letter, but a spirit -- Benedicatur Jesus Christus, sic spirem!",
  "",
  "For I is identity. God be gracious to Henry Hatsell.",
  "",
  "For K is king.",
  "",
  "For L is love. God in every language.",
  "",
  "For M is musick and Hebrew מ [Hebrew character mem] is the direct figure of God's harp.",
  "",
  "For N is new.",
  "",
  "For O is open.",
  "",
  "For P is power.",
  "",
  "For Q is quick.",
  "",
  "For R is right.",
  "",
  "For S is soul.",
  "",
  "For T is truth. God be gracious to Jermyn Pratt and to Harriote his Sister.",
  "",
  "For U is unity, and his right name is Uve to work it double.",
  "",
  "For W is word.",
  "",
  "For X [drawn as a backwards G and a G stuck together] is hope -- consisting of two check G -- God be gracious to Anne Hope.",
  "",
  "For Y is yea. God be gracious to Eennet and his family!",
  "",
  "For Z is zeal.",
  "",
  "For in the education of children it is necessary to watch the words, -which they pronounce with difficulty, for such are against them in their consequences.",
  "",
  "For A is awe, if pronounced full. Stand in awe and sin not.",
  "",
  "For B pronounced in the animal is bey importing authority.",
  "",
  "For C pronounced hard is ke importing to shut.",
  "",
  "For D pronounced full is day.",
  "",
  "For E is east particularly when formed little e with his eye.",
  "",
  "For F in it's secondary meaning is fair.",
  "",
  "For G in a secondary sense is good.",
  "",
  "For H is heave.",
  "",
  "For I is the organ of vision.",
  "",
  "For K is keep.",
  "",
  "For L is light, and ל [Hebrew character lamed] is the line of beauty.",
  "",
  "For M is meet.",
  "",
  "For N is nay.",
  "",
  "For O is over.",
  "",
  "For P is peace.",
  "",
  "For Q is quarter.",
  "",
  "For R is rain, or thus reign, or thus rein.",
  "",
  "For S is save.",
  "",
  "For T is take.",
  "",
  "For V is veil.",
  "",
  "For W is world.",
  "",
  "For X [drawn as a backwards G and a G stuck together] beginneth not, but connects and continues.",
  "",
  "For Y is young -- the Lord direct me in the better way of going on in the Fifth year of my jeopardy June the 17th N.S. 1760. God be gracious to Dr YOUNG.",
  "",
  "For Z is zest. God give us all a relish of our duty.",
  "",
  "For Action and Speaking are one according to God and the Ancients.",
  "",
  "For the approaches of Death are by illumination.",
  "",
  "For a man cannot have Publick Spirit, who is void of private benevolence.",
  "",
  "For the order of Alamoth is first three, second six, third eighteen, fourth fifty four, and then the whole band.",
  "",
  "For the order of Sheminith is first ten, second twenty, third thirty and then the whole band.",
  "",
  "For the first entrance into Heaven is by complement.",
  "",
  "For Flowers can see, and Pope's Carnations knew him.",
  "",
  "For the devil works upon damps and lowth and causes agues.",
  "",
  "For Ignorance is a sin, because illumination is to be had by prayer.",
  "",
  "For many a genius being lost at the plough is a false thought -- the divine providence is a better manager.",
  "",
  "For a man's idleness is the fruit of the adversary's diligence.",
  "",
  "For diligence is the gift of God, as well as other good things.",
  "",
  "For it is a good NOTHING in one's own eyes and in the eyes of fools.",
  "",
  "For æra in its primitive sense is but a weed amongst corn.",
  "",
  "For there is no knowing of times and seasons, in submitting them to God stands the Christian's Chronology.",
  "",
  "For Jacob's brown sheep wore the Golden fleece.",
  "",
  "For Shaving of the face was the invention of the Sodomites to make men look like women.",
  ""
]