module.exports = [
  "Let Ramah rejoice with Cochineal.",
  "",
  "Let Gaba rejoice with the Prickly Pear, which the Cochineal feeds on.",
  "",
  "Let Nebo rejoice with the Myrtle-Leaved-Sumach as with the Skirret Jub. 2d.",
  "",
  "Let Magbish rejoice with the Sage-Tree Phlomis as with the Goatsbeard Jub: 2d.",
  "",
  "Let Hashum rejoice with Moon-Trefoil.",
  "",
  "Let Netophah rejoice with Cow-Wheat.",
  "",
  "Let Chephirah rejoice with Millet.",
  "",
  "Let Beeroth rejoice with Sea-Buckthorn.",
  "",
  "Let Kirjath-arim rejoice with Cacalianthemum.",
  "",
  "Let Hadid rejoice with Capsicum Guiney Pepper.",
  "",
  "Let Senaah rejoice with Bean Cape.",
  "",
  "Let Kadmiel rejoice with Hemp-Agrimony.",
  "",
  "Let Shobai rejoice with Arbor Molle.",
  "",
  "Let Hatita rejoice with Millefolium Yarrow.",
  "",
  "Let Ziha rejoice with Mitellia.",
  "",
  "Let Hasupha rejoice with Turky Balm.",
  "",
  "Let Hattil rejoice with Xeranthemum.",
  "",
  "Let Bilshan rejoice with the Leek. David for ever! God bless the Welch March 1st 1761. N.S.",
  "",
  "Let Sotai rejoice with the Mountain Ebony.",
  "",
  "Let Sophereth rejoice with White Hellebore.",
  "",
  "Let Darkon rejoice with the Melon-Thistle.",
  "",
  "Let Jaalah rejoice with Moly wild garlick.",
  "",
  "Let Ami rejoice with the Bladder Sena in season or out of season bless the name of the Lord.",
  "",
  "Let Pochereth rejoice with Fleabane.",
  "",
  "Let Keros rejoice with Tree Germander.",
  "",
  "Let Padon rejoice with Tamnus Black Briony.",
  "",
  "Let Mizpar rejoice with Stickadore.",
  "",
  "Let Baanah rejoice with Napus the French Turnip.",
  "",
  "Let Reelaiah rejoice with the Sea-Cabbage.",
  "",
  "Let Parosh rejoice with Cacubalus Chickweed.",
  "",
  "Let Hagab rejoice with Serpyllum Mother of Thyme. Hosanna to the memory of Q. Anne. March 8th N.S. 1761 -- God be gracious to old Windsmore.",
  "",
  "Let Shalmai rejoice with Meadow Rue. --",
  "",
  "Let Habaiah rejoice with Asteriscus Yellow Starwort.",
  "",
  "Let Tel-harsa rejoice with Aparine Clivers.",
  "",
  "Let Rehoboam rejoice with Folium Montanum. God give grace to the Young King.",
  "",
  "Let Hanan rejoice with Poley of Crete.",
  "",
  "Let Sheshbazzar rejoice with Polygonatum Solomon's seal.",
  "",
  "Let Zeboim rejoice with Bastard Dittany.",
  "",
  "Let The Queen of Sheba rejoice with Bulapathon Herb Patience.",
  "",
  "Let Cyrus rejoice with Baccharis Plowman's Spikenard. God be gracious to Warburton.",
  "",
  "Let Lebanah rejoice with the Golden Wingged Flycatcher a Mexican Small Bird of Passage.",
  "",
  "Let Hagabah rejoice with Orchis. Blessed be the name of the Lord Jesus for my seed in eternity.",
  "",
  "Let Siaha rejoice with the Razor-Fish. God be gracious to John Bird and his wife.",
  "",
  "Let Artaxerxes rejoice with Vanelloes. Palm Sunday 1761. The Lord Strengthen me.",
  "",
  "Let Bishlam rejoice with the Cotton-bush.",
  "",
  "Let Mithridath rejoice with Balsam of Tolu.",
  "",
  "Let Tabeel rejoice with the Carob-Tree.",
  "",
  "Let Ariel rejoice with Balsam of Peru, which sweats from a tree, that flowers like the Foxglove.",
  "",
  "Let Ebed rejoice with Balsam of Gilead. God be gracious to Stede.",
  "",
  "Let Jarib rejoice with Balsam of Capivi. The Lord strengthen my reins.",
  "",
  "Let Shimshai rejoice with Stelis Missletoe on Fir.",
  "",
  "Let Joiarib rejoice with Veronica Fluellen or Speedwell.",
  "",
  "Let Tatnai rejoice with the Barbadoes Wild Olive.",
  "",
  "Let Ezra rejoice with the Reed. The Lord Jesus make musick of it. Good Friday 1761.",
  "",
  "Let Josiphiah rejoice with Tower-Mustard. God be gracious to Durham School.",
  "",
  "Let Shether-boznai rejoice with Turnera. End of Lent 1761. No. 5.",
  "",
  "Let Jozadak rejoice with Stephanitis a vine growing naturally into chaplets.",
  "",
  "Let Jozabad rejoice with the Lily-Daffodil. Easter Day 22nd March 1761.",
  "",
  "Let Telem rejoice with Hart's Penny-royal.",
  "",
  "Let Abdi rejoice with Winter-green. God be gracious to Abdy.",
  "",
  "Let Binnui rejoice with Spotted Lungwort or Couslip of Jerusalem. God give blessing with it.",
  "",
  "Let Aziza rejoice with the Day Lily.",
  "",
  "Let Zabbai rejoice with Buckshorn Plaintain Coronopus.",
  "",
  "Let Ramoth rejoice with Persicaria.",
  "",
  "Let Athlai rejoice with Bastard Marjoram.",
  "",
  "Let Uel rejoice with Lysimachia Loose-strife which drinks of the brook by the way.",
  "",
  "Let Kelaiah rejoice with Hermannia.",
  "",
  "Let Elasah rejoice with Olibanum White or Male Frankinsense from an Arabian tree, good against Catarrhs and Spitting blood from which Christ Jesus deliver me.",
  "",
  "Let Adna rejoice with Gum Opopanax from the wounded root of a species of panace Heracleum a tall plant growing to be two or three yards high with many large wings of a yellowish green -- good for old coughs and asthmas.",
  "",
  "Let Bedeiah rejoice with Gum Sagapenum flowing from a species of Ferula which grows in Media. Lord have mercy on my breast.",
  "",
  "Let Ishijah rejoice with Sago gotten from the inward pith of the breadtree. The Lord Jesus strengthen my whole body.",
  "",
  "Let Chelal rejoice with Apios Virginian Liquorice Vetch.",
  "",
  "Let Miamin rejoice with Mezereon. God be gracious to Polly and Bess and all Canbury.",
  "",
  "Let Zebida rejoice with Tormentil good for hæmorrhages in the mouth even so Lord Jesus.",
  "",
  "Let Shemaria rejoice with Riciasides.",
  "",
  "Let Jadau rejoice with Flixweed.",
  "",
  "Let Shimeon rejoice with Squills.",
  "",
  "Let Sheal rejoice with Scorpioides. God be gracious to Legg.",
  "",
  "Let Ramiah rejoice with Water-Germander.",
  "",
  "Let Jeziah rejoice with Viper's Grass.",
  "",
  "Let Machnadebai rejoice with the Mink, a beast.",
  "",
  "Let Meremoth rejoice with the Golden Titmouse of Surinam.",
  "",
  "Let Mattenai rejoice with Hatchet Vetch.",
  "",
  "Let Chelluh rejoice with Horehound.",
  "",
  "Let Jaasau rejoice with Bird's foot.",
  "",
  "Let Maadai rejoice with Golden Rod.",
  "",
  "Let Sharai rejoice with Honey-flower.",
  "",
  "Let Shashai rejoice with Smyrnium.",
  "",
  "Let Hananiah the son of an apothecary rejoice with Bdellium.",
  "",
  "Let Hassenaah rejoice with the White Beet. God be gracious to Hasse and all musicians.",
  "",
  "Let Hachaliah rejoice with Muscus Arboreus.",
  "",
  "Let Sanballat rejoice with Ground Moss found sometimes on human skulls.",
  "",
  "Let Col-hozeh rejoice with Myrobalans, Bellerica, Chebula, Citrina, Emblica and Indica.",
  "",
  "Let Meah rejoice with Varias, a kind of streaked panther. April 8th praise the name of the Lord.",
  "",
  "Let Eliashib rejoice with Shepherd's Purse.",
  "",
  "Let Azbuk rejoice with Valerianella Corn Sallet.",
  "",
  "Let Geshem (which is Rain) rejoice with Kneeholm. Blessed be the name of the Lord Jesus for Rain and his family and for the plenteous rain this day. April 9th 1761. N.S.",
  "",
  "Let Bavai rejoice with Calceolus Ladies Slipper.",
  "",
  "Let Henadad rejoice with Cacalianthemum.",
  "",
  "Let Shallun rejoice with Mullein Tapsus barbatus good for the breast.",
  "",
  "Let Ophel rejoice with Camara.",
  "",
  "Let Meshezabeel rejoice with Stephanomelis. Old April bless the name of the Lord Jesus.",
  "",
  "Let Zadok the son of Baana rejoice with Viburnum.",
  "",
  "Let Vaniah rejoice with Pug in a pinner. God be gracious to house of Vane especially Anne.",
  "",
  "Let Besodeiah rejoice with the Nettle.",
  "",
  "Let Melatiah rejoice with Adonis Bird's eye.",
  "",
  "Let Jadon rejoice with Borrage.",
  "",
  "Let Palal rejoice with the female Balsamime. God be gracious to my wife.",
  "",
  "Let Ezer rejoice with Basella Climbing Nightshade.",
  "",
  "Let Uzai rejoice with Meadow Sweet.",
  "",
  "Let Zalaph rejoice with Rose-bay.",
  "",
  "Let Halohesh rejoice with Ambrosia, that bears a fruit like a club.",
  "",
  "Let Malchiah Son of Rechab rejoice with the Rose-colour'd flow'ring Rush.",
  "",
  "Let Sia rejoice with Argemone Prickly Poppy.",
  "",
  "Let Lebana rejoice with Amaranthoides Globe Amaranth.",
  "",
  "Let Rephaiah the Son of Hur rejoice with the Berry-bearing Angelica.",
  "",
  "Let Harhaiah of the Goldsmiths rejoice with Segullum, the earth that detects the mine.",
  "",
  "Let Harumaph rejoice with the Upright Honeysuckle.",
  "",
  "Let Hashabniah rejoice with the Water Melon. Blessed be the manuscripts of Almighty God.",
  "",
  "Let Phaseah rejoice with the Cassioberry Bush.",
  "",
  "Let Nephishesim rejoice with Cannacorus Indian Reed.",
  "",
  "Let Tamah rejoice with Cainito Star-Apple -- God be praised for this Eleventh of April o.s. in which I enter into the Fortieth Year of my age. Blessed. Blessed. Blessed!",
  "",
  "Let Siloah rejoice with Guidonia with a Rose-Colour'd-Flower.",
  "",
  "Let Benjamin a Rebuilder of Jerusalem rejoice with the Rock-Rose. Newton, bless!",
  "",
  "Let Malchijah Son of Harim rejoice with Crysanthemoides.",
  "",
  "Let Besai rejoice with Hesperis Queen's Gilly-Flow'r.",
  "",
  "Let Perida rejoice with Podded Fumitory.",
  "",
  "Let Tabbaoth rejoice with Goldy Locks. God be merciful to my wife.",
  "",
  "Let Bakbuk rejoice with Soft Thistle.",
  "",
  "Let Hodevah rejoice with Coronilla.",
  "",
  "Let Tobiah rejoice with Crotolaria. God be praised for his infinite goodness and mercy.",
  "",
  "Let Mehetabeel rejoice with Hsemanthus the Blood Flower. Blessed be the name of the Blood of the Lord Jesus.",
  "",
  "Let Bazlith rejoice with the Horned Poppy.",
  "",
  "Let Hagaba rejoice with the Turnsole. God be gracious to Cutting.",
  "",
  "Let Shalmai rejoice with Lycopersicum Love-apple. God be gracious to Dunn.",
  "",
  "Let Arah rejoice with Fritillaria the Chequer'd Tulip.",
  "",
  "Let Raamiah rejoice with the Double Sweetscented Pione.",
  "",
  "Let Hashub Son of Pahath-moab rejoice with the French Honeysuckle.",
  "",
  "Let Ananiah rejoice with the Corn-Flag.",
  "",
  "Let Nahamani rejoice with the May-apple. God give me fruit to this month.",
  "",
  "Let Mispereth rejoice with the Ring Parrakeet.",
  "",
  "Let Nehum rejoice with the Artichoke.",
  "",
  "Let Ginnithon rejoice with the Bottle Flower.",
  "",
  "Let Zidkijah rejoice with Mulberry Blight. God be gracious to Gum my fellow Prisoner.",
  "",
  "Let Malluch rejoice with Methonica Superb Lily.",
  "",
  "Let Jeremiah rejoice with Hemlock, which is good in outward application.",
  "",
  "Let Bilgai rejoice with Tamalapatra Indian Leaf.",
  "",
  "Let Maaziah rejoice with Chick Pease. God be gracious to Harris White 5th of May 1761.",
  "",
  "Let Kelita rejoice with Xiphion the Bulbous Iris.",
  "",
  "Let Pelaiah rejoice with Cloud-Berries. God be gracious to Peele and Ferry.",
  "",
  "Let Azaniah rejoice with the Water Lily.",
  "",
  "Let Rehob rejoice with Caucalis Bastard Parsley.",
  "",
  "Let Sherebiah rejoice with Nigella, that bears a white flower.",
  "",
  "Let Beninu rejoice with Heart-Pear. God be gracious to George Bening.",
  "",
  "Let Bunni rejoice with Bulbine -- leaves like leek, purple flower.",
  "",
  "Let Zatthu rejoice with the Wild Service.",
  "",
  "Let Hizkijah rejoice with the Dwarf American Sun-Flower.",
  "",
  "Let Azzur rejoice with the Globe-Thistle.",
  "",
  "Let Hariph rejoice with Summer Savoury.",
  "",
  "Let Nebai rejoice with the Wild Cucumber.",
  "",
  "Let Magpiash rejoice with the Musk.",
  "",
  "Let Hezir rejoice with Scorpion Sena.",
  "",
  "***",
  "",
  "For H is a spirit and therefore he is God.",
  "",
  "For I is person and therefore he is God.",
  "",
  "For K is king and therefore he is God.",
  "",
  "For L is love and therefore he is God.",
  "",
  "For M is musick and therefore he is God.",
  "",
  "For N is novelty and therefore he is God.",
  "",
  "For O is over and therefore he is God.",
  "",
  "For P is power and therefore he is God.",
  "",
  "For Q is quick and therefore he is God.",
  "",
  "For R is right and therefore he is God.",
  "",
  "For S is soul and therefore he is God.",
  "",
  "For T is truth and therefore he is God.",
  "",
  "For U is union and therefore he is God.",
  "",
  "For W is worth and therefore he is God.",
  "",
  "For X has the pow'r of three and therefore he is God.",
  "",
  "For Y is yea and therefore he is God.",
  "",
  "For Z is zeal and therefore he is God, whom I pray to be gracious to the Widow Davis and Davis the Bookseller.",
  "",
  "For Christ being A and Ω is all the intermediate letters without doubt.",
  "",
  "For there is a mystery in numbers.",
  "",
  "For One is perfect and good being at unity in himself.",
  "",
  "For Two is the most Imperfect of all numbers.",
  "",
  "For every thing infinitely perfect is Three.",
  "",
  "For the Devil is two being without God.",
  "",
  "For he is an evil spirit male and female.",
  "",
  "For he is called the Duce by foolish invocation on that account.",
  "",
  "For Three is the simplest and best of all numbers.",
  "",
  "For Four is good being square.",
  "",
  "For Five is not so good in itself but works well in combination.",
  "",
  "For Five is not so good in itself as it consists of two and three.",
  "",
  "For Six is very good consisting of twice three.",
  "",
  "For Seven is very good consisting of two compleat numbers.",
  "",
  "For Eight is good for the same reason and propitious to me Eighth of March 1761 hallelujah.",
  "",
  "For Nine is a number very good and harmonious.",
  "",
  "For Cipher is a note of augmentation very good.",
  "",
  "For innumerable ciphers will amount to something.",
  "",
  "For the mind of man cannot bear a tedious accumulation of nothings without effect.",
  "",
  "For infinite upon infinite they make a chain.",
  "",
  "For the last link is from man very nothing ascending to the first Christ the Lord of All.",
  "",
  "For the vowell is the female spirit in the Hebrew consonant.",
  "",
  "For there are more letters in all languages not communicated.",
  "",
  "For there are some that have the power of sentences. O rare thirteenth of march 1761.",
  "",
  "For St Paul was caught up into the third heavens.",
  "",
  "For there he heard certain words which it was not possible for him to understand.",
  "",
  "For they were constructed by uncommunicated letters.",
  "",
  "For they are signs of speech too precious to be communicated for ever.",
  "",
  "For after ת there follows another letter in the Hebrew tongue.",
  "",
  "For his name is Wau and his figure is thus .",
  "",
  "For the Æolians knew something of him in the spirit, but could not put him down.",
  "",
  "For the figures were first communicated to Esaw. God be gracious to Musgrave.",
  "",
  "For he was blest as a merchant.",
  "",
  "For the blessing of Jacob was in the spirit and Esau's for temporal thrift.",
  "",
  "For the story of Orpheus is of the truth.",
  "",
  "For there was such a person a cunning player on the harp.",
  "",
  "For he was a believer in the true God and assisted in the spirit.",
  "",
  "For he play'd upon the harp in the spirit by breathing upon the strings.",
  "",
  "For this will affect every thing that is sustaind by the spirit, even every thing in nature.",
  "",
  "For it is the business of a man gifted in the word to prophecy good.",
  "",
  "For it will be better for England and all the world in a season, as I prophecy this day.",
  "",
  "For I prophecy that they will obey the motions of the spirit descended upon them as at this day.",
  "",
  "For they have seen the glory of God already come down upon the trees.",
  "",
  "For I prophecy that it will descend upon their heads also.",
  "",
  "For I prophecy that the praise of God will be in every man's mouth in the Publick streets.",
  "",
  "For I prophecy that there will be Publick worship in the cross ways and fields.",
  "",
  "For I prophecy that the general salutation will be. The Lord Jesus prosper you. I wish you good luck in the name of the Lord Jesus!",
  "",
  "For I prophecy that there will be more mercy for criminals.",
  "",
  "For I prophecy that there will be less mischief concerning women.",
  "",
  "For I prophecy that they will be cooped up and kept under due controul.",
  "",
  "For I prophecy that there will be full churches and empty play-houses.",
  "",
  "For I prophecy that they will learn to take pleasure in glorifying God with great cheerfulness.",
  "",
  "For I prophecy that they will observe the Rubrick with regard to days of Fasting and Abstinence.",
  "",
  "For I prophecy that the clergy in particular will set a better example.",
  "",
  "For I prophecy that they will not dare to imprison a brother or sister for debt.",
  "",
  "For I prophecy that hospitality and temperance will revive.",
  "",
  "For I prophecy that men will be much stronger in the body.",
  "",
  "For I prophecy that the gout, and consumptions will be curable.",
  "",
  "For I prophecy that man will be as good as a Lupine.",
  "",
  "For the Lupine professes his Saviour in Grain.",
  "",
  "For the very Hebrew letter is fairly graven upon his Seed.",
  "",
  "For with diligence the whole Hebrew Alphabet may be found in a parcel of his seed.",
  "",
  "For this a stupendous evidence of the communicating God in externals.",
  "",
  "For I prophecy that they will call the days by better names.",
  "",
  "For the Lord's day is the first.",
  "",
  "For the following is the second.",
  "",
  "For so of the others untill the seventh.",
  "",
  "For the seventh day is the Sabbath according to the word of God direct for ever and ever.",
  "",
  "For I prophecy that the King will have grace to put the crown upon the altar.",
  "",
  "For I prophecy that the name of king in England will be given to Christ alone.",
  "",
  "For I prophecy that mm will live to a much greater age. This ripens apace God be praised.",
  "",
  "For I prophecy that they will grow taller and stronger.",
  "",
  "For degeneracy has done a great deal more than is in general imagined.",
  "",
  "For men in David's time were ten feet high in general.",
  "",
  "For they had degenerated also from the strength of their fathers.",
  "",
  "For I prophecy that players and mimes will not be named amongst us.",
  "",
  "For I prophecy in the favour of dancing which in mutual benevolence is for the glory of God.",
  "",
  "For I prophecy that the exactions of Moab will soon be at an end.",
  "",
  "For the Moabites even the French are in their chastisement for humiliation.",
  "",
  "For I prophecy that the Reformation will make way in France when Moab is made meek by being well drubbed by the English.",
  "",
  "For I prophecy that the Reformation will make great way by means of the Venetians.",
  "",
  "For the Venetian will know that the Englishman is his brother.",
  "",
  "For the Liturgy will obtain in all languages.",
  "",
  "For England is the head and not the tail.",
  "",
  "For England is the head of Europe in the spirit.",
  "",
  "For Spain, Portugal and France are the heart.",
  "",
  "For Holland and Germany are the middle.",
  "",
  "For Italy is one of the legs.",
  "",
  "For I prophecy that there will not be a meetinghouse within two miles of a church.",
  "",
  "For I prophecy that schismaticks will be detected.",
  "",
  "For I prophecy that men will learn the use of their knees.",
  "",
  "For every thing that can be done in that posture (upon the knees) is better so done than otherwise.",
  "",
  "For I prophecy that they will understand the blessing and virtue of the rain.",
  "",
  "For rain is exceedingly good for the human body.",
  "",
  "For it is good therefore to have flat roofs to the houses, as of old.",
  "",
  "For it is good to let the rain come upon the naked body unto purity and refreshment.",
  "",
  "For I prophecy that they will respect decency in all points.",
  "",
  "For they will do it in conceit, word, and motion.",
  "",
  "For they will go forth afield.",
  "",
  "For the Devil can work upon stagnating filth to a very great degree.",
  "",
  "For I prophecy that we shall have our horns again.",
  "",
  "For in the day of David Men as yet had a glorious horn upon his forehead.",
  "",
  "For this horn was a bright substance in colour and consistence as the nail of the hand.",
  "",
  "For it was broad, thick and strong so as to serve for defence as well as ornament.",
  "",
  "For it brightened to the Glory of God, which came upon the human face at morning prayer.",
  "",
  "For it was largest and brightest in the best men.",
  "",
  "For it was taken away all at once from all of them.",
  "",
  "For this was done in the divine contempt of a general pusillanimity.",
  "",
  "For this happened in a season after their return from the Babylonish captivity.",
  "",
  "For their spirits were broke and their manhood impair'd by foreign vices for exaction.",
  "",
  "For I prophecy that the English will recover their horns the first.",
  "",
  "For I prophecy that all the nations in the world will do the like in turn.",
  "",
  "For I prophecy that all Englishmen will wear their beards again.",
  "",
  "For a beard is a good step to a horn.",
  "",
  "For when men get their horns again, they will delight to go uncovered.",
  "",
  "For it is not good to wear any thing upon the head.",
  "",
  "For a man should put no obstacle between his head and the blessing of Almighty God.",
  "",
  "For a hat was an abomination of the heathen. Lord have mercy upon the Quakers.",
  "",
  "For the ceiling of the house is an obstacle and therefore we pray on the house-top.",
  "",
  "For the head will be liable to less disorders on the recovery of its horn.",
  "",
  "For the horn on the forehead is a tower upon an arch.",
  "",
  "For it is a strong munition against the adversary, who is sickness and death.",
  "",
  "For it is instrumental in subjecting the woman.",
  "",
  "For the insolence of the woman has increased ever since Man has been crest-fallen.",
  "",
  "For they have turned the horn into scoff and derision without ceasing.",
  "",
  "For we are amerced of God, who has his horn.",
  "",
  "For we are amerced of the blessed angels, who have their horns.",
  "",
  "For when they get their horns again they will put them upon the altar.",
  "",
  "For they give great occasion for mirth and musick.",
  "",
  "For our Blessed Saviour had not his horn upon the face of the earth.",
  "",
  "For this was in meekness and condescension to the infirmities of human nature at that time.",
  "",
  "For at his second coming his horn will be exalted in glory.",
  "",
  "For his horn is the horn of Salvation.",
  "",
  "For Christ Jesus has exalted my voice to his own glory.",
  "",
  "For he has answered me in the air as with a horn from Heaven to the ears of many people.",
  "",
  "For the horn is of plenty.",
  "",
  "For this has been the sense of all ages.",
  "",
  "For Man and Earth suffer together.",
  "",
  "For when Man was amerced of his horn, earth lost part of her fertility.",
  "",
  "For the art of Agriculture is improving.",
  "",
  "For this is evident in flowers.",
  "",
  "For it is more especially manifest in double flowers.",
  "",
  "For earth will get it up again by the blessing of God on the industry of man.",
  "",
  "For the horn is of plenty because of milk and honey.",
  "",
  "For I pray God be gracious to the Bees and the Beeves this day.",
  ""
]