module.exports = [
  "The Night came on the Waters--all was rest",
  "On Earth--but Rage on Ocean's troubled Heart.",
  "The Waves arose and rolled beneath the blast;",
  "The Sailors gazed upon their shivered Mast.",
  "In that dark Hour a long loud gathered cry",
  "From out the billows pierced the sable sky,",
  "And borne o'er breakers reached the craggy shore--",
  "The Sea roars on--that Cry is heard no more.",
  "",
  "There is no vestige, in the Dawning light,",
  "Of those that shrieked thro' shadows of the Night.",
  "The Bark--the Crew--the very Wreck is gone,",
  "Marred--mutilated--traceless--all save one.",
  "In him there still is Life, the Wave that dashed",
  "On shore the plank to which his form was lashed,",
  "Returned unheeding of its helpless Prey--",
  "The lone survivor of that Yesterday--",
  "The one of Many whom the withering Gale",
  "Hath left unpunished to record their Tale.",
  "But who shall hear it? on that barren Sand",
  "None comes to stretch the hospitable hand.",
  "That shore reveals no print of human foot,",
  "Nor e'en the pawing of the wilder Brute;",
  "And niggard vegetation will not smile,",
  "All sunless on that solitary Isle.",
  "",
  "The naked Stranger rose, and wrung his hair,",
  "And that first moment passed in silent prayer.",
  "Alas! the sound--he sunk into Despair--",
  "He was on Earth--but what was Earth to him,",
  "Houseless and homeless--bare both breast and limb?",
  "Cut off from all but Memory he curst",
  "His fate--his folly--but himself the worst.",
  "What was his hope? he looked upon the Wave--",
  "Despite--of all--it still may be his Grave!",
  "",
  "He rose and with a feeble effort shaped",
  "His course unto the billows--late escaped:",
  "But weakness conquered--swam his dizzy glance,",
  "And down to Earth he sunk in silent trance.",
  "How long his senses bore its chilling chain,",
  "He knew not--but, recalled to Life again,",
  "A stranger stood beside his shivering form--",
  "And what was he? had he too scaped the storm?",
  "",
  "He raised young Julian. \"Is thy Cup so full",
  "Of bitterness--thy Hope--thy heart so dull",
  "That thou shouldst from Thee dash the Draught of Life,",
  "So late escaped the elemental strife!",
  "Rise--tho' these shores few aids to Life supply,",
  "Look upon me, and know thou shalt not die.",
  "Thou gazest in mute wonder--more may be",
  "Thy marvel when thou knowest mine and me.",
  "But come--The bark that bears us hence shall find",
  "Her Haven, soon, despite the warning Wind.\"",
  "",
  "He raised young Julian from the sand, and such",
  "Strange power of healing dwelt within the touch,",
  "That his weak limbs grew light with freshened Power,",
  "As he had slept not fainted in that hour,",
  "And woke from Slumber--as the Birds awake,",
  "Recalled at morning from the branchéd brake,",
  "When the day's promise heralds early Spring,",
  "And Heaven unfolded woos their soaring wing:",
  "So Julian felt, and gazed upon his Guide,",
  "With honest Wonder what might next betide.",
  ""
]