module.exports = [
  "The fiery mountains answer each other;",
  "Their thunderings are echoed from zone to zone;",
  "The tempestuous oceans awake one another,",
  "And the ice-rocks are shaken round Winter's throne,",
  "When the clarion of the Typhoon is blown.",
  "",
  "From a single cloud the lightening flashes,",
  "Whilst a thousand isles are illumined around,",
  "Earthquake is trampling one city to ashes,",
  "An hundred are shuddering and tottering; the sound",
  "Is bellowing underground.",
  "",
  "But keener thy gaze than the lightening's glare,",
  "And swifter thy step than the earthquake's tramp;",
  "Thou deafenest the rage of the ocean; thy stare",
  "Makes blind the volcanoes; the sun's bright lamp",
  "To thine is a fen-fire damp.",
  "",
  "From billow and mountain and exhalation",
  "The sunlight is darted through vapour and blast;",
  "From spirit to spirit, from nation to nation,",
  "From city to hamlet thy dawning is cast,--",
  "And tyrants and slaves are like shadows of night",
  "In the van of the morning light.",
  ""
]