module.exports = [
  "We meet not as we parted,",
  "We feel more than all may see;",
  "My bosom is heavy-hearted,",
  "And thine full of doubt for me:--",
  "One moment has bound the free.",
  "",
  "That moment is gone for ever,",
  "Like lightning that flashed and died--",
  "Like a snowflake upon the river--",
  "Like a sunbeam upon the tide,",
  "Which the dark shadows hide.",
  "",
  "That moment from time was singled",
  "As the first of a life of pain;",
  "The cup of its joy was mingled",
  "--Delusion too sweet though vain!",
  "Too sweet to be mine again.",
  "",
  "Sweet lips, could my heart have hidden",
  "That its life was crushed by you,",
  "Ye would not have then forbidden",
  "The death which a heart so true",
  "Sought in your briny dew.",
  "",
  "...",
  "...",
  "...",
  "Methinks too little cost",
  "For a moment so found, so lost!",
  ""
]