module.exports = [
  "Far, far away, O ye",
  "Halcyons of Memory,",
  "Seek some far calmer nest",
  "Than this abandoned breast!",
  "No news of your false spring",
  "To my heart's winter bring,",
  "Once having gone, in vain",
  "Ye come again.",
  "",
  "Vultures, who build your bowers",
  "High in the Future's towers,",
  "Withered hopes on hopes are spread!",
  "Dying joys, choked by the dead,",
  "Will serve your beaks for prey",
  "Many a day.",
  "h fade and flee",
  "In the light of life's dim morning.",
  "Thine eyes glowed in the glare",
  "Of the moon's dying light;",
  "As a fen-fire's beam on a sluggish stream",
  "Gleams dimly, so the moon shone there,",
  "And it yellowed the strings of thy raven hair,",
  "That shook in the wind of night.",
  "",
  "The moon made thy lips pale, beloved--",
  "The wind made thy bosom chill--",
  "The night did shed on thy dear head",
  "Its frozen dew, and thou didst lie",
  "Where the bitter breath of the naked sky",
  "Might visit thee at will.",
  ""
]