module.exports = [
  "Honey from silkworms who can gather,",
  "Or silk from the yellow bee?",
  "The grass may grow in winter weather",
  "As soon as hate in me.",
  "",
  "Hate men who cant, and men who pray,",
  "And men who rail like thee;",
  "An equal passion to repay",
  "They are not coy like me.",
  "",
  "Or seek some slave of power and gold",
  "To be thy dear heart's mate;",
  "Thy love will move that bigot cold",
  "Sooner than me, thy hate.",
  "",
  "A passion like the one I prove",
  "Cannot divided be;",
  "I hate thy want of truth and love--",
  "How should I then hate thee?",
  ""
]