module.exports = [
  "BEAUTY, the attribute of Heaven!",
  "In various forms to mortals given,",
  "With magic skill enslaves mankind,",
  "As sportive fancy sways the mind.",
  "Search the wide world, go where you will,",
  "VARIETY pursues you still;",
  "Capricious Nature knows no bound,",
  "Her unexhausted gifts are found",
  "In ev'ry clime, in ev'ry face,",
  "Each has its own peculiar grace.",
  "",
  "To GALLIA's frolic scenes repair,",
  "There reigns the tyny DEBONAIRE;",
  "The mincing step­the slender waist,",
  "The lip with bright vermilion grac'd:",
  "The short pert nose­the pearly teeth,",
  "With the small dimpled chin beneath,­",
  "The social converse, gay and free,",
  "The smart BON-MOT and REPARTEE.",
  "",
  "ITALIA boasts the melting fair,",
  "The pointed step, the haughty air,",
  "Th' empassion'd tone, the languid eye,",
  "The song of thrilling harmony;",
  "Insidious LOVE conceal'd in smiles",
  "That charms­and as it charms beguiles.",
  "",
  "View GRECIAN MAIDS, whose finish'd forms",
  "The wond'ring sculptor's fancy warms!",
  "There let thy ravish'd eye behold",
  "The softest gems of Nature's mould;",
  "Each charm, that REYNOLDS learnt to trace,",
  "From SHERIDAN's bewitching face.",
  "",
  "Imperious TURKEY's pride is seen",
  "In Beauty's rich luxuriant mien;",
  "The dark and sparkling orbs that glow",
  "Beneath a polish'd front of snow:",
  "The auburn curl that zephyr blows",
  "About the cheek of brightest rose:",
  "The shorten'd zone, the swelling breast,",
  "With costly gems profusely drest;",
  "Reclin'd in softly-waving bow'rs,",
  "On painted beds of fragrant flow'rs;",
  "Where od'rous canopies dispense",
  "ARABIA's spices to the sense;",
  "Where listless indolence and ease,",
  "Proclaim the sov'reign wish, to please.",
  "'Tis thus, capricious FANCY shows",
  "How far her frolic empire goes !",
  "",
  "On ASIA's sands, on ALPINE snow,",
  "We trace her steps where'er we go;",
  "The BRITISH Maid with timid grace;",
  "The tawny INDIAN 's varnish'd face;",
  "The jetty AFRICAN; the fair",
  "Nurs'd by EUROPA's softer air;",
  "With various charms delight the mind,",
  "For FANCY governs ALL MANKIND.",
  ""
]