module.exports = [
  "Alas! the people's hearts are now full of sorrow",
  "For the deceased Professor Blackie, of Edinboro';",
  "Because he was a Christian man, affable and kind,",
  "And his equal in charitable actions would be hard to find",
  "",
  "'Twas in the year of 1895, March the 2nd, he died at 10 o'clock.",
  "Which to his dear wife, and his adopted son, was a great shock;",
  "And before he died he bade farewell to his adopted son and wife.",
  "Which, no doubt, they will remember during life.",
  "",
  "Professor Blackie celebrated his golden wedding three years ago,",
  "When he was made the recipient of respect from high and low.",
  "He leaves a widow, but, fortunately, no family,",
  "Which will cause Mrs. Blackie to feel less unhappy.",
  "",
  "Professor Blackie will be greatly missed in Edinboro;",
  "Especially those that met him daily will feel great sorrow,",
  "When they think of his never-failing plaid and hazel rung,",
  "For, although he was an old man, he considered he was young.",
  "",
  "He had a very striking face, and silvery locks like a seer,",
  "And in the hearts of the Scottish people he was loved most dear;",
  "And many a heart will mourn for him, but all in vain,",
  "Because he never can return to them again.",
  "",
  "He was a very kind-hearted man, and in no way vain,",
  "And I'm afraid we ne'er shall look upon his like again;",
  "And to hear him tell Scotch stories, the time did quickly pass,",
  "And for singing Scotch songs few could him surpass.",
  "",
  "But I hope e is in heaven, singing with saints above,",
  "Around God's throne, where all is peace and love;",
  "There, where God's children daily doth meet",
  "To sing praises to God, enchanting and sweet.",
  "",
  "He had visited almost every part of Europe in his time,",
  "And, like Lord Byron, he loved the Grecian clime;",
  "Nor did he neglect his own dear country,",
  "And few men knew it more thoroughly than he.",
  "",
  "On foot he tramped o'er most of bonnie Scotland,",
  "And in his seventies he climbed the highest hills most grand.",
  "Few men in his day could be compared to him,",
  "Because he wasn't hard on fallen creatures when they did sin.",
  "",
  "Oh, dearly beloved Professor Blackie, I must conclude my muse,",
  "And to write in praise of thee my pen does not refuse;",
  "Because you were a very Christian man, be it told,",
  "Worthy of a monument, and your name written thereon in letters of gold.",
  ""
]