module.exports = [
  "Doubtless, sweet girl! the hissing lead,",
  "  Wafting destruction o'er thy charms",
  "And hurtling o'er thy lovely head,",
  "  Has fill'd that breast with fond alarms.",
  "",
  "Surely some envious Demon's force,",
  "  Vex'd to behold such beauty here,",
  "Impell'd the bullet's viewless course,",
  "  Diverted from its first career.",
  "",
  "Yes! in that nearly fatal hour,",
  "  The ball obey'd some hell-born guide;",
  "But Heaven, with interposing power,",
  "  In pity turn'd the death aside.",
  "",
  "Yet, as perchance one trembling tear",
  "  Upon that thrilling bosom fell;",
  "Which _I_, th' unconscious cause of fear,",
  "  Extracted from its glistening cell;--",
  "",
  "Say, what dire penance can atone",
  "  For such an outrage, done to thee?",
  "Arraign'd before thy beauty's throne,",
  "  What punishment wilt thou decree?",
  "",
  "Might I perform the Judge's part,",
  "  The sentence I should scarce deplore;",
  "It only would restore a heart,",
  "  Which but belong'd to _thee_ before.",
  "",
  "The least atonement I can make",
  "  Is to become no longer free;",
  "Henceforth, I breathe but for thy sake,",
  "  Thou shalt be _all in all_ to me.",
  "",
  "But thou, perhaps, may'st now reject",
  "  Such expiation of my guilt;",
  "Come then--some other mode elect?",
  "  Let it be death--or what thou wilt.",
  "",
  "Choose, then, relentless! and I swear",
  "  Nought shall thy dread decree prevent;",
  "Yet hold--one little word forbear!",
  "  Let it be aught but banishment.",
  ""
]