module.exports = [
  "Beautiful Loch Katrine in all thy majesty so grand,",
  "Oh! how charming and fascinating is thy silver strand!",
  "Thou certainly art most lovely, and worthy to be seen,",
  "Especially thy beautiful bay and shrubberies green.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  "And as I gaze upon it, let me pause and think,",
  "How many people in Glasgow of its water drink,",
  "That's conveyed to them in pipes from its placid lake,",
  "And are glad to get its water their thirst to slake.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  "The mountains on either side of it are beautiful to be seen,",
  "Likewise the steamers sailing on it with their clouds of steam:",
  "And their shadows on its crystal waters as they pass along,",
  "Is enough to make the tourist burst into song.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  "'Tis beautiful to see its tiny wimpling rills,",
  "And the placid Loch in the hollow of a circle of hills,",
  "Glittering like silver in the sun's bright array,",
  "Also many a promontory, little creek, and bay.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  "Then to the east there's the finely wooded Ellen's Isle,",
  "There the tourist can the tedious hours beguile,",
  "As he gazes on its white gravelled beautiful bay,",
  "It will help to drive dull care away.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  "The mountains Ben-An and Ben-Venue are really very grand",
  "Likewise the famous and clear silver strand;",
  "Where the bold Rob Roy spent many a happy day,",
  "With his faithful wife, near by its silvery bay.",
  "",
  "Then away to Loch Katrine in the summer time,",
  "And feast on its scenery most lovely and sublime;",
  "There's no other scene can surpass in fair Scotland,",
  "It's surrounded by mountains and trees most grand.",
  ""
]