module.exports = [
  "This is the hardest part:",
  "When I came back to life",
  "I was a good family dog",
  "and not too friendly to strangers.",
  "I got a thirty-five dollar raise",
  "in salary, and through the pea-soup fogs",
  "I drove the General, and introduced him",
  "at rallies. I had a totalitarian approach",
  "and was a massive boost to his popularity.",
  "I did my best to reduce the number of people.",
  "The local bourgeoisie did not exist.",
  "One of them was a mystic",
  "and walked right over me",
  "as if I were a bed of hot coals.",
  "This is par for the course-",
  "I will be employing sundry golf metaphors",
  "henceforth, because a dog, best friend",
  "and chief advisor to the General, should.",
  "While dining with the General I said,",
  "\"Let's play the back nine in a sacred rage.",
  "Let's tee-off over the foredoomed community",
  "and putt ourselves thunderously, touching bottom.\"",
  "He drank it all in, rugged and dusky.",
  "I think I know what he was thinking.",
  "He held his automatic to my little head",
  "and recited a poem about my many weaknesses,",
  "for which I loved him so.",
  ""
]