module.exports = [
  "The Sun, who never stops to dine,",
  "Two hours had pass'd the mid-way line,",
  "And driving at his usual rate,",
  "Lash'd on his downward car of state.",
  "And now expired the short vacation,",
  "And dinner o'er in epic fashion,",
  "While all the crew, beneath the trees,",
  "Eat pocket-pies, or bread and cheese,",
  "(Nor shall we, like old Homer, care",
  "To versify their bill of fare)",
  "Each active party, feasted well,",
  "Throng'd in, like sheep, at sound of bell;",
  "With equal spirit took their places,",
  "And meeting oped with three Oh Yesses:",
  "When first, the daring Whigs t' oppose,",
  "Again the great M'Fingal rose,",
  "Stretch'd magisterial arm amain,",
  "And thus resumed th' accusing strain.",
  "",
  "",
  "\"Ye Whigs attend, and hear affrighted",
  "The crimes whereof ye stand indicted;",
  "The sins and follies past all compass,",
  "That prove you guilty, or non compos.",
  "I leave the verdict to your senses,",
  "And jury of your consciences;",
  "Which though they're neither good nor true,",
  "Must yet convict you and your crew.",
  "",
  "",
  "\"Ungrateful sons! a factious band,",
  "That rise against your parent land!",
  "Ye viper race, that burst in strife",
  "The genial womb that gave you life,",
  "Tear with sharp fangs and forked tongue",
  "The indulgent bowels whence ye sprung;",
  "And scorn the debt and obligation,",
  "You justly owe the British nation,",
  "Which, since you cannot pay, your crew",
  "Affect to swear was never due.",
  "",
  "",
  "\"Did not the deeds of England's primate",
  "First drive your fathers to this climate,",
  "Whom jails and fines and every ill",
  "Forced to their good against their will?",
  "Ye owe to their obliging temper",
  "The peopling your new-fangled empire,",
  "While every British act and canon",
  "Stood forth your causa sine qua non.",
  "Who'd seen, except for these restraints,",
  "Your witches, quakers, whigs and saints,",
  "Or heard of Mather's famed Magnalia,",
  "If Charles and Laud had chanced to fail you?",
  "Did they not send your charters o'er,",
  "And give you lands you own'd before,",
  "Permit you all to spill your blood,",
  "And drive out heathens where you could;",
  "On these mild terms, that, conquest won,",
  "The realm you gain'd should be their own?",
  "And when of late attack'd by those,",
  "Whom her connection made your foes,",
  "Did they not then, distress'd by war,",
  "Send generals to your help from far,",
  "Whose aid you own'd, in terms less haughty,",
  "And thankfully o'erpaid your quota?",
  "Say, at what period did they grudge",
  "To send you Governor or Judge,",
  "With all their Missionary crew,",
  "To teach you law and gospel too?",
  "They brought all felons in the nation",
  "To help you on in population;",
  "Proposed their Bishops to surrender,",
  "And made their Priests a legal tender,",
  "Who only ask'd, in surplice clad,",
  "The simple tithe of all you had:",
  "And now, to keep all knaves in awe,",
  "Have sent their troops t' establish law,",
  "And with gunpowder, fire and ball,",
  "Reform your people, one and all.",
  "Yet when their insolence and pride",
  "Have anger'd all the world beside;",
  "When fear and want at once invade,",
  "Can you refuse to lend them aid,",
  "And rather risk your heads in fight,",
  "Than gratefully throw in your mite?",
  "Can they for debts make satisfaction,",
  "Should they dispose their realm at auction,",
  "And sell off Britain's goods and land all",
  "To France and Spain, by inch of candle?",
  "Shall good King George, with want oppress'd,",
  "Insert his name in bankrupt list,",
  "And shut up shop, like failing merchant,",
  "That fears the bailiffs should make search in't;",
  "With poverty shall princes strive,",
  "And nobles lack whereon to live?",
  "Have they not rack'd their whole inventions",
  "To feed their brats on posts and pensions;",
  "Made their Scotch friends with taxes groan,",
  "And pick'd poor Ireland to the bone:",
  "Yet have on hand, as well deserving,",
  "Ten thousand bastards, left for starving?",
  "And can you now, with conscience clear,",
  "Refuse them an asylum here,",
  "And not maintain, in manner fitting,",
  "These genuine sons of mother Britain?",
  "",
  "",
  "\"T' evade these crimes of blackest grain",
  "You prate of liberty in vain,",
  "And strive to hide your vile designs",
  "In terms abstruse, like school-divines.",
  "",
  "",
  "\"Your boasted patriotism is scarce,",
  "And country's love is but a farce:",
  "For after all the proofs you bring,",
  "We Tories know there's no such thing.",
  "Hath not Dalrymple show'd in print,",
  "And Johnson too, there's nothing in't;",
  "Produced you demonstration ample,",
  "From others' and their own example,",
  "That self is still, in either faction,",
  "The only principle of action;",
  "The loadstone, whose attracting tether",
  "Keeps the politic world together:",
  "And spite of all your double dealing,",
  "We all are sure 'tis so, from feeling.",
  "",
  "",
  "\"Who heeds your babbling of transmitting",
  "Freedom to brats of your begetting,",
  "Or will proceed, as tho' there were a tie,",
  "And obligation to posterity?",
  "We get them, bear them, breed and nurse.",
  "What has posterity done for us,",
  "That we, least they their rights should lose,",
  "Should trust our necks to gripe of noose?",
  "",
  "",
  "\"And who believes you will not run?",
  "Ye're cowards, every mother's son;",
  "And if you offer to deny,",
  "We've witnesses to prove it by.",
  "Attend th' opinion first, as referee,",
  "Of your old general, stout Sir Jeffery;",
  "Who swore that with five thousand foot",
  "He'd rout you all, and in pursuit",
  "Run thro' the land, as easily",
  "As camel thro' a needle's eye?",
  "Did not the mighty Colonel Grant",
  "Against your courage pour his rant,",
  "Affirm your universal failure",
  "In every principle of valour,",
  "And swear no scamperers e'er could match you,",
  "So swift, a bullet scarce could catch you?",
  "And will you not confess, in this",
  "A judge most competent he is;",
  "Well skill'd on running to decide,",
  "As what himself has often tried?",
  "'Twould not methinks be labor lost,",
  "If you'd sit down and count the cost,",
  "And ere you call your Yankies out,",
  "First think what work you've set about.",
  "Have you not roused, his force to try on,",
  "That grim old beast, the British Lion:",
  "And know you not, that at a sup",
  "He's large enough to eat you up?",
  "Have you survey'd his jaws beneath,",
  "Drawn inventories of his teeth,",
  "Or have you weigh'd, in even balance,",
  "His strength and magnitude of talons?",
  "His roar would change your boasts to fear,",
  "As easily, as sour small beer;",
  "And make your feet from dreadful fray,",
  "By native instinct run away.",
  "Britain, depend on't, will take on her",
  "T' assert her dignity and honor,",
  "And ere she'd lose your share of pelf,",
  "Destroy your country, and herself.",
  "For has not North declared they fight",
  "To gain substantial rev'nue by't,",
  "Denied he'd ever deign to treat,",
  "Till on your knees and at his feet?",
  "And feel you not a trifling ague",
  "From Van's \"Delenda est Carthago?",
  "For this now Britain has projected,",
  "Think you she has not means t' effect it?",
  "Has she not set at work all engines",
  "To spirit up the native Indians,",
  "Send on your backs the tawney band,",
  "With each an hatchet in his hand,",
  "T' amuse themselves with scalping knives.",
  "And butcher children and your wives;",
  "And paid them for your scalps at sale",
  "More than your heads would fetch by tale;",
  "That she might boast again with vanity,",
  "Her English national humanity?",
  "For now in its primeval sense",
  "This term, humanity, comprehends",
  "All things of which, on this side hell,",
  "The human mind is capable;",
  "And thus 'tis well, by writers sage,",
  "Applied to Britain and to Gage.",
  "On this brave work to raise allies,",
  "She sent her duplicate of Guys,",
  "To drive at different parts at once on,",
  "Her stout Guy Carlton and Guy Johnson;",
  "To each of whom, to send again you,",
  "Old Guy of Warwick were a ninny,",
  "Though the dun cow he fell'd in war,",
  "These killcows are his betters far.",
  "",
  "",
  "\"And has she not essay'd her notes",
  "To rouse your slaves to cut your throats;",
  "Sent o'er ambassadors with guineas,",
  "To bribe your blacks in Carolinas?",
  "And has not Gage, her missionary,",
  "Turn'd many an Afric to a Tory;",
  "Made the New-England Bishop's see grow,",
  "By many a new-converted negro?",
  "As friends to government, when he",
  "Your slaves at Boston late set free,",
  "Enlisted them in black parade,",
  "Emboss'd with regimental red;",
  "While flared the epaulette, like flambeau,",
  "On Captain Cuff and Ensign Sambo:",
  "And were they not accounted then",
  "Among his very bravest men?",
  "And when such means she stoops to take,",
  "Think you she is not wide awake?",
  "As the good man of old in Job",
  "Own'd wondrous allies through the globe,",
  "Had brought the stones along the street",
  "To ratify a cov'nant meet,",
  "And every beast, from lice to lions,",
  "To join in leagues of strict alliance:",
  "Has she not cringed, in spite of pride,",
  "For like assistance, far and wide,",
  "Till all this formidable league rose",
  "Of Indians, British troops and Negroes?",
  "And can you break these triple bands",
  "By all your workmanship of hands?",
  "",
  "",
  "\"Sir,\" quoth Honorius, \"we presume",
  "You guess from past feats what's to come,",
  "And from the mighty deeds of Gage",
  "Foretell how fierce the war he'll wage.",
  "You doubtless recollected here",
  "The annals of his first great year:",
  "While, wearying out the Tories' patience,",
  "He spent his breath in proclamations;",
  "While all his mighty noise and vapour",
  "Was used in wrangling upon paper,",
  "And boasted military fits",
  "Closed in the straining of his wits;",
  "While troops, in Boston commons placed,",
  "Laid nought, but quires of paper, waste;",
  "While strokes alternate stunn'd the nation,",
  "Protest, Address and Proclamation,",
  "And speech met speech, fib clash'd with fib,",
  "And Gage still answer'd, squib for squib.",
  "",
  "",
  "\"Though this not all his time was lost on;",
  "He fortified the town of Boston,",
  "Built breastworks, that might lend assistance",
  "To keep the patriots at a distance;",
  "For howsoe'er the rogues might scoff,",
  "He liked them best the farthest off;",
  "Works of important use to aid",
  "His courage, when he felt afraid,",
  "And whence right off, in manful station,",
  "He'd boldly pop his proclamation.",
  "Our hearts must in our bosoms freeze,",
  "At such heroic deeds as these.\"",
  "",
  "",
  "\"Vain,\" said the 'Squire, \"you'll find to sneer",
  "At Gage's first triumphant year;",
  "For Providence, disposed to teaze us,",
  "Can use what instruments it pleases.",
  "To pay a tax, at Peter's wish,",
  "His chief cashier was once a fish;",
  "An ass, in Balaam's sad disaster,",
  "Turn'd orator and saved his master;",
  "A goose, placed sentry on his station,",
  "Preserved old Rome from desolation;",
  "An English bishop's cur of late",
  "Disclosed rebellions 'gainst the state;",
  "So frogs croak'd Pharaoh to repentance,",
  "And lice delay'd the fatal sentence:",
  "And heaven can ruin you at pleasure,",
  "By Gage, as soon as by a Cæsar.",
  "Yet did our hero in these days",
  "Pick up some laurel wreaths of praise.",
  "And as the statuary of Seville",
  "Made his crackt saint an exc'llent devil;",
  "So though our war small triumph brings,",
  "We gain'd great fame in other things.",
  "",
  "",
  "\"Did not our troops show great discerning,",
  "And skill your various arts in learning?",
  "Outwent they not each native noodle",
  "By far, in playing Yankee-doodle,",
  "Which as 'twas your New-England tune,",
  "'Twas marvellous they took so soon?",
  "And ere the year was fully through,",
  "Did not they learn to foot it too,",
  "And such a dance, as ne'er was known,",
  "For twenty miles on end lead down?",
  "Did they not lay their heads together,",
  "And gain your art to tar and feather,",
  "When Colonel Nesbit, thro' the town,",
  "In triumph bore the country-clown?",
  "Oh what a glorious work to sing",
  "The veteran troops of Britain's king,",
  "Adventuring for th' heroic laurel",
  "With bag of feathers and tar-barrel!",
  "To paint the cart where culprits ride,",
  "And Nesbitt marching at its side,",
  "Great executioner and proud,",
  "Like hangman high on Holborn road;",
  "And o'er the slow-drawn rumbling car,",
  "The waving ensigns of the war!",
  "As when a triumph Rome decreed",
  "For great Caligula's valiant deed,",
  "Who had subdued the British seas,",
  "By gath'ring cockles from their base;",
  "In pompous car the conq'ror bore",
  "His captive scallops from the shore,",
  "Ovations gain'd his crabs for fetching,",
  "And mighty feats of oyster-catching:",
  "'Gainst Yankies thus the war begun,",
  "They tarr'd, and triumph'd over, one;",
  "And fought and boasted through the season,",
  "With force as great and equal reason.",
  "",
  "",
  "\"Yet thus though skill'd in vict'ry's toils,",
  "They boast, not unexpert, in wiles.",
  "For gain'd they not an equal fame in",
  "The arts of secrecy and scheming;",
  "In stratagem show'd wondrous force,",
  "And modernized the Trojan horse,",
  "Play'd o'er again the tricks Ulyssean,",
  "In their famed Salem expedition?",
  "For as that horse, the poets tell ye,",
  "Bore Grecian armies in its belly,",
  "Till their full reckoning run, with joy",
  "Shrewd Sinon midwived them in Troy:",
  "So in one ship was Leslie bold",
  "Cramm'd with three hundred men in hold,",
  "Equipp'd for enterprize and sail,",
  "Like Jonas stow'd in womb of whale.",
  "To Marblehead in depth of night",
  "The cautious vessel wing'd her flight.",
  "And now the sabbath's silent day",
  "Call'd all your Yankies off to pray;",
  "Safe from each prying jealous neighbour,",
  "The scheme and vessel fell in labor.",
  "Forth from its hollow womb pour'd hast'ly",
  "The Myrmidons of Colonel Leslie.",
  "Not thicker o'er the blacken'd strand,",
  "The frogs detachment, rush'd to land,",
  "Furious by onset and surprize",
  "To storm th' entrenchment of the mice.",
  "Through Salem straight, without delay,",
  "The bold battalion took its way,",
  "March'd o'er a bridge, in open sight",
  "Of several Yankies arm'd for fight;",
  "Then without loss of time or men,",
  "Veer'd round for Boston back again,",
  "And found so well their projects thrive,",
  "That every soul got home alive.",
  "",
  "",
  "\"Thus Gage's arms did fortune bless",
  "With triumph, safety and success.",
  "But mercy is without dispute",
  "His first and darling attribute;",
  "So great, it far outwent and conquer'd",
  "His military skill at Concord.",
  "There, when the war he chose to wage,",
  "Shone the benevolence of Gage;",
  "Sent troops to that ill-omen'd place,",
  "On errands mere of special grace;",
  "And all the work, he chose them for,",
  "Was to prevent a civil war;",
  "For which kind purpose he projected",
  "The only certain way t' effect it,",
  "To seize your powder, shot and arms,",
  "And all your means of doing harms;",
  "As prudent folks take knives away,",
  "Lest children cut themselves at play.",
  "And yet, when this was all his scheme,",
  "The war you still will charge on him;",
  "And tho' he oft has swore and said it,",
  "Stick close to facts, and give no credit.",
  "Think you, he wish'd you'd brave and beard him?",
  "Why, 'twas the very thing, that scared him.",
  "He'd rather you should all have run,",
  "Than staid to fire a single gun.",
  "So, for the civil war you lament,",
  "Faith, you yourselves must take the blame in't;",
  "For had you then, as he intended,",
  "Given up your arms, it must have ended:",
  "Since that's no war, each mortal knows,",
  "Where one side only gives the blows,",
  "And t'other bears them; on reflection",
  "The most we call it is correction.",
  "Nor could the contest have gone higher,",
  "If you had ne'er return'd the fire:",
  "But when you shot, and not before,",
  "It then commenced a civil war.",
  "Else Gage, to end this controversy,",
  "Had but corrected you in mercy;",
  "Whom mother Britain, old and wise,",
  "Sent o'er, the colonies to chastise;",
  "Command obedience on their peril",
  "Of ministerial whip and ferule;",
  "And since they ne'er must come of age,",
  "Govern'd and tutor'd them by Gage.",
  "Still more, that mercy was their errand,",
  "The army's conduct makes apparent.",
  "What though at Lexington you can say,",
  "They kill'd a few, they did not fancy;",
  "At Concord then with manful popping,",
  "Discharged a round, the ball to open;",
  "Yet when they saw your rebel rout",
  "Determined still to brave it out,",
  "Did they not show their love of peace,",
  "Their wish that discord straight might cease;",
  "Demonstrate, and by proofs uncommon,",
  "Their orders were to injure no man?",
  "For did not every regular run,",
  "As soon as e'er you fired a gun;",
  "Take the first shot you sent them, greeting,",
  "As meant their signal for retreating;",
  "And fearful, if they staid for sport,",
  "You might by accident be hurt,",
  "Convey themselves with speed away",
  "Full twenty miles in half a day;",
  "Race till their legs were grown so weary,",
  "They scarce sufficed their weight to carry?",
  "Whence Gage extols, from general hearsay,",
  "The great activity of Lord Percy;",
  "Whose brave example led them on,",
  "And spirited the troops to run;",
  "Who now may boast, at royal levees,",
  "A Yankee-chace worth forty Chevys.",
  "",
  "",
  "\"Yet you, as vile as they were kind,",
  "Pursued, like tygers, still behind;",
  "Fired on them at your will, and shut",
  "The town, as though you'd starve them out;",
  "And with parade preposterous hedged,",
  "Affect to hold them there besieged:",
  "Though Gage, whom proclamations call",
  "Your Gov'rnor and Vice-Admiral,",
  "Whose power gubernatorial still",
  "Extends as far as Bunker's hill,",
  "Whose admiralty reaches, clever,",
  "Near half a mile up Mistic river,",
  "Whose naval force yet keeps the seas,",
  "Can run away whene'er he'd please.",
  "Nay, stern with rage grim Putnam boiling",
  "Plunder'd both Hogg and Noddle Island;",
  "Scared troops of Tories into town,",
  "Burn'd all their hay and houses down,",
  "And menaced Gage, unless he'd flee,",
  "To drive him headlong to the sea;",
  "As once, to faithless Jews a sign,",
  "The De'el, turn'd hog-reeve, did the swine.",
  "",
  "",
  "\"But now your triumphs all are o'er;",
  "For see from Britain's angry shore,",
  "With deadly hosts of valor join",
  "Her Howe, her Clinton and Burgoyne!",
  "As comets thro' th' affrighted skies",
  "Pour baleful ruin as they rise;",
  "As Ætna with infernal roar",
  "In conflagration sweeps the shore;",
  "Or as Abijah White, when sent",
  "Our Marshfield friends to represent,",
  "Himself while dread array involves,",
  "Commissions, pistols, swords, resolves,",
  "In awful pomp descending down",
  "Bore terror on the factious town:",
  "Not with less glory and affright,",
  "Parade these generals forth to fight.",
  "No more each British colonel runs",
  "From whizzing beetles, as air-guns;",
  "Thinks horn-bugs bullets, or thro' fears",
  "Muskitoes takes for musketeers;",
  "Nor scapes, as if you'd gain'd supplies,",
  "From Beelzebub's whole host of flies.",
  "No bug these warlike hearts appalls;",
  "They better know the sound of balls.",
  "I hear the din of battle bray;",
  "The trump of horror marks its way.",
  "I see afar the sack of cities,",
  "The gallows strung with Whig-committees;",
  "Your moderators triced, like vermin,",
  "And gate-posts graced with heads of chairmen;",
  "Your Congress for wave-off'rings hanging,",
  "And ladders throng'd with priests haranguing.",
  "What pillories glad the Tories' eyes",
  "With patriot ears for sacrifice!",
  "What whipping-posts your chosen race",
  "Admit successive in embrace,",
  "While each bears off his sins, alack!",
  "Like Bunyan's pilgrim, on his back!",
  "Where then, when Tories scarce get clear,",
  "Shall Whigs and Congresses appear?",
  "What rocks and mountains will you call",
  "To wrap you over with their fall,",
  "And save your heads, in these sad weathers,",
  "From fire and sword, and tar and feathers?",
  "For lo! with British troops tar-bright,",
  "Again our Nesbitt heaves in sight;",
  "He comes, he comes, your lines to storm,",
  "And rig your troops in uniform.",
  "To meet such heroes will ye brag,",
  "With fury arm'd, and feather-bag,",
  "Who wield their missile pitch and tar",
  "With engines new in British war?",
  "",
  "",
  "\"Lo! where our mighty navy brings",
  "Destruction on her canvass wings,",
  "While through the deep the British thunder",
  "Shall sound th' alarm, to rob and plunder!",
  "As Phoebus first, so Homer speaks,",
  "When he march'd out t' attack the Greeks,",
  "'Gainst mules sent forth his arrows fatal,",
  "And slew th' auxiliaries, their cattle:",
  "So where our ships shall stretch the keel,",
  "What vanquish'd oxen shall they steal!",
  "What heroes, rising from the deep,",
  "Invade your marshall'd hosts of sheep;",
  "Disperse whole troops of horse, and pressing,",
  "Make cows surrender at discretion;",
  "Attack your hens, like Alexanders,",
  "And regiments rout of geese and ganders;",
  "Or where united arms combine,",
  "Lead captive many a herd of swine!",
  "Then rush in dreadful fury down",
  "To fire on every seaport town;",
  "Display their glory and their wits,",
  "Fright helpless children into fits;",
  "And stoutly, from the unequal fray,",
  "Make many a woman run away.",
  "",
  "",
  "\"And can ye doubt, whene'er we please,",
  "Our chiefs shall boast such deeds as these?",
  "Have we not chiefs transcending far",
  "The old famed thunderbolts of war;",
  "Beyond the brave knight-errant fighters,",
  "Stiled swords of death, by novel-writers;",
  "Nor in romancing ages e'er rose",
  "So terrible a tier of heroes.",
  "From Gage what sounds alarm the waves!",
  "How loud a blunderbuss is Graves!",
  "How Newport dreads the blustering sallies,",
  "That thunder from our popgun, Wallace,",
  "While noise in formidable strains,",
  "Spouts from his thimble-full of brains!",
  "I see you sink in awed surprise!",
  "I see our Tory brethren rise!",
  "And as the sect'ries Sandemanian,",
  "Our friends, describe their hoped millennium;",
  "Boast how the world in every region",
  "At once shall own their true religion,",
  "For heaven shall knock, with vengeance dread,",
  "All unbelievers on the head;",
  "And then their church, the meek in spirit,",
  "The earth, as promised, shall inherit",
  "From the dead wicked, as heirs male,",
  "Or next remainder-men in tail:",
  "Such ruin shall the Whigs oppress;",
  "Such spoils our Tory friends shall bless:",
  "While Confiscation at command",
  "Shall stalk in terror through the land,",
  "Shall give all whig-estates away,",
  "And call our brethren into play.",
  "",
  "",
  "\"And can you pause, or scruple more?",
  "These things are near you, at the door.",
  "Behold! for though to reasoning blind,",
  "Signs of the times you still might mind,",
  "And view impending fate, as plain",
  "As you'd foretell a shower of rain.",
  "",
  "",
  "\"Hath not heaven warn'd you what must ensue.",
  "And providence declared against you?",
  "Hung forth the dire portents of war",
  "By fires and beacons in the air;",
  "Alarm'd old women all around",
  "With fearful noises under ground,",
  "While earth, for many a hundred leagues,",
  "Groan'd with her dismal load of Whigs?",
  "Was there a meteor, far and wide,",
  "But muster'd on the Tory side;",
  "A star malign, that has not bent",
  "Its aspects for the parliament,",
  "Foreboding your defeat and misery,",
  "As once they fought against old Sisera?",
  "Was there a cloud, that spread the skies,",
  "But bore our armies of allies,",
  "While dreadful hosts of flame stood forth",
  "In baleful streamers from the north?",
  "Which plainly show'd what part they join'd:",
  "For North's the minister, ye mind;",
  "Whence oft your quibblers in gazettes",
  "On Northern blasts have strain'd their wits;",
  "And think you not, the clouds know how",
  "To make the pun, as well you?",
  "Did there arise an apparition,",
  "But grinn'd forth ruin to sedition;",
  "A death-watch, but has join'd our leagues,",
  "And click'd destruction to the Whigs?",
  "Heard ye not, when the wind was fair,",
  "At night our prophets in the air,",
  "Who, loud, like admiralty libel,",
  "Read awful chapters from the Bible,",
  "And war and plague and death denounced,",
  "And told you how you'd soon be trounced?",
  "I see, to join our conq'ring side,",
  "Heaven, earth and hell at once allied;",
  "See from your overthrow and end,",
  "The Tory paradise ascend,",
  "Like that new world, which claims its station,",
  "Beyond the final conflagration.",
  "I see the day, that lots your share",
  "In utter darkness and despair;",
  "The day of joy, when North, our lord,",
  "His faithful fav'rites shall reward.",
  "No Tory then shall set before him",
  "Small wish of 'Squire and Justice Quorum;",
  "But to his unmistaken eyes",
  "See lordships, posts and pensions rise.",
  "",
  "",
  "\"Awake to gladness then, ye Tories!",
  "Th' unbounded prospect lies before us.",
  "The power, display'd in Gage's banners,",
  "Shall cut their fertile lands to manors;",
  "And o'er our happy conquer'd ground,",
  "Dispense estates and titles round.",
  "Behold! the world shall stare at new setts",
  "Of home-made Earls in Massachusetts;",
  "Admire, array'd in ducal tassels,",
  "Your Ol'vers, Hutchinsons and Vassals;",
  "See join'd in ministerial work",
  "His Grace of Albany, and York.",
  "What lordships from each carved estate,",
  "On our New-York Assembly wait!",
  "What titled Jauncys, Gales and Billops;",
  "Lord Brush, Lord Wilkins and Lord Philips!",
  "In wide-sleeved pomp of godly guise,",
  "What solemn rows of Bishops rise!",
  "Aloft a Cardinal's hat is spread",
  "O'er punster Cooper's reverend head.",
  "In Vardell, that poetic zealot,",
  "I view a lawn-bedizen'd Prelate;",
  "While mitres fall, as 'tis their duty,",
  "On heads of Chandler and Auchmuty!",
  "Knights, Viscounts, Barons, shall ye meet,",
  "As thick as pebbles in the street;",
  "E'en I perhaps (heaven speed my claim!)",
  "Shall fix a Sir before my name.",
  "For titles all our foreheads ache,",
  "For what blest changes can they make!",
  "Place Reverence, Grace and Excellence,",
  "Where neither claim'd the least pretence;",
  "Transform by patent's magic words",
  "Men, likest devils, into Lords;",
  "Whence commoners, to Peers translated,",
  "Are justly said to be created.",
  "Now where commissioners you saw,",
  "Shall boards of nobles deal you law;",
  "Long-robed comptrollers judge your rights,",
  "And tide-waiters start up in knights.",
  "While Whigs subdued, in slavish awe,",
  "Our wood shall hew, our water draw,",
  "And bless the mildness, when past hope,",
  "That saved their necks from noose of rope.",
  "For since our leaders have decreed,",
  "Their blacks, who join us, shall be freed,",
  "To hang the conquer'd whigs, we all see,",
  "Would prove but weak, and thriftless policy,",
  "Except their Chiefs: the vulgar knaves",
  "Will do more good, preserved for slaves.\"",
  "",
  "",
  "\"'Tis well,\" Honorius cried; \"your scheme",
  "Has painted out a pretty dream.",
  "We can't confute your second-sight;",
  "We shall be slaves and you a knight.",
  "These things must come, but I divine,",
  "They'll come not in your day, nor mine.",
  "",
  "",
  "\"But, oh my friends, my brethren, hear;",
  "And turn for once th' attentive ear.",
  "Ye see how prompt to aid our woes",
  "The tender mercies of our foes;",
  "Ye see with what unvaried rancour",
  "Still for our blood their minions hanker;",
  "Nor aught can sate their mad ambition,",
  "From us, but death, or worse, submission.",
  "Shall these then riot in our spoil,",
  "Reap the glad harvest of our toil,",
  "Rise from their country's ruins proud,",
  "And roll their chariot-wheels in blood?",
  "See Gage, with inauspicious star,",
  "Has oped the gates of civil war,",
  "When streams of gore, from freemen slain,",
  "Encrimson'd Concord's fatal plain;",
  "Whose warning voice, with awful sound,",
  "Still cries, like Abel's, from the ground;",
  "And heaven, attentive to its call,",
  "Shall doom the proud oppressor's fall.",
  "",
  "",
  "\"Rise then, ere ruin swift surprize,",
  "To victory, to vengeance, rise.",
  "Hark, how the distant din alarms;",
  "The echoing trumpet breathes, to arms.",
  "From provinces remote afar,",
  "The sons of glory rouse to war.",
  "'Tis Freedom calls! the raptured sound",
  "The Apalachian hills rebound.",
  "The Georgian coasts her voice shall hear,",
  "And start from lethargies of fear.",
  "From the parch'd zone, with glowing ray",
  "Where pours the sun intenser day,",
  "To shores where icy waters roll,",
  "And tremble to the glimm'ring pole,",
  "Inspired by freedom's heavenly charms,",
  "United nations wake to arms.",
  "The star of conquest lights their way,",
  "And guides their vengeance on their prey.",
  "Yes, though tyrannic force oppose,",
  "Still shall they triumph o'er their foes;",
  "Till heaven the happy land shall bless",
  "With safety, liberty and peace.",
  "",
  "",
  "\"And ye, whose souls of dastard mould",
  "Start at the bravery of the bold;",
  "To love your country who pretend,",
  "Yet want all spirit to defend;",
  "Who feel your fancies so prolific,",
  "Engend'ring visions whims terrific,",
  "O'errun with horrors of coercion,",
  "Fire, blood and thunder in reversion;",
  "King's standards, pill'ries, confiscations,",
  "And Gage's scare-crow proclamations;",
  "Who scarce could rouse, if caught in fray,",
  "Presence of mind to run away;",
  "See nought but halters rise to view,",
  "In all your dreams, and deem them true;",
  "And while these phantoms haunt your brains,",
  "Bow down your willing necks to chains.",
  "Heavens! are ye sons of sires so great,",
  "Immortal in the fields of fate,",
  "Who braved all deaths, by land or sea,",
  "Who bled, who conquer'd, to be free?",
  "Hence coward souls, the worst disgrace",
  "Of our forefathers' valiant race;",
  "Hie homeward from the glorious field,",
  "There turn the wheel, the distaff wield;",
  "Act what ye are, nor dare to stain",
  "The warrior's arms with touch profane;",
  "There beg your more heroic wives",
  "To guard your own, your children's, lives;",
  "Beneath their aprons seek a screen,",
  "Nor dare to mingle more with men.\"",
  "",
  "",
  "As thus he spake, the Tories' anger",
  "Could now restrain itself no longer;",
  "Who tried before by many a freak, or",
  "Insulting noise, to stop the speaker;",
  "Swung th' un-oil'd hinge of each pew-door,",
  "Their feet kept shuffling on the floor;",
  "Made their disapprobation known",
  "By many a murmur, hum and groan,",
  "That to his speech supplied the place",
  "Of counterpart in thorough bass.",
  "Thus bagpipes, while the tune they breathe,",
  "Still drone and grumble underneath;",
  "And thus the famed Demosthenes",
  "Harangued the rumbling of the seas,",
  "Held forth with elocution grave,",
  "To audience loud of wind and wave;",
  "And had a stiller congregation,",
  "Than Tories are, to hear th' oration.",
  "The uproar now grew high and louder,",
  "As nearer thund'rings of a cloud are,",
  "And every soul with heart and voice",
  "Supplied his quota of the noise.",
  "Each listening ear was set on torture,",
  "Each Tory bellowing, \"Order, Order;\"",
  "And some, with tongue not low or weak,",
  "Were clam'ring fast, for leave to speak;",
  "The Moderator, with great vi'lence,",
  "The cushion thump'd with, \"Silence, Silence!\"",
  "The Constable to every prater",
  "Bawl'd out, \"Pray hear the moderator;\"",
  "Some call'd the vote, and some in turn",
  "Were screaming high, \"Adjourn, Adjourn.\"",
  "Not Chaos heard such jars and clashes,",
  "When all the el'ments fought for places.",
  "The storm each moment fiercer grew;",
  "His sword the great M'Fingal drew,",
  "Prepared in either chance to share,",
  "To keep the peace, or aid the war.",
  "Nor lack'd they each poetic being,",
  "Whom bards alone are skill'd in seeing;",
  "Plumed Victory stood perch'd on high,",
  "Upon the pulpit-canopy,",
  "To join, as is her custom tried,",
  "Like Indians, on the strongest side;",
  "The Destinies, with shears and distaff,",
  "Drew near their threads of life to twist off;",
  "The Furies 'gan to feast on blows,",
  "And broken head, and bloody nose:",
  "When on a sudden from without",
  "Arose a loud terrific shout;",
  "And straight the people all at once heard",
  "Of tongues an universal concert;",
  "Like Æsop's times, as fable runs,",
  "When every creature talk'd at once,",
  "Or like the variegated gabble,",
  "That crazed the carpenters of Babel.",
  "Each party soon forsook the quarrel,",
  "And let the other go on parol,",
  "Eager to know what fearful matter",
  "Had conjured up such general clatter;",
  "And left the church in thin array,",
  "As though it had been lecture-day.",
  "Our 'Squire M'Fingal straitway beckon'd",
  "The Constable to stand his second;",
  "And sallied forth with aspect fierce",
  "The crowd assembled to disperse.",
  "",
  "",
  "The Moderator, out of view,",
  "Beneath the desk had lain perdue;",
  "Peep'd up his head to view the fray,",
  "Beheld the wranglers run away,",
  "And left alone, with solemn face",
  "Adjourn'd them without time or place.",
  ""
]