module.exports = [
  "        \"There are more things in heaven and earth, Horatio,",
  "                Than are dreamt of in your philosophy.\"",
  "                       [_Hamlet,_ Act i. Scene 5, Lines 166, 167.",
  "",
  "_The Scene of the Drama is amongst the Higher Alps--partly in the",
  "         Castle of Manfred, and partly in the Mountains._",
  "",
  "ACT 1.",
  "",
  "SCENE 1.--Manfred _alone_.--_Scene, a Gothic Gallery._--",
  "                        _Time, Midnight._",
  "",
  "_Man_. The lamp must be replenished, but even then",
  "It will not burn so long as I must watch:",
  "My slumbers--if I slumber--are not sleep,",
  "But a continuance, of enduring thought,",
  "Which then I can resist not: in my heart",
  "There is a vigil, and these eyes but close",
  "To look within; and yet I live, and bear",
  "The aspect and the form of breathing men.",
  "But Grief should be the Instructor of the wise;",
  "Sorrow is Knowledge: they who know the most",
  "Must mourn the deepest o'er the fatal truth,",
  "The Tree of Knowledge is not that of Life.",
  "Philosophy and science, and the springs",
  "Of Wonder, and the wisdom of the World,",
  "I have essayed, and in my mind there is",
  "A power to make these subject to itself--",
  "But they avail not: I have done men good,",
  "And I have met with good even among men--",
  "But this availed not: I have had my foes,",
  "And none have baffled, many fallen before me--",
  "But this availed not:--Good--or evil--life--",
  "Powers, passions--all I see in other beings,",
  "Have been to me as rain unto the sands,",
  "Since that all-nameless hour. I have no dread,",
  "And feel the curse to have no natural fear,",
  "Nor fluttering throb, that beats with hopes or wishes,",
  "Or lurking love of something on the earth.",
  "Now to my task.--",
  "                 Mysterious Agency!",
  "Ye Spirits of the unbounded Universe!",
  "Whom I have sought in darkness and in light--",
  "Ye, who do compass earth about, and dwell",
  "In subtler essence--ye, to whom the tops",
  "Of mountains inaccessible are haunts,",
  "And Earth's and Ocean's caves familiar things--",
  "I call upon ye by the written charm",
  "Which gives me power upon you--Rise! Appear!",
  "                                                             [A pause.",
  "They come not yet.--Now by the voice of him",
  "Who is the first among you--by this sign,",
  "Which makes you tremble--by the claims of him",
  "Who is undying,--Rise! Appear!----Appear!",
  "                                                             [A pause.",
  "If it be so.--Spirits of Earth and Air,",
  "Ye shall not so elude me! By a power,",
  "Deeper than all yet urged, a tyrant-spell,",
  "Which had its birthplace in a star condemned,",
  "The burning wreck of a demolished world,",
  "A wandering hell in the eternal Space;",
  "By the strong curse which is upon my Soul,",
  "The thought which is within me and around me,",
  "I do compel ye to my will.--Appear!",
  "",
  "                          First Spirit.",
  "",
  "  Mortal! to thy bidding bowed,",
  "  From my mansion in the cloud,",
  "  Which the breath of Twilight builds,",
  "  And the Summer's sunset gilds",
  "  With the azure and vermilion,",
  "  Which is mixed for my pavilion;",
  "  Though thy quest may be forbidden,",
  "  On a star-beam I have ridden,",
  "  To thine adjuration bowed:",
  "  Mortal--be thy wish avowed!",
  "",
  "                  _Voice of the_ Second Spirit.",
  "",
  "Mont Blanc is the Monarch of mountains;",
  "  They crowned him long ago",
  "On a throne of rocks, in a robe of clouds,",
  "  With a Diadem of snow.",
  "Around his waist are forests braced,",
  "  The Avalanche in his hand;",
  "But ere it fall, that thundering ball",
  "  Must pause for my command.",
  "The Glacier's cold and restless mass",
  "  Moves onward day by day;",
  "But I am he who bids it pass,",
  "  Or with its ice delay.",
  "I am the Spirit of the place,",
  "  Could make the mountain bow",
  "And quiver to his caverned base--",
  "  And what with me would'st _Thou?_",
  "",
  "                   _Voice of the_ Third Spirit.",
  "",
  "In the blue depth of the waters,",
  "  Where the wave hath no strife,",
  "Where the Wind is a stranger,",
  "  And the Sea-snake hath life,",
  "Where the Mermaid is decking",
  "  Her green hair with shells,",
  "Like the storm on the surface",
  "  Came the sound of thy spells;",
  "O'er my calm Hall of Coral",
  "  The deep Echo rolled--",
  "To the Spirit of Ocean",
  "  Thy wishes unfold!",
  "",
  "                          FOURTH SPIRIT.",
  "",
  "Where the slumbering Earthquake",
  "  Lies pillowed on fire,",
  "And the lakes of bitumen",
  "  Rise boilingly higher;",
  "Where the roots of the Andes",
  "  Strike deep in the earth,",
  "As their summits to heaven",
  "  Shoot soaringly forth;",
  "I have quitted my birthplace,",
  "  Thy bidding to bide--",
  "Thy spell hath subdued me,",
  "  Thy will be my guide!",
  "",
  "                          FIFTH SPIRIT.",
  "",
  "I am the Rider of the wind,",
  "  The Stirrer of the storm;",
  "The hurricane I left behind",
  "  Is yet with lightning warm;",
  "To speed to thee, o'er shore and sea",
  "  I swept upon the blast:",
  "The fleet I met sailed well--and yet",
  "  'Twill sink ere night be past.",
  "",
  "                          SIXTH SPIRIT.",
  "",
  "My dwelling is the shadow of the Night,",
  "Why doth thy magic torture me with light?",
  "",
  "                         SEVENTH SPIRIT.",
  "",
  "The Star which rules thy destiny no",
  "Was ruled, ere earth began, by me:",
  "It was a World as fresh and fair",
  "As e'er revolved round Sun in air;",
  "Its course was free and regular,",
  "Space bosomed not a lovelier star.",
  "The Hour arrived--and it became",
  "A wandering mass of shapeless flame,",
  "A pathless Comet, and a curse,",
  "The menace of the Universe;",
  "Still rolling on with innate force,",
  "Without a sphere, without a course,",
  "A bright deformity on high,",
  "The monster of the upper sky!",
  "And Thou! beneath its influence born--",
  "Thou worm! whom I obey and scorn--",
  "Forced by a Power (which is not thine,",
  "And lent thee but to make thee mine)",
  "For this brief moment to descend,",
  "Where these weak Spirits round thee bend",
  "And parley with a thing like thee--",
  "What would'st thou, Child of Clay! with me?",
  "",
  "                       _The_ SEVEN SPIRITS.",
  "",
  "Earth--ocean--air--night--mountains--winds--thy Star,",
  "  Are at thy beck and bidding, Child of Clay!",
  "Before thee at thy quest their Spirits are--",
  "  What would'st thou with us, Son of mortals--say?",
  "",
  "_Man_. Forgetfulness----",
  "",
  "_First Spirit_.            Of what--of whom--and why?",
  "",
  "_Man_. Of that which is within me; read it there--",
  "Ye know it--and I cannot utter it.",
  "",
  "_Spirit_. We can but give thee that which we possess:",
  "Ask of us subjects, sovereignty, the power",
  "O'er earth--the whole, or portion--or a sign",
  "Which shall control the elements, whereof",
  "We are the dominators,--each and all,",
  "These shall be thine.",
  "",
  "_Man_.                Oblivion--self-oblivion!",
  "Can ye not wring from out the hidden realms",
  "Ye offer so profusely--what I ask?",
  "",
  "_Spirit_. It is not in our essence, in our skill;",
  "But--thou may'st die.",
  "",
  "_Man_.                Will Death bestow it on me?",
  "",
  "_Spirit_. We are immortal, and do not forget;",
  "We are eternal; and to us the past",
  "Is, as the future, present. Art thou answered?",
  "",
  "_Man_. Ye mock me--but the Power which brought ye here",
  "Hath made you mine. Slaves, scoff not at my will!",
  "The Mind--the Spirit--the Promethean spark,",
  "The lightning of my being, is as bright,",
  "Pervading, and far darting as your own,",
  "And shall not yield to yours, though cooped in clay!",
  "Answer, or I will teach you what I am.",
  "",
  "_Spirit_. We answer--as we answered; our reply",
  "Is even in thine own words.",
  "",
  "_Man_.                      Why say ye so?",
  "",
  "_Spirit_. If, as thou say'st, thine essence be as ours,",
  "We have replied in telling thee, the thing",
  "Mortals call death hath nought to do with us.",
  "",
  "_Man_. I then have called ye from your realms in vain;",
  "Ye cannot, or ye will not, aid me.",
  "",
  "_Spirit_.                         Say--",
  "What we possess we offer; it is thine:",
  "Bethink ere thou dismiss us; ask again;",
  "Kingdom, and sway, and strength, and length of days--",
  "",
  "_Man_. Accurséd! what have I to do with days?",
  "They are too long already.--Hence--begone!",
  "",
  "_Spirit_. Yet pause: being here, our will would do thee service;",
  "Bethink thee, is there then no other gift",
  "Which we can make not worthless in thine eyes?",
  "",
  "_Man._ No, none: yet stay--one moment, ere we part,",
  "I would behold ye face to face. I hear",
  "Your voices, sweet and melancholy sounds,",
  "As Music on the waters; and I see",
  "The steady aspect of a clear large Star;",
  "But nothing more. Approach me as ye are,",
  "Or one--or all--in your accustomed forms.",
  "",
  "_Spirit_. We have no forms, beyond the elements",
  "Of which we are the mind and principle:",
  "But choose a form--in that we will appear.",
  "",
  "_Man_. I have no choice; there is no form on earth",
  "Hideous or beautiful to me. Let him,",
  "Who is most powerful of ye, take such aspect",
  "As unto him may seem most fitting--Come!",
  "",
  "_Seventh Spirit (appearing in the shape of a beautiful",
  "female figure)_. Behold!",
  "",
  "_Man_.        Oh God! if it be thus, and _thou_",
  "Art not a madness and a mockery,",
  "I yet might be most happy. I will clasp thee,",
  "And we again will be----",
  "                                               [_The figure vanishes._",
  "                        My heart is crushed!",
  "                                           [MANFRED _falls senseless_.",
  "",
  "   (_A voice is heard in the Incantation which follows._)",
  "",
  "    When the Moon is on the wave,",
  "      And the glow-worm in the grass,",
  "    And the meteor on the grave,",
  "      And the wisp on the morass;",
  "    When the falling stars are shooting,",
  "    And the answered owls are hooting,",
  "    And the silent leaves are still",
  "    In the shadow of the hill,",
  "    Shall my soul be upon thine,",
  "    With a power and with a sign.",
  "",
  "    Though thy slumber may be deep,",
  "    Yet thy Spirit shall not sleep;",
  "    There are shades which will not vanish,",
  "    There are thoughts thou canst not banish;",
  "    By a Power to thee unknown,",
  "    Thou canst never be alone;",
  "    Thou art wrapt as with a shroud,",
  "    Thou art gathered in a cloud;",
  "    And for ever shalt thou dwell",
  "    In the spirit of this spell.",
  "",
  "    Though thou seest me not pass by,",
  "    Thou shalt feel me with thine eye",
  "    As a thing that, though unseen,",
  "    Must be near thee, and hath been;",
  "    And when in that secret dread",
  "    Thou hast turned around thy head,",
  "    Thou shalt marvel I am not",
  "    As thy shadow on the spot,",
  "    And the power which thou dost feel",
  "    Shall be what thou must conceal.",
  "",
  "    And a magic voice and verse",
  "    Hath baptized thee with a curse;",
  "    And a Spirit of the air",
  "    Hath begirt thee with a snare;",
  "    In the wind there is a voice",
  "    Shall forbid thee to rejoice;",
  "    And to thee shall Night deny",
  "    All the quiet of her sky;",
  "    And the day shall have a sun,",
  "    Which shall make thee wish it done.",
  "",
  "    From thy false tears I did distil",
  "    An essence which hath strength to kill;",
  "    From thy own heart I then did wring",
  "    The black blood in its blackest spring;",
  "    From thy own smile I snatched the snake,",
  "    For there it coiled as in a brake;",
  "    From thy own lip I drew the charm",
  "    Which gave all these their chiefest harm;",
  "    In proving every poison known,",
  "    I found the strongest was thine own.",
  "",
  "    By the cold breast and serpent smile,",
  "    By thy unfathomed gulfs of guile,",
  "    By that most seeming virtuous eye,",
  "    By thy shut soul's hypocrisy;",
  "    By the perfection of thine art",
  "    Which passed for human thine own heart;",
  "    By thy delight in others' pain,",
  "    And by thy brotherhood of Cain,",
  "    I call upon thee! and compel",
  "    Thyself to be thy proper Hell!",
  "",
  "    And on thy head I pour the vial",
  "    Which doth devote thee to this trial;",
  "    Nor to slumber, nor to die,",
  "    Shall be in thy destiny;",
  "    Though thy death shall still seem near",
  "    To thy wish, but as a fear;",
  "    Lo! the spell now works around thee,",
  "    And the clankless chain hath bound thee;",
  "    O'er thy heart and brain together",
  "    Hath the word been passed--now wither!",
  "",
  "SCENE II.--_The Mountain of the Jungfrau_.--",
  "        _Time, Morning_.--MANFRED _alone upon the cliffs._",
  "",
  "_Man_. The spirits I have raised abandon me,",
  "The spells which I have studied baffle me,",
  "The remedy I recked of tortured me",
  "I lean no more on superhuman aid;",
  "It hath no power upon the past, and for",
  "The future, till the past be gulfed in darkness,",
  "It is not of my search.--My Mother Earth!",
  "And thou fresh-breaking Day, and you, ye Mountains,",
  "Why are ye beautiful? I cannot love ye.",
  "And thou, the bright Eye of the Universe,",
  "That openest over all, and unto all",
  "Art a delight--thou shin'st not on my heart.",
  "And you, ye crags, upon whose extreme edge",
  "I stand, and on the torrent's brink beneath",
  "Behold the tall pines dwindled as to shrubs",
  "In dizziness of distance; when a leap,",
  "A stir, a motion, even a breath, would bring",
  "My breast upon its rocky bosom's bed",
  "To rest for ever--wherefore do I pause?",
  "I feel the impulse--yet I do not plunge;",
  "I see the peril--yet do not recede;",
  "And my brain reels--and yet my foot is firm:",
  "There is a power upon me which withholds,",
  "And makes it my fatality to live,--",
  "If it be life to wear within myself",
  "This barrenness of Spirit, and to be",
  "My own Soul's sepulchre, for I have ceased",
  "To justify my deeds unto myself--",
  "The last infirmity of evil. Aye,",
  "Thou winged and cloud-cleaving minister,",
  "                                                   [_An Eagle passes._",
  "Whose happy flight is highest into heaven,",
  "Well may'st thou swoop so near me--I should be",
  "Thy prey, and gorge thine eaglets; thou art gone",
  "Where the eye cannot follow thee; but thine",
  "Yet pierces downward, onward, or above,",
  "With a pervading vision.--Beautiful!",
  "How beautiful is all this visible world!",
  "How glorious in its action and itself!",
  "But we, who name ourselves its sovereigns, we,",
  "Half dust, half deity, alike unfit",
  "To sink or soar, with our mixed essence make",
  "A conflict of its elements, and breathe",
  "The breath of degradation and of pride,",
  "Contending with low wants and lofty will,",
  "Till our Mortality predominates,",
  "And men are--what they name not to themselves,",
  "And trust not to each other. Hark! the note,",
  "                      [_The Shepherd's pipe in the distance is heard._",
  "The natural music of the mountain reed--",
  "For here the patriarchal days are not",
  "A pastoral fable--pipes in the liberal air,",
  "Mixed with the sweet bells of the sauntering herd;",
  "My soul would drink those echoes. Oh, that I were",
  "The viewless spirit of a lovely sound,",
  "A living voice, a breathing harmony,",
  "A bodiless enjoyment--born and dying",
  "With the blest tone which made me!",
  "",
  "               _Enter from below a_ CHAMOIS HUNTER.",
  "",
  "_Chamois Hunter_.                 Even so",
  "This way the Chamois leapt: her nimble feet",
  "Have baffled me; my gains to-day will scarce",
  "Repay my break-neck travail.--What is here?",
  "Who seems not of my trade, and yet hath reached",
  "A height which none even of our mountaineers,",
  "Save our best hunters, may attain: his garb",
  "Is goodly, his mien manly, and his air",
  "Proud as a free-born peasant's, at this distance:",
  "I will approach him nearer.",
  "",
  "_Man_. (_not perceiving the other_). To be thus--",
  "Grey-haired with anguish, like these blasted pines,",
  "Wrecks of a single winter, barkless, branchless,",
  "A blighted trunk upon a curséd root,",
  "Which but supplies a feeling to Decay--",
  "And to be thus, eternally but thus,",
  "Having been otherwise! Now furrowed o'er",
  "With wrinkles, ploughed by moments, not by years",
  "And hours, all tortured into ages--hours",
  "Which I outlive!--Ye toppling crags of ice!",
  "Ye Avalanches, whom a breath draws down",
  "In mountainous o'erwhelming, come and crush me!",
  "I hear ye momently above, beneath,",
  "Crash with a frequent conflict; but ye pass,",
  "And only fall on things that still would live;",
  "On the young flourishing forest, or the hut",
  "And hamlet of the harmless villager.",
  "",
  "_C. Hun_. The mists begin to rise from up the valley;",
  "I'll warn him to descend, or he may chance",
  "To lose at once his way and life together.",
  "",
  "_Man_. The mists boil up around the glaciers; clouds",
  "Rise curling fast beneath me, white and sulphury,",
  "Like foam from the roused ocean of deep Hell,",
  "Whose every wave breaks on a living shore,",
  "Heaped with the damned like pebbles.--I am giddy.",
  "",
  "_C. Hun_. I must approach him cautiously; if near,",
  "A sudden step will startle him, and he",
  "Seems tottering already.",
  "",
  "_Man_.                  Mountains have fallen,",
  "Leaving a gap in the clouds, and with the shock",
  "Rocking their Alpine brethren; filling up",
  "The ripe green valleys with Destruction's splinters;",
  "Damming the rivers with a sudden dash,",
  "Which crushed the waters into mist, and made",
  "Their fountains find another channel--thus,",
  "Thus, in its old age, did Mount Rosenberg--",
  "Why stood I not beneath it?",
  "",
  "_C. Hun_.                  Friend! have a care,",
  "Your next step may be fatal!--for the love",
  "Of Him who made you, stand not on that brink!",
  "",
  "_Man_. (_not hearing him_).",
  "Such would have been for me a fitting tomb;",
  "My bones had then been quiet in their depth;",
  "They had not then been strewn upon the rocks",
  "For the wind's pastime--as thus--thus they shall be--",
  "In this one plunge.--Farewell, ye opening Heavens!",
  "Look not upon me thus reproachfully--",
  "You were not meant for me--Earth! take these atoms!",
  "",
  "     [_As_ MANFRED _is in act to spring from the cliff, the_",
  "  CHAMOIS HUNTER _seizes and retains him with a sudden grasp._",
  "",
  "_C. Hun_. Hold, madman!--though aweary of thy life,",
  "Stain not our pure vales with thy guilty blood:",
  "Away with me----I will not quit my hold.",
  "",
  "_Man_. I am most sick at heart--nay, grasp me not--",
  "I am all feebleness--the mountains whirl",
  "Spinning around me----I grow blind----What art thou?",
  "",
  "_C. Hun_. I'll answer that anon.--Away with me----",
  "The clouds grow thicker----there--now lean on me--",
  "Place your foot here--here, take this staff, and cling",
  "A moment to that shrub--now give me your hand,",
  "And hold fast by my girdle--softly--well--",
  "The Chalet will be gained within an hour:",
  "Come on, we'll quickly find a surer footing,",
  "And something like a pathway, which the torrent",
  "Hath washed since winter.--Come,'tis bravely done--",
  "You should have been a hunter.--Follow me.",
  "",
  "       [_As they descend the rocks with difficulty, the scene closes._",
  "",
  "ACT II.",
  "",
  "SCENE I.--_A Cottage among the Bernese Alps_.--",
  "                MANFRED _and the_ CHAMOIS HUNTER.",
  "",
  "_C. Hun_. No--no--yet pause--thou must not yet go forth;",
  "Thy mind and body are alike unfit",
  "To trust each other, for some hours, at least;",
  "When thou art better, I will be thy guide--",
  "But whither?",
  "",
  "_Man_.       It imports not: I do know",
  "My route full well, and need no further guidance.",
  "",
  "_C. Hun_. Thy garb and gait bespeak thee of high lineage--",
  "One of the many chiefs, whose castled crags",
  "Look o'er the lower valleys--which of these",
  "May call thee lord? I only know their portals;",
  "My way of life leads me but rarely down",
  "To bask by the huge hearths of those old halls,",
  "Carousing with the vassals; but the paths,",
  "Which step from out our mountains to their doors,",
  "I know from childhood--which of these is thine?",
  "",
  "_Man_. No matter.",
  "",
  "_C. Hun_.         Well, Sir, pardon me the question,",
  "And be of better cheer. Come, taste my wine;",
  "'Tis of an ancient vintage; many a day",
  "'T has thawed my veins among our glaciers, now",
  "Let it do thus for thine--Come, pledge me fairly!",
  "",
  "_Man_. Away, away! there's blood upon the brim!",
  "Will it then never--never sink in the earth?",
  "",
  "_C. Hun_. What dost thou mean? thy senses wander from thee.",
  "",
  "_Man_. I say 'tis blood--my blood! the pure warm stream",
  "Which ran in the veins of my fathers, and in ours",
  "When we were in our youth, and had one heart,",
  "And loved each other as we should not love,",
  "And this was shed: but still it rises up,",
  "Colouring the clouds, that shut me out from Heaven,",
  "Where thou art not--and I shall never be.",
  "",
  "_C. Hun_. Man of strange words, and some half-maddening sin,",
  "Which makes thee people vacancy, whate'er",
  "Thy dread and sufferance be, there's comfort yet--",
  "The aid of holy men, and heavenly patience----",
  "",
  "_Man_. Patience--and patience! Hence--that word was made",
  "For brutes of burthen, not for birds of prey!",
  "Preach it to mortals of a dust like thine,--",
  "I am not of thine order.",
  "",
  "_C. Hun_.                Thanks to Heaven!",
  "I would not be of thine for the free fame",
  "Of William Tell; but whatsoe'er thine ill,",
  "It must be borne, and these wild starts are useless.",
  "",
  "_Man_. Do I not bear it?--Look on me--I live.",
  "",
  "_C. Hun._ This is convulsion, and no healthful life.",
  "",
  "_Man_. I tell thee, man! I have lived many years,",
  "Many long years, but they are nothing now",
  "To those which I must number: ages--ages--",
  "Space and eternity--and consciousness,",
  "With the fierce thirst of death--and still unslaked!",
  "",
  "_C. Hun_. Why on thy brow the seal of middle age",
  "Hath scarce been set; I am thine elder far.",
  "",
  "_Man_. Think'st thou existence doth depend on time?",
  "It doth; but actions are our epochs: mine",
  "Have made my days and nights imperishable,",
  "Endless, and all alike, as sands on the shore,",
  "Innumerable atoms; and one desert,",
  "Barren and cold, on which the wild waves break,",
  "But nothing rests, save carcasses and wrecks,",
  "Rocks, and the salt-surf weeds of bitterness.",
  "",
  "_C. Hun_. Alas! he's mad--but yet I must not leave him.",
  "",
  "_Man_. I would I were--for then the things I see",
  "Would be but a distempered dream.",
  "",
  "_C. Hun_.                         What is it",
  "That thou dost see, or think thou look'st upon?",
  "",
  "_Man_. Myself, and thee--a peasant of the Alps--",
  "Thy humble virtues, hospitable home,",
  "And spirit patient, pious, proud, and free;",
  "Thy self-respect, grafted on innocent thoughts;",
  "Thy days of health, and nights of sleep; thy toils,",
  "By danger dignified, yet guiltless; hopes",
  "Of cheerful old age and a quiet grave,",
  "With cross and garland over its green turf,",
  "And thy grandchildren's love for epitaph!",
  "This do I see--and then I look within--",
  "It matters not--my Soul was scorched already!",
  "",
  "_C. Hun_. And would'st thou then exchange thy lot for mine?",
  "",
  "_Man_. No, friend! I would not wrong thee, nor exchange",
  "My lot with living being: I can bear--",
  "However wretchedly, 'tis still to bear--",
  "In life what others could not brook to dream,",
  "But perish in their slumber.",
  "",
  "_C. Hun_.                    And with this--",
  "This cautious feeling for another's pain,",
  "Canst thou be black with evil?--say not so.",
  "Can one of gentle thoughts have wreaked revenge",
  "Upon his enemies?",
  "",
  "_Man_.             Oh! no, no, no!",
  "My injuries came down on those who loved me--",
  "On those whom I best loved: I never quelled",
  "An enemy, save in my just defence--",
  "But my embrace was fatal.",
  "",
  "_C. Hun_.                Heaven give thee rest!",
  "And Penitence restore thee to thyself;",
  "My prayers shall be for thee.",
  "",
  "_Man_.                        I need them not,",
  "But can endure thy pity. I depart--",
  "'Tis time--farewell!--Here's gold, and thanks for thee--",
  "No words--it is thy due.--Follow me not--",
  "I know my path--the mountain peril's past:",
  "And once again I charge thee, follow not!",
  "                                                      [_Exit_ MANFRED.",
  "",
  "SCENE II.--_A lower Valley in the Alps.--A Cataract_.",
  "",
  "                         _Enter_ MANFRED.",
  "",
  "It is not noon--the Sunbow's rays still arch",
  "The torrent with the many hues of heaven,",
  "And roll the sheeted silver's waving column",
  "O'er the crag's headlong perpendicular,",
  "And fling its lines of foaming light along,",
  "And to and fro, like the pale courser's tail,",
  "The Giant steed, to be bestrode by Death,",
  "As told in the Apocalypse. No eyes",
  "But mine now drink this sight of loveliness;",
  "I should be sole in this sweet solitude,",
  "And with the Spirit of the place divide",
  "The homage of these waters.--I will call her.",
  "",
  "             [MANFRED _takes some of the water into the palm of his",
  "             hand and flings it into the air, muttering the ajuration.",
  "             After a pause, the_ WITCH OF THE ALPS _rises beneath",
  "             the arch of the sunbow of the torrent._",
  "",
  "Beautiful Spirit! with thy hair of light,",
  "And dazzling eyes of glory, in whose form",
  "The charms of Earth's least mortal daughters grow",
  "To an unearthly stature, in an essence",
  "Of purer elements; while the hues of youth,--",
  "Carnationed like a sleeping Infant's cheek,",
  "Rocked by the beating of her mother's heart,",
  "Or the rose tints, which Summer's twilight leaves",
  "Upon the lofty Glacier's virgin snow,",
  "The blush of earth embracing with her Heaven,--",
  "Tinge thy celestial aspect, and make tame",
  "The beauties of the Sunbow which bends o'er thee.",
  "Beautiful Spirit! in thy calm clear brow,",
  "Wherein is glassed serenity of Soul,",
  "Which of itself shows immortality,",
  "I read that thou wilt pardon to a Son",
  "Of Earth, whom the abstruser powers permit",
  "At times to commune with them--if that he",
  "Avail him of his spells--to call thee thus,",
  "And gaze on thee a moment.",
  "",
  "_Witch_.                   Son of Earth!",
  "I know thee, and the Powers which give thee power!",
  "I know thee for a man of many thoughts,",
  "And deeds of good and ill, extreme in both,",
  "Fatal and fated in thy sufferings.",
  "I have expected this--what would'st thou with me?",
  "",
  "_Man_. To look upon thy beauty--nothing further.",
  "The face of the earth hath maddened me, and I",
  "Take refuge in her mysteries, and pierce",
  "To the abodes of those who govern her--",
  "But they can nothing aid me. I have sought",
  "From them what they could not bestow, and now",
  "I search no further.",
  "",
  "_Witch_.             What could be the quest",
  "Which is not in the power of the most powerful,",
  "The rulers of the invisible?",
  "",
  "_Man_.                       A boon;--",
  "But why should I repeat it? 'twere in vain.",
  "",
  "_Witch_. I know not that; let thy lips utter it.",
  "",
  "_Man_. Well, though it torture me, 'tis but the same;",
  "My pang shall find a voice. From my youth upwards",
  "My Spirit walked not with the souls of men,",
  "Nor looked upon the earth with human eyes;",
  "The thirst of their ambition was not mine,",
  "The aim of their existence was not mine;",
  "My joys--my griefs--my passions--and my powers,",
  "Made me a stranger; though I wore the form,",
  "I had no sympathy with breathing flesh,",
  "Nor midst the Creatures of Clay that girded me",
  "Was there but One who--but of her anon.",
  "I said with men, and with the thoughts of men,",
  "I held but slight communion; but instead,",
  "My joy was in the wilderness,--to breathe",
  "The difficult air of the iced mountain's top,",
  "Where the birds dare not build--nor insect's wing",
  "Flit o'er the herbless granite; or to plunge",
  "Into the torrent, and to roll along",
  "On the swift whirl of the new-breaking wave",
  "Of river-stream, or Ocean, in their flow.",
  "In these my early strength exulted; or",
  "To follow through the night the moving moon,",
  "The stars and their development; or catch",
  "The dazzling lightnings till my eyes grew dim;",
  "Or to look, list'ning, on the scattered leaves,",
  "While Autumn winds were at their evening song.",
  "These were my pastimes, and to be alone;",
  "For if the beings, of whom I was one,--",
  "Hating to be so,--crossed me in my path,",
  "I felt myself degraded back to them,",
  "And was all clay again. And then I dived,",
  "In my lone wanderings, to the caves of Death,",
  "Searching its cause in its effect; and drew",
  "From withered bones, and skulls, and heaped up dust",
  "Conclusions most forbidden. Then I passed--",
  "The nights of years in sciences untaught,",
  "Save in the old-time; and with time and toil,",
  "And terrible ordeal, and such penance",
  "As in itself hath power upon the air,",
  "And spirits that do compass air and earth,",
  "Space, and the peopled Infinite, I made",
  "Mine eyes familiar with Eternity,",
  "Such as, before me, did the Magi, and",
  "He who from out their fountain-dwellings raised",
  "Eros and Anteros, at Gadara,",
  "As I do thee;--and with my knowledge grew",
  "The thirst of knowledge, and the power and joy",
  "Of this most bright intelligence, until----",
  "",
  "_Witch_. Proceed.",
  "",
  "_Man_.            Oh! I but thus prolonged my words,",
  "Boasting these idle attributes, because",
  "As I approach the core of my heart's grief--",
  "But--to my task. I have not named to thee",
  "Father or mother, mistress, friend, or being,",
  "With whom I wore the chain of human ties;",
  "If I had such, they seemed not such to me--",
  "Yet there was One----",
  "",
  "_Witch_.                Spare not thyself--proceed.",
  "",
  "_Man_. She was like me in lineaments--her eyes--",
  "Her hair--her features--all, to the very tone",
  "Even of her voice, they said were like to mine;",
  "But softened all, and tempered into beauty:",
  "She had the same lone thoughts and wanderings,",
  "The quest of hidden knowledge, and a mind",
  "To comprehend the Universe: nor these",
  "Alone, but with them gentler powers than mine,",
  "Pity, and smiles, and tears--which I had not;",
  "And tenderness--but that I had for her;",
  "Humility--and that I never had.",
  "Her faults were mine--her virtues were her own--",
  "I loved her, and destroyed her!",
  "",
  "_Witch_.                          With thy hand?",
  "",
  "_Man_. Not with my hand, but heart, which broke her heart;",
  "It gazed on mine, and withered. I have shed",
  "Blood, but not hers--and yet her blood was shed;",
  "I saw--and could not stanch it.",
  "",
  "_Witch_.                         And for this--",
  "A being of the race thou dost despise--",
  "The order, which thine own would rise above,",
  "Mingling with us and ours,--thou dost forego",
  "The gifts of our great knowledge, and shrink'st back",
  "To recreant mortality----Away!",
  "",
  "_Man_. Daughter of Air! I tell thee, since that hour--",
  "But words are breath--look on me in my sleep,",
  "Or watch my watchings--Come and sit by me!",
  "My solitude is solitude no more,",
  "But peopled with the Furies;--I have gnashed",
  "My teeth in darkness till returning morn,",
  "Then cursed myself till sunset;--I have prayed",
  "For madness as a blessing--'tis denied me.",
  "I have affronted Death--but in the war",
  "Of elements the waters shrunk from me,",
  "And fatal things passed harmless; the cold hand",
  "Of an all-pitiless Demon held me back,",
  "Back by a single hair, which would not break.",
  "In Fantasy, Imagination, all",
  "The affluence of my soul--which one day was",
  "A Croesus in creation--I plunged deep,",
  "But, like an ebbing wave, it dashed me back",
  "Into the gulf of my unfathomed thought.",
  "I plunged amidst Mankind--Forgetfulness",
  "I sought in all, save where 'tis to be found--",
  "And that I have to learn--my Sciences,",
  "My long pursued and superhuman art,",
  "Is mortal here: I dwell in my despair--",
  "And live--and live for ever.",
  "",
  "_Witch_.                     It may be",
  "That I can aid thee.",
  "",
  "_Man_.               To do this thy power",
  "Must wake the dead, or lay me low with them.",
  "Do so--in any shape--in any hour--",
  "With any torture--so it be the last.",
  "",
  "_Witch_. That is not in my province; but if thou",
  "Wilt swear obedience to my will, and do",
  "My bidding, it may help thee to thy wishes.",
  "",
  "_Man_. I will not swear--Obey! and whom? the Spirits",
  "Whose presence I command, and be the slave",
  "Of those who served me--Never!",
  "",
  "_Witch_.                       Is this all?",
  "Hast thou no gentler answer?--Yet bethink thee,",
  "And pause ere thou rejectest.",
  "",
  "_Man_.                       I have said it.",
  "",
  "_Witch_. Enough! I may retire then--say!",
  "",
  "_Man_.                                       Retire!",
  "",
  "                                            [_The_ WITCH _disappears._",
  "",
  "_Man_. (_alone_). We are the fools of Time and Terror: Days",
  "Steal on us, and steal from us; yet we live,",
  "Loathing our life, and dreading still to die.",
  "In all the days of this detested yoke--",
  "This vital weight upon the struggling heart,",
  "Which sinks with sorrow, or beats quick with pain,",
  "Or joy that ends in agony or faintness--",
  "In all the days of past and future--for",
  "In life there is no present--we can number",
  "How few--how less than few--wherein the soul",
  "Forbears to pant for death, and yet draws back",
  "As from a stream in winter, though the chill",
  "Be but a moment's. I have one resource",
  "Still in my science--I can call the dead,",
  "And ask them what it is we dread to be:",
  "The sternest answer can but be the Grave,",
  "And that is nothing: if they answer not--",
  "The buried Prophet answered to the Hag",
  "Of Endor; and the Spartan Monarch drew",
  "From the Byzantine maid's unsleeping spirit",
  "An answer and his destiny--he slew",
  "That which he loved, unknowing what he slew,",
  "And died unpardoned--though he called in aid",
  "The Phyxian Jove, and in Phigalia roused",
  "The Arcadian Evocators to compel",
  "The indignant shadow to depose her wrath,",
  "Or fix her term of vengeance--she replied",
  "In words of dubious import, but fulfilled.",
  "If I had never lived, that which I love",
  "Had still been living; had I never loved,",
  "That which I love would still be beautiful,",
  "Happy and giving happiness. What is she?",
  "What is she now?--a sufferer for my sins--",
  "A thing I dare not think upon--or nothing.",
  "Within few hours I shall not call in vain--",
  "Yet in this hour I dread the thing I dare:",
  "Until this hour I never shrunk to gaze",
  "On spirit, good or evil--now I tremble,",
  "And feel a strange cold thaw upon my heart.",
  "But I can act even what I most abhor,",
  "And champion human fears.--The night approaches.",
  "                                                              [_Exit._",
  "",
  "SCENE III.--_The summit of the Jungfrau Mountain._",
  "",
  "                      _Enter_ FIRST DESTINY.",
  "",
  "The Moon is rising broad, and round, and bright;",
  "And here on snows, where never human foot",
  "Of common mortal trod, we nightly tread,",
  "And leave no traces: o'er the savage sea,",
  "The glassy ocean of the mountain ice,",
  "We skim its rugged breakers, which put on",
  "The aspect of a tumbling tempest's foam,",
  "Frozen in a moment--a dead Whirlpool's image:",
  "And this most steep fantastic pinnacle,",
  "The fretwork of some earthquake--where the clouds",
  "Pause to repose themselves in passing by--",
  "Is sacred to our revels, or our vigils;",
  "Here do I wait my sisters, on our way",
  "To the Hall of Arimanes--for to-night",
  "Is our great festival--'tis strange they come not.",
  "",
  "                   _A Voice without, singing._",
  "",
  "          The Captive Usurper,",
  "            Hurled down from the throne,",
  "          Lay buried in torpor,",
  "            Forgotten and lone;",
  "          I broke through his slumbers,",
  "            I shivered his chain,",
  "          I leagued him with numbers--",
  "            He's Tyrant again!",
  "With the blood of a million he'll answer my care,",
  "With a Nation's destruction--his flight and despair!",
  "",
  "                     _Second Voice, without._",
  "",
  "The Ship sailed on, the Ship sailed fast,",
  "But I left not a sail, and I left not a mast;",
  "There is not a plank of the hull or the deck,",
  "And there is not a wretch to lament o'er his wreck;",
  "Save one, whom I held, as he swam, by the hair,",
  "And he was a subject well worthy my care;",
  "A traitor on land, and a pirate at sea--",
  "But I saved him to wreak further havoc for me!",
  "",
  "                   FIRST DESTINY, _answering._",
  "",
  "      The City lies sleeping;",
  "        The morn, to deplore it,",
  "      May dawn on it weeping:",
  "        Sullenly, slowly,",
  "      The black plague flew o'er it--",
  "        Thousands lie lowly;",
  "      Tens of thousands shall perish;",
  "        The living shall fly from",
  "      The sick they should cherish;",
  "        But nothing can vanquish",
  "      The touch that they die from.",
  "        Sorrow and anguish,",
  "      And evil and dread,",
  "        Envelope a nation;",
  "      The blest are the dead,",
  "      Who see not the sight",
  "        Of their own desolation;",
  "      This work of a night--",
  "This wreck of a realm--this deed of my doing--",
  "For ages I've done, and shall still be renewing!",
  "",
  "            _Enter the_ SECOND _and_ THIRD DESTINIES.",
  "",
  "                           _The Three._",
  "",
  "Our hands contain the hearts of men,",
  "  Our footsteps are their graves;",
  "We only give to take again",
  "  The Spirits of our slaves!",
  "",
  "_First Des_. Welcome!--Where's Nemesis?",
  "",
  "_Second Des_.                          At some great work;",
  "But what I know not, for my hands were full.",
  "",
  "_Third Des_. Behold she cometh.",
  "",
  "                         _Enter_ NEMESIS.",
  "",
  "_First Des_.                     Say, where hast thou been?",
  "My Sisters and thyself are slow to-night.",
  "",
  "_Nem_. I was detained repairing shattered thrones--",
  "Marrying fools, restoring dynasties--",
  "Avenging men upon their enemies,",
  "And making them repent their own revenge;",
  "Goading the wise to madness; from the dull",
  "Shaping out oracles to rule the world",
  "Afresh--for they were waxing out of date,",
  "And mortals dared to ponder for themselves,",
  "To weigh kings in the balance--and to speak",
  "Of Freedom, the forbidden fruit.--Away!",
  "We have outstayed the hour--mount we our clouds!",
  "                                                            [_Exeunt._",
  "",
  "SCENE IV.--_The Hall of Arimanes._--_Arimanes on his Throne,",
  "        a Globe of Fire, surrounded by the Spirits._",
  "",
  "                      _Hymn of the_ SPIRITS.",
  "",
  "Hail to our Master!--Prince of Earth and Air!",
  "  Who walks the clouds and waters--in his hand",
  "The sceptre of the Elements, which tear",
  "  Themselves to chaos at his high command!",
  "He breatheth--and a tempest shakes the sea;",
  "  He speaketh--and the clouds reply in thunder;",
  "He gazeth--from his glance the sunbeams flee;",
  "  He moveth--Earthquakes rend the world asunder.",
  "Beneath his footsteps the Volcanoes rise;",
  "  His shadow is the Pestilence: his path",
  "The comets herald through the crackling skies;",
  "  And Planets turn to ashes at his wrath.",
  "To him War offers daily sacrifice;",
  "  To him Death pays his tribute; Life is his,",
  "With all its Infinite of agonies--",
  "  And his the Spirit of whatever is!",
  "",
  "               _Enter the_ DESTINIES _and_ NEMESIS.",
  "",
  "_First Des_. Glory to Arimanes! on the earth",
  "His power increaseth--both my sisters did",
  "His bidding, nor did I neglect my duty!",
  "",
  "_Second Des_. Glory to Arimanes! we who bow",
  "The necks of men, bow down before his throne!",
  "",
  "_Third Des_. Glory to Arimanes! we await",
  "His nod!",
  "",
  "_Nem_.    Sovereign of Sovereigns! we are thine,",
  "And all that liveth, more or less, is ours,",
  "And most things wholly so; still to increase",
  "Our power, increasing thine, demands our care,",
  "And we are vigilant. Thy late commands",
  "Have been fulfilled to the utmost.",
  "",
  "                         _Enter_ MANFRED.",
  "",
  "_A Spirit_.                         What is here?",
  "A mortal!--Thou most rash and fatal wretch,",
  "Bow down and worship!",
  "",
  "_Second Spirit_.              I do know the man--",
  "A Magian of great power, and fearful skill!",
  "",
  "_Third Spirit_. Bow down and worship, slave!--What, know'st thou not",
  "Thine and our Sovereign?--Tremble, and obey!",
  "",
  "_All the Spirits_. Prostrate thyself, and thy condemnéd clay,",
  "Child of the Earth! or dread the worst.",
  "",
  "_Man_.                                   I know it;",
  "And yet ye see I kneel not.",
  "",
  "_Fourth Spirit_.             'Twill be taught thee.",
  "",
  "_Man_. 'Tis taught already;--many a night on the earth,",
  "On the bare ground, have I bowed down my face,",
  "And strewed my head with ashes; I have known",
  "The fulness of humiliation--for",
  "I sunk before my vain despair, and knelt",
  "To my own desolation.",
  "",
  "_Fifth Spirit_.         Dost thou dare",
  "Refuse to Arimanes on his throne",
  "What the whole earth accords, beholding not",
  "The terror of his Glory?--Crouch! I say.",
  "",
  "_Man_. Bid _him_ bow down to that which is above him,",
  "The overruling Infinite--the Maker",
  "Who made him not for worship--let him kneel,",
  "And we will kneel together.",
  "",
  "_The Spirits_.               Crush the worm!",
  "Tear him in pieces!--",
  "",
  "_First Des_.            Hence! Avaunt!--he's mine.",
  "Prince of the Powers invisible! This man",
  "Is of no common order, as his port",
  "And presence here denote: his sufferings",
  "Have been of an immortal nature--like",
  "Our own; his knowledge, and his powers and will,",
  "As far as is compatible with clay,",
  "Which clogs the ethereal essence, have been such",
  "As clay hath seldom borne; his aspirations",
  "Have been beyond the dwellers of the earth,",
  "And they have only taught him what we know--",
  "That knowledge is not happiness, and science",
  "But an exchange of ignorance for that",
  "Which is another kind of ignorance.",
  "This is not all--the passions, attributes",
  "Of Earth and Heaven, from which no power, nor being,",
  "Nor breath from the worm upwards is exempt,",
  "Have pierced his heart; and in their consequence",
  "Made him a thing--which--I who pity not,",
  "Yet pardon those who pity. He is mine--",
  "And thine it may be; be it so, or not--",
  "No other Spirit in this region hath",
  "A soul like his--or power upon his soul.",
  "",
  "_Nem_. What doth he here then?",
  "",
  "_First Des_.                   Let _him_ answer that.",
  "",
  "_Man_. Ye know what I have known; and without power",
  "I could not be amongst ye: but there are",
  "Powers deeper still beyond--I come in quest",
  "Of such, to answer unto what I seek.",
  "",
  "_Nem_. What would'st thou?",
  "",
  "_Man_.                     _Thou_ canst not reply to me.",
  "Call up the dead--my question is for them.",
  "",
  "_Nem_. Great Arimanes, doth thy will avouch",
  "The wishes of this mortal?",
  "",
  "_Ari_.                       Yea.",
  "",
  "_Nem_.                            Whom wouldst thou",
  "Uncharnel?",
  "",
  "_Man_.      One without a tomb--call up",
  "Astarte.",
  "",
  "                             NEMESIS.",
  "",
  "          Shadow! or Spirit!",
  "            Whatever thou art,",
  "          Which still doth inherit",
  "            The whole or a part",
  "          Of the form of thy birth,",
  "            Of the mould of thy clay,",
  "          Which returned to the earth,",
  "            Re-appear to the day!",
  "          Bear what thou borest,",
  "            The heart and the form,",
  "          And the aspect thou worest",
  "            Redeem from the worm.",
  "        Appear!--Appear!--Appear!",
  "        Who sent thee there requires thee here!",
  "",
  "            [_The Phantom of_ ASTARTE _rises and stands in the midst_.",
  "",
  "_Man_. Can this be death? there's bloom upon her cheek;",
  "But now I see it is no living hue,",
  "But a strange hectic--like the unnatural red",
  "Which Autumn plants upon the perished leaf.",
  "It is the same! Oh, God! that I should dread",
  "To look upon the same--Astarte!--No,",
  "I cannot speak to her--but bid her speak--",
  "Forgive me or condemn me.",
  "",
  "                             NEMESIS.",
  "",
  "        By the Power which hath broken",
  "          The grave which enthralled thee,",
  "        Speak to him who hath spoken.",
  "          Or those who have called thee!",
  "",
  "_Man_.                      She is silent,",
  "And in that silence I am more than answered.",
  "",
  "_Nem_. My power extends no further. Prince of Air!",
  "It rests with thee alone--command her voice.",
  "",
  "_Ari_. Spirit--obey this sceptre!",
  "",
  "_Nem_.                            Silent still!",
  "She is not of our order, but belongs",
  "To the other powers. Mortal! thy quest is vain,",
  "And we are baffled also.",
  "",
  "_Man_.                  Hear me, hear me--",
  "Astarte! my belovéd! speak to me:",
  "I have so much endured--so much endure--",
  "Look on me! the grave hath not changed thee more",
  "Than I am changed for thee. Thou lovedst me",
  "Too much, as I loved thee: we were not made",
  "To torture thus each other--though it were",
  "The deadliest sin to love as we have loved.",
  "Say that thou loath'st me not--that I do bear",
  "This punishment for both--that thou wilt be",
  "One of the blesséd--and that I shall die;",
  "For hitherto all hateful things conspire",
  "To bind me in existence--in a life",
  "Which makes me shrink from Immortality--",
  "A future like the past. I cannot rest.",
  "I know not what I ask, nor what I seek:",
  "I feel but what thou art, and what I am;",
  "And I would hear yet once before I perish",
  "The voice which was my music--Speak to me!",
  "For I have called on thee in the still night,",
  "Startled the slumbering birds from the hushed boughs,",
  "And woke the mountain wolves, and made the caves",
  "Acquainted with thy vainly echoed name,",
  "Which answered me--many things answered me--",
  "Spirits and men--but thou wert silent all.",
  "Yet speak to me! I have outwatched the stars,",
  "And gazed o'er heaven in vain in search of thee.",
  "Speak to me! I have wandered o'er the earth,",
  "And never found thy likeness--Speak to me!",
  "Look on the fiends around--they feel for me:",
  "I fear them not, and feel for thee alone.",
  "Speak to me! though it be in wrath;--but say--",
  "I reck not what--but let me hear thee once--",
  "This once--once more!",
  "",
  "_Phantom of Astarte_.   Manfred!",
  "",
  "_Man_.                           Say on, say on--",
  "I live but in the sound--it is thy voice!",
  "",
  "_Phan_. Manfred! To-morrow ends thine earthly ills.",
  "Farewell!",
  "",
  "_Man_.    Yet one word more--am I forgiven?",
  "",
  "_Phan_. Farewell!",
  "",
  "_Man_.            Say, shall we meet again?",
  "",
  "_Phan_.                                    Farewell!",
  "",
  "_Man_. One word for mercy! Say thou lovest me.",
  "",
  "_Phan_. Manfred!",
  "",
  "                                [_The Spirit of_ ASTARTE _disappears_.",
  "",
  "_Nem_.           She's gone, and will not be recalled:",
  "Her words will be fulfilled. Return to the earth.",
  "",
  "_A Spirit_. He is convulsed--This is to be a mortal,",
  "And seek the things beyond mortality.",
  "",
  "_Another Spirit_. Yet, see, he mastereth himself, and makes",
  "His torture tributary to his will.",
  "Had he been one of us, he would have made",
  "An awful Spirit.",
  "",
  "_Nem_.           Hast thou further question",
  "Of our great Sovereign, or his worshippers?",
  "",
  "_Man_. None.",
  "",
  "_Nem_.       Then for a time farewell.",
  "",
  "_Man_. We meet then! Where? On the earth?--",
  "Even as thou wilt: and for the grace accorded",
  "I now depart a debtor. Fare ye well!",
  "                                                      [_Exit_ MANFRED.",
  "",
  "                        (_Scene closes_.)",
  "",
  "ACT III.",
  "",
  "SCENE I.--_A Hall in the Castle of Manfred_.",
  "",
  "                      MANFRED _and_ HERMAN.",
  "",
  "_Man_. What is the hour?",
  "",
  "_Her_.                   It wants but one till sunset,",
  "And promises a lovely twilight.",
  "",
  "_Man_.                          Say,",
  "Are all things so disposed of in the tower",
  "As I directed?",
  "",
  "_Her_.        All, my Lord, are ready:",
  "Here is the key and casket.",
  "",
  "_Man_.                        It is well:",
  "Thou mayst retire.                                     [_Exit_ HERMAN.",
  "",
  "_Man_. (_alone_).     There is a calm upon me--",
  "Inexplicable stillness! which till now",
  "Did not belong to what I knew of life.",
  "If that I did not know Philosophy",
  "To be of all our vanities the motliest,",
  "The merest word that ever fooled the ear",
  "From out the schoolman's jargon, I should deem",
  "The golden secret, the sought \"Kalon,\" found,",
  "And seated in my soul. It will not last,",
  "But it is well to have known it, though but once:",
  "It hath enlarged my thoughts with a new sense,",
  "And I within my tablets would note down",
  "That there is such a feeling. Who is there?",
  "",
  "                        _Re-enter_ HERMAN.",
  "",
  "_Her_. My Lord, the Abbot of St. Maurice craves",
  "To greet your presence.",
  "",
  "                _Enter the_ ABBOT OF ST. MAURICE.",
  "",
  "_Abbot_.                 Peace be with Count Manfred!",
  "",
  "_Man_. Thanks, holy father! welcome to these walls;",
  "Thy presence honours them, and blesseth those",
  "Who dwell within them.",
  "",
  "_Abbot_.              Would it were so, Count!--",
  "But I would fain confer with thee alone.",
  "",
  "_Man_. Herman, retire.--What would my reverend guest?",
  "",
  "_Abbot_. Thus, without prelude:--Age and zeal--my office--",
  "And good intent must plead my privilege;",
  "Our near, though not acquainted neighbourhood,",
  "May also be my herald. Rumours strange,",
  "And of unholy nature, are abroad,",
  "And busy with thy name--a noble name",
  "For centuries: may he who bears it now",
  "Transmit it unimpaired!",
  "",
  "_Man_.                  Proceed,--I listen.",
  "",
  "_Abbot_. 'Tis said thou holdest converse with the things",
  "Which are forbidden to the search of man;",
  "That with the dwellers of the dark abodes,",
  "The many evil and unheavenly spirits",
  "Which walk the valley of the Shade of Death,",
  "Thou communest. I know that with mankind,",
  "Thy fellows in creation, thou dost rarely",
  "Exchange thy thoughts, and that thy solitude",
  "Is as an Anchorite's--were it but holy.",
  "",
  "_Man_. And what are they who do avouch these things?",
  "",
  "_Abbot_. My pious brethren--the scaréd peasantry--",
  "Even thy own vassals--who do look on thee",
  "With most unquiet eyes. Thy life's in peril!",
  "",
  "_Man_. Take it.",
  "",
  "_Abbot_.        I come to save, and not destroy:",
  "I would not pry into thy secret soul;",
  "But if these things be sooth, there still is time",
  "For penitence and pity: reconcile thee",
  "With the true church, and through the church to Heaven.",
  "",
  "_Man_. I hear thee. This is my reply--whate'er",
  "I may have been, or am, doth rest between",
  "Heaven and myself--I shall not choose a mortal",
  "To be my mediator--Have I sinned",
  "Against your ordinances? prove and punish!",
  "",
  "_Abbot_. My son! I did not speak of punishment,",
  "But penitence and pardon;--with thyself",
  "The choice of such remains--and for the last,",
  "Our institutions and our strong belief",
  "Have given me power to smooth the path from sin",
  "To higher hope and better thoughts; the first",
  "I leave to Heaven,--\"Vengeance is mine alone!\"",
  "So saith the Lord, and with all humbleness",
  "His servant echoes back the awful word.",
  "",
  "_Man_. Old man! there is no power in holy men,",
  "Nor charm in prayer, nor purifying form",
  "Of penitence, nor outward look, nor fast,",
  "Nor agony--nor, greater than all these,",
  "The innate tortures of that deep Despair,",
  "Which is Remorse without the fear of Hell,",
  "But all in all sufficient to itself",
  "Would make a hell of Heaven--can exorcise",
  "From out the unbounded spirit the quick sense",
  "Of its own sins--wrongs--sufferance--and revenge",
  "Upon itself; there is no future pang",
  "Can deal that justice on the self--condemned",
  "He deals on his own soul.",
  "",
  "_Abbot_.                 All this is well;",
  "For this will pass away, and be succeeded",
  "By an auspicious hope, which shall look up",
  "With calm assurafice to that blessed place,",
  "Which all who seek may win, whatever be",
  "Their earthly errors, so they be atoned:",
  "And the commencement of atonement is",
  "The sense of its necessity. Say on--",
  "And all our church can teach thee shall be taught;",
  "And all we can absolve thee shall be pardoned.",
  "",
  "_Man_. When Rome's sixth Emperor was near his last,",
  "The victim of a self-inflicted wound,",
  "To shun the torments of a public death",
  "From senates once his slaves, a certain soldier,",
  "With show of loyal pity, would have stanched",
  "The gushing throat with his officious robe;",
  "The dying Roman thrust him back, and said--",
  "Some empire still in his expiring glance--",
  "\"It is too late--is this fidelity?\"",
  "",
  "_Abbot_. And what of this?",
  "",
  "_Man_.                     I answer with the Roman--",
  "\"It is too late!\"",
  "",
  "_Abbot_.           It never can be so,",
  "To reconcile thyself with thy own soul,",
  "And thy own soul with Heaven. Hast thou no hope?",
  "'Tis strange--even those who do despair above,",
  "Yet shape themselves some fantasy on earth,",
  "To which frail twig they cling, like drowning men.",
  "",
  "_Man_. Aye--father! I have had those early visions,",
  "And noble aspirations in my youth,",
  "To make my own the mind of other men,",
  "The enlightener of nations; and to rise",
  "I knew not whither--it might be to fall;",
  "But fall, even as the mountain-cataract,",
  "Which having leapt from its more dazzling height,",
  "Even in the foaming strength of its abyss,",
  "(Which casts up misty columns that become",
  "Clouds raining from the re-ascended skies,)",
  "Lies low but mighty still.--But this is past,",
  "My thoughts mistook themselves.",
  "",
  "_Abbot_.                         And wherefore so?",
  "",
  "_Man_.I could not tame my nature down; for he",
  "Must serve who fain would sway; and soothe, and sue,",
  "And watch all time, and pry into all place,",
  "And be a living Lie, who would become",
  "A mighty thing amongst the mean--and such",
  "The mass are; I disdained to mingle with",
  "A herd, though to be leader--and of wolves,",
  "The lion is alone, and so am I.",
  "",
  "_Abbot_. And why not live and act with other men?",
  "",
  "_Man_. Because my nature was averse from life;",
  "And yet not cruel; for I would not make,",
  "But find a desolation. Like the Wind,",
  "The red-hot breath of the most lone Simoom,",
  "Which dwells but in the desert, and sweeps o'er",
  "The barren sands which bear no shrubs to blast,",
  "And revels o'er their wild and arid waves,",
  "And seeketh not, so that it is not sought,",
  "But being met is deadly,--such hath been",
  "The course of my existence; but there came",
  "Things in my path which are no more.",
  "",
  "_Abbot_.                             Alas!",
  "I 'gin to fear that thou art past all aid",
  "From me and from my calling; yet so young,",
  "I still would----",
  "",
  "_Man_.              Look on me! there is an order",
  "Of mortals on the earth, who do become",
  "Old in their youth, and die ere middle age,",
  "Without the violence of warlike death;",
  "Some perishing of pleasure--some of study--",
  "Some worn with toil, some of mere weariness,--",
  "Some of disease--and some insanity--",
  "And some of withered, or of broken hearts;",
  "For this last is a malady which slays",
  "More than are numbered in the lists of Fate,",
  "Taking all shapes, and bearing many names.",
  "Look upon me! for even of all these things",
  "Have I partaken; and of all these things,",
  "One were enough; then wonder not that I",
  "Am what I am, but that I ever was,",
  "Or having been, that I am still on earth.",
  "",
  "_Abbot_. Yet, hear me still--",
  "",
  "_Man_.                        Old man! I do respect",
  "Thine order, and revere thine years; I deem",
  "Thy purpose pious, but it is in vain:",
  "Think me not churlish; I would spare thyself,",
  "Far more than me, in shunning at this time",
  "All further colloquy--and so--farewell.",
  "                                                        [Exit MANFRED.",
  "",
  "_Abbot_. This should have been a noble creature: he",
  "Hath all the energy which would have made",
  "A goodly frame of glorious elements,",
  "Had they been wisely mingled; as it is,",
  "It is an awful chaos--Light and Darkness--",
  "And mind and dust--and passions and pure thoughts",
  "Mixed, and contending without end or order,--",
  "All dormant or destructive. He will perish--",
  "And yet he must not--I will try once more,",
  "For such are worth redemption; and my duty",
  "Is to dare all things for a righteous end.",
  "I'll follow him--but cautiously, though surely.",
  "                                                          [Exit ABBOT.",
  "",
  "SCENE II.--_Another Chamber_.",
  "",
  "                      MANFRED _and_ HERMAN.",
  "",
  "_Her_. My lord, you bade me wait on you at sunset:",
  "He sinks behind the mountain.",
  "",
  "_Man_.                        Doth he so?",
  "I will look on him.",
  "                        [MANFRED _advances to the Window of the Hall_.",
  "                    Glorious Orb! the idol",
  "Of early nature, and the vigorous race",
  "Of undiseased mankind, the giant sons",
  "Of the embrace of Angels, with a sex",
  "More beautiful than they, which did draw down",
  "The erring Spirits who can ne'er return.--",
  "Most glorious Orb! that wert a worship, ere",
  "The mystery of thy making was revealed!",
  "Thou earliest minister of the Almighty,",
  "Which gladdened, on their mountain tops, the hearts",
  "Of the Chaldean shepherds, till they poured",
  "Themselves in orisons! Thou material God!",
  "And representative of the Unknown--",
  "Who chose thee for his shadow! Thou chief Star!",
  "Centre of many stars! which mak'st our earth",
  "Endurable and temperest the hues",
  "And hearts of all who walk within thy rays!",
  "Sire of the seasons! Monarch of the climes,",
  "And those who dwell in them! for near or far,",
  "Our inborn spirits have a tint of thee",
  "Even as our outward aspects;--thou dost rise,",
  "And shine, and set in glory. Fare thee well!",
  "I ne'er shall see thee more. As my first glance",
  "Of love and wonder was for thee, then take",
  "My latest look: thou wilt not beam on one",
  "To whom the gifts of life and warmth have been",
  "Of a more fatal nature. He is gone--",
  "I follow.                                             [_Exit_ MANFRED.",
  "",
  "SCENE III.--_The Mountains_--_The Castle of Manfred at some",
  "    distance_--_A Terrace before a Tower_.--_Time, Twilight_.",
  "",
  "        HERMAN, MANUEL, _and other dependants of_ MANFRED.",
  "",
  "_Her_. 'Tis strange enough! night after night, for years,",
  "He hath pursued long vigils in this tower,",
  "Without a witness. I have been within it,--",
  "So have we all been oft-times; but from it,",
  "Or its contents, it were impossible",
  "To draw conclusions absolute, of aught",
  "His studies tend to. To be sure, there is",
  "One chamber where none enter: I would give",
  "The fee of what I have to come these three years,",
  "To pore upon its mysteries.",
  "",
  "_Manuel_.                  'Twere dangerous;",
  "Content thyself with what thou know'st already.",
  "",
  "_Her_. Ah! Manuel! thou art elderly and wise,",
  "And couldst say much; thou hast dwelt within the castle--",
  "How many years is't?",
  "",
  "_Manuel_.            Ere Count Manfred's birth,",
  "I served his father, whom he nought resembles.",
  "",
  "_Her_. There be more sons in like predicament!",
  "But wherein do they differ?",
  "",
  "_Manuel_.                   I speak not",
  "Of features or of form, but mind and habits;",
  "Count Sigismund was proud, but gay and free,--",
  "A warrior and a reveller; he dwelt not",
  "With books and solitude, nor made the night",
  "A gloomy vigil, but a festal time,",
  "Merrier than day; he did not walk the rocks",
  "And forests like a wolf, nor turn aside",
  "From men and their delights.",
  "",
  "_Her_.                       Beshrew the hour,",
  "But those were jocund times! I would that such",
  "Would visit the old walls again; they look",
  "As if they had forgotten them.",
  "",
  "_Manuel_.                      These walls",
  "Must change their chieftain first. Oh! I have seen",
  "Some strange things in them, Herman.",
  "",
  "_Her_.                               Come, be friendly;",
  "Relate me some to while away our watch:",
  "I've heard thee darkly speak of an event",
  "Which happened hereabouts, by this same tower.",
  "",
  "_Manuel_. That was a night indeed! I do remember",
  "'Twas twilight, as it may be now, and such",
  "Another evening:--yon red cloud, which rests",
  "On Eigher's pinnacle, so rested then,--",
  "So like that it might be the same; the wind",
  "Was faint and gusty, and the mountain snows",
  "Began to glitter with the climbing moon;",
  "Count Manfred was, as now, within his tower,--",
  "How occupied, we knew not, but with him",
  "The sole companion of his wanderings",
  "And watchings--her, whom of all earthly things",
  "That lived, the only thing he seemed to love,--",
  "As he, indeed, by blood was bound to do,",
  "The Lady Astarte, his----",
  "                          Hush! who comes here?",
  "",
  "                        _Enter the_ ABBOT.",
  "",
  "_Abbot_. Where is your master?",
  "",
  "_Her_.                          Yonder in the tower.",
  "",
  "_Abbot_. I must speak with him.",
  "",
  "_Manuel_.                       'Tis impossible;",
  "He is most private, and must not be thus",
  "Intruded on.",
  "",
  "_Abbot_.      Upon myself I take",
  "The forfeit of my fault, if fault there be--",
  "But I must see him.",
  "",
  "_Her_.              Thou hast seen him once",
  "his eve already.",
  "",
  "_Abbot_.          Herman! I command thee,",
  "Knock, and apprize the Count of my approach.",
  "",
  "_Her_. We dare not.",
  "",
  "_Abbot_.            Then it seems I must be herald",
  "Of my own purpose.",
  "",
  "_Manuel_.          Reverend father, stop--",
  "I pray you pause.",
  "",
  "_Abbot_.          Why so?",
  "",
  "_Manuel_.                 But step this way,",
  "And I will tell you further.                                [_Exeunt_.",
  "",
  "SCENE IV.--_Interior of the Tower_.",
  "",
  "                         MANFRED _alone_.",
  "",
  "The stars are forth, the moon above the tops",
  "Of the snow-shining mountains.--Beautiful!",
  "I linger yet with Nature, for the Night",
  "Hath been to me a more familiar face",
  "Than that of man; and in her starry shade",
  "Of dim and solitary loveliness,",
  "I learned the language of another world.",
  "I do remember me, that in my youth,",
  "When I was wandering,--upon such a night",
  "I stood within the Coliseum's wall,",
  "'Midst the chief relics of almighty Rome;",
  "The trees which grew along the broken arches",
  "Waved dark in the blue midnight, and the stars",
  "Shone through the rents of ruin; from afar",
  "The watch-dog bayed beyond the Tiber; and",
  "More near from out the Cæsars' palace came",
  "The owl's long cry, and, interruptedly,",
  "Of distant sentinels the fitful song",
  "Begun and died upon the gentle wind.",
  "Some cypresses beyond the time-worn breach",
  "Appeared to skirt the horizon, yet they stood",
  "Within a bowshot. Where the Cæsars dwelt,",
  "And dwell the tuneless birds of night, amidst",
  "A grove which springs through levelled battlements,",
  "And twines its roots with the imperial hearths,",
  "Ivy usurps the laurel's place of growth;",
  "But the gladiators' bloody Circus stands,",
  "A noble wreck in ruinous perfection,",
  "While Cæsar's chambers, and the Augustan halls,",
  "Grovel on earth in indistinct decay.--",
  "And thou didst shine, thou rolling Moon, upon",
  "All this, and cast a wide and tender light,",
  "Which softened down the hoar austerity",
  "Of rugged desolation, and filled up,",
  "As 'twere anew, the gaps of centuries;",
  "Leaving that beautiful which still was so,",
  "And making that which was not--till the place",
  "Became religion, and the heart ran o'er",
  "With silent worship of the Great of old,--",
  "The dead, but sceptred, Sovereigns, who still rule",
  "Our spirits from their urns.",
  "                             'Twas such a night!",
  "'Tis strange that I recall it at this time;",
  "But I have found our thoughts take wildest flight",
  "Even at the moment when they should array",
  "Themselves in pensive order.",
  "",
  "                        _Enter the_ ABBOT.",
  "",
  "_Abbot_.                     My good Lord!",
  "I crave a second grace for this approach;",
  "But yet let not my humble zeal offend",
  "By its abruptness--all it hath of ill",
  "Recoils on me; its good in the effect",
  "May light upon your head--could I say _heart_--",
  "Could I touch _that_, with words or prayers, I should",
  "Recall a noble spirit which hath wandered,",
  "But is not yet all lost.",
  "",
  "_Man_.                  Thou know'st me not;",
  "My days are numbered, and my deeds recorded:",
  "Retire, or 'twill be dangerous--Away!",
  "",
  "_Abbot_. Thou dost not mean to menace me?",
  "",
  "_Man_.                                   Not I!",
  "I simply tell thee peril is at hand,",
  "And would preserve thee.",
  "",
  "_Abbot_.                 What dost thou mean?",
  "",
  "_Man_.                                       Look there!",
  "What dost thou see?",
  "",
  "_Abbot_.           Nothing.",
  "",
  "_Man_.                      Look there, I say,",
  "And steadfastly;--now tell me what thou seest?",
  "",
  "_Abbot_. That which should shake me,--but I fear it not:",
  "I see a dusk and awful figure rise,",
  "Like an infernal god, from out the earth;",
  "His face wrapt in a mantle, and his form",
  "Robed as with angry clouds: he stands between",
  "Thyself and me--but I do fear him not.",
  "",
  "_Man_. Thou hast no cause--he shall not harm thee--but",
  "His sight may shock thine old limbs into palsy.",
  "I say to thee--Retire!",
  "",
  "_Abbot_.              And I reply--",
  "Never--till I have battled with this fiend:--",
  "What doth he here?",
  "",
  "_Man_.             Why--aye--what doth he here?",
  "I did not send for him,--he is unbidden.",
  "",
  "_Abbot_. Alas! lost Mortal! what with guests like these",
  "Hast thou to do? I tremble for thy sake:",
  "Why doth he gaze on thee, and thou on him?",
  "Ah! he unveils his aspect: on his brow",
  "The thunder-scars are graven; from his eye",
  "Glares forth the immortality of Hell--",
  "Avaunt!--",
  "",
  "_Man_.        Pronounce--what is thy mission?",
  "",
  "_Spirit_.                                     Come!",
  "",
  "_Abbot_. What art thou, unknown being? answer!--speak!",
  "",
  "_Spirit_. The genius of this mortal.--Come!'tis time.",
  "",
  "_Man_. I am prepared for all things, but deny",
  "The Power which summons me. Who sent thee here?",
  "",
  "_Spirit_. Thou'lt know anon--Come! come!",
  "",
  "_Man_.                                  I have commanded",
  "Things of an essence greater far than thine,",
  "And striven with thy masters. Get thee hence!",
  "",
  "_Spirit_. Mortal! thine hour is come--Away! I say.",
  "",
  "_Man_. I knew, and know my hour is come, but not",
  "To render up my soul to such as thee:",
  "Away! I'll die as I have lived--alone.",
  "",
  "_Spirit_. Then I must summon up my brethren.--Rise!",
  "                                                [_Other Spirits rise._",
  "",
  "_Abbot_. Avaunt! ye evil ones!--Avaunt! I say,--",
  "Ye have no power where Piety hath power,",
  "And I do charge ye in the name--",
  "",
  "_Spirit_.                        Old man!",
  "We know ourselves, our mission, and thine order;",
  "Waste not thy holy words on idle uses,",
  "It were in vain: this man is forfeited.",
  "Once more--I summon him--Away! Away!",
  "",
  "_Man_. I do defy ye,--though I feel my soul",
  "Is ebbing from me, yet I do defy ye;",
  "Nor will I hence, while I have earthly breath",
  "To breathe my scorn upon ye--earthly strength",
  "To wrestle, though with spirits; what ye take",
  "Shall be ta'en limb by limb.",
  "",
  "_Spirit_.                    Reluctant mortal!",
  "Is this the Magian who would so pervade",
  "The world invisible, and make himself",
  "Almost our equal? Can it be that thou",
  "Art thus in love with life? the very life",
  "Which made thee wretched?",
  "",
  "_Man_.                   Thou false fiend, thou liest!",
  "My life is in its last hour,--_that_ I know,",
  "Nor would redeem a moment of that hour;",
  "I do not combat against Death, but thee",
  "And thy surrounding angels; my past power",
  "Was purchased by no compact with thy crew,",
  "But by superior science--penance, daring,",
  "And length of watching, strength of mind, and skill",
  "In knowledge of our Fathers--when the earth",
  "Saw men and spirits walking side by side,",
  "And gave ye no supremacy: I stand",
  "Upon my strength--I do defy--deny--",
  "Spurn back, and scorn ye!--",
  "",
  "_Spirit_.                 But thy many crimes",
  "Have made thee--",
  "",
  "_Man_.          What are they to such as thee?",
  "Must crimes be punished but by other crimes,",
  "And greater criminals?--Back to thy hell!",
  "Thou hast no power upon me, _that_ I feel;",
  "Thou never shalt possess me, _that_ I know:",
  "What I have done is done; I bear within",
  "A torture which could nothing gain from thine:",
  "The Mind which is immortal makes itself",
  "Requital for its good or evil thoughts,--",
  "Is its own origin of ill and end--",
  "And its own place and time: its innate sense,",
  "When stripped of this mortality, derives",
  "No colour from the fleeting things without,",
  "But is absorbed in sufferance or in joy,",
  "Born from the knowledge of its own desert.",
  "_Thou_ didst not tempt me, and thou couldst not tempt me;",
  "I have not been thy dupe, nor am thy prey--",
  "But was my own destroyer, and will be",
  "My own hereafter.--Back, ye baffled fiends!",
  "The hand of Death is on me--but not yours!",
  "                                              [_The Demons disappear._",
  "",
  "_Abbot_. Alas! how pale thou art--thy lips are white--",
  "And thy breast heaves--and in thy gasping throat",
  "The accents rattle: Give thy prayers to Heaven--",
  "Pray--albeit but in thought,--but die not thus.",
  "",
  "_Man_. 'Tis over--my dull eyes can fix thee not;",
  "But all things swim around me, and the earth",
  "Heaves as it were beneath me. Fare thee well--",
  "Give me thy hand.",
  "",
  "_Abbot_.            Cold--cold--even to the heart--",
  "But yet one prayer--Alas! how fares it with thee?",
  "",
  "_Man_. Old man! 'tis not so difficult to die.",
  "                                                   [MANFRED _expires._",
  "",
  "_Abbot_. He's gone--his soul hath ta'en its earthless flight;",
  "Whither? I dread to think--but he is gone.",
  ""
]