module.exports = [
  "Now I know that Spring will come again,",
  "Perhaps to-morrow: however late I've patience",
  "After this night following on such a day.",
  "",
  "While still my temples ached from the cold burning",
  "Of hail and wind, and still the primroses",
  "Torn by the hail were covered up in it,",
  "The sun filled earth and heaven with a great light",
  "And a tenderness, almost warmth, where the hail",
  "   dripped,",
  "As if the mighty sun wept tears of joy.",
  "But 'twas too late for warmth. The sunset piled",
  "Mountains on mountains of snow and ice in the",
  "   west:",
  "Somewhere among their folds the wind was lost,",
  "And yet 'twas cold, and though I knew that",
  "   Spring",
  "Would come again, I knew it had not come,",
  "That it was lost too in those mountains chill.",
  "",
  "What did the thrushes know? Rain, snow, sleet,",
  "   hail,",
  "Had kept them quiet as the primroses.",
  "They had but an hour to sing. On boughs they",
  "   sang,",
  "On gates, on ground; they sang while they",
  "   changed perches",
  "And while they fought, if they remembered to",
  "   fight:",
  "So earnest were they to pack into that hour",
  "Their unwilling hoard of song before the moon",
  "Grew brighter than the clouds. Then 'twas",
  "   no time",
  "For singing merely. So they could keep off silence",
  "And night, they cared not what they sang or",
  "   screamed;",
  "Whether 'twas hoarse or sweet or fierce or soft;",
  "And to me all was sweet: they could do no wrong.",
  "Something they knew--I also, while they sang",
  "And after. Not till night had half its stars",
  "And never a cloud, was I aware of silence",
  "Stained with all that hour's songs, a silence",
  "Saying that Spring returns, perhaps to-morrow.",
  ""
]