module.exports = [
  "A pale Dream came to a Lady fair,",
  "And said, A boon, a boon, I pray!",
  "I know the secrets of the air,",
  "And things are lost in the glare of day,",
  "Which I can make the sleeping see,",
  "If they will put their trust in me.",
  "",
  "And thou shalt know of things unknown,",
  "If thou wilt let me rest between",
  "The veiny lids, whose fringe is thrown",
  "Over thine eyes so dark and sheen:",
  "And half in hope, and half in fright,",
  "The Lady closed her eyes so bright.",
  "",
  "At first all deadly shapes were driven",
  "Tumultuously across her sleep,",
  "And o'er the vast cope of bending heaven",
  "All ghastly-visaged clouds did sweep;",
  "And the Lady ever looked to spy",
  "If the golden sun shone forth on high.",
  "",
  "And as towards the east she turned,",
  "She saw aloft in the morning air,",
  "Which now with hues of sunrise burned,",
  "A great black Anchor rising there;",
  "And wherever the Lady turned her eyes,",
  "It hung before her in the skies.",
  "",
  "The sky was blue as the summer sea,",
  "The depths were cloudless overhead,",
  "The air was calm as it could be,",
  "There was no sight or sound of dread,",
  "But that black Anchor floating still",
  "Over the piny eastern hill.",
  "",
  "The Lady grew sick with a weight of fear",
  "To see that Anchor ever hanging,",
  "And veiled her eyes; she then did hear",
  "The sound as of a dim low clanging,",
  "And looked abroad if she might know",
  "Was it aught else, or but the flow",
  "Of the blood in her own veins, to and fro.",
  "",
  "There was a mist in the sunless air,",
  "Which shook as it were with an earthquake's shock,",
  "But the very weeds that blossomed there",
  "Were moveless, and each mighty rock",
  "Stood on its basis steadfastly;",
  "The Anchor was seen no more on high.",
  "",
  "But piled around, with summits hid",
  "In lines of cloud at intervals,",
  "Stood many a mountain pyramid",
  "Among whose everlasting walls",
  "Two mighty cities shone, and ever",
  "Through the red mist their domes did quiver.",
  "",
  "On two dread mountains, from whose crest,",
  "Might seem, the eagle, for her brood,",
  "Would ne'er have hung her dizzy nest,",
  "Those tower-encircled cities stood.",
  "A vision strange such towers to see,",
  "Sculptured and wrought so gorgeously,",
  "Where human art could never be.",
  "",
  "And columns framed of marble white,",
  "And giant fanes, dome over dome",
  "Piled, and triumphant gates, all bright",
  "With workmanship, which could not come",
  "From touch of mortal instrument,",
  "Shot o'er the vales, or lustre lent",
  "From its own shapes magnificent.",
  "",
  "But still the Lady heard that clang",
  "Filling the wide air far away;",
  "And still the mist whose light did hang",
  "Among the mountains shook alway,",
  "So that the Lady's heart beat fast,",
  "As half in joy, and half aghast,",
  "On those high domes her look she cast.",
  "",
  "Sudden, from out that city sprung",
  "A light that made the earth grow red;",
  "Two flames that each with quivering tongue",
  "Licked its high domes, and overhead",
  "Among those mighty towers and fanes",
  "Dropped fire, as a volcano rains",
  "Its sulphurous ruin on the plains.",
  "",
  "And hark! a rush as if the deep",
  "Had burst its bonds; she looked behind",
  "And saw over the western steep",
  "A raging flood descend, and wind",
  "Through that wide vale; she felt no fear,",
  "But said within herself, 'Tis clear",
  "These towers are Nature's own, and she",
  "To save them has sent forth the sea.",
  "",
  "And now those raging billows came",
  "Where that fair Lady sate, and she",
  "Was borne towards the showering flame",
  "By the wild waves heaped tumultuously.",
  "And, on a little plank, the flow",
  "Of the whirlpool bore her to and fro.",
  "",
  "The flames were fiercely vomited",
  "From every tower and every dome,",
  "And dreary light did widely shed",
  "O'er that vast flood's suspended foam,",
  "Beneath the smoke which hung its night",
  "On the stained cope of heaven's light.",
  "",
  "The plank whereon that Lady sate",
  "Was driven through the chasms, about and about,",
  "Between the peaks so desolate",
  "Of the drowning mountains, in and out,",
  "As the thistle-beard on a whirlwind sails--",
  "While the flood was filling those hollow vales.",
  "",
  "At last her plank an eddy crossed,",
  "And bore her to the city's wall,",
  "Which now the flood had reached almost;",
  "It might the stoutest heart appal",
  "To hear the fire roar and hiss",
  "Through the domes of those mighty palaces.",
  "",
  "The eddy whirled her round and round",
  "Before a gorgeous gate, which stood",
  "Piercing the clouds of smoke which bound",
  "Its aery arch with light like blood;",
  "She looked on that gate of marble clear,",
  "With wonder that extinguished fear.",
  "",
  "For it was filled with sculptures rarest,",
  "Of forms most beautiful and strange,",
  "Like nothing human, but the fairest",
  "Of winged shapes, whose legions range",
  "Throughout the sleep of those that are,",
  "Like this same Lady, good and fair.",
  "",
  "And as she looked, still lovelier grew",
  "Those marble forms;--the sculptor sure",
  "Was a strong spirit, and the hue",
  "Of his own mind did there endure",
  "After the touch, whose power had braided",
  "Such grace, was in some sad change faded.",
  "",
  "She looked, the flames were dim, the flood",
  "Grew tranquil as a woodland river",
  "Winding through hills in solitude;",
  "Those marble shapes then seemed to quiver,",
  "And their fair limbs to float in motion,",
  "Like weeds unfolding in the ocean.",
  "",
  "And their lips moved; one seemed to speak,",
  "When suddenly the mountains cracked,",
  "And through the chasm the flood did break",
  "With an earth-uplifting cataract:",
  "The statues gave a joyous scream,",
  "And on its wings the pale thin Dream",
  "Lifted the Lady from the stream.",
  "",
  "The dizzy flight of that phantom pale",
  "Waked the fair Lady from her sleep,",
  "And she arose, while from the veil",
  "Of her dark eyes the Dream did creep,",
  "And she walked about as one who knew",
  "That sleep has sights as clear and true",
  "As any waking eyes can view.",
  ""
]