module.exports = [
  "The mountain brook sung lonesomelike, and loitered on its way",
  "Ez if it waited for a child to jine it in its play;",
  "The wild-flowers uv the hillside bent down their heads to hear",
  "The music uv the little feet that had somehow grown so dear;",
  "The magpies, like winged shadders, wuz a-flutterin' to an' fro",
  "Among the rocks an' holler stumps in the ragged gulch below;",
  "The pines an' hemlocks tosst their boughs (like they wuz arms) and made",
  "Soft, sollum music on the slope where he had often played;",
  "But for these lonesome, sollum voices on the mountain-side,",
  "There wuz no sound the summer day that Marthy's younkit died.",
  "",
  "We called him Marthy's younkit, for Marthy wuz the name",
  "Uv her ez wuz his mar, the wife uv Sorry Tom,--the same",
  "Ez taught the school-house on the hill, way back in '69,",
  "When she marr'd Sorry Tom, wich owned the Gosh-all-Hemlock mine!",
  "And Marthy's younkit wuz their first, wich, bein' how it meant",
  "The first on Red Hoss Mountain, wuz truly a' event!",
  "The miners sawed off short on work ez soon ez they got word",
  "That Dock Devine allowed to Casey what had just occurred;",
  "We loaded up an' whooped around until we all wuz hoarse",
  "Salutin' the arrival, wich weighed ten pounds, uv course!",
  "",
  "Three years, and sech a pretty child!--his mother's counterpart!",
  "Three years, an' sech a holt ez he had got on every heart!",
  "A peert an' likely little tyke with hair ez red ez gold,",
  "A-laughin', toddlin' everywhere,--'nd only three years old!",
  "Up yonder, sometimes, to the store, an' sometimes down the hill",
  "He kited (boys is boys, you know,--you couldn't keep him still!)",
  "An' there he'd play beside the brook where purpul wild-flowers grew,",
  "An' the mountain pines an' hemlocks a kindly shadder threw,",
  "An' sung soft, sollum toons to him, while in the gulch below",
  "The magpies, like strange sperrits, went flutterin' to an' fro.",
  "",
  "Three years, an' then the fever come,--it wuzn't right, you know,",
  "With all us old ones in the camp, for that little child to go;",
  "It's right the old should die, but that a harmless little child",
  "Should miss the joy uv life an' love,--that can't be reconciled!",
  "That's what we thought that summer day, an' that is what we said",
  "Ez we looked upon the piteous face uv Marthy's younkit dead.",
  "But for his mother's sobbin', the house wuz very still,",
  "An' Sorry Tom wuz lookin', through the winder, down the hill,",
  "To the patch beneath the hemlocks where his darlin' used to play,",
  "An' the mountain brook sung lonesomelike an' loitered on its way.",
  "",
  "A preacher come from Roarin' Crick to comfort 'em an' pray,",
  "'Nd all the camp wuz present at the obsequies next day;",
  "A female teacher staged it twenty miles to sing a hymn,",
  "An' we jined her in the chorus,--big, husky men an' grim",
  "Sung \"Jesus, Lover uv my Soul,\" an' then the preacher prayed,",
  "An' preacht a sermon on the death uv that fair blossom laid",
  "Among them other flowers he loved,--wich sermon set sech weight",
  "On sinners bein' always heeled against the future state,",
  "That, though it had been fashionable to swear a perfec' streak,",
  "There warn't no swearin' in the camp for pretty nigh a week!",
  "",
  "Last thing uv all, four strappin' men took up the little load",
  "An' bore it tenderly along the windin', rocky road,",
  "To where the coroner had dug a grave beside the brook,",
  "In sight uv Marthy's winder, where the same could set an' look",
  "An' wonder if his cradle in that green patch, long an' wide,",
  "Wuz ez soothin' ez the cradle that wuz empty at her side;",
  "An' wonder if the mournful songs the pines wuz singin' then",
  "Wuz ez tender ez the lullabies she'd never sing again,",
  "'Nd if the bosom of the earth in wich he lay at rest",
  "Wuz half ez lovin' 'nd ez warm ez wuz his mother's breast.",
  "",
  "The camp is gone; but Red Hoss Mountain rears its kindly head,",
  "An' looks down, sort uv tenderly, upon its cherished dead;",
  "'Nd I reckon that, through all the years, that little boy wich died",
  "Sleeps sweetly an' contentedly upon the mountain-side;",
  "That the wild-flowers uv the summer-time bend down their heads to hear",
  "The footfall uv a little friend they know not slumbers near;",
  "That the magpies on the sollum rocks strange flutterin' shadders make,",
  "An' the pines an' hemlocks wonder that the sleeper doesn't wake;",
  "That the mountain brook sings lonesomelike an' loiters on its way",
  "Ez if it waited for a child to jine it in its play.",
  ""
]