module.exports = [
  "THERE never was a finer day,",
  "And never will be while May is May,--",
  "The third, and not the last of its kind;",
  "But though fair and clear the two behind",
  "Seemed pursued by tempests overpast;",
  "And the morrow with fear that it could not last",
  "Was spoiled. To-day ere the stones were warm",
  "Five minutes of thunderstorm",
  "Dashed it with rain, as if to secure,",
  "By one tear, its beauty the luck to endure.",
  "",
  "At mid-day then along the lane",
  "Old Jack Noman appeared again,",
  "Jaunty and old, crooked and tall,",
  "And stopped and grinned at me over the wall,",
  "With a cowslip bunch in his button-hole",
  "And one in his cap. Who could say if his roll",
  "Came from flints in the road, the weather, or ale?",
  "He was welcome as the nightingale.",
  "Not an hour of the sun had been wasted on Jack",
  "\"I've got my Indian complexion back\"",
  "Said he. He was tanned like a harvester,",
  "Like his short clay pipe, like the leaf and bur",
  "That clung to his coat from last night's bed,",
  "Like the ploughland crumbling red.",
  "Fairer flowers were none on the earth",
  "Than his cowslips wet with the dew of their birth,",
  "Or fresher leaves than the cress in his basket.",
  "\"Where did they come from, Jack?\" \"Don't ask it,",
  "And you'll be told no lies.\" \"Very well:",
  "Then I can't buy.\" \"I don't want to sell.",
  "Take them and these flowers, too, free.",
  "Perhaps you have something to give me?",
  "Wait till next time. The better the day . . .",
  "The Lord couldn't make a better, I say;",
  "If he could, he never has done.\"",
  "So off went Jack with his roll-walk-run,",
  "Leaving his cresses from Oakshott rill",
  "And his cowslips from Wheatham hill.",
  "",
  "'Twas the first day that the midges bit;",
  "But though they bit me, I was glad of it:",
  "Of the dust in my face, too, I was glad.",
  "Spring could do nothing to make me sad.",
  "Bluebells hid all the ruts in the copse.",
  "The elm seeds lay in the road like hops,",
  "That fine day, May the twenty-third,",
  "The day Jack Noman disappeared.",
  ""
]