module.exports = [
  "MEN are Heaven's piers; they evermore",
  "Unwearying bear the skyey floor;",
  "Man's theatre they bear with ease,",
  "Unfrowning cariatides!",
  "I, for my wife, the sun uphold,",
  "Or, dozing, strike the seasons cold.",
  "She, on her side, in fairy-wise",
  "Deals in diviner mysteries,",
  "By spells to make the fuel burn",
  "And keep the parlour warm, to turn",
  "Water to wine, and stones to bread,",
  "By her unconquered hero-head.",
  "A naked Adam, naked Eve,",
  "Alone the primal bower we weave;",
  "Sequestered in the seas of life,",
  "A Crusoe couple, man and wife,",
  "With all our good, with all our will,",
  "Our unfrequented isle we fill;",
  "And victor in day's petty wars,",
  "Each for the other lights the stars.",
  "Come then, my Eve, and to and fro",
  "Let us about our garden go;",
  "And, grateful-hearted, hand in hand",
  "Revisit all our tillage land,",
  "And marvel at our strange estate,",
  "For hooded ruin at the gate",
  "Sits watchful, and the angels fear",
  "To see us tread so boldly here.",
  "Meanwhile, my Eve, with flower and grass",
  "Our perishable days we pass;",
  "Far more the thorn observe - and see",
  "How our enormous sins go free -",
  "Nor less admire, beside the rose,",
  "How far a little virtue goes.",
  ""
]