module.exports = [
  "First was the world as one great cymbal made,",
  "Where jarring winds to infant Nature played.",
  "All music was a solitary sound,",
  "To hollow rocks and murm'ring fountains bound.",
  "",
  "Jubal first made the wilder notes agree;",
  "And Jubal tuned music's Jubilee;",
  "He call'd the echoes from their sullen cell,",
  "And built the organ's city where they dwell.",
  "",
  "Each sought a consort in that lovely place,",
  "And virgin trebles wed the manly bass.",
  "From whence the progeny of numbers new",
  "Into harmonious colonies withdrew.",
  "",
  "Some to the lute, some to the viol went,",
  "And others chose the cornet eloquent,",
  "These practicing the wind, and those the wire,",
  "To sing men's triumphs, or in Heaven's choir.",
  "",
  "Then music, the mosaic of the air,",
  "Did of all these a solemn noise prepare;",
  "With which she gain'd the empire of the ear,",
  "Including all between the earth and sphere.",
  "",
  "Victorious sounds! yet here your homage do",
  "Unto a gentler conqueror than you;",
  "Who though he flies the music of his praise,",
  "Would with you Heaven's Hallelujahs raise.",
  ""
]