module.exports = [
  "Why were you put in Lob's pond,",
  "  My boy, HOBBY O? (_bis_)",
  "For telling folks to pull the House",
  "  By the ears into the Lobby O!",
  "",
  "Who are your grand Reformers now,",
  "  My boy, HOBBY O? (_bis_)",
  "There's me and BURDETT,--gentlemen,",
  "  And Blackguards HUNT and COBBY O!",
  "",
  "Have you no other friends but these,",
  "  My boy, HOBBY O? (_bis_)",
  "Yes, Southwark's Knight, the County BYNG,",
  "  And in the City, BOBBY O!",
  "",
  "How do you recreate yourselves,",
  "  My boy, HOBBY O? (_bis_)",
  "We spout with tavern Radicals,",
  "  And drink with them hob-nobby O!",
  "",
  "What purpose can such folly work,",
  "  My boy, HOBBY O? (_bis_)",
  "It gives our partisans a chance",
  "  Watches to twitch from fob-by O!",
  "",
  "Have they no higher game in view,",
  "  My boy, HOBBY O? (_bis_)",
  "Oh yes; to stir the people up,",
  "  And then to head the mob-by O.",
  "",
  "But sure they'll at their ruin pause,",
  "  My boy, HOBBY O? (_bis_)",
  "No! they'd see King and Parliament",
  "  Both d--d without a sob-by O!",
  "",
  "But, if they fail, they'll be hanged up,",
  "  My boy, HOBBY O? (_bis_)",
  "Why, then, they'll swing, like better men,",
  "  And that will end the job-by O!",
  ""
]