module.exports = [
  "In the dome of my Sires as the clear moonbeam falls",
  "Through Silence and Shade o'er its desolate walls,",
  "It shines from afar like the glories of old;",
  "It gilds, but it warms not--'tis dazzling, but cold.",
  "",
  "Let the Sunbeam be bright for the younger of days:",
  "'Tis the light that should shine on a race that decays,",
  "When the Stars are on high and the dews on the ground,",
  "And the long shadow lingers the ruin around.",
  "",
  "And the step that o'erechoes the gray floor of stone",
  "Falls sullenly now, for 'tis only my own;",
  "And sunk are the voices that sounded in mirth,",
  "And empty the goblet, and dreary the hearth.",
  "",
  "And vain was each effort to raise and recall",
  "The brightness of old to illumine our Hall;",
  "And vain was the hope to avert our decline,",
  "And the fate of my fathers had faded to mine.",
  "",
  "And theirs was the wealth and the fulness of Fame,",
  "And mine to inherit too haughty a name;",
  "And theirs were the times and the triumphs of yore,",
  "And mine to regret, but renew them no more.",
  "",
  "And Ruin is fixed on my tower and my wall,",
  "Too hoary to fade, and too massy to fall;",
  "It tells not of Time's or the tempest's decay,",
  "But the wreck of the line that have held it in sway.",
  ""
]