module.exports = [
  "Apollo's wrath to man the dreadful spring",
  "Of ills innum'rous, tuneful goddess, sing!",
  "Thou who did'st first th' ideal pencil give,",
  "And taught'st the painter in his works to live,",
  "Inspire with glowing energy of thought,",
  "What Wilson painted, and what Ovid wrote.",
  "Muse! lend thy aid, nor let me sue in vain,",
  "Tho' last and meanest of the rhyming train!",
  "O guide my pen in lofty strains to show",
  "The Phrygian queen, all beautiful in woe.",
  "'Twas where Maeonia spreads her wide domain",
  "Niobe dwelt, and held her potent reign:",
  "See in her hand the regal sceptre shine,",
  "The wealthy heir of Tantalus divine,",
  "He most distinguish'd by Dodonean Jove,",
  "To approach the tables of the gods above:",
  "Her grandsire Atlas, who with mighty pains",
  "Th' ethereal axis on his neck sustains:",
  "Her other grandsire on the throne on high",
  "Rolls the loud-pealing thunder thro' the sky.",
  "",
  "Her spouse, Amphion, who from Jove too springs,",
  "Divinely taught to sweep the sounding strings.",
  "",
  "Seven sprightly sons the royal bed adorn,",
  "Seven daughters beauteous as the op'ning morn,",
  "As when Aurora fills the ravish'd sight,",
  "And decks the orient realms with rosy light",
  "From their bright eyes the living splendors play,",
  "Nor can beholders bear the flashing ray.",
  "",
  "Wherever, Niobe, thou turn'st thine eyes,",
  "New beauties kindle, and new joys arise!",
  "But thou had'st far the happier mother prov'd,",
  "If this fair offspring had been less belov'd:",
  "What if their charms exceed Aurora's teint.",
  "No words could tell them, and no pencil paint,",
  "Thy love too vehement hastens to destroy",
  "Each blooming maid, and each celestial boy.",
  "",
  "Now Manto comes, endu'd with mighty skill,",
  "The past to explore, the future to reveal.",
  "Thro' Thebes' wide streets Tiresia's daughter came,",
  "Divine Latona's mandate to proclaim:",
  "The Theban maids to hear the orders ran,",
  "When thus Maeonia's prophetess began:",
  "",
  "\"Go, Thebans! great Latona's will obey,",
  "\"And pious tribute at her altars pay:",
  "\"With rights divine, the goddess be implor'd,",
  "\"Nor be her sacred offspring unador'd.\"",
  "Thus Manto spoke. The Theban maids obey,",
  "And pious tribute to the goddess pay.",
  "The rich perfumes ascend in waving spires,",
  "And altars blaze with consecrated fires;",
  "The fair assembly moves with graceful air,",
  "And leaves of laurel bind the flowing hair.",
  "",
  "Niobe comes with all her royal race,",
  "With charms unnumber'd, and superior grace:",
  "Her Phrygian garments of delightful hue,",
  "Inwove with gold, refulgent to the view,",
  "Beyond description beautiful she moves",
  "Like heav'nly Venus, 'midst her smiles and loves:",
  "She views around the supplicating train,",
  "And shakes her graceful head with stern disdain,",
  "Proudly she turns around her lofty eyes,",
  "And thus reviles celestial deities:",
  "\"What madness drives the Theban ladies fair",
  "\"To give their incense to surrounding air?",
  "\"Say why this new sprung deity preferr'd?",
  "\"Why vainly fancy your petitions heard?",
  "\"Or say why Cæus offspring is obey'd,",
  "\"While to my goddesship no tribute's paid?",
  "\"For me no altars blaze with living fires,",
  "\"No bullock bleeds, no frankincense transpires,",
  "\"Tho' Cadmus' palace, not unknown to fame,",
  "\"And Phrygian nations all revere my name.",
  "\"Where'er I turn my eyes vast wealth I find,",
  "\"Lo! here an empress with a goddess join'd.",
  "\"What, shall a Titaness be deify'd,",
  "\"To whom the spacious earth a couch deny'd!",
  "\"Nor heav'n, nor earth, nor sea receiv'd your queen,",
  "\"Till pitying Delos took the wand'rer in.",
  "\"Round me what a large progeny is spread!",
  "\"No frowns of fortune has my soul to dread.",
  "\"What if indignant she decrease my train",
  "\"More than Latona's number will remain;",
  "\"Then hence, ye Theban dames, hence haste away,",
  "\"Nor longer off'rings to Latona pay;",
  "\"Regard the orders of Amphion's spouse,",
  "\"And take the leaves of laurel from your brows.\"",
  "Niobe spoke. The Theban maids obey'd,",
  "Their brows unbound, and left the rights unpaid.",
  "",
  "The angry goddess heard, then silence broke",
  "On Cynthus' summit, and indignant spoke;",
  "\"Phoebus! behold, thy mother in disgrace,",
  "\"Who to no goddess yields the prior place",
  "\"Except to Juno's self, who reigns above,",
  "\"The spouse and sister of the thund'ring Jove.",
  "\"Niobe, sprung from Tantalus, inspires",
  "\"Each Theban bosom with rebellious fires;",
  "\"No reason her imperious temper quells,",
  "\"But all her father in her tongue rebels;",
  "\"Wrap her own sons for her blaspheming breath,",
  "\"Apollo! wrap them in the shades of death.\"",
  "Latona ceas'd, and ardent thus replies",
  "The God, whose glory decks th' expanded skies.",
  "",
  "\"Cease thy complaints, mine be the task assign'd",
  "\"To punish pride, and scourge the rebel mind.\"",
  "This Phoebe join'd.--They wing their instant flight;",
  "Thebes trembled as th' immortal pow'rs alight.",
  "",
  "With clouds incompass'd glorious Phoebus stands;",
  "The feather'd vengeance quiv'ring in his hands.",
  "",
  "Near Cadmus' walls a plain extended lay,",
  "Where Thebes' young princes pass'd in sport the day:",
  "There the bold coursers bounded o'er the plains,",
  "While their great masters held the golden reins.",
  "Ismenus first the racing pastime led,",
  "And rul'd the fury of his flying steed.",
  "\"Ah me,\" he sudden cries, with shrieking breath,",
  "While in his breast he feels the shaft of death;",
  "He drops the bridle on his courser's mane,",
  "Before his eyes in shadows swims the plain,",
  "He, the first-born of great Amphion's bed,",
  "Was struck the first, first mingled with the dead.",
  "",
  "Then didst thou, Sipylus, the language hear",
  "Of fate portentous whistling in the air:",
  "As when th' impending storm the sailor sees",
  "He spreads his canvas to the fav'ring breeze,",
  "So to thine horse thou gav'st the golden reins,",
  "Gav'st him to rush impetuous o'er the plains:",
  "But ah! a fatal shaft from Phoebus' hand",
  "Smites thro' thy neck, and sinks thee on the sand.",
  "",
  "Two other brothers were at wrestling found,",
  "And in their pastime claspt each other round:",
  "A shaft that instant from Apollo's hand",
  "Transfixt them both, and stretcht them on the sand:",
  "Together they their cruel fate bemoan'd,",
  "Together languish'd, and together groan'd:",
  "Together too th' unbodied spirits fled,",
  "And sought the gloomy mansions of the dead.",
  "Alphenor saw, and trembling at the view,",
  "Beat his torn breast, that chang'd its snowy hue.",
  "He flies to raise them in a kind embrace;",
  "A brother's fondness triumphs in his face:",
  "Alphenor fails in this fraternal deed,",
  "A dart dispatch'd him (so the fates decreed",
  "Soon as the arrow left the deadly wound,",
  "His issuing entrails smoak'd upon the ground.",
  "What woes on blooming Damasichon wait!",
  "His sighs portend his near impending fate.",
  "Just where the well-made leg begins to be,",
  "And the soft sinews form the supple knee,",
  "The youth sore wounded by the Delian god",
  "Attempts t' extract the crime-avenging rod,",
  "But, whilst he strives the will of fate t' avert,",
  "Divine Apollo sends a second dart;",
  "Swift thro' his throat the feather'd mischief flies,",
  "Bereft of sense, he drops his head, and dies.",
  "",
  "Young Ilioneus, the last, directs his pray'r,",
  "And cries, \"My life, ye gods celestial! spare.\"",
  "Apollo heard, and pity touch'd his heart,",
  "But ah! too late, for he had sent the dart:",
  "Thou too, O Ilioneus, art doom'd to fall,",
  "The fates refuse that arrow to recal.",
  "",
  "On the swift wings of ever flying Fame",
  "To Cadmus' palace soon the tidings came:",
  "Niobe heard, and with indignant eyes",
  "She thus express'd her anger and surprise:",
  "\"Why is such privilege to them allow'd?",
  "\"Why thus insulted by the Delian god?",
  "\"Dwells there such mischief in the pow'rs above?",
  "\"Why sleeps the vengeance of immortal Jove?\"",
  "For now Amphion too, with grief oppress'd,",
  "Had plung'd the deadly dagger in his breast.",
  "Niobe now, less haughty than before,",
  "With lofty head directs her steps no more",
  "She, who late told her pedigree divine,",
  "And drove the Thebans from Latona's shrine,",
  "How strangely chang'd!--yet beautiful in woe,",
  "She weeps, nor weeps unpity'd by the foe.",
  "On each pale corse the wretched mother spread",
  "Lay overwhelm'd with grief, and kiss'd her dead,",
  "Then rais'd her arms, and thus, in accents slow,",
  "\"Be sated cruel Goddess! with my woe;",
  "\"If I've offended, let these streaming eyes,",
  "\"And let this sev'nfold funeral suffice:",
  "\"Ah! take this wretched life you deign'd to save,",
  "\"With them I too am carried to the grave.",
  "\"Rejoice triumphant, my victorious foe,",
  "\"But show the cause from whence your triumphs flow?",
  "\"Tho' I unhappy mourn these children slain,",
  "\"Yet greater numbers to my lot remain.\"",
  "She ceas'd, the bow string twang'd with awful sound,",
  "Which struck with terror all th' assembly round,",
  "Except the queen, who stood unmov'd alone,",
  "By her distresses more presumptuous grown.",
  "Near the pale corses stood their sisters fair",
  "In sable vestures and dishevell'd hair;",
  "One, while she draws the fatal shaft away,",
  "Faints, falls, and sickens at the light of day.",
  "To sooth her mother, lo! another flies,",
  "And blames the fury of inclement skies,",
  "And, while her words a filial pity show,",
  "Struck dumb--indignant seeks the shades below.",
  "Now from the fatal place another flies,",
  "Falls in her flight, and languishes, and dies.",
  "Another on her sister drops in death;",
  "A fifth in trembling terrors yields her breath;",
  "While the sixth seeks some gloomy cave in vain,",
  "Struck with the rest, and mingled with the slain.",
  "",
  "One only daughter lives, and she the least;",
  "The queen close clasp'd the daughter to her breast:",
  "\"Ye heav'nly pow'rs, ah spare me one,\" she cry'd,",
  "\"Ah! spare me one,\" the vocal hills reply'd:",
  "In vain she begs, the Fates her suit deny,",
  "In her embrace she sees her daughter die.",
  "",
  "*\"The queen of all her family bereft,",
  "\"Without or husband, son, or daughter left,",
  "\"Grew stupid at the shock. The passing air",
  "\"Made no impression on her stiff'ning hair.",
  "\"The blood forsook her face: amidst the flood",
  "\"Pour'd from her cheeks, quite fix'd her eye-balls stood.",
  "\"Her tongue, her palate both obdurate grew,",
  "\"Her curdled veins no longer motion knew;",
  "\"The use of neck, and arms, and feet was gone,",
  "\"And ev'n her bowels hard'ned into stone:",
  "\"A marble statue now the queen appears,",
  "\"But from the marble steal the silent tears.\"",
  ""
]