module.exports = [
  "On Martinmas eve the dogs did bark,",
  "  And I opened the window to see,",
  "When every maiden went by with her spark",
  "  But neer a one came to me.",
  "And O dear what will become of me?",
  "  And O dear what shall I do,",
  "When nobody whispers to marry me--",
  "  Nobody cometh to woo?",
  "",
  "None's born for such troubles as I be:",
  "  If the sun wakens first in the morn",
  "\"Lazy hussy\" my parents both call me,",
  "  And I must abide by their scorn,",
  "For nobody cometh to marry me,",
  "  Nobody cometh to woo,",
  "So here in distress must I tarry me--",
  "  What can a poor maiden do?",
  "",
  "If I sigh through the window when Jerry",
  "  The ploughman goes by, I grow bold;",
  "And if I'm disposed to be merry,",
  "  My parents do nothing but scold;",
  "And Jerry the clown, and no other,",
  "  Eer cometh to marry or woo;",
  "They think me the moral of mother",
  "  And judge me a terrible shrew.",
  "",
  "For mother she hateth all fellows,",
  "  And spinning's my father's desire,",
  "While the old cat growls bass with the bellows",
  "  If eer I hitch up to the fire.",
  "I make the whole house out of humour,",
  "  I wish nothing else but to please,",
  "Would fortune but bring a new comer",
  "  To marry, and make me at ease!",
  "",
  "When I've nothing my leisure to hinder",
  "  I scarce get as far as the eaves;",
  "Her head's instant out of the window",
  "  Calling out like a press after thieves.",
  "The young men all fall to remarking,",
  "  And laugh till they're weary to see't,",
  "While the dogs at the noise begin barking,",
  "  And I slink in with shame from the street.",
  "",
  "My mother's aye jealous of loving,",
  "  My father's aye jealous of play,",
  "So what with them both there's no moving,",
  "  I'm in durance for life and a day.",
  "O who shall I get for to marry me?",
  "  Who will have pity to woo?",
  "Tis death any longer to tarry me,",
  "  And what shall a poor maiden do?",
  ""
]