module.exports = [
  "Down by the beautiful Lakes of Killarney,",
  "Off times I have met my own dear Barney,",
  "In the sweet summer time of the year,",
  "In the silvery moonlight so clear,",
  "I've rambled with my sweetheart Barney,",
  "Along the green banks of the Lakes of Killarney.",
  "",
  "The Lakes of Killarney are most lovely to be seen",
  "In the summer season when nature's face is green,",
  "Especially in the beautiful silvery moonlight,",
  "When its waters do shine like silver bright;",
  "Such was the time when me and my Barney",
  "Went to walk by the purty Lakes of Killarney.",
  "",
  "My Barney was beautiful, gallant, and gay,",
  "But, alas, he has left me and gone far away,",
  "To that foreign country called Amerikay;",
  "But when he returns we will get married without delay,",
  "And again we will roam by the Lakes of Killarney,",
  "Me and my sweetheart, charming Barney.",
  "",
  "And until he returns I will feel rather sad,",
  "For while walking with Barney I always felt glad;",
  "May God send him home again safe to me,",
  "And he will fill my sad heart with glee,",
  "While we walk by the Lakes of Killarney.",
  "",
  "I dreamt one night I was walking with Barney,",
  "Down by the beautiful Lakes of Killarney,",
  "And he said, \"Nora, dear Nora, don't fret for me,",
  "For I will soon come home to thee;",
  "And I will build a nice cabin near the Lakes of Killarney,",
  "And Nora will live happy with her own dear Barney.\"",
  "",
  "But, alas, I awoke from my beautiful dream,",
  "For, och, if was a most lovely scene;",
  "But I hope it will happen some unexpected day,",
  "When Barney comes home from Amerikay;",
  "Then Barney will relate his adventures to me,",
  "As we walk by the silvery Lakes of Killarney.",
  "",
  "We will ramble among its green trees and green bushes,",
  "And hear the sweet songs of the blackbirds and thrushes,",
  "And gaze on its lovely banks so green,",
  "And its waters glittering like crystal in the moonlight's sheen;",
  "Och! how I long to be walking with Barney,",
  "Along the green banks of the Lakes of Killarney.",
  "",
  "Of all the spots in Ireland, Killarney for me,",
  "For 'twas there I first met my dear Barney:",
  "He was singing, I remember, right merrily;",
  "And his singing filled my heart with glee,",
  "And he said, \"Nora, dear Nora, will you walk with me,",
  "For you are the prettiest girl I ever did see.\"",
  "",
  "\"Now, Barney,\" I said, \"you are just mocking me,",
  "When you say no other girl like me you can see\";",
  "Then he said, \"Nora, you are the only girl I do love,",
  "And this I do swear by the saints above,",
  "I will marry you, dear Nora, without delay,",
  "When I come home from Amerikay.\"",
  "",
  "But when Barney landed in Amerikay,",
  "He courted another girl without dismay,",
  "And he married her in the month of May,",
  "And when I heard it I fainted away;",
  "So maidens beware of such men as Barney,",
  "Or else they will deceive ye with their flattering blarney.",
  ""
]