module.exports = [
  "Sybil of months, and worshipper of winds,",
  "  I love thee, rude and boisterous as thou art;",
  "And scraps of joy my wandering ever finds",
  "  Mid thy uproarious madness--when the start",
  "Of sudden tempests stirs the forest leaves",
  "  Into hoarse fury, till the shower set free",
  "Stills the huge swells. Then ebb the mighty heaves,",
  "  That sway the forest like a troubled sea.",
  "I love thy wizard noise, and rave in turn",
  "  Half-vacant thoughts and rhymes of careless form;",
  "Then hide me from the shower, a short sojourn,",
  "  Neath ivied oak; and mutter to the storm,",
  "Wishing its melody belonged to me,",
  "That I might breathe a living song to thee.",
  "here;",
  "  The wild colt only turns around to stare",
  "  At passer by, then knaps his hide again;",
  "  And moody crows beside the road forbear",
  "  To fly, though pelted by the passing swain;",
  "Thus day seems turned to night, and tries to wake in vain.",
  "",
  "The owlet leaves her hiding-place at noon,",
  "  And flaps her grey wings in the doubling light;",
  "  The hoarse jay screams to see her out so soon,",
  "  And small birds chirp and startle with affright;",
  "  Much doth it scare the superstitious wight,",
  "  Who dreams of sorry luck, and sore dismay;",
  "  While cow-boys think the day a dream of night,",
  "  And oft grow fearful on their lonely way,",
  "Fancying that ghosts may wake, and leave their graves by day.",
  "",
  "Yet but awhile the slumbering weather flings",
  "  Its murky prison round--then winds wake loud;",
  "  With sudden stir the startled forest sings",
  "  Winter's returning song-cloud races cloud.",
  "  And the horizon throws away its shroud,",
  "  Sweeping a stretching circle from the eye;",
  "  Storms upon storms in quick succession crowd,",
  "  And oer the sameness of the purple sky",
  "Heaven paints, with hurried hand, wild hues of every dye.",
  "",
  "At length it comes among the forest oaks,",
  "  With sobbing ebbs, and uproar gathering high;",
  "  The scared, hoarse raven on its cradle croaks,",
  "  And stockdove-flocks in hurried terrors fly,",
  "  While the blue hawk hangs oer them in the sky.--",
  "  The hedger hastens from the storm begun,",
  "  To seek a shelter that may keep him dry;",
  "  And foresters low bent, the wind to shun,",
  "Scarce hear amid the strife the poacher's muttering gun.",
  "",
  "The ploughman hears its humming rage begin,",
  "  And hies for shelter from his naked toil;",
  "  Buttoning his doublet closer to his chin,",
  "  He bends and scampers oer the elting soil,",
  "  While clouds above him in wild fury boil,",
  "  And winds drive heavily the beating rain;",
  "  He turns his back to catch his breath awhile,",
  "  Then ekes his speed and faces it again,",
  "To seek the shepherd's hut beside the rushy plain.",
  "",
  "The boy, that scareth from the spiry wheat",
  "  The melancholy crow--in hurry weaves,",
  "  Beneath an ivied tree, his sheltering seat,",
  "  Of rushy flags and sedges tied in sheaves,",
  "  Or from the field a shock of stubble thieves.",
  "  There he doth dithering sit, and entertain",
  "  His eyes with marking the storm-driven leaves;",
  "  Oft spying nests where he spring eggs had ta'en,",
  "And wishing in his heart twas summer-time again.",
  "",
  "Thus wears the month along, in checkered moods,",
  "  Sunshine and shadows, tempests loud, and calms;",
  "  One hour dies silent oer the sleepy woods,",
  "  The next wakes loud with unexpected storms;",
  "  A dreary nakedness the field deforms--",
  "  Yet many a rural sound, and rural sight,",
  "  Lives in the village still about the farms,",
  "  Where toil's rude uproar hums from morn till night",
  "Noises, in which the ears of industry delight.",
  "",
  "At length the stir of rural labour's still,",
  "  And industry her care awhile foregoes;",
  "  When winter comes in earnest to fulfil",
  "  His yearly task, at bleak November's close,",
  "  And stops the plough, and hides the field in snows;",
  "  When frost locks up the stream in chill delay",
  "  And mellows on the hedge the jetty sloes,",
  "  For little birds--then toil hath time for play,",
  "And nought but threshers' flails awake the dreary day.",
  ""
]