module.exports = [
  "Lo! where the rosy-bosomed Hours,",
  "Fair Venus' train, appear,",
  "Disclose the long-expecting flowers,",
  "And wake the purple year!",
  "The Attic warbler pours her throat,",
  "Responsive to the cuckoo's note,",
  "The untaught harmony of spring:",
  "While, whisp'ring pleasure as they fly,",
  "Cool Zephyrs thro' the clear blue sky",
  "Their gathered fragrance fling.",
  "",
  "Where'er the oak's thick branches stretch",
  "A broader browner shade,",
  "Where'er the rude and moss-grown beech",
  "O'er-canopies the glade,",
  "Beside some water's rushy brink",
  "With me the Muse shall sit, and think",
  "(At ease reclined in rustic state)",
  "How vain the ardour of the Crowd,",
  "How low, how little are the Proud,",
  "How indigent the Great!",
  "",
  "Still is the toiling hand of Care;",
  "The panting herds repose:",
  "Yet hark, how through the peopled air",
  "The busy murmur glows!",
  "The insect-youth are on the wing,",
  "Eager to taste the honied spring",
  "And float amid the liquid noon:",
  "Some lightly o'er the current skim,",
  "Some show their gayly-gilded trim",
  "Quick-glancing to the sun.",
  "",
  "To Contemplation's sober eye",
  "Such is the race of Man:",
  "And they that creep, and they that fly,",
  "Shall end where they began.",
  "Alike the Busy and the Gay",
  "But flutter thro' life's little day,",
  "In Fortune's varying colours drest:",
  "Brushed by the hand of rough Mischance,",
  "Or chilled by Age, their airy dance",
  "They leave, in dust to rest.",
  "",
  "Methinks I hear, in accents low,",
  "The sportive kind reply:",
  "Poor moralist! and what art thou?",
  "A solitary fly!",
  "Thy joys no glittering female meets,",
  "No hive hast thou of hoarded sweets,",
  "No painted plumage to display:",
  "On hasty wings thy youth is flown;",
  "Thy sun is set, thy spring is gone—",
  "We frolic while 'tis May.",
  ""
]