module.exports = [
  "  Descend, ye Nine! descend and sing;",
  "    The breathing instruments inspire,",
  "  Wake into voice each silent string,",
  "    And sweep the sounding lyre;",
  "    In a sadly-pleasing strain",
  "    Let the warbling lute complain:",
  "      Let the loud trumpet sound,",
  "      Till the roofs all around",
  "      The shrill echoes rebound:",
  "  While in more lengthen'd notes and slow,",
  "  The deep, majestic, solemn organs blow.",
  "      Hark! the numbers soft and clear,",
  "      Gently steal upon the ear;",
  "      Now louder, and yet louder rise,",
  "      And fill with spreading sounds the skies;",
  "  Exulting in triumph now swell the bold notes,",
  "  In broken air, trembling, the wild music floats;",
  "      Till, by degrees, remote and small,",
  "        The strains decay,",
  "        And melt away,",
  "      In a dying, dying fall.",
  "",
  "  By Music, minds an equal temper know,",
  "  Nor swell too high, nor sink too low.",
  "  If in the breast tumultuous joys arise,",
  "  Music her soft, assuasive voice applies;",
  "    Or, when the soul is press'd with cares,",
  "    Exalts her in enlivening airs.",
  "  Warriors she fires with animated sounds;",
  "  Pours balm into the bleeding lover's wounds;",
  "      Melancholy lifts her head,",
  "      Morpheus rouses from his bed,",
  "      Sloth unfolds her arms and wakes,",
  "      Listening Envy drops her snakes;",
  "  Intestine war no more our passions wage,",
  "  And giddy factions hear away their rage.",
  "",
  "  But when our country's cause provokes to arms,",
  "  How martial music every bosom warms!",
  "  So when the first bold vessel dared the seas,",
  "  High on the stern the Thracian raised his strain,",
  "      While Argo saw her kindred trees",
  "      Descend from Pelion to the main.",
  "      Transported demigods stood round,",
  "    And men grew heroes at the sound,",
  "    Inflamed with glory's charms:",
  "  Each chief his sevenfold shield display'd,",
  "  And half unsheath'd the shining blade:",
  "  And seas, and rocks, and skies rebound,",
  "  'To arms, to arms, to arms!'",
  "",
  "  But when through all the infernal bounds,",
  "  Which flaming Phlegethon surrounds,",
  "      Love, strong as death, the poet led",
  "      To the pale nations of the dead,",
  "  What sounds were heard,",
  "  What scenes appear'd,",
  "    O'er all the dreary coasts!",
  "        Dreadful gleams,",
  "        Dismal screams,",
  "        Fires that glow,",
  "        Shrieks of woe,",
  "        Sullen moans,",
  "        Hollow groans,",
  "      And cries of tortured ghosts!",
  "  But, hark! he strikes the golden lyre;",
  "  And see! the tortured ghosts respire,",
  "          See, shady forms advance!",
  "    Thy stone, O Sisyphus! stands still,",
  "    Ixion rests upon his wheel.",
  "          And the pale spectres dance!",
  "  The Furies sink upon their iron beds,",
  "  And snakes uncurl'd hang listening round their heads.",
  "",
  "     'By the streams that ever flow,",
  "      By the fragrant winds that blow",
  "        O'er the Elysian flowers;",
  "      By those happy souls who dwell",
  "      In yellow meads of asphodel,",
  "        Or amaranthine bowers;",
  "      By the hero's armèd shades,",
  "      Glittering through the gloomy glades;",
  "      By the youths that died for love,",
  "      Wandering in the myrtle grove,",
  "  Restore, restore Eurydice to life:",
  "  Oh take the husband, or return the wife!'",
  "      He sung, and hell consented",
  "        To hear the poet's prayer:",
  "      Stern Proserpine relented,",
  "        And gave him back the fair.",
  "          Thus song could prevail",
  "          O'er death and o'er hell,",
  "  A conquest how hard and how glorious!",
  "      Though fate had fast bound her",
  "      With Styx nine times round her,",
  "  Yet Music and Love were victorious.",
  "",
  "  But soon, too soon, the lover turns his eyes:",
  "  Again she falls, again she dies, she dies!",
  "  How wilt thou now the fatal sisters move?",
  "  No crime was thine, if 'tis no crime to love.",
  "    Now under hanging mountains,",
  "    Beside the falls of fountains,",
  "    Or where Hebrus wanders,",
  "    Rolling in meanders,",
  "        All alone,",
  "        Unheard, unknown,",
  "        He makes his moan;",
  "        And calls her ghost,",
  "      For ever, ever, ever lost!",
  "      Now with Furies surrounded,",
  "      Despairing, confounded,",
  "      He trembles, he glows,",
  "      Amidst Rhodope's snows:",
  "    See, wild as the winds, o'er the desert he flies;",
  "    Hark! Haemus resounds with the bacchanals' cries--",
  "                       Ah see, he dies!",
  "    Yet even in death Eurydice he sung,",
  "    Eurydice still trembled on his tongue,",
  "          Eurydice the woods,",
  "          Eurydice the floods,",
  "  Eurydice the rocks and hollow mountains rung.",
  "",
  "      Music the fiercest grief can charm,",
  "      And Fate's severest rage disarm:",
  "      Music can soften pain to ease,",
  "      And make despair and madness please:",
  "      Our joys below it can improve,",
  "      And antedate the bliss above.",
  "    This the divine Cecilia found,",
  "  And to her Maker's praise confined the sound.",
  "  When the full organ joins the tuneful choir,",
  "    The immortal powers incline their ear;",
  "  Borne on the swelling notes our souls aspire,",
  "  While solemn airs improve the sacred fire;",
  "    And angels lean from heaven to hear.",
  "  Of Orpheus now no more let poets tell,",
  "  To bright Cecilia greater power is given;",
  "    His numbers raised a shade from hell,",
  "      Hers lift the soul to heaven.",
  ""
]