module.exports = [
  "If that high world, which lies beyond",
  "  Our own, surviving Love endears;",
  "If there the cherished heart be fond,",
  "  The eye the same, except in tears--",
  "How welcome those untrodden spheres!",
  "  How sweet this very hour to die!",
  "To soar from earth and find all fears",
  "  Lost in thy light--Eternity!",
  "",
  "It must be so: 'tis not for self",
  "  That we so tremble on the brink;",
  "And striving to o'erleap the gulf,",
  "  Yet cling to Being's severing link.",
  "Oh! in that future let us think",
  "  To hold each heart the heart that shares,",
  "With them the immortal waters drink,",
  "  And soul in soul grow deathless theirs!",
  ""
]