module.exports = [
  "Ye scenes of my childhood, whose lov'd recollection",
  "  Embitters the present, compar'd with the past;",
  "Where science first dawn'd on the powers of reflection,",
  "  And friendships were form'd, too romantic to last;",
  "",
  "Where fancy, yet, joys to retrace the resemblance",
  "  Of comrades, in friendship and mischief allied;",
  "How welcome to me your ne'er fading remembrance,",
  "  Which rests in the bosom, though hope is deny'd!",
  "",
  "Again I revisit the hills where we sported,",
  "  The streams where we swam, and the fields where we fought;",
  "The school where, loud warn'd by the bell, we resorted,",
  "  To pore o'er the precepts by Pedagogues taught.",
  "",
  "Again I behold where for hours I have ponder'd,",
  "  As reclining, at eve, on yon tombstone I lay;",
  "Or round the steep brow of the churchyard I wander'd,",
  "  To catch the last gleam of the sun's setting ray.",
  "",
  "I once more view the room, with spectators surrounded,",
  "  Where, as Zanga, I trod on Alonzo o'erthrown;",
  "While, to swell my young pride, such applauses resounded,",
  "  I fancied that Mossop himself was outshone.",
  "",
  "Or, as Lear, I pour'd forth the deep imprecation,",
  "  By my daughters, of kingdom and reason depriv'd;",
  "Till, fir'd by loud plaudits and self-adulation,",
  "  I regarded myself as a _Garrick_ reviv'd.",
  "",
  "Ye dreams of my boyhood, how much I regret you!",
  "  Unfaded your memory dwells in my breast;",
  "Though sad and deserted, I ne'er can forget you:",
  "  Your pleasures may still be in fancy possest.",
  "",
  "To Ida full oft may remembrance restore me,",
  "  While Fate shall the shades of the future unroll!",
  "Since Darkness o'ershadows the prospect before me,",
  "  More dear is the beam of the past to my soul!",
  "",
  "But if, through the course of the years which await me,",
  "  Some new scene of pleasure should open to view,",
  "I will say, while with rapture the thought shall elate me,",
  "  \"Oh! such were the days which my infancy knew.\"",
  ""
]