module.exports = [
  "In one who felt as once he felt,",
  "This might, perhaps, have fann'd the flame;",
  "But now his heart no more will melt,",
  "Because that heart is not the same.",
  "",
  "As when the ebbing flames are low,",
  "The aid which once improved their light,",
  "And bade them burn with fiercer glow,",
  "Now quenches all their blaze in night.",
  "",
  "Thus has it been with Passion's fires--",
  "As many a boy and girl remembers--",
  "While every hope of love expires,",
  "Extinguish'd with the dying embers.",
  "",
  "The _first_, though not a spark survive,",
  "  Some careful hand may teach to burn;",
  "The _last_, alas! can ne'er survive;",
  "  No touch can bid its warmth return.",
  "",
  "Or, if it chance to wake again,",
  "  Not always doom'd its heat to smother,",
  "It sheds (so wayward fates ordain)",
  "  Its former warmth around another.",
  ""
]