module.exports = [
  "The kiss, dear maid! thy lip has left",
  "  Shall never part from mine,",
  "Till happier hours restore the gift",
  "  Untainted back to thine.",
  "",
  "Thy parting glance, which fondly beams,",
  "  An equal love may see:",
  "The tear that from thine eyelid streams",
  "  Can weep no change in me.",
  "",
  "I ask no pledge to make me blest",
  "  In gazing when alone;",
  "Nor one memorial for a breast,",
  "  Whose thoughts are all thine own.",
  "",
  "Nor need I write--to tell the tale",
  "  My pen were doubly weak:",
  "Oh! what can idle words avail,",
  "  Unless the heart could speak?",
  "",
  "By day or night, in weal or woe,",
  "  That heart, no longer free,",
  "Must bear the love it cannot show,",
  "  And silent ache for thee.",
  ""
]