module.exports = [
  "A HERMIT'S house beside a stream",
  "  With forests planted round,",
  "Whatever it to you may seem",
  "More real happiness I deem",
  "  Than if I were a monarch crowned.",
  "",
  "A cottage I could call my own",
  "  Remote from domes of care;",
  "A little garden, walled with stone,",
  "The wall with ivy overgrown,",
  "  A limpid fountain near,",
  "",
  "Would more substantial joys afford,",
  "  More real bliss impart",
  "Than all the wealth that misers hoard,",
  "Than vanquished worlds, or worlds restored--",
  "  Mere cankers of the heart!",
  "",
  "Vain, foolish man! how vast thy pride,",
  "  How little can your wants supply!--",
  "'Tis surely wrong to grasp so wide--",
  "You act as if you only had",
  "  To triumph--not to die!",
  ""
]