module.exports = [
  "IMMITATION OF ENGLISH POETS. EARL OF ROCHESTER",
  "",
  "   Silence! coeval with eternity;",
  "   Thou wert, ere Nature's self began to be,",
  "'Twas one vast Nothing all, and all slept fast in thee.",
  "",
  "   Thine was the sway, ere heaven was form'd, or earth,",
  "   Ere fruitful Thought conceived Creation's birth,",
  "Or midwife Word gave aid, and spoke the infant forth.",
  "",
  "   Then various elements against thee join'd,",
  "   In one more various animal combined,",
  "And framed the clamorous race of busy humankind.",
  "",
  "   The tongue moved gently first, and speech was low,",
  "   Till wrangling Science taught it noise and show,",
  "And wicked Wit arose, thy most abusive foe.",
  "",
  "   But rebel Wit deserts thee oft in vain;",
  "   Lost in the maze of words he turns again,",
  "And seeks a surer state, and courts thy gentle reign.",
  "",
  "   Afflicted Sense thou kindly dost set free,",
  "   Oppress'd with argumental tyranny,",
  "And routed Reason finds a safe retreat in thee.",
  "",
  "   With thee in private modest Dulness lies,",
  "   And in thy bosom lurks in Thought's disguise;",
  "Thou varnisher of fools, and cheat of all the wise!",
  "",
  "   Yet thy indulgence is by both confess'd;",
  "   Folly by thee lies sleeping in the breast,",
  "And 'tis in thee at last that Wisdom seeks for rest.",
  "",
  "   Silence! the knave's repute, the whore's good name,",
  "   The only honour of the wishing dame;",
  "Thy very want of tongue makes thee a kind of fame.",
  "",
  "   But couldst thou seize some tongues that now are free,",
  "   How Church and State should be obliged to thee!",
  "At Senate, and at Bar, how welcome would'st thou be!",
  "",
  "   Yet Speech even there submissively withdraws",
  "   From rights of subjects, and the poor man's cause:",
  "Then pompous Silence reigns, and stills the noisy laws.",
  "",
  "   Past services of friends, good deeds of foes,",
  "   What favourites gain, and what the nation owes,",
  "Fly the forgetful world, and in thy arms repose.",
  "",
  "   The country wit, religion of the town,",
  "   The courtier's learning, policy o' the gown,",
  "Are best by thee express'd, and shine in thee alone.",
  "",
  "   The parson's cant, the lawyer's sophistry,",
  "   Lord's quibble, critic's jest, all end in thee,",
  "All rest in peace at last, and sleep eternally.",
  ""
]