module.exports = [
  "Star of the brave!--whose beam hath shed",
  "Such glory o'er the quick and dead--",
  "Thou radiant and adored deceit!",
  "Which millions rushed in arms to greet,--",
  "Wild meteor of immortal birth!",
  "Why rise in Heaven to set on Earth?",
  "",
  "Souls of slain heroes formed thy rays;",
  "Eternity flashed through thy blaze;",
  "The music of thy martial sphere",
  "Was fame on high and honour here;",
  "And thy light broke on human eyes,",
  "Like a Volcano of the skies.",
  "",
  "Like lava rolled thy stream of blood,",
  "And swept down empires with its flood;",
  "Earth rocked beneath thee to her base,",
  "As thou didst lighten through all space;",
  "And the shorn Sun grew dim in air,",
  "And set while thou wert dwelling there.",
  "",
  "Before thee rose, and with thee grew,",
  "A rainbow of the loveliest hue",
  "Of three bright colours, each divine,",
  "And fit for that celestial sign;",
  "For Freedom's hand had blended them,",
  "Like tints in an immortal gem.",
  "",
  "One tint was of the sunbeam's dyes;",
  "One, the blue depth of Seraph's eyes;",
  "One, the pure Spirit's veil of white",
  "Had robed in radiance of its light:",
  "The three so mingled did beseem",
  "The texture of a heavenly dream.",
  "",
  "Star of the brave! thy ray is pale,",
  "And darkness must again prevail!",
  "But, oh thou Rainbow of the free!",
  "Our tears and blood must flow for thee.",
  "When thy bright promise fades away,",
  "Our life is but a load of clay.",
  "",
  "And Freedom hallows with her tread",
  "The silent cities of the dead;",
  "For beautiful in death are they",
  "Who proudly fall in her array;",
  "And soon, oh, Goddess! may we be",
  "For evermore with them or thee!",
  ""
]