module.exports = [
  "'T IS time this heart should be unmoved,",
  "  Since others it hath ceased to move:",
  "Yet, though I cannot be beloved,",
  "            Still let me love!",
  "",
  "My days are in the yellow leaf;",
  "  The flowers and fruits of Love are gone;",
  "The worm, the canker, and the grief",
  "  Are mine alone!",
  "",
  "The fire that on my bosom preys",
  "  Is lone as some Volcanic isle;",
  "No torch is kindled at its blaze--",
  "  A funeral pile.",
  "",
  "The hope, the fear, the jealous care,",
  "  The exalted portion of the pain",
  "And power of love, I cannot share,",
  "  But wear the chain.",
  "",
  "But 't is not _thus_--and 't is not _here_--",
  "  Such thoughts should shake my soul, nor now",
  "Where Glory decks the hero's bier,",
  "  Or binds his brow.",
  "",
  "The Sword, the Banner, and the Field,",
  "  Glory and Greece, around me see!",
  "The Spartan, borne upon his shield,",
  "  Was not more free.",
  "",
  "Awake! (not Greece--she _is_ awake!)",
  "  Awake, my spirit! Think through _whom_",
  "Thy life-blood tracks its parent lake,",
  "  And then strike home!",
  "",
  "Tread those reviving passions down,",
  "  Unworthy manhood!--unto thee",
  "Indifferent should the smile or frown",
  "  Of Beauty be.",
  "",
  "If thou regret'st thy youth, _why live_?",
  "  The land of honourable death",
  "Is here:--up to the Field, and give",
  "  Away thy breath!",
  "",
  "Seek out--less often sought than found--",
  "  A soldier's grave, for thee the best;",
  "Then look around, and choose thy ground,",
  "  And take thy Rest.",
  ""
]