module.exports = [
  "From the last hill that looks on thy once holy dome,",
  "I beheld thee, oh Sion! when rendered to Rome:",
  "'Twas thy last sun went down, and the flames of thy fall",
  "Flashed back on the last glance I gave to thy wall.",
  "",
  "I looked for thy temple--I looked for my home,",
  "And forgot for a moment my bondage to come;",
  "I beheld but the death-fire that fed on thy fane,",
  "And the fast-fettered hands that made vengeance in vain.",
  "",
  "On many an eve, the high spot whence I gazed",
  "Had reflected the last beam of day as it blazed;",
  "While I stood on the height, and beheld the decline",
  "Of the rays from the mountain that shone on thy shrine.",
  "",
  "And now on that mountain I stood on that day,",
  "But I marked not the twilight beam melting away;",
  "Oh! would that the lightning had glared in its stead,",
  "And the thunderbolt burst on the Conqueror's head!",
  "",
  "But the Gods of the Pagan shall never profane",
  "The shrine where Jehovah disdained not to reign;",
  "And scattered and scorned as thy people may be,",
  "Our worship, oh Father! is only for thee.",
  ""
]