module.exports = [
  "One struggle more, and I am free",
  "  From pangs that rend my heart in twain;",
  "One last long sigh to Love and thee,",
  "  Then back to busy life again.",
  "It suits me well to mingle now",
  "  With things that never pleased before:",
  "Though every joy is fled below,",
  "  What future grief can touch me more?",
  "",
  "Then bring me wine, the banquet bring;",
  "  Man was not formed to live alone:",
  "I'll be that light unmeaning thing",
  "  That smiles with all, and weeps with none.",
  "It was not thus in days more dear,",
  "  It never would have been, but thou",
  "Hast fled, and left me lonely here;",
  "  Thou'rt nothing,--all are nothing now.",
  "",
  "In vain my lyre would lightly breathe!",
  "  The smile that Sorrow fain would wear",
  "But mocks the woe that lurks beneath,",
  "  Like roses o'er a sepulchre.",
  "Though gay companions o'er the bowl",
  "  Dispel awhile the sense of ill;",
  "Though Pleasure fires the maddening soul,",
  "  The Heart,--the Heart is lonely still!",
  "",
  "On many a lone and lovely night",
  "  It soothed to gaze upon the sky;",
  "For then I deemed the heavenly light",
  "  Shone sweetly on thy pensive eye:",
  "And oft I thought at Cynthia's noon,",
  "  When sailing o'er the Ægean wave,",
  "\"Now Thyrza gazes on that moon\"--",
  "  Alas, it gleamed upon her grave!",
  "",
  "When stretched on Fever's sleepless bed,",
  "  And sickness shrunk my throbbing veins,",
  "\"'Tis comfort still,\" I faintly said,",
  "  \"That Thyrza cannot know my pains:\"",
  "Like freedom to the time-worn slave--",
  "  A boon 'tis idle then to give--",
  "Relenting Nature vainly gave",
  "  My life, when Thyrza ceased to live!",
  "",
  "My Thyrza's pledge in better days,",
  "  When Love and Life alike were new!",
  "How different now thou meet'st my gaze!",
  "  How tinged by time with Sorrow's hue!",
  "The heart that gave itself with thee",
  "  Is silent--ah, were mine as still!",
  "Though cold as e'en the dead can be,",
  "  It feels, it sickens with the chill.",
  "",
  "Thou bitter pledge! thou mournful token!",
  "  Though painful, welcome to my breast!",
  "Still, still, preserve that love unbroken,",
  "  Or break the heart to which thou'rt pressed.",
  "Time tempers Love, but not removes,",
  "  More hallowed when its Hope is fled:",
  "Oh! what are thousand living loves",
  "  To that which cannot quit the dead?",
  ""
]