module.exports = [
  "Here I sit with my paper, my pen and my ink,",
  "First of this thing, and that thing, and t'other thing think;",
  "Then my thoughts come so pell-mell all into my mind,",
  "That the sense or the subject I never can find:",
  "This word is wrong placed,--no regard to the sense,",
  "The present and future, instead of past tense,",
  "Then my grammar I want; O dear! what a bore,",
  "I think I shall never attempt to write more,",
  "With patience I then my thoughts must arraign,",
  "Have them all in due order like mutes in a train,",
  "Like them too must wait in due patience and thought,",
  "Or else my fine works will all come to nought.",
  "My wit too's so copious, it flows like a river,",
  "But disperses its waters on black and white never;",
  "Like smoke it appears independent and free,",
  "But ah luckless smoke! it all passes like thee--",
  "Then at length all my patience entirely lost,",
  "My paper and pens in the fire are tossed;",
  "But come, try again--you must never despair,",
  "Our Murray's or Entick's are not all so rare,",
  "Implore their assistance--they'll come to your aid,",
  "Perform all your business without being paid,",
  "They'll tell you the present tense, future and past,",
  "Which should come first, and which should come last,",
  "This Murray will do--then to Entick repair,",
  "To find out the meaning of any word rare.",
  "This they friendly will tell, and ne'er make you blush,",
  "With a jeering look, taunt, or an O fie! tush!",
  "Then straight all your thoughts in black and white put,",
  "Not minding the if's, the be's, and the but,",
  "Then read it all over, see how it will run,",
  "How answers the wit, the retort, and the pun,",
  "Your writings may then with old Socrates vie,",
  "May on the same shelf with Demosthenes lie,",
  "May as Junius be sharp, or as Plato be sage.",
  "The pattern or satire to all of the age;",
  "But stop--a mad author I mean not to turn,",
  "Nor with thirst of applause does my heated brain burn,",
  "Sufficient that sense, wit, and grammar combined,",
  "My letters may make some slight food for the mind;",
  "That my thoughts to my friends I may freely impart,",
  "In all the warm language that flows from the heart.",
  "Hark! futurity calls! it loudly complains,",
  "It bids me step forward and just hold the reins,",
  "My excuse shall be humble, and faithful, and true,",
  "Such as I fear can be made but by few--",
  "Of writers this age has abundance and plenty,",
  "Three score and a thousand, two millions and twenty,",
  "Three score of them wits who all sharply vie,",
  "To try what odd creature they best can belie,",
  "A thousand are prudes who for CHARITY write,",
  "And fill up their sheets with spleen, envy, and spite[,]",
  "One million are bards, who to Heaven aspire,",
  "And stuff their works full of bombast, rant, and fire,",
  "T'other million are wags who in Grubstreet attend,",
  "And just like a cobbler the old writings mend,",
  "The twenty are those who for pulpits indite,",
  "And pore over sermons all Saturday night.",
  "And now my good friends--who come after I mean,",
  "As I ne'er wore a cassock, or dined with a dean.",
  "Or like cobblers at mending I never did try,",
  "Nor with poets in lyrics attempted to vie;",
  "As for prudes these good souls I both hate and detest,",
  "So here I believe the matter must rest.--",
  "I've heard your complaint--my answer I've made,",
  "And since to your calls all the tribute I've paid,",
  "Adieu my good friend; pray never despair,",
  "But grammar and sense and everything dare,",
  "Attempt but to write dashing, easy, and free,",
  "Then take out your grammar and pay him his fee,",
  "Be not a coward, shrink not to a tense,",
  "But read it all over and make it out sense.",
  "What a tiresome girl!--pray soon make an end,",
  "Else my limited patience you'll quickly expend.",
  "Well adieu, I no longer your patience will try--",
  "So swift to the post now the letter shall fly.",
  ""
]