module.exports = [
  "OUT in the dark over the snow",
  "The fallow fawns invisible go",
  "With the fallow doe;",
  "And the winds blow",
  "Fast as the stars are slow.",
  "",
  "Stealthily the dark haunts round",
  "And, when a lamp goes, without sound",
  "At a swifter bound",
  "Than the swiftest hound,",
  "Arrives, and all else is drowned;",
  "",
  "And I and star and wind and deer,",
  "Are in the dark together,--near,",
  "Yet far,--and fear",
  "Drums on my ear",
  "In that sage company drear.",
  "",
  "How weak and little is the light,",
  "All the universe of sight,",
  "Love and delight,",
  "Before the might,",
  "If you love it not, of night.",
  ""
]