module.exports = [
  "  _Half stolen_, with acknowledgments, to be spoken in an",
  "  inarticulate voice by Master ---- at the opening of the next",
  "  new theatre.",
  "",
  "\"When energising objects men pursue,\"",
  "Then Lord knows what is writ by Lord knows who.",
  "A modest Monologue you here survey,",
  "Hissed from the theatre the \"other day,\"",
  "As if Sir Fretful wrote \"the slumberous\" verse,",
  "And gave his son \"the rubbish\" to rehearse.",
  "\"Yet at the thing you'd never be amazed,\"",
  "Knew you the rumpus which the Author raised;",
  "\"Nor even here your smiles would be represt,\"",
  "Knew you these lines--the badness of the best,",
  "\"Flame! fire! and flame!\" (words borrowed from Lucretius.)",
  "\"Dread metaphors\" which open wounds like issues!",
  "\"And sleeping pangs awake--and----But away\"--",
  "(Confound me if I know what next to say).",
  "Lo \"Hope reviving re-expands her wings,\"",
  "And Master G---- recites what Dr. Busby sings!--",
  "\"If mighty things with small we may compare,\"",
  "(Translated from the Grammar for the fair!)",
  "Dramatic \"spirit drives a conquering car,\"",
  "And burn'd poor Moscow like a tub of \"tar.\"",
  "\"This spirit\" \"Wellington has shown in Spain,\"",
  "To furnish Melodrames for Drury Lane.",
  "\"Another Marlborough points to Blenheim's story,\"",
  "And George and I will dramatise it for ye.",
  "",
  "  \"In Arts and Sciences our Isle hath shone\"",
  "(This deep discovery is mine alone).",
  "Oh \"British poesy, whose powers inspire\"",
  "My verse--or I'm a fool--and Fame's a liar,",
  "\"Thee we invoke, your Sister Arts implore\"",
  "With \"smiles,\" and \"lyres,\" and \"pencils,\" and much more.",
  "These, if we win the Graces, too, we gain",
  "_Disgraces_, too! \"inseparable train!\"",
  "\"Three who have stolen their witching airs from Cupid\"",
  "(You all know what I mean, unless you're stupid):",
  "\"Harmonious throng\" that I have kept _in petto_",
  "Now to produce in a \"divine _sestetto_\"!!",
  "\"While Poesy,\" with these delightful doxies,",
  "\"Sustains her part\" in all the \"upper\" boxes!",
  "\"Thus lifted gloriously, you'll sweep along,\"",
  "Borne in the vast balloon of Busby's song;",
  "\"Shine in your farce, masque, scenery, and play\"",
  "(For this last line George had a holiday).",
  "\"Old Drury never, never soar'd so high,\"",
  "So says the Manager, and so say I.",
  "\"But hold,\" you say, \"this self-complacent boast;\"",
  "Is this the Poem which the public lost?",
  "\"True--true--that lowers at once our mounting pride;\"",
  "But lo;--the Papers print what you deride.",
  "\"'Tis ours to look on _you_--_you_ hold the prize,\"",
  "'Tis _twenty guineas_, as they advertise!",
  "\"A _double_ blessing your rewards impart\"--",
  "I wish I had them, then, with all my heart.",
  "\"Our _twofold_ feeling _owns_ its twofold cause,\"",
  "Why son and I both beg for your applause.",
  "\"When in your fostering beams you bid us live,\"",
  "My next subscription list shall say how much you give!",
  ""
]