module.exports = [
  "WHEN by Zeus relenting the mandate was revoked,",
  "   Sentencing to exile the bright Sun-God,",
  "Mindful were the ploughmen of who the steer had yoked,",
  "   Who: and what a track show'd the upturn'd sod!",
  "Mindful were the shepherds, as now the noon severe",
  "   Bent a burning eyebrow to brown evetide,",
  "How the rustic flute drew the silver to the sphere,",
  "   Sister of his own, till her rays fell wide.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "Chirping none, the scarlet cicalas crouch'd in ranks:",
  "   Slack the thistle-head piled its down-silk gray:",
  "Scarce the stony lizard suck'd hollows in his flanks:",
  "   Thick on spots of umbrage our drowsed flocks lay.",
  "Sudden bow'd the chestnuts beneath a wind unheard,",
  "   Lengthen'd ran the grasses, the sky grew slate:",
  "Then amid a swift flight of wing'd seed white as curd,",
  "   Clear of limb a Youth smote the master's gate.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "Water, first of singers, o'er rocky mount and mead,",
  "   First of earthly singers, the sun-loved rill,",
  "Sang of him, and flooded the ripples on the reed,",
  "   Seeking whom to waken and what ear fill.",
  "Water, sweetest soother to kiss a wound and cool,",
  "   Sweetest and divinest, the sky-born brook,",
  "Chuckled, with a whimper, and made a mirror-pool",
  "   Round the guest we welcomed, the strange hand shook.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "Many swarms of wild bees descended on our fields:",
  "   Stately stood the wheatstalk with head bent high:",
  "Big of heart we labour'd at storing mighty yields,",
  "   Wool and corn, and clusters to make men cry!",
  "Hand-like rush'd the vintage; we strung the bellied skins",
  "   Plump, and at the sealing the Youth's voice rose:",
  "Maidens clung in circle, on little fists their chins;",
  "   Gentle beasties through push'd a cold long nose.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "Foot to fire in snowtime we trimm'd the slender shaft:",
  "   Often down the pit spied the lean wolf's teeth",
  "Grin against his will, trapp'd by masterstrokes of craft;",
  "   Helpless in his froth-wrath as green logs seethe!",
  "Safe the tender lambs tugg'd the teats, and winter sped",
  "   Whirl'd before the crocus, the year's new gold.",
  "Hung the hooky beak up aloft, the arrowhead",
  "   Redden'd through his feathers for our dear fold.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "Tales we drank of giants at war with gods above:",
  "   Rocks were they to look on, and earth climb'd air!",
  "Tales of search for simples, and those who sought of love",
  "   Ease because the creature was all too fair.",
  "Pleasant ran our thinking that while our work was good.",
  "   Sure as fruits for sweat would the praise come fast.",
  "He that wrestled stoutest and tamed the billow-brood",
  "   Danced in rings with girls, like a sail-flapp'd mast.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "Lo, the herb of healing, when once the herb is known,",
  "   Shines in shady woods bright as new-sprung flame.",
  "Ere the string was tighten'd we heard the mellow tone,",
  "   After he had taught how the sweet sounds came.",
  "Stretch'd about his feet, labour done, 'twas as you see",
  "   Red pomegranates tumble and burst hard rind.",
  "So began contention to give delight and be",
  "   Excellent in things aim'd to make life kind.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "You with shelly horns, rams! and, promontory goats,",
  "   You whose browsing beards dip in coldest dew!",
  "Bulls, that walk the pastures in kingly-flashing coats!",
  "   Laurel, ivy, vine, wreathed for feasts not few!",
  "You that build the shade-roof, and you that court the rays,",
  "   You that leap besprinkling the rock stream-rent:",
  "He has been our fellow, the morning of our days;",
  "   Us he chose for housemates, and this way went.",
  "   God! of whom music",
  "   And song and blood are pure,",
  "   The day is never darken'd",
  "   That had thee here obscure.",
  "",
  "   NOW the North wind ceases,",
  "   The warm South-west awakes;",
  "   Swift fly the fleeces,",
  "   Thick the blossom-flakes.",
  "",
  "Now hill to hill has made the stride,",
  "And distance waves the without-end:",
  "Now in the breast a door flings wide;",
  "Our farthest smiles, our next is friend.",
  "And song of England's rush of flowers",
  "Is this full breeze with mellow stops,",
  "That spins the lark for shine, for showers;",
  "He drinks his hurried flight, and drops.",
  "The stir in memory seem these things,",
  "Which out of moisten'd turf and clay,",
  "Astrain for light push patient rings,",
  "Or leap to find the waterway.",
  "'Tis equal to a wonder done,",
  "Whatever simple lives renew",
  "Their tricks beneath the father sun,",
  "As though they caught a broken clue:",
  "So hard was earth an eyewink back;",
  "But now the common life has come,",
  "The blotting cloud a dappled pack,",
  "The grasses one vast underhum.",
  "A City clothed in snow and soot,",
  "With lamps for day in ghostly rows,",
  "Breaks to the scene of hosts afoot,",
  "The river that reflective flows:",
  "And there did fog down crypts of street",
  "Play spectre upon eye and mouth:--",
  "Their faces are a glass to greet",
  "This magic of the whirl for South.",
  "A burly joy each creature swells",
  "With sound of its own hungry quest;",
  "Earth has to fill her empty wells,",
  "And speed the service of the nest;",
  "The phantom of the snow-wreath melt,",
  "That haunts the farmer's look abroad,",
  "Who sees what tomb a white night built,",
  "Where flocks now bleat and sprouts the clod.",
  "For iron Winter held her firm;",
  "Across her sky he laid his hand;",
  "And bird he starved, he stiffen'd worm;",
  "A sightless heaven, a shaven land.",
  "Her shivering Spring feign'd fast asleep,",
  "The bitten buds dared not unfold:",
  "We raced on roads and ice to keep",
  "Thought of the girl we love from cold.",
  "",
  "   But now the North wind ceases,",
  "   The warm South-west awakes,",
  "   The heavens are out in fleeces,",
  "   And earth's green banner shakes.",
  ""
]