module.exports = [
  "IMMITATION OF ENGLISH POETS. EARL OF DORSET",
  "",
  "  Phryne had talents for mankind,",
  "  Open she was, and unconfined,",
  "    Like some free port of trade:",
  "  Merchants unloaded here their freight,",
  "  And agents from each foreign state",
  "    Here first their entry made.",
  "",
  "  Her learning and good breeding such,",
  "  Whether the Italian or the Dutch,",
  "    Spaniards or French came to her:",
  "  To all obliging she'd appear,",
  "  'Twas 'Si, Signor,' 'twas 'Yaw, Mynheer,'",
  "    'Twas 'S' il vous plaît, Monsieur.'",
  "",
  "  Obscure by birth, renown'd by crimes,",
  "  Still changing names, religions, climes,",
  "    At length she turns a bride:",
  "  In diamonds, pearls, and rich brocades,",
  "  She shines the first of batter'd jades,",
  "    And flutters in her pride.",
  "",
  "  So have I known those insects fair,",
  "  (Which curious Germans hold so rare)",
  "    Still vary shapes and dyes;",
  "  Still gain new titles with new forms;",
  "  First grubs obscene, then wriggling worms,",
  "    Then painted butterflies.",
  ""
]