module.exports = [
  "Gracious Lord, our children see,",
  "By Thy mercy we are free;",
  "But shall these, alas! remain",
  "Subjects still of Satan's reign?",
  "Israel's young ones, when of old",
  "Pharaoh threaten'd to withhold,",
  "Then Thy messenger said, \"No;",
  "Let the children also go!\"",
  "",
  "When the angel of the Lord,",
  "Drawing forth his dreadful sword,",
  "Slew with an avenging hand,",
  "All the first-born of the land;",
  "Then Thy people's door he pass'd,",
  "Where the bloody sign was placed:",
  "Hear us, now, upon our knees,",
  "Plead the blood of Christ for these!",
  "",
  "Lord, we tremble, for we know",
  "How the fierce malicious foe,",
  "Wheeling round his watchful flight,",
  "Keeps them ever in his sight:",
  "Spread Thy pinions, King of kings!",
  "Hide them safe beneath Thy wings;",
  "Lest the ravenous bird of prey",
  "Stoop and bear the brood away.",
  ""
]