module.exports = [
  "Lord, who hast suffer'd all for me,",
  "My peace and pardon to procure,",
  "The lighter cross I bear for Thee,",
  "Help me with patience to endure.",
  "",
  "The storm of loud repining hush;",
  "I would in humble silence mourn;",
  "Why should the unburnt, though burning bush,",
  "Be angry as the crackling thorn?",
  "",
  "Man should not faint at Thy rebuke,",
  "Like Joshua falling on his face,",
  "When the cursed thing that Achan took",
  "Brought Israel into just disgrace.",
  "",
  "Perhaps some golden wedge suppress'd,",
  "Some secret sin offends my God;",
  "Perhaps that Babylonish vest,",
  "Self-righteousness, provokes the rod.",
  "",
  "Ah! were I buffeted all day,",
  "Mock'd, crown'd with thorns and spit upon,",
  "I yet should have no right to say,",
  "My great distress is mine alone.",
  "",
  "Let me not angrily declare",
  "No pain was ever sharp like mine,",
  "Nor murmur at the cross I bear,",
  "But rather weep, remembering Thine.",
  ""
]