module.exports = [
  "Now I 'm convinced the Lord is kind",
  "To men of heart sincere;",
  "Yet once my foolish thoughts repined,",
  "And bordered on despair.",
  "",
  "I grieved to see the wicked thrive,",
  "And spoke with angry breath,",
  "\"How pleasant and profane they live !",
  "How peaceful is their death !",
  "",
  "\"With well-fed flesh and haughty eyes,",
  "They lay their fears to sleep;",
  "Against the heav'ns their slanders rise,",
  "While saints in silence weep.",
  "",
  "\"In vain I lift my hands to pray,",
  "And cleanse my heart in vain;",
  "For I am chastened all the day,",
  "The night renews my pain.\"",
  "",
  "Yet while my tongue indulged complaints,",
  "I felt my heart reprove,",
  "\"Sure I shall thus offend thy saints,",
  "And grieve the men I love.\"",
  "",
  "But still I found my doubts too hard,",
  "The conflict too severe,",
  "Till I retired to search thy word,",
  "And learn thy secrets there.",
  "",
  "There, as in some prophetic glass,",
  "I saw the sinner's feet",
  "High mounted on a slipp'ry place,",
  "Beside a fiery pit.",
  "",
  "I heard the wretch profanely boast,",
  "Till at thy frown he fell;",
  "His honors in a dream were lost,",
  "And he awakes in hell.",
  "",
  "Lord, what an envious fool I was!",
  "How like a thoughtless beast",
  "Thus to suspect thy promised grace,",
  "And think the wicked blessed.",
  "",
  "Yet I was kept from full despair,",
  "Upheld by power unknown;",
  "That blessed hand that broke the snare",
  "Shall guide me to thy throne.",
  "",
  "God, my supporter and my hope,",
  "My help for ever near,",
  "Thine arm of mercy held me up,",
  "When sinking in despair.",
  "",
  "Thy counsels, Lord, shall guide my feet",
  "Through this dark wilderness;",
  "Thine hand conduct me near thy seat,",
  "To dwell before thy face.",
  "",
  "Were I in heav'n without my God,",
  "'twould be no joy to me;",
  "And whilst this earth is my abode,",
  "I long for none but thee.",
  "",
  "What if the springs of life were broke,",
  "And flesh and heart should faint?",
  "God is my soul's eternal rock,",
  "The strength of ev'ry saint.",
  "",
  "Behold, the sinners that remove",
  "Far from thy presence die;",
  "Not all the idol gods they love",
  "Can save them when they cry.",
  "",
  "But to draw near to thee, my God,",
  "Shall be my sweet employ;",
  "My tongue shall sound thy works abroad,",
  "And tell the world my joy.",
  "",
  "Lord, what a thoughtless wretch was I,",
  "To mourn, and murmur, and repine,",
  "To see the wicked placed on high,",
  "In pride and robes of' honour shine!",
  "",
  "But O their end, their dreadful end!",
  "Thy sanctuary taught me so;",
  "On slipp'ry rocks I see them stand,",
  "And fiery billows roll below.",
  "",
  "Now let them boast how tall they rise,",
  "I'll never envy them again;",
  "There they may stand with haughty eyes,",
  "Till they plunge deep in endless pain.",
  "",
  "Their fancied joys, how fast they flee!",
  "Just like a dream when man awakes;",
  "Their songs of softest harmony",
  "Are but a preface to their plagues.",
  "",
  "Now I esteem their mirth and wine",
  "Too dear to purchase with my blood;",
  "Lord, 'tis enough that thou art mine,",
  "My life, my portion, and my God.",
  "",
  "Sure there's a righteous God,",
  "Nor is religion vain;",
  "Though men of vice may boast aloud,",
  "And men of grace complain.",
  "",
  "I saw the wicked rise,",
  "And felt my heart repine,",
  "While haughty fools with scornful eyes",
  "In robes of' honor shine.",
  "",
  "Pampered with wanton ease,",
  "Their flesh looks full and fair;",
  "Their wealth rolls in like flowing seas,",
  "And grows without their care.",
  "",
  "Free from the plagues and pains",
  "That pious souls endure;",
  "Through all their life oppression reigns,",
  "And racks the humble poor.",
  "",
  "Their impious tongues blaspheme",
  "The everlasting God;",
  "Their malice blasts the good man's name,",
  "And spreads their lies abroad.",
  "",
  "But I with flowing tears",
  "Indulged my doubts to rise;",
  "\"Is there a God that sees or hears",
  "The things below the skies?\"",
  "",
  "The tumults of my thought",
  "Held me in hard suspense,",
  "Till to thy house my feet were brought,",
  "To learn thy justice thence.",
  "",
  "Thy word with light and power",
  "Did my mistake amend;",
  "I viewed the sinners' life before,",
  "But here I learned their end.",
  "",
  "On what a slippery steep",
  "The thoughtless wretches go;",
  "And O that dreadful fiery deep",
  "That waits their fall below!",
  "",
  "Lord, at thy feet I bow,",
  "My thoughts no more repine;",
  "I call my God my portion now,",
  "And all my powers are thine.",
  ""
]