module.exports = [
  "The heavens declare thy glory, Lord,",
  "In every star thy wisdom shines;",
  "But when our eyes behold thy word,",
  "We read thy name in fairer lines.",
  "",
  "The rolling sun, the changing light,",
  "And night and day, thy power confess;",
  "But the blest volume thou hast writ",
  "Reveals thy justice and thy grace.",
  "",
  "Sun, moon, and stars convey thy praise",
  "Round the whole earth, and never stand;",
  "So when thy truth began its race,",
  "It touched and glanced on every land.",
  "",
  "Nor shall thy spreading gospel rest",
  "Till through the world thy truth has run",
  "Till Christ has all the nations blest,",
  "That see the light or feel the sun.",
  "",
  "Great Sun of righteousness, arise,",
  "Bless the dark world with heavenly light:",
  "Thy gospel makes the simple wise;",
  "Thy laws are pure, thy judgments right.",
  ""
]