module.exports = [
  "v.12-15",
  "L. M.",
  "Grace above riches; or, The happy nation.",
  "",
  "Happy the city where their sons,",
  "Like pillars round a palace set,",
  "And daughters, bright as polished stones,",
  "Give strength and beauty to the state.",
  "",
  "Happy the country where the sheep,",
  "Cattle, and corn, have large increase;",
  "Where men securely work or sleep,",
  "Nor sons of plunder break the peace.",
  "",
  "Happy the nation thus endowed,",
  "But more divinely blest are those",
  "On whom the all-sufficient God",
  "Himself with all his grace bestows.",
  ""
]