module.exports = [
  "Rearrange a \"Wife's\" affection!",
  "When they dislocate my Brain!",
  "Amputate my freckled Bosom!",
  "Make me bearded like a man!",
  "",
  "Blush, my spirit, in thy Fastness --",
  "Blush, my unacknowledged clay --",
  "Seven years of troth have taught thee",
  "More than Wifehood every may!",
  "",
  "Love that never leaped its socket --",
  "Trust entrenched in narrow pain --",
  "Constancy thro' fire -- awarded --",
  "Anguish -- bare of anodyne!",
  "",
  "Burden -- borne so far triumphant --",
  "None suspect me of the crown,",
  "For I wear the \"Thorns\" till Sunset --",
  "Then -- my Diadem put on.",
  "",
  "Big my Secret but it's bandaged --",
  "It will never get away",
  "Till the Day its Weary Keeper",
  "Leads it through the Grave to thee.",
  ""
]