module.exports = [
  "  Why, Pigot, complain",
  "  Of this damsel's disdain,",
  "Why thus in despair do you fret?",
  "  For months you may try,",
  "  Yet, believe me, a _sigh_",
  "Will never obtain a _coquette_.",
  "",
  "   Would you teach her to love?",
  "   For a time seem to rove;",
  "At first she may _frown_ in a _pet;_",
  "   But leave her awhile,",
  "   She shortly will smile,",
  "And then you may _kiss_ your _coquette_.",
  "",
  "   For such are the airs",
  "   Of these fanciful fairs,",
  "They think all our _homage_ a _debt_:",
  "   Yet a partial neglect",
  "   Soon takes an effect,",
  "And humbles the proudest _coquette_.",
  "",
  "   Dissemble your pain,",
  "   And lengthen your chain,",
  "And seem her _hauteur_ to _regret;_",
  "   If again you shall sigh,",
  "   She no more will deny,",
  "That _yours_ is the rosy _coquette_.",
  "",
  "   If still, from false pride,",
  "   Your pangs she deride,",
  "This whimsical virgin forget;",
  "   Some _other_ admire,",
  "   Who will _melt_ with your _fire_,",
  "And laugh at the _little coquette_.",
  "",
  "   For _me_, I adore",
  "   Some _twenty_ or more,",
  "And love them most dearly; but yet,",
  "   Though my heart they enthral,",
  "   I'd abandon them all,",
  "Did they act like your blooming _coquette_.",
  "",
  "   No longer repine,",
  "   Adopt this design,",
  "And break through her slight-woven net!",
  "   Away with despair,",
  "   No longer forbear",
  "To fly from the captious _coquette_.",
  "",
  "  Then quit her, my friend!",
  "  Your bosom defend,",
  "Ere quite with her snares you're beset:",
  "  Lest your deep-wounded heart,",
  "  When incens'd by the smart,",
  "Should lead you to _curse_ the _coquette_.",
  ""
]