module.exports = [
  "Far from the world, O Lord, I flee,",
  "From strife and tumult far;",
  "From scenes where Satan wages still",
  "His most successful war.",
  "",
  "The calm retreat, the silent shade,",
  "With prayer and praise agree;",
  "And seem, by Thy sweet bounty made,",
  "For those who follow Thee.",
  "",
  "There if Thy Spirit touch the soul,",
  "And grace her mean abode,",
  "Oh, with what peace, and joy, and love,",
  "She communes with her God!",
  "",
  "There like the nightingale she pours",
  "Her solitary lays;",
  "Nor asks a witness of her song,",
  "Nor thirsts for human praise.",
  "",
  "Author and Guardian of my life,",
  "Sweet source of light Divine,",
  "And, -- all harmonious names in one, --",
  "My Saviour! Thou art mine.",
  "",
  "What thanks I owe Thee, and what love,",
  "A boundless, endless store,",
  "Shall echo through the realms above,",
  "When time shall be no more.",
  ""
]