module.exports = [
  "Richard Pigott, the forger, was a very bad man,",
  "And to gainsay it there's nobody can,",
  "Because for fifty years he pursued a career of deceit,",
  "And as a forger few men with him could compete.",
  "",
  "For by forged letters he tried to accuse Parnell",
  "For the Phoenix Park murders, but mark what befell.",
  "When his conscience smote him he confessed to the fraud,",
  "And the thought thereof no doubt drove him mad.",
  "",
  "Then he fled from London without delay,",
  "Knowing he wouldn't be safe there night nor day,",
  "And embarked on board a ship bound for Spain,",
  "Thinking he would escape detection there, but 'twas all in vain.",
  "",
  "Because while staying at a hotel in Spain",
  "He appeared to the landlord to be a little insane.",
  "And he noticed he was always seemingly in dread,",
  "Like a person that had committed a murder and afterwards fled.",
  "",
  "And when arrested in the hotel he seemed very cool,",
  "Just like an innocent schoolboy going to school.",
  "And he said to the detectives, \"Wait until my portmanteau I've got.\"",
  "And while going for his portmanteau, himself he shot.",
  "",
  "So perished Richard Pigott, a forger bold,",
  "Who tried to swear Parnell's life away for the sake of gold,",
  "But the vengeance of God overtook him,",
  "And Parnell's life has been saved, which I consider no sin.",
  "",
  "Because he was a man that was very fond of gold,",
  "Not altogether of the miser's craving, I've been told,",
  "But a craving desire after good meat and drink,",
  "And to obtain good things by foul means he never did shrink.",
  "",
  "He could eat and drink more than two ordinary men,",
  "And to keep up his high living by foul means we must him condemn,",
  "Because his heart's desire in life was to fare well,",
  "And to keep up his good living he tried to betray Parnell.",
  "",
  "Yes, the villain tried hard to swear his life away,",
  "But God protected him by night and by day,",
  "And during his long trial in London, without dismay,",
  "The noble patriot never flinched nor tried to run away.",
  "",
  "Richard Pigott was a man that was blinded by his own conceit.",
  "And would have robbed his dearest friend all for good meat,",
  "To satisfy his gluttony and his own sensual indulgence,",
  "Which the inhuman monster considered no great offence.",
  "",
  "But now in that undiscovered country he's getting his reward,",
  "And I'm sure few people have for him little regard,",
  "Because he was a villain of the deepest dye,",
  "And but few people for him will heave a sigh.",
  "",
  "When I think of such a monster my blood runs cold,",
  "He was like Monteith, that betrayed Wallace for English gold;",
  "But I hope Parnell will prosper for many a day",
  "In despite of his enemies that fried to swear his life away.",
  "",
  "Oh! think of his sufferings and how manfully he did stand.",
  "During his long trial in London, to me it seems grand.",
  "To see him standing at the bar, innocent and upright,",
  "Quite cool and defiant, a most beautiful sight.",
  "",
  "And to the noble patriot, honour be it said,",
  "He never was the least afraid",
  "To speak on behalf of Home Rule for Ireland,",
  "But like a true patriot nobly he did take his stand.",
  "",
  "And may he go on conquering and conquer to the end,",
  "And hoping that God will the right defend,",
  "And protect him always by night and by day,",
  "At home and abroad when far away.",
  "",
  "And now since he's set free, Ireland's sons should rejoice",
  "And applaud him to the skies, all with one voice,",
  "For he's their patriot, true and bold,",
  "And an honest, true-hearted gentleman be it told.",
  ""
]