module.exports = [
  "SATIRES AND EPISTLES OF HORACE IMITATED.",
  "",
  "What, and how great, the virtue and the art",
  "To live on little with a cheerful heart;",
  "(A doctrine sage, but truly none of mine)",
  "Let's talk, my friends, but talk before we dine;",
  "Not when a gilt buffet's reflected pride",
  "Turns you from sound philosophy aside;",
  "Not when from plate to plate your eyeballs roll,",
  "And the brain dances to the mantling bowl.",
  "",
  "Hear Bethel's sermon, one not versed in schools,",
  "But strong in sense, and wise without the rules.",
  "",
  "Go, work, hunt, exercise! (he thus began)",
  "Then scorn a homely dinner, if you can.",
  "Your wine lock'd up, your butler stroll'd abroad,",
  "Or fish denied (the river yet unthaw'd),",
  "If then plain bread and milk will do the feat,",
  "The pleasure lies in you, and not the meat.",
  "",
  "Preach as I please, I doubt our curious men",
  "Will choose a pheasant still before a hen;",
  "Yet hens of Guinea full as good I hold,",
  "Except you eat the feathers green and gold.",
  "Of carps and mullets why prefer the great,",
  "(Though cut in pieces ere my lord can eat)",
  "Yet for small turbots such esteem profess?",
  "Because God made these large, the other less.",
  "",
  "Oldfield, with more than harpy throat endued,",
  "Cries, 'Send me, gods! a whole hog barbecued!'",
  "Oh, blast it, south-winds! till a stench exhale",
  "Rank as the ripeness of a rabbit's tail.",
  "By what criterion do ye eat, d' ye think,",
  "If this is prized for sweetness, that for stink?",
  "When the tired glutton labours through a treat,",
  "He finds no relish in the sweetest meat,",
  "He calls for something bitter, something sour,",
  "And the rich feast concludes extremely poor:",
  "Cheap eggs, and herbs, and olives still we see;",
  "Thus much is left of old simplicity!",
  "",
  "The robin redbreast till of late had rest,",
  "And children sacred held a martin's nest,",
  "Till beccaficos sold so devilish dear",
  "To one that was, or would have been, a peer.",
  "Let me extol a cat, on oysters fed,",
  "I'll have a party at the Bedford-head;",
  "Or even to crack live crawfish recommend;",
  "I'd never doubt at court to make a friend.",
  "",
  "'Tis yet in vain, I own, to keep a pother",
  "About one vice, and fall into the other:",
  "Between excess and famine lies a mean;",
  "Plain, but not sordid; though not splendid, clean.",
  "",
  "Avidien, or his wife (no matter which,",
  "For him you'll call a dog, and her a bitch)",
  "Sell their presented partridges, and fruits,",
  "And humbly live on rabbits and on roots:",
  "One half-pint bottle serves them both to dine,",
  "And is at once their vinegar and wine.",
  "But on some lucky day (as when they found",
  "A lost bank-bill, or heard their son was drown'd)",
  "At such a feast, old vinegar to spare,",
  "Is what two souls so generous cannot bear:",
  "Oil, though it stink, they drop by drop impart,",
  "But souse the cabbage with a bounteous heart.",
  "",
  "He knows to live, who keeps the middle state,",
  "And neither leans on this side, nor on that;",
  "Nor stops, for one bad cork, his butler's pay;",
  "Swears, like Albutius, a good cook away;",
  "Nor lets, like Naevius, every error pass,",
  "The musty wine, foul cloth, or greasy glass.",
  "Now hear what blessings temperance can bring:",
  "(Thus said our friend, and what he said I sing)",
  "First health: the stomach (cramm'd from every dish,",
  "A tomb of boil'd and roast, and flesh and fish,",
  "Where bile, and wind, and phlegm, and acid jar,",
  "And all the man is one intestine war)",
  "Remembers oft the school-boy's simple fare,",
  "The temperate sleeps, and spirits light as air.",
  "",
  "How pale each worshipful and reverend guest",
  "Rise from a clergy or a city feast!",
  "What life in all that ample body, say?",
  "What heavenly particle inspires the clay?",
  "The soul subsides, and wickedly inclines",
  "To seem but mortal, even in sound divines.",
  "",
  "On morning wings how active springs the mind",
  "That leaves the load of yesterday behind!",
  "How easy every labour it pursues!",
  "How coming to the poet every Muse!",
  "Not but we may exceed some holy time,",
  "Or tired in search of truth, or search of rhyme;",
  "Ill health some just indulgence may engage,",
  "And more the sickness of long life, old age;",
  "For fainting age what cordial drop remains,",
  "If our intemperate youth the vessel drains?",
  "",
  "Our fathers praised rank ven'son. You suppose,",
  "Perhaps, young men! our fathers had no nose.",
  "Not so: a buck was then a week's repast,",
  "And 'twas their point, I ween, to make it last;",
  "More pleased to keep it till their friends could come,",
  "Than eat the sweetest by themselves at home.",
  "Why had not I in those good times my birth,",
  "Ere coxcomb-pies or coxcombs were on earth?",
  "",
  "Unworthy he, the voice of fame to hear--",
  "That sweetest music to an honest ear--",
  "(For, faith! Lord Fanny, you are in the wrong,",
  "The world's good word is better than a song,)",
  "Who has not learn'd, fresh sturgeon and ham-pie",
  "Are no rewards for want, and infamy!",
  "When luxury has lick'd up all thy pelf,",
  "Cursed by thy neighbours, thy trustees, thyself,",
  "To friends, to fortune, to mankind a shame,",
  "Think how posterity will treat thy name;",
  "And buy a rope, that future times may tell",
  "Thou hast at least bestow'd one penny well.",
  "",
  "'Right,' cries his lordship, 'for a rogue in need",
  "To have a taste is insolence indeed:",
  "In me 'tis noble, suits my birth and state,",
  "My wealth unwieldy, and my heap too great.'",
  "Then, like the sun, let bounty spread her ray,",
  "And shine that superfluity away.",
  "Oh, impudence of wealth! with all thy store,",
  "How dar'st thou let one worthy man be poor?",
  "Shall half the new-built churches round thee fall?",
  "Make quays, build bridges, or repair Whitehall:",
  "Or to thy country let that heap be lent,",
  "As Marlbro's was, but not at five per cent.",
  "",
  "Who thinks that Fortune cannot change her mind,",
  "Prepares a dreadful jest for all mankind.",
  "And who stands safest? tell me, is it he",
  "That spreads and swells in puff'd prosperity,",
  "Or, blest with little, whose preventing care",
  "In peace provides fit arms against a war?",
  "",
  "Thus Bethel spoke, who always speaks his thought,",
  "And always thinks the very thing he ought:",
  "His equal mind I copy what I can,",
  "And as I love, would imitate the man.",
  "In South-sea days not happier, when surmised",
  "The lord of thousands, than if now excised;",
  "In forest planted by a father's hand,",
  "Than in five acres now of rented land.",
  "Content with little, I can piddle here",
  "On broccoli and mutton, round the year;",
  "But ancient friends (though poor, or out of play)",
  "That touch my bell, I cannot turn away.",
  "'Tis true, no turbots dignify my boards,",
  "But gudgeons, flounders, what my Thames affords:",
  "To Hounslow Heath I point, and Bansted Down,",
  "Thence comes your mutton, and these chicks my own:",
  "From yon old walnut-tree a shower shall fall;",
  "And grapes, long lingering on my only wall,",
  "And figs from standard and espalier join;",
  "The devil is in you if you cannot dine:",
  "Then cheerful healths (your mistress shall have place)  150",
  "And, what's more rare, a poet shall say grace.",
  "",
  "Fortune not much of humbling me can boast;",
  "Though double tax'd, how little have I lost?",
  "My life's amusements have been just the same,",
  "Before and after standing armies came.",
  "My lands are sold, my father's house is gone;",
  "I'll hire another's; is not that my own,",
  "And yours, my friends? through whose free-opening gate",
  "None comes too early, none departs too late;",
  "(For I, who hold sage Homer's rule the best,",
  "Welcome the coming, speed the going guest).",
  "'Pray Heaven it last!' (cries Swift) 'as you go on;",
  "I wish to God this house had been your own:",
  "Pity to build, without a son or wife:",
  "Why, you'll enjoy it only all your life.'",
  "Well, if the use be mine, can it concern one,",
  "Whether the name belong to Pope or Vernon?",
  "What's property, dear Swift? You see it alter",
  "From you to me, from me to Peter Walter;",
  "Or, in a mortgage, prove a lawyer's share;",
  "Or, in a jointure, vanish from the heir;",
  "Or in pure equity (the case not clear)",
  "The Chancery takes your rents for twenty year:",
  "At best, it falls to some ungracious son,",
  "Who cries, 'My father's damn'd, and all's my own.'",
  "Shades, that to Bacon could retreat afford,",
  "Become the portion of a booby lord;",
  "And Helmsley, once proud Buckingham's delight,",
  "Slides to a scrivener or a city knight.",
  "Let lands and houses have what lords they will,",
  "Let us be fix'd, and our own masters still.",
  "",
  "       *       *       *       *       *",
  "",
  "THE FIRST EPISTLE OF THE FIRST BOOK OF HORACE.",
  "",
  "TO LORD BOLINGBROKE.",
  "",
  "St John, whose love indulged my labours past,",
  "Matures my present, and shall bound my last!",
  "Why will you break the Sabbath of my days?",
  "Now sick alike of envy and of praise.",
  "Public too long, ah, let me hide my age!",
  "See, modest Cibber now has left the stage:",
  "Our generals now, retired to their estates,",
  "Hang their old trophies o'er the garden gates,",
  "In life's cool evening satiate of applause,",
  "Nor fond of bleeding, even in Brunswick's cause.",
  "",
  "A voice there is, that whispers in my ear,",
  "('Tis reason's voice, which sometimes one can hear)",
  "'Friend Pope! be prudent, let your Muse take breath,",
  "And never gallop Pegasus to death;",
  "Lest, still and stately, void of fire or force,",
  "You limp, like Blackmore on a Lord Mayor's horse.'",
  "",
  "Farewell, then, verse, and love, and every toy,",
  "The rhymes and rattles of the man or boy;",
  "What right, what true, what fit we justly call,",
  "Let this be all my care--for this is all:",
  "To lay this harvest up, and hoard with haste",
  "What every day will want, and most, the last.",
  "",
  "But ask not, to what doctors I apply;",
  "Sworn to no master, of no sect am I:",
  "As drives the storm, at any door I knock:",
  "And house with Montaigne now, or now with Locke.",
  "Sometimes a patriot, active in debate,",
  "Mix with the world, and battle for the state,",
  "Free as young Lyttelton, her cause pursue,",
  "Still true to virtue, and as warm as true:",
  "Sometimes with Aristippus, or St Paul,",
  "Indulge my candour, and grow all to all;",
  "Back to my native moderation slide,",
  "And win my way by yielding to the tide.",
  "",
  "Long, as to him who works for debt, the day,",
  "Long as the night to her whose love's away,",
  "Long as the year's dull circle seems to run,",
  "When the brisk minor pants for twenty-one:",
  "So slow the unprofitable moments roll,",
  "That lock up all the functions of my soul;",
  "That keep me from myself; and still delay",
  "Life's instant business to a future day:",
  "That task, which, as we follow, or despise,",
  "The eldest is a fool, the youngest wise.",
  "Which done, the poorest can no wants endure;",
  "And which, not done, the richest must be poor.",
  "",
  "Late as it is, I put myself to school,",
  "And feel some comfort not to be a fool.",
  "Weak though I am of limb, and short of sight,",
  "Far from a lynx, and not a giant quite;",
  "I'll do what Mead and Cheselden advise,",
  "To keep these limbs, and to preserve these eyes.",
  "Not to go back, is somewhat to advance,",
  "And men must walk at least before they dance.",
  "",
  "Say, does thy blood rebel, thy bosom move",
  "With wretched avarice, or as wretched love?",
  "Know, there are words and spells which can control",
  "Between the fits this fever of the soul:",
  "Know, there are rhymes, which, fresh and fresh applied,",
  "Will cure the arrant'st puppy of his pride.",
  "Be furious, envious, slothful, mad, or drunk,",
  "Slave to a wife, or vassal to a punk,",
  "A Switz, a High-Dutch, or a Low-Dutch bear;",
  "All that we ask is but a patient ear.",
  "",
  "'Tis the first virtue, vices to abhor:",
  "And the first wisdom, to be fool no more.",
  "But to the world no bugbear is so great,",
  "As want of figure, and a small estate.",
  "To either India see the merchant fly,",
  "Scared at the spectre of pale poverty!",
  "See him, with pains of body, pangs of soul,",
  "Burn through the tropic, freeze beneath the pole!",
  "Wilt thou do nothing for a nobler end,",
  "Nothing, to make philosophy thy friend?",
  "To stop thy foolish views, thy long desires,",
  "And ease thy heart of all that it admires?",
  "",
  "Here, Wisdom calls: 'Seek Virtue first, be bold!",
  "As gold to silver, Virtue is to gold.'",
  "There, London's voice: 'Get money, money still!",
  "And then let virtue follow, if she will.'",
  "This, this the saving doctrine, preach'd to all,",
  "From low St James's up to high St Paul;",
  "From him whose quill stands quiver'd at his ear,",
  "To him who notches sticks at Westminster.",
  "",
  "Barnard in spirit, sense, and truth abounds;",
  "'Pray then, what wants he?' Fourscore thousand pounds;",
  "A pension, or such harness for a slave",
  "As Bug now has, and Dorimant would have.",
  "Barnard, thou art a cit, with all thy worth;",
  "But Bug and D----l, their Honours, and so forth.",
  "",
  "Yet every child another song will sing,",
  "'Virtue, brave boys! 'tis virtue makes a king.'",
  "True, conscious honour is to feel no sin,",
  "He's arm'd without that's innocent within;",
  "Be this thy screen, and this thy wall of brass;",
  "Compared to this, a minister's an ass.",
  "",
  "And say, to which shall our applause belong,",
  "This new court-jargon, or the good old song?",
  "The modern language of corrupted peers,",
  "Or what was spoke at Cressy and Poictiers?",
  "Who counsels best? who whispers, 'Be but great,",
  "With praise or infamy leave that to fate;",
  "Get place and wealth, if possible, with grace;",
  "If not, by any means get wealth and place.'",
  "For what? to have a box where eunuchs sing,",
  "And foremost in the circle eye a king.",
  "Or he, who bids thee face with steady view",
  "Proud fortune, and look shallow greatness through:",
  "And, while he bids thee, sets th' example too?",
  "If such a doctrine, in St James's air,",
  "Should chance to make the well-dress'd rabble stare;",
  "If honest S----z take scandal at a spark,",
  "That less admires the palace than the park:",
  "Faith, I shall give the answer Reynard gave:",
  "'I cannot like, dread sir, your royal cave:",
  "Because I see, by all the tracks about,",
  "Full many a beast goes in, but none comes out.'",
  "Adieu to virtue, if you're once a slave:",
  "Send her to court, you send her to her grave.",
  "",
  "Well, if a king's a lion, at the least",
  "The people are a many-headed beast:",
  "Can they direct what measures to pursue,",
  "Who know themselves so little what to do?",
  "Alike in nothing but one lust of gold,",
  "Just half the land would buy, and half be sold:",
  "Their country's wealth our mightier misers drain,",
  "Or cross, to plunder provinces, the main;",
  "The rest, some farm the poor-box, some the pews;",
  "Some keep assemblies, and would keep the stews;",
  "Some with fat bucks on childless dotards fawn;",
  "Some win rich widows by their chine and brawn;",
  "While with the silent growth of ten per cent,",
  "In dirt and darkness, hundreds stink content.",
  "",
  "Of all these ways, if each pursues his own,",
  "Satire, be kind, and let the wretch alone:",
  "But show me one who has it in his power",
  "To act consistent with himself an hour.",
  "Sir Job sail'd forth, the evening bright and still,",
  "'No place on earth' (he cried) 'like Greenwich hill!'",
  "Up starts a palace, lo, the obedient base",
  "Slopes at its foot, the woods its sides embrace,",
  "The silver Thames reflects its marble face.",
  "Now let some whimsy, or that devil within,",
  "Which guides all those who know not what they mean,",
  "But give the knight (or give his lady) spleen;",
  "'Away, away! take all your scaffolds down,",
  "For, snug's the word: my dear! we'll live in town.'",
  "",
  "At amorous Flavio is the stocking thrown?",
  "That very night he longs to lie alone.",
  "The fool, whose wife elopes some thrice a quarter,",
  "For matrimonial solace dies a martyr.",
  "Did ever Proteus, Merlin, any witch,",
  "Transform themselves so strangely as the rich?",
  "Well, but the poor--the poor have the same itch;",
  "They change their weekly barber, weekly news,",
  "Prefer a new japanner to their shoes,",
  "Discharge their garrets, move their beds, and run",
  "(They know not whither) in a chaise and one;",
  "They hire their sculler, and when once aboard,",
  "Grow sick, and damn the climate--like a lord.",
  "",
  "You laugh, half-beau, half-sloven if I stand;",
  "My wig all powder, and all snuff my band;",
  "You laugh, if coat and breeches strangely vary,",
  "White gloves, and linen worthy Lady Mary!",
  "But, when no prelate's lawn with hair-shirt lined",
  "Is half so incoherent as my mind,",
  "When (each opinion with the next at strife,",
  "One ebb and flow of follies all my life)",
  "I plant, root up; I build, and then confound;",
  "Turn round to square, and square again to round;",
  "You never change one muscle of your face,",
  "You think this madness but a common case,",
  "Nor once to Chancery, nor to Hale apply;",
  "Yet hang your lip, to see a seam awry!",
  "Careless how ill I with myself agree,",
  "Kind to my dress, my figure, not to me.",
  "Is this my guide, philosopher, and friend?",
  "This, he who loves me, and who ought to mend?",
  "Who ought to make me (what he can, or none),",
  "That man divine whom Wisdom calls her own;",
  "Great without title, without fortune bless'd;",
  "Rich even when plunder'd, honour'd while oppress'd;",
  "Loved without youth, and follow'd without power;",
  "At home, though exiled; free, though in the Tower;",
  "In short, that reasoning, high, immortal thing,",
  "Just less than Jove, and much above a king,",
  "Nay, half in heaven--except (what's mighty odd)",
  "A fit of vapours clouds this demi-god.",
  "",
  "       *       *       *       *       *",
  "",
  "THE SIXTH EPISTLE OF THE FIRST BOOK OF HORACE.",
  "",
  "TO MR MURRAY.",
  "",
  "'Not to admire, is all the art I know,",
  "To make men happy, and to keep them so.'",
  "(Plain truth, dear Murray, needs no flowers of speech,",
  "So take it in the very words of Creech.)",
  "",
  "This vault of air, this congregated ball,",
  "Self-centred sun, and stars that rise and fall,",
  "There are, my friend! whose philosophic eyes",
  "Look through and trust the Ruler with his skies,",
  "To Him commit the hour, the day, the year,",
  "And view this dreadful All without a fear.",
  "",
  "Admire we then what earth's low entrails hold,",
  "Arabian shores, or Indian seas infold;",
  "All the mad trade of fools and slaves for gold?",
  "Or popularity? or stars and strings?",
  "The mob's applauses, or the gifts of kings?",
  "Say with what eyes we ought at courts to gaze,",
  "And pay the great our homage of amaze?",
  "",
  "If weak the pleasure that from these can spring,",
  "The fear to want them is as weak a thing:",
  "Whether we dread, or whether we desire,",
  "In either case, believe me, we admire;",
  "Whether we joy or grieve, the same the curse,",
  "Surprised at better, or surprised at worse.",
  "Thus good or bad, to one extreme betray",
  "The unbalanced mind, and snatch the man away:",
  "For virtue's self may too much zeal be had;",
  "The worst of madmen is a saint run mad.",
  "",
  "Go then, and, if you can, admire the state",
  "Of beaming diamonds, and reflected plate;",
  "Procure a taste to double the surprise,",
  "And gaze on Parian charms with learnèd eyes:",
  "Be struck with bright brocade, or Tyrian dye,",
  "Our birthday nobles' splendid livery.",
  "If not so pleased, at council-board rejoice,",
  "To see their judgments hang upon thy voice;",
  "From morn to night, at Senate, Rolls, and Hall,",
  "Plead much, read more, dine late, or not at all.",
  "But wherefore all this labour, all this strife?",
  "For fame, for riches, for a noble wife?",
  "Shall one whom nature, learning, birth, conspired",
  "To form, not to admire, but be admired,",
  "Sigh, while his Chloe, blind to wit and worth,",
  "Weds the rich dulness of some son of earth?",
  "Yet time ennobles, or degrades each line;",
  "It brighten'd Craggs's, and may darken thine:",
  "And what is fame? the meanest have their day,",
  "The greatest can but blaze, and pass away.",
  "Graced as thou art, with all the power of words,",
  "So known, so honour'd, at the House of Lords:",
  "Conspicuous scene! another yet is nigh",
  "(More silent far) where kings and poets lie;",
  "Where Murray (long enough his country's pride)",
  "Shall be no more than Tully, or than Hyde!",
  "",
  "Rack'd with sciatics, martyr'd with the stone,",
  "Will any mortal let himself alone?",
  "See Ward by batter'd beaux invited over,",
  "And desperate misery lays hold on Dover.",
  "The case is easier in the mind's disease;",
  "There all men may be cured, whene'er they please.",
  "Would ye be blest? despise low joys, low gains;",
  "Disdain whatever Cornbury disdains;",
  "Be virtuous, and be happy for your pains.",
  "",
  "But art thou one, whom new opinions sway,",
  "One who believes as Tindal leads the way,",
  "Who virtue and a church alike disowns,",
  "Thinks that but words, and this but brick and stones?",
  "Fly then, on all the wings of wild desire,",
  "Admire whate'er the maddest can admire:",
  "Is wealth thy passion? Hence! from pole to pole,",
  "Where winds can carry, or where waves can roll,",
  "For Indian spices, for Peruvian gold,",
  "Prevent the greedy, and outbid the bold:",
  "Advance thy golden mountain to the skies;",
  "On the broad base of fifty thousand rise,",
  "Add one round hundred, and (if that's not fair)",
  "Add fifty more, and bring it to a square.",
  "For, mark the advantage; just so many score",
  "Will gain a wife with half as many more,",
  "Procure her beauty, make that beauty chaste,",
  "And then such friends--as cannot fail to last.",
  "A man of wealth is dubb'd a man of worth,",
  "Venus shall give him form, and Anstis birth.",
  "(Believe me, many a German prince is worse,",
  "Who, proud of pedigree, is poor of purse).",
  "His wealth brave Timon gloriously confounds;",
  "Ask'd for a groat, he gives a hundred pounds;",
  "Or if three ladies like a luckless play,",
  "Takes the whole house upon the poet's day.",
  "Now, in such exigencies not to need,",
  "Upon my word, you must be rich indeed;",
  "A noble superfluity it craves,",
  "Not for yourself, but for your fools and knaves;",
  "Something, which for your honour they may cheat,",
  "And which it much becomes you to forget.",
  "If wealth alone then make and keep us bless'd,",
  "Still, still be getting, never, never rest.",
  "",
  "But if to power and place your passion lie,",
  "If in the pomp of life consist the joy;",
  "Then hire a slave, or (if you will) a lord",
  "To do the honours, and to give the word;",
  "Tell at your levée, as the crowds approach,",
  "To whom to nod, whom take into your coach,",
  "Whom honour with your hand: to make remarks,",
  "Who rules in Cornwall, or who rules in Berks:",
  "'This may be troublesome, is near the chair:",
  "That makes three members, this can choose a mayor.'",
  "Instructed thus, you bow, embrace, protest,",
  "Adopt him son, or cousin at the least,",
  "Then turn about, and laugh at your own jest.",
  "",
  "Or if your life be one continued treat,",
  "If to live well means nothing but to eat;",
  "Up, up! cries Gluttony, 'tis break of day,",
  "Go drive the deer, and drag the finny prey;",
  "With hounds and horns go hunt an appetite--",
  "So Russel did, but could not eat at night,",
  "Call'd, happy dog! the beggar at his door,",
  "And envied thirst and hunger to the poor.",
  "",
  "Or shall we every decency confound,",
  "Through taverns, stews, and bagnios take our round,",
  "Go dine with Chartres, in each vice outdo",
  "K--l's lewd cargo, or Ty--y's crew;",
  "From Latian syrens, French Circaean feasts,",
  "Return well travell'd, and transform'd to beasts,",
  "Or for a titled punk, or foreign flame,",
  "Renounce our country, and degrade our name?",
  "",
  "If, after all, we must with Wilmot own,",
  "The cordial drop of life is love alone,",
  "And Swift cry wisely, '_Vive la bagatelle!_'",
  "The man that loves and laughs, must sure do well.",
  "",
  "Adieu--if this advice appear the worst,",
  "E'en take the counsel which I gave you first:",
  "Or better precepts if you can impart,",
  "Why do, I'll follow them with all my heart.",
  "",
  "       *       *       *       *       *",
  "",
  "THE FIRST EPISTLE OF THE SECOND BOOK OF HORACE.",
  "",
  "ADVERTISEMENT.",
  "",
  "The reflections of Horace, and the judgments past in his Epistle to",
  "Augustus, seemed so seasonable to the present times, that I could not",
  "help applying them to the use of my own country. The author thought them",
  "considerable enough to address them to his prince; whom he paints with",
  "all the great and good qualities of a monarch, upon whom the Romans",
  "depended for the increase of an absolute empire. But to make the poem",
  "entirely English, I was willing to add one or two of those which",
  "contribute to the happiness of a free people, and are more consistent",
  "with the welfare of our neighbours.",
  "",
  "This epistle will show the learned world to have fallen into two",
  "mistakes: One, that Augustus was a patron of poets in general; whereas",
  "he not only prohibited all but the best writers to name him, but",
  "recommended that care even to the civil magistrate: _Admonebat",
  "praetores, ne paterentur nomen suum obsolefieri_, &c. The other, that",
  "this piece was only a general discourse of poetry; whereas it was an",
  "apology for the poets, in order to render Augustus more their patron.",
  "Horace here pleads the cause of his contemporaries, first against the",
  "taste of the town, whose humour it was to magnify the authors of the",
  "preceding age; secondly against the court and nobility, who encouraged",
  "only the writers for the theatre; and lastly against the emperor",
  "himself, who had conceived them of little use to the government. He",
  "shows (by a view of the progress of learning, and the change of taste",
  "among the Romans) that the introduction of the polite arts of Greece had",
  "given the writers of his time great advantages over their predecessors;",
  "that their morals were much improved, and the license of those ancient",
  "poets restrained; that satire and comedy were become more just and",
  "useful; that whatever extravagances were left on the stage, were owing",
  "to the ill taste of the nobility; that poets, under due regulations,",
  "were in many respects useful to the state; and concludes, that it was",
  "upon them the emperor himself must depend for his fame with posterity.",
  "",
  "We may further learn from this epistle, that Horace made his court to",
  "this great prince by writing with a decent freedom toward him, with a",
  "just contempt of his low flatterers, and with a manly regard to his own",
  "character.",
  "",
  "TO AUGUSTUS.",
  "",
  "While you, great patron of mankind! sustain",
  "The balanced world, and open all the main;",
  "Your country, chief, in arms abroad defend,",
  "At home, with morals, arts, and laws amend;",
  "How shall the Muse, from such a monarch, steal",
  "An hour, and not defraud the public weal?",
  "",
  "Edward and Henry, now the boast of fame,",
  "And virtuous Alfred, a more sacred name,",
  "After a life of generous toils endured,",
  "The Gaul subdued, or property secured,",
  "Ambition humbled, mighty cities storm'd,",
  "Or laws establish'd, and the world reform'd;",
  "Closed their long glories with a sigh, to find",
  "The unwilling gratitude of base mankind!",
  "All human virtue, to its latest breath,",
  "Finds envy never conquer'd, but by death.",
  "The great Alcides, every labour past,",
  "Had still this monster to subdue at last.",
  "Sure fate of all, beneath whose rising ray",
  "Each star of meaner merit fades away!",
  "Oppress'd we feel the beam directly beat,",
  "Those suns of glory please not till they set.",
  "",
  "To thee, the world its present homage pays,",
  "The harvest early, but mature the praise:",
  "Great friend of liberty! in kings a name",
  "Above all Greek, above all Roman fame:",
  "Whose word is truth, as sacred and revered,",
  "As Heaven's own oracles from altars heard.",
  "Wonder of kings! like whom, to mortal eyes",
  "None e'er has risen, and none e'er shall rise.",
  "",
  "Just in one instance, be it yet confess'd,",
  "Your people, sir, are partial in the rest:",
  "Foes to all living worth except your own,",
  "And advocates for folly dead and gone.",
  "Authors, like coins, grow dear as they grow old;",
  "It is the rust we value, not the gold.",
  "Chaucer's worst ribaldry is learn'd by rote,",
  "And beastly Skelton heads of houses quote:",
  "One likes no language but the 'Faery Queen';",
  "A Scot will fight for 'Christ's Kirk o' the Green';",
  "And each true Briton is to Ben so civil,",
  "He swears the Muses met him at The Devil.",
  "",
  "Though justly Greece her eldest sons admires,",
  "Why should not we be wiser than our sires?",
  "In every public virtue we excel;",
  "We build, we paint, we sing, we dance as well,",
  "And learnèd Athens to our art must stoop,",
  "Could she behold us tumbling through a hoop.",
  "",
  "If time improve our wit as well as wine,",
  "Say at what age a poet grows divine?",
  "Shall we, or shall we not, account him so,",
  "Who died, perhaps, an hundred years ago?",
  "End all dispute; and fix the year precise",
  "When British bards begin t' immortalise?",
  "",
  "'Who lasts a century can have no flaw,",
  "I hold that wit a classic, good in law.'",
  "Suppose he wants a year, will you compound?",
  "And shall we deem him ancient, right and sound,",
  "Or damn to all eternity at once,",
  "At ninety-nine, a modern and a dunce?",
  "",
  "'We shall not quarrel for a year or two;",
  "By courtesy of England, he may do.'",
  "",
  "Then, by the rule that made the horse-tail bare,",
  "I pluck out year by year, as hair by hair,",
  "And melt down ancients like a heap of snow:",
  "While you, to measure merits, look in Stowe,",
  "And estimating authors by the year,",
  "Bestow a garland only on a bier.",
  "",
  "Shakspeare (whom you and every play-house bill",
  "Style the divine, the matchless, what you will),",
  "For gain, not glory, wing'd his roving flight,",
  "And grew immortal in his own despite.",
  "Ben, old and poor, as little seem'd to heed",
  "The life to come, in every poet's creed.",
  "Who now reads Cowley? if he pleases yet,",
  "His moral pleases, not his pointed wit;",
  "Forgot his epic, nay, Pindaric art,",
  "But still I love the language of his heart.",
  "",
  "'Yet surely, surely, these were famous men!",
  "What boy but hears the sayings of old Ben?",
  "In all debates where critics bear a part,",
  "Not one but nods and talks of Johnson's art,",
  "Of Shakspeare's nature, and of Cowley's wit;",
  "How Beaumont's judgment check'd what Fletcher writ;",
  "How Shadwell hasty, Wycherley was slow;",
  "But, for the passions, Southern sure and Rowe.",
  "These, only these, support the crowded stage,",
  "From eldest Heywood down to Cibber's age.'",
  "",
  "All this may be; the people's voice is odd,",
  "It is, and it is not, the voice of God.",
  "To Gammer Gurton if it give the bays,",
  "And yet deny the 'Careless Husband' praise,",
  "Or say our fathers never broke a rule;",
  "Why then, I say, the public is a fool.",
  "But let them own, that greater faults than we",
  "They had, and greater virtues, I'll agree.",
  "Spenser himself affects the obsolete,",
  "And Sydney's verse halts ill on Roman feet:",
  "Milton's strong pinion now not Heaven can bound,",
  "Now serpent-like, in prose he sweeps the ground,",
  "In quibbles, angel and archangel join,",
  "And God the Father turns a school-divine.",
  "Not that I'd lop the beauties from his book,",
  "Like slashing Bentley with his desperate hook,",
  "Or damn all Shakspeare, like the affected fool",
  "At court, who hates whate'er he read at school.",
  "",
  "But for the wits of either Charles's days,",
  "The mob of gentlemen who wrote with ease;",
  "Sprat, Carew, Sedley, and a hundred more,",
  "(Like twinkling stars the Miscellanies o'er)",
  "One simile, that solitary shines",
  "In the dry desert of a thousand lines,",
  "Or lengthen'd thought that gleams through many a page,",
  "Has sanctified whole poems for an age.",
  "I lose my patience, and I own it too,",
  "When works are censured, not as bad, but new;",
  "While if our elders break all reason's laws,",
  "These fools demand not pardon, but applause.",
  "",
  "On Avon's bank, where flowers eternal blow,",
  "If I but ask, if any weed can grow?",
  "One tragic sentence if I dare deride",
  "Which Betterton's grave action dignified,",
  "Or well-mouth'd Booth with emphasis proclaims,",
  "(Though but, perhaps, a muster-roll of names)",
  "How will our fathers rise up in a rage,",
  "And swear, all shame is lost in George's age!",
  "You'd think no fools disgraced the former reign,",
  "Did not some grave examples yet remain,",
  "Who scorn a lad should teach his father skill,",
  "And, having once been wrong, will be so still.",
  "He who, to seem more deep than you or I,",
  "Extols old bards, or Merlin's prophecy,",
  "Mistake him not; he envies, not admires,",
  "And to debase the sons, exalts the sires.",
  "Had ancient times conspired to disallow",
  "What then was new, what had been ancient now?",
  "Or what remain'd so worthy to be read",
  "By learned critics of the mighty dead?",
  "",
  "In days of ease, when now the weary sword",
  "Was sheathed, and luxury with Charles restored;",
  "In every taste of foreign courts improved,",
  "'All, by the king's example, lived and loved.'",
  "Then peers grew proud in horsemanship t' excel,",
  "Newmarket's glory rose, as Britain's fell;",
  "The soldier breathed the gallantries of France,",
  "And every flowery courtier writ romance.",
  "Then marble, soften'd into life, grew warm,",
  "And yielding metal flow'd to human form:",
  "Lely on animated canvas stole",
  "The sleepy eye, that spoke the melting soul.",
  "No wonder then, when all was love and sport,",
  "The willing Muses were debauch'd at court:",
  "On each enervate string they taught the note",
  "To pant, or tremble through an eunuch's throat.",
  "",
  "But Britain, changeful as a child at play,",
  "Now calls in princes, and now turns away.",
  "Now Whig, now Tory, what we loved we hate;",
  "Now all for pleasure, now for Church and State;",
  "Now for prerogative, and now for laws;",
  "Effects unhappy! from a noble cause.",
  "",
  "Time was, a sober Englishman would knock",
  "His servants up, and rise by five o'clock,",
  "Instruct his family in every rule,",
  "And send his wife to church, his son to school.",
  "To worship like his fathers, was his care;",
  "To teach their frugal virtues to his heir;",
  "To prove, that luxury could never hold;",
  "And place, on good security, his gold.",
  "Now times are changed, and one poetic itch",
  "Has seized the court and city, poor and rich:",
  "Sons, sires, and grandsires, all will wear the bays,",
  "Our wives read Milton, and our daughters plays,",
  "To theatres, and to rehearsals throng,",
  "And all our grace at table is a song.",
  "I, who so oft renounce the Muses, lie,",
  "Not ----'s self e'er tells more fibs than I;",
  "When sick of muse, our follies we deplore,",
  "And promise our best friends to rhyme no more;",
  "We wake next morning in a raging fit,",
  "And call for pen and ink to show our wit.",
  "",
  "He served a 'prenticeship, who sets up shop;",
  "Ward tried on puppies, and the poor, his drop;",
  "E'en Radcliffe's doctors travel first to France,",
  "Nor dare to practise till they've learn'd to dance.",
  "Who builds a bridge that never drove a pile?",
  "(Should Ripley venture, all the world would smile)",
  "But those who cannot write, and those who can,",
  "All rhyme, and scrawl, and scribble, to a man.",
  "",
  "Yet, sir, reflect, the mischief is not great;",
  "These madmen never hurt the Church or State:",
  "Sometimes the folly benefits mankind;",
  "And rarely avarice taints the tuneful mind.",
  "Allow him but his plaything of a pen,",
  "He ne'er rebels, or plots, like other men:",
  "Flight of cashiers, or mobs, he'll never mind;",
  "And knows no losses while the Muse is kind.",
  "To cheat a friend, or ward, he leaves to Peter;",
  "The good man heaps up nothing but mere metre,",
  "Enjoys his garden and his book in quiet;",
  "And then--a perfect hermit in his diet.",
  "",
  "Of little use the man you may suppose,",
  "Who says in verse what others say in prose;",
  "Yet let me show, a poet's of some weight,",
  "And (though no soldier) useful to the State.",
  "What will a child learn sooner than a song?",
  "What better teach a foreigner the tongue?",
  "What's long or short, each accent where to place,",
  "And speak in public with some sort of grace?",
  "I scarce can think him such a worthless thing,",
  "Unless he praise some monster of a king;",
  "Or virtue or religion turn to sport,",
  "To please a lewd or unbelieving court",
  "Unhappy Dryden!--in all Charles's days,",
  "Roscommon only boasts unspotted bays;",
  "And in our own (excuse some courtly stains)",
  "No whiter page than Addison remains.",
  "He from the taste obscene reclaims our youth,",
  "And sets the passions on the side of truth,",
  "Forms the soft bosom with the gentlest art,",
  "And pours each human virtue in the heart,",
  "Let Ireland tell, how wit upheld her cause,",
  "Her trade supported, and supplied her laws;",
  "And leave on Swift this grateful verse engraved,",
  "'The rights a court attack'd, a poet saved.'",
  "Behold the hand that wrought a nation's cure,",
  "Stretch'd to relieve the idiot and the poor,",
  "Proud vice to brand, or injured worth adorn,",
  "And stretch the ray to ages yet unborn.",
  "Not but there are, who merit other palms;",
  "Hopkins and Sternhold glad the heart with psalms:",
  "The boys and girls whom charity maintains,",
  "Implore your help in these pathetic strains:",
  "How could devotion touch the country pews,",
  "Unless the gods bestow'd a proper muse?",
  "Verse cheers their leisure, verse assists their work,",
  "Verse prays for peace, or sings down Pope and Turk.",
  "The silenced preacher yields to potent strain,",
  "And feels that grace his prayer besought in vain;",
  "The blessing thrills through all the labouring throng,",
  "And Heaven is won by violence of song.",
  "",
  "Our rural ancestors, with little blest,",
  "Patient of labour when the end was rest,",
  "Indulged the day that housed their annual grain,",
  "With feasts, and offerings, and a thankful strain:",
  "The joy their wives, their sons, and servants share,",
  "Ease of their toil, and partners of their care:",
  "The laugh, the jest, attendants on the bowl,",
  "Smooth'd every brow, and open'd every soul:",
  "With growing years the pleasing license grew,",
  "And taunts alternate innocently flew.",
  "But times corrupt, and nature, ill-inclined,",
  "Produced the point that left a sting behind;",
  "Till friend with friend, and families at strife,",
  "Triumphant malice raged through private life.",
  "Who felt the wrong, or fear'd it, took the alarm,",
  "Appeal'd to law, and justice lent her arm.",
  "At length, by wholesome dread of statutes bound,",
  "The poets learn'd to please, and not to wound:",
  "Most warp'd to flattery's side; but some, more nice,",
  "Preserved the freedom, and forbore the vice.",
  "Hence satire rose, that just the medium hit,",
  "And heals with morals what it hurts with wit.",
  "",
  "We conquer'd France, but felt our captive's charms;",
  "Her arts victorious triumph'd o'er our arms;",
  "Britain to soft refinements less a foe,",
  "Wit grew polite, and numbers learn'd to flow.",
  "Waller was smooth; but Dryden taught to join",
  "The varying verse, the full-resounding line,",
  "The long majestic march, and energy divine:",
  "Though still some traces of our rustic vein",
  "And splayfoot verse remain'd, and will remain.",
  "Late, very late, correctness grew our care,",
  "When the tired nation breathed from civil war.",
  "Exact Racine, and Corneille's noble fire,",
  "Show'd us that France had something to admire.",
  "Not but the tragic spirit was our own,",
  "And full in Shakspeare, fair in Otway shone:",
  "But Otway fail'd to polish or refine,",
  "And fluent Shakspeare scarce effaced a line.",
  "Even copious Dryden wanted, or forgot,",
  "The last and greatest art, the art to blot.",
  "Some doubt, if equal pains, or equal fire",
  "The humbler muse of Comedy require.",
  "But in known images of life, I guess",
  "The labour greater, as the indulgence less.",
  "Observe how seldom even the best succeed:",
  "Tell me if Congreve's fools are fools indeed?",
  "What pert, low dialogue has Farquhar writ!",
  "How Van wants grace, who never wanted wit!",
  "The stage how loosely does Astraea tread,",
  "Who fairly puts all characters to bed:",
  "And idle Cibber, how he breaks the laws,",
  "To make poor Pinky eat with vast applause!",
  "But fill their purse, our poets' work is done,",
  "Alike to them, by pathos or by pun.",
  "",
  "O you! whom Vanity's light bark conveys",
  "On Fame's mad voyage by the wind of praise,",
  "With what a shifting gale your course you ply,",
  "For ever sunk too low, or borne too high!",
  "Who pants for glory finds but short repose,",
  "A breath revives him, or a breath o'erthrows.",
  "Farewell the stage! if just as thrives the play,",
  "The silly bard grows fat, or falls away.",
  "",
  "There still remains, to mortify a wit,",
  "The many-headed monster of the pit:",
  "A senseless, worthless, and unhonour'd crowd;",
  "Who, to disturb their betters mighty proud,",
  "Clattering their sticks before ten lines are spoke.",
  "Call for the farce, the bear, or the black-joke.",
  "What dear delight to Britons farce affords!",
  "Ever the taste of mobs, but now of lords;",
  "(Taste, that eternal wanderer, which flies",
  "From heads to ears, and now from ears to eyes).",
  "The play stands still; damn action and discourse,",
  "Back fly the scenes, and enter foot and horse;",
  "Pageants on pageants, in long order drawn,",
  "Peers, heralds, bishops, ermine, gold, and lawn;",
  "The champion too; and, to complete the jest,",
  "Old Edward's armour beams on Cibber's breast",
  "With laughter, sure, Democritus had died,",
  "Had he beheld an audience gape so wide.",
  "Let bear or elephant be e'er so white,",
  "The people, sure, the people are the sight!",
  "Ah, luckless poet! stretch thy lungs and roar,",
  "That bear or elephant shall heed thee more;",
  "While all its throats the gallery extends,",
  "And all the thunder of the pit ascends!",
  "Loud as the wolves, on Orcas' stormy steep,",
  "Howl to the roarings of the Northern deep.",
  "Such is the shout, the long-applauding note,",
  "At Quin's high plume, or Oldfield's petticoat;",
  "Or when from court a birthday suit bestow'd,",
  "Sinks the lost actor in the tawdry load.",
  "Booth enters--hark! the universal peal!",
  "'But has he spoken?' Not a syllable.",
  "What shook the stage, and made the people stare?",
  "Cato's long wig, flower'd gown, and lacquer'd chair.",
  "",
  "Yet lest you think I rally more than teach,",
  "Or praise malignly arts I cannot reach,",
  "Let me for once presume to instruct the times,",
  "To know the poet from the man of rhymes:",
  "'Tis he, who gives my breast a thousand pains,",
  "Can make me feel each passion that he feigns;",
  "Enrage, compose, with more than magic art,",
  "With pity, and with terror, tear my heart:",
  "And snatch me, o'er the earth, or through the air,",
  "To Thebes, to Athens, when he will, and where.",
  "",
  "But not this part of the poetic state",
  "Alone, deserves the favour of the great:",
  "Think of those authors, sir, who would rely",
  "More on a reader's sense, than gazer's eye.",
  "Or who shall wander where the Muses sing?",
  "Who climb their mountain, or who taste their spring?",
  "How shall we fill a library with wit,",
  "When Merlin's cave is half unfurnish'd yet?",
  "",
  "My liege! why writers little claim your thought,",
  "I guess; and, with their leave, will tell the fault:",
  "We poets are (upon a poet's word)",
  "Of all mankind, the creatures most absurd:",
  "The season, when to come, and when to go,",
  "To sing, or cease to sing, we never know;",
  "And if we will recite nine hours in ten,",
  "You lose your patience, just like other men.",
  "Then, too, we hurt ourselves, when to defend",
  "A single verse, we quarrel with a friend;",
  "Repeat unask'd; lament, the wit's too fine",
  "For vulgar eyes, and point out every line.",
  "But most, when straining with too weak a wing,",
  "We needs will write epistles to the king;",
  "And from the moment we oblige the town,",
  "Expect a place, or pension from the crown;",
  "Or dubb'd historians by express command,",
  "To enrol your triumphs o'er the seas and land,",
  "Be call'd to court to plan some work divine,",
  "As once for Louis, Boileau and Racine.",
  "",
  "Yet think, great sir! (so many virtues shown)",
  "Ah think, what poet best may make them known?",
  "Or choose, at least, some minister of grace,",
  "Fit to bestow the Laureate's weighty place.",
  "",
  "Charles, to late times to be transmitted fair,",
  "Assign'd his figure to Bernini's care;",
  "And great Nassau to Kneller's hand decreed",
  "To fix him graceful on the bounding steed;",
  "So well in paint and stone they judged of merit:",
  "But kings in wit may want discerning spirit.",
  "The hero William, and the martyr Charles,",
  "One knighted Blackmore, and one pension'd Quarles;",
  "Which made old Ben and surly Dennis swear,",
  "'No Lord's anointed, but a Russian bear.'",
  "",
  "Not with such majesty, such bold relief,",
  "The forms august of king, or conquering chief.",
  "E'er swell'd on marble, as in verse have shined",
  "(In polish'd verse) the manners and the mind.",
  "Oh! could I mount on the Maeonian wing,",
  "Your arms, your actions, your repose to sing!",
  "What seas you traversed, and what fields you fought!",
  "Your country's peace, how oft, how dearly bought!",
  "How barbarous rage subsided at your word,",
  "And nations wonder'd while they dropp'd the sword!",
  "How, when you nodded, o'er the land and deep,",
  "Peace stole her wing, and wrapp'd the world in sleep;",
  "Till earth's extremes your mediation own,",
  "And Asia's tyrants tremble at your throne--",
  "But verse, alas! your Majesty disdains;",
  "And I'm not used to panegyric strains:",
  "The zeal of fools offends at any time,",
  "But most of all, the zeal of fools in rhyme.",
  "Besides, a fate attends on all I write,",
  "That when I aim at praise, they say I bite.",
  "A vile encomium doubly ridicules:",
  "There's nothing blackens like the ink of fools.",
  "If true, a woful likeness; and if lies,",
  "'Praise undeserved is scandal in disguise:'",
  "Well may he blush who gives it, or receives;",
  "And when I flatter, let my dirty leaves",
  "(Like journals, odes, and such forgotten things",
  "As Eusden, Philips, Settle, writ of kings)",
  "Clothe spice, line trunks, or fluttering in a row,",
  "Befringe the rails of Bedlam and Soho.",
  "",
  "       *       *       *       *       *",
  "",
  "THE SECOND EPISTLE OF THE SECOND BOOK OF HORACE.",
  "",
  "'Ludentis speciem dabit, et torquebitur.'",
  "",
  "--HOR.",
  "",
  "Dear Colonel, Cobham's and your country's friend!",
  "You love a verse, take such as I can send.",
  "A Frenchman comes, presents you with his boy,",
  "Bows and begins--'The lad, sir, is of Blois:",
  "Observe his shape how clean! his locks how curl'd!",
  "My only son;--I'd have him see the world:",
  "His French is pure: his voice, too, you shall hear.",
  "Sir, he's your slave, for twenty pound a-year.",
  "Mere wax as yet, you fashion him with ease,",
  "Your barber, cook, upholsterer, what you please:",
  "A perfect genius at an opera song--",
  "To say too much, might do my honour wrong.",
  "Take him with all his virtues, on my word;",
  "His whole ambition was to serve a lord;",
  "But, sir, to you, with what would I not part?",
  "Though, faith! I fear, 'twill break his mother's heart.",
  "Once (and but once) I caught him in a lie,",
  "And then, unwhipp'd, he had the grace to cry;",
  "The fault he has I fairly shall reveal,",
  "(Could you o'erlook but that) it is to steal.'",
  "",
  "If, after this, you took the graceless lad,",
  "Could you complain, my friend, he proved so bad?",
  "Faith, in such case, if you should prosecute,",
  "I think Sir Godfrey should decide the suit;",
  "Who sent the thief that stole the cash away,",
  "And punish'd him that put it in his way.",
  "",
  "Consider then, and judge me in this light;",
  "I told you when I went, I could not write;",
  "You said the same; and are you discontent",
  "With laws, to which you gave your own assent?",
  "Nay worse, to ask for verse at such a time!",
  "D' ye think me good for nothing but to rhyme?",
  "",
  "In Anna's wars, a soldier, poor and old,",
  "Had dearly earn'd a little purse of gold:",
  "Tired with a tedious march, one luckless night,",
  "He slept, poor dog! and lost it to a doit.",
  "This put the man in such a desperate mind,",
  "Between revenge, and grief, and hunger join'd,",
  "Against the foe, himself, and all mankind,",
  "He leap'd the trenches, scaled a castle-wall,",
  "Tore down a standard, took the fort and all.",
  "'Prodigious well!' his great commander cried,",
  "Gave him much praise, and some reward beside.",
  "Next, pleased his excellence a town to batter;",
  "(Its name I know not, and it's no great matter)",
  "'Go on, my friend,' (he cried) 'see yonder walls!",
  "Advance and conquer! go where glory calls!",
  "More honours, more rewards attend the brave.'",
  "Don't you remember what reply he gave?",
  "'D' ye think me, noble general, such a sot?",
  "Let him take castles who has ne'er a groat.'",
  "",
  "Bred up at home, full early I begun",
  "To read in Greek the wrath of Peleus' son.",
  "Besides, my father taught me from a lad,",
  "The better art to know the good from bad:",
  "(And little sure imported to remove,",
  "To hunt for truth in Maudlin's learnèd grove.)",
  "But knottier points we knew not half so well,",
  "Deprived us soon of our paternal cell;",
  "And certain laws, by sufferers thought unjust.",
  "Denied all posts of profit or of trust:",
  "Hopes after hopes of pious Papists fail'd,",
  "While mighty William's thundering arm prevail'd.",
  "For right hereditary tax'd and fined,",
  "He stuck to poverty with peace of mind;",
  "And me, the Muses help'd to undergo it:",
  "Convict a Papist he, and I a poet.",
  "But (thanks to Homer) since I live and thrive.",
  "Indebted to no prince or peer alive,",
  "Sure I should want the care of ten Monroes,",
  "If I would scribble, rather than repose.",
  "",
  "Years following years, steal something every day,",
  "At last they steal us from ourselves away;",
  "In one our frolics, one amusements end,",
  "In one a mistress drops, in one a friend:",
  "This subtle thief of life, this paltry time,",
  "What will it leave me, if it snatch my rhyme?",
  "If every wheel of that unwearied mill",
  "That turn'd ten thousand verses, now stands still?",
  "",
  "But, after all, what would you have me do?",
  "When out of twenty I can please not two;",
  "When this heroics only deigns to praise,",
  "Sharp satire that, and that Pindaric lays?",
  "One likes the pheasant's wing, and one the leg;",
  "The vulgar boil, the learnèd roast an egg;",
  "Hard task! to hit the palate of such guests,",
  "When Oldfield loves, what Dartineuf detests.",
  "",
  "But grant I may relapse, for want of grace,",
  "Again to rhyme; can London be the place?",
  "Who there his Muse, or self, or soul attends,",
  "In crowds, and courts, law, business, feasts, and friends?",
  "My counsel sends to execute a deed:",
  "A poet begs me I will hear him read:",
  "In Palace-yard at nine you'll find me there--",
  "At ten for certain, sir, in Bloomsbury Square--",
  "Before the Lords at twelve my cause comes on--",
  "There's a rehearsal, sir, exact at one.--",
  "'Oh, but a wit can study in the streets,",
  "And raise his mind above the mob he meets.'",
  "Not quite so well, however, as one ought;",
  "A hackney-coach may chance to spoil a thought:",
  "And then a nodding beam, or pig of lead,",
  "God knows, may hurt the very ablest head.",
  "Have you not seen, at Guildhall's narrow pass,",
  "Two aldermen dispute it with an ass?",
  "And peers give way, exalted as they are,",
  "Even to their own s-r-v--nce in a car?",
  "",
  "Go, lofty poet! and in such a crowd,",
  "Sing thy sonorous verse--but not aloud.",
  "Alas! to grottos and to groves we run,",
  "To ease and silence, every Muse's son:",
  "Blackmore himself, for any grand effort,",
  "Would drink and doze at Tooting or Earl's Court.",
  "How shall I rhyme in this eternal roar?",
  "How match the bards whom none e'er match'd before?",
  "",
  "The man, who, stretch'd in Isis' calm retreat,",
  "To books and study gives seven years complete,",
  "See! strew'd with learned dust, his nightcap on,",
  "He walks, an object new beneath the sun!",
  "The boys flock round him, and the people stare:",
  "So stiff, so mute! some statue, you would swear,",
  "Stepp'd from its pedestal to take the air!",
  "And here, while town, and court, and city roars,",
  "With mobs, and duns, and soldiers, at their doors:",
  "Shall I, in London, act this idle part?",
  "Composing songs, for fools to get by heart?",
  "",
  "The Temple late two brother sergeants saw,",
  "Who deem'd each other oracles of law;",
  "With equal talents, these congenial souls,",
  "One lull'd th' Exchequer, and one stunn'd the Rolls;",
  "Each had a gravity would make you split,",
  "And shook his head at Murray, as a wit.",
  "''Twas, sir, your law'--and 'Sir, your eloquence,'",
  "'Yours, Cowper's manner--and yours, Talbot's sense.'",
  "",
  "Thus we dispose of all poetic merit,",
  "Yours Milton's genius, and mine Homer's spirit.",
  "Call Tibbald Shakspeare, and he'll swear the Nine,",
  "Dear Cibber! never match'd one ode of thine.",
  "Lord! how we strut through Merlin's cave, to see",
  "No poets there, but, Stephen, you, and me.",
  "Walk with respect behind, while we at ease",
  "Weave laurel crowns, and take what names we please.",
  "'My dear Tibullus!' if that will not do,",
  "'Let me be Horace, and be Ovid you:'",
  "Or 'I'm content, allow me Dryden's strains,",
  "And you shall rise up Otway for your pains.'",
  "Much do I suffer, much, to keep in peace",
  "This jealous, waspish, wrong-head, rhyming race;",
  "And much must flatter, if the whim should bite",
  "To court applause by printing what I write:",
  "But let the fit pass o'er, I'm wise enough",
  "To stop my ears to their confounded stuff.",
  "",
  "In vain bad rhymers all mankind reject,",
  "They treat themselves with most profound respect;",
  "'Tis to small purpose that you hold your tongue,",
  "Each, praised within, is happy all day long,",
  "But how severely with themselves proceed",
  "The men, who write such verse as we can read?",
  "Their own strict judges, not a word they spare",
  "That wants, or force, or light, or weight, or care,",
  "Howe'er unwillingly it quits its place,",
  "Nay though at court (perhaps) it may find grace:",
  "Such they'll degrade; and sometimes, in its stead,",
  "In downright charity revive the dead;",
  "Mark where a bold expressive phrase appears,",
  "Bright through the rubbish of some hundred years;",
  "Command old words, that long have slept, to wake,",
  "Words that wise Bacon or brave Raleigh spake;",
  "Or bid the new be English, ages hence,",
  "(For use will father what's begot by sense)",
  "Pour the full tide of eloquence along,",
  "Serenely pure, and yet divinely strong,",
  "Rich with the treasures of each foreign tongue;",
  "Prune the luxuriant, the uncouth refine,",
  "But show no mercy to an empty line:",
  "Then polish all, with so much life and ease,",
  "You think 'tis nature, and a knack to please:",
  "But ease in writing flows from art, not chance;",
  "As those move easiest who have learn'd to dance.",
  "",
  "If such the plague and pains to write by rule,",
  "Better (say I) be pleased, and play the fool;",
  "Call, if you will, bad rhyming a disease,",
  "It gives men happiness, or leaves them ease.",
  "There lived _in primo Georgii_ (they record)",
  "A worthy member, no small fool, a lord;",
  "Who, though the House was up, delighted sat,",
  "Heard, noted, answer'd, as in full debate:",
  "In all but this, a man of sober life,",
  "Fond of his friend, and civil to his wife;",
  "Not quite a madman, though a pasty fell,",
  "And much too wise to walk into a well.",
  "Him, the damn'd doctors and his friends immured,",
  "They bled, they cupp'd, they purged; in short, they cured:",
  "Whereat the gentleman began to stare--",
  "'My friends!' he cried, 'pox take you for your care!",
  "That from a patriot of distinguish'd note,",
  "Have bled and purged me to a simple vote.'",
  "",
  "Well, on the whole, plain prose must be my fate:",
  "Wisdom (curse on it!) will come soon or late.",
  "There is a time when poets will grow dull:",
  "I'll e'en leave verses to the boys at school:",
  "To rules of poetry no more confined,",
  "I learn to smooth and harmonise my mind,",
  "Teach every thought within its bounds to roll,",
  "And keep the equal measure of the soul.",
  "",
  "Soon as I enter at my country door,",
  "My mind resumes the thread it dropped before;",
  "Thoughts, which at Hyde-park-corner I forgot,",
  "Meet, and rejoin me, in the pensive grot,",
  "There all alone, and compliments apart,",
  "I ask these sober questions of my heart:",
  "",
  "If, when the more you drink, the more you crave,",
  "You tell the doctor; when the more you have,",
  "The more you want, why not with equal ease",
  "Confess as well your folly, as disease?",
  "The heart resolves this matter in a trice,",
  "'Men only feel the smart, but not the vice.'",
  "",
  "When golden angels cease to cure the evil,",
  "You give all royal witchcraft to the devil:",
  "When servile chaplains cry, that birth and place",
  "Indue a peer with honour, truth, and grace,",
  "Look in that breast, most dirty D----! be fair,",
  "Say, can you find out one such lodger there?",
  "Yet still, not heeding what your heart can teach,",
  "You go to church to hear these flatterers preach.",
  "Indeed, could wealth bestow or wit or merit,",
  "A grain of courage, or a spark of spirit,",
  "The wisest man might blush, I must agree,",
  "If D---- loved sixpence more than he.",
  "",
  "If there be truth in law, and use can give",
  "A property, that's yours on which you live.",
  "Delightful Abbs Court, if its fields afford",
  "Their fruits to you, confesses you its lord:",
  "All Worldly's hens, nay, partridge, sold to town,",
  "His ven'son, too, a guinea makes your own:",
  "He bought at thousands, what with better wit",
  "You purchase as you want, and bit by bit;",
  "Now, or long since, what difference will be found?",
  "You pay a penny, and he paid a pound.",
  "",
  "Heathcote himself, and such large-acred men,",
  "Lords of fat Ev'sham, or of Lincoln fen,",
  "Buy every stick of wood that lends them heat,",
  "Buy every pullet they afford to eat.",
  "Yet these are wights who fondly call their own",
  "Half that the devil o'erlooks from Lincoln town.",
  "The laws of God, as well as of the land,",
  "Abhor a perpetuity should stand:",
  "Estates have wings, and hang in fortune's power",
  "Loose on the point of every wavering hour,",
  "Ready, by force, or of your own accord,",
  "By sale, at least by death, to change their lord.",
  "Man? and for ever? wretch! what wouldst thou have?",
  "Heir urges heir, like wave impelling wave.",
  "All vast possessions (just the same the case",
  "Whether you call them villa, park, or chase)",
  "Alas, my Bathurst! what will they avail!",
  "Join Cotswood hills to Saperton's fair dale,",
  "Let rising granaries and temples here,",
  "There mingled farms and pyramids appear,",
  "Link towns to towns with avenues of oak,",
  "Enclose whole downs in walls,--'tis all a joke!",
  "Inexorable death shall level all,",
  "And trees, and stones, and farms, and farmer fall.",
  "",
  "Gold, silver, ivory, vases sculptured high,",
  "Paint, marble, gems, and robes of Persian dye,",
  "There are who have not--and, thank Heaven, there are,",
  "Who, if they have not, think not worth their care.",
  "",
  "Talk what you will of taste, my friend, you'll find,",
  "Two of a face, as soon as of a mind.",
  "Why, of two brothers, rich and restless one",
  "Ploughs, burns, manures, and toils from sun to sun;",
  "The other slights, for women, sports, and wines,",
  "All Townshend's turnips, and all Grosvenor's mines:",
  "Why one like Bu----, with pay and scorn content,",
  "Bows and votes on, in court and parliament;",
  "One, driven by strong benevolence of soul,",
  "Shall fly, like Oglethorpe, from pole to pole:",
  "Is known alone to that Directing Power,",
  "Who forms the genius in the natal hour;",
  "That God of Nature, who, within us still,",
  "Inclines our action, not constrains our will;",
  "Various of temper, as of face or frame,",
  "Each individual: His great end the same.",
  "",
  "Yes, sir, how small soever be my heap,",
  "A part I will enjoy, as well as keep.",
  "My heir may sigh, and think it want of grace",
  "A man so poor would live without a place:",
  "But sure no statute in his favour says,",
  "How free, or frugal, I shall pass my days:",
  "I, who at some times spend, at others spare,",
  "Divided between carelessness and care.",
  "'Tis one thing madly to disperse my store:",
  "Another, not to heed to treasure more;",
  "Glad, like a boy, to snatch the first good day,",
  "And pleased, if sordid want be far away.",
  "",
  "What is't to me (a passenger, God wot!)",
  "Whether my vessel be first-rate or not?",
  "The ship itself may make a better figure,",
  "But I that sail am neither less nor bigger.",
  "I neither strut with every favouring breath,",
  "Nor strive with all the tempest in my teeth.",
  "In power, wit, figure, virtue, fortune, placed",
  "Behind the foremost, and before the last.",
  "",
  "'But why all this of avarice? I have none.'",
  "I wish you joy, sir, of a tyrant gone;",
  "But does no other lord it at this hour,",
  "As wild and mad--the avarice of power?",
  "Does neither rage inflame, nor fear appal?",
  "Not the black fear of death, that saddens all?",
  "With terrors round, can reason hold her throne,",
  "Despise the known, nor tremble at the unknown?",
  "Survey both worlds, intrepid and entire,",
  "In spite of witches, devils, dreams, and fire?",
  "Pleased to look forward, pleased to look behind,",
  "And count each birthday with a grateful mind?",
  "Has life no sourness, drawn so near its end?",
  "Canst thou endure a foe, forgive a friend?",
  "Has age but melted the rough parts away,",
  "As winter-fruits grow mild ere they decay?",
  "Or will you think, my friend, your business done,",
  "When, of a hundred thorns, you pull out one?",
  "",
  "Learn to live well, or fairly make your will;",
  "You've play'd, and loved, and eat, and drank your fill:",
  "Walk sober off, before a sprightlier age",
  "Comes tittering on, and shoves you from the stage:",
  "Leave such to trifle with more grace and ease,",
  "Whom folly pleases, and whose follies please.",
  "",
  "       *       *       *       *       *",
  "",
  "BOOK I. EPISTLE VII.",
  "",
  "IMITATED IN THE MANNER OF DR SWIFT.",
  "",
  "'Tis true, my lord, I gave my word,",
  "I would be with you, June the third;",
  "Changed it to August, and (in short)",
  "Have kept it--as you do at court.",
  "You humour me when I am sick,",
  "Why not when I am splenetic?",
  "In town, what objects could I meet?",
  "The shops shut up in every street,",
  "And funerals blackening all the doors,",
  "And yet more melancholy whores:",
  "And what a dust in every place!",
  "And a thin court that wants your face,",
  "And fevers raging up and down,",
  "And W---- and H---- both in town!",
  "",
  "'The dog-days are no more the case.'",
  "'Tis true, but winter comes apace:",
  "Then southward let your bard retire,",
  "Hold out some months 'twixt sun and fire,",
  "And you shall see, the first warm weather,",
  "Me and the butterflies together.",
  "",
  "My lord, your favours well I know;",
  "'Tis with distinction you bestow;",
  "And not to every one that comes,",
  "Just as a Scotchman does his plums.",
  "'Pray, take them, sir,--enough's a feast:",
  "Eat some, and pocket up the rest.'",
  "What! rob your boys? those pretty rogues",
  "'No, sir, you'll leave them to the hogs.'",
  "Thus fools with compliments besiege ye,",
  "Contriving never to oblige ye.",
  "Scatter your favours on a fop,",
  "Ingratitude's the certain crop;",
  "And 'tis but just, I'll tell ye wherefore,",
  "You give the things you never care for.",
  "A wise man always is, or should,",
  "Be mighty ready to do good;",
  "But makes a difference in his thought",
  "Betwixt a guinea and a groat.",
  "",
  "Now this I'll say, you'll find in me",
  "A safe companion, and a free;",
  "But if you'd have me always near--",
  "A word, pray, in your honour's ear.",
  "I hope it is your resolution",
  "To give me back my constitution!",
  "The sprightly wit, the lively eye,",
  "Th' engaging smile, the gaiety,",
  "That laugh'd down many a summer sun,",
  "And kept you up so oft till one:",
  "And all that voluntary vein,",
  "As when Belinda raised my strain.",
  "",
  "A weasel once made shift to slink",
  "In at a corn-loft through a chink;",
  "But having amply stuff'd his skin,",
  "Could not get out as he got in:",
  "Which one belonging to the house",
  "('Twas not a man, it was a mouse)",
  "Observing, cried, 'You 'scape not so;",
  "Lean as you came, sir, you must go.'",
  "",
  "Sir, you may spare your application,",
  "I'm no such beast, nor his relation;",
  "Nor one that temperance advance,",
  "Cramm'd to the throat with ortolans:",
  "Extremely ready to resign",
  "All that may make me none of mine.",
  "South-Sea subscriptions take who please,",
  "Leave me but liberty and ease.",
  "'Twas what I said to Craggs and Child,",
  "Who praised my modesty, and smiled.",
  "Give me, I cried, (enough for me)",
  "My bread, and independency!",
  "So bought an annual rent or two,",
  "And lived--just as you see I do;",
  "Near fifty, and without a wife,",
  "I trust that sinking fund, my life.",
  "Can I retrench? Yes, mighty well,",
  "Shrink back to my paternal cell,",
  "A little house, with trees a-row,",
  "And, like its master, very low.",
  "There died my father, no man's debtor,",
  "And there I'll die, nor worse, nor better.",
  "",
  "To set this matter full before ye,",
  "Our old friend Swift will tell his story.",
  "",
  "'Harley, the nation's great support'--",
  "But you may read it,--I stop short.",
  ""
]