module.exports = [
  "SATIRES AND EPISTLES OF HORACE IMITATED.",
  "",
  "_P_. There are (I scarce can think it, but am told)",
  "There are, to whom my satire seems too bold:",
  "Scarce to wise Peter complaisant enough,",
  "And something said of Chartres much too rough.",
  "The lines are weak, another's pleased to say,",
  "Lord Fanny spins a thousand such a day.",
  "Timorous by nature, of the rich in awe,",
  "I come to counsel learnèd in the law:",
  "'You'll give me, like a friend both sage and free,",
  "Advice; and (as you use) without a fee.'",
  "",
  "_F_. I'd write no more.",
  "",
  "_P_.              Not write? but then I think,",
  "And for my soul I cannot sleep a wink.",
  "I nod in company, I wake at night,",
  "Fools rush into my head, and so I write.",
  "",
  "_F_. You could not do a worse thing for your life.",
  "Why, if the nights seem tedious--take a wife:",
  "Or rather truly, if your point be rest,",
  "Lettuce and cowslip-wine; _probatum est_.",
  "But talk with Celsus, Celsus will advise",
  "Hartshorn, or something that shall close your eyes.",
  "Or, if you needs must write, write Caesar's praise,",
  "You'll gain at least a knighthood, or the bays.",
  "",
  "_P_. What! like Sir Richard, rumbling, rough, and fierce,",
  "With arms, and George, and Brunswick crowd the verse,",
  "Rend with tremendous sound your ears asunder,",
  "With gun, drum, trumpet, blunderbuss, and thunder?",
  "Or, nobly wild, with Budgell's fire and force,",
  "Paint angels trembling round his falling horse?",
  "",
  "_F_. Then all your Muse's softer art display,",
  "Let Carolina smooth the tuneful lay,",
  "Lull with Amelia's liquid name the Nine,",
  "And sweetly flow through all the royal line.",
  "",
  "_P_. Alas! few verses touch their nicer ear;",
  "They scarce can bear their Laureate twice a-year;",
  "And justly Caesar scorns the poet's lays,",
  "It is to history he trusts for praise.",
  "",
  "_F_. Better be Cibber, I'll maintain it still,",
  "Than ridicule all taste, blaspheme quadrille,",
  "Abuse the city's best good men in metre,",
  "And laugh at peers that put their trust in Peter.",
  "Even those you touch not, hate you.",
  "",
  "_P_.                What should ail them?",
  "",
  "_F_. A hundred smart in Timon and in Balaam:",
  "The fewer still you name, you wound the more;",
  "Bond is but one, but Harpax is a score.",
  "",
  "_P_. Each mortal has his pleasure: none deny",
  "Scarsdale his bottle, Darty his ham-pie;",
  "Ridotta sips and dances, till she see",
  "The doubling lustres dance as fast as she;",
  "F---- loves the Senate, Hockley-hole his brother,",
  "Like in all else, as one egg to another.",
  "I love to pour out all myself, as plain",
  "As downright Shippen, or as old Montaigne:",
  "In them, as certain to be loved as seen,",
  "The soul stood forth, nor kept a thought within;",
  "In me what spots (for spots I have) appear,",
  "Will prove at least the medium must be clear.",
  "In this impartial glass, my Muse intends",
  "Fair to expose myself, my foes, my friends;",
  "Publish the present age; but, where my text",
  "Is vice too high, reserve it for the next:",
  "My foes shall wish my life a longer date,",
  "And every friend the less lament my fate,",
  "My head and heart thus flowing through my quill,",
  "Verse-man or prose-man, term me which you will,",
  "Papist or Protestant, or both between,",
  "Like good Erasmus, in an honest mean,",
  "In moderation placing all my glory,",
  "While Tories call me Whig, and Whigs a Tory.",
  "",
  "Satire's my weapon, but I'm too discreet",
  "To run a-muck, and tilt at all I meet;",
  "I only wear it in a land of hectors,",
  "Thieves, supercargoes, sharpers, and directors.",
  "Save but our army! and let Jove incrust",
  "Swords, pikes, and guns, with everlasting rust!",
  "Peace is my dear delight--not Fleury's more:",
  "But touch me, and no minister so sore.",
  "Whoe'er offends, at some unlucky time",
  "Slides into verse, and hitches in a rhyme,",
  "Sacred to ridicule his whole life long,",
  "And the sad burthen of some merry song.",
  "",
  "Slander or poison dread from Delia's rage,",
  "Hard words or hanging, if your judge be Page.",
  "From furious Sappho scarce a milder fate,",
  "Pox'd by her love, or libell'd by her hate.",
  "Its proper power to hurt, each creature feels;",
  "Bulls aim their horns, and asses lift their heels;",
  "'Tis a bear's talent not to kick, but hug;",
  "And no man wonders he's not stung by pug.",
  "So drink with Walters, or with Chartres eat,",
  "They'll never poison you, they'll only cheat.",
  "",
  "Then, learnèd sir! (to cut the matter short)",
  "Whate'er my fate, or well or ill at court,",
  "Whether old age, with faint but cheerful ray,",
  "Attends to gild the evening of my day,",
  "Or death's black wing already be display'd,",
  "To wrap me in the universal shade;",
  "Whether the darken'd room to muse invite,",
  "Or whiten'd wall provoke the skewer to write:",
  "In durance, exile, Bedlam, or the Mint,",
  "Like Lee or Budgell, I will rhyme and print.",
  "",
  "_F_. Alas, young man! your days can ne'er be long,",
  "In flower of age you perish for a song!",
  "Plums and directors, Shylock and his wife,",
  "Will club their testers, now, to take your life!",
  "",
  "_P_. What? arm'd for Virtue, when I point the pen,",
  "Brand the bold front of shameless guilty men;",
  "Dash the proud gamester in his gilded car;",
  "Bare the mean heart that lurks beneath a star;",
  "Can there be wanting to defend her cause,",
  "Lights of the Church, or guardians of the laws?",
  "Could pension'd Boileau lash, in honest strain,",
  "Flatterers and bigots even in Louis' reign?",
  "Could Laureate Dryden pimp and friar engage,",
  "Yet neither Charles nor James be in a rage?",
  "And I not strip the gilding off a knave,",
  "Unplaced, unpension'd, no man's heir, or slave?",
  "I will, or perish in the generous cause:",
  "Hear this, and tremble! you who 'scape the laws.",
  "Yes, while I live, no rich or noble knave",
  "Shall walk the world, in credit, to his grave.",
  "TO VIRTUE ONLY, AND HER FRIENDS, A FRIEND,",
  "The world beside may murmur, or commend.",
  "Know, all the distant din that world can keep,",
  "Rolls o'er my grotto, and but soothes my sleep.",
  "There, my retreat the best companions grace,",
  "Chiefs out of war, and statesmen out of place.",
  "There St John mingles with my friendly bowl",
  "The feast of reason and the flow of soul:",
  "And he, whose lightning pierced th' Iberian lines,",
  "Now forms my quincunx, and now ranks my vines,",
  "Or tames the genius of the stubborn plain,",
  "Almost as quickly as he conquer'd Spain.",
  "",
  "Envy must own, I live among the great,",
  "No pimp of pleasure, and no spy of state,",
  "With eyes that pry not, tongue that ne'er repeats,",
  "Fond to spread friendships, but to cover heats;",
  "To help who want, to forward who excel;--",
  "This, all who know me, know; who love me, tell;",
  "And who unknown defame me, let them be",
  "Scribblers or peers, alike are mob to me.",
  "This is my plea, on this I rest my cause--",
  "What saith my counsel, learnèd in the laws?",
  "",
  "_F_. Your plea is good; but still, I say, beware!",
  "Laws are explain'd by men--so have a care!",
  "It stands on record, that in Richard's times",
  "A man was hang'd for very honest rhymes.",
  "Consult the statute: _quart_. I think, it is,",
  "_Edwardi Sext_. or _prim, et quint. Eliz_.",
  "See 'Libels, Satires'--here you have it--read.",
  "",
  "_P_. Libels and satires! lawless things indeed!",
  "But grave epistles, bringing vice to light,",
  "Such as a king might read, a bishop write,",
  "Such as Sir Robert would approve--",
  "",
  "_F_.                           Indeed?",
  "The case is alter'd--you may then proceed;",
  "In such a cause the plaintiff will be hiss'd,",
  "My lords the judges laugh, and you're dismiss'd.",
  ""
]