module.exports = [
  "1",
  "I SAY whatever tastes sweet to the most perfect person, that is finally right.",
  "2",
  "I say nourish a great intellect, a great brain;",
  "If I have said anything to the contrary, I hereby retract it.",
  "",
  "3",
  "I say man shall not hold property in man;",
  "I say the least developed person on earth is just as important and sacred to himself or",
  "  herself, as the most developed person is to himself or herself.",
  "",
  "4",
  "I say where liberty draws not the blood out of slavery, there slavery draws the blood out",
  "    of",
  "  liberty,",
  "I say the word of the good old cause in These States, and resound it hence over the world.",
  "",
  "",
  "5",
  "I say the human shape or face is so great, it must never be made ridiculous;",
  "I say for ornaments nothing outre can be allowed,",
  "And that anything is most beautiful without ornament,",
  "And that exaggerations will be sternly revenged in your own physiology, and in other",
  "  persons’ physiology also;",
  "And I say that clean-shaped children can be jetted and conceived only where natural forms",
  "  prevail in public, and the human face and form are never caricatured;",
  "And I say that genius need never more be turned to romances,",
  "(For facts properly told, how mean appear all romances.)",
  "",
  "6",
  "I say the word of lands fearing nothing—I will have no other land;",
  "I say discuss all and expose all—I am for every topic openly;",
  "I say there can be no salvation for These States without innovators—without free",
  "    tongues,",
  "  and ears willing to hear the tongues;",
  "And I announce as a glory of These States, that they respectfully listen to propositions,",
  "  reforms, fresh views and doctrines, from successions of men and women,",
  "Each age with its own growth.",
  "",
  "7",
  "I have said many times that materials and the Soul are great, and that all depends on",
  "    physique;",
  "Now I reverse what I said, and affirm that all depends on the æsthetic or",
  "    intellectual,",
  "And that criticism is great—and that refinement is greatest of all;",
  "And I affirm now that the mind governs—and that all depends on the mind.",
  "",
  "8",
  "With one man or woman—(no matter which one—I even pick out the lowest,)",
  "With him or her I now illustrate the whole law;",
  "I say that every right, in politics or what-not, shall be eligible to that one man or",
  "    woman, on",
  "  the same terms as any.",
  ""
]