module.exports = [
  "MADDALO, A COURTIER.",
  "MALPIGLIO, A POET.",
  "PIGNA, A MINISTER.",
  "ALBANO, AN USHER.",
  "",
  "MADDALO:",
  "No access to the Duke! You have not said",
  "That the Count Maddalo would speak with him?",
  "",
  "PIGNA:",
  "Did you inform his Grace that Signor Pigna",
  "Waits with state papers for his signature?",
  "",
  "MALPIGLIO:",
  "The Lady Leonora cannot know",
  "That I have written a sonnet to her fame,",
  "In which I ... Venus and Adonis.",
  "You should not take my gold and serve me not.",
  "",
  "ALBANO:",
  "In truth I told her, and she smiled and said,",
  "'If I am Venus, thou, coy Poesy,",
  "Art the Adonis whom I love, and he",
  "The Erymanthian boar that wounded him.'",
  "O trust to me, Signor Malpiglio,",
  "Those nods and smiles were favours worth the zechin.",
  "",
  "MALPIGLIO:",
  "The words are twisted in some double sense",
  "That I reach not: the smiles fell not on me.",
  "",
  "PIGNA:",
  "How are the Duke and Duchess occupied?",
  "",
  "ALBANO:",
  "Buried in some strange talk. The Duke was leaning,",
  "His finger on his brow, his lips unclosed.",
  "The Princess sate within the window-seat,",
  "And so her face was hid; but on her knee",
  "Her hands were clasped, veined, and pale as snow,",
  "And quivering--young Tasso, too, was there.",
  "",
  "MADDALO:",
  "Thou seest on whom from thine own worshipped heaven",
  "Thou drawest down smiles--they did not rain on thee.",
  "",
  "MALPIGLIO:",
  "Would they were parching lightnings for his sake",
  "On whom they fell!",
  "",
  "SONG FOR 'TASSO'.",
  "",
  "I loved--alas! our life is love;",
  "But when we cease to breathe and move",
  "I do suppose love ceases too.",
  "I thought, but not as now I do,",
  "Keen thoughts and bright of linked lore,",
  "Of all that men had thought before.",
  "And all that Nature shows, and more.",
  "",
  "And still I love and still I think,",
  "But strangely, for my heart can drink",
  "The dregs of such despair, and live,",
  "And love;...",
  "And if I think, my thoughts come fast,",
  "I mix the present with the past,",
  "And each seems uglier than the last.",
  "",
  "Sometimes I see before me flee",
  "A silver spirit's form, like thee,",
  "O Leonora, and I sit",
  "...still watching it,",
  "Till by the grated casement's ledge",
  "It fades, with such a sigh, as sedge",
  "Breathes o'er the breezy streamlet's edge.",
  ""
]