module.exports = [
  "FROM THE SPANISH OF CALDERON.",
  "",
  "SCENE 1:",
  "",
  "ENTER CYPRIAN, DRESSED AS A STUDENT;",
  "CLARIN AND MOSCON AS POOR SCHOLARS, WITH BOOKS.",
  "",
  "CYPRIAN:",
  "In the sweet solitude of this calm place,",
  "This intricate wild wilderness of trees",
  "And flowers and undergrowth of odorous plants,",
  "Leave me; the books you brought out of the house",
  "To me are ever best society.",
  "And while with glorious festival and song,",
  "Antioch now celebrates the consecration",
  "Of a proud temple to great Jupiter,",
  "And bears his image in loud jubilee",
  "To its new shrine, I would consume what still",
  "Lives of the dying day in studious thought,",
  "Far from the throng and turmoil. You, my friends,",
  "Go, and enjoy the festival; it will",
  "Be worth your pains. You may return for me",
  "When the sun seeks its grave among the billows",
  "Which, among dim gray clouds on the horizon,",
  "Dance like white plumes upon a hearse;-- and here",
  "I shall expect you.",
  "",
  "MOSCON:",
  "I cannot bring my mind,",
  "Great as my haste to see the festival",
  "Certainly is, to leave you, Sir, without",
  "Just saying some three or four thousand words.",
  "How is it possible that on a day",
  "Of such festivity, you can be content",
  "To come forth to a solitary country",
  "With three or four old books, and turn your back",
  "On all this mirth?",
  "",
  "CLARIN:",
  "My master's in the right;",
  "There is not anything more tiresome",
  "Than a procession day, with troops, and priests,",
  "And dances, and all that.",
  "",
  "MOSCON:",
  "From first to last,",
  "Clarin, you are a temporizing flatterer;",
  "You praise not what you feel but what he does;--",
  "Toadeater!",
  "",
  "CLARIN:",
  "You lie--under a mistake--",
  "For this is the most civil sort of lie",
  "That can be given to a man's face. I now",
  "Say what I think.",
  "",
  "CYPRIAN:",
  "Enough, you foolish fellows!",
  "Puffed up with your own doting ignorance,",
  "You always take the two sides of one question.",
  "Now go; and as I said, return for me",
  "When night falls, veiling in its shadows wide",
  "This glorious fabric of the universe.",
  "",
  "MOSCON:",
  "How happens it, although you can maintain",
  "The folly of enjoying festivals,",
  "That yet you go there?",
  "",
  "CLARIN:",
  "Nay, the consequence",
  "Is clear:--who ever did what he advises",
  "Others to do?--",
  "",
  "MOSCON:",
  "Would that my feet were wings,",
  "So would I fly to Livia.",
  "",
  "[EXIT.]",
  "",
  "CLARIN:",
  "To speak truth,",
  "Livia is she who has surprised my heart;",
  "But he is more than half-way there.--Soho!",
  "Livia, I come; good sport, Livia, soho!",
  "",
  "[EXIT.]",
  "",
  "CYPRIAN:",
  "Now, since I am alone, let me examine",
  "The question which has long disturbed my mind",
  "With doubt, since first I read in Plinius",
  "The words of mystic import and deep sense",
  "In which he defines God. My intellect",
  "Can find no God with whom these marks and signs",
  "Fitly agree. It is a hidden truth",
  "Which I must fathom.",
  "",
  "[CYPRIAN READS;",
  "THE DAEMON, DRESSED IN A COURT DRESS, ENTERS.]",
  "",
  "DAEMON:",
  "Search even as thou wilt,",
  "But thou shalt never find what I can hide.",
  "",
  "CYPRIAN:",
  "What noise is that among the boughs? Who moves?",
  "What art thou?--",
  "",
  "DAEMON:",
  "'Tis a foreign gentleman.",
  "Even from this morning I have lost my way",
  "In this wild place; and my poor horse at last,",
  "Quite overcome, has stretched himself upon",
  "The enamelled tapestry of this mossy mountain,",
  "And feeds and rests at the same time. I was",
  "Upon my way to Antioch upon business",
  "Of some importance, but wrapped up in cares",
  "(Who is exempt from this inheritance?)",
  "I parted from my company, and lost",
  "My way, and lost my servants and my comrades.",
  "",
  "CYPRIAN:",
  "'Tis singular that even within the sight",
  "Of the high towers of Antioch you could lose",
  "Your way. Of all the avenues and green paths",
  "Of this wild wood there is not one but leads,",
  "As to its centre, to the walls of Antioch;",
  "Take which you will, you cannot miss your road.",
  "",
  "DAEMON:",
  "And such is ignorance! Even in the sight",
  "Of knowledge, it can draw no profit from it.",
  "But as it still is early, and as I",
  "Have no acquaintances in Antioch,",
  "Being a stranger there, I will even wait",
  "The few surviving hours of the day,",
  "Until the night shall conquer it. I see",
  "Both by your dress and by the books in which",
  "You find delight and company, that you",
  "Are a great student;--for my part, I feel",
  "Much sympathy in such pursuits.",
  "",
  "CYPRIAN:",
  "Have you",
  "Studied much?",
  "",
  "DAEMON:",
  "No,--and yet I know enough",
  "Not to be wholly ignorant.",
  "",
  "CYPRIAN:",
  "Pray, Sir,",
  "What science may you know?--",
  "",
  "DAEMON:",
  "Many.",
  "",
  "CYPRIAN:",
  "Alas!",
  "Much pains must we expend on one alone,",
  "And even then attain it not;--but you",
  "Have the presumption to assert that you",
  "Know many without study.",
  "",
  "DAEMON:",
  "And with truth.",
  "For in the country whence I come the sciences",
  "Require no learning,--they are known.",
  "",
  "CYPRIAN:",
  "Oh, would",
  "I were of that bright country! for in this",
  "The more we study, we the more discover",
  "Our ignorance.",
  "",
  "DAEMON:",
  "It is so true, that I",
  "Had so much arrogance as to oppose",
  "The chair of the most high Professorship,",
  "And obtained many votes, and, though I lost,",
  "The attempt was still more glorious, than the failure",
  "Could be dishonourable. If you believe not,",
  "Let us refer it to dispute respecting",
  "That which you know the best, and although I",
  "Know not the opinion you maintain, and though",
  "It be the true one, I will take the contrary.",
  "",
  "CYPRIAN:",
  "The offer gives me pleasure. I am now",
  "Debating with myself upon a passage",
  "Of Plinius, and my mind is racked with doubt",
  "To understand and know who is the God",
  "Of whom he speaks.",
  "",
  "DAEMON:",
  "It is a passage, if",
  "I recollect it right, couched in these words",
  "'God is one supreme goodness, one pure essence,",
  "One substance, and one sense, all sight, all hands.'",
  "",
  "CYPRIAN:",
  "'Tis true.",
  "",
  "DAEMON:",
  "What difficulty find you here?",
  "",
  "CYPRIAN:",
  "I do not recognize among the Gods",
  "The God defined by Plinius; if he must",
  "Be supreme goodness, even Jupiter",
  "Is not supremely good; because we see",
  "His deeds are evil, and his attributes",
  "Tainted with mortal weakness; in what manner",
  "Can supreme goodness be consistent with",
  "The passions of humanity?",
  "",
  "DAEMON:",
  "The wisdom",
  "Of the old world masked with the names of Gods",
  "The attributes of Nature and of Man;",
  "A sort of popular philosophy.",
  "",
  "CYPRIAN:",
  "This reply will not satisfy me, for",
  "Such awe is due to the high name of God",
  "That ill should never be imputed. Then,",
  "Examining the question with more care,",
  "It follows, that the Gods would always will",
  "That which is best, were they supremely good.",
  "How then does one will one thing, one another?",
  "And that you may not say that I allege",
  "Poetical or philosophic learning:--",
  "Consider the ambiguous responses",
  "Of their oracular statues; from two shrines",
  "Two armies shall obtain the assurance of",
  "One victory. Is it not indisputable",
  "That two contending wills can never lead",
  "To the same end? And, being opposite,",
  "If one be good, is not the other evil?",
  "Evil in God is inconceivable;",
  "But supreme goodness fails among the Gods",
  "Without their union.",
  "",
  "DAEMON:",
  "I deny your major.",
  "These responses are means towards some end",
  "Unfathomed by our intellectual beam.",
  "They are the work of Providence, and more",
  "The battle's loss may profit those who lose,",
  "Than victory advantage those who win.",
  "",
  "CYPRIAN:",
  "That I admit; and yet that God should not",
  "(Falsehood is incompatible with deity)",
  "Assure the victory; it would be enough",
  "To have permitted the defeat. If God",
  "Be all sight,--God, who had beheld the truth,",
  "Would not have given assurance of an end",
  "Never to be accomplished: thus, although",
  "The Deity may according to his attributes",
  "Be well distinguished into persons, yet",
  "Even in the minutest circumstance",
  "His essence must be one.",
  "",
  "DAEMON:",
  "To attain the end",
  "The affections of the actors in the scene",
  "Must have been thus influenced by his voice.",
  "",
  "CYPRIAN:",
  "But for a purpose thus subordinate",
  "He might have employed Genii, good or evil,--",
  "A sort of spirits called so by the learned,",
  "Who roam about inspiring good or evil,",
  "And from whose influence and existence we",
  "May well infer our immortality.",
  "Thus God might easily, without descent",
  "To a gross falsehood in his proper person,",
  "Have moved the affections by this mediation",
  "To the just point.",
  "",
  "DAEMON:",
  "These trifling contradictions",
  "Do not suffice to impugn the unity",
  "Of the high Gods; in things of great importance",
  "They still appear unanimous; consider",
  "That glorious fabric, man,--his workmanship",
  "Is stamped with one conception.",
  "",
  "CYPRIAN:",
  "Who made man",
  "Must have, methinks, the advantage of the others.",
  "If they are equal, might they not have risen",
  "In opposition to the work, and being",
  "All hands, according to our author here,",
  "Have still destroyed even as the other made?",
  "If equal in their power, unequal only",
  "In opportunity, which of the two",
  "Will remain conqueror?",
  "",
  "DAEMON:",
  "On impossible",
  "And false hypothesis there can be built",
  "No argument. Say, what do you infer",
  "From this?",
  "",
  "CYPRIAN:",
  "That there must be a mighty God",
  "Of supreme goodness and of highest grace,",
  "All sight, all hands, all truth, infallible,",
  "Without an equal and without a rival,",
  "The cause of all things and the effect of nothing,",
  "One power, one will, one substance, and one essence.",
  "And, in whatever persons, one or two,",
  "His attributes may be distinguished, one",
  "Sovereign power, one solitary essence,",
  "One cause of all cause.",
  "",
  "[THEY RISE.]",
  "",
  "DAEMON:",
  "How can I impugn",
  "So clear a consequence?",
  "",
  "CYPRIAN:",
  "Do you regret",
  "My victory?",
  "",
  "DAEMON:",
  "Who but regrets a check",
  "In rivalry of wit? I could reply",
  "And urge new difficulties, but will now",
  "Depart, for I hear steps of men approaching,",
  "And it is time that I should now pursue",
  "My journey to the city.",
  "",
  "CYPRIAN:",
  "Go in peace!",
  "",
  "DAEMON:",
  "Remain in peace!--Since thus it profits him",
  "To study, I will wrap his senses up",
  "In sweet oblivion of all thought but of",
  "A piece of excellent beauty; and, as I",
  "Have power given me to wage enmity",
  "Against Justina's soul, I will extract",
  "From one effect two vengeances.",
  "",
  "[ASIDE AND EXIT.]",
  "",
  "CYPRIAN:",
  "I never",
  "Met a more learned person. Let me now",
  "Revolve this doubt again with careful mind.",
  "",
  "[HE READS.]",
  "",
  "[FLORO AND LELIO ENTER.]",
  "",
  "LELIO:",
  "Here stop. These toppling rocks and tangled boughs,",
  "Impenetrable by the noonday beam,",
  "Shall be sole witnesses of what we--",
  "",
  "FLORO:",
  "Draw!",
  "If there were words, here is the place for deeds.",
  "",
  "LELIO:",
  "Thou needest not instruct me; well I know",
  "That in the field, the silent tongue of steel",
  "Speaks thus,--",
  "",
  "[THEY FIGHT.]",
  "",
  "CYPRIAN:",
  "Ha! what is this? Lelio,--Floro,",
  "Be it enough that Cyprian stands between you,",
  "Although unarmed.",
  "",
  "LELIO:",
  "Whence comest thou, to stand",
  "Between me and my vengeance?",
  "",
  "FLORO:",
  "From what rocks",
  "And desert cells?",
  "",
  "[ENTER MOSCON AND CLARIN.]",
  "",
  "MOSCON:",
  "Run! run! for where we left",
  "My master. I now hear the clash of swords.",
  "",
  "CLARIN:",
  "I never run to approach things of this sort",
  "But only to avoid them. Sir! Cyprian! sir!",
  "",
  "CYPRIAN:",
  "Be silent, fellows! What! two friends who are",
  "In blood and fame the eyes and hope of Antioch,",
  "One of the noble race of the Colalti,",
  "The other son o' the Governor, adventure",
  "And cast away, on some slight cause no doubt,",
  "Two lives, the honour of their country?",
  "",
  "LELIO:",
  "Cyprian!",
  "Although my high respect towards your person",
  "Holds now my sword suspended, thou canst not",
  "Restore it to the slumber of the scabbard:",
  "Thou knowest more of science than the duel;",
  "For when two men of honour take the field,",
  "No counsel nor respect can make them friends",
  "But one must die in the dispute.",
  "",
  "FLORO:",
  "I pray",
  "That you depart hence with your people, and",
  "Leave us to finish what we have begun",
  "Without advantage.--",
  "",
  "CYPRIAN:",
  "Though you may imagine",
  "That I know little of the laws of duel,",
  "Which vanity and valour instituted,",
  "You are in error. By my birth I am",
  "Held no less than yourselves to know the limits",
  "Of honour and of infamy, nor has study",
  "Quenched the free spirit which first ordered them;",
  "And thus to me, as one well experienced",
  "In the false quicksands of the sea of honour,",
  "You may refer the merits of the case;",
  "And if I should perceive in your relation",
  "That either has the right to satisfaction",
  "From the other, I give you my word of honour",
  "To leave you.",
  "",
  "LELIO:",
  "Under this condition then",
  "I will relate the cause, and you will cede",
  "And must confess the impossibility",
  "Of compromise; for the same lady is",
  "Beloved by Floro and myself.",
  "",
  "FLORO:",
  "It seems",
  "Much to me that the light of day should look",
  "Upon that idol of my heart--but he--",
  "Leave us to fight, according to thy word.",
  "",
  "CYPRIAN:",
  "Permit one question further: is the lady",
  "Impossible to hope or not?",
  "",
  "LELIO:",
  "She is",
  "So excellent, that if the light of day",
  "Should excite Floro's jealousy, it were",
  "Without just cause, for even the light of day",
  "Trembles to gaze on her.",
  "",
  "CYPRIAN:",
  "Would you for your",
  "Part, marry her?",
  "",
  "FLORO:",
  "Such is my confidence.",
  "",
  "CYPRIAN:",
  "And you?",
  "",
  "LELIO:",
  "Oh! would that I could lift my hope",
  "So high, for though she is extremely poor,",
  "Her virtue is her dowry.",
  "",
  "CYPRIAN:",
  "And if you both",
  "Would marry her, is it not weak and vain,",
  "Culpable and unworthy, thus beforehand",
  "To slur her honour? What would the world say",
  "If one should slay the other, and if she",
  "Should afterwards espouse the murderer?",
  "",
  "[THE RIVALS AGREE TO REFER THEIR QUARREL TO CYPRIAN; WHO IN CONSEQUENCE",
  "VISITS JUSTINA, AND BECOMES ENAMOURED OF HER; SHE DISDAINS HIM, AND HE",
  "RETIRES TO A SOLITARY SEA-SHORE.]",
  "",
  "SCENE 2.",
  "",
  "CYPRIAN:",
  "O memory! permit it not",
  "That the tyrant of my thought",
  "Be another soul that still",
  "Holds dominion o'er the will,",
  "That would refuse, but can no more,",
  "To bend, to tremble, and adore.",
  "Vain idolatry!--I saw,",
  "And gazing, became blind with error;",
  "Weak ambition, which the awe",
  "Of her presence bound to terror!",
  "So beautiful she was--and I,",
  "Between my love and jealousy,",
  "Am so convulsed with hope and fear,",
  "Unworthy as it may appear;--",
  "So bitter is the life I live,",
  "That, hear me, Hell! I now would give",
  "To thy most detested spirit",
  "My soul, for ever to inherit,",
  "To suffer punishment and pine,",
  "So this woman may be mine.",
  "Hear'st thou, Hell! dost thou reject it?",
  "My soul is offered!",
  "",
  "DAEMON (UNSEEN):",
  "I accept it.",
  "",
  "[TEMPEST, WITH THUNDER AND LIGHTNING.]",
  "",
  "CYPRIAN:",
  "What is this? ye heavens for ever pure,",
  "At once intensely radiant and obscure!",
  "Athwart the aethereal halls",
  "The lightning's arrow and the thunder-balls",
  "The day affright,",
  "As from the horizon round,",
  "Burst with earthquake sound,",
  "In mighty torrents the electric fountains;--",
  "Clouds quench the sun, and thunder-smoke",
  "Strangles the air, and fire eclipses Heaven.",
  "Philosophy, thou canst not even",
  "Compel their causes underneath thy yoke:",
  "From yonder clouds even to the waves below",
  "The fragments of a single ruin choke",
  "Imagination's flight;",
  "For, on flakes of surge, like feathers light,",
  "The ashes of the desolation, cast",
  "Upon the gloomy blast,",
  "Tell of the footsteps of the storm;",
  "And nearer, see, the melancholy form",
  "Of a great ship, the outcast of the sea,",
  "Drives miserably!",
  "And it must fly the pity of the port,",
  "Or perish, and its last and sole resort",
  "Is its own raging enemy.",
  "The terror of the thrilling cry",
  "Was a fatal prophecy",
  "Of coming death, who hovers now",
  "Upon that shattered prow,",
  "That they who die not may be dying still.",
  "And not alone the insane elements",
  "Are populous with wild portents,",
  "But that sad ship is as a miracle",
  "Of sudden ruin, for it drives so fast",
  "It seems as if it had arrayed its form",
  "With the headlong storm.",
  "It strikes--I almost feel the shock,--",
  "It stumbles on a jagged rock,--",
  "Sparkles of blood on the white foam are cast.",
  "",
  "[A TEMPEST.]",
  "",
  "ALL EXCLAIM [WITHIN]:",
  "We are all lost!",
  "",
  "DAEMON [WITHIN]:",
  "Now from this plank will I",
  "Pass to the land and thus fulfil my scheme.",
  "",
  "CYPRIAN:",
  "As in contempt of the elemental rage",
  "A man comes forth in safety, while the ship's",
  "Great form is in a watery eclipse",
  "Obliterated from the Oceans page,",
  "And round its wreck the huge sea-monsters sit,",
  "A horrid conclave, and the whistling wave",
  "Is heaped over its carcase, like a grave.",
  "",
  "[THE DAEMON ENTERS, AS ESCAPED FROM THE SEA.]",
  "",
  "DAEMON [ASIDE]:",
  "It was essential to my purposes",
  "To wake a tumult on the sapphire ocean,",
  "That in this unknown form I might at length",
  "Wipe out the blot of the discomfiture",
  "Sustained upon the mountain, and assail",
  "With a new war the soul of Cyprian,",
  "Forging the instruments of his destruction",
  "Even from his love and from his wisdom.--O",
  "Beloved earth, dear mother, in thy bosom",
  "I seek a refuge from the monster who",
  "Precipitates itself upon me.",
  "",
  "CYPRIAN:",
  "Friend,",
  "Collect thyself; and be the memory",
  "Of thy late suffering, and thy greatest sorrow",
  "But as a shadow of the past,--for nothing",
  "Beneath the circle of the moon, but flows",
  "And changes, and can never know repose.",
  "",
  "DAEMON:",
  "And who art thou, before whose feet my fate",
  "Has prostrated me?",
  "",
  "CYPRIAN:",
  "One who, moved with pity,",
  "Would soothe its stings.",
  "",
  "DAEMON:",
  "Oh, that can never be!",
  "No solace can my lasting sorrows find.",
  "",
  "CYPRIAN:",
  "Wherefore?",
  "",
  "DAEMON:",
  "Because my happiness is lost.",
  "Yet I lament what has long ceased to be",
  "The object of desire or memory,",
  "And my life is not life.",
  "",
  "CYPRIAN:",
  "Now, since the fury",
  "Of this earthquaking hurricane is still,",
  "And the crystalline Heaven has reassumed",
  "Its windless calm so quickly, that it seems",
  "As if its heavy wrath had been awakened",
  "Only to overwhelm that vessel,--speak,",
  "Who art thou, and whence comest thou?",
  "",
  "DAEMON:",
  "Far more",
  "My coming hither cost, than thou hast seen",
  "Or I can tell. Among my misadventures",
  "This shipwreck is the least. Wilt thou hear?",
  "",
  "CYPRIAN:",
  "Speak.",
  "",
  "DAEMON:",
  "Since thou desirest, I will then unveil",
  "Myself to thee;--for in myself I am",
  "A world of happiness and misery;",
  "This I have lost, and that I must lament",
  "Forever. In my attributes I stood",
  "So high and so heroically great,",
  "In lineage so supreme, and with a genius",
  "Which penetrated with a glance the world",
  "Beneath my feet, that, won by my high merit,",
  "A king--whom I may call the King of kings,",
  "Because all others tremble in their pride",
  "Before the terrors of His countenance,",
  "In His high palace roofed with brightest gems",
  "Of living light--call them the stars of Heaven--",
  "Named me His counsellor. But the high praise",
  "Stung me with pride and envy, and I rose",
  "In mighty competition, to ascend",
  "His seat and place my foot triumphantly",
  "Upon His subject thrones. Chastised, I know",
  "The depth to which ambition falls; too mad",
  "Was the attempt, and yet more mad were now",
  "Repentance of the irrevocable deed:--",
  "Therefore I chose this ruin, with the glory",
  "Of not to be subdued, before the shame",
  "Of reconciling me with Him who reigns",
  "By coward cession.--Nor was I alone,",
  "Nor am I now, nor shall I be alone;",
  "And there was hope, and there may still be hope,",
  "For many suffrages among His vassals",
  "Hailed me their lord and king, and many still",
  "Are mine, and many more, perchance shall be.",
  "Thus vanquished, though in fact victorious,",
  "I left His seat of empire, from mine eye",
  "Shooting forth poisonous lightning, while my words",
  "With inauspicious thunderings shook Heaven,",
  "Proclaiming vengeance, public as my wrong,",
  "And imprecating on His prostrate slaves",
  "Rapine, and death, and outrage. Then I sailed",
  "Over the mighty fabric of the world,--",
  "A pirate ambushed in its pathless sands,",
  "A lynx crouched watchfully among its caves",
  "And craggy shores; and I have wandered over",
  "The expanse of these wide wildernesses",
  "In this great ship, whose bulk is now dissolved",
  "In the light breathings of the invisible wind,",
  "And which the sea has made a dustless ruin,",
  "Seeking ever a mountain, through whose forests",
  "I seek a man, whom I must now compel",
  "To keep his word with me. I came arrayed",
  "In tempest, and although my power could well",
  "Bridle the forest winds in their career,",
  "For other causes I forbore to soothe",
  "Their fury to Favonian gentleness;",
  "I could and would not;",
  "[ASIDE.]",
  "(thus I wake in him",
  "A love of magic art). Let not this tempest,",
  "Nor the succeeding calm excite thy wonder;",
  "For by my art the sun would turn as pale",
  "As his weak sister with unwonted fear;",
  "And in my wisdom are the orbs of Heaven",
  "Written as in a record; I have pierced",
  "The flaming circles of their wondrous spheres",
  "And know them as thou knowest every corner",
  "Of this dim spot. Let it not seem to thee",
  "That I boast vainly; wouldst thou that I work",
  "A charm over this waste and savage wood,",
  "This Babylon of crags and aged trees,",
  "Filling its leafy coverts with a horror",
  "Thrilling and strange? I am the friendless guest",
  "Of these wild oaks and pines--and as from thee",
  "I have received the hospitality",
  "Of this rude place, I offer thee the fruit",
  "Of years of toil in recompense; whate'er",
  "Thy wildest dream presented to thy thought",
  "As object of desire, that shall be thine.",
  "",
  "...",
  "",
  "And thenceforth shall so firm an amity",
  "'Twixt thee and me be, that neither Fortune,",
  "The monstrous phantom which pursues success,",
  "That careful miser, that free prodigal,",
  "Who ever alternates, with changeful hand,",
  "Evil and good, reproach and fame; nor Time,",
  "That lodestar of the ages, to whose beam",
  "The winged years speed o'er the intervals",
  "Of their unequal revolutions; nor",
  "Heaven itself, whose beautiful bright stars",
  "Rule and adorn the world, can ever make",
  "The least division between thee and me,",
  "Since now I find a refuge in thy favour.",
  "",
  "SCENE 3.",
  "",
  "THE DAEMON TEMPTS JUSTINA, WHO IS A CHRISTIAN.",
  "",
  "DAEMON:",
  "Abyss of Hell! I call on thee,",
  "Thou wild misrule of thine own anarchy!",
  "From thy prison-house set free",
  "The spirits of voluptuous death,",
  "That with their mighty breath",
  "They may destroy a world of virgin thoughts;",
  "Let her chaste mind with fancies thick as motes",
  "Be peopled from thy shadowy deep,",
  "Till her guiltless fantasy",
  "Full to overflowing be!",
  "And with sweetest harmony,",
  "Let birds, and flowers, and leaves, and all things move",
  "To love, only to love.",
  "Let nothing meet her eyes",
  "But signs of Love's soft victories;",
  "Let nothing meet her ear",
  "But sounds of Love's sweet sorrow,",
  "So that from faith no succour she may borrow,",
  "But, guided by my spirit blind",
  "And in a magic snare entwined,",
  "She may now seek Cyprian.",
  "Begin, while I in silence bind",
  "My voice, when thy sweet song thou hast began.",
  "",
  "A VOICE [WITHIN]:",
  "What is the glory far above",
  "All else in human life?",
  "",
  "ALL:",
  "Love! love!",
  "",
  "[WHILE THESE WORDS ARE SUNG,",
  "THE DAEMON GOES OUT AT ONE DOOR,",
  "AND JUSTINA ENTERS AT ANOTHER.]",
  "",
  "THE FIRST VOICE:",
  "There is no form in which the fire",
  "Of love its traces has impressed not.",
  "Man lives far more in love's desire",
  "Than by life's breath, soon possessed not.",
  "If all that lives must love or die,",
  "All shapes on earth, or sea, or sky,",
  "With one consent to Heaven cry",
  "That the glory far above",
  "All else in life is--",
  "",
  "ALL:",
  "Love! oh, Love!",
  "",
  "JUSTINA:",
  "Thou melancholy Thought which art",
  "So flattering and so sweet, to thee",
  "When did I give the liberty",
  "Thus to afflict my heart?",
  "What is the cause of this new Power",
  "Which doth my fevered being move,",
  "Momently raging more and more?",
  "What subtle Pain is kindled now",
  "Which from my heart doth overflow",
  "Into my senses?--",
  "",
  "ALL:",
  "Love! oh, Love!",
  "",
  "JUSTINA:",
  "'Tis that enamoured Nightingale",
  "Who gives me the reply;",
  "He ever tells the same soft tale",
  "Of passion and of constancy",
  "To his mate, who rapt and fond,",
  "Listening sits, a bough beyond.",
  "",
  "Be silent, Nightingale--no more",
  "Make me think, in hearing thee",
  "Thus tenderly thy love deplore,",
  "If a bird can feel his so,",
  "What a man would feel for me.",
  "And, voluptuous Vine, O thou",
  "Who seekest most when least pursuing,--",
  "To the trunk thou interlacest",
  "Art the verdure which embracest,",
  "And the weight which is its ruin,--",
  "No more, with green embraces, Vine,",
  "Make me think on what thou lovest,--",
  "For whilst thus thy boughs entwine",
  "I fear lest thou shouldst teach me, sophist,",
  "How arms might be entangled too.",
  "",
  "Light-enchanted Sunflower, thou",
  "Who gazest ever true and tender",
  "On the sun's revolving splendour!",
  "Follow not his faithless glance",
  "With thy faded countenance,",
  "Nor teach my beating heart to fear,",
  "If leaves can mourn without a tear,",
  "How eyes must weep! O Nightingale,",
  "Cease from thy enamoured tale,--",
  "Leafy Vine, unwreathe thy bower,",
  "Restless Sunflower, cease to move,--",
  "Or tell me all, what poisonous Power",
  "Ye use against me--",
  "",
  "ALL:",
  "Love! Love! Love!",
  "",
  "JUSTINA:",
  "It cannot be!--Whom have I ever loved?",
  "Trophies of my oblivion and disdain,",
  "Floro and Lelio did I not reject?",
  "And Cyprian?--",
  "[SHE BECOMES TROUBLED AT THE NAME OF CYPRIAN.]",
  "Did I not requite him",
  "With such severity, that he has fled",
  "Where none has ever heard of him again?--",
  "Alas! I now begin to fear that this",
  "May be the occasion whence desire grows bold,",
  "As if there were no danger. From the moment",
  "That I pronounced to my own listening heart,",
  "'Cyprian is absent!'--O me miserable!",
  "I know not what I feel!",
  "[MORE CALMLY.]",
  "It must be pity",
  "To think that such a man, whom all the world",
  "Admired, should be forgot by all the world,",
  "And I the cause.",
  "[SHE AGAIN BECOMES TROUBLED.]",
  "And yet if it were pity,",
  "Floro and Lelio might have equal share,",
  "For they are both imprisoned for my sake.",
  "[CALMLY.]",
  "Alas! what reasonings are these? it is",
  "Enough I pity him, and that, in vain,",
  "Without this ceremonious subtlety.",
  "And, woe is me! I know not where to find him now,",
  "Even should I seek him through this wide world.",
  "",
  "[ENTER DAEMON.]",
  "",
  "DAEMON:",
  "Follow, and I will lead thee where he is.",
  "",
  "JUSTINA:",
  "And who art thou, who hast found entrance hither,",
  "Into my chamber through the doors and locks?",
  "Art thou a monstrous shadow which my madness",
  "Has formed in the idle air?",
  "",
  "DAEMON:",
  "No. I am one",
  "Called by the Thought which tyrannizes thee",
  "From his eternal dwelling; who this day",
  "Is pledged to bear thee unto Cyprian.",
  "",
  "JUSTINA:",
  "So shall thy promise fail. This agony",
  "Of passion which afflicts my heart and soul",
  "May sweep imagination in its storm;",
  "The will is firm.",
  "",
  "DAEMON:",
  "Already half is done",
  "In the imagination of an act.",
  "The sin incurred, the pleasure then remains;",
  "Let not the will stop half-way on the road.",
  "",
  "JUSTINA:",
  "I will not be discouraged, nor despair,",
  "Although I thought it, and although 'tis true",
  "That thought is but a prelude to the deed:--",
  "Thought is not in my power, but action is:",
  "I will not move my foot to follow thee.",
  "",
  "DAEMON:",
  "But a far mightier wisdom than thine own",
  "Exerts itself within thee, with such power",
  "Compelling thee to that which it inclines",
  "That it shall force thy step; how wilt thou then",
  "Resist, Justina?",
  "",
  "JUSTINA:",
  "By my free-will.",
  "",
  "DAEMON:",
  "I",
  "Must force thy will.",
  "",
  "JUSTINA:",
  "It is invincible;",
  "It were not free if thou hadst power upon it.",
  "",
  "[HE DRAWS, BUT CANNOT MOVE HER.]",
  "",
  "DAEMON:",
  "Come, where a pleasure waits thee.",
  "",
  "JUSTINA:",
  "It were bought",
  "Too dear.",
  "",
  "DAEMON:",
  "'Twill soothe thy heart to softest peace.",
  "",
  "JUSTINA:",
  "'Tis dread captivity.",
  "",
  "DAEMON:",
  "'Tis joy, 'tis glory.",
  "",
  "JUSTINA:",
  "'Tis shame, 'tis torment, 'tis despair.",
  "",
  "DAEMON:",
  "But how",
  "Canst thou defend thyself from that or me,",
  "If my power drags thee onward?",
  "",
  "JUSTINA:",
  "My defence",
  "Consists in God.",
  "",
  "[HE VAINLY ENDEAVOURS TO FORCE HER, AND AT LAST RELEASES HER.]",
  "",
  "DAEMON:",
  "Woman, thou hast subdued me,",
  "Only by not owning thyself subdued.",
  "But since thou thus findest defence in God,",
  "I will assume a feigned form, and thus",
  "Make thee a victim of my baffled rage.",
  "For I will mask a spirit in thy form",
  "Who will betray thy name to infamy,",
  "And doubly shall I triumph in thy loss,",
  "First by dishonouring thee, and then by turning",
  "False pleasure to true ignominy.",
  "",
  "[EXIT.]",
  "",
  "JUSTINA: I",
  "Appeal to Heaven against thee; so that Heaven",
  "May scatter thy delusions, and the blot",
  "Upon my fame vanish in idle thought,",
  "Even as flame dies in the envious air,",
  "And as the floweret wanes at morning frost;",
  "And thou shouldst never--But, alas! to whom",
  "Do I still speak?--Did not a man but now",
  "Stand here before me?--No, I am alone,",
  "And yet I saw him. Is he gone so quickly?",
  "Or can the heated mind engender shapes",
  "From its own fear? Some terrible and strange",
  "Peril is near. Lisander! father! lord!",
  "Livia!--",
  "",
  "[ENTER LISANDER AND LIVIA.]",
  "",
  "LISANDER:",
  "Oh, my daughter! What?",
  "",
  "LIVIA:",
  "What!",
  "",
  "JUSTINA:",
  "Saw you",
  "A man go forth from my apartment now?--",
  "I scarce contain myself!",
  "",
  "LISANDER:",
  "A man here!",
  "",
  "JUSTINA:",
  "Have you not seen him?",
  "",
  "LIVIA:",
  "No, Lady.",
  "",
  "JUSTINA: I saw him.",
  "",
  "LISANDER: 'Tis impossible; the doors",
  "Which led to this apartment were all locked.",
  "",
  "LIVIA [ASIDE]:",
  "I daresay it was Moscon whom she saw,",
  "For he was locked up in my room.",
  "",
  "LISANDER:",
  "It must",
  "Have been some image of thy fantasy.",
  "Such melancholy as thou feedest is",
  "Skilful in forming such in the vain air",
  "Out of the motes and atoms of the day.",
  "",
  "LIVIA:",
  "My master's in the right.",
  "",
  "JUSTINA:",
  "Oh, would it were",
  "Delusion; but I fear some greater ill.",
  "I feel as if out of my bleeding bosom",
  "My heart was torn in fragments; ay,",
  "Some mortal spell is wrought against my frame;",
  "So potent was the charm that, had not God",
  "Shielded my humble innocence from wrong,",
  "I should have sought my sorrow and my shame",
  "With willing steps.--Livia, quick, bring my cloak,",
  "For I must seek refuge from these extremes",
  "Even in the temple of the highest God",
  "Where secretly the faithful worship.",
  "",
  "LIVIA:",
  "Here.",
  "",
  "JUSTINA [PUTTING ON HER CLOAK]:",
  "In this, as in a shroud of snow, may I",
  "Quench the consuming fire in which I burn,",
  "Wasting away!",
  "",
  "LISANDER:",
  "And I will go with thee.",
  "",
  "LIVIA:",
  "When I once see them safe out of the house",
  "I shall breathe freely.",
  "",
  "JUSTINA:",
  "So do I confide",
  "In thy just favour, Heaven!",
  "",
  "LISANDER:",
  "Let us go.",
  "",
  "JUSTINA:",
  "Thine is the cause, great God! turn for my sake,",
  "And for Thine own, mercifully to me!",
  ""
]