module.exports = [
  "SCENE 1.--PROLOGUE IN HEAVEN.",
  "",
  "THE LORD AND THE HOST OF HEAVEN.",
  "",
  "ENTER THREE ARCHANGELS.",
  "",
  "RAPHAEL:",
  "The sun makes music as of old",
  "Amid the rival spheres of Heaven,",
  "On its predestined circle rolled",
  "With thunder speed: the Angels even",
  "Draw strength from gazing on its glance,",
  "Though none its meaning fathom may:--",
  "The world's unwithered countenance",
  "Is bright as at Creation's day.",
  "",
  "GABRIEL:",
  "And swift and swift, with rapid lightness,",
  "The adorned Earth spins silently,",
  "Alternating Elysian brightness",
  "With deep and dreadful night; the sea",
  "Foams in broad billows from the deep",
  "Up to the rocks, and rocks and Ocean,",
  "Onward, with spheres which never sleep,",
  "Are hurried in eternal motion.",
  "",
  "MICHAEL:",
  "And tempests in contention roar",
  "From land to sea, from sea to land;",
  "And, raging, weave a chain of power,",
  "Which girds the earth, as with a band.--",
  "A flashing desolation there,",
  "Flames before the thunder's way;",
  "But Thy servants, Lord, revere",
  "The gentle changes of Thy day.",
  "",
  "CHORUS OF THE THREE:",
  "The Angels draw strength from Thy glance,",
  "Though no one comprehend Thee may;--",
  "Thy world's unwithered countenance",
  "Is bright as on Creation's day.",
  "",
  "GABRIEL:",
  "And swift, and inconceivably swift",
  "The adornment of earth winds itself round,",
  "And exchanges Paradise-clearness",
  "With deep dreadful night.",
  "The sea foams in broad waves",
  "From its deep bottom, up to the rocks,",
  "And rocks and sea are torn on together",
  "In the eternal swift course of the spheres.",
  "",
  "MICHAEL:",
  "And storms roar in emulation",
  "From sea to land, from land to sea,",
  "And make, raging, a chain",
  "Of deepest operation round about.",
  "There flames a flashing destruction",
  "Before the path of the thunderbolt.",
  "But Thy servants, Lord, revere",
  "The gentle alternations of Thy day.",
  "",
  "CHORUS:",
  "Thy countenance gives the Angels strength,",
  "Though none can comprehend Thee:",
  "And all Thy lofty works",
  "Are excellent as at the first day.",
  "",
  "[ENTER MEPHISTOPHELES.]",
  "",
  "MEPHISTOPHELES:",
  "As thou, O Lord, once more art kind enough",
  "To interest Thyself in our affairs,",
  "And ask, 'How goes it with you there below?'",
  "And as indulgently at other times",
  "Thou tookest not my visits in ill part,",
  "Thou seest me here once more among Thy household.",
  "Though I should scandalize this company,",
  "You will excuse me if I do not talk",
  "In the high style which they think fashionable;",
  "My pathos certainly would make You laugh too,",
  "Had You not long since given over laughing.",
  "Nothing know I to say of suns and worlds;",
  "I observe only how men plague themselves;--",
  "The little god o' the world keeps the same stamp,",
  "As wonderful as on creation's day:--",
  "A little better would he live, hadst Thou",
  "Not given him a glimpse of Heaven's light",
  "Which he calls reason, and employs it only",
  "To live more beastlily than any beast.",
  "With reverence to Your Lordship be it spoken,",
  "He's like one of those long-legged grasshoppers,",
  "Who flits and jumps about, and sings for ever",
  "The same old song i' the grass. There let him lie,",
  "Burying his nose in every heap of dung.",
  "",
  "THE LORD:",
  "Have you no more to say? Do you come here",
  "Always to scold, and cavil, and complain?",
  "Seems nothing ever right to you on earth?",
  "",
  "MEPHISTOPHELES:",
  "No, Lord! I find all there, as ever, bad at best.",
  "Even I am sorry for man's days of sorrow;",
  "I could myself almost give up the pleasure",
  "Of plaguing the poor things.",
  "",
  "THE LORD:",
  "Knowest thou Faust?",
  "",
  "MEPHISTOPHELES:",
  "The Doctor?",
  "",
  "THE LORD:",
  "Ay; My servant Faust.",
  "",
  "MEPHISTOPHELES:",
  "In truth",
  "He serves You in a fashion quite his own;",
  "And the fool's meat and drink are not of earth.",
  "His aspirations bear him on so far",
  "That he is half aware of his own folly,",
  "For he demands from Heaven its fairest star,",
  "And from the earth the highest joy it bears,",
  "Yet all things far, and all things near, are vain",
  "To calm the deep emotions of his breast.",
  "",
  "THE LORD:",
  "Though he now serves Me in a cloud of error,",
  "I will soon lead him forth to the clear day.",
  "When trees look green, full well the gardener knows",
  "That fruits and blooms will deck the coming year.",
  "",
  "MEPHISTOPHELES:",
  "What will You bet?--now am sure of winning--",
  "Only, observe You give me full permission",
  "To lead him softly on my path.",
  "",
  "THE LORD:",
  "As long",
  "As he shall live upon the earth, so long",
  "Is nothing unto thee forbidden--Man",
  "Must err till he has ceased to struggle.",
  "",
  "MEPHISTOPHELES:",
  "Thanks.",
  "And that is all I ask; for willingly",
  "I never make acquaintance with the dead.",
  "The full fresh cheeks of youth are food for me,",
  "And if a corpse knocks, I am not at home.",
  "For I am like a cat--I like to play",
  "A little with the mouse before I eat it.",
  "",
  "THE LORD:",
  "Well, well! it is permitted thee. Draw thou",
  "His spirit from its springs; as thou find'st power",
  "Seize him and lead him on thy downward path;",
  "And stand ashamed when failure teaches thee",
  "That a good man, even in his darkest longings,",
  "Is well aware of the right way.",
  "",
  "MEPHISTOPHELES:",
  "Well and good.",
  "I am not in much doubt about my bet,",
  "And if I lose, then 'tis Your turn to crow;",
  "Enjoy Your triumph then with a full breast.",
  "Ay; dust shall he devour, and that with pleasure,",
  "Like my old paramour, the famous Snake.",
  "",
  "THE LORD:",
  "Pray come here when it suits you; for I never",
  "Had much dislike for people of your sort.",
  "And, among all the Spirits who rebelled,",
  "The knave was ever the least tedious to Me.",
  "The active spirit of man soon sleeps, and soon",
  "He seeks unbroken quiet; therefore I",
  "Have given him the Devil for a companion,",
  "Who may provoke him to some sort of work,",
  "And must create forever.--But ye, pure",
  "Children of God, enjoy eternal beauty;--",
  "Let that which ever operates and lives",
  "Clasp you within the limits of its love;",
  "And seize with sweet and melancholy thoughts",
  "The floating phantoms of its loveliness.",
  "",
  "[HEAVEN CLOSES; THE ARCHANGELS EXEUNT.]",
  "",
  "MEPHISTOPHELES:",
  "From time to time I visit the old fellow,",
  "And I take care to keep on good terms with Him.",
  "Civil enough is the same God Almighty,",
  "To talk so freely with the Devil himself.",
  "",
  "SCENE 2.--MAY-DAY NIGHT.",
  "",
  "THE HARTZ MOUNTAIN, A DESOLATE COUNTRY.",
  "",
  "FAUST, MEPHISTOPHELES.",
  "",
  "MEPHISTOPHELES:",
  "Would you not like a broomstick? As for me",
  "I wish I had a good stout ram to ride;",
  "For we are still far from the appointed place.",
  "",
  "FAUST:",
  "This knotted staff is help enough for me,",
  "Whilst I feel fresh upon my legs. What good",
  "Is there in making short a pleasant way?",
  "To creep along the labyrinths of the vales,",
  "And climb those rocks, where ever-babbling springs,",
  "Precipitate themselves in waterfalls,",
  "Is the true sport that seasons such a path.",
  "Already Spring kindles the birchen spray,",
  "And the hoar pines already feel her breath:",
  "Shall she not work also within our limbs?",
  "",
  "MEPHISTOPHELES:",
  "Nothing of such an influence do I feel.",
  "My body is all wintry, and I wish",
  "The flowers upon our path were frost and snow.",
  "But see how melancholy rises now,",
  "Dimly uplifting her belated beam,",
  "The blank unwelcome round of the red moon,",
  "And gives so bad a light, that every step",
  "One stumbles 'gainst some crag. With your permission,",
  "I'll call on Ignis-fatuus to our aid:",
  "I see one yonder burning jollily.",
  "Halloo, my friend! may I request that you",
  "Would favour us with your bright company?",
  "Why should you blaze away there to no purpose?",
  "Pray be so good as light us up this way.",
  "",
  "IGNIS-FATUUS:",
  "With reverence be it spoken, I will try",
  "To overcome the lightness of my nature;",
  "Our course, you know, is generally zigzag.",
  "",
  "MEPHISTOPHELES:",
  "Ha, ha! your worship thinks you have to deal",
  "With men. Go straight on, in the Devil's name,",
  "Or I shall puff your flickering life out.",
  "",
  "IGNIS-FATUUS:",
  "Well,",
  "I see you are the master of the house;",
  "I will accommodate myself to you.",
  "Only consider that to-night this mountain",
  "Is all enchanted, and if Jack-a-lantern",
  "Shows you his way, though you should miss your own,",
  "You ought not to be too exact with him.",
  "",
  "FAUST, MEPHISTOPHELES, AND IGNIS-FATUUS, IN ALTERNATE CHORUS:",
  "The limits of the sphere of dream,",
  "The bounds of true and false, are past.",
  "Lead us on, thou wandering Gleam,",
  "Lead us onward, far and fast,",
  "To the wide, the desert waste.",
  "",
  "But see, how swift advance and shift",
  "Trees behind trees, row by row,--",
  "How, clift by clift, rocks bend and lift",
  "Their frowning foreheads as we go.",
  "The giant-snouted crags, ho! ho!",
  "How they snort, and how they blow!",
  "",
  "Through the mossy sods and stones,",
  "Stream and streamlet hurry down--",
  "A rushing throng! A sound of song",
  "Beneath the vault of Heaven is blown!",
  "Sweet notes of love, the speaking tones",
  "Of this bright day, sent down to say",
  "That Paradise on Earth is known,",
  "Resound around, beneath, above.",
  "All we hope and all we love",
  "Finds a voice in this blithe strain,",
  "Which wakens hill and wood and rill,",
  "And vibrates far o'er field and vale,",
  "And which Echo, like the tale",
  "Of old times, repeats again.",
  "",
  "To-whoo! to-whoo! near, nearer now",
  "The sound of song, the rushing throng!",
  "Are the screech, the lapwing, and the jay,",
  "All awake as if 'twere day?",
  "See, with long legs and belly wide,",
  "A salamander in the brake!",
  "Every root is like a snake,",
  "And along the loose hillside,",
  "With strange contortions through the night,",
  "Curls, to seize or to affright;",
  "And, animated, strong, and many,",
  "They dart forth polypus-antennae,",
  "To blister with their poison spume",
  "The wanderer. Through the dazzling gloom",
  "The many-coloured mice, that thread",
  "The dewy turf beneath our tread,",
  "In troops each other's motions cross,",
  "Through the heath and through the moss;",
  "And, in legions intertangled,",
  "The fire-flies flit, and swarm, and throng,",
  "Till all the mountain depths are spangled.",
  "",
  "Tell me, shall we go or stay?",
  "Shall we onward? Come along!",
  "Everything around is swept",
  "Forward, onward, far away!",
  "Trees and masses intercept",
  "The sight, and wisps on every side",
  "Are puffed up and multiplied.",
  "",
  "MEPHISTOPHELES:",
  "Now vigorously seize my skirt, and gain",
  "This pinnacle of isolated crag.",
  "One may observe with wonder from this point,",
  "How Mammon glows among the mountains.",
  "",
  "FAUST:",
  "Ay--",
  "And strangely through the solid depth below",
  "A melancholy light, like the red dawn,",
  "Shoots from the lowest gorge of the abyss",
  "Of mountains, lightning hitherward: there rise",
  "Pillars of smoke, here clouds float gently by;",
  "Here the light burns soft as the enkindled air,",
  "Or the illumined dust of golden flowers;",
  "And now it glides like tender colours spreading;",
  "And now bursts forth in fountains from the earth;",
  "And now it winds, one torrent of broad light,",
  "Through the far valley with a hundred veins;",
  "And now once more within that narrow corner",
  "Masses itself into intensest splendour.",
  "And near us, see, sparks spring out of the ground,",
  "Like golden sand scattered upon the darkness;",
  "The pinnacles of that black wall of mountains",
  "That hems us in are kindled.",
  "",
  "MEPHISTOPHELES:",
  "Rare: in faith!",
  "Does not Sir Mammon gloriously illuminate",
  "His palace for this festival?--it is",
  "A pleasure which you had not known before.",
  "I spy the boisterous guests already.",
  "",
  "FAUST:",
  "How",
  "The children of the wind rage in the air!",
  "With what fierce strokes they fall upon my neck!",
  "",
  "MEPHISTOPHELES:",
  "Cling tightly to the old ribs of the crag.",
  "Beware! for if with them thou warrest",
  "In their fierce flight towards the wilderness,",
  "Their breath will sweep thee into dust, and drag",
  "Thy body to a grave in the abyss.",
  "A cloud thickens the night.",
  "Hark! how the tempest crashes through the forest!",
  "The owls fly out in strange affright;",
  "The columns of the evergreen palaces",
  "Are split and shattered;",
  "The roots creak, and stretch, and groan;",
  "And ruinously overthrown,",
  "The trunks are crushed and shattered",
  "By the fierce blast's unconquerable stress.",
  "Over each other crack and crash they all",
  "In terrible and intertangled fall;",
  "And through the ruins of the shaken mountain",
  "The airs hiss and howl--",
  "It is not the voice of the fountain,",
  "Nor the wolf in his midnight prowl.",
  "Dost thou not hear?",
  "Strange accents are ringing",
  "Aloft, afar, anear?",
  "The witches are singing!",
  "The torrent of a raging wizard song",
  "Streams the whole mountain along.",
  "",
  "CHORUS OF WITCHES:",
  "The stubble is yellow, the corn is green,",
  "Now to the Brocken the witches go;",
  "The mighty multitude here may be seen",
  "Gathering, wizard and witch, below.",
  "Sir Urian is sitting aloft in the air;",
  "Hey over stock! and hey over stone!",
  "'Twixt witches and incubi, what shall be done?",
  "Tell it who dare! tell it who dare!",
  "",
  "A VOICE:",
  "Upon a sow-swine, whose farrows were nine,",
  "Old Baubo rideth alone.",
  "",
  "CHORUS:",
  "Honour her, to whom honour is due,",
  "Old mother Baubo, honour to you!",
  "An able sow, with old Baubo upon her,",
  "Is worthy of glory, and worthy of honour!",
  "The legion of witches is coming behind,",
  "Darkening the night, and outspeeding the wind--",
  "",
  "A VOICE:",
  "Which way comest thou?",
  "",
  "A VOICE:",
  "Over Ilsenstein;",
  "The owl was awake in the white moonshine;",
  "I saw her at rest in her downy nest,",
  "And she stared at me with her broad, bright eyne.",
  "",
  "VOICES:",
  "And you may now as well take your course on to Hell,",
  "Since you ride by so fast on the headlong blast.",
  "",
  "A VOICE:",
  "She dropped poison upon me as I passed.",
  "Here are the wounds--",
  "",
  "CHORUS OF WITCHES:",
  "Come away! come along!",
  "The way is wide, the way is long,",
  "But what is that for a Bedlam throng?",
  "Stick with the prong, and scratch with the broom.",
  "The child in the cradle lies strangled at home,",
  "And the mother is clapping her hands.--",
  "",
  "SEMICHORUS OF WIZARDS 1:",
  "We glide in",
  "Like snails when the women are all away;",
  "And from a house once given over to sin",
  "Woman has a thousand steps to stray.",
  "",
  "SEMICHORUS 2:",
  "A thousand steps must a woman take,",
  "Where a man but a single spring will make.",
  "",
  "VOICES ABOVE:",
  "Come with us, come with us, from Felsensee.",
  "",
  "VOICES BELOW:",
  "With what joy would we fly through the upper sky!",
  "We are washed, we are 'nointed, stark naked are we;",
  "But our toil and our pain are forever in vain.",
  "",
  "BOTH CHORUSES:",
  "The wind is still, the stars are fled,",
  "The melancholy moon is dead;",
  "The magic notes, like spark on spark,",
  "Drizzle, whistling through the dark. Come away!",
  "",
  "VOICES BELOW:",
  "Stay, Oh, stay!",
  "",
  "VOICES ABOVE:",
  "Out of the crannies of the rocks",
  "Who calls?",
  "",
  "VOICES BELOW:",
  "Oh, let me join your flocks!",
  "I, three hundred years have striven",
  "To catch your skirt and mount to Heaven,--",
  "And still in vain. Oh, might I be",
  "With company akin to me!",
  "",
  "BOTH CHORUSES:",
  "Some on a ram and some on a prong,",
  "On poles and on broomsticks we flutter along;",
  "Forlorn is the wight who can rise not to-night.",
  "",
  "A HALF-WITCH BELOW:",
  "I have been tripping this many an hour:",
  "Are the others already so far before?",
  "No quiet at home, and no peace abroad!",
  "And less methinks is found by the road.",
  "",
  "CHORUS OF WITCHES:",
  "Come onward, away! aroint thee, aroint!",
  "A witch to be strong must anoint--anoint--",
  "Then every trough will be boat enough;",
  "With a rag for a sail we can sweep through the sky,",
  "Who flies not to-night, when means he to fly?",
  "",
  "BOTH CHORUSES:",
  "We cling to the skirt, and we strike on the ground;",
  "Witch-legions thicken around and around;",
  "Wizard-swarms cover the heath all over.",
  "",
  "[THEY DESCEND.]",
  "",
  "MEPHISTOPHELES:",
  "What thronging, dashing, raging, rustling;",
  "What whispering, babbling, hissing, bustling;",
  "What glimmering, spurting, stinking, burning,",
  "As Heaven and Earth were overturning.",
  "There is a true witch element about us;",
  "Take hold on me, or we shall be divided:--",
  "Where are you?",
  "",
  "FAUST [FROM A DISTANCE]:",
  "Here!",
  "",
  "MEPHISTOPHELES:",
  "What!",
  "I must exert my authority in the house.",
  "Place for young Voland! pray make way, good people.",
  "Take hold on me, doctor, an with one step",
  "Let us escape from this unpleasant crowd:",
  "They are too mad for people of my sort.",
  "Just there shines a peculiar kind of light--",
  "Something attracts me in those bushes. Come",
  "This way: we shall slip down there in a minute.",
  "",
  "FAUST:",
  "Spirit of Contradiction! Well, lead on--",
  "'Twere a wise feat indeed to wander out",
  "Into the Brocken upon May-day night,",
  "And then to isolate oneself in scorn,",
  "Disgusted with the humours of the time.",
  "",
  "MEPHISTOPHELES:",
  "See yonder, round a many-coloured flame",
  "A merry club is huddled altogether:",
  "Even with such little people as sit there",
  "One would not be alone.",
  "",
  "FAUST:",
  "Would that I were",
  "Up yonder in the glow and whirling smoke,",
  "Where the blind million rush impetuously",
  "To meet the evil ones; there might I solve",
  "Many a riddle that torments me.",
  "",
  "MEPHISTOPHELES:",
  "Yet",
  "Many a riddle there is tied anew",
  "Inextricably. Let the great world rage!",
  "We will stay here safe in the quiet dwellings.",
  "'Tis an old custom. Men have ever built",
  "Their own small world in the great world of all.",
  "I see young witches naked there, and old ones",
  "Wisely attired with greater decency.",
  "Be guided now by me, and you shall buy",
  "A pound of pleasure with a dram of trouble.",
  "I hear them tune their instruments--one must",
  "Get used to this damned scraping. Come, I'll lead you",
  "Among them; and what there you do and see,",
  "As a fresh compact 'twixt us two shall be.",
  "How say you now? this space is wide enough--",
  "Look forth, you cannot see the end of it--",
  "An hundred bonfires burn in rows, and they",
  "Who throng around them seem innumerable:",
  "Dancing and drinking, jabbering, making love,",
  "And cooking, are at work. Now tell me, friend,",
  "What is there better in the world than this?",
  "",
  "FAUST:",
  "In introducing us, do you assume",
  "The character of Wizard or of Devil?",
  "",
  "MEPHISTOPHELES:",
  "In truth, I generally go about",
  "In strict incognito; and yet one likes",
  "To wear one's orders upon gala days.",
  "I have no ribbon at my knee; but here",
  "At home, the cloven foot is honourable.",
  "See you that snail there?--she comes creeping up,",
  "And with her feeling eyes hath smelt out something.",
  "I could not, if I would, mask myself here.",
  "Come now, we'll go about from fire to fire:",
  "I'll be the Pimp, and you shall be the Lover.",
  "[TO SOME OLD WOMEN, WHO ARE SITTING ROUND A HEAP OF GLIMMERING COALS.]",
  "Old gentlewomen, what do you do out here?",
  "You ought to be with the young rioters",
  "Right in the thickest of the revelry--",
  "But every one is best content at home.",
  "",
  "General.",
  "Who dare confide in right or a just claim?",
  "So much as I had done for them! and now--",
  "With women and the people 'tis the same,",
  "Youth will stand foremost ever,--age may go",
  "To the dark grave unhonoured.",
  "",
  "MINISTER:",
  "Nowadays",
  "People assert their rights: they go too far;",
  "But as for me, the good old times I praise;",
  "Then we were all in all--'twas something worth",
  "One's while to be in place and wear a star;",
  "That was indeed the golden age on earth.",
  "",
  "PARVENU:",
  "We too are active, and we did and do",
  "What we ought not, perhaps; and yet we now",
  "Will seize, whilst all things are whirled round and round,",
  "A spoke of Fortune's wheel, and keep our ground.",
  "",
  "AUTHOR:",
  "Who now can taste a treatise of deep sense",
  "And ponderous volume? 'tis impertinence",
  "To write what none will read, therefore will I",
  "To please the young and thoughtless people try.",
  "",
  "MEPHISTOPHELES [WHO AT ONCE APPEARS TO HAVE GROWN VERY OLD]:",
  "I",
  "find the people ripe for the last day,",
  "Since I last came up to the wizard mountain;",
  "And as my little cask runs turbid now,",
  "So is the world drained to the dregs.",
  "",
  "PEDLAR-WITCH:",
  "Look here,",
  "Gentlemen; do not hurry on so fast;",
  "And lose the chance of a good pennyworth.",
  "I have a pack full of the choicest wares",
  "Of every sort, and yet in all my bundle",
  "Is nothing like what may be found on earth;",
  "Nothing that in a moment will make rich",
  "Men and the world with fine malicious mischief--",
  "There is no dagger drunk with blood; no bowl",
  "From which consuming poison may be drained",
  "By innocent and healthy lips; no jewel,",
  "The price of an abandoned maiden's shame;",
  "No sword which cuts the bond it cannot loose,",
  "Or stabs the wearer's enemy in the back;",
  "No--",
  "",
  "MEPHISTOPHELES:",
  "Gossip, you know little of these times.",
  "What has been, has been; what is done, is past,",
  "They shape themselves into the innovations",
  "They breed, and innovation drags us with it.",
  "The torrent of the crowd sweeps over us:",
  "You think to impel, and are yourself impelled.",
  "",
  "FAUST:",
  "What is that yonder?",
  "",
  "MEPHISTOPHELES:",
  "Mark her well. It is",
  "Lilith.",
  "",
  "FAUST:",
  "Who?",
  "",
  "MEPHISTOPHELES:",
  "Lilith, the first wife of Adam.",
  "Beware of her fair hair, for she excels",
  "All women in the magic of her locks;",
  "And when she winds them round a young man's neck,",
  "She will not ever set him free again.",
  "",
  "FAUST:",
  "There sit a girl and an old woman--they",
  "Seem to be tired with pleasure and with play.",
  "",
  "MEPHISTOPHELES:",
  "There is no rest to-night for any one:",
  "When one dance ends another is begun;",
  "Come, let us to it. We shall have rare fun.",
  "",
  "[FAUST DANCES AND SINGS WITH A GIRL, AND",
  "MEPHISTOPHELES WITH AN OLD WOMAN.]",
  "",
  "FAUST:",
  "I had once a lovely dream",
  "In which I saw an apple-tree,",
  "Where two fair apples with their gleam",
  "To climb and taste attracted me.",
  "",
  "THE GIRL:",
  "She with apples you desired",
  "From Paradise came long ago:",
  "With you I feel that if required,",
  "Such still within my garden grow.",
  "",
  "...",
  "",
  "PROCTO-PHANTASMIST:",
  "What is this cursed multitude about?",
  "Have we not long since proved to demonstration",
  "That ghosts move not on ordinary feet?",
  "But these are dancing just like men and women.",
  "",
  "THE GIRL:",
  "What does he want then at our ball?",
  "",
  "FAUST:",
  "Oh! he",
  "Is far above us all in his conceit:",
  "Whilst we enjoy, he reasons of enjoyment;",
  "And any step which in our dance we tread,",
  "If it be left out of his reckoning,",
  "Is not to be considered as a step.",
  "There are few things that scandalize him not:",
  "And when you whirl round in the circle now,",
  "As he went round the wheel in his old mill,",
  "He says that you go wrong in all respects,",
  "Especially if you congratulate him",
  "Upon the strength of the resemblance.",
  "",
  "PROCTO-PHANTASMIST:",
  "Fly!",
  "Vanish! Unheard-of impudence! What, still there!",
  "In this enlightened age too, since you have been",
  "Proved not to exist!--But this infernal brood",
  "Will hear no reason and endure no rule.",
  "Are we so wise, and is the POND still haunted?",
  "How long have I been sweeping out this rubbish",
  "Of superstition, and the world will not",
  "Come clean with all my pains!--it is a case",
  "Unheard of!",
  "",
  "THE GIRL:",
  "Then leave off teasing us so.",
  "",
  "PROCTO-PHANTASMIST:",
  "I tell you, spirits, to your faces now,",
  "That I should not regret this despotism",
  "Of spirits, but that mine can wield it not.",
  "To-night I shall make poor work of it,",
  "Yet I will take a round with you, and hope",
  "Before my last step in the living dance",
  "To beat the poet and the devil together.",
  "",
  "MEPHISTOPHELES:",
  "At last he will sit down in some foul puddle;",
  "That is his way of solacing himself;",
  "Until some leech, diverted with his gravity,",
  "Cures him of spirits and the spirit together.",
  "[TO FAUST, WHO HAS SECEDED FROM THE DANCE.]",
  "Why do you let that fair girl pass from you,",
  "Who sung so sweetly to you in the dance?",
  "",
  "FAUST:",
  "A red mouse in the middle of her singing",
  "Sprung from her mouth.",
  "",
  "MEPHISTOPHELES:",
  "That was all right, my friend:",
  "Be it enough that the mouse was not gray.",
  "Do not disturb your hour of happiness",
  "With close consideration of such trifles.",
  "",
  "FAUST:",
  "Then saw I--",
  "",
  "MEPHISTOPHELES:",
  "What?",
  "",
  "FAUST:",
  "Seest thou not a pale,",
  "Fair girl, standing alone, far, far away?",
  "She drags herself now forward with slow steps,",
  "And seems as if she moved with shackled feet:",
  "I cannot overcome the thought that she",
  "Is like poor Margaret.",
  "",
  "MEPHISTOPHELES:",
  "Let it be--pass on--",
  "No good can come of it--it is not well",
  "To meet it--it is an enchanted phantom,",
  "A lifeless idol; with its numbing look,",
  "It freezes up the blood of man; and they",
  "Who meet its ghastly stare are turned to stone,",
  "Like those who saw Medusa.",
  "",
  "FAUST:",
  "Oh, too true!",
  "Her eyes are like the eyes of a fresh corpse",
  "Which no beloved hand has closed, alas!",
  "That is the breast which Margaret yielded to me--",
  "Those are the lovely limbs which I enjoyed!",
  "",
  "MEPHISTOPHELES:",
  "It is all magic, poor deluded fool!",
  "She looks to every one like his first love.",
  "",
  "FAUST:",
  "Oh, what delight! what woe! I cannot turn",
  "My looks from her sweet piteous countenance.",
  "How strangely does a single blood-red line,",
  "Not broader than the sharp edge of a knife,",
  "Adorn her lovely neck!",
  "",
  "MEPHISTOPHELES:",
  "Ay, she can carry",
  "Her head under her arm upon occasion;",
  "Perseus has cut it off for her. These pleasures",
  "End in delusion.--Gain this rising ground,",
  "It is as airy here as in a...",
  "And if I am not mightily deceived,",
  "I see a theatre.--What may this mean?",
  "",
  "ATTENDANT:",
  "Quite a new piece, the last of seven, for 'tis",
  "The custom now to represent that number.",
  "'Tis written by a Dilettante, and",
  "The actors who perform are Dilettanti;",
  "Excuse me, gentlemen; but I must vanish.",
  "I am a Dilettante curtain-lifter.",
  "",
  "JUVENILIA.",
  ""
]