module.exports = [
  "Inside this northern summer's fold",
  "The fields are full of naked gold,",
  "Broadcast from heaven on lands it loves;",
  "The green veiled air is full of doves;",
  "Soft leaves that sift the sunbeams let",
  "Light on the small warm grasses wet",
  "Fall in short broken kisses sweet,",
  "And break again like waves that beat",
  "Round the sun's feet.",
  "",
  "But I, for all this English mirth",
  "Of golden-shod and dancing days,",
  "And the old green-girt sweet-hearted earth,",
  "Desire what here no spells can raise.",
  "Far hence, with holier heavens above,",
  "The lovely city of my love",
  "Bathes deep in the sun-satiate air",
  "That flows round no fair thing more fair",
  "Her beauty bare.",
  "",
  "There the utter sky is holier, there",
  "More pure the intense white height of air,",
  "More clear men's eyes that mine would meet,",
  "And the sweet springs of things more sweet.",
  "There for this one warm note of doves",
  "A clamour of a thousand loves",
  "Storms the night's ear, the day's assails,",
  "From the tempestuous nightingales,",
  "And fills, and fails.",
  "",
  "O gracious city well-beloved,",
  "Italian, and a maiden crowned,",
  "Siena, my feet are no more moved",
  "Toward thy strange-shapen mountain-bound:",
  "But my heart in me turns and moves,",
  "O lady loveliest of my loves,",
  "Toward thee, to lie before thy feet",
  "And gaze from thy fair fountain-seat",
  "Up the sheer street;",
  "",
  "And the house midway hanging see",
  "That saw Saint Catherine bodily,",
  "Felt on its floors her sweet feet move,",
  "And the live light of fiery love",
  "Burn from her beautiful strange face,",
  "As in the sanguine sacred place",
  "Where in pure hands she took the head",
  "Severed, and with pure lips still red",
  "Kissed the lips dead.",
  "",
  "For years through, sweetest of the saints,",
  "In quiet without cease she wrought,",
  "Till cries of men and fierce complaints",
  "From outward moved her maiden thought;",
  "And prayers she heard and sighs toward France,",
  "\"God, send us back deliverance,",
  "Send back thy servant, lest we die!\"",
  "With an exceeding bitter cry",
  "They smote the sky.",
  "",
  "Then in her sacred saving hands",
  "She took the sorrows of the lands,",
  "With maiden palms she lifted up",
  "The sick time's blood-embittered cup,",
  "And in her virgin garment furled",
  "The faint limbs of a wounded world.",
  "Clothed with calm love and clear desire,",
  "She went forth in her soul's attire,",
  "A missive fire.",
  "",
  "Across the might of men that strove",
  "It shone, and over heads of kings;",
  "And molten in red flames of love",
  "Were swords and many monstrous things;",
  "And shields were lowered, and snapt were spears,",
  "And sweeter-tuned the clamorous years;",
  "And faith came back, and peace, that were",
  "Fled; for she bade, saying, \"Thou, God's heir,",
  "Hast thou no care?",
  "",
  "\"Lo, men lay waste thine heritage",
  "Still, and much heathen people rage",
  "Against thee, and devise vain things.",
  "What comfort in the face of kings,",
  "What counsel is there? Turn thine eyes",
  "And thine heart from them in like wise;",
  "Turn thee unto thine holy place",
  "To help us that of God for grace",
  "Require thy face.",
  "",
  "\"For who shall hear us if not thou",
  "In a strange land? what doest thou there?",
  "Thy sheep are spoiled, and the ploughers plough",
  "Upon us; why hast thou no care",
  "For all this, and beyond strange hills",
  "Liest unregardful what snow chills",
  "Thy foldless flock, or what rains beat?",
  "Lo, in thine ears, before thy feet,",
  "Thy lost sheep bleat.",
  "",
  "\"And strange men feed on faultless lives,",
  "And there is blood, and men put knives,",
  "Shepherd, unto the young lamb's throat;",
  "And one hath eaten, and one smote,",
  "And one had hunger and is fed",
  "Full of the flesh of these, and red",
  "With blood of these as who drinks wine",
  "And God knoweth, who hath sent thee a sign,",
  "If these were thine.\"",
  "",
  "But the Pope's heart within him burned,",
  "So that he rose up, seeing the sign,",
  "And came among them; but she turned",
  "Back to her daily way divine,",
  "And fed her faith with silent things,",
  "And lived her life with curbed white wings,",
  "And mixed herself with heaven and died:",
  "And now on the sheer city-side",
  "Smiles like a bride.",
  "",
  "You see her in the fresh clear gloom,",
  "Where walls shut out the flame and bloom",
  "Of full-breathed summer, and the roof",
  "Keeps the keen ardent air aloof",
  "And sweet weight of the violent sky:",
  "There bodily beheld on high,",
  "She seems as one hearing in tune",
  "Heaven within heaven, at heaven's full noon,",
  "In sacred swoon:",
  "",
  "A solemn swoon of sense that aches",
  "With imminent blind heat of heaven,",
  "While all the wide-eyed spirit wakes,",
  "Vigilant of the supreme Seven,",
  "Whose choral flames in God's sight move,",
  "Made unendurable with love,",
  "That without wind or blast of breath",
  "Compels all things through life and death",
  "Whither God saith.",
  "",
  "There on the dim side-chapel wall",
  "Thy mighty touch memorial,",
  "Razzi, raised up, for ages dead,",
  "And fixed for us her heavenly head:",
  "And, rent with plaited thorn and rod,",
  "Bared the live likeness of her God",
  "To men's eyes turning from strange lands,",
  "Where, pale from thine immortal hands,",
  "Christ wounded stands;",
  "",
  "And the blood blots his holy hair",
  "And white brows over hungering eyes",
  "That plead against us, and the fair",
  "Mute lips forlorn of words or sighs",
  "In the great torment that bends down",
  "His bruised head with the bloomless crown,",
  "White as the unfruitful thorn-flower,",
  "A God beheld in dreams that were",
  "Beheld of her.",
  "",
  "In vain on all these sins and years",
  "Falls the sad blood, fall the slow tears;",
  "In vain poured forth as watersprings,",
  "Priests, on your altars, and ye, kings,",
  "About your seats of sanguine gold;",
  "Still your God, spat upon and sold,",
  "Bleeds at your hands; but now is gone",
  "All his flock from him saving one;",
  "Judas alone.",
  "",
  "Surely your race it was that he,",
  "O men signed backward with his name,",
  "Beholding in Gethsemane",
  "Bled the red bitter sweat of shame,",
  "Knowing how the word of Christian should",
  "Mean to men evil and not good,",
  "Seem to men shameful for your sake,",
  "Whose lips, for all the prayers they make,",
  "Man's blood must slake.",
  "",
  "But blood nor tears ye love not, you",
  "That my love leads my longing to,",
  "Fair as the world's old faith of flowers,",
  "O golden goddesses of ours!",
  "From what Idalian rose-pleasance",
  "Hath Aphrodite bidden glance",
  "The lovelier lightnings of your feet?",
  "From what sweet Paphian sward or seat",
  "Led you more sweet?",
  "",
  "O white three sisters, three as one,",
  "With flowerlike arms for flowery bands",
  "Your linked limbs glitter like the sun,",
  "And time lies beaten at your hands.",
  "Time and wild years and wars and men",
  "Pass, and ye care not whence or when;",
  "With calm lips over sweet for scorn,",
  "Ye watch night pass, O children born",
  "Of the old-world morn.",
  "",
  "Ah, in this strange and shrineless place,",
  "What doth a goddess, what a Grace,",
  "Where no Greek worships her shrined limbs",
  "With wreaths and Cytherean hymns?",
  "Where no lute makes luxurious",
  "The adoring airs in Amathus,",
  "Till the maid, knowing her mother near,",
  "Sobs with love, aching with sweet fear?",
  "What do ye here?",
  "",
  "For the outer land is sad, and wears",
  "A raiment of a flaming fire;",
  "And the fierce fruitless mountain stairs",
  "Climb, yet seem wroth and loth to aspire,",
  "Climb, and break, and are broken down,",
  "And through their clefts and crests the town",
  "Looks west and sees the dead sun lie,",
  "In sanguine death that stains the sky",
  "With angry dye.",
  "",
  "And from the war-worn wastes without",
  "In twilight, in the time of doubt,",
  "One sound comes of one whisper, where",
  "Moved with low motions of slow air",
  "The great trees nigh the castle swing",
  "In the sad coloured evening;",
  "\"Ricorditi di me, che son",
  "La Pia\"--that small sweet word alone",
  "Is not yet gone.",
  "",
  "\"Ricorditi di me\"--the sound",
  "Sole out of deep dumb days remote",
  "Across the fiery and fatal ground",
  "Comes tender as a hurt bird's note",
  "To where, a ghost with empty hands,",
  "A woe-worn ghost, her palace stands",
  "In the mid city, where the strong",
  "Bells turn the sunset air to song,",
  "And the towers throng.",
  "",
  "With other face, with speech the same,",
  "A mightier maiden's likeness came",
  "Late among mourning men that slept,",
  "A sacred ghost that went and wept,",
  "White as the passion-wounded Lamb,",
  "Saying, \"Ah, remember me, that am",
  "Italia.\" (From deep sea to sea",
  "Earth heard, earth knew her, that this was she.)",
  "\"Ricorditi.",
  "",
  "\"Love made me of all things fairest thing,",
  "And Hate unmade me; this knows he",
  "Who with God's sacerdotal ring",
  "Enringed mine hand, espousing me.\"",
  "Yea, in thy myriad-mooded woe,",
  "Yea, Mother, hast thou not said so?",
  "Have not our hearts within us stirred,",
  "O thou most holiest, at thy word?",
  "Have we not heard?",
  "",
  "As this dead tragic land that she",
  "Found deadly, such was time to thee;",
  "Years passed thee withering in the red",
  "Maremma, years that deemed thee dead,",
  "Ages that sorrowed or that scorned;",
  "And all this while though all they mourned",
  "Thou sawest the end of things unclean,",
  "And the unborn that should see thee a queen.",
  "Have we not seen?",
  "",
  "The weary poet, thy sad son,",
  "Upon thy soil, under thy skies,",
  "Saw all Italian things save one -",
  "Italia; this thing missed his eyes;",
  "The old mother-might, the breast, the face,",
  "That reared, that lit the Roman race;",
  "This not Leopardi saw; but we,",
  "What is it, Mother, that we see,",
  "What if not thee?",
  "",
  "Look thou from Siena southward home,",
  "Where the priest's pall hangs rent on Rome,",
  "And through the red rent swaddling-bands",
  "Towards thine she strains her labouring hands.",
  "Look thou and listen, and let be",
  "All the dead quick, all the bond free;",
  "In the blind eyes let there be sight;",
  "In the eighteen centuries of the night",
  "Let there be light.",
  "",
  "Bow down the beauty of thine head,",
  "Sweet, and with lips of living breath",
  "Kiss thy sons sleeping and thy dead,",
  "That there be no more sleep or death.",
  "Give us thy light, thy might, thy love,",
  "Whom thy face seen afar above",
  "Drew to thy feet; and when, being free,",
  "Thou hast blest thy children born to thee,",
  "Bless also me.",
  "",
  "Me that when others played or slept",
  "Sat still under thy cross and wept;",
  "Me who so early and unaware",
  "Felt fall on bent bared brows and hair",
  "(Thin drops of the overflowing flood!)",
  "The bitter blessing of thy blood;",
  "The sacred shadow of thy pain,",
  "Thine, the true maiden-mother, slain",
  "And raised again.",
  "",
  "Me consecrated, if I might,",
  "To praise thee, or to love at least,",
  "O mother of all men's dear delight,",
  "Thou madest a choral-souled boy-priest,",
  "Before my lips had leave to sing,",
  "Or my hands hardly strength to cling",
  "About the intolerable tree",
  "Whereto they had nailed my heart and thee",
  "And said, \"Let be.\"",
  "",
  "For to thee too the high Fates gave",
  "Grace to be sacrificed and save,",
  "That being arisen, in the equal sun,",
  "God and the People should be one;",
  "By those red roads thy footprints trod,",
  "Man more divine, more human God,",
  "Saviour; that where no light was known",
  "But darkness, and a daytime flown,",
  "Light should be shown.",
  "",
  "Let there be light, O Italy!",
  "For our feet falter in the night.",
  "O lamp of living years to be,",
  "O light of God, let there be light!",
  "Fill with a love keener than flame",
  "Men sealed in spirit with thy name,",
  "The cities and the Roman skies,",
  "Where men with other than man's eyes",
  "Saw thy sun rise.",
  "",
  "For theirs thou wast and thine were they",
  "Whose names outshine thy very day;",
  "For they are thine and theirs thou art",
  "Whose blood beats living in man's heart,",
  "Remembering ages fled and dead",
  "Wherein for thy sake these men bled;",
  "They that saw Trebia, they that see",
  "Mentana, they in years to be",
  "That shall see thee.",
  "",
  "For thine are all of us, and ours",
  "Thou; till the seasons bring to birth",
  "A perfect people, and all the powers",
  "Be with them that bear fruit on earth;",
  "Till the inner heart of man be one",
  "With freedom, and the sovereign sun;",
  "And Time, in likeness of a guide,",
  "Lead the Republic as a bride",
  "Up to God's side.",
  ""
]