module.exports = [
  "Sorry I am, my God, sorry I am,",
  "That my offences course it in a ring.",
  "My thoughts are working like a busy flame,",
  "Until their cockatrice they hatch and bring:",
  "And when they once have perfected their draughts,",
  "My words take fire from my inflamed thoughts.",
  "",
  "My words take fire fro m my inflamed thoughts,",
  "Which spit it forth like the Sicilian hill.",
  "They vent their wares, and pass them with their faults,",
  "And by their breathing ventilate the ill.",
  "But words suffice not, where are lewd intentions:",
  "My hands do join to finish the inventions.",
  "",
  "My hands do join to finish the inventions:",
  "And so my sins ascend three stories high,",
  "As Babel grew, before there were dissentions.",
  "Let ill deeds loiter not: for they supply",
  "New thoughts of sinning:",
  "wherefore, to my shame,",
  "Sorry I am, my God, sorry I am.",
  ""
]