module.exports = [
  "Love is enough: cherish life that abideth,",
  "Lest ye die ere ye know him, and curse and misname him;",
  "For who knows in what ruin of all hope he hideth,",
  "On what wings of the terror of darkness he rideth?",
  "And what is the joy of man's life that ye blame him",
  "For his bliss grown a sword, and his rest grown a fire?",
  "",
  "Ye who tremble for death, or the death of desire,",
  "Pass about the cold winter-tide garden and ponder",
  "On the rose in his glory amidst of June's fire,",
  "On the languor of noontide that gathered the thunder,",
  "On the morn and its freshness, the eve and its wonder:",
  "Ye may make it no more--shall Spring come to awaken?",
  "",
  "Live on, for Love liveth, and earth shall be shaken",
  "By the wind of his wings on the triumphing morning,",
  "When the dead, and their deeds that die not shall awaken,",
  "And the world's tale shall sound in your trumpet of warning,",
  "And the sun smite the banner called Scorn of the Scorning,",
  "And dead pain ye shall trample, dead fruitless desire,",
  "As ye wend to pluck out the new world from the fire.",
  ""
]