module.exports = [
  "AS the Liberty lads o'er the sea",
  "Bought their freedom, and cheaply, with blood,",
  "      So we, boys, we",
  "  Will _die_ fighting, or _live_ free,",
  "And down with all kings but King Ludd!",
  "",
  "When the web that we weave is complete,",
  "And the shuttle exchanged for the sword,",
  "  We will fling the winding sheet",
  "  O'er the despot at our feet,",
  "And dye it deep in the gore he has poured.",
  "",
  "Though black as his heart its hue,",
  "Since his veins are corrupted to mud,",
  "        Yet this is the dew",
  "        Which the tree shall renew",
  "Of Liberty, planted by Ludd!",
  ""
]