module.exports = [
  "I was a Poet!",
  "But I did not know it,",
  "Neither did my Mother,",
  "Nor my Sister nor my Brother.",
  "The Rich were not aware of it;",
  "The Poor took no care of it.",
  "The Reverend Mr. Drewitt",
  "Never knew it.",
  "The High did not suspect it;",
  "The Low could not detect it.",
  "Aunt Sue",
  "Said it was obviously untrue.",
  "Uncle Ned",
  "Said I was off my head:",
  "(This from a Colonial",
  "Was really a good testimonial.)",
  "Still everybody seemed to think",
  "That genius owes a good deal to drink.",
  "So that is how",
  "I am not a poet now,",
  "And why",
  "My inspiration has run dry.",
  "It is no sort of use",
  "To cultivate the Muse",
  "If vulgar people",
  "Can't tell a village pump from a church steeple.",
  "I am merely apologizing",
  "For the lack of the surprising",
  "In what I write",
  "To-night.",
  "I am quite well-meaning,",
  "But a lot of things are always intervening",
  "Between",
  "What I mean",
  "And what it is said",
  "I had in my head.",
  "It is all very puzzling.",
  "Uncle Ned",
  "Says Poets need muzzling.",
  "He might",
  "Be right.",
  "Good-night!",
  ""
]