module.exports = [
  "Oh, for some honest lover's ghost,",
  "Some kind unbodied post",
  "Sent from the shades below!",
  "I strangely long to know",
  "Whether the noble chaplets wear",
  "Those that their mistress' scorn did bear",
  "Or those that were used kindly.",
  "",
  "For whatsoe'er they tell us here",
  "To make those sufferings dear,",
  "'Twill there, I fear, be found",
  "That to the being crowned",
  "T' have loved alone will not suffice,",
  "Unless we also have been wise",
  "And have our loves enjoyed.",
  "",
  "What posture can we think him in",
  "That, here unloved, again",
  "Departs, and 's thither gone",
  "Where each sits by his own?",
  "Or how can that Elysium be",
  "Where I my mistress still must see",
  "Circled in other's arms?",
  "",
  "For there the judges all are just,",
  "And Sophonisba must",
  "Be his whom she held dear,",
  "Not his who loved her here.",
  "The sweet Philoclea, since she died,",
  "Lies by her Pirocles his side,",
  "Not by Amphialus.",
  "",
  "Some bays, perchance, or myrtle bough",
  "For difference crowns the brow",
  "Of those kind souls that were",
  "The noble martyrs here;",
  "And if that be the only odds,",
  "(As who can tell?) ye kinder gods,",
  "Give me the woman here!",
  ""
]