module.exports = [
  "How swiftly through Heaven's wide expanse",
  "Bright day's resplendent colours fade!",
  "How sweetly does the moonbeam's glance",
  "With silver tint St. Irvyne's glade!",
  "",
  "No cloud along the spangled air,",
  "Is borne upon the evening breeze;",
  "How solemn is the scene! how fair",
  "The moonbeams rest upon the trees!",
  "",
  "Yon dark gray turret glimmers white,",
  "Upon it sits the mournful owl;",
  "Along the stillness of the night,",
  "Her melancholy shriekings roll.",
  "",
  "But not alone on Irvyne's tower,",
  "The silver moonbeam pours her ray;",
  "It gleams upon the ivied bower,",
  "It dances in the cascade's spray.",
  "",
  "'Ah! why do dark'ning shades conceal",
  "The hour, when man must cease to be?",
  "Why may not human minds unveil",
  "The dim mists of futurity?--",
  "",
  "'The keenness of the world hath torn",
  "The heart which opens to its blast;",
  "Despised, neglected, and forlorn,",
  "Sinks the wretch in death at last.'",
  ""
]