module.exports = [
  "Though the day of my Destiny's over,",
  "  And the star of my Fate hath declined,",
  "Thy soft heart refused to discover",
  "  The faults which so many could find;",
  "Though thy Soul with my grief was acquainted,",
  "  It shrunk not to share it with me,",
  "And the Love which my Spirit hath painted",
  "  It never hath found but in _Thee_.",
  "",
  "Then when Nature around me is smiling,",
  "  The last smile which answers to mine,",
  "I do not believe it beguiling,",
  "  Because it reminds me of thine;",
  "And when winds are at war with the ocean,",
  "  As the breasts I believed in with me,",
  "If their billows excite an emotion,",
  "  It is that they bear me from _Thee._",
  "",
  "Though the rock of my last Hope is shivered,",
  "  And its fragments are sunk in the wave,",
  "Though I feel that my soul is delivered",
  "  To Pain--it shall not be its slave.",
  "There is many a pang to pursue me:",
  "  They may crush, but they shall not contemn;",
  "They may torture, but shall not subdue me;",
  "  'Tis of _Thee_ that I think--not of them.",
  "",
  "Though human, thou didst not deceive me,",
  "  Though woman, thou didst not forsake,",
  "Though loved, thou forborest to grieve me,",
  "  Though slandered, thou never couldst shake;",
  "Though trusted, thou didst not disclaim me,",
  "  Though parted, it was not to fly,",
  "Though watchful, 'twas not to defame me,",
  "  Nor, mute, that the world might belie.",
  "",
  "Yet I blame not the World, nor despise it,",
  "  Nor the war of the many with one;",
  "If my Soul was not fitted to prize it,",
  "  'Twas folly not sooner to shun:",
  "And if dearly that error hath cost me,",
  "  And more than I once could foresee,",
  "I have found that, whatever it lost me,",
  "  It could not deprive me of _Thee_.",
  "",
  "From the wreck of the past, which hath perished,",
  "  Thus much I at least may recall,",
  "It hath taught me that what I most cherished",
  "  Deserved to be dearest of all:",
  "In the Desert a fountain is springing,",
  "  In the wide waste there still is a tree,",
  "And a bird in the solitude singing,",
  "  Which speaks to my spirit of _Thee_.",
  ""
]