module.exports = [
  "\"HERE POPE FIRST SUNG!\" O, hallow'd Tree !",
  "Such is the boast thy bark displays;",
  "Thy branches, like thy Patron's lays,",
  "Shall ever, ever, sacred be;",
  "Nor with'ring storm, nor woodman's stroke,",
  "Shall harm the POET'S favourite Oak.",
  "",
  "'Twas HERE, he woo'd his MUSE of fire,",
  "While Inspiration's wond'rous art,",
  "Sublimely stealing thro' his heart",
  "Did Fancy's proudest themes inspire:",
  "'Twas HERE he wisely learnt to smile",
  "At empty praise, and courtly guile.",
  "",
  "Retir'd from flatt'ring, specious arts.",
  "From fawning sycophants of state,",
  "From knaves, with ravag'd wealth elate,",
  "And little SLAVES with TYRANT Hearts;",
  "In conscious freedom nobly proud,",
  "He scorn'd the envious, grov'ling crowd.",
  "",
  "Tho' splendid DOMES around them rise,",
  "And pompous TITLES lull to rest",
  "Each strugg'ling Virtue in the breast,",
  "'Till POW'R the place of WORTH supplies;",
  "The wretched herd can never know",
  "The sober joys these haunts bestow.",
  "",
  "Does the fond MUSE delight to dwell,",
  "Where freezing Penance spreads its shade ?",
  "When scarce the Sun's warm beams pervade",
  "The hoary HERMIT'S dreary cell?",
  "Ah! no­THERE, Superstition blind,",
  "With torpid languor chills the mind.",
  "",
  "Or, does she seek Life's busy scene,",
  "Ah ! no, the sordid, mean, and proud,",
  "The little, trifling, flutt'ring crowd,",
  "Can never taste her bliss serene;",
  "She flies from Fashion's tinsel toys,",
  "Nor courts her smile, nor shares her joys.",
  "",
  "Nor can the dull pedantic mind,",
  "E'er boast her bright creative fires;",
  "Above constraint her wing aspires,",
  "Nor rigid spells her flight can bind;",
  "The narrow track of musty schools,",
  "She leaves to plodding VAPID FOOLS.",
  "",
  "To scenes like THESE she bends her way,",
  "HERE the best feelings of the soul",
  "Nor interest taints, nor threats controul,",
  "Nor vice allures, nor snares betray;",
  "HERE from each trivial hope remov'd,",
  "Our BARD first sought the MUSE he lov'd.",
  "",
  "Still shall thy pensive gloom diffuse,",
  "The verse sublime, the dulcet song;",
  "While round the POET'S seat shall throng,",
  "Each rapture sacred to the MUSE;",
  "Still shall thy verdant branches be",
  "The bow'r of wond'rous minstrelsy.",
  "",
  "When glow-worms light their little fires,",
  "The am'rous SWAIN and timid MAID",
  "Shall sit and talk beneath thy shade,",
  "AS EVE'S last rosy tint expires;",
  "While on thy boughs the plaintive DOVE,",
  "Shall learn from them the tale of LOVE.",
  "",
  "When round the quiv'ring moon-beams play,",
  "And FAIRIES form the grassy ring,",
  "'Till the shrill LARK unfurls his wing,",
  "And soars to greet the blushing day;",
  "The NIGHTINGALE shall pour to THEE,",
  "Her Song of Love-lorn Melody.",
  "",
  "When, thro' the forest dark and drear,",
  "Full oft, as ancient stories say,",
  "Old HERNE THE HUNTER i loves to stray,",
  "While village damsels quake with fear;",
  "Nor sprite or spectre, shall invade",
  "The still repose that marks THY shade.",
  "",
  "BLEST OAK! thy mossy trunk shall be",
  "As lasting as the LAUREL'S bloom",
  "That deck's immortal VIRGIL'S tomb,",
  "And fam'd as SHAKSPERE'S hallow'd Tree;",
  "For every grateful MUSE shall twine",
  "A votive Wreath to deck THY SHRINE.",
  ""
]