module.exports = [
  "Tis done--and shivering in the gale",
  "The bark unfurls her snowy sail;",
  "And whistling o'er the bending mast,",
  "Loud sings on high the fresh'ning blast;",
  "And I must from this land be gone,",
  "Because I cannot love but one.",
  "",
  "But could I be what I have been,",
  "And could I see what I have seen--",
  "Could I repose upon the breast",
  "Which once my warmest wishes blest--",
  "I should not seek another zone,",
  "Because I cannot love but one.",
  "",
  "'Tis long since I beheld that eye",
  "Which gave me bliss or misery;",
  "And I have striven, but in vain,",
  "Never to think of it again:",
  "For though I fly from Albion,",
  "I still can only love but one.",
  "",
  "As some lone bird, without a mate,",
  "My weary heart is desolate;",
  "I look around, and cannot trace",
  "One friendly smile or welcome face,",
  "And ev'n in crowds am still alone,",
  "Because I cannot love but one.",
  "",
  "And I will cross the whitening foam,",
  "And I will seek a foreign home;",
  "Till I forget a false fair face,",
  "I ne'er shall find a resting-place;",
  "My own dark thoughts I cannot shun,",
  "But ever love, and love but one.",
  "",
  "The poorest, veriest wretch on earth",
  "Still finds some hospitable hearth,",
  "Where Friendship's or Love's softer glow",
  "May smile in joy or soothe in woe;",
  "But friend or leman I have none,",
  "Because I cannot love but one.",
  "",
  "I go--but wheresoe'er I flee",
  "There's not an eye will weep for me;",
  "There's not a kind congenial heart,",
  "Where I can claim the meanest part;",
  "Nor thou, who hast my hopes undone,",
  "Wilt sigh, although I love but one.",
  "",
  "To think of every early scene,",
  "Of what we are, and what we've been,",
  "Would whelm some softer hearts with woe--",
  "But mine, alas! has stood the blow;",
  "Yet still beats on as it begun,",
  "And never truly loves but one.",
  "",
  "And who that dear lov'd one may be,",
  "Is not for vulgar eyes to see;",
  "And why that early love was cross'd,",
  "Thou know'st the best, I feel the most;",
  "But few that dwell beneath the sun",
  "Have loved so long, and loved but one.",
  "",
  "I've tried another's fetters too,",
  "With charms perchance as fair to view;",
  "And I would fain have loved as well,",
  "But some unconquerable spell",
  "Forbade my bleeding breast to own",
  "A kindred care for aught but one.",
  "",
  "'Twould soothe to take one lingering view,",
  "And bless thee in my last adieu;",
  "Yet wish I not those eyes to weep",
  "For him that wanders o'er the deep;",
  "His home, his hope, his youth are gone,",
  "Yet still he loves, and loves but one.",
  "",
  "'To----on Leaving England.'",
  "",
  "'The land recedes his Bark is gone,",
  "Yet still he loves and laves but one.'",
  ""
]