module.exports = [
  "THE sun blazed while the thunder yet",
  "Added a boom:",
  "A wagtail flickered bright over",
  "The mill-pond's gloom:",
  "",
  "Less than the cooing in the alder",
  "Isles of the pool",
  "Sounded the thunder through that plunge",
  "Of waters cool.",
  "",
  "Scared starlings on the aspen tip",
  "Past the black mill",
  "Outchattered the stream and the next roar",
  "Far on the hill.",
  "",
  "As my feet dangling teased the foam",
  "That slid below",
  "A girl came out. \"Take care!\" she said--",
  "Ages ago.",
  "",
  "She startled me, standing quite close",
  "Dressed all in white:",
  "Ages ago I was angry till",
  "She passed from sight.",
  "",
  "Then the storm burst, and as I crouched",
  "To shelter, how",
  "Beautiful and kind, too, she seemed,",
  "As she does now!",
  ""
]