module.exports = [
  "1.1 Lo now! four other acts upon the stage,",
  "1.2 Childhood, and Youth, the Manly, and Old-age.",
  "1.3 The first: son unto Phlegm, grand-child to water,",
  "1.4 Unstable, supple, moist, and cold's his Nature.",
  "1.5 The second: frolic claims his pedigree;",
  "1.6 From blood and air, for hot and moist is he.",
  "1.7 The third of fire and choler is compos'd,",
  "1.8 Vindicative, and quarrelsome dispos'd.",
  "1.9 The last, of earth and heavy melancholy,",
  "1.10 Solid, hating all lightness, and all folly.",
  "1.11 Childhood was cloth'd in white, and given to show,",
  "1.12 His spring was intermixed with some snow.",
  "1.13 Upon his head a Garland Nature set:",
  "1.14 Of Daisy, Primrose, and the Violet.",
  "1.15 Such cold mean flowers (as these) blossom betime,",
  "1.16 Before the Sun hath throughly warm'd the clime.",
  "1.17 His hobby striding, did not ride, but run,",
  "1.18 And in his hand an hour-glass new begun,",
  "1.19 In dangers every moment of a fall,",
  "1.20 And when 'tis broke, then ends his life and all.",
  "1.21 But if he held till it have run its last,",
  "1.22 Then may he live till threescore years or past.",
  "1.23 Next, youth came up in gorgeous attire",
  "1.24 (As that fond age, doth most of all desire),",
  "1.25 His Suit of Crimson, and his Scarf of Green.",
  "1.26 In's countenance, his pride quickly was seen.",
  "1.27 Garland of Roses, Pinks, and Gillyflowers",
  "1.28 Seemed to grow on's head (bedew'd with showers).",
  "1.29 His face as fresh, as is Aurora fair,",
  "1.30 When blushing first, she 'gins to red the Air.",
  "1.31 No wooden horse, but one of metal try'd:",
  "1.32 He seems to fly, or swim, and not to ride.",
  "1.33 Then prancing on the Stage, about he wheels;",
  "1.34 But as he went, death waited at his heels.",
  "1.35 The next came up, in a more graver sort,",
  "1.36 As one that cared for a good report.",
  "1.37 His Sword by's side, and choler in his eyes,",
  "1.38 But neither us'd (as yet) for he was wise,",
  "1.39 Of Autumn fruits a basket on his arm,",
  "1.40 His golden rod in's purse, which was his charm.",
  "1.41 And last of all, to act upon this Stage,",
  "1.42 Leaning upon his staff, comes up old age.",
  "1.43 Under his arm a Sheaf of wheat he bore,",
  "1.44 A Harvest of the best: what needs he more?",
  "1.45 In's other hand a glass, ev'n almost run,",
  "1.46 This writ about: This out, then I am done.",
  "1.47 His hoary hairs and grave aspect made way,",
  "1.48 And all gave ear to what he had to say.",
  "1.49 These being met, each in his equipage",
  "1.50 Intend to speak, according to their age,",
  "1.51 But wise Old-age did with all gravity",
  "1.52 To childish childhood give precedency,",
  "1.53 And to the rest, his reason mildly told:",
  "1.54 That he was young, before he grew so old.",
  "1.55 To do as he, the rest full soon assents,",
  "1.56 Their method was that of the Elements,",
  "1.57 That each should tell what of himself he knew,",
  "1.58 Both good and bad, but yet no more then's true.",
  "1.59 With heed now stood, three ages of frail man,",
  "1.60 To hear the child, who crying, thus began.",
  "",
  "Childhood.",
  "",
  "2.1 Ah me! conceiv'd in sin, and born in sorrow,",
  "2.2 A nothing, here to day, but gone to morrow,",
  "2.3 Whose mean beginning, blushing can't reveal,",
  "2.4 But night and darkness must with shame conceal.",
  "2.5 My mother's breeding sickness, I will spare,",
  "2.6 Her nine months' weary burden not declare.",
  "2.7 To shew her bearing pangs, I should do wrong,",
  "2.8 To tell that pain, which can't be told by tongue.",
  "2.9 With tears into this world I did arrive;",
  "2.10 My mother still did waste, as I did thrive,",
  "2.11 Who yet with love and all alacity,",
  "2.12 Spending was willing to be spent for me.",
  "2.13 With wayward cries, I did disturb her rest,",
  "2.14 Who sought still to appease me with her breast;",
  "2.15 With weary arms, she danc'd, and By, By, sung,",
  "2.16 When wretched I (ungrate) had done the wrong.",
  "2.17 When Infancy was past, my Childishness",
  "2.18 Did act all folly that it could express.",
  "2.19 My silliness did only take delight,",
  "2.20 In that which riper age did scorn and slight,",
  "2.21 In Rattles, Bables, and such toyish stuff.",
  "2.22 My then ambitious thoughts were low enough.",
  "2.23 My high-born soul so straitly was confin'd",
  "2.24 That its own worth it did not know nor mind.",
  "2.25 This little house of flesh did spacious count,",
  "2.26 Through ignorance, all troubles did surmount,",
  "2.27 Yet this advantage had mine ignorance,",
  "2.28 Freedom from Envy and from Arrogance.",
  "2.29 How to be rich, or great, I did not cark,",
  "2.30 A Baron or a Duke ne'r made my mark,",
  "2.31 Nor studious was, Kings favours how to buy,",
  "2.32 With costly presents, or base flattery;",
  "2.33 No office coveted, wherein I might",
  "2.34 Make strong my self and turn aside weak right.",
  "2.35 No malice bare to this or that great Peer,",
  "2.36 Nor unto buzzing whisperers gave ear.",
  "2.37 I gave no hand, nor vote, for death, of life.",
  "2.38 I'd nought to do, 'twixt Prince, and peoples' strife.",
  "2.39 No Statist I: nor Marti'list i' th' field.",
  "2.40 Where e're I went, mine innocence was shield.",
  "2.41 My quarrels, not for Diadems, did rise,",
  "2.42 But for an Apple, Plumb, or some such prize.",
  "2.43 My strokes did cause no death, nor wounds, nor scars.",
  "2.44 My little wrath did cease soon as my wars.",
  "2.45 My duel was no challenge, nor did seek.",
  "2.46 My foe should weltering, with his bowels reek.",
  "2.47 I had no Suits at law, neighbours to vex,",
  "2.48 Nor evidence for land did me perplex.",
  "2.49 I fear'd no storms, nor all the winds that blows.",
  "2.50 I had no ships at Sea, no fraughts to loose.",
  "2.51 I fear'd no drought, nor wet; I had no crop,",
  "2.52 Nor yet on future things did place my hope.",
  "2.53 This was mine innocence, but oh the seeds",
  "2.54 Lay raked up of all the cursed weeds,",
  "2.55 Which sprouted forth in my insuing age,",
  "2.56 As he can tell, that next comes on the stage.",
  "2.57 But yet me let me relate, before I go,",
  "2.58 The sins and dangers I am subject to:",
  "2.59 From birth stained, with Adam's sinful fact,",
  "2.60 From thence I 'gan to sin, as soon as act;",
  "2.61 A perverse will, a love to what's forbid;",
  "2.62 A serpent's sting in pleasing face lay hid;",
  "2.63 A lying tongue as soon as it could speak",
  "2.64 And fifth Commandment do daily break;",
  "2.65 Oft stubborn, peevish, sullen, pout, and cry;",
  "2.66 Then nought can please, and yet I know not why.",
  "2.67 As many was my sins, so dangers too,",
  "2.68 For sin brings sorrow, sickness, death, and woe,",
  "2.69 And though I miss the tossings of the mind,",
  "2.70 Yet griefs in my frail flesh I still do find.",
  "2.71 What gripes of wind, mine infancy did pain?",
  "2.72 What tortures I, in breeding teeth sustain?",
  "2.73 What crudities my cold stomach hath bred?",
  "2.74 Whence vomits, worms, and flux have issued?",
  "2.75 What breaches, knocks, and falls I daily have?",
  "2.76 And some perhaps, I carry to my grave.",
  "2.77 Sometimes in fire, sometimes in water fall:",
  "2.78 Strangely preserv'd, yet mind it not at all.",
  "2.79 At home, abroad, my danger's manifold",
  "2.80 That wonder 'tis, my glass till now doth hold.",
  "2.81 I've done: unto my elders I give way,",
  "2.82 For 'tis but little that a child can say.",
  "",
  "Youth.",
  "",
  "",
  "3.1 My goodly clothing and beauteous skin",
  "3.2 Declare some greater riches are within,",
  "3.3 But what is best I'll first present to view,",
  "3.4 And then the worst, in a more ugly hue,",
  "3.5 For thus to do we on this Stage assemble,",
  "3.6 Then let not him, which hath most craft dissemble.",
  "3.7 Mine education, and my learning's such,",
  "3.8 As might my self, and others, profit much:",
  "3.9 With nurture trained up in virtue's Schools;",
  "3.10 Of Science, Arts, and Tongues, I know the rules;",
  "3.11 The manners of the Court, I likewise know,",
  "3.12 Nor ignorant what they in Country do.",
  "3.13 The brave attempts of valiant Knights I prize",
  "3.14 That dare climb Battlements, rear'd to the skies.",
  "3.15 The snorting Horse, the Trumpet, Drum I like,",
  "3.16 The glist'ring Sword, and well advanced Pike.",
  "3.17 I cannot lie in trench before a Town,",
  "3.18 Nor wait til good advice our hopes do crown.",
  "3.19 I scorn the heavy Corslet, Musket-proof;",
  "3.20 I fly to catch the Bullet that's aloof.",
  "3.21 Though thus in field, at home, to all most kind,",
  "3.22 So affable that I do suit each mind,",
  "3.23 I can insinuate into the breast",
  "3.24 And by my mirth can raise the heart deprest.",
  "3.25 Sweet Music rapteth my harmonious Soul,",
  "3.26 And elevates my thoughts above the Pole.",
  "3.27 My wit, my bounty, and my courtesy",
  "3.28 Makes all to place their future hopes on me.",
  "3.29 This is my best, but youth (is known) alas,",
  "3.30 To be as wild as is the snuffing Ass,",
  "3.31 As vain as froth, as vanity can be,",
  "3.32 That who would see vain man may look on me:",
  "3.33 My gifts abus'd, my education lost,",
  "3.34 My woful Parents' longing hopes all crost;",
  "3.35 My wit evaporates in merriment;",
  "3.36 My valour in some beastly quarrel's spent;",
  "3.37 Martial deeds I love not, 'cause they're virtuous,",
  "3.38 But doing so, might seem magnanimous.",
  "3.39 My Lust doth hurry me to all that's ill,",
  "3.40 I know no Law, nor reason, but my will;",
  "3.41 Sometimes lay wait to take a wealthy purse",
  "3.42 Or stab the man in's own defence, that's worse.",
  "3.43 Sometimes I cheat (unkind) a female Heir",
  "3.44 Of all at once, who not so wise, as fair,",
  "3.45 Trusteth my loving looks and glozing tongue",
  "3.46 Until her friends, treasure, and honour's gone.",
  "3.47 Sometimes I sit carousing others' health",
  "3.48 Until mine own be gone, my wit, and wealth.",
  "3.49 From pipe to pot, from pot to words and blows,",
  "3.50 For he that loveth Wine wanteth no woes.",
  "3.51 Days, nights, with Ruffins, Roarers, Fiddlers spend,",
  "3.52 To all obscenity my ears I bend,",
  "3.53 All counsel hate which tends to make me wise,",
  "3.54 And dearest friends count for mine enemies.",
  "3.55 If any care I take, 'tis to be fine,",
  "3.56 For sure my suit more than my virtues shine.",
  "3.57 If any time from company I spare,",
  "3.58 'Tis spent in curling, frisling up my hair,",
  "3.59 Some young Adonais I do strive to be.",
  "3.60 Sardana Pallas now survives in me.",
  "3.61 Cards, Dice, and Oaths, concomitant, I love;",
  "3.62 To Masques, to Plays, to Taverns still I move;",
  "3.63 And in a word, if what I am you'd hear,",
  "3.64 Seek out a British, bruitish Cavalier.",
  "3.65 Such wretch, such monster am I; but yet more",
  "3.66 I want a heart all this for to deplore.",
  "3.67 Thus, thus alas! I have mispent my time,",
  "3.68 My youth, my best, my strength, my bud, and prime,",
  "3.69 Remembring not the dreadful day of Doom,",
  "3.70 Nor yet the heavy reckoning for to come,",
  "3.71 Though dangers do attend me every hour",
  "3.72 And ghastly death oft threats me with her power:",
  "3.73 Sometimes by wounds in idle combats taken,",
  "3.74 Sometimes by Agues all my body shaken;",
  "3.75 Sometimes by Fevers, all my moisture drinking,",
  "3.76 My heart lies frying, and my eyes are sinking.",
  "3.77 Sometimes the Cough, Stitch, painful Pleurisy,",
  "3.78 With sad affrights of death, do menace me.",
  "3.79 Sometimes the loathsome Pox my face be-mars",
  "3.80 With ugly marks of his eternal scars.",
  "3.81 Sometimes the Frenzy strangely mads my Brain",
  "3.82 That oft for it in Bedlam I remain.",
  "3.83 Too many's my Diseases to recite,",
  "3.84 That wonder 'tis I yet behold the light,",
  "3.85 That yet my bed in darkness is not made,",
  "3.86 And I in black oblivion's den long laid.",
  "3.87 Of Marrow full my bones, of Milk my breasts,",
  "3.88 Ceas'd by the gripes of Serjeant Death's Arrests:",
  "3.89 Thus I have said, and what I've said you see,",
  "3.90 Childhood and youth is vain, yea vanity.",
  "",
  "Middle Age.",
  "",
  "",
  "4.1 Childhood and youth forgot, sometimes I've seen,",
  "4.2 And now am grown more staid that have been green,",
  "4.3 What they have done, the same was done by me:",
  "4.4 As was their praise, or shame, so mine must be.",
  "4.5 Now age is more, more good ye do expect;",
  "4.6 But more my age, the more is my defect.",
  "4.7 But what's of worth, your eyes shall first behold,",
  "4.8 And then a world of dross among my gold.",
  "4.9 When my Wild Oats were sown, and ripe, and mown,",
  "4.10 I then receiv'd a harvest of mine own.",
  "4.11 My reason, then bad judge, how little hope",
  "4.12 Such empty seed should yield a better crop.",
  "4.13 I then with both hands graspt the world together,",
  "4.14 Thus out of one extreme into another,",
  "4.15 But yet laid hold on virtue seemingly:",
  "4.16 Who climbs without hold, climbs dangerously.",
  "4.17 Be my condition mean, I then take pains",
  "4.18 My family to keep, but not for gains.",
  "4.19 If rich, I'm urged then to gather more",
  "4.20 To bear me out i' th' world and feed the poor;",
  "4.21 If a father, then for children must provide,",
  "4.22 But if none, then for kindred near ally'd;",
  "4.23 If Noble, then mine honour to maintain;",
  "4.24 If not, yet wealth, Nobility can gain.",
  "4.25 For time, for place, likewise for each relation,",
  "4.26 I wanted not my ready allegation.",
  "4.27 Yet all my powers for self-ends are not spent,",
  "4.28 For hundreds bless me for my bounty sent,",
  "4.29 Whose loins I've cloth'd, and bellies I have fed,",
  "4.30 With mine own fleece, and with my household bread.",
  "4.31 Yea, justice I have done, was I in place,",
  "4.32 To cheer the good and wicked to deface.",
  "4.33 The proud I crush'd, th'oppressed I set free,",
  "4.34 The liars curb'd but nourisht verity.",
  "4.35 Was I a pastor, I my flock did feed",
  "4.36 And gently lead the lambs, as they had need.",
  "4.37 A Captain I, with skill I train'd my band",
  "4.38 And shew'd them how in face of foes to stand.",
  "4.39 If a Soldier, with speed I did obey",
  "4.40 As readily as could my Leader say.",
  "4.41 Was I a laborer, I wrought all day",
  "4.42 As cheerfully as ere I took my pay.",
  "4.43 Thus hath mine age (in all) sometimes done well;",
  "4.44 Sometimes mine age (in all) been worse than hell.",
  "4.45 In meanness, greatness, riches, poverty",
  "4.46 Did toil, did broil; oppress'd, did steal and lie.",
  "4.47 Was I as poor as poverty could be,",
  "4.48 Then baseness was companion unto me.",
  "4.49 Such scum as Hedges and High-ways do yield,",
  "4.50 As neither sow, nor reap, nor plant, nor build.",
  "4.51 If to Agriculture I was ordain'd,",
  "4.52 Great labours, sorrows, crosses I sustain'd.",
  "4.53 The early Cock did summon, but in vain,",
  "4.54 My wakeful thoughts up to my painful gain.",
  "4.55 For restless day and night, I'm robb'd of sleep",
  "4.56 By cankered care, who sentinel doth keep.",
  "4.57 My weary breast rest from his toil can find,",
  "4.58 But if I rest, the more distrest my mind.",
  "4.59 If happiness my sordidness hath found,",
  "4.60 'Twas in the crop of my manured ground:",
  "4.61 My fatted Ox, and my exuberous Cow,",
  "4.62 My fleeced Ewe, and ever farrowing Sow.",
  "4.63 To greater things I never did aspire,",
  "4.64 My dunghill thoughts or hopes could reach no higher.",
  "4.65 If to be rich, or great, it was my fate.",
  "4.66 How was I broil'd with envy, and with hate?",
  "4.67 Greater than was the great'st was my desire,",
  "4.68 And greater still, did set my heart on fire.",
  "4.69 If honour was the point to which I steer'd,",
  "4.70 To run my hull upon disgrace I fear'd,",
  "4.71 But by ambitious sails I was so carried",
  "4.72 That over flats, and sands, and rocks I hurried,",
  "4.73 Opprest, and sunk, and sack'd, all in my way",
  "4.74 That did oppose me to my longed bay.",
  "4.75 My thirst was higher than Nobility",
  "4.76 And oft long'd sore to taste on Royalty,",
  "4.77 Whence poison, Pistols, and dread instruments",
  "4.78 Have been curst furtherers of mine intents.",
  "4.79 Nor Brothers, Nephews, Sons, nor Sires I've spar'd.",
  "4.80 When to a Monarchy my way they barr'd,",
  "4.81 There set, I rid my self straight out of hand",
  "4.82 Of such as might my son, or his withstand,",
  "4.83 Then heapt up gold and riches as the clay,",
  "4.84 Which others scatter like the dew in May.",
  "4.85 Sometimes vain-glory is the only bait",
  "4.86 Whereby my empty school is lur'd and caught.",
  "4.87 Be I of worth, of learning, or of parts,",
  "4.88 I judge I should have room in all men's hearts;",
  "4.89 And envy gnaws if any do surmount.",
  "4.90 I hate for to be had in small account.",
  "4.91 If Bias like, I'm stript unto my skin;",
  "4.92 I glory in my wealth I have within.",
  "4.93 Thus good, and bad, and what I am, you see,",
  "4.94 Now in a word, what my diseases be:",
  "4.95 The vexing Stone, in bladder and in reins,",
  "4.96 Torments me with intolerable pains;",
  "4.97 The windy cholic oft my bowels rend,",
  "4.98 To break the darksome prison, where it's penn'd;",
  "4.99 The knotty Gout doth sadly torture me,",
  "4.100 And the restraining lame Sciatica;",
  "4.101 The Quinsy and the Fevers often distaste me,",
  "4.102 And the Consumption to the bones doth waste me,",
  "4.103 Subject to all Diseases, that's the truth,",
  "4.104 Though some more incident to age, or youth;",
  "4.105 And to conclude, I may not tedious be,",
  "4.106 Man at his best estate is vanity.",
  "",
  "Old Age.",
  "",
  "5.1 What you have been, ev'n such have I before,",
  "5.2 And all you say, say I, and something more.",
  "5.3 Babe's innocence, Youth's wildness I have seen,",
  "5.4 And in perplexed Middle-age have been,",
  "5.5 Sickness, dangers, and anxieties have past,",
  "5.6 And on this Stage am come to act my last.",
  "5.7 I have been young, and strong, and wise as you",
  "5.8 But now, Bis pueri senes is too true.",
  "5.9 In every Age I've found much vanity.",
  "5.10 An end of all perfection now I see.",
  "5.11 It's not my valour, honour, nor my gold,",
  "5.12 My ruin'd house, now falling can uphold;",
  "5.13 It's not my Learning, Rhetoric, wit so large,",
  "5.14 Now hath the power, Death's Warfare, to discharge.",
  "5.15 It's not my goodly house, nor bed of down,",
  "5.16 That can refresh, or ease, if Conscience frown;",
  "5.17 Nor from alliance now can I have hope,",
  "5.18 But what I have done well, that is my prop.",
  "5.19 He that in youth is godly, wise, and sage",
  "5.20 Provides a staff for to support his age.",
  "5.21 Great mutations, some joyful, and some sad,",
  "5.22 In this short Pilgrimage I oft have had.",
  "5.23 Sometimes the Heavens with plenty smil'd on me,",
  "5.24 Sometimes, again, rain'd all adversity;",
  "5.25 Sometimes in honour, sometimes in disgrace,",
  "5.26 Sometime an abject, then again in place:",
  "5.27 Such private changes oft mine eyes have seen.",
  "5.28 In various times of state I've also been.",
  "5.29 I've seen a Kingdom flourish like a tree",
  "5.30 When it was rul'd by that Celestial she,",
  "5.31 And like a Cedar others so surmount",
  "5.32 That but for shrubs they did themselves account.",
  "5.33 Then saw I France, and Holland sav'd, Calais won,",
  "5.34 And Philip and Albertus half undone.",
  "5.35 I saw all peace at home, terror to foes,",
  "5.36 But ah, I saw at last those eyes to close,",
  "5.37 And then, me thought, the world at noon grew dark",
  "5.38 When it had lost that radiant Sun-like spark.",
  "5.39 In midst of griefs, I saw some hopes revive",
  "5.40 (For 'twas our hopes then kept our hearts alive);",
  "5.41 I saw hopes dash't, our forwardness was shent,",
  "5.42 And silenc'd we, by Act of Parliament.",
  "5.43 I've seen from Rome, an execrable thing,",
  "5.44 A plot to blow up Nobles and their King.",
  "5.45 I've seen designs at Ree and Cades cross't,",
  "5.46 And poor Palatinate for every lost.",
  "5.47 I've seen a Prince to live on others' lands,",
  "5.48 A Royal one, by alms from Subjects' hands.",
  "5.49 I've seen base men, advanc'd to great degree,",
  "5.50 And worthy ones, put to extremity,",
  "5.51 But not their Prince's love, nor state so high,",
  "5.52 Could once reverse, their shameful destiny.",
  "5.53 I've seen one stabb'd, another lose his head,",
  "5.54 And others fly their Country through their dread.",
  "5.55 I've seen, and so have ye, for 'tis but late,",
  "5.56 The desolation of a goodly State.",
  "5.57 Plotted and acted so that none can tell",
  "5.58 Who gave the counsell, but the Prince of hell.",
  "5.59 I've seen a land unmoulded with great pain,",
  "5.60 But yet may live to see't made up again.",
  "5.61 I've seen it shaken, rent, and soak'd in blood,",
  "5.62 But out of troubles ye may see much good.",
  "5.63 These are no old wives' tales, but this is truth.",
  "5.64 We old men love to tell, what's done in youth.",
  "5.65 But I return from whence I stept awry;",
  "5.66 My memory is short and brain is dry.",
  "5.67 My Almond-tree (gray hairs) doth flourish now,",
  "5.68 And back, once straight, begins apace to bow.",
  "5.69 My grinders now are few, my sight doth fail,",
  "5.70 My skin is wrinkled, and my cheeks are pale.",
  "5.71 No more rejoice, at music's pleasant noise,",
  "5.72 But do awake at the cock's clanging voice.",
  "5.73 I cannot scent savours of pleasant meat,",
  "5.74 Nor sapors find in what I drink or eat.",
  "5.75 My hands and arms, once strong, have lost their might.",
  "5.76 I cannot labour, nor I cannot fight:",
  "5.77 My comely legs, as nimble as the Roe,",
  "5.78 Now stiff and numb, can hardly creep or go.",
  "5.79 My heart sometimes as fierce, as Lion bold,",
  "5.80 Now trembling, and fearful, sad, and cold.",
  "5.81 My golden Bowl and silver Cord, e're long,",
  "5.82 Shall both be broke, by wracking death so strong.",
  "5.83 I then shall go whence I shall come no more.",
  "5.84 Sons, Nephews, leave, my death for to deplore.",
  "5.85 In pleasures, and in labours, I have found",
  "5.86 That earth can give no consolation sound",
  "5.87 To great, to rich, to poor, to young, or old,",
  "5.88 To mean, to noble, fearful, or to bold.",
  "5.89 From King to beggar, all degrees shall find",
  "5.90 But vanity, vexation of the mind.",
  "5.91 Yea, knowing much, the pleasant'st life of all",
  "5.92 Hath yet amongst that sweet, some bitter gall.",
  "5.93 Though reading others' Works doth much refresh,",
  "5.94 Yet studying much brings weariness to th' flesh.",
  "5.95 My studies, labours, readings all are done,",
  "5.96 And my last period can e'en elmost run.",
  "5.97 Corruption, my Father, I do call,",
  "5.98 Mother, and sisters both; the worms that crawl",
  "5.99 In my dark house, such kindred I have store.",
  "5.100 There I shall rest till heavens shall be no more;",
  "5.101 And when this flesh shall rot and be consum'd,",
  "5.102 This body, by this soul, shall be assum'd;",
  "5.103 And I shall see with these same very eyes",
  "5.104 My strong Redeemer coming in the skies.",
  "5.105 Triumph I shall, o're Sin, o're Death, o're Hell,",
  "5.106 And in that hope, I bid you all farewell.",
  ""
]