module.exports = [
  "'Twas about the beginning of the past century",
  "Billy Bowls was pressed into the British Navy,",
  "And conveyed on board the \"Waterwitch\" without delay,",
  "Scarce getting time to bid farewell to the villagers of Fairway.",
  "",
  "And once on board the \"Waterwitch\" he resolved to do his duty,",
  "And if he returned safe home he'd marry Nelly Blyth, his beauty;",
  "And he'd fight for old England like a jolly British tar,",
  "And the thought of Nelly Blyth would solace him during the war.",
  "",
  "Poor fellow, he little thought what he had to go through,",
  "But in all his trials at sea he never did rue;",
  "No, the brave tar became reconciled to his fate,",
  "And felt proud of his commander, Captain Ward the Great.",
  "",
  "And on board the \"Waterwitch\" was Tom Riggles, his old comrade,",
  "And with such a comrade he seldom felt afraid;",
  "Because the stories they told each other made the time pass quickly away,",
  "And made their hearts feel light and gay.",
  "",
  "'Twas on a Sunday morning and clear to the view,",
  "Captain Ward the attention of his men he drew;",
  "\"Look!\" he cried, \"There's two French men-of-war our right,",
  "Therefore prepare, my lads, immediately to begin the fight.\"",
  "",
  "Then the \" Waterwitch\" was steered to the ship that was most near,",
  "While every men resolved to sell their lives most dear;",
  "But the French commander disinclined to engage in the fight,",
  "And he ordered his men to put on a press of canvas and take to flight.",
  "",
  "Then Captain Ward gave the order to fire,",
  "Then Billy Bowls cried, \"Now we'll get fighting to our hearts' desire\";",
  "And for an hour a running fight was maintained,",
  "And the two ships of the enemy near upon the \"Waterwitch\" gained.",
  "",
  "Captain Ward walked the deck with a firm tread,",
  "When a shot from the enemy pierced the ship, yet he felt no dread;",
  "But with a splinter Bill Bowls was wounded on the left arm,",
  "And he cried, \"Death to the frog-eaters, they have done me little harm.\"",
  "",
  "Then Captain Ward cried, \"Fear not, my men, we will win the day,",
  "Now, men, pour in a broadside without delay",
  "Then they sailed around the \"St. Denis\" and the \"Gloire,\"",
  "And in their cabin windows they poured a deadly fire.",
  "",
  "The effect on the two ships was tremendous to behold,",
  "But the Frenchmen stuck to their guns with courage bold;",
  "And the crash and din of artillery was deafening to the ear,",
  "And the cries of the wounded men ware pitiful to hear.",
  "",
  "Then Captain Ward to his men did say,",
  "\"We must board the Frenchman without delay\";",
  "Then he seized his cutlass as he spoke,",
  "And jumped on board the \" St. Denis \" in the midst of the smoke.",
  "",
  "Then Bill Bowls and Tom Riggles hastily followed him,",
  "Then, hand to hand, the battle did begin;",
  "And the men sprang upon their foe and beat them back,",
  "And hauled down their colours and hoisted the Union Jack.",
  "",
  "But the men on board the \"St. Denis\" fought desperately hard,",
  "And just as the \"St. Denis\" was captured a ball struck Captain Ward",
  "Right on the forehead, and he fell without a groan,",
  "And for the death of Captain Ward the men did moan.",
  "",
  "Then the first lieutenant who was standing near by,",
  "Loudly to the men did cry,",
  "\"Come, men, and carry your noble commander below;",
  "But there's one consolation, we have beaten the foe.\"",
  "",
  "And thus fell Captain Ward in the prime of life,",
  "But I hope he is now in the better world free from strife;",
  "But, alas! 'tis sad to think he was buried in the mighty deep,",
  "Where too many of our brave seamen silently sleep.",
  ""
]