module.exports = [
  "\"Nimium ne crede colori.\"--Virgil,",
  "",
  "ECLOGUE THE FIRST.",
  "",
  "          _London.--Before the Door of a Lecture Room_.",
  "",
  "                 _Enter_ TRACY, _meeting_ INKEL.",
  "",
  "_Ink_. You're too late.",
  "",
  "_Tra_.                  Is it over?",
  "",
  "_Ink_.                              Nor will be this hour.",
  "But the benches are crammed, like a garden in flower.",
  "With the pride of our belles, who have made it the fashion;",
  "So, instead of \"beaux arts,\" we may say \"la _belle_ passion\"",
  "For learning, which lately has taken the lead in",
  "The world, and set all the fine gentlemen reading.",
  "",
  "_Tra_. I know it too well, and have worn out my patience",
  "With studying to study your new publications.",
  "There's Vamp, Scamp, and Mouthy, and Wordswords and Co.",
  "With their damnable----",
  "",
  "_Ink_.                  Hold, my good friend, do you know",
  "Whom you speak to?",
  "",
  "_Tra_.            Right well, boy, and so does \"the Row:\"",
  "You're an author--a poet--",
  "",
  "_Ink_.                     And think you that I",
  "Can stand tamely in silence, to hear you decry",
  "The Muses?",
  "",
  "_Tra_.    Excuse me: I meant no offence",
  "To the Nine; though the number who make some pretence",
  "To their favours is such----but the subject to drop,",
  "I am just piping hot from a publisher's shop,",
  "(Next door to the pastry-cook's; so that when I",
  "Cannot find the new volume I wanted to buy",
  "On the bibliopole's shelves, it is only two paces,",
  "As one finds every author in one of those places:)",
  "Where I just had been skimming a charming critique,",
  "So studded with wit, and so sprinkled with Greek!",
  "Where your friend--you know who--has just got such a threshing,",
  "That it is, as the phrase goes, extremely \"_refreshing._\"",
  "What a beautiful word!",
  "",
  "_Ink_.                Very true; 'tis so soft",
  "And so cooling--they use it a little too oft;",
  "And the papers have got it at last--but no matter.",
  "So they've cut up our friend then?",
  "",
  "_Tra_.                            Not left him a tatter--",
  "Not a rag of his present or past reputation,",
  "Which they call a disgrace to the age, and the nation.",
  "",
  "_Ink_. I'm sorry to hear this! for friendship, you know--",
  "Our poor friend!--but I thought it would terminate so.",
  "Our friendship is such, I'll read nothing to shock it.",
  "You don't happen to have the Review in your pocket?",
  "",
  "_Tra_. No; I left a round dozen of authors and others",
  "(Very sorry, no doubt, since the cause is a brother's)",
  "All scrambling and jostling, like so many imps,",
  "And on fire with impatience to get the next glimpse.",
  "",
  "_Ink_. Let us join them.",
  "",
  "_Tra_.                  What, won't you return to the lecture?",
  "",
  "_Ink_. Why the place is so crammed, there's not room for a spectre.",
  "Besides, our friend Scamp is to-day so absurd--",
  "",
  "_Tra_. How can you know that till you hear him?",
  "",
  "_Ink_.                                          I heard",
  "Quite enough; and, to tell you the truth, my retreat",
  "Was from his vile nonsense, no less than the heat.",
  "",
  "_Tra_. I have had no great loss then?",
  "",
  "_Ink_.                                Loss!--such a palaver!",
  "I'd inoculate sooner my wife with the slaver",
  "Of a dog when gone rabid, than listen two hours",
  "To the torrent of trash which around him he pours,",
  "Pumped up with such effort, disgorged with such labour,",
  "That----come--do not make me speak ill of one's neighbour.",
  "",
  "_Tra_. _I_ make you!",
  "",
  "_Ink_.                   Yes, you! I said nothing until",
  "You compelled me, by speaking the truth----",
  "",
  "_Tra_.                               _To speak ill?_",
  "Is that your deduction?",
  "",
  "_Ink_.                 When speaking of Scamp ill,",
  "I certainly _follow, not set_ an example.",
  "The fellow's a fool, an impostor, a zany.",
  "",
  "_Tra_. And the crowd of to-day shows that one fool makes many.",
  "But we two will be wise.",
  "",
  "_Ink_.                  Pray, then, let us retire.",
  "",
  "_Tra_. I would, but----",
  "",
  "_Ink_.                There must be attraction much higher",
  "Than Scamp, or the Jew's harp he nicknames his lyre,",
  "To call you to this hotbed.",
  "",
  "_Tra_.                     I own it--'tis true--",
  "A fair lady----",
  "",
  "_Ink_.       A spinster?",
  "",
  "_Tra_.                  Miss Lilac.",
  "",
  "_Ink_.                               The Blue!",
  "",
  "_Tra_. The heiress! The angel!",
  "",
  "_Ink_.                         The devil! why, man,",
  "Pray get out of this hobble as fast as you can.",
  "_You_ wed with Miss Lilac! 'twould be your perdition:",
  "She's a poet, a chymist, a mathematician.",
  "",
  "_Tra_. I say she's an angel.",
  "",
  "_Ink_.                      Say rather an angle.",
  "If you and she marry, you'll certainly wrangle.",
  "I say she's a Blue, man, as blue as the ether.",
  "",
  "_Tra_. And is that any cause for not coming together?",
  "",
  "_Ink_. Humph! I can't say I know any happy alliance",
  "Which has lately sprung up from a wedlock with science.",
  "She's so learnéd in all things, and fond of concerning",
  "Herself in all matters connected with learning,",
  "That----",
  "",
  "_Tra_.  What?",
  "",
  "_Ink_.        I perhaps may as well hold my tongue;",
  "But there's five hundred people can tell you you're",
  "wrong.",
  "",
  "_Tra_. You forget Lady Lilac's as rich as a Jew.",
  "",
  "_Ink_. Is it miss or the cash of mamma you pursue?",
  "",
  "_Tra_. Why, Jack, I'll be frank with you--something of both.",
  "The girl's a fine girl.",
  "",
  "_Ink_.                 And you feel nothing loth",
  "To her good lady-mother's reversion; and yet",
  "Her life is as good as your own, I will bet.",
  "",
  "_Tra_. Let her live, and as long as she likes; I demand",
  "Nothing more than the heart of her daughter and hand.",
  "",
  "_Ink_. Why, that heart's in the inkstand--that hand on the pen.",
  "",
  "_Tra_. A propos--Will you write me a song now and then?",
  "",
  "_Ink_. To what purpose?",
  "",
  "_Tra_.                 You know, my dear friend, that in prose",
  "My talent is decent, as far as it goes;",
  "But in rhyme----",
  "",
  "_Ink_.         You're a terrible stick, to be sure.",
  "",
  "_Tra_. I own it; and yet, in these times, there's no lure",
  "For the heart of the fair like a stanza or two;",
  "And so, as I can't, will you furnish a few?",
  "",
  "_Ink_. In your name?",
  "",
  "_Tra_.               In my name. I will copy them out,",
  "To slip into her hand at the very next rout.",
  "",
  "_Ink_. Are you so far advanced as to hazard this?",
  "",
  "_Tra_.                                            Why,",
  "Do you think me subdued by a Blue-stocking's eye,",
  "So far as to tremble to tell her in rhyme",
  "What I've told her in prose, at the least, as sublime?",
  "",
  "_Ink_. _As sublime!_ If i be so, no need of my Muse.",
  "",
  "_Tra_. But consider, dear Inkel, she's one of the \"Blues.\"",
  "",
  "_Ink_. As sublime!--Mr. Tracy--I've nothing to say.",
  "Stick to prose--As sublime!!--but I wish you good day.",
  "",
  "_Tra_. Nay, stay, my dear fellow--consider--I'm wrong;",
  "I own it; but, prithee, compose me the song.",
  "",
  "_Ink_. _As_ sublime!!",
  "",
  "_Tra_.                 I but used the expression in haste.",
  "",
  "_Ink_. That may be, Mr. Tracy, but shows damned bad taste.",
  "",
  "_Tra_. I own it, I know it, acknowledge it--what",
  "Can I say to you more?",
  "",
  "_Ink_.                 I see what you'd be at:",
  "You disparage my parts with insidious abuse,",
  "Till you think you can turn them best to your own use.",
  "",
  "_Tra_. And is that not a sign I respect them?",
  "",
  "_Ink_.                                        Why that",
  "To be sure makes a difference.",
  "",
  "_Tra_.                        I know what is what:",
  "And you, who're a man of the gay world, no less",
  "Than a poet of t'other, may easily guess",
  "That I never could mean, by a word, to offend",
  "A genius like you, and, moreover, my friend.",
  "",
  "_Ink_. No doubt; you by this time should know what is due",
  "To a man of----but come--let us shake hands.",
  "",
  "_Tra_.                                      You knew,",
  "And you _know_, my dear fellow, how heartily I,",
  "Whatever you publish, am ready to buy.",
  "",
  "_Ink_. That's my bookseller's business; I care not for sale;",
  "Indeed the best poems at first rather fail.",
  "There were Renegade's epics, and Botherby's plays,",
  "And my own grand romance--",
  "",
  "_Tra_.                     Had its full share of praise.",
  "I myself saw it puffed in the \"Old Girl's Review.\"",
  "",
  "_Ink_. What Review?",
  "",
  "_Tra_.              Tis the English \"Journal de Trevoux;\"",
  "A clerical work of our Jesuits at home.",
  "Have you never yet seen it?",
  "",
  "_Ink_.                     That pleasure's to come.",
  "",
  "_Tra_. Make haste then.",
  "",
  "_Ink_.                  Why so?",
  "",
  "_Tra_.                         I have heard people say",
  "That it threatened to give up the _ghost_ t'other day.",
  "",
  "_Ink_. Well, that is a sign of some _spirit_.",
  "",
  "_Tra_.                                            No doubt.",
  "Shall you be at the Countess of Fiddlecome's rout?",
  "",
  "_Ink_. I've a card, and shall go: but at present, as soon",
  "As friend Scamp shall be pleased to step down from the moon,",
  "(Where he seems to be soaring in search of his wits),",
  "And an interval grants from his lecturing fits,",
  "I'm engaged to the Lady Bluebottle's collation,",
  "To partake of a luncheon and learn'd conversation:",
  "'Tis a sort of reunion for Scamp, on the days",
  "Of his lecture, to treat him with cold tongue and praise.",
  "And I own, for my own part, that 'tis not unpleasant.",
  "Will you go? There's Miss Lilac will also be present.",
  "",
  "_Tra_. That \"metal's attractive.\"",
  "",
  "_Ink_.                           No doubt--to the pocket.",
  "",
  "_Tra_. You should rather encourage my passion than shock it.",
  "But let us proceed; for I think by the hum----",
  "",
  "_Ink_. Very true; let us go, then, before they can come,",
  "Or else we'll be kept here an hour at their levee,",
  "On the rack of cross questions, by all the blue bevy.",
  "Hark! Zounds, they'll be on us; I know by the drone",
  "Of old Botherby's spouting ex-cathedrâ tone.",
  "Aye! there he is at it. Poor Scamp! better join",
  "Your friends, or he'll pay you back in your own coin.",
  "",
  "_Tra_. All fair; 'tis but lecture for lecture.",
  "",
  "_Ink_.                                         That's clear.",
  "But for God's sake let's go, or the Bore will be here.",
  "Come, come: nay, I'm off.",
  "                                                        [_Exit_ INKEL.",
  "",
  "_Tra_.                     You are right, and I'll follow;",
  "'Tis high time for a \"_Sic me servavit Apollo_.\"",
  "And yet we shall have the whole crew on our kibes,",
  "Blues, dandies, and dowagers, and second-hand scribes,",
  "All flocking to moisten their exquisite throttles",
  "With a glass of Madeira at Lady Bluebottle's.",
  "                                                        [_Exit_ TRACY.",
  "",
  "ECLOGUE THE SECOND.",
  "",
  "   _An Apartment in the House of_ LADY BLUEBOTTLE.--_A Table prepared._",
  "",
  "                 SIR RICHARD BLUEBOTTLE _solus_.",
  "",
  "Was there ever a man who was married so sorry?",
  "Like a fool, I must needs do the thing in a hurry.",
  "My life is reversed, and my quiet destroyed;",
  "My days, which once passed in so gentle a void,",
  "Must now, every hour of the twelve, be employed;",
  "The twelve, do I say?--of the whole twenty-four,",
  "Is there one which I dare call my own any more?",
  "What with driving and visiting, dancing and dining,",
  "What with learning, and teaching, and scribbling, and shining,",
  "In science and art, I'll be cursed if I know",
  "Myself from my wife; for although we are two,",
  "Yet she somehow contrives that all things shall be done",
  "In a style which proclaims us eternally one.",
  "But the thing of all things which distresses me more",
  "Than the bills of the week (though they trouble me sore)",
  "Is the numerous, humorous, backbiting crew",
  "Of scribblers, wits, lecturers, white, black, and blue,",
  "Who are brought to my house as an inn, to my cost--",
  "For the bill here, it seems, is defrayed by the host--",
  "No pleasure! no leisure! no thought for my pains,",
  "But to hear a vile jargon which addles my brains;",
  "A smatter and chatter, gleaned out of reviews,",
  "By the rag, tag, and bobtail, of those they call \"Blues;\"",
  "A rabble who know not----But soft, here they come!",
  "Would to God I were deaf! as I'm not, I'll be dumb.",
  "",
  "_Enter_ LADY BLUEBOTTLE, MISS LILAC, LADY BLUEMOUNT, MR. BOTHERBY,",
  "   INKEL, TRACY, MISS MAZARINE, _and others, with_ SCAMP _the Lecturer,",
  "                           etc., etc._",
  "",
  "_Lady Blueb_.",
  "Ah! Sir Richard, good morning: I've brought you some friends.",
  "",
  "_Sir Rich_. (_bows, and afterwards aside_).",
  "If friends, they're the first.",
  "",
  "_Lady Blueb_.                 But the luncheon attends.",
  "I pray ye be seated, \"_sans cérémonie_.\"",
  "Mr. Scamp, you're fatigued; take your chair there, next me.",
  "                                                      [_They all sit._",
  "",
  "_Sir Rich_. (_aside_). If he does, his fatigue is to come.",
  "",
  "_Lady Blueb_.                                             Mr. Tracy--",
  "Lady Bluemount--Miss Lilac--be pleased, pray, to place ye;",
  "And you, Mr. Botherby--",
  "",
  "_Both_.                 Oh, my dear Lady,",
  "I obey.",
  "",
  "_Lady Blueb_. Mr. Inkel, I ought to upbraid ye:",
  "You were not at the lecture.",
  "",
  "_Ink_.                      Excuse me, I was;",
  "But the heat forced me out in the best part--alas!",
  "And when--",
  "",
  "_Lady Blueb_. To be sure it was broiling; but then",
  "You have lost such a lecture!",
  "",
  "_Both_.                      The best of the ten.",
  "",
  "_Tra_. How can you know that? there are two more.",
  "",
  "_Both_.                                          Because",
  "I defy him to beat this day's wondrous applause.",
  "The very walls shook.",
  "",
  "_Ink_.               Oh, if that be the test,",
  "I allow our friend Scamp has this day done his best.",
  "Miss Lilac, permit me to help you;--a wing?",
  "",
  "_Miss Lil_. No more, sir, I thank you. Who lectures next spring?",
  "",
  "_Both_. Dick Dunder.",
  "",
  "_Ink_.               That is, if he lives.",
  "",
  "_Miss Lil_.                               And why not?",
  "",
  "_Ink_. No reason whatever, save that he's a sot.",
  "Lady Bluemount! a glass of Madeira?",
  "",
  "_Lady Bluem_.                      With pleasure.",
  "",
  "_Ink_. How does your friend Wordswords, that Windermere treasure?",
  "Does he stick to his lakes, like the leeches he sings,",
  "And their gatherers, as Homer sung warriors and kings?",
  "",
  "_Lady Bluem_. He has just got a place.",
  "",
  "_Ink_.                                 As a footman?",
  "",
  "_Lady Bluem_.                                       For shame!",
  "Nor profane with your sneers so poetic a name.",
  "",
  "_Ink_. Nay, I meant him no evil, but pitied his master;",
  "For the poet of pedlers 'twere, sure, no disaster",
  "To wear a new livery; the more, as 'tis not",
  "The first time he has turned both his creed and his coat.",
  "",
  "_Lady Bluem_. For shame! I repeat. If Sir George could but hear--",
  "",
  "_Lady Blueb_. Never mind our friend Inkel; we all know, my dear,",
  "'Tis his way.",
  "",
  "_Sir Rich_.    But this place--",
  "",
  "_Ink_.                          Is perhaps like friend Scamp's,",
  "A lecturer's.",
  "",
  "_Lady Bluem_. Excuse me--'tis one in the \"Stamps:\"",
  "He is made a collector.",
  "",
  "_Tra_.                 Collector!",
  "",
  "_Sir Rich_.                       How?",
  "",
  "_Miss Lil_.                            What?",
  "",
  "_Ink_. I shall think of him oft when I buy a new hat:",
  "There his works will appear--",
  "",
  "_Lady Bluem_.                Sir, they reach to the Ganges.",
  "",
  "_Ink_. I sha'n't go so far--I can have them at Grange's.",
  "",
  "_Lady Bluem_. Oh fie!",
  "",
  "_Miss Lil_.          And for shame!",
  "",
  "_Lady Bluem_.                      You're too bad.",
  "",
  "_Both_.                                           Very good!",
  "",
  "_Lady Bluem_. How good?",
  "",
  "_Lady Blueb_.          He means nought--'tis his phrase.",
  "",
  "_Lady Bluem_.                                          He grows rude.",
  "",
  "_Lady Blueb_. He means nothing; nay, ask him.",
  "",
  "_Lady Bluem_.                                Pray, Sir! did you mean",
  "What you say?",
  "",
  "_Ink_.        Never mind if he did; 'twill be seen",
  "That whatever he means won't alloy what he says.",
  "",
  "_Both_. Sir!",
  "",
  "_Ink_.      Pray be content with your portion of praise;",
  "'Twas in your defence.",
  "",
  "_Both_.               If you please, with submission",
  "I can make out my own.",
  "",
  "_Ink_.                 It would be your perdition.",
  "While you live, my dear Botherby, never defend",
  "Yourself or your works; but leave both to a friend.",
  "Apropos--Is your play then accepted at last?",
  "",
  "_Both_. At last?",
  "",
  "_Ink_. Why I thought--that's to say--there had passed",
  "A few green-room whispers, which hinted,--you know",
  "That the taste of the actors at best is so so.",
  "",
  "_Both_. Sir, the green-room's in rapture, and so's the Committee.",
  "",
  "_Ink_. Aye--yours are the plays for exciting our \"pity",
  "And fear,\" as the Greek says: for \"purging the mind,\"",
  "I doubt if you'll leave us an equal behind.",
  "",
  "_Both_. I have written the prologue, and meant to have prayed",
  "For a spice of your wit in an epilogue's aid.",
  "",
  "_Ink_. Well, time enough yet, when the play's to be played.",
  "Is it cast yet?",
  "",
  "_Both_.         The actors are fighting for parts,",
  "As is usual in that most litigious of arts.",
  "",
  "_Lady Blueb_. We'll all make a party, and go the _first_ night.",
  "",
  "_Tra_. And you promised the epilogue, Inkel.",
  "",
  "_Ink_.                                       Not quite.",
  "However, to save my friend Botherby trouble,",
  "I'll do what I can, though my pains must be double.",
  "",
  "_Tra_. Why so?",
  "",
  "_Ink_.          To do justice to what goes before.",
  "",
  "_Both_. Sir, I'm happy to say, I've no fears on that score.",
  "Your parts, Mr. Inkel, are----",
  "",
  "_Ink_.                    Never mind _mine_;",
  "Stick to those of your play, which is quite your own line.",
  "",
  "_Lady Bluem_. You're a fugitive writer, I think, sir, of rhymes?",
  "",
  "_Ink_. Yes, ma'am; and a fugitive reader sometimes.",
  "On Wordswords, for instance, I seldom alight,",
  "Or on Mouthey, his friend, without taking to flight.",
  "",
  "_Lady Bluem_. Sir, your taste is too common; but time and posterity",
  "Will right these great men, and this age's severity",
  "Become its reproach.",
  "",
  "_Ink_.               I've no sort of objection,",
  "So I'm not of the party to take the infection.",
  "",
  "_Lady Blueb_. Perhaps you have doubts that they ever will _take_?",
  "",
  "_Ink_. Not at all; on the contrary, those of the lake",
  "Have taken already, and still will continue",
  "To take--what they can, from a groat to a guinea,",
  "Of pension or place;--but the subject's a bore.",
  "",
  "_Lady Bluem_. Well, sir, the time's coming.",
  "",
  "_Ink_.                                   Scamp! don't you feel sore?",
  "What say you to this?",
  "",
  "_Scamp_.             They have merit, I own;",
  "Though their system's absurdity keeps it unknown,",
  "",
  "_Ink_. Then why not unearth it in one of your lectures?",
  "",
  "_Scamp_. It is only time past which comes under my strictures.",
  "",
  "_Lady Blueb_. Come, a truce with all tartness;--the joy of my heart",
  "Is to see Nature's triumph o'er all that is art.",
  "Wild Nature!--Grand Shakespeare!",
  "",
  "_Both_.                         And down Aristotle!",
  "",
  "_Lady Bluem_. Sir George thinks exactly with Lady Bluebottle:",
  "And my Lord Seventy-four, who protects our dear Bard,",
  "And who gave him his place, has the greatest regard",
  "For the poet, who, singing of pedlers and asses,",
  "Has found out the way to dispense with Parnassus.",
  "",
  "_Tra_. And you, Scamp!--",
  "",
  "_Scamp_.                I needs must confess I'm embarrassed.",
  "",
  "_Ink_. Don't call upon Scamp, who's already so harassed",
  "With old _schools_, and new _schools_,",
  "                         and no _schools_, and all _schools_.",
  "",
  "_Tra_. Well, one thing is certain, that _some_ must be fools.",
  "I should like to know who.",
  "",
  "_Ink_.                   And I should not be sorry",
  "To know who are _not_:--it would save us some worry.",
  "",
  "_Lady Blueb_. A truce with remark, and let nothing control",
  "This \"feast of our reason, and flow of the soul.\"",
  "Oh! my dear Mr. Botherby! sympathise!--I",
  "Now feel such a rapture, I'm ready to fly,",
  "I feel so elastic--\"_so buoyant--so buoyant!_\"",
  "",
  "_Ink_. Tracy! open the window.",
  "",
  "_Tra_.                         I wish her much joy on't.",
  "",
  "_Both_. For God's sake, my Lady Bluebottle, check not",
  "This gentle emotion, so seldom our lot",
  "Upon earth. Give it way: 'tis an impulse which lifts",
  "Our spirits from earth--the sublimest of gifts;",
  "For which poor Prometheus was chained to his mountain:",
  "'Tis the source of all sentiment--feeling's true fountain;",
  "'Tis the Vision of Heaven upon Earth: 'tis the gas",
  "Of the soul: 'tis the seizing of shades as they pass,",
  "And making them substance: 'tis something divine:--",
  "",
  "_Ink_. Shall I help you, my friend, to a little more wine?",
  "",
  "_Both_. I thank you: not any more, sir, till I dine.",
  "",
  "_Ink_. Apropos--Do you dine with Sir Humphry to day?",
  "",
  "_Tra_. I should think with _Duke_ Humphry was more in your way.",
  "",
  "_Ink_. It might be of yore; but we authors now look",
  "To the Knight, as a landlord, much more than the Duke.",
  "The truth is, each writer now quite at his ease is,",
  "And (except with his publisher) dines where he pleases.",
  "But 'tis now nearly five, and I must to the Park.",
  "",
  "_Tra_. And I'll take a turn with you there till 'tis dark.",
  "And you, Scamp--",
  "",
  "_Scamp_.          Excuse me! I must to my notes,",
  "For my lecture next week.",
  "",
  "_Ink_. He must mind whom he quotes",
  "Out of \"Elegant Extracts.\"",
  "",
  "_Lady Blueb_.             Well, now we break up;",
  "But remember Miss Diddle invites us to sup.",
  "",
  "_Ink_. Then at two hours past midnight we all meet again,",
  "For the sciences, sandwiches, hock, and champagne!",
  "",
  "_Tra_. And the sweet lobster salad!",
  "",
  "_Both_.                               I honour that meal;",
  "For 'tis then that our feelings most genuinely--feel.",
  "",
  "_Ink_. True; feeling is truest _then_, far beyond question:",
  "I wish to the gods 'twas the same with digestion!",
  "",
  "_Lady Blueb_. Pshaw!--never mind that; for one moment of feeling",
  "Is worth--God knows what.",
  "",
  "_Ink_.                  'Tis at least worth concealing",
  "For itself, or what follows--But here comes your carriage.",
  "",
  "_Sir Rich_. (_aside_).",
  "I wish all these people were d----d with _my_ marriage!",
  "                                                            [_Exeunt._",
  ""
]