module.exports = [
  "IMMITATION OF ENGLISH POETS. COWLEY",
  "",
  "Fain would my Muse the flowery treasures sing,",
  "And humble glories of the youthful Spring;",
  "Where opening roses breathing sweets diffuse,",
  "And soft carnations shower their balmy dews;",
  "Where lilies smile in virgin robes of white,",
  "The thin undress of superficial light,",
  "And varied tulips show so dazzling gay,",
  "Blushing in bright diversities of day.",
  "Each painted floweret in the lake below",
  "Surveys its beauties, whence its beauties grow;",
  "And pale Narcissus on the bank, in vain",
  "Transformèd, gazes on himself again.",
  "Here aged trees cathedral walks compose,",
  "And mount the hill in venerable rows:",
  "There the green infants in their beds are laid,",
  "The garden's hope, and its expected shade.",
  "Here orange-trees with blooms and pendants shine,",
  "And vernal honours to their autumn join;",
  "Exceed their promise in the ripen'd store,",
  "Yet in the rising blossom promise more.",
  "There in bright drops the crystal fountains play,",
  "By laurels shielded from the piercing day:",
  "Where Daphne, now a tree, as once a maid,",
  "Still from Apollo vindicates her shade,",
  "Still turns her beauties from the invading beam,",
  "Nor seeks in vain for succour to the stream.",
  "The stream at once preserves her virgin leaves,",
  "At once a shelter from her boughs receives,",
  "Where summer's beauty midst of winter stays,",
  "And winter's coolness spite of summer's rays.",
  ""
]