module.exports = [
  "TO-DAY I want the sky,",
  "The tops of the high hills,",
  "Above the last man's house,",
  "His hedges, and his cows,",
  "Where, if I will, I look",
  "Down even on sheep and rook,",
  "And of all things that move",
  "See buzzards only above:--",
  "Past all trees, past furze",
  "And thorn, where nought deters",
  "The desire of the eye",
  "For sky, nothing but sky.",
  "I sicken of the woods",
  "And all the multitudes",
  "Of hedge-trees. They are no more",
  "Than weeds upon this floor",
  "Of the river of air",
  "Leagues deep, leagues wide, where",
  "I am like a fish that lives",
  "In weeds and mud and gives",
  "What's above him no thought.",
  "I might be a tench for aught",
  "That I can do to-day",
  "Down on the wealden clay.",
  "Even the tench has days",
  "When he floats up and plays",
  "Among the lily leaves",
  "And sees the sky, or grieves",
  "Not if he nothing sees:",
  "While I, I know that trees",
  "Under that lofty sky",
  "Are weeds, fields mud, and I",
  "Would arise and go far",
  "To where the lilies are.",
  ""
]