module.exports = [
  "Scene, on an Eminence on one of those Downs, which afford to the South a view of the Sea; to the North of the Weald of Sussex. Time, an Afternoon in April, 1793.",
  "",
  "",
  "Long wintry months are past; the Moon that now",
  "Lights her pale crescent even at noon, has made",
  "Four times her revolution; since with step,",
  "Mournful and slow, along the wave-worn cliff,",
  "Pensive I took my solitary way,",
  "Lost in despondence, while contemplating",
  "Not my own wayward destiny alone,",
  "(Hard as it is, and difficult to bear!)",
  "But in beholding the unhappy lot",
  "Of the lorn Exiles; who, amid the storms",
  "Of wild disastrous Anarchy, are thrown,",
  "Like shipwreck'd sufferers, on England's coast,",
  "To see, perhaps, no more their native land,",
  "Where Desolation riots: They, like me,",
  "From fairer hopes and happier prospects driven,",
  "Shrink from the future, and regret the past.",
  "But on this Upland scene, while April comes,",
  "With fragrant airs, to fan my throbbing breast,",
  "Fain would I snatch an interval from Care,",
  "That weighs my wearied spirit down to earth;",
  "Courting, once more, the influence of Hope",
  "(For \"Hope\" still waits upon the flowery prime)",
  "As here I mark Spring's humid hand unfold",
  "The early leaves that fear capricious winds,",
  "While, even on shelter'd banks, the timid flowers",
  "Give, half reluctantly, their warmer hues",
  "To mingle with the primroses' pale stars.",
  "No shade the leafless copses yet afford,",
  "Nor hide the mossy labours of the Thrush,",
  "That, startled, darts across the narrow path;",
  "But quickly re-assur'd, resumes his talk,",
  "Or adds his louder notes to those that rise",
  "From yonder tufted brake; where the white buds",
  "Of the first thorn are mingled with the leaves",
  "Of that which blossoms on the brow of May.",
  "Ah! 'twill not be:---- So many years have pass'd,",
  "Since, on my native hills, I learn'd to gaze",
  "On these delightful landscapes; and those years",
  "Have taught me so much sorrow, that my soul",
  "Feels not the joy reviving Nature brings;",
  "But, in dark retrospect, dejected dwells",
  "On human follies, and on human woes.----",
  "What is the promise of the infant year,",
  "The lively verdure, or the bursting blooms,",
  "To those, who shrink from horrors such as War",
  "Spreads o'er the affrighted world? With swimming eye,",
  "Back on the past they throw their mournful looks,",
  "And see the Temple, which they fondly hop'd",
  "Reason would raise to Liberty, destroy'd",
  "By ruffian hands; while, on the ruin'd mass,",
  "Flush'd with hot blood, the Fiend of Discord sits",
  "In savage triumph; mocking every plea",
  "Of policy and justice, as she shews",
  "The headless corse of one, whose only crime",
  "Was being born a Monarch--Mercy turns,",
  "From spectacle so dire, her swol'n eyes;",
  "And Liberty, with calm, unruffled brow",
  "Magnanimous, as conscious of her strength",
  "In Reason's panoply, scorns to distain",
  "Her righteous cause with carnage, and resigns",
  "To Fraud and Anarchy the infuriate crowd.----",
  "What is the promise of the infant year",
  "To those, who (while the poor but peaceful hind",
  "Pens, unmolested, the encreasing flock",
  "Of his rich master in this sea-fenc'd isle)",
  "Survey, in neighbouring countries, scenes that make",
  "The sick heart shudder; and the Man, who thinks,",
  "Blush for his species? There the trumpet's voice",
  "Drowns the soft warbling of the woodland choir;",
  "And violets, lurking in their turfy beds",
  "Beneath the flow'ring thorn, are stain'd with blood.",
  "There fall, at once, the spoiler and the spoil'd;",
  "While War, wide-ravaging, annihilates",
  "The hope of cultivation; gives to Fiends,",
  "The meagre, ghastly Fiends of Want and Woe,",
  "The blasted land--There, taunting in the van",
  "Of vengeance-breathing armies, Insult stalks;",
  "And, in the ranks, \"1 Famine, and Sword, and Fire,",
  "\"Crouch for employment.\"--Lo! the suffering world,",
  "Torn by the fearful conflict, shrinks, amaz'd,",
  "From Freedom's name, usurp'd and misapplied,",
  "And, cow'ring to the purple Tyrant's rod,",
  "Deems that the lesser ill--Deluded Men!",
  "Ere ye prophane her ever-glorious name,",
  "Or catalogue the thousands that have bled",
  "Resisting her; or those, who greatly died",
  "Martyrs to Liberty --revert awhile",
  "To the black scroll, that tells of regal crimes",
  "Committed to destroy her; rather count",
  "The hecatombs of victims, who have fallen",
  "Beneath a single despot; or who gave",
  "Their wasted lives for some disputed claim",
  "Between anointed robbers: 2 Monsters both!",
  "\"3 Oh! Polish'd perturbation--golden care!\"",
  "So strangely coveted by feeble Man",
  "To lift him o'er his fellows;--Toy, for which",
  "Such showers of blood have drench'd th' affrighted earth--",
  "Unfortunate his lot, whose luckless head",
  "Thy jewel'd circlet, lin'd with thorns, has bound;",
  "And who, by custom's laws, obtains from thee",
  "Hereditary right to rule, uncheck'd,",
  "Submissive myriads: for untemper'd power,",
  "Like steel ill form'd, injures the hand",
  "It promis'd to protect--Unhappy France!",
  "If e'er thy lilies, trampled now in dust,",
  "And blood-bespotted, shall again revive",
  "In silver splendour, may the wreath be wov'n",
  "By voluntary hands; and Freemen, such",
  "As England's self might boast, unite to place",
  "The guarded diadem on his fair brow,",
  "Where Loyalty may join with Liberty",
  "To fix it firmly.--In the rugged school",
  "Of stern Adversity so early train'd,",
  "His future life, perchance, may emulate",
  "That of the brave Bernois 4 , so justly call'd",
  "The darling of his people; who rever'd",
  "The Warrior less, than they ador'd the Man!",
  "But ne'er may Party Rage, perverse and blind,",
  "And base Venality, prevail to raise",
  "To public trust, a wretch, whose private vice",
  "Makes even the wildest profligate recoil;",
  "And who, with hireling ruffians leagu'd, has burst",
  "The laws of Nature and Humanity!",
  "Wading, beneath the Patriot's specious mask,",
  "And in Equality's illusive name,",
  "To empire thro' a stream of kindred blood--",
  "Innocent prisoner!--most unhappy heir",
  "Of fatal greatness, who art suffering now",
  "For all the crimes and follies of thy race;",
  "Better for thee, if o'er thy baby brow",
  "The regal mischief never had been held:",
  "Then, in an humble sphere, perhaps content,",
  "Thou hadst been free and joyous on the heights",
  "Of Pyrennean mountains, shagg'd with woods",
  "Of chesnut, pine, and oak: as on these hills",
  "Is yonder little thoughtless shepherd lad,",
  "Who, on the slope abrupt of downy turf",
  "Reclin'd in playful indolence, sends off",
  "The chalky ball, quick bounding far below;",
  "While, half forgetful of his simple task,",
  "Hardly his length'ning shadow, or the bells'",
  "Slow tinkling of his flock, that supping tend",
  "To the brown fallows in the vale beneath,",
  "Where nightly it is folded, from his sport",
  "Recal the happy idler.--While I gaze",
  "On his gay vacant countenance, my thoughts",
  "Compare with his obscure, laborious lot,",
  "Thine, most unfortunate, imperial Boy!",
  "Who round thy sullen prison daily hear'st",
  "The savage howl of Murder, as it seeks",
  "Thy unoffending life: while sad within",
  "Thy wretched Mother, petrified with grief,",
  "Views thee with stony eyes, and cannot weep!--",
  "Ah! much I mourn thy sorrows, hapless Queen!",
  "And deem thy expiation made to Heaven",
  "For every fault, to which Prosperity",
  "Betray'd thee, when it plac'd thee on a throne",
  "Where boundless power was thine, and thou wert rais'd",
  "High (as it seem'd) above the envious reach",
  "Of destiny! Whate'er thy errors were,",
  "Be they no more remember'd; tho' the rage",
  "Of Party swell'd them to such crimes, as bade",
  "Compassion stifle every sigh that rose",
  "For thy disastrous lot--More than enough",
  "Thou hast endur'd; and every English heart,",
  "Ev'n those, that highest beat in Freedom's cause,",
  "Disclaim as base, and of that cause unworthy,",
  "The Vengeance, or the Fear, that makes thee still",
  "A miserable prisoner!--Ah! who knows,",
  "From sad experience, more than I, to feel",
  "For thy desponding spirit, as it sinks",
  "Beneath procrastinated fears for those",
  "More dear to thee than life! But eminence",
  "Of misery is thine, as once of joy;",
  "And, as we view the strange vicissitude,",
  "We ask anew, where happiness is found?------",
  "Alas! in rural life, where youthful dreams",
  "See the Arcadia that Romance describes,",
  "Not even Content resides!--In yon low hut",
  "Of clay and thatch, where rises the grey smoke",
  "Of smold'ring turf, cut from the adjoining moor,",
  "The labourer, its inhabitant, who toils",
  "From the first dawn of twilight, till the Sun",
  "Sinks in the rosy waters of the West,",
  "Finds that with poverty it cannot dwell;",
  "For bread, and scanty bread, is all he earns",
  "For him and for his household--Should Disease,",
  "Born of chill wintry rains, arrest his arm,",
  "Then, thro' his patch'd and straw-stuff'd casement, peeps",
  "The squalid figure of extremest Want;",
  "And from the Parish the reluctant dole,",
  "Dealt by th' unfeeling farmer, hardly saves",
  "The ling'ring spark of life from cold extinction:",
  "Then the bright Sun of Spring, that smiling bids",
  "All other animals rejoice, beholds,",
  "Crept from his pallet, the emaciate wretch",
  "Attempt, with feeble effort, to resume",
  "Some heavy task, above his wasted strength,",
  "Turning his wistful looks (how much in vain!)",
  "To the deserted mansion, where no more",
  "The owner (gone to gayer scenes) resides,",
  "Who made even luxury, Virtue; while he gave",
  "The scatter'd crumbs to honest Poverty.--",
  "But, tho' the landscape be too oft deform'd",
  "By figures such as these, yet Peace is here,",
  "And o'er our vallies, cloath'd with springing corn,",
  "No hostile hoof shall trample, nor fierce flames",
  "Wither the wood's young verdure, ere it form",
  "Gradual the laughing May's luxuriant shade;",
  "For, by the rude sea guarded, we are safe,",
  "And feel not evils such as with deep sighs",
  "The Emigrants deplore, as, they recal",
  "The Summer past, when Nature seem'd to lose",
  "Her course in wild distemperature, and aid,",
  "With seasons all revers'd, destructive War.",
  "Shuddering, I view the pictures they have drawn",
  "Of desolated countries, where the ground,",
  "Stripp'd of its unripe produce, was thick strewn",
  "With various Death--the war-horse falling there",
  "By famine, and his rider by the sword.",
  "The moping clouds sail'd heavy charg'd with rain,",
  "And bursting o'er the mountains misty brow,",
  "Deluged, as with an inland sea, the vales 5 ;",
  "Where, thro' the sullen evening's lurid gloom,",
  "Rising, like columns of volcanic fire,",
  "The flames of burning villages illum'd",
  "The waste of water; and the wind, that howl'd",
  "Along its troubled surface, brought the groans",
  "Of plunder'd peasants, and the frantic shrieks",
  "Of mothers for their children; while the brave,",
  "To pity still alive, listen'd aghast",
  "To these dire echoes, hopeless to prevent",
  "The evils they beheld, or check the rage,",
  "Which ever, as the people of one land",
  "Meet in contention, fires the human heart",
  "With savage thirst of kindred blood, and makes",
  "Man lose his nature; rendering him more fierce",
  "Than the gaunt monsters of the howling waste.",
  "Oft have I heard the melancholy tale,",
  "Which, all their native gaiety forgot,",
  "These Exiles tell--How Hope impell'd them on,",
  "Reckless of tempest, hunger, or the sword,",
  "Till order'd to retreat, they knew not why,",
  "From all their flattering prospects, they became",
  "The prey of dark suspicion and regret 6 :",
  "Then, in despondence, sunk the unnerv'd arm",
  "Of gallant Loyalty--At every turn",
  "Shame and disgrace appear'd, and seem'd to mock",
  "Their scatter'd squadrons; which the warlike youth,",
  "Unable to endure, often implor'd,",
  "As the last act of friendship, from the hand",
  "Of some brave comrade, to receive the blow",
  "That freed the indignant spirit from its pain.",
  "To a wild mountain, whose bare summit hides",
  "Its broken eminence in clouds; whose steeps",
  "Are dark with woods; where the receding rocks",
  "Are worn by torrents of dissolving snow,",
  "A wretched Woman, pale and breathless, flies!",
  "And, gazing round her, listens to the sound",
  "Of hostile footsteps---- No! it dies away:",
  "Nor noise remains, but of the cataract,",
  "Or surly breeze of night, that mutters low",
  "Among the thickets, where she trembling seeks",
  "A temporary shelter--clasping close",
  "To her hard-heaving heart, her sleeping child,",
  "All she could rescue of the innocent groupe",
  "That yesterday surrounded her--Escap'd",
  "Almost by miracle! Fear, frantic Fear,",
  "Wing'd her weak feet: yet, half repentant now",
  "Her headlong haste, she wishes she had staid",
  "To die with those affrighted Fancy paints",
  "The lawless soldier's victims--Hark! again",
  "The driving tempest bears the cry of Death,",
  "And, with deep sudden thunder, the dread sound",
  "Of cannon vibrates on the tremulous earth;",
  "While, bursting in the air, the murderous bomb",
  "Glares o'er her mansion. Where the splinters fall,",
  "Like scatter'd comets, its destructive path",
  "Is mark'd by wreaths of flame!--Then, overwhelm'd",
  "Beneath accumulated horror, sinks",
  "The desolate mourner; yet, in Death itself,",
  "True to maternal tenderness, she tries",
  "To save the unconscious infant from the storm",
  "In which she perishes; and to protect",
  "This last dear object of her ruin'd hopes",
  "From prowling monsters, that from other hills,",
  "More inaccessible, and wilder wastes,",
  "Lur'd by the scent of slaughter, follow fierce",
  "Contending hosts, and to polluted fields",
  "Add dire increase of horrors--But alas!",
  "The Mother and the Infant perish both!--",
  "The feudal Chief, whose Gothic battlements",
  "Frown on the plain beneath, returning home",
  "From distant lands, alone and in disguise,",
  "Gains at the fall of night his Castle walls,",
  "But, at the vacant gate, no Porter sits",
  "To wait his Lord's admittance!--In the courts",
  "All is drear silence!--Guessing but too well",
  "The fatal truth, he shudders as he goes",
  "Thro' the mute hall; where, by the blunted light",
  "That the dim moon thro' painted casements lends,",
  "He sees that devastation has been there:",
  "Then, while each hideous image to his mind",
  "Rises terrific, o'er a bleeding corse",
  "Stumbling he falls; another interrupts",
  "His staggering feet--all, all who us'd to rush",
  "With joy to meet him--all his family",
  "Lie murder'd in his way!--And the day dawns",
  "On a wild raving Maniac, whom a fate",
  "So sudden and calamitous has robb'd",
  "Of reason; and who round his vacant walls",
  "Screams unregarded, and reproaches Heaven!--",
  "Such are thy dreadful trophies, savage War!",
  "And evils such as these, or yet more dire,",
  "Which the pain'd mind recoils from, all are thine--",
  "The purple Pestilence, that to the grave",
  "Sends whom the sword has spar'd, is thine; and thine",
  "The Widow's anguish and the Orphan's tears!--",
  "Woes such as these does Man inflict on Man;",
  "And by the closet murderers, whom we style",
  "Wise Politicians; are the schemes prepar'd,",
  "Which, to keep Europe's wavering balance even,",
  "Depopulate her kingdoms, and consign",
  "To tears and anguish half a bleeding world!--",
  "Oh! could the time return, when thoughts like these",
  "Spoil'd not that gay delight, which vernal Suns,",
  "Illuminating hills, and woods, and fields,",
  "Gave to my infant spirits--Memory come!",
  "And from distracting cares, that now deprive",
  "Such scenes of all their beauty, kindly bear",
  "My fancy to those hours of simple joy,",
  "When, on the banks of Arun, which I see",
  "Make its irriguous course thro' yonder meads,",
  "I play'd; unconscious then of future ill!",
  "There (where, from hollows fring'd with yellow broom,",
  "The birch with silver rind, and fairy leaf,",
  "Aslant the low stream trembles) I have stood,",
  "And meditated how to venture best",
  "Into the shallow current, to procure",
  "The willow herb of glowing purple spikes,",
  "Or flags, whose sword-like leaves conceal'd the tide,",
  "Startling the timid reed-bird from her nest,",
  "As with aquatic flowers I wove the wreath,",
  "Such as, collected by the shepherd girls,",
  "Deck in the villages the turfy shrine,",
  "And mark the arrival of propitious May.--",
  "How little dream'd I then the time would come,",
  "When the bright Sun of that delicious month",
  "Should, from disturb'd and artificial sleep,",
  "Awaken me to never-ending toil,",
  "To terror and to tears!--Attempting still,",
  "With feeble hands and cold desponding heart,",
  "To save my children from the o'erwhelming wrongs,",
  "That have for ten long years been heap'd on me!--",
  "The fearful spectres of chicane and fraud",
  "Have, Proteus like, still chang'd their hideous forms",
  "(As the Law lent its plausible disguise),",
  "Pursuing my faint steps; and I have seen",
  "Friendship's sweet bonds (which were so early form'd,)",
  "And once I fondly thought of amaranth",
  "Inwove with silver seven times tried) give way,",
  "And fail; as these green fan-like leaves of fern",
  "Will wither at the touch of Autumn's frost.",
  "Yet there are those , whose patient pity still",
  "Hears my long murmurs; who, unwearied, try",
  "With lenient hands to bind up every wound",
  "My wearied spirit feels, and bid me go",
  "\"Right onward 7 \"--a calm votary of the Nymph,",
  "Who, from her adamantine rock, points out",
  "To conscious rectitude the rugged path,",
  "That leads at length to Peace!--Ah! yes, my friends",
  "Peace will at last be mine; for in the Grave",
  "Is Peace--and pass a few short years, perchance",
  "A few short months, and all the various pain",
  "I now endure shall be forgotten there,",
  "And no memorial shall remain of me,",
  "Save in your bosoms; while even your regret",
  "Shall lose its poignancy, as ye reflect",
  "What complicated woes that grave conceals!",
  "But, if the little praise, that may await",
  "The Mother's efforts, should provoke the spleen",
  "Of Priest or Levite; and they then arraign",
  "The dust that cannot hear them; be it yours",
  "To vindicate my humble fame; to say,",
  "That, not in selfish sufferings absorb'd,",
  "\"I gave to misery all I had, my tears 8 .\"",
  "And if, where regulated sanctity",
  "Pours her long orisons to Heaven, my voice",
  "Was seldom heard, that yet my prayer was made",
  "To him who hears even silence; not in domes",
  "Of human architecture, fill'd with crowds,",
  "But on these hills, where boundless, yet distinct,",
  "Even as a map, beneath are spread the fields",
  "His bounty cloaths; divided here by woods,",
  "And there by commons rude, or winding brooks,",
  "While I might breathe the air perfum'd with flowers,",
  "Or the fresh odours of the mountain turf;",
  "And gaze on clouds above me, as they sail'd",
  "Majestic: or remark the reddening north,",
  "When bickering arrows of electric fire",
  "Flash on the evening sky--I made my prayer",
  "In unison with murmuring waves that now",
  "Swell with dark tempests, now are mild and blue,",
  "As the bright arch above; for all to me",
  "Declare omniscient goodness; nor need I",
  "Declamatory essays to incite",
  "My wonder or my praise, when every leaf",
  "That Spring unfolds, and every simple bud,",
  "More forcibly impresses on my heart",
  "His power and wisdom--Ah! while I adore",
  "That goodness, which design'd to all that lives",
  "Some taste of happiness, my soul is pain'd",
  "By the variety of woes that Man",
  "For Man creates--his blessings often turn'd",
  "To plagues and curses: Saint-like Piety,",
  "Misled by Superstition, has destroy'd",
  "More than Ambition; and the sacred flame",
  "Of Liberty becomes a raging fire,",
  "When Licence and Confusion bid it blaze.",
  "From thy high throne, above yon radiant stars,",
  "O Power Omnipotent! with mercy view",
  "This suffering globe, and cause thy creatures cease,",
  "With savage fangs, to tear her bleeding breast:",
  "Refrain that rage for power, that bids a Man,",
  "Himself a worm, desire unbounded rule",
  "O'er beings like himself: Teach the hard hearts",
  "Of rulers, that the poorest hind, who dies",
  "For their unrighteous quarrels, in thy sight",
  "Is equal to the imperious Lord, that leads",
  "His disciplin'd destroyers to the field.----",
  "May lovely Freedom, in her genuine charms,",
  "Aided by stern but equal Justice, drive",
  "From the ensanguin'd earth the hell-born fiends",
  "Of Pride, Oppression, Avarice, and Revenge,",
  "That ruin what thy mercy made so fair!",
  "Then shall these ill-starr'd wanderers, whose sad fate",
  "These desultory lines lament, regain",
  "Their native country; private vengeance then",
  "To public virtue yield; and the fierce feuds,",
  "That long have torn their desolated land,",
  "May (even as storms, that agitate the air,",
  "Drive noxious vapours from the blighted earth)",
  "Serve, all tremendous as they are, to fix",
  "The reign of Reason, Liberty, and Peace!",
  ""
]