module.exports = [
  "THE green roads that end in the forest",
  "Are strewn with white goose feathers this June,",
  "",
  "Like marks left behind by some one gone to the forest",
  "To show his track. But he has never come back.",
  "",
  "Down each green road a cottage looks at the forest.",
  "Round one the nettle towers; two are bathed in flowers.",
  "",
  "An old man along the green road to the forest",
  "Strays from one, from another a child alone.",
  "",
  "In the thicket bordering the forest,",
  "All day long a thrush twiddles his song.",
  "",
  "It is old, but the trees are young in the forest,",
  "All but one like a castle keep, in the middle deep.",
  "",
  "That oak saw the ages pass in the forest:",
  "They were a host, but their memories are lost,",
  "",
  "For the tree is dead: all things forget the forest",
  "Excepting perhaps me, when now I see",
  "",
  "The old man, the child, the goose feathers at the edge",
  "   of the forest,",
  "And hear all day long the thrush repeat his song.",
  ""
]