module.exports = [
  "Since I noo mwore do zee your feace,",
  "Up steairs or down below,",
  "I’ll zit me in the lwonesome pleace,",
  "Where flat-bough’d beech do grow;",
  "Below the beeches’ bough, my love,",
  "Where you did never come,",
  "An’ I don’t look to meet ye now,",
  "As I do look at hwome.",
  "",
  "Since you noo mwore be at my zide,",
  "In walks in zummer het,",
  "I’ll goo alwone where mist do ride,",
  "Drough trees a-drippen wet;",
  "Below the rain-wet bough, my love,",
  "Where you did never come,",
  "An’ I don’t grieve to miss ye now,",
  "As I do grieve at hwome.",
  "",
  "Since now bezide my dinner-bwoard",
  "Your vaice do never sound,",
  "I’ll eat the bit I can avword,",
  "A-vield upon the ground;",
  "Below the darksome bough, my love,",
  "Where you did never dine,",
  "An’ I don’t grieve to miss ye now,",
  "As I at hwome do pine.",
  "",
  "Since I do miss your vaice an’ feace",
  "In prayer at eventide,",
  "I’ll pray wi’ woone sad vaice vor greace",
  "To goo where you do bide;",
  "Above the tree an’ bough, my love,",
  "Where you be gone avore,",
  "An’ be a-waiten vor me now,",
  "To come vor evermwore.",
  ""
]