module.exports = [
  "THE glory of the beauty of the morning,--",
  "The cuckoo crying over the untouched dew;",
  "The blackbird that has found it, and the dove",
  "That tempts me on to something sweeter than love;",
  "White clouds ranged even and fair as new-mown hay;",
  "The heat, the stir, the sublime vacancy",
  "Of sky and meadow and forest and my own heart:--",
  "The glory invites me, yet it leaves me scorning",
  "All I can ever do, all I can be,",
  "Beside the lovely of motion, shape, and hue,",
  "The happiness I fancy fit to dwell",
  "In beauty's presence. Shall I now this day",
  "Begin to seek as far as heaven, as hell,",
  "Wisdom or strength to match this beauty, start",
  "And tread the pale dust pitted with small dark drops,",
  "In hope to find whatever it is I seek,",
  "Hearkening to short-lived happy-seeming things",
  "That we know naught of, in the hazel copse?",
  "Or must I be content with discontent",
  "As larks and swallows are perhaps with wings?",
  "And shall I ask at the day's end once more",
  "What beauty is, and what I can have meant",
  "By happiness? And shall I let all go,",
  "Glad, weary, or both? Or shall I perhaps know",
  "That I was happy oft and oft before,",
  "Awhile forgetting how I am fast pent,",
  "How dreary-swift, with naught to travel to,",
  "Is Time? I cannot bite the day to the core.",
  ""
]