module.exports = [
  "'Twas on the 22nd of March, in the year 1885,",
  "That the Arabs rushed like a mountain torrent in full drive,",
  "And quickly attacked General M'Neill's transport-zereba,",
  "But in a short time they were forced to withdraw.",
  "",
  "And in the suddenness of surprise the men were carried away,",
  "Also camels, mules, and horses were thrown into wild disarray,",
  "By thousands of the Arabs that in ambush lay,",
  "But our brave British heroes held the enemy at bay.",
  "",
  "There was a multitude of camels heaped upon one another,",
  "Kicking and screaming, while many of them did smother,",
  "Owing to the heavy pressure of the entangled mass,",
  "That were tramping o'er one another as they lay on the grass.",
  "",
  "The scene was indescribable, and sickening to behold,",
  "To see the mass of innocent brutes lying stiff and cold,",
  "And the moaning cries of them were pitiful to hear,",
  "Likewise the cries of the dying men that lay wounded in the rear.",
  "",
  "Then General McNeill ordered his men to form in solid square,",
  "Whilst deafening shouts and shrieks of animals did tend the air,",
  "And the rush of stampeded camels made a fearful din,",
  "While the Arabs they did yell, and fiendishly did grin.",
  "",
  "Then the gallant Marines formed the east side of the square,",
  "While clouds of dust and smoke did darken the air,",
  "And on the west side the Berkshire were engaged in the fight,",
  "Firing steadily and cooly with all their might.",
  "",
  "Still camp followers were carried along by the huge animal mass,",
  "And along the face of the zereba 'twas difficult to pass,",
  "Because the mass of brutes swept on in wild dismay,",
  "Which caused the troops to be thrown into disorderly array.",
  "",
  "Then Indians and Bluejackets were all mixed together back to back,",
  "And for half-an-hour the fire and din didn't slack;",
  "And none but steady troops could have stood that fearful shock,",
  "Because against overwhelming numbers they stood as firm as a rock.",
  "",
  "The Arabs crept among the legs of the animals without any dread,",
  "But by the British bullets many were killed dead,",
  "And left dead on the field and weltering in their gore,",
  "Whilst the dying moans of the camels made a hideous roar.",
  "",
  "Then General McNeill to his men did say,",
  "Forward! my lads, and keep them at bay!",
  "Come, make ready, my men, and stand to your arms,",
  "And don't be afraid of war's alarms",
  "",
  "So forward! and charge them in front and rear,",
  "And remember you are fighting for your Queen and country dear,",
  "Therefore, charge them with your bayonets, left and right,",
  "And we'll soon put this rebel horde to flight.",
  "",
  "Then forward at the bayonet-charge they did rush,",
  "And the rebel horde they soon did crush;",
  "And by the charge of the bayonet they kept them at bay,",
  "And in confusion and terror they all fled away.",
  "",
  "The Marines held their own while engaged hand-to-hand,",
  "And the courage they displayed was really very grand;",
  "But it would be unfair to praise one corps more than another,",
  "Because each man fought as if he'd been avenging the death of a brother.",
  "",
  "The Berkshire men and the Naval Brigade fought with might and main,",
  "And, thank God! the British have defeated the Arabs again,",
  "And have added fresh laurels to their name,",
  "Which will be enrolled in the book of fame.",
  "'Tis lamentable to think of the horrors of war,",
  "That men must leave their homes and go abroad afar,",
  "To fight for their Queen and country in a foreign land,",
  "Beneath the whirlwind's drifting scorching sand.",
  "",
  "But whatsoever God wills must come to pass,",
  "The fall of a sparrow, or a tiny blade of grass;",
  "Also, man must fall at home by His command,",
  "Just equally the same as in a foreign land.",
  ""
]