module.exports = [
  "Oh King of grief! (a title strange, yet true,",
  "To thee of all kings only due)",
  "Oh King of wounds! how shall I grieve for thee,",
  "Who in all grief preventest me?",
  "Shall I weep blood? why thou has wept such store",
  "That all thy body was one door.",
  "Shall I be scourged, flouted, boxed, sold?",
  "'Tis but to tell the tale is told.",
  "'My God, my God, why dost thou part from me? '",
  "Was such a grief as cannot be.",
  "Shall I then sing, skipping, thy doleful story,",
  "And side with thy triumphant glory?",
  "Shall thy strokes be my stroking? thorns, my flower?",
  "Thy rod, my posy? cross, my bower?",
  "But how then shall I imitate thee, and",
  "Copy thy fair, though bloody hand?",
  "Surely I will revenge me on thy love,",
  "And try who shall victorious prove.",
  "If thou dost give me wealth, I will restore",
  "All back unto thee by the poor.",
  "If thou dost give me honour, men shall see,",
  "The honour doth belong to thee.",
  "I will not marry; or, if she be mine,",
  "She and her children shall be thine.",
  "My bosom friend, if he blaspheme thy name,",
  "I will tear thence his love and fame.",
  "One half of me being gone, the rest I give",
  "Unto some Chapel, die or live.",
  "As for thy passion - But of that anon,",
  "When with the other I have done.",
  "For thy predestination I'll contrive,",
  "That three years hence, if I survive,",
  "I'll build a spittle, or mend common ways,",
  "But mend mine own without delays.",
  "Then I will use the works of thy creation,",
  "As if I us'd them but for fashion.",
  "The world and I will quarrel; and the year",
  "Shall not perceive, that I am here.",
  "My music shall find thee, and ev'ry string",
  "Shall have his attribute to sing;",
  "That all together may accord in thee,",
  "And prove one God, one harmony.",
  "If thou shalt give me wit, it shall appear;",
  "If thou hast giv'n it me, 'tis here.",
  "Nay, I will read thy book, and never move",
  "Till I have found therein thy love;",
  "Thy art of love, which I'll turn back on thee,",
  "O my dear Saviour, Victory!",
  "Then for thy passion - I will do for that -",
  "Alas, my God, I know not what.",
  ""
]