module.exports = [
  "The \"good old times\"--all times when old are good--",
  "Are gone; the present might be if they would;",
  "Great things have been, and are, and greater still",
  "Want little of mere mortals but their will:",
  "A wider space, a greener field, is given",
  "To those who play their \"tricks before high heaven.\"",
  "I know not if the angels weep, but men",
  "Have wept enough--for what?--to weep again!",
  "",
  "All is exploded--be it good or bad.",
  "Reader! remember when thou wert a lad,",
  "Then Pitt was all; or, if not all, so much,",
  "His very rival almost deemed him such.",
  "We--we have seen the intellectual race",
  "Of giants stand, like Titans, face to face--",
  "Athos and Ida, with a dashing sea",
  "Of eloquence between, which flowed all free,",
  "As the deep billows of the Ægean roar",
  "Betwixt the Hellenic and the Phrygian shore.",
  "But where are they--the rivals! a few feet",
  "Of sullen earth divide each winding sheet.",
  "How peaceful and how powerful is the grave,",
  "Which hushes all! a calm, unstormy wave,",
  "Which oversweeps the World. The theme is old",
  "Of \"Dust to Dust,\" but half its tale untold:",
  "Time tempers not its terrors--still the worm",
  "Winds its cold folds, the tomb preserves its form,",
  "Varied above, but still alike below;",
  "The urn may shine--the ashes will not glow--",
  "Though Cleopatra's mummy cross the sea",
  "O'er which from empire she lured Anthony;",
  "Though Alexander's urn a show be grown",
  "On shores he wept to conquer, though unknown--",
  "How vain, how worse than vain, at length appear",
  "The madman's wish, the Macedonian's tear!",
  "He wept for worlds to conquer--half the earth",
  "Knows not his name, or but his death, and birth,",
  "And desolation; while his native Greece",
  "Hath all of desolation, save its peace.",
  "He \"wept for worlds to conquer!\" he who ne'er",
  "Conceived the Globe, he panted not to spare!",
  "With even the busy Northern Isle unknown,",
  "Which holds his urn--and never knew his throne.",
  "",
  "But where is he, the modern, mightier far,",
  "Who, born no king, made monarchs draw his car;",
  "The new Sesostris, whose unharnessed kings,",
  "Freed from the bit, believe themselves with wings,",
  "And spurn the dust o'er which they crawled of late,",
  "Chained to the chariot of the Chieftain's state?",
  "Yes! where is he, \"the champion and the child\"",
  "Of all that's great or little--wise or wild;",
  "Whose game was Empire, and whose stakes were thrones;",
  "Whose table Earth--whose dice were human bones?",
  "Behold the grand result in yon lone Isle,",
  "And, as thy nature urges--weep or smile.",
  "Sigh to behold the Eagle's lofty rage",
  "Reduced to nibble at his narrow cage;",
  "Smile to survey the queller of the nations",
  "Now daily squabbling o'er disputed rations;",
  "Weep to perceive him mourning, as he dines,",
  "O'er curtailed dishes and o'er stinted wines;",
  "O'er petty quarrels upon petty things.",
  "Is this the Man who scourged or feasted kings?",
  "Behold the scales in which his fortune hangs,",
  "A surgeon's statement, and an earl's harangues!",
  "A bust delayed,--a book refused, can shake",
  "The sleep of Him who kept the world awake.",
  "Is this indeed the tamer of the Great,",
  "Now slave of all could tease or irritate--",
  "The paltry gaoler and the prying spy,",
  "The staring stranger with his note-book nigh?",
  "Plunged in a dungeon, he had still been great;",
  "How low, how little was this middle state,",
  "Between a prison and a palace, where",
  "How few could feel for what he had to bear!",
  "Vain his complaint,--My Lord presents his bill,",
  "His food and wine were doled out duly still;",
  "Vain was his sickness, never was a clime",
  "So free from homicide--to doubt's crime;",
  "And the stiff surgeon, who maintained his cause,",
  "Hath lost his place, and gained the world's applause.",
  "But smile--though all the pangs of brain and heart",
  "Disdain, defy, the tardy aid of art;",
  "Though, save the few fond friends and imaged face",
  "Of that fair boy his Sire shall ne'er embrace,",
  "None stand by his low bed--though even the mind",
  "Be wavering, which long awed and awes mankind:",
  "Smile--for the fettered Eagle breaks his chain,",
  "And higher Worlds than this are his again.",
  "",
  "How, if that soaring Spirit still retain",
  "A conscious twilight of his blazing reign,",
  "How must he smile, on looking down, to see",
  "The little that he was and sought to be!",
  "What though his Name a wider empire found",
  "Than his Ambition, though with scarce a bound;",
  "Though first in glory, deepest in reverse,",
  "He tasted Empire's blessings and its curse;",
  "Though kings, rejoicing in their late escape",
  "From chains, would gladly be _their_ Tyrant's ape;",
  "How must he smile, and turn to yon lone grave,",
  "The proudest Sea-mark that o'ertops the wave!",
  "What though his gaoler, duteous to the last,",
  "Scarce deemed the coffin's lead could keep him fast,",
  "Refusing one poor line along the lid,",
  "To date the birth and death of all it hid;",
  "That name shall hallow the ignoble shore,",
  "A talisman to all save him who bore:",
  "The fleets that sweep before the eastern blast",
  "Shall hear their sea-boys hail it from the mast;",
  "When Victory's Gallic column shall but rise,",
  "Like Pompey's pillar, in a desert's skies,",
  "The rocky Isle that holds or held his dust,",
  "Shall crown the Atlantic like the Hero's bust,",
  "And mighty Nature o'er his obsequies",
  "Do more than niggard Envy still denies.",
  "But what are these to him? Can Glory's lust",
  "Touch the freed spirit or the fettered dust?",
  "Small care hath he of what his tomb consists;",
  "Nought if he sleeps--nor more if he exists:",
  "Alike the better-seeing Shade will smile",
  "On the rude cavern of the rocky isle,",
  "As if his ashes found their latest home",
  "In Rome's Pantheon or Gaul's mimic dome.",
  "He wants not this; but France shall feel the want",
  "Of this last consolation, though so scant:",
  "Her Honour--Fame--and Faith demand his bones,",
  "To rear above a Pyramid of thrones;",
  "Or carried onward in the battle's van,",
  "To form, like Guesclin's dust, her Talisman.",
  "But be it as it is--the time may come",
  "His name shall beat the alarm, like Ziska's drum.",
  "",
  "Oh Heaven! of which he was in power a feature;",
  "Oh Earth! of which he was a noble creature;",
  "Thou Isle! to be remembered long and well,",
  "That saw'st the unfledged eaglet chip his shell!",
  "Ye Alps which viewed him in his dawning flights",
  "Hover, the Victor of a hundred fights!",
  "Thou Rome, who saw'st thy Cæsar's deeds outdone!",
  "Alas! why passed he too the Rubicon--",
  "The Rubicon of Man's awakened rights,",
  "To herd with vulgar kings and parasites?",
  "Egypt! from whose all dateless tombs arose",
  "Forgotten Pharaohs from their long repose,",
  "And shook within their pyramids to hear",
  "A new Cambyses thundering in their ear;",
  "While the dark shades of Forty Ages stood",
  "Like startled giants by Nile's famous flood;",
  "Or from the Pyramid's tall pinnacle",
  "Beheld the desert peopled, as from hell,",
  "With clashing hosts, who strewed the barren sand,",
  "To re-manure the uncultivated land!",
  "Spain! which, a moment mindless of the Cid,",
  "Beheld his banner flouting thy Madrid!",
  "Austria! which saw thy twice-ta'en capital",
  "Twice spared to be the traitress of his fall!",
  "Ye race of Frederic!--Frederics but in name",
  "And falsehood--heirs to all except his fame:",
  "Who, crushed at Jena, crouched at Berlin, fell",
  "First, and but rose to follow! Ye who dwell",
  "Where Kosciusko dwelt, remembering yet",
  "The unpaid amount of Catherine's bloody debt!",
  "Poland! o'er which the avenging Angel past,",
  "But left thee as he found thee, still a waste,",
  "Forgetting all thy still enduring claim,",
  "Thy lotted people and extinguished name,",
  "Thy sigh for freedom, thy long-flowing tear,",
  "That sound that crashes in the tyrant's ear--",
  "Kosciusko! On--on--on--the thirst of War",
  "Gasps for the gore of serfs and of their Czar.",
  "The half barbaric Moscow's minarets",
  "Gleam in the sun, but 'tis a sun that sets!",
  "Moscow! thou limit of his long career,",
  "For which rude Charles had wept his frozen tear",
  "To see in vain--_he_ saw thee--how? with spire",
  "And palace fuel to one common fire.",
  "To this the soldier lent his kindling match,",
  "To this the peasant gave his cottage thatch,",
  "To this the merchant flung his hoarded store,",
  "The prince his hall--and Moscow was no more!",
  "Sublimest of volcanoes! Etna's flame",
  "Pales before thine, and quenchless Hecla's tame;",
  "Vesuvius shows his blaze, an usual sight",
  "For gaping tourists, from his hackneyed height:",
  "Thou stand'st alone unrivalled, till the Fire",
  "To come, in which all empires shall expire!",
  "",
  "  Thou other Element! as strong and stern,",
  "To teach a lesson conquerors will not learn!--",
  "Whose icy wing flapped o'er the faltering foe,",
  "Till fell a hero with each flake of snow;",
  "How did thy numbing beak and silent fang,",
  "Pierce, till hosts perished with a single pang!",
  "In vain shall Seine look up along his banks",
  "For the gay thousands of his dashing ranks!",
  "In vain shall France recall beneath her vines",
  "Her Youth--their blood flows faster than her wines;",
  "Or stagnant in their human ice remains",
  "In frozen mummies on the Polar plains.",
  "In vain will Italy's broad sun awaken",
  "Her offspring chilled; its beams are now forsaken.",
  "Of all the trophies gathered from the war,",
  "What shall return? the Conqueror's broken car!",
  "The Conqueror's yet unbroken heart! Again",
  "The horn of Roland sounds, and not in vain.",
  "Lutzen, where fell the Swede of victory,",
  "Beholds him conquer, but, alas! not die:",
  "Dresden surveys three despots fly once more",
  "Before their sovereign,--sovereign as before;",
  "But there exhausted Fortune quits the field,",
  "And Leipsic's treason bids the unvanquished yield;",
  "The Saxon jackal leaves the lion's side",
  "To turn the bear's, and wolf's, and fox's guide;",
  "And backward to the den of his despair",
  "The forest monarch shrinks, but finds no lair!",
  "",
  "  Oh ye! and each, and all! Oh France! who found",
  "Thy long fair fields ploughed up as hostile ground,",
  "Disputed foot by foot, till Treason, still",
  "His only victor, from Montmartre's hill",
  "Looked down o'er trampled Paris! and thou Isle,",
  "Which seest Etruria from thy ramparts smile,",
  "Thou momentary shelter of his pride,",
  "Till wooed by danger, his yet weeping bride!",
  "Oh, France! retaken by a single march,",
  "Whose path was through one long triumphal arch!",
  "Oh bloody and most bootless Waterloo!",
  "Which proves how fools may have their fortune too,",
  "Won half by blunder, half by treachery:",
  "Oh dull Saint Helen! with thy gaoler nigh--",
  "Hear! hear Prometheus from his rock appeal",
  "To Earth,--Air,--Ocean,--all that felt or feel",
  "His power and glory, all who yet shall hear",
  "A name eternal as the rolling year;",
  "He teaches them the lesson taught so long,",
  "So oft, so vainly--learn to do no wrong!",
  "A single step into the right had made",
  "This man the Washington of worlds betrayed:",
  "A single step into the wrong has given",
  "His name a doubt to all the winds of heaven;",
  "The reed of Fortune, and of thrones the rod,",
  "Of Fame the Moloch or the demigod;",
  "His country's Cæsar, Europe's Hannibal,",
  "Without their decent dignity of fall.",
  "Yet Vanity herself had better taught",
  "A surer path even to the fame he sought,",
  "By pointing out on History's fruitless page",
  "Ten thousand conquerors for a single sage.",
  "While Franklin's quiet memory climbs to Heaven,",
  "Calming the lightning which he thence hath riven,",
  "Or drawing from the no less kindled earth",
  "Freedom and peace to that which boasts his birth;",
  "While Washington's a watchword, such as ne'er",
  "Shall sink while there's an echo left to air:",
  "While even the Spaniard's thirst of gold and war",
  "Forgets Pizarro to shout Bolivar!",
  "Alas! why must the same Atlantic wave",
  "Which wafted freedom gird a tyrant's grave--",
  "The king of kings, and yet of slaves the slave,",
  "Who burst the chains of millions to renew",
  "The very fetters which his arm broke through,",
  "And crushed the rights of Europe and his own,",
  "To flit between a dungeon and a throne?",
  "",
  "But 'twill not be--the spark's awakened--lo!",
  "The swarthy Spaniard feels his former glow;",
  "The same high spirit which beat back the Moor",
  "Through eight long ages of alternate gore",
  "Revives--and where? in that avenging clime",
  "Where Spain was once synonymous with crime,",
  "Where Cortes' and Pizarro's banner flew,",
  "The infant world redeems her name of \"_New_.\"",
  "'Tis the _old_ aspiration breathed afresh,",
  "To kindle souls within degraded flesh,",
  "Such as repulsed the Persian from the shore",
  "Where Greece _was_--No! she still is Greece once more.",
  "One common cause makes myriads of one breast,",
  "Slaves of the East, or helots of the West:",
  "On Andes' and on Athos' peaks unfurled,",
  "The self-same standard streams o'er either world:",
  "The Athenian wears again Harmodius' sword;",
  "The Chili chief abjures his foreign lord;",
  "The Spartan knows himself once more a Greek,",
  "Young Freedom plumes the crest of each cacique;",
  "Debating despots, hemmed on either shore,",
  "Shrink vainly from the roused Atlantic's roar;",
  "Through Calpe's strait the rolling tides advance,",
  "Sweep slightly by the half-tamed land of France,",
  "Dash o'er the old Spaniard's cradle, and would fain",
  "Unite Ausonia to the mighty main:",
  "But driven from thence awhile, yet not for aye,",
  "Break o'er th' Ægean, mindful of the day",
  "Of Salamis!--there, there the waves arise,",
  "Not to be lulled by tyrant victories.",
  "Lone, lost, abandoned in their utmost need",
  "By Christians, unto whom they gave their creed,",
  "The desolated lands, the ravaged isle,",
  "The fostered feud encouraged to beguile,",
  "The aid evaded, and the cold delay,",
  "Prolonged but in the hope to make a prey;--",
  "These, these shall tell the tale, and Greece can show",
  "The false friend worse than the infuriate foe.",
  "But this is well: Greeks only should free Greece,",
  "Not the barbarian, with his masque of peace.",
  "How should the Autocrat of bondage be",
  "The king of serfs, and set the nations free?",
  "Better still serve the haughty Mussulman,",
  "Than swell the Cossaque's prowling caravan;",
  "Better still toil for masters, than await,",
  "The slave of slaves, before a Russian gate,--",
  "Numbered by hordes, a human capital,",
  "A live estate, existing but for thrall,",
  "Lotted by thousands, as a meet reward",
  "For the first courtier in the Czar's regard;",
  "While their immediate owner never tastes",
  "His sleep, _sans_ dreaming of Siberia's wastes:",
  "Better succumb even to their own despair,",
  "And drive the Camel--than purvey the Bear.",
  "",
  "But not alone within the hoariest clime",
  "Where Freedom dates her birth with that of Time,",
  "And not alone where, plunged in night, a crowd",
  "Of Incas darken to a dubious cloud,",
  "The dawn revives: renowned, romantic Spain",
  "Holds back the invader from her soil again.",
  "Not now the Roman tribe nor Punic horde",
  "Demands her fields as lists to prove the sword;",
  "Not now the Vandal or the Visigoth",
  "Pollute the plains, alike abhorring both;",
  "Nor old Pelayo on his mountain rears",
  "The warlike fathers of a thousand years.",
  "That seed is sown and reaped, as oft the Moor",
  "Sighs to remember on his dusky shore.",
  "Long in the peasant's song or poet's page",
  "Has dwelt the memory of Abencerrage;",
  "The Zegri, and the captive victors, flung",
  "Back to the barbarous realm from whence they sprung.",
  "But these are gone--their faith, their swords, their sway,",
  "Yet left more anti-christian foes than they;",
  "The bigot monarch, and the butcher priest,",
  "The Inquisition, with her burning feast,",
  "The Faith's red \"Auto,\" fed with human fuel,",
  "While sate the catholic Moloch, calmly cruel,",
  "Enjoying, with inexorable eye,",
  "That fiery festival of Agony!",
  "The stern or feeble sovereign, one or both",
  "By turns; the haughtiness whose pride was sloth;",
  "The long degenerate noble; the debased",
  "Hidalgo, and the peasant less disgraced,",
  "But more degraded; the unpeopled realm;",
  "The once proud navy which forgot the helm;",
  "The once impervious phalanx disarrayed;",
  "The idle forge that formed Toledo's blade;",
  "The foreign wealth that flowed on every shore,",
  "Save hers who earned it with the native's gore;",
  "The very language which might vie with Rome's,",
  "And once was known to nations like their homes,",
  "Neglected or forgotten:--such _was_ Spain;",
  "But such she is not, nor shall be again.",
  "These worst, these _home_ invaders, felt and feel",
  "The new Numantine soul of old Castile,",
  "Up! up again! undaunted Tauridor!",
  "The bull of Phalaris renews his roar;",
  "Mount, chivalrous Hidalgo! not in vain",
  "Revive the cry--\"Iago! and close Spain!\"",
  "Yes, close her with your arméd bosoms round,",
  "And form the barrier which Napoleon found,--",
  "The exterminating war, the desert plain,",
  "The streets without a tenant, save the slain;",
  "The wild Sierra, with its wilder troop",
  "Of vulture-plumed Guerrillas, on the stoop",
  "For their incessant prey; the desperate wall",
  "Of Saragossa, mightiest in her fall;",
  "The Man nerved to a spirit, and the Maid",
  "Waving her more than Amazonian blade;",
  "The knife of Arragon, Toledo's steel;",
  "The famous lance of chivalrous Castile;",
  "The unerring rifle of the Catalan;",
  "The Andalusian courser in the van;",
  "The torch to make a Moscow of Madrid;",
  "And in each heart the spirit of the Cid:--",
  "Such have been, such shall be, such are. Advance,",
  "And win--not Spain! but thine own freedom, France!",
  "",
  "But lo! a Congress! What! that hallowed name",
  "Which freed the Atlantic! May we hope the same",
  "For outworn Europe? With the sound arise,",
  "Like Samuel's shade to Saul's monarchic eyes,",
  "The prophets of young Freedom, summoned far",
  "From climes of Washington and Bolivar;",
  "Henry, the forest-born Demosthenes,",
  "Whose thunder shook the Philip of the seas;",
  "And stoic Franklin's energetic shade,",
  "Robed in the lightnings which his hand allayed;",
  "And Washington, the tyrant-tamer, wake,",
  "To bid us blush for these old chains, or break.",
  "But _who_ compose this Senate of the few",
  "That should redeem the many? _Who_ renew",
  "This consecrated name, till now assigned",
  "To councils held to benefit mankind?",
  "Who now assemble at the holy call?",
  "The blest Alliance, which says three are all!",
  "An earthly Trinity! which wears the shape",
  "Of Heaven's, as man is mimicked by the ape.",
  "A pious Unity! in purpose one--",
  "To melt three fools to a Napoleon.",
  "Why, Egypt's Gods were rational to these;",
  "Their dogs and oxen knew their own degrees,",
  "And, quiet in their kennel or their shed,",
  "Cared little, so that they were duly fed;",
  "But these, more hungry, must have something more--",
  "The power to bark and bite, to toss and gore.",
  "Ah, how much happier were good Æsop's frogs",
  "Than we! for ours are animated logs,",
  "With ponderous malice swaying to and fro,",
  "And crushing nations with a stupid blow;",
  "All dully anxious to leave little work",
  "Unto the revolutionary stork.",
  "",
  "Thrice blest Verona! since the holy three",
  "With their imperial presence shine on thee!",
  "Honoured by them, thy treacherous site forgets",
  "The vaunted tomb of \"all the Capulets!\"",
  "Thy Scaligers--for what was \"Dog the Great,\"",
  "\"Can Grande,\" (which I venture to translate,)",
  "To these sublimer pugs? Thy poet too,",
  "Catullus, whose old laurels yield to new;",
  "Thine amphitheatre, where Romans sate;",
  "And Dante's exile sheltered by thy gate;",
  "Thy good old man, whose world was all within",
  "Thy wall, nor knew the country held him in;",
  "Would that the royal guests it girds about",
  "Were so far like, as never to get out!",
  "Aye, shout! inscribe! rear monuments of shame,",
  "To tell Oppression that the world is tame!",
  "Crowd to the theatre with loyal rage,",
  "The comedy is not upon the stage;",
  "The show is rich in ribandry and stars,",
  "Then gaze upon it through thy dungeon bars;",
  "Clap thy permitted palms, kind Italy,",
  "For thus much still thy fettered hands are free!",
  "",
  "Resplendent sight! Behold the coxcomb Czar,",
  "The Autocrat of waltzes and of war!",
  "As eager for a plaudit as a realm,",
  "And just as fit for flirting as the helm;",
  "A Calmuck beauty with a Cossack wit,",
  "And generous spirit, when 'tis not frost-bit;",
  "Now half dissolving to a liberal thaw,",
  "But hardened back whene'er the morning's raw;",
  "With no objection to true Liberty,",
  "Except that it would make the nations free.",
  "How well the imperial dandy prates of peace!",
  "How fain, if Greeks would be his slaves, free Greece!",
  "How nobly gave he back the Poles their Diet,",
  "Then told pugnacious Poland to be quiet!",
  "How kindly would he send the mild Ukraine,",
  "With all her pleasant Pulks, to lecture Spain!",
  "How royally show off in proud Madrid",
  "His goodly person, from the South long hid!",
  "A blessing cheaply purchased, the world knows,",
  "By having Muscovites for friends or foes.",
  "Proceed, thou namesake of great Philip's son!",
  "La Harpe, thine Aristotle, beckons on;",
  "And that which Scythia was to him of yore",
  "Find with thy Scythians on Iberia's shore.",
  "Yet think upon, thou somewhat agéd youth,",
  "Thy predecessor on the banks of Pruth;",
  "Thou hast to aid thee, should his lot be thine,",
  "Many an old woman, but not Catherine.",
  "Spain, too, hath rocks, and rivers, and defiles--",
  "The Bear may rush into the Lion's toils.",
  "Fatal to Goths are Xeres' sunny fields;",
  "Think'st thou to thee Napoleon's victor yields?",
  "Better reclaim thy deserts, turn thy swords",
  "To ploughshares, shave and wash thy Bashkir hordes,",
  "Redeem thy realms from slavery and the knout,",
  "Than follow headlong in the fatal route,",
  "To infest the clime whose skies and laws are pure",
  "With thy foul legions. Spain wants no manure:",
  "Her soil is fertile, but she feeds no foe:",
  "Her vultures, too, were gorged not long ago;",
  "And wouldst thou furnish them with fresher prey?",
  "Alas! thou wilt not conquer, but purvey.",
  "I am Diogenes, though Russ and Hun",
  "Stand between mine and many a myriad's sun;",
  "But were I not Diogenes, I'd wander",
  "Rather a worm than _such_ an Alexander!",
  "Be slaves who will, the cynic shall be free;",
  "His tub hath tougher walls than Sinopè:",
  "Still will he hold his lantern up to scan",
  "The face of monarchs for an \"honest man.\"",
  "",
  "And what doth Gaul, the all-prolific land",
  "Of _ne plus ultra_ ultras and their band",
  "Of mercenaries? and her noisy chambers",
  "And tribune, which each orator first clambers",
  "Before he finds a voice, and when 'tis found,",
  "Hears \"the lie\" echo for his answer round?",
  "Our British Commons sometimes deign to \"hear!\"",
  "A Gallic senate hath more tongue than ear;",
  "Even Constant, their sole master of debate,",
  "Must fight next day his speech to vindicate.",
  "But this costs little to true Franks, who'd rather",
  "Combat than listen, were it to their father.",
  "What is the simple standing of a shot,",
  "To listening long, and interrupting not?",
  "Though this was not the method of old Rome,",
  "When Tully fulmined o'er each vocal dome,",
  "Demosthenes has sanctioned the transaction,",
  "In saying eloquence meant \"Action, action!\"",
  "",
  "But where's the monarch? hath he dined? or yet",
  "Groans beneath indigestion's heavy debt?",
  "Have revolutionary patés risen,",
  "And turned the royal entrails to a prison?",
  "Have discontented movements stirred the troops?",
  "Or have _no_ movements followed traitorous soups?",
  "Have Carbonaro cooks not carbonadoed",
  "Each course enough? or doctors dire dissuaded",
  "Repletion? Ah! in thy dejected looks",
  "I read all France's treason in her cooks!",
  "Good classic Louis! is it, canst thou say,",
  "Desirable to be the \"Desiré?\"",
  "Why wouldst thou leave calm Hartwell's green abode,",
  "Apician table, and Horatian ode,",
  "To rule a people who will not be ruled,",
  "And love much rather to be scourged than schooled?",
  "Ah! thine was not the temper or the taste",
  "For thrones; the table sees thee better placed:",
  "A mild Epicurean, formed, at best,",
  "To be a kind host and as good a guest,",
  "To talk of Letters, and to know by heart",
  "One _half_ the Poet's, _all_ the Gourmand's art;",
  "A scholar always, now and then a wit,",
  "And gentle when Digestion may permit;--",
  "But not to govern lands enslaved or free;",
  "The gout was martyrdom enough for thee.",
  "",
  "Shall noble Albion pass without a phrase",
  "From a bold Briton in her wonted praise?",
  "\"Arts--arms--and George--and glory--and the Isles,",
  "And happy Britain, wealth, and Freedom's smiles,",
  "White cliffs, that held invasion far aloof,",
  "Contented subjects, all alike tax-proof,",
  "Proud Wellington, with eagle beak so curled,",
  "That nose, the hook where he suspends the world!",
  "And Waterloo, and trade, and----(hush! not yet",
  "A syllable of imposts or of debt)----",
  "And ne'er (enough) lamented Castlereagh,",
  "Whose penknife slit a goose-quill t'other day--",
  "And, 'pilots who have weathered every storm'--",
  "(But, no, not even for rhyme's sake, name Reform).\"",
  "These are the themes thus sung so oft before,",
  "Methinks we need not sing them any more;",
  "Found in so many volumes far and near,",
  "There's no occasion you should find them here.",
  "Yet something may remain perchance to chime",
  "With reason, and, what's stranger still, with rhyme.",
  "Even this thy genius, Canning! may permit,",
  "Who, bred a statesman, still wast born a wit,",
  "And never, even in that dull House, couldst tame",
  "To unleavened prose thine own poetic flame;",
  "Our last, our best, our only orator,",
  "Even I can praise thee--Tories do no more:",
  "Nay, not so much;--they hate thee, man, because",
  "Thy Spirit less upholds them than it awes.",
  "The hounds will gather to their huntsman's hollo,",
  "And where he leads the duteous pack will follow;",
  "But not for love mistake their yelling cry;",
  "Their yelp for game is not an eulogy;",
  "Less faithful far than the four-footed pack,",
  "A dubious scent would lure the bipeds back.",
  "Thy saddle-girths are not yet quite secure,",
  "Nor royal stallion's feet extremely sure;",
  "The unwieldy old white horse is apt at last",
  "To stumble, kick--and now and then stick fast",
  "With his great Self and Rider in the mud;",
  "But what of that? the animal shows blood.",
  "",
  "Alas, the Country! how shall tongue or pen",
  "Bewail her now _un_country gentlemen?",
  "The last to bid the cry of warfare cease,",
  "The first to make a malady of peace.",
  "For what were all these country patriots born?",
  "To hunt--and vote--and raise the price of corn?",
  "But corn, like every mortal thing, must fall,",
  "Kings--Conquerors--and markets most of all.",
  "And must ye fall with every ear of grain?",
  "Why would you trouble Buonaparté's reign?",
  "He was your great Triptolemus; his vices",
  "Destroyed but realms, and still maintained your prices;",
  "He amplified to every lord's content",
  "The grand agrarian alchymy, high _rent_.",
  "Why did the tyrant stumble on the Tartars,",
  "And lower wheat to such desponding quarters?",
  "Why did you chain him on yon Isle so lone?",
  "The man was worth much more upon his throne.",
  "True, blood and treasure boundlessly were spilt,",
  "But what of that? the Gaul may bear the guilt;",
  "But bread was high, the farmer paid his way,",
  "And acres told upon the appointed day.",
  "But where is now the goodly audit ale?",
  "The purse-proud tenant, never known to fail?",
  "The farm which never yet was left on hand?",
  "The marsh reclaimed to most improving land?",
  "The impatient hope of the expiring lease?",
  "The doubling rental? What an evil's peace!",
  "In vain the prize excites the ploughman's skill,",
  "In vain the Commons pass their patriot bill;",
  "The _Landed Interest_--(you may understand",
  "The phrase much better leaving out the _land_)--",
  "The land self-interest groans from shore to shore,",
  "For fear that plenty should attain the poor.",
  "Up, up again, ye rents, exalt your notes,",
  "Or else the Ministry will lose their votes,",
  "And patriotism, so delicately nice,",
  "Her loaves will lower to the market price;",
  "For ah! \"the loaves and fishes,\" once so high,",
  "Are gone--their oven closed, their ocean dry,",
  "And nought remains of all the millions spent,",
  "Excepting to grow moderate and content.",
  "They who are not so, _had_ their turn--and turn",
  "About still flows from Fortune's equal urn;",
  "Now let their virtue be its own reward,",
  "And share the blessings which themselves prepared.",
  "See these inglorious Cincinnati swarm,",
  "Farmers of war, dictators of the farm;",
  "_Their_ ploughshare was the sword in hireling hands,",
  "_Their_ fields manured by gore of other lands;",
  "Safe in their barns, these Sabine tillers sent",
  "Their brethren out to battle--why? for rent!",
  "Year after year they voted cent. per cent.",
  "Blood, sweat, and tear-wrung millions--why?--for rent!",
  "They roared, they dined, they drank, they swore they meant",
  "To die for England--why then live?--for rent!",
  "The peace has made one general malcontent",
  "Of these high-market patriots; war was rent!",
  "Their love of country, millions all mis-spent,",
  "How reconcile? by reconciling rent!",
  "And will they not repay the treasures lent?",
  "No: down with everything, and up with rent!",
  "Their good, ill, health, wealth, joy, or discontent,",
  "Being, end, aim, religion--_rent_--_rent_--_rent_!",
  "Thou sold'st thy birthright, Esau! for a mess;",
  "Thou shouldst have gotten more, or eaten less;",
  "Now thou hast swilled thy pottage, thy demands",
  "Are idle; Israel says the bargain stands.",
  "Such, landlords! was your appetite for war,",
  "And gorged with blood, you grumble at a scar!",
  "What! would they spread their earthquake even o'er cash?",
  "And when land crumbles, bid firm paper crash?",
  "So rent may rise, bid Bank and Nation fall,",
  "And found on 'Change a _Fundling_ Hospital?",
  "Lo, Mother Church, while all religion writhes,",
  "Like Niobe, weeps o'er her offspring--Tithes;",
  "The Prelates go to--where the Saints have gone,",
  "And proud pluralities subside to one;",
  "Church, state, and faction wrestle in the dark,",
  "Tossed by the deluge in their common ark.",
  "Shorn of her bishops, banks, and dividends,",
  "Another Babel soars--but Britain ends.",
  "And why? to pamper the self-seeking wants,",
  "And prop the hill of these agrarian ants.",
  "\"Go to these ants, thou sluggard, and be wise;\"",
  "Admire their patience through each sacrifice,",
  "Till taught to feel the lesson of their pride,",
  "The price of taxes and of homicide;",
  "Admire their justice, which would fain deny",
  "The debt of nations:--pray _who made it high?_",
  "",
  "Or turn to sail between those shifting rocks,",
  "The new Symplegades--the crushing Stocks,",
  "Where Midas might again his wish behold",
  "In real paper or imagined gold.",
  "That magic palace of Alcina shows",
  "More wealth than Britain ever had to lose,",
  "Were all her atoms of unleavened ore,",
  "And all her pebbles from Pactolus' shore.",
  "There Fortune plays, while Rumour holds the stake",
  "And the World trembles to bid brokers break.",
  "How rich is Britain! not indeed in mines,",
  "Or peace or plenty, corn or oil, or wines;",
  "No land of Canaan, full of milk and honey,",
  "Nor (save in paper shekels) ready money:",
  "But let us not to own the truth refuse,",
  "Was ever Christian land so rich in Jews?",
  "Those parted with their teeth to good King John,",
  "And now, ye kings, they kindly draw your own;",
  "All states, all things, all sovereigns they control,",
  "And waft a loan \"from Indus to the pole.\"",
  "The banker--broker--baron--brethren, speed",
  "To aid these bankrupt tyrants in their need.",
  "Nor these alone; Columbia feels no less",
  "Fresh speculations follow each success;",
  "And philanthropic Israel deigns to drain",
  "Her mild per-centage from exhausted Spain.",
  "Not without Abraham's seed can Russia march;",
  "Tis gold, not steel, that rears the conqueror's arch.",
  "Two Jews, a chosen people, can command",
  "In every realm their Scripture-promised land:--",
  "Two Jews, keep down the Romans, and uphold",
  "The accurséd Hun, more brutal than of old:",
  "Two Jews,--but not Samaritans--direct",
  "The world, with all the spirit of their sect.",
  "What is the happiness of earth to them?",
  "A congress forms their \"New Jerusalem,\"",
  "Where baronies and orders both invite--",
  "Oh, holy Abraham! dost thou see the sight?",
  "Thy followers mingling with these royal swine,",
  "Who spit not \"on their Jewish gaberdine,\"",
  "But honour them as portion of the show--",
  "(Where now, oh Pope! is thy forsaken toe?",
  "Could it not favour Judah with some kicks?",
  "Or has it ceased to \"kick against the pricks?\")",
  "On Shylock's shore behold them stand afresh,",
  "To cut from Nation's hearts their \"pound of flesh.\"",
  "",
  "Strange sight this Congress! destined to unite",
  "All that's incongruous, all that's opposite.",
  "I speak not of the Sovereigns--they're alike,",
  "A common coin as ever mint could strike;",
  "But those who sway the puppets, pull the strings,",
  "Have more of motley than their heavy kings.",
  "Jews, authors, generals, charlatans, combine,",
  "While Europe wonders at the vast design:",
  "There Metternich, power's foremost parasite,",
  "Cajoles; there Wellington forgets to fight;",
  "There Chateaubriand forms new books of martyrs;",
  "And subtle Greeks intrigue for stupid Tartars;",
  "There Montmorenci, the sworn foe to charters,",
  "Turns a diplomatist of great éclat,",
  "To furnish articles for the \"Débats;\"",
  "Of war so certain--yet not quite so sure",
  "As his dismissal in the \"Moniteur.\"",
  "Alas! how could his cabinet thus err!",
  "Can Peace be worth an ultra-minister?",
  "He falls indeed, perhaps to rise again,",
  "\"Almost as quickly as he conquered Spain.\"",
  "",
  "Enough of this--a sight more mournful woos",
  "The averted eye of the reluctant Muse.",
  "The Imperial daughter, the Imperial bride,",
  "The imperial Victim--sacrifice to pride;",
  "The mother of the Hero's hope, the boy,",
  "The young Astyanax of Modern Troy;",
  "The still pale shadow of the loftiest Queen",
  "That Earth has yet to see, or e'er hath seen;",
  "She flits amidst the phantoms of the hour,",
  "The theme of pity, and the wreck of power.",
  "Oh, cruel mockery! Could not Austria spare",
  "A daughter? What did France's widow there?",
  "Her fitter place was by St. Helen's wave,",
  "Her only throne is in Napoleon's grave.",
  "But, no,--she still must hold a petty reign,",
  "Flanked by her formidable chamberlain;",
  "The martial Argus, whose not hundred eyes",
  "Must watch her through these paltry pageantries.",
  "What though she share no more, and shared in vain,",
  "A sway surpassing that of Charlemagne,",
  "Which swept from Moscow to the southern seas!",
  "Yet still she rules the pastoral realm of cheese,",
  "Where Parma views the traveller resort,",
  "To note the trappings of her mimic court.",
  "But she appears! Verona sees her shorn",
  "Of all her beams--while nations gaze and mourn--",
  "Ere yet her husband's ashes have had time",
  "To chill in their inhospitable clime;",
  "(If e'er those awful ashes can grow cold;--",
  "But no,--their embers soon will burst the mould;)",
  "She comes!--the Andromache (but not Racine's,",
  "Nor Homer's,)--Lo! on Pyrrhus' arm she leans!",
  "Yes! the right arm, yet red from Waterloo,",
  "Which cut her lord's half-shattered sceptre through,",
  "Is offered and accepted? Could a slave",
  "Do more? or less?--and _he_ in his new grave!",
  "Her eye--her cheek--betray no inward strife,",
  "And the _Ex_-Empress grows as _Ex_ a wife!",
  "So much for human ties in royal breasts!",
  "Why spare men's feelings, when their own are jests?",
  "",
  "But, tired of foreign follies, I turn home,",
  "And sketch the group--the picture's yet to come.",
  "My Muse 'gan weep, but, ere a tear was spilt,",
  "She caught Sir William Curtis in a kilt!",
  "While thronged the chiefs of every Highland clan",
  "To hail their brother, Vich Ian Alderman!",
  "Guildhall grows Gael, and echoes with Erse roar,",
  "While all the Common Council cry \"Claymore!\"",
  "To see proud Albyn's tartans as a belt",
  "Gird the gross sirloin of a city Celt,",
  "She burst into a laughter so extreme,",
  "That I awoke--and lo! it was _no_ dream!",
  "",
  "Here, reader, will we pause:--if there's no harm in",
  "This first--you'll have, perhaps, a second \"Carmen.\"",
  "",
  "                   B. J^n 10^th^ 1823.",
  ""
]