module.exports = [
  "Come live with me, and be my love,",
  "And we will all the pleasures prove,",
  "That hills and valleys, dales and fields,",
  "And all the craggy mountain yields.",
  "",
  "There we will sit upon the rocks,",
  "And see the shepherds feed their flocks",
  "By shallow rivers, to whose falls",
  "Melodious birds sing madrigals.",
  "",
  "And I will make thee beds of roses,",
  "With a thousand fragrant posies,",
  "A cap of flowers and a kirtle",
  "Embroidered all with leaves of myrtle;",
  "",
  "A gown made of the finest wool,",
  "Which from our pretty lambs we pull;",
  "Fair lined slippers for the cold,",
  "With buckles of the purest gold;",
  "",
  "A belt of straw and ivy buds,",
  "With coral clasps and amber studs;",
  "And if these pleasures may thee move,",
  "Come live with me, and be my love.",
  "",
  "The shepherd swains shall dance and sing",
  "For thy delight each May morning:",
  "If these delights thy mind may move,",
  "Then live with me, and be my love.",
  ""
]