module.exports = [
  "How oft on Sundays, when I'd time to tramp,",
  "My rambles led me to a gipsy's camp,",
  "Where the real effigy of midnight hags,",
  "With tawny smoked flesh and tattered rags,",
  "Uncouth-brimmed hat, and weather-beaten cloak,",
  "Neath the wild shelter of a knotty oak,",
  "Along the greensward uniformly pricks",
  "Her pliant bending hazel's arching sticks:",
  "While round-topt bush, or briar-entangled hedge,",
  "Where flag-leaves spring beneath, or ramping sedge,",
  "Keeps off the bothering bustle of the wind,",
  "And give the best retreat she hopes to find.",
  "How oft I've bent me oer her fire and smoke,",
  "To hear her gibberish tale so quaintly spoke,",
  "While the old Sybil forged her boding clack,",
  "Twin imps the meanwhile bawling at her back;",
  "Oft on my hand her magic coin's been struck,",
  "And hoping chink, she talked of morts of luck:",
  "And still, as boyish hopes did first agree,",
  "Mingled with fears to drop the fortune's fee,",
  "I never failed to gain the honours sought,",
  "And Squire and Lord were purchased with a groat.",
  "But as man's unbelieving taste came round,",
  "She furious stampt her shoeless foot aground,",
  "Wiped bye her soot-black hair with clenching fist,",
  "While through her yellow teeth the spittle hist,",
  "Swearing by all her lucky powers of fate,",
  "Which like as footboys on her actions wait,",
  "That fortune's scale should to my sorrow turn,",
  "And I one day the rash neglect should mourn;",
  "That good to bad should change, and I should be",
  "Lost to this world and all eternity;",
  "That poor as Job I should remain unblest:--",
  "  (Alas, for fourpence how my die is cast!)",
  "Of not a hoarded farthing be possesst,",
  "  And when all's done, be shoved to hell at last!",
  ""
]