module.exports = [
  "THE rock-like mud unfroze a little and rills",
  "Ran and sparkled down each side of the road",
  "Under the catkins wagging in the hedge.",
  "But earth would have her sleep out, spite of the sun;",
  "Nor did I value that thin gilding beam",
  "More than a pretty February thing",
  "Till I came down to the old Manor Farm,",
  "And church and yew-tree opposite, in age",
  "Its equals and in size. The church and yew",
  "And farmhouse slept in a Sunday silentness.",
  "The air raised not a straw. The steep farm roof,",
  "With tiles duskily glowing, entertained",
  "The mid-day sun; and up and down the roof",
  "White pigeons nestled. There was no sound but one.",
  "Three cart-horses were looking over a gate",
  "Drowsily through their forelocks, swishing their tails",
  "Against a fly, a solitary fly.",
  "",
  "The Winter's cheek flushed as if he had drained",
  "Spring, Summer, and Autumn at a draught",
  "And smiled quietly. But 'twas not Winter--",
  "Rather a season of bliss unchangeable",
  "Awakened from farm and church where it had lain",
  "Safe under tile and thatch for ages since",
  "This England, Old already, was called Merry.",
  ""
]