module.exports = [
  "Of all our antic sights and pageantry",
  "Which English idiots run in crowds to see,",
  "The Polish Medal bears the prize alone;",
  "A monster, more the favourite of the town",
  "Than either fairs or theatres have shown.",
  "Never did art so well with nature strive,",
  "Nor ever idol seemed so much alive;",
  "So like the man, so golden to the sight,",
  "So base within, so counterfeit and light.",
  "One side is filled with title and with face;",
  "And, lest the king should want a regal place,",
  "On the reverse a tower the town surveys,",
  "O'er which our mounting sun his beams displays.",
  "The word, pronounced aloud by shrieval voice,",
  "Loetamur, which in Polish is Rejoice,",
  "The day, month, year, to the great act are joined,",
  "And a new canting holiday designed.",
  "Five days he sate for every cast and look,",
  "Four more days than God to finish Adam took.",
  "But who can tell what essence angels are",
  "Or how long Heaven was making Lucifer?",
  "Oh, could the style that copied every grace",
  "And ploughed such furrows for an eunuch face,",
  "Could it have formed his ever-changing will,",
  "The various piece had tired the graver's skill!",
  "A martial hero first, with early care",
  "Blown, like a pigmy by the winds, to war;",
  "A beardless chief, a rebel ere a man,",
  "So young his hatred to his Prince began.",
  "Next this, (how wildly will ambition steer!)",
  "A vermin wriggling in the usurper's ear,",
  "Bartering his venal wit for sums of gold,",
  "He cast himself into the saint-like mould;",
  "Groaned, sighed, and prayed, while godliness was gain,",
  "The loudest bag-pipe of the squeaking train.",
  "But, as 'tis hard to cheat a juggler's eyes,",
  "His open lewdness he could ne'er disguise.",
  "There split the saint; for hypocritic zeal",
  "Allows no sins but those it can conceal.",
  "Whoring to scandal gives too large a scope;",
  "Saints must not trade, but they may interlope.",
  "The ungodly principle was all the same;",
  "But a gross cheat betrays his partners' game.",
  "Besides, their pace was formal, grave, and slack;",
  "His nimble wit outran the heavy pack.",
  "Yet still he found hs fortune at a stay,",
  "Whole droves of blockheads choking up his way;",
  "They took, but not rewarded, his advice;",
  "Villain and wit exact a double price.",
  "Power was his aim; but thrown from that pretence,",
  "The wretch turned loyal in his own defence,",
  "And malice reconciled him to his Prince.",
  "Him in the anguish of his soul he served,",
  "Rewarded faster still than he deserved.",
  "Behold him now exalted into trust,",
  "His counsels oft convenient, seldom just;",
  "Even in the most sincere advice he gave",
  "He had a grudging still to be a knave.",
  "The frauds he learnt in his fanatic years",
  "Made him uneasy in his lawful gears.",
  "At best, as little honest as he could,",
  "And, like white witches, mischievously good.",
  "To his first bias longingly he leans",
  "And rather would be great by wicked means.",
  "Thus framed for ill, he loosed our triple hold,",
  "(Advice unsafe, precipitous, and bold.)",
  "From hence those tears, that Ilium was our woe:",
  "Who helps a powerful friend forearms a foe.",
  "What wonder if the waves prevail so far,",
  "When he cut down the banks that made the bar?",
  "Seas follow but their nature to invade;",
  "But he by art our native strength betrayed.",
  "So Samson to his foe his force confest,",
  "And to be shorn lay slumbering on her breast.",
  "But when this fatal counsel, found too late,",
  "Exposed its author to the public hate,",
  "When his just sovereign by no impious way",
  "Could be seduced to arbitrary sway,",
  "Forsaken of that hope, he shifts his sail,",
  "Drives down the current with the popular gale,",
  "And shows the fiend confessed without a veil.",
  "He preaches to the crowd that power is lent,",
  "But not conveyed to kingly government,",
  "That claims successive bear no binding force,",
  "That coronation oaths are things of course;",
  "Maintains the multitude can never err,",
  "And sets the people in the papal chair.",
  "The reason's obvious, interest never lies;",
  "The most have still their interest in their eyes,",
  "The power is always theirs, and power is ever wise.",
  "Almighty crowd! thou shortenest all dispute.",
  "Power is thy essence, wit thy attribute!",
  "Nor faith nor reason make thee at a stay,",
  "Thou leapst o'er all eternal truths in thy Pindaric way!",
  "Athens, no doubt, did righteously decide,",
  "When Phocion and when Socrates were tried;",
  "As righteously they did those dooms repent;",
  "Still they were wise, whatever way they went.",
  "Crowds err not, though to both extremes they run;",
  "To kill the father and recall the son.",
  "Some think the fools were most, as times went then,",
  "But now the world's o'erstocked with prudent men.",
  "The common cry is even religion's test;",
  "The Turk's is at Constantinople best,",
  "Idols in India, Popery in Rome,",
  "And our own worship is only true at home,",
  "And true but for the time; 'tis hard to know",
  "How long we please it shall continue so;",
  "This side to-day, and that to-morrow burns;",
  "So all are God Almighties in their turns.",
  "A tempting doctrine, plausible and new;",
  "What fools our fathers were, if this be true!",
  "Who, to destroy the seeds of civil war,",
  "Inherent right in monarchs did declare;",
  "And, that a lawful power might never cease,",
  "Secured succession to secure our peace.",
  "Thus property and sovereign sway at last",
  "In equal balances were justly cast;",
  "But this new Jehu spurs the hot-mounted horse,",
  "Instructs the beast to know his native force,",
  "To take the bit between his teeth and fly",
  "To the next headlong steep of anarchy.",
  "Too happy Engand, if our good we knew,",
  "Would we possess the freedom we pursue!",
  "The lavish government can give no more;",
  "Yet we repine, and plenty makes us poor.",
  "God tried us once; our rebel fathers fought;",
  "He glutted them with all the power they sought,",
  "Till, mastered by their own usurping brave,",
  "The free-born subject sunk into a slave.",
  "We loathe our manna, and we long for quails;",
  "Ah! what is man, when his own wish prevails!",
  "How rash, how swift to plunge himself in ill,",
  "Proud of his power and boundless in his will!",
  "That kings can do no wrong we must believe;",
  "None can they do, and must they all receive?",
  "Help. Heaven, or sadly we shall see an hour",
  "When neither wrong nor right are in their power!",
  "Already they have lost their best defence,",
  "The benefit of laws which they dispense.",
  "No justice to their righteous cause allowed,",
  "But baffled by an arbitrary crowd;",
  "And medals graved, their conquest to record,",
  "The stamp and coin of their adopted lord.",
  "",
  "The man who laughed but once, to see an ass",
  "Mumbling to make the cross-grained thistles pass,",
  "Might laugh again to see a jury chaw",
  "The prickles of unpalatable law.",
  "The witnesses that, leech-like lived on blood,",
  "Sucking for them were med'cinally good;",
  "But when they fastened on their festered sore,",
  "Then justice and religion they forswore,",
  "Thus men are raised by factions and decried,",
  "And rogue and saint distinguished by their side;",
  "They rack even Scripture to confess their cause",
  "And plead a call to preach in spite of laws.",
  "But that's no news to the poor injured page,",
  "It has been used as ill in every age,",
  "And is constrained with patience all to take,",
  "For what defence can Greek and Hebrew make?",
  "Happy who can this talking trumpet seize,",
  "They make it speak whatever sense they please!",
  "'Twas framed at first our oracle to inquire;",
  "But since our sects in prophecy grow higher,",
  "The text inspires not them, but they the text inspire.",
  "",
  "London, thou great emporium of our isle,",
  "O thou too bounteous, thou too fruitful Nile!",
  "How shall I praise or curse to thy desert,",
  "Or separate thy sound from thy corrupted part?",
  "I called thee Nile; the parallel will stand:",
  "Thy tides of wealth o'erflow the fattened land;",
  "Yet monsters from thy large increase we find",
  "Engendered on the slime thou leavest behind.",
  "Sedition has not wholly seized on thee,",
  "Thy nobler parts are from infection free.",
  "Of Israel's tribes thou hast a numerous band,",
  "But still the Canaanite is in the land.",
  "Thy military chiefs are brave and true,",
  "Nor are thy disenchanted burghers few.",
  "The head is loyal which thy heart commands,",
  "But what's a head with two such gouty hands?",
  "The wise and wealthy love the surest way",
  "And are content to thrive and to obey.",
  "But wisdom is to sloth too great a slave;",
  "None are so busy as the fool and knave.",
  "Those let me curse; what vengeance will they urge,",
  "Whose ordures neither plague nor fire can purge,",
  "Nor sharp experience can to duty bring",
  "Nor angry Heaven nor a forgiving king!",
  "In gospel-phrase their chapmen they betray;",
  "Their shops are dens, the buyer is their prey;",
  "The knack of trades is living on the spoil;",
  "They boast e'en when each other they beguile.",
  "Customs to steal is such a trivial thing",
  "That 'tis their charter to defraud their King.",
  "All hands unite of every jarring sect;",
  "They cheat the country first, and then infect.",
  "They for God's cause their monarchs dare dethrone,",
  "And they'll be sure to make His cause their own.",
  "Whether the plotting Jesuit laid the plan",
  "Of murdering kings, or the French Puritan,",
  "Our sacrilegious sects their guides outgo",
  "And kings and kingly power would murder too.",
  "",
  "What means their traitorous combination less,",
  "Too plain to evade, too shameful to confess?",
  "But treason is not owned when 'tis descried;",
  "Successful crimes alone are justified.",
  "The men who no consiracy would find,",
  "Who doubts but, had it taken, they had joined?",
  "Joined in a mutual covenant of defence,",
  "At first without, at last against their Prince?",
  "If sovereign right by sovereign power they scan,",
  "The same bold maxim holds in God and man:",
  "God were not safe; his thunder could they shun,",
  "He should be forced to crown another son.",
  "Thus, when the heir was from the vineyard thrown,",
  "The rich possession was the murderers' own.",
  "In vain to sophistry they have recourse;",
  "By proving theirs no plot they prove 'tis worse,",
  "Unmasked rebellion, and audiacious force,",
  "Which, though not actual, yet all eyes may see",
  "'Tis working, in the immediate power to be;",
  "For from pretended grievances they rise",
  "First to dislike and after to dispise;",
  "Then, Cyclop-like, in human flesh to deal,",
  "Chop up a minister at every meal;",
  "Perhaps not wholly to melt down the king,",
  "But clip his regal rights within the ring;",
  "From thence to asssume the power of peace and war",
  "And ease him by degrees of public care.",
  "Yet, to consult his dignity and fame,",
  "He should have leave to exercise the name,",
  "And hold the cards while Commons played the game.",
  "For what can power give more than food and drink,",
  "To live at ease and not be bound to think?",
  "These are the cooler methods of their crime,",
  "But their hot zealots think 'tis loss of time;",
  "On utmost bounds of loyalty they stand,",
  "And grin and whet like a Croatian band",
  "That waits impatient for the last command:",
  "Thus outlaws open villainy maintain;",
  "They steal not, but in squadrons scour the plain;",
  "And if their power the passengers subdue,",
  "The most most have right, the wrong is in the few.",
  "Such impious axioms foolishly they show,",
  "For in some soils Republics will not grow:",
  "Our temperate Isle will no extremes sustain",
  "Of popular sway or arbitrary reign:",
  "But slides between them both into the best,",
  "Secure in freedom, in a monarch blest.",
  "And, though the climate, vexed with various winds,",
  "Works through our yielding bodies on our minds,",
  "The wholesome tempest purges what it breeds",
  "To recommend the calmness that succeeds.",
  "",
  "But thou, the pander of the people's hearts,",
  "(O crooked soul and serpentine in arts!)...",
  "What curses on thy blasted name will fall,",
  "Which age to age their legacy shall call,",
  "For all must curse the woes that must descend on all!",
  "Religion thou hast none: thy mercury",
  "Has passed through every sect, or theirs through thee.",
  "But what thou givest, that venom still remains,",
  "And the poxed nation feels thee in their brains.",
  "What else inspires the tongues and swells the breasts",
  "Of all thy bellowing renegado priests,",
  "That preach up thee for God, dispense thy laws,",
  "And with thy stum ferment their fainting cause,",
  "Fresh fumes of madness raise, and toil and sweat,",
  "To make the formidable cripple great?",
  "Yet should thy crimes succeed, should lawless power",
  "Compass those ends thy greedy hopes devour,",
  "Thy canting friends thy mortal foes would be,",
  "Thy god and theirs will never long agree;",
  "For thine, if thou hast any, must be one",
  "That lets the world and human kind alone;",
  "A jolly god that passes hours too well",
  "To promise Heaven or threaten us with Hell,",
  "That unconcerned can at rebellion sit",
  "And wink at crimes he did himself commit.",
  "A tyrant theirs; the heaven their priesthood paints",
  "A conventicle of gloomy sullen saints;",
  "A heaven, like Bedlam, slovenly and sad,",
  "Foredoomed for souls with false religion mad.",
  "",
  "Without a vision poets can foreshow",
  "What all but fools by common sense may know:",
  "If true succession from our Isle should fail,",
  "And crowds profane with impious arms prevail,",
  "Not thou nor those thy factious arts engage",
  "Shall reap that harvest of rebellious rage,",
  "With which thou flatterest thy decrepit age.",
  "The swelling poison of the several sects,",
  "Which, wanting vent, the nation's health infects,",
  "Shall burst its bag; and fighting out their way,",
  "The various venoms on each other prey.",
  "The Presbyter, puffed up with spiritual pride,",
  "Shall on the necks of the lewd nobles ride,",
  "His brethren damn, the civil power defy,",
  "And parcel out republic prelacy.",
  "But short shall be his reign; his rigid yoke",
  "And tyrant power will puny sects provoke,",
  "And frogs, and toads, and all the tadpole train",
  "Will croak to Heaven for help from this devouring crane.",
  "The cut-throat sword and clamorous gown shall jar",
  "In sharing their ill-gotten spoils of war;",
  "Chiefs shall be grudged the part which they pretend;",
  "Lords envy lords, and friends with every friend",
  "About their impious merit shall contend.",
  "The surly Commons shall respect deny",
  "And justle peerage out with property.",
  "Their General either shall his trust betray",
  "And force the crowd to arbitrary sway,",
  "Or they, suspecting his ambitious aim,",
  "In hate of kings shall cast anew the frame",
  "And thrust out Collatine that bore their name.",
  "",
  "Thus inborn broils the factions would engage,",
  "Or wars of exiled heirs, or foreign rage,",
  "Till halting vengeance overtook our age,",
  "And our wild labours, wearied into rest,",
  "Reclined us on a rightful monarch's breast.",
  "",
  "\"Pudet hoec opprobria vobis",
  "Et dici potuisse et non potuisse refelli.\"",
  ""
]