module.exports = [
  "The room is quiet, thoughts alone",
  "People its mute tranquillity;",
  "The yoke put on, the long task done,­",
  "I am, as it is bliss to be,",
  "Still and untroubled. Now, I see,",
  "For the first time, how soft the day",
  "O'er waveless water, stirless tree,",
  "Silent and sunny, wings its way.",
  "Now, as I watch that distant hill,",
  "So faint, so blue, so far removed,",
  "Sweet dreams of home my heart may fill,",
  "That home where I am known and loved:",
  "It lies beyond; yon azure brow",
  "Parts me from all Earth holds for me;",
  "And, morn and eve, my yearnings flow",
  "Thitherward tending, changelessly.",
  "My happiest hours, aye ! all the time,",
  "I love to keep in memory,",
  "Lapsed among moors, ere life's first prime",
  "Decayed to dark anxiety.",
  "",
  "Sometimes, I think a narrow heart",
  "Makes me thus mourn those far away,",
  "And keeps my love so far apart",
  "From friends and friendships of to-day;",
  "Sometimes, I think 'tis but a dream",
  "I measure up so jealously,",
  "All the sweet thoughts I live on seem",
  "To vanish into vacancy:",
  "And then, this strange, coarse world around",
  "Seems all that's palpable and true;",
  "And every sight, and every sound,",
  "Combines my spirit to subdue",
  "To aching grief, so void and lone",
  "Is Life and Earth­so worse than vain,",
  "The hopes that, in my own heart sown,",
  "And cherished by such sun and rain",
  "As Joy and transient Sorrow shed,",
  "Have ripened to a harvest there:",
  "Alas ! methinks I hear it said,",
  "\"Thy golden sheaves are empty air.\"",
  "All fades away; my very home",
  "I think will soon be desolate;",
  "I hear, at times, a warning come",
  "Of bitter partings at its gate;",
  "And, if I should return and see",
  "The hearth-fire quenched, the vacant chair;",
  "And hear it whispered mournfully,",
  "That farewells have been spoken there,",
  "What shall I do, and whither turn ?",
  "Where look for peace ? When cease to mourn ?",
  "",
  "'Tis not the air I wished to play,",
  "The strain I wished to sing;",
  "My wilful spirit slipped away",
  "And struck another string.",
  "I neither wanted smile nor tear,",
  "Bright joy nor bitter woe,",
  "But just a song that sweet and clear,",
  "Though haply sad, might flow.",
  "",
  "A quiet song, to solace me",
  "When sleep refused to come;",
  "A strain to chase despondency,",
  "When sorrowful for home.",
  "In vain I try; I cannot sing;",
  "All feels so cold and dead;",
  "No wild distress, no gushing spring",
  "Of tears in anguish shed;",
  "",
  "But all the impatient gloom of one",
  "Who waits a distant day,",
  "When, some great task of suffering done,",
  "Repose shall toil repay.",
  "For youth departs, and pleasure flies,",
  "And life consumes away,",
  "And youth's rejoicing ardour dies",
  "Beneath this drear delay;",
  "",
  "And Patience, weary with her yoke,",
  "Is yielding to despair,",
  "And Health's elastic spring is broke",
  "Beneath the strain of care.",
  "Life will be gone ere I have lived;",
  "Where now is Life's first prime ?",
  "I've worked and studied, longed and grieved,",
  "Through all that rosy time.",
  "",
  "To toil, to think, to long, to grieve,­",
  "Is such my future fate ?",
  "The morn was dreary, must the eve",
  "Be also desolate ?",
  "Well, such a life at least makes Death",
  "A welcome, wished-for friend;",
  "Then, aid me, Reason, Patience, Faith,",
  "To suffer to the end !",
  ""
]