module.exports = [
  "\"Is this the road that climbs above and bends",
  "Round what was once a chalk-pit: now it is",
  "By accident an amphitheatre.",
  "Some ash-trees standing ankle-deep in brier",
  "And bramble act the parts, and neither speak",
  "Nor stir.\" \"But see: they have fallen, every one,",
  "And brier and bramble have grown over them.\"",
  "\"That is the place. As usual no one is here.",
  "Hardly can I imagine the drop of the axe,",
  "And the smack that is like an echo, sounding here.\"",
  "\"I do not understand.\" \"Why, what I mean is",
  "That I have seen the place two or three times",
  "At most, and that its emptiness and silence",
  "And stillness haunt me, as if just before",
  "It was not empty, silent, still, but full",
  "Of life of some kind, perhaps tragical.",
  "Has anything unusual happened here?\"",
  "\"Not that I know of. It is called the Dell.",
  "They have not dug chalk here for a century.",
  "That was the ash-trees' age. But I will ask.\"",
  "\"No. Do not. I prefer to make a tale,",
  "Or better leave it like the end of a play,",
  "Actors and audience and lights all gone;",
  "For so it looks now. In my memory",
  "Again and again I see it, strangely dark,",
  "And vacant of a life but just withdrawn.",
  "We have not seen the woodman with the axe.",
  "Some ghost has left it now as we two came.\"",
  "\"And yet you doubted if this were the road?\"",
  "\"Well, sometimes I have thought of it and failed",
  "To place it. No. And I am not quite sure,",
  "Even now, this is it. For another place,",
  "Real or painted, may have combined with it.",
  "Or I myself a long way back in time . . .\"",
  "\"Why, as to that, I used to meet a man--",
  "I had forgotten,--searching for birds' nests",
  "Along the road and in the chalk-pit too.",
  "The wren's hole was an eye that looked at him",
  "For recognition. Every nest he knew.",
  "He got a stiff neck, by looking this side or that,",
  "Spring after spring, he told me, with his laugh,--",
  "A sort of laugh. He was a visitor,",
  "A man of forty,--smoked and strolled about.",
  "At orts and crosses Pleasure and Pain had played",
  "On his brown features;--I think both had lost;--",
  "Mild and yet wild too. You may know the kind.",
  "And once or twice a woman shared his walks,",
  "A girl of twenty with a brown boy's face,",
  "And hair brown as a thrush or as a nut,",
  "Thick eyebrows, glinting eyes--\" \"You have",
  "    said enough.",
  "A pair,--free thought, free love,--I know the",
  "    breed:",
  "I shall not mix my fancies up with them.\"",
  "\"You please yourself. I should prefer the truth",
  "Or nothing. Here, in fact, is nothing at all",
  "Except a silent place that once rang loud,",
  "And trees and us--imperfect friends, we men",
  "And trees since time began; and nevertheless",
  "Between us still we breed a mystery.\"",
  ""
]