module.exports = [
  "See with what simplicity",
  "This Nimph begins her golden daies!",
  "In the green Grass she loves to lie,",
  "And there with her fair Aspect tames",
  "The Wilder flow'rs, and gives them names:",
  "But only with the Roses playes;",
  "And them does tell",
  "What Colour best becomes them, and what Smell.",
  "",
  "Who can foretel for what high cause",
  "This Darling of the Gods was born!",
  "Yet this is She whose chaster Laws",
  "The wanton Love shall one day fear,",
  "And, under her command severe,",
  "See his Bow broke and Ensigns torn.",
  "Happy, who can",
  "Appease this virtuous Enemy of Man!",
  "",
  "O then let me in time compound,",
  "And parly with those conquering Eyes;",
  "Ere they have try'd their force to wound,",
  "Ere, with their glancing wheels, they drive",
  "In Triumph over Hearts that strive,",
  "And them that yield but more despise.",
  "Let me be laid,",
  "Where I may see thy Glories from some Shade.",
  "",
  "Mean time, whilst every verdant thing",
  "It self does at thy Beauty charm,",
  "Reform the errours of the Spring;",
  "Make that the Tulips may have share",
  "Of sweetness, seeing they are fair;",
  "And Roses of their thorns disarm:",
  "But most procure",
  "That Violets may a longer Age endure.",
  "",
  "But O young beauty of the Woods,",
  "Whom Nature courts with fruits and flow'rs,",
  "Gather the Flow'rs, but spare the Buds;",
  "Lest Flora angry at thy crime,",
  "To kill her Infants in their prime,",
  "Do quickly make th' Example Yours;",
  "And, ere we see,",
  "Nip in the blossome all our hopes and Thee.",
  ""
]