module.exports = [
  "(Mark, xi.17)",
  "",
  "Thy mansion is the Christian's heart,",
  "O Lord, Thy dwelling place secure!",
  "Bid the unruly throng depart,",
  "And leave the consecrated door.",
  "",
  "Devoted as it is to Thee,",
  "A thievish swarm frequents the place,",
  "They steal away my hopes from me,",
  "And rob my Saviour of His praise.",
  "",
  "There, too, a sharp designing trade",
  "Sin, Satan, and the World maintain;",
  "Nor cease to press me, and persuade",
  "To part with ease, and purchase pain.",
  "",
  "I know them, and I hate their din;",
  "And weary of the bustling crowd;",
  "But while their voice is heard within,",
  "I cannot serve Thee as I would.",
  "",
  "Oh! for the joy thy presence gives,",
  "What peace shall reign when Thou art there;",
  "Thy presence makes this den of thieves",
  "A calm delightful house of prayer.",
  "",
  "And if Thou make Thy temple shine,",
  "Yet self-abased, will I adore;",
  "The gold and silver are not mine;",
  "I give Thee waht was Thine before.",
  ""
]