module.exports = [
  "Vanity of vanities, all is vanity.--_Solomon",
  "",
  "What are life's joys and gains?",
  "  What pleasures crowd its ways,",
  "That man should take such pains",
  "  To seek them all his days?",
  "Sift this untoward strife",
  "  On which thy mind is bent:",
  "See if this chaff of life",
  "  Is worth the trouble spent.",
  "",
  "Is pride thy heart's desire?",
  "  Is power thy climbing aim?",
  "Is love thy folly's fire?",
  "  Is wealth thy restless game?",
  "Pride, power, love, wealth, and all",
  "  Time's touchstone shall destroy,",
  "And, like base coin, prove all",
  "  Vain substitutes for joy.",
  "",
  "Dost think that pride exalts",
  "  Thyself in other's eyes,",
  "And hides thy folly's faults,",
  "  Which reason will despise?",
  "Dost strut, and turn, and stride,",
  "  Like walking weathercocks?",
  "The shadow by thy side",
  "  Becomes thy ape, and mocks.",
  "",
  "Dost think that power's disguise",
  "  Can make thee mighty seem?",
  "It may in folly's eyes,",
  "  But not in worth's esteem,",
  "When all that thou canst ask,",
  "  And all that she can give,",
  "Is but a paltry mask",
  "  Which tyrants wear and live.",
  "",
  "Go, let thy fancies range",
  "  And ramble where they may;",
  "View power in every change,",
  "  And what is the display?",
  "--The country magistrate,",
  "  The meanest shade in power,",
  "To rulers of the state,",
  "  The meteors of an hour.",
  "",
  "View all, and mark the end",
  "  Of every proud extreme,",
  "Where flattery turns a friend,",
  "  And counterfeits esteem;",
  "Where worth is aped in show,",
  "  That doth her name purloin,",
  "Like toys of golden glow",
  "  That's sold for copper coin.",
  "",
  "Ambition's haughty nod",
  "  With fancies may deceive,",
  "Nay, tell thee thou'rt a god,",
  "  And wilt thou such believe?",
  "Go, bid the seas be dry;",
  "  Go, hold earth like a ball,",
  "Or throw thy fancies by,",
  "  For God can do it all.",
  "",
  "Dost thou possess the dower",
  "  Of laws to spare or kill?",
  "Call it not heavenly power",
  "  When but a tyrant's will.",
  "Know what a God will do,",
  "  And know thyself a fool,",
  "Nor, tyrant-like, pursue",
  "  Where He alone should rule.",
  "",
  "O put away thy pride,",
  "  Or be ashamed of power",
  "That cannot turn aside",
  "  The breeze that waves a flower.",
  "Or bid the clouds be still:",
  "  Though shadows, they can brave",
  "Thy poor power mocking will:",
  "  Then make not man a slave.",
  "",
  "Dost think, when wealth is won,",
  "  Thy heart has its desire?",
  "Hold ice up to the sun,",
  "  And wax before the fire;",
  "Nor triumph oer the reign",
  "  Which they so soon resign;",
  "In this world's ways they gain,",
  "  Insurance safe as thine.",
  "",
  "Dost think life's peace secure",
  "  In house and in land?",
  "Go, read the fairy lure",
  "  To twist a cord in sand;",
  "Lodge stones upon the sky,",
  "  Hold water in a sieve,",
  "Nor give such tales the lie,",
  "  And still thine own believe.",
  "",
  "Whoso with riches deals,",
  "  And thinks peace bought and sold,",
  "Will find them slipping eels,",
  "  That slide the firmest hold:",
  "Though sweet as sleep with health",
  "  Thy lulling luck may be,",
  "Pride may oerstride thy wealth,",
  "  And check prosperity.",
  "",
  "Dost think that beauty's power",
  "  Life sweetest pleasure gives?",
  "Go, pluck the summer flower,",
  "  And see how long it lives:",
  "Behold, the rays glide on",
  "  Along the summer plain",
  "Ere thou canst say \"they're gone,\"",
  "  And measure beauty's reign.",
  "",
  "Look on the brightest eye,",
  "  Nor teach it to be proud;",
  "View but the clearest sky,",
  "  And thou shalt find a cloud;",
  "Nor call each face ye meet",
  "  An angel's, cause it's fair,",
  "But look beneath your feet,",
  "  And think of what they are.",
  "",
  "Who thinks that love doth live",
  "  In beauty's tempting show,",
  "Shall find his hopes ungive,",
  "  And melt in reason's thaw.",
  "Who thinks that pleasure lies",
  "  In every fairy bower,",
  "Shall oft, to his surprise,",
  "  Find poison in the flower.",
  "",
  "Dost lawless passions grasp?",
  "  Judge not thou deal'st in joy:",
  "Its flowers but hide the asp,",
  "  Thy revels to destroy.",
  "Who trusts an harlot's smile,",
  "  And by her wiles are led,",
  "Plays, with a sword the while",
  "  Hung dropping oer his head.",
  "",
  "Dost doubt my warning song?",
  "  Then doubt the sun gives light,",
  "Doubt truth to teach thee wrong,",
  "  And wrong alone as right;",
  "And live as lives the knave,",
  "  Intrigue's deceiving guest;",
  "Be tyrant, or be slave,",
  "  As suits thy ends the best.",
  "",
  "Or pause amid thy toils",
  "  For visions won and lost,",
  "And count the fancied spoils,",
  "  If eer they quit the cost:",
  "And if they still possess",
  "  Thy mind, as worthy things,",
  "Plat straws with bedlam Bess,",
  "  And call them diamond rings.",
  "",
  "Thy folly's past advice,",
  "  Thy heart's already won,",
  "Thy fall's above all price,",
  "  So go, and be undone;",
  "For all who thus prefer",
  "  The seeming great for small",
  "Shall make wine vinegar,",
  "  And sweetest honey gall.",
  "",
  "Wouldst heed the truths I sing,",
  "  To profit wherewithal,",
  "Clip folly's wanton wing,",
  "  And keep her within call.",
  "I've little else to give,",
  "  What thou canst easy try;",
  "The lesson how to live",
  "  Is but to learn to die.",
  ""
]