module.exports = [
  "THE new moon hangs like an ivory bugle",
  "In the naked frosty blue;",
  "And the ghylls of the forest, already blackened",
  "By Winter, are blackened anew.",
  "",
  "The brooks that cut up and increase the forest,",
  "As if they had never known",
  "The sun, are roaring with black hollow voices",
  "Betwixt rage and a moan.",
  "",
  "But still the caravan-hut by the hollies",
  "Like a kingfisher gleams between:",
  "Round the mossed old hearths of the charcoal-burners",
  "First primroses ask to be seen.",
  "",
  "The charcoal-burners are black, but their linen",
  "Blows white on the line;",
  "And white the letter the girl is reading",
  "Under that crescent fine;",
  "",
  "And her brother who hides apart in a thicket,",
  "Slowly and surely playing",
  "On a whistle an olden nursery melody,",
  "Says far more than I am saying.",
  ""
]