module.exports = [
  "Beautiful Ancient City of Perth,",
  "One of the fairest on the earth,",
  "With your stately mansions and scenery most fine,",
  "Which seems very beautiful in the summer time;",
  "And the beautiful silvery Tay,",
  "Rolling smoothly on its way,",
  "And glittering like silver in the sunshine -",
  "And the Railway Bridge across it is really sublime.",
  "The scenery is very beautiful when in full bloom,",
  "It far excels the river Doon -",
  "For the North Inch and South Inch is most beautiful to behold,",
  "Where the buttercups do shine in the sunshine like gold.",
  "",
  "And there's the Palace of Scone, most beautiful to be seen,",
  "Near by the river Tay and the North Inch so green,",
  "Whereon is erected the statue of Prince Albert, late husband of the Queen,",
  "And also the statue of Sir Walter Scott is moat beautiful to be seen,",
  "Erected on the South Inch, which would please the Queen,",
  "And recall to her memory his novels she has read -",
  "And came her to feel a pang for him that is dead.",
  "",
  "Beautiful City of Perth, along the river Tay,",
  "I must conclude ms lay,",
  "And to write in praise of thee my heart does not gainsay,",
  "To tell the world fearlessly, without the least dismay -",
  "With your stately mansions and the beautiful river Tay,",
  "You're one of the fairest Cities of the present day.",
  ""
]