module.exports = [
  "The Fir-Tree looked on stars, but loved the Brook!",
  "\"O silver-voiced! if thou wouldst wait,",
  "My love can bravely woo.\" All smiles forsook",
  "The brook's white face. \"Too late!",
  "Too late! I go to wed the sea.",
  "I know not if my love would curse or bless thee.",
  "I may not, dare not, tarry to caress thee,",
  "Oh, do not follow me!",
  "",
  "The Fir-Tree moaned and moaned till spring;",
  "Then laughed in manic joy to feel",
  "Early one day, the woodsmen of the King",
  "Sign him with a sign of burning steel,",
  "The first to fall. \"Now flee",
  "Thy swiftest, Brook! Thy love may curse or bless me,",
  "I care not, if but once thou dost caress me,",
  "O Brook, I follow thee!",
  "",
  "All torn and bruised with mark of adze and chain,",
  "Hurled down the dizzy slide of sand,",
  "Tossed by great waves in ecstsy of pain,",
  "And rudely thrown at last to land,",
  "The Fir-Tree heard: \"Oh, see",
  "With what fierce love it is I must caress thee!",
  "I warned thee I might curse, and never bless thee,",
  "Why didst thou follow me?",
  "",
  "All stately set with spar and brace and rope,",
  "The Fir-Tree stood and sailed and sailed.",
  "In wildest storm when all the ship lost hope,",
  "The Fir-Tree never shook nor quailed,",
  "Nor ceased from saying, \"Free",
  "Art thou, O Brook! But once thou hast caressed me;",
  "For life, for death, thy love has cursed or blessed me;",
  "Behold, I follow thee!\"",
  "",
  "Lost in a night, and no man left to tell,",
  "Crushed in the giant iceberg's play,",
  "The ship went down without a song, a knell.",
  "Still drifts the Fir-Tree night and day,",
  "Still moans along the sea",
  "A voice: \"O Fir-Tree! thus must I possess thee;",
  "Eternally, brave love, will I caress thee,",
  "Dead for the love of me!\"",
  ""
]