module.exports = [
  "Beautiful Railway Bridge of the Silvery Tay!",
  "With your numerous arches and pillars in so grand array",
  "And your central girders, which seem to the eye",
  "To be almost towering to the sky.",
  "The greatest wonder of the day,",
  "And a great beautification to the River Tay,",
  "Most beautiful to be seen,",
  "Near by Dundee and the Magdalen Green.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "That has caused the Emperor of Brazil to leave",
  "His home far away, incognito in his dress,",
  "And view thee ere he passed along en route to Inverness.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "The longest of the present day",
  "That has ever crossed o'er a tidal river stream,",
  "Most gigantic to be seen,",
  "Near by Dundee and the Magdalen Green.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "Which will cause great rejoicing on the opening day",
  "And hundreds of people will come from far away,",
  "Also the Queen, most gorgeous to be seen,",
  "Near by Dundee and the Magdalen Green.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "And prosperity to Provost Cox, who has given",
  "Thirty thousand pounds and upwards away",
  "In helping to erect the Bridge of the Tay,",
  "Most handsome to be seen,",
  "Near by Dundee and the Magdalen Green.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "I hope that God will protect all passengers",
  "By night and by day,",
  "And that no accident will befall them while crossing",
  "The Bridge of the Silvery Tay,",
  "For that would be most awful to be seen",
  "Near by Dundee and the Magdalen Green.",
  "",
  "Beautiful Railway Bridge of the Silvery Tay!",
  "And prosperity to Messrs Bouche and Grothe,",
  "The famous engineers of the present day,",
  "Who have succeeded in erecting the Railway",
  "Bridge of the Silvery Tay,",
  "Which stands unequalled to be seen",
  "Near by Dundee and the Magdalen Green.",
  ""
]