module.exports = [
  "In that soft season, when descending showers",
  "Call forth the greens, and wake the rising flowers;",
  "When opening buds salute the welcome day,",
  "And earth relenting feels the genial ray;",
  "As balmy sleep had charm'd my cares to rest,",
  "And love itself was banish'd from my breast,",
  "(What time the morn mysterious visions brings,",
  "While purer slumbers spread their golden wings),",
  "A train of phantoms in wild order rose,",
  "And, join'd, this intellectual scene compose.",
  "",
  "I stood, methought, betwixt earth, seas, and skies;",
  "The whole creation open to my eyes:",
  "In air self-balanced hung the globe below,",
  "Where mountains rise and circling oceans flow;",
  "Here naked rocks, and empty wastes were seen,",
  "There towery cities, and the forests green:",
  "Here sailing ships delight the wandering eyes:",
  "There trees, and intermingled temples rise;",
  "Now a clear sun the shining scene displays,",
  "The transient landscape now in clouds decays.",
  "",
  "O'er the wide prospect, as I gazed around,",
  "Sudden I heard a wild promiscuous sound,",
  "Like broken thunders that at distance roar,",
  "Or billows murmuring on the hollow shore:",
  "Then gazing up, a glorious pile beheld,",
  "Whose towering summit ambient clouds conceal'd.",
  "High on a rock of ice the structure lay,",
  "Steep its ascent, and slippery was the way;",
  "The wondrous rock like Parian marble shone,",
  "And seem'd, to distant sight, of solid stone.",
  "Inscriptions here of various names I view'd,",
  "The greater part by hostile time subdued;",
  "Yet wide was spread their fame in ages past,",
  "And poets once had promised they should last.",
  "Some fresh engraved appear'd of wits renown'd;",
  "I look'd again, nor could their trace be found.",
  "Critics I saw, that other names deface,",
  "And fix their own, with labour, in their place:",
  "Their own, like others, soon their place resign'd,",
  "Or disappear'd, and left the first behind.",
  "Nor was the work impair'd by storms alone,",
  "But felt the approaches of too warm a sun;",
  "For Fame, impatient of extremes, decays",
  "Not more by envy than excess of praise.",
  "Yet part no injuries of heaven could feel,",
  "Like crystal faithful to the graving steel:",
  "The rock's high summit, in the temple's shade,",
  "Nor heat could melt, nor beating storm invade.",
  "Their names inscribed unnumber'd ages past",
  "From time's first birth, with time itself shall last;",
  "These ever new, nor subject to decays,",
  "Spread, and grow brighter with the length of days.",
  "",
  "So Zembla's rocks (the beauteous work of frost)",
  "Rise white in air, and glitter o'er the coast;",
  "Pale suns, unfelt, at distance roll away,",
  "And on the impassive ice the lightnings play;",
  "Eternal snows the growing mass supply,",
  "Till the bright mountains prop the incumbent sky:",
  "As Atlas fix'd, each hoary pile appears,",
  "The gather'd winter of a thousand years.",
  "",
  "On this foundation Fame's high temple stands.",
  "Stupendous pile! not rear'd by mortal hands.",
  "Whate'er proud Rome or artful Greece beheld,",
  "Or elder Babylon, its frame excell'd.",
  "Four faces had the dome, and every face",
  "Of various structure, but of equal grace;",
  "Four brazen gates, on columns lifted high,",
  "Salute the different quarters of the sky.",
  "Here fabled chiefs in darker ages born,",
  "Or worthies old, whom arms or arts adorn,",
  "Who cities raised, or tamed a monstrous race,",
  "The walls in venerable order grace;",
  "Heroes in animated marble frown,",
  "And legislators seem to think in stone.",
  "",
  "Westward, a sumptuous frontispiece appear'd,",
  "On Doric pillars of white marble rear'd,",
  "Crown'd with an architrave of antique mould,",
  "And sculpture rising on the roughen'd gold.",
  "In shaggy spoils here Theseus was beheld,",
  "And Perseus dreadful with Minerva's shield:",
  "There great Alcides stooping with his toil,",
  "Rests on his club, and holds th' Hesperian spoil.",
  "Here Orpheus sings; trees, moving to the sound,",
  "Start from their roots, and form a shade around;",
  "Amphion there the loud creating lyre",
  "Strikes, and behold a sudden Thebes aspire!",
  "Cythæron's echoes answer to his call,",
  "And half the mountain rolls into a wall:",
  "There might you see the lengthening spires ascend,",
  "The domes swell up, the widening arches bend,",
  "The growing towers, like exhalations rise,",
  "And the huge columns heave into the skies.",
  "",
  "The eastern front was glorious to behold,",
  "With diamond flaming, and barbaric gold.",
  "There Ninus shone, who spread the Assyrian fame,",
  "And the great founder of the Persian name:",
  "There in long robes the royal Magi stand,",
  "Grave Zoroaster waves the circling wand,",
  "The sage Chaldeans robed in white appear'd,",
  "And Brachmans, deep in desert woods revered.",
  "These stopp'd the moon, and call'd the unbodied shades",
  "To midnight banquets in the glimmering glades;",
  "Made visionary fabrics round them rise,",
  "And airy spectres skim before their eyes;",
  "Of talismans and sigils knew the power,",
  "And careful watch'd the planetary hour.",
  "Superior, and alone, Confucius stood,",
  "Who taught that useful science--to be good.",
  "",
  "But on the south, a long majestic race",
  "Of Egypt's priests the gilded niches grace,",
  "Who measured earth, described the starry spheres,",
  "And traced the long records of lunar years.",
  "High on his car Sesostris struck my view,",
  "Whom sceptred slaves in golden harness drew:",
  "His hands a bow and pointed javelin hold;",
  "His giant limbs are arm'd in scales of gold.",
  "Between the statues obelisks were placed,",
  "And the learn'd walls with hieroglyphics graced.",
  "",
  "Of Gothic structure was the northern side,",
  "O'erwrought with ornaments of barbarous pride.",
  "There huge Colosses rose, with trophies crown'd,",
  "And Runic characters were graved around.",
  "There sat Zamolxis with erected eyes,",
  "And Odin here in mimic trances dies.",
  "There on rude iron columns, smear'd with blood,",
  "The horrid forms of Seythian heroes stood,",
  "Druids and Bards (their once loud harps unstrung)",
  "And youths that died to be by poets sung.",
  "These, and a thousand more of doubtful fame,",
  "To whom old fables gave a lasting name,",
  "In ranks adorn'd the temple's outward face;",
  "The wall, in lustre and effect like glass,",
  "Which o'er each object casting various dyes,",
  "Enlarges some, and others multiplies:",
  "Nor void of emblem was the mystic wall,",
  "For thus romantic Fame increases all.",
  "",
  "The temple shakes, the sounding gates unfold",
  "Wide vaults appear, and roofs of fretted gold:",
  "Raised on a thousand pillars, wreathed around",
  "With laurel foliage, and with eagles crown'd:",
  "Of bright, transparent beryl were the walls,",
  "The friezes gold, and gold the capitals:",
  "As heaven with stars, the roof with jewels glows,",
  "And ever-living lamps depend in rows.",
  "Full in the passage of each spacious gate,",
  "The sage historians in white garments wait;",
  "Graved o'er their seats the form of Time was found,",
  "His scythe reversed, and both his pinions bound.",
  "Within stood heroes, who through loud alarms",
  "In bloody fields pursued renown in arms.",
  "High on a throne, with trophies charged, I view'd",
  "The youth that all things but himself subdued;",
  "His feet on sceptres and tiaras trod,",
  "And his horn'd head belied the Libyan god.",
  "There Cæsar, graced with both Minervas, shone;",
  "Cæsar, the world's great master, and his own;",
  "Unmoved, superior still in every state,",
  "And scarce detested in his country's fate.",
  "But chief were those, who not for empire fought,",
  "But with their toils their people's safety bought:",
  "High o'er the rest Epaminondas stood;",
  "Timoleon, glorious in his brother's blood;",
  "Bold Scipio, saviour of the Roman state;",
  "Great in his triumphs, in retirement great;",
  "And wise Aurelius, in whose well-taught mind,",
  "With boundless power unbounded virtue join'd,",
  "His own strict judge, and patron of mankind.",
  "",
  "Much-suffering heroes next their honours claim,",
  "Those of less noisy, and less guilty fame,",
  "Fair Virtue's silent train: supreme of these",
  "Here ever shines the godlike Socrates:",
  "He whom ungrateful Athens could expel,",
  "At all times just, but when he sign'd the shell:",
  "Here his abode the martyr'd Phocion claims,",
  "With Agis, not the last of Spartan names:",
  "Unconquer'd Cato shows the wound he tore,",
  "And Brutus his ill Genius meets no more.",
  "",
  "But in the centre of the hallow'd choir,",
  "Six pompous columns o'er the rest aspire;",
  "Around the shrine itself of Fame they stand,",
  "Hold the chief honours, and the fane command.",
  "High on the first, the mighty Homer shone;",
  "Eternal adamant composed his throne;",
  "Father of verse! in holy fillets dress'd,",
  "His silver beard waved gently o'er his breast;",
  "Though blind, a boldness in his looks appears;",
  "In years he seem'd, but not impair'd by years.",
  "The wars of Troy were round the pillar seen:",
  "Here fierce Tydides wounds the Cyprian Queen;",
  "Here Hector, glorious from Patroclus' fall,",
  "Here dragg'd in triumph round the Trojan wall:",
  "Motion and life did every part inspire,",
  "Bold was the work, and proved the master's fire;",
  "A strong expression most he seem'd to affect,",
  "And here and there disclosed a brave neglect.",
  "",
  "A golden column next in rank appear'd,",
  "On which a shrine of purest gold was rear'd;",
  "Finish'd the whole, and labour'd every part,",
  "With patient touches of unwearied art:",
  "The Mantuan there in sober triumph sate,",
  "Composed his posture, and his look sedate;",
  "On Homer still he fix'd a reverend eye,",
  "Great without pride, in modest majesty.",
  "In living sculpture on the sides were spread",
  "The Latian wars, and haughty Turnus dead;",
  "Eliza stretch'd upon the funeral pyre,",
  "Æneas bending with his aged sire:",
  "Troy flamed in burning gold, and o'er the throne,",
  "ARMS AND THE MAN in golden cyphers shone.",
  "",
  "Four swans sustain a car of silver bright,",
  "With heads advanced, and pinions stretch'd for flight:",
  "Here, like some furious prophet, Pindar rode,",
  "And seem'd to labour with the inspiring god.",
  "Across the harp a careless hand he flings,",
  "And boldly sinks into the sounding strings.",
  "The figured games of Greece the column grace,",
  "Neptune and Jove survey the rapid race.",
  "The youths hang o'er their chariots as they run;",
  "The fiery steeds seem starting from the stone;",
  "The champions in distorted postures threat;",
  "And all appear'd irregularly great.",
  "",
  "Here happy Horace tuned the Ausonian lyre",
  "To sweeter sounds, and temper'd Pindar's fire:",
  "Pleased with Alcæus' manly rage t' infuse",
  "The softer spirit of the Sapphic Muse.",
  "The polish'd pillar different sculptures grace;",
  "A work outlasting monumental brass.",
  "Here smiling Loves and Bacchanals appear,",
  "The Julian star, and great Augustus here;",
  "The doves that round the infant poet spread",
  "Myrtles and bays, hung hovering o'er his head.",
  "",
  "Here in a shrine that cast a dazzling light,",
  "Sat, fix'd in thought, the mighty Stagyrite;",
  "His sacred head a radiant zodiac crown'd,",
  "And various animals his side surround;",
  "His piercing eyes, erect, appear to view",
  "Superior worlds, and look all Nature through.",
  "",
  "With equal rays immortal Tully shone,",
  "The Roman rostra deck'd the Consul's throne:",
  "Gathering his flowing robe, he seem'd to stand",
  "In act to speak, and graceful stretch'd his hand.",
  "Behind, Rome's Genius waits with civic crowns,",
  "And the great Father of his country owns.",
  "",
  "These massy columns in a circle rise,",
  "O'er which a pompous dome invades the skies:",
  "Scarce to the top I stretch'd my aching sight,",
  "So large it spread, and swell'd to such a height.",
  "Full in the midst, proud Fame's imperial seat",
  "With jewels blazed, magnificently great;",
  "The vivid emeralds there revive the eye,",
  "The flaming rubies show their sanguine dye,",
  "Bright azure rays from lively sapphires stream,",
  "And lucid amber casts a golden gleam.",
  "With various-colour'd light the pavement shone,",
  "And all on fire appear'd the glowing throne;",
  "The dome's high arch reflects the mingled blaze,",
  "And forms a rainbow of alternate rays.",
  "When on the goddess first I cast my sight,",
  "Scarce seem'd her stature of a cubit's height;",
  "But swell'd to larger size, the more I gazed,",
  "Till to the roof her towering front she raised.",
  "With her, the temple every moment grew,",
  "And ampler vistas open'd to my view:",
  "Upward the columns shoot, the roofs ascend,",
  "And arches widen, and long aisles extend.",
  "Such was her form as ancient bards have told,",
  "Wings raise her arms, and wings her feet infold;",
  "A thousand busy tongues the goddess bears,",
  "A thousand open eyes, and thousand listening ears.",
  "Beneath, in order ranged, the tuneful Nine",
  "(Her virgin handmaids) still attend the shrine:",
  "With eyes on Fame for ever fix'd, they sing;",
  "For Fame they raise the voice, and tune the string;",
  "With Time's first birth began the heavenly lays,",
  "And last, eternal, through the length of days.",
  "",
  "Around these wonders as I cast a look,",
  "The trumpet sounded, and the temple shook,",
  "And all the nations, summon'd at the call,",
  "From different quarters fill the crowded hall:",
  "Of various tongues the mingled sounds were heard",
  "In various garbs promiscuous throngs appear'd;",
  "Thick as the bees, that with the spring renew",
  "Their flowery toils, and sip the fragrant dew,",
  "When the wing'd colonies first tempt the sky,",
  "O'er dusky fields and shaded waters fly,",
  "Or settling, seize the sweets the blossoms yield,",
  "And a low murmur runs along the field.",
  "Millions of suppliant crowds the shrine attend,",
  "And all degrees before the goddess bend;",
  "The poor, the rich, the valiant, and the sage,",
  "And boasting youth, and narrative old age.",
  "Their pleas were different, their request the same:",
  "For good and bad alike are fond of Fame.",
  "Some she disgraced, and some with honours crown'd;",
  "Unlike successes equal merits found.",
  "Thus her blind sister, fickle Fortune, reigns,",
  "And, undiscerning, scatters crowns and chains.",
  "",
  "First at the shrine the learnèd world appear,",
  "And to the goddess thus prefer their prayer:",
  "'Long have we sought to instruct and please mankind,",
  "With studies pale, with midnight vigils blind;",
  "But thank'd by few, rewarded yet by none,",
  "We here appeal to thy superior throne;",
  "On wit and learning the just prize bestow,",
  "For fame is all we must expect below.'",
  "",
  "The goddess heard, and bade the Muses raise",
  "The golden trumpet of eternal praise:",
  "From pole to pole the winds diffuse the sound,",
  "That fills the circuit of the world around;",
  "Not all at once, as thunder breaks the cloud;",
  "The notes at first were rather sweet than loud:",
  "By just degrees they every moment rise,",
  "Fill the wide earth, and gain upon the skies.",
  "At every breath were balmy odours shed,",
  "Which still grew sweeter as they wider spread;",
  "Less fragrant scents the unfolding rose exhales,",
  "Or spices breathing in Arabian gales.",
  "",
  "Next these, the good and just, an awful train,",
  "Thus on their knees address the sacred fane:",
  "'Since living virtue is with envy cursed,",
  "And the best men are treated like the worst,",
  "Do thou, just goddess, call our merits forth,",
  "And give each deed the exact intrinsic worth.'",
  "",
  "'Not with bare justice shall your act be crown'd,'",
  "(Said Fame), 'but high above desert renown'd:",
  "Let fuller notes the applauding world amaze,",
  "And the loud clarion labour in your praise.'",
  "",
  "This band dismiss'd, behold, another crowd",
  "Preferr'd the same request, and lowly bow'd;",
  "The constant tenor of whose well-spent days",
  "No less deserved a just return of praise.",
  "But straight the direful trump of Slander sounds;",
  "Through the big dome the doubling thunder bounds;",
  "Loud as the burst of cannon rends the skies,",
  "The dire report through every region flies,",
  "In every ear incessant rumours rung,",
  "And gathering scandals grew on every tongue.",
  "From the black trumpet's rusty concave broke",
  "Sulphureous flames, and clouds of rolling smoke:",
  "The poisonous vapour blots the purple skies,",
  "And withers all before it as it flies.",
  "",
  "A troop came next, who crowns and armour wore,",
  "And proud defiance in their looks they bore:",
  "'For thee' (they cried), 'amidst alarms and strife,",
  "We sail'd in tempests down the stream of life;",
  "For thee whole nations fill'd with flames and blood,",
  "And swam to empire through the purple flood.",
  "Those ills we dared, thy inspiration own,",
  "What virtue seem'd, was done for thee alone.'",
  "",
  "'Ambitious fools!' (the Queen replied, and frown'd)",
  "'Be all your acts in dark oblivion drown'd;",
  "There sleep forgot, with mighty tyrants gone,",
  "Your statues moulder'd, and your names unknown!'",
  "A sudden cloud straight snatch'd them from my sight,",
  "And each majestic phantom sunk in night.",
  "",
  "Then came the smallest tribe I yet had seen;",
  "Plain was their dress, and modest was their mien.",
  "'Great idol of mankind! we neither claim",
  "The praise of merit, nor aspire to fame;",
  "But safe in deserts from the applause of men,",
  "Would die unheard of, as we lived unseen;",
  "'Tis all we beg thee, to conceal from sight",
  "Those acts of goodness which themselves requite.",
  "Oh let us still the secret joy partake,",
  "To follow virtue even for virtue's sake.'",
  "",
  "'And live there men, who slight immortal Fame?",
  "Who then with incense shall adore our name?",
  "But, mortals! know, 'tis still our greatest pride",
  "To blaze those virtues which the good would hide.",
  "Rise, Muses, rise! add all your tuneful breath;",
  "These must not sleep in darkness and in death.'",
  "She said: in air the trembling music floats,",
  "And on the winds triumphant swell the notes;",
  "So soft, though high, so loud, and yet so clear,",
  "Even listening angels lean'd from heaven to hear:",
  "To furthest shores the ambrosial spirit flies,",
  "Sweet to the world, and grateful to the skies.",
  "",
  "Next these a youthful train their vows express'd,",
  "With feathers crown'd, with gay embroidery dress'd:",
  "'Hither' (they cried) 'direct your eyes, and see",
  "The men of pleasure, dress, and gallantry;",
  "Ours is the place at banquets, balls, and plays,",
  "Sprightly our nights, polite are all our days;",
  "Courts we frequent, where 'tis our pleasing care",
  "To pay due visits, and address the fair:",
  "In fact, 'tis true, no nymph we could persuade,",
  "But still in fancy vanquish'd every maid;",
  "Of unknown duchesses lewd tales we tell,",
  "Yet, would the world believe us, all were well.",
  "The joy let others have, and we the name,",
  "And what we want in pleasure, grant in fame.'",
  "",
  "The Queen assents, the trumpet rends the skies,",
  "And at each blast a lady's honour dies.",
  "",
  "Pleased with the strange success, vast numbers press'd",
  "Around the shrine, and made the same request:",
  "'What! you,' (she cried) 'unlearn'd in arts to please,",
  "Slaves to yourselves, and even fatigued with ease,",
  "Who lose a length of undeserving days,",
  "Would you usurp the lover's dear-bought praise?",
  "To just contempt, ye vain pretenders, fall,",
  "The people's fable and the scorn of all.'",
  "Straight the black clarion sends a horrid sound,",
  "Loud laughs burst out, and bitter scoffs fly round,",
  "Whispers are heard, with taunts reviling loud,",
  "And scornful hisses run through all the crowd.",
  "",
  "Last, those who boast of mighty mischiefs done,",
  "Enslave their country, or usurp a throne;",
  "Or who their glory's dire foundation laid",
  "On sovereigns ruin'd, or on friends betray'd;",
  "Calm, thinking villains, whom no faith could fix,",
  "Of crooked counsels, and dark politics;",
  "Of these a gloomy tribe surround the throne,",
  "And beg to make the immortal treasons known.",
  "The trumpet roars, long flaky flames expire,",
  "With sparks, that seem'd to set the world on fire.",
  "At the dread sound, pale mortals stood aghast,",
  "And startled Nature trembled with the blast.",
  "",
  "This having heard and seen, some Power unknown",
  "Straight changed the scene, and snatch'd me from the throne.",
  "Before my view appear'd a structure fair,",
  "Its site uncertain, if in earth or air;",
  "With rapid motion turn'd the mansion round;",
  "With ceaseless noise the ringing walls resound;",
  "Not less in number were the spacious doors,",
  "Than leaves on trees, or sands upon the shores;",
  "Which still unfolded stand, by night, by day,",
  "Pervious to winds, and open every way.",
  "As flames by nature to the skies ascend,",
  "As weighty bodies to the centre tend,",
  "As to the sea returning rivers roll,",
  "And the touch'd needle trembles to the pole;",
  "Hither, as to their proper place, arise",
  "All various sounds from earth, and seas, and skies,",
  "Or spoke aloud, or whisper'd in the ear;",
  "Nor ever silence, rest, or peace is here.",
  "As on the smooth expanse of crystal lakes",
  "The sinking stone at first a circle makes;",
  "The trembling surface by the motion stirr'd,",
  "Spreads in a second circle, then a third;",
  "Wide, and more wide, the floating rings advance,",
  "Fill all the watery plain, and to the margin dance:",
  "Thus every voice and sound, when first they break,",
  "On neighbouring air a soft impression make;",
  "Another ambient circle then they move;",
  "That, in its turn, impels the next above;",
  "Through undulating air the sounds are sent,",
  "And spread o'er all the fluid element.",
  "",
  "There various news I heard of love and strife,",
  "Of peace and war, health, sickness, death, and life,",
  "Of loss and gain, of famine and of store,",
  "Of storms at sea, and travels on the shore,",
  "Of prodigies, and portents seen in air,",
  "Of fires and plagues, and stars with blazing hair,",
  "Of turns of fortune, changes in the state,",
  "The falls of favourites, projects of the great,",
  "Of old mismanagements, taxations new:",
  "All neither wholly false, nor wholly true.",
  "",
  "Above, below, without, within, around,",
  "Confused, unnumber'd multitudes are found,",
  "Who pass, repass, advance, and glide away;",
  "Hosts raised by fear, and phantoms of a day:",
  "Astrologers, that future fates foreshow;",
  "Projectors, quacks, and lawyers not a few;",
  "And priests, and party-zealots, numerous bands",
  "With home-born lies, or tales from foreign lands;",
  "Each talk'd aloud, or in some secret place,",
  "And wild impatience stared in every face.",
  "The flying rumours gather'd as they roll'd,",
  "Scarce any tale was sooner heard than told;",
  "And all who told it added something new,",
  "And all who heard it made enlargements too,",
  "In every ear it spread, on every tongue it grew.",
  "Thus flying east and west, and north and south,",
  "News travell'd with increase from mouth to mouth.",
  "So from a spark, that kindled first by chance,",
  "With gathering force the quickening flames advance;",
  "Till to the clouds their curling heads aspire,",
  "And towers and temples sink in floods of fire.",
  "When thus ripe lies are to perfection sprung,",
  "Full grown, and fit to grace a mortal tongue,",
  "Through thousand vents, impatient, forth they flow,",
  "And rush in millions on the world below.",
  "Fame sits aloft, and points them out their course,",
  "Their date determines, and prescribes their force:",
  "Some to remain, and some to perish soon;",
  "Or wane and wax alternate like the moon.",
  "Around, a thousand wingèd wonders fly,",
  "Born by the trumpet's blast, and scatter'd through the sky.",
  "",
  "There, at one passage, oft you might survey",
  "A lie and truth contending for the way;",
  "And long 'twas doubtful, both so closely pent,",
  "Which first should issue through the narrow vent:",
  "At last agreed, together out they fly,",
  "Inseparable now, the truth and lie;",
  "The strict companions are for ever join'd,",
  "And this or that unmix'd, no mortal e'er shall find.",
  "",
  "While thus I stood, intent to see and hear,",
  "One came, methought, and whisper'd in my ear:",
  "'What could thus high thy rash ambition raise?",
  "Art thou, fond youth, a candidate for praise?'",
  "",
  "''Tis true,' said I, 'not void of hopes I came,",
  "For who so fond as youthful bards of fame?",
  "But few, alas! the casual blessing boast,",
  "So hard to gain, so easy to be lost.",
  "How vain that second life in others' breath,",
  "The estate which wits inherit after death!",
  "Ease, health, and life, for this they must resign,",
  "(Unsure the tenure, but how vast the fine!)",
  "The great man's curse, without the gains, endure,",
  "Be envied, wretched, and be flatter'd, poor;",
  "All luckless wits their enemies profess'd,",
  "And all successful, jealous friends at best.",
  "Nor Fame I slight, nor for her favours call;",
  "She comes unlook'd for, if she comes at all.",
  "But if the purchase costs so dear a price,",
  "As soothing folly, or exalting vice;",
  "Oh! if the Muse must flatter lawless sway,",
  "And follow still where fortune leads the way;",
  "Or if no basis bear my rising name,",
  "But the fallen ruins of another's fame;",
  "Then teach me, Heaven! to scorn the guilty bays,",
  "Drive from my breast that wretched lust of praise,",
  "Unblemish'd let me live, or die unknown;",
  "Oh, grant an honest fame, or grant me none!'",
  ""
]