module.exports = [
  "Once more the gate behind me falls;",
  "Once more before my face",
  "I see the moulder'd Abbey-walls,",
  "That stand within the chace.",
  "",
  "Beyond the lodge the city lies,",
  "Beneath its drift of smoke;",
  "And ah! with what delighted eyes",
  "I turn to yonder oak.",
  "",
  "For when my passion first began,",
  "Ere that, which in me burn'd,",
  "The love, that makes me thrice a man,",
  "Could hope itself return'd;",
  "",
  "To yonder oak within the field",
  "I spoke without restraint,",
  "And with a larger faith appeal'd",
  "Than Papist unto Saint.",
  "",
  "For oft I talk'd with him apart",
  "And told him of my choice,",
  "Until he plagiarized a heart,",
  "And answer'd with a voice.",
  "",
  "Tho' what he whisper'd under Heaven",
  "None else could understand;",
  "I found him garrulously given,",
  "A babbler in the land.",
  "",
  "But since I heard him make reply",
  "Is many a weary hour;",
  "'Twere well to question him, and try",
  "If yet he keeps the power.",
  "",
  "Hail, hidden to the knees in fern,",
  "Broad Oak of Sumner-chace,",
  "Whose topmost branches can discern",
  "The roofs of Sumner-place!",
  "",
  "Say thou, whereon I carved her name,",
  "If ever maid or spouse,",
  "As fair as my Olivia, came",
  "To rest beneath thy boughs.---",
  "",
  "\"O Walter, I have shelter'd here",
  "Whatever maiden grace",
  "The good old Summers, year by year",
  "Made ripe in Sumner-chace:",
  "",
  "\"Old Summers, when the monk was fat,",
  "And, issuing shorn and sleek,",
  "Would twist his girdle tight, and pat",
  "The girls upon the cheek,",
  "",
  "\"Ere yet, in scorn of Peter's-pence,",
  "And number'd bead, and shrift,",
  "Bluff Harry broke into the spence",
  "And turn'd the cowls adrift:",
  "",
  "\"And I have seen some score of those",
  "Fresh faces that would thrive",
  "When his man-minded offset rose",
  "To chase the deer at five;",
  "",
  "\"And all that from the town would stroll,",
  "Till that wild wind made work",
  "In which the gloomy brewer's soul",
  "Went by me, like a stork:",
  "",
  "\"The slight she-slips of royal blood,",
  "And others, passing praise,",
  "Straight-laced, but all-too-full in bud",
  "For puritanic stays:",
  "",
  "\"And I have shadow'd many a group",
  "Of beauties, that were born",
  "In teacup-times of hood and hoop,",
  "Or while the patch was worn;",
  "",
  "\"And, leg and arm with love-knots gay",
  "About me leap'd and laugh'd",
  "The modish Cupid of the day,",
  "And shrill'd his tinsel shaft.",
  "",
  "\"I swear (and else may insects prick",
  "Each leaf into a gall)",
  "This girl, for whom your heart is sick,",
  "Is three times worth them all.",
  "",
  "\"For those and theirs, by Nature's law,",
  "Have faded long ago;",
  "But in these latter springs I saw",
  "Your own Olivia blow,",
  "",
  "\"From when she gamboll'd on the greens",
  "A baby-germ, to when",
  "The maiden blossoms of her teens",
  "Could number five from ten.",
  "",
  "\"I swear, by leaf, and wind, and rain,",
  "(And hear me with thine ears,)",
  "That, tho' I circle in the grain",
  "Five hundred rings of years---",
  "",
  "\"Yet, since I first could cast a shade,",
  "Did never creature pass",
  "So slightly, musically made,",
  "So light upon the grass:",
  "",
  "\"For as to fairies, that will flit",
  "To make the greensward fresh,",
  "I hold them exquisitely knit,",
  "But far too spare of flesh.\"",
  "",
  "Oh, hide thy knotted knees in fern,",
  "And overlook the chace;",
  "And from thy topmost branch discern",
  "The roofs of Sumner-place.",
  "",
  "But thou, whereon I carved her name,",
  "That oft hast heard my vows,",
  "Declare when last Olivia came",
  "To sport beneath thy boughs.",
  "",
  "\"O yesterday, you know, the fair",
  "Was holden at the town;",
  "Her father left his good arm-chair,",
  "And rode his hunter down.",
  "",
  "\"And with him Albert came on his.",
  "I look'd at him with joy:",
  "As cowslip unto oxlip is,",
  "So seems she to the boy.",
  "",
  "\"An hour had past---and, sitting straight",
  "Within the low-wheel'd chaise,",
  "Her mother trundled to the gate",
  "Behind the dappled grays.",
  "",
  "\"But as for her, she stay'd at home,",
  "And on the roof she went,",
  "And down the way you use to come,",
  "She look'd with discontent.",
  "",
  "\"She left the novel half-uncut",
  "Upon the rosewood shelf;",
  "She left the new piano shut:",
  "She could not please herseif",
  "",
  "\"Then ran she, gamesome as the colt,",
  "And livelier than a lark",
  "She sent her voice thro' all the holt",
  "Before her, and the park.",
  "",
  "\"A light wind chased her on the wing,",
  "And in the chase grew wild,",
  "As close as might be would he cling",
  "About the darling child:",
  "",
  "\"But light as any wind that blows",
  "So fleetly did she stir,",
  "The flower, she touch'd on, dipt and rose,",
  "And turn'd to look at her.",
  "",
  "\"And here she came, and round me play'd,",
  "And sang to me the whole",
  "Of those three stanzas that you made",
  "About my Ôgiant bole;'",
  "",
  "\"And in a fit of frolic mirth",
  "She strove to span my waist:",
  "Alas, I was so broad of girth,",
  "I could not be embraced.",
  "",
  "\"I wish'd myself the fair young beech",
  "That here beside me stands,",
  "That round me, clasping each in each,",
  "She might have lock'd her hands.",
  "",
  "\"Yet seem'd the pressure thrice as sweet",
  "As woodbine's fragile hold,",
  "Or when I feel about my feet",
  "The berried briony fold.\"",
  "",
  "O muffle round thy knees with fern,",
  "And shadow Sumner-chace!",
  "Long may thy topmost branch discern",
  "The roofs of Sumner-place!",
  "",
  "But tell me, did she read the name",
  "I carved with many vows",
  "When last with throbbing heart I came",
  "To rest beneath thy boughs?",
  "",
  "\"O yes, she wander'd round and round",
  "These knotted knees of mine,",
  "And found, and kiss'd the name she found,",
  "And sweetly murmur'd thine.",
  "",
  "\"A teardrop trembled from its source,",
  "And down my surface crept.",
  "My sense of touch is something coarse,",
  "But I believe she wept.",
  "",
  "\"Then flush'd her cheek with rosy light,",
  "She glanced across the plain;",
  "But not a creature was in sight:",
  "She kiss'd me once again.",
  "",
  "\"Her kisses were so close and kind,",
  "That, trust me on my word,",
  "Hard wood I am, and wrinkled rind,",
  "But yet my sap was stirr'd:",
  "",
  "\"And even into my inmost ring",
  "A pleasure I discern'd,",
  "Like those blind motions of the Spring,",
  "That show the year is turn'd.",
  "",
  "\"Thrice-happy he that may caress",
  "The ringlet's waving balm---",
  "The cushions of whose touch may press",
  "The maiden's tender palm.",
  "",
  "\"I, rooted here among the groves",
  "But languidly adjust",
  "My vapid vegetable loves",
  "With anthers and with dust:",
  "",
  "\"For ah! my friend, the days were brief",
  "Whereof the poets talk,",
  "When that, which breathes within the leaf,",
  "Could slip its bark and walk.",
  "",
  "\"But could I, as in times foregone,",
  "From spray, and branch, and stem,",
  "Have suck'd and gather'd into one",
  "The life that spreads in them,",
  "",
  "\"She had not found me so remiss;",
  "But lightly issuing thro',",
  "I would have paid her kiss for kiss,",
  "With usury thereto.\"",
  "",
  "O flourish high, with leafy towers,",
  "And overlook the lea,",
  "Pursue thy loves among the bowers",
  "But leave thou mine to me.",
  "",
  "O flourish, hidden deep in fern,",
  "Old oak, I love thee well;",
  "A thousand thanks for what I learn",
  "And what remains to tell.",
  "",
  "\" ÔTis little more: the day was warm;",
  "At last, tired out with play,",
  "She sank her head upon her arm",
  "And at my feet she lay.",
  "",
  "\"Her eyelids dropp'd their silken eaves",
  "I breathed upon her eyes",
  "Thro' all the summer of my leaves",
  "A welcome mix'd with sighs.",
  "",
  "\"I took the swarming sound of life---",
  "The music from the town---",
  "The murmurs of the drum and fife",
  "And lull'd them in my own.",
  "",
  "\"Sometimes I let a sunbeam slip,",
  "To light her shaded eye;",
  "A second flutter'd round her lip",
  "Like a golden butterfly;",
  "",
  "\"A third would glimmer on her neck",
  "To make the necklace shine;",
  "Another slid, a sunny fleck,",
  "From head to ankle fine,",
  "",
  "\"Then close and dark my arms I spread,",
  "And shadow'd all her rest---",
  "Dropt dews upon her golden head,",
  "An acorn in her breast.",
  "",
  "\"But in a pet she started up,",
  "And pluck'd it out, and drew",
  "My little oakling from the cup,",
  "And flung him in the dew.",
  "",
  "\"And yet it was a graceful gift---",
  "I felt a pang within",
  "As when I see the woodman lift",
  "His axe to slay my kin.",
  "",
  "\"I shook him down because he was",
  "The finest on the tree.",
  "He lies beside thee on the grass.",
  "O kiss him once for me.",
  "",
  "\"O kiss him twice and thrice for me,",
  "That have no lips to kiss,",
  "For never yet was oak on lea",
  "Shall grow so fair as this.'",
  "",
  "Step deeper yet in herb and fern,",
  "Look further thro' the chace,",
  "Spread upward till thy boughs discern",
  "The front of Sumner-place.",
  "",
  "This fruit of thine by Love is blest,",
  "That but a moment lay",
  "Where fairer fruit of Love may rest",
  "Some happy future day.",
  "",
  "I kiss it twice, I kiss it thrice,",
  "The warmth it thence shall win",
  "To riper life may magnetise",
  "The baby-oak within.",
  "",
  "But thou, while kingdoms overset,",
  "Or lapse from hand to hand,",
  "Thy leaf shall never fail, nor yet",
  "Thine acorn in the land.",
  "",
  "May never saw dismember thee,",
  "Nor wielded axe disjoint,",
  "That art the fairest-spoken tree",
  "From here to Lizard-point.",
  "",
  "O rock upon thy towery-top",
  "All throats that gurgle sweet!",
  "All starry culmination drop",
  "Balm-dews to bathe thy feet!",
  "",
  "All grass of silky feather grow---",
  "And while he sinks or swells",
  "The full south-breeze around thee blow",
  "The sound of minster bells.",
  "",
  "The fat earth feed thy branchy root,",
  "That under deeply strikes!",
  "The northern morning o'er thee shoot,",
  "High up, in silver spikes!",
  "",
  "Nor ever lightning char thy grain,",
  "But, rolling as in sleep,",
  "Low thunders bring the mellow rain,",
  "That makes thee broad and deep!",
  "",
  "And hear me swear a solemn oath,",
  "That only by thy side",
  "Will I to Olive plight my troth,",
  "And gain her for my bride.",
  "",
  "And when my marriage morn may fall,",
  "She, Dryad-like, shall wear",
  "Alternate leaf and acorn-ball",
  "In wreath about her hair.",
  "",
  "And I will work in prose and rhyme,",
  "And praise thee more in both",
  "Than bard has honour'd beech or lime,",
  "Or that Thessalian growth,",
  "",
  "In which the swarthy ringdove sat,",
  "And mystic sentence spoke;",
  "And more than England honours that,",
  "Thy famous brother-oak,",
  "",
  "Wherein the younger Charles abode",
  "Till all the paths were dim,",
  "And far below the Roundhead rode,",
  "And humm'd a surly hymn.",
  ""
]