module.exports = [
  "A Poem upon the Death of His Late Highness the Lord Protector",
  "",
  "That Providence which had so long the care",
  "Of Cromwell's head, and numbered every hair,",
  "Now in itself (the glass where all appears)",
  "Had seen the period of his golden years:",
  "And thenceforh only did attend to trace",
  "What death might least so fair a life deface.",
  "",
  "The people, which what most they fear esteem,",
  "Death when more horrid, so more noble deem,",
  "And blame the last act, like spectators vain,",
  "Unless the prince whom they applaud be slain.",
  "Nor fate indeed can well refuse that right",
  "To those that lived in war, to die in fight.",
  "",
  "But long his valour none had left that could",
  "Endanger him, or clemency that would.",
  "And he whom Nature all for peace had made,",
  "But angry heaven unto war had swayed,",
  "And so less useful where he most desired,",
  "For what he least affected was admired,",
  "Deservиd yet an end whose every part,",
  "Should speak the wondrous softness of his heart.",
  "",
  "To Love and Grief the fatal writ was 'signed;",
  "(Those nobler weaknesses of human kind,",
  "From which those powers that issued the decree,",
  "Although immortal, found they were not free),",
  "That they, to whom his breast still open lies,",
  "In gentle passions should his death disguise:",
  "And leave succeeding ages cause to mourn,",
  "As long as Grief shall weep, or Love shall burn.",
  "",
  "Straight does a slow and languishing disease",
  "Eliza, Nature's and his darling, seize.",
  "Her when an infant, taken with her charms,",
  "He oft would flourish in his mighty arms,",
  "And, lest their force the tender burden wrong,",
  "Slacken the vigour of his muscles strong;",
  "Then to the Mother's breast her softly move,",
  "Which while she drained of milk, she filled with love.",
  "But as with riper years her virtue grew,",
  "And every minute adds a lustre new,",
  "When with meridian height her beauty shined,",
  "And thorough that sparkled her fairer mind,",
  "When she with smiles serene in words discreet",
  "His hidden soul at ever turn could meet;",
  "Then might y'ha' daily his affection spied,",
  "Doubling that knot which destiny had tied,",
  "While they by sense, not knowing, comprehend",
  "How on each other both their fates depend.",
  "With her each day the pleasing hours he shares,",
  "And at her aspect calms his growing cares;",
  "Or with a grandsire's joy her children sees",
  "Hanging about her neck or at his knees.",
  "Hold fast, dear infants, hold them both or none;",
  "This will not stay when once the other's gone.",
  "",
  "A silent fire now wastes those limbs of wax,",
  "And him within his tortured image racks.",
  "So the flower withering which the garden crowned,",
  "The sad root pines in secret under ground.",
  "Each groan he doubled and each sigh he sighed,",
  "Repeated over to the restless night.",
  "No trembling string composed to numbers new,",
  "Answers the touch in notes more sad, more true.",
  "She, lest he grieve, hides what she can her pains,",
  "And he to lessen hers his sorrow feigns:",
  "Yet both perceived, yet both concealed their skills,",
  "And so diminishing increased their ills:",
  "That whether by each other's grief they fell,",
  "Or on their own redoubled, none can tell.",
  "",
  "And now Eliza's purple locks were shorn,",
  "Where she so long her Father's fate had worn:",
  "And frequent lightning to her soul that flies,",
  "Divides the air, and opens all the skies:",
  "And now his life, suspended by her breath,",
  "Ran out impetuously to hasting death.",
  "Like polished mirrors, so his steely breast",
  "Had every figure of her woes expressed,",
  "And with the damp of her last gasp obscured,",
  "Had drawn such stains as were not to be cured.",
  "Fate could not either reach with single stroke,",
  "But the dear image fled, the mirror broke.",
  "",
  "Who now shall tell us more of mournful swans,",
  "Of halcyons kind, or bleeding pelicans?",
  "No downy breast did e'er so gently beat,",
  "Or fan with airy plumes so soft an heat.",
  "For he no duty by his height excused,",
  "Nor, though a prince, to be a man refused:",
  "But rather than in his Eliza's pain",
  "Not love, not grieve, would neither live nor reign:",
  "And in himself so oft immortal tried,",
  "Yet in compassion of another died.",
  "",
  "So have I seen a vine, whose lasting age",
  "Of many a winter hath survived the rage,",
  "Under whose shady tent men every year",
  "At its rich blood's expense their sorrow cheer,",
  "If some dear branch where it extends its life",
  "Chance to be pruned by an untimely knife,",
  "The parent-tree unto the grief succeeds,",
  "And through the wound its vital humour bleeds,",
  "Trickling in watery drops, whose flowing shape",
  "Weeps that it falls ere fixed into a grape.",
  "So the dry stock, no more that spreading vine,",
  "Frustrates the autumn and the hopes of wine.",
  "",
  "A secret cause does sure those signs ordain",
  "Foreboding princes' falls, and seldom vain.",
  "Whether some kinder powers that wish us well,",
  "What they above cannot prevent foretell;",
  "Or the great world do by consent presage,",
  "As hollow seas with future tempests rage;",
  "Or rather heaven, which us so long foresees,",
  "Their funerals celebrates while it decrees.",
  "But never yet was any human fate",
  "By Nature solemnized with so much state.",
  "He unconcerned the dreadful passage crossed;",
  "But, oh, what pangs that death did Nature cost!",
  "",
  "First the great thunder was shot off, and sent",
  "The signal from the starry battlement.",
  "The winds receive it, and its force outdo,",
  "As practising how they could thunder too;",
  "Out of the binder's hand the sheaves they tore,",
  "And thrashed the harvest in the airy floor;",
  "Or of huge trees, whose growth with his did rise,",
  "The deep foundations opened to the skies.",
  "Then heavy show'rs the wingиd tempests lead,",
  "And pour the deluge o'er the chaos' head.",
  "The race of warlike horses at his tomb",
  "Offer themselves in many a hecatomb;",
  "With pensive head towards the ground they fall,",
  "And helpless languish at the tainted stall.",
  "Numbers of men decrease with pains unknown,",
  "And hasten, not to see his death, their own.",
  "Such tortures all the elements unfixed,",
  "Troubled to part where so exactly mixed.",
  "And as through air his wasting spirits flowed,",
  "The universe laboured beneath their load.",
  "",
  "Nature, it seemed with him would Nature vie;",
  "He with Eliza. It with him would die,",
  "He without noise still travelled to his end,",
  "As silent suns to meet the night descend.",
  "The stars that for him fought had only power",
  "Left to determine now his final hour,",
  "Which, since they might not hinder, yet they cast",
  "To choose it worthy of his glories past.",
  "",
  "No part of time but bare his mark away",
  "Of honour; all the year was Cromwell's day:",
  "But this, of all the most ausicious found,",
  "Twice had in open field him victor crowned:",
  "When up the armиd mountains of Dunbar",
  "He marched, and through deep Severn ending war.",
  "What day should him eternize but the same",
  "That had before immortalized his name?",
  "That so who ere would at his death have joyed,",
  "In their own griefs might find themselves employed;",
  "But those that sadly his departure grieved,",
  "Yet joyed, remebering what he once achieved.",
  "And the last minute his victorious ghost",
  "Gave chase to Ligny on the Belgic coast.",
  "Here ended all his mortal toils: he laid",
  "And slept in place under the laurel shade.",
  "",
  "O Cromwell, Heaven's Favourite! To none",
  "Have such high honours from above been shown:",
  "For whom the elements we mourners see,",
  "And heaven itself would the great herald be,",
  "Which with more care set forth his obsequies",
  "Than those of Moses hid from human eyes,",
  "As jealous only here lest all be less,",
  "That we could to his memory express.",
  "Then let us to our course of mourning keep:",
  "Where heaven leads, 'tis piety to weep.",
  "Stand back, ye seas, and shrunk beneath the veil",
  "Of your abyss, with covered head bewail",
  "Your Monarch: we demand not your supplies",
  "To compass in our isle; our tears suffice:",
  "Since him away the dismal tempest rent,",
  "Who once more joined us to the continent;",
  "Who planted England on the Flandric shore,",
  "And stretched our frontier to the Indian ore;",
  "Whose greater truths obscure the fables old,",
  "Whether of British saints or Worthies told;",
  "And in a valour lessening Arthur's deeds,",
  "For holiness the Confessor exceeds.",
  "",
  "He first put arms into Religion's hand,",
  "And timorous Conscience unto Courage manned:",
  "The soldier taught that inward mail to wear,",
  "And fearing God how they should nothing fear.",
  "`Those strokes,' he said, `will pierce through all below",
  "Where those that strike from heaven fetch their blow.'",
  "Astonished armies did their flight prepare,",
  "And cities strong were stormиd by his prayer;",
  "Of that, forever Preston's field shall tell",
  "The story, and impregnable Clonmel.",
  "And where the sandy mountain Fenwick scaled,",
  "The sea between, yet hence his prayer prevailed.",
  "What man was ever so in heaven obeyed",
  "Since the commanded sun o'er Gideon stayed?",
  "In all his wars needs must he triumph when",
  "He conquered God still ere he fought with men:",
  "",
  "Hence, though in battle none so brave or fierce,",
  "Yet him the adverse steel could never pierce.",
  "Pity it seemed to hurt him more that felt",
  "Each wound himself which he to others dealt;",
  "Danger itself refusing to offend",
  "So loose an enemy, so fast a friend.",
  "",
  "Friendship, that sacred virtue, long does claim",
  "The first foundation of his house and name:",
  "But within one its narrow limits fall,",
  "His tenderness extended unto all.",
  "And that deep soul through every channel flows,",
  "Where kindly nature loves itself to lose.",
  "More strong affections never reason served,",
  "Yet still affected most what best deserved.",
  "If he Eliza loved to that degree,",
  "(Though who more worthy to be loved than she?)",
  "If so indulgent to his own, how dear",
  "To him the children of the highest were?",
  "For her he once did nature's tribute pay:",
  "For these his life adventured every day:",
  "And 'twould be found, could we his thoughts have cast,",
  "Their griefs struck deepest, if Eliza's last.",
  "",
  "What prudence more than human did he need",
  "To keep so dear, so differing minds agreed?",
  "The worser sort, as conscious of their ill,",
  "Lie weak and easy to the ruler's will;",
  "But to the good (too many or too few)",
  "All law is useless, all reward is due.",
  "Oh ill-advised, if not for love, for shame,",
  "Spare yet your own, if you neglect his fame;",
  "Lest others dare to think your zeal a mask,",
  "And you to govern, only heaven's task.",
  "",
  "Valour, religion, friendship, prudence died",
  "At once with him, and all that's good beside;",
  "And we death's refuse, nature's dregs, confined",
  "To loathsome life, alas! are left behind.",
  "Where we (so once we used) shall now no more",
  "To fetch the day, press about his chamber door--",
  "From which he issued with that awful state,",
  "It seemd Mars broke through Janus' double gate,",
  "Yet always tempered with an air so mild,",
  "No April suns that e'er so gently smiled--",
  "No more shall hear that powerful language charm,",
  "Whose force oft spared the labour of his arm:",
  "No more shall follow where he spent the days",
  "In war, in counsel, or in prayer and praise,",
  "Whose meanest acts he would himself advance,",
  "As ungirt David to the ark did dance.",
  "All, all is gone of our or his delight",
  "In horses fierce, wild deer, or armour bright;",
  "Francisca fair can nothing now but weep,",
  "Nor with soft notes shall sing his cares asleep.",
  "",
  "I saw him dead. A leaden slumber lies",
  "And mortal sleep over those wakeful eyes:",
  "Those gentle rays under the lids were fled,",
  "Which through his looks that piercing sweetness shed;",
  "That port which so majestic was and strong,",
  "Loose and deprived of vigour, stretched along:",
  "All withered, all discoloured, pale and wan--",
  "How much another thing, nor more that man?",
  "Oh human glory vain, oh death, oh wings,",
  "Oh worthless world, oh transitory things!",
  "",
  "Yet dwelt that greatnesss in his shape decayed,",
  "That still through dead, greater than death he laid:",
  "And in his altered face you something feign",
  "That threatens death he yet will live again.",
  "",
  "Not much unlike the sacred oak which shoots",
  "To heaven its branches and through earth its roots,",
  "Whose spacious bought are hung with trophies round,",
  "And honoured wreaths have oft the victor crowned.",
  "When angry Jove darts lightning through the air,",
  "At mortals' sins, nor his own plant will spare,",
  "(It groans, and bruises all below, that stood",
  "So many years the shelter of the wood.)",
  "The tree erewhile foreshortened to our view,",
  "When fall'n shows taller yet than as it grew:",
  "",
  "So shall his praise to after times increase,",
  "When truth shall be allowed, and faction cease,",
  "And his own shadows with him fall. The eye",
  "Detracts from object than itself more high:",
  "But when death takes them from that envied seat,",
  "Seeing how little, we confess how great.",
  "",
  "Thee, many ages hence in martial verse",
  "Shall the English soldier, ere he charge, rehearse,",
  "Singing of thee, inflame themselves to fight,",
  "And with the name of Cromwell, armies fright.",
  "As long as rivers to the seas shall run,",
  "As long as Cynthia shall relieve the sun,",
  "While stags shall fly unto the firests thick,",
  "While sheep delight the grassy downs to pick,",
  "As long as future times succeeds the past,",
  "Always they honour, praise, and name shall last.",
  "",
  "Thou in a pitch how far beyond the sphere",
  "Of human glory tower'st, and reigning there",
  "Despoiled of mortal robes, in seas of bliss,",
  "Plunging dost bathe, and tread the bright abyss:",
  "There thy great soul yet once a world does see,",
  "Spacious enough, and pure enough for thee.",
  "How soon thou Moses hast, and Joshua found,",
  "And David for the sword and harp renowned?",
  "How straight canst to each happy mansion go?",
  "(Far better known above than here below)",
  "And in those joys dost spend the endless day,",
  "Which in expressing we ourselves betray.",
  "",
  "For we, since thou art gone, with heavy doom,",
  "Wander like ghosts about thy lovиd tomb;",
  "And lost in tears, have neither sight nor mind",
  "To guide us upward through this region blind.",
  "Since thou art gone, who best that way couldst teach,",
  "Only our sighs, perhaps, may thither reach.",
  "",
  "And Richard yet, where his great parent led,",
  "Beats on the rugged track: he, virtue dead,",
  "Revives, and by his milder beams assures;",
  "And yet how much of them his grief obscures?",
  "",
  "He, as his father, long was kept from sight",
  "In private, to be viewed by better light;",
  "But opened once, what splendour does he throw?",
  "A Cromwell in an hour a prince will grow.",
  "How he becomes that seat, how strongly strains,",
  "How gently winds at once the ruling reins?",
  "Heaven to this choice prepared a diadem,",
  "Richer than any Easter silk or gem;",
  "A pearly rainbow, where the sun enchased",
  "His brows, like an imperial jewel graced.",
  "",
  "We find already what those omens mean,",
  "Earth ne'er more glad, nor heaven more serene.",
  "Cease now our griefs, calm peace succeeds a war,",
  "Rainbows to storms, Richard to Oliver.",
  "Tempt not his clemency to try his power,",
  "He threats no deluge, yet foretells a shower.",
  ""
]