module.exports = [
  "HALF of the grove stood dead, and those that yet",
  "   lived made",
  "Little more than the dead ones made of shade.",
  "If they led to a house, long before they had seen",
  "   its fall:",
  "But they welcomed me; I was glad without cause",
  "   and delayed.",
  "",
  "Scarce a hundred paces under the trees was the",
  "   Interval--",
  "Paces each sweeter than sweetest miles--but",
  "   nothing at all,",
  "Not even the spirits of memory and fear with",
  "   restless wing,",
  "Could climb down in to molest me over the wall",
  "",
  "That I passed through at either end without",
  "   noticing.",
  "And now an ash grove far from those hills can bring",
  "The same tranquillity in which I wander a ghost",
  "With a ghostly gladness, as if I heard a girl sing",
  "",
  "The song of the Ash Grove soft as love uncrossed,",
  "And then in a crowd or in distance it were lost,",
  "But the moment unveiled something unwilling",
  "   to die",
  "And I had what most I desired, without search or",
  "   desert or cost.",
  ""
]