module.exports = [
  "Ere the daughter of Brunswick is cold in her grave,",
  "And her ashes still float to their home o'er the tide,",
  "Lo! George the triumphant speeds over the wave,",
  "  To the long-cherished Isle which he loved like his--bride.",
  "",
  "True, the great of her bright and brief Era are gone,",
  "  The rain-bow-like Epoch where Freedom could pause",
  "For the few little years, out of centuries won,",
  "  Which betrayed not, or crushed not, or wept not her cause.",
  "",
  "True, the chains of the Catholic clank o'er his rags,",
  "  The Castle still stands, and the Senate's no more,",
  "And the Famine which dwelt on her freedomless crags",
  "  Is extending its steps to her desolate shore.",
  "",
  "To her desolate shore--where the emigrant stands",
  "  For a moment to gaze ere he flies from his hearth;",
  "Tears fall on his chain, though it drops from his hands,",
  "  For the dungeon he quits is the place of his birth.",
  "",
  "But he comes! the Messiah of Royalty comes!",
  "  Like a goodly Leviathan rolled from the waves;",
  "Then receive him as best such an advent becomes,",
  "  With a legion of cooks, and an army of slaves!",
  "",
  "He comes in the promise and bloom of threescore,",
  "  To perform in the pageant the Sovereign's part--",
  "But long live the Shamrock, which shadows him o'er!",
  "  Could the Green in his _hat_ be transferred to his _heart!_",
  "",
  "Could that long-withered spot but be verdant again,",
  "  And a new spring of noble affections arise--",
  "Then might Freedom forgive thee this dance in thy chain,",
  "  And this shout of thy slavery which saddens the skies.",
  "",
  "Is it madness or meanness which clings to thee now?",
  "  Were he God--as he is but the commonest clay,",
  "With scarce fewer wrinkles than sins on his brow--",
  "  Such servile devotion might shame him away.",
  "",
  "Aye, roar in his train! let thine orators lash",
  "  Their fanciful spirits to pamper his pride--",
  "Not thus did thy Grattan indignantly flash",
  "  His soul o'er the freedom implored and denied.",
  "",
  "Ever glorious Grattan! the best of the good!",
  "  So simple in heart, so sublime in the rest!",
  "With all which Demosthenes wanted endued,",
  "  And his rival, or victor, in all he possessed.",
  "",
  "Ere Tully arose in the zenith of Rome,",
  "  Though unequalled, preceded, the task was begun--",
  "But Grattan sprung up like a god from the tomb",
  "  Of ages, the first, last, the saviour, the _one!_",
  "",
  "With the skill of an Orpheus to soften the brute;",
  "  With the fire of Prometheus to kindle mankind;",
  "Even Tyranny, listening, sate melted or mute,",
  "  And Corruption shrunk scorched from the glance of his mind.",
  "",
  "But back to our theme! Back to despots and slaves!",
  "  Feasts furnished by Famine! rejoicings by Pain!",
  "True Freedom but _welcomes_, while Slavery still _raves_,",
  "  When a week's Saturnalia hath loosened her chain.",
  "",
  "Let the poor squalid splendour thy wreck can afford,",
  "  (As the bankrupt's profusion his ruin would hide)",
  "Gild over the palace, Lo! Erin, thy Lord!",
  "  Kiss his foot with thy blessing--his blessings denied!",
  "",
  "Or _if_ freedom past hope be extorted at last,",
  "  If the idol of brass find his feet are of clay,",
  "Must what terror or policy wring forth be classed",
  "  With what monarchs ne'er give, but as wolves yield their prey?",
  "",
  "Each brute hath its nature; a King's is to _reign_,--",
  "  To _reign!_ in that word see, ye ages, comprised",
  "The cause of the curses all annals contain,",
  "  From Cæsar the dreaded to George the despised!",
  "",
  "Wear, Fingal, thy trapping! O'Connell, proclaim",
  "  His accomplishments! _His!!!_ and thy country convince",
  "Half an age's contempt was an error of fame,",
  "  And that \"Hal is the rascaliest, sweetest _young_ prince!\"",
  "",
  "Will thy yard of blue riband, poor Fingal, recall",
  "  The fetters from millions of Catholic limbs?",
  "Or, has it not bound thee the fastest of all",
  "  The slaves, who now hail their betrayer with hymns?",
  "",
  "Aye! \"Build him a dwelling!\" let each give his mite!",
  "  Till, like Babel, the new royal dome hath arisen!",
  "Let thy beggars and helots their pittance unite--",
  "  And a palace bestow for a poor-house and prison!",
  "",
  "Spread--spread for Vitellius, the royal repast,",
  "  Till the gluttonous despot be stuffed to the gorge!",
  "And the roar of his drunkards proclaim him at last",
  "  The Fourth of the fools and oppressors called \"George!\"",
  "",
  "Let the tables be loaded with feasts till they groan!",
  "  Till they _groan_ like thy people, through ages of woe!",
  "Let the wine flow around the old Bacchanal's throne,",
  "  Like their blood which has flowed, and which yet has to flow.",
  "",
  "But let not _his_ name be thine idol alone--",
  "  On his right hand behold a Sejanus appears!",
  "Thine own Castlereagh! let him still be thine own!",
  "  A wretch never named but with curses and jeers!",
  "",
  "Till now, when the Isle which should blush for his birth,",
  "  Deep, deep as the gore which he shed on her soil,",
  "Seems proud of the reptile which crawled from her earth,",
  "  And for murder repays him with shouts and a smile.",
  "",
  "Without one single ray of her genius,--without",
  "  The fancy, the manhood, the fire of her race--",
  "The miscreant who well might plunge Erin in doubt",
  "  If _she_ ever gave birth to a being so base.",
  "",
  "If she did--let her long-boasted proverb be hushed,",
  "  Which proclaims that from Erin no reptile can spring--",
  "See the cold-blooded Serpent, with venom full flushed,",
  "  Still warming its folds in the breast of a King!",
  "",
  "Shout, drink, feast, and flatter! Oh! Erin, how low",
  "  Wert thou sunk by misfortune and tyranny, till",
  "Thy welcome of tyrants hath plunged thee below",
  "  The depth of thy deep in a deeper gulf still.",
  "",
  "My voice, though but humble, was raised for thy right;",
  "  My vote, as a freeman's, still voted thee free;",
  "This hand, though but feeble, would arm in thy fight,",
  "  And this heart, though outworn, had a throb still for _thee!_",
  "",
  "Yes, I loved thee and thine, though thou art not my land;",
  "  I have known noble hearts and great souls in thy sons,",
  "And I wept with the world, o'er the patriot band",
  "  Who are gone, but I weep them no longer as once.",
  "",
  "For happy are they now reposing afar,--",
  "  Thy Grattan, thy Curran, thy Sheridan, all",
  "Who, for years, were the chiefs in the eloquent war,",
  "  And redeemed, if they have not retarded, thy fall.",
  "",
  "Yes, happy are they in their cold English graves!",
  "  Their shades cannot start to thy shouts of to-day--",
  "Nor the steps of enslavers and chain-kissing slaves",
  "  Be stamped in the turf o'er their fetterless clay.",
  "",
  "Till now I had envied thy sons and their shore,",
  "  Though their virtues were hunted, their liberties fled;",
  "There was something so warm and sublime in the core",
  "  Of an Irishman's heart, that I envy--thy _dead_.",
  "",
  "Or, if aught in my bosom can quench for an hour",
  "  My contempt for a nation so servile, though sore,",
  "Which though trod like the worm will not turn upon power,",
  "  'Tis the glory of Grattan, and genius of Moore!",
  ""
]