module.exports = [
  "Grand rough old Martin Luther",
  "   Bloomed fables-flowers on furze,",
  "The better the uncouther:",
  "   Do roses stick like burrs?",
  "",
  "A beggar asked an alms",
  "   One day at an abbey-door,",
  "Said Luther; but, seized with qualms,",
  "   The abbot replied, \"We're poor!\"",
  "",
  "\"Poor, who had plenty once,",
  "   When gifts fell thick as rain:",
  "But they give us nought, for the nonce,",
  "   And now should we give again?\"",
  "",
  "Then the beggar, \"See your sins!",
  "   Of old, unless I err,",
  "Ye had brothers for inmates, twins,",
  "   Date and Dabitur.",
  "",
  "\"While Date was in good case",
  "   Dabitur flourished too:",
  "For Dabitur's lenten face",
  "   No wonder if Date rue.",
  "",
  "\"Would ye retrieve the one?",
  "   Try and make plump the other!",
  "When Date's penance is done,",
  "   Dabitur helps his brother.",
  "",
  "\"Only, beware relapse!\"",
  "   The Abbot hung his head.",
  "This beggar might be perhaps",
  "   An angel, Luther said.",
  ""
]