module.exports = [
  "LOVE, I renounce thy tyrant sway,",
  "I mock thy fascinating art,",
  "MINE, be the calm unruffled day,",
  "That brings no torment to the heart;",
  "The tranquil mind, the noiseless scene,",
  "Where FANCY, with enchanting mien,",
  "Shall in her right-hand lead along",
  "The graceful patroness of Song;",
  "Where HARMONY shall softly fling",
  "Her light tones o'er the dulcet string;",
  "And with her magic LYRE compose",
  "Each pang that throbs, each pulse that glows;",
  "Till her resistless strains dispense,",
  "The balm of blest INDIFFERENCE.",
  "",
  "LOVE, I defy thy vaunted pow'r!",
  "In still Retirement's sober bow'r",
  "I'll rest secure;­no fev'rish pain",
  "Shall dart its hot-shafts thro' my brain,",
  "No start'ling dreams invade my mind",
  "No spells my stagnate pulses bind;",
  "No jealous agonies impart",
  "Their madd'ning poisons to my heart",
  "But sweetly lull'd to placid rest,",
  "The sensate tenant of my breast",
  "Shall one unshaken course pursue,",
  "Such as thy vot'ries never knew.­",
  "",
  "SWEET SOLITUDE ! pure Nature's child,",
  "Fair pensive daughter of the wild;",
  "Nymph of the Forest; thee I press",
  "My weary sick'ning soul to bless;",
  "To give my heart the dear repose,",
  "That smiles unmov'd at transient woes;",
  "That shelter'd from Life's trivial cares,",
  "Each calm delicious comfort shares;",
  "While conscious rectitude of mind,",
  "Blends with each thought a bliss refin'd,",
  "And scorning fear's soul-chilling pow'r,",
  "Dares court REFLECTION'S dang'rous hour,",
  "To scrutinize with cautious art,",
  "Each hidden channel of the heart.­",
  "",
  "Ah, gentle maiden, let me stray,",
  "Where Innocence for ever gay,",
  "Shall lead me to her loveliest bow'rs",
  "And crown my brow with thornless flow'rs;",
  "And strew the weedy paths of time",
  "With Resignation's balm sublime;",
  "While Rosy SPRING, shall smiling haste,",
  "On light steps o'er the dewy waste,",
  "Eager her brightest gems to shed",
  "Around my verdant perfum'd bed;",
  "And in her train the glowing hours",
  "Shall bathe their wings in scented show'rs;",
  "And shake the fost'ring drops to earth,",
  "To nurse meek blossoms into birth;",
  "And when autumnal zephyrs fly",
  "Sportive, beneath the sapphire sky,",
  "Or in the stream their pinions lave,",
  "Or teach the golden sheaves to wave;",
  "I'll watch the ruby eye of day",
  "In awful lustre glide away,",
  "And closing sink to transient rest,",
  "On panting Ocean's pearly breast.",
  "",
  "O SOLITUDE ! how blest the lot",
  "Of her who shares thy silent cot!",
  "Who with celestial peace, pursues",
  "The pensive wand'rings of the MUSE;",
  "To stray unseen where'er she leads,",
  "O'er grassy hills and sunny meads,",
  "Or at the still of Night's cold noon",
  "To gaze upon the chilly Moon,",
  "While PHILOMELA'S mournful Song",
  "Meanders fairy haunts among,",
  "To tell the hopeless LOVER'S ear,",
  "That SYMPATHY'S FOND BIRD is near;",
  "Whose note shall soothe his aching heart,",
  "Whose grief shall emulate his smart;",
  "And by its sadly proud excess,",
  "Make every pang he suffers less;",
  "For oft in passion's direst woes,",
  "The veriest wretch can yield repose;",
  "While from the voice of kindred grief,",
  "We gain a sad, but kind relief.",
  "",
  "AH LOVE! thou barb'rous fickle boy,",
  "Thou semblance of delusive joy,",
  "Too long my heart has been thy slave:",
  "For thou hast seen me wildly rave,",
  "And with impetuous frenzy haste,",
  "Heedless across the thorny waste,",
  "And drink the cold dews, ere they fell",
  "On my bare bosom's burning swell;",
  "When bleak the wintry whirlwinds blew;",
  "And swift the sultry meteors flew;",
  "Yes, thou hast seen me, tyrant pow'r,",
  "At freezing midnight's witching hour,",
  "Start from my couch, subdu'd, oppres'd,",
  "While jealous anguish wrung my breast,",
  "While round my eager senses flew,",
  "Dark brow'd Suspicion's wily crew,",
  "Taunting my soul with restless ire,",
  "That set my pulsate brain on fire.",
  "What didst thou then ? Inhuman Boy!",
  "Didst thou not paint each well-feign'd joy,",
  "Each artful smile, each study'd grace",
  "That deck'd some sordid rival's face;",
  "Didst thou not feed my madd'ning sense",
  "With Love's delicious eloquence,",
  "While on my ear thy accents pour'd",
  "The voice of him my soul ador'd,",
  "His rapt'rous tones­his strains divine,",
  "And all those vows that once were mine.",
  "But mild Reflection's piercing ray,",
  "Soon chas'd the fatal dream away,",
  "And with it all my rending woes,",
  "While in its place majestic rose",
  "The Angel TRUTH !­her stedfast mien",
  "Bespoke the conscious breast serene;",
  "Her eye more radiant than the day",
  "Beam'd with persuasion's temper'd ray;",
  "Sweet was her voice, and while she sung",
  "Myriads of Seraphs hover'd round,",
  "Eager to iterate the sound,",
  "That on her heav'n-taught accents hung.",
  "Wond'ring I gaz'd! my throbbing breast,",
  "Celestial energies confest;",
  "Transports, before unfelt, unknown,",
  "Throng'd round my bosom's tremb'ling throne,",
  "While ev'ry nerve with rapture strange,",
  "Seem'd to partake the blissful change.",
  "",
  "Now with unmov'd and dauntless Eye,",
  "I mark thy winged arrows fly;",
  "No more thy baneful spells shall bind",
  "The purer passions of my mind;",
  "No more, false Love, shall jealous fears",
  "Inflame my check with scalding tears;",
  "Or shake my vanquish'd sense, or rend",
  "My aching heart with poignant throes,",
  "Or with tumultuous fevers blend,",
  "Self-wounding, visionary woes.­",
  "",
  "No more I'll waste the midnight hour",
  "In expectation's silent bow'r;",
  "And musing o'er thy transcripts dear,",
  "Efface their sorrows with a tear.",
  "No more with timid fondness wait",
  "Till morn unfolds her glitt'ring gate,",
  "When thy lov'd song's seraphic sound,",
  "Wou'd on my quiv'ring nerves rebound",
  "With proud delight;­no more thy blush",
  "Shall o'er my cheek unbidden rush,",
  "And scorning ev'ry strong controul,",
  "Unveil the tumults of my soul.",
  "No more when in retirement blest,",
  "Shalt thou obtrude upon my rest;",
  "And tho' encircled with delight,",
  "Absorb my sense, obscure my sight,",
  "Give to my eye the vacant glance,",
  "The mien that marks the mental trance;",
  "The fault'ring tone­the sudden start,",
  "The trembling hand, the bursting heart;",
  "The devious step, that strolls along",
  "Unmindful of the gazing throng;",
  "The feign'd indiff'rence prone to chide;",
  "That blazons­what it seeks to hide.",
  "",
  "Nor do I dread thy vengeful wiles,",
  "Thy soothing voice, thy winning smiles,",
  "Thy trick'ling tear, thy mien forlorn,",
  "Thy pray'r, thy sighs, thy oaths I scorn;",
  "No more on ME thy arrows show'r,",
  "Capricious Love­! I BRAVE THY POW'R.",
  ""
]