module.exports = [
  "Holland, that scarce deserves the name of Land,",
  "As but th'Off-scouring of the Brittish Sand;",
  "And so much Earth as was contributed",
  "By English Pilots when they heav'd the Lead;",
  "Or what by th' Oceans slow alluvion fell,",
  "Of shipwrackt Cockle and the Muscle-shell;",
  "This indigested vomit of the Sea",
  "Fell to the Dutch by just Propriety.",
  "Glad then, as Miners that have found the Oar,",
  "They with mad labour fish'd the Land to Shoar;",
  "And div'd as desperately for each piece",
  "Of Earth, as if't had been of Ambergreece;",
  "Collecting anxiously small Loads of Clay,",
  "Less then what building Swallows bear away;",
  "Transfursing into them their Dunghil Soul.",
  "How did they rivet, with Gigantick Piles,",
  "Thorough the Center their new-catched Miles;",
  "And to the stake a strugling Country bound,",
  "Where barking Waves still bait the forced Ground;",
  "Building their watry Babel far more high",
  "To reach the Sea, then those to scale the Sky.",
  "Yet still his claim the Injur'd Ocean laid,",
  "And oft at Leap-frog ore their Steeples plaid:",
  "As if on purpose it on Land had come",
  "To shew them what's their Mare Liberum.",
  "A daily deluge over them does boyl;",
  "The Earth and Water play at Level-coyl;",
  "The Fish oft-times the Burger dispossest,",
  "And sat not as a Meat but as a Guest;",
  "And oft the Tritons and the Sea-Nymphs saw",
  "Whole sholes of Dutch serv'd up for Cabillan;",
  "Or as they over the new Level rang'd",
  "For pickled Herring, pickled Heeren chang'd.",
  "Nature, it seem'd, asham'd of her mistake,",
  "Would throw their land away at Duck and Drake.",
  "Therefore Necessity, that first made Kings,",
  "Something like Government among them brings.",
  "For as with Pygmees who best kills the Crane,",
  "Among the hungry he that treasures Grain,",
  "Among the blind the one-ey'd blinkard reigns,",
  "So rules among the drowned he that draines.",
  "Not who first see the rising Sun commands,",
  "But who could first discern the rising Lands.",
  "Who best could know to pump an Earth so leak",
  "Him they their Lord and Country's Father speak.",
  "To make a Bank was a great Plot of State;",
  "Invent a Shov'l and be a Magistrate.",
  "Hence some small Dyke-grave unperceiv'd invades",
  "The Pow'r, and grows as 'twere a King of Spades.",
  "But for less envy some Joynt States endures,",
  "Who look like a Commission of the Sewers.",
  "For these Half-anders, half wet, and half dry,",
  "Nor bear strict service, nor pure Liberty.",
  "'Tis probable Religion after this",
  "Came next in order; which they could not miss.",
  "How could the Dutch but be converted, when",
  "Th' Apostles were so many Fishermen?",
  "Besides the Waters of themselves did rise,",
  "And, as their Land, so them did re-baptise.",
  "Though Herring for their God few voices mist,",
  "And Poor-John to have been th' Evangelist.",
  "Faith, that could never Twins conceive before,",
  "Never so fertile, spawn'd upon this shore:",
  "More pregnant then their Marg'ret, that laid down",
  "For Hans-in-Kelder of a whole Hans-Town.",
  "Sure when Religion did it self imbark,",
  "And from the east would Westward steer its Ark,",
  "It struck, and splitting on this unknown ground,",
  "Each one thence pillag'd the first piece he found:",
  "Hence Amsterdam, Turk-Christian-Pagan-Jew,",
  "Staple of Sects and Mint of Schisme grew;",
  "That Bank of Conscience, where not one so strange",
  "Opinion but finds Credit, and Exchange.",
  "In vain for Catholicks our selves we bear;",
  "The Universal Church is onely there.",
  "Nor can Civility there want for Tillage,",
  "Where wisely for their Court they chose a Village.",
  "How fit a Title clothes their Governours,",
  "Themselves the Hogs as all their Subjects Bores",
  "Let it suffice to give their Country Fame",
  "That it had one Civilis call'd by Name,",
  "Some Fifteen hundred and more years ago,",
  "But surely never any that was so.",
  "See but their Mairmaids with their Tails of Fish,",
  "Reeking at Church over the Chafing-Dish.",
  "A vestal Turf enshrin'd in Earthen Ware",
  "Fumes through the loop-holes of wooden Square.",
  "Each to the Temple with these Altars tend,",
  "But still does place it at her Western End:",
  "While the fat steam of Female Sacrifice",
  "Fills the Priests Nostrils and puts out his Eyes.",
  "Or what a Spectacle the Skipper gross,",
  "A Water-Hercules Butter-Coloss,",
  "Tunn'd up with all their sev'ral Towns of Beer;",
  "When Stagg'ring upon some Land, Snick and Sneer,",
  "They try, like Statuaries, if they can,",
  "Cut out each others Athos to a Man:",
  "And carve in their large Bodies, where they please,",
  "The Armes of the United Provinces.",
  "But when such Amity at home is show'd;",
  "What then are their confederacies abroad?",
  "Let this one court'sie witness all the rest;",
  "When their hole Navy they together prest,",
  "Not Christian Captives to redeem from Bands:",
  "Or intercept the Western golden Sands:",
  "No, but all ancient Rights and Leagues must vail,",
  "Rather then to the English strike their sail;",
  "to whom their weather-beaten Province ows",
  "It self, when as some greater Vessal tows",
  "A Cock-boat tost with the same wind and fate;",
  "We buoy'd so often up their Sinking State.",
  "Was this Jus Belli & Pacis; could this be",
  "Cause why their Burgomaster of the Sea",
  "Ram'd with Gun-powder, flaming with Brand wine,",
  "Should raging hold his Linstock to the Mine?",
  "While, with feign'd Treaties, they invade by stealth",
  "Our sore new circumcised Common wealth.",
  "Yet of his vain Attempt no more he sees",
  "Then of Case-Butter shot and Bullet-Cheese.",
  "And the torn Navy stagger'd with him home,",
  "While the Sea laught it self into a foam,",
  "'Tis true since that (as fortune kindly sports,)",
  "A wholesome Danger drove us to our ports.",
  "While half their banish'd keels the Tempest tost,",
  "Half bound at home in Prison to the frost:",
  "That ours mean time at leisure might careen,",
  "In a calm Winter, under Skies Serene.",
  "As the obsequious Air and waters rest,",
  "Till the dear Halcyon hatch out all its nest.",
  "The Common wealth doth by its losses grow;",
  "And, like its own Seas, only Ebbs to flow.",
  "Besides that very Agitation laves,",
  "And purges out the corruptible waves.",
  "And now again our armed Bucentore",
  "Doth yearly their Sea-Nuptials restore.",
  "And how the Hydra of seaven Provinces",
  "Is strangled by our Infant Hercules.",
  "Their Tortoise wants its vainly stretched neck;",
  "Their Navy all our Conquest or our Wreck:",
  "Or, what is left, their Carthage overcome",
  "Would render fain unto our better Rome.",
  "Unless our Senate, lest their Youth disuse,",
  "The War, (but who would) Peace if begg'd refuse.",
  "For now of nothing may our State despair,",
  "Darling of Heaven, and of Men the Care;",
  "Provided that they be what they have been,",
  "Watchful abroad, and honest still within.",
  "For while our Neptune doth a Trident shake, Blake,",
  "Steel'd with those piercing Heads, Dean, Monck and",
  "And while Jove governs in the highest Sphere,",
  "Vainly in Hell let Pluto domineer.",
  ""
]