module.exports = [
  "'Twas on the 18th of August in the year of 1798,",
  "That Nelson saw with inexpressible delight",
  "The City of Alexandria crowded with the ships of France,",
  "So he ordered all sail to be set, and immediately advance.",
  "",
  "And upon the deck, in deep anxiety he stood,",
  "And from anxiety of mind he took but little food;",
  "But now he ordered dinner and prepared without delay,",
  "Saying, I shall gain a peerage to-morrow, or Westminster Abbey.",
  "",
  "The French had found it impossible to enter the port of Alexandria,",
  "Therefore they were compelled to withdraw;",
  "Yet their hearts were burning with anxiety the war to begin,",
  "But they couldn't find a pilot who would convey them safely in.",
  "",
  "Therefore Admiral Brueyes was forced to anchor in Aboukir Bay,",
  "And in a compact line of battle, the leading vessel lay",
  "Close to a shoal, along a line of very deep water,",
  "There they lay, all eager to begin the murderous slaughter.",
  "",
  "The French force consisted of thirteen ships of the line,",
  "As fine as ever sailed on the salt sea brine;",
  "Besides four Frigates carrying 1,196 guns in all,",
  "Also 11,230 men as good as ever fired a cannon ball.",
  "",
  "The number of the English ships were thirteen in all,",
  "And carrying 1012 guns, including great and small;",
  "And the number of men were 8,068,",
  "All jolly British tars and eager for to fight.",
  "",
  "As soon as Nelson perceived the position of the enemy,",
  "His active mind soon formed a plan immediately;",
  "As the plan he thought best, as far as he could see,",
  "Was to anchor his ships on the quarter of each of the enemy.",
  "",
  "And when he had explained hid mode of attack to his officers and men,",
  "He said, form as convenient, and anchor at the stern;",
  "The first gain the victory, and make the best use of it you can,",
  "Therefore I hope every one here to-day, will do their duty to a man.",
  "",
  "When Captain Berry perceived the boldness of the plan,",
  "He said, my Lord, I'm sure the men will do their duty to a man;",
  "And, my Lord, what will the world say, if we gain the victory?",
  "Then Nelson replied, there's no if in the case, and that you'll see.",
  "",
  "Then the British tars went to work without delay,",
  "All hurrying to and fro, making ready for the fray;",
  "And there wasn't a man among them, but was confident that day,",
  "That they would make the French to fly from Aboukir Bay.",
  "",
  "Nelson's fleet did not enter Aboukir Bay at once,",
  "And by adopting that plan, that was his only chance;",
  "But one after another, they bore down on the enemy;",
  "Then Nelson cried, now open fire my heroes, immediately!",
  "",
  "Then the shores of Egypt trembled with the din of the war,",
  "While sheets of flame rent the thick clouds afar;",
  "And the contending fleets hung incumbent o'er the bay,",
  "Whilst our British tars stuck to their guns without the least dismay.",
  "",
  "And loudly roared the earthly thunder along thr river Nile,",
  "And the British ship Orion went into action in splendid style;",
  "Also Nelson's Ship Vanguard bore down on the foe,",
  "With six flags flying from her rigging high and low.",
  "",
  "Then she opened a tremendous fire on the Spartiate,",
  "And Nelson cried, fear not my lads we'll soon make them retreat!",
  "But so terrific was the fire of the enemy on them,",
  "That six of the Vanguards guns were cleared of men.",
  "",
  "Yet there stood Nelson, the noble Hero of the Nile,",
  "In the midst of death and destruction on deck all the while;",
  "And around him on every side, the cannon balls did rattle,",
  "But right well the noble hero knew the issue of the battle.",
  "",
  "But suddenly he received a wound on the head,",
  "And fell into the arms of Captain Berry, but fortunately not dead;",
  "And the flow of blood from his head was very great,",
  "But still the hero of the Nile was resigned to his fate.",
  "",
  "Then to the Cockpit the great Admiral was carried down,",
  "And in the midst of the dying, he never once did frown;",
  "Nor he didn't shake with fear, nor yet did he mourne,",
  "But patiently sat down to wait his own turn.",
  "",
  "And when the Surgeon saw him, he instantly ran,",
  "But Nelson said, Surgeon, attend to that man;",
  "Attend to the sailor you were at, for he requires your aid,",
  "Then I will take my turn, don't be the least afraid.",
  "",
  "And when his turn came, it was found that his wound was but slight,",
  "And when known, it filled the sailors hearts with delight;",
  "And they all hoped he would soon be able to command in the fight,",
  "When suddenly a cry arose of fire! Which startled Nelson with affright.",
  "",
  "And unassisted he rushed upon the deck, and to his amaze,",
  "He discovered that the Orient was all in a blaze;",
  "Then he ordered the men to lower the boats, and relieve the enemy,",
  "Saying, now men, see and obey my orders immediately.",
  "",
  "Then the noble tars manned their boats, and steered to the Orient,",
  "While the poor creatures thanked God for the succour He had sent;",
  "And the burning fragments fell around them like rain,",
  "Still our British tars rescued about seventy of them from the burning flame,",
  "",
  "And of the thirteen sail of the French the British captured nine,",
  "Besides four of their ships were burnt, which made the scene sublime,",
  "Which made the hero of the Nile cry out thank God we've won the day,",
  "And defeated the French most manfully in Aboukir Bay.",
  "",
  "Then the victory was complete and the French Fleet annihilated,",
  "And when the news arrived in England the peoples' hearts felt elated,",
  "Then Nelson sent orders immediately through the fleet,",
  "That thanksgiving should be returned to God for the victory complete.",
  ""
]