module.exports = [
  "I love to rise on a summer morn,",
  "  When birds are singing on every tree;",
  "The distant huntsman winds his horn,",
  "  And the skylark sings with me:",
  "  Oh what sweet company!",
  "",
  "But to go to school in a summer morn,--",
  "  Oh it drives all joy away!",
  "Under a cruel eye outworn,",
  "  The little ones spend the day",
  "  In sighing and dismay.",
  "",
  "Ah then at times I drooping sit,",
  "  And spend many an anxious hour;",
  "Nor in my book can I take delight,",
  "  Nor sit in learning's bower,",
  "  Worn through with the dreary shower.",
  "",
  "How can the bird that is born for joy",
  "  Sit in a cage and sing?",
  "How can a child, when fears annoy,",
  "  But droop his tender wing,",
  "  And forget his youthful spring?",
  "",
  "Oh father and mother, if buds are nipped,",
  "  And blossoms blown away;",
  "And if the tender plants are stripped",
  "  Of their joy in the springing day,",
  "  By sorrow and care's dismay,--",
  "",
  "How shall the summer arise in joy,",
  "  Or the summer fruits appear?",
  "Or how shall we gather what griefs destroy,",
  "  Or bless the mellowing year,",
  "  When the blasts of winter appear?",
  ""
]