module.exports = [
  "Two good little children, named Mary and Ann,",
  "Both happily live, as good girls always can;",
  "And though they are not either sullen or mute,",
  "They seldom or never are heard to dispute.",
  "",
  "If one wants a thing that the other would like­",
  "Well,­what do they do? Must they quarrel and strike?",
  "No, each is so willing to give up her own,",
  "That such disagreements are there never known.",
  "",
  "If one of them happens to have something nice,",
  "Directly she offers her sister a slice;",
  "And never, like some greedy children, would try",
  "To eat in a corner with nobody by!",
  "",
  "When papa or mamma has a job to be done;",
  "These good little children immediately run;",
  "Nor dispute whether this or the other should go,",
  "They would be ashamed to behave themselves so!",
  "",
  "Whatever occurs, in their work or their play,",
  "They are willing to yield, and give up their own way:",
  "Then now let us try their example to mind,",
  "And always, like them, be obliging and kind.",
  ""
]