module.exports = [
  "THE wind is without there and howls in the trees,",
  "And the rain-flurries drum on the glass:",
  "Alone by the fireside with elbows on knees",
  "I can number the hours as they pass.",
  "Yet now, when to cheer me the crickets begin,",
  "And my pipe is just happily lit,",
  "Believe me, my friend, tho' the evening draws in,",
  "That not all uncontested I sit.",
  "",
  "Alone, did I say? O no, nowise alone",
  "With the Past sitting warm on my knee,",
  "To gossip of days that are over and gone,",
  "But still charming to her and to me.",
  "With much to be glad of and much to deplore,",
  "Yet, as these days with those we compare,",
  "Believe me, my friend, tho' the sorrows seem more",
  "They are somehow more easy to bear.",
  "",
  "And thou, faded Future, uncertain and frail,",
  "As I cherish thy light in each draught,",
  "His lamp is not more to the miner - their sail",
  "Is not more to the crew on the raft.",
  "For Hope can make feeble ones earnest and brave,",
  "And, as forth thro' the years I look on,",
  "Believe me, my friend, between this and the grave,",
  "I see wonderful things to be done.",
  "",
  "To do or to try; and, believe me, my friend,",
  "If the call should come early for me,",
  "I can leave these foundations uprooted, and tend",
  "For some new city over the sea.",
  "To do or to try; and if failure be mine,",
  "And if Fortune go cross to my plan,",
  "Believe me, my friend, tho' I mourn the design",
  "I shall never lament for the man.",
  ""
]