module.exports = [
  "I'm a helpless cripple child,",
  "Gentle Christians, pity me;",
  "Once, in rosy health I smiled,",
  "Blithe and gay as you can be,",
  "And upon the village green",
  "First in every sport was seen.",
  "",
  "Now, alas! I'm weak and low,",
  "Cannot either work or play;",
  "Tottering on my crutches, slow,",
  "Thus I drag my weary way:",
  "Now no longer dance and sing,",
  "Gaily, in the merry ring.",
  "",
  "Many sleepless nights I live,",
  "Turning on my weary bed;",
  "Softest pillows cannot give",
  "Slumber to my aching head;",
  "Constant anguish makes it fly",
  "From my heavy, wakeful eye.",
  "",
  "And, when morning beams return,",
  "Still no comfort beams for me:",
  "Still my limbs with fever burn,",
  "Painful still my crippled knee.",
  "And another tedious day",
  "Passes slow and sad away.",
  "",
  "From my chamber-window high,",
  "Lifted to my easy-chair,",
  "I the village-green can spy,",
  "Once I used to frolic there,",
  "March, or beat my new-bought drum;",
  "Happy times! no more to come.",
  "",
  "There I see my fellows gay,",
  "Sporting on the daisied turf,",
  "And, amidst their cheerful play,",
  "Stopp'd by many a merry laugh;",
  "But the sight I scarce can bear,",
  "Leaning in my easy-chair.",
  "",
  "Let not then the scoffing eye",
  "Laugh, my twisted leg to see:",
  "Gentle Christians, passing by,",
  "Stop awhile, and pity me,",
  "And for you I'll breathe a prayer,",
  "Leaning in my easy-chair.",
  ""
]