module.exports = [
  "Scene, on the Cliffs to the Eastward of the Town of",
  "Brighthelmstone in Sussex. Time, a Morning in November, 1792.",
  "",
  "",
  "Slow in the Wintry Morn, the struggling light",
  "Throws a faint gleam upon the troubled waves;",
  "Their foaming tops, as they approach the shore",
  "And the broad surf that never ceasing breaks",
  "On the innumerous pebbles, catch the beams",
  "Of the pale Sun, that with reluctance gives",
  "To this cold northern Isle, its shorten'd day.",
  "Alas! how few the morning wakes to joy!",
  "How many murmur at oblivious night",
  "For leaving them so soon; for bearing thus",
  "Their fancied bliss (the only bliss they taste!),",
  "On her black wings away!--Changing the dreams",
  "That sooth'd their sorrows, for calamities",
  "(And every day brings its own sad proportion)",
  "For doubts, diseases, abject dread of Death,",
  "And faithless friends, and fame and fortune lost;",
  "Fancied or real wants; and wounded pride,",
  "That views the day star, but to curse his beams.",
  "Yet He, whose Spirit into being call'd",
  "This wond'rous World of Waters; He who bids",
  "The wild wind lift them till they dash the clouds,",
  "And speaks to them in thunder; or whose breath,",
  "Low murmuring, o'er the gently heaving tides,",
  "When the fair Moon, in summer night serene,",
  "Irradiates with long trembling lines of light",
  "Their undulating surface; that great Power,",
  "Who, governing the Planets, also knows",
  "If but a Sea-Mew falls, whose nest is hid",
  "In these incumbent cliffs; He surely means",
  "To us, his reasoning Creatures, whom He bids",
  "Acknowledge and revere his awful hand,",
  "Nothing but good: Yet Man, misguided Man,",
  "Mars the fair work that he was bid enjoy,",
  "And makes himself the evil he deplores.",
  "How often, when my weary soul recoils",
  "From proud oppression, and from legal crimes",
  "(For such are in this Land, where the vain boast",
  "Of equal Law is mockery, while the cost",
  "Of seeking for redress is sure to plunge",
  "Th' already injur'd to more certain ruin",
  "And the wretch starves, before his Counsel pleads)",
  "How often do I half abjure Society,",
  "And sigh for some lone Cottage, deep embower'd",
  "In the green woods, that these steep chalky Hills",
  "Guard from the strong South West; where round their base",
  "The Beach wide flourishes, and the light Ash",
  "With slender leaf half hides the thymy turf!--",
  "There do I wish to hide me; well content",
  "If on the short grass, strewn with fairy flowers,",
  "I might repose thus shelter'd; or when Eve",
  "In Orient crimson lingers in the west,",
  "Gain the high mound, and mark these waves remote",
  "(Lucid tho' distant), blushing with the rays",
  "Of the far-flaming Orb, that sinks beneath them;",
  "For I have thought, that I should then behold",
  "The beauteous works of God, unspoil'd by Man",
  "And less affected then, by human woes",
  "I witness'd not; might better learn to bear",
  "Those that injustice, and duplicity",
  "And faithlessness and folly, fix on me:",
  "For never yet could I derive relief,",
  "When my swol'n heart was bursting with its sorrows,",
  "From the sad thought, that others like myself",
  "Live but to swell affliction's countless tribes!",
  "--Tranquil seclusion I have vainly sought;",
  "Peace, who delights solitary shade,",
  "No more will spread for me her downy wings,",
  "But, like the fabled Danaïds--or the wretch,",
  "Who ceaseless, up the steep acclivity,",
  "Was doom'd to heave the still rebounding rock,",
  "Onward I labour; as the baffled wave,",
  "Which yon rough beach repulses, that returns",
  "With the next breath of wind, to fail again.--",
  "Ah! Mourner--cease these wailings: cease and learn,",
  "That not the Cot sequester'd, where the briar",
  "And wood-bine wild, embrace the mossy thatch,",
  "(Scarce seen amid the forest gloom obscure!)",
  "Or more substantial farm, well fenced and warm,",
  "Where the full barn, and cattle fodder'd round",
  "Speak rustic plenty; nor the statelier dome",
  "By dark firs shaded, or the aspiring pine,",
  "Close by the village Church (with care conceal'd",
  "By verdant foliage, lest the poor man's grave",
  "Should mar the smiling prospect of his Lord),",
  "Where offices well rang'd, or dove-cote stock'd,",
  "Declare manorial residence; not these",
  "Or any of the buildings, new and trim",
  "With windows circling towards the restless Sea,",
  "Which ranged in rows, now terminate my walk,",
  "Can shut out for an hour the spectre Care,",
  "That from the dawn of reason, follows still",
  "Unhappy Mortals, 'till the friendly grave",
  "(Our sole secure asylum) \"ends the chace 1 .\"",
  "Behold, in witness of this mournful truth,",
  "A group approach me, whose dejected looks,",
  "Sad Heralds of distress! proclaim them Men",
  "Banish'd for ever and for conscience sake",
  "From their distracted Country, whence the name",
  "Of Freedom misapplied, and much abus'd",
  "By lawless Anarchy, has driven them far",
  "To wander; with the prejudice they learn'd",
  "From Bigotry (the Tut'ress of the blind),",
  "Thro' the wide World unshelter'd; their sole hope,",
  "That German spoilers, thro' that pleasant land",
  "May carry wide the desolating scourge",
  "Of War and Vengeance; yet unhappy Men,",
  "Whate'er your errors, I lament your fate:",
  "And, as disconsolate and sad ye hang",
  "Upon the barrier of the rock, and seem",
  "To murmur your despondence, waiting long",
  "Some fortunate reverse that never comes;",
  "Methinks in each expressive face, I see",
  "Discriminated anguish; there droops one,",
  "Who in a moping cloister long consum'd",
  "This life inactive, to obtain a better,",
  "And thought that meagre abstinence, to wake",
  "From his hard pallet with the midnight bell,",
  "To live on eleemosynary bread,",
  "And to renounce God's works, would please that God.",
  "And now the poor pale wretch receives, amaz'd,",
  "The pity, strangers give to his distress,",
  "Because these Strangers are, by his dark creed,",
  "Condemn'd as Heretics--and with sick heart",
  "Regrets 2 his pious prison, and his beads.--",
  "Another, of more haughty port, declines",
  "The aid he needs not; while in mute despair",
  "His high indignant thoughts go back to France,",
  "Dwelling on all he lost--the Gothic dome,",
  "That vied with splendid palaces 3 ; the beds",
  "Of silk and down, the silver chalices,",
  "Vestments with gold enwrought for blazing altars;",
  "Where, amid clouds of incense, he held forth",
  "To kneeling crowds the imaginary bones",
  "Of Saints suppos'd, in pearl and gold enchas'd,",
  "And still with more than living Monarchs' pomp",
  "Surrounded; was believ'd by mumbling bigots",
  "To hold the keys of Heaven, and to admit",
  "Whom he thought good to share it--Now alas!",
  "He, to whose daring soul and high ambition",
  "The World seem'd circumscrib'd; who, wont to dream,",
  "Of Fleuri, Richelieu, Alberoni, men",
  "Who trod on Empire, and whose politics",
  "Were not beyond the grasp of his vast mind,",
  "Is, in a Land once hostile, still prophan'd",
  "By disbelief, and rites un-orthodox,",
  "The object of compassion--At his side,",
  "Lighter of heart than these, but heavier far",
  "Than he was wont, another victim comes,",
  "An Abbé--who with less contracted brow",
  "Still smiles and flatters, and still talks of Hope;",
  "Which, sanguine as he is, he does not feel,",
  "And so he cheats the sad and weighty pressure",
  "Of evils present;---- Still, as Men misled",
  "By early prejudice (so hard to break),",
  "I mourn your sorrows; for I too have known",
  "Involuntary exile; and while yet",
  "England had charms for me, have felt how sad",
  "It is to look across the dim cold sea,",
  "That melancholy rolls its refluent tides",
  "Between us and the dear regretted land",
  "We call our own--as now ye pensive wait",
  "On this bleak morning, gazing on the waves",
  "That seem to leave your shore; from whence the wind",
  "Is loaded to your ears, with the deep groans",
  "Of martyr'd Saints and suffering Royalty,",
  "While to your eyes the avenging power of Heaven",
  "Appears in aweful anger to prepare",
  "The storm of vengeance, fraught with plagues and death.",
  "Even he of milder heart, who was indeed",
  "The simple shepherd in a rustic scene,",
  "And, 'mid the vine-clad hills of Languedoc,",
  "Taught to the bare-foot peasant, whose hard hands",
  "Produc'd 4 the nectar he could seldom taste,",
  "Submission to the Lord for whom he toil'd;",
  "He, or his brethren, who to Neustria's sons",
  "Enforc'd religious patience, when, at times,",
  "On their indignant hearts Power's iron hand",
  "Too strongly struck; eliciting some sparks",
  "Of the bold spirit of their native North;",
  "Even these Parochial Priests, these humbled men;",
  "Whose lowly undistinguish'd cottages",
  "Witness'd a life of purest piety,",
  "While the meek tenants were, perhaps, unknown",
  "Each to the haughty Lord of his domain,",
  "Who mark'd them not; the Noble scorning still",
  "The poor and pious Priest, as with slow pace",
  "He glided thro' the dim arch'd avenue",
  "Which to the Castle led; hoping to cheer",
  "The last sad hour of some laborious life",
  "That hasten'd to its close--even such a Man",
  "Becomes an exile; staying not to try",
  "By temperate zeal to check his madd'ning flock,",
  "Who, at the novel sound of Liberty",
  "(Ah! most intoxicating sound to slaves!),",
  "Start into licence--Lo! dejected now,",
  "The wandering Pastor mourns, with bleeding heart,",
  "His erring people, weeps and prays for them,",
  "And trembles for the account that he must give",
  "To Heaven for souls entrusted to his care.--",
  "Where the cliff, hollow'd by the wintry storm,",
  "Affords a seat with matted sea-weed strewn,",
  "A softer form reclines; around her run,",
  "On the rough shingles, or the chalky bourn,",
  "Her gay unconscious children, soon amus'd;",
  "Who pick the fretted stone, or glossy shell,",
  "Or crimson plant marine: or they contrive",
  "The fairy vessel, with its ribband sail",
  "And gilded paper pennant: in the pool,",
  "Left by the salt wave on the yielding sands,",
  "They launch the mimic navy--Happy age!",
  "Unmindful of the miseries of Man!--",
  "Alas! too long a victim to distress,",
  "Their Mother, lost in melancholy thought,",
  "Lull'd for a moment by the murmurs low",
  "Of sullen billows, wearied by the task",
  "Of having here, with swol'n and aching eyes",
  "Fix'd on the grey horizon, since the dawn",
  "Solicitously watch'd the weekly sail",
  "From her dear native land, now yields awhile",
  "To kind forgetfulness, while Fancy brings,",
  "In waking dreams, that native land again!",
  "Versailles appears--its painted galleries,",
  "And rooms of regal splendour, rich with gold,",
  "Where, by long mirrors multiply'd, the crowd",
  "Paid willing homage--and, united there,",
  "Beauty gave charms to empire--Ah! too soon",
  "From the gay visionary pageant rous'd,",
  "See the sad mourner start!--and, drooping, look",
  "With tearful eyes and heaving bosom round",
  "On drear reality--where dark'ning waves,",
  "Urg'd by the rising wind, unheeded foam",
  "Near her cold rugged seat:--To call her thence",
  "A fellow-sufferer comes: dejection deep",
  "Checks, but conceals not quite, the martial air,",
  "And that high consciousness of noble blood,",
  "Which he has learn'd from infancy to think",
  "Exalts him o'er the race of common men:",
  "Nurs'd in the velvet lap of luxury,",
  "And fed by adulation--could he learn,",
  "That worth alone is true Nobility?",
  "And that the peasant who, \"amid 5 the sons",
  "\"Of Reason, Valour, Liberty, and Virtue,",
  "\"Displays distinguish'd merit, is a Noble",
  "\"Of Nature's own creation!\"--If even here,",
  "If in this land of highly vaunted Freedom,",
  "Even Britons controvert the unwelcome truth,",
  "Can it be relish'd by the sons of France?",
  "Men, who derive their boasted ancestry",
  "From the fierce leaders of religious wars,",
  "The first in Chivalry's emblazon'd page;",
  "Who reckon Gueslin, Bayard, or De Foix,",
  "Among their brave Progenitors? Their eyes,",
  "Accustom'd to regard the splendid trophies",
  "Of Heraldry (that with fantastic hand",
  "Mingles, like images in feverish dreams,",
  "\"Gorgons and Hydras, and Chimeras dire,\"",
  "With painted puns, and visionary shapes;),",
  "See not the simple dignity of Virtue,",
  "But hold all base, whom honours such as these",
  "Exalt not from the crowd 6 --As one, who long",
  "Has dwelt amid the artificial scenes",
  "Of populous City, deems that splendid shows,",
  "The Theatre, and pageant pomp of Courts,",
  "Are only worth regard; forgets all taste",
  "For Nature's genuine beauty; in the lapse",
  "Of gushing waters hears no soothing sound,",
  "Nor listens with delight to sighing winds,",
  "That, on their fragrant pinions, waft the notes",
  "Of birds rejoicing in the trangled copse;",
  "Nor gazes pleas'd on Ocean's silver breast,",
  "While lightly o'er it sails the summer clouds",
  "Reflected in the wave, that, hardly heard,",
  "Flows on the yellow sands: so to his mind,",
  "That long has liv'd where Despotism hides",
  "His features harsh, beneath the diadem",
  "Of worldly grandeur, abject Slavery seems,",
  "If by that power impos'd, slavery no more:",
  "For luxury wreathes with silk the iron bonds,",
  "And hides the ugly rivets with her flowers,",
  "Till the degenerate triflers, while they love",
  "The glitter of the chains, forget their weight.",
  "But more the Men, whose ill acquir'd wealth",
  "Was wrung from plunder'd myriads, by the means",
  "Too often legaliz'd by power abus'd,",
  "Feel all the horrors of the fatal change,",
  "When their ephemeral greatness, marr'd at once",
  "(As a vain toy that Fortune's childish hand",
  "Equally joy'd to fashion or to crush),",
  "Leaves them expos'd to universal scorn",
  "For having nothing else; not even the claim",
  "To honour, which respect for Heroes past",
  "Allows to ancient titles; Men, like these,",
  "Sink even beneath the level, whence base arts",
  "Alone had rais'd them;--unlamented sink,",
  "And know that they deserve the woes they feel.",
  "Poor wand'ring wretches! whosoe'er ye are,",
  "That hopeless, houseless, friendless, travel wide",
  "O'er these bleak russet downs; where, dimly seen,",
  "The solitary Shepherd shiv'ring tends",
  "His dun discolour'd flock (Shepherd, unlike",
  "Him, whom in song the Poet's fancy crowns",
  "With garlands, and his crook with vi'lets binds);",
  "Poor vagrant wretches! outcasts of the world!",
  "Whom no abode receives, no parish owns;",
  "Roving, like Nature's commoners, the land",
  "That boasts such general plenty: if the sight",
  "Of wide-extended misery softens yours",
  "Awhile, suspend your murmurs!--here behold",
  "The strange vicissitudes of fate--while thus",
  "The exil'd Nobles, from their country driven,",
  "Whose richest luxuries were their's, must feel",
  "More poignant anguish, than the lowest poor,",
  "Who, born to indigence, have learn'd to brave",
  "Rigid Adversity's depressing breath!--",
  "Ah! rather Fortune's worthless favourites!",
  "Who feed on England's vitals--Pensioners",
  "Of base corruption, who, in quick ascent",
  "To opulence unmerited, become",
  "Giddy with pride, and as ye rise, forgetting",
  "The dust ye lately left, with scorn look down",
  "On those beneath ye (tho' your equals once",
  "In fortune , and in worth superior still ,",
  "They view the eminence, on which ye stand,",
  "With wonder, not with envy; for they know",
  "The means, by which ye reach'd it, have been such",
  "As, in all honest eyes, degrade ye far",
  "Beneath the poor dependent, whose sad heart",
  "Reluctant pleads for what your pride denies);",
  "Ye venal, worthless hirelings of a Court!",
  "Ye pamper'd Parasites! whom Britons pay",
  "For forging fetters for them; rather here",
  "Study a lesson that concerns ye much;",
  "And, trembling, learn, that if oppress'd too long,",
  "The raging multitude, to madness stung,",
  "Will turn on their oppressors; and, no more",
  "By sounding titles and parading forms",
  "Bound like tame victims, will redress themselves!",
  "Then swept away by the resistless torrent,",
  "Not only all your pomp may disappear,",
  "But, in the tempest lost, fair Order sink",
  "Her decent head, and lawless Anarchy",
  "O'erturn celestial Freedom's radiant throne;--",
  "As now in Gallia; where Confusion, born",
  "Of party rage and selfish love of rule,",
  "Sully the noblest cause that ever warm'd",
  "The heart of Patriot Virtue 8 --There arise",
  "The infernal passions; Vengeance, seeking blood,",
  "And Avarice; and Envy's harpy fangs",
  "Pollute the immortal shrine of Liberty,",
  "Dismay her votaries, and disgrace her name.",
  "Respect is due to principle; and they,",
  "Who suffer for their conscience, have a claim,",
  "Whate'er that principle may be, to praise.",
  "These ill-starr'd Exiles then, who, bound by ties,",
  "To them the bonds of honour; who resign'd",
  "Their country to preserve them, and now seek",
  "In England an asylum--well deserve",
  "To find that (every prejudice forgot,",
  "Which pride and ignorance teaches), we for them",
  "Feel as our brethren; and that English hearts,",
  "Of just compassion ever own the sway,",
  "As truly as our element, the deep,",
  "Obeys the mild dominion of the Moon--",
  "This they have found; and may they find it still!",
  "Thus may'st thou, Britain, triumph!--May thy foes,",
  "By Reason's gen'rous potency subdued,",
  "Learn, that the God thou worshippest, delights",
  "In acts of pure humanity!--May thine",
  "Be still such bloodless laurels! nobler far",
  "Than those acquir'd at Cressy or Poictiers,",
  "Or of more recent growth, those well bestow'd",
  "On him who stood on Calpe's blazing height",
  "Amid the thunder of a warring world,",
  "Illustrious rather from the crowds he sav'd",
  "From flood and fire, than from the ranks who fell",
  "Beneath his valour!--Actions such as these,",
  "Like incense rising to the Throne of Heaven,",
  "Far better justify the pride, that swells",
  "In British bosoms, than the deafening roar",
  "Of Victory from a thousand brazen throats,",
  "That tell with what success wide-wasting War",
  "Has by our brave Compatriots thinned the world.",
  ""
]