module.exports = [
  "THE PROLOGUE.",
  "",
  "WHEN said was this miracle, every man",
  "As sober was, that wonder was to see,",
  "Till that our Host to japen he began,",
  "And then at erst he looked upon me,",
  "And saide thus; \"What man art thou?\" quoth he;",
  "\"Thou lookest as thou wouldest find an hare,",
  "For ever on the ground I see thee stare.",
  "",
  "\"Approache near, and look up merrily.",
  "Now ware you, Sirs, and let this man have place.",
  "He in the waist is shapen as well as I;",
  "This were a puppet in an arm t'embrace",
  "For any woman small and fair of face.",
  "He seemeth elvish by his countenance,",
  "For unto no wight doth he dalliance.",
  "",
  "\"Say now somewhat, since other folk have said;",
  "Tell us a tale of mirth, and that anon.\"",
  "\"Hoste,\" quoth I, \"be not evil apaid,",
  "For other tale certes can I none,",
  "Eut of a rhyme I learned yore agone.\"",
  "\"Yea, that is good,\" quoth he; \"now shall we hear",
  "Some dainty thing, me thinketh by thy cheer.\"",
  "",
  "THE TALE",
  "",
  "The First Fit",
  "",
  "Listen, lordings, in good intent,",
  "And I will tell you verrament",
  "Of mirth and of solas,",
  "All of a knight was fair and gent,",
  "In battle and in tournament,",
  "His name was Sir Thopas.",
  "",
  "Y-born he was in far country,",
  "In Flanders, all beyond the sea,",
  "At Popering  in the place;",
  "His father was a man full free,",
  "And lord he was of that country,",
  "As it was Godde's grace.",
  "",
  "Sir Thopas was a doughty swain,",
  "White was his face as paindemain,",
  "His lippes red as rose.",
  "His rode is like scarlet in grain,",
  "And I you tell in good certain",
  "He had a seemly nose.",
  "",
  "His hair, his beard, was like saffroun,",
  "That to his girdle reach'd adown,",
  "His shoes of cordewane:",
  "Of Bruges were his hosen brown;",
  "His robe was of ciclatoun,",
  "That coste many a jane.",
  "",
  "He coulde hunt at the wild deer,",
  "And ride on hawking for rivere",
  "With gray goshawk on hand:",
  "Thereto he was a good archere,",
  "Of wrestling was there none his peer,",
  "Where any ram  should stand.",
  "",
  "Full many a maiden bright in bow'r",
  "They mourned for him par amour,",
  "When them were better sleep;",
  "But he was chaste, and no lechour,",
  "And sweet as is the bramble flow'r",
  "That beareth the red heep.",
  "",
  "And so it fell upon a day,",
  "For sooth as I you telle may,",
  "Sir Thopas would out ride;",
  "He worth upon his steede gray,",
  "And in his hand a launcegay,",
  "A long sword by his side.",
  "",
  "He pricked through a fair forest,",
  "Wherein is many a wilde beast,",
  "Yea, bothe buck and hare;",
  "And as he pricked north and east,",
  "I tell it you, him had almest",
  "Betid a sorry care.",
  "",
  "There sprange herbes great and small,",
  "The liquorice and the setewall,",
  "And many a clove-gilofre,",
  "And nutemeg to put in ale,",
  "Whether it be moist or stale,",
  "Or for to lay in coffer.",
  "",
  "The birdes sang, it is no nay,",
  "The sperhawk and the popinjay,",
  "That joy it was to hear;",
  "The throstle-cock made eke his lay,",
  "The woode-dove upon the spray",
  "She sang full loud and clear.",
  "",
  "Sir Thopas fell in love-longing",
  "All when he heard the throstle sing,",
  "And prick'd as he were wood;",
  "His faire steed in his pricking",
  "So sweated, that men might him wring,",
  "His sides were all blood.",
  "",
  "Sir Thopas eke so weary was",
  "For pricking on the softe grass,",
  "So fierce was his corage,",
  "That down he laid him in that place,",
  "To make his steed some solace,",
  "And gave him good forage.",
  "",
  "\"Ah, Saint Mary, ben'dicite,",
  "What aileth thilke love at me",
  "To binde me so sore?",
  "Me dreamed all this night, pardie,",
  "An elf-queen shall my leman be,",
  "And sleep under my gore.",
  "",
  "An elf-queen will I love, y-wis,",
  "For in this world no woman is",
  "Worthy to be my make",
  "In town;",
  "All other women I forsake,",
  "And to an elf-queen I me take",
  "By dale and eke by down.\"",
  "",
  "Into his saddle he clomb anon,",
  "And pricked over stile and stone",
  "An elf-queen for to spy,",
  "Till he so long had ridden and gone,",
  "That he found in a privy wonne",
  "The country of Faery,",
  "So wild;",
  "For in that country was there none",
  "That to him durste ride or gon,",
  "Neither wife nor child.",
  "",
  "Till that there came a great giaunt,",
  "His name was Sir Oliphaunt,",
  "A perilous man of deed;",
  "He saide, \"Child, by Termagaunt,",
  "But if thou prick out of mine haunt,",
  "Anon I slay thy steed",
  "With mace.",
  "Here is the Queen of Faery,",
  "With harp, and pipe, and symphony,",
  "Dwelling in this place.\"",
  "",
  "The Child said, \"All so may I the,",
  "To-morrow will I meete thee,",
  "When I have mine armor;",
  "And yet I hope, par ma fay,",
  "That thou shalt with this launcegay",
  "Abyen it full sore;",
  "Thy maw",
  "Shall I pierce, if I may,",
  "Ere it be fully prime of day,",
  "For here thou shalt be slaw.\"",
  "",
  "Sir Thopas drew aback full fast;",
  "This giant at him stones cast",
  "Out of a fell staff sling:",
  "But fair escaped Child Thopas,",
  "And all it was through Godde's grace,",
  "And through his fair bearing.",
  "",
  "Yet listen, lordings, to my tale,",
  "Merrier than the nightingale,",
  "For now I will you rown,",
  "How Sir Thopas, with sides smale,",
  "Pricking over hill and dale,",
  "Is come again to town.",
  "",
  "His merry men commanded he",
  "To make him both game and glee;",
  "For needes must he fight",
  "With a giant with heades three,",
  "For paramour and jollity",
  "Of one that shone full bright.",
  "",
  "\"Do come,\" he saide, \"my minstrales",
  "And gestours for to telle tales.",
  "Anon in mine arming,",
  "Of romances that be royales,",
  "Of popes and of cardinales,",
  "And eke of love-longing.\"",
  "",
  "They fetch'd him first the sweete wine,",
  "And mead eke in a maseline,",
  "And royal spicery;",
  "Of ginger-bread that was full fine,",
  "And liquorice and eke cumin,",
  "With sugar that is trie.",
  "",
  "He didde, next his white lere,",
  "Of cloth of lake fine and clear,",
  "A breech and eke a shirt;",
  "And next his shirt an haketon,",
  "And over that an habergeon,",
  "For piercing of his heart;",
  "",
  "And over that a fine hauberk,",
  "Was all y-wrought of Jewes' werk,",
  "Full strong it was of plate;",
  "And over that his coat-armour,",
  "As white as is the lily flow'r,",
  "In which he would debate.",
  "",
  "His shield was all of gold so red",
  "And therein was a boare's head,",
  "A charboucle beside;",
  "And there he swore on ale and bread,",
  "How that the giant should be dead,",
  "Betide whatso betide.",
  "",
  "His jambeaux were of cuirbouly,",
  "His sworde's sheath of ivory,",
  "His helm of latoun bright,",
  "His saddle was of rewel  bone,",
  "His bridle as the sunne shone,",
  "Or as the moonelight.",
  "",
  "His speare was of fine cypress,",
  "That bodeth war, and nothing peace;",
  "The head full sharp y-ground.",
  "His steede was all dapple gray,",
  "It went an amble in the way",
  "Full softely and round",
  "In land.",
  "",
  "Lo, Lordes mine, here is a fytt;",
  "If ye will any more of it,",
  "To tell it will I fand.",
  "",
  "The Second Fit",
  "",
  "Now hold your mouth for charity,",
  "Bothe knight and lady free,",
  "And hearken to my spell;",
  "Of battle and of chivalry,",
  "Of ladies' love and druerie,",
  "Anon I will you tell.",
  "",
  "Men speak of romances of price",
  "Of Horn Child, and of Ipotis,",
  "Of Bevis, and Sir Guy,",
  "Of Sir Libeux,  and Pleindamour,",
  "But Sir Thopas, he bears the flow'r",
  "Of royal chivalry.",
  "",
  "His goode steed he all bestrode,",
  "And forth upon his way he glode,",
  "As sparkle out of brand;",
  "Upon his crest he bare a tow'r,",
  "And therein stick'd a lily flow'r;",
  "God shield his corse from shand!",
  "",
  "And, for he was a knight auntrous,",
  "He woulde sleepen in none house,",
  "But liggen in his hood,",
  "His brighte helm was his wanger,",
  "And by him baited his destrer",
  "Of herbes fine and good.",
  "",
  "Himself drank water of the well,",
  "As did the knight Sir Percivel,",
  "So worthy under weed;",
  "Till on a day -   .   .   .",
  ""
]