module.exports = [
  "THERE are so many things I have forgot,",
  "That once were much to me, or that were not,",
  "All lost, as is a childless woman's child",
  "And its child's children, in the undefiled",
  "Abyss of what can never be again.",
  "I have forgot, too, names of the mighty men",
  "That fought and lost or won in the old wars,",
  "Of kings and fiends and gods, and most of the stars.",
  "Some things I have forgot that I forget.",
  "But lesser things there are, remembered yet,",
  "Than all the others. One name that I have not--",
  "Though 'tis an empty thingless name--forgot",
  "Never can die because Spring after Spring",
  "Some thrushes learn to say it as they sing.",
  "There is always one at midday saying it clear",
  "And tart--the name, only the name I hear.",
  "While perhaps I am thinking of the elder scent",
  "That is like food, or while I am content",
  "With the wild rose scent that is like memory,",
  "This name suddenly is cried out to me",
  "From somewhere in the bushes by a bird",
  "Over and over again, a pure thrush word.",
  ""
]