module.exports = [
  "THE PROLOGUE.",
  "",
  "OUR Hoste gan to swear as he were wood;",
  "\"Harow!\" quoth he, \"by nailes and by blood,",
  "This was a cursed thief, a false justice.",
  "As shameful death as hearte can devise",
  "Come to these judges and their advoca's.",
  "Algate this sely maid is slain, alas!",
  "Alas! too deare bought she her beauty.",
  "Wherefore I say, that all day man may see",
  "That giftes of fortune and of nature",
  "Be cause of death to many a creature.",
  "Her beauty was her death, I dare well sayn;",
  "Alas! so piteously as she was slain.",
  "[Of bothe giftes, that I speak of now",
  "Men have full often more harm than prow,]",
  "But truely, mine owen master dear,",
  "This was a piteous tale for to hear;",
  "But natheless, pass over; 'tis no force.",
  "I pray to God to save thy gentle corse,",
  "And eke thine urinals, and thy jordans,",
  "Thine Hippocras, and eke thy Galliens,",
  "And every boist full of thy lectuary,",
  "God bless them, and our lady Sainte Mary.",
  "So may I the', thou art a proper man,",
  "And like a prelate, by Saint Ronian;",
  "Said I not well? Can I not speak in term?",
  "But well I wot thou dost mine heart to erme,",
  "That I have almost caught a cardiacle:",
  "By corpus Domini , but I have triacle,",
  "Or else a draught of moist and corny  ale,",
  "Or but I hear anon a merry tale,",
  "Mine heart is brost for pity of this maid.",
  "Thou bel ami, thou Pardoner,\" he said,",
  "\"Tell us some mirth of japes right anon.\"",
  "\"It shall be done,\" quoth he, \"by Saint Ronion.",
  "But first,\" quoth he, \"here at this ale-stake",
  "I will both drink, and biten on a cake.\"",
  "But right anon the gentles gan to cry,",
  "\"Nay, let him tell us of no ribaldry.",
  "Tell us some moral thing, that we may lear",
  "Some wit, and thenne will we gladly hear.\"",
  "\"I grant y-wis,\" quoth he; \"but I must think",
  "Upon some honest thing while that I drink.\"",
  "",
  "THE TALE",
  "",
  "Lordings (quoth he), in churche when I preach,",
  "I paine me to have an hautein speech,",
  "And ring it out, as round as doth a bell,",
  "For I know all by rote that I tell.",
  "My theme is always one, and ever was;",
  "Radix malorum est cupiditas.",
  "First I pronounce whence that I come,",
  "And then my bulles shew I all and some;",
  "Our liege lorde's seal on my patent,",
  "That shew I first, my body to warrent,",
  "That no man be so hardy, priest nor clerk,",
  "Me to disturb of Christe's holy werk.",
  "And after that then tell I forth my tales.",
  "Bulles of popes, and of cardinales,",
  "Of patriarchs, and of bishops I shew,",
  "And in Latin I speak a wordes few,",
  "To savour with my predication,",
  "And for to stir men to devotion",
  "Then show I forth my longe crystal stones,",
  "Y-crammed fall of cloutes and of bones;",
  "Relics they be, as weene they each one.",
  "Then have I in latoun a shoulder-bone",
  "Which that was of a holy Jewe's sheep.",
  "\"Good men,\" say I, \"take of my wordes keep;",
  "If that this bone be wash'd in any well,",
  "If cow, or calf, or sheep, or oxe swell,",
  "That any worm hath eat, or worm y-stung,",
  "Take water of that well, and wash his tongue,",
  "And it is whole anon; and farthermore",
  "Of pockes, and of scab, and every sore",
  "Shall every sheep be whole, that of this well",
  "Drinketh a draught; take keep of that I tell.",
  "",
  "\"If that the goodman, that the beastes oweth,",
  "Will every week, ere that the cock him croweth,",
  "Fasting, y-drinken of this well a draught,",
  "As thilke holy Jew our elders taught,",
  "His beastes and his store shall multiply.",
  "And, Sirs, also it healeth jealousy;",
  "For though a man be fall'n in jealous rage,",
  "Let make with this water his pottage,",
  "And never shall he more his wife mistrist,",
  "Though he the sooth of her defaulte wist;",
  "All had she taken priestes two or three.",
  "Here is a mittain eke, that ye may see;",
  "He that his hand will put in this mittain,",
  "He shall have multiplying of his grain,",
  "When he hath sowen, be it wheat or oats,",
  "So that he offer pence, or elles groats.",
  "And, men and women, one thing warn I you;",
  "If any wight be in this churche now",
  "That hath done sin horrible, so that he",
  "Dare not for shame of it y-shriven be;",
  "Or any woman, be she young or old,",
  "That hath y-made her husband cokewold,",
  "Such folk shall have no power nor no grace",
  "To offer to my relics in this place.",
  "And whoso findeth him out of such blame,",
  "He will come up and offer in God's name;",
  "And I assoil him by the authority",
  "Which that by bull y-granted was to me.\"",
  "",
  "By this gaud have I wonne year by year",
  "A hundred marks, since I was pardonere.",
  "I stande like a clerk in my pulpit,",
  "And when the lewed people down is set,",
  "I preache so as ye have heard before,",
  "And telle them a hundred japes more.",
  "Then pain I me to stretche forth my neck,",
  "And east and west upon the people I beck,",
  "As doth a dove, sitting on a bern;",
  "My handes and my tongue go so yern,",
  "That it is joy to see my business.",
  "Of avarice and of such cursedness",
  "Is all my preaching, for to make them free",
  "To give their pence, and namely unto me.",
  "For mine intent is not but for to win,",
  "And nothing for correction of sin.",
  "I recke never, when that they be buried,",
  "Though that their soules go a blackburied.",
  "For certes many a predication",
  "Cometh oft-time of evil intention;",
  "Some for pleasance of folk, and flattery,",
  "To be advanced by hypocrisy;",
  "And some for vainglory, and some for hate.",
  "For, when I dare not otherwise debate,",
  "Then will I sting him with my tongue smart",
  "In preaching, so that he shall not astart",
  "To be defamed falsely, if that he",
  "Hath trespass'd to my brethren or to me.",
  "For, though I telle not his proper name,",
  "Men shall well knowe that it is the same",
  "By signes, and by other circumstances.",
  "Thus quite I folk that do us displeasances:",
  "Thus spit I out my venom, under hue",
  "Of holiness, to seem holy and true.",
  "But, shortly mine intent I will devise,",
  "I preach of nothing but of covetise.",
  "Therefore my theme is yet, and ever was, --",
  "Radix malorum est cupiditas.",
  "Thus can I preach against the same vice",
  "Which that I use, and that is avarice.",
  "But though myself be guilty in that sin,",
  "Yet can I maken other folk to twin",
  "From avarice, and sore them repent.",
  "But that is not my principal intent;",
  "I preache nothing but for covetise.",
  "Of this mattere it ought enough suffice.",
  "Then tell I them examples many a one,",
  "Of olde stories longe time gone;",
  "For lewed people love tales old;",
  "Such thinges can they well report and hold.",
  "What? trowe ye, that whiles I may preach",
  "And winne gold and silver for I teach,",
  "That I will live in povert' wilfully?",
  "Nay, nay, I thought it never truely.",
  "For I will preach and beg in sundry lands;",
  "I will not do no labour with mine hands,",
  "Nor make baskets for to live thereby,",
  "Because I will not beggen idlely.",
  "I will none of the apostles counterfeit;",
  "I will have money, wool, and cheese, and wheat,",
  "All were it given of the poorest page,",
  "Or of the pooreste widow in a village:",
  "All should her children sterve for famine.",
  "Nay, I will drink the liquor of the vine,",
  "And have a jolly wench in every town.",
  "But hearken, lordings, in conclusioun;",
  "Your liking is, that I shall tell a tale",
  "Now I have drunk a draught of corny ale,",
  "By God, I hope I shall you tell a thing",
  "That shall by reason be to your liking;",
  "For though myself be a full vicious man,",
  "A moral tale yet I you telle can,",
  "Which I am wont to preache, for to win.",
  "Now hold your peace, my tale I will begin.",
  "",
  "In Flanders whilom was a company",
  "Of younge folkes, that haunted folly,",
  "As riot, hazard, stewes, and taverns;",
  "Where as with lutes, harpes, and giterns,",
  "They dance and play at dice both day and night,",
  "And eat also, and drink over their might;",
  "Through which they do the devil sacrifice",
  "Within the devil's temple, in cursed wise,",
  "By superfluity abominable.",
  "Their oathes be so great and so damnable,",
  "That it is grisly for to hear them swear.",
  "Our blissful Lorde's body they to-tear;",
  "Them thought the Jewes rent him not enough,",
  "And each of them at other's sinne lough.",
  "And right anon in come tombesteres",
  "Fetis and small, and younge fruitesteres.",
  "Singers with harpes, baudes, waferers,",
  "Which be the very devil's officers,",
  "To kindle and blow the fire of lechery,",
  "That is annexed unto gluttony.",
  "The Holy Writ take I to my witness,",
  "That luxury is in wine and drunkenness.",
  "Lo, how that drunken Lot unkindely",
  "Lay by his daughters two unwittingly,",
  "So drunk he was he knew not what he wrought.",
  "Herodes, who so well the stories sought,",
  "When he of wine replete was at his feast,",
  "Right at his owen table gave his hest",
  "To slay the Baptist John full guilteless.",
  "Seneca saith a good word, doubteless:",
  "He saith he can no difference find",
  "Betwixt a man that is out of his mind,",
  "And a man whiche that is drunkelew:",
  "But that woodness, y-fallen in a shrew,",
  "Persevereth longer than drunkenness.",
  "",
  "O gluttony, full of all cursedness;",
  "O cause first of our confusion,",
  "Original of our damnation,",
  "Till Christ had bought us with his blood again!",
  "Looke, how deare, shortly for to sayn,",
  "Abought was first this cursed villainy:",
  "Corrupt was all this world for gluttony.",
  "Adam our father, and his wife also,",
  "From Paradise, to labour and to woe,",
  "Were driven for that vice, it is no dread.",
  "For while that Adam fasted, as I read,",
  "He was in Paradise; and when that he",
  "Ate of the fruit defended of the tree,",
  "Anon he was cast out to woe and pain.",
  "O gluttony! well ought us on thee plain.",
  "Oh! wist a man how many maladies",
  "Follow of excess and of gluttonies,",
  "He woulde be the more measurable",
  "Of his diete, sitting at his table.",
  "Alas! the shorte throat, the tender mouth,",
  "Maketh that east and west, and north and south,",
  "In earth, in air, in water, men do swink",
  "To get a glutton dainty meat and drink.",
  "Of this mattere, O Paul! well canst thou treat",
  "Meat unto womb, and womb eke unto meat,",
  "Shall God destroye both, as Paulus saith.",
  "Alas! a foul thing is it, by my faith,",
  "To say this word, and fouler is the deed,",
  "When man so drinketh of the white and red,",
  "That of his throat he maketh his privy",
  "Through thilke cursed superfluity",
  "The apostle saith,  weeping full piteously,",
  "There walk many, of which you told have I, --",
  "I say it now weeping with piteous voice, --",
  "That they be enemies of Christe's crois;",
  "Of which the end is death; womb is their God.",
  "O womb, O belly, stinking is thy cod,",
  "Full fill'd of dung and of corruptioun;",
  "At either end of thee foul is the soun.",
  "How great labour and cost is thee to find!",
  "These cookes how they stamp, and strain, and grind,",
  "And turne substance into accident,",
  "To fulfill all thy likerous talent!",
  "Out of the harde bones knocke they",
  "The marrow, for they caste naught away",
  "That may go through the gullet soft and swoot",
  "Of spicery and leaves, of bark and root,",
  "Shall be his sauce y-maked by delight,",
  "To make him have a newer appetite.",
  "But, certes, he that haunteth such delices",
  "Is dead while that he liveth in those vices.",
  "",
  "A lecherous thing is wine, and drunkenness",
  "Is full of striving and of wretchedness.",
  "O drunken man! disfgur'd is thy face,",
  "Sour is thy breath, foul art thou to embrace:",
  "And through thy drunken nose sowneth the soun',",
  "As though thous saidest aye, Samsoun! Samsoun!",
  "And yet, God wot, Samson drank never wine.",
  "Thou fallest as it were a sticked swine;",
  "Thy tongue is lost, and all thine honest cure;",
  "For drunkenness is very sepulture",
  "Of manne's wit and his discretion.",
  "In whom that drink hath domination,",
  "He can no counsel keep, it is no dread.",
  "Now keep you from the white and from the red,",
  "And namely from the white wine of Lepe,",
  "That is to sell in Fish Street  and in Cheap.",
  "This wine of Spaine creepeth subtilly  --",
  "In other wines growing faste by,",
  "Of which there riseth such fumosity,",
  "That when a man hath drunken draughtes three,",
  "And weeneth that he be at home in Cheap,",
  "He is in Spain, right at the town of Lepe,",
  "Not at the Rochelle, nor at Bourdeaux town;",
  "And thenne will he say, Samsoun! Samsoun!",
  "But hearken, lordings, one word, I you pray,",
  "That all the sovreign actes, dare I say,",
  "Of victories in the Old Testament,",
  "Through very God that is omnipotent,",
  "Were done in abstinence and in prayere:",
  "Look in the Bible, and there ye may it lear.",
  "Look, Attila, the greate conqueror,",
  "Died in his sleep,  with shame and dishonour,",
  "Bleeding aye at his nose in drunkenness:",
  "A captain should aye live in soberness",
  "And o'er all this, advise you right well",
  "What was commanded unto Lemuel;",
  "Not Samuel, but Lemuel, say I.",
  "Reade the Bible, and find it expressly",
  "Of wine giving to them that have justice.",
  "No more of this, for it may well suffice.",
  "",
  "And, now that I have spoke of gluttony,",
  "Now will I you defende hazardry.",
  "Hazard is very mother of leasings,",
  "And of deceit, and cursed forswearings:",
  "Blasphem' of Christ, manslaughter, and waste also",
  "Of chattel and of time; and furthermo'",
  "It is repreve, and contrar' of honour,",
  "For to be held a common hazardour.",
  "And ever the higher he is of estate,",
  "The more he is holden desolate.",
  "If that a prince use hazardry,",
  "In alle governance and policy",
  "He is, as by common opinion,",
  "Y-hold the less in reputation.",
  "",
  "Chilon, that was a wise ambassador,",
  "Was sent to Corinth with full great honor",
  "From Lacedemon,  to make alliance;",
  "And when he came, it happen'd him, by chance,",
  "That all the greatest that were of that land,",
  "Y-playing atte hazard he them fand.",
  "For which, as soon as that it mighte be,",
  "He stole him home again to his country",
  "And saide there, \"I will not lose my name,",
  "Nor will I take on me so great diffame,",
  "You to ally unto no hazardors.",
  "Sende some other wise ambassadors,",
  "For, by my troth, me were lever die,",
  "Than I should you to hazardors ally.",
  "For ye, that be so glorious in honours,",
  "Shall not ally you to no hazardours,",
  "As by my will, nor as by my treaty.\"",
  "This wise philosopher thus said he.",
  "Look eke how to the King Demetrius",
  "The King of Parthes, as the book saith us,",
  "Sent him a pair of dice of gold in scorn,",
  "For he had used hazard therebeforn:",
  "For which he held his glory and renown",
  "At no value or reputatioun.",
  "Lordes may finden other manner play",
  "Honest enough to drive the day away.",
  "",
  "Now will I speak of oathes false and great",
  "A word or two, as olde bookes treat.",
  "Great swearing is a thing abominable,",
  "And false swearing is more reprovable.",
  "The highe God forbade swearing at all;",
  "Witness on Matthew:  but in special",
  "Of swearing saith the holy Jeremie,",
  "Thou thalt swear sooth thine oathes, and not lie:",
  "And swear in doom and eke in righteousness;",
  "But idle swearing is a cursedness.",
  "Behold and see, there in the firste table",
  "Of highe Godde's hestes honourable,",
  "How that the second best of him is this,",
  "Take not my name in idle or amiss.",
  "Lo, rather he forbiddeth such swearing,",
  "Than homicide, or many a cursed thing;",
  "I say that as by order thus it standeth;",
  "This knoweth he that his hests understandeth,",
  "How that the second hest of God is that.",
  "And farthermore, I will thee tell all plat,",
  "That vengeance shall not parte from his house,",
  "That of his oathes is outrageous.",
  "\"By Godde's precious heart, and by his nails,",
  "And by the blood of Christ, that is in Hailes,",
  "Seven is my chance, and thine is cinque and trey:",
  "By Godde's armes, if thou falsely play,",
  "This dagger shall throughout thine hearte go.\"",
  "This fruit comes of the bicched bones two,",
  "Forswearing, ire, falseness, and homicide.",
  "Now, for the love of Christ that for us died,",
  "Leave your oathes, bothe great and smale.",
  "But, Sirs, now will I ell you forth my tale.",
  "",
  "These riotoures three, of which I tell,",
  "Long erst than prime rang of any bell,",
  "Were set them in a tavern for to drink;",
  "And as they sat, they heard a belle clink",
  "Before a corpse, was carried to the grave.",
  "That one of them gan calle to his knave,",
  "\"Go bet,\"  quoth he, \"and aske readily",
  "What corpse is this, that passeth here forth by;",
  "And look that thou report his name well.\"",
  "\"Sir,\" quoth the boy, \"it needeth never a deal;",
  "It was me told ere ye came here two hours;",
  "He was, pardie, an old fellow of yours,",
  "And suddenly he was y-slain to-night;",
  "Fordrunk as he sat on his bench upright,",
  "There came a privy thief, men clepe Death,",
  "That in this country all the people slay'th,",
  "And with his spear he smote his heart in two,",
  "And went his way withoute wordes mo'.",
  "He hath a thousand slain this pestilence;",
  "And, master, ere you come in his presence,",
  "Me thinketh that it were full necessary",
  "For to beware of such an adversary;",
  "Be ready for to meet him evermore.",
  "Thus taughte me my dame; I say no more.\"",
  "\"By Sainte Mary,\" said the tavernere,",
  "\"The child saith sooth, for he hath slain this year,",
  "Hence ov'r a mile, within a great village,",
  "Both man and woman, child, and hind, and page;",
  "I trow his habitation be there;",
  "To be advised great wisdom it were,",
  "Ere that he did a man a dishonour.\"",
  "",
  "\"Yea, Godde's armes,\" quoth this riotour,",
  "\"Is it such peril with him for to meet?",
  "I shall him seek, by stile and eke by street.",
  "I make a vow, by Godde's digne bones.\"",
  "Hearken, fellows, we three be alle ones:",
  "Let each of us hold up his hand to other,",
  "And each of us become the other's brother,",
  "And we will slay this false traitor Death;",
  "He shall be slain, he that so many slay'th,",
  "By Godde's dignity, ere it be night.\"",
  "Together have these three their trothe plight",
  "To live and die each one of them for other",
  "As though he were his owen sworen brother.",
  "And up they start, all drunken, in this rage,",
  "And forth they go towardes that village",
  "Of which the taverner had spoke beforn,",
  "And many a grisly oathe have they sworn,",
  "And Christe's blessed body they to-rent;",
  "\"Death shall be dead, if that we may him hent.\"",
  "When they had gone not fully half a mile,",
  "Right as they would have trodden o'er a stile,",
  "An old man and a poore with them met.",
  "This olde man full meekely them gret,",
  "And saide thus; \"Now, lordes, God you see!\"",
  "The proudest of these riotoures three",
  "Answer'd again; \"What? churl, with sorry grace,",
  "Why art thou all forwrapped save thy face?",
  "Why livest thou so long in so great age?\"",
  "This olde man gan look on his visage,",
  "And saide thus; \"For that I cannot find",
  "A man, though that I walked unto Ind,",
  "Neither in city, nor in no village go,",
  "That woulde change his youthe for mine age;",
  "And therefore must I have mine age still",
  "As longe time as it is Godde's will.",
  "And Death, alas! he will not have my life.",
  "Thus walk I like a resteless caitife,",
  "And on the ground, which is my mother's gate,",
  "I knocke with my staff, early and late,",
  "And say to her, 'Leve mother, let me in.",
  "Lo, how I wane, flesh, and blood, and skin;",
  "Alas! when shall my bones be at rest?",
  "Mother, with you I woulde change my chest,",
  "That in my chamber longe time hath be,",
  "Yea, for an hairy clout to wrap in me.'",
  "But yet to me she will not do that grace,",
  "For which fall pale and welked is my face.",
  "But, Sirs, to you it is no courtesy",
  "To speak unto an old man villainy,",
  "But he trespass in word or else in deed.",
  "In Holy Writ ye may yourselves read;",
  "'Against an old man, hoar upon his head,",
  "Ye should arise:' therefore I you rede,",
  "Ne do unto an old man no harm now,",
  "No more than ye would a man did you",
  "In age, if that ye may so long abide.",
  "And God be with you, whether ye go or ride",
  "I must go thither as I have to go.\"",
  "",
  "\"Nay, olde churl, by God thou shalt not so,\"",
  "Saide this other hazardor anon;",
  "\"Thou partest not so lightly, by Saint John.",
  "Thou spakest right now of that traitor Death,",
  "That in this country all our friendes slay'th;",
  "Have here my troth, as thou art his espy;",
  "Tell where he is, or thou shalt it abie,",
  "By God and by the holy sacrament;",
  "For soothly thou art one of his assent",
  "To slay us younge folk, thou false thief.\"",
  "\"Now, Sirs,\" quoth he, \"if it be you so lief",
  "To finde Death, turn up this crooked way,",
  "For in that grove I left him, by my fay,",
  "Under a tree, and there he will abide;",
  "Nor for your boast he will him nothing hide.",
  "See ye that oak? right there ye shall him find.",
  "God save you, that bought again mankind,",
  "And you amend!\" Thus said this olde man;",
  "And evereach of these riotoures ran,",
  "Till they came to the tree, and there they found",
  "Of florins fine, of gold y-coined round,",
  "Well nigh a seven bushels, as them thought.",
  "No longer as then after Death they sought;",
  "But each of them so glad was of the sight,",
  "For that the florins were so fair and bright,",
  "That down they sat them by the precious hoard.",
  "The youngest of them spake the firste word:",
  "\"Brethren,\" quoth he, \"take keep what I shall say;",
  "My wit is great, though that I bourde and play",
  "This treasure hath Fortune unto us given",
  "In mirth and jollity our life to liven;",
  "And lightly as it comes, so will we spend.",
  "Hey! Godde's precious dignity! who wend",
  "Today that we should have so fair a grace?",
  "But might this gold he carried from this place",
  "Home to my house, or elles unto yours",
  "(For well I wot that all this gold is ours),",
  "Then were we in high felicity.",
  "But truely by day it may not be;",
  "Men woulde say that we were thieves strong,",
  "And for our owen treasure do us hong.",
  "This treasure muste carried be by night,",
  "As wisely and as slily as it might.",
  "Wherefore I rede, that cut among us all",
  "We draw, and let see where the cut will fall:",
  "And he that hath the cut, with hearte blithe",
  "Shall run unto the town, and that full swithe,",
  "And bring us bread and wine full privily:",
  "And two of us shall keepe subtilly",
  "This treasure well: and if he will not tarry,",
  "When it is night, we will this treasure carry,",
  "By one assent, where as us thinketh best.\"",
  "Then one of them the cut brought in his fist,",
  "And bade them draw, and look where it would fall;",
  "And it fell on the youngest of them all;",
  "And forth toward the town he went anon.",
  "And all so soon as  that he was y-gone,",
  "The one of them spake thus unto the other;",
  "\"Thou knowest well that thou art my sworn brother,",
  "Thy profit will I tell thee right anon.",
  "Thou knowest well that our fellow is gone,",
  "And here is gold, and that full great plenty,",
  "That shall departed he among us three.",
  "But natheless, if I could shape it so",
  "That it departed were among us two,",
  "Had I not done a friende's turn to thee?\"",
  "Th' other answer'd, \"I n'ot how that may be;",
  "He knows well that the gold is with us tway.",
  "What shall we do? what shall we to him say?\"",
  "\"Shall it be counsel?\" said the firste shrew;",
  "\"And I shall tell to thee in wordes few",
  "What we shall do, and bring it well about.\"",
  "\"I grante,\" quoth the other, \"out of doubt,",
  "That by my truth I will thee not bewray.\"",
  "\"Now,\" quoth the first, \"thou know'st well we be tway,",
  "And two of us shall stronger be than one.",
  "Look; when that he is set, thou right anon",
  "Arise, as though thou wouldest with him play;",
  "And I shall rive him through the sides tway,",
  "While that thou strugglest with him as in game;",
  "And with thy dagger look thou do the same.",
  "And then shall all this gold departed be,",
  "My deare friend, betwixte thee and me:",
  "Then may we both our lustes all fulfil,",
  "And play at dice right at our owen will.\"",
  "And thus accorded be these shrewes tway",
  "To slay the third, as ye have heard me say.",
  "",
  "The youngest, which that wente to the town,",
  "Full oft in heart he rolled up and down",
  "The beauty of these florins new and bright.",
  "\"O Lord!\" quoth he, \"if so were that I might",
  "Have all this treasure to myself alone,",
  "There is no man that lives under the throne",
  "Of God, that shoulde have so merry as I.\"",
  "And at the last the fiend our enemy",
  "Put in his thought, that he should poison buy,",
  "With which he mighte slay his fellows twy.",
  "For why, the fiend found him in such living,",
  "That he had leave to sorrow him to bring.",
  "For this was utterly his full intent",
  "To slay them both, and never to repent.",
  "And forth he went, no longer would he tarry,",
  "Into the town to an apothecary,",
  "And prayed him that he him woulde sell",
  "Some poison, that he might his rattes quell,",
  "And eke there was a polecat in his haw,",
  "That, as he said, his eapons had y-slaw:",
  "And fain he would him wreak, if that he might,",
  "Of vermin that destroyed him by night.",
  "Th'apothecary answer'd, \"Thou shalt have",
  "A thing, as wisly God my soule save,",
  "In all this world there is no creature",
  "That eat or drank hath of this confecture,",
  "Not but the mountance of a corn of wheat,",
  "That he shall not his life anon forlete;",
  "Yea, sterve he shall, and that in lesse while",
  "Than thou wilt go apace nought but a mile:",
  "This poison is so strong and violent.\"",
  "This cursed man hath in his hand y-hent",
  "This poison in a box, and swift he ran",
  "Into the nexte street, unto a man,",
  "And borrow'd of him large bottles three;",
  "And in the two the poison poured he;",
  "The third he kepte clean for his own drink,",
  "For all the night he shope him for to swink",
  "In carrying off the gold out of that place.",
  "And when this riotour, with sorry grace,",
  "Had fill'd with wine his greate bottles three,",
  "",
  "To his fellows again repaired he.",
  "What needeth it thereof to sermon more?",
  "For, right as they had cast his death before,",
  "Right so they have him slain, and that anon.",
  "And when that this was done, thus spake the one;",
  "\"Now let us sit and drink, and make us merry,",
  "And afterward we will his body bury.\"",
  "And with that word it happen'd him par cas",
  "To take the bottle where the poison was,",
  "And drank, and gave his fellow drink also,",
  "For which anon they sterved both the two.",
  "But certes I suppose that Avicen",
  "Wrote never in no canon, nor no fen,",
  "More wondrous signes of empoisoning,",
  "Than had these wretches two ere their ending.",
  "Thus ended be these homicides two,",
  "And eke the false empoisoner also.",
  "",
  "O cursed sin, full of all cursedness!",
  "O trait'rous homicide! O wickedness!",
  "O glutt'ny, luxury, and hazardry!",
  "Thou blasphemer of Christ with villany,",
  "And oathes great, of usage and of pride!",
  "Alas! mankinde, how may it betide,",
  "That to thy Creator, which that thee wrought,",
  "And with his precious hearte-blood thee bought,",
  "Thou art so false and so unkind, alas!",
  "Now, good men, God forgive you your trespass,",
  "And ware you from the sin of avarice.",
  "Mine holy pardon may you all warice,",
  "So that ye offer nobles or sterlings,",
  "Or elles silver brooches, spoons, or rings.",
  "Bowe your head under this holy bull.",
  "Come up, ye wives, and offer of your will;",
  "Your names I enter in my roll anon;",
  "Into the bliss of heaven shall ye gon;",
  "I you assoil by mine high powere,",
  "You that will offer, as clean and eke as clear",
  "As ye were born. Lo, Sires, thus I preach;",
  "And Jesus Christ, that is our soules' leech,",
  "So grante you his pardon to receive;",
  "For that is best, I will not deceive.",
  "",
  "But, Sirs, one word forgot I in my tale;",
  "I have relics and pardon in my mail,",
  "As fair as any man in Engleland,",
  "Which were me given by the Pope's hand.",
  "If any of you will of devotion",
  "Offer, and have mine absolution,",
  "Come forth anon, and kneele here adown",
  "And meekely receive my pardoun.",
  "Or elles take pardon, as ye wend,",
  "All new and fresh at every towne's end,",
  "So that ye offer, always new and new,",
  "Nobles or pence which that be good and true.",
  "'Tis an honour to evereach that is here,",
  "That ye have a suffisant pardonere",
  "T'assoile you in country as ye ride,",
  "For aventures which that may betide.",
  "Paraventure there may fall one or two",
  "Down of his horse, and break his neck in two.",
  "Look, what a surety is it to you all,",
  "That I am in your fellowship y-fall,",
  "That may assoil you bothe more and lass,",
  "When that the soul shall from the body pass.",
  "I rede that our Hoste shall begin,",
  "For he is most enveloped in sin.",
  "Come forth, Sir Host, and offer first anon,",
  "And thou shalt kiss; the relics every one,",
  "Yea, for a groat; unbuckle anon thy purse.",
  "",
  "\"Nay, nay,\" quoth he, \"then have I Christe's curse!",
  "Let be,\" quoth he, \"it shall not be, so the'ch.",
  "Thou wouldest make me kiss thine olde breech,",
  "And swear it were a relic of a saint,",
  "Though it were with thy fundament depaint'.",
  "But, by the cross which that Saint Helen fand,",
  "I would I had thy coilons in mine hand,",
  "Instead of relics, or of sanctuary.",
  "Let cut them off, I will thee help them carry;",
  "They shall be shrined in a hogge's turd.\"",
  "The Pardoner answered not one word;",
  "So wroth he was, no worde would he say.",
  "",
  "\"Now,\" quoth our Host, \"I will no longer play",
  "With thee, nor with none other angry man.\"",
  "But right anon the worthy Knight began",
  "(When that he saw that all the people lough),",
  "\"No more of this, for it is right enough.",
  "Sir Pardoner, be merry and glad of cheer;",
  "And ye, Sir Host, that be to me so dear,",
  "I pray you that ye kiss the Pardoner;",
  "And, Pardoner, I pray thee draw thee ner,",
  "And as we didde, let us laugh and play.\"",
  "Anon they kiss'd, and rode forth their way.",
  ""
]