module.exports = [
  "A pathetic tragedy I will relate,",
  "Concerning poor Fred. Marsden's fate,",
  "Who suffocated himself by the fumes of gas,",
  "On the 18th of May, and in the year of 1888, alas!",
  "",
  "Fred. Marsden was a playwright, the theatrical world knows,",
  "And was highly esteemed by the people, and had very few foes;",
  "And in New York, in his bedroom, he took his life away,",
  "And was found by his servant William in his bedroom where he lay.",
  "",
  "The manner in which he took his life : first he locked the door,",
  "Then closed down the window, and a sheet to shreds he tore",
  "And then stopped the keyholes and chinks through which air might come,",
  "Then turned on the single gas-burner, and soon the deed was done.",
  "",
  "About seven o'clock in the evening he bade his wife good-night,",
  "And she left him, smoking, in his room, thinking all was right,",
  "But when morning came his daughter said she smelled gas,",
  "Then William, his servant, called loudly on him, but no answer, alas!",
  "",
  "Then suspicion flashed across William's brain, and he broke open the door,",
  "Then soon the family were in a state of uproar,",
  "For the room was full of gas, and Mr Marsden quite dead,",
  "And a more kind-hearted father never ate of the world's bread.",
  "",
  "And by his kindness he spoiled his only child,",
  "His pretty daughter Blanche, which made him wild;",
  "For some time he thought her an angel, she was so very civil,",
  "But she dishonoured herself, and proved herself a devil.",
  "",
  "Her father idolised her, and on her spared no expense,",
  "And the kind-hearted father gave her too much indulgence,",
  "Because evening parties and receptions were got up for her sake,",
  "Besides, he bought her a steam yacht to sail on Schroon Lake.",
  "",
  "His means he lavished upon his home and his wife,",
  "And he loved his wife and daughter as dear as his life;",
  "But Miss Blanche turned to folly, and wrecked their home through strife,",
  "And through Miss Marsden's folly her father took his life.",
  "",
  "She wanted to ride, and her father bought her a horse,",
  "And by giving her such indulgences, in morals she grew worse;",
  "And by her immoral actions she broke her father's heart;",
  "And, in my opinion, she has acted a very ungrateful part.",
  "",
  "At last she fled from her father's house, which made him mourn,",
  "Then the crazy father went after her and begged her to return,",
  "But she tore her father's beard, and about the face beat him,",
  "Then fled to her companions in evil, and thought it no sin.",
  "",
  "Then her father sent her one hundred dollars, and found her again,",
  "And he requested her to come home, but it was all in vain;",
  "For his cruel daughter swore at him without any dread,",
  "And, alas! next morning, he was found dead in his bed.",
  "",
  "And soon theatrical circles were shocked to learn,",
  "Of the sudden death of genial Fred Marsden,",
  "Whose house had been famous for its hospitality,",
  "To artists, litterateurs, and critics of high and low degree.",
  "",
  "And now dear Mrs Marsden is left alone to mourn",
  "The loss of her loving husband, whom to her will ne'er return;",
  "But I hope God will be kind to her in her bereavement,",
  "And open her daughter's eyes, and make her repent",
  "",
  "For being the cause of her father's death, the generous Fred,",
  "Who oft poor artists and mendicants has fed;",
  "But, alas! his bounties they will never receive more,",
  "Therefore poor artists and mendicants will his loss deplore.",
  "",
  "Therefore, all ye kind parents of high and low degree,",
  "I pray ye all, be advised by me,",
  "And never pamper your children in any way,",
  "Nor idolise them, for they are apt to go astray,",
  "",
  "And treat ye, like pretty Blanche Marsden,",
  "Who by her folly has been the death of one of the finest men;",
  "So all kind parents, be warned by me,",
  "And remember always this sad Tragedy!",
  ""
]