module.exports = [
  "THE PROLOGUE.",
  "",
  "When that the Knight had thus his tale told",
  "In all the rout was neither young nor old,",
  "That he not said it was a noble story,",
  "And worthy to be drawen to memory;",
  "And namely the gentles every one.",
  "Our Host then laugh'd and swore, \"So may I gon,",
  "This goes aright; unbuckled is the mail;",
  "Let see now who shall tell another tale:",
  "For truely this game is well begun.",
  "Now telleth ye, Sir Monk, if that ye conne,",
  "Somewhat, to quiten with the Knighte's tale.\"",
  "The Miller that fordrunken was all pale,",
  "So that unnethes upon his horse he sat,",
  "He would avalen neither hood nor hat,",
  "Nor abide no man for his courtesy,",
  "But in Pilate's voice he gan to cry,",
  "And swore by armes, and by blood, and bones,",
  "\"I can a noble tale for the nones",
  "With which I will now quite the Knighte's tale.\"",
  "Our Host saw well how drunk he was of ale,",
  "And said; \"Robin, abide, my leve brother,",
  "Some better man shall tell us first another:",
  "Abide, and let us worke thriftily.\"",
  "By Godde's soul,\" quoth he, \"that will not I,",
  "For I will speak, or elles go my way!\"",
  "Our Host answer'd; \"Tell on a devil way;",
  "Thou art a fool; thy wit is overcome.\"",
  "\"Now hearken,\" quoth the Miller, \"all and some:",
  "But first I make a protestatioun.",
  "That I am drunk, I know it by my soun':",
  "And therefore if that I misspeak or say,",
  "Wite it the ale of Southwark, I you pray:",
  "For I will tell a legend and a life",
  "Both of a carpenter and of his wife,",
  "How that a clerk hath set the wrighte's cap.\"",
  "The Reeve answer'd and saide, \"Stint thy clap,",
  "Let be thy lewed drunken harlotry.",
  "It is a sin, and eke a great folly",
  "To apeiren any man, or him defame,",
  "And eke to bringe wives in evil name.",
  "Thou may'st enough of other thinges sayn.\"",
  "This drunken Miller spake full soon again,",
  "And saide, \"Leve brother Osewold,",
  "Who hath no wife, he is no cuckold.",
  "But I say not therefore that thou art one;",
  "There be full goode wives many one.",
  "Why art thou angry with my tale now?",
  "I have a wife, pardie, as well as thou,",
  "Yet n'old I, for the oxen in my plough,",
  "Taken upon me more than enough,",
  "To deemen of myself that I am one;",
  "I will believe well that I am none.",
  "An husband should not be inquisitive",
  "Of Godde's privity, nor of his wife.",
  "So he may finde Godde's foison there,",
  "Of the remnant needeth not to enquere.\"",
  "",
  "What should I more say, but that this Millere",
  "He would his wordes for no man forbear,",
  "But told his churlish tale in his mannere;",
  "Me thinketh, that I shall rehearse it here.",
  "And therefore every gentle wight I pray,",
  "For Godde's love to deem not that I say",
  "Of evil intent, but that I must rehearse",
  "Their tales all, be they better or worse,",
  "Or elles falsen some of my mattere.",
  "And therefore whoso list it not to hear,",
  "Turn o'er the leaf, and choose another tale;",
  "For he shall find enough, both great and smale,",
  "Of storial thing that toucheth gentiless,",
  "And eke morality and holiness.",
  "Blame not me, if that ye choose amiss.",
  "The Miller is a churl, ye know well this,",
  "So was the Reeve, with many other mo',",
  "And harlotry they tolde bothe two.",
  "Avise you now, and put me out of blame;",
  "And eke men should not make earnest of game.",
  "",
  "THE TALE.",
  "",
  "Whilom there was dwelling in Oxenford",
  "A riche gnof, that guestes held to board,",
  "And of his craft he was a carpenter.",
  "With him there was dwelling a poor scholer,",
  "Had learned art, but all his fantasy",
  "Was turned for to learn astrology.",
  "He coude a certain of conclusions",
  "To deeme by interrogations,",
  "If that men asked him in certain hours,",
  "When that men should have drought or elles show'rs:",
  "Or if men asked him what shoulde fall",
  "Of everything, I may not reckon all.",
  "",
  "This clerk was called Hendy Nicholas;",
  "Of derne love he knew and of solace;",
  "And therewith he was sly and full privy,",
  "And like a maiden meek for to see.",
  "A chamber had he in that hostelry",
  "Alone, withouten any company,",
  "Full fetisly y-dight with herbes swoot,",
  "And he himself was sweet as is the root",
  "Of liquorice, or any setewall.",
  "His Almagest, and bookes great and small,",
  "His astrolabe,  belonging to his art,",
  "His augrim stones, layed fair apart",
  "On shelves couched at his bedde's head,",
  "His press y-cover'd with a falding red.",
  "And all above there lay a gay psalt'ry",
  "On which he made at nightes melody,",
  "So sweetely, that all the chamber rang:",
  "And Angelus ad virginem he sang.",
  "And after that he sung the kinge's note;",
  "Full often blessed was his merry throat.",
  "And thus this sweete clerk his time spent",
  "After his friendes finding and his rent.",
  "",
  "This carpenter had wedded new a wife,",
  "Which that he loved more than his life:",
  "Of eighteen year, I guess, she was of age.",
  "Jealous he was, and held her narr'w in cage,",
  "For she was wild and young, and he was old,",
  "And deemed himself belike a cuckold.",
  "He knew not Cato, for his wit was rude,",
  "That bade a man wed his similitude.",
  "Men shoulde wedden after their estate,",
  "For youth and eld are often at debate.",
  "But since that he was fallen in the snare,",
  "He must endure (as other folk) his care.",
  "Fair was this younge wife, and therewithal",
  "As any weasel her body gent and small.",
  "A seint she weared, barred all of silk,",
  "A barm-cloth eke as white as morning milk",
  "Upon her lendes, full of many a gore.",
  "White was her smock, and broider'd all before,",
  "And eke behind, on her collar about",
  "Of coal-black silk, within and eke without.",
  "The tapes of her white volupere",
  "Were of the same suit of her collere;",
  "Her fillet broad of silk, and set full high:",
  "And sickerly she had a likerous eye.",
  "Full small y-pulled were her browes two,",
  "And they were bent, and black as any sloe.",
  "She was well more blissful on to see",
  "Than is the newe perjenete tree;",
  "And softer than the wool is of a wether.",
  "And by her girdle hung a purse of leather,",
  "Tassel'd with silk, and pearled with latoun.",
  "In all this world to seeken up and down",
  "There is no man so wise, that coude thenche",
  "So gay a popelot, or such a wench.",
  "Full brighter was the shining of her hue,",
  "Than in the Tower the noble forged new.",
  "But of her song, it was as loud and yern,",
  "As any swallow chittering on a bern.",
  "Thereto she coulde skip, and make a game",
  "As any kid or calf following his dame.",
  "Her mouth was sweet as braket, or as methe",
  "Or hoard of apples, laid in hay or heath.",
  "Wincing she was as is a jolly colt,",
  "Long as a mast, and upright as a bolt.",
  "A brooch she bare upon her low collere,",
  "As broad as is the boss of a bucklere.",
  "Her shoon were laced on her legges high;",
  "She was a primerole, a piggesnie ,",
  "For any lord t' have ligging in his bed,",
  "Or yet for any good yeoman to wed.",
  "",
  "Now, sir, and eft sir, so befell the case,",
  "That on a day this Hendy Nicholas",
  "Fell with this younge wife to rage and play,",
  "While that her husband was at Oseney,",
  "As clerkes be full subtle and full quaint.",
  "And privily he caught her by the queint,",
  "And said; \"Y-wis, but if I have my will,",
  "For derne love of thee, leman, I spill.\"",
  "And helde her fast by the haunche bones,",
  "And saide \"Leman, love me well at once,",
  "Or I will dien, all so God me save.\"",
  "And she sprang as a colt doth in the trave:",
  "And with her head she writhed fast away,",
  "And said; \"I will not kiss thee, by my fay.",
  "Why let be,\" quoth she, \"let be, Nicholas,",
  "Or I will cry out harow and alas!",
  "Do away your handes, for your courtesy.\"",
  "This Nicholas gan mercy for to cry,",
  "And spake so fair, and proffer'd him so fast,",
  "That she her love him granted at the last,",
  "And swore her oath by Saint Thomas of Kent,",
  "That she would be at his commandement,",
  "When that she may her leisure well espy.",
  "\"My husband is so full of jealousy,",
  "That but ye waite well, and be privy,",
  "I wot right well I am but dead,\" quoth she.",
  "\"Ye muste be full derne as in this case.\"",
  "\"Nay, thereof care thee nought,\" quoth Nicholas:",
  "\"A clerk had litherly beset his while,",
  "But if he could a carpenter beguile.\"",
  "And thus they were accorded and y-sworn",
  "To wait a time, as I have said beforn.",
  "When Nicholas had done thus every deal,",
  "And thwacked her about the lendes well,",
  "He kiss'd her sweet, and taketh his psalt'ry",
  "And playeth fast, and maketh melody.",
  "Then fell it thus, that to the parish church,",
  "Of Christe's owen workes for to wirch,",
  "This good wife went upon a holy day;",
  "Her forehead shone as bright as any day,",
  "So was it washen, when she left her werk.",
  "",
  "Now was there of that church a parish clerk,",
  "The which that was y-cleped Absolon.",
  "Curl'd was his hair, and as the gold it shone,",
  "And strutted as a fanne large and broad;",
  "Full straight and even lay his jolly shode.",
  "His rode was red, his eyen grey as goose,",
  "With Paule's windows carven on his shoes",
  "In hosen red he went full fetisly.",
  "Y-clad he was full small and properly,",
  "All in a kirtle of a light waget;",
  "Full fair and thicke be the pointes set,",
  "And thereupon he had a gay surplice,",
  "As white as is the blossom on the rise.",
  "A merry child he was, so God me save;",
  "Well could he letten blood, and clip, and shave,",
  "And make a charter of land, and a quittance.",
  "In twenty manners could he trip and dance,",
  "After the school of Oxenforde tho,",
  "And with his legges caste to and fro;",
  "And playen songes on a small ribible;",
  "Thereto he sung sometimes a loud quinible",
  "And as well could he play on a gitern.",
  "In all the town was brewhouse nor tavern,",
  "That he not visited with his solas,",
  "There as that any garnard tapstere was.",
  "But sooth to say he was somedeal squaimous",
  "Of farting, and of speeche dangerous.",
  "This Absolon, that jolly was and gay,",
  "Went with a censer on the holy day,",
  "Censing the wives of the parish fast;",
  "And many a lovely look he on them cast,",
  "And namely on this carpenter's wife:",
  "To look on her him thought a merry life.",
  "She was so proper, and sweet, and likerous.",
  "I dare well say, if she had been a mouse,",
  "And he a cat, he would her hent anon.",
  "This parish clerk, this jolly Absolon,",
  "Hath in his hearte such a love-longing!",
  "That of no wife took he none offering;",
  "For courtesy he said he woulde none.",
  "The moon at night full clear and brighte shone,",
  "And Absolon his gitern hath y-taken,",
  "For paramours he thoughte for to waken,",
  "And forth he went, jolif and amorous,",
  "Till he came to the carpentere's house,",
  "A little after the cock had y-crow,",
  "And dressed him under a shot window ,",
  "That was upon the carpentere's wall.",
  "He singeth in his voice gentle and small;",
  "\"Now, dear lady, if thy will be,",
  "I pray that ye will rue on me;\"",
  "Full well accordant to his giterning.",
  "This carpenter awoke, and heard him sing,",
  "And spake unto his wife, and said anon,",
  "What Alison, hear'st thou not Absolon,",
  "That chanteth thus under our bower wall?\"",
  "And she answer'd her husband therewithal;",
  "\"Yes, God wot, John, I hear him every deal.\"",
  "This passeth forth; what will ye bet than well?",
  "",
  "From day to day this jolly Absolon",
  "So wooeth her, that him is woebegone.",
  "He waketh all the night, and all the day,",
  "To comb his lockes broad, and make him gay.",
  "He wooeth her by means and by brocage,",
  "And swore he woulde be her owen page.",
  "He singeth brokking as a nightingale.",
  "He sent her piment , mead, and spiced ale,",
  "And wafers piping hot out of the glede:",
  "And, for she was of town, he proffer'd meed.",
  "For some folk will be wonnen for richess,",
  "And some for strokes, and some with gentiless.",
  "Sometimes, to show his lightness and mast'ry,",
  "He playeth Herod  on a scaffold high.",
  "But what availeth him as in this case?",
  "So loveth she the Hendy Nicholas,",
  "That Absolon may blow the bucke's horn:",
  "He had for all his labour but a scorn.",
  "And thus she maketh Absolon her ape,",
  "And all his earnest turneth to a jape.",
  "Full sooth is this proverb, it is no lie;",
  "Men say right thus alway; the nighe sly",
  "Maketh oft time the far lief to be loth.",
  "For though that Absolon be wood or wroth",
  "Because that he far was from her sight,",
  "This nigh Nicholas stood still in his light.",
  "Now bear thee well, thou Hendy Nicholas,",
  "For Absolon may wail and sing \"Alas!\"",
  "",
  "And so befell, that on a Saturday",
  "This carpenter was gone to Oseney,",
  "And Hendy Nicholas and Alison",
  "Accorded were to this conclusion,",
  "That Nicholas shall shape him a wile",
  "The silly jealous husband to beguile;",
  "And if so were the game went aright,",
  "She shoulde sleepen in his arms all night;",
  "For this was her desire and his also.",
  "And right anon, withoute wordes mo',",
  "This Nicholas no longer would he tarry,",
  "But doth full soft unto his chamber carry",
  "Both meat and drinke for a day or tway.",
  "And to her husband bade her for to say,",
  "If that he asked after Nicholas,",
  "She shoulde say, \"She wist not where he was;",
  "Of all the day she saw him not with eye;",
  "She trowed he was in some malady,",
  "For no cry that her maiden could him call",
  "He would answer, for nought that might befall.\"",
  "Thus passed forth all thilke Saturday,",
  "That Nicholas still in his chamber lay,",
  "And ate, and slept, and didde what him list",
  "Till Sunday, that the sunne went to rest.",
  "This silly carpenter had great marvaill",
  "Of Nicholas, or what thing might him ail,",
  "And said; \"I am adrad, by Saint Thomas!",
  "It standeth not aright with Nicholas:",
  "God shielde that he died suddenly.",
  "This world is now full fickle sickerly.",
  "I saw to-day a corpse y-borne to chirch,",
  "That now on Monday last I saw him wirch.",
  "\"Go up,\" quod he unto his knave, \"anon;",
  "Clepe at his door, or knocke with a stone:",
  "Look how it is, and tell me boldely.\"",
  "This knave went him up full sturdily,",
  "And, at the chamber door while that he stood,",
  "He cried and knocked as that he were wood:",
  "\"What how? what do ye, Master Nicholay?",
  "How may ye sleepen all the longe day?\"",
  "But all for nought, he hearde not a word.",
  "An hole he found full low upon the board,",
  "Where as the cat was wont in for to creep,",
  "And at that hole he looked in full deep,",
  "And at the last he had of him a sight.",
  "This Nicholas sat ever gaping upright,",
  "As he had kyked on the newe moon.",
  "Adown he went, and told his master soon,",
  "In what array he saw this ilke man.",
  "",
  "This carpenter to blissen him began,",
  "And said: \"Now help us, Sainte Frideswide.",
  "A man wot little what shall him betide.",
  "This man is fall'n with his astronomy",
  "Into some woodness or some agony.",
  "I thought aye well how that it shoulde be.",
  "Men should know nought of Godde's privity.",
  "Yea, blessed be alway a lewed man,",
  "That nought but only his believe can.",
  "So far'd another clerk with astronomy:",
  "He walked in the fieldes for to pry",
  "Upon the starres, what there should befall,",
  "Till he was in a marle pit y-fall.",
  "He saw not that. But yet, by Saint Thomas!",
  "Me rueth sore of Hendy Nicholas:",
  "He shall be rated of his studying,",
  "If that I may, by Jesus, heaven's king!",
  "Get me a staff, that I may underspore",
  "While that thou, Robin, heavest off the door:",
  "He shall out of his studying, as I guess.\"",
  "And to the chamber door he gan him dress",
  "His knave was a strong carl for the nonce,",
  "And by the hasp he heav'd it off at once;",
  "Into the floor the door fell down anon.",
  "This Nicholas sat aye as still as stone,",
  "And ever he gap'd upward into the air.",
  "The carpenter ween'd he were in despair,",
  "And hent him by the shoulders mightily,",
  "And shook him hard, and cried spitously;",
  "\"What, Nicholas? what how, man? look adown:",
  "Awake, and think on Christe's passioun.",
  "I crouche thee from elves, and from wights.",
  "Therewith the night-spell said he anon rights,",
  "On the four halves of the house about,",
  "And on the threshold of the door without.",
  "\"Lord Jesus Christ, and Sainte Benedight,",
  "Blesse this house from every wicked wight,",
  "From the night mare, the white Pater-noster;",
  "Where wonnest thou now, Sainte Peter's sister?\"",
  "And at the last this Hendy Nicholas",
  "Gan for to sigh full sore, and said; \"Alas!",
  "Shall all time world be lost eftsoones now?\"",
  "This carpenter answer'd; \"What sayest thou?",
  "What? think on God, as we do, men that swink.\"",
  "This Nicholas answer'd; \"Fetch me a drink;",
  "And after will I speak in privity",
  "Of certain thing that toucheth thee and me:",
  "I will tell it no other man certain.\"",
  "",
  "This carpenter went down, and came again,",
  "And brought of mighty ale a large quart;",
  "And when that each of them had drunk his part,",
  "This Nicholas his chamber door fast shet,",
  "And down the carpenter by him he set,",
  "And saide; \"John, mine host full lief and dear,",
  "Thou shalt upon thy truthe swear me here,",
  "That to no wight thou shalt my counsel wray:",
  "For it is Christes counsel that I say,",
  "And if thou tell it man, thou art forlore:",
  "For this vengeance thou shalt have therefor,",
  "That if thou wraye me, thou shalt be wood.\"",
  "\"Nay, Christ forbid it for his holy blood!\"",
  "Quoth then this silly man; \"I am no blab,",
  "Nor, though I say it, am I lief to gab.",
  "Say what thou wilt, I shall it never tell",
  "To child or wife, by him that harried Hell.\"",
  "",
  "\"Now, John,\" quoth Nicholas, \"I will not lie,",
  "I have y-found in my astrology,",
  "As I have looked in the moone bright,",
  "That now on Monday next, at quarter night,",
  "Shall fall a rain, and that so wild and wood,",
  "That never half so great was Noe's flood.",
  "This world,\" he said, \"in less than half an hour",
  "Shall all be dreint, so hideous is the shower:",
  "Thus shall mankinde drench, and lose their life.\"",
  "This carpenter answer'd; \"Alas, my wife!",
  "And shall she drench? alas, mine Alisoun!\"",
  "For sorrow of this he fell almost adown,",
  "And said; \"Is there no remedy in this case?\"",
  "\"Why, yes, for God,\" quoth Hendy Nicholas;",
  "\"If thou wilt worken after lore and rede;",
  "Thou may'st not worken after thine own head.",
  "For thus saith Solomon, that was full true:",
  "Work all by counsel, and thou shalt not rue.",
  "And if thou worke wilt by good counseil,",
  "I undertake, withoute mast or sail,",
  "Yet shall I save her, and thee, and me.",
  "Hast thou not heard how saved was Noe,",
  "When that our Lord had warned him beforn,",
  "That all the world with water should be lorn?\"",
  "\"Yes,\" quoth this carpenter,\" full yore ago.\"",
  "\"Hast thou not heard,\" quoth Nicholas, \"also",
  "The sorrow of Noe, with his fellowship,",
  "That he had ere he got his wife to ship?",
  "Him had been lever, I dare well undertake,",
  "At thilke time, than all his wethers black,",
  "That she had had a ship herself alone.",
  "And therefore know'st thou what is best to be done?",
  "This asketh haste, and of an hasty thing",
  "Men may not preach or make tarrying.",
  "Anon go get us fast into this inn",
  "A kneading trough, or else a kemelin,",
  "For each of us; but look that they be large,",
  "In whiche we may swim as in a barge:",
  "And have therein vitaille suffisant",
  "But for one day; fie on the remenant;",
  "The water shall aslake and go away",
  "Aboute prime upon the nexte day.",
  "But Robin may not know of this, thy knave,",
  "Nor eke thy maiden Gill I may not save:",
  "Ask me not why: for though thou aske me",
  "I will not telle Godde's privity.",
  "Sufficeth thee, but if thy wit be mad,",
  "To have as great a grace as Noe had;",
  "Thy wife shall I well saven out of doubt.",
  "Go now thy way, and speed thee hereabout.",
  "But when thou hast for her, and thee, and me,",
  "Y-gotten us these kneading tubbes three,",
  "Then shalt thou hang them in the roof full high,",
  "So that no man our purveyance espy:",
  "And when thou hast done thus as I have said,",
  "And hast our vitaille fair in them y-laid,",
  "And eke an axe to smite the cord in two",
  "When that the water comes, that we may go,",
  "And break an hole on high upon the gable",
  "Into the garden-ward, over the stable,",
  "That we may freely passe forth our way,",
  "When that the greate shower is gone away.",
  "Then shalt thou swim as merry, I undertake,",
  "As doth the white duck after her drake:",
  "Then will I clepe, 'How, Alison? How, John?",
  "Be merry: for the flood will pass anon.'",
  "And thou wilt say, 'Hail, Master Nicholay,",
  "Good-morrow, I see thee well, for it is day.'",
  "And then shall we be lordes all our life",
  "Of all the world, as Noe and his wife.",
  "But of one thing I warne thee full right,",
  "Be well advised, on that ilke night,",
  "When we be enter'd into shippe's board,",
  "That none of us not speak a single word,",
  "Nor clepe nor cry, but be in his prayere,",
  "For that is Godde's owen heste dear.",
  "Thy wife and thou must hangen far atween,",
  "For that betwixte you shall be no sin,",
  "No more in looking than there shall in deed.",
  "This ordinance is said: go, God thee speed",
  "To-morrow night, when men be all asleep,",
  "Into our kneading tubbes will we creep,",
  "And sitte there, abiding Godde's grace.",
  "Go now thy way, I have no longer space",
  "To make of this no longer sermoning:",
  "Men say thus: Send the wise, and say nothing:",
  "Thou art so wise, it needeth thee nought teach.",
  "Go, save our lives, and that I thee beseech.\"",
  "",
  "This silly carpenter went forth his way,",
  "Full oft he said, \"Alas! and Well-a-day!,'",
  "And to his wife he told his privity,",
  "And she was ware, and better knew than he",
  "What all this quainte cast was for to say.",
  "But natheless she fear'd as she would dey,",
  "And said: \"Alas! go forth thy way anon.",
  "Help us to scape, or we be dead each one.",
  "I am thy true and very wedded wife;",
  "Go, deare spouse, and help to save our life.\"",
  "Lo, what a great thing is affection!",
  "Men may die of imagination,",
  "So deeply may impression be take.",
  "This silly carpenter begins to quake:",
  "He thinketh verily that he may see",
  "This newe flood come weltering as the sea",
  "To drenchen Alison, his honey dear.",
  "He weepeth, waileth, maketh sorry cheer;",
  "He sigheth, with full many a sorry sough.",
  "He go'th, and getteth him a kneading trough,",
  "And after that a tub, and a kemelin,",
  "And privily he sent them to his inn:",
  "And hung them in the roof full privily.",
  "With his own hand then made he ladders three,",
  "To climbe by the ranges and the stalks",
  "Unto the tubbes hanging in the balks;",
  "And victualed them, kemelin, trough, and tub,",
  "With bread and cheese, and good ale in a jub,",
  "Sufficing right enough as for a day.",
  "But ere that he had made all this array,",
  "He sent his knave, and eke his wench also,",
  "Upon his need to London for to go.",
  "And on the Monday, when it drew to night,",
  "He shut his door withoute candle light,",
  "And dressed every thing as it should be.",
  "And shortly up they climbed all the three.",
  "They satte stille well a furlong way.",
  "\"Now, Pater noster, clum,\" said Nicholay,",
  "And \"clum,\" quoth John; and \"clum,\" said Alison:",
  "This carpenter said his devotion,",
  "And still he sat and bidded his prayere,",
  "Awaking on the rain, if he it hear.",
  "The deade sleep, for weary business,",
  "Fell on this carpenter, right as I guess,",
  "About the curfew-time, or little more,",
  "For travail of his ghost he groaned sore,",
  "And eft he routed, for his head mislay.",
  "Adown the ladder stalked Nicholay;",
  "And Alison full soft adown she sped.",
  "Withoute wordes more they went to bed,",
  "There as the carpenter was wont to lie:",
  "There was the revel, and the melody.",
  "And thus lay Alison and Nicholas,",
  "In business of mirth and in solace,",
  "Until the bell of laudes gan to ring,",
  "And friars in the chancel went to sing.",
  "",
  "This parish clerk, this amorous Absolon,",
  "That is for love alway so woebegone,",
  "Upon the Monday was at Oseney",
  "With company, him to disport and play;",
  "And asked upon cas a cloisterer",
  "Full privily after John the carpenter;",
  "And he drew him apart out of the church,",
  "And said, \"I n'ot; I saw him not here wirch",
  "Since Saturday; I trow that he be went",
  "For timber, where our abbot hath him sent.",
  "And dwellen at the Grange a day or two:",
  "For he is wont for timber for to go,",
  "Or else he is at his own house certain.",
  "Where that he be, I cannot soothly sayn.\"",
  "This Absolon full jolly was and light,",
  "And thought, \"Now is the time to wake all night,",
  "For sickerly I saw him not stirring",
  "About his door, since day began to spring.",
  "So may I thrive, but I shall at cock crow",
  "Full privily go knock at his window,",
  "That stands full low upon his bower wall:",
  "To Alison then will I tellen all",
  "My love-longing; for I shall not miss",
  "That at the leaste way I shall her kiss.",
  "Some manner comfort shall I have, parfay,",
  "My mouth hath itched all this livelong day:",
  "That is a sign of kissing at the least.",
  "All night I mette eke I was at a feast.",
  "Therefore I will go sleep an hour or tway,",
  "And all the night then will I wake and play.\"",
  "When that the first cock crowed had, anon",
  "Up rose this jolly lover Absolon,",
  "And him arrayed gay, at point devise.",
  "But first he chewed grains and liquorice,",
  "To smelle sweet, ere he had combed his hair.",
  "Under his tongue a true love   he bare,",
  "For thereby thought he to be gracious.",
  "",
  "Then came he to the carpentere's house,",
  "And still he stood under the shot window;",
  "Unto his breast it raught, it was so low;",
  "And soft he coughed with a semisoun'.",
  "\"What do ye, honeycomb, sweet Alisoun?",
  "My faire bird, my sweet cinamome,",
  "Awaken, leman mine, and speak to me.",
  "Full little thinke ye upon my woe,",
  "That for your love I sweat there as I go.",
  "No wonder is that I do swelt and sweat.",
  "I mourn as doth a lamb after the teat",
  "Y-wis, leman, I have such love-longing,",
  "That like a turtle true is my mourning.",
  "I may not eat, no more than a maid.\"",
  "\"Go from the window, thou jack fool,\" she said:",
  "\"As help me God, it will not be, 'come ba me.'",
  "I love another, else I were to blame\",",
  "Well better than thee, by Jesus, Absolon.",
  "Go forth thy way, or I will cast a stone;",
  "And let me sleep; a twenty devil way.",
  "\"Alas!\" quoth Absolon, \"and well away!",
  "That true love ever was so ill beset:",
  "Then kiss me, since that it may be no bet,",
  "For Jesus' love, and for the love of me.\"",
  "\"Wilt thou then go thy way therewith?\" , quoth she.",
  "\"Yea, certes, leman,\" quoth this Absolon.",
  "\"Then make thee ready,\" quoth she, \"I come anon.\"",
  "[And unto Nicholas she said full still:",
  "\"Now peace, and thou shalt laugh anon thy fill.\"]",
  "This Absolon down set him on his knees,",
  "And said; \"I am a lord at all degrees:",
  "For after this I hope there cometh more;",
  "Leman, thy grace, and, sweete bird, thine ore.\"",
  "The window she undid, and that in haste.",
  "\"Have done,\" quoth she, \"come off, and speed thee fast,",
  "Lest that our neighebours should thee espy.\"",
  "Then Absolon gan wipe his mouth full dry.",
  "Dark was the night as pitch or as the coal,",
  "And at the window she put out her hole,",
  "And Absolon him fell ne bet ne werse,",
  "But with his mouth he kiss'd her naked erse",
  "Full savourly. When he was ware of this,",
  "Aback he start, and thought it was amiss;",
  "For well he wist a woman hath no beard.",
  "He felt a thing all rough, and long y-hair'd,",
  "And saide; \"Fy, alas! what have I do?\"",
  "\"Te he!\" quoth she, and clapt the window to;",
  "And Absolon went forth at sorry pace.",
  "\"A beard, a beard,\" said Hendy Nicholas;",
  "\"By God's corpus, this game went fair and well.\"",
  "This silly Absolon heard every deal,",
  "And on his lip he gan for anger bite;",
  "And to himself he said, \"I shall thee quite.",
  "Who rubbeth now, who frotteth now his lips",
  "With dust, with sand, with straw, with cloth, with chips,",
  "But Absolon? that saith full oft, \"Alas!",
  "My soul betake I unto Sathanas,",
  "But me were lever than all this town,\" quoth he",
  "I this despite awroken for to be.",
  "Alas! alas! that I have been y-blent.\"",
  "His hote love is cold, and all y-quent.",
  "For from that time that he had kiss'd her erse,",
  "Of paramours he sette not a kers,",
  "For he was healed of his malady;",
  "Full often paramours he gan defy,",
  "And weep as doth a child that hath been beat.",
  "A softe pace he went over the street",
  "Unto a smith, men callen Dan Gerveis,",
  "That in his forge smithed plough-harness;",
  "He sharped share and culter busily.",
  "This Absolon knocked all easily,",
  "And said; \"Undo, Gerveis, and that anon.\"",
  "\"What, who art thou?\" \"It is I, Absolon.\"",
  "\"What? Absolon, what? Christe's sweete tree,",
  "Why rise so rath? hey! Benedicite,",
  "What aileth you? some gay girl, God it wote,",
  "Hath brought you thus upon the viretote:",
  "By Saint Neot, ye wot well what I mean.\"",
  "This Absolon he raughte not a bean",
  "Of all his play; no word again he gaf,",
  "For he had more tow on his distaff",
  "Than Gerveis knew, and saide; \"Friend so dear,",
  "That hote culter in the chimney here",
  "Lend it to me, I have therewith to don:",
  "I will it bring again to thee full soon.\"",
  "Gerveis answered; \"Certes, were it gold,",
  "Or in a poke nobles all untold,",
  "Thou shouldst it have, as I am a true smith.",
  "Hey! Christe's foot, what will ye do therewith?\"",
  "\"Thereof,\" quoth Absolon, \"be as be may;",
  "I shall well tell it thee another day:\"",
  "And caught the culter by the colde stele.",
  "Full soft out at the door he gan to steal,",
  "And went unto the carpentere's wall",
  "He coughed first, and knocked therewithal",
  "Upon the window, light as he did ere.",
  "This Alison answered; \"Who is there",
  "That knocketh so? I warrant him a thief.\"",
  "\"Nay, nay,\" quoth he, \"God wot, my sweete lefe,",
  "I am thine Absolon, my own darling.",
  "Of gold,\" quoth he, \"I have thee brought a ring,",
  "My mother gave it me, so God me save!",
  "Full fine it is, and thereto well y-grave:",
  "This will I give to thee, if thou me kiss.\"",
  "Now Nicholas was risen up to piss,",
  "And thought he would amenden all the jape;",
  "He shoulde kiss his erse ere that he scape:",
  "And up the window did he hastily,",
  "And out his erse he put full privily",
  "Over the buttock, to the haunche bone.",
  "And therewith spake this clerk, this Absolon,",
  "\"Speak, sweete bird, I know not where thou art.\"",
  "This Nicholas anon let fly a fart,",
  "As great as it had been a thunder dent;",
  "That with the stroke he was well nigh y-blent;",
  "But he was ready with his iron hot,",
  "And Nicholas amid the erse he smote.",
  "Off went the skin an handbreadth all about.",
  "The hote culter burned so his tout,",
  "That for the smart he weened he would die;",
  "As he were wood, for woe he gan to cry,",
  "\"Help! water, water, help for Godde's heart!\"",
  "",
  "This carpenter out of his slumber start,",
  "And heard one cry \"Water,\" as he were wood,",
  "And thought, \"Alas! now cometh Noe's flood.\"",
  "He sat him up withoute wordes mo'",
  "And with his axe he smote the cord in two;",
  "And down went all; he found neither to sell",
  "Nor bread nor ale, till he came to the sell,",
  "Upon the floor, and there in swoon he lay.",
  "Up started Alison and Nicholay,",
  "And cried out an \"harow!\"   in the street.",
  "The neighbours alle, bothe small and great",
  "In ranne, for to gauren on this man,",
  "That yet in swoone lay, both pale and wan:",
  "For with the fall he broken had his arm.",
  "But stand he must unto his owen harm,",
  "For when he spake, he was anon borne down",
  "With Hendy Nicholas and Alisoun.",
  "They told to every man that he was wood;",
  "He was aghaste so of Noe's flood,",
  "Through phantasy, that of his vanity",
  "He had y-bought him kneading-tubbes three,",
  "And had them hanged in the roof above;",
  "And that he prayed them for Godde's love",
  "To sitten in the roof for company.",
  "The folk gan laughen at his phantasy.",
  "Into the roof they kyken and they gape,",
  "And turned all his harm into a jape.",
  "For whatsoe'er this carpenter answer'd,",
  "It was for nought, no man his reason heard.",
  "With oathes great he was so sworn adown,",
  "That he was holden wood in all the town.",
  "For every clerk anon right held with other;",
  "They said, \"The man was wood, my leve brother;\"",
  "And every wight gan laughen at his strife.",
  "Thus swived was the carpentere's wife,",
  "For all his keeping and his jealousy;",
  "And Absolon hath kiss'd her nether eye;",
  "And Nicholas is scalded in the tout.",
  "This tale is done, and God save all the rout.",
  ""
]