module.exports = [
  "I.",
  "",
  "A Shepherd's Dog there was; and he",
  "Was faithful to his master's will,",
  "For well he lov'd his company,",
  "Along the plain or up the hill;",
  "All Seasons were, to him, the same",
  "Beneath the Sun's meridian flame;",
  "Or, when the wintry wind blew shrill and keen,",
  "Still the Old Shepherd's Dog, was with his Master seen.",
  "",
  "",
  "II.",
  "",
  "His form was shaggy clothed; yet he",
  "Was of a bold and faithful breed;",
  "And kept his master company",
  "In smiling days, and days of need;",
  "When the long Ev'ning slowly clos'd,",
  "When ev'ry living thing repos'd,",
  "When e'en the breeze slept on the woodlands round,",
  "The Shepherd's watchful Dog, was ever waking found.",
  "",
  "III.",
  "",
  "All night, upon the cold turf he",
  "Contented lay, with list'ning care;",
  "And though no stranger company,",
  "Or lonely traveller rested there;",
  "Old Trim was pleas'd to guard it still,",
  "For 'twas his aged master's will;--",
  "And so pass'd on the chearful night and day,",
  "'Till the poor Shepherd's Dog, was very old, and grey.",
  "",
  "",
  "IV.",
  "",
  "Among the villagers was he",
  "Belov'd by all the young and old,",
  "For he was chearful company,",
  "When the north-wind blew keen and cold;",
  "And when the cottage scarce was warm,",
  "While round it flew, the midnight storm,",
  "When loudly, fiercely roll'd the swelling tide--",
  "The Shepherd's faithful Dog, crept closely by his side.",
  "",
  "",
  "V.",
  "",
  "When Spring in gaudy dress would be,",
  "Sporting across the meadows green,",
  "He kept his master company,",
  "And all amid the flow'rs was seen;",
  "Now barking loud, now pacing fast,",
  "Now, backward he a look would cast,",
  "And now, subdu'd and weak, with wanton play,",
  "Amid the waving grass, the Shepherd's Dog would stay.",
  "",
  "",
  "VI.",
  "",
  "Now, up the rugged path would he",
  "The steep hill's summit slowly gain,",
  "And still be chearful company,",
  "Though shiv'ring in the pelting rain;",
  "And when the brook was frozen o'er,",
  "Or the deep snow conceal'd the moor,",
  "When the pale moon-beams scarcely shed a ray,",
  "The Shepherd's faithful Dog, would mark the dang'rous way.",
  "",
  "",
  "VII.",
  "",
  "On Sunday, at the old Yew Tree,",
  "Which canopies the church-yard stile,",
  "Forc'd from his master's company,",
  "The faithful TRIM would mope awhile;",
  "For then his master's only care",
  "Was the loud Psalm, or fervent Pray'r,",
  "And, 'till the throng the church-yard path retrod,",
  "The Shepherd's patient guard, lay silent on the sod.",
  "",
  "",
  "VIII.",
  "",
  "Near their small hovel stood a tree,",
  "Where TRIM was ev'ry morning found--",
  "Waiting his master's company,",
  "And looking wistfully around;",
  "And if, along the upland mead,",
  "He heard him tune the merry reed,",
  "O, then ! o'er hedge and ditch, thro' brake and briar,",
  "The Shepherd's dog would haste, with eyes that seem'd on fire.",
  "",
  "",
  "IX.",
  "",
  "And now he pac'd the valley, free,",
  "And now he bounded o'er the dew,",
  "For well his master's company",
  "Would recompence his toil he knew;",
  "And where a rippling rill was seen",
  "Flashing the woody brakes between,",
  "Fearless of danger, thro' the lucid tide,",
  "The Shepherd's eager dog, yelping with joy, would glide.",
  "",
  "",
  "X.",
  "",
  "Full many a year, the same was he",
  "His love still stronger every day,",
  "For, in his master's company,",
  "He had grown old, and very grey;",
  "And now his sight grew dim: and slow",
  "Up the rough mountain he would go,",
  "And his loud bark, which all the village knew,",
  "With ev'ry wasting hour, more faint, and peevish grew.",
  "",
  "",
  "XI.",
  "",
  "One morn, to the low mead went he,",
  "Rous'd from his threshold-bed to meet",
  "A gay and lordly company!",
  "The Sun was bright, the air was sweet;",
  "Old TRIM was watchful of his care,",
  "His master's flocks were feeding there,",
  "And, fearful of the hounds, he yelping stood",
  "Beneath a willow Tree, that wav'd across the flood.",
  "",
  "",
  "XII.",
  "",
  "Old TRIM was urg'd to wrath; for he",
  "Was guardian of the meadow bounds;",
  "And, heedless of the company,",
  "With angry snarl attack'd the hounds!",
  "Some felt his teeth, though they were old,",
  "For still his ire was fierce and bold,",
  "And ne'er did valiant chieftain feel more strong",
  "Than the Old Shepherd's dog, when daring foes among.",
  "",
  "",
  "XIII.",
  "",
  "The Sun was setting o'er the Sea",
  "The breezes murmuring sad, and slow,",
  "When a gay lordly company,",
  "Came to the Shepherd's hovel low;",
  "Their arm'd associates stood around",
  "The sheep-cote fence's narrow bound,",
  "While its poor master heard, with fix'd despair,",
  "That TRIM, his friend, deem'd MAD, was doom'd to perish there!",
  "",
  "",
  "XIV.",
  "",
  "The kind old Shepherd wept, for he",
  "Had no such guide, to mark his way,",
  "And kneeling pray'd the company,",
  "To let him live, his little day !",
  "\"For many a year my Dog has been",
  "\"The only friend these eyes have seen,",
  "\"We both are old and feeble, he and I--",
  "\"Together we have liv'd, together let us die!",
  "",
  "",
  "XV.",
  "",
  "\"Behold his dim, yet speaking eye!",
  "\"Which ill befits his visage grim",
  "\"He cannot from your anger fly,",
  "\"For slow and feeble is old TRIM!",
  "\"He looks, as though he fain would speak,",
  "\"His beard is white--his voice is weak--",
  "\"He IS NOT MAD! O! then, in pity spare",
  "\"The only watchful friend, of my small fleecy care!\"",
  "",
  "",
  "XVI.",
  "",
  "The Shepherd ceas'd to speak, for He",
  "Leant on his maple staff, subdu'd;",
  "While pity touch'd the company,",
  "And all, poor TRIM with sorrow view'd:",
  "Nine days upon a willow bed",
  "Old TRIM was doom'd to lay his head,",
  "Oppress'd and sever'd from his master's door,",
  "Enough to make him MAD--were he not so before!",
  "",
  "",
  "XVII.",
  "",
  "But not forsaken yet, was he,",
  "For ev'ry morn, at peep of day,",
  "To keep his old friend company,",
  "The lonely Shepherd bent his way:",
  "A little boat, across the stream,",
  "Which glitter'd in the sunny beam,",
  "Bore him, where foes no longer could annoy,",
  "Where TRIM stood yelping loud, and ALMOST MAD with joy!",
  "",
  "",
  "XVIII.",
  "",
  "Six days had pass'd and still was he",
  "Upon the island left to roam,",
  "When on the stream a wither'd tree",
  "Was gliding rapid midst the foam!",
  "The little Boat now onward prest,",
  "Danc'd o'er the river's bounding breast,",
  "Till dash'd impetuous, 'gainst the old tree's side,",
  "The Shepherd plung'd and groan'd, then sunk amid the tide.",
  "",
  "",
  "XIX.",
  "",
  "Old TRIM, now doom'd his friend to see",
  "Beating the foam with wasted breath,",
  "Resolv'd to bear him company,",
  "E'en in the icy arms of death;",
  "Soon with exulting cries he bore",
  "His feeble master to the shore,",
  "And, standing o'er him, howl'd in cadence sad,",
  "For, fear and fondness, now, had nearly made him MAD.",
  "",
  "",
  "XX.",
  "",
  "Together, still their flocks they tend,",
  "More happy than the proudly great;",
  "The Shepherd has no other friend--",
  "No Lordly home, no bed of state!",
  "But on a pallet, clean and low,",
  "They hear, unmov'd, the wild winds blow,",
  "And though they ne'er another spring may see;",
  "The Shepherd, and his Dog, are chearful company.",
  ""
]