module.exports = [
  "The trees in the garden rained flowers.",
  "Children ran there joyously.",
  "They gathered the flowers",
  "Each to himself.",
  "Now there were some",
  "Who gathered great heaps --",
  "Having opportunity and skill --",
  "Until, behold, only chance blossoms",
  "Remained for the feeble.",
  "Then a little spindling tutor",
  "Ran importantly to the father, crying:",
  "\"Pray, come hither!",
  "See this unjust thing in your garden!\"",
  "But when the father had surveyed,",
  "He admonished the tutor:",
  "\"Not so, small sage!",
  "This thing is just.",
  "For, look you,",
  "Are not they who possess the flowers",
  "Stronger, bolder, shrewder",
  "Than they who have none?",
  "Why should the strong --",
  "The beautiful strong --",
  "Why should they not have the flowers?\"",
  "Upon reflection, the tutor bowed to the ground,",
  "\"My lord,\" he said,",
  "\"The stars are displaced",
  "By this towering wisdom.\"",
  ""
]