module.exports = [
  "At Loschwitz above the city",
  "The air is sunny and chill;",
  "The birch-trees and the pine-trees",
  "Grow thick upon the hill.",
  "",
  "Lone and tall, with silver stem,",
  "A birch-tree stands apart;",
  "The passionate wind of spring-time",
  "Stirs in its leafy heart.",
  "",
  "I lean against the birch-tree,",
  "My arms around it twine;",
  "It pulses, and leaps, and quivers,",
  "Like a human heart to mine.",
  "",
  "One moment I stand, then sudden",
  "Let loose mine arms that cling:",
  "O God! the lonely hillside,",
  "The passionate wind of spring!",
  ""
]