module.exports = [
  "At Flores in the Azores Sir Richard Grenville lay,",
  "And a pinnace, like a fluttered bird, came flying from far away:",
  "'Spanish ships of war at sea! we have sighted'",
  "Then sware Lord Thomas Howard: ''Fore God I am no coward;",
  "But I cannot meet them here, for my ships are out of gear,",
  "And the half my men are sick. I must fly, but follow quick.",
  "We are six ships of the line; can we fight with ?'",
  "",
  "Then spake Sir Richard Grenville: 'I know you are no coward;",
  "You fly them for a moment to fight with them again.",
  "But I've ninety men and more that are lying sick ashore.",
  "I should count myself the coward if I left them, my Lord Howard,",
  "To these Inquisition dogs and the devildoms of Spain.'",
  "",
  "So Lord Howard passed away with five ships of war that day,",
  "Till he melted like a cloud in the silent summer heaven;",
  "But Sir Richard bore in hand all his sick men from the land",
  "Very carefully and slow,",
  "Men of Bideford in Devon,",
  "And we laid them on the ballast down below;",
  "For we brought them all aboard,",
  "And they blest him in their pain, that they were not left to Spain,",
  "To the thumbscrew and the stake, for the glory of the Lord.",
  "",
  "He had only a hundred seamen to work the ship and to fight,",
  "And he sailed away from Flores till the Spaniard came in sight,",
  "With his huge sea-castles heaving upon the weather bow.",
  "'Shall we fight or shall we fly?",
  "Good Sir Richard, tell us now,",
  "For to fight is but to die!",
  "There'll be little of us left by the time this sun be set.'",
  "And Sir Richard said again: 'We be all good English men.",
  "Let us bang these dogs of Seville, the children of the devil,",
  "For I never turned my back upon Don or devil yet.'",
  "",
  "Sir Richard spoke and he laughed, and we roared a hurrah, and so",
  "The little Revenge ran on sheer into the heart of the foe,",
  "With her hundred fighters on deck, and her ninety sick below;",
  "For half of their fleet to the right and half to the left were seen,",
  "And the little Revenge ran on through the long sea-lane between.",
  "",
  "Thousands of their soldiers looked down from their decks and laughed,",
  "Thousands of their seamen made mock at the mad little craft",
  "Running on and on, till delayed",
  "By their mountain-like",
  ""
]