module.exports = [
  "Composed, by Special Request, 18th June 1890",
  "",
  "",
  "Then Pilate, the Roman Governor, took Jesus and scourged Him,",
  "And the soldiers platted a crown of thorns, and thought it no sin",
  "To put it on His head, while meekly Jesus stands;",
  "They put on Him a purple robe, and smote Him with their hands.",
  "",
  "Then Pilate went forth again, and said unto them,",
  "Behold, I bring Him forth to you, but I cannot Him condemn,",
  "And I would have you to remember I find no fault in Him,",
  "And to treat Him too harshly 'twould be a sin.",
  "",
  "But the rabble cried. Hail, King of the Jews, and crucify Him;",
  "But Pilate saith unto them, I find in Him no sin;",
  "Then Jesus came forth, looking dejected and wan,",
  "And Pilate saith unto them, Behold the Man.",
  "",
  "Then the Jews cried out, By our laws He ought to die,",
  "Because He made Himself the Son of God the Most High;",
  "And when Pilate heard that saying the Jews had made,",
  "He saw they were dissatisfied, and he was the more afraid.",
  "",
  "And to release Jesus Pilate did really intend,",
  "But the Jews cried angrily, Pilate, thou art not Caesar's friend,",
  "Remember, if thou let this vile impostor go,",
  "It only goes to prove thou art Caesar's foe.",
  "",
  "When Pilate heard that he felt very irate,",
  "Then he brought Josus forth, and sat down in the judgment-seat,",
  "In a place that is called the Pavement,",
  "While the Blessed Saviour stood calm and content.",
  "",
  "The presence of His enemies did not Him appal,",
  "When Pilate asked of Him, before them all,",
  "Whence art Thou, dost say from on High?",
  "But Jesus, the Lamb of God, made no reply.",
  "",
  "Then saith Pilate unto Him, Speakest Thou not unto me,",
  "Remember, I have the power to crucify Thee;",
  "But Jesus answered, Thou hast no power at all against me,",
  "Except from above it were given to thee.",
  "",
  "Then Pilate to the Jews loudly cried,",
  "Take Him away to be crucified;",
  "Then the soldiers took Jesus and led Him away,",
  "And He, bearing His Cross, without dismay.",
  "",
  "And they led Him to a place called Golgotha,",
  "But the Saviour met His fate without any awe,",
  "And there crucified Him with two others, one on either side,",
  "And Jesus in the midst, whilst the Jews did Him deride.",
  "",
  "Then Pilate tried to pacify the Jews, they felt so morose,",
  "And he wrote a title, and put it on the Cross;",
  "And the title he wrote did the Jews amuse,",
  "The writing was, Jesus of Nazareth the King of the Jews.",
  "",
  "This title read many of the Jews without any pity;",
  "And the place where Jesus was crucified was nigh to the city;",
  "And the title was written in Hebrew, and Greek, and Latin,",
  "And while reading the title the Jews did laugh and grin.",
  "",
  "While on the Cross the sun refused to shine,",
  "And there was total darkness for a long time;",
  "The reason was God wanted to hide His wounds from view,",
  "And He kept the blessed sun from breaking through.",
  "",
  "And to quench His thirst they gave Him vinegar and hyssop,",
  "While the blood from His wounded brow copiously did drop,",
  "Then He drank of it willingly, and bowed His head,",
  "And in a few minutes the dear Saviour was dead.",
  "",
  "Then Joseph of Arimathea sadly did grieve,",
  "And he asked if Pilate would give him leave",
  "To take the body of Jesus away,",
  "And Pilate told him to remove it without delay.",
  "",
  "Then Joseph took the body of Jesus away,",
  "And wound it in linen, which was the Jewish custom of that day,",
  "And embalmed his body with spices sweet,",
  "Then laid it in a new sepulchre, as Joseph thought meet.",
  "",
  "But death could not hold Him in the grave,",
  "Because He died poor sinners' souls to save;",
  "And God His Father took Him to Heaven on high;",
  "And those that believe in Jesus shall never die.",
  "",
  "Oh! think of the precious Blood our Saviour did loss,",
  "That flowed from His wounds while on the Cross,",
  "Especially the wound in His side, made with a spear,",
  "And if you are a believer, you will drop a silent tear.",
  "",
  "And if you are not a believer, try and believe,",
  "And don't let the devil any longer you deceive,",
  "Because the precious Blood that Jesus shed will free you from all sin,",
  "Therefore, believe in the Saviour, and Heaven you shall enter in!",
  ""
]