module.exports = [
  "The furl of fresh-leaved dogrose down",
  "His cheeks the forth-and-flaunting sun",
  "Had swarthed about with lion-brown",
  "Before the Spring was done.",
  "",
  "His locks like all a ravel-rope’s-end,",
  "With hempen strands in spray—",
  "Fallow, foam-fallow, hanks—fall’n off their ranks,",
  "Swung down at a disarray.",
  "",
  "Or like a juicy and jostling shock",
  "Of bluebells sheaved in May",
  "Or wind-long fleeces on the flock",
  "A day off shearing day.",
  "",
  "Then over his turnиd temples—here—",
  "Was a rose, or, failing that,",
  "Rough-Robin or five-lipped campion clear",
  "For a beauty-bow to his hat,",
  "And the sunlight sidled, like dewdrops, like dandled diamonds",
  "Through the sieve of the straw of the plait.",
  ". . . . . . .",
  ""
]