module.exports = [
  "Pity the sorrows of the poor blind,",
  "For they can but little comfort find;",
  "As they walk along the street,",
  "They know not where to put their feet.",
  "They are deprived of that earthly joy",
  "Of seeing either man, woman, or boy;",
  "Sad and lonely through the world they go,",
  "Not knowing a friend from a foe:",
  "Nor the difference betwixt day and night,",
  "For the want of their eyesight;",
  "The blind mother cannot see her darling boy,",
  "That was once her soul's joy.",
  "By day and night,",
  "Since she lost her precious sight;",
  "To her the world seems dark and drear,",
  "And she can find no comfort here.",
  "She once found pleasure in reading books,",
  "But now pale and careworn are her looks.",
  "Since she has lost her eyesight,",
  "Everything seems wrong and nothing right.",
  "",
  "The face of nature, with all its beauties and livery green,",
  "Appears to the blind just like a dream.",
  "All things beautiful have vanished from their sight,",
  "Which were once their heart's delight.",
  "The blind father cannot see his beautiful child, nor wife,",
  "That was once the joy of his life;",
  "That he was wont to see at morn and night,",
  "When he had his eyesight.",
  "All comfort has vanished from him now,",
  "And a dejected look hangs on his brow.",
  "",
  "Kind Christians all, both great and small,",
  "Pity the sorrows of the blind,",
  "They can but little comfort find;",
  "Therefore we ought to be content with our lot,",
  "And for the eyesight we have got,",
  "And pray to God both day and night",
  "To preserve our eyesight;",
  "To be always willing to help the blind in their distress,",
  "And the Lord will surely bless",
  "And guard us by night and day,",
  "And remember us at the judgment day.",
  ""
]