module.exports = [
  "The eternal gates terrific porter lifted the northern bar:",
  "Thel enter'd in & saw the secrets of the land unknown;",
  "She saw the couches of the dead, & where the fibrous roots",
  "Of every heart on earth infixes deep its restless twists:",
  "A land of sorrows & of tears where never smile was seen.",
  "",
  "She wandered in the land of clouds thro' valleys dark, listning",
  "Dolors & lamentations: waiting oft beside the dewy grave",
  "She stood in silence, listning to the voices of the ground,",
  "Till to her own grave plot she came, & there she sat down.",
  "And heard this voice of sorrow breathed from the hollow pit.",
  "",
  "Why cannot the Ear be closed to its own destruction?",
  "Or the glistening Eye to the poison of a smile!",
  "Why are Eyelids stord with arrows ready drawn,",
  "Where a thousand fighting men in ambush lie!",
  "Or an Eye of gifts & graces showring fruits & coined gold!",
  "",
  "Why a Tongue impress'd with honey from every wind?",
  "Why an Ear, a whirlpool fierce to draw creations in?",
  "Why a Nostril wide inhaling terror trembling & affright",
  "Why a tender curb upon the youthful burning boy?",
  "Why a little curtain of flesh on the bed of our desire?",
  "",
  "The Virgin started from her seat, & with a shriek,",
  "Fled back unhinderd till she came into the vales of Har.",
  ""
]