module.exports = [
  "'Twas in the year 1815, and on the 18th day of June,",
  "That British cannon, against the French army, loudly did boom,",
  "Upon the ever memorable bloody field of Waterloo;",
  "Which Napoleon remembered while in St. Helena, and bitterly did rue.",
  "The morning of the 18th was gloomy and cheerless to behold,",
  "But the British soon recovered from the severe cold",
  "That they had endured the previous rainy night;",
  "And each man prepared to burnish his arms for the coming fight.",
  "",
  "Then the morning passed in mutual arrangements for battle,",
  "And the French guns, at half-past eleven, loudly did rattle;",
  "And immediately the order for attack was given,",
  "Then the bullets flew like lightning till the Heaven's seemed riven.",
  "",
  "The place from which Bonaparte viewed the bloody field",
  "Was the farmhouse of La Belle Alliance, which some protection did yield;",
  "And there he remained for the most part of the day,",
  "Pacing to and fro with his hands behind him in doubtful dismay.",
  "",
  "The Duke of Wellington stood upon a bridge behind La Haye,",
  "And viewed the British army in all their grand array,",
  "And where danger threatened most the noble Duke was found",
  "In the midst of shot and shell on every side around.",
  "",
  "Hougemont was the key of the Duke of Wellington's position,",
  "A spot that was naturally very strong, and a great acqusition",
  "To the Duke and his staff during the day,",
  "Which the Coldstream Guards held to the last, without dismay.",
  "",
  "The French 2nd Corps were principally directed during the day",
  "To carry Hougemont farmhouse without delay;",
  "So the farmhouse in quick succession they did attack,",
  "But the British guns on the heights above soon drove them back.",
  "",
  "But still the heavy shot and shells ploughed through the walls;",
  "Yet the brave Guards resolved to hold the place no matter what befalls;",
  "And they fought manfully to the last, with courage unshaken,",
  "Until the tower of Hougemont was in a blaze but still it remained untaken.",
  "",
  "By these desperate attacks Napoleon lost ten thousand men,",
  "And left them weltering in their gore like sheep in a pen;",
  "And the British lost one thousand men-- which wasn't very great,",
  "Because the great Napoleon met with a crushing defeat.",
  "",
  "The advance of Napoleon on the right was really very fine,",
  "Which was followed by a general onset upon the British line,",
  "In which three hundred pieces of artillery opened their cannonade;",
  "But the British artillery played upon them, and great courage displayed.",
  "",
  "For ten long hours it was a continued succession of attacks;",
  "Whilst the British cavalry charged them in all their drawbacks;",
  "And the courage of the British Army was great in square at Waterloo,",
  "Because hour after hour they were mowed down in numbers not a few.",
  "",
  "At times the temper of the troops had very nearly failed,",
  "Especially amongst the Irish regiments who angry railed;",
  "And they cried: \" When will we get at them? Show us the way",
  "That we may avenge the death of our comrades without delay\"",
  "",
  "\"But be steady and cool, my brave lads,\" was their officers' command,",
  "While each man was ready to charge with gun in hand;",
  "Oh, Heaven! if was pitiful to see their comrades lying around,",
  "Dead and weltering in their gore, and cumbering the ground.",
  "",
  "It was a most dreadful sight to behold,",
  "Heaps upon heaps of dead men lying stiff and cold;",
  "While the cries of the dying was lamentable to hear;",
  "And for the loss Of their comrades many a soldier shed a tear.",
  "",
  "Men and horses fell on every aide around,",
  "Whilst heavy cannon shot tore up the ground;",
  "And musket balls in thousands flew,",
  "And innocent blood bedewed the field of Waterloo.",
  "",
  "Methinks I see the solid British square,",
  "Whilst the shout of the French did rend the air,",
  "As they rush against the square of steel.",
  "Which forced them back and made them reel.",
  "",
  "And when a gap was made in that square,",
  "The cry of \"Close up! Close up!\" did rend the air,",
  "\"And charge them with your bayonets, and make them fly!",
  "And Scotland for ever! be the cry.\"",
  "",
  "The French and British closed in solid square,",
  "While the smoke of the heavy cannonade darkened the air;",
  "Then the noble Picton deployed his division into line,",
  "And drove back the enemy in a very short time.",
  "",
  "Then Lord Anglesey seized on the moment, and charging with the Greys,",
  "Whilst the Inniskillings burst through everything, which they did always;",
  "Then the French infantry fell in hundreds by the swords of the Dragoons;",
  "Whilst the thundering of the cannonade loudly booms.",
  "",
  "And the Eagles of the 45th and 105th were all captured that day,",
  "And upwards of 2000 prisoners, all in grand array;",
  "But, alas! at the head of his division, the noble Picton fell,",
  "While the Highlanders played a lament for him they loved so well.",
  "",
  "Then the French cavalry receded from the square they couldn't penetrate,",
  "Still Napoleon thought to weary the British into defeat;",
  "But when he saw his columns driven back in dismay,",
  "He cried, \"How beautifully these English fight, but they must give way.\"",
  "",
  "And well did British bravery deserve the proud encomium,",
  "Which their enduring courage drew from the brave Napoleon;",
  "And when the close column of infantry came on the British square,",
  "Then the British gave one loud cheer which did rend the air.",
  "",
  "Then the French army pressed forward at Napoleon's command,",
  "Determined, no doubt, to make a bold stand;",
  "Then Wellington cried, \" Up Guards and break their ranks through,",
  "And chase the French invaders from off the field of Waterloo!\"",
  "",
  "Then, in a moment, they were all on their feet,",
  "And they met the French, sword in hand, and made them retreat;",
  "Then Wellington in person directed the attack,",
  "And at every point and turning the French were beaten back.",
  "",
  "And the road was choked and encumbered with the dead;",
  "And, unable to stand the charge, the French instantly fled,",
  "And Napoleon's army of yesterday was now a total wreck,",
  "Which the British manfully for ten long hours held in check.",
  "",
  "Then, panic-struck, the French were forced to yield,",
  "And Napoleon turned his charger's head, and fled from the field,",
  "With his heart full of woe, no doubt",
  "Exclaiming, \"Oh, Heaven! my noble army has met with a total rout!\"",
  ""
]