module.exports = [
  "IT stood in the sunset sky",
  "Like the straight-backed down,",
  "Many a time--the barn",
  "At the edge of the town,",
  "",
  "So huge and dark that it seemed",
  "It was the hill",
  "Till the gable's precipice proved",
  "It impossible.",
  "",
  "Then the great down in the west",
  "Grew into sight,",
  "A barn stored full to the ridge",
  "With black of night;",
  "",
  "And the barn fell to a barn",
  "Or even less",
  "Before critical eyes and its own",
  "Late mightiness.",
  "",
  "But far down and near barn and I",
  "Since then have smiled,",
  "Having seen my new cautiousness",
  "By itself beguiled",
  "",
  "To disdain what seemed the barn",
  "Till a few steps changed",
  "It past all doubt to the down;",
  "So the barn was avenged.",
  ""
]