module.exports = [
  "If souls should only sheen so bright",
  "In heaven as in e’thly light,",
  "An’ nothen better wer the cease,",
  "How comely still, in sheape an’ feace,",
  "Would many reach thik happy pleace, -",
  "The hopevul souls that in their prime",
  "Ha’ seem’d a-took avore their time, -",
  "The young that died in beauty.",
  "",
  "But when woone’s lim’s ha’ lost their strangth",
  "A-tweilen drough a lifetime’s langth,",
  "An’ over cheaks a-growen wold",
  "The slowly-weasten years ha’ roll’d",
  "The deep’nen wrinkle’s hollow vwold;",
  "When life is ripe, then death do call",
  "Vor less ov thought, than when do vall",
  "On young vo’ks in their beauty.",
  "",
  "But pinen souls, wi’ heads a-hung",
  "In heavy sorrow vor the young,",
  "The sister ov the brother dead,",
  "The father wi’ a child a-vled,",
  "The husband when his bride ha’ laid",
  "Her head at rest, noo mwore to turn,",
  "Have all a-vound the time to murn",
  "Vor youth that died in beauty.",
  "",
  "An’ yeet the church, where prayer do rise",
  "Vrom thoughtvul souls, wi’ downcast eyes,",
  "An’ village greens, a-beat half beare",
  "By dancers that do meet, an’ wear",
  "Such merry looks at feast an’ feair,",
  "Do gather under leatest skies,",
  "Their bloomen cheaks an’ sparklen eyes,",
  "Though young ha’ died in beauty.",
  "",
  "But still the dead shall mwore than keep",
  "The beauty ov their early sleep;",
  "Where comely looks shall never wear",
  "Uncomely, under tweil an' ceare.",
  "The feair at death be always feair,",
  "Still feair to livers’ thought an’ love,",
  "An’ feairer still to God above,",
  "Than when they died in beauty.",
  ""
]