module.exports = [
  "IT stands alone",
  "Up in a land of stone",
  "All worn like ancient stairs,",
  "A land of rocks and trees",
  "Nourished on wind and stone.",
  "",
  "And all within",
  "Long delicate has been;",
  "By arts and kindliness",
  "Coloured, sweetened, and warmed",
  "For many years has been.",
  "",
  "Safe resting there",
  "Men hear in the travelling air",
  "But music, pictures see",
  "In the same daily land",
  "Painted by the wild air.",
  "",
  "One maker's mind",
  "Made both, and the house is kind",
  "To the land that gave it peace,",
  "And the stone has taken the house",
  "To its cold heart and is kind.",
  ""
]