module.exports = [
  "CHAPEL and gravestones, old and few,",
  "Are shrouded by a mountain fold",
  "From sound and view",
  "Of life. The loss of the brook's voice",
  "Falls like a shadow. All they hear is",
  "The eternal noise",
  "Of wind whistling in grass more shrill",
  "Than aught as human as a sword,",
  "And saying still:",
  "\"'Tis but a moment since man's birth",
  "And in another moment more",
  "Man lies in earth",
  "For ever; but I am the same",
  "Now, and shall be, even as I was",
  "Before he came;",
  "Till there is nothing I shall be.\"",
  "Yet there the sun shines after noon",
  "So cheerfully",
  "The place almost seems peopled, nor",
  "Lacks cottage chimney, cottage hearth:",
  "It is not more",
  "In size than is a cottage, less",
  "Than any other empty home",
  "In homeliness.",
  "It has a garden of wild flowers",
  "And finest grass and gravestones warm",
  "In sunshine hours",
  "The year through. Men behind the glass",
  "Stand once a week, singing, and drown",
  "The whistling grass",
  "Their ponies munch. And yet somewhere,",
  "Near or far off, there's a man could",
  "Be happy here,",
  "Or one of the gods perhaps, were they",
  "Not of inhuman stature dire,",
  "As poets say",
  "Who have not seen them clearly; if",
  "At sound of any wind of the world",
  "In grass-blades stiff",
  "They would not startle and shudder cold",
  "Under the sun. When gods were young",
  "This wind was old.",
  ""
]