module.exports = [
  "The valley lay smiling before me,",
  "Where lately I left her behind;",
  "Yet I trembled, and something hung o'er me,",
  "That sadden'd the joy of my mind.",
  "I look'd for the lamp which, she told me,",
  "Should shine when her Pilgrim return'd;",
  "But, though darkness began to infold me,",
  "No lamp from the battlements burn'd!",
  "",
  "I flew to her chamber -- 'twas lonely,",
  "As if the loved tenant lay dead; --",
  "Ah, would it were death, and death only!",
  "But no, the young false one had fled.",
  "And there hung the lute that could soften",
  "My very worst pains into bliss;",
  "While the hand that had waked it so often",
  "Now throbb'd to a proud rival's kiss.",
  "",
  "There was a time, falsest of women,",
  "When Breffni's good sword would have sought",
  "That man, through a million of foemen,",
  "Who dared but to wrong thee in thought!",
  "While now -- oh degenerate daughter",
  "Of Erin, how fallen is thy fame!",
  "And through ages of bondage and slaughter,",
  "Our country shall bleed for thy shame.",
  "",
  "Already the curse is upon her,",
  "And strangers her valleys profane;",
  "They come to divide, to dishonour,",
  "And tyrants they long will remain.",
  "But onward! --- the green banner rearing,",
  "Go, flesh every sword to the hilt;",
  "On our side is Virtue and Erin,",
  "On theirs is the Saxon and Guilt.",
  ""
]