module.exports = [
  "THE PROLOGUE.",
  "",
  "\"SIR Clerk of Oxenford,\" our Hoste said,",
  "\"Ye ride as still and coy, as doth a maid",
  "That were new spoused, sitting at the board:",
  "This day I heard not of your tongue a word.",
  "I trow ye study about some sophime:",
  "But Solomon saith, every thing hath time.",
  "For Godde's sake, be of better cheer,",
  "It is no time for to study here.",
  "Tell us some merry tale, by your fay;",
  "For what man that is entered in a play,",
  "He needes must unto that play assent.",
  "But preache not, as friars do in Lent,",
  "To make us for our olde sinnes weep,",
  "Nor that thy tale make us not to sleep.",
  "Tell us some merry thing of aventures.",
  "Your terms, your coloures, and your figures,",
  "Keep them in store, till so be ye indite",
  "High style, as when that men to kinges write.",
  "Speake so plain at this time, I you pray,",
  "That we may understande what ye say.\"",
  "",
  "This worthy Clerk benignely answer'd;",
  "\"Hoste,\" quoth he, \"I am under your yerd,",
  "Ye have of us as now the governance,",
  "And therefore would I do you obeisance,",
  "As far as reason asketh, hardily:",
  "I will you tell a tale, which that I",
  "Learn'd at Padova of a worthy clerk,",
  "As proved by his wordes and his werk.",
  "He is now dead, and nailed in his chest,",
  "I pray to God to give his soul good rest.",
  "Francis Petrarc', the laureate poet,",
  "Highte this clerk, whose rhetoric so sweet",
  "Illumin'd all Itale of poetry,",
  "As Linian  did of philosophy,",
  "Or law, or other art particulere:",
  "But death, that will not suffer us dwell here",
  "But as it were a twinkling of an eye,",
  "Them both hath slain, and alle we shall die.",
  "",
  "\"But forth to tellen of this worthy man,",
  "That taughte me this tale, as I began,",
  "I say that first he with high style inditeth",
  "(Ere he the body of his tale writeth)",
  "A proem, in the which describeth he",
  "Piedmont, and of Saluces  the country,",
  "And speaketh of the Pennine hilles high,",
  "That be the bounds of all West Lombardy:",
  "And of Mount Vesulus in special,",
  "Where as the Po out of a welle small",
  "Taketh his firste springing and his source,",
  "That eastward aye increaseth in his course",
  "T'Emilia-ward,  to Ferraro, and Venice,",
  "The which a long thing were to devise.",
  "And truely, as to my judgement,",
  "Me thinketh it a thing impertinent,",
  "Save that he would conveye his mattere:",
  "But this is the tale, which that ye shall hear.\"",
  "",
  "THE TALE.",
  "",
  "Pars Prima.",
  "",
  "There is, right at the west side of Itale,",
  "Down at the root of Vesulus the cold,",
  "A lusty plain, abundant of vitaille;",
  "There many a town and tow'r thou may'st behold,",
  "That founded were in time of fathers old,",
  "And many another delectable sight;",
  "And Saluces this noble country hight.",
  "",
  "A marquis whilom lord was of that land,",
  "As were his worthy elders him before,",
  "And obedient, aye ready to his hand,",
  "Were all his lieges, bothe less and more:",
  "Thus in delight he liv'd, and had done yore,",
  "Belov'd and drad, through favour of fortune,",
  "Both of his lordes and of his commune.",
  "",
  "Therewith he was, to speak of lineage,",
  "The gentilest y-born of Lombardy,",
  "A fair person, and strong, and young of age,",
  "And full of honour and of courtesy:",
  "Discreet enough his country for to gie,",
  "Saving in some things that he was to blame;",
  "And Walter was this younge lordes name.",
  "",
  "I blame him thus, that he consider'd not",
  "In time coming what might him betide,",
  "But on his present lust was all his thought,",
  "And for to hawk and hunt on every side;",
  "Well nigh all other cares let he slide,",
  "And eke he would (that was the worst of all)",
  "Wedde no wife for aught that might befall.",
  "",
  "Only that point his people bare so sore,",
  "That flockmel on a day to him they went,",
  "And one of them, that wisest was of lore",
  "(Or elles that the lord would best assent",
  "That he should tell him what the people meant,",
  "Or elles could he well shew such mattere),",
  "He to the marquis said as ye shall hear.",
  "",
  "\"O noble Marquis! your humanity",
  "Assureth us and gives us hardiness,",
  "As oft as time is of necessity,",
  "That we to you may tell our heaviness:",
  "Accepte, Lord, now of your gentleness,",
  "What we with piteous heart unto you plain,",
  "And let your ears my voice not disdain.",
  "",
  "\"All have I nought to do in this mattere",
  "More than another man hath in this place,",
  "Yet forasmuch as ye, my Lord so dear,",
  "Have always shewed me favour and grace,",
  "I dare the better ask of you a space",
  "Of audience, to shewen our request,",
  "And ye, my Lord, to do right as you lest.",
  "",
  "\"For certes, Lord, so well us like you",
  "And all your work, and ev'r have done, that we",
  "Ne coulde not ourselves devise how",
  "We mighte live in more felicity:",
  "Save one thing, Lord, if that your will it be,",
  "That for to be a wedded man you lest;",
  "Then were your people in sovereign hearte's rest.",
  "",
  "\"Bowe your neck under the blissful yoke",
  "Of sovereignty, and not of service,",
  "Which that men call espousal or wedlock:",
  "And thinke, Lord, among your thoughtes wise,",
  "How that our dayes pass in sundry wise;",
  "For though we sleep, or wake, or roam, or ride,",
  "Aye fleeth time, it will no man abide.",
  "",
  "\"And though your greene youthe flow'r as yet,",
  "In creepeth age always as still as stone,",
  "And death menaceth every age, and smit",
  "In each estate, for there escapeth none:",
  "And all so certain as we know each one",
  "That we shall die, as uncertain we all",
  "Be of that day when death shall on us fall.",
  "",
  "\"Accepte then of us the true intent,",
  "That never yet refused youre hest,",
  "And we will, Lord, if that ye will assent,",
  "Choose you a wife, in short time at the lest,",
  "Born of the gentilest and of the best",
  "Of all this land, so that it ought to seem",
  "Honour to God and you, as we can deem.",
  "",
  "\"Deliver us out of all this busy dread,",
  "And take a wife, for highe Godde's sake:",
  "For if it so befell, as God forbid,",
  "That through your death your lineage should slake,",
  "And that a strange successor shoulde take",
  "Your heritage, oh! woe were us on live:",
  "Wherefore we pray you hastily to wive.\"",
  "",
  "Their meeke prayer and their piteous cheer",
  "Made the marquis for to have pity.",
  "\"Ye will,\" quoth he, \"mine owen people dear,",
  "To that I ne'er ere thought constraine me.",
  "I me rejoiced of my liberty,",
  "That seldom time is found in rnarriage;",
  "Where I was free, I must be in servage!",
  "",
  "\"But natheless I see your true intent,",
  "And trust upon your wit, and have done aye:",
  "Wherefore of my free will I will assent",
  "To wedde me, as soon as e'er I may.",
  "But whereas ye have proffer'd me to-day",
  "To choose me a wife, I you release",
  "That choice, and pray you of that proffer cease.",
  "",
  "\"For God it wot, that children often been",
  "Unlike their worthy elders them before,",
  "Bounte comes all of God, not of the strene",
  "Of which they be engender'd and y-bore:",
  "I trust in Godde's bounte, and therefore",
  "My marriage, and mine estate and rest,",
  "I him betake; he may do as him lest.",
  "",
  "\"Let me alone in choosing of my wife;",
  "That charge upon my back I will endure:",
  "But I you pray, and charge upon your life,",
  "That what wife that I take, ye me assure",
  "To worship her, while that her life may dure,",
  "In word and work both here and elleswhere,",
  "As she an emperore's daughter were.",
  "",
  "\"And farthermore this shall ye swear, that ye",
  "Against my choice shall never grudge nor strive.",
  "For since I shall forego my liberty",
  "At your request, as ever may I thrive,",
  "Where as mine heart is set, there will I live",
  "And but ye will assent in such mannere,",
  "I pray you speak no more of this mattere.\"",
  "",
  "With heartly will they sworen and assent",
  "To all this thing, there said not one wight nay:",
  "Beseeching him of grace, ere that they went,",
  "That he would grante them a certain day",
  "Of his espousal, soon as e'er he rnay,",
  "For yet always the people somewhat dread",
  "Lest that the marquis woulde no wife wed.",
  "",
  "He granted them a day, such as him lest,",
  "On which he would be wedded sickerly,",
  "And said he did all this at their request;",
  "And they with humble heart full buxomly,",
  "Kneeling upon their knees full reverently,",
  "Him thanked all; and thus they have an end",
  "Of their intent, and home again they wend.",
  "",
  "And hereupon he to his officers",
  "Commanded for the feaste to purvey.",
  "And to his privy knightes and squiers",
  "Such charge he gave, as him list on them lay:",
  "And they to his commandement obey,",
  "And each of them doth all his diligence",
  "To do unto the feast all reverence.",
  "",
  "Pars Secunda",
  "",
  "Not far from thilke palace honourable,",
  "Where as this marquis shope his marriage,",
  "There stood a thorp, of sighte delectable,",
  "In which the poore folk of that village",
  "Hadde their beastes and their harbourage,",
  "And of their labour took their sustenance,",
  "After the earthe gave them abundance.",
  "",
  "Among this poore folk there dwelt a man",
  "Which that was holden poorest of them all;",
  "But highe God sometimes sende can",
  "His grace unto a little ox's stall;",
  "Janicola men of that thorp him call.",
  "A daughter had he, fair enough to sight,",
  "And Griseldis this younge maiden hight.",
  "",
  "But for to speak of virtuous beauty,",
  "Then was she one the fairest under sun:",
  "Full poorely y-foster'd up was she;",
  "No likerous lust was in her heart y-run;",
  "Well ofter of the well than of the tun",
  "She drank,  and, for she woulde virtue please",
  "She knew well labour, but no idle ease.",
  "",
  "But though this maiden tender were of age;",
  "Yet in the breast of her virginity",
  "There was inclos'd a sad and ripe corage;",
  "And in great reverence and charity",
  "Her olde poore father foster'd she.",
  "A few sheep, spinning, on the field she kept,",
  "She woulde not be idle till she slept.",
  "",
  "And when she homeward came, she would bring",
  "Wortes, and other herbes, times oft,",
  "The which she shred and seeth'd for her living,",
  "And made her bed full hard, and nothing soft:",
  "And aye she kept her father's life on loft",
  "With ev'ry obeisance and diligence,",
  "That child may do to father's reverence.",
  "",
  "Upon Griselda, this poor creature,",
  "Full often sithes this marquis set his eye,",
  "As he on hunting rode, paraventure:",
  "And when it fell that he might her espy,",
  "He not with wanton looking of folly",
  "His eyen cast on her, but in sad wise",
  "Upon her cheer he would him oft advise;",
  "",
  "Commending in his heart her womanhead,",
  "And eke her virtue, passing any wight",
  "Of so young age, as well in cheer as deed.",
  "For though the people have no great insight",
  "In virtue, he considered full right",
  "Her bounte, and disposed that he would",
  "Wed only her, if ever wed he should.",
  "",
  "The day of wedding came, but no wight can",
  "Telle what woman that it shoulde be;",
  "For which marvail wonder'd many a man,",
  "And saide, when they were in privity,",
  "\"Will not our lord yet leave his vanity?",
  "Will he not wed?  Alas, alas the while!",
  "Why will he thus himself and us beguile?\"",
  "",
  "But natheless this marquis had done make",
  "Of gemmes, set in gold and in azure,",
  "Brooches and ringes, for Griselda's sake,",
  "And of her clothing took he the measure",
  "Of a maiden like unto her stature,",
  "And eke of other ornamentes all",
  "That unto such a wedding shoulde fall.",
  "",
  "The time of undern of the same day",
  "Approached, that this wedding shoulde be,",
  "And all the palace put was in array,",
  "Both hall and chamber, each in its degree,",
  "Houses of office stuffed with plenty",
  "There may'st thou see of dainteous vitaille,",
  "That may be found, as far as lasts Itale.",
  "",
  "This royal marquis, richely array'd,",
  "Lordes and ladies in his company,",
  "The which unto the feaste were pray'd,",
  "And of his retinue the bach'lery,",
  "With many a sound of sundry melody,",
  "Unto the village, of the which I told,",
  "In this array the right way did they hold.",
  "",
  "Griseld' of this (God wot) full innocent,",
  "That for her shapen was all this array,",
  "To fetche water at a well is went,",
  "And home she came as soon as e'er she may.",
  "For well she had heard say, that on that day",
  "The marquis shoulde wed, and, if she might,",
  "She fain would have seen somewhat of that sight.",
  "",
  "She thought, \"I will with other maidens stand,",
  "That be my fellows, in our door, and see",
  "The marchioness; and therefore will I fand",
  "To do at home, as soon as it may be,",
  "The labour which belongeth unto me,",
  "And then I may at leisure her behold,",
  "If she this way unto the castle hold.\"",
  "",
  "And as she would over the threshold gon,",
  "The marquis came and gan for her to call,",
  "And she set down her water-pot anon",
  "Beside the threshold, in an ox's stall,",
  "And down upon her knees she gan to fall,",
  "And with sad countenance kneeled still,",
  "Till she had heard what was the lorde's will.",
  "",
  "The thoughtful marquis spake unto the maid",
  "Full soberly, and said in this mannere:",
  "\"Where is your father, Griseldis?\" he said.",
  "And she with reverence, in humble cheer,",
  "Answered, \"Lord, he is all ready here.\"",
  "And in she went withoute longer let",
  "And to the marquis she her father fet.",
  "",
  "He by the hand then took the poore man,",
  "And saide thus, when he him had aside:",
  "\"Janicola, I neither may nor can",
  "Longer the pleasance of mine hearte hide;",
  "If that thou vouchesafe, whatso betide,",
  "Thy daughter will I take, ere that I wend,",
  "As for my wife, unto her life's end.",
  "",
  "\"Thou lovest me, that know I well certain,",
  "And art my faithful liegeman y-bore,",
  "And all that liketh me, I dare well sayn",
  "It liketh thee; and specially therefore",
  "Tell me that point, that I have said before, --",
  "If that thou wilt unto this purpose draw,",
  "To take me as for thy son-in-law.\"",
  "",
  "This sudden case the man astonied so,",
  "That red he wax'd, abash'd, and all quaking",
  "He stood; unnethes said he wordes mo',",
  "But only thus; \"Lord,\" quoth he, \"my willing",
  "Is as ye will, nor against your liking",
  "I will no thing, mine owen lord so dear;",
  "Right as you list governe this mattere.\"",
  "",
  "\"Then will I,\" quoth the marquis softely,",
  "\"That in thy chamber I, and thou, and she,",
  "Have a collation; and know'st thou why?",
  "For I will ask her, if her will it be",
  "To be my wife, and rule her after me:",
  "And all this shall be done in thy presence,",
  "I will not speak out of thine audience.\"",
  "",
  "And in the chamber while they were about",
  "The treaty, which ye shall hereafter hear,",
  "The people came into the house without,",
  "And wonder'd them in how honest mannere",
  "And tenderly she kept her father dear;",
  "But utterly Griseldis wonder might,",
  "For never erst ne saw she such a sight.",
  "",
  "No wonder is though that she be astoned,",
  "To see so great a guest come in that place,",
  "She never was to no such guestes woned;",
  "For which she looked with full pale face.",
  "But shortly forth this matter for to chase,",
  "These are the wordes that the marquis said",
  "To this benigne, very, faithful maid.",
  "",
  "\"Griseld',\" he said, \"ye shall well understand,",
  "It liketh to your father and to me",
  "That I you wed, and eke it may so stand,",
  "As I suppose ye will that it so be:",
  "But these demandes ask I first,\" quoth he,",
  "\"Since that it shall be done in hasty wise;",
  "Will ye assent, or elles you advise?",
  "",
  "\"I say this, be ye ready with good heart",
  "To all my lust, and that I freely may,",
  "As me best thinketh, do you laugh or smart,",
  "And never ye to grudge, night nor day,",
  "And eke when I say Yea, ye say not Nay,",
  "Neither by word, nor frowning countenance?",
  "Swear this, and here I swear our alliance.\"",
  "",
  "Wond'ring upon this word, quaking for dread,",
  "She saide; \"Lord, indigne and unworthy",
  "Am I to this honour that ye me bede,",
  "But as ye will yourself, right so will I:",
  "And here I swear, that never willingly",
  "In word or thought I will you disobey,",
  "For to be dead; though me were loth to dey.\"",
  "",
  "\"This is enough, Griselda mine,\" quoth he.",
  "And forth he went with a full sober cheer,",
  "Out at the door, and after then came she,",
  "And to the people he said in this mannere:",
  "\"This is my wife,\" quoth he, \"that standeth here.",
  "Honoure her, and love her, I you pray,",
  "Whoso me loves; there is no more to say.\"",
  "",
  "And, for that nothing of her olde gear",
  "She shoulde bring into his house, he bade",
  "That women should despoile her right there;",
  "Of which these ladies were nothing glad",
  "To handle her clothes wherein she was clad:",
  "But natheless this maiden bright of hue",
  "From foot to head they clothed have all new.",
  "",
  "Her haires have they comb'd that lay untress'd",
  "Full rudely, and with their fingers small",
  "A crown upon her head they have dress'd,",
  "And set her full of nouches  great and small:",
  "Of her array why should I make a tale?",
  "Unneth the people her knew for her fairness,",
  "When she transmuted was in such richess.",
  "",
  "The marquis hath her spoused with a ring",
  "Brought for the same cause, and then her set",
  "Upon a horse snow-white, and well ambling,",
  "And to his palace, ere he longer let",
  "With joyful people, that her led and met,",
  "Conveyed her; and thus the day they spend",
  "In revel, till the sunne gan descend.",
  "",
  "And, shortly forth this tale for to chase,",
  "I say, that to this newe marchioness",
  "God hath such favour sent her of his grace,",
  "That it ne seemed not by likeliness",
  "That she was born and fed in rudeness, --",
  "As in a cot, or in an ox's stall, --",
  "But nourish'd in an emperore's hall.",
  "",
  "To every wight she waxen is so dear",
  "And worshipful, that folk where she was born,",
  "That from her birthe knew her year by year,",
  "Unnethes trowed they, but durst have sworn,",
  "That to Janicol' of whom I spake before,",
  "She was not daughter, for by conjecture",
  "Them thought she was another creature.",
  "",
  "For though that ever virtuous was she,",
  "She was increased in such excellence",
  "Of thewes good, y-set in high bounte,",
  "And so discreet, and fair of eloquence,",
  "So benign, and so digne of reverence,",
  "And coulde so the people's heart embrace,",
  "That each her lov'd that looked on her face.",
  "",
  "Not only of Saluces in the town",
  "Published was the bounte of her name,",
  "But eke besides in many a regioun;",
  "If one said well, another said the same:",
  "So spread of here high bounte the fame,",
  "That men and women, young as well as old,",
  "Went to Saluces, her for to behold.",
  "",
  "Thus Walter lowly, -- nay, but royally,-",
  "Wedded with fortn'ate honestete,",
  "In Godde's peace lived full easily",
  "At home, and outward grace enough had he:",
  "And, for he saw that under low degree",
  "Was honest virtue hid, the people him held",
  "A prudent man, and that is seen full seld'.",
  "",
  "Not only this Griseldis through her wit",
  "Couth all the feat of wifely homeliness,",
  "But eke, when that the case required it,",
  "The common profit coulde she redress:",
  "There n'as discord, rancour, nor heaviness",
  "In all the land, that she could not appease,",
  "And wisely bring them all in rest and ease",
  "",
  "Though that her husband absent were or non,",
  "If gentlemen or other of that country,",
  "Were wroth, she woulde bringe them at one,",
  "So wise and ripe wordes hadde she,",
  "And judgement of so great equity,",
  "That she from heaven sent was, as men wend,",
  "People to save, and every wrong t'amend",
  "",
  "Not longe time after that this Griseld'",
  "Was wedded, she a daughter had y-bore;",
  "All she had lever borne a knave child,",
  "Glad was the marquis and his folk therefore;",
  "For, though a maiden child came all before,",
  "She may unto a knave child attain",
  "By likelihood, since she is not barren.",
  "",
  "Pars Tertia.",
  "",
  "There fell, as falleth many times mo',",
  "When that his child had sucked but a throw,",
  "This marquis in his hearte longed so",
  "To tempt his wife, her sadness for to know,",
  "That he might not out of his hearte throw",
  "This marvellous desire his wife t'asssay;",
  "Needless, God wot, he thought her to affray.",
  "",
  "He had assayed her anough before,",
  "And found her ever good; what needed it",
  "Her for to tempt, and always more and more?",
  "Though some men praise it for a subtle wit,",
  "But as for me, I say that evil it sit",
  "T'assay a wife when that it is no need,",
  "And putte her in anguish and in dread.",
  "",
  "For which this marquis wrought in this mannere:",
  "He came at night alone there as she lay,",
  "With sterne face and with full troubled cheer,",
  "And saide thus; \"Griseld',\" quoth he \"that day",
  "That I you took out of your poor array,",
  "And put you in estate of high nobless,",
  "Ye have it not forgotten, as I guess.",
  "",
  "\"I say, Griseld', this present dignity,",
  "In which that I have put you, as I trow",
  "Maketh you not forgetful for to be",
  "That I you took in poor estate full low,",
  "For any weal you must yourselfe know.",
  "Take heed of every word that I you say,",
  "There is no wight that hears it but we tway.",
  "",
  "\"Ye know yourself well how that ye came here",
  "Into this house, it is not long ago;",
  "And though to me ye be right lefe and dear,",
  "Unto my gentles ye be nothing so:",
  "They say, to them it is great shame and woe",
  "For to be subject, and be in servage,",
  "To thee, that born art of small lineage.",
  "",
  "\"And namely since thy daughter was y-bore",
  "These wordes have they spoken doubteless;",
  "But I desire, as I have done before,",
  "To live my life with them in rest and peace:",
  "I may not in this case be reckeless;",
  "I must do with thy daughter for the best,",
  "Not as I would, but as my gentles lest.",
  "",
  "\"And yet, God wot, this is full loth to me:",
  "But natheless withoute your weeting",
  "I will nought do; but this will I,\" quoth he,",
  "\"That ye to me assenten in this thing.",
  "Shew now your patience in your working,",
  "That ye me hight and swore in your village",
  "The day that maked was our marriage.\"",
  "",
  "When she had heard all this, she not amev'd",
  "Neither in word, in cheer, nor countenance",
  "(For, as it seemed, she was not aggriev'd);",
  "She saide; \"Lord, all lies in your pleasance,",
  "My child and I, with hearty obeisance",
  "Be youres all, and ye may save or spill",
  "Your owen thing: work then after your will.",
  "",
  "\"There may no thing, so God my soule save,",
  "Like to you, that may displease me:",
  "Nor I desire nothing for to have,",
  "Nor dreade for to lose, save only ye:",
  "This will is in mine heart, and aye shall be,",
  "No length of time, nor death, may this deface,",
  "Nor change my corage to another place.\"",
  "",
  "Glad was the marquis for her answering,",
  "But yet he feigned as he were not so;",
  "All dreary was his cheer and his looking",
  "When that he should out of the chamber go.",
  "Soon after this, a furlong way or two,",
  "He privily hath told all his intent",
  "Unto a man, and to his wife him sent.",
  "",
  "A manner sergeant was this private man,",
  "The which he faithful often founden had",
  "In thinges great, and eke such folk well can",
  "Do execution in thinges bad:",
  "The lord knew well, that he him loved and drad.",
  "And when this sergeant knew his lorde's will,",
  "Into the chamber stalked he full still.",
  "",
  "\"Madam,\" he said, \"ye must forgive it me,",
  "Though I do thing to which I am constrain'd;",
  "Ye be so wise, that right well knowe ye",
  "That lordes' hestes may not be y-feign'd;",
  "They may well be bewailed and complain'd,",
  "But men must needs unto their lust obey;",
  "And so will I, there is no more to say.",
  "",
  "\"This child I am commanded for to take.\"",
  "And spake no more, but out the child he hent",
  "Dispiteously, and gan a cheer to make",
  "As though he would have slain it ere he went.",
  "Griseldis must all suffer and consent:",
  "And as a lamb she sat there meek and still,",
  "And let this cruel sergeant do his will",
  "",
  "Suspicious was the diffame of this man,",
  "Suspect his face, suspect his word also,",
  "Suspect the time in which he this began:",
  "Alas! her daughter, that she loved so,",
  "She weened he would have it slain right tho,",
  "But natheless she neither wept nor siked,",
  "Conforming her to what the marquis liked.",
  "",
  "But at the last to speake she began,",
  "And meekly she unto the sergeant pray'd,",
  "So as he was a worthy gentle man,",
  "That she might kiss her child, ere that it died:",
  "And in her barme this little child she laid,",
  "With full sad face, and gan the child to bless,",
  "And lulled it, and after gan it kiss.",
  "",
  "And thus she said in her benigne voice:",
  "Farewell, my child, I shall thee never see;",
  "But since I have thee marked with the cross,",
  "Of that father y-blessed may'st thou be",
  "That for us died upon a cross of tree:",
  "Thy soul, my little child, I him betake,",
  "For this night shalt thou dien for my sake.",
  "",
  "I trow that to a norice in this case",
  "It had been hard this ruthe for to see:",
  "Well might a mother then have cried, \"Alas!\"",
  "But natheless so sad steadfast was she,",
  "That she endured all adversity,",
  "And to the sergeant meekely she said,",
  "\"Have here again your little younge maid.",
  "",
  "\"Go now,\" quoth she, \"and do my lord's behest.",
  "And one thing would I pray you of your grace,",
  "But if my lord forbade you at the least,",
  "Bury this little body in some place,",
  "That neither beasts nor birdes it arace.\"",
  "But he no word would to that purpose say,",
  "But took the child and went upon his way.",
  "",
  "The sergeant came unto his lord again,",
  "And of Griselda's words and of her cheer",
  "He told him point for point, in short and plain,",
  "And him presented with his daughter dear.",
  "Somewhat this lord had ruth in his mannere,",
  "But natheless his purpose held he still,",
  "As lordes do, when they will have their will;",
  "",
  "And bade this sergeant that he privily",
  "Shoulde the child full softly wind and wrap,",
  "With alle circumstances tenderly,",
  "And carry it in a coffer, or in lap;",
  "But, upon pain his head off for to swap,",
  "That no man shoulde know of his intent,",
  "Nor whence he came, nor whither that he went;",
  "",
  "But at Bologna, to his sister dear,",
  "That at that time of Panic' was Countess,",
  "He should it take, and shew her this mattere,",
  "Beseeching her to do her business",
  "This child to foster in all gentleness,",
  "And whose child it was he bade her hide",
  "From every wight, for aught that might betide.",
  "",
  "The sergeant went, and hath fulfill'd this thing.",
  "But to the marquis now returne we;",
  "For now went he full fast imagining",
  "If by his wife's cheer he mighte see,",
  "Or by her wordes apperceive, that she",
  "Were changed; but he never could her find,",
  "But ever-in-one alike sad and kind.",
  "",
  "As glad, as humble, as busy in service,",
  "And eke in love, as she was wont to be,",
  "Was she to him, in every manner wise;",
  "And of her daughter not a word spake she;",
  "No accident for no adversity",
  "Was seen in her, nor e'er her daughter's name",
  "She named, or in earnest or in game.",
  "",
  "Pars Quarta",
  "",
  "In this estate there passed be four year",
  "Ere she with childe was; but, as God wo'ld,",
  "A knave child she bare by this Waltere,",
  "Full gracious and fair for to behold;",
  "And when that folk it to his father told,",
  "Not only he, but all his country, merry",
  "Were for this child, and God they thank and hery.",
  "",
  "When it was two year old, and from the breast",
  "Departed of the norice, on a day",
  "This marquis caughte yet another lest",
  "To tempt his wife yet farther, if he may.",
  "Oh! needless was she tempted in as say;",
  "But wedded men not connen no measure,",
  "When that they find a patient creature.",
  "",
  "\"Wife,\" quoth the marquis, \"ye have heard ere this",
  "My people sickly bear our marriage;",
  "And namely since my son y-boren is,",
  "Now is it worse than ever in all our age:",
  "The murmur slays mine heart and my corage,",
  "For to mine ears cometh the voice so smart,",
  "That it well nigh destroyed hath mine heart.",
  "",
  "\"Now say they thus, 'When Walter is y-gone,",
  "Then shall the blood of Janicol' succeed,",
  "And be our lord, for other have we none:'",
  "Such wordes say my people, out of drede.",
  "Well ought I of such murmur take heed,",
  "For certainly I dread all such sentence,",
  "Though they not plainen in mine audience.",
  "",
  "\"I woulde live in peace, if that I might;",
  "Wherefore I am disposed utterly,",
  "As I his sister served ere by night,",
  "Right so think I to serve him privily.",
  "This warn I you, that ye not suddenly",
  "Out of yourself for no woe should outraie;",
  "Be patient, and thereof I you pray.\"",
  "",
  "\"I have,\" quoth she, \"said thus, and ever shall,",
  "I will no thing, nor n'ill no thing, certain,",
  "But as you list; not grieveth me at all",
  "Though that my daughter and my son be slain",
  "At your commandement; that is to sayn,",
  "I have not had no part of children twain,",
  "But first sickness, and after woe and pain.",
  "",
  "\"Ye be my lord, do with your owen thing",
  "Right as you list, and ask no rede of me:",
  "For, as I left at home all my clothing",
  "When I came first to you, right so,\" quoth she,",
  "\"Left I my will and all my liberty,",
  "And took your clothing: wherefore I you pray,",
  "Do your pleasance, I will your lust obey.",
  "",
  "\"And, certes, if I hadde prescience",
  "Your will to know, ere ye your lust me told,",
  "I would it do withoute negligence:",
  "But, now I know your lust, and what ye wo'ld,",
  "All your pleasance firm and stable I hold;",
  "For, wist I that my death might do you ease,",
  "Right gladly would I dien you to please.",
  "",
  "\"Death may not make no comparisoun",
  "Unto your love.\" And when this marquis say",
  "The constance of his wife,  he cast adown",
  "His eyen two, and wonder'd how she may",
  "In patience suffer all this array;",
  "And forth he went with dreary countenance;",
  "But to his heart it was full great pleasance.",
  "",
  "This ugly sergeant, in the same wise",
  "That he her daughter caught, right so hath he",
  "(Or worse, if men can any worse devise,)",
  "Y-hent her son, that full was of beauty:",
  "And ever-in-one so patient was she,",
  "That she no cheere made of heaviness,",
  "But kiss'd her son, and after gan him bless.",
  "",
  "Save this she prayed him, if that he might,",
  "Her little son he would in earthe grave,",
  "His tender limbes, delicate to sight,",
  "From fowles and from beastes for to save.",
  "But she none answer of him mighte have;",
  "He went his way, as him nothing ne raught,",
  "But to Bologna tenderly it brought.",
  "",
  "The marquis wonder'd ever longer more",
  "Upon her patience; and, if that he",
  "Not hadde soothly knowen therebefore",
  "That perfectly her children loved she,",
  "He would have ween'd that of some subtilty,",
  "And of malice, or for cruel corage,",
  "She hadde suffer'd this with sad visage.",
  "",
  "But well he knew, that, next himself, certain",
  "She lov'd her children best in every wise.",
  "But now of women would I aske fain,",
  "If these assayes mighte not suffice?",
  "What could a sturdy husband more devise",
  "To prove her wifehood and her steadfastness,",
  "And he continuing ev'r in sturdiness?",
  "",
  "But there be folk of such condition,",
  "That, when they have a certain purpose take,",
  "Thiey cannot stint of their intention,",
  "But, right as they were bound unto a stake,",
  "They will not of their firste purpose slake:",
  "Right so this marquis fully hath purpos'd",
  "To tempt his wife, as he was first dispos'd.",
  "",
  "He waited, if by word or countenance",
  "That she to him was changed of corage:",
  "But never could he finde variance,",
  "She was aye one in heart and in visage,",
  "And aye the farther that she was in age,",
  "The more true (if that it were possible)",
  "She was to him in love, and more penible.",
  "",
  "For which it seemed thus, that of them two",
  "There was but one will; for, as Walter lest,",
  "The same pleasance was her lust also;",
  "And, God be thanked, all fell for the best.",
  "She shewed well, for no worldly unrest,",
  "A wife as of herself no thinge should",
  "Will, in effect, but as her husbaud would.",
  "",
  "The sland'r of Walter wondrous wide sprad,",
  "That of a cruel heart he wickedly,",
  "For he a poore woman wedded had,",
  "Had murder'd both his children privily:",
  "Such murmur was among them commonly.",
  "No wonder is: for to the people's ear",
  "There came no word, but that they murder'd were.",
  "",
  "For which, whereas his people therebefore",
  "Had lov'd him well, the sland'r of his diffame",
  "Made them that they him hated therefore.",
  "To be a murd'rer is a hateful name.",
  "But natheless, for earnest or for game,",
  "He of his cruel purpose would not stent;",
  "To tempt his wife was set all his intent.",
  "",
  "When that his daughter twelve year was of age,",
  "He to the Court of Rome, in subtle wise",
  "Informed of his will, sent his message,",
  "Commanding him such bulles to devise",
  "As to his cruel purpose may suffice,",
  "How that the Pope, for his people's rest,",
  "Bade him to wed another, if him lest.",
  "",
  "I say he bade they shoulde counterfeit",
  "The Pope's bulles, making mention",
  "That he had leave his firste wife to lete,",
  "To stinte rancour and dissension",
  "Betwixt his people and him: thus spake the bull,",
  "The which they have published at full.",
  "",
  "The rude people, as no wonder is,",
  "Weened full well that it had been right so:",
  "But, when these tidings came to Griseldis.",
  "I deeme that her heart was full of woe;",
  "But she, alike sad for evermo',",
  "Disposed was, this humble creature,",
  "Th' adversity of fortune all t' endure;",
  "",
  "Abiding ever his lust and his pleasance,",
  "To whom that she was given, heart and all,",
  "As to her very worldly suffisance.",
  "But, shortly if this story tell I shall,",
  "The marquis written hath in special",
  "A letter, in which he shewed his intent,",
  "And secretly it to Bologna sent.",
  "",
  "To th' earl of Panico, which hadde tho",
  "Wedded his sister, pray'd he specially",
  "To bringe home again his children two",
  "In honourable estate all openly:",
  "But one thing he him prayed utterly,",
  "That he to no wight, though men would inquere,",
  "Shoulde not tell whose children that they were,",
  "",
  "But say, the maiden should y-wedded be",
  "Unto the marquis of Saluce anon.",
  "And as this earl was prayed, so did he,",
  "For, at day set, he on his way is gone",
  "Toward Saluce, and lorde's many a one",
  "In rich array, this maiden for to guide, --",
  "Her younge brother riding her beside.",
  "",
  "Arrayed was toward her marriage",
  "This freshe maiden, full of gemmes clear;",
  "Her brother, which that seven year was of age,",
  "Arrayed eke full fresh in his mannere:",
  "And thus, in great nobless, and with glad cheer,",
  "Toward Saluces shaping their journey,",
  "From day to day they rode upon their way.",
  "",
  "Pars Quinta.",
  "",
  "Among all this, after his wick' usage,",
  "The marquis, yet his wife to tempte more",
  "To the uttermost proof of her corage,",
  "Fully to have experience and lore",
  "If that she were as steadfast as before,",
  "He on a day, in open audience,",
  "Full boisterously said her this sentence:",
  "",
  "\"Certes, Griseld', I had enough pleasance",
  "To have you to my wife, for your goodness,",
  "And for your truth, and for your obeisance,",
  "Not for your lineage, nor for your richess;",
  "But now know I, in very soothfastness,",
  "That in great lordship, if I well advise,",
  "There is great servitude in sundry wise.",
  "",
  "\"I may not do as every ploughman may:",
  "My people me constraineth for to take",
  "Another wife, and cryeth day by day;",
  "And eke the Pope, rancour for to slake,",
  "Consenteth it, that dare I undertake:",
  "And truely, thus much I will you say,",
  "My newe wife is coming by the way.",
  "",
  "\"Be strong of heart, and void anon her place;",
  "And thilke dower that ye brought to me,",
  "Take it again, I grant it of my grace.",
  "Returne to your father's house,\" quoth he;",
  "\"No man may always have prosperity;",
  "With even heart I rede you to endure",
  "The stroke of fortune or of aventure.\"",
  "",
  "And she again answer'd in patience:",
  "\"My Lord,\" quoth she, \"I know, and knew alway,",
  "How that betwixte your magnificence",
  "And my povert' no wight nor can nor may",
  "Make comparison, it is no nay;",
  "I held me never digne in no mannere",
  "To be your wife, nor yet your chamberere.",
  "",
  "\"And in this house, where ye me lady made,",
  "(The highe God take I for my witness,",
  "And all so wisly he my soule glade),",
  "I never held me lady nor mistress,",
  "But humble servant to your worthiness,",
  "And ever shall, while that my life may dure,",
  "Aboven every worldly creature.",
  "",
  "\"That ye so long, of your benignity,",
  "Have holden me in honour and nobley,",
  "Where as I was not worthy for to be,",
  "That thank I God and you, to whom I pray",
  "Foryield it you; there is no more to say:",
  "Unto my father gladly will I wend,",
  "And with him dwell, unto my lifes end,",
  "",
  "\"Where I was foster'd as a child full small,",
  "Till I be dead my life there will I lead,",
  "A widow clean in body, heart, and all.",
  "For since I gave to you my maidenhead,",
  "And am your true wife, it is no dread,",
  "God shielde such a lordes wife to take",
  "Another man to husband or to make.",
  "",
  "\"And of your newe wife, God of his grace",
  "So grant you weal and all prosperity:",
  "For I will gladly yield to her my place,",
  "In which that I was blissful wont to be.",
  "For since it liketh you, my Lord,\" quoth she,",
  "\"That whilom weren all mine hearte's rest,",
  "That I shall go, I will go when you lest.",
  "",
  "\"But whereas ye me proffer such dowaire",
  "As I first brought, it is well in my mind,",
  "It was my wretched clothes, nothing fair,",
  "The which to me were hard now for to find.",
  "O goode God! how gentle and how kind",
  "Ye seemed by your speech and your visage,",
  "The day that maked was our marriage!",
  "",
  "\"But sooth is said, -- algate I find it true,",
  "For in effect it proved is on me, --",
  "Love is not old as when that it is new.",
  "But certes, Lord, for no adversity,",
  "To dien in this case, it shall not be",
  "That e'er in word or work I shall repent",
  "That I you gave mine heart in whole intent.",
  "",
  "\"My Lord, ye know that in my father's place",
  "Ye did me strip out of my poore weed,",
  "And richely ye clad me of your grace;",
  "To you brought I nought elles, out of dread,",
  "But faith, and nakedness, and maidenhead;",
  "And here again your clothing I restore,",
  "And eke your wedding ring for evermore.",
  "",
  "\"The remnant of your jewels ready be",
  "Within your chamber, I dare safely sayn:",
  "Naked out of my father's house,\" quoth she,",
  "\"I came, and naked I must turn again.",
  "All your pleasance would I follow fain:",
  "But yet I hope it be not your intent",
  "That smockless I out of your palace went.",
  "",
  "\"Ye could not do so dishonest a thing,",
  "That thilke womb, in which your children lay,",
  "Shoulde before the people, in my walking,",
  "Be seen all bare: and therefore I you pray,",
  "Let me not like a worm go by the way:",
  "Remember you, mine owen Lord so dear,",
  "I was your wife, though I unworthy were.",
  "",
  "\"Wherefore, in guerdon of my maidenhead,",
  "Which that I brought and not again I bear,",
  "As vouchesafe to give me to my meed",
  "But such a smock as I was wont to wear,",
  "That I therewith may wrie the womb of her",
  "That was your wife: and here I take my leave",
  "Of you, mine owen Lord, lest I you grieve.\"",
  "",
  "\"The smock,\" quoth he, \"that thou hast on thy back,",
  "Let it be still, and bear it forth with thee.\"",
  "But well unnethes thilke word he spake,",
  "But went his way for ruth and for pity.",
  "Before the folk herselfe stripped she,",
  "And in her smock, with foot and head all bare,",
  "Toward her father's house forth is she fare.",
  "",
  "The folk her follow'd weeping on her way,",
  "And fortune aye they cursed as they gon:",
  "But she from weeping kept her eyen drey,",
  "Nor in this time worde spake she none.",
  "Her father, that this tiding heard anon,",
  "Cursed the day and time, that nature",
  "Shope him to be a living creature.",
  "",
  "For, out of doubt, this olde poore man",
  "Was ever in suspect of her marriage:",
  "For ever deem'd he, since it first began,",
  "That when the lord fulfill'd had his corage,",
  "He woulde think it were a disparage",
  "To his estate, so low for to alight,",
  "And voide her as soon as e'er he might.",
  "",
  "Against his daughter hastily went he",
  "(For he by noise of folk knew her coming),",
  "And with her olde coat, as it might be,",
  "He cover'd her, full sorrowfully weeping:",
  "But on her body might he it not bring,",
  "For rude was the cloth, and more of age",
  "By dayes fele than at her marriage.",
  "",
  "Thus with her father for a certain space",
  "Dwelled this flow'r of wifely patience,",
  "That neither by her words nor by her face,",
  "Before the folk nor eke in their absence,",
  "Ne shewed she that her was done offence,",
  "Nor of her high estate no remembrance",
  "Ne hadde she, as by her countenance.",
  "",
  "No wonder is, for in her great estate",
  "Her ghost was ever in plein humility;",
  "No tender mouth, no hearte delicate,",
  "No pomp, and no semblant of royalty;",
  "But full of patient benignity,",
  "Discreet and prideless, aye honourable,",
  "And to her husband ever meek and stable.",
  "",
  "Men speak of Job, and most for his humbless,",
  "As clerkes, when them list, can well indite,",
  "Namely of men; but, as in soothfastness,",
  "Though clerkes praise women but a lite,",
  "There can no man in humbless him acquite",
  "As women can, nor can be half so true",
  "As women be, but it be fall of new.",
  "",
  "Pars Sexta",
  "",
  "From Bologn' is the earl of Panic' come,",
  "Of which the fame up sprang to more and less;",
  "And to the people's eares all and some",
  "Was know'n eke, that a newe marchioness",
  "He with him brought, in such pomp and richess",
  "That never was there seen with manne's eye",
  "So noble array in all West Lombardy.",
  "",
  "The marquis, which that shope and knew all this,",
  "Ere that the earl was come, sent his message",
  "For thilke poore sely Griseldis;",
  "And she, with humble heart and glad visage,",
  "Nor with no swelling thought in her corage,",
  "Came at his hest, and on her knees her set,",
  "And rev'rently and wisely she him gret.",
  "",
  "\"Griseld',\" quoth he, \"my will is utterly,",
  "This maiden, that shall wedded be to me,",
  "Received be to-morrow as royally",
  "As it possible is in my house to be;",
  "And eke that every wight in his degree",
  "Have his estate in sitting and service,",
  "And in high pleasance, as I can devise.",
  "",
  "\"I have no women sufficient, certain,",
  "The chambers to array in ordinance",
  "After my lust; and therefore would I fain",
  "That thine were all such manner governance:",
  "Thou knowest eke of old all my pleasance;",
  "Though thine array be bad, and ill besey,",
  "Do thou thy devoir at the leaste way.\"",
  "",
  "\"Not only, Lord, that I am glad,\" quoth she,",
  "\"To do your lust, but I desire also",
  "You for to serve and please in my degree,",
  "Withoute fainting, and shall evermo':",
  "Nor ever for no weal, nor for no woe,",
  "Ne shall the ghost within mine hearte stent",
  "To love you best with all my true intent.\"",
  "",
  "And with that word she gan the house to dight,",
  "And tables for to set, and beds to make,",
  "And pained her to do all that she might,",
  "Praying the chambereres for Godde's sake",
  "To hasten them, and faste sweep and shake,",
  "And she the most serviceable of all",
  "Hath ev'ry chamber arrayed, and his hall.",
  "",
  "Aboute undern gan the earl alight,",
  "That with him brought these noble children tway;",
  "For which the people ran to see the sight",
  "Of their array, so richely besey;",
  "And then at erst amonges them they say,",
  "That Walter was no fool, though that him lest",
  "To change his wife; for it was for the best.",
  "",
  "For she is fairer, as they deemen all,",
  "Than is Griseld', and more tender of age,",
  "And fairer fruit between them shoulde fall,",
  "And more pleasant, for her high lineage:",
  "Her brother eke so fair was of visage,",
  "That them to see the people hath caught pleasance,",
  "Commending now the marquis' governance.",
  "",
  "\"O stormy people, unsad and ev'r untrue,",
  "And undiscreet, and changing as a vane,",
  "Delighting ev'r in rumour that is new,",
  "For like the moon so waxe ye and wane:",
  "Aye full of clapping, dear enough a jane,",
  "Your doom is false, your constance evil preveth,",
  "A full great fool is he that you believeth.\"",
  "",
  "Thus saide the sad folk in that city,",
  "When that the people gazed up and down;",
  "For they were glad, right for the novelty,",
  "To have a newe lady of their town.",
  "No more of this now make I mentioun,",
  "But to Griseld' again I will me dress,",
  "And tell her constancy and business.",
  "",
  "Full busy was Griseld' in ev'ry thing",
  "That to the feaste was appertinent;",
  "Right nought was she abash'd of her clothing,",
  "Though it were rude, and somedeal eke to-rent;",
  "But with glad cheer unto the gate she went",
  "With other folk, to greet the marchioness,",
  "And after that did forth her business.",
  "",
  "With so glad cheer his guestes she receiv'd",
  "And so conningly each in his degree,",
  "That no defaulte no man apperceiv'd,",
  "But aye they wonder'd what she mighte be",
  "That in so poor array was for to see,",
  "And coude such honour and reverence;",
  "And worthily they praise her prudence.",
  "",
  "In all this meane while she not stent",
  "This maid, and eke her brother, to commend",
  "With all her heart in full benign intent,",
  "So well, that no man could her praise amend:",
  "But at the last, when that these lordes wend",
  "To sitte down to meat, he gan to call",
  "Griseld', as she was busy in the hall.",
  "",
  "\"Griseld',\" quoth he, as it were in his play,",
  "\"How liketh thee my wife, and her beauty?\"",
  "\"Right well, my Lord,\" quoth she, \"for, in good fay,",
  "A fairer saw I never none than she:",
  "I pray to God give you prosperity;",
  "And so I hope, that he will to you send",
  "Pleasance enough unto your lives end.",
  "",
  "\"One thing beseech I you, and warn also,",
  "That ye not pricke with no tormenting",
  "This tender maiden, as ye have done mo:",
  "For she is foster'd in her nourishing",
  "More tenderly, and, to my supposing,",
  "She mighte not adversity endure",
  "As could a poore foster'd creature.\"",
  "",
  "And when this Walter saw her patience,",
  "Her gladde cheer, and no malice at all,",
  "And he so often had her done offence,",
  "And she aye sad and constant as a wall,",
  "Continuing ev'r her innocence o'er all,",
  "The sturdy marquis gan his hearte dress",
  "To rue upon her wifely steadfastness.",
  "",
  "\"This is enough, Griselda mine,\" quoth he,",
  "\"Be now no more aghast, nor evil paid,",
  "I have thy faith and thy benignity",
  "As well as ever woman was, assay'd,",
  "In great estate and poorely array'd:",
  "Now know I, deare wife, thy steadfastness;\"",
  "And her in arms he took, and gan to kiss.",
  "",
  "And she for wonder took of it no keep;",
  "She hearde not what thing he to her said:",
  "She far'd as she had start out of a sleep,",
  "Till she out of her mazedness abraid.",
  "\"Griseld',\" quoth he, \"by God that for us died,",
  "Thou art my wife, none other I have,",
  "Nor ever had, as God my soule save.",
  "",
  "\"This is thy daughter, which thou hast suppos'd",
  "To be my wife; that other faithfully",
  "Shall be mine heir, as I have aye dispos'd;",
  "Thou bare them of thy body truely:",
  "At Bologna kept I them privily:",
  "Take them again, for now may'st thou not say",
  "That thou hast lorn none of thy children tway.",
  "",
  "\"And folk, that otherwise have said of me,",
  "I warn them well, that I have done this deed",
  "For no malice, nor for no cruelty,",
  "But to assay in thee thy womanhead:",
  "And not to slay my children (God forbid),",
  "But for to keep them privily and still,",
  "Till I thy purpose knew, and all thy will.\"",
  "",
  "When she this heard, in swoon adown she falleth",
  "For piteous joy; and after her swooning,",
  "She both her younge children to her calleth,",
  "And in her armes piteously weeping",
  "Embraced them, and tenderly kissing,",
  "Full like a mother, with her salte tears",
  "She bathed both their visage and their hairs.",
  "",
  "O, what a piteous thing it was to see",
  "Her swooning, and her humble voice to hear!",
  "\"Grand mercy, Lord, God thank it you,\" quoth she,",
  "That ye have saved me my children dear;",
  "Now reck I never to be dead right here;",
  "Since I stand in your love, and in your grace,",
  "No force of death, nor when my spirit pace.",
  "",
  "\"O tender, O dear, O young children mine,",
  "Your woeful mother weened steadfastly",
  "That cruel houndes, or some foul vermine,",
  "Had eaten you; but God of his mercy,",
  "And your benigne father tenderly",
  "Have done you keep:\" and in that same stound",
  "All suddenly she swapt down to the ground.",
  "",
  "And in her swoon so sadly holdeth she",
  "Her children two, when she gan them embrace,",
  "That with great sleight and great difficulty",
  "The children from her arm they can arace,",
  "O! many a tear on many a piteous face",
  "Down ran of them that stoode her beside,",
  "Unneth' aboute her might they abide.",
  "",
  "Walter her gladdeth, and her sorrow slaketh:",
  "She riseth up abashed from her trance,",
  "And every wight her joy and feaste maketh,",
  "Till she hath caught again her countenance.",
  "Walter her doth so faithfully pleasance,",
  "That it was dainty for to see the cheer",
  "Betwixt them two, since they be met in fere.",
  "",
  "The ladies, when that they their time sey,",
  "Have taken her, and into chamber gone,",
  "And stripped her out of her rude array,",
  "And in a cloth of gold that brightly shone,",
  "And with a crown of many a riche stone",
  "Upon her head, they into hall her brought:",
  "And there she was honoured as her ought.",
  "",
  "Thus had this piteous day a blissful end;",
  "For every man and woman did his might",
  "This day in mirth and revel to dispend,",
  "Till on the welkin shone the starres bright:",
  "For more solemn in every mannes sight",
  "This feaste was, and greater of costage,",
  "Than was the revel of her marriage.",
  "",
  "Full many a year in high prosperity",
  "Lived these two in concord and in rest;",
  "And richely his daughter married he",
  "Unto a lord, one of the worthiest",
  "Of all Itale; and then in peace and rest",
  "His wife's father in his court he kept,",
  "Till that the soul out of his body crept.",
  "",
  "His son succeeded in his heritage,",
  "In rest and peace, after his father's day:",
  "And fortunate was eke in marriage,",
  "All he put not his wife in great assay:",
  "This world is not so strong, it is no nay,",
  "As it hath been in olde times yore;",
  "And hearken what this author saith, therefore;",
  "",
  "This story is said,  not for that wives should",
  "Follow Griselda in humility,",
  "For it were importable though they would;",
  "But for that every wight in his degree",
  "Shoulde be constant in adversity,",
  "As was Griselda; therefore Petrarch writeth",
  "This story, which with high style he inditeth.",
  "",
  "For, since a woman was so patient",
  "Unto a mortal man, well more we ought",
  "Receiven all in gree that God us sent.",
  "For great skill is he proved that he wrought:",
  "But he tempteth no man that he hath bought,",
  "As saith Saint James, if ye his 'pistle read;",
  "He proveth folk all day, it is no dread.",
  "",
  "And suffereth us, for our exercise,",
  "With sharpe scourges of adversity",
  "Full often to be beat in sundry wise;",
  "Not for to know our will, for certes he,",
  "Ere we were born, knew all our frailty;",
  "And for our best is all his governance;",
  "Let us then live in virtuous sufferance.",
  "",
  "But one word, lordings, hearken, ere I go:",
  "It were full hard to finde now-a-days",
  "In all a town Griseldas three or two:",
  "For, if that they were put to such assays,",
  "The gold of them hath now so bad allays",
  "With brass, that though the coin be fair at eye,",
  "It woulde rather break in two than ply.",
  "",
  "For which here, for the Wife's love of Bath, --",
  "Whose life and all her sex may God maintain",
  "In high mast'ry, and elles were it scath, --",
  "I will, with lusty hearte fresh and green,",
  "Say you a song to gladden you, I ween:",
  "And let us stint of earnestful mattere.",
  "Hearken my song, that saith in this mannere.",
  "",
  "L'Envoy of Chaucer.",
  "",
  "\"Griseld' is dead, and eke her patience,",
  "And both at once are buried in Itale:",
  "For which I cry in open audience,",
  "No wedded man so hardy be t' assail",
  "His wife's patience, in trust to find",
  "Griselda's, for in certain he shall fail.",
  "",
  "\"O noble wives, full of high prudence,",
  "Let no humility your tongues nail:",
  "Nor let no clerk have cause or diligence",
  "To write of you a story of such marvail,",
  "As of Griselda patient and kind,",
  "Lest Chichevache you swallow in her entrail.",
  "",
  "\"Follow Echo, that holdeth no silence,",
  "But ever answereth at the countertail;",
  "Be not bedaffed for your innocence,",
  "But sharply take on you the governail;",
  "Imprinte well this lesson in your mind,",
  "For common profit, since it may avail.",
  "",
  "\"Ye archiwives, stand aye at defence,",
  "Since ye be strong as is a great camail,",
  "Nor suffer not that men do you offence.",
  "And slender wives, feeble in battail,",
  "Be eager as a tiger yond in Ind;",
  "Aye clapping as a mill, I you counsail.",
  "",
  "\"Nor dread them not, nor do them reverence;",
  "For though thine husband armed be in mail,",
  "The arrows of thy crabbed eloquence",
  "Shall pierce his breast, and eke his aventail;",
  "In jealousy I rede eke thou him bind,",
  "And thou shalt make him couch as doth a quail.",
  "",
  "\"If thou be fair, where folk be in presence",
  "Shew thou thy visage and thine apparail:",
  "If thou be foul, be free of thy dispence;",
  "To get thee friendes aye do thy travail:",
  "Be aye of cheer as light as leaf on lind,",
  "And let him care, and weep, and wring, and wail.\"",
  ""
]