module.exports = [
  "Rintrah roars and shakes his fires in the burden'd air,",
  "Hungry clouds swag on the deep.",
  "",
  "Once meek, and in a perilous path",
  "The just man kept his course along",
  "The Vale of Death.",
  "Roses are planted where thorns grow,",
  "And on the barren heath",
  "Sing the honey bees.",
  "",
  "Then the perilous path was planted,",
  "And a river and a spring",
  "On every cliff and tomb;",
  "And on the bleached bones",
  "Red clay brought forth:",
  "Till the villain left the paths of ease",
  "To walk in perilous paths, and drive",
  "The just man into barren climes.",
  "",
  "Now the sneaking serpent walks",
  "In mild humility;",
  "And the just man rages in the wilds",
  "Where lions roam.",
  "",
  "Rintrah roars and shakes his fires in the burden'd air,",
  "Hungry clouds swag on the deep.",
  ""
]