module.exports = [
  "THE Devil returned to Hell by two,",
  "  And he stayed at home till five;",
  "When he dined on some homicides done in _ragoût_,",
  "  And a rebel or so in an _Irish_ stew,",
  "And sausages made of a self-slain Jew,",
  "And bethought himself what next to do,",
  "  \"And,\" quoth he, \"I'll take a drive.",
  "I walked in the morning, I'll ride to-night;",
  "In darkness my children take most delight,",
  "  And I'll see how my favourites thrive.",
  "",
  "\"And what shall I ride in?\" quoth Lucifer, then--",
  "  \"If I followed my taste, indeed,",
  "I should mount in a waggon of wounded men,",
  "  And smile to see them bleed.",
  "But these will be furnished again and again,",
  "  And at present my purpose is speed;",
  "To see my manor as much as I may,",
  "And watch that no souls shall be poached away.",
  "",
  "\"I have a state-coach at Carlton House,",
  "  A chariot in Seymour-place;",
  "But they're lent to two friends, who make me amends",
  "  By driving my favourite pace:",
  "And they handle their reins with such a grace,",
  "I have something for both at the end of the race.",
  "",
  "\"So now for the earth to take my chance,\"",
  "  Then up to the earth sprung he;",
  "And making a jump from Moscow to France,",
  "  He stepped across the sea,",
  "And rested his hoof on a turnpike road,",
  "No very great way from a Bishop's abode.",
  "",
  "But first as he flew, I forgot to say,",
  "That he hovered a moment upon his way,",
  "  To look upon Leipsic plain;",
  "And so sweet to his eye was its sulphury glare,",
  "And so soft to his ear was the cry of despair,",
  "  That he perched on a mountain of slain;",
  "And he gazed with delight from its growing height,",
  "Nor often on earth had he seen such a sight,",
  "  Nor his work done half as well:",
  "For the field ran so red with the blood of the dead,",
  "  That it blushed like the waves of Hell!",
  "Then loudly, and wildly, and long laughed he:",
  "\"Methinks they have little need here of _me_!\"",
  "",
  "Long he looked down on the hosts of each clime,",
  "  While the warriors hand to hand were--",
  "Gaul--Austrian and Muscovite heroes sublime,",
  "And--(Muse of Fitzgerald arise with a rhyme!)",
  "  A quantity of _Landwehr_!",
  "      Gladness was there,",
  "For the men of all might and the monarchs of earth,",
  "There met for the wolf and the worm to make mirth,",
  "  And a feast for the fowls of the Air!",
  "",
  "But he turned aside and looked from the ridge",
  "  Of hills along the river,",
  "And the best thing he saw was a broken bridge,",
  "  Which a Corporal chose to shiver;",
  "Though an Emperor's taste was displeased with his haste,",
  "  The Devil he thought it clever;",
  "And he laughed again in a lighter strain,",
  "  O'er the torrent swoln and rainy,",
  "When he saw \"on a fiery steed\" Prince Pon,",
  "In taking care of Number _One_--",
  "Get drowned with a great _many_!",
  "",
  "But the softest note that soothed his ear",
  "  Was the sound of a widow sighing;",
  "And the sweetest sight was the icy tear,",
  "Which Horror froze in the blue eye clear",
  "  Of a maid by her lover lying--",
  "As round her fell her long fair hair,",
  "And she looked to Heaven with that frenzied air",
  "Which seemed to ask if a God were there!",
  "And stretched by the wall of a ruined hut,",
  "With its hollow cheek, and eyes half shut,",
  "  A child of Famine dying:",
  "And the carnage _begun_, when _resistance_ is done,",
  "  And the fall of the vainly flying!",
  "",
  "Then he gazed on a town by besiegers taken,",
  "  Nor cared he who were winning;",
  "But he saw an old maid, for years forsaken,",
  "  Get up and leave her spinning;",
  "And she looked in her glass, and to one that did pass,",
  "She said--\"pray are the rapes beginning?\"",
  "",
  "But the Devil has reached our cliffs so white,",
  "  And what did he there, I pray?",
  "If his eyes were good, he but saw by night",
  "  What we see every day;",
  "But he made a tour and kept a journal",
  "Of all the wondrous sights nocturnal,",
  "And he sold it in shares to the _Men_ of the _Row_,",
  "Who bid pretty well--but they _cheated_ him, though!",
  "",
  "The Devil first saw, as he thought, the _Mail_,",
  "  Its coachman and his coat;",
  "So instead of a pistol he cocked his tail,",
  "  And seized him by the throat;",
  "\"Aha!\" quoth he, \"what have we here?",
  "'T is a new barouche, and an ancient peer!\"",
  "",
  "So he sat him on his box again,",
  "  And bade him have no fear,",
  "But be true to his club, and staunch to his rein,",
  "  His brothel and his beer;",
  "\"Next to seeing a Lord at the Council board,",
  "I would rather see him here.\"",
  "",
  "Satan hired a horse and gig",
  "  With promises to pay;",
  "And he pawned his horns for a spruce new wig,",
  "  To redeem as he came away:",
  "And he whistled some tune, a waltz or a jig,",
  "  And drove off at the close of day.",
  "",
  "The first place he stopped at--he heard the Psalm",
  "  That rung from a Methodist Chapel:",
  "\"'T is the best sound I've heard,\" quoth he, \"since my palm",
  "  Presented Eve her apple!",
  "When _Faith_ is all, 't is an excellent sign,",
  "That the _Works_ and Workmen both are mine.\"",
  "",
  "He passed Tommy Tyrwhitt, that standing jest,",
  "  To princely wit a Martyr:",
  "But the last joke of all was by far the best,",
  "  When he sailed away with \"the Garter\"!",
  "\"And\"--quoth Satan--\"this Embassy's worthy my sight,",
  "Should I see nothing else to amuse me to night.",
  "With no one to bear it, but Thomas à Tyrwhitt,",
  "This ribband belongs to an 'Order of Merit'!\"",
  "",
  "He stopped at an Inn and stepped within",
  "  The Bar and read the \"Times;\"",
  "And never such a treat, as--the epistle of one \"Vetus,\"",
  "  Had he found save in downright crimes:",
  "\"Though I doubt if this drivelling encomiast of War",
  "Ever saw a field fought, or felt a scar,",
  "Yet his fame shall go farther than he can guess,",
  "For I'll keep him a place in my _hottest Press_;",
  "And his works shall be bound in Morocco _d'Enfer_,",
  "And lettered behind with his _Nom de Guerre_.\"",
  "",
  "The Devil gat next to Westminster,",
  "  And he turned to \"the room\" of the Commons;",
  "But he heard as he purposed to enter in there,",
  "  That \"the Lords\" had received a summons;",
  "And he thought, as \"a _quondam_ Aristocrat,\"",
  "He might peep at the Peers, though to _hear_ them were flat;",
  "And he walked up the House so like one of his own,",
  "That they say that he stood pretty near the throne.",
  "",
  "He saw the Lord Liverpool seemingly wise,",
  "  The Lord Westmoreland certainly silly,",
  "And Jockey of Norfolk--a man of some size--",
  "  And Chatham, so like his friend Billy;",
  "And he saw the tears in Lord Eldon's eyes,",
  "  Because the Catholics would _not_ rise,",
  "  In spite of his prayers and his prophecies;",
  "And he heard--which set Satan himself a staring--",
  "A certain Chief Justice say something like _swearing_.",
  "And the Devil was shocked--and quoth he, \"I must go,",
  "For I find we have much better manners below.",
  "If thus he harangues when he passes my border,",
  "I shall hint to friend Moloch to call him to order.\"",
  "",
  "Then the Devil went down to the humbler House,",
  "  Where he readily found his way",
  "As natural to him as its hole to a Mouse,",
  "  He had been there many a day;",
  "And many a vote and soul and job he",
  "  Had bid for and carried away from the Lobby:",
  "But there now was a \"call\" and accomplished debaters",
  "Appeared in the glory of hats, boots and gaiters--",
  "_Some_ paid rather more--but _all_ worse dressed",
  "      than Waiters!",
  "",
  "There was Canning for War, and Whitbread for peace,",
  "  And others as suited their fancies;",
  "But all were agreed that our debts should increase",
  "  Excepting the Demagogue Francis.",
  "That rogue! how could Westminster chuse him again",
  "  To leaven the virtue of these honest men!",
  "But the Devil remained till the Break of Day",
  "  Blushed upon Sleep and Lord Castlereagh:",
  "Then up half the house got, and Satan got up",
  "  With the drowsy to snore--or the hungry to sup:--",
  "But so torpid the power of some speakers, 't is said,",
  "That they sent even him to his brimstone bed.",
  "",
  "He had seen George Rose--but George was grown dumb,",
  "   And only lied in thought!",
  "And the Devil has all the pleasure to come",
  "  Of hearing him talk as he ought.",
  "With the falsest of tongues, the sincerest of men--",
  "  His veracity were but deceit--",
  "And Nature must first have unmade him again,",
  "Ere his breast or his face, or his tongue, or his pen,",
  "Conceived--uttered--looked--or wrote down letters ten,",
  "Which Truth would acknowledge complete.",
  "",
  "Satan next took the army list in hand,",
  "  Where he found a new \"Field Marshal;\"",
  "And when he saw this high command",
  "  Conferred on his Highness of Cumberland,",
  "\"Oh! were I prone to cavil--or were I not the Devil,",
  "  I should say this was somewhat partial;",
  "Since the only wounds that this Warrior gat,",
  "Were from God knows whom--and the Devil knows what!\"",
  "",
  "He then popped his head in a royal Ball,",
  "  And saw all the Haram so hoary;",
  "And who there besides but Corinna de Staël!",
  "  Turned Methodist and Tory!",
  "\"Aye--Aye\"--quoth he--\"'t is the way with them all,",
  "  When Wits grow tired of Glory:",
  "But thanks to the weakness, that thus could pervert her,",
  "Since the dearest of prizes to me's a deserter:",
  "_Mem_--whenever a sudden conversion I want,",
  "To send to the school of Philosopher Kant;",
  "And whenever I need a critic who can gloss over",
  "All faults--to send for Mackintosh to write up the Philosopher.\"",
  "",
  "The Devil waxed faint at the sight of this Saint,",
  "  And he thought himself of eating;",
  "And began to cram from a plate of ham",
  "  Wherewith a Page was retreating--",
  "Having nothing else to do (for \"the friends\" each so near",
  "  Had sold all their souls long before),",
  "As he swallowed down the bacon he wished himself a Jew",
  "  For the sake of another crime more:",
  "For Sinning itself is but half a recreation,",
  "Unless it ensures most infallible Damnation.",
  "",
  "But he turned him about, for he heard a sound",
  "  Which even his ear found faults in;",
  "For whirling above--underneath--and around--",
  "  Were his fairest Disciples Waltzing!",
  "And quoth he--\"though this be--the _premier pas_ to me,",
  "  Against it I would warn all--",
  "Should I introduce these revels among my younger devils,",
  "  They would all turn perfectly carnal:",
  "And though fond of the flesh--yet I never could bear it",
  "Should quite in my kingdom get the upper hand of Spirit.\"",
  "",
  "The Devil (but 't was over) had been vastly glad",
  "  To see the new Drury Lane,",
  "And yet he might have been rather mad",
  "  To see it rebuilt in vain;",
  "And had he beheld their \"Nourjahad,\"",
  "  Would never have gone again:",
  "And Satan had taken it much amiss,",
  "They should fasten such a piece on a friend of his--",
  "Though he knew that his works were somewhat sad,",
  "He never had found them _quite_ so bad:",
  "For this was \"the book\" which, of yore, Job, sorely smitten,",
  "Said, \"Oh that _mine_ enemy, _mine_ enemy had written\"!",
  "",
  "Then he found sixty scribblers in separate cells,",
  "  And marvelled what they were doing,",
  "For they looked like little fiends in their own little hells,",
  "  Damnation for others brewing--",
  "Though their paper seemed to shrink, from the heat of their ink,",
  "  They were only _coolly_ reviewing!",
  "And as one of them wrote down the pronoun \"_We_,\"",
  "  \"That Plural\"--says Satan--\"means _him_ and _me_,",
  "With the Editor added to make up the three",
  "Of an Athanasian Trinity,",
  "And render the believers in our 'Articles' sensible,",
  "How many must combine to form _one_ Incomprehensible\"!",
  ""
]