module.exports = [
  "Sir William Wallace of Ellerslie,",
  "I'm told he went to the High School in Dundee,",
  "For to learn to read and write,",
  "And after that he learned to fight,",
  "While at the High School in Dundee,",
  "The Provost's son with him disagree,",
  "Because Wallace did wear a dirk,",
  "He despised him like an ignorant stirk,",
  "Which with indignation he keenly felt,",
  "And told him it would become him better in his belt.",
  "",
  "Then Wallace's blood began to boil,",
  "Just like the serpent in its coil,",
  "Before it leaps upon its prey;",
  "And unto him he thus did say:",
  "'Proud saucy cur, come cease your prate,",
  "for no longer shall i wait,",
  "For to hear you insult me,",
  "At the High School in Dundee;",
  "For such insolence makes my heart to smart,",
  "And I'll plunge my dagger in you heart,'",
  "",
  "Then his heart's blood did quickly flow,",
  "And poor Wallace did not know where to go;",
  "And he stood by him until dead.",
  "Then far from him he quickly fled,",
  "Lamenting greatly the deed he had done,",
  "the murdering of the Provost's son.",
  "",
  "The scene shifts to where he was fishing on day,",
  "Where three English soldiers met him by the way,",
  "And they asked him fo give them some fish,",
  "And from them they would make a delicious dish,",
  "then Wallace gave them share of his fish,",
  "For to satisfy their wish;",
  "But they seemed dissatisfied with the share they got,",
  "So they were resolved to have all the lot.",
  "",
  "Then Wallace he thought it was time to look out,",
  "When they were resolved to have all his trout;",
  "So he swung his fishing-rod with great force round his head,",
  "And struck on of them a blow that killed him dead;",
  "So he instantly seized the fallen man's sword,",
  "And the other two fled without uttering a word.",
  "",
  "Sir William Wallace of Ellerslie,",
  "You were a warrior of great renown,",
  "And might have worn Scotland's crown;",
  "Had it not been for Monteith, the base traitor knave,",
  "That brought you to a premature grave;",
  "Yes! you were sold for English gold,",
  "And brought like a sheep from the fold,",
  "To die upon a shameful scaffold high,",
  "Amidst the derisive shouts of your enemies standing by.",
  "",
  "But you met your doom like a warrior bold,",
  "Bidding defiance to them that had you sold,",
  "And bared your neck for the headsman's stroke;",
  "And cried, 'Marion, dear, my heart is broke;",
  "My lovely dear I come to thee,",
  "Oh! I am longing thee to see!'",
  "But the headsman was as stolid as the rock,",
  "And the axe fell heavily on the block,",
  "And the scaffold did shake with the terrible shock,",
  "As the body of noble Wallace fell,",
  "Who had fought for Scotland so well.",
  ""
]