module.exports = [
  "THE PROLOGUE.",
  "",
  "THE Cook of London, while the Reeve thus spake,",
  "For joy he laugh'd and clapp'd him on the back:",
  "\"Aha!\" quoth he, \"for Christes passion,",
  "This Miller had a sharp conclusion,",
  "Upon this argument of herbergage.",
  "Well saide Solomon in his language,",
  "Bring thou not every man into thine house,",
  "For harbouring by night is perilous.",
  "Well ought a man avised for to be",
  "Whom that he brought into his privity.",
  "I pray to God to give me sorrow and care",
  "If ever, since I highte Hodge of Ware,",
  "Heard I a miller better set a-work;",
  "He had a jape of malice in the derk.",
  "But God forbid that we should stinte here,",
  "And therefore if ye will vouchsafe to hear",
  "A tale of me, that am a poore man,",
  "I will you tell as well as e'er I can",
  "A little jape that fell in our city.\"",
  "",
  "Our Host answer'd and said; \"I grant it thee.",
  "Roger, tell on; and look that it be good,",
  "For many a pasty hast thou letten blood,",
  "And many a Jack of Dover hast thou sold,",
  "That had been twice hot and twice cold.",
  "Of many a pilgrim hast thou Christe's curse,",
  "For of thy parsley yet fare they the worse.",
  "That they have eaten in thy stubble goose:",
  "For in thy shop doth many a fly go loose.",
  "Now tell on, gentle Roger, by thy name,",
  "But yet I pray thee be not wroth for game;",
  "A man may say full sooth in game and play.\"",
  "\"Thou sayst full sooth,\" quoth Roger, \"by my fay;",
  "But sooth play quad play, as the Fleming saith,",
  "And therefore, Harry Bailly, by thy faith,",
  "Be thou not wroth, else we departe here,",
  "Though that my tale be of an hostelere.",
  "But natheless, I will not tell it yet,",
  "But ere we part, y-wis thou shalt be quit.\"",
  "And therewithal he laugh'd and made cheer,",
  "And told his tale, as ye shall after hear.",
  "",
  "THE TALE.",
  "",
  "A prentice whilom dwelt in our city,",
  "And of a craft of victuallers was he:",
  "Galliard he was, as goldfinch in the shaw,",
  "Brown as a berry, a proper short fellaw:",
  "With lockes black, combed full fetisly.",
  "And dance he could so well and jollily,",
  "That he was called Perkin Revellour.",
  "He was as full of love and paramour,",
  "As is the honeycomb of honey sweet;",
  "Well was the wenche that with him might meet.",
  "At every bridal would he sing and hop;",
  "He better lov'd the tavern than the shop.",
  "For when there any riding was in Cheap,",
  "Out of the shoppe thither would he leap,",
  "And, till that he had all the sight y-seen,",
  "And danced well, he would not come again;",
  "And gather'd him a meinie of his sort,",
  "To hop and sing, and make such disport:",
  "And there they sette steven for to meet",
  "To playen at the dice in such a street.",
  "For in the towne was there no prentice",
  "That fairer coulde cast a pair of dice",
  "Than Perkin could; and thereto he was free",
  "Of his dispence, in place of privity.",
  "That found his master well in his chaffare,",
  "For oftentime he found his box full bare.",
  "For, soothely, a prentice revellour,",
  "That haunteth dice, riot, and paramour,",
  "His master shall it in his shop abie,",
  "All have he no part of the minstrelsy.",
  "For theft and riot they be convertible,",
  "All can they play on gitern or ribible.",
  "Revel and truth, as in a low degree,",
  "They be full wroth all day, as men may see.",
  "",
  "This jolly prentice with his master bode,",
  "Till he was nigh out of his prenticehood,",
  "All were he snubbed both early and late,",
  "And sometimes led with revel to Newgate.",
  "But at the last his master him bethought,",
  "Upon a day when he his paper sought,",
  "Of a proverb, that saith this same word;",
  "Better is rotten apple out of hoard,",
  "Than that it should rot all the remenant:",
  "So fares it by a riotous servant;",
  "It is well lesse harm to let him pace,",
  "Than he shend all the servants in the place.",
  "Therefore his master gave him a quittance,",
  "And bade him go, with sorrow and mischance.",
  "And thus this jolly prentice had his leve:",
  "Now let him riot all the night, or leave.",
  "And, for there is no thief without a louke,",
  "That helpeth him to wasten and to souk",
  "Of that he bribe can, or borrow may,",
  "Anon he sent his bed and his array",
  "Unto a compere of his owen sort,",
  "That loved dice, and riot, and disport;",
  "And had a wife, that held for countenance",
  "A shop, and swived for her sustenance.",
  ""
]