module.exports = [
  "Sit still­ a word­ a breath may break",
  "(As light airs stir a sleeping lake,)",
  "The glassy calm that soothes my woes,",
  "The sweet, the deep, the full repose.",
  "O leave me not ! for ever be",
  "Thus, more than life itself to me !",
  "",
  "Yes, close beside thee, let me kneel­",
  "Give me thy hand that I may feel",
  "The friend so true­so tried­so dear,",
  "My heart's own chosen­indeed is near;",
  "And check me not­this hour divine",
  "Belongs to me­is fully mine.",
  "",
  "'Tis thy own hearth thou sitt'st beside,",
  "After long absence­wandering wide;",
  "'Tis thy own wife reads in thine eyes,",
  "A promise clear of stormless skies,",
  "For faith and true love light the rays,",
  "Which shine responsive to her gaze.",
  "",
  "Aye,­well that single tear may fall;",
  "Ten thousand might mine eyes recall,",
  "Which from their lids, ran blinding fast,",
  "In hours of grief, yet scarcely past,",
  "Well may'st thou speak of love to me;",
  "For, oh ! most truly­I love thee !",
  "",
  "Yet smile­for we are happy now.",
  "Whence, then, that sadness on thy brow ?",
  "What say'st thou ? \" We must once again,",
  "Ere long, be severed by the main ? \"",
  "I knew not this­I deemed no more,",
  "Thy step would err from Britain's shore.",
  "",
  "\" Duty commands ?\" 'Tis true­'tis just;",
  "Thy slightest word I wholly trust,",
  "Nor by request, nor faintest sigh",
  "Would I, to turn thy purpose, try;",
  "But, William­hear my solemn vow­",
  "Hear and confirm !­with thee I go.",
  "",
  "\" Distance and suffering,\" did'st thou say ?",
  "\" Danger by night, and toil by day ?\"",
  "Oh, idle words, and vain are these;",
  "Hear me ! I cross with thee the seas.",
  "Such risk as thou must meet and dare,",
  "I­thy true wife­will duly share.",
  "",
  "Passive, at home, I will not pine;",
  "Thy toils­thy perils, shall be mine;",
  "Grant this­and be hereafter paid",
  "By a warm heart's devoted aid:",
  "'Tis granted­with that yielding kiss,",
  "Entered my soul unmingled bliss.",
  "",
  "Thanks, William­thanks ! thy love has joy,",
  "Pure­undefiled with base alloy;",
  "'Tis not a passion, false and blind,",
  "Inspires, enchains, absorbs my mind;",
  "Worthy, I feel, art thou to be",
  "Loved with my perfect energy.",
  "",
  "This evening, now, shall sweetly flow,",
  "Lit by our clear fire's happy glow;",
  "And parting's peace-embittering fear,",
  "Is warned, our hearts to come not near;",
  "For fate admits my soul's decree,",
  "In bliss or bale­to go with thee !",
  ""
]