module.exports = [
  "THE PROLOGUE.",
  "",
  "\"Ho!\" quoth the Knight, \"good sir, no more of this;",
  "That ye have said is right enough, y-wis,",
  "And muche more; for little heaviness",
  "Is right enough to muche folk, I guess.",
  "I say for me, it is a great disease,",
  "Where as men have been in great wealth and ease,",
  "To hearen of their sudden fall, alas!",
  "And the contrary is joy and great solas,",
  "As when a man hath been in poor estate,",
  "And climbeth up, and waxeth fortunate,",
  "And there abideth in prosperity;",
  "Such thing is gladsome, as it thinketh me,",
  "And of such thing were goodly for to tell.\"",
  "",
  "\"Yea,\" quoth our Hoste, \"by Saint Paule's bell.",
  "Ye say right sooth; this monk hath clapped loud;",
  "He spake how Fortune cover'd with a cloud",
  "I wot not what, and als' of a tragedy",
  "Right now ye heard: and pardie no remedy",
  "It is for to bewaile, nor complain",
  "That that is done, and also it is pain,",
  "As ye have said, to hear of heaviness.",
  "Sir Monk, no more of this, so God you bless;",
  "Your tale annoyeth all this company;",
  "Such talking is not worth a butterfly,",
  "For therein is there no sport nor game;",
  "Therefore, Sir Monke, Dan Piers by your name,",
  "I pray you heart'ly, tell us somewhat else,",
  "For sickerly, n'ere clinking of your bells,",
  "That on your bridle hang on every side,",
  "By heaven's king, that for us alle died,",
  "I should ere this have fallen down for sleep,",
  "Although the slough had been never so deep;",
  "Then had your tale been all told in vain.",
  "For certainly, as these clerkes sayn,",
  "Where as a man may have no audience,",
  "Nought helpeth it to telle his sentence.",
  "And well I wot the substance is in me,",
  "If anything shall well reported be.",
  "Sir, say somewhat of hunting,  I you pray.\"",
  "",
  "\"Nay,\" quoth the Monk, \"I have no lust to play;",
  "Now let another tell, as I have told.\"",
  "Then spake our Host with rude speech and bold,",
  "And said unto the Nunne's Priest anon,",
  "\"Come near, thou Priest, come hither, thou Sir John,",
  "Tell us such thing as may our heartes glade.",
  "Be blithe, although thou ride upon a jade.",
  "What though thine horse be bothe foul and lean?",
  "If he will serve thee, reck thou not a bean;",
  "Look that thine heart be merry evermo'.\"",
  "",
  "\"Yes, Host,\" quoth he, \"so may I ride or go,",
  "But I be merry, y-wis I will be blamed.\"",
  "And right anon his tale he hath attamed",
  "And thus he said unto us every one,",
  "This sweete priest, this goodly man, Sir John.",
  "",
  "THE TALE.",
  "",
  "A poor widow, somedeal y-stept in age,",
  "Was whilom dwelling in a poor cottage,",
  "Beside a grove, standing in a dale.",
  "This widow, of which I telle you my tale,",
  "Since thilke day that she was last a wife,",
  "In patience led a full simple life,",
  "For little was her chattel and her rent.",
  "By husbandry of such as God her sent,",
  "She found herself, and eke her daughters two.",
  "Three large sowes had she, and no mo';",
  "Three kine, and eke a sheep that highte Mall.",
  "Full sooty was her bow'r, and eke her hall,",
  "In which she ate full many a slender meal.",
  "Of poignant sauce knew she never a deal.",
  "No dainty morsel passed through her throat;",
  "Her diet was accordant to her cote.",
  "Repletion her made never sick;",
  "Attemper diet was all her physic,",
  "And exercise, and hearte's suffisance.",
  "The goute let her nothing for to dance,",
  "Nor apoplexy shente not her head.",
  "No wine drank she, neither white nor red:",
  "Her board was served most with white and black,",
  "Milk and brown bread, in which she found no lack,",
  "Seind bacon, and sometimes an egg or tway;",
  "For she was as it were a manner dey.",
  "A yard she had, enclosed all about",
  "With stickes, and a drye ditch without,",
  "In which she had a cock, hight Chanticleer;",
  "In all the land of crowing n'as his peer.",
  "His voice was merrier than the merry orgon,",
  "On masse days that in the churches gon.",
  "Well sickerer was his crowing in his lodge,",
  "Than is a clock, or an abbay horloge.",
  "By nature he knew each ascension",
  "Of th' equinoctial in thilke town;",
  "For when degrees fiftene were ascended,",
  "Then crew he, that it might not be amended.",
  "His comb was redder than the fine coral,",
  "Embattell'd  as it were a castle wall.",
  "His bill was black, and as the jet it shone;",
  "Like azure were his legges and his tone;",
  "His nailes whiter than the lily flow'r,",
  "And like the burnish'd gold was his colour,",
  "This gentle cock had in his governance",
  "Sev'n hennes, for to do all his pleasance,",
  "Which were his sisters and his paramours,",
  "And wondrous like to him as of colours.",
  "Of which the fairest-hued in the throat",
  "Was called Damoselle Partelote,",
  "Courteous she was, discreet, and debonair,",
  "And companiable, and bare herself so fair,",
  "Since the day that she sev'n night was old,",
  "That truely she had the heart in hold",
  "Of Chanticleer, locked in every lith;",
  "He lov'd her so, that well was him therewith,",
  "But such a joy it was to hear them sing,",
  "When that the brighte sunne gan to spring,",
  "In sweet accord, \"My lefe is fare in land.\"",
  "For, at that time, as I have understand,",
  "Beastes and birdes coulde speak and sing.",
  "",
  "And so befell, that in a dawening,",
  "As Chanticleer among his wives all",
  "Sat on his perche, that was in the hall,",
  "And next him sat this faire Partelote,",
  "This Chanticleer gan groanen in his throat,",
  "As man that in his dream is dretched sore,",
  "And when that Partelote thus heard him roar,",
  "She was aghast, and saide, \"Hearte dear,",
  "What aileth you to groan in this mannere?",
  "Ye be a very sleeper, fy for shame!\"",
  "And he answer'd and saide thus; \"Madame,",
  "I pray you that ye take it not agrief;",
  "By God, me mette I was in such mischief,",
  "Right now, that yet mine heart is sore affright'.",
  "Now God,\" quoth he, \"my sweven read aright",
  "And keep my body out of foul prisoun.",
  "Me mette, how that I roamed up and down",
  "Within our yard, where as I saw a beast",
  "Was like an hound, and would have made arrest",
  "Upon my body, and would have had me dead.",
  "His colour was betwixt yellow and red;",
  "And tipped was his tail, and both his ears,",
  "With black, unlike the remnant of his hairs.",
  "His snout was small, with glowing eyen tway;",
  "Yet of his look almost for fear I dey;",
  "This caused me my groaning, doubteless.\"",
  "",
  "\"Away,\"  quoth she, \"fy on you, hearteless!",
  "Alas!\" quoth she, \"for, by that God above!",
  "Now have ye lost my heart and all my love;",
  "I cannot love a coward, by my faith.",
  "For certes, what so any woman saith,",
  "We all desiren, if it mighte be,",
  "To have husbandes hardy, wise, and free,",
  "And secret, and no niggard nor no fool,",
  "Nor him that is aghast of every tool,",
  "Nor no avantour, by that God above!",
  "How durste ye for shame say to your love",
  "That anything might make you afear'd?",
  "Have ye no manne's heart, and have a beard?",
  "Alas! and can ye be aghast of swevenes?",
  "Nothing but vanity, God wot, in sweven is,",
  "Swevens engender of repletions,",
  "And oft of fume, and of complexions,",
  "When humours be too abundant in a wight.",
  "Certes this dream, which ye have mette tonight,",
  "Cometh of the great supefluity",
  "Of youre rede cholera, pardie,",
  "Which causeth folk to dreaden in their dreams",
  "Of arrows, and of fire with redde beams,",
  "Of redde beastes, that they will them bite,",
  "Of conteke, and of whelpes great and lite;",
  "Right as the humour of melancholy",
  "Causeth full many a man in sleep to cry,",
  "For fear of bulles, or of beares blake,",
  "Or elles that black devils will them take,",
  "Of other humours could I tell also,",
  "That worke many a man in sleep much woe;",
  "That I will pass as lightly as I can.",
  "Lo, Cato, which that was so wise a man,",
  "",
  "Now, Sir,\" quoth she, \"when we fly from these beams,",
  "For Godde's love, as take some laxatife;",
  "On peril of my soul, and of my life,",
  "I counsel you the best, I will not lie,",
  "That both of choler, and melancholy,",
  "Ye purge you; and, for ye shall not tarry,",
  "Though in this town is no apothecary,",
  "I shall myself two herbes teache you,",
  "That shall be for your health, and for your prow;",
  "And in our yard the herbes shall I find,",
  "The which have of their property by kind",
  "To purge you beneath, and eke above.",
  "Sire, forget not this for Godde's love;",
  "Ye be full choleric of complexion;",
  "Ware that the sun, in his ascension,",
  "You finde not replete of humours hot;",
  "And if it do, I dare well lay a groat,",
  "That ye shall have a fever tertiane,",
  "Or else an ague, that may be your bane,",
  "A day or two ye shall have digestives",
  "Of wormes, ere ye take your laxatives,",
  "Of laurel, centaury,  and fumeterere,",
  "Or else of elder-berry, that groweth there,",
  "Of catapuce,  or of the gaitre-berries,",
  "Or herb ivy growing in our yard, that merry is:",
  "Pick them right as they grow, and eat them in,",
  "Be merry, husband, for your father's kin;",
  "Dreade no dream; I can say you no more.\"",
  "",
  "\"Madame,\" quoth he, \"grand mercy of your lore,",
  "But natheless, as touching Dan Catoun,",
  "That hath of wisdom such a great renown,",
  "Though that he bade no dreames for to dread,",
  "By God, men may in olde bookes read",
  "Of many a man more of authority",
  "Than ever Cato was, so may I the,",
  "That all the reverse say of his sentence,",
  "And have well founden by experience",
  "That dreames be significations",
  "As well of joy, as tribulations",
  "That folk enduren in this life present.",
  "There needeth make of this no argument;",
  "The very preve sheweth it indeed.",
  "One of the greatest authors that men read",
  "Saith thus, that whilom two fellowes went",
  "On pilgrimage in a full good intent;",
  "And happen'd so, they came into a town",
  "Where there was such a congregatioun",
  "Of people, and eke so strait of herbergage,",
  "That they found not as much as one cottage",
  "In which they bothe might y-lodged be:",
  "Wherefore they musten of necessity,",
  "As for that night, departe company;",
  "And each of them went to his hostelry,",
  "And took his lodging as it woulde fall.",
  "The one of them was lodged in a stall,",
  "Far in a yard, with oxen of the plough;",
  "That other man was lodged well enow,",
  "As was his aventure, or his fortune,",
  "That us governeth all, as in commune.",
  "And so befell, that, long ere it were day,",
  "This man mette in his bed, there: as he lay,",
  "How that his fellow gan upon him call,",
  "And said, 'Alas! for in an ox's stall",
  "This night shall I be murder'd, where I lie",
  "Now help me, deare brother, or I die;",
  "In alle haste come to me,' he said.",
  "This man out of his sleep for fear abraid;",
  "But when that he was wak'd out of his sleep,",
  "He turned him, and took of this no keep;",
  "He thought his dream was but a vanity.",
  "Thus twies in his sleeping dreamed he,",
  "And at the thirde time yet his fellaw again",
  "Came, as he thought, and said, 'I am now slaw;",
  "Behold my bloody woundes, deep and wide.",
  "Arise up early, in the morning, tide,",
  "And at the west gate of the town,' quoth he,",
  "'A carte full of dung there shalt: thou see,",
  "In which my body is hid privily.",
  "Do thilke cart arroste boldely.",
  "My gold caused my murder, sooth to sayn.'",
  "And told him every point how he was slain,",
  "With a full piteous face, and pale of hue.",
  "",
  "\"And, truste well, his dream he found full true;",
  "For on the morrow, as soon as it was day,",
  "To his fellowes inn he took his way;",
  "And when that he came to this ox's stall,",
  "After his fellow he began to call.",
  "The hostelere answered him anon,",
  "And saide, 'Sir, your fellow is y-gone,",
  "As soon as day he went out of the town.'",
  "This man gan fallen in suspicioun,",
  "Rememb'ring on his dreames that he mette,",
  "And forth he went, no longer would he let,",
  "Unto the west gate of the town, and fand",
  "A dung cart, as it went for to dung land,",
  "That was arrayed in the same wise",
  "As ye have heard the deade man devise;",
  "And with an hardy heart he gan to cry,",
  "'Vengeance and justice of this felony:",
  "My fellow murder'd in this same night",
  "And in this cart he lies, gaping upright.",
  "I cry out on the ministers,' quoth he.",
  "'That shoulde keep and rule this city;",
  "Harow! alas! here lies my fellow slain.'",
  "What should I more unto this tale sayn?",
  "The people out start, and cast the cart to ground",
  "And in the middle of the dung they found",
  "The deade man, that murder'd was all new.",
  "O blissful God! that art so good and true,",
  "Lo, how that thou bewray'st murder alway.",
  "Murder will out, that see we day by day.",
  "Murder is so wlatsom and abominable",
  "To God, that is so just and reasonable,",
  "That he will not suffer it heled be;",
  "Though it abide a year, or two, or three,",
  "Murder will out, this is my conclusioun,",
  "And right anon, the ministers of the town",
  "Have hent the carter, and so sore him pined,",
  "And eke the hostelere so sore engined,",
  "That they beknew their wickedness anon,",
  "And were hanged by the necke bone.",
  "",
  "\"Here may ye see that dreames be to dread.",
  "And certes in the same book I read,",
  "Right in the nexte chapter after this",
  "(I gabbe not, so have I joy and bliss),",
  "Two men that would, have passed over sea,",
  "For certain cause, into a far country,",
  "If that the wind not hadde been contrary,",
  "That made them in a city for to tarry,",
  "That stood full merry upon an haven side;",
  "But on a day, against the even-tide,",
  "The wind gan change, and blew right as them lest.",
  "Jolly and glad they wente to their rest,",
  "And caste them full early for to sail.",
  "But to the one man fell a great marvail",
  "That one of them, in sleeping as he lay,",
  "He mette a wondrous dream, against the day:",
  "He thought a man stood by his bedde's side,",
  "And him commanded that he should abide;",
  "And said him thus; 'If thou to-morrow wend,",
  "Thou shalt be drown'd; my tale is at an end.'",
  "He woke, and told his follow what he mette,",
  "And prayed him his voyage for to let;",
  "As for that day, he pray'd him to abide.",
  "His fellow, that lay by his bedde's side,",
  "Gan for to laugh, and scorned him full fast.",
  "'No dream,' quoth he,'may so my heart aghast,",
  "That I will lette for to do my things.",
  "I sette not a straw by thy dreamings,",
  "For swevens be but vanities and japes.",
  "Men dream all day of owles and of apes,",
  "And eke of many a maze therewithal;",
  "Men dream of thing that never was, nor shall.",
  "But since I see, that thou wilt here abide,",
  "And thus forslothe wilfully thy tide,",
  "God wot, it rueth me; and have good day.'",
  "And thus he took his leave, and went his way.",
  "But, ere that he had half his course sail'd,",
  "I know not why, nor what mischance it ail'd,",
  "But casually the ship's bottom rent,",
  "And ship and man under the water went,",
  "In sight of other shippes there beside",
  "That with him sailed at the same tide.",
  "",
  "\"And therefore, faire Partelote so dear,",
  "By such examples olde may'st thou lear,",
  "That no man shoulde be too reckeless",
  "Of dreames, for I say thee doubteless,",
  "That many a dream full sore is for to dread.",
  "Lo, in the life of Saint Kenelm  I read,",
  "That was Kenulphus' son, the noble king",
  "Of Mercenrike,  how Kenelm mette a thing.",
  "A little ere he was murder'd on a day,",
  "His murder in his vision he say.",
  "His norice him expounded every deal",
  "His sweven, and bade him to keep him well",
  "For treason; but he was but seven years old,",
  "And therefore little tale hath he told",
  "Of any dream, so holy was his heart.",
  "By God, I hadde lever than my shirt",
  "That ye had read his legend, as have I.",
  "Dame Partelote, I say you truely,",
  "Macrobius, that wrote the vision",
  "In Afric' of the worthy Scipion,",
  "Affirmeth dreames, and saith that they be",
  "'Warnings of thinges that men after see.",
  "And furthermore, I pray you looke well",
  "In the Old Testament, of Daniel,",
  "If he held dreames any vanity.",
  "Read eke of Joseph, and there shall ye see",
  "Whether dreams be sometimes (I say not all)",
  "Warnings of thinges that shall after fall.",
  "Look of Egypt the king, Dan Pharaoh,",
  "His baker and his buteler also,",
  "Whether they felte none effect in dreams.",
  "Whoso will seek the acts of sundry remes",
  "May read of dreames many a wondrous thing.",
  "Lo Croesus, which that was of Lydia king,",
  "Mette he not that he sat upon a tree,",
  "Which signified he shoulde hanged be?",
  "Lo here, Andromache, Hectore's wife,",
  "That day that Hector shoulde lose his life,",
  "She dreamed on the same night beforn,",
  "How that the life of Hector should be lorn,",
  "If thilke day he went into battaile;",
  "She warned him, but it might not avail;",
  "He wente forth to fighte natheless,",
  "And was y-slain anon of Achilles.",
  "But thilke tale is all too long to tell;",
  "And eke it is nigh day, I may not dwell.",
  "Shortly I say, as for conclusion,",
  "That I shall have of this avision",
  "Adversity; and I say furthermore,",
  "That I ne tell of laxatives no store,",
  "For they be venomous, I wot it well;",
  "I them defy, I love them never a del.",
  "",
  "\"But let us speak of mirth, and stint all this;",
  "Madame Partelote, so have I bliss,",
  "Of one thing God hath sent me large grace;",
  "For when I see the beauty of your face,",
  "Ye be so scarlet-hued about your eyen,",
  "I maketh all my dreade for to dien,",
  "For, all so sicker as In principio,",
  "Mulier est hominis confusio.",
  "Madam, the sentence of of this Latin is,",
  "Woman is manne's joy and manne's bliss.",
  "For when I feel at night your softe side, --",
  "Albeit that I may not on you ride,",
  "For that our perch is made so narrow, Alas!",
  "I am so full of joy and of solas,",
  "That I defy both sweven and eke dream.\"",
  "And with that word he flew down from the beam,",
  "For it was day, and eke his hennes all;",
  "And with a chuck he gan them for to call,",
  "For he had found a corn, lay in the yard.",
  "Royal he was, he was no more afear'd;",
  "He feather'd Partelote twenty time,",
  "And as oft trode her, ere that it was prime.",
  "He looked as it were a grim lion,",
  "And on his toes he roamed up and down;",
  "He deigned not to set his feet to ground;",
  "He chucked, when he had a corn y-found,",
  "And to him ranne then his wives all.",
  "Thus royal, as a prince is in his hall,",
  "Leave I this Chanticleer in his pasture;",
  "And after will I tell his aventure.",
  "",
  "When that the month in which the world began,",
  "That highte March, when God first maked man,",
  "Was complete, and y-passed were also,",
  "Since March ended, thirty days and two,",
  "Befell that Chanticleer in all his pride,",
  "His seven wives walking him beside,",
  "Cast up his eyen to the brighte sun,",
  "That in the sign of Taurus had y-run",
  "Twenty degrees and one, and somewhat more;",
  "He knew by kind, and by none other lore,",
  "That it was prime, and crew with blissful steven.",
  "\"The sun,\" he said, \"is clomben up in heaven",
  "Twenty degrees and one, and more y-wis.",
  "Madame Partelote, my worlde's bliss,",
  "Hearken these blissful birdes how they sing,",
  "And see the freshe flowers how they spring;",
  "Full is mine heart of revel and solace.\"",
  "But suddenly him fell a sorrowful case;",
  "For ever the latter end of joy is woe:",
  "God wot that worldly joy is soon y-go:",
  "And, if a rhetor coulde fair indite,",
  "He in a chronicle might it safely write,",
  "As for a sov'reign notability",
  "Now every wise man, let him hearken me;",
  "This story is all as true, I undertake,",
  "As is the book of Launcelot du Lake,",
  "That women hold in full great reverence.",
  "Now will I turn again to my sentence.",
  "",
  "A col-fox,  full of sly iniquity,",
  "That in the grove had wonned yeares three,",
  "By high imagination forecast,",
  "The same night thorough the hedges brast",
  "Into the yard, where Chanticleer the fair",
  "Was wont, and eke his wives, to repair;",
  "And in a bed of wortes still he lay,",
  "Till it was passed undern  of the day,",
  "Waiting his time on Chanticleer to fall:",
  "As gladly do these homicides all,",
  "That in awaite lie to murder men.",
  "O false murd'rer! Rouking in thy den!",
  "O new Iscariot, new Ganilion!",
  "O false dissimuler, O Greek Sinon,",
  "That broughtest Troy all utterly to sorrow!",
  "O Chanticleer! accursed be the morrow",
  "That thou into thy yard flew from the beams;",
  "Thou wert full well y-warned by thy dreams",
  "That thilke day was perilous to thee.",
  "But what that God forewot must needes be,",
  "After th' opinion of certain clerkes.",
  "Witness on him that any perfect clerk is,",
  "That in school is great altercation",
  "In this matter, and great disputation,",
  "And hath been of an hundred thousand men.",
  "But I ne cannot boult it to the bren,",
  "As can the holy doctor Augustine,",
  "Or Boece, or the bishop Bradwardine,",
  "Whether that Godde's worthy foreweeting",
  "Straineth me needly for to do a thing",
  "(Needly call I simple necessity),",
  "Or elles if free choice be granted me",
  "To do that same thing, or do it not,",
  "Though God forewot it ere that it was wrought;",
  "Or if his weeting straineth never a deal,",
  "But by necessity conditionel.",
  "I will not have to do of such mattere;",
  "My tale is of a cock, as ye may hear,",
  "That took his counsel of his wife, with sorrow,",
  "To walken in the yard upon the morrow",
  "That he had mette the dream, as I you told.",
  "Womane's counsels be full often cold;",
  "Womane's counsel brought us first to woe,",
  "And made Adam from Paradise to go,",
  "There as he was full merry and well at case.",
  "But, for I n'ot to whom I might displease",
  "If I counsel of women woulde blame,",
  "Pass over, for I said it in my game.",
  "Read authors, where they treat of such mattere",
  "And what they say of women ye may hear.",
  "These be the cocke's wordes, and not mine;",
  "I can no harm of no woman divine.",
  "Fair in the sand, to bathe her merrily,",
  "Lies Partelote, and all her sisters by,",
  "Against the sun, and Chanticleer so free",
  "Sang merrier than the mermaid in the sea;",
  "For Physiologus saith sickerly,",
  "How that they singe well and merrily.",
  "And so befell that, as he cast his eye",
  "Among the wortes, on a butterfly,",
  "He was ware of this fox that lay full low.",
  "Nothing ne list him thenne for to crow,",
  "But cried anon \"Cock! cock!\" and up he start,",
  "As man that was affrayed in his heart.",
  "For naturally a beast desireth flee",
  "From his contrary, if be may it see,",
  "Though he ne'er erst had soon it with his eye",
  "This Chanticleer, when he gan him espy,",
  "He would have fled, but that the fox anon",
  "Said, \"Gentle Sir, alas! why will ye gon?",
  "Be ye afraid of me that am your friend?",
  "Now, certes, I were worse than any fiend,",
  "If I to you would harm or villainy.",
  "I am not come your counsel to espy.",
  "But truely the cause of my coming",
  "Was only for to hearken how ye sing;",
  "For truely ye have as merry a steven,",
  "As any angel hath that is in heaven;",
  "Therewith ye have of music more feeling,",
  "Than had Boece, or any that can sing.",
  "My lord your father (God his soule bless)",
  "And eke your mother of her gentleness,",
  "Have in mnine house been, to my great ease:",
  "And certes, Sir, full fain would I you please.",
  "But, for men speak of singing, I will say,",
  "So may I brooke well mine eyen tway,",
  "Save you, I hearde never man so sing",
  "As did your father in the morrowning.",
  "Certes it was of heart all that he sung.",
  "And, for to make his voice the more strong,",
  "He would so pain him, that with both his eyen",
  "He muste wink, so loud he woulde cryen,",
  "And standen on his tiptoes therewithal,",
  "And stretche forth his necke long and small.",
  "And eke he was of such discretion,",
  "That there was no man, in no region,",
  "That him in song or wisdom mighte pass.",
  "I have well read in Dan Burnel the Ass,",
  "Among his verse, how that there was a cock",
  "That, for a prieste's son gave him a knock",
  "Upon his leg, while he was young and nice,",
  "He made him for to lose his benefice.",
  "But certain there is no comparison",
  "Betwixt the wisdom and discretion",
  "Of youre father, and his subtilty.",
  "Now singe, Sir, for sainte charity,",
  "Let see, can ye your father counterfeit?\"",
  "",
  "This Chanticleer his wings began to beat,",
  "As man that could not his treason espy,",
  "So was he ravish'd with his flattery.",
  "Alas! ye lordes, many a false flattour",
  "Is in your court, and many a losengeour,",
  "That please you well more, by my faith,",
  "Than he that soothfastness unto you saith.",
  "Read in Ecclesiast' of flattery;",
  "Beware, ye lordes, of their treachery.",
  "This Chanticleer stood high upon his toes,",
  "Stretching his neck, and held his eyen close,",
  "And gan to crowe loude for the nonce",
  "And Dan Russel  the fox start up at once,",
  "And by the gorge hente Chanticleer,",
  "And on his back toward the wood him bare.",
  "For yet was there no man that him pursu'd.",
  "O destiny, that may'st not be eschew'd!",
  "Alas, that Chanticleer flew from the beams!",
  "Alas, his wife raughte nought of dreams!",
  "And on a Friday fell all this mischance.",
  "O Venus, that art goddess of pleasance,",
  "Since that thy servant was this Chanticleer",
  "And in thy service did all his powere,",
  "More for delight, than the world to multiply,",
  "Why wilt thou suffer him on thy day to die?",
  "O Gaufrid, deare master sovereign,",
  "That, when thy worthy king Richard was slain",
  "With shot, complainedest his death so sore,",
  "Why n'had I now thy sentence and thy lore,",
  "The Friday for to chiden, as did ye?",
  "(For on a Friday, soothly, slain was he),",
  "Then would I shew you how that I could plain",
  "For Chanticleere's dread, and for his pain.",
  "",
  "Certes such cry nor lamentation",
  "Was ne'er of ladies made, when Ilion",
  "Was won, and Pyrrhus with his straighte sword,",
  "When he had hent king Priam by the beard,",
  "And slain him (as saith us Eneidos),",
  "As maden all the hennes in the close,",
  "When they had seen of Chanticleer the sight.",
  "But sov'reignly Dame Partelote shright,",
  "Full louder than did Hasdrubale's wife,",
  "When that her husband hadde lost his life,",
  "And that the Romans had y-burnt Carthage;",
  "She was so full of torment and of rage,",
  "That wilfully into the fire she start,",
  "And burnt herselfe with a steadfast heart.",
  "O woeful hennes! right so cried ye,",
  "As, when that Nero burned the city",
  "Of Rome, cried the senatores' wives,",
  "For that their husbands losten all their lives;",
  "Withoute guilt this Nero hath them slain.",
  "Now will I turn unto my tale again;",
  "",
  "The sely widow, and her daughters two,",
  "Hearde these hennes cry and make woe,",
  "And at the doors out started they anon,",
  "And saw the fox toward the wood is gone,",
  "And bare upon his back the cock away:",
  "They cried, \"Out! harow! and well-away!",
  "Aha! the fox!\" and after him they ran,",
  "And eke with staves many another man",
  "Ran Coll our dog, and Talbot, and Garland;",
  "And Malkin, with her distaff in her hand",
  "Ran cow and calf, and eke the very hogges",
  "So fear'd they were for barking of the dogges,",
  "And shouting of the men and women eke.",
  "They ranne so, them thought their hearts would break.",
  "They yelled as the fiendes do in hell;",
  "The duckes cried as men would them quell;",
  "The geese for feare flewen o'er the trees,",
  "Out of the hive came the swarm of bees,",
  "So hideous was the noise, ben'dicite!",
  "Certes he, Jacke Straw, and his meinie,",
  "Ne made never shoutes half so shrill",
  "When that they woulden any Fleming kill,",
  "As thilke day was made upon the fox.",
  "Of brass they broughte beames and of box,",
  "Of horn and bone, in which they blew and pooped,",
  "And therewithal they shrieked and they hooped;",
  "It seemed as the heaven shoulde fall",
  "",
  "Now, goode men, I pray you hearken all;",
  "Lo, how Fortune turneth suddenly",
  "The hope and pride eke of her enemy.",
  "This cock, that lay upon the fox's back,",
  "In all his dread unto the fox he spake,",
  "And saide, \"Sir, if that I were as ye,",
  "Yet would I say (as wisly God help me),",
  "'Turn ye again, ye proude churles all;",
  "A very pestilence upon you fall.",
  "Now am I come unto the woode's side,",
  "Maugre your head, the cock shall here abide;",
  "I will him eat, in faith, and that anon.'\"",
  "The fox answer'd, \"In faith it shall be done:\"",
  "And, as he spake the word, all suddenly",
  "The cock brake from his mouth deliverly,",
  "And high upon a tree he flew anon.",
  "And when the fox saw that the cock was gone,",
  "\"Alas!\" quoth he, \"O Chanticleer, alas!",
  "I have,\" quoth he, \"y-done to you trespass,",
  "Inasmuch as I maked you afear'd,",
  "When I you hent, and brought out of your yard;",
  "But, Sir, I did it in no wick' intent;",
  "Come down, and I shall tell you what I meant.",
  "I shall say sooth to you, God help me so.\"",
  "\"Nay then,\" quoth he, \"I shrew us both the two,",
  "And first I shrew myself, both blood and bones,",
  "If thou beguile me oftener than once.",
  "Thou shalt no more through thy flattery",
  "Do me to sing and winke with mine eye;",
  "For he that winketh when he shoulde see,",
  "All wilfully, God let him never the.\"",
  "\"Nay,\" quoth the fox; \"but God give him mischance",
  "That is so indiscreet of governance,",
  "That jangleth when that he should hold his peace.\"",
  "",
  "Lo, what it is for to be reckeless",
  "And negligent, and trust on flattery.",
  "But ye that holde this tale a folly,",
  "As of a fox, or of a cock or hen,",
  "Take the morality thereof, good men.",
  "For Saint Paul saith, That all that written is,",
  "To our doctrine it written is y-wis.",
  "Take the fruit, and let the chaff be still.",
  "",
  "Now goode God, if that it be thy will,",
  "As saith my Lord,  so make us all good men;",
  "And bring us all to thy high bliss. Amen.",
  "",
  "THE EPILOGUE",
  "",
  "\"Sir Nunne's Priest,\" our hoste said anon,",
  "\"Y-blessed be thy breech, and every stone;",
  "This was a merry tale of Chanticleer.",
  "But by my truth, if thou wert seculere,",
  "Thou wouldest be a treadefowl aright;",
  "For if thou have courage as thou hast might,",
  "Thee were need of hennes, as I ween,",
  "Yea more than seven times seventeen.",
  "See, whate brawnes hath this gentle priest,",
  "So great a neck, and such a large breast",
  "He looketh as a sperhawk with his eyen",
  "Him needeth not his colour for to dyen",
  "With Brazil, nor with grain of Portugale.",
  "But, Sir, faire fall you for your tale'.\"",
  "And, after that, he with full merry cheer",
  "Said to another, as ye shall hear.",
  ""
]