module.exports = [
  "Stopt by the storm, that long in sullen black",
  "From the south-west stained its encroaching track,",
  "Haymakers, hustling from the rain to hide,",
  "Sought the grey willows by the pasture-side;",
  "And there, while big drops bow the grassy stems,",
  "And bleb the withering hay with pearly gems,",
  "Dimple the brook, and patter in the leaves,",
  "The song or tale an hour's restraint relieves.",
  "And while the old dames gossip at their ease,",
  "And pinch the snuff-box empty by degrees,",
  "The young ones join in love's delightful themes,",
  "Truths told by gipsies, and expounded dreams;",
  "And mutter things kept secrets from the rest,",
  "As sweethearts' names, and whom they love the best;",
  "And dazzling ribbons they delight to show,",
  "And last new favours of some veigling beau,",
  "Who with such treachery tries their hearts to move,",
  "And, like the highest, bribes the maidens' love.",
  "The old dames, jealous of their whispered praise,",
  "Throw in their hints of man's deluding ways;",
  "And one, to give her counsels more effect,",
  "And by example illustrate the fact",
  "Of innocence oercome by flattering man,",
  "Thrice tapped her box, and pinched, and thus began.",
  "",
  "  \"Now wenches listen, and let lovers lie,",
  "Ye'll hear a story ye may profit by;",
  "I'm your age treble, with some oddments to't,",
  "And right from wrong can tell, if ye'll but do't:",
  "Ye need not giggle underneath your hat,",
  "Mine's no joke-matter, let me tell you that;",
  "So keep ye quiet till my story's told,",
  "And don't despise your betters cause they're old.",
  "",
  "  \"That grave ye've heard of, where the four roads meet,",
  "Where walks the spirit in a winding-sheet,",
  "Oft seen at night, by strangers passing late,",
  "And tarrying neighbours that at market wait,",
  "Stalking along as white as driven snow,",
  "And long as one's shadow when the sun is low;",
  "The girl that's buried there I knew her well,",
  "And her whole history, if ye'll hark, can tell.",
  "Her name was Jane, and neighbour's children we,",
  "And old companions once, as ye may be;",
  "And like to you, on Sundays often strolled",
  "To gipsies' camps to have our fortunes told;",
  "And oft, God rest her, in the fortune-book",
  "Which we at hay-time in our pockets took,",
  "Our pins at blindfold on the wheel we stuck,",
  "When hers would always prick the worst of luck;",
  "For try, poor thing, as often as she might,",
  "Her point would always on the blank alight;",
  "Which plainly shows the fortune one's to have,",
  "As such like go unwedded to the grave,--",
  "And so it proved.--The next succeeding May,",
  "We both to service went from sports and play,",
  "Though in the village still; as friends and kin",
  "Thought neighbour's service better to begin.",
  "So out we went:--Jane's place was reckoned good,",
  "Though she bout life but little understood,",
  "And had a master wild as wild can be,",
  "And far unfit for such a child as she;",
  "And soon the whisper went about the town,",
  "That Jane's good looks procured her many a gown",
  "From him, whose promise was to every one,",
  "But whose intention was to wive with none.",
  "Twas nought to wonder, though begun by guess;",
  "For Jane was lovely in her Sunday dress,",
  "And all expected such a rosy face",
  "Would be her ruin--as was just the case.",
  "The while the change was easily perceived,",
  "Some months went by, ere I the tales believed;",
  "For there are people nowadays, Lord knows,",
  "Will sooner hatch up lies than mend their clothes;",
  "And when with such-like tattle they begin,",
  "Don't mind whose character they spoil a pin:",
  "But passing neighbours often marked them smile,",
  "And watched him take her milkpail oer a stile;",
  "And many a time, as wandering closer by,",
  "From Jenny's bosom met a heavy sigh;",
  "And often marked her, as discoursing deep,",
  "When doubts might rise to give just cause to weep,",
  "Smothering their notice, by a wished disguise",
  "To slive her apron corner to her eyes.",
  "Such signs were mournful and alarming things,",
  "And far more weighty than conjecture brings;",
  "Though foes made double what they heard of all,",
  "Swore lies as proofs, and prophesied her fall.",
  "Poor thoughtless wench! it seems but Sunday past",
  "Since we went out together for the last,",
  "And plain enough indeed it was to find",
  "She'd something more than common on her mind;",
  "For she was always fond and full of chat,",
  "In passing harmless jokes bout beaus and that,",
  "But nothing then was scarcely talked about,",
  "And what there was, I even forced it out.",
  "A gloomy wanness spoiled her rosy cheek,",
  "And doubts hung there it was not mine to seek;",
  "She neer so much as mentioned things to come,",
  "But sighed oer pleasures ere she left her home;",
  "And now and then a mournful smile would raise",
  "At freaks repeated of our younger days,",
  "Which I brought up, while passing spots of ground",
  "Where we, when children, \"hurly-burlied\" round,",
  "Or \"blindman-buffed\" some morts of hours away--",
  "Two games, poor thing, Jane dearly loved to play.",
  "She smiled at these, but shook her head and sighed",
  "When eer she thought my look was turned aside;",
  "Nor turned she round, as was her former way,",
  "To praise the thorn, white over then with May;",
  "Nor stooped once, though thousands round her grew,",
  "To pull a cowslip as she used to do:",
  "For Jane in flowers delighted from a child--",
  "I like the garden, but she loved the wild--",
  "And oft on Sundays young men's gifts declined,",
  "Posies from gardens of the sweetest kind,",
  "And eager scrambled the dog-rose to get,",
  "And woodbine-flowers at every bush she met.",
  "The cowslip blossom, with its ruddy streak,",
  "Would tempt her furlongs from the path to seek;",
  "And gay long purple, with its tufty spike,",
  "She'd wade oer shoes to reach it in the dyke;",
  "And oft, while scratching through the briary woods",
  "For tempting cuckoo-flowers and violet buds,",
  "Poor Jane, I've known her crying sneak to town,",
  "Fearing her mother, when she'd torn her gown.",
  "Ah, these were days her conscience viewed with pain,",
  "Which all are loth to lose, as well as Jane.",
  "And, what I took more odd than all the rest,",
  "Was, that same night she neer a wish exprest",
  "To see the gipsies, so beloved before,",
  "That lay a stone's throw from us on the moor:",
  "I hinted it; she just replied again--",
  "She once believed them, but had doubts since then.",
  "And when we sought our cows, I called, \"Come mull!\"",
  "But she stood silent, for her heart was full.",
  "She loved dumb things: and ere she had begun",
  "To milk, caressed them more than eer she'd done;",
  "But though her tears stood watering in her eye,",
  "I little took it as her last good-bye;",
  "For she was tender, and I've often known",
  "Her mourn when beetles have been trampled on:",
  "So I neer dreamed from this, what soon befell,",
  "Till the next morning rang her passing-bell.",
  "My story's long, but time's in plenty yet,",
  "Since the black clouds betoken nought but wet;",
  "And I'll een snatch a minute's breath or two,",
  "And take another pinch, to help me through.",
  "",
  "  \"So, as I said, next morn I heard the bell,",
  "And passing neighbours crossed the street, to tell",
  "That my poor partner Jenny had been found",
  "In the old flag-pool, on the pasture, drowned.",
  "God knows my heart! I twittered like a leaf,",
  "And found too late the cause of Sunday's grief;",
  "For every tongue was loosed to gabble oer",
  "The slanderous things that secret passed before:",
  "With truth or lies they need not then be strict,",
  "The one they railed at could not contradict.",
  "Twas now no secret of her being beguiled,",
  "For every mouth knew Jenny died with child;",
  "And though more cautious with a living name,",
  "Each more than guessed her master bore the blame.",
  "That very morning, it affects me still,",
  "Ye know the foot-path sidles down the hill,",
  "Ignorant as babe unborn I passed the pond",
  "To milk as usual in our close beyond,",
  "And cows were drinking at the water's edge,",
  "And horses browsed among the flags and sedge,",
  "And gnats and midges danced the water oer,",
  "Just as I've marked them scores of times before,",
  "And birds sat singing, as in mornings gone,--",
  "While I as unconcerned went soodling on,",
  "But little dreaming, as the wakening wind",
  "Flapped the broad ash-leaves oer the pond reclin'd,",
  "And oer the water crinked the curdled wave,",
  "That Jane was sleeping in her watery grave.",
  "The neatherd boy that used to tend the cows,",
  "While getting whip-sticks from the dangling boughs",
  "Of osiers drooping by the water-side,",
  "Her bonnet floating on the top espied;",
  "He knew it well, and hastened fearful down",
  "To take the terror of his fears to town,--",
  "",
  "A melancholy story, far too true;",
  "And soon the village to the pasture flew,",
  "Where, from the deepest hole the pond about,",
  "They dragged poor Jenny's lifeless body out,",
  "And took her home, where scarce an hour gone by",
  "She had been living like to you and I.",
  "I went with more, and kissed her for the last,",
  "And thought with tears on pleasures that were past;",
  "And, the last kindness left me then to do,",
  "I went, at milking, where the blossoms grew,",
  "And handfuls got of rose and lambtoe sweet,",
  "And put them with her in her winding-sheet.",
  "A wilful murder, jury made the crime;",
  "Nor parson 'lowed to pray, nor bell to chime;",
  "On the cross roads, far from her friends and kin,",
  "The usual law for their ungodly sin",
  "Who violent hands upon themselves have laid,",
  "Poor Jane's last bed unchristian-like was made;",
  "And there, like all whose last thoughts turn to heaven,",
  "She sleeps, and doubtless hoped to be forgiven.",
  "But, though I say't, for maids thus veigled in",
  "I think the wicked men deserve the sin;",
  "And sure enough we all at last shall see",
  "The treachery punished as it ought to be.",
  "For ere his wickedness pretended love,",
  "Jane, I'll be bound, was spotless as the dove,",
  "And's good a servant, still old folks allow,",
  "As ever scoured a pail or milked a cow;",
  "And ere he led her into ruin's way,",
  "As gay and buxom as a summer's day:",
  "The birds that ranted in the hedge-row boughs,",
  "As night and morning we have sought our cows,",
  "With yokes and buckets as she bounced along,",
  "Were often deafed to silence with her song.",
  "",
  "But now she's gone:--girls, shun deceitful men,",
  "The worst of stumbles ye can fall agen;",
  "Be deaf to them, and then, as twere, ye'll see",
  "Your pleasures safe as under lock and key.",
  "Throw not my words away, as many do;",
  "They're gold in value, though they're cheap to you.",
  "And husseys hearken, and be warned from this,",
  "If ye love mothers, never do amiss:",
  "Jane might love hers, but she forsook the plan",
  "To make her happy, when she thought of man.",
  "Poor tottering dame, it was too plainly known,",
  "Her daughter's dying hastened on her own,",
  "For from the day the tidings reached her door",
  "She took to bed and looked up no more,",
  "And, ere again another year came round,",
  "She, well as Jane, was laid within the ground;",
  "And all were grieved poor Goody's end to see:",
  "No better neighbour entered house than she,",
  "A harmless soul, with no abusive tongue,",
  "Trig as new pins, and tight's the day was long;",
  "And go the week about, nine times in ten",
  "Ye'd find her house as cleanly as her sen.",
  "But, Lord protect us! time such change does bring,",
  "We cannot dream what oer our heads may hing;",
  "The very house she lived in, stick and stone,",
  "Since Goody died, has tumbled down and gone:",
  "And where the marjoram once, and sage, and rue,",
  "And balm, and mint, with curled-leaf parsley grew,",
  "And double marygolds, and silver thyme,",
  "And pumpkins neath the window used to climb;",
  "And where I often when a child for hours",
  "Tried through the pales to get the tempting flowers,",
  "As lady's laces, everlasting peas,",
  "True-love-lies-bleeding, with the hearts-at-ease,",
  "And golden rods, and tansy running high",
  "That oer the pale-tops smiled on passers-by,",
  "Flowers in my time that every one would praise,",
  "Though thrown like weeds from gardens nowadays;",
  "Where these all grew, now henbane stinks and spreads,",
  "And docks and thistles shake their seedy heads,",
  "And yearly keep with nettles smothering oer;--",
  "The house, the dame, the garden known no more:",
  "While, neighbouring nigh, one lonely elder-tree",
  "Is all that's left of what had used to be,",
  "Marking the place, and bringing up with tears",
  "The recollections of one's younger years.",
  "And now I've done, ye're each at once as free",
  "To take your trundle as ye used to be;",
  "To take right ways, as Jenny should have ta'en,",
  "Or headlong run, and be a second Jane;",
  "For by one thoughtless girl that's acted ill",
  "A thousand may be guided if they will:",
  "As oft mong folks to labour bustling on,",
  "We mark the foremost kick against a stone,",
  "Or stumble oer a stile he meant to climb,",
  "While hind ones see and shun the fall in time.",
  "But ye, I will be bound, like far the best",
  "Love's tickling nick-nacks and the laughing jest,",
  "And ten times sooner than be warned by me,",
  "Would each be sitting on some fellow's knee,",
  "Sooner believe the lies wild chaps will tell",
  "Than old dames' cautions, who would wish ye well:",
  "So have your wills.\"--She pinched her box again,",
  "And ceased her tale, and listened to the rain,",
  "Which still as usual pattered fast around,",
  "And bowed the bent-head loaded to the ground;",
  "While larks, their naked nest by force forsook,",
  "Pruned their wet wings in bushes by the brook.",
  "",
  "  The maids, impatient now old Goody ceased,",
  "As restless children from the school released,",
  "Right gladly proving, what she'd just foretold,",
  "That young ones' stories were preferred to old,",
  "Turn to the whisperings of their former joy,",
  "That oft deceive, but very rarely cloy.",
  ""
]