module.exports = [
  "\"Ah! don't you remember, 'tis almost December,",
  "And soon will the holidays come;",
  "Oh, 'twill be so funny, I've plenty of money,",
  "I'll buy me a sword and a drum. \"",
  "",
  "Thus said little Harry, unwilling to tarry,",
  "Impatient from school to depart;",
  "But we shall discover, this holiday lover",
  "Knew little what was in his heart.",
  "",
  "For when on returning, he gave up his learning,",
  "Away from his sums and his books,",
  "Though playthings surrounded, and sweetmeats abounded,",
  "Chagrin still appear'd in his looks.",
  "",
  "Though first they delighted, his toys were now slighted,",
  "And thrown away out of his sight;",
  "He spent every morning in stretching and yawning,",
  "Yet went to bed weary at night.",
  "",
  "He had not that treasure which really makes pleasure,",
  "(A secret discover'd by few).",
  "You'll take it for granted, more playthings he wanted;",
  "Oh naught was something to do.",
  "",
  "We must have employment to give us enjoyment",
  "And pass the time cheerfully away;",
  "And study and reading give pleasure, exceeding",
  "The pleasures of toys and of play.",
  "",
  "To school now returning­to study and learning",
  "With eagerness Harry applied;",
  "He felt no aversion to books or exertion,",
  "Nor yet for the holidays sigh'd.",
  ""
]