module.exports = [
  "The Ghost of Miltiades came at night,",
  "And he stood by the bed of the Benthamite,",
  "And he said, in a voice, that thrill'd the frame,",
  "\"If ever the sound of Marathon's name",
  "Hath fir'd they blood or flush'd thy brow,",
  "Lover of Liberty, rise thee now!\"",
  "",
  "",
  "The Benthamite, yawning, left his bed --",
  "Away to the Stock Exchange he sped,",
  "And he found the Scrip of Greece so high,",
  "That it fir'd his blood, it flush'd his eye,",
  "And oh, 'twas a sight to see,",
  "For never was Greek more Greek than he!",
  "And still as the premium higher went,",
  "His ecstas rose - so much per cent.,",
  "(As we see in a glass, that tells the weather,",
  "The heat and the silver rise together,)",
  "And Liberty sung from the patriot's lip,",
  "While a voice from pocket whisper'd \"Scrip!\"",
  "The Ghost of Miltiades came again; --",
  "He smil'd as the pale moon smiles through rain,",
  "For his soul was glad at the patriot strain;",
  "(And poor, dear ghost -- how little he knew",
  "The jobs and the tricks of the Philhellene crew!)",
  "\"Blessings and thanks!\" was all he said,",
  "Then, melting away, like a night-dream, fled!",
  "",
  "",
  "The Benthamite hears -- amaz'd that ghosts",
  "Could be such fools -- and away he posts,",
  "A patriot still? Ah no, ah no --",
  "Goddess of Freedom, thy scrip is low,",
  "And, warm and fond as they lovers are,",
  "Thou triest their passion, when under par.",
  "The Benthamite's ardour fast decays,",
  "By turns he weeps, and swears, and prays,",
  "And wishes the d--l had Crescent and Cross,",
  "Ere he had been forc'd to sell at a loss.",
  "They quote thim the Stock of various nations,",
  "But, spite of his classical associations,",
  "Lord how he loathes the Greek quotations!",
  "",
  "",
  "\"Who'll buy my Scrip! Who'll buy my Scrip?\"",
  "Is now the theme of the patriot's lip,",
  "And he runs to tell how hard his lot is",
  "To Messrs. Orlando and Luriottis,",
  "And says, \"Oh Greece, for Liberty's sake,",
  "Do buy my Scrip and I vow to break",
  "Those dark, unholy bonds of thine --",
  "If you'll only consent to buy up mine!\"",
  "The Ghost of Miltiades came once more; --",
  "His brow, like the night, was lowering o'er,",
  "And he said, with a look that flash'd dismay,",
  "\"Of Liberty's foes the worst are they",
  "Who turn to a trade her cause divine,",
  "And gamble for gold on Freedom's shrine!\"",
  "Thus saying, the Ghost, as he took his flight,",
  "Gave a Parthian kick to the Benthamite,",
  "Which sent him, whimpering, off to Jerry --",
  "And vanish'd away to the Stygian ferry!",
  ""
]