module.exports = [
  "  The Harp the Monarch Minstrel swept,",
  "    The King of men, the loved of Heaven!",
  "  Which Music hallowed while she wept",
  "    O'er tones her heart of hearts had given--",
  "Redoubled be her tears, its chords are riven!",
  "  It softened men of iron mould,",
  "    It gave them virtues not their own;",
  "  No ear so dull, no soul so cold,",
  "    That felt not--fired not to the tone,",
  "Till David's Lyre grew mightier than his Throne!",
  "",
  "  It told the triumphs of our King,",
  "    It wafted glory to our God;",
  "  It made our gladdened valleys ring,",
  "    The cedars bow, the mountains nod;",
  "Its sound aspired to Heaven and there abode!",
  "  Since then, though heard on earth no more,",
  "    Devotion and her daughter Love",
  "  Still bid the bursting spirit soar",
  "    To sounds that seem as from above,",
  "In dreams that day's broad light can not remove.",
  ""
]