module.exports = [
  "                   Pallas te hoc Vulnere Pallas",
  "  Immolat et poenam scelerato ex Sanguine Sumit.",
  "",
  "Slow sinks, more lovely ere his race be run,",
  "Along Morea's hills the setting Sun;",
  "Not, as in northern climes, obscurely bright,",
  "But one unclouded blaze of living light;",
  "O'er the hushed deep the yellow beam he throws,",
  "Gilds the green wave that trembles as it glows;",
  "On old Ægina's rock and Hydra's isle",
  "The God of gladness sheds his parting smile;",
  "O'er his own regions lingering loves to shine,",
  "Though there his altars are no more divine.",
  "Descending fast, the mountain-shadows kiss",
  "Thy glorious Gulf, unconquered Salamis!",
  "Their azure arches through the long expanse,",
  "More deeply purpled, meet his mellowing glance,",
  "And tenderest tints, along their summits driven,",
  "Mark his gay course, and own the hues of Heaven;",
  "Till, darkly shaded from the land and deep,",
  "Behind his Delphian rock he sinks to sleep.",
  "",
  "  On such an eve his palest beam he cast",
  "When, Athens! here thy Wisest looked his last.",
  "How watched thy better sons his farewell ray,",
  "That closed their murdered Sage's latest day!",
  "Not yet--not yet--Sol pauses on the hill,",
  "The precious hour of parting lingers still;",
  "But sad his light to agonizing eyes,",
  "And dark the mountain's once delightful dyes;",
  "Gloom o'er the lovely land he seemed to pour,",
  "The land where Phoebus never frowned before;",
  "But ere he sunk below Cithaeron's head,",
  "The cup of Woe was quaffed--the Spirit fled;",
  "The soul of Him that scorned to fear or fly,",
  "Who lived and died as none can live or die.",
  "",
  "  But lo! from high Hymettus to the plain",
  "The Queen of Night asserts her silent reign;",
  "No murky vapour, herald of the storm,",
  "Hides her fair face, or girds her glowing form;",
  "With cornice glimmering as the moonbeams play,",
  "There the white column greets her grateful ray,",
  "And bright around, with quivering beams beset,",
  "Her emblem sparkles o'er the Minaret;",
  "The groves of olive scattered dark and wide,",
  "Where meek Cephisus sheds his scanty tide,",
  "The cypress saddening by the sacred mosque,",
  "The gleaming turret of the gay kiosk,",
  "And sad and sombre 'mid the holy calm,",
  "Near Theseus' fane, yon solitary palm;",
  "All, tinged with varied hues, arrest the eye;",
  "And dull were his that passed them heedless by.",
  "Again the Ægean, heard no more afar,",
  "Lulls his chafed breast from elemental war:",
  "Again his waves in milder tints unfold",
  "Their long expanse of sapphire and of gold,",
  "Mixed with the shades of many a distant isle",
  "That frown, where gentler Ocean deigns to smile.",
  "",
  "  As thus, within the walls of Pallas' fane,",
  "I marked the beauties of the land and main,",
  "Alone, and friendless, on the magic shore,",
  "Whose arts and arms but live in poets' lore;",
  "Oft as the matchless dome I turned to scan,",
  "Sacred to Gods, but not secure from Man,",
  "The Past returned, the Present seemed to cease,",
  "And Glory knew no clime beyond her Greece!",
  "",
  "  Hour rolled along, and Dian's orb on high",
  "Had gained the centre of her softest sky;",
  "And yet unwearied still my footsteps trod",
  "O'er the vain shrine of many a vanished God:",
  "But chiefly, Pallas! thine, when Hecate's glare",
  "Checked by thy columns, fell more sadly fair",
  "O'er the chill marble, where the startling tread",
  "Thrills the lone heart like echoes from the dead.",
  "Long had I mused, and treasured every trace",
  "The wreck of Greece recorded of her race,",
  "When, lo! a giant-form before me strode,",
  "And Pallas hailed me in her own Abode!",
  "",
  "  Yes,'twas Minerva's self; but, ah! how changed,",
  "Since o'er the Dardan field in arms she ranged!",
  "Not such as erst, by her divine command,",
  "Her form appeared from Phidias' plastic hand:",
  "Gone were the terrors of her awful brow,",
  "Her idle Ægis bore no Gorgon now;",
  "Her helm was dinted, and the broken lance",
  "Seemed weak and shaftless e'en to mortal glance;",
  "The Olive Branch, which still she deigned to clasp,",
  "Shrunk from her touch, and withered in her grasp;",
  "And, ah! though still the brightest of the sky,",
  "Celestial tears bedimmed her large blue eye;",
  "Round the rent casque her owlet circled slow,",
  "And mourned his mistress with a shriek of woe!",
  "",
  "  \"Mortal!\"--'twas thus she spake--\"that blush of shame",
  "Proclaims thee Briton, once a noble name;",
  "First of the mighty, foremost of the free,",
  "Now honoured 'less' by all, and 'least' by me:",
  "Chief of thy foes shall Pallas still be found.",
  "Seek'st thou the cause of loathing!--look around.",
  "Lo! here, despite of war and wasting fire,",
  "I saw successive Tyrannies expire;",
  "'Scaped from the ravage of the Turk and Goth,",
  "Thy country sends a spoiler worse than both.",
  "Survey this vacant, violated fane;",
  "Recount the relics torn that yet remain:",
  "'These' Cecrops placed, 'this' Pericles adorned,",
  "'That' Adrian reared when drooping Science mourned.",
  "What more I owe let Gratitude attest--",
  "Know, Alaric and Elgin did the rest.",
  "That all may learn from whence the plunderer came,",
  "The insulted wall sustains his hated name:",
  "For Elgin's fame thus grateful Pallas pleads,",
  "Below, his name--above, behold his deeds!",
  "Be ever hailed with equal honour here",
  "The Gothic monarch and the Pictish peer:",
  "Arms gave the first his right, the last had none,",
  "But basely stole what less barbarians won.",
  "So when the Lion quits his fell repast,",
  "Next prowls the Wolf, the filthy Jackal last:",
  "Flesh, limbs, and blood the former make their own,",
  "The last poor brute securely gnaws the bone.",
  "Yet still the Gods are just, and crimes are crossed:",
  "See here what Elgin won, and what he lost!",
  "Another name with _his_ pollutes my shrine:",
  "Behold where Dian's beams disdain to shine!",
  "Some retribution still might Pallas claim,",
  "When Venus half avenged Minerva's shame.\"",
  "",
  "  She ceased awhile, and thus I dared reply,",
  "To soothe the vengeance kindling in her eye:",
  "\"Daughter of Jove! in Britain's injured name,",
  "A true-born Briton may the deed disclaim.",
  "Frown not on England; England owns him not:",
  "Athena, no! thy plunderer was a Scot.",
  "Ask'st thou the difference? From fair Phyles' towers",
  "Survey Boeotia;--Caledonia's ours.",
  "And well I know within that bastard land",
  "Hath Wisdom's goddess never held command;",
  "A barren soil, where Nature's germs, confined",
  "To stern sterility, can stint the mind;",
  "Whose thistle well betrays the niggard earth,",
  "Emblem of all to whom the Land gives birth;",
  "Each genial influence nurtured to resist;",
  "A land of meanness, sophistry, and mist.",
  "Each breeze from foggy mount and marshy plain",
  "Dilutes with drivel every drizzly brain,",
  "Till, burst at length, each wat'ry head o'erflows,",
  "Foul as their soil, and frigid as their snows:",
  "Then thousand schemes of petulance and pride",
  "Despatch her scheming children far and wide;",
  "Some East, some West, some--everywhere but North!",
  "In quest of lawless gain, they issue forth.",
  "And thus--accursed be the day and year!",
  "She sent a Pict to play the felon here.",
  "Yet Caledonia claims some native worth,",
  "As dull Boeotia gave a Pindar birth;",
  "So may her few, the lettered and the brave,",
  "Bound to no clime, and victors of the grave,",
  "Shake off the sordid dust of such a land,",
  "And shine like children of a happier strand;",
  "As once, of yore, in some obnoxious place,",
  "Ten names (if found) had saved a wretched race.\"",
  "",
  "  \"Mortal!\" the blue-eyed maid resumed, \"once more",
  "Bear back my mandate to thy native shore.",
  "Though fallen, alas! this vengeance yet is mine,",
  "To turn my counsels far from lands like thine.",
  "Hear then in silence Pallas' stern behest;",
  "Hear and believe, for Time will tell the rest.",
  "",
  "  \"First on the head of him who did this deed",
  "My curse shall light,--on him and all his seed:",
  "Without one spark of intellectual fire,",
  "Be all the sons as senseless as the sire:",
  "If one with wit the parent brood disgrace,",
  "Believe him bastard of a brighter race:",
  "Still with his hireling artists let him prate,",
  "And Folly's praise repay for Wisdom's hate;",
  "Long of their Patron's gusto let them tell,",
  "Whose noblest, _native_ gusto is--to sell:",
  "To sell, and make--may shame record the day!--",
  "The State--Receiver of his pilfered prey.",
  "Meantime, the flattering, feeble dotard, West,",
  "Europe's worst dauber, and poor Britain's best,",
  "With palsied hand shall turn each model o'er,",
  "And own himself an infant of fourscore.",
  "Be all the Bruisers culled from all St. Giles',",
  "That Art and Nature may compare their styles;",
  "While brawny brutes in stupid wonder stare,",
  "And marvel at his Lordship's 'stone shop' there.",
  "Round the thronged gate shall sauntering coxcombs creep",
  "To lounge and lucubrate, to prate and peep;",
  "While many a languid maid, with longing sigh,",
  "On giant statues casts the curious eye;",
  "The room with transient glance appears to skim,",
  "Yet marks the mighty back and length of limb;",
  "Mourns o'er the difference of _now_ and _then_;",
  "Exclaims, 'These Greeks indeed were proper men!'",
  "Draws slight comparisons of 'these' with 'those',",
  "And envies Laïs all her Attic beaux.",
  "When shall a modern maid have swains like these?",
  "Alas! Sir Harry is no Hercules!",
  "And last of all, amidst the gaping crew,",
  "Some calm spectator, as he takes his view,",
  "In silent indignation mixed with grief,",
  "Admires the plunder, but abhors the thief.",
  "Oh, loathed in life, nor pardoned in the dust,",
  "May Hate pursue his sacrilegious lust!",
  "Linked with the fool that fired the Ephesian dome,",
  "Shall vengeance follow far beyond the tomb,",
  "And Eratostratus and Elgin shine",
  "In many a branding page and burning line;",
  "Alike reserved for aye to stand accursed,",
  "Perchance the second blacker than the first.",
  "",
  "  \"So let him stand, through ages yet unborn,",
  "Fixed statue on the pedestal of Scorn;",
  "Though not for him alone revenge shall wait,",
  "But fits thy country for her coming fate:",
  "Hers were the deeds that taught her lawless son",
  "To do what oft Britannia's self had done.",
  "Look to the Baltic--blazing from afar,",
  "Your old Ally yet mourns perfidious war.",
  "Not to such deeds did Pallas lend her aid,",
  "Or break the compact which herself had made;",
  "Far from such counsels, from the faithless field",
  "She fled--but left behind her Gorgon shield;",
  "A fatal gift that turned your friends to stone,",
  "And left lost Albion hated and alone.",
  "",
  "\"Look to the East, where Ganges' swarthy race",
  "Shall shake your tyrant empire to its base;",
  "Lo! there Rebellion rears her ghastly head,",
  "And glares the Nemesis of native dead;",
  "Till Indus rolls a deep purpureal flood,",
  "And claims his long arrear of northern blood.",
  "So may ye perish!--Pallas, when she gave",
  "Your free-born rights, forbade ye to enslave.",
  "",
  "  \"Look on your Spain!--she clasps the hand she hates,",
  "But boldly clasps, and thrusts you from her gates.",
  "Bear witness, bright Barossa! thou canst tell",
  "Whose were the sons that bravely fought and fell.",
  "But Lusitania, kind and dear ally,",
  "Can spare a few to fight, and sometimes fly.",
  "Oh glorious field! by Famine fiercely won,",
  "The Gaul retires for once, and all is done!",
  "But when did Pallas teach, that one retreat",
  "Retrieved three long Olympiads of defeat?",
  "",
  "  \"Look last at home--ye love not to look there",
  "On the grim smile of comfortless despair:",
  "Your city saddens: loud though Revel howls,",
  "Here Famine faints, and yonder Rapine prowls.",
  "See all alike of more or less bereft;",
  "No misers tremble when there's nothing left.",
  "'Blest paper credit;' who shall dare to sing?",
  "It clogs like lead Corruption's weary wing.",
  "Yet Pallas pluck'd each Premier by the ear,",
  "Who Gods and men alike disdained to hear;",
  "But one, repentant o'er a bankrupt state,",
  "On Pallas calls,--but calls, alas! too late:",
  "Then raves for'----'; to that Mentor bends,",
  "Though he and Pallas never yet were friends.",
  "Him senates hear, whom never yet they heard,",
  "Contemptuous once, and now no less absurd.",
  "So, once of yore, each reasonable frog,",
  "Swore faith and fealty to his sovereign 'log.'",
  "Thus hailed your rulers their patrician clod,",
  "As Egypt chose an onion for a God.",
  "",
  "  \"Now fare ye well! enjoy your little hour;",
  "Go, grasp the shadow of your vanished power;",
  "Gloss o'er the failure of each fondest scheme;",
  "Your strength a name, your bloated wealth a dream.",
  "Gone is that Gold, the marvel of mankind.",
  "And Pirates barter all that's left behind.",
  "No more the hirelings, purchased near and far,",
  "Crowd to the ranks of mercenary war.",
  "The idle merchant on the useless quay",
  "Droops o'er the bales no bark may bear away;",
  "Or, back returning, sees rejected stores",
  "Rot piecemeal on his own encumbered shores:",
  "The starved mechanic breaks his rusting loom,",
  "And desperate mans him 'gainst the coming doom.",
  "Then in the Senates of your sinking state",
  "Show me the man whose counsels may have weight.",
  "Vain is each voice where tones could once command;",
  "E'en factions cease to charm a factious land:",
  "Yet jarring sects convulse a sister Isle,",
  "And light with maddening hands the mutual pile.",
  "",
  "  \"'Tis done, 'tis past--since Pallas warns in vain;",
  "The Furies seize her abdicated reign:",
  "Wide o'er the realm they wave their kindling brands,",
  "And wring her vitals with their fiery hands.",
  "But one convulsive struggle still remains,",
  "And Gaul shall weep ere Albion wear her chains,",
  "The bannered pomp of war, the glittering files,",
  "O'er whose gay trappings stern Bellona smiles;",
  "The brazen trump, the spirit-stirring drum,",
  "That bid the foe defiance ere they come;",
  "The hero bounding at his country's call,",
  "The glorious death that consecrates his fall,",
  "Swell the young heart with visionary charms.",
  "And bid it antedate the joys of arms.",
  "But know, a lesson you may yet be taught,",
  "With death alone are laurels cheaply bought;",
  "Not in the conflict Havoc seeks delight,",
  "His day of mercy is the day of fight.",
  "But when the field is fought, the battle won,",
  "Though drenched with gore, his woes are but begun:",
  "His deeper deeds as yet ye know by name;",
  "The slaughtered peasant and the ravished dame,",
  "The rifled mansion and the foe-reaped field,",
  "Ill suit with souls at home, untaught to yield.",
  "Say with what eye along the distant down",
  "Would flying burghers mark the blazing town?",
  "How view the column of ascending flames",
  "Shake his red shadow o'er the startled Thames?",
  "Nay, frown not, Albion! for the torch was thine",
  "That lit such pyres from Tagus to the Rhine:",
  "Now should they burst on thy devoted coast,",
  "Go, ask thy bosom who deserves them most?",
  "The law of Heaven and Earth is life for life,",
  "And she who raised, in vain regrets, the strife.\"",
  ""
]