module.exports = [
  "'Twas in the year of 1884, and on Saturday the 20th of September,",
  "Which the inhabitants of Dundee will long remember",
  "The great Liberal Franchise Demonstration,",
  "Which filled their minds with admiration.",
  "",
  "Oh! it was a most magnificent display,",
  "To see about 20 or 30 thousand men all in grand array;",
  "And each man with a medal on his breast;",
  "And every man in the procession dressed in his best.",
  "",
  "The banners of the processionists were really grand to see-",
  "The like hasn't been seen for a long time in Dundee;",
  "While sweet music from the bands did rend the skies,",
  "And every processionist was resolved to vote for the Franchise.",
  "",
  "And as the procession passed along each street,",
  "The spectators did loudly the processionists greet;",
  "As they viewed their beautiful banners waving in the wind,",
  "They declared such a scene would be ever fresh in their mind.",
  "",
  "The mustering of the processionists was very grand,",
  "As along the Esplanade each man took his stand,",
  "And as soon as they were marshalled in grand array,",
  "To the Magdalen Green, in haste, they wended their way.",
  "",
  "And when they arrived on the Magdalen Green,",
  "I'm sure it was a very beautiful imposing scene-",
  "While the cheers of that vast multitude ascended to the skies,",
  "For the \"Grand Old Man,\" Gladstone, the Hero of the Franchise,",
  "",
  "Who has struggled very hard for the people's rights,",
  "Many long years, and many weary nights;",
  "And I think the \"Grand Old Man\" will gain the Franchise,",
  "And if he does, the people will laud him to the skies.",
  "",
  "And his name should be written in letters of gold :",
  "For he is a wise statesman- true and bold-",
  "Who has advocated the people's rights for many long years;",
  "And when he is dead they will thank him with their tears.",
  "",
  "For he is the man for the working man,",
  "And without fear of contradiction, deny it who can;",
  "Because he wishes the working man to have a good coat,",
  "And, both in town and country, to have power to vote.",
  "",
  "The reason why the Lords won't pass the Franchise Bill :",
  "They fear that it will do themselves some ill;",
  "That is the reason why they wish to throw it out,",
  "Yes, believe me, fellow citizens, that's the cause without doubt.",
  "",
  "The emblems and mottoes in the procession, were really grand,",
  "The like hasn't been seen in broad Scotland;",
  "Especially the picture of Gladstone- the nation's hope,",
  "Who is a much cleverer man than Sir John Cope.",
  "",
  "There were masons and ploughmen all in a row,",
  "Also tailors, tenters, and blacksmiths, which made a grand show;",
  "Likewise carters and bakers which was most beautiful to be seen,",
  "To see them marching from the Esplanade to the Magdalen Green.",
  "",
  "I'm sure it was a most beautiful sight to see,",
  "The like has never been seen before in Dundee;",
  "Such a body of men, and Gladstone at the helm,",
  "Such a sight, I'm sure, 'twould the Lords o'erwhelm.",
  "",
  "Oh! it was grand to see that vast crowd,",
  "And to hear the speeches, most eloquent and loud,",
  "That were made by the speakers, regarding the Franchise;",
  "While the spectators applauded them to the skies.",
  "",
  "And for the \"Grand Old Man\" they gave three cheers,",
  "Hoping he would live for many long years;",
  "And when the speeches were ended, the people's hearts were gay,",
  "And they all dispersed quietly to their homes without delay.",
  ""
]