module.exports = [
  "PART I.",
  "",
  "SCENE I.--_A Forest_.",
  "",
  "             _Enter_ ARNOLD _and his mother_ BERTHA.",
  "",
  "_Bert._ Out, Hunchback!",
  "",
  "_Arn._                 I was born so, Mother!",
  "",
  "_Bert._                                       Out,",
  "Thou incubus! Thou nightmare! Of seven sons,",
  "The sole abortion!",
  "",
  "_Arn._              Would that I had been so,",
  "And never seen the light!",
  "",
  "_Bert._                  I would so, too!",
  "But as thou _hast_--hence, hence--and do thy best!",
  "That back of thine may bear its burthen; 'tis",
  "More high, if not so broad as that of others.",
  "",
  "_Arn._ It _bears_ its burthen;--but, my heart! Will it",
  "Sustain that which you lay upon it, Mother?",
  "I love, or, at the least, I loved you: nothing",
  "Save You, in nature, can love aught like me.",
  "You nursed me--do not kill me!",
  "",
  "_Bert._                      Yes--I nursed thee,",
  "Because thou wert my first-born, and I knew not",
  "If there would be another unlike thee,",
  "That monstrous sport of Nature. But get hence,",
  "And gather wood!",
  "",
  "_Arn._           I will: but when I bring it,",
  "Speak to me kindly. Though my brothers are",
  "So beautiful and lusty, and as free",
  "As the free chase they follow, do not spurn me:",
  "Our milk has been the same.",
  "",
  "_Bert._                    As is the hedgehog's,",
  "Which sucks at midnight from the wholesome dam",
  "Of the young bull, until the milkmaid finds",
  "The nipple, next day, sore, and udder dry.",
  "Call not thy brothers brethren! Call me not",
  "Mother; for if I brought thee forth, it was",
  "As foolish hens at times hatch vipers, by",
  "Sitting upon strange eggs. Out, urchin, out!",
  "                                                       [_Exit_ BERTHA.",
  "",
  "_Arn._ (_solus_). Oh, mother!--She is gone, and I must do",
  "Her bidding;--wearily but willingly",
  "I would fulfil it, could I only hope",
  "A kind word in return. What shall I do?",
  "",
  "                            [_ARNOLD begins to cut wood: in doing this",
  "                                 he wounds one of his hands_.",
  "",
  "My labour for the day is over now.",
  "Accursed be this blood that flows so fast;",
  "For double curses will be my meed now",
  "At home--What home? I have no home, no kin,",
  "No kind--not made like other creatures, or",
  "To share their sports or pleasures. Must I bleed, too,",
  "Like them? Oh, that each drop which falls to earth",
  "Would rise a snake to sting them, as they have stung me!",
  "Or that the Devil, to whom they liken me,",
  "Would aid his likeness! If I must partake",
  "His form, why not his power? Is it because",
  "I have not his will too? For one kind word",
  "From her who bore me would still reconcile me",
  "Even to this hateful aspect. Let me wash",
  "The wound.",
  "",
  "                         [ARNOLD _goes to a spring, and stoops to wash",
  "                                 his hand: he starts back_.",
  "",
  "They are right; and Nature's mirror shows me,",
  "What she hath made me. I will not look on it",
  "Again, and scarce dare think on't. Hideous wretch",
  "That I am! The very waters mock me with",
  "My horrid shadow--like a demon placed",
  "Deep in the fountain to scare back the cattle",
  "From drinking therein.                                   [_He pauses_.",
  "                       And shall I live on,",
  "A burden to the earth, myself, and shame",
  "Unto what brought me into life? Thou blood,",
  "Which flowest so freely from a scratch, let me",
  "Try if thou wilt not, in a fuller stream,",
  "Pour forth my woes for ever with thyself",
  "On earth, to which I will restore, at once,",
  "This hateful compound of her atoms, and",
  "Resolve back to her elements, and take",
  "The shape of any reptile save myself,",
  "And make a world for myriads of new worms!",
  "This knife! now let me prove if it will sever",
  "This withered slip of Nature's nightshade--my",
  "Vile form--from the creation, as it hath",
  "The green bough from the forest.",
  "",
  "                         [ARNOLD _places the knife in the ground, with",
  "                                the point upwards_.",
  "",
  "                                Now 'tis set,",
  "And I can fall upon it. Yet one glance",
  "On the fair day, which sees no foul thing like",
  "Myself, and the sweet sun which warmed me, but",
  "In vain. The birds--how joyously they sing!",
  "So let them, for I would not be lamented:",
  "But let their merriest notes be Arnold's knell;",
  "The fallen leaves my monument; the murmur",
  "Of the near fountain my sole elegy.",
  "Now, knife, stand firmly, as I fain would fall!",
  "",
  "                       [_As he rushes to throw himself upon the knife,",
  "                           his eye is suddenly caught by the fountain,",
  "                           which seems in motion_.",
  "",
  "The fountain moves without a wind: but shall",
  "The ripple of a spring change my resolve?",
  "No. Yet it moves again! The waters stir,",
  "Not as with air, but by some subterrane",
  "And rocking Power of the internal world.",
  "What's here? A mist! No more?--",
  "",
  "                   [_A cloud comes from the fountain. He stands gazing",
  "                         upon it: it is dispelled, and a tall black",
  "                         man comes towards him_.",
  "",
  "_Arn._                           What would you? Speak!",
  "Spirit or man?",
  "",
  "_Stran._       As man is both, why not",
  "Say both in one?",
  "",
  "_Arn._          Your form is man's, and yet",
  "You may be devil.",
  "",
  "_Stran._         So many men are that",
  "Which is so called or thought, that you may add me",
  "To which you please, without much wrong to either.",
  "But come: you wish to kill yourself;--pursue",
  "Your purpose.",
  "",
  "_Arn._       You have interrupted me.",
  "",
  "_Stran._ What is that resolution which can e'er",
  "Be interrupted? If I be the devil",
  "You deem, a single moment would have made you",
  "Mine, and for ever, by your suicide;",
  "And yet my coming saves you.",
  "",
  "_Arn._                       I said not",
  "You _were_ the Demon, but that your approach",
  "Was like one.",
  "",
  "_Stran._      Unless you keep company",
  "With him (and you seem scarce used to such high",
  "Society) you can't tell how he approaches;",
  "And for his aspect, look upon the fountain,",
  "And then on me, and judge which of us twain",
  "Looks likest what the boors believe to be",
  "Their cloven-footed terror.",
  "",
  "_Arn._                      Do you--dare _you_",
  "To taunt me with my born deformity?",
  "",
  "_Stran._ Were I to taunt a buffalo with this",
  "Cloven foot of thine, or the swift dromedary",
  "With thy Sublime of Humps, the animals",
  "Would revel in the compliment. And yet",
  "Both beings are more swift, more strong, more mighty",
  "In action and endurance than thyself,",
  "And all the fierce and fair of the same kind",
  "With thee. Thy form is natural: 'twas only",
  "Nature's mistaken largess to bestow",
  "The gifts which are of others upon man.",
  "",
  "_Arn._ Give me the strength then of the buffalo's foot,",
  "When he spurns high the dust, beholding his",
  "Near enemy; or let me have the long",
  "And patient swiftness of the desert-ship,",
  "The helmless dromedary!--and I'll bear",
  "Thy fiendish sarcasm with a saintly patience.",
  "",
  "_Stran._ I will.",
  "",
  "_Arn._ (_with surprise_). Thou _canst?_",
  "",
  "_Stran._                          Perhaps. Would you aught else?",
  "",
  "_Arn._ Thou mockest me.",
  "",
  "_Stran._                Not I. Why should I mock",
  "What all are mocking? That's poor sport, methinks.",
  "To talk to thee in human language (for",
  "Thou canst not yet speak mine), the forester",
  "Hunts not the wretched coney, but the boar,",
  "Or wolf, or lion--leaving paltry game",
  "To petty burghers, who leave once a year",
  "Their walls, to fill their household cauldrons with",
  "Such scullion prey. The meanest gibe at thee,--",
  "Now _I_ can mock the mightiest.",
  "",
  "_Arn._                           Then waste not",
  "Thy time on me: I seek thee not.",
  "",
  "_Stran._                         Your thoughts",
  "Are not far from me. Do not send me back:",
  "I'm not so easily recalled to do",
  "Good service.",
  "",
  "_Arn._        What wilt thou do for me?",
  "",
  "_Stran._                               Change",
  "Shapes with you, if you will, since yours so irks you;",
  "Or form you to your wish in any shape.",
  "",
  "_Arn._ Oh! then you are indeed the Demon, for",
  "Nought else would wittingly wear mine.",
  "",
  "_Stran._                               I'll show thee",
  "The brightest which the world e'er bore, and give thee",
  "Thy choice.",
  "",
  "_Arn._       On what condition?",
  "",
  "_Stran._                       There's a question!",
  "An hour ago you would have given your soul",
  "To look like other men, and now you pause",
  "To wear the form of heroes.",
  "",
  "_Arn._                     No; I will not.",
  "I must not compromise my soul.",
  "",
  "_Stran._                       What soul,",
  "Worth naming so, would dwell in such a carcase?",
  "",
  "_Arn._ 'Tis an aspiring one, whate'er the tenement",
  "In which it is mislodged. But name your compact:",
  "Must it be signed in blood?",
  "",
  "_Stran._                   Not in your own.",
  "",
  "_Arn._ Whose blood then?",
  "",
  "_Stran._                 We will talk of that hereafter.",
  "But I'll be moderate with you, for I see",
  "Great things within you. You shall have no bond",
  "But your own will, no contract save your deeds.",
  "Are you content?",
  "",
  "_Arn._           I take thee at thy word.",
  "",
  "_Stran._   Now then!--",
  "         [_The Stranger approaches the fountain, and turns to_ ARNOLD.",
  "",
  "                      A little of your blood.",
  "",
  "_Arn._                                        For what?",
  "",
  "_Stran._ To mingle with the magic of the waters,",
  "And make the charm effective.",
  "",
  "_Arn._ (_holding out his wounded arm_). Take it all.",
  "",
  "_Stran._ Not now. A few drops will suffice for this.",
  "",
  "                  [_The Stranger takes some of_ ARNOLD'S _blood in his",
  "                         hand, and casts it into the fountain_.",
  "",
  "Shadows of Beauty!",
  "  Shadows of Power!",
  "Rise to your duty--",
  "  This is the hour!",
  "Walk lovely and pliant",
  "  From the depth of this fountain,",
  "As the cloud-shapen giant",
  "  Bestrides the Hartz Mountain.",
  "Come as ye were,",
  "  That our eyes may behold",
  "The model in air",
  "  Of the form I will mould,",
  "Bright as the Iris",
  "  When ether is spanned;--",
  "Such _his_ desire is,                           [_Pointing to_ ARNOLD.",
  "  Such _my_ command!",
  "Demons heroic--",
  "  Demons who wore",
  "The form of the Stoic",
  "  Or sophist of yore--",
  "Or the shape of each victor--",
  "  From Macedon's boy,",
  "To each high Roman's picture,",
  "  Who breathed to destroy--",
  "Shadows of Beauty!",
  "  Shadows of Power!",
  "Up to your duty--",
  "  This is the hour!",
  "",
  "                    [_Various phantoms arise from the waters, and pass",
  "                        in succession before the Stranger and_ ARNOLD.",
  "",
  "_Arn._ What do I see?",
  "",
  "_Stran._              The black-eyed Roman, with",
  "The eagle's beak between those eyes which ne'er",
  "Beheld a conqueror, or looked along",
  "The land he made not Rome's, while Rome became",
  "His, and all theirs who heired his very name.",
  "",
  "_Arn._ The phantom's bald; _my_ quest is beauty. Could I",
  "Inherit but his fame with his defects!",
  "",
  "_Stran._ His brow was girt with laurels more than hairs.",
  "You see his aspect--choose it, or reject.",
  "I can but promise you his form; his fame",
  "Must be long sought and fought for.",
  "",
  "_Arn._                              I will fight, too,",
  "But not as a mock Cæsar. Let him pass:",
  "His aspect may be fair, but suits me not.",
  "",
  "_Stran._ Then you are far more difficult to please",
  "Than Cato's sister, or than Brutus's mother,",
  "Or Cleopatra at sixteen--an age",
  "When love is not less in the eye than heart.",
  "But be it so! Shadow, pass on!",
  "                            [_The phantom of Julius Cæsar disappears_.",
  "",
  "_Arn._                          And can it",
  "Be, that the man who shook the earth is gone,",
  "And left no footstep?",
  "",
  "_Stran._             There you err. His substance",
  "Left graves enough, and woes enough, and fame",
  "More than enough to track his memory;",
  "But for his shadow--'tis no more than yours,",
  "Except a little longer and less crooked",
  "I' the sun. Behold another!                [_A second phantom passes_.",
  "",
  "_Arn._                     Who is he?",
  "",
  "_Stran._ He was the fairest and the bravest of",
  "Athenians. Look upon him well.",
  "",
  "_Arn._                             He is",
  "More lovely than the last. How beautiful!",
  "",
  "_Stran._ Such was the curled son of Clinias;--wouldst thou",
  "Invest thee with his form?",
  "",
  "_Arn._                     Would that I had",
  "Been born with it! But since I may choose further,",
  "I will _look_ further.          [_The shade of Alcibiades disappears_.",
  "",
  "_Stran._              Lo! behold again!",
  "",
  "_Arn._ What! that low, swarthy, short-nosed, round-eyed satyr,",
  "With the wide nostrils and Silenus' aspect,",
  "The splay feet and low stature! I had better",
  "Remain that which I am.",
  "",
  "_Stran._               And yet he was",
  "The earth's perfection of all mental beauty,",
  "And personification of all virtue.",
  "But you reject him?",
  "",
  "_Arn._             If his form could bring me",
  "That which redeemed it--no.",
  "",
  "_Stran._                     I have no power",
  "To promise that; but you may try, and find it",
  "Easier in such a form--or in your own.",
  "",
  "_Arn._ No. I was not born for philosophy,",
  "Though I have that about me which has need on't.",
  "Let him fleet on.",
  "",
  "_Stran._          Be air, thou Hemlock-drinker!",
  "                  [_The shadow of Socrates disappears: another rises_.",
  "",
  "_Arn._ What's here? whose broad brow and whose curly beard",
  "And manly aspect look like Hercules,",
  "Save that his jocund eye hath more of Bacchus",
  "Than the sad purger of the infernal world,",
  "Leaning dejected on his club of conquest,",
  "As if he knew the worthlessness of those",
  "For whom he had fought.",
  "",
  "_Stran._                It was the man who lost",
  "The ancient world for love.",
  "",
  "_Arn._                      I cannot blame him,",
  "Since I have risked my soul because I find not",
  "That which he exchanged the earth for.",
  "",
  "_Stran._                              Since so far",
  "You seem congenial, will you wear his features?",
  "",
  "_Arn._ No. As you leave me choice, I am difficult.",
  "If but to see the heroes I should ne'er",
  "Have seen else, on this side of the dim shore,",
  "Whence they float back before us.",
  "",
  "_Stran._                         Hence, Triumvir,",
  "Thy Cleopatra's waiting.",
  "                     [_The shade of Antony disappears: another rises_.",
  "",
  "_Arn._                  Who is this?",
  "Who truly looketh like a demigod,",
  "Blooming and bright, with golden hair, and stature,",
  "If not more high than mortal, yet immortal",
  "In all that nameless bearing of his limbs,",
  "Which he wears as the Sun his rays--a something",
  "Which shines from him, and yet is but the flashing",
  "Emanation of a thing more glorious still.",
  "Was _he e'er human only?_",
  "",
  "_Stran._                   Let the earth speak,",
  "If there be atoms of him left, or even",
  "Of the more solid gold that formed his urn.",
  "",
  "_Arn._ Who was this glory of mankind?",
  "",
  "_Stran._                              The shame",
  "Of Greece in peace, her thunderbolt in war--",
  "Demetrius the Macedonian, and",
  "Taker of cities.",
  "",
  "_Arn._           Yet one shadow more.",
  "",
  "_Stran._ (_addressing the shadow_). Get thee to Lamia's lap!",
  "        [_The shade of Demetrius Poliorcetes vanishes: another rises_.",
  "                                  I'll fit you still,",
  "Fear not, my Hunchback: if the shadows of",
  "That which existed please not your nice taste,",
  "I'll animate the ideal marble, till",
  "Your soul be reconciled to her new garment",
  "",
  "_Arn._ Content! I will fix here.",
  "",
  "_Stran._                         I must commend",
  "Your choice. The godlike son of the sea-goddess,",
  "The unshorn boy of Peleus, with his locks",
  "As beautiful and clear as the amber waves",
  "Of rich Pactolus, rolled o'er sands of gold,",
  "Softened by intervening crystal, and",
  "Rippled like flowing waters by the wind,",
  "All vowed to Sperchius as they were--behold them!",
  "And _him_--as he stood by Polixena,",
  "With sanctioned and with softened love, before",
  "The altar, gazing on his Trojan bride,",
  "With some remorse within for Hector slain",
  "And Priam weeping, mingled with deep passion",
  "For the sweet downcast virgin, whose young hand",
  "Trembled in _his_ who slew her brother. So",
  "He stood i' the temple! Look upon him as",
  "Greece looked her last upon her best, the instant",
  "Ere Paris' arrow flew.",
  "",
  "_Arn._                I gaze upon him",
  "As if I were his soul, whose form shall soon",
  "Envelope mine.",
  "",
  "_Stran._       You have done well. The greatest",
  "Deformity should only barter with",
  "The extremest beauty--if the proverb's true",
  "Of mortals, that Extremes meet.",
  "",
  "_Arn._                          Come! Be quick!",
  "I am impatient.",
  "",
  "_Stran._        As a youthful beauty",
  "Before her glass. _You both_ see what is not,",
  "But dream it is what must be.",
  "",
  "_Arn._                        Must I wait?",
  "",
  "_Stran._ No; that were a pity. But a word or two:",
  "His stature is twelve cubits; would you so far",
  "Outstep these times, and be a Titan? Or",
  "(To talk canonically) wax a son",
  "Of Anak?",
  "",
  "_Arn._ Why not?",
  "",
  "_Stran._        Glorious ambition!",
  "I love thee most in dwarfs! A mortal of",
  "Philistine stature would have gladly pared",
  "His own Goliath down to a slight David:",
  "But thou, my manikin, wouldst soar a show",
  "Rather than hero. Thou shalt be indulged,",
  "If such be thy desire; and, yet, by being",
  "A little less removed from present men",
  "In figure, thou canst sway them more; for all",
  "Would rise against thee now, as if to hunt",
  "A new-found Mammoth; and their curséd engines,",
  "Their culverins, and so forth, would find way",
  "Through our friend's armour there, with greater ease",
  "Than the Adulterer's arrow through his heel",
  "Which Thetis had forgotten to baptize",
  "In Styx.",
  "",
  "_Arn._  Then let it be as thou deem'st best.",
  "",
  "_Stran._ Thou shalt be beauteous as the thing thou seest,",
  "And strong as what it was, and----",
  "",
  "_Arn._                          I ask not",
  "For Valour, since Deformity is daring.",
  "It is its essence to o'ertake mankind",
  "By heart and soul, and make itself the equal--",
  "Aye, the superior of the rest. There is",
  "A spur in its halt movements, to become",
  "All that the others cannot, in such things",
  "As still are free to both, to compensate",
  "For stepdame Nature's avarice at first.",
  "They woo with fearless deeds the smiles of fortune,",
  "And oft, like Timour the lame Tartar, win them.",
  "",
  "_Stran._ Well spoken! And thou doubtless wilt remain",
  "Formed as thou art. I may dismiss the mould",
  "Of shadow, which must turn to flesh, to incase",
  "This daring soul, which could achieve no less",
  "Without it.",
  "",
  "_Arn._      Had no power presented me",
  "The possibility of change, I would",
  "Have done the best which spirit may to make",
  "Its way with all Deformity's dull, deadly,",
  "Discouraging weight upon me, like a mountain,",
  "In feeling, on my heart as on my shoulders--",
  "A hateful and unsightly molehill to",
  "The eyes of happier men. I would have looked",
  "On Beauty in that sex which is the type",
  "Of all we know or dream of beautiful,",
  "Beyond the world they brighten, with a sigh--",
  "Not of love, but despair; nor sought to win,",
  "Though to a heart all love, what could not love me",
  "In turn, because of this vile crookéd clog,",
  "Which makes me lonely. Nay, I could have borne",
  "It all, had not my mother spurned me from her.",
  "The she-bear licks her cubs into a sort",
  "Of shape;--my Dam beheld my shape was hopeless.",
  "Had she exposed me, like the Spartan, ere",
  "I knew the passionate part of life, I had",
  "Been a clod of the valley,--happier nothing",
  "Than what I am. But even thus--the lowest,",
  "Ugliest, and meanest of mankind--what courage",
  "And perseverance could have done, perchance",
  "Had made me something--as it has made heroes",
  "Of the same mould as mine. You lately saw me",
  "Master of my own life, and quick to quit it;",
  "And he who is so is the master of",
  "Whatever dreads to die.",
  "",
  "_Stran._               Decide between",
  "What you have been, or will be.",
  "",
  "_Arn._                         I have done so.",
  "You have opened brighter prospects to my eyes,",
  "And sweeter to my heart. As I am now,",
  "I might be feared--admired--respected--loved",
  "Of all save those next to me, of whom I",
  "Would be belovéd. As thou showest me",
  "A choice of forms, I take the one I view.",
  "Haste! haste!",
  "",
  "_Stran._      And what shall _I_ wear?",
  "",
  "_Arn._                                 Surely, he",
  "Who can command all forms will choose the highest,",
  "Something superior even to that which was",
  "Pelides now before us. Perhaps _his_",
  "Who slew him, that of Paris: or--still higher--",
  "The Poet's God, clothed in such limbs as are",
  "Themselves a poetry.",
  "",
  "_Stran._            Less will content me;",
  "For I, too, love a change.",
  "",
  "_Arn._                    Your aspect is",
  "Dusky, but not uncomely.",
  "",
  "_Stran._                  If I chose,",
  "I might be whiter; but I have a _penchant_",
  "For black--it is so honest, and, besides,",
  "Can neither blush with shame nor pale with fear;",
  "But I have worn it long enough of late,",
  "And now I'll take your figure.",
  "",
  "_Arn._                         Mine!",
  "",
  "_Stran._                            Yes. You",
  "Shall change with Thetis' son, and I with Bertha,",
  "Your mother's offspring. People have their tastes;",
  "You have yours--I mine.",
  "",
  "_Arn._                  Despatch! despatch!",
  "",
  "_Stran._                                  Even so.",
  "",
  "                         [_The Stranger takes some earth and moulds it",
  "                              along the turf, and then addresses",
  "                              the phantom of Achilles_.",
  "",
  "Beautiful shadow",
  "  Of Thetis's boy!",
  "Who sleeps in the meadow",
  "  Whose grass grows o'er Troy:",
  "From the red earth, like Adam,",
  "  Thy likeness I shape,",
  "As the Being who made him,",
  "  Whose actions I ape.",
  "Thou Clay, be all glowing,",
  "  Till the Rose in his cheek",
  "Be as fair as, when blowing,",
  "  It wears its first streak!",
  "Ye Violets, I scatter,",
  "  Now turn into eyes!",
  "And thou, sunshiny Water,",
  "  Of blood take the guise!",
  "Let these Hyacinth boughs",
  "  Be his long flowing hair,",
  "And wave o'er his brows,",
  "  As thou wavest in air!",
  "Let his heart be this marble",
  "  I tear from the rock!",
  "But his voice as the warble",
  "  Of birds on yon oak!",
  "Let his flesh be the purest",
  "  Of mould, in which grew",
  "The Lily-root surest,",
  "  And drank the best dew!",
  "Let his limbs be the lightest",
  "  Which clay can compound,",
  "And his aspect the brightest",
  "  On earth to be found!",
  "Elements, near me,",
  "  Be mingled and stirred,",
  "Know me, and hear me,",
  "  And leap to my word!",
  "Sunbeams, awaken",
  "  This earth's animation!",
  "'Tis done! He hath taken",
  "  His stand in creation!",
  "",
  "              [ARNOLD _falls senseless; his soul passes into the shape",
  "                     of Achilles, which rises from the ground; while",
  "                     the phantom has disappeared, part by part,",
  "                     as the figure was formed from the earth_.",
  "",
  "_Arn._ (_in his new form_). I love, and I shall be beloved! Oh, life!",
  "At last I feel thee! Glorious Spirit!",
  "",
  "_Stran._                             Stop!",
  "What shall become of your abandoned garment,",
  "Yon hump, and lump, and clod of ugliness,",
  "Which late you wore, or were?",
  "",
  "_Arn._                       Who cares? Let wolves",
  "And vultures take it, if they will.",
  "",
  "_Stran._                            And if",
  "They do, and are not scared by it, you'll say",
  "It must be peace-time, and no better fare",
  "Abroad i' the fields.",
  "",
  "_Arn._               Let us but leave it there;",
  "No matter what becomes on't.",
  "",
  "_Stran._                    That's ungracious;",
  "If not ungrateful. Whatsoe'er it be,",
  "It hath sustained your soul full many a day.",
  "",
  "_Arn._ Aye, as the dunghill may conceal a gem",
  "Which is now set in gold, as jewels should be.",
  "",
  "_Stran._ But if I give another form, it must be",
  "By fair exchange, not robbery. For they",
  "Who make men without women's aid have long",
  "Had patents for the same, and do not love",
  "Your Interlopers. The Devil may take men,",
  "Not make them,--though he reap the benefit",
  "Of the original workmanship:--and therefore",
  "Some one must be found to assume the shape",
  "You have quitted.",
  "",
  "_Arn._            Who would do so?",
  "",
  "_Stran._                         That I know not,",
  "And therefore I must.",
  "",
  "_Arn._                You!",
  "",
  "_Stran._                  I said it ere",
  "You inhabited your present dome of beauty.",
  "",
  "_Arn._ True. I forget all things in the new joy",
  "Of this immortal change.",
  "",
  "_Stran._                In a few moments",
  "I will be as you were, and you shall see",
  "Yourself for ever by you, as your shadow.",
  "",
  "_Arn._ I would be spared this.",
  "",
  "_Stran._                       But it cannot be.",
  "What! shrink already, being what you are,",
  "From seeing what you were?",
  "",
  "_Arn._                    Do as thou wilt.",
  "",
  "_Stran._ (_to the late form of_ ARNOLD, _extended on the earth_).",
  "      Clay! not dead, but soul-less!",
  "        Though no man would choose thee,",
  "      An Immortal no less",
  "        Deigns not to refuse thee.",
  "      Clay thou art; and unto spirit",
  "      All clay is of equal merit.",
  "      Fire! _without_ which nought can live;",
  "      Fire! but _in_ which nought can live,",
  "        Save the fabled salamander,",
  "        Or immortal souls, which wander,",
  "      Praying what doth not forgive,",
  "      Howling for a drop of water,",
  "          Burning in a quenchless lot:",
  "      Fire! the only element",
  "        Where nor fish, beast, bird, nor worm,",
  "          Save the Worm which dieth not,",
  "        Can preserve a moment's form,",
  "      But must with thyself be blent:",
  "      Fire! man's safeguard and his slaughter:",
  "      Fire! Creation's first-born Daughter,",
  "        And Destruction's threatened Son,",
  "        When Heaven with the world hath done:",
  "      Fire! assist me to renew",
  "      Life in what lies in my view",
  "        Stiff and cold!",
  "      His resurrection rests with me and you!",
  "      One little, marshy spark of flame--",
  "      And he again shall seem the same;",
  "        But I his Spirit's place shall hold!",
  "",
  "                    [_An ignis-fatuus flits through the wood and rests",
  "                         on the brow of the body. The Stranger",
  "                         disappears: the body rises_.",
  "",
  "_Arn._ (_in his new form_). Oh! horrible!",
  "",
  "_Stran._ (_in_ ARNOLD'S _late shape_). What! tremblest thou?",
  "",
  "_Arn._                                   Not so--",
  "I merely shudder. Where is fled the shape",
  "Thou lately worest?",
  "",
  "_Stran._           To the world of shadows.",
  "But let us thread the present. Whither wilt thou?",
  "",
  "_Arn._ Must thou be my companion?",
  "",
  "_Stran._                          Wherefore not?",
  "Your betters keep worse company.",
  "",
  "_Arn._                          _My_ betters!",
  "",
  "_Stran._ Oh! you wax proud, I see, of your new form:",
  "I'm glad of that. Ungrateful too! That's well;",
  "You improve apace;--two changes in an instant,",
  "And you are old in the World's ways already.",
  "But bear with me: indeed you'll find me useful",
  "Upon your pilgrimage. But come, pronounce",
  "Where shall we now be errant?",
  "",
  "_Arn._                       Where the World",
  "Is thickest, that I may behold it in",
  "Its workings.",
  "",
  "_Stran._     That's to say, where there is War",
  "And Woman in activity. Let's see!",
  "Spain--Italy--the new Atlantic world--",
  "Afric with all its Moors. In very truth,",
  "There is small choice: the whole race are just now",
  "Tugging as usual at each other's hearts.",
  "",
  "_Arn._ I have heard great things of Rome.",
  "",
  "_Stran._                                  A goodly choice--",
  "And scarce a better to be found on earth,",
  "Since Sodom was put out. The field is wide too;",
  "For now the Frank, and Hun, and Spanish scion",
  "Of the old Vandals, are at play along",
  "The sunny shores of the World's garden.",
  "",
  "_Arn._                                 How",
  "Shall we proceed?",
  "",
  "_Stran._         Like gallants, on good coursers.",
  "What, ho! my chargers! Never yet were better,",
  "Since Phaeton was upset into the Po.",
  "Our pages too!",
  "",
  "         _Enter two Pages, with four coal-black horses_.",
  "",
  "_Arn._          A noble sight!",
  "",
  "_Stran._                      And of",
  "A nobler breed. Match me in Barbary,",
  "Or your Kochlini race of Araby,",
  "With these!",
  "",
  "_Arn._     The mighty steam, which volumes high",
  "From their proud nostrils, burns the very air;",
  "And sparks of flame, like dancing fire-flies wheel",
  "Around their manes, as common insects swarm",
  "Round common steeds towards sunset.",
  "",
  "_Stran._                           Mount, my lord:",
  "They and I are your servitors.",
  "",
  "_Arn._                        And these",
  "Our dark-eyed pages--what may be their names?",
  "",
  "_Stran._ You shall baptize them.",
  "",
  "_Arn._                           What! in holy water?",
  "",
  "_Stran._ Why not? The deeper sinner, better saint.",
  "",
  "_Arn._ They are beautiful, and cannot, sure, be demons.",
  "",
  "_Stran._ True; the devil's always ugly: and your beauty",
  "Is never diabolical.",
  "",
  "_Arn._               I'll call him",
  "Who bears the golden horn, and wears such bright",
  "And blooming aspect, _Huon_; for he looks",
  "Like to the lovely boy lost in the forest,",
  "And never found till now. And for the other",
  "And darker, and more thoughtful, who smiles not,",
  "But looks as serious though serene as night,",
  "He shall be _Memnon_, from the Ethiop king",
  "Whose statue turns a harper once a day.",
  "And you?",
  "",
  "_Stran._ I have ten thousand names, and twice",
  "As many attributes; but as I wear",
  "A human shape, will take a human name.",
  "",
  "_Arn._ More human than the shape (though it was mine once)",
  "I trust.",
  "",
  "_Stran._ Then call me Cæsar.",
  "",
  "_Arn._                       Why, that name",
  "Belongs to Empire, and has been but borne",
  "By the World's lords.",
  "",
  "_Stran._             And therefore fittest for",
  "The Devil in disguise--since so you deem me,",
  "Unless you call me Pope instead.",
  "",
  "_Arn._                           Well, then,",
  "Cæsar thou shalt be. For myself, my name",
  "Shall be plain Arnold still.",
  "",
  "_Cæs._                      We'll add a title--",
  "\"Count Arnold:\" it hath no ungracious sound,",
  "And will look well upon a billet-doux.",
  "",
  "_Arn._ Or in an order for a battle-field.",
  "",
  "_Cæs._ (_sings_).",
  "    To horse! to horse! my coal-black steed",
  "      Paws the ground and snuffs the air!",
  "    There's not a foal of Arab's breed",
  "      More knows whom he must bear;",
  "      On the hill he will not tire,",
  "      Swifter as it waxes higher;",
  "      In the marsh he will not slacken,",
  "      On the plain be overtaken;",
  "      In the wave he will not sink,",
  "      Nor pause at the brook's side to drink;",
  "      In the race he will not pant,",
  "      In the combat he'll not faint;",
  "      On the stones he will not stumble,",
  "      Time nor toil shall make him humble;",
  "      In the stall he will not stiffen,",
  "      But be wingèd as a Griffin,",
  "      Only flying with his feet:",
  "      And will not such a voyage be sweet?",
  "      Merrily! merrily! never unsound,",
  "      Shall our bonny black horses skim over the ground!",
  "    From the Alps to the Caucasus, ride we, or fly!",
  "    For we'll leave them behind in the glance of an eye.",
  "                            [_They mount their horses, and disappear_.",
  "",
  "SCENE II.--_A Camp before the walls of Rome_.",
  "",
  "                       ARNOLD _and_ CÆSAR.",
  "",
  "_Cæs._ You are well entered now.",
  "",
  "_Arn._                           Aye; but my path",
  "Has been o'er carcasses: mine eyes are full",
  "Of blood.",
  "",
  "_Cæs._    Then wipe them, and see clearly. Why!",
  "Thou art a conqueror; the chosen knight",
  "And free companion of the gallant Bourbon,",
  "Late constable of France; and now to be",
  "Lord of the city which hath been Earth's Lord",
  "Under its emperors, and--changing sex,",
  "Not sceptre, an Hermaphrodite of Empire--",
  "_Lady_ of the old world.",
  "",
  "_Arn._                       How _old?_ What! are there",
  "_New_ worlds?",
  "",
  "_Cæs._       To _you_. You'll find there are such shortly,",
  "By its rich harvests, new disease, and gold;",
  "From one _half_ of the world named a _whole_ new one,",
  "Because you know no better than the dull",
  "And dubious notice of your eyes and ears.",
  "",
  "_Arn._ I'll trust them.",
  "",
  "_Cæs._                  Do! They will deceive you sweetly,",
  "And that is better than the bitter truth.",
  "",
  "_Arn._ Dog!",
  "",
  "_Cæs._       Man!",
  "",
  "_Arn._            Devil!",
  "",
  "_Cæs._                  Your obedient humble servant.",
  "",
  "_Arn._ Say _master_ rather. Thou hast lured me on,",
  "Through scenes of blood and lust, till I am here.",
  "",
  "_Cæs._ And where wouldst thou be?",
  "",
  "_Arn._                           Oh, _at_ peace--_in_ peace!",
  "",
  "_Cæs._ And where is that which is so? From the star",
  "To the winding worm, all life is motion; and",
  "In life _commotion_ is the extremest point",
  "Of life. The planet wheels till it becomes",
  "A comet, and destroying as it sweeps",
  "The stars, goes out. The poor worm winds its way,",
  "Living upon the death of other things,",
  "But still, like them, must live and die, the subject",
  "Of something which has made it live and die.",
  "You must obey what all obey, the rule",
  "Of fixed Necessity: against her edict",
  "Rebellion prospers not.",
  "",
  "_Arn._                  And when it prospers----",
  "",
  "_Cæs._ 'Tis no rebellion.",
  "",
  "_Arn._                     Will it prosper now?",
  "",
  "_Cæs._ The Bourbon hath given orders for the assault,",
  "And by the dawn there will be work.",
  "",
  "_Arn._                              Alas!",
  "And shall the city yield? I see the giant",
  "Abode of the true God, and his true saint,",
  "Saint Peter, rear its dome and cross into",
  "That sky whence Christ ascended from the cross,",
  "Which his blood made a badge of glory and",
  "Of joy (as once of torture unto him),--",
  "God and God's Son, man's sole and only refuge!",
  "",
  "_Cæs._ 'Tis there, and shall be.",
  "",
  "_Arn._                            What?",
  "",
  "_Cæs._                                The Crucifix",
  "Above, and many altar shrines below.",
  "Also some culverins upon the walls,",
  "And harquebusses, and what not; besides",
  "The men who are to kindle them to death",
  "Of other men.",
  "",
  "_Arn._        And those scarce mortal arches,",
  "Pile above pile of everlasting wall,",
  "The theatre where Emperors and their subjects",
  "(Those subjects _Romans_) stood at gaze upon",
  "The battles of the monarchs of the wild",
  "And wood--the lion and his tusky rebels",
  "Of the then untamed desert, brought to joust",
  "In the arena--as right well they might,",
  "When they had left no human foe unconquered--",
  "Made even the forest pay its tribute of",
  "Life to their amphitheatre, as well",
  "As Dacia men to die the eternal death",
  "For a sole instant's pastime, and \"Pass on",
  "To a new gladiator!\"--Must it fall?",
  "",
  "_Cæs._ The city, or the amphitheatre?",
  "The church, or one, or all? for you confound",
  "Both them and me.",
  "",
  "_Arn._            To-morrow sounds the assault",
  "With the first cock-crow.",
  "",
  "_Cæs._                   Which, if it end with",
  "The evening's first nightingale, will be",
  "Something new in the annals of great sieges;",
  "For men must have their prey after long toil.",
  "",
  "_Arn._ The sun goes down as calmly, and perhaps",
  "More beautifully, than he did on Rome",
  "On the day Remus leapt her wall.",
  "",
  "_Cæs._                          I saw him.",
  "",
  "_Arn._ You!",
  "",
  "_Cæs._      Yes, Sir! You forget I am or was",
  "Spirit, till I took up with your cast shape,",
  "And a worse name. I'm Cæsar and a hunch-back",
  "Now. Well! the first of Cæsars was a bald-head,",
  "And loved his laurels better as a wig",
  "(So history says) than as a glory. Thus",
  "The world runs on, but we'll be merry still.",
  "I saw your Romulus (simple as I am)",
  "Slay his own twin, quick-born of the same womb,",
  "Because he leapt a ditch ('twas then no wall,",
  "Whate'er it now be); and Rome's earliest cement",
  "Was brother's blood; and if its native blood",
  "Be spilt till the choked Tiber be as red",
  "As e'er 'twas yellow, it will never wear",
  "The deep hue of the Ocean and the Earth,",
  "Which the great robber sons of fratricide",
  "Have made their never-ceasing scene of slaughter,",
  "For ages.",
  "",
  "_Arn._    But what have these done, their far",
  "Remote descendants, who have lived in peace,",
  "The peace of Heaven, and in her sunshine of",
  "Piety?",
  "",
  "_Cæs._ And what had _they_ done, whom the old",
  "Romans o'erswept?--Hark!",
  "",
  "_Arn._                   They are soldiers singing",
  "A reckless roundelay, upon the eve",
  "Of many deaths, it may be of their own.",
  "",
  "_Cæs._ And why should they not sing as well as swans?",
  "They are black ones, to be sure.",
  "",
  "_Arn._                          So, you are learned,",
  "I see, too?",
  "",
  "_Cæs._     In my grammar, certes. I",
  "Was educated for a monk of all times,",
  "And once I was well versed in the forgotten",
  "Etruscan letters, and--were I so minded--",
  "Could make their hieroglyphics plainer than",
  "Your alphabet.",
  "",
  "_Arn._         And wherefore do you not?",
  "",
  "_Cæs._ It answers better to resolve the alphabet",
  "Back into hieroglyphics. Like your statesman,",
  "And prophet, pontiff, doctor, alchymist,",
  "Philosopher, and what not, they have built",
  "More Babels, without new dispersion, than",
  "The stammering young ones of the flood's dull ooze,",
  "Who failed and fled each other. Why? why, marry,",
  "Because no man could understand his neighbour.",
  "They are wiser now, and will not separate",
  "For nonsense. Nay, it is their brotherhood,",
  "Their Shibboleth--their Koran--Talmud--their",
  "Cabala--their best brick-work, wherewithal",
  "They build more----",
  "",
  "_Arn._ (_interrupting him_). Oh, thou everlasting sneerer!",
  "Be silent! How the soldier's rough strain seems",
  "Softened by distance to a hymn-like cadence!",
  "Listen!",
  "",
  "_Cæs._ Yes. I have heard the angels sing.",
  "",
  "_Arn._ And demons howl.",
  "",
  "_Cæs._                 And man, too. Let us listen:",
  "I love all music.",
  "",
  "                 _Song of the Soldiers within_.",
  "",
  "            The black bands came over",
  "              The Alps and their snow;",
  "            With Bourbon, the rover,",
  "              They passed the broad Po.",
  "            We have beaten all foemen,",
  "              We have captured a King,",
  "            We have turned back on no men,",
  "              And so let us sing!",
  "            Here's the Bourbon for ever!",
  "              Though penniless all,",
  "            We'll have one more endeavour",
  "              At yonder old wall.",
  "            With the Bourbon we'll gather",
  "              At day-dawn before",
  "            The gates, and together",
  "              Or break or climb o'er",
  "            The wall: on the ladder,",
  "              As mounts each firm foot,",
  "            Our shout shall grow gladder,",
  "              And Death only be mute.",
  "            With the Bourbon we'll mount o'er",
  "              The walls of old Rome,",
  "            And who then shall count o'er",
  "              The spoils of each dome?",
  "            Up! up with the Lily!",
  "              And down with the Keys!",
  "            In old Rome, the seven-hilly,",
  "              We'll revel at ease.",
  "            Her streets shall be gory,",
  "              Her Tiber all red,",
  "            And her temples so hoary",
  "              Shall clang with our tread.",
  "            Oh, the Bourbon! the Bourbon!",
  "              The Bourbon for aye!",
  "            Of our song bear the burden!",
  "              And fire, fire away!",
  "            With Spain for the vanguard,",
  "              Our varied host comes;",
  "            And next to the Spaniard",
  "              Beat Germany's drums;",
  "            And Italy's lances",
  "              Are couched at their mother;",
  "            But our leader from France is,",
  "              Who warred with his brother.",
  "            Oh, the Bourbon! the Bourbon!",
  "              Sans country or home,",
  "            We'll follow the Bourbon,",
  "              To plunder old Rome.",
  "",
  "_Cæs._           An indifferent song",
  "For those within the walls, methinks, to hear.",
  "",
  "_Arn._ Yes, if they keep to their chorus. But here comes",
  "The general with his chiefs and men of trust.",
  "A goodly rebel.",
  "",
  "      _Enter the Constable_ BOURBON _\"cum suis,\" etc., etc._",
  "",
  "_Phil._          How now, noble Prince,",
  "You are not cheerful?",
  "",
  "_Bourb._             Why should I be so?",
  "",
  "_Phil._ Upon the eve of conquest, such as ours,",
  "Most men would be so.",
  "",
  "_Bourb._               If I were secure!",
  "",
  "_Phil._ Doubt not our soldiers. Were the walls of adamant,",
  "They'd crack them. Hunger is a sharp artillery.",
  "",
  "_Bourb._ That they will falter is my least of fears.",
  "That they will be repulsed, with Bourbon for",
  "Their chief, and all their kindled appetites",
  "To marshal them on--were those hoary walls",
  "Mountains, and those who guard them like the gods",
  "Of the old fables, I would trust my Titans;--",
  "But now----",
  "",
  "_Phil._    They are but men who war with mortals.",
  "",
  "_Bourb._ True: but those walls have girded in great ages,",
  "And sent forth mighty spirits. The past earth",
  "And present phantom of imperious Rome",
  "Is peopled with those warriors; and methinks",
  "They flit along the eternal City's rampart,",
  "And stretch their glorious, gory, shadowy hands,",
  "And beckon me away!",
  "",
  "_Phil._            So let them! Wilt thou",
  "Turn back from shadowy menaces of shadows?",
  "",
  "_Bourb._ They do not menace me. I could have faced,",
  "Methinks, a Sylla's menace; but they clasp,",
  "And raise, and wring their dim and deathlike hands,",
  "And with their thin aspen faces and fixed eyes",
  "Fascinate mine. Look there!",
  "",
  "_Phil._                    I look upon",
  "A lofty battlement.",
  "",
  "_Bourb._            And there!",
  "",
  "_Phil._                       Not even",
  "A guard in sight; they wisely keep below,",
  "Sheltered by the grey parapet from some",
  "Stray bullet of our lansquenets, who might",
  "Practise in the cool twilight.",
  "",
  "_Bourb._                      You are blind.",
  "",
  "_Phil._ If seeing nothing more than may be seen",
  "Be so.",
  "",
  "_Bourb._ A thousand years have manned the walls",
  "With all their heroes,--the last Cato stands",
  "And tears his bowels, rather than survive",
  "The liberty of that I would enslave.",
  "And the first Cassar with his triumphs flits",
  "From battlement to battlement.",
  "",
  "_Phil._                        Then conquer",
  "The walls for which he conquered and be greater!",
  "",
  "_Bourb._ True: so I will, or perish.",
  "",
  "_Phil._                              You can _not_.",
  "In such an enterprise to die is rather",
  "The dawn of an eternal day, than death.",
  "                               [_Count_ ARNOLD _and_ CÆSAR _advance_.",
  "",
  "_Cæs._ And the mere men--do they, too, sweat beneath",
  "The noon of this same ever-scorching glory?",
  "",
  "_Bourb._                                   Ah!",
  "Welcome the bitter Hunchback! and his master,",
  "The beauty of our host, and brave as beauteous,",
  "And generous as lovely. We shall find",
  "Work for you both ere morning.",
  "",
  "_Cæs._                        You will find,",
  "So please your Highness, no less for yourself.",
  "",
  "_Bourb._ And if I do, there will not be a labourer",
  "More forward, Hunchback!",
  "",
  "_Cæs._                  You may well say so,",
  "For _you_ have seen that back--as general,",
  "Placed in the rear in action--but your foes",
  "Have never seen it.",
  "",
  "_Bourb._           That's a fair retort,",
  "For I provoked it:--but the Bourbon's breast",
  "Has been, and ever shall be, far advanced",
  "In danger's face as yours, were you the _devil_.",
  "",
  "_Cæs._ And if I were, I might have saved myself",
  "The toil of coming here.",
  "",
  "_Phil._                 Why so?",
  "",
  "_Cæs._                         One half",
  "Of your brave bands of their own bold accord",
  "Will go to him, the other half be sent,",
  "More swiftly, not less surely.",
  "",
  "_Bourb._                      Arnold, your",
  "Slight crooked _friend's_ as snake-like in his words",
  "As his deeds.",
  "",
  "_Cæs._        Your Highness much mistakes me.",
  "The first snake was a flatterer--I am none;",
  "And for my deeds, I only sting when stung.",
  "",
  "_Bourb._ You are brave, and _that's_ enough for me; and quick",
  "In speech as sharp in action--and that's more.",
  "I am not alone the soldier, but the soldiers'",
  "Comrade.",
  "",
  "_Cæs._   They are but bad company, your Highness;",
  "And worse even for their friends than foes, as being",
  "More permanent acquaintance.",
  "",
  "_Phil._                      How now, fellow!",
  "Thou waxest insolent, beyond the privilege",
  "Of a buffoon.",
  "",
  "_Cæs._       You mean I speak the truth.",
  "I'll lie--it is as easy: then you'll praise me",
  "For calling you a hero.",
  "",
  "_Bourb._               Philibert!",
  "Let him alone; he's brave, and ever has",
  "Been first, with that swart face and mountain shoulder,",
  "In field or storm, and patient in starvation;",
  "And for his tongue, the camp is full of licence,",
  "And the sharp stinging of a lively rogue",
  "Is, to my mind, far preferable to",
  "The gross, dull, heavy, gloomy execration",
  "Of a mere famished sullen grumbling slave,",
  "Whom nothing can convince save a full meal,",
  "And wine, and sleep, and a few Maravedis,",
  "With which he deems him rich.",
  "",
  "_Cæs._                        It would be well",
  "If the earth's princes asked no more.",
  "",
  "_Bourb._                             Be silent!",
  "",
  "_Cæs._ Aye, but not idle. Work yourself with words!",
  "You have few to speak.",
  "",
  "_Phil._                What means the audacious prater?",
  "",
  "_Cæs._ To prate, like other prophets.",
  "",
  "_Bourb._                              Philibert!",
  "Why will you vex him? Have we not enough",
  "To think on? Arnold! I will lead the attack",
  "To-morrow.",
  "",
  "_Arn._     I have heard as much, my Lord.",
  "",
  "_Bourb._ And you will follow?",
  "",
  "_Arn._                        Since I must not lead.",
  "",
  "_Bourb._ 'Tis necessary for the further daring",
  "Of our too needy army, that their chief",
  "Plant the first foot upon the foremost ladder's",
  "First step.",
  "",
  "_Cæs._      Upon its topmost, let us hope:",
  "So shall he have his full deserts.",
  "",
  "_Bourb._                          The world's",
  "Great capital perchance is ours to-morrow.",
  "Through every change the seven-hilled city hath",
  "Retained her sway o'er nations, and the Cæsars",
  "But yielded to the Alarics, the Alarics",
  "Unto the pontiffs. Roman, Goth, or priest.",
  "Still the world's masters! Civilised, barbarian,",
  "Or saintly, still the walls of Romulus",
  "Have been the circus of an Empire. Well!",
  "'Twas _their_ turn--now 'tis ours; and let us hope",
  "That we will fight as well, and rule much better.",
  "",
  "_Cæs._ No doubt, the camp's the school of civic rights.",
  "What would you make of Rome?",
  "",
  "_Bourb._                    That which it was.",
  "",
  "_Cæs._ In Alaric's time?",
  "",
  "_Bourb._                 No, slave! in the first Cæsar's,",
  "Whose name you bear like other curs----",
  "",
  "_Cæs._                             And kings!",
  "'Tis a great name for blood-hounds.",
  "",
  "_Bourb._                           There's a demon",
  "In that fierce rattlesnake thy tongue. Wilt never",
  "Be serious?",
  "",
  "_Cæs._      On the eve of battle, no;--",
  "That were not soldier-like. 'Tis for the general",
  "To be more pensive: we adventurers",
  "Must be more cheerful. Wherefore should we think?",
  "Our tutelar Deity, in a leader's shape,",
  "Takes care of us. Keep thought aloof from hosts!",
  "If the knaves take to thinking, you will have",
  "To crack those walls alone.",
  "",
  "_Bourb._                    You may sneer, since",
  "'Tis lucky for you that you fight no worse for 't.",
  "",
  "_Cæs._ I thank you for the freedom; 'tis the only",
  "Pay I have taken in your Highness' service.",
  "",
  "_Bourb._ Well, sir, to-morrow you shall pay yourself.",
  "Look on those towers; they hold my treasury:",
  "But, Philibert, we'll in to council. Arnold,",
  "We would request your presence.",
  "",
  "_Arn._                          Prince! my service",
  "Is yours, as in the field.",
  "",
  "_Bourb._                   In both we prize it,",
  "And yours will be a post of trust at daybreak.",
  "",
  "_Cæs._ And mine?",
  "",
  "_Bourb._         To follow glory with the Bourbon.",
  "Good night!",
  "",
  "_Arn._ (_to_ CÆSAR). Prepare our armour for the assault,",
  "And wait within my tent.",
  "                          [_Exeunt_ BOURBON, ARNOLD, PHILIBERT, _etc._",
  "",
  "_Cæs._ (_solus_).       Within thy tent!",
  "Think'st thou that I pass from thee with my presence?",
  "Or that this crooked coffer, which contained",
  "Thy principle of life, is aught to me",
  "Except a mask? And these are men, forsooth!",
  "Heroes and chiefs, the flower of Adam's bastards!",
  "This is the consequence of giving matter",
  "The power of thought. It is a stubborn substance,",
  "And thinks chaotically, as it acts,",
  "Ever relapsing into its first elements.",
  "Well! I must play with these poor puppets: 'tis",
  "The Spirit's pastime in his idler hours.",
  "When I grow weary of it, I have business",
  "Amongst the stars, which these poor creatures deem",
  "Were made for them to look at. 'Twere a jest now",
  "To bring one down amongst them, and set fire",
  "Unto their anthill: how the pismires then",
  "Would scamper o'er the scalding soil, and, ceasing",
  "From tearing down each other's nests, pipe forth",
  "One universal orison! ha! ha!                          [_Exit_ CÆSAR.",
  "",
  "PART II.",
  "",
  "SCENE I.--_Before the walls of Rome.--The Assault: the",
  "      Army in motion, with ladders to scale the walls_;",
  "     BOURBON _with a white scarf over his armour, foremost_.",
  "",
  "                 _Chorus of Spirits in the air_.",
  "",
  "'Tis the morn, but dim and dark.",
  "Whither flies the silent lark?",
  "Whither shrinks the clouded sun?",
  "Is the day indeed begun?",
  "Nature's eye is melancholy",
  "O'er the city high and holy:",
  "But without there is a din",
  "Should arouse the saints within,",
  "And revive the heroic ashes",
  "Round which yellow Tiber dashes.",
  "Oh, ye seven hills! awaken,",
  "Ere your very base be shaken!",
  "",
  "Hearken to the steady stamp!",
  "Mars is in their every tramp!",
  "Not a step is out of tune,",
  "As the tides obey the moon!",
  "On they march, though to self-slaughter,",
  "Regular as rolling water,",
  "Whose high-waves o'ersweep the border",
  "Of huge moles, but keep their order,",
  "Breaking only rank by rank.",
  "Hearken to the armour's clank!",
  "Look down o'er each frowning warrior,",
  "How he glares upon the barrier:",
  "Look on each step of each ladder,",
  "As the stripes that streak an adder.",
  "",
  "Look upon the bristling wall,",
  "Manned without an interval!",
  "Round and round, and tier on tier,",
  "Cannon's black mouth, shining spear,",
  "Lit match, bell-mouthed Musquetoon,",
  "Gaping to be murderous soon;",
  "All the warlike gear of old,",
  "Mixed with what we now behold,",
  "In this strife 'twixt old and new,",
  "Gather like a locusts' crew.",
  "Shade of Remus! 'tis a time",
  "Awful as thy brother's crime!",
  "Christians war against Christ's shrine:--",
  "Must its lot be like to thine?",
  "",
  "Near--and near--and nearer still,",
  "As the Earthquake saps the hill,",
  "First with trembling, hollow motion,",
  "Like a scarce awakened ocean,",
  "Then with stronger shock and louder,",
  "Till the rocks are crushed to powder,--",
  "Onward sweeps the rolling host!",
  "Heroes of the immortal boast!",
  "Mighty Chiefs! eternal shadows!",
  "First flowers of the bloody meadows",
  "Which encompass Rome, the mother",
  "Of a people without brother!",
  "Will you sleep when nations' quarrels",
  "Plough the root up of your laurels?",
  "Ye who weep o'er Carthage burning,",
  "Weep not--_strike_! for Rome is mourning!",
  "",
  "Onward sweep the varied nations!",
  "Famine long hath dealt their rations.",
  "To the wall, with hate and hunger,",
  "Numerous as wolves, and stronger,",
  "On they sweep. Oh, glorious City!",
  "Must thou be a theme for pity?",
  "Fight, like your first sire, each Roman!",
  "Alaric was a gentle foeman,",
  "Matched with Bourbon's black banditti!",
  "Rouse thee, thou eternal City;",
  "Rouse thee! Rather give the torch",
  "With thine own hand to thy porch,",
  "Than behold such hosts pollute",
  "Your worst dwelling with their foot.",
  "",
  "Ah! behold yon bleeding spectre!",
  "Ilion's children find no Hector;",
  "Priam's offspring loved their brother;",
  "Rome's great sire forgot his mother,",
  "When he slew his gallant twin,",
  "With inexpiable sin.",
  "See the giant shadow stride",
  "O'er the ramparts high and wide!",
  "When the first o'erleapt thy wall,",
  "Its foundation mourned thy fall.",
  "Now, though towering like a Babel,",
  "Who to stop his steps are able?",
  "Stalking o'er thy highest dome,",
  "Remus claims his vengeance, Rome!",
  "",
  "Now they reach thee in their anger:",
  "Fire and smoke and hellish clangour",
  "Are around thee, thou world's wonder!",
  "Death is in thy walls and under.",
  "Now the meeting steel first clashes,",
  "Downward then the ladder crashes,",
  "With its iron load all gleaming,",
  "Lying at its foot blaspheming!",
  "Up again! for every warrior",
  "Slain, another climbs the barrier.",
  "Thicker grows the strife: thy ditches",
  "Europe's mingling gore enriches.",
  "Rome! although thy wall may perish,",
  "Such manure thy fields will cherish,",
  "Making gay the harvest-home;",
  "But thy hearths, alas! oh, Rome!--",
  "Yet be Rome amidst thine anguish,",
  "Fight as thou wast wont to vanquish!",
  "",
  "Yet once more, ye old Penates!",
  "Let not your quenched hearts be Atés!",
  "Yet again, ye shadowy Heroes,",
  "Yield not to these stranger Neros!",
  "Though the son who slew his mother",
  "Shed Rome's blood, he was your brother:",
  "'Twas the Roman curbed the Roman;--",
  "Brennus was a baffled foeman.",
  "Yet again, ye saints and martyrs,",
  "Rise! for yours are holier charters!",
  "Mighty Gods of temples falling,",
  "Yet in ruin still appalling!",
  "Mightier Founders of those altars,",
  "True and Christian,--strike the assaulters!",
  "Tiber! Tiber! let thy torrent",
  "Show even Nature's self abhorrent.",
  "Let each breathing heart dilated",
  "Turn, as doth the lion baited!",
  "Rome be crashed to one wide tomb,",
  "But be still the Roman's Rome!",
  "",
  "             [BOURBON, ARNOLD, CÆSAR, _and others, arrive at the foot",
  "                  of the wall_. ARNOLD _is about to plant his ladder_.",
  "",
  "_Bourb._ Hold, Arnold! I am first.",
  "",
  "_Arn._                             Not so, my Lord.",
  "",
  "_Bourb._ Hold, sir, I charge you! Follow! I am proud",
  "Of such a follower, but will brook no leader.",
  "                    [BOURBON _plants his ladder, and begins to mount_.",
  "Now, boys! On! on!",
  "                           [_A shot strikes him, and_ BOURBON _falls_.",
  "",
  "_Cæs._             And off!",
  "",
  "_Arn._                     Eternal powers!",
  "The host will be appalled,--but vengeance! vengeance!",
  "",
  "_Bourb._ 'Tis nothing--lend me your hand.",
  "",
  "                  [BOURBON _takes_ ARNOLD _by the hand, and rises; but",
  "                        as he puts his foot on the step, falls again_.",
  "",
  "                                       Arnold! I am sped.",
  "Conceal my fall--all will go well--conceal it!",
  "Fling my cloak o'er what will be dust anon;",
  "Let not the soldiers see it.",
  "",
  "_Arn._                     You must be",
  "Removed; the aid of----",
  "",
  "_Bourb._                No, my gallant boy!",
  "Death is upon me. But what is _one_ life?",
  "The Bourbon's spirit shall command them still.",
  "Keep them yet ignorant that I am but clay,",
  "Till they are conquerors--then do as you may.",
  "",
  "_Cæs._ Would not your Highness choose to kiss the cross?",
  "We have no priest here, but the hilt of sword",
  "May serve instead:--it did the same for Bayard.",
  "",
  "_Bourb._ Thou bitter slave! to name _him_ at this time!",
  "But I deserve it.",
  "",
  "_Arn._ (_to_ CÆSAR). Villain, hold your peace!",
  "",
  "_Cæs._ What, when a Christian dies? Shall I not offer",
  "A Christian \"Vade in pace?\"",
  "",
  "_Arn._                        Silence! Oh!",
  "Those eyes are glazing which o'erlooked the world,",
  "And saw no equal.",
  "",
  "_Bourb._          Arnold, shouldst thou see",
  "France----But hark! hark! the assault grows warmer--Oh!",
  "For but an hour, a minute more of life,",
  "To die within the wall! Hence, Arnold, hence!",
  "You lose time--they will conquer Rome without thee.",
  "",
  "_Arn._ And without _thee_.",
  "",
  "_Bourb._                   Not so; I'll lead them still",
  "In spirit. Cover up my dust, and breathe not",
  "That I have ceased to breathe. Away! and be",
  "Victorious.",
  "",
  "_Arn._      But I must not leave thee thus.",
  "",
  "_Bourb._ You must--farewell--Up! up! the world is winning.",
  "                                                      [BOURBON _dies_.",
  "",
  "_Cæs._ (_to_ ARNOLD). Come, Count, to business.",
  "",
  "_Arn._                      True. I'll weep hereafter.",
  "",
  "                       [ARNOLD _covers_ BOURBON'S _body with a mantle,",
  "                            mounts the ladder, crying_",
  "",
  "The Bourbon! Bourbon! On, boys! Rome is ours!",
  "",
  "_Cæs._ Good night, Lord Constable! thou wert a Man.",
  "",
  "                [CÆSAR _follows_ ARNOLD; _they reach the battlement;_",
  "                    ARNOLD _and_ CÆSAR _are struck down_.",
  "",
  "_Cæs._ A precious somerset! Is your countship injured?",
  "",
  "_Arn._ No.                                     [_Remounts the ladder_.",
  "",
  "_Cæs._ A rare blood-hound, when his own is heated!",
  "And 'tis no boy's play. Now he strikes them down!",
  "His hand is on the battlement--he grasps it",
  "As though it were an altar; now his foot",
  "Is on it, and----What have we here?--a Roman?",
  "The first bird of the covey! he has fallen             [_A man falls_.",
  "On the outside of the nest. Why, how now, fellow?",
  "",
  "_Wounded Man_. A drop of water!",
  "",
  "_Cæs._                         Blood's the only liquid",
  "Nearer than Tiber.",
  "",
  "_Wounded Man_. I have died for Rome.                          [_Dies_.",
  "",
  "_Cæs._ And so did Bourbon, in another sense.",
  "Oh, these immortal men! and their great motives!",
  "But I must after my young charge. He is",
  "By this time i' the Forum. Charge! charge!",
  "                        [CÆSAR _mounts the ladder; the scene closes_.",
  "",
  "SCENE II.--_The City_.--_Combats between the Besiegers",
  " and Besieged in the streets_. _Inhabitants flying in confusion_.",
  "",
  "                         _Enter_ CÆSAR.",
  "",
  "_Cæs._ I cannot find my hero; he is mixed",
  "With the heroic crowd that now pursue",
  "The fugitives, or battle with the desperate.",
  "What have we here? A Cardinal or two",
  "That do not seem in love with martyrdom.",
  "How the old red-shanks scamper! Could they doff",
  "Their hose as they have doffed their hats, 'twould be",
  "A blessing, as a mark the less for plunder.",
  "But let them fly; the crimson kennels now",
  "Will not much stain their stockings, since the mire",
  "Is of the self-same purple hue.",
  "",
  " _Enter a Party fighting_--ARNOLD _at the head of the Besiegers_.",
  "",
  "                               He comes,",
  "Hand in hand with the mild twins--Gore and Glory.",
  "Holla! hold, Count!",
  "",
  "_Arn._              Away! they must not rally.",
  "",
  "_Cæs._ I tell thee, be not rash; a golden bridge",
  "Is for a flying enemy. I gave thee",
  "A form of beauty, and an",
  "Exemption from some maladies of body,",
  "But not of mind, which is not mine to give.",
  "But though I gave the form of Thetis' son,",
  "I dipped thee not in Styx; and 'gainst a foe",
  "I would not warrant thy chivalric heart",
  "More than Pelides' heel; why, then, be cautious,",
  "And know thyself a mortal still.",
  "",
  "_Arn._                          And who",
  "With aught of soul would combat if he were",
  "Invulnerable? That were pretty sport.",
  "Think'st thou I beat for hares when lions roar?",
  "                                     [ARNOLD _rushes into the combat_.",
  "",
  "_Cæs._ A precious sample of humanity!",
  "Well, his blood's up; and, if a little's shed,",
  "'Twill serve to curb his fever.",
  "",
  "                            [ARNOLD _engages with a Roman, who retires",
  "                                towards a portico_.",
  "",
  "_Arn._                          Yield thee, slave!",
  "I promise quarter.",
  "",
  "_Rom._            That's soon said.",
  "",
  "_Arn._                              And done----",
  "My word is known.",
  "",
  "_Rom._           So shall be my deeds.",
  "                            [_They re-engage_. CÆSAR _comes forward_.",
  "",
  "_Cæs._ Why, Arnold! hold thine own: thou hast in hand",
  "A famous artisan, a cunning sculptor;",
  "Also a dealer in the sword and dagger.",
  "Not so, my musqueteer; 'twas he who slew",
  "The Bourbon from the wall.",
  "",
  "_Arn._                     Aye, did he so?",
  "Then he hath carved his monument.",
  "",
  "_Rom._                           I yet",
  "May live to carve your better's.",
  "",
  "_Cæs._ Well said, my man of marble! Benvenuto,",
  "Thou hast some practice in both ways; and he",
  "Who slays Cellini will have worked as hard",
  "As e'er thou didst upon Carrara's blocks.",
  "",
  "                  [ARNOLD _disarms and wounds_ CELLINI, _hit slightly:",
  "                      the latter draws a pistol, and fires; then",
  "                      retires, and disappears through the portico_.",
  "",
  "_Cæs._ How farest thou? Thou hast a taste, methinks,",
  "Of red Bellona's banquet.",
  "",
  "_Arn._ (_staggers_). 'Tis a scratch.",
  "Lend me thy scarf. He shall not 'scape me thus.",
  "",
  "_Cæs._ Where is it?",
  "",
  "_Arn._             In the shoulder, not the sword arm--",
  "And that's enough. I am thirsty: would I had",
  "A helm of water!",
  "",
  "_Cæs._           That's a liquid now",
  "In requisition, but by no means easiest",
  "To come at.",
  "",
  "_Arn._      And my thirst increases;--but",
  "I'll find a way to quench it.",
  "",
  "_Cæs._                       Or be quenched",
  "Thyself.",
  "",
  "_Arn._   The chance is even; we will throw",
  "The dice thereon. But I lose time in prating;",
  "Prithee be quick.                        [CÆSAR _binds on the scarf_.",
  "                 And what dost thou so idly?",
  "Why dost not strike?",
  "",
  "_Cæs._              Your old philosophers",
  "Beheld mankind, as mere spectators of",
  "The Olympic games. When I behold a prize",
  "Worth wrestling for, I may be found a Milo.",
  "",
  "_Arn._ Aye, 'gainst an oak.",
  "",
  "_Cæs._                    A forest, when it suits me:",
  "I combat with a mass, or not at all.",
  "Meantime, pursue thy sport as I do mine;",
  "Which is just now to gaze, since all these labourers",
  "Will reap my harvest gratis.",
  "",
  "_Arn._                       Thou art still",
  "A fiend!",
  "",
  "_Cæs._   And thou--a man.",
  "",
  "_Arn._ Why, such I fain would show me.",
  "",
  "_Cæs._                                 True--as men are.",
  "",
  "_Arn._ And what is that?",
  "",
  "_Cæs._                  Thou feelest and thou see'st.",
  "",
  "                    [_Exit_ ARNOLD, _joining in the combat which still",
  "                       continues between detached parties. The",
  "                       scene closes_.",
  "",
  "SCENE III.--_St. Peter's--The interior of the Church--The",
  "     Pope at the Altar--Priests, etc., crowding in confusion,",
  "      and Citizens flying for refuge, pursued by Soldiery_.",
  "",
  "                         _Enter_ CÆSAR.",
  "",
  "_A Spanish Soldier_. Down with them, comrades, seize upon those lamps!",
  "Cleave yon bald-pated shaveling to the chine!",
  "His rosary's of gold!",
  "",
  "_Lutheran Soldier_. Revenge! revenge!",
  "Plunder hereafter, but for vengeance now--",
  "Yonder stands Anti-Christ!",
  "",
  "_Cæs._ (_interposing_).    How now, schismatic?",
  "What wouldst thou?",
  "",
  "_Luth. Sold._      In the holy name of Christ,",
  "Destroy proud Anti-Christ. I am a Christian.",
  "",
  "_Cæs._ Yea, a disciple that would make the founder",
  "Of your belief renounce it, could he see",
  "Such proselytes. Best stint thyself to plunder.",
  "",
  "_Luth. Sold._ I say he is the Devil.",
  "",
  "_Cæs._                               Hush! keep that secret,",
  "Lest he should recognise you for his own.",
  "",
  "_Luth. Sold._ Why would you save him? I repeat he is",
  "The Devil, or the Devil's vicar upon earth.",
  "",
  "_Cæs._ And that's the reason: would you make a quarrel",
  "With your best friends? You had far best be quiet;",
  "His hour is not yet come.",
  "",
  "_Luth. Sold._            That shall be seen!",
  "",
  "                         [_The Lutheran Soldier rushes forward: a shot",
  "                            strikes him from one of the Pope's Guards,",
  "                            and he falls at the foot of the Altar_.",
  "",
  "_Cæs._ (_to the Lutheran_). I told you so.",
  "",
  "_Luth. Sold._               And will you not avenge me?",
  "",
  "_Cæs._ Not I! You know that \"Vengeance is the Lord's:\"",
  "You see he loves no interlopers.",
  "",
  "_Luth. Sold._ (_dying_).         Oh!",
  "Had I but slain him, I had gone on high,",
  "Crowned with eternal glory! Heaven, forgive",
  "My feebleness of arm that reached him not,",
  "And take thy servant to thy mercy. 'Tis",
  "A glorious triumph still; proud Babylon's",
  "No more; the Harlot of the Seven Hills",
  "Hath changed her scarlet raiment for sackcloth",
  "And ashes!                                       [_The Lutheran dies_.",
  "",
  "_Cæs._     Yes, thine own amidst the rest.",
  "Well done, old Babel!",
  "",
  "                 [_The Guards defend themselves desperately, while the",
  "                       Pontiff escapes, by a private passage, to the",
  "                       Vatican and the Castle of St. Angelo_.",
  "",
  "_Cæs._                Ha! right nobly battled!",
  "Now, priest! now, soldier! the two great professions,",
  "Together by the ears and hearts! I have not",
  "Seen a more comic pantomime since Titus",
  "Took Jewry. But the Romans had the best then;",
  "Now they must take their turn.",
  "",
  "_Soldiers_.                   He hath escaped!",
  "Follow!",
  "",
  "_Another Sold._ They have barred the narrow passage up,",
  "And it is clogged with dead even to the door.",
  "",
  "_Cæs._ I am glad he hath escaped: he may thank me for't",
  "In part. I would not have his bulls abolished--",
  "'Twere worth one half our empire: his indulgences",
  "Demand some in return; no, no, he must not",
  "Fall;--and besides, his now escape may furnish",
  "A future miracle, in future proof",
  "Of his infallibility.                      [_To the Spanish Soldiery_.",
  "                     Well, cut-throats!",
  "What do you pause for? If you make not haste,",
  "There will not be a link of pious gold left.",
  "And _you_, too, Catholics! Would ye return",
  "From such a pilgrimage without a relic?",
  "The very Lutherans have more true devotion:",
  "See how they strip the shrines!",
  "",
  "_Soldiers_.                    By holy Peter!",
  "He speaks the truth; the heretics will bear",
  "The best away.",
  "",
  "_Cæs._         And that were shame! Go to!",
  "Assist in their conversion.",
  "         [_The Soldiers disperse; many quit the Church, others enter_.",
  "",
  "_Cæs._                     They are gone,",
  "And others come: so flows the wave on wave",
  "Of what these creatures call Eternity,",
  "Deeming themselves the breakers of the Ocean,",
  "While they are but its bubbles, ignorant",
  "That foam is their foundation. So, another!",
  "",
  "          _Enter_ OLIMPIA, _flying from the pursuit--She",
  "                     springs upon the Altar_.",
  "",
  "_Sold._ She's mine!",
  "",
  "_Another Sold._ (_opposing the former_).",
  "                   You lie, I tracked her first: and were she",
  "The Pope's niece, I'll not yield her.                   [_They fight_.",
  "",
  "_3d Sold._ (_advancing towards_ OLIMPIA). You may settle",
  "Your claims; I'll make mine good.",
  "",
  "_Olimp._                          Infernal slave!",
  "You touch me not alive.",
  "",
  "_3d Sold._             Alive or dead!",
  "",
  "_Olimp._ (_embracing a massive crucifix_). Respect your God!",
  "",
  "_3d Sold._ Yes, when he shines in gold.",
  "Girl, you but grasp your dowry.",
  "",
  "                 [_As he advances_, OLIMPIA, _with a strong and sudden",
  "                       effort, casts down the crucifix; it strikes the",
  "                       Soldier, who falls_.",
  "",
  "_3d Sold._                     Oh, great God!",
  "",
  "_Olimp._ Ah! now you recognise him.",
  "",
  "_3d Sold._                          My brain's crushed!",
  "Comrades, help, ho! All's darkness!                          [He dies.",
  "",
  "_Other Soldiers_ (_coming up_).",
  "Slay her, although she had a thousand lives:",
  "She hath killed our comrade.",
  "",
  "_Olimp._                     Welcome such a death!",
  "You have no life to give, which the worst slave",
  "Would take. Great God! through thy redeeming Son,",
  "And thy Son's Mother, now receive me as",
  "I would approach thee, worthy her, and him, and thee!",
  "",
  "                         _Enter_ ARNOLD.",
  "",
  "_Arn._ What do I see? Accurséd jackals! Forbear!",
  "",
  "_Cæs._ (_aside and laughing_). Ha! ha! here's equity! The dogs",
  "Have as much right as he. But to the issue!",
  "",
  "_Soldiers_. Count, she hath slain our comrade.",
  "",
  "_Arn._                                         With what weapon?",
  "",
  "_Sold._ The cross, beneath which he is crushed; behold him",
  "Lie there, more like a worm than man; she cast it",
  "Upon his head.",
  "",
  "_Arn._        Even so: there is a woman",
  "Worthy a brave man's liking. Were ye such,",
  "Ye would have honoured her. But get ye hence,",
  "And thank your meanness, other God you have none,",
  "For your existence. Had you touched a hair",
  "Of those dishevelled locks, I would have thinned",
  "Your ranks more than the enemy. Away!",
  "Ye jackals! gnaw the bones the lion leaves,",
  "But not even these till he permits.",
  "",
  "_A Sold._ (_murmuring_).            The lion",
  "Might conquer for himself then.",
  "",
  "_Arn._ (_cuts him down_).      Mutineer!",
  "Rebel in hell--you shall obey on earth!",
  "                                       [_The Soldiers assault_ ARNOLD.",
  "",
  "_Arn._ Come on! I'm glad on't! I will show you, slaves,",
  "How you should be commanded, and who led you",
  "First o'er the wall you were so shy to scale,",
  "Until I waved my banners from its height,",
  "As you are bold within it.",
  "     [ARNOLD _mows down the foremost; the rest throw down their arms_.",
  "",
  "_Soldiers_.                Mercy! mercy!",
  "",
  "_Arn._ Then learn to grant it. Have I taught you _who_",
  "Led you o'er Rome's eternal battlements?",
  "",
  "_Soldiers_. We saw it, and we know it; yet forgive",
  "A moment's error in the heat of conquest--",
  "The conquest which you led to.",
  "",
  "_Arn._                        Get you hence!",
  "Hence to your quarters! you will find them fixed",
  "In the Colonna palace.",
  "",
  "_Olimp._ (_aside_).   In my father's",
  "House!",
  "",
  "_Arn._ (_to the Soldiers_). Leave your arms; ye have no further need",
  "Of such: the city's rendered. And mark well",
  "You keep your hands clean, or I'll find out a stream",
  "As red as Tiber now runs, for your baptism.",
  "",
  "_Soldiers_ (_deposing their arms and departing_). We obey!",
  "",
  "_Arn._ (_to_ OLIMPIA). Lady, you are safe.",
  "",
  "_Olimp._                                  I should be so,",
  "Had I a knife even; but it matters not--",
  "Death hath a thousand gates; and on the marble,",
  "Even at the altar foot, whence I look down",
  "Upon destruction, shall my head be dashed,",
  "Ere thou ascend it. God forgive thee, man!",
  "",
  "_Arn._ I wish to merit his forgiveness, and",
  "Thine own, although I have not injured thee.",
  "",
  "_Olimp._ No! Thou hast only sacked my native land,--",
  "No injury!--and made my father's house",
  "A den of thieves! No injury!--this temple--",
  "Slippery with Roman and with holy gore!",
  "No injury! And now thou wouldst preserve me,",
  "To be----but that shall never be!",
  "",
  "            [_She raises her eyes to Heaven, folds her robe round her,",
  "                  and prepares to dash herself down on the side of",
  "                  the Altar opposite to that where_ ARNOLD _stands_.",
  "",
  "_Arn._                           Hold! hold!",
  "I swear.",
  "",
  "_Olimp._ Spare thine already forfeit soul",
  "A perjury for which even Hell would loathe thee.",
  "I know thee.",
  "",
  "_Arn._       No, thou know'st me not; I am not",
  "Of these men, though----",
  "",
  "_Olimp._                 I judge thee by thy mates;",
  "It is for God to judge thee as thou art.",
  "I see thee purple with the blood of Rome;",
  "Take mine, 'tis all thou e'er shalt have of me,",
  "And here, upon the marble of this temple,",
  "Where the baptismal font baptized me God's,",
  "I offer him a blood less holy",
  "But not less pure (pure as it left me then,",
  "A redeeméd infant) than the holy water",
  "The saints have sanctified!",
  "",
  "                [OLIMPIA _waves her hand to_ ARNOLD _with disdain, and",
  "                      dashes herself on the pavement from the Altar_.",
  "",
  "_Arn._                      Eternal God!",
  "I feel thee now! Help! help! she's gone.",
  "",
  "_Cæs._ (_approaches_).                  I am here.",
  "",
  "_Arn._ Thou! but oh, save her!",
  "",
  "_Cæs._ (_assisting him to raise_ OLIMPIA). She hath done it well!",
  "The leap was serious.",
  "",
  "_Arn._                Oh! she is lifeless!",
  "",
  "_Cæs._                                     If",
  "She be so, I have nought to do with that:",
  "The resurrection is beyond me.",
  "",
  "_Arn._                        Slave!",
  "",
  "_Cæs._ Aye, slave or master, 'tis all one: methinks",
  "Good words, however, are as well at times.",
  "",
  "_Arn._ Words!--Canst thou aid her?",
  "",
  "_Cæs._                           I will try. A sprinkling",
  "Of that same holy water may be useful.",
  "                        [_He brings some in his helmet from the font_.",
  "",
  "_Arn._ 'Tis mixed with blood.",
  "",
  "_Cæs._                       There is no cleaner now",
  "In Rome.",
  "",
  "_Arn._ How pale! how beautiful! how lifeless!",
  "Alive or dead, thou Essence of all Beauty,",
  "I love but thee!",
  "",
  "_Cæs._          Even so Achilles loved",
  "Penthesilea; with his form it seems",
  "You have his heart, and yet it was no soft one.",
  "",
  "_Arn._ She breathes! But no, 'twas nothing, or the last",
  "Faint flutter Life disputes with Death.",
  "",
  "_Cæs._                                 She breathes.",
  "",
  "_Arn._ _Thou_ say'st it? Then 'tis truth.",
  "",
  "_Cæs._                                   You do me right--",
  "The Devil speaks truth much oftener than he's deemed:",
  "He hath an ignorant audience.",
  "",
  "_Arn._ (_without attending to him_). Yes! her heart beats.",
  "Alas! that the first beat of the only heart",
  "I ever wished to beat with mine should vibrate",
  "To an assassin's pulse.",
  "",
  "_Cæs._                  A sage reflection,",
  "But somewhat late i' the day. Where shall we bear her?",
  "I say she lives.",
  "",
  "_Arn._          And will she live?",
  "",
  "_Cas._                             As much",
  "As dust can.",
  "",
  "_Arn._ Then she is dead!",
  "",
  "_Cæs._                   Bah! bah! You are so,",
  "And do not know it. She will come to life--",
  "Such as you think so, such as you now are;",
  "But we must work by human means.",
  "",
  "_Arn._                          We will",
  "Convey her unto the Colonna palace,",
  "Where I have pitched my banner.",
  "",
  "_Cæs._                         Come then! raise her up!",
  "",
  "_Arn._ Softly!",
  "",
  "_Cæs._        As softly as they bear the dead,",
  "Perhaps because they cannot feel the jolting.",
  "",
  "_Arn._ But doth she live indeed?",
  "",
  "_Cæs._                           Nay, never fear!",
  "But, if you rue it after, blame not me.",
  "",
  "_Arn._ Let her but live!",
  "",
  "_Cæs._                  The Spirit of her life",
  "Is yet within her breast, and may revive.",
  "Count! count! I am your servant in all things,",
  "And this is a new office:--'tis not oft",
  "I am employed in such; but you perceive",
  "How staunch a friend is what you call a fiend.",
  "On earth you have often only fiends for friends;",
  "Now _I_ desert not mine. Soft! bear her hence,",
  "The beautiful half-clay, and nearly spirit!",
  "I am almost enamoured of her, as",
  "Of old the Angels of her earliest sex.",
  "",
  "_Arn._ Thou!",
  "",
  "_Cæs._      I! But fear not. I'll not be your rival.",
  "",
  "_Arn._ Rival!",
  "",
  "_Cæs._       I could be one right formidable;",
  "But since I slew the seven husbands of",
  "Tobias' future bride (and after all",
  "Was smoked out by some incense), I have laid",
  "Aside intrigue: 'tis rarely worth the trouble",
  "Of gaining, or--what is more difficult--",
  "Getting rid of your prize again; for there's",
  "The rub! at least to mortals.",
  "",
  "_Arn._                       Prithee, peace!",
  "Softly! methinks her lips move, her eyes open!",
  "",
  "_Cæs._ Like stars, no doubt; for that's a metaphor",
  "For Lucifer and Venus.",
  "",
  "_Arn._                To the palace",
  "Colonna, as I told you!",
  "",
  "_Cæs._                 Oh! I know",
  "My way through Rome.",
  "",
  "_Arn._              Now onward, onward! Gently!",
  "                       [_Exeunt, bearing_ OLIMPIA. _The scene closes_.",
  "",
  "PART III.",
  "",
  "SCENE I.--_A Castle in the Apennines, surrounded by a wild but",
  "  smiling Country. Chorus of Peasants singing before the Gates_.",
  "",
  "                            _Chorus_.",
  "",
  "         The wars are over,",
  "           The spring is come;",
  "         The bride and her lover",
  "           Have sought their home:",
  "They are happy, we rejoice;",
  "Let their hearts have an echo in every voice!",
  "",
  "The spring is come; the violet's gone,",
  "The first-born child of the early sun:",
  "With us she is but a winter's flower,",
  "The snow on the hills cannot blast her bower,",
  "And she lifts up her dewy eye of blue",
  "To the youngest sky of the self-same hue.",
  "",
  "And when the spring comes with her host",
  "Of flowers, that flower beloved the most",
  "Shrinks from the crowd that may confuse",
  "Her heavenly odour and virgin hues.",
  "",
  "Pluck the others, but still remember",
  "Their herald out of dim December--",
  "The morning star of all the flowers,",
  "The pledge of daylight's lengthened hours;",
  "Nor, midst the roses, e'er forget",
  "The virgin--virgin Violet.",
  "",
  "                         _Enter_ CÆSAR.",
  "",
  "                      _Cæs._ (_singing_).",
  "The wars are all over,",
  "  Our swords are all idle,",
  "  The steed bites the bridle,",
  "The casque's on the wall.",
  "There's rest for the rover;",
  "  But his armour is rusty,",
  "  And the veteran grows crusty,",
  "As he yawns in the hall.",
  "  He drinks--but what's drinking?",
  "  A mere pause from thinking!",
  "No bugle awakes him with life-and-death call.",
  "",
  "                           _Chorus_.",
  "",
  "    But the hound bayeth loudly,",
  "      The boar's in the wood,",
  "    And the falcon longs proudly",
  "      To spring from her hood:",
  "    On the wrist of the noble",
  "      She sits like a crest,",
  "    And the air is in trouble",
  "      With birds from their nest.",
  "",
  "                            _Cæs_.",
  "    Oh! shadow of Glory!",
  "      Dim image of War!",
  "    But the chase hath no story,",
  "      Her hero no star,",
  "    Since Nimrod, the founder",
  "      Of empire and chase,",
  "    Who made the woods wonder",
  "      And quake for their race.",
  "    When the lion was young,",
  "      In the pride of his might,",
  "    Then 'twas sport for the strong",
  "      To embrace him in fight;",
  "    To go forth, with a pine",
  "      For a spear, 'gainst the mammoth,",
  "    Or strike through the ravine",
  "      At the foaming behemoth;",
  "    While man was in stature",
  "      As towers in our time,",
  "    The first born of Nature,",
  "      And, like her, sublime!",
  "",
  "                                _Chorus_.",
  "",
  "    But the wars are over,",
  "      The spring is come;",
  "    The bride and her lover",
  "      Have sought their home:",
  "They are happy, and we rejoice;",
  "Let their hearts have an echo from every voice!",
  "                                     [_Exeunt the Peasantry, singing_.",
  "",
  "FRAGMENT OF THE THIRD PART OF _THE DEFORMED TRANSFORMED_.",
  "",
  "                            _Chorus_.",
  "",
  "When the merry bells are ringing,",
  "And the peasant girls are singing,",
  "And the early flowers are flinging",
  "  Their odours in the air;",
  "And the honey bee is clinging",
  "To the buds; and birds are winging",
  "  Their way, pair by pair:",
  "Then the earth looks free from trouble",
  "With the brightness of a bubble:",
  "Though I did not make it,",
  "I could breathe on and break it;",
  "But too much I scorn it,",
  "Or else I would mourn it,",
  "To see despots and slaves",
  "Playing o'er their own graves.",
  "",
  "                      _Enter_ COUNT ARNOLD.",
  "",
  "        {_Mem._ Jealous--Arnold of Cæsar.",
  "        {Olympia at first not liking Cæsar",
  "        {--then?--Arnold jealous of himself",
  "        {under his former figure, owing to",
  "        {the power of intellect, etc., etc., etc.",
  "",
  "_Arnold_. You are merry, Sir--what? singing too?",
  "",
  "_Cæsar_.                                         It is",
  "The land of Song--and Canticles you know",
  "Were once my avocation.",
  "",
  "_Arn._              Nothing moves you;",
  "You scoff even at your own calamity--",
  "And such calamity! how wert thou fallen",
  "Son of the Morning! and yet Lucifer",
  "Can smile.",
  "",
  "_Cæs._     His shape can--would you have me weep,",
  "In the fair form I wear, to please you?",
  "",
  "_Arn._                                 Ah!",
  "",
  "_Cæs._ You are grave--what have you on your spirit!",
  "",
  "_Arn._                                               Nothing.",
  "",
  "_Cæs._ How mortals lie by instinct! If you ask",
  "A disappointed courtier--What's the matter?",
  "\"Nothing\"--an outshone Beauty what has made",
  "Her smooth brow crisp--\"Oh, Nothing!\"--a young heir",
  "When his Sire has recovered from the Gout,",
  "What ails him? \"Nothing!\" or a Monarch who",
  "Has heard the truth, and looks imperial on it--",
  "What clouds his royal aspect? \"Nothing,\" \"Nothing!\"",
  "Nothing--eternal nothing--of these nothings",
  "All are a lie--for all to them are much!",
  "And they themselves alone the real \"Nothings.\"",
  "Your present Nothing, too, is something to you--",
  "What is it?",
  "",
  "_Arn._      Know you not?",
  "",
  "_Cæs._                   I only know",
  "What I desire to know! and will not waste",
  "Omniscience upon phantoms. Out with it!",
  "If you seek aid from me--or else be silent.",
  "And eat your thoughts--till they breed snakes within you.",
  "",
  "_Arn._ Olimpia!",
  "",
  "_Cæs._          I thought as much--go on.",
  "",
  "_Arn._ I thought she had loved me.",
  "",
  "_Cæs._                             Blessings on your Creed!",
  "What a good Christian you were found to be!",
  "But what cold Sceptic hath appalled your faith",
  "And transubstantiated to crumbs again",
  "The _body_ of your Credence?",
  "",
  "_Arn._                      No one--but--",
  "Each day--each hour--each minute shows me more",
  "And more she loves me not--",
  "",
  "_Cæs._                     Doth she rebel?",
  "",
  "_Arn._ No, she is calm, and meek, and silent with me,",
  "And coldly dutiful, and proudly patient--",
  "Endures my Love--not meets it.",
  "",
  "_Cæs._                        That seems strange.",
  "You are beautiful and brave! the first is much",
  "For passion--and the rest for Vanity.",
  "",
  "_Arn._ I saved her life, too; and her Father's life,",
  "And Father's house from ashes.",
  "",
  "_Cæs._                        These are nothing.",
  "You seek for Gratitude--the Philosopher's stone.",
  "",
  "_Arn._ And find it not.",
  "",
  "_Cæs._                  You cannot find what is not.",
  "But _found_ would it content you? would you owe",
  "To thankfulness what you desire from Passion?",
  "No! No! you would be _loved_--what you call loved--",
  "_Self-loved_--loved for _yourself_--for neither health,",
  "Nor wealth, nor youth, nor power, nor rank, nor beauty--",
  "For these you may be stript of--but _beloved_",
  "As an abstraction--for--you know not what!",
  "These are the wishes of a moderate lover--",
  "And _so_ you love.",
  "",
  "_Arn._             Ah! could I be beloved,",
  "Would I ask wherefore?",
  "",
  "_Cæs._               Yes! and not believe",
  "The answer--You are jealous.",
  "",
  "_Arn._                       And of whom?",
  "",
  "_Cæs._ It may be of yourself, for Jealousy",
  "Is as a shadow of the Sun. The Orb",
  "Is mighty--as you mortals deem--and to",
  "Your little Universe seems universal;",
  "But, great as He appears, and is to you,",
  "The smallest cloud--the slightest vapour of",
  "Your humid earth enables you to look",
  "Upon a Sky which you revile as dull;",
  "Though your eyes dare not gaze on it when cloudless.",
  "Nothing can blind a mortal like to light.",
  "Now Love in you is as the Sun--a thing",
  "Beyond you--and your Jealousy's of Earth--",
  "A cloud of your own raising.",
  "",
  "_Arn._                       Not so always!",
  "There is a cause at times.",
  "",
  "_Cæs._                    Oh, yes! when atoms jostle,",
  "The System is in peril. But I speak",
  "Of things you know not. Well, to earth again!",
  "This precious thing of dust--this bright Olimpia--",
  "This marvellous Virgin, is a marble maid--",
  "An Idol, but a cold one to your heat",
  "Promethean, and unkindled by your torch.",
  "",
  "_Arn._ Slave!",
  "",
  "_Cæs._         In the victor's Chariot, when Rome triumphed,",
  "There was a Slave of yore to tell him truth!",
  "You are a Conqueror--command your Slave.",
  "",
  "_Arn._ Teach me the way to win the woman's love.",
  "",
  "_Cæs._ Leave her.",
  "",
  "_Arn._            Where that the path--I'd not pursue it.",
  "",
  "_Cæs._ No doubt! for if you did, the remedy",
  "Would be for a disease already cured.",
  "",
  "_Arn._ All wretched as I am, I would not quit",
  "My unrequited love, for all that's happy.",
  "",
  "_Cæs._ You have possessed the woman--still possess.",
  "What need you more?",
  "",
  "_Arn._         To be myself possessed--",
  "To be her heart as she is mine.",
  ""
]