module.exports = [
  "O THE sad day!",
  "When friends shall shake their heads, and say",
  "Of miserable me--",
  "'Hark, how he groans!",
  "Look, how he pants for breath!",
  "See how he struggles with the pangs of death!'",
  "When they shall say of these dear eyes--",
  "'How hollow, O how dim they be!",
  "Mark how his breast doth rise and swell",
  "Against his potent enemy!'",
  "When some old friend shall step to my bedside,",
  "Touch my chill face, and thence shall gently slide.",
  "",
  "But--when his next companions say",
  "'How does he do? What hopes?'--shall turn away,",
  "Answering only, with a lift-up hand--",
  "'Who can his fate withstand?'",
  "",
  "Then shall a gasp or two do more",
  "Than e'er my rhetoric could before:",
  "Persuade the world to trouble me no more!",
  ""
]