module.exports = [
  "THE PROLOGUE.",
  "",
  "By that the Manciple his tale had ended,",
  "The sunne from the south line was descended",
  "So lowe, that it was not to my sight",
  "Degrees nine-and-twenty as in height.",
  "Four of the clock it was then, as I guess,",
  "For eleven foot, a little more or less,",
  "My shadow was at thilke time, as there,",
  "Of such feet as my lengthe parted were",
  "In six feet equal of proportion.",
  "Therewith the moone's exaltation,",
  "In meane Libra, gan alway ascend,",
  "As we were ent'ring at a thorpe's end.",
  "For which our Host, as he was wont to gie,",
  "As in this case, our jolly company,",
  "Said in this wise; \"Lordings every one,",
  "Now lacketh us no more tales than one.",
  "Fulfill'd is my sentence and my decree;",
  "I trow that we have heard of each degree.",
  "Almost fulfilled is mine ordinance;",
  "I pray to God so give him right good chance",
  "That telleth us this tale lustily.",
  "Sir Priest,\" quoth he, \"art thou a vicary?",
  "Or art thou a Parson? say sooth by thy fay.",
  "Be what thou be, breake thou not our play;",
  "For every man, save thou, hath told his tale.",
  "Unbuckle, and shew us what is in thy mail.",
  "For truely me thinketh by thy cheer",
  "Thou shouldest knit up well a great mattere.",
  "Tell us a fable anon, for cocke's bones.\"",
  "",
  "This Parson him answered all at ones;",
  "\"Thou gettest fable none y-told for me,",
  "For Paul, that writeth unto Timothy,",
  "Reproveth them that weive soothfastness,",
  "And telle fables, and such wretchedness.",
  "Why should I sowe draff out of my fist,",
  "When I may sowe wheat, if that me list?",
  "For which I say, if that you list to hear",
  "Morality and virtuous mattere,",
  "And then that ye will give me audience,",
  "I would full fain at Christe's reverence",
  "Do you pleasance lawful, as I can.",
  "But, truste well, I am a southern man,",
  "I cannot gest, rom, ram, ruf,  by my letter;",
  "And, God wot, rhyme hold I but little better.",
  "And therefore if you list, I will not glose,",
  "I will you tell a little tale in prose,",
  "To knit up all this feast, and make an end.",
  "And Jesus for his grace wit me send",
  "To shewe you the way, in this voyage,",
  "Of thilke perfect glorious pilgrimage,",
  "That hight Jerusalem celestial.",
  "And if ye vouchesafe, anon I shall",
  "Begin upon my tale, for which I pray",
  "Tell your advice, I can no better say.",
  "But natheless this meditation",
  "I put it aye under correction",
  "Of clerkes, for I am not textuel;",
  "I take but the sentence, trust me well.",
  "Therefore I make a protestation,",
  "That I will stande to correction.\"",
  "Upon this word we have assented soon;",
  "For, as us seemed, it was for to do'n,",
  "To enden in some virtuous sentence,",
  "And for to give him space and audience;",
  "And bade our Host he shoulde to him say",
  "That alle we to tell his tale him pray.",
  "Our Hoste had. the wordes for us all:",
  "\"Sir Priest,\" quoth he, \"now faire you befall;",
  "Say what you list, and we shall gladly hear.\"",
  "And with that word he said in this mannere;",
  "\"Telle,\" quoth he, \"your meditatioun,",
  "But hasten you, the sunne will adown.",
  "Be fructuous, and that in little space;",
  "And to do well God sende you his grace.\"",
  ""
]