module.exports = [
  "There was a time, I need not name,",
  "  Since it will ne'er forgotten be,",
  "When all our feelings were the same",
  "  As still my soul hath been to thee.",
  "",
  "And from that hour when first thy tongue",
  "  Confess'd a love which equall'd mine,",
  "Though many a grief my heart hath wrung,",
  "  Unknown, and thus unfelt, by thine,",
  "",
  "None, none hath sunk so deep as this--",
  "  To think how all that love hath flown;",
  "Transient as every faithless kiss,",
  "  But transient in thy breast alone.",
  "",
  "And yet my heart some solace knew,",
  "  When late I heard thy lips declare,",
  "In accents once imagined true,",
  "  Remembrance of the days that were.",
  "",
  "Yes! my adored, yet most unkind!",
  "  Though thou wilt never love again,",
  "To me 'tis doubly sweet to find",
  "  Remembrance of that love remain.",
  "",
  "Yes! 'tis a glorious thought to me,",
  "  Nor longer shall my soul repine,",
  "Whate'er thou art or e'er shall be,",
  "  Thou hast been dearly, solely mine.",
  ""
]