module.exports = [
  "THERE was a time when this poor frame was whole",
  "And I had youth and never another care,",
  "Or none that should have troubled a strong soul.",
  "Yet, except sometimes in a frosty air",
  "When my heels hammered out a melody",
  "From pavements of a city left behind,",
  "I never would acknowledge my own glee",
  "Because it was less mighty than my mind",
  "Had dreamed of. Since I could not boast of strength",
  "Great as I wished, weakness was all my boast.",
  "I sought yet hated pity till at length",
  "I earned it. Oh, too heavy was the cost.",
  "But now that there is something I could use",
  "My youth and strength for, I deny the age,",
  "The care and weakness that I know--refuse",
  "To admit I am unworthy of the wage",
  "Paid to a man who gives up eyes and breath",
  "For what can neither ask nor heed his death.",
  ""
]