module.exports = [
  "This life is all chequer'd with pleasures and woes,",
  "That chase one another like waves of the deep --",
  "Each brightly or darkly, as onward it flows,",
  "Reflecting our eyes, as they sparkle or weep.",
  "So closely our whims on our miseries tread,",
  "That the laugh is awaked ere the tear can be dried;",
  "And, as fast as the rain-drop of Pity is shed,",
  "The goose-plumage of Folly can turn it aside.",
  "But pledge me the cup -- if existence would cloy,",
  "With hearts ever happy and heads ever wise,",
  "Be ours the light Sorrow, half-sister to Joy,",
  "And the light brilliant Folly that flashes and dies.",
  "",
  "When Hylas was sent with his urn to the fount,",
  "Through fields full of light, and with heart full of play,",
  "Light rambled the boy, over meadow and mount,",
  "And neglected his task for the flowers on the way.",
  "Thus many, like me, who in youth should have tasted",
  "The fountain that runs by Philosophy's shrine,",
  "Their time with the flowers on the margin have wasted,",
  "And left their light urns all as empty as mine.",
  "But pledge me the goblet; -- while idleness weaves",
  "These flowerets together, should Wisdom but see",
  "One bright drop or two that has fall'n on the leaves",
  "From her fountain divine, 'tis sufficient for me.",
  ""
]