module.exports = [
  "High in the midst, surrounded by his peers,",
  "Magnus his ample front sublime uprears:",
  "Plac'd on his chair of state, he seems a God,",
  "While Sophs and Freshmen tremble at his nod;",
  "As all around sit wrapt in speechless gloom,",
  "_His_ voice, in thunder, shakes the sounding dome;",
  "Denouncing dire reproach to luckless fools,",
  "Unskill'd to plod in mathematic rules.",
  "",
  " Happy the youth! in Euclid's axioms tried,",
  "Though little vers'd in any art beside;",
  "Who, scarcely skill'd an English line to pen,",
  "Scans Attic metres with a critic's ken.",
  "",
  "What! though he knows not how his fathers bled,",
  "When civil discord pil'd the fields with dead,",
  "When Edward bade his conquering bands advance,",
  "Or Henry trampled on the crest of France:",
  "Though marvelling at the name of _Magna Charta_,",
  "Yet well he recollects the _laws_ of _Sparta_;",
  "Can tell, what edicts sage _Lycurgus_ made,",
  "While _Blackstone's_ on the _shelf_, _neglected_ laid;",
  "Of _Grecian dramas_ vaunts the deathless fame,",
  "Of _Avon's bard_, rememb'ring scarce the name.",
  "",
  "Such is the youth whose scientific pate",
  "Class-honours, medals, fellowships, await;",
  "Or even, perhaps, the _declamation_ prize,",
  "If to such glorious height, he lifts his eyes.",
  "But lo! no _common_ orator can hope",
  "The envied silver cup within his scope:",
  "Not that our _heads_ much eloquence require,",
  "Th' ATHENIAN'S glowing style, or TULLY'S fire.",
  "A _manner_ clear or warm is useless, since",
  "We do not try by _speaking_ to _convince_;",
  "Be other _orators_ of pleasing _proud_,--",
  "We speak to _please_ ourselves, not _move_ the crowd:",
  "Our gravity prefers the _muttering_ tone,",
  "A proper mixture of the _squeak_ and _groan_:",
  "No borrow'd _grace_ of _action_ must be seen,",
  "The slightest motion would displease the _Dean_;",
  "Whilst every staring Graduate would prate,",
  "Against what--_he_ could never imitate.",
  "",
  "The man, who hopes t' obtain the promis'd cup,",
  "Must in one _posture_ stand, and _ne'er look up_;",
  "Nor _stop_, but rattle over _every_ word--",
  "No matter _what_, so it can _not_ be heard:",
  "Thus let him hurry on, nor think to rest:",
  "Who speaks the _fastest's_ sure to speak the _best_;",
  "Who utters most within the shortest space,",
  "May, safely, hope to win the _wordy race_.",
  "",
  "The Sons of _Science_ these, who, thus repaid,",
  "Linger in ease in Granta's sluggish shade;",
  "Where on Cam's sedgy banks, supine, they lie,",
  "Unknown, unhonour'd live--unwept for die:",
  "Dull as the pictures, which adorn their halls,",
  "They think all learning fix'd within their walls:",
  "In manners rude, in foolish forms precise,",
  "All modern arts affecting to despise;",
  "Yet prizing _Bentley's, Brunck's_, or _Porson's_ note,",
  "More than the _verse on which the critic wrote_:",
  "Vain as their honours, heavy as their Ale,",
  "Sad as their wit, and tedious as their tale;",
  "To friendship dead, though not untaught to feel,",
  "When Self and Church demand a Bigot zeal.",
  "With eager haste they court the lord of power,",
  "(Whether 'tis PITT or PETTY rules the hour;)",
  "To _him_, with suppliant smiles, they bend the head,",
  "While distant mitres to their eyes are spread;",
  "But should a storm o'erwhelm him with disgrace,",
  "They'd fly to seek the next, who fill'd his place.",
  "_Such_ are the men who learning's treasures guard!",
  "_Such_ is their _practice_, such is their _reward_!",
  "This _much_, at least, we may presume to say--",
  "The premium can't exceed the _price_ they _pay_.",
  ""
]