module.exports = [
  "      When in summer thou walkest",
  "        In the meads by the river,",
  "      And to thyself talkest,",
  "        Dost thou think of one ever--",
  "      A lost and a lorn one",
  "        That adores thee and loves thee?",
  "      And when happy morn's gone,",
  "        And nature's calm moves thee,",
  "Leaving thee to thy sleep like an angel at rest,",
  "Does the one who adores thee still live in thy breast?",
  "",
  "      Does nature eer give thee",
  "        Love's past happy vision,",
  "      And wrap thee and leave thee",
  "        In fancies elysian?",
  "      Thy beauty I clung to,",
  "        As leaves to the tree;",
  "      When thou fair and young too",
  "        Looked lightly on me,",
  "Till love came upon thee like the sun to the west",
  "And shed its perfuming and bloom on thy breast.",
  ""
]