module.exports = [
  "Tie the Strings to my Life, My Lord,",
  "Then, I am ready to go!",
  "Just a look at the Horses --",
  "Rapid! That will do!",
  "",
  "Put me in on the firmest side --",
  "So I shall never fall --",
  "For we must ride to the Judgment --",
  "And it's partly, down Hill --",
  "",
  "But never I mind the steeper --",
  "And never I mind the Sea --",
  "Held fast in Everlasting Race --",
  "By my own Choice, and Thee --",
  "",
  "Goodbye to the Life I used to live --",
  "And the World I used to know --",
  "And kiss the Hills, for me, just once --",
  "Then -- I am ready to go!",
  ""
]