module.exports = [
  "I.",
  "",
  "Time, thy name is sorrow, says the stricken",
  "Heart of life, laid waste with wasting flame",
  "Ere the change of things and thoughts requicken,",
  "Time, thy name.",
  "",
  "Girt about with shadow, blind and lame,",
  "Ghosts of things that smite and thoughts that sicken",
  "Hunt and hound thee down to death and shame.",
  "",
  "Eyes of hours whose paces halt or quicken",
  "Read in bloodred lines of loss and blame,",
  "Writ where cloud and darkness round it thicken,",
  "Time, thy name.",
  "",
  "II.",
  "",
  "Nay, but rest is born of me for healing,",
  "- So might haply time, with voice represt,",
  "Speak: is grief the last gift of my dealing?",
  "Nay, but rest.",
  "",
  "All the world is wearied, east and west,",
  "Tired with toil to watch the slow sun wheeling,",
  "Twelve loud hours of life's laborious quest.",
  "",
  "Eyes forspent with vigil, faint and reeling,",
  "Find at last my comfort, and are blest,",
  "Not with rapturous light of life's revealing -",
  "Nay, but rest.",
  ""
]