module.exports = [
  "PART I",
  "",
  "It is an hour before the hour of dawn.",
  "Set in mine hand my staff and leave me here",
  "Outside the hollow house that blind men fear,",
  "More blind than I who live on life withdrawn",
  "And feel on eyes that see not but foresee",
  "The shadow of death which clothes Antigone.",
  "",
  "Here lay her living body that here lies",
  "Dead, if man living know what thing is death,",
  "If life be all made up of blood and breath,",
  "And no sense be save as of ears and eyes.",
  "But heart there is not, tongue there is not found,",
  "To think or sing what verge hath life or bound.",
  "",
  "In the beginning when the powers that made",
  "The young child man a little loved him, seeing",
  "His joy of life and fair face of his being,",
  "And bland and laughing with the man-child played,",
  "As friends they saw on our divine one day",
  "King Cadmus take to queen Harmonia.",
  "",
  "The strength of soul that builds up as with hands",
  "Walls spiritual and towers and towns of thought",
  "Which only fate, not force, can bring to nought,",
  "Took then to wife the light of all men's lands,",
  "War's child and love's, most sweet and wise and strong,",
  "Order of things and rule and guiding song.",
  "",
  "It was long since: yea, even the sun that saw",
  "Remembers hardly what was, nor how long.",
  "And now the wise heart of the worldly song",
  "Is perished, and the holy hand of law",
  "Can set no tune on time, nor help again",
  "The power of thought to build up life for men.",
  "",
  "Yea, surely are they now transformed or dead,",
  "And sleep below this world, where no sun warms,",
  "Or move about it now in formless forms",
  "Incognizable, and all their lordship fled;",
  "And where they stood up singing crawl and hiss,",
  "With fangs that kill behind their lips that kiss.",
  "",
  "Yet though her marriage-garment, seeming fair,",
  "Was dyed in sin and woven of jealousy",
  "To turn their seed to poison, time shall see",
  "The gods reissue from them, and repair",
  "Their broken stamp of godhead, and again",
  "Thought and wise love sing words of law to men.",
  "",
  "I, Tiresias the prophet, seeing in Thebes",
  "Much evil, and the misery of men's hands",
  "Who sow with fruitless wheat the stones and sands,",
  "With fruitful thorns the fallows and warm glebes,",
  "Bade their hands hold lest worse hap came to pass;",
  "But which of you had heed of Tiresias?",
  "",
  "I am as Time's self in mine own wearied mind,",
  "Whom the strong heavy-footed years have led",
  "From night to night and dead men unto dead,",
  "And from the blind hope to the memory blind;",
  "For each man's life is woven, as Time's life is,",
  "Of blind young hopes and old blind memories.",
  "",
  "I am a soul outside of death and birth.",
  "I see before me and afterward I see,",
  "O child, O corpse, the live dead face of thee,",
  "Whose life and death are one thing upon earth",
  "Where day kills night and night again kills day",
  "And dies; but where is that Harmonia?",
  "",
  "O all-beholden light not seen of me,",
  "Air, and warm winds that under the sun's eye",
  "Stretch your strong wings at morning; and thou, sky,",
  "Whose hollow circle engirdling earth and sea",
  "All night the set stars limit, and all day",
  "The moving sun remeasures; ye, I say,",
  "",
  "Ye heights of hills, and thou Dircean spring",
  "Inviolable, and ye towers that saw cast down",
  "Seven kings keen-sighted toward your seven-faced town",
  "And quenched the red seed of one sightless king;",
  "And thou, for death less dreadful than for birth,",
  "Whose wild leaves hide the horror of the earth,",
  "",
  "O mountain whereon gods made chase of kings,",
  "Cithaeron, thou that sawest on Pentheus dead",
  "Fangs of a mother fasten and wax red",
  "And satiate with a son thy swollen springs,",
  "And heardst her cry fright all thine eyries' nests",
  "Who gave death suck at sanguine-suckling breasts;",
  "",
  "Yea, and a grief more grievous, without name,",
  "A curse too grievous for the name of grief,",
  "Thou sawest, and heardst the rumour scare belief",
  "Even unto death and madness, when the flame",
  "Was lit whose ashes dropped about the pyre",
  "That of two brethren made one sundering fire;",
  "",
  "O bitter nurse, that on thine hard bare knees",
  "Rear'dst for his fate the bloody-footed child",
  "Whose hands should be more bloodily defiled",
  "And the old blind feet walk wearier ways than these,",
  "Whose seed, brought forth in darkness unto doom,",
  "Should break as fire out of his mother's womb;",
  "",
  "I bear you witness as ye bear to me,",
  "Time, day, night, sun, stars, life, death, air, sea, earth,",
  "And ye that round the human house of birth",
  "Watch with veiled heads and weaponed hands, and see",
  "Good things and evil, strengthless yet and dumb,",
  "Sit in the clouds with cloudlike hours to come;",
  "",
  "Ye forces without form and viewless powers",
  "That have the keys of all our years in hold,",
  "That prophesy too late with tongues of gold,",
  "In a strange speech whose words are perished hours,",
  "I witness to you what good things ye give",
  "As ye to me what evil while I live.",
  "",
  "What should I do to blame you, what to praise,",
  "For floral hours and hours funereal?",
  "What should I do to curse or bless at all",
  "For winter-woven or summer-coloured days?",
  "Curse he that will and bless you whoso can,",
  "I have no common part in you with man.",
  "",
  "I hear a springing water, whose quick sound",
  "Makes softer the soft sunless patient air,",
  "And the wind's hand is laid on my thin hair",
  "Light as a lover's, and the grasses round",
  "Have odours in them of green bloom and rain",
  "Sweet as the kiss wherewith sleep kisses pain.",
  "",
  "I hear the low sound of the spring of time",
  "Still beating as the low live throb of blood,",
  "And where its waters gather head and flood",
  "I hear change moving on them, and the chime",
  "Across them of reverberate wings of hours",
  "Sounding, and feel the future air of flowers.",
  "",
  "The wind of change is soft as snow, and sweet",
  "The sense thereof as roses in the sun,",
  "The faint wind springing with the springs that run,",
  "The dim sweet smell of flowering hopes, and heat",
  "Of unbeholden sunrise; yet how long",
  "I know not, till the morning put forth song.",
  "",
  "I prophesy of life, who live with death;",
  "Of joy, being sad; of sunlight, who am blind;",
  "Of man, whose ways are alien from mankind",
  "And his lips are not parted with man's breath;",
  "I am a word out of the speechless years,",
  "The tongue of time, that no man sleeps who hears.",
  "",
  "I stand a shadow across the door of doom,",
  "Athwart the lintel of death's house, and wait;",
  "Nor quick nor dead, nor flexible by fate,",
  "Nor quite of earth nor wholly of the tomb;",
  "A voice, a vision, light as fire or air,",
  "Driven between days that shall be and that were.",
  "",
  "I prophesy, with feet upon a grave,",
  "Of death cast out and life devouring death",
  "As flame doth wood and stubble with a breath;",
  "Of freedom, though all manhood were one slave;",
  "Of truth, though all the world were liar; of love,",
  "That time nor hate can raze the witness of.",
  "",
  "Life that was given for love's sake and his law's",
  "Their powers have no more power on; they divide",
  "Spoils wrung from lust or wrath of man or pride,",
  "And keen oblivion without pity or pause",
  "Sets them on fire and scatters them on air",
  "Like ashes shaken from a suppliant's hair.",
  "",
  "But life they lay no hand on; life once given",
  "No force of theirs hath competence to take;",
  "Life that was given for some divine thing's sake,",
  "To mix the bitterness of earth with heaven,",
  "Light with man's night, and music with his breath,",
  "Dies not, but makes its living food of death.",
  "",
  "I have seen this, who live where men are not,",
  "In the high starless air of fruitful night",
  "On that serenest and obscurest height",
  "Where dead and unborn things are one in thought",
  "And whence the live unconquerable springs",
  "Feed full of force the torrents of new things.",
  "",
  "I have seen this, who saw long since, being man,",
  "As now I know not if indeed I be,",
  "The fair bare body of Wisdom, good to see",
  "And evil, whence my light and night began;",
  "Light on the goal and darkness on the way,",
  "Light all through night and darkness all through day.",
  "",
  "Mother, that by that Pegasean spring",
  "Didst fold round in thine arms thy blinded son,",
  "Weeping \"O holiest, what thing hast thou done,",
  "What, to my child? woe's me that see the thing!",
  "Is this thy love to me-ward, and hereof",
  "Must I take sample how the gods can love?",
  "",
  "\"O child, thou hast seen indeed, poor child of mine,",
  "The breasts and flanks of Pallas bare in sight,",
  "But never shalt see more the dear sun's light;",
  "O Helicon, how great a pay is thine",
  "For some poor antelopes and wild-deer dead,",
  "My child's eyes hast thou taken in their stead--\"",
  "",
  "Mother, thou knewest not what she had to give,",
  "Thy goddess, though then angered, for mine eyes;",
  "Fame and foreknowledge, and to be most wise,",
  "And centuries of high-thoughted life to live,",
  "And in mine hand this guiding staff to be",
  "As eyesight to the feet of men that see.",
  "",
  "Perchance I shall not die at all, nor pass",
  "The general door and lintel of men dead;",
  "Yet even the very tongue of wisdom said",
  "What grace should come with death to Tiresias,",
  "What special honour that God's hand accord",
  "Who gathers all men's nations as their lord.",
  "",
  "And sometimes when the secret eye of thought",
  "Is changed with obscuration, and the sense",
  "Aches with long pain of hollow prescience,",
  "And fiery foresight with foresuffering bought",
  "Seems even to infect my spirit and consume,",
  "Hunger and thirst come on me for the tomb.",
  "",
  "I could be fain to drink my death and sleep,",
  "And no more wrapped about with bitter dreams",
  "Talk with the stars and with the winds and streams",
  "And with the inevitable years, and weep;",
  "For how should he who communes with the years",
  "Be sometime not a living spring of tears?",
  "",
  "O child, that guided of thine only will",
  "Didst set thy maiden foot against the gate",
  "To strike it open ere thine hour of fate,",
  "Antigone, men say not thou didst ill,",
  "For love's sake and the reverence of his awe",
  "Divinely dying, slain by mortal law;",
  "",
  "For love is awful as immortal death.",
  "And through thee surely hath thy brother won",
  "Rest, out of sight of our world-weary sun,",
  "And in the dead land where ye ghosts draw breath",
  "A royal place and honour; so wast thou",
  "Happy, though earth have hold of thee too now.",
  "",
  "So hast thou life and name inviolable",
  "And joy it may be, sacred and severe,",
  "Joy secret-souled beyond all hope or fear,",
  "A monumental joy wherein to dwell",
  "Secluse and silent, a selected state,",
  "Serene possession of thy proper fate.",
  "",
  "Thou art not dead as these are dead who live",
  "Full of blind years, a sorrow-shaken kind,",
  "Nor as these are am I the prophet blind;",
  "They have not life that have not heart to give",
  "Life, nor have eyesight who lack heart to see",
  "When to be not is better than to be.",
  "",
  "O ye whom time but bears with for a span,",
  "How long will ye be blind and dead, how long",
  "Make your own souls part of your own soul's wrong?",
  "Son of the word of the most high gods, man,",
  "Why wilt thou make thine hour of light and breath",
  "Emptier of all but shame than very death?",
  "",
  "Fool, wilt thou live for ever? though thou care",
  "With all thine heart for life to keep it fast,",
  "Shall not thine hand forego it at the last?",
  "Lo, thy sure hour shall take thee by the hair",
  "Sleeping, or when thou knowest not, or wouldst fly;",
  "And as men died much mightier shalt thou die.",
  "",
  "Yea, they are dead, men much more worth than thou;",
  "The savour of heroic lives that were,",
  "Is it not mixed into thy common air?",
  "The sense of them is shed about thee now:",
  "Feel not thy brows a wind blowing from far?",
  "Aches not thy forehead with a future star?",
  "",
  "The light that thou may'st make out of thy name",
  "Is in the wind of this same hour that drives,",
  "Blown within reach but once of all men's lives;",
  "And he that puts forth hand upon the flame",
  "Shall have it for a garland on his head",
  "To sign him for a king among the dead.",
  "",
  "But these men that the lessening years behold,",
  "Who sit the most part without flame or crown,",
  "And brawl and sleep and wear their life-days down",
  "With joys and griefs ignobler than of old,",
  "And care not if the better day shall be -",
  "Are these or art thou dead, Antigone?",
  "",
  "PART II",
  "",
  "As when one wakes out of a waning dream",
  "And sees with instant eyes the naked thought",
  "Whereof the vision as a web was wrought,",
  "I saw beneath a heaven of cloud and gleam,",
  "Ere yet the heart of the young sun waxed brave,",
  "One like a prophet standing by a grave.",
  "",
  "In the hoar heaven was hardly beam or breath,",
  "And all the coloured hills and fields were grey,",
  "And the wind wandered seeking for the day,",
  "And wailed as though he had found her done to death",
  "And this grey hour had built to bury her",
  "The hollow twilight for a sepulchre.",
  "",
  "But in my soul I saw as in a glass",
  "A pale and living body full of grace",
  "There lying, and over it the prophet's face",
  "Fixed; and the face was not of Tiresias,",
  "For such a starry fire was in his eyes",
  "As though their light it was that made the skies.",
  "",
  "Such eyes should God's have been when very love",
  "Looked forth of them and set the sun aflame,",
  "And such his lips that called the light by name",
  "And bade the morning forth at sound thereof;",
  "His face was sad and masterful as fate,",
  "And like a star's his look compassionate.",
  "",
  "Like a star's gazed on of sad eyes so long",
  "It seems to yearn with pity, and all its fire",
  "As a man's heart to tremble with desire",
  "And heave as though the light would bring forth song;",
  "Yet from his face flashed lightning on the land,",
  "And like the thunder-bearer's was his hand.",
  "",
  "The steepness of strange stairs had tired his feet,",
  "And his lips yet seemed sick of that salt bread",
  "Wherewith the lips of banishment are fed;",
  "But nothing was there in the world so sweet",
  "As the most bitter love, like God's own grace,",
  "Wherewith he gazed on that fair buried face.",
  "",
  "Grief and glad pride and passion and sharp shame,",
  "Wrath and remembrance, faith and hope and hate",
  "And pitiless pity of days degenerate,",
  "Were in his eyes as an incorporate flame",
  "That burned about her, and the heart thereof",
  "And central flower was very fire of love.",
  "",
  "But all about her grave wherein she slept",
  "Were noises of the wild wind-footed years",
  "Whose footprints flying were full of blood and tears,",
  "Shrieks as of Maenads on their hills that leapt",
  "And yelled as beasts of ravin, and their meat",
  "Was the rent flesh of their own sons to eat:",
  "",
  "And fiery shadows passing with strange cries,",
  "And Sphinx-like shapes about the ruined lands,",
  "And the red reek of parricidal hands",
  "And intermixture of incestuous eyes,",
  "And light as of that self-divided flame",
  "Which made an end of the Cadmean name.",
  "",
  "And I beheld again, and lo the grave,",
  "And the bright body laid therein as dead,",
  "And the same shadow across another head",
  "That bowed down silent on that sleeping slave",
  "Who was the lady of empire from her birth",
  "And light of all the kingdoms of the earth.",
  "",
  "Within the compass of the watcher's hand",
  "All strengths of other men and divers powers",
  "Were held at ease and gathered up as flowers;",
  "His heart was as the heart of his whole land,",
  "And at his feet as natural servants lay",
  "Twilight and dawn and night and labouring day.",
  "",
  "He was most awful of the sons of God.",
  "Even now men seeing seemed at his lips to see",
  "The trumpet of the judgment that should be,",
  "And in his right hand terror for a rod,",
  "And in the breath that made the mountains bow",
  "The horned fire of Moses on his brow.",
  "",
  "The strong wind of the coming of the Lord",
  "Had blown as flame upon him, and brought down",
  "On his bare head from heaven fire for a crown,",
  "And fire was girt upon him as a sword",
  "To smite and lighten, and on what ways he trod",
  "There fell from him the shadow of a God.",
  "",
  "Pale, with the whole world's judgment in his eyes,",
  "He stood and saw the grief and shame endure",
  "That he, though highest of angels might not cure,",
  "And the same sins done under the same skies,",
  "And the same slaves to the same tyrants thrown,",
  "And fain he would have slept, and fain been stone.",
  "",
  "But with unslumbering eyes he watched the sleep",
  "That sealed her sense whose eyes were suns of old;",
  "And the night shut and opened, and behold,",
  "The same grave where those prophets came to weep,",
  "But she that lay therein had moved and stirred,",
  "And where those twain had watched her stood a third.",
  "",
  "The tripled rhyme that closed in Paradise",
  "With Love's name sealing up its starry speech -",
  "The tripled might of hand that found in reach",
  "All crowns beheld far off of all men's eyes,",
  "Song, colour, carven wonders of live stone -",
  "These were not, but the very soul alone.",
  "",
  "The living spirit, the good gift of grace,",
  "The faith which takes of its own blood to give",
  "That the dead veins of buried hope may live,",
  "Came on her sleeping, face to naked face,",
  "And from a soul more sweet than all the south",
  "Breathed love upon her sealed and breathless mouth.",
  "",
  "Between her lips the breath was blown as fire,",
  "And through her flushed veins leapt the liquid life,",
  "And with sore passion and ambiguous strife",
  "The new birth rent her and the new desire,",
  "The will to live, the competence to be,",
  "The sense to hearken and the soul to see.",
  "",
  "And the third prophet standing by her grave",
  "Stretched forth his hand and touched her, and her eyes",
  "Opened as sudden suns in heaven might rise,",
  "And her soul caught from his the faith to save;",
  "Faith above creeds, faith beyond records, born",
  "Of the pure, naked, fruitful, awful morn.",
  "",
  "For in the daybreak now that night was dead",
  "The light, the shadow, the delight, the pain,",
  "The purpose and the passion of those twain,",
  "Seemed gathered on that third prophetic head,",
  "And all their crowns were as one crown, and one",
  "His face with her face in the living sun.",
  "",
  "For even with that communion of their eyes",
  "His whole soul passed into her and made her strong;",
  "And all the sounds and shows of shame and wrong,",
  "The hand that slays, the lip that mocks and lies,",
  "Temples and thrones that yet men seem to see -",
  "Are these dead or art thou dead, Italy?",
  ""
]