module.exports = [
  "When Man, expell'd from Eden's bowers,",
  "  A moment linger'd near the gate,",
  "Each scene recall'd the vanish'd hours,",
  "  And bade him curse his future fate.",
  "",
  "But, wandering on through distant climes,",
  "  He learnt to bear his load of grief;",
  "Just gave a sigh to other times,",
  "  And found in busier scenes relief.",
  "",
  "Thus, Lady! will it be with me,",
  "  And I must view thy charms no more;",
  "For, while I linger near to thee,",
  "  I sigh for all I knew before.",
  "",
  "In flight I shall be surely wise,",
  "  Escaping from temptation's snare:",
  "I cannot view my Paradise",
  "  Without the wish of dwelling there.",
  ""
]