module.exports = [
  "Oh say not, sweet Anne, that the Fates have decreed",
  "The heart which adores you should wish to dissever;",
  "Such Fates were to me most unkind ones indeed,--",
  "To bear me from Love and from Beauty for ever.",
  "",
  "Your frowns, lovely girl, are the Fates which alone",
  "Could bid me from fond admiration refrain;",
  "By these, every hope, every wish were o'erthrown,",
  "Till smiles should restore me to rapture again.",
  "",
  "As the ivy and oak, in the forest entwin'd,",
  "The rage of the tempest united must weather;",
  "My love and my life were by nature design'd",
  "To flourish alike, or to perish together.",
  "",
  "Then say not, sweet Anne, that the Fates have decreed",
  "  Your lover should bid you a lasting adieu:",
  "Till Fate can ordain that his bosom shall bleed,",
  "  His Soul, his Existence, are centred in you.",
  "e, when I cease to adore you!",
  ""
]