module.exports = [
  "Ah, heedless girl! why thus disclose",
  "  What ne'er was meant for other ears;",
  "Why thus destroy thine own repose,",
  "  And dig the source of future tears?",
  "",
  "Oh, thou wilt weep, imprudent maid,",
  "While lurking envious foes will smile,",
  "For all the follies thou hast said",
  "Of those who spoke but to beguile.",
  "",
  "Vain girl! thy lingering woes are nigh,",
  "If thou believ'st what striplings say:",
  "Oh, from the deep temptation fly,",
  "Nor fall the specious spoiler's prey.",
  "",
  "Dost thou repeat, in childish boast,",
  "The words man utters to deceive?",
  "Thy peace, thy hope, thy all is lost,",
  "If thou canst venture to believe.",
  "",
  "While now amongst thy female peers",
  "Thou tell'st again the soothing tale,",
  "Canst thou not mark the rising sneers",
  "Duplicity in vain would veil?",
  "",
  "These tales in secret silence hush,",
  "Nor make thyself the public gaze:",
  "What modest maid without a blush",
  "Recounts a flattering coxcomb's praise?",
  "",
  "Will not the laughing boy despise",
  "Her who relates each fond conceit--",
  "Who, thinking Heaven is in her eyes,",
  "Yet cannot see the slight deceit?",
  "",
  "For she who takes a soft delight",
  "These amorous nothings in revealing,",
  "Must credit all we say or write,",
  "While vanity prevents concealing.",
  "",
  "Cease, if you prize your Beauty's reign!",
  "No jealousy bids me reprove:",
  "One, who is thus from nature vain,",
  "I pity, but I cannot love.",
  ""
]