module.exports = [
  "These locks, which fondly thus entwine,",
  "In firmer chains our hearts confine,",
  "Than all th' unmeaning protestations",
  "Which swell with nonsense, love orations.",
  "Our love is fix'd, I think we've prov'd it;",
  "Nor time, nor place, nor art have mov'd it;",
  "Then wherefore should we sigh and whine,",
  "With groundless jealousy repine;",
  "With silly whims, and fancies frantic,",
  "Merely to make our love romantic?",
  "Why should you weep, like _Lydia Languish_,",
  "And fret with self-created anguish?",
  "Or doom the lover you have chosen,",
  "On winter nights to sigh half frozen;",
  "In leafless shades, to sue for pardon,",
  "Only because the scene's a garden?",
  "For gardens seem, by one consent,",
  "(Since Shakespeare set the precedent;",
  "Since Juliet first declar'd her passion)",
  "To form the place of assignation.",
  "Oh! would some modern muse inspire,",
  "And seat her by a _sea-coal_ fire;",
  "Or had the bard at Christmas written,",
  "And laid the scene of love in Britain;",
  "He surely, in commiseration,",
  "Had chang'd the place of declaration.",
  "In Italy, I've no objection,",
  "Warm nights are proper for reflection;",
  "But here our climate is so rigid,",
  "That love itself, is rather frigid:",
  "Think on our chilly situation,",
  "And curb this rage for imitation.",
  "Then let us meet, as oft we've done,",
  "Beneath the influence of the sun;",
  "Or, if at midnight I must meet you,",
  "Within your mansion let me greet you:",
  "'There', we can love for hours together,",
  "Much better, in such snowy weather,",
  "Than plac'd in all th' Arcadian groves,",
  "That ever witness'd rural loves;",
  "'Then', if my passion fail to please,",
  "Next night I'll be content to freeze;",
  "No more I'll give a loose to laughter,",
  "But curse my fate, for ever after.",
  ""
]