module.exports = [
  "Few years have pass'd since thou and I",
  "  Were firmest friends, at least in name,",
  "And Childhood's gay sincerity",
  "  Preserved our feelings long the same.",
  "",
  "But now, like me, too well thou know'st",
  "  What trifles oft the heart recall;",
  "And those who once have loved the most",
  "  Too soon forget they lov'd at all.",
  "",
  "And such the change the heart displays,",
  "  So frail is early friendship's reign,",
  "A month's brief lapse, perhaps a day's,",
  "  Will view thy mind estrang'd again.",
  "",
  "If so, it never shall be mine",
  "  To mourn the loss of such a heart;",
  "The fault was Nature's fault, not thine,",
  "  Which made thee fickle as thou art.",
  "",
  "As rolls the Ocean's changing tide,",
  "  So human feelings ebb and flow;",
  "And who would in a breast confide",
  "  Where stormy passions ever glow?",
  "",
  "It boots not that, together bred,",
  "  Our childish days were days of joy:",
  "My spring of life has quickly fled;",
  "  Thou, too, hast ceas'd to be a boy.",
  "",
  "And when we bid adieu to youth,",
  "  Slaves to the specious World's controul,",
  "We sigh a long farewell to truth;",
  "  That World corrupts the noblest soul.",
  "",
  "Ah, joyous season! when the mind",
  "  Dares all things boldly but to lie;",
  "When Thought ere spoke is unconfin'd,",
  "  And sparkles in the placid eye.",
  "",
  "Not so in Man's maturer years,",
  "  When Man himself is but a tool;",
  "When Interest sways our hopes and fears,",
  "  And all must love and hate by rule.",
  "",
  "With fools in kindred vice the same,",
  "  We learn at length our faults to blend;",
  "And those, and those alone, may claim",
  "  The prostituted name of friend.",
  "",
  "Such is the common lot of man:",
  "  Can we then 'scape from folly free?",
  "Can we reverse the general plan,",
  "  Nor be what all in turn must be?",
  "",
  "No; for myself, so dark my fate",
  "  Through every turn of life hath been;",
  "Man and the World so much I hate,",
  "  I care not when I quit the scene.",
  "",
  "But thou, with spirit frail and light,",
  "  Wilt shine awhile, and pass away;",
  "As glow-worms sparkle through the night,",
  "  But dare not stand the test of day.",
  "",
  "Alas! whenever Folly calls",
  "  Where parasites and princes meet,",
  "(For cherish'd first in royal halls,",
  "  The welcome vices kindly greet,)",
  "",
  "Ev'n now thou'rt nightly seen to add",
  "  One insect to the fluttering crowd;",
  "And still thy trifling heart is glad",
  "  To join the vain and court the proud.",
  "",
  "There dost thou glide from fair to fair,",
  "  Still simpering on with eager haste,",
  "As flies along the gay parterre,",
  "  That taint the flowers they scarcely taste.",
  "",
  "But say, what nymph will prize the flame",
  "  Which seems, as marshy vapours move,",
  "To flit along from dame to dame,",
  "  An ignis-fatuus gleam of love?",
  "",
  "What friend for thee, howe'er inclin'd,",
  "  Will deign to own a kindred care?",
  "Who will debase his manly mind,",
  "  For friendship every fool may share?",
  "",
  "In time forbear; amidst the throng",
  "  No more so base a thing be seen;",
  "No more so idly pass along;",
  "  Be something, any thing, but--mean.",
  ""
]