module.exports = [
  "Young Oak! when I planted thee deep in the ground,",
  "  I hoped that thy days would be longer than mine;",
  "That thy dark-waving branches would flourish around,",
  "  And ivy thy trunk with its mantle entwine.",
  "",
  "Such, such was my hope, when in Infancy's years,",
  "  On the land of my Fathers I rear'd thee with pride;",
  "They are past, and I water thy stem with my tears,--",
  "  Thy decay, not the _weeds_ that surround thee can hide.",
  "",
  "I left thee, my Oak, and, since that fatal hour,",
  "  A stranger has dwelt in the hall of my Sire;",
  "Till Manhood shall crown me, not mine is the power,",
  "  But his, whose neglect may have bade thee expire.",
  "",
  "Oh! hardy thou wert--even now little care",
  "  Might revive thy young head, and thy wounds gently",
  "    heal:",
  "But thou wert not fated affection to share--",
  "  For who could suppose that a Stranger would feel?",
  "",
  "Ah, droop not, my Oak! lift thy head for a while;",
  "  Ere twice round yon Glory this planet shall run,",
  "The hand of thy Master will teach thee to smile,",
  "  When Infancy's years of probation are done.",
  "",
  "Oh, live then, my Oak! tow'r aloft from the weeds,",
  "  That clog thy young growth, and assist thy decay,",
  "For still in thy bosom are Life's early seeds,",
  "  And still may thy branches their beauty display.",
  "",
  "Oh! yet, if Maturity's years may be thine,",
  "  Though _I_ shall lie low in the cavern of Death,",
  "On thy leaves yet the day-beam of ages may shine,",
  "  Uninjured by Time, or the rude Winter's breath.",
  "",
  "For centuries still may thy boughs lightly wave",
  "  O'er the corse of thy Lord in thy canopy laid;",
  "While the branches thus gratefully shelter his grave,",
  "  The Chief who survives may recline in thy shade.",
  "",
  "And as he, with his boys, shall revisit this spot,",
  "  He will tell them in whispers more softly to tread.",
  "Oh! surely, by these I shall ne'er be forgot;",
  "  Remembrance still hallows the dust of the dead.",
  "",
  "And here, will they say, when in Life's glowing prime,",
  "  Perhaps he has pour'd forth his young simple lay,",
  "And here must he sleep, till the moments of Time",
  "  Are lost in the hours of Eternity's day.",
  ""
]