module.exports = [
  "Belshazzar! from the banquet turn,",
  "  Nor in thy sensual fulness fall;",
  "Behold! while yet before thee burn",
  "  The graven words, the glowing wall,",
  "Many a despot men miscall",
  "  Crowned and anointed from on high;",
  "But thou, the weakest, worst of all--",
  "  Is it not written, thou must die?",
  "",
  "Go! dash the roses from thy brow--",
  "  Grey hairs but poorly wreathe with them;",
  "Youth's garlands misbecome thee now,",
  "  More than thy very diadem,",
  "Where thou hast tarnished every gem:--",
  "  Then throw the worthless bauble by,",
  "Which, worn by thee, ev'n slaves contemn;",
  "  And learn like better men to die!",
  "",
  "Oh! early in the balance weighed,",
  "  And ever light of word and worth,",
  "Whose soul expired ere youth decayed,",
  "  And left thee but a mass of earth.",
  "To see thee moves the scorner's mirth:",
  "  But tears in Hope's averted eye",
  "Lament that even thou hadst birth--",
  "  Unfit to govern, live, or die.",
  ""
]