module.exports = [
  "When I hear you express an affection so warm,",
  "  Ne'er think, my belov'd, that I do not believe;",
  "For your lip would the soul of suspicion disarm,",
  "  And your eye beams a ray which can never deceive.",
  "",
  "Yet still, this fond bosom regrets, while adoring,",
  "  That love, like the leaf, must fall into the sear,",
  "That Age will come on, when Remembrance, deploring,",
  "Contemplates the scenes of her youth, with a tear;",
  "",
  "That the time must arrive, when, no longer retaining",
  "  Their auburn, those locks must wave thin to the breeze,",
  "When a few silver hairs of those tresses remaining,",
  "  Prove nature a prey to decay and disease.",
  "",
  "Tis this, my belov'd, which spreads gloom o'er my features,",
  "  Though I ne'er shall presume to arraign the decree",
  "Which God has proclaim'd as the fate of his creatures,",
  "  In the death which one day will deprive you of me.",
  "",
  "Mistake not, sweet sceptic, the cause of emotion,",
  "  No doubt can the mind of your lover invade;",
  "He worships each look with such faithful devotion,",
  "  A smile can enchant, or a tear can dissuade.",
  "",
  "But as death, my belov'd, soon or late shall o'ertake us,",
  "  And our breasts, which alive with such sympathy glow,",
  "Will sleep in the grave, till the blast shall awake us,",
  "  When calling the dead, in Earth's bosom laid low.",
  "",
  "Oh! then let us drain, while we may, draughts of pleasure,",
  "  Which from passion, like ours, must unceasingly flow;",
  "Let us pass round the cup of Love's bliss in full measure,",
  "  And quaff the contents as our nectar below.",
  "rough the neighbouring grove.",
  "",
  "But when _awake_, your lips I seek,",
  "  And clasp enraptur'd all your charms,",
  "So chill's the pressure of your cheek,",
  "  I fold a statue in my arms.",
  "",
  "If thus, when to my heart embrac'd,",
  "No pleasure in your eyes is trac'd,",
  "You may be prudent, fair, and _chaste_,",
  "  But ah! my girl, you _do not love_.",
  ""
]