module.exports = [
  "Eliza! what fools are the Mussulman sect,",
  "  Who, to woman, deny the soul's future existence;",
  "Could they see thee, Eliza! they'd own their defect,",
  "  And this doctrine would meet with a general resistance.",
  "",
  "Had their Prophet possess'd half an atom of sense,",
  "  He ne'er would have _woman_ from Paradise driven;",
  "Instead of his _Houris_, a flimsy pretence,",
  "  With _woman alone_ he had peopled his Heaven.",
  "",
  "Yet, still, to increase your calamities more,",
  "  Not content with depriving your bodies of spirit,",
  "He allots one poor husband to share amongst four! -",
  "  With _souls_ you'd dispense; but, this last, who could bear it?",
  "",
  "His religion to please neither party is made;",
  "  On _husbands_ 'tis _hard_, to the wives most uncivil;",
  "Still I can't contradict, what so oft has been said,",
  "  \"Though women are angels, yet wedlock's the devil.\"",
  "",
  "This terrible truth, even Scripture has told,",
  "  Ye Benedicks! hear me, and listen with rapture;",
  "If a glimpse of redemption you wish to behold,",
  "  Of ST. MATT.--read the second and twentieth chapter.",
  "",
  "'Tis surely enough upon earth to be vex'd,",
  "  With wives who eternal confusion are spreading;",
  "\"But in Heaven\" (so runs the Evangelists' Text)",
  "  \"We neither have giving in marriage, or wedding.\"",
  "",
  "From this we suppose, (as indeed well we may,)",
  "  That should Saints after death, with their spouses put up more,",
  "And wives, as in life, aim at absolute sway,",
  "  All Heaven would ring with the conjugal uproar.",
  "",
  "Distraction and Discord would follow in course,",
  "  Nor MATTHEW, nor MARK, nor ST. PAUL, can deny it,",
  "The only expedient is general divorce,",
  "  To prevent universal disturbance and riot.",
  "",
  "But though husband and wife, shall at length be disjoin'd,",
  "  Yet woman and man ne'er were meant to dissever,",
  "Our chains once dissolv'd, and our hearts unconfin'd,",
  "  We'll love without bonds, but we'll love you for ever.",
  "",
  "Though souls are denied you by fools and by rakes,",
  "  Should you own it yourselves, I would even then doubt you,",
  "Your nature so much of _celestial_ partakes,",
  "  The Garden of Eden would wither without you.",
  ""
]