module.exports = [
  "Oh! yes, I will own we were dear to each other;",
  "  The friendships of childhood, though fleeting, are true;",
  "The love which you felt was the love of a brother,",
  "  Nor less the affection I cherish'd for you.",
  "",
  "But Friendship can vary her gentle dominion;",
  "  The attachment of years, in a moment expires:",
  "Like Love, too, she moves on a swift-waving pinion,",
  "  But glows not, like Love, with unquenchable fires.",
  "",
  "Full oft have we wander'd through Ida together,",
  "  And blest were the scenes of our youth, I allow:",
  "In the spring of our life, how serene is the weather!",
  "  But Winter's rude tempests are gathering now.",
  "",
  "No more with Affection shall Memory blending,",
  "  The wonted delights of our childhood retrace:",
  "When Pride steels the bosom, the heart is unbending,",
  "  And what would be Justice appears a disgrace.",
  "",
  "However, dear George, for I still must esteem you-",
  "  The few, whom I love, I can never upbraid;",
  "The chance, which has lost, may in future redeem you,",
  "  Repentance will cancel the vow you have made.",
  "",
  "I will not complain, and though chill'd is affection,",
  "  With me no corroding resentment shall live:",
  "My bosom is calm'd by the simple reflection,",
  "  That both may be wrong, and that both should forgive.",
  "",
  "You knew, that my soul, that my heart, my existence,",
  "  If danger demanded, were wholly your own;",
  "You knew me unalter'd, by years or by distance,",
  "  Devoted to love and to friendship alone.",
  "",
  "You knew,--but away with the vain retrospection!",
  "  The bond of affection no longer endures;",
  "Too late you may droop o'er the fond recollection,",
  "  And sigh for the friend, who was formerly yours.",
  "",
  "For the present, we part,--I will hope not for ever;",
  "  For time and regret will restore you at last:",
  "To forget our dissension we both should endeavour,",
  "  I ask no atonement, but days like the past.",
  ""
]