module.exports = [
  "Thy look of love has power to calm",
  "The stormiest passion of my soul;",
  "Thy gentle words are drops of balm",
  "In life's too bitter bowl;",
  "No grief is mine, but that alone",
  "These choicest blessings I have known.",
  "",
  "Harriet! if all who long to live",
  "In the warm sunshine of thine eye,",
  "That price beyond all pain must give,--",
  "Beneath thy scorn to die;",
  "Then hear thy chosen own too late",
  "His heart most worthy of thy hate.",
  "",
  "Be thou, then, one among mankind",
  "Whose heart is harder not for state,",
  "Thou only virtuous, gentle, kind,",
  "Amid a world of hate;",
  "And by a slight endurance seal",
  "A fellow-being's lasting weal.",
  "",
  "For pale with anguish is his cheek,",
  "His breath comes fast, his eyes are dim,",
  "Thy name is struggling ere he speak,",
  "Weak is each trembling limb;",
  "In mercy let him not endure",
  "The misery of a fatal cure.",
  "",
  "Oh, trust for once no erring guide!",
  "Bid the remorseless feeling flee;",
  "'Tis malice, 'tis revenge, 'tis pride,",
  "'Tis anything but thee;",
  "Oh, deign a nobler pride to prove,",
  "And pity if thou canst not love.",
  " such love as ours.",
  "Harriet! let death all mortal ties dissolve,",
  "But ours shall not be mortal! The cold hand",
  "Of Time may chill the love of earthly minds",
  "Half frozen now; the frigid intercourse",
  "Of common souls lives but a summer's day;",
  "It dies, where it arose, upon this earth.",
  "But ours! oh, 'tis the stretch of Fancy's hope",
  "To portray its continuance as now,",
  "Warm, tranquil, spirit-healing; nor when age",
  "Has tempered these wild ecstasies, and given",
  "A soberer tinge to the luxurious glow",
  "Which blazing on devotion's pinnacle",
  "Makes virtuous passion supersede the power",
  "Of reason; nor when life's aestival sun",
  "To deeper manhood shall have ripened me;",
  "Nor when some years have added judgement's store",
  "To all thy woman sweetness, all the fire",
  "Which throbs in thine enthusiast heart; not then",
  "Shall holy friendship (for what other name",
  "May love like ours assume?), not even then",
  "Shall Custom so corrupt, or the cold forms",
  "Of this desolate world so harden us,",
  "As when we think of the dear love that binds",
  "Our souls in soft communion, while we know",
  "Each other's thoughts and feelings, can we say",
  "Unblushingly a heartless compliment,",
  "Praise, hate, or love with the unthinking world,",
  "Or dare to cut the unrelaxing nerve",
  "That knits our love to virtue. Can those eyes,",
  "Beaming with mildest radiance on my heart",
  "To purify its purity, e'er bend",
  "To soothe its vice or consecrate its fears?",
  "Never, thou second Self! Is confidence",
  "So vain in virtue that I learn to doubt",
  "The mirror even of Truth? Dark flood of Time,",
  "Roll as it listeth thee; I measure not",
  "By month or moments thy ambiguous course.",
  "Another may stand by me on thy brink,,",
  "And watch the bubble whirled beyond his ken,",
  "Which pauses at my feet. The sense of love,",
  "The thirst for action, and the impassioned thought",
  "Prolong my being; if I wake no more,",
  "My life more actual living will contain",
  "Than some gray veteran's of the world's cold school,",
  "Whose listless hours unprofitably roll",
  "By one enthusiast feeling unredeemed,",
  "Virtue and Love! unbending Fortitude,",
  "Freedom, Devotedness and Purity!",
  "That life my Spirit consecrates to you.",
  ""
]