module.exports = [
  "LESBIA! since far from you I've rang'd,",
  "  Our souls with fond affection glow not;",
  "You say, 'tis I, not you, have chang'd,",
  " I'd tell you why,--but yet I know not.",
  "",
  "Your polish'd brow no cares have crost;",
  "  And Lesbia! we are not much older,",
  "Since, trembling, first my heart I lost,",
  "  Or told my love, with hope grown bolder.",
  "",
  "Sixteen was then our utmost age,",
  "  Two years have lingering pass'd away, love!",
  "And now new thoughts our minds engage,",
  "  At least, I feel disposed to stray, love!",
  "",
  "\"Tis _I_ that am alone to blame,",
  "  _I_, that am guilty of love's treason;",
  "Since your sweet breast is still the same,",
  "  Caprice must be my only reason.",
  "",
  "I do not, love! suspect your truth,",
  "  With jealous doubt my bosom heaves not;",
  "Warm was the passion of my youth,",
  "  One trace of dark deceit it leaves not.",
  "",
  "No, no, my flame was not pretended;",
  "  For, oh! I lov'd you most sincerely;",
  "And though our dream at last is ended",
  "  My bosom still esteems you dearly.",
  "",
  "No more we meet in yonder bowers;",
  "  Absence has made me prone to roving;",
  "But older, firmer _hearts_ than ours",
  "  Have found monotony in loving.",
  "",
  "Your cheek's soft bloom is unimpair'd,",
  "  New beauties, still, are daily bright'ning,",
  "Your eye, for conquest beams prepar'd,",
  "  The forge of love's resistless lightning.",
  "",
  "Arm'd thus, to make their bosoms bleed,",
  "  Many will throng, to sigh like me, love!",
  "More constant they may prove, indeed;",
  "  Fonder, alas! they ne'er can be, love!",
  ""
]