module.exports = [
  "Mine eyes were dim with tears unshed;",
  "Yes, I was firm--thus wert not thou;--",
  "My baffled looks did fear yet dread",
  "To meet thy looks--I could not know",
  "How anxiously they sought to shine",
  "With soothing pity upon mine.",
  "",
  "To sit and curb the soul's mute rage",
  "Which preys upon itself alone;",
  "To curse the life which is the cage",
  "Of fettered grief that dares not groan,",
  "Hiding from many a careless eye",
  "The scorned load of agony.",
  "",
  "Whilst thou alone, then not regarded,",
  "The ... thou alone should be,",
  "To spend years thus, and be rewarded,",
  "As thou, sweet love, requited me",
  "When none were near--Oh! I did wake",
  "From torture for that moment's sake.",
  "",
  "Upon my heart thy accents sweet",
  "Of peace and pity fell like dew",
  "On flowers half dead;--thy lips did meet",
  "Mine tremblingly; thy dark eyes threw",
  "Their soft persuasion on my brain,",
  "Charming away its dream of pain.",
  "",
  "We are not happy, sweet! our state",
  "Is strange and full of doubt and fear;",
  "More need of words that ills abate;--",
  "Reserve or censure come not near",
  "Our sacred friendship, lest there be",
  "No solace left for thee and me.",
  "",
  "Gentle and good and mild thou art,",
  "Nor can I live if thou appear",
  "Aught but thyself, or turn thine heart",
  "Away from me, or stoop to wear",
  "The mask of scorn, although it be",
  "To hide the love thou feel'st for me.",
  ""
]