module.exports = [
  "FOR Orford and for Waldegrave",
  "You give much more than me you _gave_;",
  "Which is not fairly to behave,",
  "            My Murray!",
  "",
  "Because if a live dog, 't is said,",
  "Be worth a lion fairly sped,",
  "A live lord must be worth _two_ dead,",
  "            My Murray!",
  "",
  "And if, as the opinion goes,",
  "Verse hath a better sale than prose,--",
  "Certes, I should have more than those,",
  "            My Murray!",
  "",
  "But now this sheet is nearly crammed,",
  "So, if _you will_, _I_ shan't be shammed,",
  "And if you _won't_,--_you_ may be damned,",
  "            My Murray!",
  "           My Murray.",
  "",
  "Tours, Travels, Essays, too, I wist,",
  "And Sermons, to thy mill bring grist;",
  "And then thou hast the _Navy List_,",
  "                      My Murray.",
  "",
  "And Heaven forbid I should conclude,",
  "Without \"the Board of Longitude,\"",
  "Although this narrow paper would,",
  "                      My Murray.",
  ""
]