module.exports = [
  "LOng my dull Muse in heavy slumbers lay,",
  "Indulging Sloth, and to soft Ease gave way,",
  "Her Fill of Rest resolving to enjoy,",
  "Or fancying little worthy her employ.",
  "When Noble Cleanors obliging Strains",
  "Her, the neglected Lyre to tune, constrains.",
  "Confus'd at first, she rais'd her drowsie Head,",
  "Ponder'd a while, then pleas'd, forsook her Bed.",
  "Survey'd each Line with Fancy richly fraught,",
  "Re-read, and then revolv'd them in her Thought.",
  "  And can it be ? she said, and can it be ?",
  "That 'mong the Great Ones I a Poet see ?",
  "",
  "The Great Ones? who their Ill-spent time devide,",
  "'Twixt dang'rous Politicks, and formal Pride,",
  "Destructive Vice, expensive Vanity,",
  "In worse Ways yet, if Worse there any be:",
  "Leave to Inferiours the despised Arts,",
  "Let their Retainers be the Men of Parts.",
  "But here with Wonder and with Joy I find,",
  "I'th'Noble Born, a no less Noble Mind;",
  "One, who on Ancestors, does not rely",
  "For Fame, in Merit, as in Title, high!",
  "",
  "  The Severe Goddess thus approv'd the Laies:",
  "Yet too much pleas'd, alas, with her own Praise.",
  "But to vain Pride, My Muse, cease to give place,",
  "Virgils immortal Numbers once did grace",
  "A Smother'd Gnat: By high Applause is shown,",
  "If undeserv'd, the Praisers worth alone:",
  "Nor that you should believ't, is't always meant,",
  "'Tis often for Instruction only sent,",
  "To praise men to Amendment, and display,",
  "By its Perfection, where their Weakness lay.",
  "This Use of these Applauding Numbers make",
  "Them for Example, not Encomium, take.",
  ""
]