module.exports = [
  "Whene'er I view those lips of thine,",
  "  Their hue invites my fervent kiss;",
  "Yet, I forego that bliss divine,",
  "  Alas! it were--unhallow'd bliss.",
  "",
  "Whene'er I dream of that pure breast,",
  "  How could I dwell upon its snows!",
  "Yet, is the daring wish represt,",
  "  For that,--would banish its repose.",
  "",
  "A glance from thy soul-searching eye",
  "  Can raise with hope, depress with fear;",
  "Yet, I conceal my love,--and why?",
  "  I would not force a painful tear.",
  "",
  "I ne'er have told my love, yet thou",
  "  Hast seen my ardent flame too well;",
  "And shall I plead my passion now,",
  "  To make thy bosom's heaven a hell?",
  "",
  "No! for thou never canst be mine,",
  "  United by the priest's decree:",
  "By any ties but those divine,",
  "  Mine, my belov'd, thou ne'er shalt be.",
  "",
  "Then let the secret fire consume,",
  "  Let it consume, thou shalt not know:",
  "With joy I court a certain doom,",
  "  Rather than spread its guilty glow.",
  "",
  "I will not ease my tortur'd heart,",
  "  By driving dove-ey'd peace from thine;",
  "Rather than such a sting impart,",
  "  Each thought presumptuous I resign.",
  "",
  "Yes! yield those lips, for which I'd brave",
  "  More than I here shall dare to tell;",
  "Thy innocence and mine to save,--",
  "  I bid thee now a last farewell.",
  "",
  "Yes! yield that breast, to seek despair",
  "  And hope no more thy soft embrace;",
  "Which to obtain, my soul would dare,",
  "  All, all reproach, but thy disgrace.",
  "",
  "At least from guilt shall thou be free,",
  "  No matron shall thy shame reprove;",
  "Though cureless pangs may prey on me,",
  "  No martyr shall thou be to love.",
  ""
]