module.exports = [
  "MARION! why that pensive brow?",
  "What disgust to life hast thou?",
  "Change that discontented air;",
  "Frowns become not one so fair.",
  "'Tis not Love disturbs thy rest,",
  "Love's a stranger to thy breast:",
  "_He_, in dimpling smiles, appears,",
  "Or mourns in sweetly timid tears;",
  "Or bends the languid eyelid down,",
  "But _shuns_ the cold forbidding 'frown'.",
  "Then resume thy former fire,",
  "Some will _love_, and all admire!",
  "While that icy aspect chills us,",
  "Nought but cool Indiff'rence thrills us.",
  "Would'st thou wand'ring hearts beguile,",
  "Smile, at least, or _seem_ to _smile_;",
  "Eyes like _thine_ were never meant",
  "To hide their orbs in dark restraint;",
  "Spite of all thou fain wouldst say,",
  "Still in _truant_ beams they play.",
  "Thy lips--but here my _modest_ Muse",
  "Her impulse _chaste_ must needs refuse:",
  "She _blushes, curtsies, frowns,_--in short She",
  "Dreads lest the _Subject_ should transport me;",
  "And flying off, in search of _Reason_,",
  "Brings Prudence back in proper season.",
  "_All_ I shall, therefore, say (whate'er",
  "I think, is neither here nor there,)",
  "Is, that such _lips_, of looks endearing,",
  "Were form'd for _better things_ than _sneering_.",
  "Of soothing compliments divested,",
  "Advice at least's disinterested;",
  "Such is my artless song to thee,",
  "From all the flow of Flatt'ry free;",
  "Counsel like _mine_ is as a brother's,",
  "_My_ heart is given to some others;",
  "That is to say, unskill'd to cozen,",
  "It shares itself among a dozen.",
  "",
  "  Marion, adieu! oh, pr'ythee slight not",
  "This warning, though it may delight not;",
  "And, lest my precepts be displeasing,",
  "To those who think remonstrance teazing,",
  "At once I'll tell thee our opinion,",
  "Concerning Woman's soft Dominion:",
  "Howe'er we gaze, with admiration,",
  "On eyes of blue or lips carnation;",
  "Howe'er the flowing locks attract us,",
  "Howe'er those beauties may distract us;",
  "Still fickle, we are prone to rove,",
  "_These_ cannot fix our souls to love;",
  "It is not too _severe_ a stricture,",
  "To say they form a _pretty picture_;",
  "But would'st thou see the secret chain,",
  "Which binds us in your humble train,",
  "To hail you Queens of all Creation,",
  "Know, in a _word, 'tis Animation_.",
  ""
]