module.exports = [
  "Oh! did those eyes, instead of fire,",
  "  With bright, but mild affection shine:",
  "Though they might kindle less desire,",
  "  Love, more than mortal, would be thine.",
  "",
  "For thou art form'd so heavenly fair,",
  "  _Howe'er_ those orbs _may_ wildly beam,",
  "We must _admire,_ but still despair;",
  "  That fatal glance forbids esteem.",
  "",
  "When Nature stamp'd thy beauteous birth,",
  "  So much perfection in thee shone,",
  "She fear'd that, too divine for earth,",
  "  The skies might claim thee for their own.",
  "",
  "Therefore, to guard her dearest work,",
  "  Lest angels might dispute the prize,",
  "She bade a secret lightning lurk,",
  "  Within those once celestial eyes.",
  "",
  "These might the boldest Sylph appall,",
  "  When gleaming with meridian blaze;",
  "Thy beauty must enrapture all;",
  "  But who can dare thine ardent gaze?",
  "",
  "'Tis said that Berenice's hair,",
  "  In stars adorns the vault of heaven;",
  "But they would ne'er permit _thee_ there,",
  "  _Thou_ wouldst so far outshine the seven.",
  "",
  "For did those eyes as planets roll,",
  "  Thy sister-lights would scarce appear:",
  "E'en suns, which systems now controul,",
  "  Would twinkle dimly through their sphere.",
  ""
]