module.exports = [
  "This faint resemblance of thy charms,",
  "  (Though strong as mortal art could give,)",
  "My constant heart of fear disarms,",
  "  Revives my hopes, and bids me live.",
  "",
  "Here, I can trace the locks of gold",
  "  Which round thy snowy forehead wave;",
  "The cheeks which sprung from Beauty's mould,",
  "  The lips, which made me 'Beauty's' slave.",
  "",
  "Here I can trace--ah, no! that eye,",
  "  Whose azure floats in liquid fire,",
  "Must all the painter's art defy,",
  "  And bid him from the task retire.",
  "",
  "Here, I behold its beauteous hue;",
  "But where's the beam so sweetly straying,",
  "Which gave a lustre to its blue,",
  "  Like Luna o'er the ocean playing?",
  "",
  "Sweet copy! far more dear to me,",
  "  Lifeless, unfeeling as thou art,",
  "Than all the living forms could be,",
  "  Save her who plac'd thee next my heart.",
  "",
  "She plac'd it, sad, with needless fear,",
  "  Lest time might shake my wavering soul,",
  "Unconscious that her image there",
  "  Held every sense in fast controul.",
  "",
  "Thro' hours, thro' years, thro' time,'twill cheer--",
  "  My hope, in gloomy moments, raise;",
  "In life's last conflict 'twill appear,",
  "  And meet my fond, expiring gaze.",
  ""
]