module.exports = [
  "Without a stone to mark the spot,",
  "  And say, what Truth might well have said,",
  "By all, save one, perchance forgot,",
  "  Ah! wherefore art thou lowly laid?",
  "By many a shore and many a sea",
  "  Divided, yet beloved in vain;",
  "The Past, the Future fled to thee,",
  "  To bid us meet--no--ne'er again!",
  "Could this have been--a word, a look,",
  "  That softly said, \"We part in peace,\"",
  "Had taught my bosom how to brook,",
  "  With fainter sighs, thy soul's release.",
  "And didst thou not, since Death for thee",
  "  Prepared a light and pangless dart,",
  "Once long for him thou ne'er shalt see,",
  "  Who held, and holds thee in his heart?",
  "Oh! who like him had watched thee here?",
  "  Or sadly marked thy glazing eye,",
  "In that dread hour ere Death appear,",
  "  When silent Sorrow fears to sigh,",
  "Till all was past? But when no more",
  "  'Twas thine to reck of human woe,",
  "Affection's heart-drops, gushing o'er,",
  "  Had flowed as fast--as now they flow.",
  "Shall they not flow, when many a day",
  "  In these, to me, deserted towers,",
  "Ere called but for a time away,",
  "  Affection's mingling tears were ours?",
  "Ours too the glance none saw beside;",
  "  The smile none else might understand;",
  "The whispered thought of hearts allied,",
  "  The pressure of the thrilling hand;",
  "The kiss, so guiltless and refined,",
  "  That Love each warmer wish forbore;",
  "Those eyes proclaimed so pure a mind,",
  "  Ev'n Passion blushed to plead for more.",
  "The tone, that taught me to rejoice,",
  "  When prone, unlike thee, to repine;",
  "The song, celestial from thy voice,",
  "  But sweet to me from none but thine;",
  "The pledge we wore--_I_ wear it still,",
  "  But where is thine?--Ah! where art thou?",
  "Oft have I borne the weight of ill,",
  "  But never bent beneath till now!",
  "Well hast thou left in Life's best bloom",
  "  The cup of Woe for me to drain.",
  "If rest alone be in the tomb,",
  "  I would not wish thee here again:",
  "But if in worlds more blest than this",
  "  Thy virtues seek a fitter sphere,",
  "Impart some portion of thy bliss,",
  "  To wean me from mine anguish here.",
  "Teach me--too early taught by thee!",
  "  To bear, forgiving and forgiven:",
  "On earth thy love was such to me;",
  "  It fain would form my hope in Heaven!",
  ""
]