module.exports = [
  "What are you doing now,",
  "  Oh Thomas Moore?",
  "What are you doing now,",
  "  Oh Thomas Moore?",
  "Sighing or suing now,",
  "Rhyming or wooing now,",
  "Billing or cooing now,",
  "  Which, Thomas Moore?",
  "",
  "But the Carnival's coming,",
  "  Oh Thomas Moore!",
  "The Carnival's coming,",
  "  Oh Thomas Moore!",
  "Masking and humming,",
  "Fifing and drumming,",
  "Guitarring and strumming,",
  "  Oh Thomas Moore!",
  " It hath springs that may be won.",
  "",
  "Were't the last drop in the well,",
  "  As I gasped upon the brink,",
  "Ere my fainting spirit fell,",
  "  'T is to thee that I would drink.",
  "",
  "With that water, as this wine,",
  "  The libation I would pour",
  "Should be--peace with thine and mine,",
  "  And a health to thee, Tom Moore.",
  "put on my breeches, and wait on the Heathcote;",
  "But to-morrow, at four, we will both play the _Scurra_,",
  "And you'll be Catullus, the Regent Mamurra.",
  ""
]