module.exports = [
  "Under General Greene, in South Carolina,",
  "    who fell in the action of September 8, 1781",
  "",
  "AT Eutaw Springs the valiant died;",
  "  Their limbs with dust are covered o'er--",
  "Weep on, ye springs, your tearful tide;",
  "  How many heroes are no more!",
  "",
  "If in this wreck or ruin, they",
  "  Can yet be thought to claim a tear,",
  "O smite your gentle breast, and say",
  "  The friends of freedom slumber here!",
  "",
  "Thou, who shalt trace this bloody plain,",
  "  If goodness rules thy generous breast,",
  "Sigh for the wasted rural reign;",
  "  Sign for the shepherds, sunk to rest!",
  "",
  "Stranger, their humble graves adorn;",
  "  You too may fall, and ask a tear;",
  "'Tis not the beauty of the morn",
  "  That proves the evening shall be clear.--",
  "",
  "They saw their injured country's woe;",
  "  The flaming town, the wasted field;",
  "Then rushed to meet the insulting foe;",
  "  They took the spear--but left the shield.",
  "",
  "Led by thy conquering genius, Greene,",
  "  The Britons they compelled to fly;",
  "None distant viewed the fatal plain,",
  "  None grieved, in such a cause to die--",
  "",
  "But, like the Parthian, famed of old,",
  "  Who, flying, still their arrows threw,",
  "These routed Britons, full as bold,",
  "  Retreated, and retreating slew.",
  "",
  "Now rest in peace, our patriot band,",
  "  Though far from nature's limits thrown,",
  "We trust they find a happier land,",
  "  A brighter sunshine of their own.",
  ""
]