module.exports = [
  "Thy country's curse is on thee, darkest crest",
  "Of that foul, knotted, many-headed worm",
  "Which rends our Mother's bosom--Priestly Pest!",
  "Masked Resurrection of a buried Form!",
  "",
  "Thy country's curse is on thee! Justice sold,",
  "Truth trampled, Nature's landmarks overthrown,",
  "And heaps of fraud-accumulated gold,",
  "Plead, loud as thunder, at Destruction's throne.",
  "",
  "And whilst that sure slow Angel which aye stands",
  "Watching the beck of Mutability",
  "Delays to execute her high commands,",
  "And, though a nation weeps, spares thine and thee,",
  "",
  "Oh, let a father's curse be on thy soul,",
  "And let a daughter's hope be on thy tomb;",
  "Be both, on thy gray head, a leaden cowl",
  "To weigh thee down to thine approaching doom.",
  "",
  "I curse thee by a parent's outraged love,",
  "By hopes long cherished and too lately lost,",
  "By gentle feelings thou couldst never prove,",
  "By griefs which thy stern nature never crossed;",
  "",
  "By those infantine smiles of happy light,",
  "Which were a fire within a stranger's hearth,",
  "Quenched even when kindled, in untimely night",
  "Hiding the promise of a lovely birth:",
  "",
  "By those unpractised accents of young speech,",
  "Which he who is a father thought to frame",
  "To gentlest lore, such as the wisest teach--",
  "THOU strike the lyre of mind!--oh, grief and shame!",
  "",
  "By all the happy see in children's growth--",
  "That undeveloped flower of budding years--",
  "Sweetness and sadness interwoven both,",
  "Source of the sweetest hopes and saddest fears-",
  "",
  "By all the days, under an hireling's care,",
  "Of dull constraint and bitter heaviness,--",
  "O wretched ye if ever any were,--",
  "Sadder than orphans, yet not fatherless!",
  "",
  "By the false cant which on their innocent lips",
  "Must hang like poison on an opening bloom,",
  "By the dark creeds which cover with eclipse",
  "Their pathway from the cradle to the tomb--",
  "",
  "By thy most impious Hell, and all its terror;",
  "By all the grief, the madness, and the guilt",
  "Of thine impostures, which must be their error--",
  "That sand on which thy crumbling power is built--",
  "",
  "By thy complicity with lust and hate--",
  "Thy thirst for tears--thy hunger after gold--",
  "The ready frauds which ever on thee wait--",
  "The servile arts in which thou hast grown old--",
  "",
  "By thy most killing sneer, and by thy smile--",
  "By all the arts and snares of thy black den,",
  "And--for thou canst outweep the crocodile--",
  "By thy false tears--those millstones braining men--",
  "",
  "By all the hate which checks a father's love--",
  "By all the scorn which kills a father's care--",
  "By those most impious hands which dared remove",
  "Nature's high bounds--by thee--and by despair--",
  "",
  "Yes, the despair which bids a father groan,",
  "And cry, 'My children are no longer mine--",
  "The blood within those veins may be mine own,",
  "But--Tyrant--their polluted souls are thine;--",
  "",
  "I curse thee--though I hate thee not.--O slave!",
  "If thou couldst quench the earth-consuming Hell",
  "Of which thou art a daemon, on thy grave",
  "This curse should be a blessing. Fare thee well!",
  ""
]