module.exports = [
  "Shall we roam, my love,",
  "To the twilight grove,",
  "When the moon is rising bright;",
  "Oh, I'll whisper there,",
  "In the cool night-air,",
  "What I dare not in broad daylight!",
  "",
  "I'll tell thee a part",
  "Of the thoughts that start",
  "To being when thou art nigh;",
  "And thy beauty, more bright",
  "Than the stars' soft light,",
  "Shall seem as a weft from the sky.",
  "",
  "When the pale moonbeam",
  "On tower and stream",
  "Sheds a flood of silver sheen,",
  "How I love to gaze",
  "As the cold ray strays",
  "O'er thy face, my heart's throned queen!",
  "",
  "Wilt thou roam with me",
  "To the restless sea,",
  "And linger upon the steep,",
  "And list to the flow",
  "Of the waves below",
  "How they toss and roar and leap?",
  "",
  "Those boiling waves,",
  "And the storm that raves",
  "At night o'er their foaming crest,",
  "Resemble the strife",
  "That, from earliest life,",
  "The passions have waged in my breast.",
  "",
  "Oh, come then, and rove",
  "To the sea or the grove,",
  "When the moon is rising bright;",
  "And I'll whisper there,",
  "In the cool night-air,",
  "What I dare not in broad daylight.",
  ""
]