module.exports = [
  "You have asked for a verse:--the request",
  "  In a rhymer 'twere strange to deny;",
  "But my Hippocrene was but my breast,",
  "  And my feelings (its fountain) are dry.",
  "",
  "Were I now as I was, I had sung",
  "  What Lawrence has painted so well;",
  "But the strain would expire on my tongue,",
  "  And the theme is too soft for my shell.",
  "",
  "I am ashes where once I was fire,",
  "  And the bard in my bosom is dead;",
  "What I loved I now merely admire,",
  "  And my heart is as grey as my head.",
  "",
  "My Life is not dated by years--",
  "  There are _moments_ which act as a plough,",
  "And there is not a furrow appears",
  "  But is deep in my soul as my brow.",
  "",
  "Let the young and the brilliant aspire",
  "  To sing what I gaze on in vain;",
  "For Sorrow has torn from my lyre",
  "  The string which was worthy the strain.",
  "",
  "                                                                    B.",
  ""
]