module.exports = [
  "Thy little footsteps on the sands",
  "Of a remote and lonely shore;",
  "The twinkling of thine infant hands,",
  "Where now the worm will feed no more;",
  "Thy mingled look of love and glee",
  "When we returned to gaze on thee--",
  "shes find a tomb,",
  "But beneath this pyramid",
  "Thou art not--if a thing divine",
  "Like thee can die, thy funeral shrine",
  "Is thy mother's grief and mine.",
  "",
  "Where art thou, my gentle child?",
  "Let me think thy spirit feeds,",
  "With its life intense and mild,",
  "The love of living leaves and weeds",
  "Among these tombs and ruins wild;--",
  "Let me think that through low seeds",
  "Of sweet flowers and sunny grass",
  "Into their hues and scents may pass",
  "A portion--",
  "",
  "Come thou, beloved as thou art;",
  "Another sleepeth still",
  "Near thy sweet mother's anxious heart,",
  "Which thou with joy shalt fill,",
  "With fairest smiles of wonder thrown",
  "On that which is indeed our own,",
  "And which in distant lands will be",
  "The dearest playmate unto thee.",
  "",
  "Fear not the tyrants will rule for ever,",
  "Or the priests of the evil faith;",
  "They stand on the brink of that raging river,",
  "Whose waves they have tainted with death.",
  "It is fed from the depth of a thousand dells,",
  "Around them it foams and rages and swells;",
  "And their swords and their sceptres I floating see,",
  "Like wrecks on the surge of eternity.",
  "",
  "Rest, rest, and shriek not, thou gentle child!",
  "The rocking of the boat thou fearest,",
  "And the cold spray and the clamour wild?--",
  "There, sit between us two, thou dearest--",
  "Me and thy mother--well we know",
  "The storm at which thou tremblest so,",
  "With all its dark and hungry graves,",
  "Less cruel than the savage slaves",
  "Who hunt us o'er these sheltering waves.",
  "",
  "This hour will in thy memory",
  "Be a dream of days forgotten long.",
  "We soon shall dwell by the azure sea",
  "Of serene and golden Italy,",
  "Or Greece, the Mother of the free;",
  "And I will teach thine infant tongue",
  "To call upon those heroes old",
  "In their own language, and will mould",
  "Thy growing spirit in the flame",
  "Of Grecian lore, that by such name",
  "A patriot's birthright thou mayst claim!",
  ""
]