module.exports = [
  "",
  "Aprochen gan the fatal destinee",
  "That Ioves hath in disposicioun,",
  "And to yow, angry Parcas, sustren three,",
  "Committeth, to don execucioun;",
  "For which Criseyde moste out of the toun,",
  "And Troilus shal dwelle forth in pyne",
  "Til Lachesis his threed no lenger twyne. --",
  "",
  "The golden-tressed Phebus heighe on-lofte",
  "Thryes hadde alle with his bemes shene",
  "The snowes molte, and Zephirus as ofte",
  "Y-brought ayein the tendre leves grene,",
  "Sin that the sone of Ecuba the quene",
  "Bigan to love hir first, for whom his sorwe",
  "Was al, that she departe sholde a-morwe.",
  "",
  "Ful redy was at pryme Dyomede,",
  "Criseyde un-to the Grekes ost to lede,",
  "For sorwe of which she felt hir herte blede,",
  "As she that niste what was best to rede.",
  "And trewely, as men in bokes rede,",
  "Men wiste never womman han the care,",
  "Ne was so looth out of a toun to fare.",
  "",
  "This Troilus, with-outen reed or lore,",
  "As man that hath his Ioyes eek forlore,",
  "Was waytinge on his lady ever-more",
  "As she that was the soothfast crop and more",
  "Of al his lust, or Ioyes here-tofore.",
  "But Troilus, now farewel al thy Ioye,",
  "For shaltow never seen hir eft in Troye!",
  "",
  "Soth is, that whyl he bood in this manere,",
  "He gan his wo ful manly for to hyde.",
  "That wel unnethe it seen was in his chere;",
  "But at the yate ther she sholde oute ryde",
  "With certeyn folk, he hoved hir tabyde,",
  "So wo bigoon, al wolde he nought him pleyne,",
  "That on his hors unnethe he sat for peyne.",
  "",
  "For ire he quook, so gan his herte gnawe,",
  "Whan Diomede on horse gan him dresse,",
  "And seyde un-to him-self this ilke sawe,",
  "`Allas,' quod he, `thus foul a wrecchednesse",
  "Why suffre ich it, why nil ich it redresse?",
  "Were it not bet at ones for to dye",
  "Than ever-more in langour thus to drye?",
  "",
  "`Why nil I make at ones riche and pore",
  "To have y-nough to done, er that she go?",
  "Why nil I bringe al Troye upon a rore?",
  "Why nil I sleen this Diomede also?",
  "Why nil I rather with a man or two",
  "Stele hir a-way? Why wol I this endure?",
  "Why nil I helpen to myn owene cure?'",
  "",
  "But why he nolde doon so fel a dede,",
  "That shal I seyn, and why him liste it spare;",
  "He hadde in herte alweyes a maner drede,",
  "Lest that Criseyde, in rumour of this fare,",
  "Sholde han ben slayn; lo, this was al his care.",
  "And ellis, certeyn, as I seyde yore,",
  "He hadde it doon, with-outen wordes more.",
  "",
  "Criseyde, whan she redy was to ryde,",
  "Ful sorwfully she sighte, and seyde `Allas!'",
  "But forth she moot, for ought that may bityde,",
  "And forth she rit ful sorwfully a pas.",
  "Ther nis non other remedie in this cas.",
  "What wonder is though that hir sore smerte,",
  "Whan she forgoth hir owene swete herte?",
  "",
  "This Troilus, in wyse of curteisye,",
  "With hauke on hond, and with an huge route",
  "Of knightes, rood and dide hir companye,",
  "Passinge al the valey fer with-oute,",
  "And ferther wolde han riden, out of doute,",
  "Ful fayn, and wo was him to goon so sone;",
  "But torne he moste, and it was eek to done.",
  "",
  "And right with that was Antenor y-come",
  "Out of the Grekes ost, and every wight",
  "Was of it glad, and seyde he was wel-come.",
  "And Troilus, al nere his herte light,",
  "He peyned him with al his fulle might",
  "Him to with-holde of wepinge at the leste,",
  "And Antenor he kiste, and made feste.",
  "",
  "And ther-with-al he moste his leve take,",
  "And caste his eye upon hir pitously,",
  "And neer he rood, his cause for to make,",
  "To take hir by the honde al sobrely.",
  "And lord! So she gan wepen tendrely!",
  "And he ful softe and sleighly gan hir seye,",
  "`Now hold your day, and dooth me not to deye.'",
  "",
  "With that his courser torned he a-boute",
  "With face pale, and un-to Diomede",
  "No word he spak, ne noon of al his route;",
  "Of which the sone of Tydeus took hede,",
  "As he that coude more than the crede",
  "In swich a craft, and by the reyne hir hente;",
  "And Troilus to Troye homwarde he wente.",
  "",
  "This Diomede, that ladde hir by the brydel,",
  "Whan that he saw the folk of Troye aweye,",
  "Thoughte, `Al my labour shal not been on ydel,",
  "If that I may, for somwhat shal I seye,",
  "For at the worste it may yet shorte our weye.",
  "I have herd seyd, eek tymes twyes twelve,",
  "\"He is a fool that wol for-yete him-selve.\"'",
  "",
  "But natheles this thoughte he wel ynough,",
  "`That certaynly I am aboute nought,",
  "If that I speke of love, or make it tough;",
  "For douteles, if she have in hir thought",
  "Him that I gesse, he may not been y-brought",
  "So sone awey; but I shal finde a mene,",
  "That she not wite as yet shal what I mene.'",
  "",
  "This Diomede, as he that coude his good,",
  "Whan this was doon, gan fallen forth in speche",
  "Of this and that, and asked why she stood",
  "In swich disese, and gan hir eek biseche,",
  "That if that he encrese mighte or eche",
  "With any thing hir ese, that she sholde",
  "Comaunde it him, and seyde he doon it wolde.",
  "",
  "For trewely he swoor hir, as a knight,",
  "That ther nas thing with whiche he mighte hir plese,",
  "That he nolde doon his peyne and al his might",
  "To doon it, for to doon hir herte an ese.",
  "And preyede hir, she wolde hir sorwe apese,",
  "And seyde, `Y-wis, we Grekes con have Ioye",
  "To honouren yow, as wel as folk of Troye.'",
  "",
  "He seyde eek thus, `I woot, yow thinketh straunge,",
  "No wonder is, for it is to yow newe,",
  "Thaqueintaunce of these Troianis to chaunge,",
  "For folk of Grece, that ye never knewe.",
  "But wolde never god but-if as trewe",
  "A Greek ye shulde among us alle finde",
  "As any Troian is, and eek as kinde.",
  "",
  "`And by the cause I swoor yow right, lo, now,",
  "To been your freend, and helply, to my might,",
  "And for that more aqueintaunce eek of yow",
  "Have ich had than another straunger wight,",
  "So fro this forth, I pray yow, day and night,",
  "Comaundeth me, how sore that me smerte,",
  "To doon al that may lyke un-to your herte;",
  "",
  "`And that ye me wolde as your brother trete,",
  "And taketh not my frendship in despyt;",
  "And though your sorwes be for thinges grete,",
  "Noot I not why, but out of more respyt,",
  "Myn herte hath for to amende it greet delyt.",
  "And if I may your harmes not redresse,",
  "I am right sory for your hevinesse,",
  "",
  "`And though ye Troians with us Grekes wrothe",
  "Han many a day be, alwey yet, pardee,",
  "O god of love in sooth we serven bothe.",
  "And, for the love of god, my lady free,",
  "Whom so ye hate, as beth not wroth with me.",
  "For trewely, ther can no wight yow serve,",
  "That half so looth your wraththe wolde deserve.",
  "",
  "`And nere it that we been so neigh the tente",
  "Of Calkas, which that seen us bothe may,",
  "I wolde of this yow telle al myn entente;",
  "But this enseled til another day.",
  "Yeve me your hond, I am, and shal ben ay,",
  "God help me so, whyl that my lyf may dure,",
  "Your owene aboven every creature.",
  "",
  "`Thus seyde I never er now to womman born;",
  "For god myn herte as wisly glade so,",
  "I lovede never womman here-biforn",
  "As paramours, ne never shal no mo.",
  "And, for the love of god, beth not my fo;",
  "Al can I not to yow, my lady dere,",
  "Compleyne aright, for I am yet to lere.",
  "",
  "`And wondreth not, myn owene lady bright,",
  "Though that I speke of love to you thus blyve;",
  "For I have herd or this of many a wight,",
  "Hath loved thing he never saugh his lyve.",
  "Eek I am not of power for to stryve",
  "Ayens the god of love, but him obeye",
  "I wol alwey, and mercy I yow preye.",
  "",
  "`Ther been so worthy knightes in this place,",
  "And ye so fair, that everich of hem alle",
  "Wol peynen him to stonden in your grace.",
  "But mighte me so fair a grace falle,",
  "That ye me for your servaunt wolde calle,",
  "So lowly ne so trewely you serve",
  "Nil noon of hem, as I shal, til I sterve.'",
  "",
  "Criseide un-to that purpos lyte answerde,",
  "As she that was with sorwe oppressed so",
  "That, in effect, she nought his tales herde,",
  "But here and there, now here a word or two.",
  "Hir thoughte hir sorwful herte brast a-two.",
  "For whan she gan hir fader fer aspye,",
  "Wel neigh doun of hir hors she gan to sye.",
  "",
  "But natheles she thonked Diomede",
  "Of al his travaile, and his goode chere,",
  "And that him liste his friendship hir to bede;",
  "And she accepteth it in good manere,",
  "And wolde do fayn that is him leef and dere;",
  "And trusten him she wolde, and wel she mighte,",
  "As seyde she, and from hir hors she alighte.",
  "",
  "Hir fader hath hir in his armes nome,",
  "And tweynty tyme he kiste his doughter swete,",
  "And seyde, `O dere doughter myn, wel-come!'",
  "She seyde eek, she was fayn with him to mete,",
  "And stood forth mewet, milde, and mansuete.",
  "But here I leve hir with hir fader dwelle,",
  "And forth I wol of Troilus yow telle.",
  "",
  "To Troye is come this woful Troilus,",
  "In sorwe aboven alle sorwes smerte,",
  "With felon look, and face dispitous.",
  "Tho sodeinly doun from his hors he sterte,",
  "And thorugh his paleys, with a swollen herte,",
  "To chambre he wente; of no-thing took he hede,",
  "Ne noon to him dar speke a word for drede.",
  "",
  "And there his sorwes that he spared hadde",
  "He yaf an issue large, and `Deeth!' he cryde;",
  "And in his throwes frenetyk and madde",
  "He cursed Iove, Appollo, and eek Cupyde,",
  "He cursed Ceres, Bacus, and Cipryde,",
  "His burthe, him-self, his fate, and eek nature,",
  "And, save his lady, every creature.",
  "",
  "To bedde he goth, and weyleth there and torneth",
  "In furie, as dooth he, Ixion in helle;",
  "And in this wyse he neigh til day soiorneth.",
  "But tho bigan his herte a lyte unswelle",
  "Thorugh teres which that gonnen up to welle;",
  "And pitously he cryde up-on Criseyde,",
  "And to him-self right thus he spak, and seyde: --",
  "",
  "`Wher is myn owene lady lief and dere,",
  "Wher is hir whyte brest, wher is it, where?",
  "Wher ben hir armes and hir eyen clere,",
  "That yesternight this tyme with me were?",
  "Now may I wepe allone many a tere,",
  "And graspe aboute I may, but in this place,",
  "Save a pilowe, I finde nought tenbrace.",
  "",
  "`How shal I do? Whan shal she com ayeyn?",
  "I noot, allas! Why leet ich hir to go?",
  "As wolde god, ich hadde as tho be sleyn!",
  "O herte myn, Criseyde, O swete fo!",
  "O lady myn, that I love and no mo!",
  "To whom for ever-mo myn herte I dowe;",
  "See how I deye, ye nil me not rescowe!",
  "",
  "`Who seeth yow now, my righte lode-sterre?",
  "Who sit right now or stant in your presence?",
  "Who can conforten now your hertes werre?",
  "Now I am gon, whom yeve ye audience?",
  "Who speketh for me right now in myn absence?",
  "Allas, no wight; and that is al my care;",
  "For wel wot I, as yvel as I ye fare.",
  "",
  "`How sholde I thus ten dayes ful endure,",
  "Whan I the firste night have al this tene?",
  "How shal she doon eek, sorwful creature?",
  "For tendernesse, how shal she this sustene,",
  "Swich wo for me? O pitous, pale, and grene",
  "Shal been your fresshe wommanliche face",
  "For langour, er ye torne un-to this place.'",
  "",
  "And whan he fil in any slomeringes,",
  "Anoon biginne he sholde for to grone,",
  "And dremen of the dredfulleste thinges",
  "That mighte been; as, mete he were allone",
  "In place horrible, makinge ay his mone,",
  "Or meten that he was amonges alle",
  "His enemys, and in hir hondes falle.",
  "",
  "And ther-with-al his body sholde sterte,",
  "And with the stert al sodeinliche awake,",
  "And swich a tremour fele aboute his herte,",
  "That of the feer his body sholde quake;",
  "And there-with-al he sholde a noyse make,",
  "And seme as though he sholde falle depe",
  "From heighe a-lofte; and than he wolde wepe,",
  "",
  "And rewen on him-self so pitously,",
  "That wonder was to here his fantasye.",
  "Another tyme he sholde mightily",
  "Conforte him-self, and seyn it was folye,",
  "So causeles swich drede for to drye,",
  "And eft biginne his aspre sorwes newe,",
  "That every man mighte on his sorwes rewe.",
  "",
  "Who coude telle aright or ful discryve",
  "His wo, his pleynt, his langour, and his pyne?",
  "Nought al the men that han or been on-lyve.",
  "Thou, redere, mayst thy-self ful wel devyne",
  "That swich a wo my wit can not defyne.",
  "On ydel for to wryte it sholde I swinke,",
  "Whan that my wit is wery it to thinke.",
  "",
  "On hevene yet the sterres were sene,",
  "Al-though ful pale y-waxen was the mone;",
  "And whyten gan the orisonte shene",
  "Al estward, as it woned is for to done.",
  "And Phebus with his rosy carte sone",
  "Gan after that to dresse him up to fare,",
  "Whan Troilus hath sent after Pandare.",
  "",
  "This Pandare, that of al the day biforn",
  "Ne mighte han comen Troilus to see,",
  "Al-though he on his heed it hadde y-sworn,",
  "For with the king Pryam alday was he,",
  "So that it lay not in his libertee",
  "No-wher to gon, but on the morwe he wente",
  "To Troilus, whan that he for him sente.",
  "",
  "For in his herte he coude wel devyne,",
  "That Troilus al night for sorwe wook;",
  "And that he wolde telle him of his pyne,",
  "This knew he wel y-nough, with-oute book.",
  "For which to chaumbre streight the wey he took,",
  "And Troilus tho sobreliche he grette,",
  "And on the bed ful sone he gan him sette.",
  "",
  "`My Pandarus,' quod Troilus, `the sorwe",
  "Which that I drye, I may not longe endure.",
  "I trowe I shal not liven til to-morwe;",
  "For whiche I wolde alwey, on aventure,",
  "To thee devysen of my sepulture",
  "The forme, and of my moeble thou dispone",
  "Right as thee semeth best is for to done.",
  "",
  "`But of the fyr and flaumbe funeral",
  "In whiche my body brenne shal to glede,",
  "And of the feste and pleyes palestral",
  "At my vigile, I prey thee tak good hede",
  "That be wel; and offre Mars my stede,",
  "My swerd, myn helm, and, leve brother dere,",
  "My sheld to Pallas yef, that shyneth clere.",
  "",
  "`The poudre in which myn herte y-brend shal torne,",
  "That preye I thee thou take and it conserve",
  "In a vessel, that men clepeth an urne,",
  "Of gold, and to my lady that I serve,",
  "For love of whom thus pitously I sterve,",
  "So yeve it hir, and do me this plesaunce,",
  "To preye hir kepe it for a remembraunce.",
  "",
  "`For wel I fele, by my maladye,",
  "And by my dremes now and yore ago,",
  "Al certeinly, that I mot nedes dye.",
  "The owle eek, which that hight Ascaphilo,",
  "Hath after me shright alle thise nightes two.",
  "And, god Mercurie! Of me now, woful wrecche,",
  "The soule gyde, and, whan thee list, it fecche!'",
  "",
  "Pandare answerde, and seyde, `Troilus,",
  "My dere freend, as I have told thee yore,",
  "That it is folye for to sorwen thus,",
  "And causeles, for whiche I can no-more.",
  "But who-so wol not trowen reed ne lore,",
  "I can not seen in him no remedye,",
  "But lete him worthen with his fantasye.",
  "",
  "`But Troilus, I pray thee tel me now,",
  "If that thou trowe, er this, that any wight",
  "Hath loved paramours as wel as thou?",
  "Ye, god wot, and fro many a worthy knight",
  "Hath his lady goon a fourtenight,",
  "And he not yet made halvendel the fare.",
  "What nede is thee to maken al this care?",
  "",
  "`Sin day by day thou mayst thy-selven see",
  "That from his love, or elles from his wyf,",
  "A man mot twinnen of necessitee,",
  "Ye, though he love hir as his owene lyf;",
  "Yet nil he with him-self thus maken stryf.",
  "For wel thow wost, my leve brother dere,",
  "That alwey freendes may nought been y-fere.",
  "",
  "`How doon this folk that seen hir loves wedded",
  "By freendes might, as it bi-tit ful ofte,",
  "And seen hem in hir spouses bed y-bedded?",
  "God woot, they take it wysly, faire and softe.",
  "For-why good hope halt up hir herte on-lofte,",
  "And for they can a tyme of sorwe endure;",
  "As tyme hem hurt, a tyme doth hem cure.",
  "",
  "`So sholdestow endure, and late slyde",
  "The tyme, and fonde to ben glad and light.",
  "Ten dayes nis so longe not tabyde.",
  "And sin she thee to comen hath bihight,",
  "She nil hir hestes breken for no wight.",
  "For dred thee not that she nil finden weye",
  "To come ayein, my lyf that dorste I leye.",
  "",
  "`Thy swevenes eek and al swich fantasye",
  "Dryf out, and lat hem faren to mischaunce;",
  "For they procede of thy malencolye,",
  "That doth thee fele in sleep al this penaunce.",
  "A straw for alle swevenes signifiaunce!",
  "God helpe me so, I counte hem not a bene,",
  "Ther woot no man aright what dremes mene.",
  "",
  "`For prestes of the temple tellen this,",
  "That dremes been the revelaciouns",
  "Of goddes, and as wel they telle, y-wis,",
  "That they ben infernals illusiouns;",
  "And leches seyn, that of complexiouns",
  "Proceden they, or fast, or glotonye.",
  "Who woot in sooth thus what they signifye?",
  "",
  "`Eek othere seyn that thorugh impressiouns,",
  "As if a wight hath faste a thing in minde,",
  "That ther-of cometh swiche avisiouns;",
  "And othere seyn, as they in bokes finde,",
  "That, after tymes of the yeer by kinde,",
  "Men dreme, and that theffect goth by the mone;",
  "But leve no dreem, for it is nought to done.",
  "",
  "`Wel worth of dremes ay thise olde wyves,",
  "And treweliche eek augurie of thise foules;",
  "For fere of which men wenen lese her lyves,",
  "As ravenes qualm, or shryking of thise oules.",
  "To trowen on it bothe fals and foul is.",
  "Allas, allas, so noble a creature",
  "As is a man, shal drede swich ordure!",
  "",
  "`For which with al myn herte I thee beseche,",
  "Un-to thy-self that al this thou foryive;",
  "And rys up now with-oute more speche,",
  "And lat us caste how forth may best be drive",
  "This tyme, and eek how freshly we may live",
  "Whan that she cometh, the which shal be right sone;",
  "God help me so, the beste is thus to done.",
  "",
  "`Rys, lat us speke of lusty lyf in Troye",
  "That we han lad, and forth the tyme dryve;",
  "And eek of tyme cominge us reioye,",
  "That bringen shal our blisse now so blyve;",
  "And langour of these twyes dayes fyve",
  "We shal ther-with so foryete or oppresse,",
  "That wel unnethe it doon shal us duresse.",
  "",
  "`This toun is ful of lordes al aboute,",
  "And trewes lasten al this mene whyle.",
  "Go we pleye us in som lusty route",
  "To Sarpedon, not hennes but a myle.",
  "And thus thou shalt the tyme wel bigyle,",
  "And dryve it forth un-to that blisful morwe,",
  "That thou hir see, that cause is of thy sorwe.",
  "",
  "`Now rys, my dere brother Troilus;",
  "For certes, it noon honour is to thee",
  "To wepe, and in thy bedde to iouken thus.",
  "For trewely, of o thing trust to me,",
  "If thou thus ligge a day, or two, or three,",
  "The folk wol wene that thou, for cowardyse,",
  "Thee feynest syk, and that thou darst not ryse.'",
  "",
  "This Troilus answerde, `O brother dere,",
  "This knowen folk that han y-suffred peyne,",
  "That though he wepe and make sorwful chere,",
  "That feleth harm and smert in every veyne,",
  "No wonder is; and though I ever pleyne,",
  "Or alwey wepe, I am no-thing to blame,",
  "Sin I have lost the cause of al my game.",
  "",
  "`But sin of fyne force I moot aryse,",
  "I shal aryse as sone as ever I may;",
  "And god, to whom myn herte I sacrifyse,",
  "So sende us hastely the tenthe day!",
  "For was ther never fowl so fayn of May,",
  "As I shal been, whan that she cometh in Troye,",
  "That cause is of my torment and my Ioye.",
  "",
  "`But whider is thy reed,' quod Troilus,",
  "`That we may pleye us best in al this toun?'",
  "`Bi god, my conseil is,' quod Pandarus,",
  "`To ryde and pleye us with king Sarpedoun.'",
  "So longe of this they speken up and doun,",
  "Til Troilus gan at the laste assente",
  "To ryse, and forth to Sarpedoun they wente.",
  "",
  "This Sarpedoun, as he that honourable",
  "Was ever his lyve, and ful of heigh prowesse,",
  "With al that mighte y-served been on table,",
  "That deyntee was, al coste it greet richesse,",
  "He fedde hem day by day, that swich noblesse,",
  "As seyden bothe the moste and eek the leste,",
  "Was never er that day wist at any feste.",
  "",
  "Nor in this world ther is non instrument",
  "Delicious, through wind, or touche, of corde,",
  "As fer as any wight hath ever y-went,",
  "That tonge telle or herte may recorde,",
  "That at that feste it nas wel herd acorde;",
  "Ne of ladies eek so fayr a companye",
  "On daunce, er tho, was never y-seyn with ye.",
  "",
  "But what avayleth this to Troilus,",
  "That for his sorwe no-thing of it roughte?",
  "For ever in oon his herte pietous",
  "Ful bisily Criseyde his lady soughte.",
  "On hir was ever al that his herte thoughte,",
  "Now this, now that, so faste imagininge,",
  "That glade, y-wis, can him no festeyinge.",
  "",
  "These ladies eek that at this feste been,",
  "Sin that he saw his lady was a-weye,",
  "It was his sorwe upon hem for to seen,",
  "Or for to here on instrumentz so pleye.",
  "For she, that of his herte berth the keye,",
  "Was absent, lo, this was his fantasye,",
  "That no wight sholde make melodye.",
  "",
  "Nor ther nas houre in al the day or night,",
  "Whan he was ther-as no wight mighte him here,",
  "That he ne seyde, `O lufsom lady bright,",
  "How have ye faren, sin that ye were here?",
  "Wel-come, y-wis, myn owene lady dere.'",
  "But welaway, al this nas but a mase;",
  "Fortune his howve entended bet to glase.",
  "",
  "The lettres eek, that she of olde tyme",
  "Hadde him y-sent, he wolde allone rede,",
  "An hundred sythe, a-twixen noon and pryme;",
  "Refiguringe hir shap, hir womanhede,",
  "With-inne his herte, and every word and dede",
  "That passed was, and thus he droof to an ende",
  "The ferthe day, and seyde, he wolde wende.",
  "",
  "And seyde, `Leve brother Pandarus,",
  "Intendestow that we shal here bleve",
  "Til Sarpedoun wol forth congeyen us?",
  "Yet were it fairer that we toke our leve.",
  "For goddes love, lat us now sone at eve",
  "Our leve take, and homward lat us torne;",
  "For trewely, I nil not thus soiourne.'",
  "",
  "Pandare answerde, `Be we comen hider",
  "To fecchen fyr, and rennen hoom ayeyn?",
  "God helpe me so, I can not tellen whider",
  "We mighten goon, if I shal soothly seyn,",
  "Ther any wight is of us more fayn",
  "Than Sarpedoun; and if we hennes hye",
  "Thus sodeinly, I holde it vilanye.",
  "",
  "`Sin that we seyden that we wolde bleve",
  "With him a wouke; and now, thus sodeinly,",
  "The ferthe day to take of him oure leve,",
  "He wolde wondren on it, trewely!",
  "Lat us holde forth our purpos fermely;",
  "And sin that ye bihighten him to byde,",
  "Hold forward now, and after lat us ryde.'",
  "",
  "Thus Pandarus, with alle peyne and wo,",
  "Made him to dwelle; and at the woukes ende,",
  "Of Sarpedoun they toke hir leve tho,",
  "And on hir wey they spedden hem to wende.",
  "Quod Troilus, `Now god me grace sende,",
  "That I may finden, at myn hom-cominge,",
  "Criseyde comen!' And ther-with gan he singe.",
  "",
  "`Ye, hasel-wode!' thoughte this Pandare,",
  "And to him-self ful softely he seyde,",
  "`God woot, refreyden may this hote fare,",
  "Er Calkas sende Troilus Criseyde!'",
  "But natheles, he Iaped thus, and seyde,",
  "And swor, y-wis, his herte him wel bihighte,",
  "She wolde come as sone as ever she mighte.",
  "",
  "Whan they un-to the paleys were y-comen",
  "Of Troilus, they doun of hors alighte,",
  "And to the chambre hir wey than han they nomen.",
  "And in-to tyme that it gan to nighte,",
  "They spaken of Crysede the brighte.",
  "And after this, whan that hem bothe leste,",
  "They spedde hem fro the soper un-to reste.",
  "",
  "On morwe, as sone as day bigan to clere,",
  "This Troilus gan of his sleep tabrayde,",
  "And to Pandare, his owene brother dere,",
  "`For love of god,' ful pitously he seyde,",
  "`As go we seen the paleys of Criseyde;",
  "For sin we yet may have namore feste,",
  "So lat us seen hir paleys at the leste.'",
  "",
  "And ther-with-al, his meyne for to blende,",
  "A cause he fond in toune for to go,",
  "And to Criseydes hous they gonnen wende.",
  "But lord! This sely Troilus was wo!",
  "Him thoughte his sorweful herte braste a-two.",
  "For whan he saugh hir dores sperred alle,",
  "Wel neigh for sorwe a-doun he gan to falle.",
  "",
  "Therwith, whan he was war and gan biholde",
  "How shet was every windowe of the place,",
  "As frost, him thoughte, his herte gan to colde;",
  "For which with chaunged deedlich pale face,",
  "With-outen word, he forth bigan to pace;",
  "And, as god wolde, he gan so faste ryde,",
  "That no wight of his contenance aspyde.",
  "",
  "Than seyde he thus; `O paleys desolat,",
  "O hous, of houses whylom best y-hight,",
  "O paleys empty and disconsolat,",
  "O thou lanterne, of which queynt is the light,",
  "O paleys, whylom day, that now art night,",
  "Wel oughtestow to falle, and I to dye,",
  "Sin she is went that wont was us to gye!",
  "",
  "`O paleys, whylom croune of houses alle,",
  "Enlumined with sonne of alle blisse!",
  "O ring, fro which the ruby is out-falle,",
  "O cause of wo, that cause hast been of lisse!",
  "Yet, sin I may no bet, fayn wolde I kisse",
  "Thy colde dores, dorste I for this route;",
  "And fare-wel shryne, of which the seynt is oute!'",
  "",
  "Ther-with he caste on Pandarus his ye",
  "With chaunged face, and pitous to biholde;",
  "And whan he mighte his tyme aright aspye,",
  "Ay as he rood, to Pandarus he tolde",
  "His newe sorwe, and eek his Ioyes olde,",
  "So pitously and with so dede an hewe,",
  "That every wight mighte on his sorwe rewe.",
  "",
  "Fro thennesforth he rydeth up and doun,",
  "And every thing com him to remembraunce",
  "As he rood forbi places of the toun",
  "In whiche he whylom hadde al his plesaunce.",
  "`Lo, yond saugh I myn owene lady daunce;",
  "And in that temple, with hir eyen clere,",
  "Me coughte first my righte lady dere.",
  "",
  "`And yonder have I herd ful lustily",
  "My dere herte laugh, and yonder pleye",
  "Saugh I hir ones eek ful blisfully.",
  "And yonder ones to me gan she seye,",
  "\"Now goode swete, love me wel, I preye.\"",
  "And yond so goodly gan she me biholde,",
  "That to the deeth myn herte is to hir holde.",
  "",
  "`And at that corner, in the yonder hous,",
  "Herde I myn alderlevest lady dere",
  "So wommanly, with voys melodious,",
  "Singen so wel, so goodly, and so clere,",
  "That in my soule yet me thinketh I here",
  "The blisful soun; and, in that yonder place,",
  "My lady first me took un-to hir grace.'",
  "",
  "Thanne thoughte he thus, `O blisful lord Cupyde,",
  "Whanne I the proces have in my memorie,",
  "How thou me hast wereyed on every syde,",
  "Men might a book make of it, lyk a storie.",
  "What nede is thee to seke on me victorie,",
  "Sin I am thyn, and hoolly at thy wille?",
  "What Ioye hastow thyn owene folk to spille?",
  "",
  "`Wel hastow, lord, y-wroke on me thyn ire,",
  "Thou mighty god, and dredful for to greve!",
  "Now mercy, lord, thou wost wel I desire",
  "Thy grace most, of alle lustes leve,",
  "And live and deye I wol in thy bileve,",
  "For which I naxe in guerdon but a bone,",
  "That thou Criseyde ayein me sende sone.",
  "",
  "`Distreyne hir herte as faste to retorne",
  "As thou dost myn to longen hir to see;",
  "Than woot I wel, that she nil nought soiorne.",
  "Now, blisful lord, so cruel thou ne be",
  "Un-to the blood of Troye, I preye thee,",
  "As Iuno was un-to the blood Thebane,",
  "For which the folk of Thebes caughte hir bane.'",
  "",
  "And after this he to the yates wente",
  "Ther-as Criseyde out-rood a ful good paas,",
  "And up and doun ther made he many a wente,",
  "And to him-self ful ofte he seyde `Allas!",
  "From hennes rood my blisse and my solas!",
  "As wolde blisful god now, for his Ioye,",
  "I mighte hir seen ayein come in-to Troye!",
  "",
  "`And to the yonder hille I gan hir gyde,",
  "Allas! And there I took of hir my leve!",
  "And yond I saugh hir to hir fader ryde,",
  "For sorwe of which myn herte shal to-cleve.",
  "And hider hoom I com whan it was eve;",
  "And here I dwelle out-cast from alle Ioye,",
  "And shal, til I may seen hir eft in Troye.'",
  "",
  "And of him-self imagened he ofte",
  "To ben defet, and pale, and waxen lesse",
  "Than he was wont, and that men seyden softe,",
  "`What may it be? Who can the sothe gesse",
  "Why Troilus hath al this hevinesse?'",
  "And al this nas but his malencolye,",
  "That he hadde of him-self swich fantasye.",
  "",
  "Another tyme imaginen he wolde",
  "That every wight that wente by the weye",
  "Had of him routhe, and that they seyen sholde,",
  "`I am right sory Troilus wole deye.'",
  "And thus he droof a day yet forth or tweye.",
  "As ye have herd, swich lyf right gan he lede,",
  "As he that stood bitwixen hope and drede.",
  "",
  "For which him lyked in his songes shewe",
  "Thencheson of his wo, as he best mighte,",
  "And made a song of wordes but a fewe,",
  "Somwhat his woful herte for to lighte.",
  "And whan he was from every mannes sighte,",
  "With softe voys he, of his lady dere,",
  "That was absent, gan singe as ye may here.",
  "",
  "`O sterre, of which I lost have al the light,",
  "With herte soor wel oughte I to bewayle,",
  "That ever derk in torment, night by night,",
  "Toward my deeth with wind in stere I sayle;",
  "For which the tenthe night if that I fayle",
  "The gyding of thy bemes brighte an houre,",
  "My ship and me Caribdis wole devoure.'",
  "",
  "This song whan he thus songen hadde, sone",
  "He fil ayein in-to his sykes olde;",
  "And every night, as was his wone to done,",
  "He stood the brighte mone to beholde,",
  "And al his sorwe he to the mone tolde;",
  "And seyde, `Y-wis, whan thou art horned newe,",
  "I shal be glad, if al the world be trewe!",
  "",
  "`I saugh thyn hornes olde eek by the morwe,",
  "Whan hennes rood my righte lady dere,",
  "That cause is of my torment and my sorwe;",
  "For whiche, O brighte Lucina the clere,",
  "For love of god, ren faste aboute thy spere!",
  "For whan thyn hornes newe ginne springe,",
  "Than shal she come, that may my blisse bringe!'",
  "",
  "The day is more, and lenger every night,",
  "Than they be wont to be, him thoughte tho;",
  "And that the sonne wente his course unright",
  "By lenger wey than it was wont to go;",
  "And seyde, `Y-wis, me dredeth ever-mo,",
  "The sonnes sone, Pheton, be on-lyve,",
  "And that his fadres cart amis he dryve.'",
  "",
  "Upon the walles faste eek wolde he walke,",
  "And on the Grekes ost he wolde see,",
  "And to him-self right thus he wolde talke,",
  "`Lo, yonder is myn owene lady free,",
  "Or elles yonder, ther tho tentes be!",
  "And thennes comth this eyr, that is so sote,",
  "That in my soule I fele it doth me bote.",
  "",
  "`And hardely this wind, that more and more",
  "Thus stoundemele encreseth in my face,",
  "Is of my ladyes depe sykes sore.",
  "I preve it thus, for in non othere place",
  "Of al this toun, save onliche in this space,",
  "Fele I no wind that souneth so lyk peyne;",
  "It seyth, \"Allas! Why twinned be we tweyne?\"'",
  "",
  "This longe tyme he dryveth forth right thus,",
  "Til fully passed was the nynthe night;",
  "And ay bi-syde him was this Pandarus,",
  "That bisily dide alle his fulle might",
  "Him to comforte, and make his herte light;",
  "Yevinge him hope alwey, the tenthe morwe",
  "That she shal come, and stinten al his sorwe.",
  "",
  "Up-on that other syde eek was Criseyde,",
  "With wommen fewe, among the Grekes stronge;",
  "For which ful ofte a day `Allas,' she seyde,",
  "`That I was born! Wel may myn herte longe",
  "After my deeth; for now live I to longe!",
  "Allas! And I ne may it not amende;",
  "For now is wors than ever yet I wende.",
  "",
  "`My fader nil for no-thing do me grace",
  "To goon ayein, for nought I can him queme;",
  "And if so be that I my terme passe,",
  "My Troilus shal in his herte deme",
  "That I am fals, and so it may wel seme.",
  "Thus shal I have unthank on every syde;",
  "That I was born, so weylaway the tyde!",
  "",
  "`And if that I me putte in Iupartye,",
  "To stele awey by nighte, and it bifalle",
  "That I be caught, I shal be holde a spye;",
  "Or elles, lo, this drede I most of alle,",
  "If in the hondes of som wrecche I falle,",
  "I am but lost, al be myn herte trewe;",
  "Now mighty god, thou on my sorwe rewe!'",
  "",
  "Ful pale y-waxen was hir brighte face,",
  "Hir limes lene, as she that al the day",
  "Stood whan she dorste, and loked on the place",
  "Ther she was born, and ther she dwelt hadde ay.",
  "And al the night wepinge, allas! she lay.",
  "And thus despeired, out of alle cure,",
  "She ladde hir lyf, this woful creature.",
  "",
  "Ful ofte a day she sighte eek for destresse,",
  "And in hir-self she wente ay portrayinge",
  "Of Troilus the grete worthinesse,",
  "And alle his goodly wordes recordinge",
  "Sin first that day hir love bigan to springe.",
  "And thus she sette hir woful herte a-fyre",
  "Through remembraunce of that she gan desyre.",
  "",
  "In al this world ther nis so cruel herte",
  "That hir hadde herd compleynen in hir sorwe,",
  "That nolde han wopen for hir peynes smerte,",
  "So tendrely she weep, bothe eve and morwe.",
  "Hir nedede no teres for to borwe.",
  "And this was yet the worste of al hir peyne,",
  "Ther was no wight to whom she dorste hir pleyne.",
  "",
  "Ful rewfully she loked up-on Troye,",
  "Biheld the toures heighe and eek the halles;",
  "`Allas!' quod she, `The plesaunce and the Ioye",
  "The whiche that now al torned in-to galle is,",
  "Have I had ofte with-inne yonder walles!",
  "O Troilus, what dostow now,' she seyde;",
  "`Lord! Whether yet thou thenke up-on Criseyde?",
  "",
  "`Allas! I ne hadde trowed on your lore,",
  "And went with yow, as ye me radde er this!",
  "Thanne hadde I now not syked half so sore.",
  "Who mighte han seyd, that I had doon a-mis",
  "To stele awey with swich on as he is?",
  "But al to late cometh the letuarie,",
  "Whan men the cors un-to the grave carie.",
  "",
  "`To late is now to speke of this matere;",
  "Prudence, allas! Oon of thyn eyen three",
  "Me lakked alwey, er that I come here;",
  "On tyme y-passed, wel remembred me;",
  "And present tyme eek coude I wel y-see.",
  "But futur tyme, er I was in the snare,",
  "Coude I not seen; that causeth now my care.",
  "",
  "`But natheles, bityde what bityde,",
  "I shal to-morwe at night, by est or weste,",
  "Out of this ost stele on som maner syde,",
  "And go with Troilus wher-as him leste.",
  "This purpos wol I holde, and this is beste.",
  "No fors of wikked tonges Ianglerye,",
  "For ever on love han wrecches had envye.",
  "",
  "`For who-so wole of every word take hede,",
  "Or rewlen him by every wightes wit,",
  "Ne shal he never thryven, out of drede.",
  "For that that som men blamen ever yit,",
  "Lo, other maner folk commenden it.",
  "And as for me, for al swich variaunce,",
  "Felicitee clepe I my suffisaunce.",
  "",
  "`For which, with-outen any wordes mo,",
  "To Troye I wol, as for conclusioun.'",
  "But god it wot, er fully monthes two,",
  "She was ful fer fro that entencioun.",
  "For bothe Troilus and Troye toun",
  "Shal knotteles through-out hir herte slyde;",
  "For she wol take a purpos for tabyde.",
  "",
  "This Diomede, of whom yow telle I gan,",
  "Goth now, with-inne him-self ay arguinge",
  "With al the sleighte and al that ever he can,",
  "How he may best, with shortest taryinge,",
  "In-to his net Criseydes herte bringe.",
  "To this entente he coude never fyne;",
  "To fisshen hir, he leyde out hook and lyne.",
  "",
  "But natheles, wel in his herte he thoughte,",
  "That she nas nat with-oute a love in Troye,",
  "For never, sithen he hir thennes broughte,",
  "Ne coude he seen her laughe or make Ioye.",
  "He nist how best hir herte for tacoye.",
  "`But for to assaye,' he seyde, `it nought ne greveth;",
  "For he that nought nassayeth, nought nacheveth.'",
  "",
  "Yet seide he to him-self upon a night,",
  "`Now am I not a fool, that woot wel how",
  "Hir wo for love is of another wight,",
  "And here-up-on to goon assaye hir now?",
  "I may wel wite, it nil not been my prow.",
  "For wyse folk in bokes it expresse,",
  "\"Men shal not wowe a wight in hevinesse.\"",
  "",
  "`But who-so mighte winnen swich a flour",
  "From him, for whom she morneth night and day,",
  "He mighte seyn, he were a conquerour.'",
  "And right anoon, as he that bold was ay,",
  "Thoughte in his herte, `Happe how happe may,",
  "Al sholde I deye, I wole hir herte seche;",
  "I shal no more lesen but my speche.'",
  "",
  "This Diomede, as bokes us declare,",
  "Was in his nedes prest and corageous;",
  "With sterne voys and mighty limes square,",
  "Hardy, testif, strong, and chevalrous",
  "Of dedes, lyk his fader Tideus.",
  "And som men seyn, he was of tunge large;",
  "And heir he was of Calidoine and Arge.",
  "",
  "Criseyde mene was of hir stature,",
  "Ther-to of shap, of face, and eek of chere,",
  "Ther mighte been no fairer creature.",
  "And ofte tyme this was hir manere,",
  "To gon y-tressed with hir heres clere",
  "Doun by hir coler at hir bak bihinde,",
  "Which with a threde of gold she wolde binde.",
  "",
  "And, save hir browes ioyneden y-fere,",
  "Ther nas no lak, in ought I can espyen;",
  "But for to speken of hir eyen clere,",
  "Lo, trewely, they writen that hir syen,",
  "That Paradys stood formed in hir yen.",
  "And with hir riche beautee ever-more",
  "Strof love in hir, ay which of hem was more.",
  "",
  "She sobre was, eek simple, and wys with-al,",
  "The beste y-norisshed eek that mighte be,",
  "And goodly of hir speche in general,",
  "Charitable, estatliche, lusty, and free;",
  "Ne never-mo ne lakkede hir pitee;",
  "Tendre-herted, slydinge of corage;",
  "But trewely, I can not telle hir age.",
  "",
  "And Troilus wel waxen was in highte,",
  "And complet formed by proporcioun",
  "So wel, that kinde it not amenden mighte;",
  "Yong, fresshe, strong, and hardy as lyoun;",
  "Trewe as steel in ech condicioun;",
  "On of the beste enteched creature,",
  "That is, or shal, whyl that the world may dure.",
  "",
  "And certainly in storie it is y-founde,",
  "That Troilus was never un-to no wight,",
  "As in his tyme, in no degree secounde",
  "In durring don that longeth to a knight.",
  "Al mighte a geaunt passen him of might,",
  "His herte ay with the firste and with the beste",
  "Stood paregal, to durre don that him leste.",
  "",
  "But for to tellen forth of Diomede: --",
  "It fil that after, on the tenthe day,",
  "Sin that Criseyde out of the citee yede,",
  "This Diomede, as fresshe as braunche in May,",
  "Com to the tente ther-as Calkas lay,",
  "And feyned him with Calkas han to done;",
  "But what he mente, I shal yow telle sone.",
  "",
  "Criseyde, at shorte wordes for to telle,",
  "Welcomed him, and doun by hir him sette;",
  "And he was ethe y-nough to maken dwelle.",
  "And after this, with-outen longe lette,",
  "The spyces and the wyn men forth hem fette;",
  "And forth they speke of this and that y-fere,",
  "As freendes doon, of which som shal ye here.",
  "",
  "He gan first fallen of the werre in speche",
  "Bitwixe hem and the folk of Troye toun;",
  "And of thassege he gan hir eek byseche,",
  "To telle him what was hir opinioun.",
  "Fro that demaunde he so descendeth doun",
  "To asken hir, if that hir straunge thoughte",
  "The Grekes gyse, and werkes that they wroughte?",
  "",
  "And why hir fader tarieth so longe",
  "To wedden hir un-to som worthy wight?",
  "Criseyde, that was in hir peynes stronge",
  "For love of Troilus, hir owene knight,",
  "As fer-forth as she conning hadde or might,",
  "Answerde him tho; but, as of his entente,",
  "It semed not she wiste what he mente.",
  "",
  "But natheles, this ilke Diomede",
  "Gan in him-self assure, and thus he seyde,",
  "`If ich aright have taken of yow hede,",
  "Me thinketh thus, O lady myn, Criseyde,",
  "That sin I first hond on your brydel leyde,",
  "Whan ye out come of Troye by the morwe,",
  "Ne coude I never seen yow but in sorwe.",
  "",
  "`Can I not seyn what may the cause be",
  "But-if for love of som Troyan it were,",
  "The which right sore wolde athinken me",
  "That ye, for any wight that dwelleth there,",
  "Sholden spille a quarter of a tere,",
  "Or pitously your-selven so bigyle;",
  "For dredelees, it is nought worth the whyle.",
  "",
  "`The folk of Troye, as who seyth, alle and some",
  "In preson been, as ye your-selven see;",
  "Nor thennes shal not oon on-lyve come",
  "For al the gold bitwixen sonne and see.",
  "Trusteth wel, and understondeth me.",
  "Ther shal not oon to mercy goon on-lyve,",
  "Al were he lord of worldes twyes fyve!",
  "",
  "`Swich wreche on hem, for fecching of Eleyne,",
  "Ther shal be take, er that we hennes wende,",
  "That Manes, which that goddes ben of peyne,",
  "Shal been agast that Grekes wol hem shende.",
  "And men shul drede, un-to the worldes ende,",
  "From hennes-forth to ravisshe any quene,",
  "So cruel shal our wreche on hem be sene.",
  "",
  "`And but-if Calkas lede us with ambages,",
  "That is to seyn, with double wordes slye,",
  "Swich as men clepe a \"word with two visages,\"",
  "Ye shal wel knowen that I nought ne lye,",
  "And al this thing right seen it with your ye,",
  "And that anoon; ye nil not trowe how sone;",
  "Now taketh heed, for it is for to done.",
  "",
  "`What wene ye your wyse fader wolde",
  "Han yeven Antenor for yow anoon,",
  "If he ne wiste that the citee sholde",
  "Destroyed been? Why, nay, so mote I goon!",
  "He knew ful wel ther shal not scapen oon",
  "That Troyan is; and for the grete fere,",
  "He dorste not, ye dwelte lenger there.",
  "",
  "`What wole ye more, lufsom lady dere?",
  "Lat Troye and Troyan fro your herte pace!",
  "Dryf out that bittre hope, and make good chere,",
  "And clepe ayein the beautee of your face,",
  "That ye with salte teres so deface.",
  "For Troye is brought in swich a Iupartye,",
  "That, it to save, is now no remedye.",
  "",
  "`And thenketh wel, ye shal in Grekes finde,",
  "A more parfit love, er it be night,",
  "Than any Troian is, and more kinde,",
  "And bet to serven yow wol doon his might.",
  "And if ye vouche sauf, my lady bright,",
  "I wol ben he to serven yow my-selve,",
  "Yee, lever than he lord of Greces twelve!'",
  "",
  "And with that word he gan to waxen reed,",
  "And in his speche a litel wight he quook,",
  "And caste a-syde a litel wight his heed,",
  "And stinte a whyle; and afterward awook,",
  "And sobreliche on hir he threw his look,",
  "And seyde, `I am, al be it yow no Ioye,",
  "As gentil man as any wight in Troye.",
  "",
  "`For if my fader Tydeus,' he seyde,",
  "`Y-lived hadde, I hadde been, er this,",
  "Of Calidoine and Arge a king, Criseyde!",
  "And so hope I that I shal yet, y-wis.",
  "But he was slayn, allas! The more harm is,",
  "Unhappily at Thebes al to rathe,",
  "Polymites and many a man to scathe.",
  "",
  "`But herte myn, sin that I am your man,",
  "And been the ferste of whom I seche grace,",
  "To serven you as hertely as I can,",
  "And ever shal, whyl I to live have space,",
  "So, er that I departe out of this place,",
  "Ye wol me graunte, that I may to-morwe,",
  "At bettre leyser, telle yow my sorwe.'",
  "",
  "What shold I telle his wordes that he seyde?",
  "He spak y-now, for o day at the meste;",
  "It preveth wel, he spak so that Criseyde",
  "Graunted, on the morwe, at his requeste,",
  "For to speken with him at the leste,",
  "So that he nolde speke of swich matere;",
  "And thus to him she seyde, as ye may here:",
  "",
  "As she that hadde hir herte on Troilus",
  "So faste, that ther may it noon arace;",
  "And straungely she spak, and seyde thus;",
  "`O Diomede, I love that ilke place",
  "Ther I was born; and Ioves, for his grace,",
  "Delivere it sone of al that doth it care!",
  "God, for thy might, so leve it wel to fare!",
  "",
  "`That Grekes wolde hir wraththe on Troye wreke,",
  "If that they mighte, I knowe it wel, y-wis.",
  "But it shal not bifallen as ye speke;",
  "And god to-forn, and ferther over this,",
  "I wot my fader wys and redy is;",
  "And that he me hath bought, as ye me tolde,",
  "So dere, I am the more un-to him holde.",
  "",
  "`That Grekes been of heigh condicioun,",
  "I woot eek wel; but certein, men shal finde",
  "As worthy folk with-inne Troye toun,",
  "As conning, and as parfit and as kinde,",
  "As been bitwixen Orcades and Inde.",
  "And that ye coude wel your lady serve,",
  "I trowe eek wel, hir thank for to deserve.",
  "",
  "`But as to speke of love, y-wis,' she seyde,",
  "`I hadde a lord, to whom I wedded was,",
  "The whos myn herte al was, til that he deyde;",
  "And other love, as helpe me now Pallas,",
  "Ther in myn herte nis, ne nevere was.",
  "And that ye been of noble and heigh kinrede,",
  "I have wel herd it tellen, out of drede.",
  "",
  "`And that doth me to han so gret a wonder,",
  "That ye wol scornen any womman so.",
  "Eek, god wot, love and I be fer a-sonder!",
  "I am disposed bet, so mote I go,",
  "Un-to my deeth, to pleyne and maken wo.",
  "What I shal after doon, I can not seye;",
  "But trewely, as yet me list not pleye.",
  "",
  "`Myn herte is now in tribulacioun,",
  "And ye in armes bisy, day by day.",
  "Here-after, whan ye wonnen han the toun,",
  "Paraunter, thanne so it happen may,",
  "That whan I see that I never er say,",
  "Than wole I werke that I never wroughte!",
  "This word to yow y-nough suffysen oughte.",
  "",
  "`To-morwe eek wol I speken with yow fayn,",
  "So that ye touchen nought of this matere.",
  "And whan yow list, ye may come here ayeyn;",
  "And, er ye gon, thus muche I seye yow here;",
  "As help me Pallas with hir heres clere,",
  "If that I sholde of any Greek han routhe,",
  "It sholde be your-selven, by my trouthe!",
  "",
  "`I sey not therfore that I wol yow love,",
  "Ne I sey not nay, but in conclusioun,",
  "I mene wel, by god that sit above:' --",
  "And ther-with-al she caste hir eyen doun,",
  "And gan to syke, and seyde, `O Troye toun,",
  "Yet bidde I god, in quiete and in reste",
  "I may yow seen, or do myn herte breste.'",
  "",
  "But in effect, and shortly for to seye,",
  "This Diomede al freshly newe ayeyn",
  "Gan pressen on, and faste hir mercy preye;",
  "And after this, the sothe for to seyn,",
  "Hir glove he took, of which he was ful fayn.",
  "And fynally, whan it was waxen eve,",
  "And al was wel, he roos and took his leve.",
  "",
  "The brighte Venus folwede and ay taughte",
  "The wey, ther brode Phebus doun alighte;",
  "And Cynthea hir char-hors over-raughte",
  "To whirle out of the Lyon, if she mighte;",
  "And Signifer his candelse shewed brighte,",
  "Whan that Criseyde un-to hir bedde wente",
  "In-with hir fadres faire brighte tente.",
  "",
  "Retorning in hir soule ay up and doun",
  "The wordes of this sodein Diomede,",
  "His greet estat, and peril of the toun,",
  "And that she was allone and hadde nede",
  "Of freendes help; and thus bigan to brede",
  "The cause why, the sothe for to telle,",
  "That she tok fully purpos for to dwelle.",
  "",
  "The morwe com, and goostly for to speke,",
  "This Diomede is come un-to Criseyde,",
  "And shortly, lest that ye my tale breke,",
  "So wel he for him-selve spak and seyde,",
  "That alle hir sykes sore adoun he leyde.",
  "And fynally, the sothe for to seyne,",
  "He refte hir of the grete of al hir peyne.",
  "",
  "And after this the story telleth us,",
  "That she him yaf the faire baye stede,",
  "The which he ones wan of Troilus;",
  "And eek a broche (and that was litel nede)",
  "That Troilus was, she yaf this Diomede.",
  "And eek, the bet from sorwe him to releve,",
  "She made him were a pencel of hir sleve.",
  "",
  "I finde eek in stories elles-where,",
  "Whan through the body hurt was Diomede",
  "Of Troilus, tho weep she many a tere,",
  "Whan that she saugh his wyde woundes blede;",
  "And that she took to kepen him good hede,",
  "And for to hele him of his sorwes smerte.",
  "Men seyn, I not, that she yaf him hir herte.",
  "",
  "But trewely, the story telleth us,",
  "Ther made never womman more wo",
  "Than she, whan that she falsed Troilus.",
  "She seyde, `Allas! For now is clene a-go",
  "My name of trouthe in love, for ever-mo!",
  "For I have falsed oon, the gentileste",
  "That ever was, and oon the worthieste!",
  "",
  "`Allas, of me, un-to the worldes ende,",
  "Shal neither been y-writen nor y-songe",
  "No good word, for thise bokes wol me shende.",
  "O, rolled shal I been on many a tonge;",
  "Through-out the world my belle shal be ronge;",
  "And wommen most wol hate me of alle.",
  "Allas, that swich a cas me sholde falle!",
  "",
  "`They wol seyn, in as muche as in me is,",
  "I have hem don dishonour, weylawey!",
  "Al be I not the first that dide amis,",
  "What helpeth that to do my blame awey?",
  "But sin I see there is no bettre way,",
  "And that to late is now for me to rewe,",
  "To Diomede algate I wol be trewe.",
  "",
  "`But Troilus, sin I no better may,",
  "And sin that thus departen ye and I,",
  "Yet preye I god, so yeve yow right good day",
  "As for the gentileste, trewely,",
  "That ever I say, to serven feithfully,",
  "And best can ay his lady honour kepe:' --",
  "And with that word she brast anon to wepe.",
  "",
  "`And certes yow ne haten shal I never,",
  "And freendes love, that shal ye han of me,",
  "And my good word, al mighte I liven ever.",
  "And, trewely, I wolde sory be",
  "For to seen yow in adversitee.",
  "And giltelees, I woot wel, I yow leve;",
  "But al shal passe; and thus take I my leve.'",
  "",
  "But trewely, how longe it was bitwene,",
  "That she for-sook him for this Diomede,",
  "Ther is non auctor telleth it, I wene.",
  "Take every man now to his bokes hede;",
  "He shal no terme finden, out of drede.",
  "For though that he bigan to wowe hir sone,",
  "Er he hir wan, yet was ther more to done.",
  "",
  "Ne me ne list this sely womman chyde",
  "Ferther than the story wol devyse.",
  "Hir name, allas! Is publisshed so wyde,",
  "That for hir gilt it oughte y-noe suffyse.",
  "And if I mighte excuse hir any wyse,",
  "For she so sory was for hir untrouthe,",
  "Y-wis, I wolde excuse hir yet for routhe.",
  "",
  "This Troilus, as I biforn have told,",
  "Thus dryveth forth, as wel as he hath might.",
  "But often was his herte hoot and cold,",
  "And namely, that ilke nynthe night,",
  "Which on the morwe she hadde him byhight",
  "To come ayein: god wot, ful litel reste",
  "Hadde he that night; no-thing to slepe him leste.",
  "",
  "The laurer-crouned Phebus, with his hete,",
  "Gan, in his course ay upward as he wente,",
  "To warmen of the est see the wawes wete,",
  "And Nisus doughter song with fresh entente,",
  "Whan Troilus his Pandare after sente;",
  "And on the walles of the toun they pleyde,",
  "To loke if they can seen ought of Criseyde.",
  "",
  "Til it was noon, they stoden for to see",
  "Who that ther come; and every maner wight,",
  "That cam fro fer, they seyden it was she,",
  "Til that they coude knowen him a-right.",
  "Now was his herte dul, now was it light;",
  "And thus by-iaped stonden for to stare",
  "Aboute nought, this Troilus and Pandare.",
  "",
  "To Pandarus this Troilus tho seyde,",
  "`For ought I wot, bi-for noon, sikerly,",
  "In-to this toun ne comth nought here Criseyde.",
  "She hath y-now to done, hardily,",
  "To winnen from hir fader, so trowe I;",
  "Hir olde fader wol yet make hir dyne",
  "Er that she go; god yeve his herte pyne!'",
  "",
  "Pandare answerde, `It may wel be, certeyn;",
  "And for-thy lat us dyne, I thee biseche;",
  "And after noon than maystw thou come ayeyn.'",
  "And hoom they go, with-oute more speche;",
  "And comen ayein, but longe may they seche",
  "Er that they finde that they after cape;",
  "Fortune hem bothe thenketh for to Iape.",
  "",
  "Quod Troilus, `I see wel now, that she",
  "Is taried with hir olde fader so,",
  "That er she come, it wole neigh even be.",
  "Com forth, I wol un-to the yate go.",
  "Thise portours been unkonninge ever-mo;",
  "And I wol doon hem holden up the yate",
  "As nought ne were, al-though she come late.'",
  "",
  "The day goth faste, and after that comth eve,",
  "And yet com nought to Troilus Criseyde.",
  "He loketh forth by hegge, by tree, by greve,",
  "And fer his heed over the wal he leyde.",
  "And at the laste he torned him, and seyde.",
  "`By god, I woot hir mening now, Pandare!",
  "Al-most, y-wis, al newe was my care.",
  "",
  "`Now douteles, this lady can hir good;",
  "I woot, she meneth ryden prively.",
  "I comende hir wysdom, by myn hood!",
  "She wol not maken peple nycely",
  "Gaure on hir, whan she comth; but softely",
  "By nighte in-to the toun she thenketh ryde.",
  "And, dere brother, thenk not longe to abyde.",
  "",
  "`We han nought elles for to don, y-wis.",
  "And Pandarus, now woltow trowen me?",
  "Have here my trouthe, I see hir! Yond she is.",
  "Heve up thyn eyen, man! Maystow not see?'",
  "Pandare answerde, `Nay, so mote I thee!",
  "Al wrong, by god; what seystow, man, wher art?",
  "That I see yond nis but a fare-cart.'",
  "",
  "`Allas, thou seist right sooth,' quod Troilus;",
  "`But, hardely, it is not al for nought",
  "That in myn herte I now reioyse thus.",
  "It is ayein som good I have a thought.",
  "Noot I not how, but sin that I was wrought,",
  "Ne felte I swich a confort, dar I seye;",
  "She comth to-night, my lyf, that dorste I leye!'",
  "",
  "Pandare answerde, `It may be wel, y-nough';",
  "And held with him of al that ever he seyde;",
  "But in his herte he thoughte, and softe lough,",
  "And to him-self ful sobrely he seyde:",
  "`From hasel-wode, ther Ioly Robin pleyde,",
  "Shal come al that thou abydest here;",
  "Ye, fare-wel al the snow of ferne yere!'",
  "",
  "The wardein of the yates gan to calle",
  "The folk which that with-oute the yates were,",
  "And bad hem dryven in hir bestes alle,",
  "Or al the night they moste bleven there.",
  "And fer with-in the night, with many a tere,",
  "This Troilus gan hoomward for to ryde;",
  "For wel he seeth it helpeth nought tabyde.",
  "",
  "But natheles, he gladded him in this;",
  "He thoughte he misacounted hadde his day,",
  "And seyde, `I understonde have al a-mis.",
  "For thilke night I last Criseyde say,",
  "She seyde, \"I shal ben here, if that I may,",
  "Er that the mone, O dere herte swete!",
  "The Lyon passe, out of this Ariete.\"",
  "",
  "`For which she may yet holde al hir biheste.'",
  "And on the morwe un-to the yate he wente,",
  "And up and down, by west and eek by este,",
  "Up-on the walles made he many a wente.",
  "But al for nought; his hope alwey him blente;",
  "For which at night, in sorwe and sykes sore,",
  "He wente him hoom, with-outen any more.",
  "",
  "This hope al clene out of his herte fledde,",
  "He nath wher-on now lenger for to honge;",
  "But for the peyne him thoughte his herte bledde,",
  "So were his throwes sharpe and wonder stronge.",
  "For when he saugh that she abood so longe,",
  "He niste what he iuggen of it mighte,",
  "Sin she hath broken that she him bihighte.",
  "",
  "The thridde, ferthe, fifte, sixte day",
  "After tho dayes ten, of which I tolde,",
  "Bitwixen hope and drede his herte lay,",
  "Yet som-what trustinge on hir hestes olde.",
  "But whan he saugh she nolde hir terme holde,",
  "He can now seen non other remedye,",
  "But for to shape him sone for to dye.",
  "",
  "Ther-with the wikked spirit, god us blesse,",
  "Which that men clepeth wode Ialousye,",
  "Gan in him crepe, in al this hevinesse;",
  "For which, by-cause he wolde sone dye,",
  "He ne eet ne dronk, for his malencolye,",
  "And eek from every companye he fledde;",
  "This was the lyf that al the tyme he ledde.",
  "",
  "He so defet was, that no maner man",
  "Unneth mighte him knowe ther he wente;",
  "So was he lene, and ther-to pale and wan,",
  "And feble, that he walketh by potente;",
  "And with his ire he thus himselven shente.",
  "But who-so axed him wher-of him smerte,",
  "He seyde, his harm was al aboute his herte.",
  "",
  "Pryam ful ofte, and eek his moder dere,",
  "His bretheren and his sustren gonne him freyne",
  "Why he so sorwful was in al his chere,",
  "And what thing was the cause of al his peyne?",
  "But al for nought; he nolde his cause pleyne,",
  "But seyde, he felte a grevous maladye",
  "A-boute his herte, and fayn he wolde dye.",
  "",
  "So on a day he leyde him doun to slepe,",
  "And so bifel that in his sleep him thoughte,",
  "That in a forest faste he welk to wepe",
  "For love of hir that him these peynes wroughte;",
  "And up and doun as he the forest soughte,",
  "He mette he saugh a boor with tuskes grete,",
  "That sleep ayein the brighte sonnes hete.",
  "",
  "And by this boor, faste in his armes folde,",
  "Lay kissing ay his lady bright Criseyde:",
  "For sorwe of which, whan he it gan biholde,",
  "And for despyt, out of his slepe he breyde,",
  "And loude he cryde on Pandarus, and seyde,",
  "`O Pandarus, now knowe I crop and rote!",
  "I nam but deed; ther nis non other bote!",
  "",
  "`My lady bright Criseyde hath me bitrayed,",
  "In whom I trusted most of any wight,",
  "She elles-where hath now hir herte apayed;",
  "The blisful goddes, through hir grete might,",
  "Han in my dreem y-shewed it ful right.",
  "Thus in my dreem Criseyde I have biholde' --",
  "And al this thing to Pandarus he tolde.",
  "",
  "`O my Criseyde, allas! What subtiltee.",
  "What newe lust, what beautee, what science,",
  "What wratthe of iuste cause have ye to me?",
  "What gilt of me, what fel experience",
  "Hath fro me raft, allas! Thyn advertence?",
  "O trust, O feyth, O depe aseuraunce,",
  "Who hath me reft Criseyde, al my plesaunce?",
  "",
  "`Allas! Why leet I you from hennes go,",
  "For which wel neigh out of my wit I breyde?",
  "Who shal now trowe on any othes mo?",
  "God wot I wende, O lady bright, Criseyde,",
  "That every word was gospel that ye seyde!",
  "But who may bet bigylen, yf him liste,",
  "Than he on whom men weneth best to triste?",
  "",
  "`What shal I doon, my Pandarus, allas!",
  "I fele now so sharpe a newe peyne,",
  "Sin that ther is no remedie in this cas,",
  "That bet were it I with myn hondes tweyne",
  "My-selven slow, than alwey thus to pleyne.",
  "For through my deeth my wo sholde han an ende,",
  "Ther every day with lyf my-self I shende.'",
  "",
  "Pandare answerde and seyde, `Allas the whyle",
  "That I was born; have I not seyd er this,",
  "That dremes many a maner man bigyle?",
  "And why? For folk expounden hem a-mis.",
  "How darstow seyn that fals thy lady is,",
  "For any dreem, right for thyn owene drede?",
  "Lat be this thought, thou canst no dremes rede.",
  "",
  "`Paraunter, ther thou dremest of this boor,",
  "It may so be that it may signifye",
  "Hir fader, which that old is and eek hoor,",
  "Ayein the sonne lyth, on poynt to dye,",
  "And she for sorwe ginneth wepe and crye,",
  "And kisseth him, ther he lyth on the grounde;",
  "Thus shuldestow thy dreem a-right expounde.'",
  "",
  "`How mighte I thanne do?' quod Troilus,",
  "`To knowe of this, ye, were it never so lyte?'",
  "`Now seystow wysly,' quod this Pandarus,",
  "`My reed is this, sin thou canst wel endyte,",
  "That hastely a lettre thou hir wryte,",
  "Thorugh which thou shalt wel bringen it aboute,",
  "To knowe a sooth of that thou art in doute.",
  "",
  "`And see now why; for this I dar wel seyn,",
  "That if so is that she untrewe be,",
  "I can not trowe that she wol wryte ayeyn.",
  "And if she wryte, thou shalt ful sone see,",
  "As whether she hath any libertee",
  "To come ayein, or ellis in som clause,",
  "If she be let, she wol assigne a cause.",
  "",
  "`Thou hast not writen hir sin that she wente,",
  "Nor she to thee, and this I dorste leye,",
  "Ther may swich cause been in hir entente,",
  "That hardely thou wolt thy-selven seye,",
  "That hir a-bood the beste is for yow tweye.",
  "Now wryte hir thanne, and thou shalt fele sone",
  "A sothe of al; ther is no more to done.'",
  "",
  "Acorded been to this conclusioun,",
  "And that anoon, these ilke lordes two;",
  "And hastely sit Troilus adoun,",
  "And rolleth in his herte to and fro,",
  "How he may best discryven hir his wo.",
  "And to Criseyde, his owene lady dere,",
  "He wroot right thus, and seyde as ye may here.",
  "",
  "`Right fresshe flour, whos I have been and shal,",
  "With-outen part of elles-where servyse,",
  "With herte, body, lyf, lust, thought, and al;",
  "I, woful wight, in every humble wyse",
  "That tonge telle or herte may devyse,",
  "As ofte as matere occupyeth place,",
  "Me recomaunde un-to your noble grace.",
  "",
  "`Lyketh it yow to witen, swete herte,",
  "As ye wel knowe how longe tyme agoon",
  "That ye me lefte in aspre peynes smerte,",
  "Whan that ye wente, of which yet bote noon",
  "Have I non had, but ever wers bigoon",
  "Fro day to day am I, and so mot dwelle,",
  "While it yow list, of wele and wo my welle.",
  "",
  "`For which to yow, with dredful herte trewe,",
  "I wryte, as he that sorwe dryfth to wryte,",
  "My wo, that every houre encreseth newe,",
  "Compleyninge as I dar or can endyte.",
  "And that defaced is, that may ye wyte",
  "The teres, which that fro myn eyen reyne,",
  "That wolde speke, if that they coude, and pleyne.",
  "",
  "`Yow first biseche I, that your eyen clere",
  "To look on this defouled ye not holde;",
  "And over al this, that ye, my lady dere,",
  "Wol vouche-sauf this lettre to biholde.",
  "And by the cause eek of my cares colde,",
  "That sleeth my wit, if ought amis me asterte,",
  "For-yeve it me, myn owene swete herte.",
  "",
  "`If any servant dorste or oughte of right",
  "Up-on his lady pitously compleyne,",
  "Than wene I, that ich oughte be that wight,",
  "Considered this, that ye these monthes tweyne",
  "Han taried, ther ye seyden, sooth to seyne,",
  "But dayes ten ye nolde in ost soiourne,",
  "But in two monthes yet ye not retourne.",
  "",
  "`But for-as-muche as me mot nedes lyke",
  "Al that yow list, I dar not pleyne more,",
  "But humbely with sorwful sykes syke;",
  "Yow wryte ich myn unresty sorwes sore,",
  "Fro day to day desyring ever-more",
  "To knowen fully, if your wil it were,",
  "How ye han ferd and doon, whyl ye be there.",
  "",
  "`The whos wel-fare and hele eek god encresse",
  "In honour swich, that upward in degree",
  "It growe alwey, so that it never cesse;",
  "Right as your herte ay can, my lady free,",
  "Devyse, I prey to god so mote it be.",
  "And graunte it that ye sone up-on me rewe",
  "As wisly as in al I am yow trewe.",
  "",
  "`And if yow lyketh knowen of the fare",
  "Of me, whos wo ther may no wight discryve,",
  "I can no more but, cheste of every care,",
  "At wrytinge of this lettre I was on-lyve,",
  "Al redy out my woful gost to dryve;",
  "Which I delaye, and holde him yet in honde,",
  "Upon the sight of matere of your sonde.",
  "",
  "`Myn eyen two, in veyn with which I see,",
  "Of sorweful teres salte arn waxen welles;",
  "My song, in pleynte of myn adversitee;",
  "My good, in harm; myn ese eek waxen helle is.",
  "My Ioye, in wo; I can sey yow nought elles,",
  "But turned is, for which my lyf I warie,",
  "Everich Ioye or ese in his contrarie.",
  "",
  "`Which with your cominge hoom ayein to Troye",
  "Ye may redresse, and, more a thousand sythe",
  "Than ever ich hadde, encressen in me Ioye.",
  "For was ther never herte yet so blythe",
  "To han his lyf, as I shal been as swythe",
  "As I yow see; and, though no maner routhe",
  "Commeve yow, yet thinketh on your trouthe.",
  "",
  "`And if so be my gilt hath deeth deserved,",
  "Or if yow list no more up-on me see,",
  "In guerdon yet of that I have you served,",
  "Biseche I yow, myn hertes lady free,",
  "That here-upon ye wolden wryte me,",
  "For love of god, my righte lode-sterre,",
  "Ther deeth may make an ende of al my werre.",
  "",
  "`If other cause aught doth yow for to dwelle,",
  "That with your lettre ye me recomforte;",
  "For though to me your absence is an helle,",
  "With pacience I wol my wo comporte,",
  "And with your lettre of hope I wol desporte.",
  "Now wryteth, swete, and lat me thus not pleyne;",
  "With hope, or deeth, delivereth me fro peyne.",
  "",
  "`Y-wis, myn owene dere herte trewe,",
  "I woot that, whan ye next up-on me see,",
  "So lost have I myn hele and eek myn hewe,",
  "Criseyde shal nought conne knowe me!",
  "Y-wis, myn hertes day, my lady free,",
  "So thursteth ay myn herte to biholde",
  "Your beautee, that my lyf unnethe I holde.",
  "",
  "`I sey no more, al have I for to seye",
  "To you wel more than I telle may;",
  "But whether that ye do me live or deye,",
  "Yet pray I god, so yeve yow right good day.",
  "And fareth wel, goodly fayre fresshe may,",
  "As ye that lyf or deeth me may comaunde;",
  "And to your trouthe ay I me recomaunde",
  "",
  "`With hele swich that, but ye yeven me",
  "The same hele, I shal noon hele have.",
  "In you lyth, whan yow liste that it so be,",
  "The day in which me clothen shal my grave.",
  "In yow my lyf, in yow might for to save",
  "Me from disese of alle peynes smerte;",
  "And fare now wel, myn owene swete herte!",
  "Le vostre T.'",
  "",
  "This lettre forth was sent un-to Criseyde,",
  "Of which hir answere in effect was this;",
  "Ful pitously she wroot ayein, and seyde,",
  "That also sone as that she might, y-wis,",
  "She wolde come, and mende al that was mis.",
  "And fynally she wroot and seyde him thanne,",
  "She wolde come, ye, but she niste whenne.",
  "",
  "But in hir lettre made she swich festes,",
  "That wonder was, and swereth she loveth him best,",
  "Of which he fond but botmelees bihestes.",
  "But Troilus, thou mayst now, est or west,",
  "Pype in an ivy leef, if that thee lest;",
  "Thus gooth the world; god shilde us fro mischaunce,",
  "And every wight that meneth trouthe avaunce!",
  "",
  "Encresen gan the wo fro day to night",
  "Of Troilus, for taryinge of Criseyde;",
  "And lessen gan his hope and eek his might,",
  "For which al doun he in his bed him leyde;",
  "He ne eet, ne dronk, ne sleep, ne word he seyde,",
  "Imagininge ay that she was unkinde;",
  "For which wel neigh he wex out of his minde.",
  "",
  "This dreem, of which I told have eek biforn,",
  "May never come out of his remembraunce;",
  "He thoughte ay wel he hadde his lady lorn,",
  "And that Ioves, of his purveyaunce,",
  "Him shewed hadde in sleep the signifiaunce",
  "Of hir untrouthe and his disaventure,",
  "And that the boor was shewed him in figure.",
  "",
  "For which he for Sibille his suster sente,",
  "That called was Cassandre eek al aboute;",
  "And al his dreem he tolde hir er he stente,",
  "And hir bisoughte assoilen him the doute",
  "Of the stronge boor, with tuskes stoute;",
  "And fynally, with-inne a litel stounde,",
  "Cassandre him gan right thus his dreem expounde.",
  "",
  "She gan first smyle, and seyde, `O brother dere,",
  "If thou a sooth of this desyrest knowe,",
  "Thou most a fewe of olde stories here,",
  "To purpos, how that fortune over-throwe",
  "Hath lordes olde; through which, with-inne a throwe,",
  "Thou wel this boor shalt knowe, and of what kinde",
  "He comen is, as men in bokes finde.",
  "",
  "`Diane, which that wrooth was and in ire",
  "For Grekes nolde doon hir sacrifyse,",
  "Ne encens up-on hir auter sette a-fyre,",
  "She, for that Grekes gonne hir so dispyse,",
  "Wrak hir in a wonder cruel wyse.",
  "For with a boor as greet as oxe in stalle",
  "She made up frete hir corn and vynes alle.",
  "",
  "`To slee this boor was al the contree reysed,",
  "A-monges which ther com, this boor to see,",
  "A mayde, oon of this world the best y-preysed;",
  "And Meleagre, lord of that contree,",
  "He lovede so this fresshe mayden free",
  "That with his manhod, er he wolde stente,",
  "This boor he slow, and hir the heed he sente;",
  "",
  "`Of which, as olde bokes tellen us,",
  "Ther roos a contek and a greet envye;",
  "And of this lord descended Tydeus",
  "By ligne, or elles olde bokes lye;",
  "But how this Meleagre gan to dye",
  "Thorugh his moder, wol I yow not telle,",
  "For al to long it were for to dwelle.'",
  "",
  "[Argument of the 12 Books of Statius' \"Thebais\"]",
  "",
  "Associat profugum Tideo primus Polimitem;",
  "Tidea legatum docet insidiasque secundus;",
  "Tercius Hemoniden canit et vates latitantes;",
  "Quartus habet reges ineuntes prelia septem;",
  "Mox furie Lenne quinto narratur et anguis;",
  "Archimori bustum sexto ludique leguntur;",
  "Dat Graios Thebes et vatem septimus vmbria;",
  "Octauo cecidit Tideus, spes, vita Pelasgia;",
  "Ypomedon nono moritur cum Parthonopeo;",
  "Fulmine percussus, decimo Capaneus superatur;",
  "Vndecimo sese perimunt per vulnera fratres;",
  "Argiuam flentem narrat duodenus et igneum.",
  "",
  "She tolde eek how Tydeus, er she stente,",
  "Un-to the stronge citee of Thebes,",
  "To cleyme kingdom of the citee, wente,",
  "For his felawe, daun Polymites,",
  "Of which the brother, daun Ethyocles,",
  "Ful wrongfully of Thebes held the strengthe;",
  "This tolde she by proces, al by lengthe.",
  "",
  "She tolde eek how Hemonides asterte,",
  "Whan Tydeus slough fifty knightes stoute.",
  "She tolde eek al the prophesyes by herte,",
  "And how that sevene kinges, with hir route,",
  "Bisegeden the citee al aboute;",
  "And of the holy serpent, and the welle,",
  "And of the furies, al she gan him telle.",
  "",
  "Of Archimoris buryinge and the pleyes,",
  "And how Amphiorax fil through the grounde,",
  "How Tydeus was slayn, lord of Argeyes,",
  "And how Ypomedoun in litel stounde",
  "Was dreynt, and deed Parthonope of wounde;",
  "And also how Cappaneus the proude",
  "With thonder-dint was slayn, that cryde loude.",
  "",
  "She gan eek telle him how that either brother,",
  "Ethyocles and Polimyte also,",
  "At a scarmyche, eche of hem slough other,",
  "And of Argyves wepinge and hir wo;",
  "And how the town was brent she tolde eek tho.",
  "And so descendeth doun from gestes olde",
  "To Diomede, and thus she spak and tolde.",
  "",
  "`This ilke boor bitokneth Diomede,",
  "Tydeus sone, that doun descended is",
  "Fro Meleagre, that made the boor to blede.",
  "And thy lady, wher-so she be, y-wis,",
  "This Diomede hir herte hath, and she his.",
  "Weep if thou wolt, or leef; for, out of doute,",
  "This Diomede is inne, and thou art oute.'",
  "",
  "`Thou seyst nat sooth,' quod he, `thou sorceresse,",
  "With al thy false goost of prophesye!",
  "Thou wenest been a greet devyneresse;",
  "Now seestow not this fool of fantasye",
  "Peyneth hir on ladyes for to lye?",
  "Awey!' quod he. `Ther Ioves yeve thee sorwe!",
  "Thou shalt be fals, paraunter, yet to-morwe!",
  "",
  "`As wel thou mightest lyen on Alceste,",
  "That was of creatures, but men lye,",
  "That ever weren, kindest and the beste.",
  "For whanne hir housbonde was in Iupartye",
  "To dye him-self, but-if she wolde dye,",
  "She chees for him to dye and go to helle,",
  "And starf anoon, as us the bokes telle.'",
  "",
  "Cassandre goth, and he with cruel herte",
  "For-yat his wo, for angre of hir speche;",
  "And from his bed al sodeinly he sterte,",
  "As though al hool him hadde y-mad a leche.",
  "And day by day he gan enquere and seche",
  "A sooth of this, with al his fulle cure;",
  "And thus he dryeth forth his aventure.",
  "",
  "Fortune, whiche that permutacioun",
  "Of thinges hath, as it is hir committed",
  "Through purveyaunce and disposicioun",
  "Of heighe Iove, as regnes shal ben flitted",
  "Fro folk in folk, or whan they shal ben smitted,",
  "Gan pulle awey the fetheres brighte of Troye",
  "Fro day to day, til they ben bare of Ioye.",
  "",
  "Among al this, the fyn of the parodie",
  "Of Ector gan approchen wonder blyve;",
  "The fate wolde his soule sholde unbodie,",
  "And shapen hadde a mene it out to dryve;",
  "Ayeins which fate him helpeth not to stryve;",
  "But on a day to fighten gan he wende,",
  "At which, allas! He coughte his lyves ende.",
  "",
  "For which me thinketh every maner wight",
  "That haunteth armes oughte to biwayle",
  "The deeth of him that was so noble a knight;",
  "For as he drough a king by thaventayle,",
  "Unwar of this, Achilles through the mayle",
  "And through the body gan him for to ryve;",
  "And thus this worthy knight was brought of lyve.",
  "",
  "For whom, as olde bokes tellen us,",
  "Was mad swich wo, that tonge it may not telle;",
  "And namely, the sorwe of Troilus,",
  "That next him was of worthinesse welle.",
  "And in this wo gan Troilus to dwelle,",
  "That, what for sorwe, and love, and for unreste,",
  "Ful ofte a day he bad his herte breste.",
  "",
  "But natheles, though he gan him dispeyre,",
  "And dradde ay that his lady was untrewe,",
  "Yet ay on hir his herte gan repeyre.",
  "And as these loveres doon, he soughte ay newe",
  "To gete ayein Criseyde, bright of hewe.",
  "And in his herte he wente hir excusinge,",
  "That Calkas causede al hir taryinge.",
  "",
  "And ofte tyme he was in purpos grete",
  "Him-selven lyk a pilgrim to disgyse,",
  "To seen hir; but he may not contrefete",
  "To been unknowen of folk that weren wyse,",
  "Ne finde excuse aright that may suffyse,",
  "If he among the Grekes knowen were;",
  "For which he weep ful ofte many a tere.",
  "",
  "To hir he wroot yet ofte tyme al newe",
  "Ful pitously, he lefte it nought for slouthe,",
  "Biseching hir that, sin that he was trewe,",
  "She wolde come ayein and holde hir trouthe.",
  "For which Criseyde up-on a day, for routhe,",
  "I take it so, touchinge al this matere,",
  "Wrot him ayein, and seyde as ye may here.",
  "",
  "`Cupydes sone, ensample of goodlihede,",
  "O swerd of knighthod, sours of gentilesse!",
  "How might a wight in torment and in drede",
  "And helelees, yow sende as yet gladnesse?",
  "I hertelees, I syke, I in distresse;",
  "Sin ye with me, nor I with yow may dele,",
  "Yow neither sende ich herte may nor hele.",
  "",
  "`Your lettres ful, the papir al y-pleynted,",
  "Conceyved hath myn hertes pietee;",
  "I have eek seyn with teres al depeynted",
  "Your lettre, and how that ye requeren me",
  "To come ayein, which yet ne may not be.",
  "But why, lest that this lettre founden were,",
  "No mencioun ne make I now, for fere.",
  "",
  "`Grevous to me, god woot, is your unreste,",
  "Your haste, and that, the goddes ordenaunce,",
  "It semeth not ye take it for the beste.",
  "Nor other thing nis in your remembraunce,",
  "As thinketh me, but only your plesaunce.",
  "But beth not wrooth, and that I yow biseche;",
  "For that I tarie, is al for wikked speche.",
  "",
  "`For I have herd wel more than I wende,",
  "Touchinge us two, how thinges han y-stonde;",
  "Which I shal with dissimulinge amende.",
  "And beth nought wrooth, I have eek understonde,",
  "How ye ne doon but holden me in honde.",
  "But now no fors, I can not in yow gesse",
  "But alle trouthe and alle gentilesse.",
  "",
  "`Comen I wol, but yet in swich disioynte",
  "I stonde as now, that what yeer or what day",
  "That this shal be, that can I not apoynte.",
  "But in effect, I prey yow, as I may,",
  "Of your good word and of your frendship ay.",
  "For trewely, whyl that my lyf may dure,",
  "As for a freend, ye may in me assure.",
  "",
  "`Yet preye I yow on yvel ye ne take,",
  "That it is short which that I to yow wryte;",
  "I dar not, ther I am, wel lettres make,",
  "Ne never yet ne coude I wel endyte.",
  "Eek greet effect men wryte in place lite.",
  "Thentente is al, and nought the lettres space;",
  "And fareth now wel, god have you in his grace!",
  "La vostre C.'",
  "",
  "This Troilus this lettre thoughte al straunge,",
  "Whan he it saugh, and sorwefully he sighte;",
  "Him thoughte it lyk a kalendes of chaunge;",
  "But fynally, he ful ne trowen mighte",
  "That she ne wolde him holden that she highte;",
  "For with ful yvel wil list him to leve",
  "That loveth wel, in swich cas, though him greve.",
  "",
  "But natheles, men seyn that, at the laste,",
  "For any thing, men shal the sothe see;",
  "And swich a cas bitidde, and that as faste,",
  "That Troilus wel understood that she",
  "Nas not so kinde as that hir oughte be.",
  "And fynally, he woot now, out of doute,",
  "That al is lost that he hath been aboute.",
  "",
  "Stood on a day in his malencolye",
  "This Troilus, and in suspecioun",
  "Of hir for whom he wende for to dye.",
  "And so bifel, that through-out Troye toun,",
  "As was the gyse, y-bore was up and doun",
  "A maner cote-armure, as seyth the storie,",
  "Biforn Deiphebe, in signe of his victorie,",
  "",
  "The whiche cote, as telleth Lollius,",
  "Deiphebe it hadde y-rent from Diomede",
  "The same day; and whan this Troilus",
  "It saugh, he gan to taken of it hede,",
  "Avysing of the lengthe and of the brede,",
  "And al the werk; but as he gan biholde,",
  "Ful sodeinly his herte gan to colde,",
  "",
  "As he that on the coler fond with-inne",
  "A broche, that he Criseyde yaf that morwe",
  "That she from Troye moste nedes twinne,",
  "In remembraunce of him and of his sorwe;",
  "And she him leyde ayein hir feyth to borwe",
  "To kepe it ay; but now, ful wel he wiste,",
  "His lady nas no lenger on to triste.",
  "",
  "He gooth him hoom, and gan ful sone sende",
  "For Pandarus; and al this newe chaunce,",
  "And of this broche, he tolde him word and ende,",
  "Compleyninge of hir hertes variaunce,",
  "His longe love, his trouthe, and his penaunce;",
  "And after deeth, with-outen wordes more,",
  "Ful faste he cryde, his reste him to restore.",
  "",
  "Than spak he thus, `O lady myn Criseyde,",
  "Wher is your feyth, and wher is your biheste?",
  "Wher is your love, wher is your trouthe,' he seyde;",
  "`Of Diomede have ye now al this feste!",
  "Allas, I wolde have trowed at the leste.",
  "That, sin ye nolde in trouthe to me stonde,",
  "That ye thus nolde han holden me in honde!",
  "",
  "`Who shal now trowe on any othes mo?",
  "Allas, I never wolde han wend, er this,",
  "That ye, Criseyde, coude han chaunged so;",
  "Ne, but I hadde a-gilt and doon amis,",
  "So cruel wende I not your herte, y-wis,",
  "To slee me thus; allas, your name of trouthe",
  "Is now for-doon, and that is al my routhe.",
  "",
  "`Was ther non other broche yow liste lete",
  "To feffe with your newe love,' quod he,",
  "`But thilke broche that I, with teres wete,",
  "Yow yaf, as for a remembraunce of me?",
  "Non other cause, allas, ne hadde ye",
  "But for despyt, and eek for that ye mente",
  "Al-outrely to shewen your entente!",
  "",
  "`Through which I see that clene out of your minde",
  "Ye han me cast, and I ne can nor may,",
  "For al this world, with-in myn herte finde",
  "To unloven yow a quarter of a day!",
  "In cursed tyme I born was, weylaway!",
  "That ye, that doon me al this wo endure,",
  "Yet love I best of any creature.",
  "",
  "`Now god,' quod he, `me sende yet the grace",
  "That I may meten with this Diomede!",
  "And trewely, if I have might and space,",
  "Yet shal I make, I hope, his sydes blede.",
  "O god,' quod he, `that oughtest taken hede",
  "To fortheren trouthe, and wronges to punyce,",
  "Why niltow doon a vengeaunce of this vyce?",
  "",
  "`O Pandare, that in dremes for to triste",
  "Me blamed hast, and wont art oft up-breyde,",
  "Now maystow see thy-selve, if that thee liste,",
  "How trewe is now thy nece, bright Criseyde!",
  "In sondry formes, god it woot,' he seyde,",
  "`The goddes shewen bothe Ioye and tene",
  "In slepe, and by my dreme it is now sene.",
  "",
  "`And certaynly, with-oute more speche,",
  "From hennes-forth, as ferforth as I may,",
  "Myn owene deeth in armes wol I seche;",
  "I recche not how sone be the day!",
  "But trewely, Criseyde, swete may,",
  "Whom I have ay with al my might y-served,",
  "That ye thus doon, I have it nought deserved.'",
  "",
  "This Pandarus, that alle these thinges herde,",
  "And wiste wel he seyde a sooth of this,",
  "He nought a word ayein to him answerde;",
  "For sory of his frendes sorwe he is,",
  "And shamed, for his nece hath doon a-mis;",
  "And stant, astoned of these causes tweye,",
  "As stille as stoon; a word ne coude he seye.",
  "",
  "But at the laste thus he spak, and seyde,",
  "`My brother dere, I may thee do no-more.",
  "What shulde I seyn? I hate, y-wis, Criseyde!",
  "And, god wot, I wol hate hir evermore!",
  "And that thou me bisoughtest doon of yore,",
  "Havinge un-to myn honour ne my reste",
  "Right no reward, I dide al that thee leste.",
  "",
  "`If I dide ought that mighte lyken thee,",
  "It is me leef; and of this treson now,",
  "God woot, that it a sorwe is un-to me!",
  "And dredelees, for hertes ese of yow,",
  "Right fayn wolde I amende it, wiste I how.",
  "And fro this world, almighty god I preye,",
  "Delivere hir sone; I can no-more seye.'",
  "",
  "Gret was the sorwe and pleynt of Troilus;",
  "But forth hir cours fortune ay gan to holde.",
  "Criseyde loveth the sone of Tydeus,",
  "And Troilus mot wepe in cares colde.",
  "Swich is this world; who-so it can biholde,",
  "In eche estat is litel hertes reste;",
  "God leve us for to take it for the beste!",
  "",
  "In many cruel batayle, out of drede,",
  "Of Troilus, this ilke noble knight,",
  "As men may in these olde bokes rede,",
  "Was sene his knighthod and his grete might.",
  "And dredelees, his ire, day and night,",
  "Ful cruelly the Grekes ay aboughte;",
  "And alwey most this Diomede he soughte.",
  "",
  "And ofte tyme, I finde that they mette",
  "With blody strokes and with wordes grete,",
  "Assayinge how hir speres weren whette;",
  "And god it woot, with many a cruel hete",
  "Gan Troilus upon his helm to bete.",
  "But natheles, fortune it nought ne wolde,",
  "Of others hond that either deyen sholde. --",
  "",
  "And if I hadde y-taken for to wryte",
  "The armes of this ilke worthy man,",
  "Than wolde I of his batailles endyte.",
  "But for that I to wryte first bigan",
  "Of his love, I have seyd as that I can.",
  "His worthy dedes, who-so list hem here,",
  "Reed Dares, he can telle hem alle y-fere.",
  "",
  "Bisechinge every lady bright of hewe,",
  "And every gentil womman, what she be,",
  "That al be that Criseyde was untrewe,",
  "That for that gilt she be not wrooth with me.",
  "Ye may hir gilt in othere bokes see;",
  "And gladlier I wole wryten, if yow leste,",
  "Penolopees trouthe and good Alceste.",
  "",
  "Ne I sey not this al-only for these men,",
  "But most for wommen that bitraysed be",
  "Through false folk; god yeve hem sorwe, amen!",
  "That with hir grete wit and subtiltee",
  "Bitrayse yow! And this commeveth me",
  "To speke, and in effect yow alle I preye,",
  "Beth war of men, and herkeneth what I seye! --",
  "",
  "Go, litel book, go litel myn tragedie,",
  "Ther god thy maker yet, er that he dye,",
  "So sende might to make in som comedie!",
  "But litel book, no making thou nenvye,",
  "But subgit be to alle poesye;",
  "And kis the steppes, wher-as thou seest pace",
  "Virgile, Ovyde, Omer, Lucan, and Stace.",
  "",
  "And for ther is so greet diversitee",
  "In English and in wryting of our tonge,",
  "So preye I god that noon miswryte thee,",
  "Ne thee mismetre for defaute of tonge.",
  "And red wher-so thou be, or elles songe,",
  "That thou be understonde I god beseche!",
  "But yet to purpos of my rather speche. --",
  "",
  "The wraththe, as I began yow for to seye,",
  "Of Troilus, the Grekes boughten dere;",
  "For thousandes his hondes maden deye,",
  "As he that was with-outen any pere,",
  "Save Ector, in his tyme, as I can here.",
  "But weylawey, save only goddes wille,",
  "Dispitously him slough the fiers Achille.",
  "",
  "And whan that he was slayn in this manere,",
  "His lighte goost ful blisfully is went",
  "Up to the holownesse of the seventh spere,",
  "In convers letinge every element;",
  "And ther he saugh, with ful avysement,",
  "The erratik sterres, herkeninge armonye",
  "With sownes fulle of hevenish melodye.",
  "",
  "And doun from thennes faste he gan avyse",
  "This litel spot of erthe, that with the see",
  "Embraced is, and fully gan despyse",
  "This wrecched world, and held al vanitee",
  "To respect of the pleyn felicitee",
  "That is in hevene above; and at the laste,",
  "Ther he was slayn, his loking doun he caste;",
  "",
  "And in him-self he lough right at the wo",
  "Of hem that wepten for his deeth so faste;",
  "And dampned al our werk that folweth so",
  "The blinde lust, the which that may not laste,",
  "And sholden al our herte on hevene caste.",
  "And forth he wente, shortly for to telle,",
  "Ther as Mercurie sorted him to dwelle. --",
  "",
  "Swich fyn hath, lo, this Troilus for love,",
  "Swich fyn hath al his grete worthinesse;",
  "Swich fyn hath his estat real above,",
  "Swich fyn his lust, swich fyn hath his noblesse;",
  "Swich fyn hath false worldes brotelnesse.",
  "And thus bigan his lovinge of Criseyde,",
  "As I have told, and in this wyse he deyde.",
  "",
  "O yonge fresshe folkes, he or she,",
  "In which that love up groweth with your age,",
  "Repeyreth hoom from worldly vanitee,",
  "And of your herte up-casteth the visage",
  "To thilke god that after his image",
  "Yow made, and thinketh al nis but a fayre",
  "This world, that passeth sone as floures fayre.",
  "",
  "And loveth him, the which that right for love",
  "Upon a cros, our soules for to beye,",
  "First starf, and roos, and sit in hevene a-bove;",
  "For he nil falsen no wight, dar I seye,",
  "That wol his herte al hoolly on him leye.",
  "And sin he best to love is, and most meke,",
  "What nedeth feyned loves for to seke?",
  "",
  "Lo here, of Payens corsed olde rytes,",
  "Lo here, what alle hir goddes may availle;",
  "Lo here, these wrecched worldes appetytes;",
  "Lo here, the fyn and guerdon for travaille",
  "Of Iove, Appollo, of Mars, of swich rascaille!",
  "Lo here, the forme of olde clerkes speche",
  "In poetrye, if ye hir bokes seche. --",
  "",
  "O moral Gower, this book I directe",
  "To thee, and to the philosophical Strode,",
  "To vouchen sauf, ther nede is, to corecte,",
  "Of your benignitees and zeles gode.",
  "And to that sothfast Crist, that starf on rode,",
  "With al myn herte of mercy ever I preye;",
  "And to the lord right thus I speke and seye:",
  "",
  "Thou oon, and two, and three, eterne on-lyve,",
  "That regnest ay in three and two and oon,",
  "Uncircumscript, and al mayst circumscryve,",
  "Us from visible and invisible foon",
  "Defende; and to thy mercy, everichoon,",
  "So make us, Iesus, for thy grace digne,",
  "For love of mayde and moder thyn benigne! Amen.",
  ""
]