module.exports = [
  "CHORUS OF ATHENIANS.",
  "",
  "STROPHE I.",
  "",
  "Ye shades, where sacred truth is sought;",
  "Groves, where immortal sages taught:",
  "    Where heavenly visions Plato fired,",
  "    And Epicurus' lay inspired;",
  "    In vain your guiltless laurels stood",
  "    Unspotted long with human blood.",
  "War, horrid war, your thoughtful walks invades,",
  "And steel now glitters in the Muses' shades.",
  "",
  "ANTISTROPHE I.",
  "",
  "    O heaven-born sisters! source of art!",
  "    Who charm the sense, or mend the heart;",
  "    Who lead fair Virtue's train along,",
  "    Moral truth, and mystic song!",
  "    To what new clime, what distant sky,",
  "    Forsaken, friendless, shall ye fly?",
  "Say, will ye bless the bleak Atlantic shore,",
  "Or bid the furious Gaul be rude no more?",
  "",
  "STROPHE II.",
  "",
  "    When Athens sinks by fates unjust,",
  "    When wild barbarians spurn her dust;",
  "    Perhaps even Britain's utmost shore",
  "    Shall cease to blush with strangers' gore,",
  "    See Arts her savage sons control,",
  "    And Athens rising near the pole!",
  "Till some new tyrant lifts his purple hand,",
  "And civil madness tears them from the land.",
  "",
  "ANTISTROPHE II.",
  "",
  "    Ye gods! what justice rules the ball?",
  "    Freedom and Arts together fall;",
  "    Fools grant whate'er Ambition craves,",
  "    And men, once ignorant, are slaves.",
  "    Oh, cursed effects of civil hate,",
  "    In every age, in every state!",
  "Still, when the lust of tyrant power succeeds,",
  "Some Athens perishes, some Tully bleeds.",
  "",
  "CHORUS OF YOUTHS AND VIRGINS.",
  "",
  "SEMICHORUS.",
  "",
  "O tyrant Love! hast thou possess'd",
  "The prudent, learn'd, and virtuous breast?",
  "Wisdom and wit in vain reclaim,",
  "And arts but soften us to feel thy flame.",
  "  Love, soft intruder, enters here,",
  "  But entering learns to be sincere.",
  "  Marcus with blushes owns he loves,",
  "  And Brutus tenderly reproves.",
  "    Why, Virtue, dost thou blame desire,",
  "      Which Nature has impress'd",
  "    Why, Nature, dost thou soonest fire",
  "      The mild and generous breast?",
  "",
  "CHORUS.",
  "",
  "  Love's purer flames the gods approve;",
  "  The gods and Brutus bend to love:",
  "  Brutus for absent Portia sighs,",
  "And sterner Cassius melts at Junia's eyes.",
  "What is loose love? a transient gust,",
  "Spent in a sudden storm of lust,",
  "A vapour fed from wild desire,",
  "A wandering, self-consuming fire.",
  "  But Hymen's kinder flames unite,",
  "    And burn for ever one;",
  "  Chaste as cold Cynthia's virgin light,",
  "    Productive as the sun.",
  "",
  "SEMICHORUS.",
  "",
  "  Oh source of every social tie,",
  "  United wish, and mutual joy!",
  "  What various joys on one attend,",
  "As son, as father, brother, husband, friend!",
  "  Whether his hoary sire he spies,",
  "  While thousand grateful thoughts arise;",
  "  Or meets his spouse's fonder eye;",
  "  Or views his smiling progeny;",
  "    What tender passions take their turns,",
  "      What home-felt raptures move?",
  "    His heart now melts, now leaps, now burns,",
  "      With reverence, hope, and love.",
  "",
  "CHORUS.",
  "",
  "Hence, guilty joys, distastes, surmises,",
  "Hence, false tears, deceits, disguises,",
  "Dangers, doubts, delays, surprises,",
  "  Fires that scorch, yet dare not shine!",
  "Purest love's unwasting treasure,",
  "Constant faith, fair hope, long leisure,",
  "Days of ease, and nights of pleasure;",
  "  Sacred Hymen! these are thine.",
  ""
]