module.exports = [
  "INFERNO 33, 22-75.",
  "",
  "Now had the loophole of that dungeon, still",
  "Which bears the name of Famine's Tower from me,",
  "And where 'tis fit that many another will",
  "",
  "Be doomed to linger in captivity,",
  "Shown through its narrow opening in my cell",
  "'Moon after moon slow waning', when a sleep,",
  "",
  "'That of the future burst the veil, in dream",
  "Visited me. It was a slumber deep",
  "And evil; for I saw, or I did seem'",
  "",
  "To see, 'that' tyrant Lord his revels keep",
  "The leader of the cruel hunt to them,",
  "Chasing the wolf and wolf-cubs up the steep",
  "",
  "Ascent, that from 'the Pisan is the screen'",
  "Of 'Lucca'; with him Gualandi came,",
  "Sismondi, and Lanfranchi, 'bloodhounds lean,",
  "",
  "Trained to the sport and eager for the game",
  "Wide ranging in his front;' but soon were seen",
  "Though by so short a course, with 'spirits tame,'",
  "",
  "The father and 'his whelps' to flag at once,",
  "And then the sharp fangs gored their bosoms deep.",
  "Ere morn I roused myself, and heard my sons,",
  "",
  "For they were with me, moaning in their sleep,",
  "And begging bread. Ah, for those darling ones!",
  "Right cruel art thou, if thou dost not weep",
  "",
  "In thinking of my soul's sad augury;",
  "And if thou weepest not now, weep never more!",
  "They were already waked, as wont drew nigh",
  "",
  "The allotted hour for food, and in that hour",
  "Each drew a presage from his dream. When I",
  "'Heard locked beneath me of that horrible tower",
  "",
  "The outlet; then into their eyes alone",
  "I looked to read myself,' without a sign",
  "Or word. I wept not--turned within to stone.",
  "",
  "They wept aloud, and little Anselm mine,",
  "Said--'twas my youngest, dearest little one,--",
  "\"What ails thee, father? Why look so at thine?\"",
  "",
  "In all that day, and all the following night,",
  "I wept not, nor replied; but when to shine",
  "Upon the world, not us, came forth the light",
  "",
  "Of the new sun, and thwart my prison thrown",
  "Gleamed through its narrow chink, a doleful sight,",
  "'Three faces, each the reflex of my own,",
  "",
  "Were imaged by its faint and ghastly ray;'",
  "Then I, of either hand unto the bone,",
  "Gnawed, in my agony; and thinking they",
  "",
  "Twas done from sudden pangs, in their excess,",
  "All of a sudden raise themselves, and say,",
  "\"Father! our woes, so great, were yet the less",
  "",
  "Would you but eat of us,--twas 'you who clad",
  "Our bodies in these weeds of wretchedness;",
  "Despoil them'.\" Not to make their hearts more sad,",
  "",
  "I 'hushed' myself. That day is at its close,--",
  "Another--still we were all mute. Oh, had",
  "The obdurate earth opened to end our woes!",
  "",
  "The fourth day dawned, and when the new sun shone,",
  "Outstretched himself before me as it rose",
  "My Gaddo, saying, \"Help, father! hast thou none",
  "",
  "For thine own child--is there no help from thee?\"",
  "He died--there at my feet--and one by one,",
  "I saw them fall, plainly as you see me.",
  "",
  "Between the fifth and sixth day, ere twas dawn,",
  "I found 'myself blind-groping o'er the three.'",
  "Three days I called them after they were gone.",
  "",
  "Famine of grief can get the mastery.",
  ""
]