module.exports = [
  "WHEN these old woods were young",
  "The thrushes' ancestors",
  "As sweetly sung",
  "In the old years.",
  "",
  "There was no garden here,",
  "Apples nor mistletoe;",
  "No children dear",
  "Ran to and fro.",
  "",
  "New then was this thatched cot,",
  "But the keeper was old,",
  "And he had not",
  "Much lead or gold.",
  "",
  "Most silent beech and yew:",
  "As he went round about",
  "The woods to view",
  "Seldom he shot.",
  "",
  "But now that he is gone",
  "Out of most memories,",
  "Still lingers on,",
  "A stoat of his,",
  "",
  "But one, shrivelled and green,",
  "And with no scent at all,",
  "And barely seen",
  "On this shed wall.",
  ""
]