module.exports = [
  "'Tis midnight--but it is not dark",
  "Within thy spacious place, St. Mark!",
  "The Lights within, the Lamps without,",
  "Shine above the revel rout.",
  "The brazen Steeds are glittering o'er",
  "The holy building's massy door,",
  "Glittering with their collars of gold,",
  "The goodly work of the days of old--",
  "And the wingéd Lion stern and solemn",
  "Frowns from the height of his hoary column,",
  "Facing the palace in which doth lodge",
  "The ocean-city's dreaded Doge.",
  "The palace is proud--but near it lies,",
  "Divided by the \"Bridge of Sighs,\"",
  "The dreary dwelling where the State",
  "Enchains the captives of their hate:",
  "These--they perish or they pine;",
  "But which their doom may none divine:",
  "Many have passed that Arch of pain,",
  "But none retraced their steps again.",
  "",
  "It is a princely colonnade!",
  "And wrought around a princely place,",
  "When that vast edifice displayed",
  "Looks with its venerable face",
  "Over the far and subject sea,",
  "Which makes the fearless isles so free!",
  "And 'tis a strange and noble pile,",
  "Pillared into many an aisle:",
  "Every pillar fair to see,",
  "Marble--jasper--and porphyry--",
  "The Church of St. Mark--which stands hard by",
  "With fretted pinnacles on high,",
  "And Cupola and minaret;",
  "More like the mosque of orient lands,",
  "Than the fanes wherein we pray,",
  "And Mary's blesséd likeness stands.--",
  ""
]