module.exports = [
  "A cat in distress,",
  "Nothing more, nor less;",
  "Good folks, I must faithfully tell ye,",
  "As I am a sinner,",
  "It waits for some dinner",
  "To stuff out its own little belly.",
  "",
  "You would not easily guess",
  "All the modes of distress",
  "Which torture the tenants of earth;",
  "And the various evils,",
  "Which like so many devils,",
  "Attend the poor souls from their birth.",
  "",
  "Some a living require,",
  "And others desire",
  "An old fellow out of the way;",
  "And which is the best",
  "I leave to be guessed,",
  "For I cannot pretend to say.",
  "",
  "One wants society,",
  "Another variety,",
  "Others a tranquil life;",
  "Some want food,",
  "Others, as good,",
  "Only want a wife.",
  "",
  "But this poor little cat",
  "Only wanted a rat,",
  "To stuff out its own little maw;",
  "And it were as good",
  "SOME people had such food,",
  "To make them HOLD THEIR JAW!",
  ""
]