module.exports = [
  "The King was on his throne,",
  "  The Satraps thronged the hall:",
  "A thousand bright lamps shone",
  "  O'er that high festival.",
  "A thousand cups of gold,",
  "  In Judah deemed divine--",
  "Jehovah's vessels hold",
  "  The godless Heathen's wine!",
  "",
  "In that same hour and hall,",
  "  The fingers of a hand",
  "Came forth against the wall,",
  "  And wrote as if on sand:",
  "The fingers of a man;--",
  "  A solitary hand",
  "Along the letters ran,",
  "  And traced them like a wand.",
  "",
  "The monarch saw, and shook,",
  "  And bade no more rejoice;",
  "All bloodless waxed his look,",
  "  And tremulous his voice.",
  "\"Let the men of lore appear,",
  "  The wisest of the earth,",
  "And expound the words of fear,",
  "  Which mar our royal mirth.\"",
  "",
  "Chaldea's seers are good,",
  "  But here they have no skill;",
  "And the unknown letters stood",
  "  Untold and awful still.",
  "And Babel's men of age",
  "  Are wise and deep in lore;",
  "But now they were not sage,",
  "  They saw--but knew no more.",
  "",
  "A captive in the land,",
  "  A stranger and a youth,",
  "He heard the King's command,",
  "  He saw that writing's truth.",
  "The lamps around were bright,",
  "  The prophecy in view;",
  "He read it on that night,--",
  "  The morrow proved it true.",
  "",
  "\"Belshazzar's grave is made,",
  "  His kingdom passed away.",
  "He, in the balance weighed,",
  "  Is light and worthless clay;",
  "The shroud, his robe of state,",
  "  His canopy the stone;",
  "The Mede is at his gate!",
  "  The Persian on his throne!\"",
  ""
]