module.exports = [
  "1",
  "I CELEBRATE myself;",
  "And what I assume you shall assume;",
  "For every atom belonging to me, as good belongs to you.",
  "",
  "I loafe and invite my Soul;",
  "I lean and loafe at my ease, observing a spear of summer grass.",
  "",
  "Houses and rooms are full of perfumes—the shelves are crowded with",
  "  perfumes;",
  "I breathe the fragrance myself, and know it and like it;",
  "The distillation would intoxicate me also, but I shall not let it.",
  "",
  "The atmosphere is not a perfume—it has no taste of the distillation—it",
  "  is odorless;",
  "It is for my mouth forever—I am in love with it;",
  "I will go to the bank by the wood, and become undisguised and naked;",
  "I am mad for it to be in contact with me.",
  "",
  "2",
  "The smoke of my own breath;",
  "Echoes, ripples, buzz’d whispers, love-root, silk-thread, crotch and vine;",
  "My respiration and inspiration, the beating of my heart, the passing of blood",
  "  and air through my lungs;",
  "The sniff of green leaves and dry leaves, and of the shore, and",
  "  dark-color’d sea-rocks, and of hay in the barn;",
  "The sound of the belch’d words of my voice, words loos’d to the eddies",
  "  of the wind;",
  "A few light kisses, a few embraces, a reaching around of arms;",
  "The play of shine and shade on the trees as the supple boughs wag;",
  "The delight alone, or in the rush of the streets, or along the fields and",
  "  hill-sides;",
  "The feeling of health, the full-noon trill, the song of me rising from bed and",
  "  meeting the sun.",
  "",
  "Have you reckon’d a thousand acres much? have you reckon’d the earth",
  "  much?",
  "Have you practis’d so long to learn to read?",
  "Have you felt so proud to get at the meaning of poems?",
  "",
  "Stop this day and night with me, and you shall possess the origin of all poems;",
  "You shall possess the good of the earth and sun—(there are millions of suns",
  "  left;)",
  "You shall no longer take things at second or third hand, nor look through the",
  "  eyes of the dead, nor feed on the spectres in books;",
  "You shall not look through my eyes either, nor take things from me:",
  "You shall listen to all sides, and filter them from yourself.",
  "",
  "3",
  "I have heard what the talkers were talking, the talk of the beginning and the",
  "  end;",
  "But I do not talk of the beginning or the end.",
  "",
  "There was never any more inception than there is now,",
  "Nor any more youth or age than there is now;",
  "And will never be any more perfection than there is now,",
  "Nor any more heaven or hell than there is now.",
  "",
  "Urge, and urge, and urge;",
  "Always the procreant urge of the world.",
  "",
  "Out of the dimness opposite equals advance—always substance and increase,",
  "  always sex;",
  "Always a knit of identity—always distinction—always a breed of life.",
  "",
  "To elaborate is no avail—learn’d and unlearn’d feel that it is",
  "  so.",
  "",
  "Sure as the most certain sure, plumb in the uprights, well entretied, braced in",
  "  the beams,",
  "Stout as a horse, affectionate, haughty, electrical,",
  "I and this mystery, here we stand.",
  "",
  "Clear and sweet is my Soul, and clear and sweet is all that is not my Soul.",
  "",
  "Lack one lacks both, and the unseen is proved by the seen,",
  "Till that becomes unseen, and receives proof in its turn.",
  "",
  "Showing the best, and dividing it from the worst, age vexes age;",
  "Knowing the perfect fitness and equanimity of things, while they discuss I am",
  "  silent, and go bathe and admire myself.",
  "",
  "Welcome is every organ and attribute of me, and of any man hearty and clean;",
  "Not an inch, nor a particle of an inch, is vile, and none shall be less familiar",
  "  than the rest.",
  "",
  "I am satisfied—I see, dance, laugh, sing:",
  "As the hugging and loving Bed-fellow sleeps at my side through the night, and",
  "  withdraws at the peep of the day, with stealthy tread,",
  "Leaving me baskets cover’d with white towels, swelling the house with their",
  "  plenty,",
  "Shall I postpone my acceptation and realization, and scream at my eyes,",
  "That they turn from gazing after and down the road,",
  "And forthwith cipher and show me a cent,",
  "Exactly the contents of one, and exactly the contents of two, and which is",
  "  ahead?",
  "",
  "4",
  "Trippers and askers surround me;",
  "People I meet—the effect upon me of my early life, or the ward and city I",
  "  live in, or the nation,",
  "The latest dates, discoveries, inventions, societies, authors old and new,",
  "My dinner, dress, associates, looks, compliments, dues,",
  "The real or fancied indifference of some man or woman I love,",
  "The sickness of one of my folks, or of myself, or ill-doing, or loss or lack of",
  "  money, or depressions or exaltations;",
  "Battles, the horrors of fratricidal war, the fever of doubtful news, the fitful",
  "  events;",
  "These come to me days and nights, and go from me again,",
  "But they are not the Me myself.",
  "",
  "Apart from the pulling and hauling stands what I am;",
  "Stands amused, complacent, compassionating, idle, unitary;",
  "Looks down, is erect, or bends an arm on an impalpable certain rest,",
  "Looking with side-curved head, curious what will come next;",
  "Both in and out of the game, and watching and wondering at it.",
  "",
  "Backward I see in my own days where I sweated through fog with linguists and",
  "  contenders;",
  "I have no mockings or arguments—I witness and wait.",
  "",
  "5",
  "I believe in you, my Soul—the other I am must not abase itself to you;",
  "And you must not be abased to the other.",
  "",
  "Loafe with me on the grass—loose the stop from your throat;",
  "Not words, not music or rhyme I want—not custom or lecture, not even the",
  "  best;",
  "Only the lull I like, the hum of your valved voice.",
  "",
  "I mind how once we lay, such a transparent summer morning;",
  "How you settled your head athwart my hips, and gently turn’d over upon me,",
  "And parted the shirt from my bosom-bone, and plunged your tongue to my",
  "  bare-stript heart,",
  "And reach’d till you felt my beard, and reach’d till you held my feet.",
  "",
  "",
  "Swiftly arose and spread around me the peace and knowledge that pass all the",
  "  argument of the earth;",
  "And I know that the hand of God is the promise of my own,",
  "And I know that the spirit of God is the brother of my own;",
  "And that all the men ever born are also my brothers, and the women my sisters",
  "  and lovers;",
  "And that a kelson of the creation is love;",
  "And limitless are leaves, stiff or drooping in the fields;",
  "And brown ants in the little wells beneath them;",
  "And mossy scabs of the worm fence, and heap’d stones, elder, mullen and",
  "  poke-weed.",
  "",
  "6",
  "A child said, What is the grass? fetching it to me with full hands;",
  "How could I answer the child? I do not know what it is, any more than he.",
  "",
  "I guess it must be the flag of my disposition, out of hopeful green stuff woven.",
  "",
  "",
  "Or I guess it is the handkerchief of the Lord,",
  "A scented gift and remembrancer, designedly dropt,",
  "Bearing the owner’s name someway in the corners, that we may see and",
  "  remark, and say, Whose?",
  "",
  "Or I guess the grass is itself a child, the produced babe of the vegetation.",
  "",
  "Or I guess it is a uniform hieroglyphic;",
  "And it means, Sprouting alike in broad zones and narrow zones,",
  "Growing among black folks as among white;",
  "Kanuck, Tuckahoe, Congressman, Cuff, I give them the same, I receive them the",
  "  same.",
  "",
  "And now it seems to me the beautiful uncut hair of graves.",
  "",
  "Tenderly will I use you, curling grass;",
  "It may be you transpire from the breasts of young men;",
  "It may be if I had known them I would have loved them;",
  "It may be you are from old people, and from women, and from offspring taken soon",
  "  out of their mothers’ laps;",
  "And here you are the mothers’ laps.",
  "",
  "This grass is very dark to be from the white heads of old mothers;",
  "Darker than the colorless beards of old men;",
  "Dark to come from under the faint red roofs of mouths.",
  "",
  "O I perceive after all so many uttering tongues!",
  "And I perceive they do not come from the roofs of mouths for nothing.",
  "",
  "I wish I could translate the hints about the dead young men and women,",
  "And the hints about old men and mothers, and the offspring taken soon out of",
  "  their laps.",
  "",
  "What do you think has become of the young and old men?",
  "And what do you think has become of the women and children?",
  "",
  "They are alive and well somewhere;",
  "The smallest sprout shows there is really no death;",
  "And if ever there was, it led forward life, and does not wait at the end to",
  "  arrest it,",
  "And ceas’d the moment life appear’d.",
  "",
  "All goes onward and outward—nothing collapses;",
  "And to die is different from what any one supposed, and luckier.",
  "",
  "7",
  "Has any one supposed it lucky to be born?",
  "I hasten to inform him or her, it is just as lucky to die, and I know it.",
  "",
  "I pass death with the dying, and birth with the new-wash’d babe, and am not",
  "  contain’d between my hat and boots;",
  "And peruse manifold objects, no two alike, and every one good;",
  "The earth good, and the stars good, and their adjuncts all good.",
  "",
  "I am not an earth, nor an adjunct of an earth;",
  "I am the mate and companion of people, all just as immortal and fathomless as",
  "  myself;",
  "(They do not know how immortal, but I know.)",
  "",
  "Every kind for itself and its own—for me mine, male and female;",
  "For me those that have been boys, and that love women;",
  "For me the man that is proud, and feels how it stings to be slighted;",
  "For me the sweet-heart and the old maid—for me mothers, and the mothers of",
  "  mothers;",
  "For me lips that have smiled, eyes that have shed tears;",
  "For me children, and the begetters of children.",
  "",
  "Undrape! you are not guilty to me, nor stale, nor discarded;",
  "I see through the broadcloth and gingham, whether or no;",
  "And am around, tenacious, acquisitive, tireless, and cannot be shaken away.",
  "",
  "8",
  "The little one sleeps in its cradle;",
  "I lift the gauze, and look a long time, and silently brush away flies with my",
  "  hand.",
  "",
  "The youngster and the red-faced girl turn aside up the bushy hill;",
  "I peeringly view them from the top.",
  "",
  "The suicide sprawls on the bloody floor of the bed-room;",
  "I witness the corpse with its dabbled hair—I note where the pistol has",
  "  fallen.",
  "",
  "The blab of the pave, the tires of carts, sluff of boot-soles, talk of the",
  "  promenaders;",
  "The heavy omnibus, the driver with his interrogating thumb, the clank of the",
  "  shod horses on the granite floor;",
  "The snow-sleighs, the clinking, shouted jokes, pelts of snowballs;",
  "The hurrahs for popular favorites, the fury of rous’d mobs;",
  "The flap of the curtain’d litter, a sick man inside, borne to the hospital;",
  "The meeting of enemies, the sudden oath, the blows and fall;",
  "The excited crowd, the policeman with his star, quickly working his passage to",
  "  the centre of the crowd;",
  "The impassive stones that receive and return so many echoes;",
  "What groans of over-fed or half-starv’d who fall sun-struck, or in fits;",
  "What exclamations of women taken suddenly, who hurry home and give birth to",
  "  babes;",
  "What living and buried speech is always vibrating here—what howls",
  "  restrain’d by decorum;",
  "Arrests of criminals, slights, adulterous offers made, acceptances, rejections",
  "  with convex lips;",
  "I mind them or the show or resonance of them—I come, and I depart.",
  "",
  "9",
  "The big doors of the country barn stand open and ready;",
  "The dried grass of the harvest-time loads the slow-drawn wagon;",
  "The clear light plays on the brown gray and green intertinged;",
  "The armfuls are pack’d to the sagging mow.",
  "",
  "I am there—I help—I came stretch’d atop of the load;",
  "I felt its soft jolts—one leg reclined on the other;",
  "I jump from the cross-beams, and seize the clover and timothy,",
  "And roll head over heels, and tangle my hair full of wisps.",
  "",
  "10",
  "Alone, far in the wilds and mountains, I hunt,",
  "Wandering, amazed at my own lightness and glee;",
  "In the late afternoon choosing a safe spot to pass the night,",
  "Kindling a fire and broiling the fresh-kill’d game;",
  "Falling asleep on the gather’d leaves, with my dog and gun by my side.",
  "",
  "The Yankee clipper is under her sky-sails—she cuts the sparkle and scud;",
  "My eyes settle the land—I bend at her prow, or shout joyously from the",
  "  deck.",
  "",
  "The boatmen and clam-diggers arose early and stopt for me;",
  "I tuck’d my trowser-ends in my boots, and went and had a good time:",
  "(You should have been with us that day round the chowder-kettle.)",
  "",
  "I saw the marriage of the trapper in the open air in the far west—the bride",
  "  was a red girl;",
  "Her father and his friends sat near, cross-legged and dumbly smoking—they",
  "  had moccasins to their feet, and large thick blankets hanging from their",
  "  shoulders;",
  "On a bank lounged the trapper—he was drest mostly in skins—his",
  "  luxuriant beard and curls protected his neck—he held his bride by the hand;",
  "",
  "She had long eyelashes—her head was bare—her coarse straight locks",
  "  descended upon her voluptuous limbs and reach’d to her feet.",
  "",
  "The runaway slave came to my house and stopt outside;",
  "I heard his motions crackling the twigs of the woodpile;",
  "Through the swung half-door of the kitchen I saw him limpsy and weak,",
  "And went where he sat on a log, and led him in and assured him,",
  "And brought water, and fill’d a tub for his sweated body and bruis’d",
  "  feet,",
  "And gave him a room that enter’d from my own, and gave him some coarse",
  "  clean clothes,",
  "And remember perfectly well his revolving eyes and his awkwardness,",
  "And remember putting plasters on the galls of his neck and ankles;",
  "He staid with me a week before he was recuperated and pass’d north;",
  "(I had him sit next me at table—my fire-lock lean’d in the corner.)",
  "",
  "11",
  "Twenty-eight young men bathe by the shore;",
  "Twenty-eight young men, and all so friendly:",
  "Twenty-eight years of womanly life, and all so lonesome.",
  "",
  "She owns the fine house by the rise of the bank;",
  "She hides, handsome and richly drest, aft the blinds of the window.",
  "",
  "Which of the young men does she like the best?",
  "Ah, the homeliest of them is beautiful to her.",
  "",
  "Where are you off to, lady? for I see you;",
  "You splash in the water there, yet stay stock still in your room.",
  "",
  "Dancing and laughing along the beach came the twenty-ninth bather;",
  "The rest did not see her, but she saw them and loved them.",
  "",
  "The beards of the young men glisten’d with wet, it ran from their long",
  "  hair:",
  "Little streams pass’d all over their bodies.",
  "",
  "An unseen hand also pass’d over their bodies;",
  "It descended tremblingly from their temples and ribs.",
  "",
  "The young men float on their backs—their white bellies bulge to the",
  "  sun—they do not ask who seizes fast to them;",
  "They do not know who puffs and declines with pendant and bending arch;",
  "They do not think whom they souse with spray.",
  "",
  "12",
  "The butcher-boy puts off his killing clothes, or sharpens his knife at the stall",
  "  in the market;",
  "I loiter, enjoying his repartee, and his shuffle and break-down.",
  "",
  "Blacksmiths with grimed and hairy chests environ the anvil;",
  "Each has his main-sledge—they are all out—(there is a great heat in",
  "  the fire.)",
  "",
  "From the cinder-strew’d threshold I follow their movements;",
  "The lithe sheer of their waists plays even with their massive arms;",
  "Over-hand the hammers swing—over-hand so slow—over-hand so sure:",
  "They do not hasten—each man hits in his place.",
  "",
  "13",
  "The negro holds firmly the reins of his four horses—the block swags",
  "  underneath on its tied-over chain;",
  "The negro that drives the dray of the stone-yard—steady and tall he stands,",
  "  pois’d on one leg on the string-piece;",
  "His blue shirt exposes his ample neck and breast, and loosens over his hip-band;",
  "",
  "His glance is calm and commanding—he tosses the slouch of his hat away from",
  "  his forehead;",
  "The sun falls on his crispy hair and moustache—falls on the black of his",
  "  polish’d and perfect limbs.",
  "",
  "I behold the picturesque giant, and love him—and I do not stop there;",
  "I go with the team also.",
  "",
  "In me the caresser of life wherever moving—backward as well as forward",
  "  slueing;",
  "To niches aside and junior bending.",
  "",
  "Oxen that rattle the yoke and chain, or halt in the leafy shade! what is that",
  "  you express in your eyes?",
  "It seems to me more than all the print I have read in my life.",
  "",
  "My tread scares the wood-drake and wood-duck, on my distant and day-long ramble;",
  "",
  "They rise together—they slowly circle around.",
  "",
  "I believe in those wing’d purposes,",
  "And acknowledge red, yellow, white, playing within me,",
  "And consider green and violet, and the tufted crown, intentional;",
  "And do not call the tortoise unworthy because she is not something else;",
  "And the jay in the woods never studied the gamut, yet trills pretty well to me;",
  "And the look of the bay mare shames silliness out of me.",
  "",
  "14",
  "The wild gander leads his flock through the cool night;",
  "Ya-honk! he says, and sounds it down to me like an invitation;",
  "(The pert may suppose it meaningless, but I listen close;",
  "I find its purpose and place up there toward the wintry sky.)",
  "",
  "The sharp-hoof’d moose of the north, the cat on the house-sill, the",
  "  chickadee, the prairie-dog,",
  "The litter of the grunting sow as they tug at her teats,",
  "The brood of the turkey-hen, and she with her half-spread wings;",
  "I see in them and myself the same old law.",
  "",
  "The press of my foot to the earth springs a hundred affections;",
  "They scorn the best I can do to relate them.",
  "",
  "I am enamour’d of growing out-doors,",
  "Of men that live among cattle, or taste of the ocean or woods,",
  "Of the builders and steerers of ships, and the wielders of axes and mauls, and",
  "  the drivers of horses;",
  "I can eat and sleep with them week in and week out.",
  "",
  "What is commonest, cheapest, nearest, easiest, is Me;",
  "Me going in for my chances, spending for vast returns;",
  "Adorning myself to bestow myself on the first that will take me;",
  "Not asking the sky to come down to my good will;",
  "Scattering it freely forever.",
  "",
  "15",
  "The pure contralto sings in the organ loft;",
  "The carpenter dresses his plank—the tongue of his foreplane whistles its",
  "  wild ascending lisp;",
  "The married and unmarried children ride home to their Thanksgiving dinner;",
  "The pilot seizes the king-pin—he heaves down with a strong arm;",
  "The mate stands braced in the whale-boat—lance and harpoon are ready;",
  "The duck-shooter walks by silent and cautious stretches;",
  "The deacons are ordain’d with cross’d hands at the altar;",
  "The spinning-girl retreats and advances to the hum of the big wheel;",
  "The farmer stops by the bars, as he walks on a First-day loafe, and looks at the",
  "  oats and rye;",
  "The lunatic is carried at last to the asylum, a confirm’d case,",
  "(He will never sleep any more as he did in the cot in his mother’s",
  "  bed-room;)",
  "The jour printer with gray head and gaunt jaws works at his case,",
  "He turns his quid of tobacco, while his eyes blurr with the manuscript;",
  "The malform’d limbs are tied to the surgeon’s table,",
  "What is removed drops horribly in a pail;",
  "The quadroon girl is sold at the auction-stand—the drunkard nods by the",
  "  bar-room stove;",
  "The machinist rolls up his sleeves—the policeman travels his beat—the",
  "  gate-keeper marks who pass;",
  "The young fellow drives the express-wagon—(I love him, though I do not know",
  "  him;)",
  "The half-breed straps on his light boots to complete in the race;",
  "The western turkey-shooting draws old and young—some lean on their rifles,",
  "  some sit on logs,",
  "Out from the crowd steps the marksman, takes his position, levels his piece;",
  "The groups of newly-come immigrants cover the wharf or levee;",
  "As the woolly-pates hoe in the sugar-field, the overseer views them from his",
  "  saddle;",
  "The bugle calls in the ball-room, the gentlemen run for their partners, the",
  "  dancers bow to each other;",
  "The youth lies awake in the cedar-roof’d garret, and harks to the musical",
  "  rain;",
  "The Wolverine sets traps on the creek that helps fill the Huron;",
  "The squaw, wrapt in her yellow-hemm’d cloth, is offering moccasins and",
  "  bead-bags for sale;",
  "The connoisseur peers along the exhibition-gallery with half-shut eyes bent",
  "  sideways;",
  "As the deck-hands make fast the steamboat, the plank is thrown for the",
  "  shore-going passengers;",
  "The young sister holds out the skein, while the elder sister winds it off in a",
  "  ball, and stops now and then for the knots;",
  "The one-year wife is recovering and happy, having a week ago borne her first",
  "  child;",
  "The clean-hair’d Yankee girl works with her sewing-machine, or in the",
  "  factory or mill;",
  "The nine months’ gone is in the parturition chamber, her faintness and",
  "  pains are advancing;",
  "The paving-man leans on his two-handed rammer—the reporter’s lead",
  "  flies swiftly over the note-book—the sign-painter is lettering with red and",
  "  gold;",
  "The canal boy trots on the tow-path—the book-keeper counts at his",
  "  desk—the shoemaker waxes his thread;",
  "The conductor beats time for the band, and all the performers follow him;",
  "The child is baptized—the convert is making his first professions;",
  "The regatta is spread on the bay—the race is begun—how the white sails",
  "  sparkle!",
  "The drover, watching his drove, sings out to them that would stray;",
  "The pedler sweats with his pack on his back, (the purchaser higgling about the",
  "  odd cent;)",
  "The camera and plate are prepared, the lady must sit for her daguerreotype;",
  "The bride unrumples her white dress, the minute-hand of the clock moves slowly;",
  "The opium-eater reclines with rigid head and just-open’d lips;",
  "The prostitute draggles her shawl, her bonnet bobs on her tipsy and pimpled",
  "  neck;",
  "The crowd laugh at her blackguard oaths, the men jeer and wink to each other;",
  "(Miserable! I do not laugh at your oaths, nor jeer you;)",
  "The President, holding a cabinet council, is surrounded by the Great",
  "  Secretaries;",
  "On the piazza walk three matrons stately and friendly with twined arms;",
  "The crew of the fish-smack pack repeated layers of halibut in the hold;",
  "The Missourian crosses the plains, toting his wares and his cattle;",
  "As the fare-collector goes through the train, he gives notice by the jingling of",
  "  loose change;",
  "The floor-men are laying the floor—the tinners are tinning the",
  "  roof—the masons are calling for mortar;",
  "In single file, each shouldering his hod, pass onward the laborers;",
  "Seasons pursuing each other, the indescribable crowd is gather’d—it is",
  "  the Fourth of Seventh-month—(What salutes of cannon and small arms!)",
  "Seasons pursuing each other, the plougher ploughs, the mower mows, and the",
  "  winter-grain falls in the ground;",
  "Off on the lakes the pike-fisher watches and waits by the hole in the frozen",
  "  surface;",
  "The stumps stand thick round the clearing, the squatter strikes deep with his",
  "  axe;",
  "Flatboatmen make fast, towards dusk, near the cottonwood or pekan-trees;",
  "Coon-seekers go through the regions of the Red river, or through those",
  "  drain’d by the Tennessee, or through those of the Arkansaw;",
  "Torches shine in the dark that hangs on the Chattahoochee or Altamahaw;",
  "Patriarchs sit at supper with sons and grandsons and great-grandsons around",
  "  them;",
  "In walls of adobie, in canvas tents, rest hunters and trappers after their",
  "  day’s sport;",
  "The city sleeps, and the country sleeps;",
  "The living sleep for their time, the dead sleep for their time;",
  "The old husband sleeps by his wife, and the young husband sleeps by his wife;",
  "And these one and all tend inward to me, and I tend outward to them;",
  "And such as it is to be of these, more or less, I am.",
  "",
  "16",
  "I am of old and young, of the foolish as much as the wise;",
  "Regardless of others, ever regardful of others,",
  "Maternal as well as paternal, a child as well as a man,",
  "Stuff’d with the stuff that is coarse, and stuff’d with the stuff that",
  "  is fine;",
  "One of the Great Nation, the nation of many nations, the smallest the same, and",
  "  the largest the same;",
  "A southerner soon as a northerner—a planter nonchalant and hospitable, down",
  "  by the Oconee I live;",
  "A Yankee, bound by my own way, ready for trade, my joints the limberest joints",
  "  on earth, and the sternest joints on earth;",
  "A Kentuckian, walking the vale of the Elkhorn, in my deer-skin leggings—a",
  "  Louisianian or Georgian;",
  "A boatman over lakes or bays, or along coasts—a Hoosier, Badger, Buckeye;",
  "At home on Kanadian snow-shoes, or up in the bush, or with fishermen off",
  "  Newfoundland;",
  "At home in the fleet of ice-boats, sailing with the rest and tacking;",
  "At home on the hills of Vermont, or in the woods of Maine, or the Texan ranch;",
  "Comrade of Californians—comrade of free north-westerners, (loving their big",
  "  proportions;)",
  "Comrade of raftsmen and coalmen—comrade of all who shake hands and welcome",
  "  to drink and meat;",
  "A learner with the simplest, a teacher of the thoughtfullest;",
  "A novice beginning, yet experient of myriads of seasons;",
  "Of every hue and caste am I, of every rank and religion;",
  "A farmer, mechanic, artist, gentleman, sailor, quaker;",
  "A prisoner, fancy-man, rowdy, lawyer, physician, priest.",
  "",
  "I resist anything better than my own diversity;",
  "I breathe the air, but leave plenty after me,",
  "And am not stuck up, and am in my place.",
  "",
  "(The moth and the fish-eggs are in their place;",
  "The suns I see, and the suns I cannot see, are in their place;",
  "The palpable is in its place, and the impalpable is in its place.)",
  "",
  "17",
  "These are the thoughts of all men in all ages and lands—they are not",
  "  original with me;",
  "If they are not yours as much as mine, they are nothing, or next to nothing;",
  "If they are not the riddle, and the untying of the riddle, they are nothing;",
  "If they are not just as close as they are distant, they are nothing.",
  "",
  "This is the grass that grows wherever the land is, and the water is;",
  "This is the common air that bathes the globe.",
  "",
  "18",
  "With music strong I come—with my cornets and my drums,",
  "I play not marches for accepted victors only—I play great marches for",
  "  conquer’d and slain persons.",
  "",
  "Have you heard that it was good to gain the day?",
  "I also say it is good to fall—battles are lost in the same spirit in which",
  "  they are won.",
  "",
  "I beat and pound for the dead;",
  "I blow through my embouchures my loudest and gayest for them.",
  "",
  "Vivas to those who have fail’d!",
  "And to those whose war-vessels sank in the sea!",
  "And to those themselves who sank in the sea!",
  "And to all generals that lost engagements! and all overcome heroes!",
  "And the numberless unknown heroes, equal to the greatest heroes known.",
  "",
  "19",
  "This is the meal equally set—this is the meat for natural hunger;",
  "It is for the wicked just the same as the righteous—I make appointments",
  "  with all;",
  "I will not have a single person slighted or left away;",
  "The kept-woman, sponger, thief, are hereby invited;",
  "The heavy-lipp’d slave is invited—the venerealee is invited:",
  "There shall be no difference between them and the rest.",
  "",
  "This is the press of a bashful hand—this is the float and odor of hair;",
  "This is the touch of my lips to yours—this is the murmur of yearning;",
  "This is the far-off depth and height reflecting my own face;",
  "This is the thoughtful merge of myself, and the outlet again.",
  "",
  "Do you guess I have some intricate purpose?",
  "Well, I have—for the Fourth-month showers have, and the mica on the side of",
  "  a rock has.",
  "",
  "Do you take it I would astonish?",
  "Does the daylight astonish? Does the early redstart, twittering through the",
  "  woods?",
  "Do I astonish more than they?",
  "",
  "This hour I tell things in confidence;",
  "I might not tell everybody, but I will tell you.",
  "",
  "20",
  "Who goes there? hankering, gross, mystical, nude;",
  "How is it I extract strength from the beef I eat?",
  "",
  "What is a man, anyhow? What am I? What are you?",
  "",
  "All I mark as my own, you shall offset it with your own;",
  "Else it were time lost listening to me.",
  "",
  "I do not snivel that snivel the world over,",
  "That months are vacuums, and the ground but wallow and filth;",
  "That life is a suck and a sell, and nothing remains at the end but threadbare",
  "  crape, and tears.",
  "",
  "Whimpering and truckling fold with powders for invalids—conformity goes to",
  "  the fourth-remov’d;",
  "I wear my hat as I please, indoors or out.",
  "",
  "Why should I pray? Why should I venerate and be ceremonious?",
  "",
  "Having pried through the strata, analyzed to a hair, counsell’d with",
  "  doctors, and calculated close,",
  "I find no sweeter fat than sticks to my own bones.",
  "",
  "In all people I see myself—none more, and not one a barleycorn less;",
  "And the good or bad I say of myself, I say of them.",
  "",
  "And I know I am solid and sound;",
  "To me the converging objects of the universe perpetually flow;",
  "All are written to me, and I must get what the writing means.",
  "",
  "I know I am deathless;",
  "I know this orbit of mine cannot be swept by the carpenter’s compass;",
  "I know I shall not pass like a child’s carlacue cut with a burnt stick at",
  "  night.",
  "",
  "I know I am august;",
  "I do not trouble my spirit to vindicate itself or be understood;",
  "I see that the elementary laws never apologize;",
  "(I reckon I behave no prouder than the level I plant my house by, after all.)",
  "",
  "I exist as I am—that is enough;",
  "If no other in the world be aware, I sit content;",
  "And if each and all be aware, I sit content.",
  "",
  "One world is aware, and by far the largest to me, and that is myself;",
  "And whether I come to my own to-day, or in ten thousand or ten million years,",
  "I can cheerfully take it now, or with equal cheerfulness I can wait.",
  "",
  "My foothold is tenon’d and mortis’d in granite;",
  "I laugh at what you call dissolution;",
  "And I know the amplitude of time.",
  "",
  "21",
  "I am the poet of the Body;",
  "And I am the poet of the Soul.",
  "",
  "The pleasures of heaven are with me, and the pains of hell are with me;",
  "The first I graft and increase upon myself—the latter I translate into a",
  "  new tongue.",
  "",
  "I am the poet of the woman the same as the man;",
  "And I say it is as great to be a woman as to be a man;",
  "And I say there is nothing greater than the mother of men.",
  "",
  "I chant the chant of dilation or pride;",
  "We have had ducking and deprecating about enough;",
  "I show that size is only development.",
  "",
  "Have you outstript the rest? Are you the President?",
  "It is a trifle—they will more than arrive there, every one, and still pass",
  "  on.",
  "",
  "I am he that walks with the tender and growing night;",
  "I call to the earth and sea, half-held by the night.",
  "",
  "Press close, bare-bosom’d night! Press close, magnetic, nourishing night!",
  "Night of south winds! night of the large few stars!",
  "Still, nodding night! mad, naked, summer night.",
  "",
  "Smile, O voluptuous, cool-breath’d earth!",
  "Earth of the slumbering and liquid trees;",
  "Earth of departed sunset! earth of the mountains, misty-topt!",
  "Earth of the vitreous pour of the full moon, just tinged with blue!",
  "Earth of shine and dark, mottling the tide of the river!",
  "Earth of the limpid gray of clouds, brighter and clearer for my sake!",
  "Far-swooping elbow’d earth! rich, apple-blossom’d earth!",
  "Smile, for your lover comes!",
  "",
  "Prodigal, you have given me love! Therefore I to you give love!",
  "O unspeakable, passionate love!",
  "",
  "22",
  "You sea! I resign myself to you also—I guess what you mean;",
  "I behold from the beach your crooked inviting fingers;",
  "I believe you refuse to go back without feeling of me;",
  "We must have a turn together—I undress—hurry me out of sight of the",
  "  land;",
  "Cushion me soft, rock me in billowy drowse;",
  "Dash me with amorous wet—I can repay you.",
  "",
  "Sea of stretch’d ground-swells!",
  "Sea breathing broad and convulsive breaths!",
  "Sea of the brine of life! sea of unshovell’d yet always-ready graves!",
  "Howler and scooper of storms! capricious and dainty sea!",
  "I am integral with you—I too am of one phase, and of all phases.",
  "",
  "Partaker of influx and efflux I—extoller of hate and conciliation;",
  "Extoller of amies, and those that sleep in each others’ arms.",
  "",
  "I am he attesting sympathy;",
  "(Shall I make my list of things in the house, and skip the house that supports",
  "  them?)",
  "",
  "I am not the poet of goodness only—I do not decline to be the poet of",
  "  wickedness also.",
  "",
  "Washes and razors for foofoos—for me freckles and a bristling beard.",
  "",
  "What blurt is this about virtue and about vice?",
  "Evil propels me, and reform of evil propels me—I stand indifferent;",
  "My gait is no fault-finder’s or rejecter’s gait;",
  "I moisten the roots of all that has grown.",
  "",
  "Did you fear some scrofula out of the unflagging pregnancy?",
  "Did you guess the celestial laws are yet to be work’d over and rectified?",
  "",
  "I find one side a balance, and the antipodal side a balance;",
  "Soft doctrine as steady help as stable doctrine;",
  "Thoughts and deeds of the present, our rouse and early start.",
  "",
  "This minute that comes to me over the past decillions,",
  "There is no better than it and now.",
  "",
  "What behaved well in the past, or behaves well to-day, is not such a wonder;",
  "The wonder is, always and always, how there can be a mean man or an infidel.",
  "",
  "23",
  "Endless unfolding of words of ages!",
  "And mine a word of the modern—the word En-Masse.",
  "",
  "A word of the faith that never balks;",
  "Here or henceforward, it is all the same to me—I accept Time, absolutely.",
  "",
  "It alone is without flaw—it rounds and completes all;",
  "That mystic, baffling wonder I love, alone completes all.",
  "",
  "I accept reality, and dare not question it;",
  "Materialism first and last imbuing.",
  "",
  "Hurrah for positive science! long live exact demonstration!",
  "Fetch stonecrop, mixt with cedar and branches of lilac;",
  "This is the lexicographer—this the chemist—this made a grammar of the",
  "  old cartouches;",
  "These mariners put the ship through dangerous unknown seas;",
  "This is the geologist—this works with the scalpel—and this is a",
  "  mathematician.",
  "",
  "Gentlemen! to you the first honors always:",
  "Your facts are useful and real—and yet they are not my dwelling;",
  "(I but enter by them to an area of my dwelling.)",
  "",
  "Less the reminders of properties told, my words;",
  "And more the reminders, they, of life untold, and of freedom and extrication,",
  "And make short account of neuters and geldings, and favor men and women fully",
  "  equipt,",
  "And beat the gong of revolt, and stop with fugitives, and them that plot and",
  "  conspire.",
  "",
  "24",
  "Walt Whitman am I, a Kosmos, of mighty Manhattan the son,",
  "Turbulent, fleshy and sensual, eating, drinking and breeding;",
  "No sentimentalist—no stander above men and women, or apart from them;",
  "No more modest than immodest.",
  "",
  "Unscrew the locks from the doors!",
  "Unscrew the doors themselves from their jambs!",
  "",
  "Whoever degrades another degrades me;",
  "And whatever is done or said returns at last to me.",
  "",
  "Through me the afflatus surging and surging—through me the current and",
  "  index.",
  "",
  "I speak the pass-word primeval—I give the sign of democracy;",
  "By God! I will accept nothing which all cannot have their counterpart of on the",
  "  same terms.",
  "",
  "Through me many long dumb voices;",
  "Voices of the interminable generations of slaves;",
  "Voices of prostitutes, and of deform’d persons;",
  "Voices of the diseas’d and despairing, and of thieves and dwarfs;",
  "Voices of cycles of preparation and accretion,",
  "And of the threads that connect the stars—and of wombs, and of the",
  "  father-stuff,",
  "And of the rights of them the others are down upon;",
  "Of the trivial, flat, foolish, despised,",
  "Fog in the air, beetles rolling balls of dung.",
  "",
  "Through me forbidden voices;",
  "Voice of sexes and lusts—voices veil’d, and I remove the veil;",
  "Voices indecent, by me clarified and transfigur’d.",
  "",
  "I do not press my fingers across my mouth;",
  "I keep as delicate around the bowels as around the head and heart;",
  "Copulation is no more rank to me than death is.",
  "",
  "I believe in the flesh and the appetites;",
  "Seeing, hearing, feeling, are miracles, and each part and tag of me is a",
  "  miracle.",
  "",
  "Divine am I inside and out, and I make holy whatever I touch or am touch’d",
  "  from;",
  "The scent of these arm-pits, aroma finer than prayer;",
  "This head more than churches, bibles, and all the creeds.",
  "",
  "If I worship one thing more than another, it shall be the spread of my own body,",
  "  or any part of it.",
  "",
  "Translucent mould of me, it shall be you!",
  "Shaded ledges and rests, it shall be you!",
  "Firm masculine colter, it shall be you.",
  "",
  "Whatever goes to the tilth of me, it shall be you!",
  "You my rich blood! Your milky stream, pale strippings of my life.",
  "",
  "Breast that presses against other breasts, it shall be you!",
  "My brain, it shall be your occult convolutions.",
  "",
  "Root of wash’d sweet flag! timorous pond-snipe! nest of guarded duplicate",
  "  eggs! it shall be you!",
  "Mix’d tussled hay of head, beard, brawn, it shall be you!",
  "Trickling sap of maple! fibre of manly wheat! it shall be you!",
  "",
  "Sun so generous, it shall be you!",
  "Vapors lighting and shading my face, it shall be you!",
  "You sweaty brooks and dews, it shall be you!",
  "Winds whose soft-tickling genitals rub against me, it shall be you!",
  "Broad, muscular fields! branches of live oak! loving lounger in my winding",
  "  paths! it shall be you!",
  "Hands I have taken—face I have kiss’d—mortal I have ever",
  "  touch’d! it shall be you.",
  "",
  "I dote on myself—there is that lot of me, and all so luscious;",
  "Each moment, and whatever happens, thrills me with joy.",
  "",
  "O I am wonderful!",
  "I cannot tell how my ankles bend, nor whence the cause of my faintest wish;",
  "Nor the cause of the friendship I emit, nor the cause of the friendship I take",
  "  again.",
  "",
  "That I walk up my stoop! I pause to consider if it really be;",
  "A morning-glory at my window satisfies me more than the metaphysics of books.",
  "",
  "To behold the day-break!",
  "The little light fades the immense and diaphanous shadows;",
  "The air tastes good to my palate.",
  "",
  "Hefts of the moving world, at innocent gambols, silently rising, freshly",
  "  exuding,",
  "Scooting obliquely high and low.",
  "",
  "Something I cannot see puts upward libidinous prongs;",
  "Seas of bright juice suffuse heaven.",
  "",
  "The earth by the sky staid with—the daily close of their junction;",
  "The heav’d challenge from the east that moment over my head;",
  "The mocking taunt, See then whether you shall be master!",
  "",
  "25",
  "Dazzling and tremendous, how quick the sun-rise would kill me,",
  "If I could not now and always send sun-rise out of me.",
  "",
  "We also ascend, dazzling and tremendous as the sun;",
  "We found our own, O my Soul, in the calm and cool of the daybreak.",
  "",
  "My voice goes after what my eyes cannot reach;",
  "With the twirl of my tongue I encompass worlds, and volumes of worlds.",
  "",
  "Speech is the twin of my vision—it is unequal to measure itself;",
  "It provokes me forever;",
  "It says sarcastically, Walt, you contain enough—why don’t you let",
  "  it out, then?",
  "",
  "Come now, I will not be tantalized—you conceive too much of articulation.",
  "",
  "Do you not know, O speech, how the buds beneath you are folded?",
  "Waiting in gloom, protected by frost;",
  "The dirt receding before my prophetical screams;",
  "I underlying causes, to balance them at last;",
  "My knowledge my live parts—it keeping tally with the meaning of things,",
  "HAPPINESS—which, whoever hears me, let him or her set out in search of this",
  "  day.",
  "",
  "My final merit I refuse you—I refuse putting from me what I really am;",
  "Encompass worlds, but never try to encompass me;",
  "I crowd your sleekest and best by simply looking toward you.",
  "",
  "Writing and talk do not prove me;",
  "I carry the plenum of proof, and everything else, in my face;",
  "With the hush of my lips I wholly confound the skeptic.",
  "",
  "26",
  "I think I will do nothing now but listen,",
  "To accrue what I hear into myself—to let sounds contribute toward me.",
  "",
  "I hear bravuras of birds, bustle of growing wheat, gossip of flames, clack of",
  "  sticks cooking my meals;",
  "I hear the sound I love, the sound of the human voice;",
  "I hear all sounds running together, combined, fused or following;",
  "",
  "Sounds of the city, and sounds out of the city—sounds of the day and night;",
  "",
  "Talkative young ones to those that like them—the loud laugh of work-people",
  "  at their meals;",
  "The angry base of disjointed friendship—the faint tones of the sick;",
  "The judge with hands tight to the desk, his pallid lips pronouncing a",
  "  death-sentence;",
  "The heave’e’yo of stevedores unlading ships by the wharves—the",
  "  refrain of the anchor-lifters;",
  "The ring of alarm-bells—the cry of fire—the whirr of swift-streaking",
  "  engines and hose-carts, with premonitory tinkles, and color’d lights;",
  "The steam-whistle—the solid roll of the train of approaching cars;",
  "The slow-march play’d at the head of the association, marching two and two,",
  "",
  "(They go to guard some corpse—the flag-tops are draped with black muslin.)",
  "",
  "I hear the violoncello (’tis the young man’s heart’s complaint;)",
  "I hear the key’d cornet—it glides quickly in through my ears;",
  "It shakes mad-sweet pangs through my belly and breast.",
  "",
  "I hear the chorus—it is a grand opera;",
  "Ah, this indeed is music! This suits me.",
  "",
  "A tenor large and fresh as the creation fills me;",
  "The orbic flex of his mouth is pouring and filling me full.",
  "",
  "I hear the train’d soprano—(what work, with hers, is this?)",
  "The orchestra whirls me wider than Uranus flies;",
  "It wrenches such ardors from me, I did not know I possess’d them;",
  "It sails me—I dab with bare feet—they are lick’d by the indolent",
  "  waves;",
  "I am exposed, cut by bitter and angry hail—I lose my breath,",
  "Steep’d amid honey’d morphine, my windpipe throttled in fakes of",
  "  death;",
  "At length let up again to feel the puzzle of puzzles,",
  "And that we call BEING.",
  "",
  "27",
  "To be, in any form—what is that?",
  "(Round and round we go, all of us, and ever come back thither;)",
  "If nothing lay more develop’d, the quahaug in its callous shell were",
  "  enough.",
  "",
  "Mine is no callous shell;",
  "I have instant conductors all over me, whether I pass or stop;",
  "They seize every object and lead it harmlessly through me.",
  "",
  "I merely stir, press, feel with my fingers, and am happy;",
  "To touch my person to some one else’s is about as much as I can stand.",
  "",
  "28",
  "Is this then a touch? quivering me to a new identity,",
  "Flames and ether making a rush for my veins,",
  "Treacherous tip of me reaching and crowding to help them,",
  "My flesh and blood playing out lightning to strike what is hardly different from",
  "  myself;",
  "On all sides prurient provokers stiffening my limbs,",
  "Straining the udder of my heart for its withheld drip,",
  "Behaving licentious toward me, taking no denial,",
  "Depriving me of my best, as for a purpose,",
  "Unbuttoning my clothes, holding me by the bare waist,",
  "Deluding my confusion with the calm of the sunlight and pasture-fields,",
  "Immodestly sliding the fellow-senses away,",
  "They bribed to swap off with touch, and go and graze at the edges of me;",
  "No consideration, no regard for my draining strength or my anger;",
  "Fetching the rest of the herd around to enjoy them a while,",
  "Then all uniting to stand on a headland and worry me.",
  "",
  "The sentries desert every other part of me;",
  "They have left me helpless to a red marauder;",
  "They all come to the headland, to witness and assist against me.",
  "",
  "I am given up by traitors;",
  "I talk wildly—I have lost my wits—I and nobody else am the greatest",
  "  traitor;",
  "I went myself first to the headland—my own hands carried me there.",
  "",
  "You villian touch! what are you doing? My breath is tight in its throat;",
  "Unclench your floodgates! you are too much for me.",
  "",
  "29",
  "Blind, loving, wrestling touch! sheath’d, hooded, sharp-tooth’d touch!",
  "",
  "Did it make you ache so, leaving me?",
  "",
  "Parting, track’d by arriving—perpetual payment of perpetual loan;",
  "Rich, showering rain, and recompense richer afterward.",
  "",
  "Sprouts take and accumulate—stand by the curb prolific and vital:",
  "Landscapes, projected, masculine, full-sized and golden.",
  "",
  "30",
  "All truths wait in all things;",
  "They neither hasten their own delivery, nor resist it;",
  "They do not need the obstetric forceps of the surgeon;",
  "The insignificant is as big to me as any;",
  "(What is less or more than a touch?)",
  "",
  "Logic and sermons never convince;",
  "The damp of the night drives deeper into my soul.",
  "",
  "Only what proves itself to every man and woman is so;",
  "Only what nobody denies is so.",
  "",
  "A minute and a drop of me settle my brain;",
  "I believe the soggy clods shall become lovers and lamps,",
  "And a compend of compends is the meat of a man or woman,",
  "And a summit and flower there is the feeling they have for each other,",
  "And they are to branch boundlessly out of that lesson until it becomes omnific,",
  "And until every one shall delight us, and we them.",
  "",
  "31",
  "I believe a leaf of grass is no less than the journey-work of the stars,",
  "And the pismire is equally perfect, and a grain of sand, and the egg of the",
  "  wren,",
  "And the tree-toad is a chef-d’oeuvre for the highest,",
  "And the running blackberry would adorn the parlors of heaven,",
  "And the narrowest hinge in my hand puts to scorn all machinery,",
  "And the cow crunching with depress’d head surpasses any statue,",
  "And a mouse is miracle enough to stagger sextillions of infidels,",
  "And I could come every afternoon of my life to look at the farmer’s girl",
  "  boiling her iron tea-kettle and baking shortcake.",
  "",
  "I find I incorporate gneiss, coal, long-threaded moss, fruits, grains, esculent",
  "  roots,",
  "And am stucco’d with quadrupeds and birds all over,",
  "And have distanced what is behind me for good reasons,",
  "And call anything close again, when I desire it.",
  "",
  "In vain the speeding or shyness;",
  "In vain the plutonic rocks send their old heat against my approach;",
  "In vain the mastodon retreats beneath its own powder’d bones;",
  "In vain objects stand leagues off, and assume manifold shapes;",
  "In vain the ocean settling in hollows, and the great monsters lying low;",
  "In vain the buzzard houses herself with the sky;",
  "In vain the snake slides through the creepers and logs;",
  "In vain the elk takes to the inner passes of the woods;",
  "In vain the razor-bill’d auk sails far north to Labrador;",
  "I follow quickly, I ascend to the nest in the fissure of the cliff.",
  "",
  "32",
  "I think I could turn and live with animals, they are so placid and",
  "  self-contain’d;",
  "I stand and look at them long and long.",
  "",
  "They do not sweat and whine about their condition;",
  "They do not lie awake in the dark and weep for their sins;",
  "They do not make me sick discussing their duty to God;",
  "Not one is dissatisfied—not one is demented with the mania of owning",
  "  things;",
  "Not one kneels to another, nor to his kind that lived thousands of years ago;",
  "Not one is respectable or industrious over the whole earth.",
  "",
  "So they show their relations to me, and I accept them;",
  "They bring me tokens of myself—they evince them plainly in their",
  "  possession.",
  "",
  "I wonder where they get those tokens:",
  "Did I pass that way huge times ago, and negligently drop them?",
  "Myself moving forward then and now and forever,",
  "Gathering and showing more always and with velocity,",
  "Infinite and omnigenous, and the like of these among them;",
  "Not too exclusive toward the reachers of my remembrancers;",
  "Picking out here one that I love, and now go with him on brotherly terms.",
  "",
  "A gigantic beauty of a stallion, fresh and responsive to my caresses,",
  "Head high in the forehead, wide between the ears,",
  "Limbs glossy and supple, tail dusting the ground,",
  "Eyes full of sparkling wickedness—ears finely cut, flexibly moving.",
  "",
  "His nostrils dilate, as my heels embrace him;",
  "His well-built limbs tremble with pleasure, as we race around and return.",
  "",
  "I but use you a moment, then I resign you, stallion;",
  "Why do I need your paces, when I myself out-gallop them?",
  "Even, as I stand or sit, passing faster than you.",
  "",
  "33",
  "O swift wind! O space and time! now I see it is true, what I guessed at;",
  "What I guess’d when I loaf’d on the grass;",
  "What I guess’d while I lay alone in my bed,",
  "And again as I walk’d the beach under the paling stars of the morning.",
  "",
  "My ties and ballasts leave me—I travel—I sail—my elbows rest in",
  "  the sea-gaps;",
  "I skirt the sierras—my palms cover continents;",
  "I am afoot with my vision.",
  "",
  "By the city’s quadrangular houses—in log huts—camping with",
  "  lumbermen;",
  "Along the ruts of the turnpike—along the dry gulch and rivulet bed;",
  "Weeding my onion-patch, or hoeing rows of carrots and parsnips—crossing",
  "  savannas—trailing in forests;",
  "Prospecting—gold-digging—girdling the trees of a new purchase;",
  "Scorch’d ankle-deep by the hot sand—hauling my boat down the shallow",
  "  river;",
  "Where the panther walks to and fro on a limb overhead—where the buck turns",
  "  furiously at the hunter;",
  "Where the rattlesnake suns his flabby length on a rock—where the otter is",
  "  feeding on fish;",
  "Where the alligator in his tough pimples sleeps by the bayou;",
  "Where the black bear is searching for roots or honey—where the beaver pats",
  "  the mud with his paddle-shaped tail;",
  "Over the growing sugar—over the yellow-flower’d cotton plant—over",
  "  the rice in its low moist field;",
  "Over the sharp-peak’d farm house, with its scallop’d scum and slender",
  "  shoots from the gutters;",
  "Over the western persimmon—over the long-leav’d corn—over the",
  "  delicate blue-flower flax;",
  "Over the white and brown buckwheat, a hummer and buzzer there with the rest;",
  "Over the dusky green of the rye as it ripples and shades in the breeze;",
  "Scaling mountains, pulling myself cautiously up, holding on by low scragged",
  "  limbs;",
  "Walking the path worn in the grass, and beat through the leaves of the brush;",
  "Where the quail is whistling betwixt the woods and the wheat-lot;",
  "Where the bat flies in the Seventh-month eve—where the great gold-bug drops",
  "  through the dark;",
  "Where flails keep time on the barn floor;",
  "Where the brook puts out of the roots of the old tree and flows to the meadow;",
  "Where cattle stand and shake away flies with the tremulous shuddering of their",
  "  hides;",
  "Where the cheese-cloth hangs in the kitchen—where andirons straddle the",
  "  hearth-slab—where cobwebs fall in festoons from the rafters;",
  "Where trip-hammers crash—where the press is whirling its cylinders;",
  "Wherever the human heart beats with terrible throes under its ribs;",
  "Where the pear-shaped balloon is floating aloft, (floating in it myself, and",
  "  looking composedly down;)",
  "Where the life-car is drawn on the slip-noose—where the heat hatches",
  "  pale-green eggs in the dented sand;",
  "Where the she-whale swims with her calf, and never forsakes it;",
  "Where the steam-ship trails hind-ways its long pennant of smoke;",
  "Where the fin of the shark cuts like a black chip out of the water;",
  "Where the half-burn’d brig is riding on unknown currents,",
  "Where shells grow to her slimy deck—where the dead are corrupting below;",
  "Where the dense-starr’d flag is borne at the head of the regiments;",
  "Approaching Manhattan, up by the long-stretching island;",
  "Under Niagara, the cataract falling like a veil over my countenance;",
  "Upon a door-step—upon the horse-block of hard wood outside;",
  "Upon the race-course, or enjoying picnics or jigs, or a good game of base-ball;",
  "At he-festivals, with blackguard jibes, ironical license, bull-dances, drinking,",
  "  laughter;",
  "At the cider-mill, tasting the sweets of the brown mash, sucking the juice",
  "  through a straw;",
  "At apple-peelings, wanting kisses for all the red fruit I find;",
  "At musters, beach-parties, friendly bees, huskings, house-raisings:",
  "Where the mocking-bird sounds his delicious gurgles, cackles, screams, weeps;",
  "Where the hay-rick stands in the barn-yard—where the dry-stalks are",
  "  scattered—where the brood-cow waits in the hovel;",
  "Where the bull advances to do his masculine work—where the stud to the",
  "  mare—where the cock is treading the hen;",
  "Where the heifers browse—where geese nip their food with short jerks;",
  "Where sun-down shadows lengthen over the limitless and lonesome prairie;",
  "Where herds of buffalo make a crawling spread of the square miles far and near;",
  "Where the humming-bird shimmers—where the neck of the long-lived swan is",
  "  curving and winding;",
  "Where the laughing-gull scoots by the shore, where she laughs her near-human",
  "  laugh;",
  "Where bee-hives range on a gray bench in the garden, half hid by the high weeds;",
  "",
  "Where band-neck’d partridges roost in a ring on the ground with their heads",
  "  out;",
  "Where burial coaches enter the arch’d gates of a cemetery;",
  "Where winter wolves bark amid wastes of snow and icicled trees;",
  "Where the yellow-crown’d heron comes to the edge of the marsh at night and",
  "  feeds upon small crabs;",
  "Where the splash of swimmers and divers cools the warm noon;",
  "Where the katy-did works her chromatic reed on the walnut-tree over the well;",
  "Through patches of citrons and cucumbers with silver-wired leaves;",
  "Through the salt-lick or orange glade, or under conical firs;",
  "Through the gymnasium—through the curtain’d saloon—through the",
  "  office or public hall;",
  "Pleas’d with the native, and pleas’d with the",
  "  foreign—pleas’d with the new and old;",
  "Pleas’d with women, the homely as well as the handsome;",
  "Pleas’d with the quakeress as she puts off her bonnet and talks",
  "  melodiously;",
  "Pleas’d with the tune of the choir of the white-wash’d church;",
  "Pleas’d with the earnest words of the sweating Methodist preacher, or any",
  "  preacher—impress’d seriously at the camp-meeting:",
  "Looking in at the shop-windows of Broadway the whole forenoon—flatting the",
  "  flesh of my nose on the thick plate-glass;",
  "Wandering the same afternoon with my face turn’d up to the clouds,",
  "My right and left arms round the sides of two friends, and I in the middle:",
  "Coming home with the silent and dark-cheek’d bush-boy—(behind me he",
  "  rides at the drape of the day;)",
  "Far from the settlements, studying the print of animals’ feet, or the",
  "  moccasin print;",
  "By the cot in the hospital, reaching lemonade to a feverish patient;",
  "Nigh the coffin’d corpse when all is still, examining with a candle:",
  "Voyaging to every port, to dicker and adventure;",
  "Hurrying with the modern crowd, as eager and fickle as any;",
  "Hot toward one I hate, ready in my madness to knife him;",
  "Solitary at midnight in my back yard, my thoughts gone from me a long while;",
  "Walking the old hills of Judea, with the beautiful gentle God by my side;",
  "Speeding through space—speeding through heaven and the stars;",
  "Speeding amid the seven satellites, and the broad ring, and the diameter of",
  "  eighty thousand miles;",
  "Speeding with tail’d meteors—throwing fire-balls like the rest;",
  "Carrying the crescent child that carries its own full mother in its belly;",
  "Storming, enjoying, planning, loving, cautioning,",
  "Backing and filling, appearing and disappearing;",
  "I tread day and night such roads.",
  "",
  "I visit the orchards of spheres, and look at the product:",
  "And look at quintillions ripen’d, and look at quintillions green.",
  "",
  "I fly the flight of the fluid and swallowing soul;",
  "My course runs below the soundings of plummets.",
  "",
  "I help myself to material and immaterial;",
  "No guard can shut me off, nor law prevent me.",
  "",
  "I anchor my ship for a little while only;",
  "My messengers continually cruise away, or bring their returns to me.",
  "",
  "I go hunting polar furs and the seal—leaping chasms with a pike-pointed",
  "  staff—clinging to topples of brittle and blue.",
  "",
  "I ascend to the foretruck;",
  "I take my place late at night in the crow’s-nest;",
  "We sail the arctic sea—it is plenty light enough;",
  "Through the clear atmosphere I stretch around on the wonderful beauty;",
  "The enormous masses of ice pass me, and I pass them—the scenery is plain in",
  "  all directions;",
  "The white-topt mountains show in the distance—I fling out my fancies toward",
  "  them;",
  "(We are approaching some great battle-field in which we are soon to be engaged;",
  "We pass the colossal outposts of the encampment—we pass with still feet and",
  "  caution;",
  "Or we are entering by the suburbs some vast and ruin’d city;",
  "The blocks and fallen architecture more than all the living cities of the",
  "  globe.)",
  "",
  "I am a free companion—I bivouac by invading watchfires.",
  "",
  "I turn the bridegroom out of bed, and stay with the bride myself;",
  "I tighten her all night to my thighs and lips.",
  "",
  "My voice is the wife’s voice, the screech by the rail of the stairs;",
  "They fetch my man’s body up, dripping and drown’d.",
  "",
  "I understand the large hearts of heroes,",
  "The courage of present times and all times;",
  "How the skipper saw the crowded and rudderless wreck of the steam-ship, and",
  "  Death chasing it up and down the storm;",
  "How he knuckled tight, and gave not back one inch, and was faithful of days and",
  "  faithful of nights,",
  "And chalk’d in large letters, on a board, Be of good cheer, we will not",
  "  desert you:",
  "How he follow’d with them, and tack’d with them—and would not",
  "  give it up;",
  "How he saved the drifting company at last:",
  "How the lank loose-gown’d women look’d when boated from the side of",
  "  their prepared graves;",
  "How the silent old-faced infants, and the lifted sick, and the sharp-lipp’d",
  "  unshaved men:",
  "All this I swallow—it tastes good—I like it well—it becomes mine;",
  "I am the man—I suffer’d—I was there.",
  "",
  "The disdain and calmness of olden martyrs;",
  "The mother, condemn’d for a witch, burnt with dry wood, her children gazing",
  "  on;",
  "The hounded slave that flags in the race, leans by the fence, blowing,",
  "  cover’d with sweat;",
  "The twinges that sting like needles his legs and neck—the murderous",
  "  buckshot and the bullets;",
  "All these I feel, or am.",
  "",
  "I am the hounded slave, I wince at the bite of the dogs,",
  "Hell and despair are upon me, crack and again crack the marksmen;",
  "I clutch the rails of the fence, my gore dribs, thinn’d with the ooze of my",
  "  skin;",
  "I fall on the weeds and stones;",
  "The riders spur their unwilling horses, haul close,",
  "Taunt my dizzy ears, and beat me violently over the head with whip-stocks.",
  "",
  "Agonies are one of my changes of garments;",
  "I do not ask the wounded person how he feels—I myself become the wounded",
  "  person;",
  "My hurts turn livid upon me as I lean on a cane and observe.",
  "",
  "I am the mash’d fireman with breast-bone broken;",
  "Tumbling walls buried me in their debris;",
  "Heat and smoke I inspired—I heard the yelling shouts of my comrades;",
  "I heard the distant click of their picks and shovels;",
  "They have clear’d the beams away—they tenderly lift me forth.",
  "",
  "I lie in the night air in my red shirt—the pervading hush is for my sake;",
  "Painless after all I lie, exhausted but not so unhappy;",
  "White and beautiful are the faces around me—the heads are bared of their",
  "  fire-caps;",
  "The kneeling crowd fades with the light of the torches.",
  "",
  "Distant and dead resuscitate;",
  "They show as the dial or move as the hands of me—I am the clock myself.",
  "",
  "I am an old artillerist—I tell of my fort’s bombardment;",
  "I am there again.",
  "",
  "Again the long roll of the drummers;",
  "Again the attacking cannon, mortars;",
  "Again, to my listening ears, the cannon responsive.",
  "",
  "I take part—I see and hear the whole;",
  "The cries, curses, roar—the plaudits for well-aim’d shots;",
  "The ambulanza slowly passing, trailing its red drip;",
  "Workmen searching after damages, making indispensable repairs;",
  "The fall of grenades through the rent roof—the fan-shaped explosion;",
  "The whizz of limbs, heads, stone, wood, iron, high in the air.",
  "",
  "Again gurgles the mouth of my dying general—he furiously waves with his",
  "  hand;",
  "He gasps through the clot, Mind not me—mind—the entrenchments.",
  "",
  "34",
  "Now I tell what I knew in Texas in my early youth;",
  "(I tell not the fall of Alamo,",
  "Not one escaped to tell the fall of Alamo,",
  "The hundred and fifty are dumb yet at Alamo;)",
  "’Tis the tale of the murder in cold blood of four hundred and twelve young",
  "  men.",
  "",
  "Retreating, they had form’d in a hollow square, with their baggage for",
  "  breastworks;",
  "Nine hundred lives out of the surrounding enemy’s, nine times their number,",
  "  was the price they took in advance;",
  "Their colonel was wounded and their ammunition gone;",
  "They treated for an honorable capitulation, receiv’d writing and seal, gave",
  "  up their arms, and march’d back prisoners of war.",
  "",
  "They were the glory of the race of rangers;",
  "Matchless with horse, rifle, song, supper, courtship,",
  "Large, turbulent, generous, handsome, proud, and affectionate,",
  "Bearded, sunburnt, drest in the free costume of hunters,",
  "Not a single one over thirty years of age.",
  "",
  "The second First-day morning they were brought out in squads, and",
  "  massacred—it was beautiful early summer;",
  "The work commenced about five o’clock, and was over by eight.",
  "",
  "None obey’d the command to kneel;",
  "Some made a mad and helpless rush—some stood stark and straight;",
  "A few fell at once, shot in the temple or heart—the living and dead lay",
  "  together;",
  "The maim’d and mangled dug in the dirt—the newcomers saw them there;",
  "Some, half-kill’d, attempted to crawl away;",
  "These were despatch’d with bayonets, or batter’d with the blunts of",
  "  muskets;",
  "A youth not seventeen years old seiz’d his assassin till two more came to",
  "  release him;",
  "The three were all torn, and cover’d with the boy’s blood.",
  "",
  "At eleven o’clock began the burning of the bodies:",
  "That is the tale of the murder of the four hundred and twelve young men.",
  "",
  "35",
  "Would you hear of an old-fashion’d sea-fight?",
  "Would you learn who won by the light of the moon and stars?",
  "List to the story as my grandmother’s father, the sailor, told it to me.",
  "",
  "Our foe was no skulk in his ship, I tell you, (said he;)",
  "His was the surly English pluck—and there is no tougher or truer, and never",
  "  was, and never will be;",
  "Along the lower’d eve he came, horribly raking us.",
  "",
  "We closed with him—the yards entangled—the cannon touch’d;",
  "My captain lash’d fast with his own hands.",
  "",
  "We had receiv’d some eighteen pound shots under the water;",
  "On our lower-gun-deck two large pieces had burst at the first fire, killing all",
  "  around, and blowing up overhead.",
  "",
  "Fighting at sun-down, fighting at dark;",
  "Ten o’clock at night, the full moon well up, our leaks on the gain, and",
  "  five feet of water reported;",
  "The master-at-arms loosing the prisoners confined in the afterhold, to give them",
  "  a chance for themselves.",
  "",
  "The transit to and from the magazine is now stopt by the sentinels,",
  "They see so many strange faces, they do not know whom to trust.",
  "",
  "Our frigate takes fire;",
  "The other asks if we demand quarter?",
  "If our colors are struck, and the fighting is done?",
  "",
  "Now I laugh content, for I hear the voice of my little captain,",
  "We have not struck, he composedly cries, we have just begun our part",
  "  of the fighting.",
  "",
  "Only three guns are in use;",
  "One is directed by the captain himself against the enemy’s mainmast;",
  "Two, well served with grape and canister, silence his musketry and clear his",
  "  decks.",
  "",
  "The tops alone second the fire of this little battery, especially the main-top;",
  "They hold out bravely during the whole of the action.",
  "",
  "Not a moment’s cease;",
  "The leaks gain fast on the pumps—the fire eats toward the powder-magazine.",
  "",
  "One of the pumps has been shot away—it is generally thought we are sinking.",
  "",
  "",
  "Serene stands the little captain;",
  "He is not hurried—his voice is neither high nor low;",
  "His eyes give more light to us than our battle-lanterns.",
  "",
  "Toward twelve at night, there in the beams of the moon, they surrender to us.",
  "",
  "36",
  "Stretch’d and still lies the midnight;",
  "Two great hulls motionless on the breast of the darkness;",
  "Our vessel riddled and slowly sinking—preparations to pass to the one we",
  "  have conquer’d;",
  "The captain on the quarter-deck coldly giving his orders through a countenance",
  "  white as a sheet;",
  "Near by, the corpse of the child that serv’d in the cabin;",
  "The dead face of an old salt with long white hair and carefully curl’d",
  "  whiskers;",
  "The flames, spite of all that can be done, flickering aloft and below;",
  "The husky voices of the two or three officers yet fit for duty;",
  "Formless stacks of bodies, and bodies by themselves—dabs of flesh upon the",
  "  masts and spars,",
  "Cut of cordage, dangle of rigging, slight shock of the soothe of waves,",
  "Black and impassive guns, litter of powder-parcels, strong scent,",
  "Delicate sniffs of sea-breeze, smells of sedgy grass and fields by the shore,",
  "  death-messages given in charge to survivors,",
  "The hiss of the surgeon’s knife, the gnawing teeth of his saw,",
  "Wheeze, cluck, swash of falling blood, short wild scream, and long, dull,",
  "  tapering groan;",
  "These so—these irretrievable.",
  "",
  "37",
  "O Christ! This is mastering me!",
  "In at the conquer’d doors they crowd. I am possess’d.",
  "",
  "I embody all presences outlaw’d or suffering;",
  "See myself in prison shaped like another man,",
  "And feel the dull unintermitted pain.",
  "",
  "For me the keepers of convicts shoulder their carbines and keep watch;",
  "It is I let out",
  ""
]