module.exports = [
  "What the bee is to the floweret,",
  "When he looks for honey-dew,",
  "Through the leaves that close embower it,",
  "That, my love, I'll be to you.",
  "",
  "She. --",
  "",
  "What the bank, with verdure glowing,",
  "Is to waves that wander near,",
  "Whispering kisses, while they're going,",
  "That I'll be to you, my dear.",
  "",
  "She. --",
  "",
  "But they say, the bee's a rover,",
  "Who will fly, when sweets are gone,",
  "And, when once the kiss is over,",
  "Faithless brooks will wander on.",
  "",
  "He. --",
  "",
  "Nay, if flowers will lose their looks",
  "If sunny banks will wear away,",
  "'Tis but right that bees and brooks",
  "Should sip and kiss them, while they may.",
  ""
]