module.exports = [
  "When coldness wraps this suffering clay,",
  "  Ah! whither strays the immortal mind?",
  "It cannot die, it cannot stay,",
  "  But leaves its darkened dust behind.",
  "Then, unembodied, doth it trace",
  "  By steps each planet's heavenly way?",
  "Or fill at once the realms of space,",
  "  A thing of eyes, that all survey?",
  "",
  "Eternal--boundless,--undecayed,",
  "  A thought unseen, but seeing all,",
  "All, all in earth, or skies displayed,",
  "  Shall it survey, shall it recall:",
  "Each fainter trace that Memory holds",
  "  So darkly of departed years,",
  "In one broad glance the Soul beholds,",
  "  And all, that was, at once appears.",
  "",
  "Before Creation peopled earth,",
  "  Its eye shall roll through chaos back;",
  "And where the farthest heaven had birth,",
  "  The Spirit trace its rising track.",
  "And where the future mars or makes,",
  "  Its glance dilate o'er all to be,",
  "While Sun is quenched--or System breaks,",
  "  Fixed in its own Eternity.",
  "",
  "Above or Love--Hope--Hate--or Fear,",
  "  It lives all passionless and pure:",
  "An age shall fleet like earthly year;",
  "  Its years as moments shall endure.",
  "Away--away--without a wing,",
  "  O'er all--through all--its thought shall fly,",
  "A nameless and eternal thing,",
  "  Forgetting what it was to die.",
  ""
]