module.exports = [
  "WHEN first I came here I had hope,",
  "Hope for I knew not what. Fast beat",
  "My heart at sight of the tall slope",
  "Or grass and yews, as if my feet",
  "",
  "Only by scaling its steps of chalk",
  "Would see something no other hill",
  "Ever disclosed. And now I walk",
  "Down it the last time. Never will",
  "",
  "My heart beat so again at sight",
  "Of any hill although as fair",
  "And loftier. For infinite",
  "The change, late unperceived, this year,",
  "",
  "The twelfth, suddenly, shows me plain.",
  "Hope now,--not health, nor cheerfulness,",
  "Since they can come and go again,",
  "As often one brief hour witnesses,--",
  "",
  "Just hope has gone for ever. Perhaps",
  "I may love other hills yet more",
  "Than this: the future and the maps",
  "Hide something I was waiting for.",
  "",
  "One thing I know, that love with chance",
  "And use and time and necessity",
  "Will grow, and louder the heart's dance",
  "At parting than at meeting be.",
  ""
]