module.exports = [
  "         I saw her crop a rose",
  "           Right early in the day,",
  "         And I went to kiss the place",
  "           Where she broke the rose away",
  "         And I saw the patten rings",
  "           Where she oer the stile had gone,",
  "         And I love all other things",
  "           Her bright eyes look upon.",
  "If she looks upon the hedge or up the leafing tree,",
  "The whitethorn or the brown oak are made dearer things to me.",
  "",
  "         I have a pleasant hill",
  "           Which I sit upon for hours,",
  "         Where she cropt some sprigs of thyme",
  "           And other little flowers;",
  "         And she muttered as she did it",
  "           As does beauty in a dream,",
  "         And I loved her when she hid it",
  "           On her breast, so like to cream,",
  "Near the brown mole on her neck that to me a diamond shone",
  "Then my eye was like to fire, and my heart was like to stone.",
  "",
  "         There is a small green place",
  "           Where cowslips early curled,",
  "         Which on Sabbath day I trace,",
  "           The dearest in the world.",
  "         A little oak spreads oer it,",
  "           And throws a shadow round,",
  "         A green sward close before it,",
  "           The greenest ever found:",
  "There is not a woodland nigh nor is there a green grove,",
  "Yet stood the fair maid nigh me and told me all her love.",
  ""
]