module.exports = [
  "Who bides his time, and day by day",
  "Faces defeat full patiently,",
  "And lifts a mirthful roundelay,",
  "However poor his fortunes be,--",
  "He will not fail in any qualm",
  "Of poverty -- the paltry dime",
  "It will grow golden in his palm,",
  "Who bides his time.",
  "",
  "Who bides his time -- he tastes the sweet",
  "Of honey in the saltest tear;",
  "And though he fares with slowest feet,",
  "Joy runs to meet him, drawing near;",
  "The birds are hearalds of his cause;",
  "And, like a never-ending rhyme,",
  "The roadsides bloom in his applause,",
  "Who bides his time.",
  "",
  "Who bides his time, and fevers not",
  "In the hot race that none achieves,",
  "Shall wear cool-wreathen laurel, wrought",
  "With crimson berries in the leaves;",
  "And he shall reign a goodly king,",
  "And sway his hand o'er every clime",
  "With peace writ on his signet-ring,",
  "Who bides his time.",
  ""
]