module.exports = [
  "TO THE RIGHT HONOURABLE GEORGE LORD LANSDOWNE.",
  "",
  "'Non injussa cano: te nostrae, Vare, myricae,",
  "Te nemus omne canet; nee Phoebo gratior ulla est,",
  "Quam sibi quae Vari praescripsit pagina nomen.'",
  "",
  "VIRG.",
  "",
  "Thy forests, Windsor! and thy green retreats,",
  "At once the Monarch's and the Muse's seats,",
  "Invite my lays. Be present, sylvan Maids!",
  "Unlock your springs, and open all your shades.",
  "Granville commands; your aid, O Muses, bring!",
  "What Muse for Granville can refuse to sing?",
  "",
  "The groves of Eden, vanish'd now so long,",
  "Live in description, and look green in song:",
  "These, were my breast inspired with equal flame,",
  "Like them in beauty, should be like in fame.",
  "Here hills and vales, the woodland and the plain,",
  "Here earth and water seem to strive again;",
  "Not chaos-like, together crush'd and bruised,",
  "But, as the world, harmoniously confused;",
  "Where order in variety we see,",
  "And where, though all things differ, all agree.",
  "Here waving groves a chequer'd scene display,",
  "And part admit, and part exclude the day;",
  "As some coy nymph her lover's warm address",
  "Nor quite indulges, nor can quite repress.",
  "There, interspersed in lawns and opening glades,",
  "Thin trees arise that shun each other's shades.",
  "Here in full light the russet plains extend:",
  "There, wrapt in clouds the bluish hills ascend.",
  "Ev'n the wild heath displays her purple dyes,",
  "And 'midst the desert fruitful fields arise,",
  "That crown'd with tufted trees and springing corn,",
  "Like verdant isles the sable waste adorn.",
  "Let India boast her plants, nor envy we",
  "The weeping amber or the balmy tree,",
  "While by our oaks the precious loads are born,",
  "And realms commanded which those trees adorn.",
  "Not proud Olympus yields a nobler sight,",
  "Though gods assembled grace his towering height.",
  "Than what more humble mountains offer here,",
  "Where, in their blessings, all those gods appear.",
  "See Pan with flocks, with fruits Pomona crown'd,",
  "Here blushing Flora paints the enamell'd ground,",
  "Here Ceres' gifts in waving prospect stand,",
  "And nodding tempt the joyful reaper's hand;",
  "Rich industry sits smiling on the plains,",
  "And peace and plenty tell a Stuart reigns.",
  "",
  "Not thus the land appear'd in ages past,",
  "A dreary desert, and a gloomy waste,",
  "To savage beasts and savage laws a prey,",
  "And kings more furious and severe than they;",
  "Who claim'd the skies, dispeopled air and floods,",
  "The lonely lords of empty wilds and woods:",
  "Cities laid waste, they storm'd the dens and caves,",
  "(For wiser brutes were backward to be slaves).",
  "What could be free, when lawless beasts obey'd,",
  "And even the elements a tyrant sway'd?",
  "In vain kind seasons swell'd the teeming grain,",
  "Soft showers distill'd, and suns grew warm in vain;",
  "The swain with tears his frustrate labour yields,",
  "And famish'd dies amidst his ripen'd fields.",
  "What wonder, then, a beast or subject slain",
  "Were equal crimes in a despotic reign?",
  "Both doom'd alike, for sportive tyrants bled,",
  "But while the subject starved, the beast was fed.",
  "Proud Nimrod first the bloody chase began,",
  "A mighty hunter, and his prey was man:",
  "Our haughty Norman boasts that barbarous name,",
  "And makes his trembling slaves the royal game.",
  "The fields are ravish'd from the industrious swains,",
  "From men their cities, and from gods their fanes:",
  "The levell'd towns with weeds lie cover'd o'er;",
  "The hollow winds through naked temples roar;",
  "Round broken columns clasping ivy twined;",
  "O'er heaps of ruin stalk'd the stately hind;",
  "The fox obscene to gaping tombs retires,",
  "And savage howlings fill the sacred choirs.",
  "Awed by his Nobles, by his Commons cursed,",
  "The oppressor ruled tyrannic where he durst,",
  "Stretch'd o'er the poor and Church his iron rod,",
  "And served alike his vassals and his God.",
  "Whom even the Saxon spared, and bloody Dane,",
  "The wanton victims of his sport remain.",
  "But see, the man who spacious regions gave",
  "A waste for beasts, himself denied a grave!",
  "Stretch'd on the lawn, his second hope survey,",
  "At once the chaser, and at once the prey:",
  "Lo Rufus, tugging at the deadly dart,",
  "Bleeds in the forest like a wounded hart.",
  "Succeeding monarchs heard the subjects' cries,",
  "Nor saw displeased the peaceful cottage rise.",
  "Then gathering flocks on unknown mountains fed,",
  "O'er sandy wilds were yellow harvests spread,",
  "The forests wonder'd at the unusual grain,",
  "And secret transport touch'd the conscious swain.",
  "Fair Liberty, Britannia's goddess, rears",
  "Her cheerful head, and leads the golden years.",
  "",
  "Ye vigorous swains! while youth ferments your blood,",
  "And purer spirits swell the sprightly flood,",
  "Now range the hills, the gameful woods beset,",
  "Wind the shrill horn, or spread the waving net.",
  "When milder autumn summer's heat succeeds,",
  "And in the new-shorn field the partridge feeds,",
  "Before his lord the ready spaniel bounds,",
  "Panting with hope, he tries the furrow'd grounds;",
  "But when the tainted gales the game betray,",
  "Couch'd close he lies, and meditates the prey:",
  "Secure they trust the unfaithful field beset,",
  "Till hovering o'er 'em sweeps the swelling net.",
  "Thus (if small things we may with great compare)",
  "When Albion sends her eager sons to war,",
  "Some thoughtless town, with ease and plenty blest,",
  "Near, and more near, the closing lines invest;",
  "Sudden they seize the amazed, defenceless prize,",
  "And high in air Britannia's standard flies.",
  "",
  "See! from the brake the whirring pheasant springs,",
  "And mounts exulting on triumphant wings:",
  "Short is his joy; he feels the fiery wound,",
  "Flutters in blood, and panting beats the ground.",
  "Ah! what avail his glossy, varying dyes,",
  "His purple crest, and scarlet-circled eyes,",
  "The vivid green his shining plumes unfold,",
  "His painted wings, and breast that flames with gold?",
  "",
  "Nor yet, when moist Arcturus clouds the sky,",
  "The woods and fields their pleasing toils deny.",
  "To plains with well-breath'd beagles we repair,",
  "And trace the mazes of the circling hare;",
  "(Beasts, urged by us, their fellow-beasts pursue,",
  "And learn of man each other to undo.)",
  "With slaughtering gun the unwearied fowler roves,",
  "When frosts have whiten'd all the naked groves;",
  "Where doves in flocks the leafless trees o'ershade,",
  "And lonely woodcocks haunt the watery glade.",
  "He lifts the tube, and levels with his eye;",
  "Straight a short thunder breaks the frozen sky;",
  "Oft, as in airy rings they skim the heath,",
  "The clamorous lapwings feel the leaden death:",
  "Oft, as the mounting larks their notes prepare,",
  "They fall, and leave their little lives in air.",
  "",
  "In genial spring, beneath the quivering shade,",
  "Where cooling vapours breathe along the mead,",
  "The patient fisher takes his silent stand,",
  "Intent, his angle trembling in his hand:",
  "With looks unmoved, he hopes the scaly breed,",
  "And eyes the dancing cork, and bending reed.",
  "Our plenteous streams a various race supply,",
  "The bright-eyed perch with fins of Tyrian dye,",
  "The silver eel, in shining volumes roll'd,",
  "The yellow carp, in scales bedropp'd with gold,",
  "Swift trouts, diversified with crimson stains,",
  "And pikes, the tyrants of the watery plains.",
  "",
  "Now Cancer glows with Phoebus' fiery car:",
  "The youth rush eager to the sylvan war,",
  "Swarm o'er the lawns, the forest walks surround,",
  "Rouse the fleet hart, and cheer the opening hound.",
  "The impatient courser pants in every vein,",
  "And pawing, seems to beat the distant plain:",
  "Hills, vales, and floods appear already cross'd,",
  "And ere he starts, a thousand steps are lost.",
  "See the bold youth strain up the threatening steep,",
  "Rush through the thickets, down the valleys sweep,",
  "Hang o'er their coursers' heads with eager speed,",
  "And earth rolls back beneath the flying steed.",
  "Let old Arcadia boast her ample plain,",
  "The immortal huntress, and her virgin-train;",
  "Nor envy, Windsor! since thy shades have seen",
  "As bright a goddess, and as chaste a queen,",
  "Whose care, like hers, protects the sylvan reign,",
  "The earth's fair light, and empress of the main.",
  "",
  "Here too, 'tis sung, of old Diana stray'd,",
  "And Cynthus' top forsook for Windsor shade;",
  "Here was she seen o'er airy wastes to rove,",
  "Seek the clear spring, or haunt the pathless grove;",
  "Here, arm'd with silver bows, in early dawn,",
  "Her buskin'd virgins traced the dewy lawn.",
  "",
  "Above the rest a rural nymph was famed,",
  "Thy offspring, Thames! the fair Lodona named;",
  "(Lodona's fate, in long oblivion cast,",
  "The Muse shall sing, and what she sings shall last).",
  "Scarce could the goddess from her nymph be known,",
  "But by the crescent and the golden zone.",
  "She scorn'd the praise of beauty, and the care;",
  "A belt her waist, a fillet binds her hair;",
  "A painted quiver on her shoulder sounds,",
  "And with her dart the flying deer she wounds.",
  "It chanced, as eager of the chase, the maid",
  "Beyond the forest's verdant limits stray'd,",
  "Pan saw and loved, and, burning with desire,",
  "Pursued her flight, her flight increased his fire.",
  "Not half so swift the trembling doves can fly,",
  "When the fierce eagle cleaves the liquid sky;",
  "Not half so swiftly the fierce eagle moves,",
  "When through the clouds he drives the trembling doves;",
  "As from the god she flew with furious pace,",
  "Or as the god, more furious, urged the chase.",
  "Now fainting, sinking, pale the nymph appears;",
  "Now close behind, his sounding steps she hears;",
  "And now his shadow reach'd her as she run,",
  "His shadow lengthen'd by the setting sun;",
  "And now his shorter breath, with sultry air,",
  "Pants on her neck, and fans her parting hair.",
  "In vain on father Thames she calls for aid,",
  "Nor could Diana help her injured maid.",
  "Faint, breathless, thus she pray'd, nor pray'd in vain:",
  "'Ah, Cynthia! ah--though banish'd from thy train,",
  "Let me, oh! let me, to the shades repair,",
  "My native shades--there weep, and murmur there.'",
  "She said, and melting as in tears she lay,",
  "In a soft, silver stream dissolved away.",
  "The silver stream her virgin coldness keeps,",
  "For ever murmurs, and for ever weeps;",
  "Still bears the name the hapless virgin bore,",
  "And bathes the forest where she ranged before.",
  "In her chaste current oft the goddess laves,",
  "And with celestial tears augments the waves.",
  "Oft in her glass the musing shepherd spies",
  "The headlong mountains and the downward skies,",
  "The watery landscape of the pendent woods,",
  "And absent trees that tremble in the floods;",
  "In the clear azure gleam the flocks are seen,",
  "And floating forests paint the waves with green,",
  "Through the fair scene roll slow the lingering streams,",
  "Then foaming pour along, and rush into the Thames.",
  "",
  "Thou, too, great Father of the British floods!",
  "With joyful pride survey'st our lofty woods;",
  "Where towering oaks their growing honours rear,",
  "And future navies on thy shores appear.",
  "Not Neptune's self from all her streams receives",
  "A wealthier tribute, than to thine he gives.",
  "No seas so rich, so gay no banks appear,",
  "No lake so gentle, and no spring so clear.",
  "Nor Po so swells the fabling poet's lays,",
  "While led along the skies his current strays,",
  "As thine, which visits Windsor's famed abodes,",
  "To grace the mansion of our earthly gods:",
  "Nor all his stars above a lustre show,",
  "Like the bright beauties on thy banks below;",
  "Where Jove, subdued by mortal passion still,",
  "Might change Olympus for a nobler hill.",
  "",
  "Happy the man whom this bright court approves,",
  "His sovereign favours, and his country loves:",
  "Happy next him who to these shades retires,",
  "Whom Nature charms, and whom the Muse inspires:",
  "Whom humbler joys of home-felt quiet please,",
  "Successive study, exercise, and ease.",
  "He gathers health from herbs the forest yields,",
  "And of their fragrant physic spoils the fields:",
  "With chemic art exalts the mineral powers,",
  "And draws the aromatic souls of flowers:",
  "Now marks the course of rolling orbs on high;",
  "O'er figured worlds now travels with his eye;",
  "Of ancient writ unlocks the learnèd store,",
  "Consults the dead, and lives past ages o'er:",
  "Or wandering thoughtful in the silent wood,",
  "Attends the duties of the wise and good,",
  "To observe a mean, be to himself a friend,",
  "To follow nature, and regard his end;",
  "Or looks on Heaven with more than mortal eyes,",
  "Bids his free soul expatiate in the skies,",
  "Amid her kindred stars familiar roam,",
  "Survey the region, and confess her home!",
  "Such was the life great Scipio once admired,",
  "Thus Atticus, and Trumbull thus retired.",
  "",
  "Ye sacred Nine! that all my soul possess,",
  "Whose raptures fire me, and whose visions bless,",
  "Bear me, oh, bear me to sequester'd scenes,",
  "The bowery mazes, and surrounding greens:",
  "To Thames's banks which fragrant breezes fill,",
  "Or where ye Muses sport on Cooper's Hill.",
  "(On Cooper's Hill eternal wreaths shall grow,",
  "While lasts the mountain, or while Thames shall flow.)",
  "I seem through consecrated walks to rove,",
  "I hear soft music die along the grove:",
  "Led by the sound, I roam from shade to shade,",
  "By godlike poets venerable made:",
  "Here his first lays majestic Denham sung;",
  "There the last numbers flow'd from Cowley's tongue. 270",
  "Oh early lost! what tears the river shed,",
  "When the sad pomp along his banks was led!",
  "His drooping swans on every note expire,",
  "And on his willows hung each Muse's lyre.",
  "",
  "Since fate relentless stopp'd their heavenly voice,",
  "No more the forests ring, or groves rejoice;",
  "Who now shall charm the shades, where Cowley strung",
  "His living harp, and lofty Denham sung?",
  "But hark! the groves rejoice, the forest rings!",
  "Are these revived? or is it Granville sings?",
  "'Tis yours, my lord, to bless our soft retreats,",
  "And call the Muses to their ancient seats;",
  "To paint anew the flowery sylvan scenes,",
  "To crown the forest with immortal greens,",
  "Make Windsor hills in lofty numbers rise,",
  "And lift her turrets nearer to the skies;",
  "To sing those honours you deserve to wear,",
  "And add new lustre to her silver star.",
  "",
  "Here noble Surrey felt the sacred rage,",
  "Surrey, the Granville of a former age:",
  "Matchless his pen, victorious was his lance,",
  "Bold in the lists, and graceful in the dance:",
  "In the same shades the Cupids tuned his lyre,",
  "To the same notes, of love and soft desire:",
  "Fair Geraldine, bright object of his vow,",
  "Then fill'd the groves, as heavenly Mira now.",
  "",
  "Oh, wouldst thou sing what heroes Windsor bore,",
  "What kings first breathed upon her winding shore,",
  "Or raise old warriors, whose adored remains",
  "In weeping vaults her hallow'd earth contains!",
  "With Edward's acts adorn the shining page,",
  "Stretch his long triumphs down through every age,",
  "Draw monarchs chain'd, and Cressy's glorious field,",
  "The lilies blazing on the regal shield:",
  "Then, from her roofs when Verrio's colours fall,",
  "And leave inanimate the naked wall,",
  "Still in thy song should vanquish'd France appear,",
  "And bleed for ever under Britain's spear.",
  "",
  "Let softer strains ill-fated Henry mourn,",
  "And palms eternal flourish round his urn.",
  "Here o'er the martyr-king the marble weeps,",
  "And, fast beside him, once-fear'd Edward sleeps.",
  "Whom not the extended Albion could contain,",
  "From old Belerium to the northern main,",
  "The grave unites; where ev'n the great find rest,",
  "And blended lie the oppressor and the oppress'd!",
  "",
  "Make sacred Charles' tomb for ever known,",
  "(Obscure the place, and uninscribed the stone)",
  "Oh fact accursed! what tears has Albion shed,",
  "Heavens, what new wounds! and how her old have bled!",
  "She saw her sons with purple deaths expire,",
  "Her sacred domes involved in rolling fire,",
  "A dreadful series of intestine wars,",
  "Inglorious triumphs and dishonest scars.",
  "At length great Anna said--'Let discord cease!'",
  "She said, the world obey'd, and all was peace!",
  "",
  "In that blest moment, from his oozy bed",
  "Old Father Thames advanced his reverend head;",
  "His tresses dropp'd with dews, and o'er the stream",
  "His shining horns diffused a golden gleam:",
  "Graved on his urn appear'd the moon, that guides",
  "His swelling waters, and alternate tides;",
  "The figured streams in waves of silver roll'd,",
  "And on their banks Augusta rose in gold.",
  "Around his throne the sea-born brothers stood,",
  "Who swell with tributary urns his flood;",
  "First the famed authors of his ancient name,",
  "The winding Isis and the fruitful Thame:",
  "The Kennet swift, for silver eels renown'd;",
  "The Loddon slow, with verdant alders crown'd;",
  "Cole, whose dark streams his flowery islands lave;",
  "And chalky Wey, that rolls a milky wave;",
  "The blue, transparent Vandalis appears;",
  "The gulfy Lee his sedgy tresses rears;",
  "And sullen Mole, that hides his diving flood;",
  "And silent Darent, stain'd with Danish blood.",
  "",
  "High in the midst, upon his urn reclined,",
  "(His sea-green mantle waving with the wind)",
  "The god appear'd: he turn'd his azure eyes",
  "Where Windsor-domes and pompous turrets rise;",
  "Then bow'd and spoke; the winds forget to roar,",
  "And the hush'd waves glide softly to the shore.",
  "",
  "Hail, sacred Peace! hail, long-expected days,",
  "That Thames's glory to the stars shall raise!",
  "Though Tiber's streams immortal Rome behold,",
  "Though foaming Hermus swells with tides of gold,",
  "From heaven itself though sevenfold Nilus flows,",
  "And harvests on a hundred realms bestows;",
  "These now no more shall be the Muse's themes,",
  "Lost in my fame, as in the sea their streams.",
  "Let Volga's banks with iron squadrons shine,",
  "And groves of lances glitter on the Rhine,",
  "Let barbarous Ganges arm a servile train;",
  "Be mine the blessings of a peaceful reign.",
  "No more my sons shall dye with British blood",
  "Red Iber's sands, or Ister's foaming flood:",
  "Safe on my shore each unmolested swain",
  "Shall tend the flocks, or reap the bearded grain;",
  "The shady empire shall retain no trace",
  "Of war or blood, but in the sylvan chase;",
  "The trumpet sleep, while cheerful horns are blown,",
  "And arms employ'd on birds and beasts alone.",
  "Behold! the ascending villas on my side,",
  "Project long shadows o'er the crystal tide,",
  "Behold! Augusta's glittering spires increase,",
  "And temples rise, the beauteous works of Peace.",
  "I see, I see, where two fair cities bend",
  "Their ample bow, a new Whitehall ascend!",
  "There mighty nations shall inquire their doom,",
  "The world's great oracle in times to come;",
  "There kings shall sue, and suppliant states be seen",
  "Once more to bend before a British queen.",
  "",
  "Thy trees, fair Windsor! now shall leave their woods,",
  "And half thy forests rush into the floods,",
  "Bear Britain's thunder, and her cross display,",
  "To the bright regions of the rising day;",
  "Tempt icy seas, where scarce the waters roll,",
  "Where clearer flames glow round the frozen pole;",
  "Or under southern skies exalt their sails,",
  "Led by new stars, and borne by spicy gales!",
  "For me the balm shall bleed, and amber flow,",
  "The coral redden, and the ruby glow,",
  "The pearly shell its lucid globe infold,",
  "And Phoebus warm the ripening ore to gold.",
  "The time shall come when, free as seas or wind,",
  "Unbounded Thames shall flow for all mankind,",
  "Whole nations enter with each swelling tide,",
  "And seas but join the regions they divide;",
  "Earth's distant ends our glory shall behold,",
  "And the new world launch forth to seek the old.",
  "Then ships of uncouth form shall stem the tide,",
  "And feather'd people crowd my wealthy side,",
  "And naked youths and painted chiefs admire",
  "Our speech, our colour, and our strange attire!",
  "O stretch thy reign, fair Peace! from shore to shore,",
  "Till conquest cease, and slavery be no more;",
  "Till the freed Indians in their native groves",
  "Reap their own fruits, and woo their sable loves,",
  "Peru once more a race of kings behold,",
  "And other Mexicos be roof'd with gold.",
  "Exiled by thee from earth to deepest hell,",
  "In brazen bonds, shall barbarous Discord dwell;",
  "Gigantic Pride, pale Terror, gloomy Care,",
  "And mad Ambition shall attend her there:",
  "There purple Vengeance bathed in gore retires,",
  "Her weapons blunted, and extinct her fires:",
  "There hateful Envy her own snakes shall feel,",
  "And Persecution mourn her broken wheel:",
  "There Faction roar, Rebellion bite her chain,",
  "And gasping Furies thirst for blood in vain.",
  "",
  "Here cease thy flight, nor with unhallow'd lays",
  "Touch the fair fame of Albion's golden days:",
  "The thoughts of gods let Granville's verse recite,",
  "And bring the scenes of opening fate to light.",
  "My humble Muse, in unambitious strains,",
  "Paints the green forests and the flowery plains,",
  "Where Peace descending bids her olives spring,",
  "And scatters blessings from her dove-like wing.",
  "Ev'n I more sweetly pass my careless days,",
  "Pleased in the silent shade with empty praise;",
  "Enough for me, that to the listening swains",
  "First in these fields I sung the sylvan strains.",
  ""
]