module.exports = [
  "Within the circuit of this plodding life",
  "There enter moments of an azure hue,",
  "Untarnished fair as is the violet",
  "Or anemone, when the spring strews them",
  "By some meandering rivulet, which make",
  "The best philosophy untrue that aims",
  "But to console man for his grievances",
  "I have remembered when the winter came,",
  "High in my chamber in the frosty nights,",
  "When in the still light of the cheerful moon,",
  "On every twig and rail and jutting spout,",
  "The icy spears were adding to their length",
  "Against the arrows of the coming sun,",
  "How in the shimmering noon of summer past",
  "Some unrecorded beam slanted across",
  "The upland pastures where the Johnswort grew;",
  "Or heard, amid the verdure of my mind,",
  "The bee's long smothered hum, on the blue flag",
  "Loitering amidst the mead; or busy rill,",
  "Which now through all its course stands still and dumb",
  "Its own memorial,—purling at its play",
  "Along the slopes, and through the meadows next,",
  "Until its youthful sound was hushed at last",
  "In the staid current of the lowland stream;",
  "Or seen the furrows shine but late upturned,",
  "And where the fieldfare followed in the rear,",
  "When all the fields around lay bound and hoar",
  "Beneath a thick integument of snow.",
  "So by God's cheap economy made rich",
  "To go upon my winter's task again.",
  ""
]