module.exports = [
  "You cannot rob us of the rights we cherish,",
  "Nor turn our thoughts away",
  "From the bright picture of a \"Woman's Mission\"",
  "Our hearts portray.",
  "",
  "We claim to dwell, in quiet and seclusion,",
  "Beneath the household roof,--",
  "From the great world's harsh strife, and jarring voices,",
  "To stand aloof;--",
  "",
  "Not in a dreamy and inane abstraction",
  "To sleep our life away,",
  "But, gathering up the brightness of home sunshine,",
  "To deck our way.",
  "",
  "As humble plants by country hedgerows growing,",
  "That treasure up the rain,",
  "And yield in odours, ere the day's declining,",
  "The gift again;",
  "",
  "So let us, unobtrusive and unnoticed,",
  "But happy none the less,",
  "Be privileged to fill the air around us",
  "With happiness;",
  "",
  "To live, unknown beyond the cherished circle,",
  "Which we can bless and aid;",
  "To die, and not a heart that does not love us",
  "Know where we're laid.",
  ""
]