module.exports = [
  "Fellow men! why should the lords try to despise",
  "And prohibit women from having the benefit of the parliamentary Franchise?",
  "When they pay the same taxes as you and me,",
  "I consider they ought to have the same liberty.",
  "",
  "And I consider if they are not allowed the same liberty,",
  "From taxation every one of them should be set free;",
  "And if they are not, it is really very unfair,",
  "And an act of injustice I most solemnly declare.",
  "",
  "Women, farmers, have no protection as the law now stands;",
  "And many of them have lost their property and lands,",
  "And have been turned out of their beautiful farms",
  "By the unjust laws of the land and the sheriffs' alarms.",
  "",
  "And in my opinion, such treatment is very cruel;",
  "And fair play, 'tis said, is a precious jewel;",
  "But such treatment causes women to fret and to dote,",
  "Because they are deprived of the parliamentary Franchise vote.",
  "",
  "In my opinion, what a man pays for he certainly should get;",
  "And if he does not, he will certainly fret;",
  "And why wouldn't women do the very same?",
  "Therefore, to demand the parliamentary Franchise they are not to blame.",
  "",
  "Therefore let them gather, and demand the parliamentary Franchise;",
  "And I'm sure no reasonable man will their actions despise,",
  "For trying to obtain the privileges most unjustly withheld from them;",
  "Which Mr. Gladstone will certainly encourage and never condemn.",
  "",
  "And as for the working women, many are driven to the point of starvation,",
  "All through the tendency of the legislation;",
  "Besides, upon members of parliament they have no claim",
  "As a deputation, which is a very great shame.",
  "",
  "Yes, the Home Secretary of the present day,",
  "Against working women's deputations, has always said- nay;",
  "Because they haven't got the parliamentary Franchise-,",
  "That is the reason why he does them despise.",
  "",
  "And that, in my opinion, is really very unjust;",
  "But the time is not far distant, I most earnestly trust,",
  "When women will have a parliamentary vote,",
  "And many of them, I hope, will wear a better petticoat.",
  "",
  "And I hope that God will aid them in this enterprise,",
  "And enable them to obtain the parliamentary Franchise;",
  "And rally together, and make a bold stand,",
  "And demand the parliamentary Franchise throughout Scotland.",
  "",
  "And do not rest day nor night-",
  "Because your demands are only right",
  "In the eyes of reasonable men, and God's eyesight;",
  "And Heaven, I'm sure, will defend the right.",
  "",
  "Therefore go on brave women! and never fear,",
  "Although your case may seem dark and drear,",
  "And put your trust in God, for He is strong;",
  "And ye will gain the parliamentary Franchise before very long.",
  ""
]