module.exports = [
  "Verse, a Breeze 'mid blossoms straying,",
  "Where HOPE clung feeding, like a bee--",
  "Both were mine ! Life went a-maying",
  "With NATURE, HOPE, and POESY,",
  "[Image][Image]When I was young !",
  "",
  "When I was young ?--Ah, woful WHEN !",
  "Ah ! for the Change 'twixt Now and Then !",
  "This breathing House not built with hands,",
  "This body that does me grievous wrong,",
  "O'er жry Cliffs and glittering Sands,",
  "How lightly then it flashed along :--",
  "Like those trim skiffs, unknown of yore,",
  "On winding lakes and rivers wide,",
  "That ask no aid of Sail or Oar,",
  "That fear no spite of Wind or Tide !",
  "Nought cared this Body for wind or weather",
  "When YOUTH and I lived in't together.",
  "",
  "FLOWERS are lovely ; LOVE is flower-like ;",
  "FRIENDSHIP is a sheltering tree ;",
  "O ! the Joys, that came down shower-like,",
  "Of FRIENDSHIP, LOVE, and LIBERTY,",
  "[Image] [Image] [Image] [Image] Ere I was old !",
  "",
  "Ere I was old ? Ah woful ERE,",
  "Which tells me, YOUTH'S no longer here !",
  "O YOUTH ! for years so many and sweet,",
  "'Tis known, that Thou and I were one,",
  "I'll think it but a fond conceit--",
  "It cannot be that Thou art gone !",
  "Thy Vesper-bell hath not yet toll'd :--",
  "And thou wert aye a Masker bold !",
  "What strange Disguise hast now put on,",
  "To make believe, that thou art gone ?",
  "I see these Locks in silvery slips,",
  "This drooping Gait, this altered Size :",
  "But SPRINGTIDE blossoms on thy Lips,",
  "And Tears take sunshine from thine eyes !",
  "Life is but Thought : so think I will",
  "That YOUTH and I are House-mates still.",
  "",
  "Dew-drops are the gems of morning,",
  "But the tears of mournful eve !",
  "Where no hope is, life's a warning",
  "That only serves to make us grieve,",
  "[Image][Image]When we are old :",
  "",
  "That only serves to make us grieve",
  "With oft and tedious taking-leave,",
  "Like some poor nigh-related guest,",
  "That may not rudely be dismist ;",
  "Yet hath outstay'd his welcome while,",
  "And tells the jest without the smile.",
  ""
]