module.exports = [
  "good night",
  "soooooo bilingue",
  "Ugh sush",
  "To com FOME",
  "Feel empty",
  "movies tonight",
  "Oh god",
  "Weekend actually",
  "Ok lol",
  "Stay Tuned",
  "Sooo bored",
  "22nd month",
  "Lol done",
  "Now what",
  "Good night",
  "Sup guys",
  "SAVE LIVES",
  "Nah what",
  "15460 tweets",
  "Dont abuse",
  "Trap queen",
  "But same",
  "good night",
  "got damn",
  "beyond annoyed",
  "Ahhhh Lionel",
  "young pistol starter",
  "im out",
  "God damn",
  "Like chill",
  "Harry styles",
  "dark times",
  "Un AMD",
  "fuck eahhh",
  "JD ILY",
  "tela touch screen",
  "Com guri",
  "to com fome",
  "wanna shower",
  "Happy sunday",
  "Super hungry",
  "wya bubs",
  "Nap time",
  "I do",
  "At the mall",
  "like HUNTY REALLY",
  "Im gay",
  "Chris Travis",
  "BEATS STEADY KNOCKIN",
  "Like never",
  "Help meeee",
  "No way",
  "leaving lakeland",
  "i am sad",
  "My LRT",
  "Lord knows",
  "Happy sunday",
  "Happy happyv",
  "que fome manow",
  "En fin",
  "FUCKING TAMPAAAA",
  "Cmon Hawks",
  "lol fuck",
  "Hey guys",
  "Animal Shelter",
  "Feed goals",
  "Easy peasy",
  "so sad",
  "pork squad",
  "Wow lmao",
  "to com sede",
  "Happy Sunday",
  "Kinky reggue",
  "New life",
  "alright whatever",
  "gtfo Tampa",
  "to com fome",
  "New love",
  "good music",
  "Off work",
  "Good karma",
  "IS GOD GOOD",
  "Go All Away",
  "Please forgive",
  "to com fome",
  "good night",
  "Too soon",
  "Ton tday",
  "To com fome",
  "The Calm",
  "Uckers badders",
  "Chaps please",
  "GOOD NIGHT",
  "Look weird",
  "to com fome",
  "Little darling",
  "always waiting",
  "Tryna settle",
  "Sup guys",
  "The city never sleepd",
  "The wait",
  "This sucks",
  "great strike",
  "Cracking equaliser",
  "YES JACK",
  "Rough mannnn",
  "YESSSS ENGLAND",
  "Oh wow",
  "ITV DOWN",
  "Good night",
  "Jake funny",
  "Nap time",
  "no tak",
  "Good night sayang",
  "plot twist",
  "Wilshere fantastic",
  "Beaut thougg",
  "Top bins",
  "Connor McJesus",
  "Ohio sucks",
  "NOT FUCK",
  "no way",
  "Head games",
  "New king",
  "Stalks friends",
  "GOOD NIGHT",
  "On the head",
  "Oh wow",
  "LOOOL rooney finally",
  "WAYNE ROONEY",
  "Love wazza",
  "3rd time lucky Rooney",
  "Oh ffs",
  "Ezzz Cappo",
  "my eye burn",
  "Wayne Rooney",
  "high hopes",
  "Smh stfu",
  "Make parry",
  "staying positive",
  "Stalk aquele",
  "but then again",
  "Cybernetic Disinthropy",
  "that sucks",
  "Omg cant sleep",
  "Ma psy",
  "Full house",
  "Hi you",
  "Turnup tonight",
  "phil watch sense8",
  "en fin",
  "still hating Mondays",
  "fuck kirby",
  "Happy sunday",
  "Sunny Sunday",
  "you will",
  "fruity pebbles",
  "Lol damn",
  "TIE GAME",
  "Pop that",
  "15664 tweets",
  "Nap time",
  "Or Hst",
  "fucking annoying",
  "home alone",
  "Sehun please",
  "Joe Dirt",
  "Rat Pack",
  "Hey baby",
  "To com fome",
  "Like whyyy",
  "pierre edwards",
  "Luvvvvv Kendrick",
  "Sup guyz",
  "This sucks",
  "Dub Show",
  "15688 tweets",
  "Wow lmao",
  "gtf lmao",
  "No ask",
  "Die hard",
  "She fine",
  "All cats",
  "rough feelin",
  "Sooo bored",
  "night babies",
  "mentally preparing",
  "Ima just laugh",
  "a dm",
  "Happy Sunday",
  "My boy",
  "Piped dreams",
  "Blessed Redeemer",
  "gol Zzzz",
  "At all",
  "o no",
  "Wapp alone",
  "And ksoo",
  "Forever Belieber",
  "calmly waiting",
  "Cago James",
  "Off offf",
  "15807 tweets",
  "Need sleep",
  "bbl then",
  "so hot",
  "Ja lol",
  "Fake world",
  "Pretty annoyed",
  "LA Fit real quick",
  "We dem boyz",
  "KILL STEAM",
  "Forzza barazil",
  "Not even tired",
  "talk dirty",
  "Good night",
  "dont leave",
  "Half there",
  "Bob Weir",
  "Always wanking",
  "neon green",
  "Jeb Bush",
  "good night",
  "Smh hoes crazy",
  "send nudes",
  "Kiwanna annoying",
  "I so hot",
  "Shitty weekend",
  "Riley Finish",
  "NEW GAME",
  "Willian insolent",
  "Heeeey brother",
  "Hey kids",
  "Juicy Wiggle",
  "To com fome",
  "Selow respon",
  "Ok mom",
  "HARD TIMES",
  "Mdrrr really",
  "Rip Jeff",
  ""
]