module.exports = [
  "To you",
  "That looks plenty",
  "Oh hey",
  "On the real",
  "We are only block",
  "In too deep",
  "Long drive",
  "good night",
  "spam music",
  "WEST COAST",
  "Last naaaa",
  "AWWW SHEET",
  "rip arin",
  "Good night",
  "rip arin",
  "Too long",
  "Wide awake",
  "home alone",
  "Off here",
  "wicked awesome",
  "Just kinda",
  "Very happy",
  "Hard times",
  "Hot damn",
  "Poor Renee",
  "RIP Beto",
  "CRIEM JUSTIN",
  "Lush night",
  "nba time",
  "rly want white castle",
  "That seems blocky",
  "Good start",
  "YOU SUCK",
  "bad call there",
  "This shade",
  "Wdf they doing",
  "Kenton doubled",
  "ROY HYPE",
  "Yeah buddy",
  "Slow start",
  "Damn Shump",
  "I am",
  "Just shook",
  "saw this comin",
  "Playing terrible",
  "sf mad",
  "BEAUTIFUL BASKETBALL",
  "Ima king",
  "Thank muffin",
  "To com fome",
  "Soooo sleepy",
  "Lol sigh",
  "Random thought",
  "9irls always",
  "Grey goose",
  "Good times",
  "Too late",
  "Sit down fatty",
  "Evil again",
  "Home alone",
  "Good Night",
  "Wow refs",
  "probably allergies",
  "Oh god",
  "Neck burnt",
  "Lesson learned",
  "que fase",
  "Got eeem",
  "AIR BALL",
  "Gah damn smith",
  "Coto forro",
  "Be the rain",
  "Finish washing",
  "Stain season",
  "This sucks",
  "Oh God",
  "I DO NOT CARE",
  "Mr bbq",
  "Bad call",
  "Bad call",
  "bad call",
  "Love hurts",
  "Bad call",
  "The fuck",
  "My guy hehe",
  "Black falcon",
  "Barnes lmaoooo",
  "LORD JESUS",
  "Barnes trippin",
  "Hit that",
  "How nice",
  "EJ who",
  "DEMON LAZERS",
  "Finally shumpert",
  "Tie game",
  "Ahh tied",
  "Oh wtf",
  "JON SNOW",
  "Skooly sliding",
  "oh god",
  "LOV doom",
  "Butt hurts",
  "This sucks",
  "Wow bron",
  "Lol what",
  "Yea bron",
  "sooooo anxious",
  "Steph mannnn",
  "Yes klay yesss",
  "My God",
  "THAT SMURK",
  "Quel match",
  "RIP Snow",
  "Our ball",
  "Jon Snow",
  "Smh Klay",
  "so bad",
  "Okay andre",
  "Butt naked",
  "LETS GOOOO",
  "Wtf Cavs",
  "god damn",
  "Great finals",
  "OH GOD",
  "sick beats",
  "Or red",
  "Huge plays",
  "GS GOT THIS",
  "Aw man",
  "Steph cookin",
  "new pack",
  "its done",
  "Lmao crazy",
  "MY GOD",
  "God damn",
  "Gat damn",
  "God damn Steph",
  "FUCK DELLY",
  "My god",
  "I am",
  "Who mate",
  "Holy Steph",
  ""
]