module.exports = [
  "Good day",
  "CHAPAME LIONEL",
  "GOOOAL MESSI",
  "Lio x1",
  "Bouta face one",
  "Ruby gem",
  "Bitter sweet",
  "Turnin nigga",
  "thats rude",
  "Suns out",
  "Guns out",
  "feeling pissed",
  "tremendo stalkeo",
  "very sat",
  "Party time",
  "Stay lit",
  "lmfao have fun",
  "DRINK BEER",
  "Little white lies",
  "Thelfie thtick",
  "Fuck off",
  "Ch n",
  "Bible talk",
  "Happy 50th",
  "Necesito makisss",
  "Young thug",
  "Faaaack youuuu",
  "KKKKK QUSE",
  "Same tbh",
  "chunn chun",
  "Fuck off",
  "Whats good",
  "Stupid guppy",
  "Miss you",
  "Sleeping nowwwww",
  "Party time",
  "Good day",
  "Bref off",
  "False hope",
  "still like you",
  "Bet it",
  "RIP PH",
  "Nice nap",
  "Developed insomnia",
  "Good god",
  "Large Eggs",
  "Miss her",
  "morning mimosa",
  "Period pains",
  "POUND CAKE",
  "Staying humble",
  "Wealthy Dreams",
  "Miss Him",
  "Goooal Sharp",
  "Kenny 2016",
  "OOZ FC",
  "enjoy with you",
  " Matter",
  "Why am u",
  "every sigh",
  "every gasp",
  "Need you rn",
  "DEONTAY WILDER",
  "GIRL BYE",
  "youre ugly",
  "cancer sucks",
  "Fuck you",
  "Deep joy",
  "chicken nugget",
  "Thanks Fretz",
  "Crib boo",
  "Cooking dinner",
  "Wats Gud",
  "Necesito netflix",
  "nigga lyin",
  "true tho",
  "pls no",
  "WHERES RAJIV",
  "dead leg",
  "Great goal",
  "Spastic Rooney",
  "rooney mannn",
  "Still shit",
  "ugly ppl",
  "beach any1",
  "Still miss",
  "amazing daniel",
  "Text meh",
  "Say OK",
  "wtf ok",
  "MOVIE TIME",
  "get in",
  "CRACK ROCK",
  "Why me",
  "Get in",
  "Super Jack",
  "England stinks",
  "finally rooney",
  "fucK YES",
  "Finally Rooney",
  "COMEEEEE ONNNNNN",
  "Neend arhi hai",
  "Wealthy Dreams",
  "Cutch baby",
  "tiefus apple",
  "Scary hoes",
  "Super Jack",
  "Learn life",
  "Game day",
  "GOOD DAY",
  "sepi wks",
  "Night life",
  "Anyone wanna swim",
  "Reading before",
  "Sneak Peak",
  "Time fly",
  "gotta zayn",
  "Cereal fiend",
  "black hair",
  "black soul",
  "Finna lift man",
  "jesus wept",
  "Fucking sleepy",
  "LMFAOOO XAVIER",
  "What aea",
  "Gets old",
  "Money Long",
  "Drama time",
  "Run it",
  "Truffle Butter",
  "Since 2015",
  "Lol no",
  "Zion wth",
  "PENAL DICE",
  "Aggy lol",
  "lol RT",
  "Vol8 Ch1",
  "was up",
  "bachemian rhapsody",
  "Sum1 hug me",
  "sen at",
  "LING BOO",
  " GOING",
  " GOING",
  " GONE",
  "Phone with bae",
  "Nobody knows shit",
  "Hashtag raging",
  "Choral music",
  "Genight people",
  "Nippy cubt",
  "VAMOS NJDS",
  "Catching flights",
  "Lets get it",
  "fuck you",
  "Chest hair",
  "That nap",
  "Golden State",
  "Still slay",
  "New pp",
  "fuck man",
  "chugga sucks",
  "Missing people sucks",
  "Game day",
  "Worst ting",
  "G35 or Z",
  "Absolutely shattered",
  "Really nigga",
  "Fuck Dot",
  "repitam comigo",
  "How so",
  "Summer vibes",
  "Anyone wanna hang",
  "missin gordo",
  "Awfully lonely",
  "fuck you go",
  "Broken smile",
  "Karma baby",
  "fuck you",
  ""
]