module.exports = [
  "nighty night",
  "MILK BOY",
  "Beyond bored",
  "Krizzle shawty",
  "Nights young",
  "everybody hahahaha",
  "Skye pls",
  "fuck off",
  "Done lol",
  "weak asl",
  "Because summer",
  "Tagal prof",
  "Iron Sky",
  "Theeeese hooeees",
  "CUBS WIN",
  "thot box",
  "just wtf",
  "Cubs win",
  "Numba four",
  "battlestar galactica",
  "Fuck off",
  "Yeah Mar",
  "callate mariel",
  "Always alone",
  "math atm",
  "Pretty tired",
  "Debbie cakes",
  "Getting Sleepy",
  "Who up",
  "Fuck you",
  "Getting sleepy",
  "LOOOL Boom",
  "Neeeeedddddd sleeeeepppp",
  "LMFAOO CHRIS",
  "Relax mode",
  "Get Up",
  "alien talk",
  "SUNDAY CANDY",
  "GOODBYE SIGNAL",
  "Fuck you",
  "Ashley hella fake",
  "fck it",
  "nighty night",
  "Fuck man",
  "Phone dead asf",
  "Hungry again",
  "phew man",
  "currently freezing",
  "maya why",
  "Hunnid bands",
  "Pound Cake",
  "Faded bruh",
  "Clutch reply",
  "Hungry again",
  "Eyes low",
  "thanks stray",
  "Bailey guess what",
  "Brown dirt",
  "fuck you",
  "Summer lovin",
  "SENA EAT ME",
  "Hungry still",
  "Say Hi",
  "Pound cake",
  "Done lol",
  "Choco baby",
  "BACK OFF",
  "Who up",
  "Flocka Flame",
  "Morning tweeps",
  "Livin life",
  "Nasty kids",
  "then fix us",
  "good msg",
  "Damn son",
  "say it",
  "Hot in",
  "nanda wins",
  "Big up",
  "fuck off",
  "POOLSIDE CHILLIN",
  "when tho",
  "taylor swift jams idc",
  "arriva kylie",
  "hot af",
  "Grabe dami ugh",
  "SWEET DIVA",
  "wrong step",
  "fuck you",
  "Bruh wtf",
  "Weed too",
  "Getting sleepy",
  "Lol at u",
  "Fuck The Bs",
  "Just try",
  "WHITE WOLF",
  "lean wit it",
  "Sqn kk",
  "SAME MOM",
  "Quick food run",
  "Surogat family",
  "Heart cold",
  "Like wtf",
  "Right nice one",
  "party rock",
  "naaah mate",
  "Outside hotttt",
  "do i",
  "Like wtf",
  "greattt dayyyy",
  "Estou bege",
  "Getting coffee again oops",
  "Feeling sleepy",
  "New dp",
  "kinda want too",
  "wh a",
  "New pp",
  "what the",
  "Balls deep",
  "yiee omg",
  "Whats good for td",
  "Teeth hurt",
  "Never ends",
  "Itchy eyes",
  "FIZZ OMG",
  "heart burn",
  "Gurl wtf",
  "Judith beata",
  "Omfgg gaga",
  "Werks slow",
  "Looooong showers",
  "Asthma sucks",
  "Feeling guilty",
  "FEELING SLEEPY",
  "Miss You",
  "JOSH PLS",
  "Wilson sucks",
  "Taken away",
  "Missed calls",
  "Slow day",
  "Lemes eyyy",
  "Shits dead",
  "remember nuerest",
  "Fuck you",
  "Dalee Cris",
  "Jukebox Joints",
  "Looks nice tho",
  "just ask",
  "mont yes",
  "Miss you",
  "lmao hoe",
  "Missin uuuuu",
  "who am I",
  "Always tired",
  "Super bass",
  "Blessed Friday",
  "long day",
  "Fuck you",
  "Like wtf yo",
  "BUSTER POSEY",
  "Cabs for me",
  "dodge ball",
  "Time out",
  "Rally time",
  "Crab ass",
  "Logic goat",
  "Almost there",
  "Is g",
  "Jimmy dean",
  "family drama",
  "Kinda cold",
  "Over due",
  "wrong pope",
  "caria ever",
  "Counting shadows",
  "HELP PLS",
  "pray for me",
  "Solid pick",
  "lonely dayyy",
  "Awful pick",
  "Toxic dude",
  "watch muna",
  "Trade time",
  "Dumb pic",
  "Lol ew",
  "gotta pack",
  "sick asf rn",
  "THOSE BOOS THO",
  "poor cam",
  "Poor guy",
  "Young dirk",
  "Shap atm",
  "Elfrid sucks",
  "Solid pick",
  "Yeah you",
  "Willie Trill",
  "Pretty Girls",
  "Willie Trill",
  "Willie Trill",
  "Willie TRILL",
  "Willie Trill",
  "Chases every star",
  "Chases every star",
  "Sel am",
  "slow net",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Bombs away",
  "Salty NiNi",
  "parquet courts tbhwy",
  "Miss you",
  "Bobby hill",
  "Leeward skulls",
  "Flint town",
  "Feeling lonely sucks",
  "Ahhhh shit",
  "Loco cou",
  "FUCK YES",
  "Great Pick",
  "Chicken vagina",
  "Ooooh yeah",
  "Posting realll sooon",
  "wheres oubre",
  "JAAAAASON YEEEEEES",
  "Chases every star",
  "Chases every star",
  "Fuckin crunk",
  "hayley being Real",
  "noble mien",
  "disagreeable countenance",
  "Bingley before",
  "Darcy mean",
  "and Mr",
  "they had",
  "dear sir",
  "and Mr",
  "and Mr",
  "and go",
  "but Mr",
  "connected together",
  "Family pride",
  "and is",
  "let Mr",
  "and Mr",
  "and Mr",
  "had Mr",
  "and Mr",
  "that you",
  "for Mr",
  "and Mr",
  "They had",
  "long ago",
  "and as",
  "Very odd",
  "and Mr",
  "for Mr",
  "for Mr",
  "but Mr",
  "and Mr",
  "Darcy only",
  "sometimes together",
  "still more",
  "and Mr",
  "And so",
  "But Mr",
  "and Mr",
  "instantly occurred",
  "But no",
  "Darcy then was",
  "for Mr",
  "readily obeyed",
  "and Mr",
  "wretched mistake",
  "where Jane",
  "that Mrs",
  "dear sir",
  "dear sir",
  "When Mrs",
  "considering everything",
  "good man",
  "and Mr",
  "Bennet found",
  "for Mr",
  "Lydia once",
  "This Mrs",
  "But Mr",
  "and Mr",
  "And so",
  "And so",
  "Darcy with him",
  "How Mr",
  "Bingley called again",
  "After this day",
  "Has he",
  "which will",
  "and so",
  "and Mr",
  "And so",
  "get up",
  "Family Grief",
  "Satisfying Curiosity",
  "CHAPTER XXVIII",
  "CHAPTER XXXIII",
  "CHAPTER XXXVII",
  "Mooning Around",
  "Sailing Orders",
  "being gone",
  "away off",
  "after that",
  "looky here",
  "coming along down",
  "And so",
  "next day",
  "mind you",
  "solid cash",
  "Looky here",
  "looky here",
  "dey is",
  "is I",
  "Looky here",
  "every time",
  "lazying around",
  "black with sin",
  "that way",
  "_so_ boy",
  "sick him",
  "they all do",
  "NEXT day",
  "solid blue",
  "mind you",
  "and Mr",
  "and Dr",
  "Will you",
  "and my",
  "William Fourth",
  "CHAPTER XXVIII",
  "What was it",
  "Pray for me",
  "But no",
  "hour out",
  "mind you",
  "did he",
  "that way",
  "was ye",
  "say it",
  "Cuss you",
  "every time",
  "and Mr",
  "_Huck Finn",
  "CHAPTER XXXIII",
  "Looky here",
  "Will you",
  "and on",
  "and on",
  "looky here",
  "Mars Sid",
  "drat him",
  "_Who_ sung out",
  "after that",
  "are we",
  "Mars Sid",
  "Mars Sid",
  "will you",
  "Mars Sid",
  "that way",
  "They all do",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "_dey_ will",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "Mars Tom",
  "_Unknown_ _Friend_",
  "Without _help_",
  "mind you",
  "trying every door",
  "and oh",
  "dear Sir",
  "And oh",
  "Mary Ann",
  "whatever happens",
  "Mary Ann",
  "has he",
  "sleepy voice",
  "rather shyly",
  "And oh",
  "Mind now",
  "she do",
  "Will you",
  "will you",
  "Will you",
  "will you",
  "Will you",
  "will you",
  "Will you",
  "will you",
  "and it",
  "there they are",
  "turning purple",
  "Nobody moved",
  "Alice dear",
  "candle light",
  "FREDERICK DOUGLASS",
  "till you",
  "like you",
  "_Till then",
  "They are",
  "severely whipped",
  "almost naked",
  "even now",
  "and Mr",
  "and Mr",
  "After that",
  "brick wall",
  "They are",
  "and Mr",
  "West and Mr",
  "Poor man",
  "Try it",
  "William Hughes",
  "Covey said",
  "cowardice departed",
  "Weeden owned",
  "Edward Covey",
  "Damn you",
  "gathering strength",
  "Kill him",
  "kill him",
  "Such was",
  "Walter Price",
  "paid for",
  "Yet Mr",
  "carry wood",
  "FREDERICK DOUGLASS",
  "Godfrey Norton",
  "Godfrey Norton",
  "This way",
  "and Mr",
  "and so",
  "Hosmer Angel",
  "Hosmer Angel",
  "Hosmer Angel",
  "Hosmer Angel",
  "and Mr",
  "Hosmer Angel",
  "Hosmer Angel",
  "Hosmer Angel",
  "black hair",
  "Hosmer Angel",
  "Hosmer Angel",
  "and Dr",
  "who is",
  "fluffy ashes",
  "McCauley cleared",
  "pasty face",
  "but as",
  "There were",
  "Wimpole Street",
  "and he",
  "very old",
  "for Dr",
  "Grimesby Roylott",
  "Grimesby Roylott",
  "sat Dr",
  "Grimesby Roylott",
  "hydraulic engineer",
  "Drink this",
  "only one",
  "heavily barred",
  "unhealthy blotches",
  "Jeremiah Hayling",
  "sharp nose",
  "Hanover Square",
  "Hanover Square",
  "what for",
  "and so",
  "with you",
  "eager face",
  "seedy coat",
  "your son",
  "and he",
  "whatever remains",
  "quick face",
  "year out",
  "little birds",
  "This man",
  "for Mr",
  "and so",
  "gilded frame",
  "There were old",
  "and so",
  "lightly tossed",
  "stone dead",
  "They did so",
  "clearly peeved",
  "After that",
  "even now",
  "excellent Margaret",
  "Good God",
  "although unhappy",
  "Captain Walton",
  "Even now",
  "This man",
  "Good God",
  "sleep came",
  "In M",
  "very ill",
  "dearest Victor",
  "like him",
  "Good God",
  "felt not",
  "sweet lady",
  "your son",
  "deathlike solitude",
  "quite bare",
  "still more",
  "Their food",
  "while they",
  "unhappy wretch",
  "like him",
  "Beloved friend",
  "Almost spent",
  "for Mr",
  "dearest Victor",
  "and he",
  "Urged thus far",
  "but is",
  "Such men",
  "greater hatred",
  "attacked Tuscany",
  "After this",
  "amongst others",
  "This man",
  "and he",
  "They had",
  "This man",
  "Scipio Cyrus",
  "and he",
  "carefully observed",
  "rising again",
  "for if",
  "She is",
  "And if",
  "Edward Dacre",
  "vulgar child",
  "Mars Tom",
  "Mars Tom",
  "Stop her",
  "right away",
  "and oh",
  "delivering judgments",
  "Fine boy",
  "some day",
  "eleven steps",
  "will you",
  "will you",
  "Will you",
  "you do",
  "But no",
  "That was it",
  "careful combat",
  "without moving",
  "like Sid",
  "right away",
  "shower baths",
  "distinct whistle",
  "poor boy",
  "generous natures",
  "some day",
  "hang her",
  "you do",
  "Poor boy",
  "and oh",
  "could they",
  "Little hands",
  "What for",
  "knelt down",
  "Never mind",
  "will you",
  "Uncle Jake",
  "That was it",
  "panting gently",
  "What was it",
  "postoffice addresses",
  "that was it",
  "turn out",
  "along with Tom",
  "into Mrs",
  "old Mr",
  "that way",
  "twenty times",
  "would play",
  "Ebenezer Scrooge",
  "Poor boy",
  "looking mildly",
  "not us",
  "Tiny Tim",
  "only one",
  "which bore him up",
  "where iron",
  "were all",
  "little child",
  "EBENEZER SCROOGE",
  "Hallo here",
  "Never mind",
  "Hallo here",
  "And so",
  "spiral horns",
  "asphaltic pavement",
  "they say",
  "horrifying implement",
  "may be",
  "Arter that",
  "Still more",
  "they say",
  "they say",
  "sunny cold",
  "WALTER CANNY",
  "unstirring paralysis",
  "noble ship",
  "That was it",
  "they say",
  "But if",
  "being said",
  "cold air",
  "Sideways leaning",
  "belted about",
  "Marchant service indeed",
  "didst thou",
  "gaunt body",
  "Captain Bildad",
  "Captain Bildad",
  "and he",
  "widowed mother",
  "good man",
  "may be",
  "when Mrs",
  "some one",
  "has he",
  "drawing nearer",
  "long ago",
  "will you",
  "will you",
  "very dim",
  "perry easy",
  "friend Peleg",
  "And he",
  "But if",
  "among them all",
  "Thou who",
  "sable hair",
  "broad form",
  "was it",
  "Sulphur Bottom",
  "BOOK III",
  "BOOK III",
  "BOOK III",
  "And if",
  "Admiral Nelson",
  "sing out",
  "What say ye",
  "time was",
  "Why so",
  "Spanish ladies",
  "thou Pip",
  "What say ye",
  "Jig it",
  "ICELAND SAILOR",
  "MALTESE SAILOR",
  "Rig it",
  "dig it",
  "Split jibs",
  "MALTESE SAILOR",
  "ENGLISH SAILOR",
  "SPANISH SAILOR",
  "SPANISH SAILOR",
  "White skin",
  "BELFAST SAILOR",
  "ENGLISH SAILOR",
  "Sweet work",
  "right work",
  "broken limbs",
  "sadder souls",
  "sadder souls",
  "Can we",
  "crazy Ahab",
  "Sandwich Islands",
  "unchanging vibration",
  "their lord",
  "What say ye",
  "give way",
  "Give way",
  "Give way",
  "For me",
  "barbaric majesty",
  "down all",
  "drenched through",
  "vague form",
  "however inland",
  "sleepy night",
  "Your cup",
  "What say ye",
  "closely netted",
  "Albert Durer",
  "with him",
  "thought Daggoo",
  "they say",
  "better jokes",
  "And lo",
  "Your hat",
  "have you",
  "swings clear",
  "that oil",
  "like man",
  "fanning motion",
  "poor lad",
  "blind wall",
  "while poor",
  "and is",
  "Even now",
  "intrepidly advancing",
  "nameless impulse",
  "hearts alive",
  "really water",
  "Let us",
  "And so",
  "fresh wind",
  "curiously situated",
  "broken teeth",
  "previously mentioned",
  "some one",
  "Cachalot Blanche",
  "Fine day",
  "precious candles",
  "does not",
  "Poor Pip",
  "stringy affair",
  "King Asa",
  "glad sun",
  "Look you",
  "Prick ears",
  "did he",
  "look you",
  "flukes first",
  "Captain Boomer",
  "that you",
  "Still more",
  "sprung spars",
  "LEATHER STRAPS",
  "they say",
  "do I",
  "poor Pip",
  "generally speaking",
  "drowned dreams",
  "landed world",
  "What say ye",
  "pleasant weather",
  "steadily pulling",
  "thou sun",
  "Curse thee",
  "Curse thee",
  "Glancing upwards",
  "and lo",
  "Jerk him",
  "Rig it",
  "they say",
  "But no",
  "Next day",
  "poor lad",
  "your hat",
  "white ribs",
  "immortal infancy",
  "very old",
  "noble soul",
  "previously described",
  "And so",
  "Away now",
  "good bye",
  "even now",
  "Glancing upwards",
  "For me",
  "ACT II",
  "Kinsey Peile",
  "Old Mr",
  "dear boy",
  "Ask Mr",
  "Quite dead",
  "Uncle Jack",
  "Uncle Jack",
  "Uncle Jack",
  "Uncle Jack",
  "Uncle Jack",
  "has he",
  "Uncle Jack",
  "Quite sure",
  "That may be",
  "When did Mr",
  "Lon la",
  "lon la",
  "faded away",
  "will you",
  "will you",
  "will you",
  "Janey Mack",
  "Wonderful entirely",
  "Come out",
  "leaping nimbly",
  "Haines asked",
  "Haines began",
  "Prolonged applause",
  "just now",
  "Ask me",
  "Comyn said",
  "Welloff people",
  "Ask me",
  "ask me",
  "good man",
  "Soft day",
  "Soft day",
  "do I",
  "they say",
  "Why in",
  "Kinch here",
  "walking warily",
  "Must get",
  "Green eyes",
  "Napper Tandy",
  "am I",
  "Take all",
  "keep all",
  "Try it",
  "live dog",
  "from far",
  "soused their bags and",
  "Buss her",
  "will you",
  "blast them",
  "What she",
  "rearing horses",
  "Easy now",
  "That one",
  "Quite safe",
  "Must get it",
  "sentry there",
  "meet him",
  "pleasing himself",
  "General thirst",
  "Slieve Bloom",
  "smiling boldly",
  "They lay",
  "shiny sole",
  "_Those girls",
  "lying back now",
  "they say",
  "like her",
  "will you",
  "will you",
  "Poor man",
  "That day",
  "And Mr",
  "Henry dear",
  "they say",
  "Still life",
  "Seventh heaven",
  "Lovely shame",
  "Never tell you",
  "But we",
  "discreetly buttoning",
  "Visit some day",
  "Doctor Whack",
  "smelling herself",
  "Bantam Lyons said",
  "Gold cup",
  "Damn bad ad",
  "Heavenly weather really",
  "softly laved",
  "pined away",
  "was it",
  "Not he",
  "Burst open",
  "With wax",
  "Developing waterways",
  "Last lap",
  "Wrongfully condemned",
  "How so",
  "Poisoned himself",
  "Poor boy",
  "Blackedged notepaper",
  "Chilly place this",
  "After that",
  "Broken heart",
  "Get up",
  "Last day",
  "Hynes said",
  "ants too",
  "they say",
  "Near you",
  "Three days",
  "Hynes said",
  "Hynes said",
  "Convivial evenings",
  "Never mind",
  "will you",
  "Way in",
  "Nature notes",
  "Hynes said",
  "they say",
  "Hynes said",
  "Third hint",
  "Plain Jane",
  "Losing heart",
  "every time",
  "they say",
  "Cabled right away",
  "smiling palely",
  "False lull",
  "mark you",
  "seeking outlet",
  "Look out",
  "Frantic hearts",
  "tell him",
  "delivery waggons",
  "really sweet face",
  "Raise Cain",
  "Three days",
  "High tea",
  "sweating helmets",
  "Decoy duck",
  "piledup bricks",
  "Initials perhaps",
  "Taree tara",
  "Must eat",
  "spilt beer",
  "Slight spasm",
  "Table talk",
  "Clyde road",
  "Potted meats",
  "have you",
  "Young life",
  "Bantam Lyons said",
  "Since when",
  "Get on",
  "took out",
  "calls them",
  "Their life",
  "Did he",
  "Awfully clever",
  "Veils fall",
  "mister honey",
  "Good day",
  "This way",
  "Argive Helen",
  "Thing done",
  "But do",
  "Your own",
  "repeats itself",
  "shall live",
  "Piper says",
  "Other chap",
  "Where then",
  "Invincible ignorance",
  "Maggy said",
  "Maggy said",
  "Maggy said",
  "Maggy said",
  "will you",
  "lifting fruits",
  "will you",
  "Human eyes",
  "were you",
  "sneezed loudly",
  "Turn Now On",
  "Turn Now On",
  "Had it",
  "exparte motion",
  "Dilly said",
  "Dilly said",
  "Dilly said",
  "Dilly said",
  "Dilly said",
  "Dilly said",
  "Dilly said",
  "First rate",
  "Spontaneous combustion",
  "Palm oil",
  "Well now",
  "that was",
  "Greasy black rope",
  "quite true",
  "_Nebrakada femininum",
  "Dilly said",
  "Dilly said",
  "Save her",
  "mind you",
  "lagging behind",
  "Haines asked",
  "nodding curtly",
  "gravely walked",
  "Full tup",
  "True men",
  "still less",
  "they say",
  "came Pat",
  "Third time",
  "Near now",
  "lifted aloft",
  "For me",
  "drinking quickly",
  "How do",
  "How do",
  "Bald Pat",
  "Four now",
  "stopped abrupt",
  "Tight trou",
  "she is",
  "Bald Pat",
  "emptying spittle",
  "dear one",
  "Get up",
  "Explain better",
  "Musical chairs",
  "Yellow knees",
  "Good man",
  "Rutland square",
  "coral lips",
  "Lionel Simon",
  "told him",
  "Human life",
  "said she",
  "deaf Pat",
  "Bloom said",
  "Five Dig",
  "But do",
  "Postal order",
  "Walk now",
  "might hear",
  "Peasants outside",
  "bald Pat",
  "Mirror there",
  "Blank face",
  "Popped corks",
  "good men",
  "murmured tankard",
  "was it",
  "Sing out",
  "Hope she",
  "does she",
  "Damn her",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "poor man",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "silvery fishes",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "Owen Roe",
  "Gautama Buddha",
  "says Joe",
  "Barnfield crescent",
  "says Joe",
  "says Joe",
  "Drink that",
  "And lo",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Alf",
  "But he",
  "even she",
  "says Joe",
  "says Alf",
  "says Alf",
  "says Joe",
  "With who",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Alf",
  "says Alf",
  "says Joe",
  "will you",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "Joseph Manuo",
  "says Joe",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Alf",
  "William Delany",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Alf",
  "says Joe",
  "says Joe",
  "And lo",
  "says Ned",
  "So J",
  "says Joe",
  "says Ned",
  "says Alf",
  "says Ned",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Ned",
  "says Alf",
  "says Ned",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Alf",
  "says Joe",
  "Perfide Albion",
  "says Joe",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Joe",
  "says Joe",
  "Also now",
  "says Alf",
  "says Joe",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Joe",
  "says Alf",
  "says Joe",
  "says Ned",
  "says Ned",
  "says Joe",
  "says Ned",
  "says Joe",
  "says Ned",
  "Your God",
  "says Joe",
  "says Joe",
  "Tommy said",
  "standard designs",
  "taking snuff",
  "pray for us",
  "pray for us",
  "pray for us",
  "wrung from her",
  "Reserve better",
  "Sister souls",
  "Turns milk",
  "Into her",
  "Cider that was",
  "Mushy like",
  "Will she",
  "Looked round",
  "Saves them",
  "washing corpse",
  "will you",
  "Celery sauce",
  "Let me",
  "Into the",
  "Bailey light",
  "Weeping willow",
  "Pray for us",
  "Never find out",
  "Mine too",
  "_Buenas noches",
  "Why me",
  "they say",
  "not me",
  "Something confused",
  "Very God",
  "_effectu secuto_",
  "look you",
  "folk say",
  "There Leop",
  "they say",
  "After that",
  "sprang their luff",
  "weighed anchor",
  "even you",
  "_ventre biche_",
  "Bridie Kelly",
  "And lo",
  "is W",
  "intensely regarded",
  "Mr M",
  "Mr J",
  "Mr S",
  "Dr A",
  "and on",
  "Theodore Purefoy",
  "Thou art",
  "punch milk",
  "Hurrah there",
  "dear sir",
  "Parson Steve",
  "Declare misery",
  "Ten to",
  "What say",
  "Must you go",
  "honest injun",
  "Play low",
  "Jubilee mutton",
  "Pold veg",
  "Time all",
  "Cut up",
  "jerks past",
  "lurching heavily",
  "Figures wander",
  "hairy arse",
  "standing upright",
  "Better cross here",
  "Special recipe",
  "hussy like you",
  "leap out",
  "heel toe",
  "Killing simply",
  "was it",
  "Soon got",
  "What was he",
  "steps back",
  "Deadly agony",
  "About noon",
  "Crucial moment",
  "Mr V",
  "Hurrah there",
  "hard hat",
  "Hanna dear",
  "Geld him",
  "bend low",
  "stands forth",
  "Church music",
  "Laboursaving apparatuses",
  "chiefly ladies",
  "Hats off",
  "theatre passes",
  "pray for us",
  "Stephen Christ",
  "Got me",
  "Yeats says",
  "Keats says",
  "Lipoti Virag",
  "they say",
  "Hence this",
  "Cometh forth",
  "Dear Ger",
  "that you",
  "was it",
  "stands forth",
  "Let me",
  "Handy Andy",
  "purple gills",
  "ducky dear",
  "turning turtle",
  "damn you",
  "Poldy Kock",
  "Beg up",
  "Manx cat",
  "Hundred pounds",
  "rob it",
  "beautiful immortal",
  "yelling flatly",
  "not me",
  "Dead cod",
  "will you",
  "_brevi manu_",
  "Father Dolan",
  "Harmony Avenue",
  "trots past",
  "poppysmic plopslop",
  "seeking badger earth",
  "Last lap",
  "Soft day",
  "Avant deux",
  "Pisser Burke",
  "Benjamin Dollard",
  "Theodore Purefoy",
  "Wolfe Tone",
  "For me",
  "take him",
  "Cease fire",
  "stand back",
  "Gone off",
  "Gold cup",
  "looms down",
  "stands erect",
  "Try it",
  "they say",
  "which they did",
  "Galeria Becche",
  "Europa point",
  "evidently derelict",
  "that cup",
  "Quite dark",
  "Johnny Lever",
  "Johnny Lever",
  "Mr B",
  "they say",
  "Intellectual stimulation",
  "Mr F",
  "Mr W",
  "Bloom said",
  "keyless couple",
  "Medina Villa",
  "passing slowly",
  "first arts",
  "rendering obsolete popguns",
  "Fire lit",
  "county Clare",
  "spoil five",
  "Rutland square",
  "window blind",
  "minimising victories",
  "Garrison Library",
  "tipup seat",
  "of S",
  "city man",
  "be L",
  "moderately mercenary",
  "inducing inertia",
  "desired desire",
  "quadruple battened",
  "Matthew Dillon",
  "Benjamin Dollard",
  "Joseph Cuffe",
  "intraracial inhibition",
  "criminal assault",
  "by E",
  "by W",
  "Enter NORA",
  "Just now",
  "Do I",
  "You do",
  "quarterly interest",
  "Did he",
  "Say it",
  "There they are",
  "There they are",
  "She is",
  "Good day",
  "Such fun",
  "Here she is",
  "what now",
  "Quite sure",
  "Was he",
  "Did he",
  "Sleep well",
  "helpless darling",
  "That too",
  "That too",
  "innumerable cigarettes",
  "Some day",
  "like Eve",
  "this lad",
  "Some day",
  "have you",
  "love him",
  "and oh",
  "Their eyes met",
  "amongst others",
  "shabbily dressed actors",
  "Sibyl dead",
  "infinite passion",
  "and Mr",
  "some day",
  "What was it",
  "And so",
  "among whom was St",
  "jewelled surcoat",
  "These oval",
  "Mind you",
  "Know you",
  "somewhat harshly",
  "even now",
  "Good God",
  "ask Mr",
  "and Mr",
  "hardly older",
  "From him",
  "Never mind",
  "Since then",
  "very shy",
  "They are",
  "young Herr",
  "must you go",
  "Isten szek",
  "agonised wailing",
  "dear sir",
  "miles away",
  "and he",
  "got up",
  "meagre facts",
  "Now go",
  "square boxes",
  "metallic whisper",
  "sickly odour",
  "dear sir",
  "That was Mr",
  "well off",
  "But oh",
  "would they",
  "Every spar",
  "thin man",
  "bless them",
  "driving clouds",
  "sweet lady",
  "even now",
  "will You",
  "and oh",
  "Then Mrs",
  "very bad",
  "very bad",
  "Why so",
  "Somehow Arthur feels very",
  "Mind you",
  "and Mr",
  "white face",
  "dimly dark",
  "Cannot leave",
  "that Mrs",
  "Now go",
  "dear Sir",
  "drawn back",
  "not so",
  "For me",
  "before night",
  "perfectly rejoiced",
  "which sent",
  "thin man",
  "and he",
  "Poor Mrs",
  "and me",
  "Madam Mina",
  "mobile mouth",
  "sensitive nostrils",
  "Madam Mina",
  "Madam Mina",
  "Madam Mina",
  "Madam Mina",
  "Madam Mina",
  "Will you",
  "but oh",
  "angrily rising again",
  "like you",
  "Quincey Morris",
  "and is",
  "which gave out",
  "dear lad",
  "Read all",
  "Here she is",
  "but Dr",
  "and Mr",
  "These were",
  "that did",
  "and oh",
  "for Dr",
  "Madam Mina",
  "and Mr",
  "and Dr",
  "For me",
  "Quincey Morris",
  "and Dr",
  "Madam Mina",
  "Quincey Morris",
  "but Dr",
  "arched oaken door",
  "crying again",
  "Poor man",
  "There were",
  "and Dr",
  "thin man",
  "help her",
  "help her",
  "thin man",
  "And oh",
  "what end",
  "but oh",
  "would they not",
  "Madam Mina",
  "Madam Mina",
  "And oh",
  "Madam Mina",
  "and is",
  "Well for us",
  "stood back",
  "For me",
  "lay Mr",
  "and Mr",
  "but no",
  "Quincey Morris",
  "And so",
  "for oh",
  "like him",
  "for me",
  "Even now",
  "Even Mrs",
  "dear one",
  "and Mr",
  "And oh",
  "_Rufus Smith",
  "And oh",
  "Here now",
  "fear not",
  "Madam Mina",
  "They had",
  "moving along",
  "and Dr",
  "lying down",
  "and up",
  "Madam Mina",
  "and is",
  "sail you",
  "sweet idea",
  "put in",
  "beauty build",
  "left out",
  "fear not",
  "O       quenchless",
  "ceaseless vehicles",
  "this air",
  "Looks down",
  "ironical license",
  "strong scent",
  "Stand back",
  "touch them",
  "Tickets buying",
  "If I",
  "Potent mates",
  "wandering immortal",
  "Bathing myself",
  "very old",
  "bloody drops",
  "statutes mocking",
  "waves dash",
  "solitary toilers",
  "daily life",
  "Something unproved",
  "gloomy heart",
  "for us",
  "queer race",
  "heaving breast",
  "here joy",
  "Fresh come",
  "these arts",
  "shuts none out",
  "shuts none out",
  "nothing losing",
  "Say on",
  "That see",
  "Western youths",
  "varied world",
  "through defeat",
  "Through angers",
  "Here too",
  "Commerce opening",
  "BOOK XIX",
  "not me",
  "sink low",
  "deny not me",
  "through spaces",
  "Weep not",
  "Weep not",
  "some old",
  "Through Nature",
  "and lo",
  "indoors arming",
  "launch forth",
  "Point this day",
  "deeper green",
  "dearest mother",
  "calmly close",
  "for me",
  "hardly human",
  "returning homeward",
  "Whatever appears",
  "this day",
  "obedient persons",
  "positive knowers",
  "This arm",
  "strong waves",
  "sweet wars",
  "for lo",
  "promises nothing",
  "While upon all",
  "lavish giver",
  "meanings unknown before",
  "lose not",
  "Scotch tunes",
  "Libertad forever",
  "Marco Polo",
  "And lo",
  "interior command",
  "turn him",
  "last out",
  "BOOK XXX",
  "sibilant chorals",
  "still live",
  "equal with any",
  "leaping easily above hell",
  "lines give way",
  "always dying",
  "While thou",
  "bright green",
  "private haunts",
  "tire not",
  "for lo",
  "Unborn deeds",
  "clear eyes",
  "Screaming electric",
  "caged bird",
  "Thou dim",
  "equal sons",
  "Born Feb",
  "from you",
  "Wherever Freedom",
  "Close home",
  "Thine eyes",
  "their ears",
  "open air",
  "feudal tales",
  "Walter Scott",
  "often evil",
  "of G",
  "and he",
  "But he",
  "feed him",
  "Govinda twenty paces away",
  "Thus sat he",
  "almost naked",
  "unsown cloak",
  "This man",
  "even him",
  "shared their life",
  "But he",
  "every word",
  "This too",
  "carrying baskets",
  "pretty shoes",
  "Bowed that man",
  "every look",
  "without thirst",
  "Siddhartha collapsed",
  "But no",
  "After that",
  "wasted money",
  "wasted money",
  "Good for me",
  "every path",
  "every goal",
  "Your son",
  "like you",
  "from sin",
  "now he",
  "soft man",
  "breathed Sansara",
  "After this",
  "being open",
  "every bird",
  "Only him",
  "often dark",
  "beyond which",
  "Desired Spirit",
  "save one",
  "From her",
  "Mine eye",
  "even all",
  "Fail not",
  "each one",
  "Tell him",
  "And lo",
  "But he",
  "living topaz",
  "Each one",
  "such joy",
  "Sweet star",
  "which thou",
  "But lo",
  "Sweet love",
  "spirit blest",
  "Deem now",
  "like one",
  "But he",
  "Isaias saith",
  "but ah",
  "Ancient father",
  "Silence ensued",
  "where thou",
  "Wherever merited",
  "Sarah next",
  "And he",
  "Gratia Plena",
  "for me",
  "above them all",
  "That one",
  "Not so",
  "Like men",
  "There left",
  "Among them one",
  "and he",
  "But lo",
  "For me",
  "There both",
  "Like one",
  "even now",
  "saw me",
  "pray for us",
  "disclose thyself",
  "who is",
  "sloping onward",
  "finds Curs",
  "Not so",
  "Met us",
  "That all",
  "Grant then",
  "this man",
  "enter here",
  "And he",
  "like him",
  "thick hung",
  "That beg",
  "there came",
  "weep not",
  "and lo",
  "Never fire",
  "But lo",
  "which thee",
  "And lo",
  "Before these",
  "Large hail",
  "flays them",
  "Almighty Justice",
  "tarry thou",
  "Speak thou",
  "And lo",
  "happy thou",
  "not he",
  "straight replied",
  "when her",
  "without escort",
  "throughout Distorted",
  "though light",
  "And lo",
  "still dost rue",
  "still make",
  "through amazed",
  "Accursed traitor",
  "This one",
  "and Mr",
  "Another sister",
  "have you",
  "Then Mrs",
  "closed again",
  "dear boy",
  "Get up",
  "but oh",
  "Even now",
  "even now",
  "and Mr",
  "But no",
  "plunging forward",
  "Carry dear",
  "or I",
  "but no",
  "Write then",
  "dear Mrs",
  "but Mr",
  "try me",
  "dear boy",
  "gaining ground",
  "and us",
  "Next day Mr",
  "When Mrs",
  "Before going away",
  "feeling poorly",
  "This had",
  "but Mr",
  "Dear Mrs",
  "has it",
  "while Mary",
  "shove away",
  "really sharp",
  "while Mary",
  "and he",
  "Here was",
  "There will",
  "have you",
  "without vanity",
  "There were",
  "named Dale",
  "Ellen dear",
  "stiff tool",
  "but me",
  "have you",
  "small feet",
  "trembled visibly",
  "that was so",
  "growing bolder",
  "Harry dear",
  "and no",
  "Try on",
  "have you",
  "dear Mrs",
  "inclined forward",
  "Ellen came",
  "try it",
  "having Harry",
  "knelt down",
  "After this",
  "and as",
  "chatty terms",
  "which done",
  "regulated movement",
  "Harry Dale",
  "for Mr",
  "thickly haired",
  "dear sir",
  "hold him in",
  "mostly dried fish",
  "when you",
  "Donegal Square",
  "Hungary BUENOS AYRES",
  "Sweden GIJON",
  "Russia PERTH",
  "James Watt",
  "This law",
  "Dark red",
  "like ice",
  "Cubic Foot",
  "Cubic Inch",
  "Cubic Foot",
  "Cubic Foot",
  "Cubic Foot",
  "Total Heat",
  "ume Cu",
  "C",
  "C",
  "H",
  "S",
  "C",
  "C",
  "H",
  "S",
  "C",
  "C",
  "H",
  "S",
  "C",
  "C",
  "H",
  "S",
  "in B",
  "A",
  "B",
  "C",
  "D",
  "Cubic Feet",
  "O",
  "N",
  "H",
  "Cubic Feet",
  "H",
  "Bed No",
  "Bed No",
  "Bed No",
  "Bed No",
  "Rush Run No",
  "of M",
  "V",
  "H",
  "N",
  "M",
  "o",
  "y",
  "i",
  "S",
  "o",
  "C",
  "C",
  "d",
  "O",
  "t",
  "u",
  "i",
  "S",
  "a",
  "r",
  "x",
  "r",
  "l",
  "s",
  "t",
  "r",
  "o",
  "y",
  "o",
  "p",
  "t",
  "a",
  "b",
  "g",
  "g",
  "g",
  "h",
  "A",
  "u",
  "t",
  "o",
  "e",
  "e",
  "e",
  "e",
  "s",
  "r",
  "e",
  "n",
  "n",
  "n",
  "n",
  "r",
  "h",
  "e",
  "Shaking grates",
  "C",
  "H",
  "N",
  "O",
  "C",
  "H",
  "O",
  "N",
  "Porto Rico",
  "Porto Rico",
  "Porto Rico",
  "outside mixers",
  "_",
  "O",
  "O",
  "H",
  "N",
  "H",
  "N",
  "O",
  "O",
  "H",
  "N",
  "Cubic Foot",
  "R",
  "remaining unburned",
  "through custom",
  "Broadly stated",
  "Briefly stated",
  "Hocking Valley",
  "of N",
  "of N",
  "Hocking Valley",
  "of N",
  "of N",
  "Union Elec",
  "Union Elec",
  "O",
  "Another method",
  "Generally speaking",
  "replaced loosely",
  "Feet per",
  "B",
  "T",
  "h",
  "W",
  "i",
  "c",
  "k",
  "G",
  "n",
  "a",
  "e",
  "u",
  "s",
  "g",
  "s",
  "e",
  "Where used",
  "L",
  "by D",
  "S",
  "use of",
  "lime and",
  "John Cox",
  "glide past",
  "they say",
  "Charlie Marlow",
  "murmured vaguely",
  "rubbishy cottons",
  "very far",
  "That was it",
  "a",
  "never mind",
  "Their talk",
  "from him",
  "grunting phrases",
  "even yet",
  "Never mind",
  "did he",
  "very bad",
  "Only one",
  "where pure",
  "what was it",
  "Save _me",
  "Never mind",
  "I",
  "very low",
  "but Mr",
  "breathless utterance",
  "without clamor",
  "Was it",
  "every word",
  "every sign",
  "Madam Mope",
  "since that day",
  "half imp",
  "Was it",
  "who am I",
  "For me",
  "Next day",
  "till now",
  "pretty child",
  "when Mrs",
  "unsophisticated accommodations",
  "though stout",
  "arranged thereon",
  "Seen now",
  "though grave",
  "like you",
  "and Co",
  "Bates came out",
  "will you",
  "that too",
  "modern style",
  "When Mrs",
  "which room",
  "calm day",
  "when Mrs",
  "with Mrs",
  "Old Mr",
  "And so",
  "young lady",
  "Young lady",
  "Will you",
  "looked round",
  "get up",
  "She is",
  "besides myself",
  "quite well",
  "but Mr",
  "did he",
  "and he",
  "olive face",
  "Every good",
  "Now go",
  "Much too",
  "better still",
  "Mild Mrs",
  "and Mr",
  "Blanche Ingram",
  "Good God",
  "and Mr",
  "keep off",
  "canine noise",
  "Rochester enforced",
  "for me",
  "between whiles",
  "abrupt voice",
  "despotic eyebrow",
  "pining thing",
  "ourselves excepted",
  "filling trunks",
  "emptying drawers",
  "burning papers",
  "Rochester entering",
  "they say",
  "when Mrs",
  "silvered columns",
  "which they did",
  "black door",
  "Mason does",
  "Rochester suddenly",
  "Bertha Mason",
  "beautiful creature",
  "kind Mrs",
  "beginning inwardly",
  "Whitcross regained",
  "Move off",
  "Worn out",
  "Get up",
  "Move off",
  "fetch some",
  "Rivers lived here",
  "Old Mr",
  "humble place",
  "that you",
  "and St",
  "They are",
  "What did St",
  "like him",
  "For me",
  "blindly unjust",
  "What aim",
  "have you",
  "some day",
  "like him",
  "and St",
  "Winter snows",
  "And oh",
  "they say",
  "they say",
  "am I",
  "then say",
  "for me",
  "for me",
  "have you",
  "But no",
  "What day",
  "Even now",
  "steaming towards Buenos Ayres",
  "breathing uneasily",
  "Doran here",
  "never fear",
  "never fear",
  "Dear God",
  "mind you",
  "for go",
  "After that Mrs",
  "railway porter",
  "Captain Sinico",
  "Just God",
  "Never fear",
  "poor Joe",
  "wait now",
  "but Mr",
  "When Mrs",
  "but Mr",
  "But Mr",
  "and Mr",
  "After that Mrs",
  "but Mr",
  "Power said",
  "they say",
  "will you",
  "Cunningham continued",
  "When Mrs",
  "lovely voice",
  "and Mr",
  "even Mrs",
  "was it",
  "paltry world",
  "terse fact",
  "lightsome solitude",
  "Everything ponderous",
  "dangerous thoughts",
  "standing without",
  "without NUANCE",
  "better still",
  "Richard Wagner",
  "something obliging",
  "which live",
  "something floating",
  "Socrates himself",
  "generally speaking",
  "beside which",
  "before which",
  "like her",
  "their hard",
  "rarely loves",
  "put on",
  "And if",
  "Act IV",
  "still less",
  "blown upon",
  "Woe me",
  "by E",
  "like him",
  "unvaried surface",
  "change would come",
  "going back",
  "Even yet",
  "for me",
  "look you",
  "Hush now",
  "good Sir",
  "Yonder woman",
  "good Sir",
  "look you",
  "good Sir",
  "good men",
  "or I",
  "coming forth",
  "mine own",
  "And so",
  "every word",
  "sinful woman",
  "however simple",
  "deeply black eyes",
  "Little Pearl",
  "glossy brown",
  "Little Pearl",
  "Speak thou",
  "not so",
  "sinful woman",
  "that old Mr",
  "though still calm",
  "Yet Mr",
  "good sir",
  "good sir",
  "Dimmesdale shuddered",
  "There were men",
  "naturally belonged",
  "persuasive eloquence",
  "Not so",
  "Had Mr",
  "Little Pearl",
  "good sir",
  "good sir",
  "Little Pearl",
  "thought Hester",
  "slightly stirred",
  "heavy book",
  "another moment",
  "Not so",
  "lawless region",
  "unprovoked malignity",
  "dear sir",
  "dear sir",
  "kind sir",
  "among whom",
  "long ago",
  "busying itself",
  "They say",
  "What was it",
  "Hester stood",
  "Little Pearl",
  "prevailing eloquence",
  "still more",
  "after many",
  "But Mr",
  "will you",
  "grey cat",
  "saucy look",
  "Old Mr",
  "and Mr",
  "They met",
  "Master Edgar",
  "French horns",
  "am I",
  "deluded father",
  "coming there",
  "has he",
  "was Mr",
  "And oh",
  "worse than all",
  "were you",
  "and he",
  "Let Mr",
  "Even you",
  "fall out",
  "They say Mr",
  "not he",
  "were you",
  "like his",
  "suspecting something",
  "wicked rages",
  "and Mr",
  "Ellen Dean",
  "Ellen Dean",
  "Ellen Dean",
  "very ill",
  "have you",
  "with you",
  "She is",
  "never mind",
  "did it",
  "hurry down",
  "Get up",
  "join her",
  "has he",
  "Drink your tea",
  "For me",
  "Poor lad",
  "like you",
  "will you",
  "mind you",
  "am I",
  "have you",
  "whining wretch",
  "considerably crestfallen",
  "now do",
  "have you",
  "and lo",
  "incorporeal sweetheart",
  "rough bank",
  "knelt down",
  "heavy look",
  "darling cousin",
  "will you",
  "Niver heed",
  "Since then",
  "will you",
  "will you",
  "Cathy rose",
  "though dying",
  "Get up",
  "will you",
  "take him in",
  "Dean mad",
  "looking slowly round",
  "have you",
  "little idiot",
  "damn him",
  "and do",
  "since then",
  "Get up",
  "Poor lad",
  "and Mr",
  "have you",
  "poor man",
  "Ellen Dean",
  "and Mr",
  "have you",
  "not Mr",
  "BOOK III",
  "BOOK VII",
  "BOOK XII",
  "BOOK XIV",
  "BOOK XVI",
  "BOOK XIX",
  "BOOK XXI",
  "without reason",
  "amongst others",
  "_Christ Church",
  "and is",
  "polished numbers",
  "and Dr",
  "heavenly goddess",
  "But he",
  "vain man",
  "for me",
  "valiant chiefs",
  "Shall Troy",
  "generous Ithacus",
  "From him",
  "factious monster",
  "Sedition silence",
  "but ah",
  "This day",
  "wretched mortals",
  "Where Myde",
  "Nestor alone",
  "godlike Hector",
  "BOOK III",
  "retires behind",
  "And oh",
  "great Jove",
  "For me",
  "Then say",
  "Not so",
  "This bow",
  "These seen",
  "generous brother",
  "They cry",
  "Haste then",
  "BOOK VII",
  "Great Jove",
  "That day",
  "brave Ajax",
  "give ear",
  "take not",
  "sadly slow",
  "give ear",
  "Join all",
  "This day",
  "But ah",
  "retreat behind their wall",
  "There tied",
  "give ear",
  "This day",
  "Haste then",
  "Myself shall stay",
  "And be",
  "With him",
  "Whatever methods",
  "Watch thus",
  "Let me",
  "Should start",
  "Some god",
  "not so",
  "Atrides stands",
  "this day",
  "Tell him",
  "BOOK XII",
  "wisely brave",
  "Next him",
  "That far",
  "Enormous boaster",
  "BOOK XIV",
  "From him",
  "great Ajax",
  "Canst thou",
  "great Mars",
  "am I",
  "though angry",
  "Even yet",
  "And lo",
  "shields rattle",
  "BOOK XVI",
  "what man",
  "Great Ajax saw",
  "oppose their arms",
  "Great Jove",
  "helmets rattle",
  "For he",
  "brave hero",
  "For lo",
  "For ah",
  "And lo",
  "their legs",
  "their feet",
  "For ah",
  "Let me",
  "That arm",
  "renews their toil",
  "But go",
  "as I",
  "angry Jove",
  "And ye",
  "hoary sire",
  "Phoebus impels",
  "and we",
  "BOOK XXI",
  "With his",
  "Seest thou not me",
  "am I",
  "that now",
  "stay not",
  "What god",
  "elate with joy",
  "let me",
  "falling asleep",
  "Fall two",
  "valiant Greeks",
  "their eyes",
  "Fortune denies",
  "for me",
  "Invades around",
  "For ah",
  "Unhappy prince",
  "Thou too",
  "Till now",
  "sadly dear",
  "dearest friend",
  "like art",
  "BOOK III",
  "crying aloud",
  "Damon says",
  "First duty",
  "First then",
  "which last",
  "they say",
  "which here",
  "would fain",
  "BOOK VII",
  "military tactics",
  "diligent natures",
  "like man",
  "Like man",
  "Friend Homer",
  "military tactics",
  "Thus far",
  "Like him",
  "their wars",
  "sweet hope",
  "For if",
  "Never mind",
  "Consider further",
  "Then now",
  "They may",
  "having doors",
  "But if",
  "Since then",
  "because afraid",
  "There must",
  "Quite true",
  "Quite true",
  "Quite true",
  "Then God",
  "BOOK III",
  "Quite true",
  "They are so",
  "Quite true",
  "Then now",
  "These then",
  "And so",
  "Quite true",
  "How so",
  "Quite true",
  "But we",
  "How so",
  "some God",
  "having found them",
  "How so",
  "Why so",
  "Then now",
  "How so",
  "Why so",
  "And so",
  "Why so",
  "ages ago",
  "But if",
  "And so",
  "Quite true",
  "How so",
  "Fear not",
  "And if",
  "How so",
  "Let us",
  "Quite true",
  "How so",
  "But if",
  "Another person",
  "and if",
  "Quite true",
  "Quite true",
  "simply blind",
  "they may",
  "For he",
  "Quite true",
  "sweet sirs",
  "however slight",
  "BOOK VII",
  "Quite true",
  "How so",
  "and we",
  "And so",
  "And so",
  "Quite true",
  "And so",
  "after that",
  "There will",
  "and so",
  "Quite true",
  "How so",
  "Quite true",
  "How so",
  "And he",
  "Why so",
  "Extremely suitable",
  "What way",
  "And so",
  "Quite true",
  "Thus far",
  "Where then",
  "Mortal souls",
  "pretty woman",
  "and he",
  "When Mrs",
  "When Mrs",
  "sandy path",
  "never mind",
  "But he",
  "boyish laugh",
  "till Mrs",
  "Monsieur Farival",
  "which left him",
  "Give Mrs",
  "And Mr",
  "and Mr",
  "looking pained",
  "tell her so",
  "Sleep well",
  "stupid dream",
  "And Dr",
  "Venez donc",
  "Look her",
  "without number",
  "without excuse",
  "soft fan",
  "chere amie",
  "crying aloud",
  "Eighty poles",
  "looking mildly",
  "about them",
  "and is",
  "colours flying",
  "imperial majesty",
  "But he",
  "Another farmer",
  "This man",
  "because nature",
  "vicious people",
  "PART III",
  "when two",
  "For if",
  "containing vineyards",
  "Thus _N_",
  "extends itself",
  "restiff temper",
  "told him",
  "About noon",
  "every part",
  "without appeal",
  "For if",
  "laden with hay",
  "without vanity",
  "broken nails",
  "Here you",
  "For me",
  "mostly oaths",
  "mind you",
  "mind you",
  "dazed with rum",
  "clear hand",
  "Under that",
  "Hold Mrs",
  "difficult business",
  "stone dead",
  "have you",
  "for Dr",
  "of N",
  "and by E",
  "and so",
  "quite loud",
  "was he",
  "What was it",
  "did he",
  "Show him in",
  "mind you",
  "Israel Hands",
  "she is",
  "that was",
  "says you",
  "like you",
  "Well now",
  "Israel Hands",
  "do I",
  "do I",
  "says you",
  "they did",
  "they was",
  "and Dr",
  "Second point",
  "Lay to",
  "blond face",
  "have you",
  "says you",
  "says you",
  "mate Jim",
  "says you",
  "Carpet bowls",
  "says you",
  "says you",
  "says you",
  "Well now",
  "not he",
  "and he",
  "even for me",
  "Israel Hands",
  "very low",
  "Say on",
  "you do",
  "for me",
  "Well now",
  "knives going",
  "wooded shore",
  "sharply enough",
  "And so",
  "under that",
  "was it",
  "will you",
  "After that",
  "Well now",
  "George Merry",
  "Not me",
  "George Merry",
  "burn you",
  "George Merry",
  "Heaven knows",
  "do I",
  "But no",
  "They ran",
  "of N",
  "and by E",
  "will you",
  "and by E",
  "says you",
  "Great guns",
  "says you",
  "Stand back",
  "After that",
  "That was",
  "and Mr",
  "and Mr",
  "did it",
  "but Mr",
  "dear one",
  "and Mr",
  "sweet kind",
  "but Mr",
  "good dog",
  "save him",
  "listening intently",
  "what bit",
  "They are",
  "And so",
  "Which will win",
  "You or I",
  "let go",
  "mother Wendy",
  "which Tink",
  "There were",
  "What was it",
  "who am I",
  "like Mrs",
  "Next day",
  "Slightly darling",
  "They are",
  "Wake her",
  "Hook saw it",
  "Cecco went",
  "James Hook",
  "James Hook",
  "and Mr",
  "feeling drowsy",
  "Sweet Home",
  "they did",
  "will you",
  "you do",
  "that was it",
  "Heyyy guys",
  "French toast",
  "need oot",
  "Thou fix",
  "little russo",
  ""
]